import type { LessonInput } from '../../schema';

/**
 * Bachelorles voor "Het betekenisvolle woorddeel": werkwoorden met een onscheidbaar voorvoegsel
 * (be-, ver-, ont-, ge-, her-, er-, mis-). Wat ze met de betekenis en de zin doen, welke basis ze
 * nemen, het voltooid deelwoord zonder ge-, en het verschil met scheidbare deeltjes. Het kale
 * rijtje van d3, de ge-regel van d5 en het hoofd van d7 worden hier verdiept, niet herhaald.
 */
export const LES_D21: LessonInput = {
  id: 'd21',
  stage: 'bachelor',
  domain: 'morf',
  also: ['syn', 'fon'],
  title: 'Be-, ver-, ont-: werkwoorden met een voorvoegsel',
  skill: 'Woorden',
  icon: 'be-',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Een vast stukje vooraan',
      panels: [
        {
          text: 'Een voorvoegsel als *be-*, *ver-*, *ont-*, *ge-*, *her-* of *er-* zit vast aan de stam. Het gaat nooit los in de zin, en *be-*, *ver-*, *ont-*, *ge-* en *er-* krijgen nooit de klemtoon: *be-SPRE-ken*, *ver-HUI-zen*. Daarom heten ze *onscheidbaar*. Je ziet het aan elke vorm: *ik bespreek het*, *omdat ik het bespreek*, *ik heb het besproken*. In het voltooid deelwoord komt geen *ge-*. Maar let op de *d* en de *t*: die volgen gewoon de stam.',
          rule: 'Onscheidbaar voorvoegsel: altijd vast, geen klemtoon, geen *ge-* in het voltooid deelwoord.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['hij … (nu)', 'voltooid deelwoord'],
            rows: [
              { label: 'bespreken', cells: [{ fill: 'bespreekt' }, { fill: 'besproken', hint: 'Sterk werkwoord: spreken, gesproken. Met be- valt ge- weg.' }] },
              { label: 'verhuizen', cells: [{ fill: 'verhuist', hint: 'Stam verhuis + t.' }, { fill: 'verhuisd', hint: 'De stam eindigt eigenlijk op z, niet in ’t kofschip: -d.' }] },
              { label: 'ontbranden', cells: [{ fill: 'ontbrandt', hint: 'Stam ontbrand + t: dt.' }, { fill: 'ontbrand', hint: 'De stam eindigt al op d: er komt geen tweede d bij.' }] },
              { label: 'verbreden', cells: [{ fill: 'verbreedt', hint: 'Stam verbreed + t: dt.' }, { fill: 'verbreed', hint: 'De stam eindigt al op d: geen extra d.' }] },
              { label: 'herhalen', cells: [{ fill: 'herhaalt' }, { fill: 'herhaald', hint: 'Geen ge-, en l zit niet in ’t kofschip: -d.' }] },
            ],
            extra: ['gebesproken', 'verhuizd', 'ontbrandd', 'geherhaald'],
            note: 'Vijf werkwoorden, geen enkele ge-. De d of t komt van de stam: verbreedt en ontbrandt in het nu, verbreed en ontbrand als voltooid deelwoord.',
          },
        },
        {
          text: 'Wat doet *be-*? Vergelijk *Hij kijkt naar het schilderij* met *Hij bekijkt het schilderij*. Zonder *be-* heb je een voorzetsel nodig. Met *be-* wordt het schilderij een *lijdend voorwerp*. Zo ook *wonen in* → *bewonen*, *twijfelen aan* → *betwijfelen*, *antwoorden op* → *beantwoorden*. Taalkundigen noemen zo’n voorvoegsel een *applicatief*: het maakt van een voorzetselgroep een lijdend voorwerp. Speel het na met de voorwerpen.',
          rule: '*be-* maakt van een voorzetselgroep een lijdend voorwerp: *kijken naar iets* → *iets bekijken*.',
          cast: {
            q: 'Tik het lijdend voorwerp, kies dan het voorzetsel',
            rounds: [
              {
                text: 'De muis bewoont het kasteel.',
                ask: 'Tik wat er bewoond wordt',
                cast: ['muis', 'kasteel', 'huis', 'kip'],
                answer: ['kasteel'],
                then: { q: 'Zonder be-: de muis woont … het kasteel.', options: ['in', 'aan', 'over'], answer: 'in' },
                note: 'Bij wonen was het kasteel een plaats: in het kasteel. Bij bewonen wordt het een lijdend voorwerp.',
              },
              {
                text: 'De kip bekijkt het ei.',
                ask: 'Tik wat er bekeken wordt',
                cast: ['kip', 'ei', 'pan', 'glas'],
                answer: ['ei'],
                then: { q: 'Zonder be-: de kip kijkt … het ei.', options: ['naar', 'op', 'om'], answer: 'naar' },
                note: 'Kijken naar iets, iets bekijken: het voorzetsel verdwijnt.',
              },
              {
                text: 'De zon beschijnt de bloem.',
                ask: 'Tik wat er beschenen wordt',
                cast: ['zon', 'bloem', 'pot', 'ster'],
                answer: ['bloem'],
                then: { q: 'Zonder be-: de zon schijnt … de bloem.', options: ['op', 'naar', 'over'], answer: 'op' },
                note: 'En het voltooid deelwoord is beschenen, zonder ge-: de bloem wordt door de zon beschenen.',
              },
              {
                text: 'Pim beschrijft de vissersboot.',
                ask: 'Tik wat er beschreven wordt',
                cast: ['pim', 'vissersboot', 'boek', 'visser'],
                answer: ['vissersboot'],
                then: { q: 'Zonder be-: Pim schrijft … de vissersboot.', options: ['over', 'aan', 'in'], answer: 'over' },
                note: 'Schrijven over iets, iets beschrijven. Pim blijft het onderwerp; alleen de boot krijgt een nieuwe rol.',
              },
              {
                text: 'De struisvogel bewaakt het ei.',
                ask: 'Tik wat er bewaakt wordt',
                cast: ['struisvogel', 'ei', 'kip', 'pinguin'],
                answer: ['ei'],
                then: { q: 'Zonder be-: de struisvogel waakt … het ei.', options: ['over', 'naar', 'op'], answer: 'over' },
                note: 'Waken over iets, iets bewaken. Vijf keer hetzelfde patroon: be- slikt het voorzetsel in.',
              },
            ],
            note: 'Vijf zinnen, één patroon: be- maakt van een voorzetselgroep een lijdend voorwerp, en het voorzetsel valt weg.',
          },
          deep: {
            q: 'En be- voor een zelfstandig naamwoord?',
            a: 'Dan betekent het vaak *voorzien van*: *bewapenen* (van wapens voorzien), *bebossen* (van bos voorzien), *bemannen* (van een bemanning voorzien). Het voorvoegsel links maakt er een werkwoord van; welke vragen dat oproept over het hoofd van het woord, zag je bij Wie is de baas in het woord?.',
          },
        },
        {
          text: '*ver-* heeft drie hoofdbetekenissen. Met een bijvoeglijk naamwoord: *anders worden* of *anders maken*. *Verbreden* is breder maken, *verarmen* is arm worden. Met een werkwoord en *zich*: *verkeerd*. Wie zich *verslaapt*, slaapt te lang; wie zich *verspreekt*, zegt iets wat hij niet wilde zeggen. En vaak: *weg*, naar een andere plek. Je *verhuist* naar een ander huis en je *verjaagt* een kat.',
          rule: '*ver-*: anders worden of maken (*verbreden*), verkeerd (*zich verslapen*), weg (*verhuizen*, *verjagen*).',
          lab: {
            label: 'Tik een werkwoord',
            chips: [
              { k: 'verbreden', out: 'breed → breder maken', note: 'Basis: een bijvoeglijk naamwoord. Betekenis: anders maken. De weg wordt verbreed.' },
              { k: 'verarmen', out: 'arm → arm worden', note: 'Ook een nieuwe toestand, maar nu zonder lijdend voorwerp: het land verarmt.' },
              { k: 'zich verslapen', out: 'slapen → te lang slapen', note: 'Verkeerd. Let op zich: ik heb me verslapen.' },
              { k: 'verhuizen', out: 'huis → naar een ander huis', note: 'Weg, naar een andere plek. De basis is een zelfstandig naamwoord.' },
              { k: 'verjagen', out: 'jagen → wegjagen', note: 'Weg: de kat is verjaagd.' },
            ],
          },
        },
        {
          text: '*ont-* heeft ook een paar gezichten. Met een zelfstandig naamwoord haalt het iets *weg*: *ontbossen* (het bos weg), *ontharen*, *ontkalken*. Vaak is het het spiegelbeeld van *be-*: *bewapenen* en *ontwapenen*, *belasten* en *ontlasten*. Met een werkwoord kan het een *begin* aangeven: wie *ontwaakt*, wordt wakker; vuur dat *ontbrandt*, begint te branden. En bij beweging betekent het *weg van*: *ontsnappen*, *ontkomen*, *ontvluchten*.',
          rule: '*ont-*: weghalen (*ontbossen*), een begin (*ontwaken*), weg van (*ontsnappen*).',
          mark: {
            q: 'Tik de werkwoorden waarin ont- iets weghaalt',
            sentence: 'ontbossen ontwaken ontharen ontbranden ontkalken ontsnappen',
            targets: [0, 2, 4],
            note: 'ontbossen, ontharen en ontkalken halen bos, haar en kalk weg. ontwaken en ontbranden zijn een begin, en ontsnappen is weg van iets.',
          },
        },
      ],
    },
    {
      kind: 'morph',
      id: 'bos',
      prompt: 'Bouw werkwoorden met bos',
      intro: 'be- zet er iets bij, ont- haalt het weg. En -ing wil een werkwoord.',
      stem: 'bos',
      slots: [
        { id: 'pre', label: 'Ervoor', side: 'before', parts: ['be', 'ont'] },
        { id: 's1', label: 'Erachter', side: 'after', parts: ['en', 'ing'] },
      ],
      words: [
        { combo: ['', ''], w: 'bos', cls: 'zn', mean: 'Een stuk land vol bomen.' },
        { combo: ['', 'en'], w: 'bossen', cls: 'zn', mean: 'Het meervoud: twee bossen. Geen werkwoord, want bossen kun je niet doen.' },
        { combo: ['be', 'en'], w: 'bebossen', cls: 'ww', mean: 'Van bos voorzien: bomen planten op kale grond.' },
        { combo: ['ont', 'en'], w: 'ontbossen', cls: 'ww', mean: 'Het bos weghalen: het spiegelbeeld van bebossen.' },
        { combo: ['be', 'ing'], w: 'bebossing', cls: 'zn', mean: 'Het bebossen. -ing kan, want bebossen is een werkwoord.' },
        { combo: ['ont', 'ing'], w: 'ontbossing', cls: 'zn', mean: 'Het weghalen van bos, zoals in het Amazonegebied.' },
      ],
      forms: { '': 'bos', en: 'bossen', ing: 'bossing' },
      hints: [
        { part: 'ing', note: 'bossing bestaat niet: -ing wil een werkwoord, en bos is een zelfstandig naamwoord. Zet er eerst be- of ont- voor.' },
        { part: 'be', note: 'Alleen een stam: ik bebos. Het hele werkwoord krijgt -en: bebossen.' },
        { part: 'ont', note: 'Alleen een stam: ik ontbos. Het hele werkwoord krijgt -en: ontbossen.' },
      ],
      goal: 5,
      done: {
        title: 'Erbij en eraf',
        text: 'Hetzelfde bos, twee richtingen: be- zet er bos bij, ont- haalt het weg. En -ing kon pas komen toen er een werkwoord was.',
      },
    },
    {
      kind: 'sort',
      id: 'ver-betekenis',
      prompt: 'Wat doet ver- hier?',
      buckets: ['anders worden of maken', 'verkeerd', 'weg'],
      items: [
        { t: 'verbreden', b: 0 },
        { t: 'verduidelijken', b: 0 },
        { t: 'verroesten', b: 0 },
        { t: 'verarmen', b: 0 },
        { t: 'zich verspreken', b: 1 },
        { t: 'zich verrekenen', b: 1 },
        { t: 'zich verschrijven', b: 1 },
        { t: 'verjagen', b: 2 },
        { t: 'verdrijven', b: 2 },
        { t: 'verhuizen', b: 2 },
      ],
      why: 'verbreden, verduidelijken, verroesten en verarmen: een nieuwe toestand. zich verspreken, verrekenen en verschrijven: iets verkeerd doen, altijd met zich. verjagen, verdrijven en verhuizen: weg, naar een andere plek.',
    },
    {
      kind: 'fix',
      id: 'verbreed',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'De weg wordt volgend jaar verbreedt.',
      wrong: 5,
      answer: 'verbreed',
      why: 'Een voltooid deelwoord: ver- is vast, dus geen ge-, en de stam verbreed eindigt al op d. Er komt geen t achter.',
    },
    {
      kind: 'rewrite',
      id: 'betwijfelen',
      prompt: 'Zeg hetzelfde met een werkwoord met be-, zonder voorzetsel.',
      source: 'Hij twijfelt aan haar verhaal.',
      accept: ['Hij betwijfelt haar verhaal.'],
      why: 'twijfelen aan iets wordt iets betwijfelen: be- maakt van de voorzetselgroep een lijdend voorwerp.',
    },
    {
      kind: 'explain',
      id: 'verdieping',
      title: 'Vast of los, en welke basis',
      panels: [
        {
          text: 'Sommige deeltjes kunnen allebei: *door*, *over*, *onder*, *om*, *voor*, *achter*. Dan beslist de klemtoon. Ligt hij op het deeltje, dan is het werkwoord scheidbaar: *Hij loopt door*, *doorgelopen*. Ligt hij op de stam, dan is het vast, net als *be-*: *Hij doorloopt de opleiding*, *doorlopen*. Je kende al *Het komt vaak voor* tegenover *Dat voorkomt problemen*. Ook *mis-* staat op die grens: *misbruiken* is vast (*misbruikt*), *misgaan* scheidbaar (*Het gaat mis*, *misgegaan*).',
          rule: 'Klemtoon op het deeltje: scheidbaar (*loopt door*, *doorgelopen*). Klemtoon op de stam: vast (*doorloopt*, *doorlopen*).',
          paradigm: {
            q: 'Scheidbaar of vast? Vul de vormen in',
            cols: ['hij … (nu)', 'voltooid deelwoord'],
            rows: [
              {
                label: 'dóórlopen (verder lopen)',
                cells: [{ fill: 'loopt door', hint: 'Klemtoon op door: het deeltje gaat los.' }, { fill: 'doorgelopen', hint: 'Scheidbaar: ge- tussen deeltje en stam.' }],
              },
              {
                label: 'doorlópen (afmaken)',
                cells: [{ fill: 'doorloopt', hint: 'Klemtoon op lopen: alles blijft vast.' }, { fill: 'doorlopen', hint: 'Vast, dus geen ge-.' }],
              },
              { label: 'óndergaan (zakken)', cells: [{ fill: 'gaat onder' }, { fill: 'ondergegaan' }] },
              { label: 'ondergáán (meemaken)', cells: [{ fill: 'ondergaat' }, { fill: 'ondergaan', hint: 'Vast: geen ge-. Hij heeft een operatie ondergaan.' }] },
              { label: 'overwégen (nadenken over)', cells: [{ fill: 'overweegt' }, { fill: 'overwogen', hint: 'Vast, en sterk: wegen, gewogen, dus overwogen.' }] },
            ],
            extra: ['gedoorlopen', 'geondergaan', 'overgewogen'],
            note: 'Klemtoon op het deeltje: los in de zin en ge- ertussen. Klemtoon op de stam: één vast blok zonder ge-, net als bij be-, ver- en ont-.',
          },
        },
        {
          text: 'Welke basis nemen ze? Alle drie zijn ze ruimhartig. *be-* neemt een werkwoord (*bespreken*), een zelfstandig naamwoord (*bewapenen*) of een bijvoeglijk naamwoord (*bevrijden*, van *vrij*). *ver-* ook: *verkopen*, *verfilmen*, *verbreden*. En *ont-*: *ontdooien*, *ontbossen*, *ontnuchteren* (van *nuchter*). Wat eruit komt is altijd een werkwoord. Daarom zien sommige taalkundigen het voorvoegsel hier als het hoofd, links in het woord.',
          rule: '*be-*, *ver-* en *ont-* nemen een werkwoord, een zelfstandig naamwoord of een bijvoeglijk naamwoord, en maken er altijd een werkwoord van.',
          mark: {
            q: 'Tik de werkwoorden met een bijvoeglijk naamwoord als basis',
            sentence: 'verbreden bewapenen verarmen ontbossen bevrijden verfilmen ontnuchteren bespreken',
            targets: [0, 2, 4, 6],
            note: 'breed, arm, vrij en nuchter zijn bijvoeglijke naamwoorden. wapen, bos en film zijn zelfstandige naamwoorden, en spreken is een werkwoord.',
          },
        },
        {
          text: 'Welke voorvoegsels leven nog? Kijk naar nieuwe woorden. *ver-* maakt volop werkwoorden van bijvoeglijke naamwoorden: *verduurzamen*, *vergroenen*. *ont-* is populair voor iets wegnemen: *onthaasten* (de haast eruit), *ontzorgen*, *ontvrienden*. *her-* (opnieuw) maakt ook nog nieuwe woorden: *herstarten*, *herbestemmen*. Maar *ge-* en *er-* zijn dood. *Gebruiken*, *geloven*, *erkennen* en *ervaren* zijn oude woorden, en er komen geen nieuwe bij.',
          rule: 'Levend: *ver-*, *ont-*, *her-*. Dood: *ge-* en *er-*.',
          lab: {
            label: 'Tik een voorvoegsel',
            chips: [
              { k: 'ver-', out: 'verduurzamen, vergroenen', note: 'Levend: een bijvoeglijk naamwoord wordt een werkwoord van verandering.' },
              { k: 'ont-', out: 'onthaasten, ontzorgen', note: 'Levend: iets wegnemen, vaak een last of een gevoel.' },
              { k: 'her-', out: 'herstarten, herbestemmen', note: 'Levend: opnieuw.' },
              { k: 'ge-', out: 'gebruiken, geloven, gebeuren', note: 'Dood: geen nieuwe werkwoorden meer. En wat betekent ge- hier eigenlijk nog?' },
              { k: 'er-', out: 'erkennen, ervaren', note: 'Dood: een handvol oude woorden.' },
            ],
          },
          deep: {
            q: 'En be-?',
            a: 'Minder levendig dan *ver-* en *ont-*, maar niet dood. Met een zelfstandig naamwoord ontstaan nog woorden als *bemensen* (van mensen voorzien: *de balie bemensen*) en *beprijzen* (een prijs zetten op). Hoe je productiviteit precies meet, zie je in de master (Productiviteit meten).',
          },
        },
        {
          text: 'Waarom bestaat *onbewoonbaar* wel en *woonbaar* niet? Uit Elk achtervoegsel stelt eisen weet je: *-baar* wil een overgankelijk werkwoord. *Wonen* is dat niet: je woont *in* een huis. Maar *be-* maakt er een lijdend voorwerp bij: je *bewoont* een huis. Pas dan kan *-baar* erachter. Het voorvoegsel levert dus precies wat het achtervoegsel eist. Bouw de boom.',
          rule: '*be-* kan de eis van *-baar* vervullen: *wonen* → *bewonen* → *bewoonbaar*.',
          bracket: {
            q: 'Bouw onbewoonbaar van binnen naar buiten',
            tree: '[on [[be woon] baar]]',
            nodes: [
              { w: 'bewoon', cat: 'ww', note: 'be- + wonen: nu met een lijdend voorwerp. Je bewoont een huis.' },
              { w: 'bewoonbaar', cat: 'bn', note: '-baar kan nu wel: wat bewoond kan worden.' },
              { w: 'onbewoonbaar', cat: 'bn', note: 'on- plakt aan het bijvoeglijk naamwoord en draait het om.' },
            ],
            traps: [
              { w: 'woonbaar', note: 'wonen heeft geen lijdend voorwerp, dus -baar past niet. Eerst be-.' },
              { w: 'onbe', note: 'Twee voorvoegsels zonder stam vormen geen woord. Begin bij woon.' },
            ],
            note: '[on [[be woon] baar]]: be- maakt het werkwoord overgankelijk, en daardoor mag -baar. Twee affixen werken samen.',
          },
        },
      ],
    },
    {
      kind: 'ambiguity',
      id: 'overschrijven',
      prompt: 'Eén werkwoord, twee klemtonen',
      intro: 'In de infinitief zie je niet of het deeltje los kan. Kies een betekenis en zoek de zin die alleen dát kan betekenen.',
      sentence: 'Ik moet die tekst nog overschrijven.',
      meanings: [
        {
          id: 'kopie',
          label: 'Overnemen, bijvoorbeeld van het bord (óverschrijven)',
          highlight: ['overschrijven'],
          right: 'Klopt. Klemtoon op over: scheidbaar. Ik schrijf hem over, ik heb hem overgeschreven.',
        },
        {
          id: 'weg',
          label: 'Er iets nieuws overheen zetten, zoals bij een bestand (overschríjven)',
          highlight: ['overschrijven'],
          right: 'Klopt. Klemtoon op schrijven: vast. Ik overschrijf hem, ik heb hem overschreven.',
        },
      ],
      options: [
        { t: 'Ik moet die tekst morgen nog overschrijven.', fits: null, note: 'Nog steeds allebei mogelijk: de infinitief verraadt niets.' },
        { t: 'Ik schrijf die tekst morgen van het bord over.', fits: 'kopie' },
        { t: 'Ik heb die tekst per ongeluk overschreven.', fits: 'weg' },
      ],
      done: {
        title: 'De vorm verraadt het',
        text: 'Pas in de persoonsvorm of het deelwoord zie je het verschil: schrijft over en overgeschreven tegenover overschrijft en overschreven.',
      },
    },
    {
      kind: 'type',
      id: 'ondergegaan',
      prompt: 'Typ het voltooid deelwoord van óndergaan (zakken).',
      before: 'Om tien uur was de zon al',
      after: '.',
      hint: 'onder…',
      answer: 'ondergegaan',
      why: 'Klemtoon op onder: scheidbaar, dus ge- tussen deeltje en stam. Bij ondergáán (een operatie) was het ondergaan geweest.',
    },
    {
      kind: 'highlight',
      id: 'basis',
      prompt: 'Kleur elk werkwoord naar zijn basis',
      intro: 'Haal het voorvoegsel en de -en weg. Wat blijft er over?',
      pens: [
        { id: 'zn', label: 'zelfstandig naamwoord', tag: 'zn', ask: 'Is de basis een ding, zoals wapen of bos?', accent: 'blue' },
        { id: 'bn', label: 'bijvoeglijk naamwoord', tag: 'bn', ask: 'Is de basis een eigenschap, zoals breed of vrij?', accent: 'orange' },
        { id: 'ww', label: 'werkwoord', tag: 'ww', ask: 'Is de basis zelf al een werkwoord?', accent: 'purple' },
      ],
      words: [
        { t: 'bewapenen', role: 'zn' },
        { t: 'verduidelijken', role: 'bn' },
        { t: 'bespreken', role: 'ww' },
        { t: 'ontbossen', role: 'zn' },
        { t: 'ontnuchteren', role: 'bn' },
        { t: 'ontdooien', role: 'ww' },
        { t: 'verfilmen', role: 'zn' },
        { t: 'vergroenen', role: 'bn' },
        { t: 'verkopen', role: 'ww' },
      ],
      done: {
        title: 'Drie bases, één uitkomst',
        text: 'wapen, bos en film; duidelijk, nuchter en groen; spreken, dooien en kopen. Wat eruit komt, is telkens een werkwoord.',
      },
    },
    {
      kind: 'bet',
      id: 'ontspullen',
      prompt: 'Een nieuw werkwoord voor ‘alle overbodige spullen uit je huis wegdoen’. Welke vorm past bij de levende patronen?',
      options: ['ontspullen', 'erspullen', 'gespullen'],
      answer: 'ontspullen',
      why: 'ont- leeft: iets wegnemen, zoals onthaasten en ontzorgen. er- en ge- maken geen nieuwe werkwoorden meer.',
    },
    {
      kind: 'explain',
      id: 'onderzoek',
      title: 'Wat het voorvoegsel met de zin doet',
      panels: [
        {
          text: 'Vergelijk *Ze plakt posters op de muur* met *Ze beplakt de muur met posters*. Dezelfde handeling, maar de tweede zin zegt meer: de muur raakt vol. Wat lijdend voorwerp wordt, wordt in zijn geheel geraakt. Dat heet het *holistische effect*. Het Engels kent het zonder voorvoegsel: *load hay onto the truck* tegenover *load the truck with hay*. Beth Levin (1993) zette tientallen Engelse werkwoorden met zo’n wisseling op een rij. Het Nederlands gebruikt er vaak *be-* voor: *beladen*, *beplanten*, *beplakken*.',
          rule: 'Met *be-* wordt de plaats het lijdend voorwerp, en die wordt in zijn geheel geraakt: *de tuin beplanten*.',
          quiz: {
            q: 'Welke zin zegt dat de hele tuin vol staat?',
            options: ['Hij beplant de tuin met rozen.', 'Hij plant rozen in de tuin.'],
            answer: 'Hij beplant de tuin met rozen.',
            why: 'Met be- wordt de tuin het lijdend voorwerp, en een lijdend voorwerp wordt als geheel geraakt. In de tweede zin kunnen er ook een paar rozen in een hoekje staan.',
          },
          deep: {
            q: 'Is dat effect een harde regel?',
            a: 'Nee, het is een sterke neiging. *Hij beplantte de tuin met een paar rozen* is niet onmogelijk. Maar wat een lezer zonder verdere informatie aanneemt, verschilt duidelijk. Voor schrijvers is het een middel: met *be-* zet je het geraakte ding in het midden van de zin.',
          },
        },
        {
          text: 'Waarom valt *ge-* weg na een vast voorvoegsel? Is het klank of morfologie? Het Duits helpt. Daar valt *ge-* weg zodra de eerste lettergreep van het werkwoord geen klemtoon heeft, ook zonder voorvoegsel: *studiert*, *trompetet*. Het Nederlands zegt *gestudeerd* en *getrompet*. In het Nederlands telt dus niet de klemtoon, maar het voorvoegsel zelf. Ook als de basis niets betekent: *vergeten*, *begonnen*.',
          rule: 'Duits: geen *ge-* als de eerste lettergreep geen klemtoon heeft. Nederlands: geen *ge-* na een vast voorvoegsel.',
          lab: {
            label: 'Tik een werkwoord',
            chips: [
              { k: 'studeren', out: 'gestudeerd (Duits: studiert)', note: 'Eerste lettergreep zonder klemtoon. Het Duits laat ge- weg, het Nederlands niet.' },
              { k: 'trompetten', out: 'getrompet (Duits: trompetet)', note: 'Weer klemtoon op de tweede lettergreep, weer alleen in het Duits zonder ge-.' },
              { k: 'vergeten', out: 'vergeten', note: 'ver- is een voorvoegsel, ook al betekent geten niets: geen ge-.' },
              { k: 'geloven', out: 'geloofd', note: 'Het voorvoegsel ge- staat er al. Er komt geen tweede bij.' },
            ],
          },
        },
        {
          text: 'Als voorvoegsel en deeltje samenkomen, telt de bouw. *Voorbereiden* is *voor* + *bereiden*: het deeltje staat buiten, en *bereiden* heeft al *be-*. Dus *voorbereid*, zonder *ge-*. *Herindelen* is andersom: *her-* + *indelen*. Binnenin zit een scheidbaar werkwoord, en dat krijgt gewoon zijn *ge-*: *ingedeeld*. Met *her-* ervoor wordt het *heringedeeld*. De vorm volgt de boom van het woord.',
          rule: 'Vast voorvoegsel achter het deeltje: geen *ge-* (*voorbereid*). Deeltje binnen *her-*: *ge-* blijft (*heringedeeld*).',
          split: {
            q: 'Knip het voltooid deelwoord in morfemen',
            word: 'heringedeeld',
            answer: 'her-in-ge-deel-d',
            note: 'her + in + ge + deel + d. De ge- staat tussen het deeltje in en de stam deel. her- staat helemaal buiten, voor het hele werkwoord indelen.',
          },
          deep: {
            q: 'Waarom klinkt ‘De provincie herindeelt de gemeenten’ zo vreemd?',
            a: 'Omdat zo’n werkwoord twee eisen tegelijk stelt. Het deeltje *in* wil los in de hoofdzin (*deelt in*), maar *her-* wil vast aan het werkwoord. Geen van beide vormen voelt goed. Veel sprekers gebruiken zulke werkwoorden daarom vooral als infinitief of deelwoord: *Ze gaan de gemeenten herindelen*, *De gemeente is heringedeeld*.',
          },
        },
        {
          text: 'De vaste kant van *door*, *over* en *om* lijkt verdacht veel op *be-*. Vergelijk *Ze fietst door de stad* met *Ze doorkruist de stad*, en *Het schip vaart om de kaap* met *Het schip omvaart de kaap*. Wat eerst een voorzetselgroep was, wordt een lijdend voorwerp. Ook de betekenis schuift vaak naar het figuurlijke: wie een probleem *omzeilt*, zeilt nergens. Het vaste deeltje doet dus wat *be-* doet: het werkt als een applicatief.',
          rule: 'Een vast deeltje maakt, net als *be-*, vaak van een voorzetselgroep een lijdend voorwerp.',
          mark: {
            q: 'Tik het kernwoord van elk lijdend voorwerp',
            sentence: 'Ze doorkruist de stad, ondergaat een operatie en omzeilt elk probleem.',
            targets: [3, 6, 10],
            note: 'stad, operatie en probleem: drie lijdende voorwerpen bij drie vaste werkwoorden. Zonder vast deeltje heb je een voorzetsel nodig: door de stad fietsen.',
          },
        },
      ],
    },
    {
      kind: 'rewrite',
      id: 'beplanten',
      prompt: 'Zet de tuin centraal: maak er een zin met beplanten van.',
      source: 'Ze plantte tulpen in de hele tuin.',
      accept: ['Ze beplantte de hele tuin met tulpen.', 'Ze beplantte de tuin met tulpen.'],
      why: 'Met be- wordt de tuin het lijdend voorwerp en komen de tulpen in een met-groep. Verleden tijd: beplant + te, want t zit in ’t kofschip.',
    },
    {
      kind: 'sort',
      id: 'ge-of-niet',
      prompt: 'Krijgt het voltooid deelwoord een ge-?',
      buckets: ['met ge-', 'zonder ge-'],
      items: [
        { t: 'studeren', b: 0 },
        { t: 'trompetten', b: 0 },
        { t: 'herindelen', b: 0 },
        { t: 'misgaan', b: 0 },
        { t: 'achterlaten', b: 0 },
        { t: 'geloven', b: 1 },
        { t: 'vergeten', b: 1 },
        { t: 'voorbereiden', b: 1 },
        { t: 'uitbetalen', b: 1 },
        { t: 'misbruiken', b: 1 },
      ],
      why: 'gestudeerd, getrompet, heringedeeld, misgegaan en achtergelaten. Maar geloofd, vergeten, voorbereid, uitbetaald en misbruikt: daar staat een vast voorvoegsel vlak voor de stam.',
    },
    {
      kind: 'type',
      id: 'heringedeeld',
      prompt: 'Typ het voltooid deelwoord van herindelen.',
      before: 'Volgend jaar wordt onze gemeente',
      after: '.',
      hint: 'her…',
      answer: 'heringedeeld',
      why: 'her + ingedeeld: binnenin zit het scheidbare indelen, en dat krijgt zijn ge- tussen in en deel.',
    },
    {
      kind: 'bet',
      id: 'verplommen',
      prompt: 'Een verzonnen werkwoord: ‘verplommen’. Het voltooid deelwoord is…',
      options: ['verplomd', 'geverplomd', 'verplomt'],
      answer: 'verplomd',
      why: 'ver- is vast: geen ge-. De stam verplom eindigt op m, en die zit niet in ’t kofschip: -d. Ook bij een woord dat niemand kent, werkt de regel.',
    },
    {
      kind: 'swipe',
      id: 'voorvoegsel-waar',
      prompt: 'Klopt deze zin?',
      cards: [
        { t: 'Bij ‘Ze beplakt de muur met posters’ denk je dat de hele muur vol hangt.', ok: true, why: 'Het holistische effect: het lijdend voorwerp wordt als geheel geraakt.' },
        { t: 'Het Duits zegt gestudiert, net als het Nederlands gestudeerd.', ok: false, fix: 'het Duits zegt studiert, zonder ge-', why: 'In het Duits valt ge- weg als de eerste lettergreep geen klemtoon heeft.' },
        { t: 'Vergeten krijgt geen ge-, ook al betekent geten niets.', ok: true, why: 'Het gaat om de vorm ver-, niet om de betekenis van de rest.' },
        { t: 'Het voltooid deelwoord van herindelen is herindeeld.', ok: false, fix: 'heringedeeld', why: 'Binnenin zit indelen, met ge- tussen in en deel.' },
        { t: 'Doorkruisen heeft net als bekijken een lijdend voorwerp.', ok: true, why: 'Ze doorkruist de stad: het vaste deeltje werkt als be-.' },
        { t: 'ge- maakt nog steeds nieuwe werkwoorden, zoals geloven.', ok: false, fix: 'ge- is dood; geloven is een oud woord', why: 'Nieuwe werkwoorden komen met ver-, ont- en her-.' },
      ],
    },
  ],
};
