import type { LessonInput } from '../../schema';

/**
 * Bachelorles voor "Het betekenisvolle woorddeel": persoonsnamen uit werkwoorden (nomina agentis).
 * De vormen -er, -aar en -der, de rollen die -er noemt (doener, werktuig, nooit wie het ondergaat),
 * de vrouwelijke achtervoegsels en welke bij welke mannelijke vorm hoort, de neutrale neiging,
 * -ling en het deelwoord met -e voor wie iets ondergaat, en -ant, -ent en -eur bij leenwerkwoorden.
 * De -er/-aar-regel en de blokkering uit d11 worden verondersteld, niet herhaald.
 */
export const LES_D22: LessonInput = {
  id: 'd22',
  stage: 'bachelor',
  domain: 'morf',
  also: ['sem', 'fon'],
  title: 'Bakker, bakster en schilderes: wie het doet',
  skill: 'Woorden',
  icon: '-ster',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'De naam van de doener',
      panels: [
        {
          text: 'Wie bakt, is een *bakker*; wie leest, een *lezer*. Het achtervoegsel *-er* maakt van een werkwoord de naam van wie het doet: een *nomen agentis*, letterlijk ‘doenernaam’. Het is een van de productiefste achtervoegsels van het Nederlands: *skater*, *vlogger*, *streamer*. De vorm hangt af van de stam. Na een beklemtoonde lettergreep *-er* (*lezer*), na een zwakke lettergreep op *l*, *r* of *n* *-aar* (*wandelaar*, dat kende je al). En na een beklemtoonde stam op *r* komt er een *d* tussen: *huurder*, *bestuurder*, *bewaarder*. Twee *r*-lettergrepen achter elkaar, *huur-rer*, klinken slecht; dezelfde *d* zie je in *duur*, *duurder* en in *boerderij*.',
          rule: 'Na een beklemtoonde stam op *r* komt *-der*: *huurder*, *bestuurder*. Vergelijk *duurder*.',
          paradigm: {
            q: 'Maak de naam van wie het doet',
            cols: ['wie het doet'],
            rows: [
              { label: 'huren', cells: [{ fill: 'huurder', hint: 'Beklemtoonde stam op r: een d ertussen.' }] },
              { label: 'besturen', cells: [{ fill: 'bestuurder' }] },
              {
                label: 'bewonderen',
                cells: [{ fill: 'bewonderaar', hint: 'be-WON-der: zwakke lettergreep op r, dus -aar. Niet -der: dat is voor een beklemtoonde stam op r.' }],
              },
              { label: 'bewaren', cells: [{ fill: 'bewaarder', hint: 'be-WAAR: beklemtoond, op r: -der.' }] },
              { label: 'skaten', cells: [{ fill: 'skater' }] },
              { label: 'verzamelen', cells: [{ fill: 'verzamelaar' }] },
            ],
            extra: ['huurer', 'bestuurer', 'bewonderder', 'bewaaraar', 'verzameler'],
            note: 'bewonderaar naast bewaarder: in allebei zit een r, maar bewonder eindigt zwak (-aar) en bewaar beklemtoond (-der). De klemtoon beslist, niet de letter.',
          },
          deep: {
            q: 'Waarom hebben dienaar, minnaar en leraar -aar na een beklemtoonde stam?',
            a: 'Dat zijn oude woorden. *-aar* gaat terug op het Latijnse *-arius*: *molenaar* naast *molinarius*. Vroeger kon *-aar* overal staan; de verdeling naar klemtoon is later gegroeid. Woorden die toen al bestonden, hielden hun vorm. *Dienaar*, *minnaar* en *leraar* zijn dus geen uitzonderingen op de regel, maar ouder dan de regel.',
          },
        },
        {
          text: 'Een *-er*-woord noemt het onderwerp van het werkwoord, en dat hoeft geen mens te zijn: een *opener* opent, een *printer* print, een *aansteker* steekt aan. Zulke werktuignamen volgen dezelfde klankregel: *schakelaar*, *versnipperaar*. Maar lang niet elk werktuig krijgt *-er*: een potlood heet geen *schrijver*, een pan geen *bakker*. En wie de handeling ondergaat, krijgt nooit *-er*: een vis die gevangen wordt, is geen *vanger*. Speel de rollen na.',
          rule: '*-er* noemt het onderwerp: wie het doet, of wat het doet. Nooit wat de handeling ondergaat.',
          cast: {
            q: 'Tik de rol die de zin vraagt',
            rounds: [
              {
                text: 'De visser vangt een vis vanuit de boot.',
                ask: 'Tik wie het doet',
                cast: ['visser', 'vis', 'boot', 'mus'],
                answer: ['visser'],
                then: { q: 'Hoe heet wie vist?', options: ['visser', 'vissaar', 'visder'], answer: 'visser' },
                note: 'vis eindigt beklemtoond en niet op r: -er, met een dubbele s. Wie vist, is een visser.',
              },
              {
                text: 'De vis wordt door de visser gevangen.',
                ask: 'Tik wat de handeling ondergaat',
                cast: ['visser', 'vis', 'boot', 'ster'],
                answer: ['vis'],
                then: {
                  q: 'Kan de vis een vanger heten?',
                  options: ['Nee: -er noemt nooit wat de handeling ondergaat', 'Ja: alles bij vangen mag -er krijgen'],
                  answer: 'Nee: -er noemt nooit wat de handeling ondergaat',
                },
                note: 'De vanger is de visser. Voor wie iets ondergaat heeft het Nederlands andere middelen; die zie je in de tweede uitleg.',
              },
              {
                text: 'Pim schrijft in het boek.',
                ask: 'Tik de schrijver',
                cast: ['pim', 'boek', 'kast', 'mes'],
                answer: ['pim'],
                then: {
                  q: 'En een gewoon potlood in je hand: heet dat een schrijver?',
                  options: ['Nee: een werktuig krijgt -er alleen als het als onderwerp gezien wordt, zoals een opener', 'Ja: elk werktuig krijgt -er'],
                  answer: 'Nee: een werktuig krijgt -er alleen als het als onderwerp gezien wordt, zoals een opener',
                },
                note: 'Pim is de schrijver: hij doet het. Een opener opent als het ware zelf; een potlood schrijft niet zelf. Welke werktuigen -er krijgen, ligt deels per woord vast.',
              },
            ],
            note: 'Drie rollen: wie het doet (visser), wat het ondergaat (vis) en waarmee (boot, potlood). Alleen de eerste krijgt vanzelf -er; werktuigen soms, en wat de handeling ondergaat nooit.',
          },
          deep: {
            q: 'Waarom krijgt de opener wel -er en het potlood niet?',
            a: 'Een werktuig krijgt *-er* als je het als vanzelf werkend ziet: *de opener opent*, *de wekker wekt*, *de printer print*. Een potlood doet niets uit zichzelf. Rochelle Lieber (2004) beschrijft *-er* als een achtervoegsel dat het eerste argument van een dynamische situatie noemt, mens of ding. Toch blijft het deels per woord geregeld: *zender* en *ontvanger* zijn apparaten, *lezer* en *schrijver* zijn mensen, al bestaat *kaartlezer*.',
          },
        },
        {
          text: 'Voor een vrouw heeft het Nederlands vijf achtervoegsels, en welk je kiest hangt af van de mannelijke vorm. *-ster* plakt aan de werkwoordstam, niet aan *-er*: *bakster*, *schrijfster* (met *f*, zoals de stam), *schaatsster* (drie keer *s*). *-es* komt na *-aar* en na een vaste groep oudere *-er*-woorden: *lerares*, *tekenares*, *zangeres*, *dichteres*, *schilderes*. *-in* hoort bij korte zelfstandige naamwoorden: *vriendin*, *boerin*, *koningin*. *-e* bij Franse en Latijnse persoonsnamen: *studente*, *pianiste*, *advocate*, *psychologe*. En *-euse* of *-trice* bij *-eur*: *masseuse*, *actrice*.',
          rule: '*-ster* aan de stam (*schrijfster*), *-es* na *-aar* en oude *-er*-woorden (*lerares*, *zangeres*), *-in* bij korte naamwoorden (*boerin*), *-e* bij leenwoorden (*studente*), *-euse* of *-trice* bij *-eur*.',
          paradigm: {
            q: 'Vul de vrouwelijke vorm in',
            cols: ['vrouw'],
            rows: [
              { label: 'bakker', cells: [{ fill: 'bakster', hint: '-ster aan de stam bak, niet aan bakker.' }] },
              { label: 'schrijver', cells: [{ fill: 'schrijfster', hint: 'De stam is schrijf, met f.' }] },
              { label: 'leraar', cells: [{ fill: 'lerares', hint: 'Na -aar komt -es, en de klemtoon gaat mee: leraRES.' }] },
              { label: 'zanger', cells: [{ fill: 'zangeres' }] },
              { label: 'student', cells: [{ fill: 'studente' }] },
              { label: 'acteur', cells: [{ fill: 'actrice', hint: 'Na -teur: -trice, zoals in het Frans.' }] },
              { label: 'boer', cells: [{ fill: 'boerin' }] },
            ],
            extra: ['bakkerin', 'schrijvster', 'zangster', 'studentin', 'acteuse', 'leraarster'],
            note: 'Zeven mannen, vijf achtervoegsels. De mannelijke vorm vertelt welk je nodig hebt: stam + ster, -aar of oud -er + es, kort naamwoord + in, leenwoord + e, -teur + trice.',
          },
          deep: {
            q: 'Waarom hoor je de klemtoon verschuiven bij lerares en koningin?',
            a: '*-ster* en *-e* zijn klemtoonloos: *BAKster*, *stuDENte*. Maar *-es*, *-in*, *-euse* en *-trice* nemen de klemtoon: *leraRES*, *koningIN*, *masSEUse*, *acTRIce*. *-in* is inheems en toch beklemtoond; *-es* kwam via het Frans uit het Latijn (*-issa*), net als in *prinses*, en de Franse uitgangen doen wat Franse uitgangen altijd doen. In de master (Inheems, geleerd en een paradox) zie je waarom herkomst en klemtoon niet hetzelfde zijn.',
          },
        },
        {
          text: 'Moet je de vrouwelijke vorm gebruiken? Het Taalunie-advies zegt: het mag, het hoeft niet. In Nederland wint de neutrale vorm: *zij is directeur*, *de docent zei dat zij…*, *onze minister en haar team*. In België zijn *directrice*, *advocate* en *docente* gewoner. Bij sommige beroepen koos het vak zelf een nieuwe, neutrale naam: *verpleegster* en *verpleger* werden *verpleegkundige*. De sport gaat juist de andere kant op: *schaatsster*, *wielrenster* en *aanvoerster* zijn daar de gewone woorden.',
          rule: 'Neutraal (*zij is directeur*) en vrouwelijk (*directrice*) zijn allebei goed; Nederland neigt naar neutraal, België naar vrouwelijk.',
          lab: {
            label: 'Tik een beroep',
            chips: [
              {
                k: 'directeur',
                out: 'zij is directeur / zij is directrice',
                note: 'Allebei goed. In Nederlandse teksten is directeur voor een vrouw gewoon; in België hoor je vaker directrice.',
              },
              {
                k: 'docent',
                out: 'de docent, zij / de docente',
                note: 'Met -e is de vrouw gemarkeerd. Zonder -e wijst alleen het voornaamwoord zij haar aan.',
              },
              {
                k: 'verpleegster',
                out: 'verpleegkundige',
                note: 'De oude vorm was vrouwelijk, verpleger de uitzondering voor mannen. Het vak koos een vorm zonder geslacht: een bijvoeglijk naamwoord met -e, zoals deskundige.',
              },
              {
                k: 'voorzitter',
                out: 'de voorzitter / de voorzitster',
                note: 'Voorzitster bestaat, maar bijna elke vergadering zegt voorzitter, ook voor een vrouw.',
              },
              { k: 'schaatser', out: 'de schaatsster', note: 'In de sport blijft de vrouwelijke vorm standaard: de schaatsster won de 1500 meter.' },
            ],
          },
          deep: {
            q: 'Waarom laat Nederland de vrouwelijke vorm vallen?',
            a: 'De mannelijke vorm is in veel talen ook de algemene: *alle schrijvers van de twintigste eeuw* omvat vrouwen. Wie *schrijfster* zegt, voegt iets toe: het geslacht. Sommige vrouwen willen dat juist, anderen zien het als een etiket dat mannen niet krijgen. Het Nederlandse gebruik koos het weglaten als gelijk; het Vlaamse het noemen. Over het voornaamwoord zijn beide het eens: *de directeur zei dat zij…*.',
          },
        },
      ],
    },
    {
      kind: 'morph',
      id: 'bak',
      prompt: 'Bouw woorden met bak',
      intro: 'Wie bakt, wat gebakken is, en waar. Niet elk stukje past op elk stukje.',
      stem: 'bak',
      slots: [
        { id: 's1', label: 'Erachter', side: 'after', parts: ['er', 'ster', 'sel'] },
        { id: 's2', label: 'Daarna', side: 'after', parts: ['ij', 's'] },
      ],
      words: [
        { combo: ['', ''], w: 'bak', cls: 'ww', mean: 'De stam van bakken: ik bak.' },
        { combo: ['er', ''], w: 'bakker', cls: 'zn', mean: 'Wie bakt. Dubbele k: de korte a blijft kort.' },
        { combo: ['ster', ''], w: 'bakster', cls: 'zn', mean: 'Een vrouw die bakt. -ster aan de stam, niet aan bakker.' },
        { combo: ['sel', ''], w: 'baksel', cls: 'zn', mean: 'Wat gebakken is: het resultaat, geen persoon.' },
        { combo: ['er', 'ij'], w: 'bakkerij', cls: 'zn', mean: 'De plek van de bakker. -ij plakt aan bakker en neemt de klemtoon: bakkeRIJ.' },
        { combo: ['er', 's'], w: 'bakkers', cls: 'zn', mean: 'Meervoud: twee bakkers.' },
        { combo: ['ster', 's'], w: 'baksters', cls: 'zn', mean: 'Meervoud: twee baksters.' },
        { combo: ['sel', 's'], w: 'baksels', cls: 'zn', mean: 'Meervoud: alle baksels van vandaag.' },
      ],
      forms: { '': 'bak', er: 'bakker', ster: 'bakster', sel: 'baksel' },
      hints: [
        {
          part: 'ij',
          note: 'Bestaat zo niet. -ij maakt een plaats of bedrijf van een persoonsnaam op -er: bakkerij. Niet van bakster of baksel, en niet van de kale stam.',
        },
        { part: 's', note: 'Bestaat niet. De meervouds-s hoort achter een woord op -er, -ster of -sel, niet achter de kale stam.' },
      ],
      goal: 6,
      done: { title: 'Wie, wat en waar', text: 'bakker en bakster noemen de persoon, baksel het resultaat, bakkerij de plaats. Elk stukje kiest zijn buur.' },
    },
    {
      kind: 'sort',
      id: 'er-aar-der',
      prompt: 'Wie het doet: -er, -aar of -der?',
      buckets: ['-er', '-aar', '-der'],
      items: [
        { t: 'skaten', b: 0 },
        { t: 'vloggen', b: 0 },
        { t: 'ontwerpen', b: 0 },
        { t: 'verzamelen', b: 1 },
        { t: 'fluisteren', b: 1 },
        { t: 'bewonderen', b: 1 },
        { t: 'huren', b: 2 },
        { t: 'bewaren', b: 2 },
        { t: 'aanvoeren', b: 2 },
        { t: 'snorren (met een auto klanten zoeken)', b: 2 },
      ],
      why: 'skater, vlogger, ontwerper: stam beklemtoond, niet op r. verzamelaar, fluisteraar, bewonderaar: zwakke lettergreep op l of r. huurder, bewaarder, aanvoerder en snorder: beklemtoonde stam op r, dus een d ertussen.',
    },
    {
      kind: 'type',
      id: 'schrijfster',
      prompt: 'Typ het woord voor een vrouw die boeken schrijft.',
      before: 'Ze is de bekendste',
      after: 'van haar generatie.',
      hint: 'schrijf…',
      answer: 'schrijfster',
      why: '-ster plakt aan de stam schrijf, met een f: schrijfster. Niet aan schrijver, en geen v.',
    },
    {
      kind: 'fix',
      id: 'schaatsster',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'De Nederlandse schaatster won goud op de 1500 meter.',
      wrong: 2,
      answer: 'schaatsster',
      why: 'schaats + ster: de stam eindigt op s en het achtervoegsel begint met s. Drie keer s, net als in tennisster en fietsster.',
    },
    {
      kind: 'explain',
      id: 'verdieping',
      title: 'Wie het ondergaat, en de leenwoorden',
      panels: [
        {
          text: 'Het oude achtervoegsel *-ling* maakt ook persoonsnamen, maar met een andere rol. Vaak noemt het wie de handeling *ondergaat*: een *dopeling* wordt gedoopt, een *vondeling* gevonden, een *huurling* gehuurd, een *beschermeling* beschermd. Toch is *-ling* geen spiegelbeeld van *-er*: een *zuigeling* zuigt zelf, een *volgeling* volgt zelf. En de basis kan ook een bijvoeglijk naamwoord zijn (*nieuweling*, *vreemdeling*) of een telwoord (*tweeling*). Nieuwe *-ling*-woorden komen er nauwelijks bij.',
          rule: '*-ling* noemt vaak wie iets ondergaat (*dopeling*), maar niet altijd (*zuigeling*); het is bijna niet meer productief.',
          mark: {
            q: 'Tik de -ling-woorden die noemen wie de handeling ondergaat',
            sentence: 'dopeling zuigeling vondeling volgeling huurling nieuweling',
            targets: [0, 2, 4],
            note: 'dopeling, vondeling en huurling worden gedoopt, gevonden en gehuurd. zuigeling en volgeling doen het zelf. nieuweling heeft geen werkwoord als basis, maar nieuw.',
          },
          deep: {
            q: 'Hoe weet je dat -ling niet meer leeft?',
            a: 'Probeer het: wie geappt wordt, is geen *appeling*; wie ontslagen wordt, geen *ontslageling*. Sprekers grijpen naar een ander middel, dat je in het volgende paneel ziet. In de master (Productiviteit meten) leer je hoe je zoiets in een corpus telt: *-ling* levert vrijwel geen nieuwe woorden meer op.',
          },
        },
        {
          text: 'Voor wie iets ondergaat gebruikt het Nederlands vooral het voltooid deelwoord met *-e*: *de genodigde*, *de verdachte*, *de gevangene*, *de geadresseerde*, *de gedupeerde*. Dat is levend en onbeperkt: *de geïnterviewde*, en als het moet *de geappte*. Het meervoud krijgt *-n*: *de genodigden*. En het is vanzelf geslachtsneutraal: *de verdachte* is een man of een vrouw. Zet naast elke doener de persoon die het ondergaat.',
          rule: 'Wie het ondergaat: voltooid deelwoord + *-e* (*de ondervraagde*). Wie het doet: *-er* (*de ondervrager*).',
          paradigm: {
            q: 'Vul de doener en wie het ondergaat in',
            cols: ['wie het doet', 'wie het ondergaat'],
            rows: [
              { label: 'kiezen', cells: [{ fill: 'kiezer' }, { fill: 'gekozene', hint: 'Voltooid deelwoord gekozen + e.' }] },
              { label: 'ondervragen', cells: [{ fill: 'ondervrager' }, { fill: 'ondervraagde' }] },
              { label: 'interviewen', cells: ['interviewer', { fill: 'geïnterviewde', hint: 'Deelwoord geïnterviewd, met trema, + e.' }] },
              {
                label: 'verzekeren',
                cells: [
                  { fill: 'verzekeraar', hint: 'ver-ZE-ker: zwakke lettergreep op r, dus -aar.' },
                  { fill: 'verzekerde', hint: 'Deelwoord verzekerd + e: de klant.' },
                ],
              },
            ],
            extra: ['kiesling', 'verzekerer', 'interviewling', 'ondervraagling'],
            note: 'Links -er of -aar voor wie het doet, rechts het deelwoord met -e voor wie het ondergaat. Het deelwoord werkt altijd; -ling is uitgespeeld.',
          },
          deep: {
            q: 'Is de gevangene dan een zelfstandig naamwoord?',
            a: 'Het is een bijvoeglijk naamwoord dat als zelfstandig naamwoord gebruikt wordt, net als *de rijke* of *de zieke*. Daarom krijgt het meervoud *-n* (*gevangenen*, *zieken*) en geen *-s* of *-en* zoals een echt naamwoord. Je herkent zo’n woord ook aan het lidwoord: het heeft bijna altijd *de* en een bepaalde lezing, *de verdachte* in deze zaak.',
          },
        },
        {
          text: 'Bij werkwoorden op *-eren* uit het Latijn en Frans doet *-er* het vaak niet. Wie demonstreert is een *demonstrant*, wie studeert een *student*, wie masseert een *masseur*. *-ant* of *-ent*? Dat beslist het Latijn: werkwoorden van de a-klasse (*demonstrare*) geven *-ant* (*demonstrant*, *sollicitant*, *emigrant*), de andere klassen geven *-ent* (*student*, *docent*, *producent*, *dirigent*). Aan het Nederlandse werkwoord zie je dat niet. *-eur* hoort bij werkwoorden uit het Frans (*regisseur*, *controleur*, *monteur*), en *-ist* hoort meestal bij een zelfstandig naamwoord: *piano*, *pianist*.',
          rule: 'Leenwerkwoorden op *-eren*: *-ant* (*demonstrant*), *-ent* (*student*) of *-eur* (*masseur*). Het Latijn en het Frans beslissen; leer het per woord.',
          build: {
            before: 'Wie solliciteert, is een…',
            stem: 'sollicit',
            endings: ['ant', 'ent', 'eur', 'er'],
            answer: 'ant',
            note: 'sollicitare is een a-werkwoord: sollicitant. Een sollicitent of solliciteur bestaat niet, en -er maakt het Nederlands hier niet.',
          },
          deep: {
            q: 'Wat als je het Latijn niet kent?',
            a: 'Dan helpt de familie. Staat er al een woord op *-atie*, dan is het meestal *-ant*: *demonstratie*, *demonstrant*; *emigratie*, *emigrant*; *sollicitatie*, *sollicitant*. Staat er een woord op *-entie* of *-ctie*, dan *-ent*: *concurrentie*, *concurrent*; *productie*, *producent*. Zo kiest een spreker het achtervoegsel door te ruilen binnen de familie, zoals bij *-isme* en *-ist* (zie Elk achtervoegsel stelt eisen).',
          },
        },
        {
          text: 'De richting van afleiden is meestal man → vrouw: *bakker* → *bakster*. Maar niet altijd. *Weduwnaar* is gemaakt van *weduwe*, met het achtervoegsel *-naar*: hier is de vrouw de basis. En *schilder* was oorspronkelijk geen *-er*-afleiding van *schilderen*: het was *schild* + *-er*, iemand die schilden maakte en beschilderde. Het werkwoord *schilderen* is later van het naamwoord afgeleid. Daarom heet een vrouw een *schilderes*, naar het oude naamwoord, en geen *schildster*.',
          rule: 'De richting is niet vast: *weduwnaar* komt van *weduwe*, en *schilderen* van *schilder*.',
          quiz: {
            q: 'Welk woord is van de vrouwelijke vorm afgeleid?',
            options: ['weduwnaar', 'boerin', 'lerares'],
            answer: 'weduwnaar',
            why: 'weduwe is de basis, -naar maakt er de man van. boerin en lerares gaan de gewone kant op: van boer en leraar.',
          },
          deep: {
            q: 'Zijn er meer van zulke omkeringen?',
            a: 'Ja, de *terugvorming*: van *stofzuiger* kwam *stofzuigen*, van *beeldhouwer* *beeldhouwen*, van *chauffeur* *chaufferen*. Sprekers zien een *-er*-woord en verzinnen er het werkwoord bij dat eronder hoort te zitten. Dat laat zien hoe sterk het patroon werkwoord → *-er* in het hoofd zit: zo sterk dat het ook achteruit werkt. Meer daarover in de master (Woorden in beweging).',
          },
        },
      ],
    },
    {
      kind: 'rewrite',
      id: 'ondervraagde',
      prompt: 'Zeg hetzelfde met één persoonsnaam in plaats van de bijzin.',
      source: 'De man die ondervraagd werd, zweeg.',
      accept: ['De ondervraagde zweeg.'],
      why: 'Wie iets ondergaat: voltooid deelwoord + e. De ondervraagde zweeg. Geen -ling: een ondervraagling bestaat niet.',
    },
    {
      kind: 'choice',
      id: 'sollicitant',
      prompt: 'Kies de goede persoonsnaam.',
      before: 'Na het gesprek belde de',
      after: 'nog één keer om te bedanken.',
      options: ['sollicitant', 'sollicitent', 'solliciteerder'],
      answer: 'sollicitant',
      why: 'Latijnse a-klasse, en de familie bevestigt het: sollicitatie, sollicitant. Een -er-vorm maakt het Nederlands hier niet.',
    },
    {
      kind: 'bet',
      id: 'ling-rol',
      prompt: 'Welk -ling-woord noemt iemand die de handeling zelf doet?',
      options: ['volgeling', 'dopeling', 'vondeling'],
      answer: 'volgeling',
      why: 'Een volgeling volgt zelf. Een dopeling wordt gedoopt en een vondeling gevonden. -ling is dus geen zuivere naam voor wie iets ondergaat.',
    },
    {
      kind: 'dictation',
      id: 'dictee-namen',
      prompt: 'Luister en typ de zin.',
      sentence: 'De dirigent prees de zangeres en de pianiste.',
      right: 'Goed: dirigent met -ent (dirigere), zangeres met -es na het oude -er-woord zanger, pianiste met -e bij een leenwoord.',
      wrong: 'Let op: dirigent met -ent, zangeres met -es, pianiste met -e. Drie persoonsnamen, drie uitgangen.',
    },
    {
      kind: 'explain',
      id: 'onderzoek',
      title: 'Wat -er echt noemt, en wie er verdwijnt',
      panels: [
        {
          text: 'Wat noemt *-er* precies? Malka Rappaport Hovav en Beth Levin (1992) zeiden voor het Engels: het *externe argument*, het onderwerp dat de handeling in gang zet. Dat voorspelt een gat: werkwoorden waarvan het onderwerp iets overkomt (*vallen*, *blijven*, *aankomen*; taalkundigen noemen ze *onaccusatief*) zouden geen *-er* krijgen. Het Nederlands is soepeler: een *nieuwkomer* komt aan, een *thuisblijver* blijft, een *uitvaller* valt uit, en een *meevaller* is zelfs geen persoon. Wie een theorie op het Engels bouwt, moet haar in het Nederlands opnieuw toetsen.',
          rule: '*-er* noemt het onderwerp, ook als dat onderwerp niets doet maar iets overkomt: *nieuwkomer*, *uitvaller*.',
          mark: {
            q: 'Tik de -er-woorden waarvan het onderwerp iets overkomt in plaats van doet',
            sentence: 'bakker nieuwkomer lezer uitvaller thuisblijver ontwerper',
            targets: [1, 3, 4],
            note: 'nieuwkomer, uitvaller en thuisblijver: aankomen, uitvallen en blijven hebben een onderwerp dat niets in gang zet. Volgens de Engelse theorie zouden ze geen -er mogen krijgen. bakker, lezer en ontwerper zijn gewone doeners.',
          },
          deep: {
            q: 'Wat zegt dit over de regel?',
            a: 'Geert Booij beschrijft *-er* daarom liever als een achtervoegsel voor het *onderwerp* van het werkwoord, zonder eis dat dat onderwerp handelt. Dat dekt *lezer*, *wekker*, *meevaller* en *nieuwkomer* in één keer. De prijs is dat de betekenis ‘doener’ niet in het achtervoegsel zit, maar in het werkwoord: *bakker* is een doener omdat *bakken* een doener heeft.',
          },
        },
        {
          text: 'Vrouwelijke vormen zijn oud, en ze verdwijnen al eeuwen. Het Germaanse *-ster* had het Oudengels ook: *bæcestre* was een vrouw die bakte. Toen het achtervoegsel daar zijn vrouwelijke betekenis verloor, bleven de woorden als familienamen hangen: *Baxter*, *Webster* (een weefster). Het Nederlands verloor zo het achtervoegsel *-egge*: alleen *dievegge* is over. Roman Jakobson gaf er een naam aan: de mannelijke vorm is *ongemarkeerd*, de algemene; de vrouwelijke is *gemarkeerd*, hij zegt iets extra’s. Wat gemarkeerd is, kan verdwijnen zonder dat de taal een gat krijgt.',
          rule: 'De mannelijke vorm is ongemarkeerd (ook algemeen), de vrouwelijke gemarkeerd. Gemarkeerde vormen slijten het eerst.',
          lab: {
            label: 'Tik een vorm',
            chips: [
              {
                k: 'Baxter',
                out: 'bake + -ster: vrouw die bakt',
                note: 'Oudengels bæcestre. De betekenis vrouw sleet weg; de naam bleef, nu voor mannen én vrouwen.',
              },
              {
                k: 'Webster',
                out: 'web (weven) + -ster: weefster',
                note: 'Hetzelfde achtervoegsel als ons -ster. In het Engels overleeft het alleen in namen en in spinster.',
              },
              {
                k: 'dievegge',
                out: 'dief + -egge',
                note: 'Het enige Nederlandse woord met dit oude vrouwelijke achtervoegsel. Alle andere -egge-woorden zijn verdwenen.',
              },
              { k: 'naaister', out: 'naai + -ster', note: 'Hier leeft -ster nog gewoon. Of het blijft, hangt af van wat sprekers gemarkeerd willen zeggen.' },
            ],
          },
          deep: {
            q: 'Is verdwijnen de enige richting?',
            a: 'Nee. Het Duits ging de andere kant op: daar is *-in* springlevend (*Lehrerin*, *Studentin*) en schrijven veel teksten bewust *Studentinnen und Studenten*. Dezelfde markering, een andere keuze: het Duits maakt de vrouw juist zichtbaar, het Nederlands van Nederland laat haar opgaan in de algemene vorm. Wat gelijkwaardig is, beslist de taalgemeenschap, niet de grammatica.',
          },
        },
        {
          text: 'Is de algemene vorm echt algemeen in het hoofd van de lezer? Pascal Gygax en collega’s (2008) lieten lezers zinnen lezen als *De muzikanten kwamen uit het gebouw. Een van de vrouwen…* In het Frans en Duits, met een mannelijke meervoudsvorm, kostte die vervolgzin extra tijd: lezers hadden mannen voor zich gezien, ook bij beroepen die meestal vrouwen doen. In het Engels, zonder grammaticaal geslacht, volgden lezers het stereotype van het beroep. De ‘algemene’ mannelijke vorm is dus niet neutraal in de verwerking.',
          rule: 'Een mannelijke meervoudsvorm wordt vaak als mannen gelezen, ook als hij algemeen bedoeld is (Gygax e.a. 2008).',
          quiz: {
            q: 'Wat vonden Gygax en collega’s voor het Frans en Duits?',
            options: [
              'Lezers zagen bij een mannelijke meervoudsvorm vooral mannen voor zich',
              'Lezers volgden alleen het stereotype van het beroep',
              'Lezers maakten geen verschil',
            ],
            answer: 'Lezers zagen bij een mannelijke meervoudsvorm vooral mannen voor zich',
            why: 'De grammaticale vorm won het van het stereotype. In het Engels, zonder zo’n vorm, won juist het stereotype.',
          },
          deep: {
            q: 'En het Nederlands?',
            a: 'Het Nederlands lijkt op het Duits waar een vrouwelijke vorm bestaat (*zangers* naast *zangeressen*) en op het Engels waar die ontbreekt (*de ministers*). Voor schrijvers is dat een keuzemoment. *Alle medewerkers* leest neutraal; *alle zangers* kan mannen oproepen zodra *zangeressen* in de buurt is. Wie neutraal wil zijn, kiest een vorm zonder vrouwelijke tegenhanger (*medewerkers*, *collega’s*, *verpleegkundigen*) of noemt beide.',
          },
        },
        {
          text: 'Hetzelfde *-er* zit in *Amsterdammer*, *twintiger* en *driewieler*: geen werkwoord als basis, maar een naam, een getal of een ding. Taalkundigen twisten of dit één achtervoegsel is met een ruime betekenis (‘iets of iemand met een band met X’) of twee die toevallig gelijk klinken. Eén argument voor ‘hetzelfde’: de klankregel is identiek. Na een zwakke lettergreep op *l*, *r* of *n* wordt het *-aar*, ook hier: *Leidenaar*, *Brusselaar*. Maar inwonersnamen bewaren ook grillen: *Delftenaar* heeft *-enaar* na een beklemtoonde stam, en *Groninger* laat *-en* vallen. Vul de inwoners in.',
          rule: 'Inwonersnamen volgen dezelfde klankregel als doeners (*Amsterdammer*, *Leidenaar*), met per woord vastgelegde uitzonderingen (*Delftenaar*).',
          paradigm: {
            q: 'Hoe heet de inwoner?',
            cols: ['inwoner'],
            rows: [
              { label: 'Amsterdam', cells: ['Amsterdammer'] },
              { label: 'Leiden', cells: [{ fill: 'Leidenaar', hint: 'LEI-den: zwakke lettergreep op n, dus -aar.' }] },
              { label: 'Brussel', cells: [{ fill: 'Brusselaar' }] },
              { label: 'Haarlem', cells: [{ fill: 'Haarlemmer', hint: 'HAAR-lem: zwakke lettergreep op m, niet op l, r of n. Gewoon -er, met dubbele m.' }] },
              { label: 'Delft', cells: [{ fill: 'Delftenaar', hint: 'Beklemtoond en toch -enaar: per woord geleerd, net als kunstenaar.' }] },
              { label: 'Groningen', cells: [{ fill: 'Groninger', hint: 'De -en valt weg: Groning + er.' }] },
            ],
            extra: ['Leidener', 'Brusseler', 'Delfter', 'Groningenaar', 'Haarlemaar'],
            note: 'Leidenaar en Brusselaar volgen de regel, Haarlemmer ook (m telt niet mee). Delftenaar en Groninger zijn per woord vastgelegd: een inwonersnaam leer je zoals een eigennaam.',
          },
          deep: {
            q: 'Is het dan één -er?',
            a: 'Veel beschrijvingen houden ze uit elkaar: het *-er* van *lezer* vraagt een werkwoord en noemt het onderwerp; het *-er* van *Amsterdammer* en *twintiger* vraagt een naamwoord of telwoord en noemt iemand of iets met een band met de basis. Dat ze dezelfde klankregel delen, komt doordat die regel niet van het achtervoegsel is maar van het Nederlands: twee zwakke lettergrepen achter elkaar worden overal vermeden (zie Woordbouw met een maatlat).',
          },
        },
      ],
    },
    {
      kind: 'bet',
      id: 'fluisperaar',
      prompt: 'Een verzonnen werkwoord: fluisperen, zachtjes mopperen. Wie dat doet is een…',
      options: ['fluisperaar', 'fluisperer', 'fluisperder'],
      answer: 'fluisperaar',
      why: 'FLUIS-pe-ren eindigt op een zwakke lettergreep met r: -aar, net als fluisteraar. -der komt alleen na een beklemtoonde stam op r, zoals huurder.',
    },
    {
      kind: 'ambiguity',
      id: 'speler',
      prompt: 'Eén -er-woord, twee onderwerpen',
      intro: 'Een speler kan een mens zijn of een apparaat. Kies een betekenis en zoek de zin die alleen dát kan betekenen.',
      sentence: 'De speler is kapot.',
      meanings: [
        { id: 'mens', label: 'Een sporter die uitgeput is', highlight: ['De speler'], right: 'Klopt. Wie speelt: een mens. Kapot betekent hier doodmoe.' },
        {
          id: 'ding',
          label: 'Een apparaat dat muziek afspeelt en stuk is',
          highlight: ['De speler'],
          right: 'Klopt. Wat afspeelt: een ding, zoals een cd-speler. -er noemt ook hier het onderwerp.',
        },
      ],
      options: [
        { t: 'De speler is helemaal kapot.', fits: null, note: 'Nog steeds allebei: helemaal past bij een mens en bij een apparaat.' },
        { t: 'De speler is kapot na negentig minuten rennen.', fits: 'mens' },
        { t: 'De speler is kapot: hij leest geen enkele cd meer.', fits: 'ding' },
      ],
      done: { title: 'Mens of ding, één achtervoegsel', text: 'Beide keren noemt -er het onderwerp van spelen. Welk onderwerp, zegt de context.' },
    },
    {
      kind: 'chat',
      id: 'sportredactie',
      prompt: 'App met je collega van de sportredactie',
      intro: 'Kies telkens de persoonsnaam die klopt met de regels en met de stijlgids: neutrale functienamen, maar in de sport de vrouwelijke vorm.',
      contact: { name: 'Femke', role: 'je collega', initials: 'F' },
      rounds: [
        {
          say: 'Wie zet ik in de kop voor de 1500 meter?',
          options: ['De Nederlandse schaatsster.', 'De Nederlandse schaatster.'],
          right: 0,
          fix: 'schaatster → schaatsster',
          why: 'schaats + ster: drie keer s. De sport houdt de vrouwelijke vorm.',
        },
        {
          say: 'En de nieuwe baas van de bond, hoe noem ik haar?',
          options: ['De nieuwe directrice van de bond.', 'De nieuwe directeur van de bond.'],
          right: 1,
          fix: 'directrice → directeur (stijlgids)',
          why: 'Allebei goed Nederlands, maar de stijlgids kiest de neutrale functienaam. Het voornaamwoord doet de rest: zij.',
        },
        {
          say: 'Wie leidde de ploeg op het veld?',
          options: ['De aanvoerdster was Lotte.', 'De aanvoerster was Lotte.'],
          right: 1,
          fix: 'aanvoerdster → aanvoerster',
          why: '-ster plakt aan de stam aanvoer. De d van aanvoerder hoort bij -der en komt niet mee.',
        },
        {
          say: 'En die man die de ijsbaan verhuurt aan de club?',
          options: ['De verhuurder van de baan.', 'De verhuurer van de baan.'],
          right: 0,
          fix: 'verhuurer → verhuurder',
          why: 'Beklemtoonde stam op r: -der.',
        },
      ],
      bye: 'Top, de kop staat. Dank je!',
    },
    {
      kind: 'proofread',
      id: 'nalezen-namen',
      prompt: 'Lees het bericht na',
      intro: 'Er zitten vier foute persoonsnamen in. Tik ze aan.',
      tokens: [
        { t: 'De' },
        { t: 'schaatster', fix: 'schaatsster', why: 'schaats + ster: drie keer s.' },
        { t: 'en' },
        { t: 'de' },
        { t: 'wielrenster' },
        { t: 'kregen' },
        { t: 'een' },
        { t: 'prijs' },
        { t: 'van' },
        { t: 'de' },
        { t: 'verhuurer', fix: 'verhuurder', why: 'Beklemtoonde stam op r: -der.' },
        { t: 'van' },
        { t: 'de' },
        { t: 'baan,' },
        { t: 'een' },
        { t: 'fanatieke' },
        { t: 'wandeler', fix: 'wandelaar', why: 'WAN-del: zwakke lettergreep op l, dus -aar.' },
        { t: 'en' },
        { t: 'dichtster.', fix: 'dichteres.', why: 'dichter hoort bij de oude -er-woorden die -es krijgen: dichteres.' },
      ],
      done: { title: 'Vier gevonden', text: 'schaatsster, verhuurder, wandelaar, dichteres: vier regels in één zin. wielrenster was goed: wielren + ster.' },
    },
    {
      kind: 'swipe',
      id: 'namen-waar',
      prompt: 'Klopt deze zin?',
      cards: [
        { t: 'Volgens Rappaport Hovav en Levin noemt Engels -er het externe argument.', ok: true, why: 'Het onderwerp dat de handeling in gang zet.' },
        {
          t: 'Het Nederlands maakt geen -er-woorden van werkwoorden als aankomen en blijven.',
          ok: false,
          fix: 'nieuwkomer en thuisblijver bestaan',
          why: 'Het Nederlands is soepeler dan de Engelse theorie voorspelt.',
        },
        { t: 'Baxter en Webster zijn oude vrouwelijke vormen met -ster.', ok: true, why: 'bæcestre en webbestre: een vrouw die bakt, een vrouw die weeft.' },
        { t: 'Dievegge is het enige Nederlandse woord met het achtervoegsel -egge.', ok: true, why: 'De andere -egge-woorden zijn verdwenen.' },
        {
          t: 'Gygax en collega’s vonden dat Engelse lezers bij beroepsnamen het stereotype volgen.',
          ok: true,
          why: 'Zonder grammaticaal geslacht beslist het beeld van het beroep.',
        },
        {
          t: 'Delftenaar volgt de gewone klankregel voor -er en -aar.',
          ok: false,
          fix: 'Delft eindigt beklemtoond en krijgt toch -enaar',
          why: 'Een uitzondering die je per woord leert.',
        },
        { t: 'Volgens Jakobson is de vrouwelijke vorm de gemarkeerde.', ok: true, why: 'Ze zegt iets extra’s; de mannelijke vorm is ook de algemene.' },
      ],
    },
  ],
};
