import type { LessonInput } from '../../schema';

/**
 * Bachelorles voor "Het betekenisvolle woorddeel": de spelling van samenstellingen en afleidingen.
 * Aaneen (en de Engelse ziekte), koppelteken bij klinkerbotsing tegenover trema, bij hoofdletters,
 * cijfers, letters en afkortingen, bij ex-/oud-/niet-, bij nevenschikking, woordgroepen als eerste
 * deel, en de gevallen waarin spatie of streepje de betekenis verandert. De tussenklank (d10) en de
 * basis van trema en apostrof (niveau letter) worden hier niet herhaald.
 */
export const LES_D23: LessonInput = {
  id: 'd23',
  stage: 'bachelor',
  domain: 'morf',
  also: ['orth', 'sem'],
  title: 'Aaneen, met streepje of los?',
  skill: 'Spelling',
  icon: 'a-b',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Eén begrip, één woord',
      panels: [
        {
          text: 'De grondregel van de Nederlandse spelling is simpel en streng: wat één woord is, schrijf je als één woord. Een samenstelling is één woord, hoe lang ook, en hoe Engels het eerste deel ook klinkt. *Privacy verklaring* met een spatie is fout, en een streepje is hier overbodig: dat zet je alleen als een regel erom vraagt. In de les over samenstellingen zag je de toets: één hoofdklemtoon, en je kunt er niets tussen zetten. Hier leer je wat er daarna komt: aaneen, met een streepje, of toch los. Begin met de voorwerpen. Iemand schreef hun naam los.',
          rule: 'Een samenstelling schrijf je aaneen. Een koppelteken komt er alleen als een regel dat vraagt.',
          cast: {
            q: 'Tik wat de schrijver bedoelt, kies dan de spelling',
            rounds: [
              {
                text: 'de computer muis',
                ask: 'Tik wat de schrijver bedoelt',
                cast: ['computermuis', 'muis', 'boek', 'glas'],
                answer: ['computermuis'],
                then: { q: 'Hoe schrijf je het?', options: ['computermuis', 'computer muis', 'computer-muis'], answer: 'computermuis' },
                note: 'Eén ding, één woord. De spatie is de Engelse ziekte; een streepje is niet nodig, want r en m botsen niet.',
              },
              {
                text: 'een zonne bloem',
                ask: 'Tik wat bedoeld is',
                cast: ['zonnebloem', 'zon', 'bloem', 'bloempot'],
                answer: ['zonnebloem'],
                then: { q: 'Welke spelling klopt?', options: ['zonnebloem', 'zonne-bloem', 'zonne bloem'], answer: 'zonnebloem' },
                note: 'zonne + bloem: e en b botsen niet, dus geen streepje. Vergelijk zonne-energie, waar e op e stuit.',
              },
              {
                text: 'het hang slot',
                ask: 'Tik wat bedoeld is',
                cast: ['hangslot', 'kasteel', 'mes', 'huis'],
                answer: ['hangslot'],
                then: { q: 'Hoe schrijf je het?', options: ['hangslot', 'hang slot', 'hang-slot'], answer: 'hangslot' },
                note: 'Werkwoordstam plus zelfstandig naamwoord: aaneen, net als zwembad en leesbril.',
              },
              {
                text: 'de rood borst',
                ask: 'Tik de vogel die bedoeld is',
                cast: ['roodborst', 'mus', 'kip', 'pinguin'],
                answer: ['roodborst'],
                then: { q: 'Hoe schrijf je het?', options: ['roodborst', 'rood borst', 'rode borst'], answer: 'roodborst' },
                note: 'Eén begrip, één woord: roodborst. Een rode borst, los, is een borst die rood is. De spatie verandert hier de betekenis.',
              },
            ],
            note: 'Vier keer aaneen, en nergens een streepje. Pas als klinkers botsen of een ander teken meespeelt, komt het koppelteken erbij.',
          },
        },
        {
          text: 'Botsen er klinkers op de naad, dan hangt het teken af van de bouw van het woord. Op de grens tussen twee woorden van een samenstelling komt een koppelteken: *zee-egel*, *auto-ongeluk*, *mede-eigenaar*. Binnen één woord, dus in een afleiding of een verbogen vorm, komt een trema op de tweede klinker: *zeeën*, *geïnd*, *beïnvloeden*, *coördinatie*. Het streepje zegt: hier eindigt een woord. Het trema zegt: hier begint een nieuwe lettergreep, binnen hetzelfde woord. Sinds 1995 geldt dat ook voor *zo-even*, *mee-eten* en *toe-eigenen*: die tellen als samenstellingen.',
          rule: 'Klinkerbotsing op een woordgrens: koppelteken (*zee-egel*). Binnen een woord: trema (*zeeën*, *geïnd*).',
          paradigm: {
            q: 'Kies de goede vorm',
            cols: ['vorm'],
            rows: [
              { label: 'zee + en (meervoud)', cells: [{ fill: 'zeeën', hint: 'Een uitgang: binnen het woord, dus trema.' }] },
              { label: 'zee + egel', cells: [{ fill: 'zee-egel', hint: 'Twee woorden: koppelteken.' }] },
              { label: 'mede + eigenaar', cells: [{ fill: 'mede-eigenaar', hint: 'Een samenstelling: koppelteken op de grens.' }] },
              { label: 'ge + ind', cells: [{ fill: 'geïnd', hint: 'Een voorvoegsel: binnen het woord, dus trema.' }] },
              { label: 'co + ordinatie', cells: [{ fill: 'coördinatie', hint: 'Een geleerd woord met een Latijns voorvoegsel: trema.' }] },
              { label: 'na + apen', cells: [{ fill: 'na-apen', hint: 'Na en apen zijn twee woorden: koppelteken.' }] },
            ],
            extra: ['zeeen', 'zeeëgel', 'medeëigenaar', 'ge-ind'],
            note: 'Drie keer een streepje op een woordgrens, drie keer een trema binnen het woord. Het teken verraadt de bouw.',
          },
          deep: {
            q: 'En als niemand het verkeerd kan lezen?',
            a: 'Dan komt er geen teken. *Politieagent*, *radioactief* en *theater*: ie + a, o + a en e + a lees je toch niet als één klank. De regel kijkt niet naar de letters alleen, maar naar wat een lezer ermee zou doen. In De lettergreep zag je dezelfde toets.',
          },
        },
        {
          text: 'Een koppelteken komt er ook als een deel van het woord uit de toon valt. Een hoofdletter midden in een woord, bijvoorbeeld: *Noord-Hollands*, *anti-Amerikaans*, *on-Nederlands*. Een cijfer, een losse letter, een symbool of een afkorting: *3D-printer*, *A4-formaat*, *T-shirt*, *cd-speler*, *tv-programma*, *65-plusser*. Het streepje houdt het vreemde stuk apart, zodat het niet in het woord oplost. Let op het verschil met een afleiding: *tv’tje* en *A4’tje* krijgen een apostrof, geen streepje, want daar plakt een uitgang aan de afkorting.',
          rule: 'Hoofdletter, cijfer, letter, symbool of afkorting in een samenstelling: koppelteken (*3D-printer*, *Noord-Hollands*).',
          lab: {
            label: 'Tik een combinatie',
            chips: [
              {
                k: 'anti + Amerikaans',
                out: 'anti-Amerikaans',
                note: 'Een hoofdletter midden in het woord: streepje. Zonder hoofdletter plakt anti- gewoon vast: antibiotica.',
              },
              { k: 'Noord + Hollands', out: 'Noord-Hollands', note: 'Twee hoofdletters: streepje, ook in de afleiding Noord-Hollander.' },
              { k: '3D + printer', out: '3D-printer', note: 'Cijfer en letter vooraan: streepje. De hoofdletter D blijft staan.' },
              { k: 'tv + programma', out: 'tv-programma', note: 'Een afkorting als eerste deel: streepje. Vergelijk tv’tje, met een apostrof.' },
              { k: 'A4 + tje', out: 'A4’tje', note: 'Een uitgang, geen woord: dan een apostrof. A4-tje is fout.' },
            ],
          },
          deep: {
            q: 'Waarom A4’tje en niet A4-tje?',
            a: 'Omdat *-tje* geen woord is. Het koppelteken staat op een grens tussen woorden; een uitgang hoort bij het woord zelf. Bij een afkorting of een cijfer houdt de apostrof de uitgang leesbaar: *tv’s*, *cd’tje*, *A4’tje*, *vwo’er*. Zie ook Accent, apostrof, koppelteken op het niveau van de letter.',
          },
        },
      ],
    },
    {
      kind: 'speed',
      id: 'aaneen-los',
      prompt: 'Aan elkaar of los?',
      intro: 'Eén samenstelling, of twee woorden in een woordgroep?',
      seconds: 40,
      items: [
        { a: 'privacy', b: 'verklaring', joined: true, tip: 'privacyverklaring: één woord, ook met een Engels eerste deel.' },
        { a: 'rood', b: 'borst', joined: true, tip: 'roodborst: de vogel.' },
        { a: 'rode', b: 'borst', joined: false, tip: 'een rode borst: een borst die rood is.' },
        { a: 'zwem', b: 'bad', joined: true, tip: 'zwembad: werkwoordstam plus naamwoord.' },
        { a: 'heel', b: 'erg', joined: false, tip: 'heel erg: twee bijwoorden, een woordgroep.' },
        { a: 'tweedehands', b: 'auto', joined: true, tip: 'tweedehandsauto: tweedehands is één woord, en de auto plakt eraan.' },
        { a: 'lange', b: 'afstand', joined: false, tip: 'een lange afstand: bijvoeglijk naamwoord plus naamwoord, een woordgroep.' },
        { a: 'online', b: 'winkelen', joined: false, tip: 'online winkelen: een werkwoord met een bijwoord ervoor, los.' },
      ],
    },
    {
      kind: 'sort',
      id: 'teken',
      prompt: 'Welk teken komt er op de naad?',
      buckets: ['koppelteken', 'trema', 'apostrof', 'geen teken'],
      items: [
        { t: 'zee + egel', b: 0 },
        { t: 'zee + en', b: 1 },
        { t: 'tv + gids', b: 0 },
        { t: 'tv + tje', b: 2 },
        { t: 'mede + eigenaar', b: 0 },
        { t: 'ge + upload', b: 1 },
        { t: 'politie + agent', b: 3 },
        { t: 'radio + actief', b: 3 },
        { t: 'Noord + Hollands', b: 0 },
        { t: 'co + ordinatie', b: 1 },
      ],
      why: 'Koppelteken op een woordgrens bij botsing, afkorting of hoofdletter. Trema binnen een woord: zeeën, geüpload, coördinatie. Apostrof bij een uitgang achter een afkorting: tv’tje. Geen teken als niemand het verkeerd leest: politieagent, radioactief.',
    },
    {
      kind: 'fix',
      id: 'botsing',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Na het autoongeluk bleef de zee-egel ongedeerd.',
      wrong: 2,
      answer: 'auto-ongeluk',
      why: 'Twee woorden met o tegen o: een koppelteken. Zee-egel stond al goed.',
    },
    {
      kind: 'type',
      id: 'anti',
      prompt: 'Typ de afleiding: anti + Amerikaans, in de verbogen vorm.',
      before: 'De demonstranten droegen',
      after: 'leuzen.',
      hint: 'anti…',
      answer: 'anti-Amerikaanse',
      why: 'Een hoofdletter midden in het woord vraagt een koppelteken, ook in de verbogen vorm: anti-Amerikaanse.',
    },
    {
      kind: 'explain',
      id: 'verdieping',
      title: 'Streepjes met betekenis',
      panels: [
        {
          text: 'Een vaste groep eerste delen krijgt altijd een koppelteken: *ex-*, *oud-*, *niet-*, *non-*, *bijna-*, *kandidaat-*, *aspirant-*, *adjunct-*, *interim-*, *chef-*, *collega-*, *leerling-*, *meester-*, *Sint-*. Ze geven een nadere bepaling van het tweede deel: een *oud-minister* is een minister van vroeger, een *niet-roker* iemand die niet rookt. Het streepje houdt ze uit elkaar van de gewone woordgroep. Een *oude minister* is een minister op leeftijd, en *niet roken* is een verbod. Hier beslist het streepje dus mee over de betekenis.',
          rule: '*ex-*, *oud-*, *niet-*, *non-*, *bijna-*, *kandidaat-* en hun vrienden: altijd een koppelteken (*oud-minister*, *niet-roker*).',
          lab: {
            label: 'Tik een vorm',
            chips: [
              { k: 'oud-leerling', out: 'iemand die vroeger leerling was', note: 'Het streepje: oud- als bepaling, één begrip.' },
              { k: 'oude leerling', out: 'een leerling op leeftijd', note: 'Een gewone woordgroep: het bijvoeglijk naamwoord is gebogen en staat los.' },
              { k: 'niet-roker', out: 'iemand die niet rookt', note: 'Een zelfstandig naamwoord met niet- ervoor: streepje.' },
              { k: 'niet roken', out: 'een verbod', note: 'Niet bij een werkwoord: gewoon los.' },
              { k: 'bijna-doodervaring', out: 'een ervaring van bijna dood zijn', note: 'bijna- als eerste deel: streepje, en daarna plakt ervaring eraan.' },
            ],
          },
          deep: {
            q: 'Waarom zijn dit niet gewoon voorvoegsels?',
            a: 'Omdat ze ook los voorkomen (*oud*, *niet*, *chef*) en als woord aanvoelen. De spelling behandelt ze als het eerste deel van een samenstelling, maar met een vast streepje, zodat je *oud-minister* niet als *oudminister* hoeft te lezen. Het meervoud gaat naar het hoofd: *oud-ministers*, zoals je bij Wie is de baas in het woord? zag.',
          },
        },
        {
          text: 'Zijn twee delen gelijkwaardig, dan komt er een koppelteken tussen: *zwart-wit*, *man-vrouw*, *hotel-restaurant*, *Nederlands-Belgisch*. Je kunt ze in principe omdraaien, en het streepje betekent ‘en’. Komt er nog een deel achter, dan plakt dat gewoon vast: *zwart-witfoto*, *woon-werkverkeer*, *kop-staartbotsing*, *zit-slaapbank*. Bij kleuren beslist de betekenis. *Geel-groen* zijn twee kleuren naast elkaar; *geelgroen* is één kleur, een groen dat naar geel neigt. Daar staat het hoofd gewoon rechts. Tik de woorden waarin de delen gelijkwaardig zijn.',
          rule: 'Gelijkwaardige delen: koppelteken ertussen (*zwart-wit*), en het volgende deel plakt eraan (*zwart-witfoto*).',
          mark: {
            q: 'Tik de samenstellingen waarin de delen gelijkwaardig zijn',
            sentence: 'zwart-witfoto geelgroen woon-werkverkeer roodbruin kop-staartbotsing sneeuwwit',
            targets: [0, 2, 4],
            note: 'zwart én wit, wonen én werken, kop én staart: gelijkwaardig, met een streepje. Geelgroen en roodbruin zijn één kleur met het hoofd rechts, en sneeuwwit is wit als sneeuw.',
          },
          deep: {
            q: 'Wat is nevenschikking in een woord eigenlijk?',
            a: 'Taalkundigen noemen zo’n samenstelling *coördinatief* of, naar het Sanskriet, een *dvandva*. Beide delen zijn even belangrijk voor de betekenis: een *zangeres-actrice* is zangeres én actrice. Voor de vorm geldt toch de rechterhoofdregel: het meervoud komt achteraan, *zangeres-actrices*. Zie Samenstellingen zonder einde.',
          },
        },
        {
          text: 'Soms is het eerste deel zelf een woordgroep. Bestaat die uit een bijvoeglijk naamwoord of telwoord met een zelfstandig naamwoord, dan schrijf je alles aaneen: *langeafstandsloper*, *hogesnelheidstrein*, *kortetermijngeheugen*, *grotestedenbeleid*, *eerstejaarsstudent*. Door het aaneenschrijven laat je zien dat *lange* bij *afstand* hoort, niet bij *loper*: een *lange afstandsloper* is een lange loper. Is de groep van een ander soort, met een werkwoord of voegwoord erin, dan houden koppeltekens haar bij elkaar: *doe-het-zelfzaak*, *kant-en-klaarmaaltijd* (zie Een woord is een vrije vorm). Bouw de loper.',
          rule: 'Woordgroep van bijvoeglijk naamwoord + zelfstandig naamwoord als eerste deel: alles aaneen (*langeafstandsloper*).',
          bracket: {
            q: 'Bouw het woord van binnen naar buiten',
            tree: '[[lange afstand] loper]',
            words: true,
            nodes: [
              { w: 'lange afstand', cat: 'woordgroep', note: 'Bijvoeglijk naamwoord plus naamwoord: een gewone groep uit de zinsbouw.' },
              {
                w: 'lange afstand loper',
                form: 'langeafstandsloper',
                cat: 'zn (samenstelling)',
                note: 'De groep wordt het eerste deel, met een tussen-s, en alles plakt aaneen. Nu is de afstand lang, niet de loper.',
              },
            ],
            traps: [{ w: 'afstand loper', note: 'Dan zou lange bij de loper horen: een lange afstandsloper, een lange persoon. Bedoeld is de lange afstand.' }],
            note: '[[lange afstand] loper]: eerst de groep, dan het hoofd. De spelling zonder spatie volgt de boom.',
          },
          deep: {
            q: 'En rodekool naast rode kool?',
            a: 'Allebei goed, sinds 2015. *Rodekool* behandelt de groente als één begrip, *rode kool* beschrijft een kool die rood is; een betekenisverschil is er nauwelijks, en de Woordenlijst laat de keuze. Bij *hogeschool* ligt het anders: een *hogeschool* is een onderwijsinstelling, een *hoge school* een school die hoog is.',
          },
        },
        {
          text: 'Ook buiten de samenstelling kan de spatie betekenis dragen. *Ten slotte* is ‘als laatste’, *tenslotte* is ‘per slot van rekening’. *Ten minste* is ‘minimaal’, *tenminste* ‘in elk geval’. *Te veel* is ‘meer dan goed is’, *het teveel* is ‘het overschot’. *Al lang* is ‘sinds lange tijd’, *allang* is ‘heus wel, zeker’. In elk paar is de losse vorm letterlijk en de aaneengeschreven vorm een eigen woord met een eigen betekenis. Kies de vorm die de zin vraagt.',
          rule: 'Los is letterlijk (*ten slotte*: als laatste), aaneen is een eigen woord (*tenslotte*: per slot van rekening).',
          quiz: {
            q: 'Welke zin zegt dat hij minimaal drie uur wachtte?',
            options: ['Hij wachtte ten minste drie uur.', 'Hij wachtte tenminste drie uur.'],
            answer: 'Hij wachtte ten minste drie uur.',
            why: 'Ten minste, los, is minimaal. Tenminste, aaneen, is in elk geval: Hij wachtte, tenminste, dat zei hij.',
          },
        },
      ],
    },
    {
      kind: 'chat',
      id: 'app-streepjes',
      prompt: 'App met je studiegenoot',
      intro: 'Kies telkens het antwoord met de goede spelling.',
      contact: { name: 'Noor', role: 'je studiegenoot', initials: 'N' },
      rounds: [
        {
          say: 'Wie sprak er gisteren op het congres?',
          options: ['Een oud-minister, die van het vorige kabinet.', 'Een oude minister, die van het vorige kabinet.'],
          right: 0,
          fix: 'oude minister → oud-minister',
          why: 'Van vroeger: oud- met streepje. Een oude minister is op leeftijd.',
        },
        {
          say: 'Heb je de foto’s al gezien?',
          options: ['Ja, mooie zwart-wit foto’s.', 'Ja, mooie zwart-witfoto’s.'],
          right: 1,
          fix: 'zwart-wit foto’s → zwart-witfoto’s',
          why: 'Na de gelijkwaardige delen plakt foto gewoon vast.',
        },
        {
          say: 'Hoe ga je morgen naar Antwerpen?',
          options: ['Met de hogesnelheidstrein.', 'Met de hoge snelheidstrein.'],
          right: 0,
          fix: 'hoge snelheidstrein → hogesnelheidstrein',
          why: 'De woordgroep hoge snelheid is het eerste deel: alles aaneen. Een hoge snelheidstrein zou een hoge trein zijn.',
        },
        {
          say: 'Zit er een roker in jullie coupé? Ik hoop het niet.',
          options: ['Nee hoor, alleen niet-rokers.', 'Nee hoor, alleen niet rokers.'],
          right: 0,
          fix: 'niet rokers → niet-rokers',
          why: 'niet- voor een zelfstandig naamwoord: streepje.',
        },
      ],
      bye: 'Top. Tot morgen op het perron!',
    },
    {
      kind: 'proofread',
      id: 'redactie',
      prompt: 'Lees het verslag na',
      intro: 'Er staan vijf fouten in: spaties, streepjes en tekens. Tik ze aan.',
      header: { to: 'de redactie', subject: 'Verslag van de studiereis' },
      tokens: [
        { t: 'Onze' },
        { t: 'studie reis', fix: 'studiereis', why: 'Een samenstelling: aaneen.' },
        { t: 'naar' },
        { t: 'Noord-Holland' },
        { t: 'begon' },
        { t: 'met' },
        { t: 'een' },
        { t: 'autoongeluk', fix: 'auto-ongeluk', why: 'o tegen o op een woordgrens: koppelteken.' },
        { t: 'zonder' },
        { t: 'gewonden.' },
        { t: 'De' },
        { t: 'oud-burgemeester' },
        { t: 'ontving' },
        { t: 'ons,' },
        { t: 'en' },
        { t: 'een' },
        { t: 'ex collega', fix: 'ex-collega', why: 'ex- krijgt altijd een koppelteken.' },
        { t: 'van' },
        { t: 'onze' },
        { t: 'docent' },
        { t: 'gaf' },
        { t: 'een' },
        { t: 'lezing' },
        { t: 'over' },
        { t: 'het' },
        { t: 'kortetermijngeheugen.' },
        { t: 'Daarna' },
        { t: 'fotografeerden' },
        { t: 'we' },
        { t: 'zeeegels', fix: 'zee-egels', why: 'e tegen e op een woordgrens: koppelteken, geen trema.' },
        { t: 'met' },
        { t: 'een' },
        { t: '3D-camera' },
        { t: 'en' },
        { t: 'schreven' },
        { t: 'we' },
        { t: 'onze' },
        { t: 'ideeën' },
        { t: 'op' },
        { t: 'een' },
        { t: 'A4-tje.', fix: 'A4’tje.', why: 'Een uitgang achter een afkorting: apostrof, geen streepje.' },
      ],
      done: {
        title: 'Vijf gevonden',
        text: 'studiereis aaneen, auto-ongeluk en zee-egels met een streepje op de botsing, ex-collega met zijn vaste streepje, en A4’tje met een apostrof, want -tje is een uitgang. Noord-Holland, oud-burgemeester, kortetermijngeheugen, 3D-camera en ideeën stonden goed.',
      },
    },
    {
      kind: 'bet',
      id: 'knorper',
      prompt: 'Een verzonnen beroep: knorper. Iemand die vroeger knorper was, is een…',
      options: ['ex-knorper', 'exknorper', 'ex knorper'],
      answer: 'ex-knorper',
      why: 'ex- krijgt altijd een koppelteken, ook voor een woord dat niemand kent.',
    },
    {
      kind: 'rewrite',
      id: 'hst',
      prompt: 'Maak er één samenstelling van.',
      source: 'een trein die met hoge snelheid rijdt',
      accept: ['een hogesnelheidstrein', 'hogesnelheidstrein'],
      why: 'De woordgroep hoge snelheid wordt het eerste deel, met een tussen-s, en alles plakt aaneen.',
    },
    {
      kind: 'type',
      id: 'vlag',
      prompt: 'Typ de kleur van een vlag met twee banen, rood en wit.',
      before: 'De vlag is',
      after: '.',
      hint: 'rood + wit',
      answer: 'rood-wit',
      why: 'Twee gelijkwaardige kleuren naast elkaar: een koppelteken. Aaneen zou het één mengkleur zijn, zoals roodbruin.',
    },
    {
      kind: 'explain',
      id: 'onderzoek',
      title: 'Wat het streepje voor de lezer doet',
      panels: [
        {
          text: 'Een koppelteken is soms niet verplicht, maar wel toegestaan. De spelling laat het toe als een samenstelling anders moeilijk leesbaar is of op twee manieren gelezen kan worden: *stress-situatie* naast *stresssituatie*, *grote-stedenbeleid* naast *grotestedenbeleid*. Het streepje laat dan de bouw zien. Kijk naar *massagebed*: een bed voor massage, of een gebed van een massa mensen? Beide lezingen zijn echte woorden. Zet het streepje waar de masseur het wil.',
          rule: 'Een facultatief koppelteken mag als het woord anders moeilijk leesbaar of dubbelzinnig is: *massage-bed*.',
          split: {
            q: 'Knip het woord zodat het een bed voor massage wordt',
            word: 'massagebed',
            answer: 'massage-bed',
            note: 'Zonder streepje kun je massa-gebed lezen. Verplicht is het streepje hier niet, want er botsen geen klinkers. Maar het helpt de lezer, en dat mag.',
          },
          deep: {
            q: 'Zijn er meer van zulke woorden?',
            a: '*Bommelding* (een bom-melding, of een bommel-ding), *valkuil* (een val-kuil, of een valk-uil). Meestal redt de context het. Een streepje zet je alleen als je de verkeerde lezing echt verwacht. Zie ook Woordbomen, waar het streepje in een lange samenstelling op de hoogste knoop komt.',
          },
        },
        {
          text: 'Helpt een spatie de lezer eigenlijk? Je zou denken van wel: *privacy verklaring* is in één oogopslag te knippen. Albrecht Inhoff, Ralph Radach en Dieter Heller (2000) maten oogbewegingen bij Duitse samenstellingen, met en zonder ingevoegde spatie. Met spatie vonden de ogen de delen sneller, maar het samenvoegen tot één betekenis duurde langer: de lezer moest de stukken daarna weer bij elkaar zoeken. De spatie helpt dus bij het knippen en hindert bij het begrijpen. Precies daarom schrijft het Nederlands een samenstelling als één blok: de vorm zegt dat het één begrip is.',
          rule: 'Een spatie in een samenstelling versnelt het knippen, maar vertraagt het begrijpen.',
          quiz: {
            q: 'Wat vonden Inhoff en collega’s bij samenstellingen met een ingevoegde spatie?',
            options: ['Sneller geknipt, trager begrepen', 'Sneller geknipt én sneller begrepen', 'Geen enkel verschil'],
            answer: 'Sneller geknipt, trager begrepen',
            why: 'De spatie maakt de delen zichtbaar, maar de lezer moet ze daarna weer samenvoegen.',
          },
          deep: {
            q: 'Waar komt de Engelse ziekte dan vandaan?',
            a: 'Uit meer dan één kracht tegelijk: het Engels, waar *washing machine* los staat; spellingcontrole, die een lang, nieuw woord rood onderstreept; en de wens van de schrijver om in een lange samenstelling de grens te laten zien. Voor die laatste wens is een facultatief koppelteken het nette middel: *stress-situatie*, nooit een spatie.',
          },
        },
        {
          text: 'Waarom kreeg *zoëven* in 1995 een streepje? Omdat de spelling kiest voor *gelijkvormigheid*: een woorddeel ziet er overal hetzelfde uit. In *zo-even* blijven *zo* en *even* herkenbaar, net als in *mee-eten* en *toe-eigenen*. Een trema zou ze laten versmelten tot één woordbeeld. In een afleiding is dat juist de bedoeling: *reünie* en *coöperatie* zijn geen twee woorden, dus daar blijft het trema. Het teken volgt zo de bouw. Een streepje laat de delen staan, een trema bindt. Tik de samenstellingen.',
          rule: 'Gelijkvormigheid: de delen van een samenstelling blijven herkenbaar, daarom een streepje en geen trema (*zo-even*).',
          mark: {
            q: 'Tik de samenstellingen: die kregen in 1995 een koppelteken in plaats van het trema',
            sentence: 'zo-even reünie mee-eten coöperatie toe-eigenen ideeën',
            targets: [0, 2, 4],
            note: 'zo-even, mee-eten en toe-eigenen tellen als samenstellingen. Reünie, coöperatie en ideeën zijn afleidingen of verbogen vormen: daar bleef het trema.',
          },
          deep: {
            q: 'Welke beginselen hanteert de Woordenlijst?',
            a: 'Drie: de standaarduitspraak (je schrijft wat je hoort), de gelijkvormigheid (een woorddeel ziet er overal hetzelfde uit) en de etymologie (de herkomst telt mee). De regels voor koppelteken en trema zijn vooral gelijkvormigheid: ze houden de bouw van het woord zichtbaar.',
          },
        },
      ],
    },
    {
      kind: 'ambiguity',
      id: 'massagebed',
      prompt: 'Eén woord, twee bomen',
      intro: 'Kies een lezing en zoek de zin die alleen dát kan betekenen.',
      sentence: 'Het programma begint met een massagebed.',
      meanings: [
        {
          id: 'bed',
          label: 'Een bed voor massage',
          highlight: ['massagebed'],
          right: 'Klopt. Massage-bed: het streepje op de hoogste knoop maakt de lezing zeker.',
        },
        {
          id: 'gebed',
          label: 'Een gebed van een massa mensen',
          highlight: ['massagebed'],
          right: 'Klopt. Massa-gebed: ook deze lezing is een echt woord, en het streepje kiest hem.',
        },
      ],
      options: [
        { t: 'Het programma begint met een massage-bed.', fits: 'bed' },
        { t: 'Het programma begint met een massa-gebed.', fits: 'gebed' },
        { t: 'Het programma begint met een lang massagebed.', fits: null, note: 'Lang past bij allebei: het streepje ontbreekt nog.' },
      ],
      done: {
        title: 'Eén woord, twee bomen',
        text: 'Niet verplicht, wel verstandig: een facultatief koppelteken zet de lezer op de goede boom.',
      },
    },
    {
      kind: 'highlight',
      id: 'drie-stiften',
      prompt: 'Kleur elk paar met de spelling die het vraagt',
      intro: 'Eén woord aaneen, een koppelteken, of twee losse woorden?',
      pens: [
        { id: 'aaneen', label: 'aaneen', tag: 'één woord', ask: 'Is het één samenstelling zonder botsing of bijzonder deel?', accent: 'blue' },
        {
          id: 'streep',
          label: 'koppelteken',
          tag: 'streepje',
          ask: 'Botsen er klinkers, of zit er een hoofdletter, afkorting, ex- of nevenschikking in?',
          accent: 'orange',
        },
        { id: 'los', label: 'los', tag: 'woordgroep', ask: 'Zijn het twee woorden in een woordgroep?', accent: 'purple' },
      ],
      words: [
        { t: 'privacy+verklaring', role: 'aaneen' },
        { t: 'auto+ongeluk', role: 'streep' },
        { t: 'heel+groot', role: 'los' },
        { t: 'oud+minister', role: 'streep' },
        { t: 'zwem+bad', role: 'aaneen' },
        { t: 'tv+gids', role: 'streep' },
        { t: 'online+winkelen', role: 'los' },
        { t: 'Noord+Hollands', role: 'streep' },
        { t: 'tweedehands+auto', role: 'aaneen' },
        { t: 'niet+roken', role: 'los' },
        { t: 'radio+actief', role: 'aaneen' },
        { t: 'zwart+wit', role: 'streep' },
      ],
      done: {
        title: 'Drie stiften, drie regels',
        text: 'Aaneen is de grondregel. Het streepje komt bij botsing, hoofdletter, afkorting, ex- en nevenschikking. Los is alleen de woordgroep.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ de zin.',
      sentence: 'De oud-minister kocht een cd-speler en een zwart-witfoto in Noord-Holland.',
      right: 'Goed: oud- met streepje, cd- en zwart-wit met streepje en foto eraan vast, Noord-Holland met hoofdletters en streepje.',
      wrong: 'Let op de streepjes: oud-minister, cd-speler, zwart-witfoto en Noord-Holland. Foto plakt aan zwart-wit vast.',
    },
    {
      kind: 'swipe',
      id: 'streep-waar',
      prompt: 'Klopt deze zin?',
      cards: [
        {
          t: 'Een samenstelling met een Engels eerste deel mag je los schrijven.',
          ok: false,
          fix: 'ook dan aaneen: privacyverklaring',
          why: 'De herkomst van het eerste deel verandert de regel niet.',
        },
        { t: 'Bij klinkerbotsing op een woordgrens komt een koppelteken, binnen een woord een trema.', ok: true, why: 'zee-egel tegenover zeeën.' },
        {
          t: 'A4-tje is de juiste spelling.',
          ok: false,
          fix: 'A4’tje',
          why: 'Een uitgang achter een afkorting krijgt een apostrof; A4-formaat krijgt wel een streepje.',
        },
        {
          t: 'Geel-groen en geelgroen betekenen hetzelfde.',
          ok: false,
          fix: 'twee kleuren tegenover één mengkleur',
          why: 'Het streepje betekent en; aaneen staat het hoofd rechts.',
        },
        { t: 'Een facultatief koppelteken mag als een samenstelling anders dubbelzinnig is.', ok: true, why: 'massage-bed, stress-situatie.' },
        {
          t: 'Inhoff en collega’s vonden dat een spatie in een samenstelling het begrijpen versnelt.',
          ok: false,
          fix: 'het knippen versnelt, het begrijpen vertraagt',
          why: 'De lezer moet de losse stukken daarna weer samenvoegen.',
        },
        { t: 'Rodekool en rode kool zijn sinds 2015 allebei goed.', ok: true, why: 'De Woordenlijst laat de keuze; het betekenisverschil is klein.' },
      ],
    },
    {
      kind: 'bet',
      id: 'kwaai',
      prompt: 'Een nieuw dier, de ‘kwaai’, legt eieren. Hoe schrijf je kwaai + ei?',
      options: ['kwaai-ei', 'kwaaiei', 'kwaai ei'],
      answer: 'kwaai-ei',
      why: 'i en e botsen op een woordgrens: koppelteken, net als in thee-ei. Ook bij een woord dat niemand kent.',
    },
  ],
};
