import type { LessonInput } from '../../schema';

/**
 * Masterles voor "Het betekenisvolle woorddeel", de laatste van het niveau: waar woordbouw en
 * zinsbouw elkaar raken. Synthetische samenstellingen en argumentvererving (aardappelschiller,
 * boekbespreking, het First Sister Principle), gebeurtenis- tegenover resultaatnominalisaties
 * (Grimshaw), samenstellingen met een woordgroep als eerste deel (blotevoetenpad, rodewijnglas,
 * langeafstandsloper) en de Lexicale-integriteitshypothese met haar lekken. Bouwt voort op d7
 * (het hoofd), d8 (woordbomen), d9 (samenstellingen) en d14 (de haakjesparadox). De eilandtoets
 * zelf en de woordgroepsamenstelling met een hele zin staan bij Het woord (w7) en De woordgroep.
 */
export const LES_D24: LessonInput = {
  id: 'd24',
  stage: 'master',
  domain: 'morf',
  also: ['syn', 'orth'],
  title: 'Vrachtwagenchauffeur en blotevoetenpad',
  skill: 'Woorden',
  icon: 'N+V',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Een werkwoord verstopt in het hoofd',
      panels: [
        {
          text: 'Een *aardappelschiller* schilt aardappels. Het hoofd *schiller* komt van een werkwoord, en *aardappel* is het lijdend voorwerp van dat werkwoord. Zo’n woord heet een *synthetische samenstelling*; bij Samenstellingen zonder einde zag je het al even. Het bijzondere: de relatie tussen de delen ligt vast. Bij *aardappelsoep* mag je raden wat soep met aardappels te maken heeft, bij *aardappelschiller* niet. Geert Booij (*The Morphology of Dutch*, 2002) beschrijft dat als *argumentvererving*: *-er* maakt van *schillen* een naamwoord, maar het naamwoord houdt de open plek van het werkwoord (een schiller van iets), en het eerste deel vult die plek. Bouw de boom.',
          rule: 'Synthetische samenstelling: het hoofd is afgeleid van een werkwoord, en het eerste deel vult een argument van dat werkwoord, meestal het lijdend voorwerp.',
          bracket: {
            q: 'Bouw: iets of iemand die aardappels schilt',
            tree: '[aardappel [schil er]]',
            nodes: [
              { w: 'schiler', form: 'schiller', cat: 'zn', note: '-er maakt van schillen een naamwoord, maar de open plek blijft: een schiller van iets.' },
              {
                w: 'aardappelschiler',
                form: 'aardappelschiller',
                cat: 'zn',
                note: 'aardappel vult de open plek: het lijdend voorwerp van schillen zit nu in het woord.',
              },
            ],
            traps: [
              {
                w: 'aardappelschil',
                note: 'Een bestaand woord, maar het betekent de schil van een aardappel: schil is daar een naamwoord, zonder werkwoord. De betekenis wil aardappel als lijdend voorwerp van schillen. Begin dus bij schil + er.',
              },
            ],
            note: '[aardappel [schil er]]: eerst het naamwoord met zijn open plek, dan het deel dat de plek vult. Daarom weet je zeker wat een aardappelschiller doet.',
          },
        },
        {
          text: 'Welke plek mag het eerste deel vullen? Thomas Roeper en Muffy Siegel (1978) gaven voor het Engels het *First Sister Principle*: wat in de zin direct naast het werkwoord staat, zijn eerste zuster, mag de samenstelling in. Het lijdend voorwerp dus (*truck driver*), of een bepaling (*thuiswerker*). Het onderwerp van een overgankelijk werkwoord niet: een *menseneter* eet mensen en is nooit een mens die eet. Bij *-er* kan dat ook niet anders, want de dader is de *-er* zelf. Heeft het werkwoord geen lijdend voorwerp, dan mag zijn enige argument wél vooraan: *vogelgezang* is het zingen van vogels.',
          rule: 'Het eerste deel is de eerste zuster van het werkwoord: het lijdend voorwerp of een bepaling. De dader van een overgankelijk werkwoord nooit.',
          lab: {
            label: 'Tik een woord',
            chips: [
              {
                k: 'menseneter',
                out: 'iets dat mensen eet',
                note: 'Mensen is het lijdend voorwerp van eten. De eter, de dader, is de -er en staat niet apart in het woord.',
              },
              {
                k: 'muizenvanger',
                out: 'iets dat muizen vangt',
                note: 'Een kat of een val. Nooit een muis die vangt: de dader van vangen mag het eerste deel niet zijn.',
              },
              {
                k: 'vogelgezang',
                out: 'het zingen van vogels',
                note: 'Zingen heeft hier geen lijdend voorwerp. Dan mag het onderwerp, het enige argument, wel vooraan.',
              },
              {
                k: 'thuiswerker',
                out: 'iemand die thuis werkt',
                note: 'Geen argument maar een bepaling van plaats. Ook die staat direct naast het werkwoord, dus Roeper en Siegel lieten haar toe.',
              },
              {
                k: 'vrachtwagenchauffeur',
                out: 'chauffeur van een vrachtwagen',
                note: 'Chauffeur is een Frans leenwoord; een werkwoord erbij gebruiken we nauwelijks. Toch heeft chauffeur een open plek, chauffeur van iets, en die vult vrachtwagen. Argumentvererving zonder werkwoord.',
              },
            ],
          },
          deep: {
            q: 'Waarom staat het lijdend voorwerp links?',
            a: 'In het Engels staat het lijdend voorwerp achter het werkwoord (*drive a truck*), en de samenstelling draait het om: *truck driver*. Het Nederlands hoeft niets om te draaien. In de bijzin staat het lijdend voorwerp al vlak vóór het werkwoord: *dat ze aardappels schilt*. De samenstelling *aardappelschiller* bewaart die volgorde. De eerste zuster is in het Nederlands letterlijk de linkerbuur.',
          },
        },
        {
          text: 'Nu op het toneel. In elk woord hieronder zit ergens een *-er*. Tik het ding aan dat het lijdend voorwerp van het werkwoord is. Soms is er niets te tikken: dan komt het hoofd niet van een werkwoord en is het een gewone samenstelling, ook al zit er ergens een *-er* in. Na het tikken volgt soms een vraag over wie of wat de *-er* zelf is.',
          rule: 'Alleen als het hoofd van een werkwoord komt, is er een open plek om te vullen.',
          cast: {
            q: 'Tik het lijdend voorwerp dat in het woord zit',
            rounds: [
              {
                text: 'visverkoper',
                ask: 'Tik wat er verkocht wordt',
                cast: ['vis', 'visser', 'boot', 'munten'],
                answer: ['vis'],
                then: { q: 'Wie verkoopt?', options: ['iemand buiten het woord: de -er', 'de vis', 'de munten'], answer: 'iemand buiten het woord: de -er' },
                note: 'Vis is het lijdend voorwerp van verkopen. De verkoper zelf staat niet als apart deel in het woord: dat is de -er.',
              },
              {
                text: 'eierkoker',
                ask: 'Tik wat er gekookt wordt',
                cast: ['ei', 'pan', 'kip', 'glas'],
                answer: ['ei'],
                then: {
                  q: 'Wat is de eierkoker zelf?',
                  options: ['het apparaat dat kookt', 'het ei', 'de kip die het ei legde'],
                  answer: 'het apparaat dat kookt',
                },
                note: 'Een -er hoeft geen mens te zijn: een eierkoker is een apparaat. Ook een ding kan de daderplek vullen.',
              },
              {
                text: 'vissersboot',
                ask: 'Tik het lijdend voorwerp van vissen dat in vissersboot zit',
                cast: ['vis', 'visser', 'boot', 'mes'],
                answer: [],
                note: 'Niets: boot komt niet van een werkwoord, dus er is geen plek te vullen. Vissers zegt alleen van wie de boot is. Een gewone samenstelling, al zit er een -er in het eerste deel.',
              },
              {
                text: 'muizenvanger',
                ask: 'Tik wat er gevangen wordt',
                cast: ['muis', 'kip', 'kasteel', 'mus'],
                answer: ['muis'],
                then: {
                  q: 'Kan een muizenvanger een muis zijn die vangt?',
                  options: ['Nee: bij -er is het eerste deel nooit de dader', 'Ja, allebei kan'],
                  answer: 'Nee: bij -er is het eerste deel nooit de dader',
                },
                note: 'Muis is het lijdend voorwerp van vangen. De dader is de -er: een kat, een val, een uil.',
              },
              {
                text: 'pannenkoekenbakker',
                ask: 'Tik wat er gebakken wordt',
                cast: ['pannenkoek', 'pan', 'ei', 'koek'],
                answer: ['pannenkoek'],
                note: 'Pannenkoek is het lijdend voorwerp van bakken. De pan zit ook in het woord, maar als deel van pannenkoek, niet als argument van bakken: bomen in bomen.',
              },
            ],
            note: 'Vier keer vulde het eerste deel het lijdend voorwerp, één keer was er niets te vullen. De -er in visser maakte vissersboot niet synthetisch: alleen het hoofd telt.',
          },
        },
        {
          text: '*-ing* doet hetzelfde als *-er*, maar het naamwoord is dan geen dader: het is de handeling zelf, of wat eruit komt. *Boekbespreking*: een bespreking van een boek. Nu het raadsel uit Samenstellingen zonder einde. Bij *boekverkoper* bestaan zowel *boekverkoop* als *verkoper*; welke boom is goed? Argumentvererving geeft het antwoord: *-er* plakt aan werkwoorden, niet aan het naamwoord *boekverkoop*. Dus [boek [verkoop er]], en *boekverkoop* is een andere samenstelling, met het naamwoord *verkoop* als hoofd. Bouw *boekbespreking* op dezelfde manier.',
          rule: 'Eerst wordt het werkwoord een naamwoord met een open plek (*-er*, *-ing*); dan vult het eerste deel die plek.',
          bracket: {
            q: 'Bouw: een bespreking van een boek',
            tree: '[boek [bespreek ing]]',
            nodes: [
              {
                w: 'bespreeking',
                form: 'bespreking',
                cat: 'zn',
                note: '-ing maakt van bespreken een naamwoord en erft de open plek: een bespreking van iets. In de spelling valt een e weg: bespreking.',
              },
              { w: 'boekbespreeking', form: 'boekbespreking', cat: 'zn', note: 'boek vult de open plek. Vaste relatie: het boek wordt besproken.' },
            ],
            traps: [
              {
                w: 'boekbespreek',
                note: 'Een werkwoord boekbespreken bestaat niet: ik boekbespreek kan niemand zeggen. Eerst wordt het werkwoord een naamwoord, dan pas komt boek erbij.',
              },
            ],
            note: '[boek [bespreek ing]]: dezelfde boom als bij aardappelschiller. Het werkwoord wordt eerst een naamwoord met een open plek, en de samenstelling vult die plek.',
          },
          deep: {
            q: 'Bestaan er dan nooit werkwoorden met een lijdend voorwerp erin?',
            a: 'Een handvol, en die ontstonden achteraf. *Stofzuigen* is een *terugvorming* uit *stofzuiger*: het naamwoord was er eerder dan het werkwoord. Zo ook *ademhalen* uit *ademhaling*. Daarom klinkt *ik aardappelschil* onmogelijk en *ik stofzuig* gewoon. Hoe zulke werkwoorden zich in de zin gedragen, zag je bij Waar houdt het woord op?.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'eerste-deel',
      prompt: 'Wat doet het eerste deel in het woord?',
      buckets: ['lijdend voorwerp', 'onderwerp (werkwoord zonder lijdend voorwerp)', 'geen argument'],
      items: [
        { t: 'aardappelschiller', b: 0 },
        { t: 'boekbespreking', b: 0 },
        { t: 'visverkoper', b: 0 },
        { t: 'menseneter', b: 0 },
        { t: 'kindergehuil', b: 1 },
        { t: 'vogelgezang', b: 1 },
        { t: 'hondengeblaf', b: 1 },
        { t: 'vissersboot', b: 2 },
        { t: 'zakmes', b: 2 },
        { t: 'thuiswerker', b: 2 },
      ],
      why: 'Schillen, bespreken, verkopen en eten hebben een lijdend voorwerp, en dat staat vooraan. Huilen, zingen en blaffen niet: dan staat hun onderwerp vooraan. Vissersboot en zakmes hebben geen werkwoord in het hoofd, en thuis in thuiswerker is een bepaling, geen argument.',
    },
    {
      kind: 'bet',
      id: 'wibbel',
      prompt: 'Een verzonnen woord: ‘wibbelsnijder’. Wat is dat?',
      options: ['Iets wat wibbels snijdt', 'Een wibbel die snijdt', 'Een wibbel die gesneden is'],
      answer: 'Iets wat wibbels snijdt',
      why: 'Het hoofd snijder komt van snijden, en het eerste deel vult het lijdend voorwerp. De dader is de -er zelf. Ook bij een woord dat niemand kent, ligt de relatie vast.',
    },
    {
      kind: 'rewrite',
      id: 'eierkoker',
      prompt: 'Zeg het met één synthetische samenstelling.',
      source: 'een apparaat dat eieren kookt',
      accept: ['een eierkoker', 'eierkoker'],
      why: 'ei + er + koker: het lijdend voorwerp vooraan, de -er voor het apparaat dat kookt. De tussenklank volgt het meervoud eieren, net als in eierdoos.',
    },
    {
      kind: 'type',
      id: 'slijper',
      prompt: 'Typ de synthetische samenstelling.',
      before: 'Wie schaatsen slijpt, is een',
      after: '.',
      hint: 'schaats…',
      answer: 'schaatsenslijper',
      why: 'schaats + en + slijper: schaats heeft alleen het meervoud schaatsen, dus -en-. Het lijdend voorwerp van slijpen staat vooraan.',
    },
    {
      kind: 'explain',
      id: 'verdieping',
      title: 'Wat -ing erft: gebeurtenis of ding',
      panels: [
        {
          text: '*De vertaling van de roman door Ans duurde jaren.* Hier erft *vertaling* alles van *vertalen*: de roman (het lijdend voorwerp, nu met *van*), Ans (de dader, nu met *door*), en het duurt. *De vertaling ligt op tafel.* Hier is *vertaling* een ding: geen argumenten, wel een plek. Jane Grimshaw (*Argument Structure*, 1990) noemde de eerste een *complexe gebeurtenisnominalisatie* en de tweede een *resultaatnominalisatie*. Alleen de eerste heeft argumentstructuur. Haar toetsen: kan er een *door*-bepaling bij, past *voortdurend* ervoor, en is er een meervoud? Tik de zinnen.',
          rule: 'Gebeurtenisnominalisatie: erft de argumenten (*van*, *door*), duurt, geen meervoud. Resultaatnominalisatie: een ding, telbaar, zonder argumenten.',
          lab: {
            label: 'Tik een zin',
            chips: [
              {
                k: 'De vertaling van de roman door Ans duurde jaren.',
                out: 'gebeurtenis',
                note: 'Vertaling erft hier beide argumenten van vertalen: de roman met van, Ans met door. En het duurt: een gebeurtenis.',
              },
              { k: 'De vertaling ligt op tafel.', out: 'resultaat', note: 'Geen argumenten, wel een plek: het ding dat uit het vertalen kwam.' },
              {
                k: 'Drie vertalingen van de roman.',
                out: 'resultaat',
                note: 'Een gebeurtenisnominalisatie heeft geen meervoud. Drie vertalingen zijn drie boeken.',
              },
              {
                k: 'De voortdurende vertaling van nieuws door vrijwilligers.',
                out: 'gebeurtenis',
                note: 'Voortdurend past alleen bij iets wat duurt, en door brengt de dader mee. Precies de toetsen van Grimshaw.',
              },
            ],
          },
          deep: {
            q: 'Is er nog een derde soort?',
            a: 'Ja. Grimshaw onderscheidde ook de *eenvoudige gebeurtenis*: een naamwoord dat een gebeurtenis noemt zonder argumenten te eisen, zoals *de wedstrijd* of *de reis*. Je kunt zeggen dat die duurde, maar niet wie wat deed. Alleen de complexe gebeurtenisnominalisatie draagt de argumenten van het werkwoord mee.',
          },
        },
        {
          text: 'Nominalisaties vormen een glijdende schaal. Het hele werkwoord met *het* is nog bijna een werkwoord: *het snel vertalen*, met een bijwoord, en zelfs *het romans vertalen*, met het lijdend voorwerp los ervoor en zonder *van*. *De vertaling* staat in het midden: geen bijwoord meer, maar in de gebeurtenislezing wel argumenten via *van* en *door*. *De vertaler* is een gewoon naamwoord: zijn lijdend voorwerp kan alleen nog in een *van*-groep (*vertaler van romans*) of in een samenstelling (*romanvertaler*). Vul de tabel in met ja of nee.',
          rule: 'Van *het vertalen* via *de vertaling* naar *de vertaler* verliest het woord stap voor stap zijn werkwoordelijke eigenschappen.',
          paradigm: {
            q: 'Kan dit erbij? Vul ja of nee in',
            cols: ['meervoud', 'bijwoord ervoor', 'los lijdend voorwerp ervoor'],
            rows: [
              {
                label: 'het vertalen',
                cells: [
                  'nee',
                  { fill: 'ja', hint: 'het snel vertalen: een bijwoord kan, want vertalen is nog een werkwoord.' },
                  { fill: 'ja', hint: 'het romans vertalen: het lijdend voorwerp mag los ervoor, zonder van.' },
                ],
              },
              { label: 'de vertaling (gebeurtenis)', cells: [{ fill: 'nee', hint: 'Een gebeurtenis die duurt, telt niet: geen meervoud.' }, 'nee', 'nee'] },
              { label: 'de vertaling (resultaat)', cells: [{ fill: 'ja', hint: 'Drie vertalingen op tafel: dingen kun je tellen.' }, 'nee', 'nee'] },
              {
                label: 'de vertaler',
                cells: [
                  'ja',
                  { fill: 'nee', hint: 'de snel vertaler kan niet: vertaler is een echt naamwoord. Wel: de snelle vertaler, met een bijvoeglijk naamwoord.' },
                  {
                    fill: 'nee',
                    hint: 'de romans vertaler kan niet. Het lijdend voorwerp kan alleen via van (vertaler van romans) of in een samenstelling (romanvertaler).',
                  },
                ],
              },
            ],
            note: 'Van boven naar beneden wordt het woord steeds minder werkwoord. Het hele werkwoord neemt nog een bijwoord en een los lijdend voorwerp; de -ing erft argumenten via van en door; de -er kan zijn lijdend voorwerp alleen nog kwijt in een van-groep of een samenstelling.',
          },
        },
        {
          text: 'Ook een hele woordgroep kan het eerste deel zijn. Een *blotevoetenpad* is een pad voor *blote voeten*, een *oudemannenhuis* een huis voor *oude mannen*, een *langeafstandsloper* iemand die *de lange afstand* loopt. De groep komt kant-en-klaar uit de zinsbouw: *blote* met zijn *-e*, *voeten* in het meervoud. Dat meervoud is dus echt, anders dan de tussenklank in *pannenkoek* (zie Pannenkoek of pannekoek?). De Woordenlijst schrijft zulke samenstellingen aaneen; een koppelteken mag alleen als het woord anders slecht leesbaar is. Bouw *langeafstandsloper*: een woordgroep én een synthetische samenstelling in één.',
          rule: 'Woordgroep als eerste deel: de groep gaat ongewijzigd het woord in, en het geheel schrijf je aaneen: *blotevoetenpad*, *langeafstandsloper*.',
          bracket: {
            q: 'Bouw: iemand die de lange afstand loopt',
            tree: '[[lange afstand] [loop er]]',
            words: true,
            nodes: [
              { w: 'lange afstand', cat: 'naamwoordgroep', note: 'Bijvoeglijk naamwoord met -e plus naamwoord: een gewone groep uit de zinsbouw.' },
              { w: 'loop er', form: 'loper', cat: 'zn', note: '-er maakt van lopen een naamwoord met een open plek: een loper van iets.' },
              {
                w: 'lange afstand loop er',
                form: 'langeafstandsloper',
                cat: 'zn (samenstelling)',
                note: 'De hele groep vult de open plek van loper. Aaneen, met een tussen-s. Blotevoetenpad en oudemannenhuis volgen hetzelfde bouwplan.',
              },
            ],
            traps: [
              { w: 'afstand loop', note: 'Eerst wordt loop + er een naamwoord, en lange hoort bij afstand: de groep gaat als geheel.' },
              {
                w: 'lange afstand loop',
                note: 'Een langeafstandsloop bestaat, dat is de wedstrijd. Maar -er plakt aan een werkwoord, niet aan dat naamwoord. Loper erft zijn open plek van lopen.',
              },
            ],
            note: '[[lange afstand] [loop er]]: links een woordgroep, rechts een afleiding van een werkwoord, en de groep vult de plek. Twee verschijnselen uit deze les in één woord.',
          },
        },
        {
          text: 'Nu het gevaarlijke paar. *Een rood wijnglas* is een wijnglas dat rood is: een woordgroep, met het bijvoeglijk naamwoord vóór de samenstelling *wijnglas*. Na *een* buigt *rood* niet, want *glas* is een het-woord. *Een rodewijnglas* is een glas voor rode wijn: de groep *rode wijn* zit in het woord, en *rode* blijft *rode*, ook na *een*. Dat is de *buigingstoets*: wat in een woord zit, buigt niet meer mee met de zin. Hetzelfde geldt voor *een hoge school* tegenover *een hogeschool*. In de uitspraak hoor je het verschil nauwelijks; in de spelling moet je kiezen. Tik hieronder elk woord dat aan zijn buur vast moet.',
          rule: 'Buigingstoets: *een rood wijnglas* (woordgroep, *rood* buigt mee) tegenover *een rodewijnglas* (samenstelling, *rode* staat vast).',
          mark: {
            q: 'Tik elk woord dat aan zijn buur vast moet',
            sentence: 'Op het blote voeten pad dronk ze rode wijn uit een rood wijnglas, niet uit een rode wijn glas.',
            targets: [2, 3, 4, 16, 17, 18],
            note: 'blotevoetenpad en rodewijnglas: twee samenstellingen met een woordgroep erin. Maar rode wijn (die ze dronk) is een vrije woordgroep, en een rood wijnglas is een wijnglas dat rood is. Die blijven los.',
          },
        },
      ],
    },
    {
      kind: 'ambiguity',
      id: 'vertaling-slecht',
      prompt: 'Eén nominalisatie, twee lezingen',
      intro: 'Vertaling kan een gebeurtenis zijn of het boek dat eruit kwam. Kies een lezing en zoek de zin die alleen dát kan betekenen.',
      sentence: 'De vertaling van de roman was slecht.',
      meanings: [
        {
          id: 'gebeurtenis',
          label: 'Het vertalen zelf ging slecht (gebeurtenis)',
          highlight: ['vertaling van de roman'],
          right: 'Klopt. Met door Ans en verliep erft vertaling de argumenten van vertalen en wordt het een gebeurtenis.',
        },
        {
          id: 'resultaat',
          label: 'Het boek dat eruit kwam is slecht (resultaat)',
          highlight: ['De vertaling'],
          right: 'Klopt. Wat in de winkel ligt, is een ding: de resultaatnominalisatie.',
        },
      ],
      options: [
        { t: 'De vertaling van de roman door Ans verliep slecht.', fits: 'gebeurtenis' },
        { t: 'De vertaling van de roman ligt vol fouten in de winkel.', fits: 'resultaat' },
        { t: 'De vertaling van de roman was slecht, vond iedereen.', fits: null, note: 'Nog steeds allebei mogelijk: een mening erbij kiest geen lezing.' },
      ],
      done: {
        title: 'Door en ligt beslissen',
        text: 'Een door-bepaling en een werkwoord van verloop (verliep, duurde) dwingen de gebeurtenislezing af; een plek of een meervoud dwingt het ding af.',
      },
    },
    {
      kind: 'speed',
      id: 'aaneen',
      prompt: 'Aan elkaar of los?',
      intro: 'Zit de woordgroep in het woord, of staat het bijvoeglijk naamwoord los vóór een samenstelling?',
      seconds: 40,
      items: [
        { a: 'blote voeten', b: 'pad', joined: true, tip: 'blotevoetenpad: een pad voor blote voeten.' },
        { a: 'blote', b: 'voeten', joined: false, tip: 'blote voeten: een gewone woordgroep.' },
        { a: 'rode wijn', b: 'glas', joined: true, tip: 'rodewijnglas: een glas voor rode wijn.' },
        { a: 'rood', b: 'wijnglas', joined: false, tip: 'een rood wijnglas: het glas is rood. Rood buigt mee met een.' },
        { a: 'korte termijn', b: 'geheugen', joined: true, tip: 'kortetermijngeheugen: geheugen voor de korte termijn.' },
        { a: 'korte', b: 'termijn', joined: false, tip: 'korte termijn: een woordgroep.' },
        { a: 'oude mannen', b: 'huis', joined: true, tip: 'oudemannenhuis: een huis voor oude mannen.' },
        { a: 'lange afstand', b: 'loper', joined: true, tip: 'langeafstandsloper: de groep vult de open plek van loper.' },
      ],
    },
    {
      kind: 'highlight',
      id: 'nominalisaties',
      prompt: 'Gebeurtenis of ding?',
      intro: 'Kleur elke nominalisatie: erft ze argumenten en duurt ze, of is ze een telbaar ding met een plek?',
      pens: [
        { id: 'ev', label: 'gebeurtenis', tag: 'gebeurtenis', ask: 'Duurt het, en komen de argumenten mee met van en door?', accent: 'orange' },
        { id: 're', label: 'resultaat', tag: 'resultaat', ask: 'Is het een ding: te tellen, ergens te vinden?', accent: 'blue' },
      ],
      words: [
        { t: 'De' },
        { t: 'vertaling', role: 'ev' },
        { t: 'van' },
        { t: 'de' },
        { t: 'roman' },
        { t: 'door' },
        { t: 'Ans' },
        { t: 'duurde' },
        { t: 'drie' },
        { t: 'jaar,' },
        { t: 'maar' },
        { t: 'nu' },
        { t: 'ligt' },
        { t: 'de' },
        { t: 'vertaling', role: 're' },
        { t: 'op' },
        { t: 'tafel.' },
        { t: 'De' },
        { t: 'beschrijving', role: 'ev' },
        { t: 'van' },
        { t: 'het' },
        { t: 'dorp' },
        { t: 'door' },
        { t: 'de' },
        { t: 'reiziger' },
        { t: 'kostte' },
        { t: 'maanden;' },
        { t: 'zijn' },
        { t: 'beschrijvingen', role: 're' },
        { t: 'staan' },
        { t: 'in' },
        { t: 'dit' },
        { t: 'boek.' },
        { t: 'De' },
        { t: 'opening', role: 'ev' },
        { t: 'van' },
        { t: 'het' },
        { t: 'museum' },
        { t: 'door' },
        { t: 'de' },
        { t: 'koning' },
        { t: 'begint' },
        { t: 'om' },
        { t: 'tien' },
        { t: 'uur,' },
        { t: 'en' },
        { t: 'de' },
        { t: 'opening', role: 're' },
        { t: 'in' },
        { t: 'de' },
        { t: 'muur' },
        { t: 'is' },
        { t: 'dichtgemetseld.' },
      ],
      done: {
        title: 'Drie paren',
        text: 'vertaling, beschrijving en opening: telkens eerst een gebeurtenis met van en door, dan een ding dat ligt, in een boek staat of in een muur zit.',
      },
    },
    {
      kind: 'bet',
      id: 'wibbeling',
      prompt: 'Een verzonnen werkwoord: ‘iets wibbelen’. Welke zin kan alleen de gebeurtenislezing van ‘wibbeling’ hebben?',
      options: ['De wibbeling van de kast door Pim duurde een uur.', 'Er liggen drie wibbelingen op tafel.', 'Dit is een mooie wibbeling.'],
      answer: 'De wibbeling van de kast door Pim duurde een uur.',
      why: 'Een door-bepaling en duurde: dat kan alleen bij een gebeurtenisnominalisatie, die de argumenten van wibbelen erft. Drie wibbelingen op tafel zijn dingen.',
    },
    {
      kind: 'fix',
      id: 'afstandsloop',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Ze traint al maanden voor de lange afstandsloop van zondag.',
      wrong: 6,
      answer: 'langeafstandsloop',
      why: 'De woordgroep lange afstand zit in de samenstelling: aaneen, met tussen-s. Los zou het een afstandsloop zijn die lang is. (Tik het eerste deel.)',
    },
    {
      kind: 'explain',
      id: 'onderzoek',
      title: 'Het eiland en zijn lekken',
      panels: [
        {
          text: 'Alles in deze les draait om één vraag: hoe streng is de grens tussen woord en zin? De *Lexicale-integriteitshypothese* zegt: zinsregels kunnen niet in een woord kijken. Anna-Maria Di Sciullo en Edwin Williams (1987) noemden woorden *syntactische atomen*; Joan Bresnan en Sam Mchombo (1995) formuleerden de hypothese scherp en toetsten haar aan Bantoetalen. De buigingstoets uit de verdieping hoort erbij: in *een rodewijnglas* buigt *rode* niet mee met *een*, want de zin komt het woord niet in. Ook het meervoud blijft buiten: *rodewijnglazen*, niet *rodewijnenglas*. En de eilandtoets (*een zeer hoogleraar* kan niet) en de verwijzingstoets van Postal (zie Het woord) horen bij dezelfde hypothese.',
          rule: 'Lexicale integriteit: de zin kan niet in het woord; buiging, meervoud en bepalingen hechten aan het hele woord.',
          quiz: {
            q: 'Na welk lidwoord zie je dat rode in rodewijnglas niet meebuigt met de zin?',
            options: ['een', 'het', 'de'],
            answer: 'een',
            why: 'Na een krijgt een bijvoeglijk naamwoord bij een het-woord geen -e: een rood glas. Toch blijft het een rodewijnglas. Na het en de buigt een bijvoeglijk naamwoord sowieso: daar zie je niets.',
          },
        },
        {
          text: 'Maar het eiland lekt. *Voor- en nadelen* laat de nevenschikking een stuk van een woord delen; Booij (1985) liet zien dat dat kan als het stuk een eigen klankwoord is. Argumentvererving is zelf een lek: in *aardappelschiller* vult een deel van het woord een plek van het werkwoord, een relatie die bij de zinsbouw hoort. Rochelle Lieber (1992) concludeerde dat woordbouw en zinsbouw één systeem zijn. Peter Ackema en Ad Neeleman (*Beyond Morphology*, 2004) houden ze juist apart, als twee systemen die om dezelfde betekenis concurreren: *aardappelschiller* naast *schiller van aardappels*. Geert Booij (*Construction Morphology*, 2010) houdt het eiland overeind, maar met vaste bouwplannen die een woordgroep als bouwsteen kunnen opnemen. Het debat is open.',
          rule: 'Lekken: nevenschikking van woorddelen, argumentvererving, woordgroepen in woorden, terugvorming. Elke theorie moet ze apart verklaren.',
          lab: {
            label: 'Tik een geval',
            chips: [
              {
                k: 'voor- en nadelen',
                out: 'lek: de nevenschikking deelt een woorddeel',
                note: 'Booij (1985): dat kan alleen als het gedeelde stuk een eigen klankwoord is (zie Woordbomen).',
              },
              {
                k: 'aardappelschiller',
                out: 'lek: een argument in het woord',
                note: 'Het eerste deel vult een plek van het werkwoord: een relatie uit de zinsbouw. Lieber zag daarin bewijs dat woordbouw en zinsbouw één zijn.',
              },
              {
                k: 'blijf-van-mijn-lijfhuis',
                out: 'een zin in een woord, maar bevroren',
                note: 'Zodra het woord af is, kan mijn niet meer wisselen: een blijf-van-haar-lijfhuis voor háár huis bestaat niet. Het eiland sluit zodra het woord af is.',
              },
              {
                k: 'ik stofzuig',
                out: 'terugvorming: uit stofzuiger ontstond een werkwoord',
                note: 'Het lijdend voorwerp stof zit nu in een werkwoord. Zeldzaam, en pas achteraf ontstaan.',
              },
            ],
          },
          deep: {
            q: 'Wat zou het debat beslissen?',
            a: 'Een scherpe voorspelling. Als woordbouw gewoon zinsbouw is, verwacht je dat alles wat de zin kan, ook in het woord kan: verplaatsen, verwijzen, buigen. Dat zien we niet: *rode* in *rodewijnglas* staat vast, en *mijn* in *blijf-van-mijn-lijfhuis* wisselt niet mee met de bewoner. Wie het eiland verdedigt, moet omgekeerd elk lek apart verklaren: de nevenschikking via het klankwoord, de argumentvererving via het bouwplan van *-er* en *-ing*.',
          },
        },
        {
          text: 'Waar komen de bouwstenen vandaan? Uit de zin. Kijk naar de bijzin *dat ze op blote voeten de lange afstand loopt*. Daar staan de groepen al klaar: *blote voeten*, een naamwoordgroep met buiging en meervoud, en *de lange afstand* als lijdend voorwerp, vlak vóór het werkwoord (in de bijzin staat het lijdend voorwerp immers vóór het werkwoord, zie De woordgroep). *Blotevoetenpad* en *langeafstandsloper* nemen die groepen over zoals ze zijn, op één ding na: het lidwoord. *De* uit *de lange afstand* valt weg, en het woord krijgt zijn eigen lidwoord van het hoofd: *de langeafstandsloper*, want *de loper*. Zoek de groepen in de bijzin.',
          rule: 'De zin levert de groep, het woord laat het lidwoord buiten en zet er een hoofd achter.',
          phrase: {
            q: 'Vind de twee naamwoordgroepen en de voorzetselgroep',
            sentence: 'dat ze op blote voeten de lange afstand loopt',
            groups: [
              { span: [3, 4], cat: 'naamwoordgroep', head: 4, note: 'blote voeten: met -e en meervoud. Zo gaat de groep het woord blotevoetenpad in.' },
              {
                span: [2, 4],
                cat: 'voorzetselgroep',
                head: 2,
                note: 'op blote voeten: het voorzetsel blijft buiten de samenstelling. Een pad voor blote voeten, geen opblotevoetenpad.',
              },
              {
                span: [5, 7],
                cat: 'naamwoordgroep',
                head: 7,
                note: 'de lange afstand: het lijdend voorwerp van loopt. Zonder het lidwoord wordt het de eerste bouwsteen van langeafstandsloper.',
              },
            ],
            traps: [
              {
                span: [7, 8],
                note: 'afstand loopt is geen groep: afstand is het lijdend voorwerp, loopt de persoonsvorm. Maar juist deze twee buren groeien in langeafstandsloper aan elkaar.',
              },
              { span: [4, 5], note: 'voeten de loopt over twee groepen heen.' },
            ],
            note: 'De zinsbouw levert de groepen kant-en-klaar; de woordbouw plakt er een hoofd achter en laat het lidwoord buiten. Daarom ziet een samenstelling er soms uit als een stukje zin.',
          },
        },
        {
          text: 'Wat betekent dit voor je schrijven? Een gebeurtenisnominalisatie erft de argumenten van haar werkwoord, en die moeten ergens heen: in *van*- en *door*-groepen. Zo ontstaat de *naamwoordstijl* (zie De woordgroep): *de uitvoering van de controle van de gegevens door de afdeling*. Drie werkwoorden zijn naamwoorden geworden, en elk sleept een *van* of *door* mee. Haal het werkwoord terug, en de argumenten vallen op hun gewone plek: onderwerp en lijdend voorwerp. Let op: niet elke nominalisatie moet weg. Een resultaatnominalisatie als *de melding* is gewoon een ding en mag blijven. Tik de nominalisaties die je beter als werkwoord schrijft.',
          rule: 'Een gebeurtenisnominalisatie sleept haar argumenten mee in *van* en *door*; een werkwoord zet ze op hun plek.',
          mark: {
            q: 'Tik de drie gebeurtenisnominalisaties',
            sentence: 'De uitvoering van de controle van de gegevens door de afdeling vond plaats na de ontvangst van de melding.',
            targets: [1, 4, 15],
            note: 'uitvoering, controle en ontvangst: drie gebeurtenissen met van- en door-groepen eraan. Melding is een ding dat je ontvangt. Korter: De afdeling controleerde de gegevens nadat ze de melding had ontvangen.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'sportdag',
      prompt: 'Lees het verslag na',
      intro: 'Er staan vier samenstellingen los die aan elkaar horen. Pas op: rode wijn en een rood wijnglas zijn goed zoals ze staan.',
      header: { to: 'de redactie', subject: 'Verslag van de sportdag' },
      tokens: [
        { t: 'Onze' },
        { t: 'lange afstandsloper', fix: 'langeafstandsloper', why: 'De woordgroep lange afstand zit in de samenstelling: aaneen, met tussen-s.' },
        { t: 'won' },
        { t: 'zondag' },
        { t: 'de' },
        { t: 'wedstrijd' },
        { t: 'over' },
        { t: 'het' },
        { t: 'blote voeten pad', fix: 'blotevoetenpad', why: 'Een pad voor blote voeten: de hele groep gaat aaneen het woord in.' },
        { t: 'naar' },
        { t: 'de' },
        { t: 'finish.' },
        { t: 'Daarna' },
        { t: 'dronk' },
        { t: 'hij' },
        { t: 'rode' },
        { t: 'wijn' },
        { t: 'uit' },
        { t: 'een' },
        { t: 'rood' },
        { t: 'wijnglas' },
        { t: 'en' },
        { t: 'vergat' },
        { t: 'hij' },
        { t: 'alles' },
        { t: 'meteen:' },
        { t: 'zijn' },
        {
          t: 'korte termijn geheugen',
          fix: 'kortetermijngeheugen',
          why: 'Geheugen voor de korte termijn: de groep korte termijn zit in het woord, dus aaneen.',
        },
        { t: 'is' },
        { t: 'berucht.' },
        { t: 'Thuis' },
        { t: 'wachtte' },
        { t: 'een' },
        {
          t: 'eier koker',
          fix: 'eierkoker',
          why: 'Een synthetische samenstelling: eieren is het lijdend voorwerp van koken. Aaneen, met de tussenklank -er-.',
        },
        { t: 'als' },
        { t: 'prijs.' },
      ],
      done: {
        title: 'Vier gevonden',
        text: 'langeafstandsloper, blotevoetenpad, kortetermijngeheugen en eierkoker. Rode wijn is een vrije woordgroep en een rood wijnglas is een wijnglas dat rood is: die blijven los.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ de zin.',
      sentence: 'Op het blotevoetenpad zag de langeafstandsloper een rodewijnglas staan.',
      right: 'Goed: drie samenstellingen met een woordgroep erin, alle drie aaneen.',
      wrong:
        'Let op: blotevoetenpad, langeafstandsloper en rodewijnglas schrijf je aaneen. De woordgroep gaat met buiging en al het woord in, en het geheel is één woord.',
    },
    {
      kind: 'chat',
      id: 'redacteur',
      prompt: 'App met de eindredacteur',
      intro: 'Kies telkens het antwoord dat klopt met wat je in deze les leerde.',
      contact: { name: 'Daan', role: 'eindredacteur van het blad', initials: 'D' },
      rounds: [
        {
          say: 'Ik schrijf: "De controle van de cijfers door Fatima vond plaats op maandag." Kan dat korter?',
          options: ['Fatima controleerde de cijfers op maandag.', 'De controle door Fatima van de cijfers vond plaats op maandag.'],
          right: 0,
          fix: 'de controle van de cijfers door Fatima vond plaats → Fatima controleerde de cijfers',
          why: 'De gebeurtenisnominalisatie sleept beide argumenten mee in een van- en een door-groep. Het werkwoord zet ze op hun gewone plek: onderwerp en lijdend voorwerp.',
        },
        {
          say: 'En de kop: moet het "rode wijnglazen" of "rodewijnglazen" zijn? Het gaat om glazen voor rode wijn.',
          options: ['rodewijnglazen', 'rode wijnglazen'],
          right: 0,
          fix: 'rode wijnglazen → rodewijnglazen',
          why: 'De groep rode wijn zit in het woord: aaneen. Rode wijnglazen zijn wijnglazen die rood zijn. En het meervoud hecht aan het hoofd: glazen.',
        },
        {
          say: 'In het stuk staat "muizenvanger". Is dat een kat die muizen vangt, of een muis die vangt?',
          options: ['Een kat (of een val) die muizen vangt.', 'Een muis die vangt.'],
          right: 0,
          fix: 'een muis die vangt → een kat die muizen vangt',
          why: 'Bij -er vult het eerste deel het lijdend voorwerp. De dader is de -er zelf en staat buiten het woord.',
        },
        {
          say: 'Laatste: "lange-afstandsloper" met een streepje, mag dat?',
          options: [
            'Liever langeafstandsloper, aaneen. Een streepje alleen als het woord anders slecht leesbaar is.',
            'Nee, het moet lange afstandsloper zijn, los.',
          ],
          right: 0,
          fix: 'lange-afstandsloper → langeafstandsloper',
          why: 'De Woordenlijst schrijft een samenstelling met een woordgroep aaneen. Los zou het een afstandsloper zijn die lang is.',
        },
      ],
      bye: 'Dank je. Nu durf ik de kop te zetten: Langeafstandsloper wint op blotevoetenpad.',
    },
    {
      kind: 'swipe',
      id: 'eiland-waar',
      prompt: 'Klopt deze zin?',
      cards: [
        {
          t: 'In aardappelschiller is aardappel het lijdend voorwerp van schillen.',
          ok: true,
          why: 'Een synthetische samenstelling: het eerste deel vult de open plek die -er van het werkwoord erft.',
        },
        {
          t: 'Een menseneter kan ook een mens zijn die eet.',
          ok: false,
          fix: 'Een menseneter eet mensen',
          why: 'De dader van een overgankelijk werkwoord kan niet vooraan: die is de -er zelf.',
        },
        {
          t: 'Volgens Grimshaw heeft alleen de complexe gebeurtenisnominalisatie argumentstructuur.',
          ok: true,
          why: 'De vertaling van de roman door Ans duurde jaren: argumenten en duur. De vertaling op tafel is een ding.',
        },
        {
          t: 'Een rood wijnglas en een rodewijnglas betekenen hetzelfde.',
          ok: false,
          fix: 'Een rood wijnglas is rood; een rodewijnglas is voor rode wijn',
          why: 'De buigingstoets: rood buigt mee met een, rode in het woord niet.',
        },
        {
          t: 'Volgens Roeper en Siegel mag alleen het lijdend voorwerp de samenstelling in.',
          ok: false,
          fix: 'Alles wat eerste zuster van het werkwoord is, ook een bepaling zoals thuis in thuiswerker',
          why: 'Het First Sister Principle gaat over de plek naast het werkwoord, niet alleen over het lijdend voorwerp.',
        },
        {
          t: 'Ackema en Neeleman zien woordbouw en zinsbouw als twee systemen die concurreren.',
          ok: true,
          why: 'Aardappelschiller naast schiller van aardappels: twee wegen naar dezelfde betekenis.',
        },
        {
          t: 'Het meervoud van rodewijnglas is rodewijnenglas.',
          ok: false,
          fix: 'rodewijnglazen',
          why: 'Het meervoud hecht aan het hele woord, aan het hoofd. Binnenin verandert niets: lexicale integriteit.',
        },
      ],
    },
  ],
};
