import type { LessonInput } from '../../schema';

/**
 * Werkwoordspelling als systeem: de stam schrijf je zoals je hem in het hele werkwoord ziet
 * (gelijkvormigheid), de uitgang -t volgt het onderwerp, en de verleden tijd en het deelwoord
 * zijn sommen van zichtbare stukken. Daarna de homofonen (gebeurt/gebeurd, verwachtte/verwachte),
 * het deelwoord als bijvoeglijk naamwoord en de Engelse leenwerkwoorden volgens de Woordenlijst.
 * Bouwt voort op ’t Kofschip werkt op klank (k12), De vier principes (k16) en d17 (de d/t-fout).
 */
export const LES_W23: LessonInput = {
  id: 'w23',
  stage: 'bachelor',
  domain: 'morf',
  also: ['orth', 'fon'],
  title: 'Word, wordt en gebeurd',
  skill: 'Spelling',
  icon: '-dt',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Je schrijft de stam, ook als je hem niet hoort',
      panels: [
        {
          text: 'Je hoort [wort], je schrijft *wordt*. Dat is geen pesterij maar een afspraak die door de hele spelling loopt: het *beginsel van de gelijkvormigheid*. Een woorddeel houdt zoveel mogelijk dezelfde vorm, ook als je het anders hoort. *Hond* krijgt een d vanwege *honden*, *web* een b vanwege *webben*, en de stam *word* krijgt een d vanwege *worden*. De ik-vorm is die kale stam: *ik word*, *ik vind*, *ik antwoord*. Alleen als het hele werkwoord een v of z laat zien, past de stam zich aan: *leven* geeft *ik leef* en *verhuizen* geeft *ik verhuis*, want een Nederlands woord eindigt niet op v of z (een enkel leenwoord als *quiz* daargelaten).',
          rule: 'Gelijkvormigheid: schrijf de stam zoals je hem in het hele werkwoord ziet. De ik-vorm is de stam.',
          split: {
            q: 'Knip wordt in stam en uitgang',
            word: 'wordt',
            answer: 'word-t',
            note: 'word is de stam, uit worden. De t is de uitgang van hij, zij en het. Twee stukken, allebei zichtbaar, al hoor je er maar één klank.',
          },
        },
        {
          text: 'De uitgang *-t* is een morfeem met een vaste verdeling. *Hij*, *zij*, *het*, *wie*, *dat* en elk ander onderwerp in de derde persoon enkelvoud krijgen stam + t: *hij loopt*, dus ook *hij wordt*, waar je die t niet hoort. *Jij* en *je* krijgen de t alleen als ze vóór de persoonsvorm staan: *jij wordt* tegenover *word jij*. *U* is de uitzondering op de uitzondering: altijd stam + t, voor én achter het werkwoord: *u wordt*, *wordt u*. Vul het hele systeem in en let op de twee rijen met inversie.',
          rule: 'Derde persoon en u: altijd stam + t. Jij en je: stam + t ervoor, kale stam erachter.',
          paradigm: {
            q: 'Vul het systeem in',
            cols: ['vinden', 'worden'],
            rows: [
              { label: 'ik', cells: ['vind', 'word'] },
              { label: 'jij …', cells: ['vindt', { fill: 'wordt', hint: 'Jij staat vóór de persoonsvorm: stam + t.' }] },
              {
                label: '… jij?',
                cells: [
                  { fill: 'vind', hint: 'Jij staat erachter: de t valt weg. Vind jij?' },
                  { fill: 'word', hint: 'Word jij? Jij erachter, geen t.' },
                ],
              },
              { label: 'hij', cells: [{ fill: 'vindt', hint: 'Hij loopt, dus hij vindt: stam vind + t.' }, 'wordt'] },
              { label: 'u …', cells: ['vindt', { fill: 'wordt', hint: 'U krijgt altijd stam + t.' }] },
              {
                label: '… u?',
                cells: [
                  { fill: 'vindt', hint: 'Ook achter de persoonsvorm houdt u de t: vindt u?' },
                  { fill: 'wordt', hint: 'Wordt u? Alleen jij en je verliezen de t bij inversie.' },
                ],
              },
            ],
            extra: ['vint', 'wort'],
            note: 'Zes rijen, vier vormen. De enige rij zonder t is jij achter het werkwoord. U gedraagt zich als een derde persoon.',
          },
          deep: {
            q: 'Waarom valt de t weg bij word jij?',
            a: 'Dat is geschiedenis, geen logica. In het Middelnederlands versmolt de uitgang met het voornaamwoord erachter: *hebt ghi* werd *hebdi*. Toen *jij* en *je* die oude vormen vervingen, bleef de werkwoordsvorm zonder t staan. *U* deed niet mee: het ontstond pas in de zeventiende eeuw uit de aanspreking *Uwe Edelheid* en gedraagt zich als een derde persoon: *u is*, *u wordt*. Daarom mogen *u hebt* en *u heeft* allebei.',
          },
        },
        {
          text: 'Eindigt de stam al op een t, dan komt er niets bij: *hij zet*, *hij praat*, *hij bijt*. Geen *zett*: de spelling kent geen dubbele medeklinker aan het woordeinde. Eindigt de stam op een d, dan komt de t er gewoon achter: *hij vindt*, *hij houdt*, *hij rijdt*, *hij wordt*. De combinatie *dt* is dus niets bijzonders. Het is de gewone som stam + t, met een stam die toevallig op d eindigt. Wie *dt* als aparte regel leert, leert iets wat niet bestaat.',
          rule: 'Stam op t: niets erbij (hij zet). Stam op d: + t (hij vindt). dt is gewoon stam + uitgang.',
          build: {
            before: 'Hij (zetten) de kopjes op tafel. Hij…',
            stem: 'zet',
            endings: ['', 't', 'dt'],
            answer: '',
            note: 'De stam zet eindigt al op t. Een tweede t schrijf je niet: hij zet. Vergelijk hij vindt, waar de stam op d eindigt en de t er wel bij komt.',
          },
        },
        {
          text: 'De t van de derde persoon hoort alleen bij de *persoonsvorm*: het werkwoord dat met de tijd meeverandert. Een voltooid deelwoord of een heel werkwoord krijgt hem nooit. Twijfel je welk woord de persoonsvorm is? Verander de tijd. In *Morgen wordt het pakket bezorgd* wordt *wordt* tot *werd*, maar *bezorgd* blijft staan. Dus is *wordt* de persoonsvorm en *bezorgd* een deelwoord. Zoek daarna het onderwerp: *het pakket*, derde persoon, dus stam + t.',
          rule: 'Persoonsvorm: verandert mee met de tijd. Alleen die krijgt de t van hij, zij, het en u.',
          mark: {
            q: 'Tik de persoonsvorm',
            sentence: 'Morgen wordt het pakket van de buren bij ons bezorgd.',
            targets: [1],
            note: 'Verander de tijd: werd. Alleen wordt verandert mee. Bezorgd blijft staan, dat is een voltooid deelwoord. Het onderwerp is het pakket, dus stam + t.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'stam-of-t',
      prompt: 'Kale stam of stam + t?',
      buckets: ['kale stam', 'stam + t'],
      items: [
        { t: '… jij dat ook? (vinden)', b: 0 },
        { t: 'Hij … het mooi. (vinden)', b: 1 },
        { t: 'Morgen … u zestig. (worden)', b: 1 },
        { t: '… u ook zo moe? (worden)', b: 1 },
        { t: '… je morgen weer? (snorfen)', b: 0 },
        { t: 'Zij … elke dag. (snorfen)', b: 1 },
        { t: 'Ik … nooit. (plurken)', b: 0 },
        { t: 'Het … hier vaak. (gebeuren)', b: 1 },
        { t: 'Wie … dat? (zeggen)', b: 1 },
        { t: '… je dat echt? (plurken)', b: 0 },
      ],
      why: 'Alleen ik, en jij of je áchter de persoonsvorm, krijgen de kale stam. Hij, zij, het, wie en u krijgen stam + t, waar ze ook staan. Snorfen en plurken bestaan niet, en toch wist je het: de regel kijkt niet naar het woord maar naar het onderwerp.',
    },
    {
      kind: 'type',
      id: 'wordt-u',
      prompt: 'Typ de goede vorm van worden.',
      before: 'Morgen',
      after: 'u zestig, meneer De Wit?',
      hint: 'worden',
      answer: 'wordt',
      why: 'U krijgt altijd stam + t, ook als u achter de persoonsvorm staat: wordt u. Alleen jij en je verliezen de t bij inversie.',
    },
    {
      kind: 'fix',
      id: 'word-het',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Je verwacht dat het morgen druk wordt, maar word het dat ook?',
      wrong: 8,
      answer: 'wordt',
      why: 'Het onderwerp is het, derde persoon: stam + t, ook bij inversie. De t valt alleen weg bij jij en je erachter. Het eerste wordt was goed.',
    },
    {
      kind: 'chat',
      id: 'stage',
      prompt: 'Chat met je stagebegeleider',
      intro: 'Kies telkens het antwoord met de goede vorm. Let op wie het onderwerp is en waar het staat.',
      contact: { name: 'Meneer De Wit', role: 'je stagebegeleider', initials: 'DW' },
      rounds: [
        {
          say: 'Goedemorgen. Hoe staat het met het verslag?',
          options: ['Goed! Vind u het goed als ik het vrijdag stuur?', 'Goed! Vindt u het goed als ik het vrijdag stuur?'],
          right: 1,
          fix: 'Vind u → Vindt u',
          why: 'U krijgt altijd stam + t, ook achter de persoonsvorm.',
        },
        {
          say: 'Prima. Word je morgen op kantoor verwacht?',
          options: ['Ja, ik wordt om negen uur verwacht.', 'Ja, ik word om negen uur verwacht.'],
          right: 1,
          fix: 'ik wordt → ik word',
          why: 'Ik krijgt de kale stam. Dat ik wordt zo vaak voorkomt, komt doordat wordt veel vaker te zien is dan word.',
        },
        {
          say: 'Mooi. Mijn collega komt ook, als ze niet ziek wordt.',
          options: ['Hopelijk word ze niet ziek!', 'Hopelijk wordt ze niet ziek!'],
          right: 1,
          fix: 'word ze → wordt ze',
          why: 'Zij of ze verliest de t niet bij inversie. Alleen jij en je doen dat: word je, maar wordt ze.',
        },
        {
          say: 'Zeker. Nog vragen van jouw kant?',
          options: ['Als u eerder iets nodig hebt, antwoord ik meteen.', 'Als u eerder iets nodig hebt, antwoordt ik meteen.'],
          right: 0,
          fix: 'antwoordt ik → antwoord ik',
          why: 'Ik krijgt de kale stam antwoord, ook als ik achter de persoonsvorm staat. De d van antwoorden blijft staan.',
        },
      ],
      bye: 'Dank je. Je berichten zijn altijd foutloos, dat valt op.',
    },
    {
      kind: 'explain',
      id: 'verdieping',
      title: 'Verleden tijd, deelwoord en de e die het verschil maakt',
      panels: [
        {
          text: 'De verleden tijd van een zwak werkwoord is stam + *de* of *te*, en het meervoud krijgt daar nog een n achter. Welke van de twee? ’t Kofschip kijkt naar de laatste klank van de stam zoals die in het hele werkwoord klinkt: *verhuizen* heeft een z, dus *verhuisde*; *leven* een v, dus *leefde*; *verven* ook een v, dus *verfde*. Eindigt de stam zelf al op d of t, dan tel je gewoon door: *antwoord* + *de* = *antwoordde*, *zet* + *te* = *zette*, *verwacht* + *te* = *verwachtte*. De dubbele letter is geen regel op zich. Het is de som van twee zichtbare stukken.',
          rule: 'Verleden tijd: stam + de of te (+ n). Stam op d of t: de letter verdubbelt vanzelf (antwoordde, zette).',
          split: {
            q: 'Knip antwoordden in stam, tijdsuitgang en meervoudsuitgang',
            word: 'antwoordden',
            answer: 'antwoord-de-n',
            note: 'antwoord is de stam, de is de uitgang van de verleden tijd (d zit niet in ’t kofschip), n is het meervoud. De dubbele d ontstaat vanzelf op de naad.',
          },
        },
        {
          text: 'Het voltooid deelwoord van een zwak werkwoord is *ge* + stam + d of t, met dezelfde keuze als in de verleden tijd: *gewerkt* naast *werkte*, *geleefd* naast *leefde*. Twee dingen schrap je. Begint het werkwoord met een onbeklemtoond voorvoegsel als *be-*, *ge-*, *ver-*, *ont-*, *her-* of *er-*, dan komt er geen *ge-* bij: *gebeurd*, *verhuisd*, *herhaald*. Eindigt de stam op d of t, dan komt er geen letter bij: *gezet*, *geantwoord*, *beantwoord*. Je hoort *gebeurd* met een t, maar je schrijft de d van *gebeurde*: weer gelijkvormigheid.',
          rule: 'Voltooid deelwoord: (ge) + stam + d of t. Geen ge- na be-, ge-, ver-, ont-, her-, er-. Stam op d of t: niets erbij.',
          quiz: {
            q: 'Wat is het voltooid deelwoord van herhalen?',
            options: ['herhaald', 'geherhaald', 'herhaalt'],
            answer: 'herhaald',
            why: 'her- is onbeklemtoond, dus geen ge-. De stam herhaal eindigt op l, niet in ’t kofschip, dus d. Herhaalt bestaat ook, maar dat is de persoonsvorm: zij herhaalt.',
          },
        },
        {
          text: 'Een deelwoord kan als bijvoeglijk naamwoord vóór een zelfstandig naamwoord staan en krijgt dan de buigings-e: *de verbrande toast*, *het gebruikte boek*, *de verwachte gasten*. Je plakt de e achter het deelwoord, dus met één d of t: *verwacht* + *e* = *verwachte*. De verleden tijd *verwachtte* is stam + *te*, met twee. Ze klinken precies hetzelfde. Alleen de bouw verschilt, en die zie je in de spelling.',
          rule: 'Bijvoeglijk: deelwoord + e (de verwachte gasten). Verleden tijd: stam + te (ze verwachtte).',
          paradigm: {
            q: 'Vul de drie vormen in',
            cols: ['verleden tijd', 'voltooid deelwoord', 'bijvoeglijk (de … )'],
            rows: [
              {
                label: 'verwachten',
                cells: ['verwachtte', { fill: 'verwacht', hint: 'Stam op t: geen extra t.' }, { fill: 'verwachte', hint: 'Deelwoord verwacht + e: één t.' }],
              },
              {
                label: 'verbranden',
                cells: [
                  { fill: 'verbrandde', hint: 'Stam verbrand + de: twee d’s.' },
                  'verbrand',
                  { fill: 'verbrande', hint: 'Deelwoord verbrand + e: één d.' },
                ],
              },
              {
                label: 'gebruiken',
                cells: [
                  { fill: 'gebruikte', hint: 'Stam gebruik + te: de k zit in ’t kofschip.' },
                  { fill: 'gebruikt', hint: 'ge- zit al in het werkwoord: gebruik + t.' },
                  'gebruikte',
                ],
              },
              {
                label: 'vergroten',
                cells: [
                  { fill: 'vergrootte', hint: 'Stam vergroot + te: twee t’s.' },
                  { fill: 'vergroot', hint: 'Geen ge- na ver-, en geen extra t.' },
                  { fill: 'vergrote', hint: 'Deelwoord vergroot + e: één t.' },
                ],
              },
            ],
            extra: ['verwachtde', 'gebruikd', 'vergroote'],
            note: 'Bij gebruiken is de verleden tijd gelijk aan het bijvoeglijk naamwoord: gebruikte. Bij verwachten, verbranden en vergroten zie je het verschil wél: tt of dd in de verleden tijd, één letter in het bijvoeglijk naamwoord.',
          },
        },
        {
          text: 'Zo ontstaan de beruchte homofonen: *gebeurt* en *gebeurd*, *verwachtte* en *verwachte*, *wordt* en *word*. Je oor helpt niet, je ontleding wel. Vervang het werkwoord door een sterk werkwoord dat wél hoorbaar verandert, zoals *vallen*: *het gebeurt* wordt *het valt* (persoonsvorm), *het is gebeurd* wordt *het is gevallen* (deelwoord). Een bijvoeglijk deelwoord herken je aan zijn plek vóór het naamwoord: *de verbrande toast* is *de gebakken toast*.',
          rule: 'Vervangproef: valt (persoonsvorm), gevallen (deelwoord), de gebakken toast (bijvoeglijk).',
          lab: {
            label: 'Tik een zin en vervang het werkwoord',
            chips: [
              { k: 'Het gebeurt vaak.', out: 'Het valt vaak.', note: 'Valt is een persoonsvorm: het viel. Dus stam + t: gebeurt.' },
              { k: 'Het is al gebeurd.', out: 'Het is al gevallen.', note: 'Gevallen is een voltooid deelwoord. Dus gebeur + d, met de d van gebeurde.' },
              { k: 'Ze verwachtte ons.', out: 'Ze zag ons.', note: 'Zag is verleden tijd. Dus stam + te: verwachtte, met twee t’s.' },
              {
                k: 'de verbrande toast',
                out: 'de gebakken toast',
                note: 'Gebakken staat als bijvoeglijk naamwoord vóór toast. Dus deelwoord + e: verbrande, met één d.',
              },
            ],
          },
        },
      ],
    },
    {
      kind: 'dictation',
      id: 'gasten',
      prompt: 'Luister en typ de zin.',
      sentence: 'De verwachte gasten antwoordden niet, dus het feest werd verzet.',
      right: 'Goed: verwachte (deelwoord + e, één t), antwoordden (antwoord + de + n, twee d’s) en verzet (stam op t, niets erbij).',
      wrong:
        'Let op: verwachte met één t (deelwoord + e), antwoordden met dd (antwoord + de + n) en verzet zonder extra t. Vergeet de hoofdletter, de komma en de punt niet.',
    },
    {
      kind: 'bet',
      id: 'gleuden',
      prompt: 'Een verzonnen werkwoord: gleuden. Gisteren … hij de hele dag.',
      options: ['gleudde', 'gleude', 'gleutte'],
      answer: 'gleudde',
      why: 'De stam gleud eindigt op d, niet in ’t kofschip, dus de: gleud + de = gleudde. Gleude zou een bijvoeglijk deelwoord zijn (de gegleude dag), en gleutte hoort bij een stam op t.',
    },
    {
      kind: 'rewrite',
      id: 'verleden-tijd',
      prompt: 'Zet de zin in de verleden tijd.',
      source: 'Ik verwacht dat hij antwoordt.',
      accept: ['Ik verwachtte dat hij antwoordde.'],
      why: 'verwacht + te en antwoord + de: twee keer een dubbele letter, omdat de stam al op t of d eindigt en de uitgang er gewoon achter komt.',
    },
    {
      kind: 'sort',
      id: 'drie-vormen',
      prompt: 'Welke vorm is het?',
      buckets: ['verleden tijd', 'voltooid deelwoord', 'bijvoeglijk naamwoord'],
      items: [
        { t: 'ze vergrootte de foto', b: 0 },
        { t: 'de vergrote foto', b: 2 },
        { t: 'de foto is vergroot', b: 1 },
        { t: 'het gebeurde gisteren', b: 0 },
        { t: 'het is al gebeurd', b: 1 },
        { t: 'de bedoelde persoon', b: 2 },
        { t: 'ik bedoelde jou', b: 0 },
        { t: 'de gebruikte kopjes', b: 2 },
        { t: 'ze gebruikte mijn kopje', b: 0 },
        { t: 'we hebben alles gebruikt', b: 1 },
      ],
      why: 'Verleden tijd: stam + de of te (vergrootte, gebruikte). Voltooid deelwoord: (ge)stam + d of t (vergroot, gebruikt). Bijvoeglijk: deelwoord + e (vergrote, gebruikte). Gebruikte kan twee dingen zijn; de plek in de zin beslist. Bij vergroten zie je het verschil wél in de spelling.',
    },
    {
      kind: 'explain',
      id: 'onderzoek',
      title: 'Een spelling die morfemen schrijft, en waarom je brein toch struikelt',
      panels: [
        {
          text: 'Waarom schrijft het Nederlands een t die niemand hoort? Omdat onze spelling hier *morfografisch* is: ze schrijft de bouwstenen, niet de klanken (zie De vier principes, k16). Aan het woordeinde verliest elke d haar stem, dus *word* en *wordt* klinken allebei als [wort]; de spelling maakt die samenval ongedaan en toont stam en uitgang apart. Noam Chomsky en Morris Halle (1968) noemden de Engelse spelling om die reden bijna optimaal: ze geeft de onderliggende vorm van een woord weer, niet de uitspraak van het moment. Andere talen lossen hetzelfde probleem anders op. Vergelijk.',
          rule: 'Morfografische spelling: je ziet stam + uitgang, ook als de uitspraak ze laat samenvallen.',
          lab: {
            label: 'Tik een taal',
            chips: [
              { k: 'Nederlands', out: 'hij vindt', note: 'Stam vind + t. Je ziet twee morfemen, je hoort er één klank.' },
              { k: 'Duits', out: 'er findet', note: 'Het Duits schuift een e tussen stam en uitgang. Dan hoor je de t, en het probleem verdwijnt.' },
              { k: 'Engels', out: 'he finds', note: 'De Engelse uitgang is een s. Die hoor je altijd, dus daar vergist niemand zich.' },
              {
                k: 'Afrikaans',
                out: 'hy vind',
                note: 'Het Afrikaans, gegroeid uit het zeventiende-eeuwse Nederlands, heeft de persoonsuitgangen afgeschaft: ek vind, jy vind, hy vind. Geen t, geen fout.',
              },
            ],
          },
          deep: {
            q: 'Is onhoorbaar ook echt onhoorbaar?',
            a: 'Bijna. Natasha Warner en collega’s (2004) maten een piepklein restverschil tussen een onderliggende d en t aan het woordeinde (zie Het betekenisvolle woorddeel, d12). Voor een luisteraar is dat te klein om op te vertrouwen. De spelling doet dus wat het oor niet kan: ze bewaart het verschil tussen *word* en *wordt*.',
          },
        },
        {
          text: 'Als de regel zo simpel is, waarom gaat het dan zo vaak mis? Dominiek Sandra, Steven Frisson en Frans Daems (1999) lieten zien dat je geheugen de vaakst geziene vorm aanbiedt, en dat de fout groeit met de afstand tussen onderwerp en persoonsvorm (zie d17). Daar komt een tweede val bij. Kathryn Bock en Carol Miller (1991) beschreven *attractie*: in *The key to the cabinets are…* trekt het dichtstbijzijnde naamwoord de persoonsvorm naar zich toe. Ook in het Nederlands lokt een meervoud vlak vóór het werkwoord een verkeerde vorm uit. De remedie is geen beter oor maar een betere zoektocht: vind eerst het onderwerp.',
          rule: 'Twee vallen: de frequente homofoon (ik wordt) en attractie door een naamwoord vlakbij. Zoek het onderwerp, niet de klank.',
          mark: {
            q: 'Tik het onderwerp van wordt',
            sentence: 'De sleutel van de twee kasten die op zolder staan, wordt vanmiddag gezocht.',
            targets: [0, 1],
            note: 'Wie of wat wordt gezocht? De sleutel. Kasten en staan staan ertussen en trekken aan de persoonsvorm, maar het onderwerp is enkelvoud: wordt.',
          },
        },
        {
          text: 'Een deelwoord dat vóór een naamwoord staat, is op weg naar een nieuw woord. *Verwacht*, *bekend* en *gesloten* gedragen zich als bijvoeglijke naamwoorden: ze krijgen *on-* (*onverwacht*, *onbekend*), ze laten *zeer* toe (*zeer bekend*) en soms een trap van vergelijking (*bekender*). Morfologen zoals Geert Booij beschrijven dat als conversie: een werkwoordsvorm wordt opgenomen in een andere woordsoort. Voor de spelling betekent het dat de buigings-e een aparte laag is, buiten op het deelwoord: *beantwoord* + *d* + *e*. De *-de* van de verleden tijd is een andere laag, direct op de stam. Bouw het woord laag voor laag.',
          rule: 'Bijvoeglijk deelwoord: [[stam + d] + e]. Verleden tijd: [stam + de]. Dezelfde letters, een andere bouw.',
          bracket: {
            q: 'Bouw de beantwoorde vraag van binnen naar buiten',
            tree: '[[[be antwoord] d] e]',
            nodes: [
              {
                w: 'beantwoord',
                cat: 'werkwoordstam',
                note: 'be- plus antwoord: de stam van beantwoorden. Omdat be- onbeklemtoond is, krijgt het deelwoord straks geen ge-.',
              },
              {
                w: 'beantwoordd',
                form: 'beantwoord',
                cat: 'voltooid deelwoord',
                note: 'Stam + d. Op papier zie je één d, want een dubbele medeklinker aan het woordeinde schrijven we niet. De tweede d zit erin verstopt.',
              },
              {
                w: 'beantwoordde',
                form: 'beantwoorde',
                cat: 'bn',
                note: 'Deelwoord + buigings-e: de beantwoorde vraag. Eén d, want de e komt op het deelwoord, niet op de stam.',
              },
            ],
            traps: [
              { w: 'antwoordd', note: 'be- hoort bij de stam. Eerst beantwoord, dan pas de uitgang.' },
              {
                w: 'de',
                note: 'd en e zijn hier twee aparte stappen: eerst het deelwoord, dan de buigings-e. Plak je ze eerst aan elkaar, dan bouw je de uitgang -de van de verleden tijd (beantwoordde), en dat is een ander woord.',
              },
            ],
            note: 'Drie lagen: stam, deelwoord, bijvoeglijk naamwoord. De verleden tijd beantwoordde heeft maar twee lagen, stam + de, en daarom twee d’s op de naad.',
          },
        },
        {
          text: 'Leenwerkwoorden zijn de lakmoesproef van het systeem. Geen enkel geleend werkwoord wordt in het Nederlands sterk: *gecrasht*, *geüpdatet*, *gestreamd*, nooit een nieuwe klinkerwisseling. Steven Pinker (1999) ziet daarin het bewijs dat de zwakke vervoeging een echte regel is, de standaard die alles opvangt wat niet in het geheugen staat; Gary Marcus en collega’s (1995) lieten hetzelfde zien voor de Duitse meervouds-s. De Woordenlijst houdt de Engelse stam intact en zet er de Nederlandse uitgangen achter: *updaten* geeft *ik update*, *hij updatet*, *updatete*, *geüpdatet*. De laatste klank van de stam kiest -te of -de; een stomme e aan het eind telt niet mee. Een trema (*geüpdatet*) of een koppelteken (*ge-sms’t*, *ge-e-maild*) houdt de delen leesbaar.',
          rule: 'Leenwerkwoorden zijn altijd zwak: Engelse stam, Nederlandse uitgang, ’t kofschip op de klank.',
          paradigm: {
            q: 'Vul de vormen in volgens de Woordenlijst',
            cols: ['verleden tijd', 'voltooid deelwoord'],
            rows: [
              { label: 'updaten', cells: [{ fill: 'updatete', hint: 'Laatste klank [t], de stomme e telt niet: update + te.' }, 'geüpdatet'] },
              { label: 'crashen', cells: ['crashte', { fill: 'gecrasht', hint: 'De sj-klank is stemloos: t.' }] },
              {
                label: 'streamen',
                cells: [
                  { fill: 'streamde', hint: 'Laatste klank [m]: stemhebbend, dus de.' },
                  { fill: 'gestreamd', hint: 'Engelse stam, Nederlandse d: gestreamd.' },
                ],
              },
              {
                label: 'sms’en',
                cells: [
                  { fill: 'sms’te', hint: 'De naam van de letter s eindigt op [s]: te. De apostrof blijft staan.' },
                  { fill: 'ge-sms’t', hint: 'Een koppelteken na ge- bij een afkorting: ge-sms’t.' },
                ],
              },
              { label: 'e-mailen', cells: ['e-mailde', { fill: 'ge-e-maild', hint: 'Koppelteken na ge- vóór een losse letter: ge-e-maild.' }] },
            ],
            extra: ['updatede', 'geüpdated', 'gestreamed', 'gesmst'],
            note: 'Vijf Engelse stammen, één Nederlands systeem. Wat je niet hoort (de t van geüpdatet) en wat je in het Engels nooit ziet (de d van gestreamd) volgt allebei uit de regel.',
          },
        },
      ],
    },
    {
      kind: 'highlight',
      id: 'kleuren',
      prompt: 'Welke werkwoordsvorm is het?',
      intro: 'Kleur elke werkwoordsvorm met de stift van zijn functie. De andere woorden mag je overslaan.',
      pens: [
        { id: 'pv', label: 'persoonsvorm', tag: 'verandert mee met de tijd', ask: 'Verandert dit woord als je de zin in een andere tijd zet?', accent: 'blue' },
        {
          id: 'vd',
          label: 'voltooid deelwoord',
          tag: 'bij hebben, zijn of worden',
          ask: 'Hoort dit woord bij een hulpwerkwoord en blijft het staan als de tijd verandert?',
          accent: 'orange',
        },
        {
          id: 'bn',
          label: 'bijvoeglijk',
          tag: 'deelwoord + e vóór een naamwoord',
          ask: 'Staat dit deelwoord met een e vóór een zelfstandig naamwoord?',
          accent: 'green',
        },
      ],
      words: [
        { t: 'De' },
        { t: 'verwachte', role: 'bn' },
        { t: 'storm' },
        { t: 'werd', role: 'pv' },
        { t: 'afgezwakt,', role: 'vd' },
        { t: 'maar' },
        { t: 'de' },
        { t: 'verbrande', role: 'bn' },
        { t: 'bomen' },
        { t: 'worden', role: 'pv' },
        { t: 'pas' },
        { t: 'morgen' },
        { t: 'geruimd.', role: 'vd' },
      ],
      done: {
        title: 'Zes vormen, drie functies',
        text: 'werd en worden veranderen mee met de tijd. afgezwakt en geruimd horen bij worden en blijven staan. verwachte en verbrande staan met een e vóór een naamwoord: deelwoord + e, dus één t en één d.',
      },
    },
    {
      kind: 'proofread',
      id: 'klacht',
      prompt: 'Lees de klacht na',
      intro: 'Er zitten vijf werkwoordsfouten in. Pas op: niet elke dubbele t is fout, en niet elke word zonder t.',
      header: { to: 'de klantenservice', subject: 'Mijn bestelling' },
      tokens: [
        { t: 'Geachte' },
        { t: 'heer' },
        { t: 'De' },
        { t: 'Wit,' },
        { t: 'Ik' },
        { t: 'wordt', fix: 'word', why: 'Ik krijgt de kale stam: ik word. Wordt is de vaakst geziene vorm en glipt er daarom in.' },
        { t: 'al' },
        { t: 'twee' },
        { t: 'weken' },
        { t: 'aan' },
        { t: 'het' },
        { t: 'lijntje' },
        { t: 'gehouden.' },
        { t: 'Uw' },
        { t: 'collega' },
        { t: 'verwachtte' },
        { t: 'dat' },
        { t: 'het' },
        { t: 'pakket' },
        { t: 'vrijdag' },
        { t: 'zou' },
        { t: 'komen,' },
        { t: 'maar' },
        { t: 'er' },
        { t: 'is' },
        { t: 'niets' },
        { t: 'gebeurt.', fix: 'gebeurd.', why: 'Hoort bij is: voltooid deelwoord. Er is niets gevallen, dus gebeurd met de d van gebeurde.' },
        { t: 'De' },
        { t: 'verwachtte', fix: 'verwachte', why: 'Vóór levertijd staat een bijvoeglijk deelwoord: verwacht + e, één t. Verwachtte is de verleden tijd.' },
        { t: 'levertijd' },
        { t: 'was' },
        { t: 'drie' },
        { t: 'dagen.' },
        { t: 'Als' },
        { t: 'u' },
        { t: 'mij' },
        { t: 'vandaag' },
        { t: 'antwoord,', fix: 'antwoordt,', why: 'U krijgt altijd stam + t: u antwoordt.' },
        { t: 'word' },
        { t: 'ik' },
        { t: 'misschien' },
        { t: 'nog' },
        { t: 'een' },
        { t: 'tevreden' },
        { t: 'klant.' },
        { t: 'De' },
        { t: 'app' },
        { t: 'die' },
        { t: 'ik' },
        { t: 'gisteren' },
        { t: 'geüpdated', fix: 'geüpdatet', why: 'Stam update, laatste klank [t]: Nederlandse uitgang t, geen Engelse d.' },
        { t: 'heb,' },
        { t: 'zegt' },
        { t: 'dat' },
        { t: 'het' },
        { t: 'systeem' },
        { t: 'gecrasht' },
        { t: 'is.' },
      ],
      done: {
        title: 'Alle vijf gevonden',
        text: 'word (ik), gebeurd (bij is), verwachte (vóór levertijd), antwoordt (u) en geüpdatet (Engelse stam, Nederlandse t). Uw collega verwachtte, word ik en gecrasht waren goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'updatete',
      prompt: 'Luister en typ de zin.',
      sentence: 'Ze updatete de app, maar daarna crashte hij meteen.',
      right: 'Goed: update + te, met de stomme e van de Engelse stam ertussen, en crash + te omdat de sj-klank stemloos is.',
      wrong: 'Let op: updatete is update + te (de stomme e blijft staan) en crashte is crash + te. Vergeet de hoofdletter, de komma en de punt niet.',
    },
    {
      kind: 'bet',
      id: 'ik-wordt',
      prompt: 'Welke fout komt in echte teksten vaker voor?',
      options: ['ik wordt', 'hij word'],
      answer: 'ik wordt',
      why: 'Wordt komt veel vaker voor dan word: bij hij, zij, het en in de lijdende vorm. Sandra, Frisson en Daems lieten zien dat je geheugen de vaakst geziene homofoon aanbiedt. Daarom glipt wordt er ook achter ik in.',
    },
    {
      kind: 'swipe',
      id: 'bewezen',
      prompt: 'Klopt deze zin?',
      cards: [
        {
          t: 'In hij vindt schrijf je een t die je niet hoort, omdat elke derde persoon stam + t krijgt.',
          ok: true,
          why: 'Hij loopt, dus hij vindt. De spelling toont het morfeem, niet de klank.',
        },
        {
          t: 'Het Afrikaans heeft hetzelfde d/t-probleem als het Nederlands.',
          ok: false,
          fix: 'Het Afrikaans vervoegt niet meer: hy vind',
          why: 'Zonder persoonsuitgang is er niets om fout te schrijven.',
        },
        { t: 'Het Duits schrijft er findet: een extra e maakt de uitgang hoorbaar.', ok: true, why: 'Daarom heeft een Duitser geen dt-regel nodig.' },
        {
          t: 'Volgens Bock en Miller lokt een naamwoord vlak vóór de persoonsvorm fouten uit.',
          ok: true,
          why: 'Attractie: het dichtstbijzijnde naamwoord trekt aan het werkwoord.',
        },
        {
          t: 'De verleden tijd verwachtte en het bijvoeglijk naamwoord verwachte klinken verschillend.',
          ok: false,
          fix: 'Ze klinken precies hetzelfde',
          why: 'Alleen de bouw verschilt: stam + te tegenover deelwoord + e. Dat zie je, dat hoor je niet.',
        },
        {
          t: 'Een geleend werkwoord kan in het Nederlands sterk worden.',
          ok: false,
          fix: 'Leenwerkwoorden zijn altijd zwak',
          why: 'Gecrasht, geüpdatet, gestreamd: de zwakke vervoeging is de standaardregel die alles opvangt.',
        },
        { t: 'Ge-sms’t schrijf je met een koppelteken en een apostrof.', ok: true, why: 'Zo blijft de afkorting sms leesbaar tussen ge- en t.' },
      ],
    },
  ],
};
