import type { LessonInput } from '../../schema';

/**
 * Die, dat, wat en wie: betrekkelijke voornaamwoorden die terugwijzen naar hun antecedent, daarna
 * hun, hen en ze, en kort zich tegenover zichzelf. De norm volgt de ANS en Taaladvies; waar de
 * spreektaal afwijkt, staat dat erbij.
 */
export const LES_W24: LessonInput = {
  id: 'w24',
  stage: 'bachelor',
  domain: 'syn',
  also: ['morf', 'sem'],
  title: 'Die, dat, wat en wie',
  skill: 'Woorden',
  icon: 'die',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Een voornaamwoord dat terugkijkt',
      panels: [
        {
          text: 'Een *betrekkelijk voornaamwoord* opent een bijzin en kijkt terug naar een woord ervoor: het *antecedent*. Dat antecedent beslist. Een de-woord of een meervoud krijgt *die*: *de kast die*, *de boeken die*. Een het-woord in het enkelvoud krijgt *dat*: *het boek dat*. Verandert het antecedent, dan verandert het voornaamwoord mee: maak van *de kast* een *kastje*, en je krijgt *het kastje dat*.',
          rule: 'die: de-woorden en meervoud. dat: het-woorden in het enkelvoud.',
          morph: {
            q: 'Verander het antecedent, en kies het voornaamwoord dat meeverandert',
            rounds: [
              {
                thing: 'kast',
                from: 'de kast die ik kocht',
                ask: 'maak de kast klein',
                effect: 'klein',
                options: ['het kastje die ik kocht', 'het kastje dat ik kocht'],
                answer: 'het kastje dat ik kocht',
                note: 'Een verkleinwoord is altijd een het-woord. Dus wordt die ook dat.',
              },
              {
                thing: 'boek',
                from: 'het boek dat ik las',
                ask: 'maak er veel boeken van',
                effect: 'veel',
                options: ['de boeken dat ik las', 'de boeken die ik las', 'de boeken wat ik las'],
                answer: 'de boeken die ik las',
                note: 'Meervoud krijgt altijd die, ook als het enkelvoud een het-woord is.',
              },
              {
                thing: 'huis',
                from: 'het huis dat te koop staat',
                ask: 'veel kleine huizen',
                effect: 'klein-veel',
                options: ['de huisjes die te koop staan', 'de huisjes dat te koop staan', 'het huisjes dat te koop staat'],
                answer: 'de huisjes die te koop staan',
                note: 'Verkleinwoord in het meervoud: de huisjes. Het meervoud wint, dus die.',
              },
              {
                thing: 'glas',
                from: 'het glas dat ik brak',
                ask: 'maak het glas rood',
                effect: 'kleur',
                paint: 'rood',
                options: ['het rode glas dat ik brak', 'het rode glas die ik brak'],
                answer: 'het rode glas dat ik brak',
                note: 'Een bijvoeglijk naamwoord verandert het geslacht niet. Glas blijft een het-woord: dat.',
              },
            ],
            note: 'Het voornaamwoord kijkt naar het antecedent zoals het er nu staat: verkleind, in het meervoud of gekleurd.',
          },
        },
        {
          text: 'Soms is er geen zelfstandig naamwoord om naar terug te kijken. Dan komt *wat*: na *alles*, *iets*, *niets*, *veel* en *weinig* (*alles wat je zegt*), na *het* met een overtreffende trap (*het mooiste wat ik ken*) en na een hele zin (*Hij kwam te laat, wat me ergerde.*). Wat niet hoort in verzorgde taal: *wat* na een het-woord. *Het boek wat ik lees* hoor je overal, maar de norm zegt *het boek dat ik lees*.',
          rule: 'wat: na alles, iets, niets, veel, weinig, het mooiste en een hele zin. Na een het-woord: dat.',
          lab: {
            label: 'Tik een antecedent',
            chips: [
              { k: 'alles', out: 'alles wat je zegt', note: 'Geen zelfstandig naamwoord, dus geen geslacht: wat.' },
              { k: 'het mooiste', out: 'het mooiste wat ik ken', note: 'Een overtreffende trap als zelfstandig naamwoord: meestal wat.' },
              { k: 'Hij kwam te laat,', out: 'Hij kwam te laat, wat me ergerde.', note: 'Wat verwijst naar de hele zin. Dat kan hier niet.' },
              { k: 'het boek', out: 'het boek dat ik lees', note: 'Een het-woord: dat. Het boek wat ik lees is spreektaal.' },
            ],
          },
          deep: {
            q: 'Is iets dat dan fout?',
            a: 'Niet altijd. Na *iets*, *het enige* en *het mooiste* komt ook *dat* voor, vooral als het om iets bepaalds gaat: *Ik heb iets gekocht dat je mooi zult vinden.* *Wat* is daar de gewone keuze, *dat* is geen fout. Na een hele zin is het wel duidelijk: alleen *wat*.',
          },
        },
        {
          text: 'Na een voorzetsel verandert de vorm. Bij een persoon wordt het *voorzetsel + wie*: *de vrouw met wie ik werk*, *de man op wie ik wacht*. Bij een ding wordt het *waar + voorzetsel*, aan elkaar: *het huis waarin ik woon*, *de pen waarmee ik schrijf*; dat is hetzelfde R-woord als *ermee* (zie De voorzetselgroep). *De pen met die* bestaat niet, en *de collega waarmee ik werk* hoor je wel, maar verzorgder is *met wie*. *Welke* (*de stad, welke …*) is formeel en klinkt ouderwets: kies gewoon *die* of *dat*.',
          rule: 'Persoon: voorzetsel + wie. Ding: waar + voorzetsel.',
          cast: {
            q: 'Tik aan wat de zin vraagt',
            rounds: [
              {
                text: 'de … met wie ik praat',
                ask: 'Tik alles waarbij met wie past',
                cast: ['visser', 'boot', 'mes', 'pan', 'huis'],
                answer: ['visser'],
                then: {
                  q: 'En bij de boot?',
                  options: ['de boot waarmee ik vaar', 'de boot met wie ik vaar', 'de boot met die ik vaar'],
                  answer: 'de boot waarmee ik vaar',
                },
                note: 'Wie is voor personen. Bij een ding: waar + voorzetsel, aan elkaar geschreven.',
              },
              {
                text: 'het … waarin ik woon',
                ask: 'Tik alles waar deze woorden over kunnen gaan',
                cast: ['huis', 'kasteel', 'visser', 'pan', 'mes'],
                answer: ['huis', 'kasteel'],
                then: {
                  q: 'En bij de koning die in het kasteel woont?',
                  options: ['de koning bij wie ik logeer', 'de koning bij die ik logeer', 'de koning wie ik bij logeer'],
                  answer: 'de koning bij wie ik logeer',
                },
                note: 'Huis en kasteel: dingen en het-woorden, dus het … waarin. Een persoon krijgt voorzetsel + wie, en dat voorzetsel blijft vooraan staan.',
              },
            ],
            note: 'Hier kiest niet het lidwoord, maar de betekenis van het antecedent: persoon of ding.',
          },
        },
        {
          text: 'Wat telt: het lidwoord of de betekenis? Bij het betrekkelijk voornaamwoord wint in verzorgde taal het lidwoord: *het meisje dat daar zingt* (zie De, het en hij). Hetzelfde geldt voor woorden voor groepen: *het kabinet dat besloot*, *het publiek dat klapte*, *het team dat won*. Er zitten veel mensen in, maar het blijft een het-woord in het enkelvoud, en ook de persoonsvorm blijft enkelvoud: *Het publiek klapte.* In spreektaal schuift de betekenis wel eens voor (*het meisje die*), maar dat is geen verzorgde taal.',
          rule: 'Grammatica boven betekenis: het meisje dat, het team dat, met een persoonsvorm in het enkelvoud.',
          quiz: {
            q: 'Welke zin is verzorgde taal?',
            options: ['Het team dat gisteren won, viert feest.', 'Het team die gisteren won, viert feest.', 'Het team dat gisteren won, vieren feest.'],
            answer: 'Het team dat gisteren won, viert feest.',
            why: 'Team is een het-woord in het enkelvoud: dat, en een persoonsvorm in het enkelvoud. Ook al bestaat een team uit veel spelers.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'antecedent',
      prompt: 'die, dat of wat?',
      buckets: ['die', 'dat', 'wat'],
      items: [
        { t: 'het huis … we kochten', b: 1 },
        { t: 'de mensen … daar wonen', b: 0 },
        { t: 'alles … je zegt', b: 2 },
        { t: 'het plorkje … ik vond', b: 1 },
        { t: 'de wibbels … ik kocht', b: 0 },
        { t: 'Hij won, … niemand had verwacht.', b: 2 },
        { t: 'het personeel … staakt', b: 1 },
        { t: 'er is veel … ik niet weet', b: 2 },
        { t: 'het meisje … zingt', b: 1 },
        { t: 'de boeken … ik las', b: 0 },
      ],
      why: 'die bij de-woorden en meervoud, ook bij verzonnen wibbels. dat bij het-woorden, ook bij het plorkje: -je maakt er een het-woord van. wat na alles, veel en een hele zin.',
    },
    {
      kind: 'fix',
      id: 'boek-wat',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Het boek wat ik nu lees, is erg spannend.',
      wrong: 2,
      answer: 'dat',
      why: 'Boek is een het-woord met een geslacht om te volgen: dat. Wat na een het-woord is spreektaal.',
    },
    {
      kind: 'type',
      id: 'waarmee',
      prompt: 'Vul het betrekkelijk voornaamwoord in, als één woord.',
      before: 'Dit is de pen',
      after: 'ik al mijn brieven schrijf.',
      hint: 'waar…',
      answer: 'waarmee',
      why: 'Een ding na een voorzetsel: waar + met wordt waarmee, aan elkaar. Met wordt mee, net als in ermee.',
    },
    {
      kind: 'bet',
      id: 'met-wie',
      prompt: 'Welke zin is het meest verzorgd?',
      options: ['De collega met wie ik samenwerk, is ziek.', 'De collega waarmee ik samenwerk, is ziek.', 'De collega met die ik samenwerk, is ziek.'],
      answer: 'De collega met wie ik samenwerk, is ziek.',
      why: 'Bij een persoon: voorzetsel + wie. Waarmee hoor je vaak bij personen, maar met wie is verzorgder. Met die bestaat niet.',
    },
    {
      kind: 'explain',
      id: 'verdieping',
      title: 'Hun, hen en ze',
      panels: [
        {
          text: 'Nu de persoonlijke voornaamwoorden voor meer mensen. In verzorgde schrijftaal hangt de vorm af van de functie in de zin. *Hun* is het *meewerkend voorwerp*: *Ik geef hun een boek.* *Hen* is het *lijdend voorwerp* (*Ik heb hen gezien*) en staat ook na een voorzetsel (*met hen*, *aan hen*, *voor hen*). Een toets: kun je de zin omzetten met *aan* of *voor*, zoals *Ik geef een boek aan hen*? Dan is het zonder voorzetsel *hun*.',
          rule: 'hun: meewerkend voorwerp zonder voorzetsel. hen: lijdend voorwerp en na een voorzetsel.',
          paradigm: {
            q: 'Kies hun of hen voor elke zin',
            cols: ['verzorgde vorm'],
            rows: [
              { label: 'Ik stuur … een kaart.', cells: [{ fill: 'hun', hint: 'Een kaart aan hen: meewerkend voorwerp, dus hun.' }] },
              { label: 'Ik heb … gisteren gezien.', cells: [{ fill: 'hen', hint: 'Wie zag ik? Lijdend voorwerp: hen.' }] },
              { label: 'Ik praat vaak met …', cells: [{ fill: 'hen', hint: 'Na een voorzetsel: hen.' }] },
              { label: 'Het is … niet gelukt.', cells: [{ fill: 'hun', hint: 'Lukken heeft een meewerkend voorwerp, net als in het is mij gelukt: hun.' }] },
              { label: 'We hebben … uitgenodigd.', cells: [{ fill: 'hen', hint: 'Wie nodigden we uit? Lijdend voorwerp: hen.' }] },
            ],
            extra: ['zij'],
            note: 'Twee keer hun, drie keer hen. Zij is het onderwerp en past hier nergens.',
          },
        },
        {
          text: 'Dit onderscheid is bedacht. Grammatici in de zeventiende eeuw wilden dat het Nederlands naamvallen had, zoals het Latijn, en de verdeling tussen *hun* en *hen* gaat terug op een voorstel van de grammaticus Christiaen van Heule uit 1633. In de spreektaal is ze nooit echt aangeslagen: veel sprekers zeggen *hun* in elke functie. In Nederland hoor je zelfs *hun* als onderwerp: *Hun hebben gewonnen.* Dat geldt als substandaard en wordt streng beoordeeld; in verzorgde taal is het onderwerp *zij* of *ze*.',
          rule: 'Hun als onderwerp is substandaard. Het onderwerp is zij (met nadruk) of ze (zonder nadruk).',
          lab: {
            label: 'Tik een zin',
            chips: [
              { k: 'Hun hebben gewonnen.', out: 'substandaard', note: 'Hun als onderwerp: veel gehoord, maar geen standaardtaal.' },
              { k: 'Zij hebben gewonnen.', out: 'standaard, met nadruk', note: 'Zij kun je beklemtonen: zij, niet wij.' },
              { k: 'Ze hebben gewonnen.', out: 'standaard, zonder nadruk', note: 'Ze is de gewone, onbeklemtoonde vorm.' },
              { k: 'Ik heb hun gezien.', out: 'spreektaal', note: 'In verzorgde taal: Ik heb hen gezien, of Ik heb ze gezien.' },
            ],
          },
        },
        {
          text: 'Twijfel je? Dan is *ze* bijna altijd veilig, als lijdend voorwerp (*Ik heb ze gezien*) en als meewerkend voorwerp (*Ik heb ze een kaart gestuurd*). Op twee plekken gaat het niet. Na een voorzetsel schrijf je in verzorgde taal *hen*, niet *met ze*. En *ze* kan geen klemtoon dragen: *Ik zag hén, niet jullie.* Let ook op dingen: *hun* en *hen* zijn voor personen, dus *De boeken? Ik heb ze gelezen*, nooit *hen*.',
          rule: 'ze is veilig als voorwerp. Niet na een voorzetsel, niet met klemtoon. Bij dingen nooit hun of hen.',
          quiz: {
            q: 'In welke zin kun je hen in verzorgde taal niet door ze vervangen?',
            options: ['Ik heb hen gisteren gebeld.', 'Zonder hen was het mislukt.', 'We hebben hen uitgenodigd.'],
            answer: 'Zonder hen was het mislukt.',
            why: 'Na een voorzetsel is ze spreektaal. In verzorgde taal blijft het zonder hen.',
          },
        },
      ],
    },
    {
      kind: 'chat',
      id: 'appje',
      prompt: 'App met je studiegenoot',
      intro: 'Kies telkens de vorm die past in verzorgde taal.',
      contact: { name: 'Noor', role: 'je studiegenoot', initials: 'N' },
      rounds: [
        {
          say: 'Heb je de twee nieuwe studenten al gesproken?',
          options: ['Ja, ik heb hun gisteren gesproken.', 'Ja, ik heb hen gisteren gesproken.'],
          right: 1,
          fix: 'hun → hen',
          why: 'Wie heb je gesproken? Lijdend voorwerp: hen.',
        },
        {
          say: 'En wat heb je ze gegeven?',
          options: ['Ik heb hun de opdrachten gegeven.', 'Ik heb hen de opdrachten gegeven.'],
          right: 0,
          fix: 'hen → hun',
          why: 'De opdrachten aan hen: meewerkend voorwerp, dus hun.',
        },
        {
          say: 'Wie heeft het verslag eigenlijk geschreven?',
          options: ['Hun hebben het geschreven.', 'Zij hebben het geschreven.'],
          right: 1,
          fix: 'Hun → Zij',
          why: 'Het onderwerp is zij of ze. Hun als onderwerp is substandaard.',
        },
        {
          say: 'Ga je morgen met ze lunchen?',
          options: ['Ja, ik lunch morgen met hen.', 'Ja, ik lunch morgen met hun.'],
          right: 0,
          fix: 'met hun → met hen',
          why: 'Na een voorzetsel: hen.',
        },
      ],
      bye: 'Top, jij schrijft verzorgder dan mijn scriptiebegeleider. Tot morgen!',
    },
    {
      kind: 'sort',
      id: 'hun-hen',
      prompt: 'hun of hen?',
      buckets: ['hun', 'hen'],
      items: [
        { t: 'De docent gaf … een voldoende.', b: 0 },
        { t: 'Ik heb … gisteren gebeld.', b: 1 },
        { t: 'Zonder … was het mislukt.', b: 1 },
        { t: 'Ik heb … de weg gewezen.', b: 0 },
        { t: 'Dit cadeau is voor …', b: 1 },
        { t: 'Ik heb … beloofd te komen.', b: 0 },
        { t: 'De buren? Ik vertrouw … niet.', b: 1 },
        { t: 'We stuurden … een uitnodiging.', b: 0 },
        { t: 'Ik heb … geholpen met verhuizen.', b: 1 },
        { t: 'De film beviel … goed.', b: 0 },
      ],
      why: 'hun: meewerkend voorwerp, vaak om te zetten met aan of voor (een voldoende aan hen). hen: lijdend voorwerp (bellen, vertrouwen, helpen) en na een voorzetsel.',
    },
    {
      kind: 'fix',
      id: 'aan-hen',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Ik heb het pakket gisteren aan hun gegeven.',
      wrong: 6,
      answer: 'hen',
      why: 'Na een voorzetsel: hen. Zonder aan was het wel hun geweest: Ik heb hun het pakket gegeven.',
    },
    {
      kind: 'bet',
      id: 'van-heule',
      prompt: 'Waar komt het verschil tussen hun en hen vandaan?',
      options: ['Een grammaticus stelde het in 1633 voor', 'Het is altijd zo gesproken', 'Het komt uit het Frans'],
      answer: 'Een grammaticus stelde het in 1633 voor',
      why: 'Christiaen van Heule verdeelde de vormen naar het voorbeeld van naamvallen. Daarom voelt het onderscheid voor veel sprekers kunstmatig.',
    },
    {
      kind: 'explain',
      id: 'onderzoek',
      title: 'Een vorm zonder geslacht, twee lezingen en een gat in het systeem',
      panels: [
        {
          text: 'Waarom staat *wat* juist na *alles*, *iets*, *het mooiste* en een hele zin? Die hebben iets gemeen: geen zelfstandig naamwoord met een geslacht. *Die* en *dat* kopiëren het geslacht van hun antecedent; valt er niets te kopiëren, dan wordt het *wat*, de vorm zonder geslacht. Taalkundigen spreken van *d-vormen* (*die*, *dat*), verwant aan de aanwijzende voornaamwoorden, en *w-vormen* (*wie*, *wat*, *waar*), verwant aan de vraagwoorden. *Het boek wat ik lees* is dan een w-vorm die terrein wint waar wel een geslacht te kopiëren valt.',
          rule: 'd-vorm: kopieert een geslacht. w-vorm: als er geen geslacht is, of na een voorzetsel.',
          quiz: {
            q: 'Volgens deze analyse: waarom staat er wat in ‘Ze slaagde, wat niemand verwachtte’?',
            options: ['Een hele zin heeft geen geslacht om te kopiëren', 'Slagen is een het-woord', 'Na een komma staat altijd wat'],
            answer: 'Een hele zin heeft geen geslacht om te kopiëren',
            why: 'Een zin is geen zelfstandig naamwoord. Er valt niets te kopiëren, dus komt de vorm zonder geslacht. En na een komma kan best dat staan: het boek, dat ik las.',
          },
        },
        {
          text: '*Die* en *dat* zeggen niet of ze onderwerp of lijdend voorwerp zijn. *De agent die de verdachte zag* kan betekenen dat de agent keek, of dat de verdachte keek. Vaak beslist pas de persoonsvorm aan het eind, via het getal: in *de agent die de verdachten zagen* keken de verdachten. Lezers kiezen eerst de onderwerpslezing en struikelen als die niet klopt (onder meer Lyn Frazier, 1987). Willem Mak, Wietske Vonk en Herbert Schriefers (2002) lieten zien dat betekenis helpt: is het antecedent een ding en het andere woord een mens, zoals in *het boek dat de student leest*, dan valt dat struikelen weg.',
          rule: 'die is geen naamval: het getal van de persoonsvorm beslist wie wat doet.',
          mark: {
            q: 'Tik het woord dat beslist wie er keek',
            sentence: 'Dat is de agent die de verdachten zagen.',
            targets: [7],
            note: 'zagen is meervoud. Het past alleen bij de verdachten: zij zagen de agent.',
          },
        },
        {
          text: 'Waarom zeggen zo veel mensen *hun hebben*, ondanks de afkeuring? Geertje van Bergen en collega’s (2011) gaven hun artikel erover de titel *Leve hun!*. Hun verklaring: het systeem heeft een gat. *Zij* kan ook één vrouw zijn, en *ze* is zwak en kan ook naar dingen verwijzen; *hun* is ondubbelzinnig meervoud en verwijst naar mensen. De norm blijft *zij* of *ze*, maar de verandering heeft een logica.',
          rule: 'Een afgekeurde vorm kan een gat in het systeem vullen: hun is meervoud én menselijk.',
          quiz: {
            q: 'Welke zin past het best bij deze verklaring?',
            options: ['Hun hebben gewonnen (over spelers).', 'Hun liggen op tafel (over boeken).'],
            answer: 'Hun hebben gewonnen (over spelers).',
            why: 'Volgens de verklaring vult hun een gat bij personen: meervoud én menselijk. Voor boeken is dat gat er niet.',
          },
        },
        {
          text: 'Tot slot het wederkerend voornaamwoord: *zich* tegenover *zichzelf*. Tanya Reinhart en Eric Reuland (1993) gebruikten dat Nederlandse paar in hun theorie van *reflexiviteit*. Een werkwoord dat uit zichzelf al terugslaat op het onderwerp, neemt *zich*: *Max schaamt zich*, *Max vergist zich*. Een gewoon werkwoord, dat meestal over iemand anders gaat, heeft *zichzelf* nodig: *Max haat zichzelf*, niet *Max haat zich*. In een plaatsbepaling past weer *zich*: *Max heeft geen geld bij zich*.',
          rule: 'zich: bij echt wederkerende werkwoorden en in een plaatsbepaling. zichzelf: als een gewoon werkwoord terugslaat.',
          paradigm: {
            q: 'Zich of zichzelf?',
            cols: ['vorm'],
            rows: [
              { label: 'Max schaamt …', cells: [{ fill: 'zich', hint: 'Zich schamen is echt wederkerend: zich.' }] },
              { label: 'Max haat …', cells: [{ fill: 'zichzelf', hint: 'Haten gaat meestal over een ander. Om terug te slaan: zichzelf.' }] },
              { label: 'Max vergist …', cells: [{ fill: 'zich', hint: 'Je kunt niet iemand anders vergissen: zich.' }] },
              { label: 'Max heeft geen geld bij …', cells: [{ fill: 'zich', hint: 'Een plaatsbepaling: bij zich.' }] },
            ],
            note: 'Drie keer zich, één keer zichzelf. Zichzelf maakt van een gewoon werkwoord een terugslaand werkwoord.',
          },
        },
      ],
    },
    {
      kind: 'ambiguity',
      id: 'agent',
      prompt: 'Eén zin, twee lezingen',
      intro: 'Kies een lezing en zoek de zin die alleen dát kan betekenen.',
      sentence: 'Dat is de agent die de verdachte zag.',
      meanings: [
        {
          id: 'agent',
          label: 'De agent zag de verdachte',
          highlight: ['de agent'],
          right: 'Klopt. Zag is enkelvoud en past niet bij de verdachten: dus keek de agent.',
        },
        {
          id: 'verdachte',
          label: 'De verdachte zag de agent',
          highlight: ['de verdachte'],
          right: 'Klopt. Zagen is meervoud en hoort bij de verdachten: zij keken.',
        },
      ],
      options: [
        { t: 'Dat is de agent die de verdachten zag.', fits: 'agent' },
        { t: 'Dat is de agent die de verdachten zagen.', fits: 'verdachte' },
        { t: 'Dat is de agent die gisteren de verdachte zag.', fits: null, note: 'Nog steeds allebei mogelijk: er kwam alleen een tijd bij.' },
      ],
      done: {
        title: 'Het getal beslist',
        text: 'Die zegt niet of het onderwerp of lijdend voorwerp is. Geef de twee naamwoorden een verschillend getal, en de persoonsvorm kiest.',
      },
    },
    {
      kind: 'highlight',
      id: 'ze-ze-ze',
      prompt: 'Welke vorm hoort hier in verzorgde taal?',
      intro: 'Elke ze is een ander zinsdeel. Kleur hem met de vorm die op zijn plek hoort.',
      pens: [
        { id: 'zij', label: 'zij', tag: 'onderwerp', ask: 'Doet deze ze zelf iets? Dan is het het onderwerp: zij.', accent: 'blue' },
        { id: 'hen', label: 'hen', tag: 'lijdend voorwerp', ask: 'Ondergaat deze ze de handeling? Lijdend voorwerp: hen.', accent: 'orange' },
        { id: 'hun', label: 'hun', tag: 'meewerkend voorwerp', ask: 'Krijgt deze ze iets? Meewerkend voorwerp: hun.', accent: 'purple' },
      ],
      words: [
        { t: 'De' },
        { t: 'buren?' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'ze', role: 'hen' },
        { t: 'gebeld' },
        { t: 'en' },
        { t: 'ze', role: 'hun' },
        { t: 'een' },
        { t: 'fles' },
        { t: 'wijn' },
        { t: 'beloofd,' },
        { t: 'want' },
        { t: 'ze', role: 'zij' },
        { t: 'hebben' },
        { t: 'ons' },
        { t: 'vaak' },
        { t: 'geholpen.' },
      ],
      done: {
        title: 'Drie keer ze, drie functies',
        text: 'Ik heb hen gebeld, hun een fles wijn beloofd, want zij hebben ons geholpen. Ze dekt alle drie, en daarom is ze zo veilig.',
      },
    },
    {
      kind: 'proofread',
      id: 'eindredactie',
      prompt: 'Lees de mail na',
      intro: 'Er zitten vijf fouten met voornaamwoorden in. Pas op: niet elke hun is fout.',
      header: { to: 'het projectteam', subject: 'Verslag van de vergadering' },
      tokens: [
        { t: 'Het' },
        { t: 'verslag' },
        { t: 'wat', fix: 'dat', why: 'Verslag is een het-woord: dat.' },
        { t: 'ik' },
        { t: 'gisteren' },
        { t: 'stuurde,' },
        { t: 'was' },
        { t: 'niet' },
        { t: 'compleet.' },
        { t: 'De' },
        { t: 'klanten' },
        { t: 'hebben' },
        { t: 'hun' },
        { t: 'plannen' },
        { t: 'toegelicht.' },
        { t: 'Hun', fix: 'Zij', why: 'Het onderwerp is zij of ze, nooit hun.' },
        { t: 'willen' },
        { t: 'alles' },
        { t: 'wat' },
        { t: 'we' },
        { t: 'beloofden,' },
        { t: 'en' },
        { t: 'snel.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'hun', fix: 'hen', why: 'Bellen heeft een lijdend voorwerp: hen.' },
        { t: 'daarna' },
        { t: 'gebeld' },
        { t: 'en' },
        { t: 'hun' },
        { t: 'een' },
        { t: 'offerte' },
        { t: 'gestuurd.' },
        { t: 'Het' },
        { t: 'team' },
        { t: 'die', fix: 'dat', why: 'Team is een het-woord in het enkelvoud: dat.' },
        { t: 'het' },
        { t: 'project' },
        { t: 'leidt,' },
        { t: 'schaamt' },
        { t: 'zichzelf', fix: 'zich', why: 'Zich schamen is echt wederkerend: zich.' },
        { t: 'een' },
        { t: 'beetje' },
        { t: 'over' },
        { t: 'de' },
        { t: 'vertraging.' },
        { t: 'Morgen' },
        { t: 'praat' },
        { t: 'ik' },
        { t: 'met' },
        { t: 'hen.' },
      ],
      done: {
        title: 'Alle vijf gevonden',
        text: 'dat (het verslag), zij (onderwerp), hen (na bellen), dat (het team) en zich (zich schamen). Hun plannen, hun een offerte, alles wat en met hen waren goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'pen',
      prompt: 'Luister en typ de zin.',
      sentence: 'Dit is de pen waarmee ik alles opschrijf wat ik bedenk.',
      right: 'Goed: waarmee aan elkaar, en wat na alles.',
      wrong: 'Let op: waarmee is één woord, want waar en mee staan naast elkaar. En na alles komt wat.',
    },
    {
      kind: 'swipe',
      id: 'terugwijzen',
      prompt: 'Klopt deze zin?',
      cards: [
        { t: 'Wat verwijst naar antecedenten zonder zelfstandig naamwoord, zoals alles of een hele zin.', ok: true, why: 'Er valt geen geslacht te kopiëren.' },
        {
          t: 'Die laat zien of het onderwerp of lijdend voorwerp is.',
          ok: false,
          fix: 'Die is voor beide gelijk',
          why: 'Pas de persoonsvorm beslist, via het getal.',
        },
        { t: 'Het onderscheid tussen hun en hen gaat terug op een voorstel uit 1633.', ok: true, why: 'Van de grammaticus Christiaen van Heule.' },
        {
          t: 'Hun als onderwerp is standaardtaal geworden.',
          ok: false,
          fix: 'Het geldt nog steeds als substandaard',
          why: 'De norm is zij of ze. Wel heeft het een logica: hun is meervoud en menselijk.',
        },
        {
          t: 'Max haat zich is net zo goed als Max haat zichzelf.',
          ok: false,
          fix: 'Alleen Max haat zichzelf',
          why: 'Haten is geen wederkerend werkwoord; pas zichzelf laat het terugslaan.',
        },
        { t: 'Bij dingen gebruik je ze, niet hun of hen.', ok: true, why: 'De boeken? Ik heb ze gelezen.' },
        {
          t: 'De pen met die ik schrijf is verzorgde taal.',
          ok: false,
          fix: 'de pen waarmee ik schrijf',
          why: 'Bij een ding na een voorzetsel: waar + voorzetsel.',
        },
      ],
    },
  ],
};
