import type { LessonInput } from '../../schema';

/**
 * Masterles voor "Het woord": de vier functies van er volgens de ANS (presentatief of plaatsonderwerp,
 * plaatsaanduidend, kwantitatief en prepositioneel), het definietheidseffect, één er dat dubbel werk
 * doet, de vaste plek in het middenveld, de spelling van de R-woorden (ervan, daarvan, waarvan) en het
 * debat of er wel een onderwerp is (Bennis 1986). De R-woorden na een voorzetsel uit p7 en w24 en de
 * zwakke kwantoren van Milsark uit p15 worden hier gebruikt, niet herhaald.
 */
export const LES_W25: LessonInput = {
  id: 'w25',
  stage: 'master',
  domain: 'syn',
  also: ['sem', 'orth'],
  title: 'De vier gezichten van er',
  skill: 'Zinsbouw',
  icon: 'er',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Eén woordje, vier banen',
      panels: [
        {
          text: '*Er* is het kleinste zware woord van het Nederlands. De ANS onderscheidt vier functies, en je herkent ze met een vervangingstoets. Begin met het *presentatieve er*, ook *existentieel er* genoemd: *Er loopt een man op straat.* Het echte onderwerp is *een man*, en dat is onbepaald. Maak het bepaald en *er* verdwijnt: *De man loopt op straat*, niet *Er loopt de man op straat*. Dit *er* betekent niets. Het vult de eerste plek, zodat de persoonsvorm op plek twee kan staan en het nieuwe onderwerp verderop in de zin komt. In de schoolgrammatica heet het daarom *plaatsonderwerp*. Hetzelfde *er* staat in het onpersoonlijk passief, waar helemaal geen onderwerp is: *Er wordt gedanst.*',
          rule: 'Presentatief er: bij een onbepaald onderwerp, of helemaal geen onderwerp. Een bepaald onderwerp verdrijft het.',
          cast: {
            q: 'Tik aan wat de zin vraagt',
            rounds: [
              {
                text: 'Er ligt een mes naast de pan.',
                ask: 'Tik het echte onderwerp',
                cast: ['mes', 'pan', 'pim', 'koek'],
                answer: ['mes'],
                then: {
                  q: 'Wat is er in deze zin?',
                  options: ['een plaatsonderwerp zonder betekenis', 'het onderwerp', 'een plaatsbepaling: daar'],
                  answer: 'een plaatsonderwerp zonder betekenis',
                },
                note: 'Een mes is onbepaald, dus de zin begint met er. Zet er het mes en er moet weg: Het mes ligt naast de pan.',
              },
              {
                text: 'Er wordt gevist.',
                ask: 'Tik het onderwerp',
                cast: ['visser', 'vis', 'boot'],
                answer: [],
                note: 'Niets. Het onpersoonlijk passief heeft geen onderwerp, en toch staat er een er: het vult de eerste plek. De visser mag erbij als door-bepaling: Er wordt door de visser gevist.',
              },
              {
                text: 'De kip staat op de kast.',
                ask: 'Tik het onderwerp',
                cast: ['kip', 'kast', 'ei', 'glas'],
                answer: ['kip'],
                then: {
                  q: 'Welke zin kan ook?',
                  options: ['Er staat een kip op de kast.', 'Er staat de kip op de kast.'],
                  answer: 'Er staat een kip op de kast.',
                },
                note: 'Een bepaald onderwerp: geen er. Maak het onbepaald (een kip) en er komt vanzelf. Dat is het definietheidseffect.',
              },
            ],
            note: 'Drie keer kijken naar het onderwerp: onbepaald (er), afwezig (er) of bepaald (geen er).',
          },
        },
        {
          text: 'Het tweede *er* is een plaatsbepaling: *Ik woon er al jaren.* Dit is het zwakke broertje van *daar*. De toets: vervang het door *daar* en de zin blijft kloppen (*Ik woon daar al jaren*). Het verschil is klemtoon. *Daar* kun je beklemtonen en vooraan zetten (*Dáár woon ik*), *er* nooit: *Er woon ik* bestaat niet. Alleen het presentatieve *er* mag een zin openen. Begint een zin met *er*, dan weet je dus meteen welk *er* je leest.',
          rule: 'Plaatsaanduidend er = onbeklemtoond daar. Het staat in het middenveld, nooit vooraan.',
          mark: {
            q: 'Tik het er dat je door daar kunt vervangen',
            sentence: 'Er liggen mooie stranden aan die kust en we zijn er vorig jaar geweest.',
            targets: [10],
            note: 'Het tweede er is daar: we zijn daar geweest. Het eerste er is presentatief: het opent de zin voor het onbepaalde onderwerp mooie stranden.',
          },
        },
        {
          text: 'Het derde *er* telt. *Hoeveel koeken heb je? Ik heb er drie.* Het zelfstandig naamwoord is weggelaten en *er* neemt zijn plaats in, samen met een getal of een hoeveelheidswoord: *er drie*, *er veel*, *er geen*, *er genoeg*. De toets: zet het naamwoord terug en *er* moet weg: *Ik heb drie koeken*, niet *Ik heb er drie koeken*. Het werkt alleen bij een onbepaalde hoeveelheid van iets telbaars; *Ik heb er deze* kan niet. Een bijvoeglijk naamwoord mag wel blijven staan: *Ik heb er drie rode.*',
          rule: 'Kwantitatief er: een getal of hoeveelheid zonder naamwoord. Zet het naamwoord terug en er verdwijnt.',
          morph: {
            q: 'Verander de hoeveelheid, zonder het naamwoord te herhalen',
            rounds: [
              {
                thing: 'koek',
                from: 'Pim heeft een koek.',
                ask: 'maak er drie van',
                effect: 'veel',
                options: ['Pim heeft er drie.', 'Pim heeft er drie koeken.', 'Pim heeft drie er.'],
                answer: 'Pim heeft er drie.',
                note: 'Het naamwoord blijft weg, er neemt zijn plek in en het getal volgt. Er drie koeken is dubbelop: er en het naamwoord sluiten elkaar uit.',
              },
              {
                thing: 'glas',
                from: 'Pim heeft een glas.',
                ask: 'maak er veel kleine van',
                effect: 'klein-veel',
                options: ['Pim heeft er veel kleine.', 'Pim heeft veel kleine er.', 'Pim heeft er veel glaasjes.'],
                answer: 'Pim heeft er veel kleine.',
                note: 'Een bijvoeglijk naamwoord mag blijven: er veel kleine. Zodra glaasjes erbij staat, moet er weg: Pim heeft veel glaasjes.',
              },
              {
                thing: 'boek',
                from: 'Pim heeft drie boeken.',
                ask: 'maak ze rood, zonder boeken te herhalen',
                effect: 'kleur',
                paint: 'rood',
                options: ['Pim heeft er drie rode.', 'Pim heeft er drie rood.', 'Pim heeft er rode drie.'],
                answer: 'Pim heeft er drie rode.',
                note: 'Rode krijgt de -e van het weggelaten meervoud boeken, en het getal staat vóór het bijvoeglijk naamwoord, net als in drie rode boeken.',
              },
            ],
            note: 'Drie keer kwantitatief er: met een getal, met een hoeveelheidswoord en met een bijvoeglijk naamwoord. Het naamwoord zelf blijft steeds weg.',
          },
        },
        {
          text: 'Het vierde *er* hoort bij een voorzetsel: *Ik denk erover na.* *Er* vervangt hier *het* of *dat* na een voorzetsel (zie De voorzetselgroep, p7): niet *over het*, maar *erover*. Samen heten ze een *voornaamwoordelijk bijwoord*. Dit *er* kan van zijn voorzetsel losraken: *Ik denk er vaak over na.* De spelling volgt de zin. Staan *er* en het voorzetsel naast elkaar, dan schrijf je ze aan elkaar: *erover*, *ervan*, *erop*. Staat er iets tussen, dan los: *er vaak over*. Let op: *na* in *nadenken* is een partikel, geen voorzetsel, dus *erover na*, niet *eroverna*.',
          rule: 'Prepositioneel er: er + voorzetsel = voorzetsel + het. Naast elkaar aan elkaar, uit elkaar los.',
          lab: {
            label: 'Tik een stukje zin en kijk naar de spelling',
            chips: [
              { k: 'erover na', out: 'Ik denk erover na.', note: 'er en over staan naast elkaar: aan elkaar. Na is het partikel van nadenken en blijft los.' },
              { k: 'er vaak over na', out: 'Ik denk er vaak over na.', note: 'Vaak staat ertussen: er en over los.' },
              { k: 'ernaar uit', out: 'Ik kijk ernaar uit.', note: 'ernaar aan elkaar; uit is het partikel van uitkijken.' },
              { k: 'ervan uit', out: 'Ik ga ervan uit.', note: 'Niet er van uit: er en van staan naast elkaar en vormen samen ervan.' },
              { k: 'er niet van uit', out: 'Ik ga er niet van uit.', note: 'Niet staat ertussen: drie losse woorden.' },
            ],
          },
          deep: {
            q: 'Waarom kan over het niet?',
            a: 'Een onbeklemtoond *het* kan niet na een voorzetsel staan. Verwijst het naar een ding, dan wordt het een *R-woord*: *er* (zwak), *daar* (sterk), *hier* en *waar*. Bij een persoon blijft het gewone voornaamwoord: *Ik denk aan hem*. *Ik denk eraan* gaat over een ding of een zaak.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'vier-er',
      prompt: 'Welk er is dit?',
      buckets: ['presentatief', 'plaats (daar)', 'kwantitatief', 'prepositioneel'],
      items: [
        { t: 'Er loopt een kat door de tuin.', b: 0 },
        { t: 'Ik woon er al tien jaar.', b: 1 },
        { t: 'Hoeveel? Ik heb er twee.', b: 2 },
        { t: 'Ze denkt er niet aan.', b: 3 },
        { t: 'Er wordt gebeld.', b: 0 },
        { t: 'Ik ben er nog nooit geweest.', b: 1 },
        { t: 'Appels? Ik heb er geen.', b: 2 },
        { t: 'Hij kijkt er al weken naar uit.', b: 3 },
        { t: 'Van de tien vragen had ik er acht goed.', b: 2 },
        { t: 'Ze rekent er niet op.', b: 3 },
      ],
      why: 'Vooraan: presentatief, ook zonder onderwerp (er wordt gebeld). Vervangbaar door daar: plaats. Bij een getal of hoeveelheid zonder naamwoord (twee, geen, acht): kwantitatief. Met een voorzetsel verderop (aan, naar, op): prepositioneel.',
    },
    {
      kind: 'type',
      id: 'ervan-uit',
      prompt: 'Vul het voornaamwoordelijk bijwoord in, als één woord.',
      before: 'Ik ga',
      after: 'uit dat je morgen komt.',
      hint: 'er…',
      answer: 'ervan',
      why: 'Uitgaan van iets: van iets wordt ervan. Er en van staan naast elkaar, dus aan elkaar. Uit is het partikel van uitgaan en blijft los.',
    },
    {
      kind: 'fix',
      id: 'er-vooraan',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Er woon ik al tien jaar met veel plezier.',
      wrong: 0,
      answer: 'Daar',
      why: 'Een plaatsaanduidend er kan niet vooraan: alleen het presentatieve er opent een zin. Op de eerste plek moet de sterke vorm daar.',
    },
    {
      kind: 'bet',
      id: 'definiet',
      prompt: 'Welke zin is goed?',
      options: ['Er staat een fiets voor de deur.', 'Er staat de fiets voor de deur.', 'Er staat mijn fiets voor de deur.'],
      answer: 'Er staat een fiets voor de deur.',
      why: 'Het definietheidseffect: na presentatief er komt alleen een onbepaald onderwerp. De fiets en mijn fiets zijn bepaald: De fiets staat voor de deur.',
    },
    {
      kind: 'explain',
      id: 'verdieping',
      title: 'Definietheid, dubbel werk en een vaste plek',
      panels: [
        {
          text: 'Waarom verdraagt *er* geen bepaald onderwerp? Een *er*-zin zet iets nieuws op het toneel: *Er staat een fiets voor de deur* vertelt de lezer dat die fiets bestaat. Een bepaald onderwerp (*de fiets*, *mijn fiets*, *Jan*) is al bekend, dus valt er niets te presenteren. Gary Milsark (1977) beschreef dat als het verschil tussen zwakke en sterke kwantoren (zie Kwantoren en bereik, p15). Eén bekende uitzondering is de *opsomming*: *Wie kan ons helpen? Nou, er is altijd nog Piet.* Hier presenteer je niet Piet, maar een lijstje met kandidaten. En let op: staat iets anders vooraan, dan is presentatief *er* vaak weglaatbaar, vooral in schrijftaal: *In 1945 werd hard gewerkt.*',
          rule: 'Een er-zin introduceert iets nieuws. Bekend onderwerp: geen er. Een lijstje: er mag toch.',
          quiz: {
            q: 'Welke zin kan niet?',
            options: ['Er zit een muis in de kast.', 'Er zit de muis in de kast.', 'Er is altijd nog de muis van de buren om de schuld te geven.'],
            answer: 'Er zit de muis in de kast.',
            why: 'De muis is bepaald: De muis zit in de kast. De derde zin is een opsomming van kandidaten, en daar mag een bepaald naamwoord wel na er.',
          },
        },
        {
          text: 'Wat gebeurt er als een zin twee functies van *er* nodig heeft? Dan staat er meestal maar één *er*, dat dubbel werk doet. *Er wordt veel over gepraat*: dit *er* is presentatief (onpersoonlijk passief) én prepositioneel (*er … over* = *daarover*). *Er wonen veel studenten*: presentatief én plaats (*daar*). *Ik heb er twee van gelezen*: kwantitatief (*er twee*) én prepositioneel (*er … van*). Eén combinatie laat *er* wél twee keer toe, naast elkaar: presentatief plus kwantitatief. *Hoeveel fietsen staan er buiten? Er staan er drie.*',
          rule: 'Twee functies, meestal één er. Alleen presentatief plus kwantitatief geeft er er.',
          lab: {
            label: 'Tik een zin en tel de functies',
            chips: [
              {
                k: 'Er wordt veel over gepraat.',
                out: 'presentatief + prepositioneel',
                note: 'Onpersoonlijk passief (er) en daarover (er … over). Eén er, twee banen.',
              },
              {
                k: 'Er wonen veel studenten.',
                out: 'presentatief + plaats',
                note: 'Een onbepaald onderwerp (er) en daar (er). Zonder context is de plaatslezing optioneel.',
              },
              {
                k: 'Ik heb er twee van gelezen.',
                out: 'kwantitatief + prepositioneel',
                note: 'Twee van die boeken: er telt (er twee) en hoort bij van (ervan). Weer één er.',
              },
              {
                k: 'Er staan er drie.',
                out: 'presentatief + kwantitatief: twee keer er',
                note: 'De enige combinatie met twee er naast elkaar. Het eerste opent de zin, het tweede telt.',
              },
              {
                k: 'Er zijn er die er niets van snappen.',
                out: 'drie er, elk met een eigen baan',
                note: 'Presentatief (Er zijn), kwantitatief (er die: van die mensen) en prepositioneel (er niets van: daarvan). Ze staan in verschillende stukken van de zin en botsen niet.',
              },
            ],
          },
        },
        {
          text: 'Waar staat *er*? Vroeg in het middenveld, direct na de persoonsvorm of na een onderwerp dat een voornaamwoord is: *Ik heb er gisteren drie gekocht*, niet *Ik heb gisteren er drie gekocht*. Het gedraagt zich als een klitiek (zie Waar houdt het woord op?, w20): geen klemtoon, een vaste vroege plek, en nooit op de eerste plaats behalve als presentatief *er*. In een bijzin schuift het naar vlak na het onderwerp: *dat ik er gisteren drie kocht*. Alleen *daar* mag zwerven en nadruk dragen.',
          rule: 'Er staat vroeg in het middenveld en draagt nooit klemtoon. Wil je nadruk of de eerste plek, dan neem je daar.',
          swap: {
            goal: 'Zet er op zijn plek',
            blocks: ['Ik heb', 'gisteren', 'er', 'drie gekocht'],
            accept: ['Ik heb er gisteren drie gekocht'],
            note: 'Er komt direct na heb, vóór het bijwoord. Kwantitatief er heeft geen sterke tegenhanger, dus het kan nergens anders staan.',
          },
        },
        {
          text: 'De spelling van de R-woorden volgt één tabel. *Er*, *daar*, *hier* en *waar* plakken aan het voorzetsel; *met* wordt daarbij *mee* en *tot* wordt *toe*. Zo krijg je *ervan*, *daarvan*, *hiervan*, *waarvan*, en *ermee*, *ertoe*. Hetzelfde gebeurt in betrekkelijke bijzinnen (*het boek waarvan ik droom*, zie w24) en in vragen (*Waarvan droom je?*). Eén val: een voorzetsel dat niet bij *er* hoort, plak je niet aan. *Hij woont er in een flat* heeft *er* (daar) en *in een flat*, twee losse stukken.',
          rule: 'R-woord + voorzetsel: aan elkaar als ze samen één voornaamwoordelijk bijwoord zijn. met wordt mee, tot wordt toe.',
          paradigm: {
            q: 'Vul de tabel van de R-woorden in',
            cols: ['van', 'met', 'tot'],
            rows: [
              { label: 'er', cells: ['ervan', { fill: 'ermee', hint: 'met wordt mee.' }, { fill: 'ertoe', hint: 'tot wordt toe.' }] },
              {
                label: 'daar',
                cells: [{ fill: 'daarvan', hint: 'De sterke vorm van ervan.' }, 'daarmee', { fill: 'daartoe', hint: 'tot wordt toe: daartoe.' }],
              },
              { label: 'hier', cells: [{ fill: 'hiervan', hint: 'hier + van, aan elkaar.' }, { fill: 'hiermee', hint: 'met wordt mee.' }, 'hiertoe'] },
              {
                label: 'waar',
                cells: [
                  { fill: 'waarvan', hint: 'In een vraag en in een betrekkelijke bijzin: waarvan.' },
                  { fill: 'waarmee', hint: 'met wordt mee.' },
                  { fill: 'waartoe', hint: 'tot wordt toe.' },
                ],
              },
            ],
            extra: ['ermet', 'daartot', 'waarmet', 'er van'],
            note: 'Vier R-woorden, drie voorzetsels, twaalf vormen die je allemaal aan elkaar schrijft. Alleen met en tot veranderen zelf van vorm.',
          },
        },
      ],
    },
    {
      kind: 'speed',
      id: 'aaneen-er',
      prompt: 'Aan elkaar of los?',
      intro:
        'Een R-woord en zijn voorzetsel schrijf je aan elkaar als ze naast elkaar staan. Staat er iets tussen, of hoort het voorzetsel bij iets anders, dan los.',
      seconds: 45,
      items: [
        { a: 'er', b: 'over', joined: true, tip: 'erover: er en over naast elkaar.' },
        { a: 'er', b: 'naar uit', joined: true, tip: 'ernaar uit: ernaar aan elkaar, uit is het partikel van uitkijken.' },
        { a: 'er', b: 'vaak over', joined: false, tip: 'er vaak over: vaak staat ertussen.' },
        { a: 'daar', b: 'van', joined: true, tip: 'daarvan: de sterke vorm van ervan.' },
        { a: 'waar', b: 'mee', joined: true, tip: 'waarmee: met wordt mee.' },
        { a: 'er', b: 'in een flat', joined: false, tip: 'Hij woont er in een flat: er is daar, en in hoort bij een flat.' },
        { a: 'er', b: 'vandoor', joined: true, tip: 'ervandoor: ze gaat ervandoor, één woord.' },
        { a: 'er', b: 'niet van uit', joined: false, tip: 'er niet van uit: niet staat ertussen, dus drie losse woorden.' },
        { a: 'hier', b: 'over', joined: true, tip: 'hierover.' },
      ],
      done: {
        title: 'De spatie volgt de analyse',
        text: 'Hetzelfde er is soms één schriftwoord met zijn voorzetsel en soms twee. Je kijkt of ze naast elkaar staan én of het voorzetsel echt bij er hoort.',
      },
    },
    {
      kind: 'rewrite',
      id: 'ervan',
      prompt: 'Herschrijf met een voornaamwoordelijk bijwoord: van dat plan wordt een vorm met er.',
      source: 'Ik ben niet overtuigd van dat plan.',
      accept: ['Ik ben er niet van overtuigd.'],
      why: 'Van dat plan wordt er … van. Er springt naar zijn vaste plek vroeg in het middenveld, direct na ben, en van blijft bij overtuigd staan.',
    },
    {
      kind: 'rewrite',
      id: 'daarvan',
      prompt: 'Herschrijf met daar vooraan: van die regel wordt een R-woord.',
      source: 'Ik heb nog nooit van die regel gehoord.',
      accept: ['Daar heb ik nog nooit van gehoord.', 'Daarvan heb ik nog nooit gehoord.'],
      why: 'Daar … van is de sterke, gesplitste vorm; daarvan in één stuk vooraan kan ook. Met er kan dit niet: er mag niet op de eerste plek.',
    },
    {
      kind: 'type',
      id: 'waarvan',
      prompt: 'Vul het R-woord in, als één woord.',
      before: 'Dat is het huis',
      after: 'ik al jaren droom.',
      hint: 'waar…',
      answer: 'waarvan',
      why: 'Dromen van iets, en een huis is een ding: waar + van, aan elkaar. Bij een persoon: de vrouw van wie ik droom.',
    },
    {
      kind: 'bet',
      id: 'twee-er',
      prompt: 'Welke zin is goed Nederlands?',
      options: ['Er staan er drie in de gang.', 'Er wordt er veel over gepraat.', 'Ik woon er er al jaren.'],
      answer: 'Er staan er drie in de gang.',
      why: 'Presentatief plus kwantitatief is de enige combinatie met twee er. Bij presentatief plus prepositioneel doet één er dubbel werk: Er wordt veel over gepraat. Twee keer er voor dezelfde functie bestaat niet.',
    },
    {
      kind: 'explain',
      id: 'onderzoek',
      title: 'Onderwerp of bijwoord, en een Germaans buitenbeentje',
      panels: [
        {
          text: 'Is presentatief *er* een onderwerp? Het Engelse *there* in *There is a man at the door* gedraagt zich als onderwerp: het is verplicht en het staat op de onderwerpsplek. Het Nederlandse *er* is losser. Staat iets anders vooraan, dan kan het wegblijven: *In 1945 werd hard gewerkt*, *Gisteren is hard gewerkt*. En in het onpersoonlijk passief is er helemaal geen onderwerp om te vervangen. Hans Bennis (1986) betoogde in *Gaps and Dummies* op grond van zulke feiten dat *er* geen loos onderwerp is zoals *there*, maar eerder een bijwoord dat op de eerste plek is beland. De schoolgrammatica houdt het bij *plaatsonderwerp*; in de taalkunde loopt het debat nog.',
          rule: 'There is verplicht en gedraagt zich als onderwerp. Er kan wegblijven zodra de eerste plek gevuld is.',
          mark: {
            q: 'Tik het woord dat de eerste plek vult, zodat er mag wegblijven',
            sentence: 'Gisteren werd in de fabriek hard gewerkt.',
            targets: [0],
            note: 'Gisteren staat vooraan, dus er is niet nodig. Begin je met de persoonsvorm, dan moet er terug: Er werd gisteren in de fabriek hard gewerkt.',
          },
        },
        {
          text: 'Het kwantitatieve *er* is een buitenbeentje in de Germaanse familie. Het Duits zegt *Ich habe drei*, het Engels *I have three*: geen spoor van een telwoordje. Het Frans en het Italiaans hebben wél zo’n partitief woordje: *J’en ai trois*, *Ne ho tre*. Het Nederlandse *er* lijkt dus meer op het Romaanse *en* en *ne* dan op zijn Germaanse buren. Voor wie Nederlands leert, is dit *er* vaak het laatste dat vanzelf gaat: de meeste talen hebben er geen woord voor, dus niets in de moedertaal herinnert je eraan.',
          rule: 'Kwantitatief er heeft Romaanse neven (en, ne), maar geen Germaanse.',
          lab: {
            label: 'Tik een taal',
            chips: [
              { k: 'Nederlands', out: 'Ik heb er drie.', note: 'Kwantitatief er, verplicht.' },
              { k: 'Duits', out: 'Ich habe drei.', note: 'Geen telwoordje. Davon kan erbij, maar hoeft niet.' },
              { k: 'Engels', out: 'I have three.', note: 'Of voluit: I have three of them.' },
              { k: 'Frans', out: 'J’en ai trois.', note: 'en: een partitief klitiek, net als er.' },
              { k: 'Italiaans', out: 'Ne ho tre.', note: 'ne doet hetzelfde werk als en en er.' },
            ],
          },
        },
        {
          text: 'Waar komt *er* vandaan? Het is de onbeklemtoonde vorm van *daar*: in zwakke positie werd *daar* tot *der*, en de *d* sleet weg. In oude teksten en in veel dialecten hoor je nog *der*: *der is niemand*. Dat verklaart waarom *er* en *daar* zo vaak elkaars partner zijn: *er … van* naast *daar … van*, *er wordt* naast *daar wordt*. Het verklaart ook waarom *er* geen klemtoon kan dragen: het is per definitie de zwakke vorm. Alleen het kwantitatieve *er* heeft geen sterke tegenhanger; *Ik heb daar drie* betekent iets anders.',
          rule: 'er is zwak daar. Zwak betekent: geen klemtoon, geen eerste plek. De sterke vorm doet wat er niet kan.',
          swap: {
            goal: 'Maak de sterke variant: zet daar vooraan',
            blocks: ['denk', 'Daar', 'ik', 'niet aan'],
            accept: ['Daar denk ik niet aan'],
            note: 'Er denk ik niet aan kan niet: er blijft in het middenveld (Ik denk er niet aan). Daar mag vooraan en krijgt daar nadruk.',
          },
        },
        {
          text: 'Wat doe je ermee als schrijver? Een *er*-zin is een presentatiezin: hij zet iets nieuws neer, waarna de tekst er met een bepaald woord over verdergaat. *Er is een probleem met de server. Het probleem is …* Schrijfadviezen waarschuwen tegen een overdaad aan *er*-zinnen, zeker *Er zijn veel mensen die …*: vaak is *Veel mensen …* strakker. Maar schrap niet blind. *Er wordt gedanst* heeft geen onderwerp en kan niet zomaar zonder; en wie een nieuw onderwerp introduceert, mag *er* gewoon gebruiken.',
          rule: 'Gebruik er om iets nieuws te presenteren. Schrap het waar het alleen de zin uitrekt.',
          quiz: {
            q: 'Welke er-zin kun je niet strakker maken door er gewoon te schrappen?',
            options: ['Er wordt in de hal gedanst.', 'Er zijn veel mensen die dit lezen.', 'Er is een probleem met de server.'],
            answer: 'Er wordt in de hal gedanst.',
            why: 'Het onpersoonlijk passief heeft geen onderwerp; haal er weg en je moet de zin verbouwen (In de hal wordt gedanst). De andere twee: Veel mensen lezen dit. De server heeft een probleem.',
          },
        },
      ],
    },
    {
      kind: 'highlight',
      id: 'vier-kleuren',
      prompt: 'Kleur de vier er’s',
      intro: 'In deze tekst staat vier keer er, elke keer met een andere baan. Alleen die vier kleur je.',
      pens: [
        { id: 'pres', label: 'presentatief', tag: 'opent', ask: 'Opent dit er de zin voor een onbepaald onderwerp?', accent: 'blue' },
        { id: 'loc', label: 'plaats', tag: 'daar', ask: 'Kun je dit er door daar vervangen?', accent: 'green' },
        { id: 'kwant', label: 'kwantitatief', tag: 'telt', ask: 'Staat er een getal of hoeveelheid zonder naamwoord bij?', accent: 'orange' },
        { id: 'prep', label: 'prepositioneel', tag: 'voorzetsel', ask: 'Hoort dit er bij een voorzetsel verderop?', accent: 'purple' },
      ],
      words: [
        { t: 'Er', role: 'pres' },
        { t: 'staan' },
        { t: 'drie' },
        { t: 'fietsen' },
        { t: 'in' },
        { t: 'de' },
        { t: 'schuur.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'er', role: 'kwant' },
        { t: 'een' },
        { t: 'gekocht,' },
        { t: 'maar' },
        { t: 'ik' },
        { t: 'rijd' },
        { t: 'er', role: 'prep' },
        { t: 'zelden' },
        { t: 'op,' },
        { t: 'want' },
        { t: 'ik' },
        { t: 'kom' },
        { t: 'er', role: 'loc' },
        { t: 'bijna' },
        { t: 'nooit' },
        { t: 'meer.' },
      ],
      done: {
        title: 'Vier banen, één woord',
        text: 'Er staan (presentatief), er een (kwantitatief: een van die fietsen), er … op (prepositioneel: erop) en er bijna nooit (plaats: daar, in de schuur).',
      },
    },
    {
      kind: 'ambiguity',
      id: 'er-veel-gezien',
      prompt: 'Eén zin, twee er’s',
      intro: 'Kies een lezing en zoek de zin die alleen dát kan betekenen.',
      sentence: 'We hebben er veel gezien.',
      meanings: [
        {
          id: 'kwant',
          label: 'Veel van die dingen gezien',
          highlight: ['er veel'],
          right: 'Klopt. Van die kerken hebben we er veel gezien: er telt, samen met veel.',
        },
        {
          id: 'loc',
          label: 'Daar veel gezien',
          highlight: ['er'],
          right: 'Klopt. We hebben daar veel gezien: er is een plek.',
        },
      ],
      options: [
        { t: 'Van die kerken hebben we er veel gezien.', fits: 'kwant' },
        { t: 'We hebben daar veel gezien.', fits: 'loc' },
        { t: 'We hebben er vorige zomer veel gezien.', fits: null, note: 'Nog steeds allebei mogelijk: een tijd kiest niet.' },
      ],
      done: {
        title: 'Zelfde klank, andere baan',
        text: 'Kwantitatief er en plaatsaanduidend er klinken gelijk en staan op dezelfde plek. Pas de context, of de sterke vorm daar, haalt ze uit elkaar.',
      },
    },
    {
      kind: 'proofread',
      id: 'eindredactie-er',
      prompt: 'Lees de mail na',
      intro: 'Er zitten vijf fouten in met er en de R-woorden. Pas op: niet elke losse er is fout.',
      header: { to: 'Sam', subject: 'Nieuwe printer' },
      tokens: [
        { t: 'Er' },
        { t: 'is' },
        { t: 'gisteren' },
        { t: 'een' },
        { t: 'nieuwe' },
        { t: 'printer' },
        { t: 'geleverd.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'er' },
        { t: 'al' },
        { t: 'mee' },
        { t: 'gewerkt' },
        { t: 'en' },
        { t: 'ben' },
        { t: 'er' },
        { t: 'erg' },
        { t: 'tevreden' },
        { t: 'over.' },
        {
          t: 'Er staat de oude printer',
          fix: 'De oude printer staat',
          why: 'Een bepaald onderwerp verdraagt geen presentatief er: De oude printer staat nog in de gang.',
        },
        { t: 'nog' },
        { t: 'in' },
        { t: 'de' },
        { t: 'gang;' },
        { t: 'er ben ik', fix: 'daar ben ik', why: 'Plaatsaanduidend er kan niet vooraan. Na de puntkomma begint een nieuwe hoofdzin, en die opent met daar.' },
        { t: 'vanmorgen' },
        { t: 'nog' },
        { t: 'geweest.' },
        { t: 'We' },
        { t: 'gaan' },
        { t: 'er van uit', fix: 'ervan uit', why: 'er en van staan naast elkaar: ervan. Uit is het partikel van uitgaan en blijft los.' },
        { t: 'dat' },
        { t: 'jij' },
        { t: 'die' },
        { t: 'weghaalt.' },
        { t: 'Daar na', fix: 'Daarna', why: 'Daarna, in de betekenis vervolgens, is één woord.' },
        { t: 'kun' },
        { t: 'je' },
        { t: 'er mee', fix: 'ermee', why: 'er en mee staan naast elkaar: ermee.' },
        { t: 'printen' },
        { t: 'zoveel' },
        { t: 'je' },
        { t: 'wilt.' },
        { t: 'Er' },
        { t: 'zijn' },
        { t: 'er' },
        { t: 'die' },
        { t: 'zeggen' },
        { t: 'dat' },
        { t: 'de' },
        { t: 'oude' },
        { t: 'beter' },
        { t: 'was,' },
        { t: 'maar' },
        { t: 'daar' },
        { t: 'geloof' },
        { t: 'ik' },
        { t: 'niets' },
        { t: 'van.' },
      ],
      done: {
        title: 'Alle vijf gevonden',
        text: 'De oude printer staat (bepaald onderwerp), daar ben ik (plaats vooraan), ervan uit, Daarna en ermee. Goed waren: er al mee, er erg tevreden over, Er zijn er die, en daar … van.',
      },
    },
    {
      kind: 'swipe',
      id: 'er-stellingen',
      prompt: 'Klopt deze zin?',
      cards: [
        {
          t: 'Er loopt de man op straat is goed Nederlands.',
          ok: false,
          fix: 'De man loopt op straat',
          why: 'Een bepaald onderwerp verdraagt geen presentatief er.',
        },
        {
          t: 'Alleen het presentatieve er kan een zin openen.',
          ok: true,
          why: 'Plaatsaanduidend, kwantitatief en prepositioneel er staan in het middenveld; vooraan komt daar.',
        },
        {
          t: 'Ik heb er drie boeken is goed Nederlands.',
          ok: false,
          fix: 'Ik heb er drie, of ik heb drie boeken',
          why: 'Kwantitatief er en het naamwoord sluiten elkaar uit.',
        },
        {
          t: 'Er zijn er drie bevat twee keer er, en dat is correct.',
          ok: true,
          why: 'Presentatief plus kwantitatief: de enige combinatie met twee er naast elkaar.',
        },
        {
          t: 'Er kan klemtoon krijgen, net als daar.',
          ok: false,
          fix: 'Er is altijd onbeklemtoond',
          why: 'Het is de zwakke vorm van daar. Wil je nadruk, dan zeg je daar.',
        },
        { t: 'In Ik ga ervan uit schrijf je ervan aan elkaar.', ok: true, why: 'er en van staan naast elkaar. Met niet ertussen wordt het er niet van uit.' },
        {
          t: 'Het Engelse there is net zo vrij weglaatbaar als het Nederlandse er.',
          ok: false,
          fix: 'There is verplicht, er niet altijd',
          why: 'In 1945 werd hard gewerkt kan zonder er. Dat is een van de redenen om te twijfelen of er wel een onderwerp is.',
        },
      ],
    },
    {
      kind: 'dictation',
      id: 'dictee-er',
      prompt: 'Luister en typ de zin.',
      sentence: 'Ik ga ervan uit dat je er morgen over nadenkt.',
      right: 'Goed: ervan aan elkaar, want er en van staan naast elkaar. Er morgen over los, want morgen staat ertussen.',
      wrong:
        'Let op: er en van staan naast elkaar (ervan), maar tussen er en over staat morgen, dus die schrijf je los. Uit en na zijn partikels en blijven altijd los.',
    },
  ],
};
