import type { LessonInput } from '../../schema';

/**
 * Laatste masterles van "Het woord": tijd en aspect. Het achttijdensysteem van Te Winkel (1866) als
 * drie tegenstellingen, de drie punten van Reichenbach (1947), het Nederlandse perfectum dat zo vaak
 * het preteritum vervangt (en wat het verschil dan nog is), progressief aspect met aan het en met
 * zitten, staan en liggen te, zou als toekomst in het verleden en als modaal werkwoord, en de
 * tijdsconsecutie in een verhaal. De spelling van de verleden tijd (legacy w1), de sterke en zwakke
 * werkwoorden (w10) en het hulpwerkwoord hebben of zijn (w16) worden hier gebruikt, niet herhaald.
 */
export const LES_W26: LessonInput = {
  id: 'w26',
  stage: 'master',
  domain: 'sem',
  also: ['morf', 'syn', 'tekst'],
  title: 'Tijd en aspect: wanneer gebeurt het?',
  skill: 'Zinsbouw',
  icon: 'tijd',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Acht tijden uit drie keuzes',
      panels: [
        {
          text: 'Het Nederlands heeft volgens de schoolgrammatica acht tijden, en dat getal is geen toeval. L.A. te Winkel (1866) bouwde het systeem uit drie tegenstellingen: *tegenwoordig* of *verleden*, *onvoltooid* of *voltooid*, *niet-toekomend* of *toekomend*. Twee keer twee keer twee is acht. Elke keuze heeft een eigen plek in de vorm. Tegenwoordig of verleden zit in de persoonsvorm (*werk*, *werkte*; *heb*, *had*; *zal*, *zou*). Voltooid is *hebben* of *zijn* plus voltooid deelwoord. Toekomend is *zullen* plus infinitief. De ANS gebruikt dit systeem nog steeds, en de afkortingen ken je van school: o.t.t., v.v.t., o.v.t.t.',
          rule: 'Drie keuzes, elk met een eigen vorm: de tijd in de persoonsvorm, voltooid met hebben of zijn, toekomend met zullen.',
          paradigm: {
            q: 'Vul de acht tijden van werken in (ik)',
            cols: ['onvoltooid', 'voltooid'],
            rows: [
              {
                label: 'tegenwoordig',
                cells: ['ik werk', { fill: 'ik heb gewerkt', hint: 'Voltooid: hebben + deelwoord, met de persoonsvorm in het heden.' }],
              },
              {
                label: 'verleden',
                cells: [
                  { fill: 'ik werkte', hint: 'Onvoltooid verleden: de persoonsvorm krijgt -te.' },
                  { fill: 'ik had gewerkt', hint: 'Voltooid verleden: had + deelwoord.' },
                ],
              },
              {
                label: 'tegenwoordig toekomend',
                cells: [
                  { fill: 'ik zal werken', hint: 'zal + infinitief.' },
                  { fill: 'ik zal gewerkt hebben', hint: 'zal + voltooide infinitief: gewerkt hebben.' },
                ],
              },
              {
                label: 'verleden toekomend',
                cells: [
                  { fill: 'ik zou werken', hint: 'zou is de verleden tijd van zal.' },
                  { fill: 'ik zou gewerkt hebben', hint: 'zou + gewerkt hebben: alle drie de keuzes tegelijk.' },
                ],
              },
            ],
            extra: ['ik heb werken', 'ik zal werkte', 'ik zou gewerkt'],
            note: 'Acht vakjes, en elk vakje is de optelsom van drie keuzes. Zou is gewoon zal in de verleden tijd: toekomend én verleden.',
          },
        },
        {
          text: 'Hans Reichenbach (1947) gaf elke tijd drie punten op een lijn. *S* is het spreekmoment, *E* het moment van de gebeurtenis en *R* het referentiemoment: het punt van waaruit je kijkt. *Ik werkte*: E en R vallen samen, vóór S. *Ik heb gewerkt*: E ligt vóór R, en R valt samen met S; je staat in het nu en kijkt terug. *Ik had gewerkt*: E vóór R, en R vóór S; je staat in het verleden en kijkt nog verder terug. Het verschil tussen *werkte* en *heb gewerkt* zit dus niet in E, maar in R: waar de spreker staat.',
          rule: 'S is spreken, E is de gebeurtenis, R is het standpunt. Voltooid: E vóór R. Verleden: R vóór S.',
          lab: {
            label: 'Tik een tijd en zie de drie punten',
            chips: [
              { k: 'ik werk', out: 'E = R = S', note: 'Alles valt samen.' },
              { k: 'ik werkte', out: 'E = R, vóór S', note: 'Je staat in het verleden en de gebeurtenis is daar.' },
              { k: 'ik heb gewerkt', out: 'E vóór R = S', note: 'Je staat in het nu en kijkt terug: voltooid.' },
              { k: 'ik had gewerkt', out: 'E vóór R vóór S', note: 'Twee stappen terug: voltooid verleden.' },
              { k: 'ik zal werken', out: 'S vóór R = E', note: 'Standpunt en gebeurtenis liggen allebei na het spreken.' },
              { k: 'ik zal gewerkt hebben', out: 'S, dan E, dan R', note: 'Je kijkt vanuit een toekomstig punt terug op iets wat dan voorbij is.' },
            ],
          },
          deep: {
            q: 'Waarom drie punten en niet twee?',
            a: 'Met alleen S en E kun je *werkte* en *heb gewerkt* niet uit elkaar houden: in beide ligt de gebeurtenis vóór het spreken. Pas het standpunt R maakt het verschil zichtbaar. En *had gewerkt* heeft R echt nodig: het is een verleden vóór een ander verleden.',
          },
        },
        {
          text: 'Waarom zegt een Nederlander *Gisteren heb ik gewerkt*, terwijl een Engelsman *Yesterday I worked* moet zeggen? In het Nederlands mag het perfectum bij een tijdsbepaling in het verleden; in het Engels niet. Het Nederlandse perfectum heeft zo een groot deel van het terrein van het preteritum overgenomen, net als in het Duits en in het gesproken Frans. Toch is het verschil niet weg. Het perfectum meldt vanuit het nu dat iets gebeurd is: *Ik ben in Rome geweest.* Het preteritum zet je midden in de situatie van toen: *Het regende, en ik liep naar huis.* Daarom begint een verslag vaak met een perfectum en gaat het verder in het preteritum: *Ik ben gisteren naar Gent geweest. Ik vertrok om acht uur, het regende …*',
          rule: 'Perfectum: vanuit het nu terugkijken, ook bij gisteren. Preteritum: in het verleden staan, vertellen en beschrijven.',
          quiz: {
            q: 'Welke Nederlandse zin kan, terwijl de letterlijke Engelse vertaling niet kan?',
            options: ['Gisteren heb ik gewerkt.', 'Ik heb twee uur gewerkt.', 'Ik werkte gisteren.'],
            answer: 'Gisteren heb ik gewerkt.',
            why: 'Yesterday I have worked is fout in het Engels: een perfectum verdraagt daar geen tijdsbepaling in het verleden. In het Nederlands is het de gewone manier om te melden wat je gedaan hebt.',
          },
        },
        {
          text: 'Tijd zegt wanneer; *aspect* zegt hoe je naar de gebeurtenis kijkt: als afgerond geheel, of als iets wat aan de gang is. Het Nederlands heeft daarvoor geen verplichte vorm zoals het Engelse *-ing*, maar wel twee bouwsels. *Aan het* plus infinitief: *Ik ben aan het werken.* En de houdingswerkwoorden *zitten*, *staan*, *liggen*, *lopen* en *hangen* met *te*: *Ik zit te lezen.* Allebei kunnen niet bij een toestand: *Ik ben aan het weten* bestaat niet. Een lijdend voorwerp gaat vóór *aan het*: *Ik ben de krant aan het lezen.* En in de voltooide tijd gebeurt iets vreemds: *Ik heb zitten lezen*, met een infinitief in plaats van een deelwoord en zonder *te* (de vervangende infinitief, zie d13).',
          rule: 'Progressief: aan het + infinitief, of zitten, staan, liggen te + infinitief. Niet bij toestanden, en nooit verplicht.',
          swap: {
            goal: 'Bouw de progressieve zin met een lijdend voorwerp',
            blocks: ['Ik ben', 'aan het', 'de krant', 'lezen'],
            accept: ['Ik ben de krant aan het lezen'],
            note: 'Het lijdend voorwerp gaat vóór aan het. Ik ben aan het lezen de krant kan niet, en ook aan het de krant lezen niet.',
          },
        },
      ],
    },
    {
      kind: 'timeline',
      id: 'tijdschuif',
      prompt: 'Schuif drie werkwoorden door zes tijden',
      intro: 'Let op wat er verandert: alleen de persoonsvorm, of ook een hulpwerkwoord erbij.',
      stops: [
        { label: 'eerder toen', sub: 'v.v.t.', tense: 'Voltooid verleden tijd' },
        { label: 'toen', sub: 'o.v.t.', tense: 'Onvoltooid verleden tijd' },
        { label: 'nu klaar', sub: 'v.t.t.', tense: 'Voltooid tegenwoordige tijd' },
        { label: 'nu', sub: 'o.t.t.', tense: 'Onvoltooid tegenwoordige tijd' },
        { label: 'straks', sub: 'o.t.t.t.', tense: 'Onvoltooid tegenwoordige toekomende tijd' },
        { label: 'straks klaar', sub: 'v.t.t.t.', tense: 'Voltooid tegenwoordige toekomende tijd' },
      ],
      verbs: [
        {
          t: 'werken',
          cells: [
            {
              segs: [{ t: 'Toen je belde, ' }, { t: 'had', hi: true }, { t: ' ik al ' }, { t: 'gewerkt', hi: true }, { t: '.' }],
              rule: 'had + deelwoord',
              note: 'Standpunt toen, en het werken lag daar nog vóór: E vóór R vóór S.',
            },
            { segs: [{ t: 'Gisteren ' }, { t: 'werkte', hi: true }, { t: ' ik thuis.' }], rule: 'stam + te', note: 'Je staat in het verleden: E = R, vóór S.' },
            {
              segs: [{ t: 'Ik ' }, { t: 'heb', hi: true }, { t: ' vandaag ' }, { t: 'gewerkt', hi: true }, { t: '.' }],
              rule: 'heb + deelwoord',
              note: 'Vanuit nu terugkijken: E vóór R = S.',
            },
            { segs: [{ t: 'Ik ' }, { t: 'werk', hi: true }, { t: ' nu.' }], rule: 'stam', note: 'Alles valt samen.' },
            {
              segs: [{ t: 'Ik ' }, { t: 'zal', hi: true }, { t: ' morgen ' }, { t: 'werken', hi: true }, { t: '.' }],
              rule: 'zal + infinitief',
              note: 'R en E liggen na S. In de praktijk zeg je vaak gewoon: morgen werk ik.',
            },
            {
              segs: [{ t: 'Morgen om vijf uur ' }, { t: 'zal', hi: true }, { t: ' ik ' }, { t: 'gewerkt hebben', hi: true }, { t: '.' }],
              rule: 'zal + gewerkt hebben',
              note: 'Vanuit morgen vijf uur (R) kijk je terug op het werken (E): S, E, R.',
            },
          ],
        },
        {
          t: 'vallen',
          cells: [
            {
              segs: [{ t: 'Toen ik keek, ' }, { t: 'was', hi: true }, { t: ' hij al ' }, { t: 'gevallen', hi: true }, { t: '.' }],
              rule: 'was + deelwoord',
              note: 'Vallen kiest zijn (zie w16). Het hulpwerkwoord draagt de tijd: was.',
            },
            {
              segs: [{ t: 'Hij ' }, { t: 'viel', hi: true }, { t: ' van de trap.' }],
              rule: 'sterk: viel',
              note: 'Een sterk werkwoord wisselt van klinker in plaats van -te te krijgen.',
            },
            {
              segs: [{ t: 'Hij ' }, { t: 'is', hi: true }, { t: ' net ' }, { t: 'gevallen', hi: true }, { t: '.' }],
              rule: 'is + deelwoord',
              note: 'Zijn als hulpwerkwoord: een verandering met een eindpunt.',
            },
            { segs: [{ t: 'Kijk, hij ' }, { t: 'valt', hi: true }, { t: '!' }], rule: 'stam + t', note: 'Derde persoon: valt.' },
            {
              segs: [{ t: 'Pas op, hij ' }, { t: 'zal', hi: true }, { t: ' ' }, { t: 'vallen', hi: true }, { t: '.' }],
              rule: 'zal + infinitief',
              note: 'Zal klinkt hier als een voorspelling. Hij gaat vallen is de gewone spreektaal.',
            },
            {
              segs: [{ t: 'Voor je er bent, ' }, { t: 'zal', hi: true }, { t: ' hij al ' }, { t: 'gevallen zijn', hi: true }, { t: '.' }],
              rule: 'zal + gevallen zijn',
              note: 'Voltooide infinitief met zijn: gevallen zijn.',
            },
          ],
        },
        {
          t: 'opbellen',
          cells: [
            {
              segs: [{ t: 'Ze ' }, { t: 'had', hi: true }, { t: ' me al ' }, { t: 'opgebeld', hi: true }, { t: '.' }],
              rule: 'had + opgebeld',
              note: 'Scheidbaar: ge- kruipt tussen op en beld (zie w20).',
            },
            {
              segs: [{ t: 'Ze ' }, { t: 'belde', hi: true }, { t: ' me ' }, { t: 'op', hi: true }, { t: '.' }],
              rule: 'belde … op',
              note: 'In de hoofdzin gaat het partikel naar achteren.',
            },
            {
              segs: [{ t: 'Ze ' }, { t: 'heeft', hi: true }, { t: ' me ' }, { t: 'opgebeld', hi: true }, { t: '.' }],
              rule: 'heeft + opgebeld',
              note: 'Deelwoord in één woord, want op en gebeld staan naast elkaar.',
            },
            {
              segs: [{ t: 'Ze ' }, { t: 'belt', hi: true }, { t: ' me ' }, { t: 'op', hi: true }, { t: '.' }],
              rule: 'belt … op',
              note: 'Persoonsvorm op plek twee, partikel achteraan.',
            },
            {
              segs: [{ t: 'Ze ' }, { t: 'zal', hi: true }, { t: ' me ' }, { t: 'opbellen', hi: true }, { t: '.' }],
              rule: 'zal + opbellen',
              note: 'De infinitief staat weer in één stuk.',
            },
            {
              segs: [{ t: 'Ze ' }, { t: 'zal', hi: true }, { t: ' me ' }, { t: 'opgebeld hebben', hi: true }, { t: '.' }],
              rule: 'zal + opgebeld hebben',
              note: 'Ook hier: zullen plus voltooide infinitief.',
            },
          ],
        },
      ],
      done: {
        title: 'Zes tijden, drie bouwstenen',
        text: 'De persoonsvorm draagt tegenwoordig of verleden, hebben of zijn maakt voltooid, zullen maakt toekomend. Het werkwoord zelf verandert alleen in de o.v.t. en in het deelwoord.',
      },
    },
    {
      kind: 'sort',
      id: 'standpunt',
      prompt: 'Waar staat de spreker (R) ten opzichte van het spreekmoment (S)?',
      buckets: ['R = S: standpunt nu', 'R vóór S: standpunt toen', 'R na S: standpunt straks'],
      items: [
        { t: 'ik werk', b: 0 },
        { t: 'ik heb gewerkt', b: 0 },
        { t: 'ik werkte', b: 1 },
        { t: 'ik had gewerkt', b: 1 },
        { t: 'ik zou werken', b: 1 },
        { t: 'ik zal werken', b: 2 },
        { t: 'ik zal gewerkt hebben', b: 2 },
        { t: 'ik ben gevallen', b: 0 },
        { t: 'ik was gevallen', b: 1 },
      ],
      why: 'Het standpunt zit in de persoonsvorm. Tegenwoordig (werk, heb, ben): nu. Verleden (werkte, had, was, zou): toen. Zal: straks. Of E vóór R ligt, is een aparte keuze: voltooid of niet.',
    },
    {
      kind: 'fix',
      id: 'toen-had',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Toen ik thuiskwam, heeft ze al gegeten.',
      wrong: 3,
      answer: 'had',
      why: 'Het standpunt ligt in het verleden (toen ik thuiskwam: R vóór S) en het eten ligt daar nog vóór (E vóór R): voltooid verleden tijd, had gegeten.',
    },
    {
      kind: 'chat',
      id: 'aan-het',
      prompt: 'App met Lotte',
      intro: 'Kies telkens de zin met de goede progressieve vorm.',
      contact: { name: 'Lotte', role: 'je huisgenoot', initials: 'L' },
      rounds: [
        {
          say: 'Wat ben je aan het doen?',
          options: ['Ik ben de afwas aan het doen.', 'Ik ben aan het doen de afwas.'],
          right: 0,
          fix: 'aan het doen de afwas → de afwas aan het doen',
          why: 'Het lijdend voorwerp staat vóór aan het.',
        },
        {
          say: 'Weet je al of je morgen kunt?',
          options: ['Ik ben het aan het weten.', 'Ik weet het nog niet.'],
          right: 1,
          fix: 'ben het aan het weten → weet het',
          why: 'Weten is een toestand, en een toestand is niet aan de gang.',
        },
        {
          say: 'Wat heb je vanmiddag gedaan?',
          options: ['Ik heb de hele middag zitten lezen.', 'Ik heb de hele middag gezeten te lezen.'],
          right: 0,
          fix: 'gezeten te lezen → zitten lezen',
          why: 'In de voltooide tijd wordt het deelwoord een infinitief en valt te weg: de vervangende infinitief.',
        },
        {
          say: 'En waar is Sam?',
          options: ['Sam is vissen.', 'Sam is te vissen.'],
          right: 0,
          fix: 'is te vissen → is vissen',
          why: 'Zijn plus infinitief zonder te: Sam is weg om te vissen. Taalkundigen noemen deze vorm de absentief; hij zegt dat Sam er niet is.',
        },
      ],
      bye: 'Dank je! Dan ga ik verder met waar ik mee bezig was.',
    },
    {
      kind: 'explain',
      id: 'verdieping',
      title: 'Zou, en de tijden van een verhaal',
      panels: [
        {
          text: '*Zou* is om te beginnen gewoon de verleden tijd van *zal*: toekomend in het verleden. *Hij beloofde dat hij zou komen*: op het moment van beloven (R, in het verleden) lag het komen (E) nog in de toekomst. Bij Reichenbach: R vóór S, en E na R. Of hij echt gekomen is, zegt de zin niet; dat blijft open. Daarom hoort *zou* thuis in de indirecte rede na een verleden tijd: *Ze zei dat ze de volgende dag zou vertrekken.* Vergelijk de directe rede: *Ze zei: ik vertrek morgen.*',
          rule: 'zou = zal in het verleden: op een punt in het verleden lag de gebeurtenis nog in de toekomst.',
          mark: {
            q: 'Tik de persoonsvorm die het standpunt in het verleden zet',
            sentence: 'Ze beloofde dat ze de volgende dag zou bellen.',
            targets: [1],
            note: 'Beloofde zet R in het verleden. Zou kijkt van daaruit vooruit naar het bellen.',
          },
        },
        {
          text: 'Daarnaast is *zou* een *modaal* werkwoord: het zegt iets over werkelijkheid en zekerheid, niet over tijd. Vier gebruikswijzen. *Hypothetisch*: *Als ik rijk was, zou ik een boot kopen* (het is niet zo). *Beleefd*: *Zou u het raam dicht willen doen?* *Advies*: *Je zou eens naar de dokter moeten.* *Van horen zeggen*: *De dader zou een man van dertig zijn* (zegt men; ik sta er niet voor in). In al die zinnen staat de spreker in het nu; *zou* schuift de uitspraak alleen een stap van de werkelijkheid af. De vorm is dezelfde, de betekenis niet. Het Engelse *would* en het Duitse *würde* doen precies hetzelfde.',
          rule: 'Modaal zou: hypothese, beleefdheid, advies of van horen zeggen. Het standpunt blijft nu.',
          lab: {
            label: 'Tik een zin',
            chips: [
              { k: 'Hij zei dat hij zou helpen.', out: 'tijd: toekomst in het verleden', note: 'R in het verleden (zei), het helpen daarna.' },
              { k: 'Als ik jou was, zou ik gaan.', out: 'modaal: hypothese', note: 'Ik ben jou niet. De uitspraak is een gedachte-experiment.' },
              { k: 'Zou je me even willen helpen?', out: 'modaal: beleefd', note: 'Zou maakt de vraag zachter dan wil je.' },
              { k: 'Volgens de krant zou hij ziek zijn.', out: 'modaal: van horen zeggen', note: 'De spreker geeft het door zonder ervoor in te staan.' },
              { k: 'Je zou wat vaker moeten slapen.', out: 'modaal: advies', note: 'Een voorzichtige aanbeveling.' },
            ],
          },
        },
        {
          text: 'Een verhaal heeft een *verhaaltijd*, meestal het preteritum. Alles wat op de verhaallijn gebeurt, staat in de o.v.t.: *Hij kwam thuis, zette de tas neer en keek rond.* Wat eerder gebeurde dan de verhaallijn, krijgt de v.v.t.: *Ze had al gegeten.* Wat vanuit het verhaal nog moet komen, krijgt *zou*: *Hij wist dat hij dit nooit zou vergeten.* Zo blijft de lezer op één standpunt staan. Spring je ineens naar het perfectum (*Hij kwam thuis. Hij heeft de tas neergezet.*), dan verhuist het standpunt naar het nu en breekt het verhaal. Dat is wat *tijdsconsecutie* betekent: de tijden volgen één gekozen standpunt.',
          rule: 'Verhaallijn: o.v.t. Eerder dan de verhaallijn: v.v.t. Later vanuit het verhaal: zou.',
          paradigm: {
            q: 'Kies de vorm die het verhaal op één standpunt houdt',
            cols: ['vorm'],
            rows: [
              { label: 'Toen hij thuiskwam, … ze al. (eten)', cells: [{ fill: 'had gegeten', hint: 'Eerder dan de verhaallijn: voltooid verleden.' }] },
              { label: 'Hij … de tas neer. (zetten)', cells: [{ fill: 'zette', hint: 'Op de verhaallijn: o.v.t.' }] },
              { label: 'Hij wist dat hij dit nooit … (vergeten)', cells: [{ fill: 'zou vergeten', hint: 'Later vanuit het verhaal: zou.' }] },
              { label: 'De volgende ochtend … het. (regenen)', cells: [{ fill: 'regende', hint: 'Weer op de verhaallijn.' }] },
            ],
            extra: ['heeft gegeten', 'zal vergeten', 'zet', 'regent'],
            note: 'Vier zinnen, één standpunt. Heeft gegeten en zal vergeten zouden de lezer naar het nu halen.',
          },
        },
        {
          text: 'Twee bijzonderheden. Eén: de indirecte rede. Het Engels schuift streng op (*He said he was ill*). Het Nederlands is soepeler: *Hij zei dat hij ziek was* én *Hij zei dat hij ziek is* kunnen allebei, het tweede als hij nu nog ziek is. Schuif je, dan schuift alles mee: *ik kom morgen* wordt *hij zou de volgende dag komen*. Twee: het *historisch presens*. Een verteller kan midden in een verhaal naar de o.t.t. springen om het dichtbij te halen: *Ik loop gisteren op straat en opeens staat daar een hert.* Dat is geen fout maar een stijlmiddel, zolang je niet per zin wisselt.',
          rule: 'Indirecte rede: verschuiven mag, en moet niet altijd. Historisch presens: een bewuste sprong naar nu, geen slip.',
          quiz: {
            q: 'Welke zin is een bewust historisch presens?',
            options: [
              'Ik loop gisteren op straat en opeens staat daar een hert.',
              'Ik liep gisteren op straat en opeens staat daar een hert.',
              'Ik loop morgen even langs.',
            ],
            answer: 'Ik loop gisteren op straat en opeens staat daar een hert.',
            why: 'Het hele stukje staat in de o.t.t. met een verleden tijdsbepaling: een sprong naar nu als stijlmiddel. De tweede zin wisselt halverwege, en dat leest als een slip. De derde is gewoon de toekomst.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'zou-sorteren',
      prompt: 'Wat doet zou hier?',
      buckets: ['toekomst in het verleden', 'hypothese', 'beleefd of advies', 'van horen zeggen'],
      items: [
        { t: 'Hij beloofde dat hij zou helpen.', b: 0 },
        { t: 'Zou je het raam dicht willen doen?', b: 2 },
        { t: 'Volgens de krant zou de minister aftreden.', b: 3 },
        { t: 'Ik zou dat niet doen als ik jou was.', b: 1 },
        { t: 'Ze wist dat het feest zou doorgaan.', b: 0 },
        { t: 'Je zou eens wat vaker moeten sporten.', b: 2 },
        { t: 'Als ik rijk was, zou ik een boot kopen.', b: 1 },
        { t: 'De dader zou een man van dertig zijn.', b: 3 },
        { t: 'Hij dacht dat de trein om acht uur zou vertrekken.', b: 0 },
        { t: 'Zou u mij even kunnen helpen?', b: 2 },
      ],
      why: 'Na een verleden tijd (beloofde, wist, dacht) is zou tijd: toekomst vanuit toen. Met als of een niet-werkelijke voorwaarde is het hypothese. In een vraag of met moeten maakt het beleefd of adviserend. Met volgens, of bij een bewering die je doorgeeft, is het van horen zeggen.',
    },
    {
      kind: 'rewrite',
      id: 'in-de-ovt',
      prompt: 'Zet het stukje in de onvoltooid verleden tijd.',
      source: 'Ze loopt naar huis en belt haar moeder. Die neemt niet op.',
      accept: ['Ze liep naar huis en belde haar moeder. Die nam niet op.'],
      why: 'Lopen en opnemen zijn sterk: liep, nam op. Bellen is zwak: belde, want l zit niet in ’t kofschip. Alle persoonsvormen verhuizen, de rest blijft.',
    },
    {
      kind: 'rewrite',
      id: 'indirecte-rede',
      prompt: 'Zet om in de indirecte rede, met zou. Morgen wordt de volgende dag.',
      source: 'Ze zei: ik vertrek morgen.',
      accept: ['Ze zei dat ze de volgende dag zou vertrekken.', 'Zij zei dat zij de volgende dag zou vertrekken.'],
      why: 'Na zei ligt het standpunt in het verleden. Vertrek morgen wordt zou vertrekken, en morgen wordt de volgende dag, want morgen hoort bij het spreekmoment van nu.',
    },
    {
      kind: 'ambiguity',
      id: 'zou-ambigu',
      prompt: 'Eén zou, twee lezingen',
      intro: 'Kies een lezing en zoek de zin die alleen dát kan betekenen.',
      sentence: 'Ze zou morgen vertrekken.',
      meanings: [
        {
          id: 'tijd',
          label: 'Toekomst in het verleden: dat was het plan',
          highlight: ['zou morgen vertrekken'],
          right: 'Klopt. Gisteren zei ze het: vanuit toen lag het vertrek nog in de toekomst.',
        },
        {
          id: 'modaal',
          label: 'Van horen zeggen: dat beweert iemand',
          highlight: ['zou'],
          right: 'Klopt. Volgens haar zus: de spreker geeft het door zonder ervoor in te staan.',
        },
      ],
      options: [
        { t: 'Ze zei gisteren dat ze morgen zou vertrekken.', fits: 'tijd' },
        { t: 'Volgens haar zus zou ze morgen vertrekken, maar niemand weet het zeker.', fits: 'modaal' },
        { t: 'Ze zou morgen met de trein vertrekken.', fits: null, note: 'Nog steeds allebei mogelijk: de trein kiest niet.' },
      ],
      done: {
        title: 'Eén vorm, twee betekenissen',
        text: 'Na een verleden tijd (zei) is zou tijd. Met volgens of een bron is het modaal. Zonder context houdt de zin beide open.',
      },
    },
    {
      kind: 'bet',
      id: 'acht',
      prompt: 'Waarom zijn het er in het systeem van Te Winkel precies acht?',
      options: ['Drie tegenstellingen met elk twee waarden: 2 × 2 × 2', 'Het Latijn had er acht', 'Er zijn acht hulpwerkwoorden'],
      answer: 'Drie tegenstellingen met elk twee waarden: 2 × 2 × 2',
      why: 'Te Winkel kruiste tegenwoordig of verleden, onvoltooid of voltooid en niet-toekomend of toekomend. Het Latijn heeft zes tijden in de aantonende wijs, en de hulpwerkwoorden van tijd zijn er maar drie: hebben, zijn en zullen.',
    },
    {
      kind: 'explain',
      id: 'onderzoek',
      title: 'Lagen in de vorm, en wat tijd nog betekent',
      panels: [
        {
          text: 'De acht tijden zijn gelaagd. *Ik zou gewerkt hebben* bouw je van binnen naar buiten: eerst het voltooide stuk (*gewerkt hebben*), dan *zullen*, dat de toekomst erbij doet, en pas de buitenste persoonsvorm draagt de tijd (*zou*, verleden). Dezelfde lagen zie je in de bijzin, waar het hele cluster achteraan staat: *dat ik gewerkt zou hebben*, naast *dat ik zou hebben gewerkt*; beide volgordes zijn standaardtaal. De tijd zit dus niet in één woord, maar in een bouwwerk.',
          rule: 'Van binnen naar buiten: voltooid, toekomend, tijd. Precies de drie keuzes van Te Winkel, als drie lagen.',
          bracket: {
            q: 'Bouw het gezegde van binnen naar buiten',
            tree: '[ik [zou [gewerkt hebben]]]',
            words: true,
            nodes: [
              { w: 'gewerkt hebben', cat: 'voltooide infinitief', note: 'De voltooidheid: hebben + deelwoord, nog zonder tijd.' },
              { w: 'zou gewerkt hebben', cat: 'werkwoordelijk gezegde', note: 'Zullen voegt toekomend toe; zijn vorm zou draagt de verleden tijd.' },
              { w: 'ik zou gewerkt hebben', cat: 'zin', note: 'De persoonsvorm richt zich naar het onderwerp: ik zou.' },
            ],
            traps: [
              { w: 'zou gewerkt', note: 'Zullen neemt een infinitief, geen deelwoord: zou gewerkt bestaat niet.' },
              { w: 'ik zou', note: 'Eerst het hele gezegde, dan het onderwerp: zou krijgt zijn vorm pas als het bouwwerk af is.' },
            ],
            note: 'Voltooid binnenin, toekomend eromheen, de tijd op de buitenste laag.',
          },
        },
        {
          text: 'Hoe ver gaat de opmars van het perfectum? Ver, maar niet overal even ver. In Zuid-Duitse dialecten is het preteritum uit de spreektaal vrijwel verdwenen; Duitse taalkundigen noemen dat de *Präteritumschwund*. Het Afrikaans ging nog verder: *ek het gewerk* dekt daar elk verleden, en het preteritum leeft alleen nog in een handvol vormen als *was*, *kon*, *sou* en *moes*. Het gesproken Frans verloor de passé simple, die alleen nog op papier bestaat. Het Nederlands staat daartussen: het perfectum meldt, het preteritum vertelt, en beide zijn springlevend. Wie Nederlands schrijft, moet dus wél kiezen.',
          rule: 'In het Nederlands is het preteritum niet verdwenen: het is de tijd van het vertellen.',
          lab: {
            label: 'Tik een taal',
            chips: [
              { k: 'Engels', out: 'I worked · I have worked: strikt gescheiden', note: 'Een tijdsbepaling in het verleden dwingt het preteritum af.' },
              { k: 'Duits (zuiden)', out: 'ich habe gearbeitet, bijna altijd', note: 'Präteritumschwund: in de spreektaal is het preteritum vrijwel weg.' },
              { k: 'Afrikaans', out: 'ek het gewerk', note: 'Eén verleden tijd voor bijna alles. Alleen was, kon, sou en moes zijn nog preterita.' },
              { k: 'Frans', out: 'j’ai travaillé · je travaillai', note: 'De passé simple leeft alleen in geschreven verhalen.' },
              { k: 'Nederlands', out: 'ik heb gewerkt · ik werkte', note: 'Allebei levend, verdeeld naar functie: melden tegenover vertellen.' },
            ],
          },
        },
        {
          text: 'Waarom kan *aan het weten* niet? Zeno Vendler (1957) verdeelde werkwoorden naar hun innerlijke tijd: *toestanden* (*weten*, *wonen*), *activiteiten* zonder eindpunt (*wandelen*), *processen met eindpunt* (*een brief schrijven*) en *momenten* (*aankomen*). Twee toetsen: een activiteit duurt *een uur lang*, een proces met eindpunt is klaar *in een uur*, en een toestand doet geen van beide graag. De progressieve vorm vraagt iets wat aan de gang kan zijn: activiteiten en processen. Een toestand is niet aan de gang, hij is er gewoon. Dit is dezelfde eigenschap als de teliciteit uit Hebben of zijn (w16), maar nu gebruikt voor aspect in plaats van voor het hulpwerkwoord.',
          rule: 'Aspect kijkt naar de innerlijke tijd van het werkwoord: duurt het, eindigt het, of is het er gewoon?',
          paradigm: {
            q: 'Vul de klassen van Vendler in',
            cols: ['klasse', 'toets', 'aan het?'],
            rows: [
              {
                label: 'weten',
                cells: [
                  'toestand',
                  { fill: 'geen van beide', hint: 'Een uur lang weten en in een uur weten klinken allebei raar.' },
                  { fill: 'kan niet', hint: 'Een toestand is niet aan de gang.' },
                ],
              },
              {
                label: 'wandelen',
                cells: [
                  { fill: 'activiteit', hint: 'Geen eindpunt: je kunt eindeloos wandelen.' },
                  'een uur lang',
                  { fill: 'kan', hint: 'Ik ben aan het wandelen.' },
                ],
              },
              {
                label: 'een brief schrijven',
                cells: [
                  { fill: 'proces met eindpunt', hint: 'Als de brief af is, is het klaar.' },
                  { fill: 'in een uur', hint: 'Ze schreef de brief in een uur.' },
                  'kan',
                ],
              },
            ],
            extra: ['moment', 'een uur lang'],
            note: 'Toestand, activiteit, proces met eindpunt: drie klassen, en alleen de laatste twee kunnen aan de gang zijn.',
          },
        },
        {
          text: 'Hoe toekomend is de toekomende tijd? Zelden puur. Voor een plan zegt het Nederlands gewoon *Morgen werk ik thuis*: de o.t.t. met een tijdsbepaling. *Zullen* brengt bijna altijd een modale kleur mee: een belofte (*Ik zal het doen*), een verwachting (*Dat zal wel*), een waarschijnlijkheid (*Hij zal nu wel thuis zijn*, en dat gaat over het heden). Daarnaast rukt *gaan* op als hulpwerkwoord van de nabije toekomst of het voornemen: *Het gaat regenen*, *Ik ga morgen bellen*. Taalkundigen bespreken daarom of *zullen* in het Nederlands wel een echte tijd uitdrukt, of eerder modaliteit. Het systeem van acht tijden is een net: het vangt de vormen, niet altijd het gebruik.',
          rule: 'De toekomst staat meestal in de o.t.t. met een tijdsbepaling. Zullen kleurt: belofte, verwachting, waarschijnlijkheid.',
          quiz: {
            q: 'Wat is de gewoonste manier om een afspraak van morgen te melden?',
            options: ['Morgen werk ik thuis.', 'Morgen zal ik thuis werken.', 'Morgen zal ik thuis gewerkt hebben.'],
            answer: 'Morgen werk ik thuis.',
            why: 'Het Nederlands zet de toekomst meestal in de o.t.t. met een tijdsbepaling. Zullen voegt een modale kleur toe (belofte, verwachting), en de v.t.t.t. kijkt vanuit morgen terug op iets wat dan klaar is.',
          },
        },
      ],
    },
    {
      kind: 'highlight',
      id: 'kleur-de-tijden',
      prompt: 'Kleur de tijden',
      intro: 'Vier tijden in één stukje. Kleur elke persoonsvorm en elk deelwoord met de stift van zijn tijd.',
      pens: [
        { id: 'ovt', label: 'o.v.t.', tag: 'verhaallijn', ask: 'Staat dit op de verhaallijn in het verleden?', accent: 'blue' },
        { id: 'vvt', label: 'v.v.t.', tag: 'eerder', ask: 'Gebeurde dit nog vóór de verhaallijn?', accent: 'purple' },
        { id: 'vtt', label: 'v.t.t.', tag: 'vanuit nu', ask: 'Kijkt de spreker vanuit nu terug?', accent: 'orange' },
        { id: 'ott', label: 'o.t.t.', tag: 'nu of straks', ask: 'Staat dit in het heden, of in de toekomst zonder zullen?', accent: 'green' },
      ],
      words: [
        { t: 'Gisteren' },
        { t: 'belde', role: 'ovt' },
        { t: 'Amir.' },
        { t: 'Hij' },
        { t: 'had', role: 'vvt' },
        { t: 'de' },
        { t: 'uitslag' },
        { t: 'al' },
        { t: 'gehoord', role: 'vvt' },
        { t: 'en' },
        { t: 'was', role: 'ovt' },
        { t: 'dolblij.' },
        { t: 'Ik' },
        { t: 'heb', role: 'vtt' },
        { t: 'hem' },
        { t: 'meteen' },
        { t: 'gefeliciteerd,', role: 'vtt' },
        { t: 'en' },
        { t: 'morgen' },
        { t: 'vieren', role: 'ott' },
        { t: 'we' },
        { t: 'het.' },
      ],
      done: {
        title: 'Vier standpunten in vier zinnen',
        text: 'Belde en was: de verhaallijn. Had gehoord: nog eerder. Heb gefeliciteerd: de spreker stapt naar het nu. Vieren: de toekomst in de o.t.t., zonder zullen.',
      },
    },
    {
      kind: 'proofread',
      id: 'verhaallijn',
      prompt: 'Lees het verhaal na',
      intro: 'Er zitten vijf tijdfouten in: sprongen van het standpunt. Niet elke voltooide tijd is fout.',
      tokens: [
        { t: 'Vorige' },
        { t: 'week' },
        { t: 'ging' },
        { t: 'ik' },
        { t: 'naar' },
        { t: 'de' },
        { t: 'markt.' },
        { t: 'Ik' },
        { t: 'kocht' },
        { t: 'appels' },
        { t: 'en' },
        { t: 'een' },
        { t: 'brood.' },
        { t: 'Bij' },
        { t: 'de' },
        { t: 'kaaskraam' },
        { t: 'zie', fix: 'zag', why: 'De verhaallijn staat in de o.v.t.: ging, kocht, dus ook zag.' },
        { t: 'ik' },
        { t: 'een' },
        { t: 'oude' },
        { t: 'vriend.' },
        { t: 'We' },
        { t: 'hebben', fix: 'hadden', why: 'Eerder dan de verhaallijn: voltooid verleden tijd, hadden gezien.' },
        { t: 'elkaar' },
        { t: 'sinds' },
        { t: 'de' },
        { t: 'middelbare' },
        { t: 'school' },
        { t: 'niet' },
        { t: 'meer' },
        { t: 'gezien.' },
        { t: 'Hij' },
        { t: 'vertelde' },
        { t: 'dat' },
        { t: 'hij' },
        { t: 'net' },
        { t: 'was' },
        { t: 'verhuisd' },
        { t: 'en' },
        { t: 'nodigde' },
        { t: 'me' },
        { t: 'uit.' },
        { t: 'Toen' },
        { t: 'ik' },
        { t: 'thuiskwam,' },
        { t: 'merkte' },
        { t: 'ik' },
        { t: 'dat' },
        { t: 'ik' },
        { t: 'mijn' },
        { t: 'sleutels' },
        { t: 'ben', fix: 'was', why: 'Het vergeten lag vóór het thuiskomen: was vergeten, voltooid verleden.' },
        { t: 'vergeten.' },
        { t: 'Gelukkig' },
        { t: 'heeft', fix: 'had', why: 'De buurvrouw heeft die sleutel misschien nog steeds, maar het verhaal staat in het verleden: had.' },
        { t: 'de' },
        { t: 'buurvrouw' },
        { t: 'een' },
        { t: 'reservesleutel.' },
        { t: 'Ik' },
        { t: 'wist' },
        { t: 'dat' },
        { t: 'het' },
        { t: 'een' },
        { t: 'lange' },
        { t: 'avond' },
        { t: 'zal', fix: 'zou', why: 'Toekomst vanuit het verleden (wist): zou worden.' },
        { t: 'worden.' },
      ],
      done: {
        title: 'Eén standpunt, vijf keer hersteld',
        text: 'Zag en had op de verhaallijn, hadden gezien en was vergeten als voorverleden, zou worden als toekomst vanuit toen. Was verhuisd was al goed: dat lag vóór het vertellen.',
      },
    },
    {
      kind: 'type',
      id: 'vttt',
      prompt: 'Vul het deelwoord in: voltooid tegenwoordige toekomende tijd van vertrekken.',
      before: 'Morgen om acht uur zal de trein al',
      after: 'zijn.',
      hint: 'deelwoord',
      answer: 'vertrokken',
      why: 'Vertrekken kiest zijn (verandering van plaats, zie w16): zal vertrokken zijn. Vanuit morgen acht uur (R) kijk je terug op het vertrek (E): S, dan E, dan R.',
    },
    {
      kind: 'order',
      id: 'reichenbach-orde',
      prompt: 'Zet de drie momenten van Reichenbach in de volgorde van ‘Ik had gewerkt’.',
      tiles: ['R (standpunt)', 'S (spreken)', 'E (gebeurtenis)'],
      answer: 'E (gebeurtenis) R (standpunt) S (spreken)',
      why: 'Voltooid verleden: eerst de gebeurtenis, dan het standpunt in het verleden, dan het spreken in het nu. E vóór R vóór S.',
    },
    {
      kind: 'swipe',
      id: 'tijd-stellingen',
      prompt: 'Klopt deze zin?',
      cards: [
        { t: 'Zou is de verleden tijd van zal.', ok: true, why: 'Toekomend in het verleden: hij zei dat hij zou komen.' },
        {
          t: 'In het Engels kun je net als in het Nederlands zeggen: Yesterday I have worked.',
          ok: false,
          fix: 'Yesterday I worked',
          why: 'Het Engelse perfectum verdraagt geen tijdsbepaling in het verleden; het Nederlandse wel.',
        },
        { t: 'Ik ben aan het weten bestaat niet.', ok: true, why: 'Weten is een toestand, en een toestand is niet aan de gang.' },
        { t: 'In het systeem van Te Winkel zijn er zes tijden.', ok: false, fix: 'Acht tijden', why: 'Drie tegenstellingen met elk twee waarden: 2 × 2 × 2.' },
        { t: 'Bij ik had gewerkt ligt R vóór S.', ok: true, why: 'Het standpunt ligt in het verleden, en E ligt daar nog vóór.' },
        {
          t: 'Ik heb zitten lezen is fout; het moet ik heb gezeten te lezen zijn.',
          ok: false,
          fix: 'Ik heb zitten lezen is goed',
          why: 'De vervangende infinitief: zitten in plaats van gezeten, en zonder te.',
        },
        {
          t: 'Een historisch presens is altijd een fout.',
          ok: false,
          fix: 'Het is een stijlmiddel',
          why: 'Een bewuste sprong naar nu maakt een verhaal levendig. Alleen onbedoeld wisselen is een slip.',
        },
      ],
    },
  ],
};
