import type { StepInput } from '../../schema';

/** Onderzoek bij d17: een derde uitlegronde op onderzoeksniveau, daarna zwaardere oefeningen. */
export const ONDERZOEK_D17: StepInput[] = [
  {
    kind: 'explain',
    id: 'onderzoek',
    title: 'Routes die samenwerken, stukken die stranden',
    panels: [
      {
        text: 'Hoe lees je *vissersboot*? Het racemodel zegt: de snelste route wint. Victor Kuperman, Robert Schreuder, Raymond Bertram en Harald Baayen (2009) volgden de oogbewegingen van lezers bij lange Nederlandse samenstellingen. Hun uitkomst: de frequentie van het hele woord, die van het eerste deel én die van het tweede deel beïnvloedden allemaal hoe lang de ogen bleven hangen, en al vroeg. Niet één route die wint, maar alle informatie tegelijk: een *multiple route model*. Raymond Bertram en Jukka Hyönä (2003) vonden bij Finse samenstellingen bovendien dat lengte telt: korte samenstellingen lees je vooral als geheel, lange in stukken.',
        rule: 'Bij het lezen van een samenstelling gaan het hele woord én de delen tegelijk aan.',
        cast: {
          q: 'Tik alles wat in je hoofd aangaat',
          rounds: [
            {
              text: 'vissersboot',
              ask: 'Je leest vissersboot. Tik elk woord dat volgens Kuperman en collega’s meedoet',
              cast: ['visser', 'boot', 'vissersboot', 'pan'],
              answer: ['visser', 'boot', 'vissersboot'],
              focus: 'vissersboot',
              then: {
                q: 'Welke frequentie telt mee voor de leestijd?',
                options: ['Die van het geheel én van beide delen', 'Alleen die van het hele woord', 'Alleen die van het laatste deel'],
                answer: 'Die van het geheel én van beide delen',
              },
              note: 'Drie woorden tegelijk: visser, boot en vissersboot. De ogen blijven korter hangen als alle drie vaak voorkomen.',
            },
            {
              text: 'zonnebloem',
              ask: 'Je leest zonnebloem. Tik elk woord dat meedoet, ook als de betekenis niet klopt',
              cast: ['zon', 'bloem', 'zonnebloem', 'ster'],
              answer: ['zon', 'bloem', 'zonnebloem'],
              focus: 'zonnebloem',
              then: {
                q: 'Een zonnebloem is geen zon. Doet zon toch mee?',
                options: ['Ja: vroeg in het lezen telt de vorm, niet de betekenis', 'Nee: de betekenis houdt zon tegen'],
                answer: 'Ja: vroeg in het lezen telt de vorm, niet de betekenis',
              },
              note: 'Net als corner en corn: het eerste knippen gaat op vorm. Zon doet mee, ook al is een zonnebloem alleen maar zo geel als de zon.',
            },
            {
              text: 'bloempot',
              ask: 'Je leest bloempot. Tik wat meedoet',
              cast: ['bloem', 'pot', 'bloempot', 'glas'],
              answer: ['bloem', 'pot', 'bloempot'],
              focus: 'bloempot',
              then: {
                q: 'Bloempot is kort en frequent. Wat voorspellen Bertram en Hyönä?',
                options: ['De route via het hele woord weegt dan het zwaarst', 'Alleen de delen tellen', 'Het woord wordt niet gelezen'],
                answer: 'De route via het hele woord weegt dan het zwaarst',
              },
              note: 'Korte, frequente samenstellingen lees je grotendeels als geheel. De delen doen mee, maar wegen minder.',
            },
          ],
          note: 'Geen race met één winnaar, maar een optelsom: alle routes dragen bij, en lengte en frequentie bepalen hoeveel.',
        },
      },
      {
        text: 'In Het woord zag je twee soorten versprekingen: klanken die ruilen en woorden die ruilen. Er is een derde, en die is het mooiste bewijs voor losse morfemen. Victoria Fromkin (1971) en Merrill Garrett (1975) beschreven versprekingen waarin twee *stammen* ruilen terwijl de affixen blijven staan. Iemand wil *de plantjes water geven* zeggen en zegt *de watertjes plant geven*. Het verkleinwoord bleef op zijn plek; alleen de stammen verhuisden. Dat kan alleen als *plant* en *-jes* op dat moment twee losse stukken zijn. Dit heet *stranding*: het affix blijft gestrand achter.',
        rule: 'Bij stranding ruilen de stammen en blijven de affixen staan: bewijs dat je woorden tijdens het spreken opbouwt.',
        lab: {
          label: 'Tik een verspreking (gemaakt naar echte patronen)',
          chips: [
            {
              k: 'de watertjes plant geven',
              out: 'stranding: -jes bleef staan',
              note: 'Bedoeld: de plantjes water geven. De stammen ruilden, het verkleinwoord niet.',
            },
            {
              k: 'hij huiste naar fiets',
              out: 'stranding: -te bleef staan',
              note: 'Bedoeld: hij fietste naar huis. De verleden tijd hangt aan de plek, niet aan de stam.',
            },
            { k: 'wode rijn', out: 'klankwissel', note: 'Bedoeld: rode wijn. Twee beginklanken ruilden, zoals je al kende.' },
            {
              k: 'de kat uitlaten en de hond voeren',
              out: 'woordwissel',
              note: 'Bedoeld: de hond uitlaten en de kat voeren. Hele woorden ruilden van plek.',
            },
          ],
        },
        deep: {
          q: 'Wat doet een gestrand stukje met zijn nieuwe buur?',
          a: 'Het past zich aan. Wie *het dak van de schuur* wil zeggen en *de schuur van het dak* produceert, zet de lidwoorden netjes om: niet *de dak* of *het schuur*. Garrett leidde daaruit af dat zulke stukjes pas ná de ruil hun vorm krijgen. Eerst staat er een abstract ‘lidwoord’ of ‘meervoud’, dan pas *de*, *het*, *-en* of *-s*. Dat is dezelfde volgorde als in Morfeem, proces of paradigma?: eerst de kenmerken, daarna de vorm.',
        },
      },
      {
        text: 'Moet het eigenlijk opslaan óf opbouwen zijn? Joan Bybee (1995) zegt: nee. In haar *gebruiksgebaseerde* model heeft elke vorm die je vaak hoort een eigen *lexicale sterkte*, en regels zijn niets anders dan *schema’s* die over opgeslagen vormen heen getrokken worden. Hoe meer verschillende woorden een patroon volgen (de *typefrequentie*), hoe sterker het schema; hoe vaker één vorm voorkomt (de *tokenfrequentie*), hoe steviger die vorm zelf staat. Harald Baayen en collega’s (2011) gingen verder: in hun model van *naive discriminative learning* leert het brein rechtstreeks verbanden tussen letters en betekenissen, zonder één morfeem. Toch voorspelt het model de effecten van familie en frequentie die je in deze les zag.',
        rule: 'Gebruiksgebaseerd: geen scherpe grens tussen geheugen en regel, maar sterkte door gebruik.',
        quiz: {
          q: 'Welk achtervoegsel geeft volgens Bybee het sterkste schema?',
          options: [
            'Een achtervoegsel dat in veel verschillende woorden zit',
            'Een achtervoegsel dat in één heel frequent woord zit',
            'Een achtervoegsel dat kort is',
          ],
          answer: 'Een achtervoegsel dat in veel verschillende woorden zit',
          why: 'Typefrequentie maakt een schema sterk: dat is de versie van productiviteit bij Bybee. Tokenfrequentie versterkt alleen het ene woord zelf.',
        },
        deep: {
          q: 'Wat betekent dit voor de d/t-fout?',
          a: 'In zo’n model staan *vind* en *vindt* allebei in je geheugen, elk met een eigen sterkte. Bij elke zin wedijveren ze, en de sterkste springt eerder naar voren. Homofoondominantie is dan geen bijverschijnsel, maar een directe voorspelling: de vaakst geziene vorm wint onder druk. De regel is een schema dat je er bewust tegenin kunt zetten.',
        },
      },
      {
        text: 'Terug naar de schrijver. Homofoondominantie werkt in twee richtingen. Bij *vinden* is *vind* heel frequent (*ik vind dat…*), dus sluipt *hij vind* erin. Bij *worden* is het andersom: *wordt* komt veel vaker voor dan *word* (*het wordt*, *hij wordt*, de lijdende vorm), dus schrijven mensen *ik wordt*. Het onderzoek van Dominiek Sandra en collega’s laat zien dat de fout toeneemt onder tijdsdruk en bij een grotere afstand tot het onderwerp, en dat ook goede spellers hem maken. Het is geen kennisprobleem maar een geheugenprobleem. De remedie is dus niet nóg een keer de regel leren, maar een controlemoment inbouwen op precies de plekken waar een homofoon op de loer ligt, zoals werkwoorden met een stam op *d*.',
        rule: 'Controleer gericht: in de tegenwoordige tijd enkelvoud heeft een werkwoord met een stam op *d* een even klinkende tweeling (*word*, *wordt*).',
        mark: {
          q: 'Tik de persoonsvormen waar een homofoon op de loer ligt',
          sentence: 'Ik word steeds moe, hij vindt dat raar, en zij loopt gewoon door.',
          targets: [1, 5],
          note: 'word (naast wordt) en vindt (naast vind) hebben een even klinkende tweelingvorm. loopt niet: loop en loopt klinken anders. Alleen bij de tweelingen kan het geheugen de verkeerde aanreiken.',
        },
      },
    ],
  },
  {
    kind: 'sort',
    id: 'wat-ruilde',
    prompt: 'Welke eenheid ruilde in deze verspreking?',
    buckets: ['klank', 'stam (affix bleef staan)', 'heel woord'],
    items: [
      { t: 'rode wijn → wode rijn', b: 0 },
      { t: 'lange bomen → bange lomen', b: 0 },
      { t: 'koude kaas → kade kous', b: 0 },
      { t: 'de plantjes water geven → de watertjes plant geven', b: 1 },
      { t: 'een kopje thee → een theetje kop', b: 1 },
      { t: 'hij fietste naar huis → hij huiste naar fiets', b: 1 },
      { t: 'de bakker belt → de beller bakt', b: 1 },
      { t: 'de hond uitlaten en de kat voeren → de kat uitlaten en de hond voeren', b: 2 },
      { t: 'het dak van de schuur → de schuur van het dak', b: 2 },
    ],
    why: 'Klanken ruilen binnen hun plek in de lettergreep. Stammen ruilen en laten -jes, -te, -er en -t gestrand achter. Hele woorden ruilen van plek, en het lidwoord past zich aan de nieuwe buur aan: de schuur, het dak.',
  },
  {
    kind: 'chat',
    id: 'werkstuk',
    prompt: 'App met Jamal, die een werkstuk schrijft',
    intro: 'Kies telkens het antwoord dat klopt met het onderzoek uit deze les.',
    contact: { name: 'Jamal', role: 'je studiegenoot', initials: 'J' },
    rounds: [
      {
        say: 'Ik schrijf steeds ‘ik wordt’. Ik ken de regel echt wel! Ben ik dom?',
        options: ['Nee. Wordt komt veel vaker voor dan word, dus je geheugen reikt die vorm als eerste aan.', 'Ja, je moet de regel gewoon beter leren.'],
        right: 0,
        fix: 'ik wordt → ik word',
        why: 'Homofoondominantie: de frequentste tweelingvorm sluipt erin, ook bij wie de regel kent.',
      },
      {
        say: 'Het gebeurt vooral als ik snel typ, en als de zin lang is.',
        options: [
          'Logisch: onder tijdsdruk wint de snelle geheugenroute, en bij afstand raak je het onderwerp kwijt.',
          'Dan typ je gewoon te slordig, dat heeft niets met je hoofd te maken.',
        ],
        right: 0,
        fix: 'Niets te verbeteren: precies wat Sandra en collega’s vonden.',
        why: 'Tijdsdruk en afstand tot het onderwerp vergroten de kans dat de regelroute het verliest.',
      },
      {
        say: 'Mijn docent zegt: zoek eerst het onderwerp. Waarom helpt dat?',
        options: ['Het zet de regelroute bewust aan; het geheugen geeft alleen de vaakst geziene vorm.', 'Het onderwerp bepaalt hoe het werkwoord klinkt.'],
        right: 0,
        fix: 'Niets te verbeteren: twee routes, en jij kiest bewust de trage.',
        why: 'Hij vindt en hij vind klinken hetzelfde. Alleen de regel, via het onderwerp, kan het verschil maken.',
      },
      {
        say: 'Gelukkig. Dan kijk ik straks mijn hele werkstuk nog eens na, woord voor woord.',
        options: [
          'Slimmer: controleer gericht elke persoonsvorm van een werkwoord met een stam op d.',
          'Goed idee, lees vooral alle bijvoeglijke naamwoorden nog eens.',
        ],
        right: 0,
        fix: 'Niets te verbeteren: gericht nalezen.',
        why: 'Alleen daar bestaat een even klinkende tweeling. Loop en loopt kun je niet verwarren.',
      },
    ],
    bye: 'Top, dan zoek ik nu alle d-stammen. Ik vind, hij vindt, jij vindt het vast goed.',
  },
  {
    kind: 'bet',
    id: 'dominantie',
    prompt: 'Welke fout voorspelt homofoondominantie bij het werkwoord worden?',
    options: ['ik wordt', 'hij word', 'allebei even vaak'],
    answer: 'ik wordt',
    why: 'Wordt komt veel vaker voor dan word (het wordt, hij wordt, de lijdende vorm). De frequentste vorm dringt zich op waar de zeldzamere hoort: ik wordt.',
  },
  {
    kind: 'proofread',
    id: 'd-stammen',
    prompt: 'Lees het berichtje na',
    intro: 'Drie werkwoordsfouten, alle drie bij een stam op d. Eén vorm lijkt fout, maar is goed.',
    tokens: [
      { t: 'Hoi' },
      { t: 'Sam,' },
      { t: 'ik' },
      { t: 'wordt', fix: 'word', why: 'ik + stam: word. Wordt komt vaker voor en dringt zich op.' },
      { t: 'morgen' },
      { t: 'om' },
      { t: 'negen' },
      { t: 'uur' },
      { t: 'verwacht.' },
      { t: 'Word' },
      { t: 'jij' },
      { t: 'ook' },
      { t: 'gevraagd?' },
      { t: 'Mijn' },
      { t: 'zus,' },
      { t: 'die' },
      { t: 'bij' },
      { t: 'de' },
      { t: 'bank' },
      { t: 'werkt,' },
      { t: 'vind', fix: 'vindt', why: 'Onderwerp mijn zus: zij vindt. De bijzin ertussen en de frequente vorm vind lokken de fout uit.' },
      { t: 'het' },
      { t: 'spannend.' },
      { t: 'Gisteren' },
      { t: 'antwoorde', fix: 'antwoordde', why: 'Verleden tijd van antwoorden: stam antwoord + de. Je hoort één d, je schrijft er twee.' },
      { t: 'niemand' },
      { t: 'op' },
      { t: 'mijn' },
      { t: 'mail.' },
    ],
    done: {
      title: 'Drie tweelingen gevangen',
      text: 'ik word, zij vindt, antwoordde. En Word jij? was goed: jij achter de persoonsvorm krijgt geen t. Juist die vorm lijkt fout, omdat wordt zo vaak voorkomt.',
    },
  },
  {
    kind: 'swipe',
    id: 'lexicon-waar',
    prompt: 'Klopt deze zin?',
    cards: [
      {
        t: 'Volgens Kuperman en collega’s wint bij het lezen van een samenstelling één route.',
        ok: false,
        fix: 'Alle routes dragen tegelijk bij',
        why: 'De frequentie van het geheel én van beide delen beïnvloedde de leestijd.',
      },
      {
        t: 'Bertram en Hyönä vonden dat lange samenstellingen eerder in stukken gelezen worden.',
        ok: true,
        why: 'Kort en frequent: als geheel. Lang: in delen.',
      },
      {
        t: 'In de watertjes plant geven ruilden de verkleinwoorden van plaats.',
        ok: false,
        fix: 'De stammen ruilden, -jes bleef staan',
        why: 'Stranding: het affix blijft gestrand achter.',
      },
      {
        t: 'Stranding laat zien dat je woorden tijdens het spreken opbouwt uit stam en affix.',
        ok: true,
        why: 'Anders kon een stam niet zonder zijn affix verhuizen.',
      },
      { t: 'Volgens Bybee is een regel een schema over opgeslagen vormen.', ok: true, why: 'Geen scherpe grens tussen geheugen en regel.' },
      {
        t: 'Het model van Baayen en collega’s uit 2011 gebruikt morfemen als bouwstenen.',
        ok: false,
        fix: 'Het werkt zonder morfemen',
        why: 'Het leert rechtstreeks verbanden tussen letters en betekenissen.',
      },
      {
        t: 'Ik wordt is een typische fout, omdat wordt vaker voorkomt dan word.',
        ok: true,
        why: 'Homofoondominantie, in de andere richting dan bij hij vind.',
      },
    ],
  },
];
