import type { StepInput } from '../../schema';

/** Onderzoek bij d19: een derde uitlegronde op onderzoeksniveau, daarna zwaardere oefeningen. */
export const ONDERZOEK_D19: StepInput[] = [
  {
    kind: 'explain',
    id: 'onderzoek',
    title: 'Korte woorden, volle grammatica',
    panels: [
      {
        text: 'Is *prof* een nieuw woord, of een andere vorm van *professor*? Kijk naar de grammatica. Een afkapping erft het lidwoord van haar bronwoord: *het lab* (*het laboratorium*), *het abo* (*het abonnement*), *de uni* (*de universiteit*). Maar het meervoud maakt ze zelf: *profs*, niet *professoren*. Een afkapping is dus een nieuw woord dat iets van zijn bron meeneemt.',
        rule: 'Een afkapping erft het lidwoord van haar bron, maar buigt als een nieuw kort woord: *het lab*, *de labs*.',
        paradigm: {
          q: 'Vul het meervoud van de afkapping in',
          cols: ['meervoud van de bron', 'meervoud van de afkapping'],
          rows: [
            {
              label: 'prof (professor)',
              cells: ['professoren', { fill: 'profs', hint: 'De afkapping kiest -s, net als labs. Op een medeklinker: geen apostrof.' }],
            },
            { label: 'lab (laboratorium)', cells: ['laboratoria', { fill: 'labs', hint: 'Niet het Latijnse -a van laboratoria: het korte woord kiest -s.' }] },
            {
              label: 'abo (abonnement)',
              cells: ['abonnementen', { fill: 'abo’s', hint: 'Eindigt op één klinkerletter: een apostrof voor de s, net als foto’s.' }],
            },
            { label: 'uni (universiteit)', cells: ['universiteiten', { fill: 'uni’s', hint: 'Eindigt op één klinkerletter: apostrof.' }] },
          ],
          extra: ['prof’s', 'abos', 'unis'],
          note: 'Het lidwoord komt van de bron, het meervoud volgt de vorm van het nieuwe woord: profs, labs, abo’s, uni’s.',
        },
      },
      {
        text: 'Hoe spreek je *btw* uit? *bee-tee-WEE*: de klemtoon valt op de laatste letter. Zo ook *pc*, *tv* en *EHBO*. Dat is opvallend, want een samenstelling heeft de klemtoon meestal vooraan: *VOETbal*. Een initiaalwoord klinkt eerder als een rijtje losse woorden, met de klemtoon achteraan, zoals een woordgroep. Een acroniem als *NAVO* of *havo* gedraagt zich wel als een gewoon woord: *NA-vo*, *HA-vo*.',
        rule: 'Initiaalwoord: klemtoon op de laatste letter (*bee-tee-WEE*). Acroniem: klemtoon zoals in een gewoon woord (*NA-vo*).',
        quiz: {
          q: 'Waar ligt de klemtoon in ‘EHBO’?',
          options: ['op de E', 'op de H', 'op de B', 'op de O'],
          answer: 'op de O',
          why: 'Initiaalwoorden krijgen de klemtoon op de laatste letter: ee-haa-bee-OO. Net als btw en pc.',
        },
        deep: {
          q: 'Wat zegt dat over het woord?',
          a: 'Dat ‘woord’ op verschillende manieren kan. In de spelling is *btw* één woord, en in de grammatica ook: *de btw*, met één lidwoord. Maar in de klank gedraagt het zich als een rijtje van drie, met de nadruk achteraan. Spelling, grammatica en klank vallen hier niet samen.',
        },
      },
      {
        text: 'Letterwoorden doen gewoon mee met de morfologie. Een lid van de VVD is een *VVD’er*, iemand met tbs een *tbs’er*, een leerling van het vwo een *vwo’er*. De apostrof hoort bij letterwoorden die je letter voor letter uitspreekt, net als in *tv’s* en *pc’tje*. Een acroniem dat je als woord uitspreekt, gaat verder: van *havo* maak je *havist*.',
        rule: 'Letterwoord letter voor letter + achtervoegsel: apostrof (*VVD’er*, *tv’tje*). Een acroniem gedraagt zich als een gewoon woord (*havist*).',
        build: {
          before: 'Een lid van de PvdA is een…',
          stem: 'PvdA',
          endings: ['er', '’er', '-er', 'ist'],
          answer: '’er',
          note: 'PvdA spreek je letter voor letter uit: pee-vee-dee-AA. Dan komt er een apostrof voor -er: PvdA’er.',
        },
      },
      {
        text: 'Het eindpunt: het letterwoord wordt een gewoon woord, en niemand ziet de letters nog. *Radar*, *laser* en *aids* waren Engelse letterwoorden; nu schrijf je ze klein, als soortnaam. *Pin* (uit het Engelse *personal identification number*) werd zelfs een werkwoord: *pinnen*, *ik pin*, *gepind*. *Sms* gaat dezelfde weg: *sms’en*, nog met een apostrof, omdat je het letter voor letter zegt. Tik de woorden die als letterwoord begonnen.',
        rule: 'Een letterwoord kan een gewoon woord worden: klein geschreven, en zelfs een werkwoord (*pinnen*).',
        mark: {
          q: 'Tik de woorden die als letterwoord begonnen',
          sentence: 'radar lepel laser pinnen bus aids',
          targets: [0, 2, 3, 5],
          note: 'radar, laser, pinnen en aids begonnen als letterwoord. bus is een afkapping van omnibus, lepel een gewoon woord.',
        },
      },
    ],
  },
  {
    kind: 'ladder',
    id: 'inburgering',
    prompt: 'Van afkorting naar gewoon woord',
    intro: 'Let op drie dingen: hoofdletters, letter voor letter uitspreken, en of je de letters nog herkent.',
    sentence: { before: 'Op deze sport staat:', after: '' },
    steps: [{ t: 'KLM' }, { t: 'tv' }, { t: 'havo' }, { t: 'laser' }],
    low: 'nog een afkorting',
    high: 'een gewoon woord',
    startHint: 'Begin bij de naam in hoofdletters die je letter voor letter zegt.',
    done: {
      title: 'Ingeburgerd',
      text: 'KLM: een naam, letter voor letter. tv: klein, maar nog letters. havo: als woord uitgesproken. laser: niemand ziet de letters nog.',
    },
  },
  {
    kind: 'proofread',
    id: 'nalezen',
    prompt: 'Lees de tekst na',
    intro: 'Er staan vier fouten in de spelling van korte woorden. Tik ze aan.',
    tokens: [
      { t: 'In' },
      { t: 'het' },
      { t: 'lab' },
      { t: 'gaven' },
      { t: 'twee' },
      { t: 'prof’s', fix: 'profs', why: 'Na een medeklinker komt geen apostrof: profs, net als labs.' },
      { t: 'drie' },
      { t: 'demos', fix: 'demo’s', why: 'demo eindigt op één klinkerletter: demo’s, net als foto’s.' },
      { t: 'aan' },
      { t: 'een' },
      { t: 'groep' },
      { t: 'VVD-ers.', fix: 'VVD’ers.', why: 'Een afleiding van een letterwoord dat je letter voor letter zegt: een apostrof, geen streepje.' },
      { t: 'Daarna' },
      { t: 'kochten' },
      { t: 'ze' },
      { t: 'twee' },
      { t: 'tvs.', fix: 'tv’s.', why: 'Het meervoud van een initiaalwoord krijgt een apostrof: tv’s.' },
    ],
    done: { title: 'Vier korte woorden', text: 'profs zonder apostrof, demo’s en tv’s met, en VVD’ers met een apostrof in plaats van een streepje.' },
  },
  {
    kind: 'bet',
    id: 'pinde',
    prompt: 'Pinnen is een gewoon werkwoord geworden. Gisteren … ik bij de bakker.',
    options: ['pinde', 'pinte', 'PIN-de'],
    answer: 'pinde',
    why: 'Stam pin, op een n: niet in ’t kofschip, dus -de. Een letterwoord dat een werkwoord werd, volgt gewoon de regels: ik pin, ik pinde, gepind.',
  },
  {
    kind: 'sort',
    id: 'klemtoon',
    prompt: 'Waar ligt de klemtoon?',
    buckets: ['op de laatste letter', 'zoals in een gewoon woord'],
    items: [
      { t: 'btw', b: 0 },
      { t: 'pc', b: 0 },
      { t: 'EHBO', b: 0 },
      { t: 'vwo', b: 0 },
      { t: 'cao', b: 0 },
      { t: 'NAVO', b: 1 },
      { t: 'havo', b: 1 },
      { t: 'mavo', b: 1 },
      { t: 'NASA', b: 1 },
    ],
    why: 'bee-tee-WEE, pee-SEE, ee-haa-bee-OO, vee-wee-OO, see-aa-OO: initiaalwoorden, klemtoon achteraan. NA-vo, HA-vo, MA-vo, NA-sa: acroniemen, klemtoon zoals in een gewoon woord.',
  },
  {
    kind: 'swipe',
    id: 'kort-waar',
    prompt: 'Klopt deze zin?',
    cards: [
      { t: 'Het is het lab, omdat laboratorium een het-woord is.', ok: true, why: 'Een afkapping erft het lidwoord van haar bron.' },
      { t: 'Het meervoud van prof is professoren, net als bij het bronwoord.', ok: false, fix: 'profs', why: 'Het meervoud maakt de afkapping zelf.' },
      { t: 'In btw valt de klemtoon op de b.', ok: false, fix: 'op de w: bee-tee-WEE', why: 'Initiaalwoorden krijgen de klemtoon achteraan.' },
      { t: 'Een lid van de VVD is een VVD’er.', ok: true, why: 'Letterwoord letter voor letter + -er: een apostrof.' },
      {
        t: 'Laser schrijf je met hoofdletters, omdat het een letterwoord is.',
        ok: false,
        fix: 'laser is een gewoon woord geworden: klein',
        why: 'Niemand kent de letters nog; het is een soortnaam.',
      },
      { t: 'Pinnen begon als letterwoord.', ok: true, why: 'Pin: personal identification number. Nu een gewoon werkwoord: gepind.' },
    ],
  },
];
