import type { StepInput } from '../../schema';

/** Onderzoek bij w13: een derde uitlegronde op onderzoeksniveau, daarna zwaardere oefeningen. */
export const ONDERZOEK_W13: StepInput[] = [
  {
    kind: 'explain',
    id: 'onderzoek',
    title: 'Patronen, schalen en ketens die breken',
    panels: [
      {
        text: 'Hoe vind je hyponiemen in miljoenen zinnen? Marti Hearst (1992) liet een computer zoeken naar vaste patronen: *Y zoals X*, *X en andere Y*, *Y, waaronder X*. Uit *roofvogels zoals de buizerd* haalt de computer: een buizerd is een roofvogel. Maar het patroon is niet kieskeurig: *honden en andere huisdieren* levert ook een paar op, terwijl *huisdier* een functionele categorie is (zie de verdieping). Het patroon vindt dus ‘soort van’ in brede zin, niet alleen echte taxonymie.',
        rule: 'De taal wijst de stamboom zelf aan: *zoals*, *en andere* en *waaronder* staan tussen hyponiem en hyperoniem.',
        mark: {
          q: 'Tik de drie hyponiemen die een patroon van Hearst in deze zin vindt',
          sentence: 'Roofvogels zoals de buizerd en de sperwer jagen op muizen en andere knaagdieren.',
          targets: [3, 6, 9],
          note: 'Y zoals X: buizerd en sperwer onder roofvogel. X en andere Y: muis onder knaagdier.',
        },
      },
      {
        text: 'Graduele woorden staan op een *schaal*: *lauw*, *warm*, *heet*. Wie *heet* zegt, zegt ook *warm*: dat volgt logisch. Wie *warm* zegt, laat verstaan dat het *niet heet* is, maar dat volgt niet logisch: het is een *implicatuur*. Paul Grice (1975) legde uit waarom: je bent zo informatief als nodig, dus had je *heet* gezegd als het heet was. Laurence Horn (1972) beschreef zulke schalen, die nu *Horn-schalen* heten; een implicatuur kun je intrekken, een logisch gevolg niet.',
        rule: 'Sterk sluit zwak in: heet is ook warm. Zwak laat alleen verstaan dat sterk niet geldt.',
        lab: {
          label: 'Tik een zin',
          chips: [
            { k: 'warm, zelfs heet', out: 'klopt', note: 'Van zwak naar sterk: je trekt de implicatuur ‘niet heet’ in.' },
            { k: 'heet, zelfs warm', out: 'raar', note: 'Heet zegt al warm. Zelfs voegt niets toe.' },
            { k: 'warm, maar niet heet', out: 'klopt', note: 'Je maakt de implicatuur expliciet.' },
            { k: 'heet, maar niet warm', out: 'tegenspraak', note: 'Heet betekent ook warm: dit kan logisch niet.' },
          ],
        },
      },
      {
        text: 'Deel-geheel is niet één relatie, maar een familie. Morton Winston, Roger Chaffin en Douglas Herrmann (1987) onderscheidden er zes, onder meer *onderdeel* (wiel, fiets), *lid* (boom, bos), *portie* (plak, kaas) en *stof* (staal, fiets). Dat verklaart waarom meronymie niet altijd doorloopt. *De arm hoort bij de violist* en *de violist hoort bij het orkest*, maar de arm is geen deel van het orkest. De eerste stap is onderdeel, de tweede lid: twee soorten, en dan breekt de keten. Eén soort is wel nodig, maar geen garantie: denk aan de klink uit de eerste uitleg.',
        rule: 'Deel van loopt alleen door binnen één soort deel-geheel.',
        quiz: {
          q: 'Het wiel hoort bij de fiets, de fiets hoort bij de verhuurvloot. Is het wiel een deel van de vloot?',
          options: ['Nee, dat klinkt raar', 'Ja, deel van loopt altijd door'],
          answer: 'Nee, dat klinkt raar',
          why: 'Wiel en fiets: onderdeel. Fiets en vloot: lid van een groep. Bij twee soorten breekt de keten.',
        },
      },
      {
        text: 'Samenstellingen zijn een fabriek van hyponiemen. Het laatste deel is de baas en geeft het hyperoniem: een *keukenstoel* is een soort *stoel*. Bouw je verder, dan schuift de baas mee: een *keukenstoelfabriek* is een soort *fabriek*, geen soort stoel. Maar een *roodborst* is geen soort *borst*: het is een vogel mét een rode borst. Zo’n samenstelling zonder baas binnenin heet *exocentrisch*.',
        rule: 'Het laatste deel van een samenstelling is het hyperoniem, behalve bij een exocentrische samenstelling.',
        bracket: {
          q: 'Bouw het woord en kijk telkens wat het is',
          tree: '[[keuken stoel] fabriek]',
          nodes: [
            { w: 'keukenstoel', cat: 'zn', note: 'Stoel is de baas: een keukenstoel is een soort stoel.' },
            { w: 'keukenstoelfabriek', cat: 'zn', note: 'Nu is fabriek de baas: een soort fabriek, die keukenstoelen maakt.' },
          ],
          traps: [{ w: 'stoelfabriek', note: 'Dan zou het een stoelfabriek in de keuken zijn. Deze fabriek maakt keukenstoelen.' }],
          note: 'Bij elke stap wordt het nieuwe laatste deel het hyperoniem. Zo hangt elke samenstelling als nieuwe tak onder haar baas.',
        },
      },
    ],
  },
  {
    kind: 'ladder',
    id: 'schaal',
    prompt: 'Van zwak naar sterk',
    intro: 'Zet de woorden op de schaal. Elk woord zegt meer dan het woord eronder.',
    sentence: { before: 'Het water in de pan is', after: '.' },
    steps: [{ t: 'lauw' }, { t: 'warm' }, { t: 'heet' }, { t: 'kokend' }],
    low: 'zwak',
    high: 'sterk',
    startHint: 'Begin bij het woord dat het minst zegt.',
    done: { title: 'Een Horn-schaal', text: 'Wie kokend zegt, zegt ook heet. Wie warm zegt, laat verstaan: niet heet. Dat laatste kun je intrekken.' },
  },
  {
    kind: 'sort',
    id: 'deel-soort',
    prompt: 'Welk soort deel-geheel?',
    buckets: ['onderdeel', 'lid van een groep', 'portie', 'stof'],
    items: [
      { t: 'wiel → fiets', b: 0 },
      { t: 'toets → toetsenbord', b: 0 },
      { t: 'boom → bos', b: 1 },
      { t: 'speler → team', b: 1 },
      { t: 'schaap → kudde', b: 1 },
      { t: 'plak → kaas', b: 2 },
      { t: 'slok → koffie', b: 2 },
      { t: 'staal → fiets', b: 3 },
      { t: 'meel → brood', b: 3 },
      { t: 'glas → ruit', b: 3 },
    ],
    why: 'Onderdeel: een stuk met een eigen functie. Lid: één van een verzameling. Portie: een stuk van een hoeveelheid. Stof: waarvan iets gemaakt is.',
  },
  {
    kind: 'bet',
    id: 'tegenspraak',
    prompt: 'Welke zin is een echte tegenspraak?',
    options: ['Het water is warm, maar niet heet.', 'Het water is heet, maar niet warm.', 'Het water is warm, zelfs heet.'],
    answer: 'Het water is heet, maar niet warm.',
    why: 'Heet sluit warm in: dat is logica. Warm, maar niet heet maakt alleen de implicatuur expliciet, en warm, zelfs heet trekt haar in.',
  },
  {
    kind: 'highlight',
    id: 'bomenweb',
    prompt: 'Kleur het web',
    intro: 'Drie stiften: een soort boom, een deel van een boom, of het algemene woord erboven.',
    pens: [
      { id: 'soort', label: 'hyponiem', tag: 'een soort boom', ask: 'Is dit een soort boom?', accent: 'green' },
      { id: 'deel', label: 'meroniem', tag: 'een deel', ask: 'Is dit een deel van een boom?', accent: 'orange' },
      { id: 'boven', label: 'hyperoniem', tag: 'het algemene woord', ask: 'Is dit het algemene woord boven de andere?', accent: 'blue' },
    ],
    words: [
      { t: 'Bij' },
      { t: 'de' },
      { t: 'eik', role: 'soort' },
      { t: 'en' },
      { t: 'de' },
      { t: 'beuk', role: 'soort' },
      { t: 'vielen' },
      { t: 'takken', role: 'deel' },
      { t: 'en' },
      { t: 'bladeren,', role: 'deel' },
      { t: 'maar' },
      { t: 'geen' },
      { t: 'enkele' },
      { t: 'boom', role: 'boven' },
      { t: 'ging' },
      { t: 'om.' },
    ],
    done: { title: 'Web compleet', text: 'Eik en beuk zijn co-hyponiemen, takken en bladeren meroniemen, en boom is het hyperoniem dat ze samenhoudt.' },
  },
  {
    kind: 'swipe',
    id: 'relaties',
    prompt: 'Klopt deze zin?',
    cards: [
      { t: 'Het patroon X en andere Y vindt ook functionele categorieën.', ok: true, why: 'Honden en andere huisdieren levert hond onder huisdier op.' },
      { t: 'Heet en warm staan op één Horn-schaal.', ok: true, why: 'Heet is de sterke kant, warm de zwakke.' },
      {
        t: 'Wie warm zegt, zegt logisch dat het niet heet is.',
        ok: false,
        fix: 'Dat is een implicatuur, geen logisch gevolg',
        why: 'Je kunt hem intrekken: warm, zelfs heet.',
      },
      {
        t: 'Een roodborst is een soort borst.',
        ok: false,
        fix: 'Roodborst is exocentrisch: het is een vogel',
        why: 'Het laatste deel is hier niet het hyperoniem.',
      },
      { t: 'Een keukenstoelfabriek is een soort fabriek.', ok: true, why: 'Het laatste deel is de baas.' },
      {
        t: 'Deel van loopt altijd door, ook van onderdeel naar lid.',
        ok: false,
        fix: 'Bij twee soorten deel-geheel breekt de keten',
        why: 'De arm hoort bij de violist en de violist bij het orkest, maar de arm niet bij het orkest.',
      },
    ],
  },
];
