import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": lettergrepen vinden, tellen en knippen met een stappenplan. */
export const LES_G20: LessonInput = {
  id: 'g20',
  stage: 'regels',
  domain: 'fon',
  also: ['orth'],
  title: 'Lettergrepen vinden en knippen',
  skill: 'Spelling',
  icon: 'klap',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Klappen, tellen, knippen',
      panels: [
        {
          text: 'Een lettergreep is een stukje van een woord dat je in één keer uitspreekt. Zeg het woord langzaam en klap bij elk stukje: *boek* (één klap), *ta-fel* (twee), *va-kan-tie* (drie), *in-for-ma-tie* (vier). Zo hoor je hoeveel lettergrepen een woord heeft.',
          rule: 'Eén klap is één lettergreep.',
          bins: {
            q: 'Klap het woord en zet het in de goede bak',
            bins: ['1 lettergreep', '2 lettergrepen', '3 lettergrepen'],
            items: [
              { thing: 'boek', bin: 0, note: 'boek: één klap.' },
              { thing: 'huis', bin: 0, note: 'huis: één klap. ui is één klank.' },
              { thing: 'visser', bin: 1, note: 'vis-ser: twee klappen.' },
              { thing: 'bloempot', bin: 1, note: 'bloem-pot: twee klappen.' },
              { thing: 'vleermuis', bin: 1, note: 'vleer-muis: twee klappen.' },
              { thing: 'pannenkoek', bin: 2, note: 'pan-nen-koek: drie klappen.' },
              { thing: 'zonnebloem', bin: 2, note: 'zon-ne-bloem: drie klappen. De doffe e is ook een klinkerklank.' },
              { thing: 'struisvogel', bin: 2, note: 'struis-vo-gel: drie klappen.' },
            ],
            note: 'Klappen werkt altijd: elk stukje dat je in één keer zegt, is een lettergreep.',
          },
        },
        {
          text: 'Elke lettergreep heeft precies één *klinkerklank*. Dat kan één letter zijn (*a*, *e*, *i*, *o*, *u*, ook de doffe e in *de*), maar ook twee of meer letters die samen één klank maken: *aa*, *ee*, *oo*, *uu*, *ie*, *oe*, *eu*, *ui*, *ei*, *ij*, *au*, *ou*. Zelfs *aai*, *ooi*, *oei*, *eeuw* en *ieuw* tellen als één klank. Tel dus de klinkerklanken, niet de klinkerletters.',
          rule: 'Aantal klinkerklanken = aantal lettergrepen.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'fietsen', out: 'fiet-sen: 2', note: 'ie is één klank, de doffe e de tweede.' },
              { k: 'sneeuw', out: 'sneeuw: 1', note: 'eeuw is één klank: één lettergreep.' },
              { k: 'leeuwen', out: 'leeu-wen: 2', note: 'eeuw + de doffe e van -en.' },
              { k: 'draaien', out: 'draai-en: 2', note: 'aai is één klank, en dan nog -en.' },
              { k: 'eieren', out: 'ei-e-ren: 3', note: 'ei, e, e: drie klinkerklanken.' },
              { k: 'moeilijk', out: 'moei-lijk: 2', note: 'oei is één klank. In -lijk klinkt ij als een doffe e.' },
            ],
          },
          quiz: {
            q: 'Hoeveel lettergrepen heeft sneeuwbui?',
            options: ['2', '3', '4'],
            answer: '2',
            why: 'sneeuw-bui: twee klinkerklanken, eeuw en ui. Dus twee lettergrepen.',
          },
        },
        {
          text: 'Nu knippen. Gebruik dit stappenplan. *1.* Zoek de klinkerklanken. *2.* Staat er één medeklinker tussen twee klinkerklanken? Dan gaat die mee naar de volgende lettergreep: *ra-men*, *bo-men*, *ze-ven*, *ta-fel*, *le-zen*. *3.* Staan er twee medeklinkers tussen? Dan knip je ertussen: één blijft links, één gaat mee: *kat-ten*, *kan-ten*, *har-ten*, *ap-pel*, *lam-pen*, *mor-gen*.',
          rule: 'Eén medeklinker ertussen: die gaat mee (*ra-men*). Twee medeklinkers: knip ertussen (*kat-ten*).',
          split: {
            word: 'katten',
            answer: 'kat-ten',
            note: 'Twee medeklinkers tussen de a en de e: knip ertussen. kat-ten.',
          },
          quiz: {
            q: 'Hoe knip je ramen?',
            options: ['ra-men', 'ram-en', 'raa-men'],
            answer: 'ra-men',
            why: 'Eén medeklinker (m) tussen a en e: die gaat mee naar de volgende lettergreep. ra-men.',
          },
        },
        {
          text: 'Letters die samen één klank maken, knip je nooit: *oe*, *ie*, *eu*, *ui*, *ij*, *ei*, *aa*, *ee*, *oo*, *uu*, *au*, *ou*. Dus *boe-ken*, *rij-den*, *hui-zen*, *bui-ten*. Ook *ch* blijft heel: *la-chen*, *ka-chel*. Maar *ng* knip je wel: *zin-gen*, *jon-gen*, *vin-ger*. De n blijft links, de g gaat mee naar de volgende lettergreep.',
          rule: 'Nooit knippen in *oe*, *ui*, *ij*, *ch* … Wel knippen in *ng*: *zin-gen*.',
          split: {
            word: 'lachen',
            answer: 'la-chen',
            note: 'ch is één klank en blijft heel. Hij gaat mee naar de volgende lettergreep: la-chen.',
          },
        },
        {
          text: 'Waarom is dit handig? Omdat veel spellingregels werken met lettergrepen. Eindigt een lettergreep op een klinker, dan schrijf je een lange klank met één letter: *ra-men*, *bo-men*. Hoor je een korte klank, dan verdubbel je de medeklinker: *ram-men*, *bom-men*. En aan het eind van een regel breek je een woord af tussen twee lettergrepen. Dat leer je in de volgende lessen.',
          rule: 'Knippen is de basis voor één of twee letters, verdubbelen en afbreken.',
          lab: {
            label: 'Tik een paar',
            chips: [
              { k: 'bomen / bommen', out: 'bo-men · bom-men', note: 'Lange o: één o en één m. Korte o: dubbele m.' },
              { k: 'manen / mannen', out: 'ma-nen · man-nen', note: 'Lange a tegenover korte a.' },
              { k: 'kopen / koppen', out: 'ko-pen · kop-pen', note: 'Lange o tegenover korte o.' },
              { k: 'zeven / zetten', out: 'ze-ven · zet-ten', note: 'Lange e tegenover korte e.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'tellen',
      prompt: 'Hoeveel lettergrepen heeft het woord?',
      buckets: ['2', '3', '4', '5 of meer'],
      items: [
        { t: 'schreeuwen', b: 0 },
        { t: 'moeilijk', b: 0 },
        { t: 'richting', b: 0 },
        { t: 'gemeente', b: 1 },
        { t: 'verhuizen', b: 1 },
        { t: 'gesprekken', b: 1 },
        { t: 'eigenlijk', b: 1 },
        { t: 'apotheek', b: 1 },
        { t: 'vergadering', b: 2 },
        { t: 'oefeningen', b: 2 },
        { t: 'ingewikkeld', b: 2 },
        { t: 'zorgverzekering', b: 3 },
        { t: 'gemeentebelasting', b: 3 },
        { t: 'belastingaangifte', b: 3 },
      ],
      why: 'Twee: schreeu-wen, moei-lijk, rich-ting. Drie: ge-meen-te, ver-hui-zen, ge-sprek-ken, ei-gen-lijk, a-po-theek. Vier: ver-ga-de-ring, oe-fe-nin-gen, in-ge-wik-keld. Vijf of meer: zorg-ver-ze-ke-ring (5), ge-meen-te-be-las-ting (6), be-las-ting-aan-gif-te (6). Tel de klinkerklanken: eeuw, oe, ei en ij in -lijk zijn er elk één.',
    },
    {
      kind: 'choice',
      id: 'verandering',
      prompt: 'Hoe knip je dit woord in lettergrepen?',
      before: 'verandering →',
      after: '',
      options: ['ver-an-de-ring', 've-ran-de-ring', 'ver-and-er-ing', 'ver-an-der-ing'],
      answer: 'ver-an-de-ring',
      why: 'ver- is een voorvoegsel en een eigen lettergreep, dus niet ve-ran. Daarna an-de-ring: n en d uit elkaar, en de r gaat mee.',
    },
    {
      kind: 'type',
      id: 'zaterdagavond',
      prompt: 'Knip het woord in lettergrepen. Typ het met een streepje op elke knip, zoals bo-men.',
      before: 'zaterdagavond →',
      after: '',
      hint: '',
      answer: 'za-ter-dag-a-vond',
      why: 'zaterdag + avond: eerst tussen de delen knippen, dus de g blijft bij zaterdag. Dan za-ter (één medeklinker gaat mee, r en d uit elkaar) en a-vond.',
    },
    {
      kind: 'swipe',
      id: 'knippen',
      prompt: 'Is het goed geknipt?',
      cards: [
        { t: 'lichaam → li-chaam', ok: true, why: 'ch is één klank: die blijft heel en gaat mee naar de volgende lettergreep.' },
        { t: 'dochter → do-chter', ok: false, fix: 'doch-ter', why: 'Tussen o en e staan twee medeklinkerklanken: ch en t. Knip ertussen; ch blijft heel.' },
        { t: 'huisarts → hui-sarts', ok: false, fix: 'huis-arts', why: 'huis + arts: eerst tussen de delen knippen.' },
        { t: 'zingen → zing-en', ok: false, fix: 'zin-gen', why: 'ng knip je wel: de n blijft links, de g gaat mee.' },
        {
          t: 'woning → wo-ning',
          ok: true,
          why: 'Eén medeklinker (n) tussen o en i: die gaat mee. De ng aan het eind blijft samen, want er komt geen klinker meer.',
        },
        { t: 'eeuwig → eeuw-ig', ok: false, fix: 'eeu-wig', why: 'De w gaat mee naar de volgende lettergreep, net als in leeu-wen en nieu-we.' },
        { t: 'draaien → draai-en', ok: true, why: 'aai is één klank en blijft heel. Daarna komt -en.' },
        { t: 'kinderen → kin-der-en', ok: false, fix: 'kin-de-ren', why: 'Eén medeklinker (r) tussen de twee e’s: die gaat mee. kin-de-ren.' },
        { t: 'wachten → wach-ten', ok: true, why: 'ch en t: knip ertussen. ch blijft heel.' },
        {
          t: 'aardappel → aar-dap-pel',
          ok: false,
          fix: 'aard-ap-pel',
          why: 'aard + appel: eerst tussen de delen knippen. Dan ap-pel: de dubbele p gaat uit elkaar.',
        },
        { t: 'ruïne → ru-ï-ne', ok: true, why: 'Het trema laat zien dat er een nieuwe lettergreep begint: ru-ï-ne, drie lettergrepen.' },
        { t: 'goochelen → gooch-e-len', ok: false, fix: 'goo-che-len', why: 'ch blijft heel en gaat mee: goo-che-len.' },
      ],
    },
    {
      kind: 'order',
      id: 'sollicitatiegesprek',
      prompt: 'Zet de lettergrepen in de goede volgorde.',
      tiles: ['ci', 'sprek', 'sol', 'tie', 'li', 'ge', 'ta'],
      answer: 'sol li ci ta tie ge sprek',
      why: 'sol-li-ci-ta-tie-ge-sprek: sollicitatie + gesprek. De dubbele l gaat uit elkaar, en ge- is een eigen lettergreep. Zeven lettergrepen.',
    },
    {
      kind: 'bet',
      id: 'geinteresseerd',
      prompt: 'Hoeveel lettergrepen heeft geïnteresseerd?',
      options: ['3', '4', '5', '6'],
      answer: '5',
      why: 'ge-ïn-te-res-seerd: vijf klinkerklanken (e, ï, e, e, ee). Het trema begint een nieuwe lettergreep, en de dubbele s gaat uit elkaar.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Lastige gevallen',
      panels: [
        {
          text: 'Valkuil 1: veel klinkerletters achter elkaar. Lees ze niet als losse klanken. *aai* in *draaien*, *ooi* in *nooit*, *oei* in *roeien*, *eeuw* in *meeuwen* en *ieuw* in *nieuwe* zijn elk één klank. Een trema laat juist zien dat er een nieuwe lettergreep begint: *i-dee-ën*, *knie-ën*, *Bel-gi-ë*.',
          rule: 'aai, ooi, oei, eeuw, ieuw: één klank. Een trema: een nieuwe lettergreep.',
          quiz: {
            q: 'Hoeveel lettergrepen heeft ideeën?',
            options: ['3', '2', '4'],
            answer: '3',
            why: 'i-dee-ën: de i, de ee, en dan de ë met het trema. Drie lettergrepen.',
          },
        },
        {
          text: 'Valkuil 2: dubbele medeklinkers. Je hoort er maar één, maar je knipt er wel tussen: *bak-ker*, *pan-nen*, *kat-ten*, *zet-ten*, *bel-len*. De eerste blijft links, de tweede gaat mee. Bij *ch* doe je dat niet: die blijft samen (*la-chen*). En bij *ng* knip je tussen de n en de g (*zin-gen*).',
          rule: 'Dubbele medeklinker: knip ertussen (*bak-ker*). ch blijft samen, ng gaat uit elkaar.',
          split: {
            word: 'bakker',
            answer: 'bak-ker',
            note: 'Twee k’s: één blijft links, één gaat mee. bak-ker.',
          },
        },
        {
          text: 'Valkuil 3: samenstellingen en voorvoegsels. Bestaat een woord uit twee woorden, dan knip je eerst tussen die woorden. Daarna knip je elk deel apart: *hand-doek*, *slaap-ka-mer*, *zon-ne-bloem*, *a-vond-e-ten*. Bij *avondeten* zou de gewone regel *a-von-de-ten* geven, maar *avond* en *eten* zijn twee woorden. Ook *be-*, *ge-* en *ver-* zijn een eigen lettergreep: *be-ta-len*, *ge-lo-pen*, *ver-ge-ten*.',
          rule: 'Samenstelling: eerst tussen de delen knippen (*a-vond-e-ten*), dan elk deel apart.',
          split: {
            word: 'avondeten',
            answer: 'a-vond-e-ten',
            note: 'avond + eten: de d blijft bij avond. a-vond-e-ten.',
          },
        },
        {
          text: 'Het hele stappenplan op een rij. *1.* Klap het woord: hoeveel stukjes? *2.* Zoek de klinkerklanken; letters die één klank maken knip je nooit. *3.* Is het een samenstelling? Knip eerst tussen de delen. *4.* Eén medeklinker ertussen: die gaat mee. *5.* Twee medeklinkers ertussen: knip ertussen (ook bij ng), behalve bij ch.',
          rule: 'Klappen, klinkerklanken zoeken, delen scheiden, dan medeklinkers verdelen.',
          split: {
            word: 'zonnebloem',
            answer: 'zon-ne-bloem',
            note: 'zonne + bloem: eerst tussen de delen knippen. Dan zon-ne: de dubbele n gaat uit elkaar. zon-ne-bloem.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'waar-knip',
      prompt: 'Waar ligt de eerste knip in het woord?',
      buckets: ['tussen twee medeklinkers (kat-ten)', 'vóór de enige medeklinker (ra-men)', 'tussen de delen (huis-arts, ver-an-de-ring)'],
      items: [
        { t: 'honger', b: 0 },
        { t: 'monteur', b: 0 },
        { t: 'kussen', b: 0 },
        { t: 'lachten', b: 0 },
        { t: 'kachel', b: 1 },
        { t: 'juichen', b: 1 },
        { t: 'nieuwe', b: 1 },
        { t: 'medicijnen', b: 1 },
        { t: 'werkoverleg', b: 2 },
        { t: 'beantwoorden', b: 2 },
        { t: 'bijeenkomst', b: 2 },
        { t: 'opeens', b: 2 },
        { t: 'kerstavond', b: 2 },
        { t: 'vereniging', b: 2 },
      ],
      why: 'Twee medeklinkers: hon-ger, mon-teur, kus-sen, lach-ten (ch telt als één). Eén medeklinker gaat mee: ka-chel, jui-chen, nieu-we, me-di-cij-nen. Tussen de delen: werk-o-ver-leg, be-ant-woor-den, bij-een-komst, op-eens, kerst-a-vond, ver-e-ni-ging. Met de gewone regel zou je daar fout knippen (wer-ko-ver-leg, ve-re-ni-ging).',
    },
    {
      kind: 'type',
      id: 'verantwoordelijk',
      prompt: 'Knip het woord in lettergrepen. Typ het met een streepje op elke knip, zoals bo-men.',
      before: 'verantwoordelijk →',
      after: '',
      hint: '',
      answer: 'ver-ant-woor-de-lijk',
      why: 'ver- is een eigen lettergreep, dus niet ve-rant. Dan ant-woor: n en t uit elkaar. woor-de-lijk: telkens één medeklinker, die gaat mee.',
    },
    {
      kind: 'choice',
      id: 'rekeningen',
      prompt: 'Hoe knip je dit woord in lettergrepen?',
      before: 'rekeningen →',
      after: '',
      options: ['re-ke-nin-gen', 're-ke-ning-en', 'rek-en-in-gen', 're-ken-in-gen'],
      answer: 're-ke-nin-gen',
      why: 'Telkens één medeklinker tussen de klinkerklanken: re-ke-nin. Dan de ng: die knip je, de g gaat mee. re-ke-nin-gen.',
    },
    {
      kind: 'sort',
      id: 'klanken-tellen',
      prompt: 'Tel de klinkerklanken. Hoeveel lettergrepen?',
      buckets: ['1', '2', '3', '4 of meer'],
      items: [
        { t: 'nooit', b: 0 },
        { t: 'meeuw', b: 0 },
        { t: 'nieuws', b: 0 },
        { t: 'kooien', b: 1 },
        { t: 'mooie', b: 1 },
        { t: 'knieën', b: 1 },
        { t: 'zeeën', b: 1 },
        { t: 'eieren', b: 2 },
        { t: 'egoïst', b: 2 },
        { t: 'reünie', b: 2 },
        { t: 'poëzie', b: 2 },
        { t: 'kopiëren', b: 3 },
        { t: 'bacteriën', b: 3 },
        { t: 'financiële', b: 3 },
      ],
      why: 'Eén: nooit, meeuw, nieuws (ooi, eeuw, ieuw zijn één klank). Twee: kooi-en, mooi-e, knie-ën, zee-ën. Drie: ei-e-ren, e-go-ïst, re-ü-nie, po-ë-zie. Vier of meer: ko-pi-ë-ren (4), bac-te-ri-ën (4), fi-nan-ci-ë-le (5). Een trema begint altijd een nieuwe lettergreep.',
    },
    {
      kind: 'order',
      id: 'ziektekostenverzekering',
      prompt: 'Zet de lettergrepen in de goede volgorde.',
      tiles: ['ver', 'kos', 'ring', 'ziek', 'ze', 'ten', 'ke', 'te'],
      answer: 'ziek te kos ten ver ze ke ring',
      why: 'ziek-te-kos-ten-ver-ze-ke-ring: ziekte + kosten + verzekering. Acht lettergrepen.',
    },
    {
      kind: 'swipe',
      id: 'lastig',
      prompt: 'Klopt het?',
      intro: 'De lastige gevallen door elkaar.',
      cards: [
        { t: 'koningin → ko-nin-gin', ok: true, why: 'Eén medeklinker na ko: die gaat mee. Dan ng: knip ertussen, nin-gin.' },
        { t: 'vanavond → va-na-vond', ok: false, fix: 'van-a-vond', why: 'van + avond: eerst tussen de delen. De n blijft bij van.' },
        {
          t: 'Het woord sneeuwt heeft twee lettergrepen.',
          ok: false,
          fix: 'Het woord sneeuwt heeft één lettergreep.',
          why: 'eeuw is één klank: sneeuwt heeft één klinkerklank, dus één lettergreep.',
        },
        { t: 'onderzoek → on-der-zoek', ok: true, why: 'onder + zoek. n en d uit elkaar: on-der.' },
        { t: 'pechvogel → pe-chvo-gel', ok: false, fix: 'pech-vo-gel', why: 'pech + vogel: eerst tussen de delen. ch blijft bij pech.' },
        { t: 'jongeren → jon-ge-ren', ok: true, why: 'ng knip je: jon-ge. Dan gaat de r mee: ge-ren.' },
        { t: 'geopend → ge-o-pend', ok: true, why: 'ge- is een eigen lettergreep. Dan o-pend: één medeklinker, die gaat mee.' },
        { t: 'erover → e-ro-ver', ok: false, fix: 'er-o-ver', why: 'er + over: eerst tussen de delen. De r blijft bij er.' },
        { t: 'uitleggen → uit-leg-gen', ok: true, why: 'uit + leggen. De dubbele g gaat uit elkaar: leg-gen.' },
        { t: 'eigenaar → ei-ge-naar', ok: true, why: 'Telkens één medeklinker: die gaat mee. ei blijft heel.' },
        { t: 'gebruiken → geb-rui-ken', ok: false, fix: 'ge-brui-ken', why: 'ge- is een voorvoegsel en een eigen lettergreep: ge-brui-ken.' },
        {
          t: 'Het woord bacteriën heeft drie lettergrepen.',
          ok: false,
          fix: 'Het woord bacteriën heeft vier lettergrepen.',
          why: 'bac-te-ri-ën: het trema begint een nieuwe lettergreep. Vier klinkerklanken.',
        },
      ],
    },
    {
      kind: 'rewrite',
      id: 'huiseigenaar',
      prompt: 'Knip elk woord in lettergrepen. Zet een streepje op elke knip.',
      source: 'ongeduldige buren wachten op de huiseigenaar',
      accept: ['on-ge-dul-di-ge bu-ren wach-ten op de huis-ei-ge-naar'],
      why: 'on-ge-dul-di-ge: on- en ge- zijn eigen lettergrepen, l en d uit elkaar. bu-ren: de r gaat mee. wach-ten: ch blijft heel. huis-ei-ge-naar: eerst huis + eigenaar, dan ei-ge-naar.',
    },
    {
      kind: 'bet',
      id: 'verongelukken',
      prompt: 'Hoe knip je verongelukken?',
      options: ['ver-on-ge-luk-ken', 've-ron-ge-luk-ken', 'ver-ong-e-luk-ken', 'ver-on-ge-lukk-en'],
      answer: 'ver-on-ge-luk-ken',
      why: 'Drie voorvoegsels achter elkaar: ver-, on- en ge-. Elk is een eigen lettergreep. Dan luk-ken: de dubbele k gaat uit elkaar.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: knip met streepjes (bo-men) of schrijf het woord',
      intro:
        'Knippen? Typ het woord met een streepje op elke knip, zoals *bo-men*. Tellen? Typ het getal. Bij de andere opdrachten typ je alleen het woord. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Knip in lettergrepen: *ouderavond*',
          a: 'ou-der-a-vond',
          why: 'ouder + avond: eerst tussen de delen knippen. De r blijft bij ouder: niet ou-de-ra-vond.',
        },
        { q: 'Knip in lettergrepen: *onderwijs*', a: 'on-der-wijs', why: 'onder + wijs. n en d uit elkaar: on-der. ij blijft heel.' },
        {
          q: 'Meervoud van *brief*, geknipt in lettergrepen',
          a: 'brie-ven',
          why: 'In het meervoud hoor je een v: brieven. ie blijft heel, de v gaat mee: brie-ven.',
        },
        {
          q: 'Knip in lettergrepen: *echtgenote*',
          a: 'echt-ge-no-te',
          why: 'echt + genote: eerst tussen de delen. Dan ge-no-te: telkens één medeklinker, die gaat mee.',
        },
        { q: 'Knip in lettergrepen: *wandelingen*', a: 'wan-de-lin-gen', why: 'n en d uit elkaar, de l gaat mee, en ng knip je: lin-gen.' },
        {
          q: 'Meervoud van *idee*',
          before: 'Heb jij goede',
          after: 'voor het teamuitje?',
          a: 'ideeën',
          why: 'idee + en: de ee blijft, en het trema laat zien dat er een nieuwe lettergreep begint: i-dee-ën.',
        },
        {
          q: 'Hoeveel lettergrepen heeft *coördinator*? Typ het getal.',
          a: '5',
          also: ['vijf'],
          why: 'co-ör-di-na-tor: het trema begint een nieuwe lettergreep. Vijf klinkerklanken.',
        },
        {
          q: 'Knip in lettergrepen: *uitnodiging*',
          a: 'uit-no-di-ging',
          why: 'uit + nodiging: eerst tussen de delen. Dan telkens één medeklinker: no-di-ging.',
        },
        {
          q: 'Vul de vorm van *liggen* in',
          before: 'Mijn telefoon',
          after: 'nog in de auto. Kun jij hem even pakken?',
          a: 'ligt',
          why: 'liggen: stam lig, plus t. Een werkwoord met g houdt de g: ligt, niet licht.',
        },
        {
          q: 'Knip in lettergrepen: *koninginnen*',
          a: 'ko-nin-gin-nen',
          why: 'Eén medeklinker na ko: die gaat mee. ng knip je: nin-gin. De dubbele n gaat uit elkaar: gin-nen.',
        },
        { q: 'Knip in lettergrepen: *voorouders*', a: 'voor-ou-ders', why: 'voor + ouders: eerst tussen de delen. Niet voo-rou-ders.' },
        {
          q: 'Hoeveel lettergrepen heeft *geïnformeerd*? Typ het getal.',
          a: '4',
          also: ['vier'],
          why: 'ge-ïn-for-meerd: vier klinkerklanken. Het trema begint een nieuwe lettergreep.',
        },
        {
          q: 'Meervoud van *bewijs*, geknipt in lettergrepen',
          a: 'be-wij-zen',
          why: 'In het meervoud hoor je een z: bewijzen. be- is een eigen lettergreep: be-wij-zen.',
        },
        { q: 'Knip in lettergrepen: *ontvangen*', a: 'ont-van-gen', why: 'ont- is een eigen lettergreep. Dan van-gen: ng knip je.' },
        {
          q: 'Verleden tijd van *antwoorden*',
          before: 'De huisarts',
          after: 'meteen op mijn mail.',
          a: 'antwoordde',
          why: 'Stam antwoord, en d staat niet in ’t kofschip: -de. antwoord + de = antwoordde.',
        },
        { q: 'Knip in lettergrepen: *gemeentehuis*', a: 'ge-meen-te-huis', why: 'gemeente + huis. ge- is een eigen lettergreep, n en t uit elkaar: meen-te.' },
        { q: 'Knip in lettergrepen: *goochelaar*', a: 'goo-che-laar', why: 'ch blijft heel en gaat mee: goo-che. Dan gaat de l mee: laar.' },
        {
          q: 'Meervoud van *menu*',
          before: 'Het restaurant heeft twee',
          after: ': een gewoon en een vegetarisch.',
          a: 'menu’s',
          why: 'menu eindigt op u: meervoud met ’s.',
        },
        {
          q: 'Knip in lettergrepen: *herinneren*',
          a: 'her-in-ne-ren',
          why: 'her- is een voorvoegsel en een eigen lettergreep: niet he-rin-ne-ren. Dan in-ne-ren.',
        },
        {
          q: 'Hoeveel lettergrepen heeft *nieuwsgierig*? Typ het getal.',
          a: '3',
          also: ['drie'],
          why: 'nieuws-gie-rig: ieuw is één klank. Drie klinkerklanken.',
        },
        {
          q: 'Schrijf het getal 1 in letters, met nadruk',
          before: 'Ik heb niet twee kinderen, maar',
          after: 'kind.',
          a: 'één',
          why: 'Het getal 1 met nadruk: één, met een accent op beide e’s.',
        },
        { q: 'Knip in lettergrepen: *eeuwigheid*', a: 'eeu-wig-heid', why: 'De w gaat mee naar de volgende lettergreep: eeu-wig. Dan -heid.' },
        {
          q: 'Schrijf het woord dat je hoort: die bel je bij een inbraak',
          say: 'de politie',
          a: 'de politie',
          also: ['politie'],
          why: 'Je hoort tsie aan het eind: schrijf -tie. politie.',
        },
        { q: 'Knip in lettergrepen: *lachten*', a: 'lach-ten', why: 'ch en t: knip ertussen. ch blijft heel.' },
        { q: 'Knip in lettergrepen: *daarom*', a: 'daar-om', why: 'daar + om: eerst tussen de delen. Niet daa-rom.' },
        {
          q: 'Bijvoeglijk naamwoord van *vriend*',
          before: 'Onze nieuwe buurman is erg',
          after: '.',
          a: 'vriendelijk',
          why: 'vriend + -elijk: de d blijft (vrienden). En ‘luhk’ schrijf je -lijk.',
        },
      ],
      done: { title: 'Reeks klaar', text: 'Voorvoegsels, samenstellingen, ch, ng en het trema: je hebt ze allemaal door elkaar gehad.' },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail van je taaldocent aan. Knip met streepjes (zoals bo-men), typ een aantal als getal, en typ de andere woorden helemaal.',
      intro: 'Kijk goed naar de zin om het gat heen. In het grijs staat soms een hint.',
      title: 'Mail van je taaldocent',
      text: 'Beste cursisten,\n\nBedankt voor jullie {ideeën|meervoud van idee|idee, ideeën: de ee blijft, en het trema laat zien dat er een nieuwe lettergreep begint.} van vorige week. Deze week knippen we lange woorden uit echte {brieven|meervoud van brief|Eén brief, twee brieven: in het langere woord hoor je een v.} van de gemeente en de huisarts. Zulke lange woorden lees je makkelijker als je ze eerst in stukjes knipt.\n\nDe gemeente schrijft over je ‘inschrijving’: {in-schrij-ving|met streepjes|in + schrijving: eerst tussen de delen. ij blijft heel, en de v gaat mee.}. In dezelfde brief staat ‘verhuizing’: {ver-hui-zing|met streepjes|ver- is een eigen lettergreep. ui blijft heel, en de z gaat mee.}. En ‘aanvraag’ knip je tussen de delen: {aan-vraag|met streepjes|aan + vraag: twee delen, twee lettergrepen.}.\n\nDe huisarts stuurt een ‘herinnering’: {her-in-ne-ring|met streepjes|her- is een eigen lettergreep, dus niet he-rin. Dan in-ne-ring: de dubbele n gaat uit elkaar.}. Hij wil een ‘onderzoek’ doen: {on-der-zoek|met streepjes|onder + zoek: eerst tussen de delen. Dan on-der: n en d uit elkaar.}. ‘Medicijnen’ knip je als {me-di-cij-nen|met streepjes|Telkens één medeklinker tussen de klinkerklanken: die gaat mee. ij blijft heel.}, en ‘wachtkamer’ als {wacht-ka-mer|met streepjes|wacht + kamer: eerst tussen de delen. ch blijft heel.}. De apotheek is door een ‘verbouwing’ tijdelijk dicht: {ver-bou-wing|met streepjes|ver- is een eigen lettergreep. ou blijft heel, en de w gaat mee.}.\n\nTel ook de klinkerklanken. ‘Schreeuwen’ heeft {twee~2|getal|schreeu-wen: eeuw is één klank. Twee klinkerklanken, dus twee lettergrepen.} lettergrepen. ‘Ruïne’ heeft er {drie~3|getal|ru-ï-ne: het trema begint een nieuwe lettergreep.}.\n\n{Zo’n|zo een, korter|zo’n is zo een: de weggelaten letters worden een apostrof.} lijst is veel werk, dat weet ik. Ben je {geïnteresseerd|ge + interesseren|ge- + een woord dat met i begint: trema op de i, zodat je ge-ïn leest.} in een extra les? Mail me dan {uiterlijk|op z’n laatst|uiterlijk: ‘luhk’ schrijf je -lijk, met ij.} vrijdag. Ik {antwoord|antwoorden, ik-vorm|antwoorden: stam antwoord, met d. Bij ik komt er niets achter.} binnen twee dagen.\n\nMet vriendelijke groet,\nMarleen de Wit',
      why: 'Knippen: voorvoegsels (in-, ver-, her-) en delen van een samenstelling (aan-vraag, on-der-zoek, wacht-ka-mer) eerst. Dan één medeklinker mee (me-di-cij-nen), en klanken als eeuw tellen als één. Uit eerdere lessen: ideeën en geïnteresseerd met een trema, brieven met v, zo’n met een apostrof, uiterlijk met -lijk en antwoord met d.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen uit een briefje aan de buren. Hoofdletters en leestekens tellen mee.',
      title: 'Een briefje aan de buren',
      sentences: [
        'Beste buren, zaterdagavond vieren wij de verjaardag van onze dochter in de tuin.',
        'Met al haar vrienden erbij wordt het misschien een beetje rumoerig.',
        'Na het avondeten zingen we samen met de kinderen uit de straat.',
        '’s Avonds laat gaat iedereen weer naar huis.',
        'U mag altijd bij ons aanbellen als u toch last hebt van het lawaai.',
        'Wij bieden u alvast onze excuses aan voor de overlast.',
      ],
      right:
        'Alles goed. Lange woorden als zaterdagavond, verjaardag, rumoerig en aanbellen heb je stukje voor stukje goed geschreven, en ’s Avonds met de hoofdletter op de A.',
      wrong:
        'Kijk de lange woorden na: knip ze in lettergrepen en schrijf ze stukje voor stukje (za-ter-dag-a-vond, ver-jaar-dag, ru-moe-rig, a-vond-e-ten, aan-bel-len, o-ver-last). Na ’s aan het begin van de zin krijgt het tweede woord de hoofdletter: ’s Avonds. En lawaai schrijf je met aai.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk het huiswerk van je cursusgenoot na',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      signoff: 'Groetjes,\nMarco',
      tokens: [
        { t: 'Hoi' },
        { t: 'Hasan,' },
        { t: 'kun' },
        { t: 'jij' },
        { t: 'mijn' },
        { t: 'huiswerk' },
        { t: 'nakijken' },
        { t: 'voordat' },
        { t: 'ik' },
        { t: 'het' },
        { t: 'inlever?' },
        { t: 'De' },
        { t: 'opdracht' },
        { t: 'was:' },
        { t: 'knip', trap: 'Goed: na een dubbele punt schrijf je met een kleine letter verder.' },
        { t: 'tien' },
        { t: 'lange' },
        { t: 'woorden' },
        { t: 'in' },
        { t: 'lettergrepen.' },
        { t: 'Dit' },
        { t: 'zijn' },
        { t: 'mijn' },
        { t: 'antwoorden:' },
        { t: 've-ran-de-ring,', fix: 'ver-an-de-ring,', why: 'ver- is een voorvoegsel en een eigen lettergreep: ver-an-de-ring.' },
        { t: 'hui-sarts,', fix: 'huis-arts,', why: 'huis + arts: eerst tussen de delen knippen.' },
        { t: 'uit-no-di-ging,' },
        { t: 'li-chaam,', trap: 'Goed: ch is één klank, die blijft heel en gaat mee naar de volgende lettergreep.' },
        { t: 'wan-del-en,', fix: 'wan-de-len,', why: 'Eén medeklinker (l) tussen de twee e’s: die gaat mee. wan-de-len.' },
        { t: 'doch-ter,' },
        { t: 'aar-dap-pe-len,', fix: 'aard-ap-pe-len,', why: 'aard + appelen: eerst tussen de delen. De d blijft bij aard.' },
        { t: 'eeu-wig,', trap: 'Goed: de w gaat mee naar de volgende lettergreep, net als in leeu-wen.' },
        { t: 're-ken-ing', fix: 're-ke-ning', why: 'Telkens één medeklinker tussen de klinkerklanken: die gaat mee. re-ke-ning.' },
        { t: 'en' },
        { t: 'za-ter-dag-a-vond.', trap: 'Goed: zaterdag + avond. De a van avond is een lettergreep op zich.' },
        { t: 'Bij' },
        { t: '‘ideeen’', fix: '‘ideeën’', also: ['ideeën'], why: 'idee + en: trema op de laatste e, want daar begint een nieuwe lettergreep.' },
        { t: 'twijvel', fix: 'twijfel', why: 'twijfelen: je hoort een f, dus twijfel met f.' },
        { t: 'ik' },
        { t: 'nog:' },
        { t: 'zijn' },
        { t: 'dat' },
        { t: 'twee' },
        { t: 'of' },
        { t: 'drie' },
        { t: 'lettergrepen?' },
        { t: 'Volgens' },
        { t: 'mij' },
        { t: 'drie,' },
        { t: 'want' },
        { t: 'ik' },
        { t: 'hoor' },
        { t: 'drie' },
        { t: 'klinkerklanken.' },
        { t: 'Het' },
        { t: 'was' },
        { t: 'best' },
        { t: 'moeilijk,' },
        { t: 'vooral' },
        { t: 'bij' },
        { t: 'de' },
        { t: 'samenstellingen.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'ook' },
        { t: 'geteld:' },
        { t: '‘geïnteresseerd’' },
        { t: 'heeft' },
        { t: 'vijf' },
        { t: 'lettergrepen.' },
        { t: 'Onze' },
        { t: 'docent' },
        { t: 'wil' },
        { t: 'het' },
        { t: 'huiswerk' },
        { t: 'voor' },
        { t: 'Woensdag', fix: 'woensdag', why: 'Dagen van de week schrijf je met een kleine letter.' },
        { t: 'hebben.' },
        { t: 'De' },
        { t: 'rest' },
        { t: 'is' },
        { t: 'volgens' },
        { t: 'mij' },
        { t: 'goed.' },
        { t: 'Alvast' },
        { t: 'bedankt!' },
      ],
      done: {
        title: 'Nagekeken',
        text: 'Vijf knipfouten: ver-an-de-ring, huis-arts, wan-de-len, aard-ap-pe-len en re-ke-ning. En drie fouten uit eerdere lessen: ideeën, twijfel en woensdag.',
      },
    },
  ],
};
