import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": open en gesloten lettergrepen, en wanneer je aa, ee, oo en uu met één of twee letters schrijft. */
export const LES_G21: LessonInput = {
  id: 'g21',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'Open of gesloten: één letter of twee?',
  skill: 'Spelling',
  icon: 'aa·a',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Eén letter of twee?',
      panels: [
        {
          text: 'Elk woord bestaat uit lettergrepen: *ra-men*, *bo-men*, *ta-fel*. Een lettergreep is *open* als hij eindigt op een klinker: *ra*, *bo*, *ta*. Hij is *gesloten* als hij eindigt op een medeklinker: *raam*, *bom*, *men*, *fel*. Twijfel je of je één of twee letters schrijft? Kijk dan altijd naar de lettergreep waarin de klank staat.',
          rule: 'Open lettergreep: eindigt op een klinker. Gesloten lettergreep: eindigt op een medeklinker.',
          split: { word: 'ramen', answer: 'ra-men', note: 'ra eindigt op de klinker a: open. men eindigt op de n: gesloten.' },
          quiz: {
            q: 'Is de eerste lettergreep van ‘zomer’ open of gesloten?',
            options: ['open', 'gesloten'],
            answer: 'open',
            why: 'zo-mer: zo eindigt op de klinker o. De lettergreep is open, en daarom is één o genoeg.',
          },
        },
        {
          text: 'De lange klanken *aa*, *ee*, *oo* en *uu* schrijf je soms met twee letters en soms met één. Dat hangt af van de lettergreep. In een gesloten lettergreep schrijf je twee letters: *raam*, *been*, *boom*, *muur*. In een open lettergreep is één letter genoeg, want daar klinkt de klinker vanzelf lang: *ra-men*, *be-nen*, *bo-men*, *mu-ren*.',
          rule: 'Lange klank in een gesloten lettergreep: twee letters (*raam*). Lange klank in een open lettergreep: één letter (*ra-men*).',
          lab: {
            label: 'Tik een woord en zie het meervoud',
            chips: [
              { k: 'raam', out: 'ra-men', note: 'raam is gesloten (m erachter): aa. In ra-men gaat de m naar de volgende lettergreep, ra is open: één a.' },
              { k: 'been', out: 'be-nen', note: 'been: ee in een gesloten lettergreep. be-nen: be is open, dus één e.' },
              { k: 'boom', out: 'bo-men', note: 'boom: oo. bo-men: bo is open, dus één o.' },
              { k: 'muur', out: 'mu-ren', note: 'muur: uu. mu-ren: mu is open, dus één u.' },
            ],
          },
        },
        {
          text: 'De regel geldt overal waar een woord langer wordt. Bij het meervoud: *maan*, *manen*. Bij werkwoorden: *ik loop*, *wij lopen*; *ik maak*, *wij maken*. Bij een bijvoeglijk naamwoord met *-e*: *groot*, *een grote tas*; *raar*, *een rare vraag*; *duur*, *dure schoenen*. Steeds schuift de medeklinker naar de volgende lettergreep. De lettergreep met de lange klank wordt open, en er valt een letter weg.',
          rule: 'Wordt het woord langer en schuift de medeklinker door? Dan wordt *aa*, *ee*, *oo*, *uu* één letter.',
          paradigm: {
            q: 'Zet de langere vorm in het goede vakje',
            cols: ['langere vorm'],
            rows: [
              { label: 'ik loop → wij …', cells: [{ fill: 'lopen', hint: 'lo-pen: lo is open, dus één o.' }] },
              { label: 'ik maak → wij …', cells: [{ fill: 'maken', hint: 'ma-ken: ma is open, dus één a.' }] },
              { label: 'ik hoor → wij …', cells: [{ fill: 'horen', hint: 'ho-ren: ho is open, dus één o.' }] },
              { label: 'groot → een … tas', cells: [{ fill: 'grote', hint: 'gro-te: gro is open, dus één o.' }] },
              { label: 'raar → een … vraag', cells: [{ fill: 'rare', hint: 'ra-re: ra is open, dus één a.' }] },
              { label: 'duur → … schoenen', cells: [{ fill: 'dure', hint: 'du-re: du is open, dus één u.' }] },
            ],
            extra: ['loopen', 'maaken', 'groote', 'raare'],
            note: 'Zes keer hetzelfde: zodra de medeklinker naar de volgende lettergreep gaat, schrijf je de lange klank met één letter.',
          },
        },
        {
          text: 'Dit geldt alleen voor *aa*, *ee*, *oo* en *uu*. De klanken *ie*, *oe*, *eu*, *ui*, *ei*, *ij*, *au* en *ou* schrijf je met twee letters, in een open én in een gesloten lettergreep: *boek*, *boe-ken*; *deur*, *deu-ren*; *tuin*, *tui-nen*; *lijn*, *lij-nen*; *vrouw*, *vrou-wen*. Daar valt geen letter weg. Alleen in een paar leenwoorden hoor je *ie* en schrijf je één *i*: *kilo*, *liter*, *piloot*.',
          rule: '*ie*, *oe*, *eu*, *ui*, *ei*, *ij*, *au*, *ou* blijven twee letters (behalve de *i* in leenwoorden als *kilo*).',
          mark: {
            q: 'Tik de meervouden waarin de klank met één letter wordt geschreven',
            sentence: 'boeken ramen tuinen bomen deuren muren lijnen benen',
            targets: [1, 3, 5, 7],
            note: 'ramen, bomen, muren en benen: aa, oo, uu en ee worden één letter in een open lettergreep. boeken, tuinen, deuren en lijnen houden oe, ui, eu en ij.',
          },
        },
        {
          text: 'Aan het eind van een woord is de lettergreep ook open. Daar schrijf je *a*, *o*, *u* en *i* met één letter: *pa*, *ja*, *zo*, *nu*, *menu*, *foto*, *taxi*. Maar de lange *ee* krijgt aan het eind wél twee letters: *zee*, *mee*, *twee*, *thee*, *idee*. Zo zie je het verschil met de doffe e van *de*, *me* en *je*. In gewone Nederlandse woorden schrijf je de klank ie aan het eind als *ie*: *die*, *knie*, *drie*. Alleen in leenwoorden als *taxi* en *ski* staat er één *i*.',
          rule: 'Aan het eind van een woord: *a*, *o*, *u*, *i* met één letter (*foto*), maar *ee* met twee (*zee*).',
          quiz: {
            q: 'Welke zin is goed geschreven?',
            options: ['Wil je nog thee?', 'Wil je nog the?', 'Wil je nog tee?'],
            answer: 'Wil je nog thee?',
            why: 'Een lange ee aan het eind van een woord schrijf je met twee letters. En thee schrijf je met th.',
          },
          deep: {
            q: 'En als er een s achter komt, zoals bij foto?',
            a: 'Dan zou de *o* in een gesloten lettergreep komen te staan, en *fotos* lees je met een korte o. Daarom zet je een apostrof: *foto’s*, *menu’s*, *auto’s*. Meer daarover in de les over het meervoud.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'een-of-twee',
      prompt: 'Eén letter of twee? Kies wat er op de puntjes hoort.',
      buckets: ['één letter (a, e, o, u)', 'twee letters (aa, ee, oo, uu)'],
      items: [
        { t: 'wij verl…gen de prijs', b: 0 },
        { t: 'de prijs is verl…gd', b: 1 },
        { t: 'twee j…ren geleden', b: 0 },
        { t: 'een j…rlijks gesprek', b: 1 },
        { t: 'een r…delijke prijs', b: 0 },
        { t: 'de huur wordt d…rder', b: 1 },
        { t: 'de d…re huur', b: 0 },
        { t: 'de gr…tste fout', b: 1 },
        { t: 'n…mens de directie', b: 0 },
        { t: 'de w…rheid', b: 1 },
        { t: 'een v…ste baan', b: 0 },
        { t: 'z…ziek op de boot', b: 1 },
        { t: 'de verg…dering', b: 0 },
        { t: 'een gev…rlijke kruising', b: 1 },
      ],
      why: 'Eén letter: ver-la-gen, ja-ren, re-de-lij-ke, du-re, na-mens, ver-ga-de-ring: de lange klank staat aan het eind van de lettergreep. vaste heeft een korte a: ook één letter. Twee letters: ver-laagd, jaar-lijks, duur-der, groot-ste, waar-heid, ge-vaar-lij-ke: er staat een medeklinker achter in dezelfde lettergreep. En zee-ziek: zee houdt zijn ee, ook in een samenstelling.',
    },
    {
      kind: 'type',
      id: 'bezwaren',
      prompt: 'Typ het meervoud van ‘bezwaar’.',
      before: 'De buren hebben drie',
      after: 'tegen de nieuwe schuur.',
      hint: 'meervoud',
      answer: 'bezwaren',
      why: 'be-zwa-ren: de r gaat naar de laatste lettergreep, en zwa is open. Dus één a.',
    },
    {
      kind: 'choice',
      id: 'verhuurd',
      prompt: 'Welk woord past?',
      before: 'De kamer boven de winkel is sinds januari',
      after: 'aan een student.',
      options: ['verhuurd', 'verhurd', 'verhuurt', 'verhuurdt'],
      answer: 'verhuurd',
      why: 'ver-huurd: de r en de d sluiten de lettergreep, dus uu. En de stam verhuur eindigt op een r, die niet in ’t kofschip zit: het voltooid deelwoord eindigt op d.',
    },
    {
      kind: 'fix',
      id: 'bewoners',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'De nieuwe regels gelden vanaf januari, maar niemand heeft de bewooners op tijd ingelicht.',
      wrong: 10,
      answer: 'bewoners',
      why: 'be-wo-ners: wo is open, dus één o. Net als re-gels: één e.',
    },
    {
      kind: 'type',
      id: 'beloven',
      prompt: 'Typ hetzelfde werkwoord, in dezelfde tijd, voor ‘mijn collega’s’.',
      before: 'Ik beloof het, en mijn collega’s',
      after: 'het ook.',
      hint: '',
      answer: 'beloven',
      why: 'be-lo-ven: lo is open, dus één o. En in het langere woord hoor je een v: ik beloof, wij beloven.',
    },
    {
      kind: 'bet',
      id: 'beoordelen',
      prompt: 'Hoe schrijf je het hele werkwoord bij ‘ik beoordeel’?',
      options: ['beoordelen', 'beoordeelen', 'beordelen', 'beoordellen'],
      answer: 'beoordelen',
      why: 'be-oor-de-len: oor is gesloten (de r erachter), dus oo. de is open, dus één e. En geen dubbele l: de e is lang.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Twijfel je? Zo doe je het',
      panels: [
        {
          text: 'Twijfel je tussen één en twee letters? Gebruik dit stappenplan. Stap 1: hoor je een lange *aa*, *ee*, *oo* of *uu*? Stap 2: knip het woord in lettergrepen. Stap 3: eindigt de lettergreep op die lange klank? Dan schrijf je één letter. Staat er in dezelfde lettergreep nog een medeklinker achter? Dan schrijf je twee letters. Een lang woord kan allebei hebben: *ka-me-raad*.',
          rule: 'Lange klank + einde van de lettergreep: één letter. Lange klank + medeklinker in dezelfde lettergreep: twee letters.',
          split: {
            q: 'Knip het woord in lettergrepen',
            word: 'kameraad',
            answer: 'ka-me-raad',
            note: 'ka is open: één a. raad is gesloten: twee a’s. Eén woord, allebei de regels.',
          },
        },
        {
          text: 'Twee uitzonderingen. De eerste: woorden die op *ee* eindigen, houden de dubbele *ee*, ook als er iets achter komt: *zee*, *zeeën*; *idee*, *ideeën*; *met z’n tweeën*. Het trema laat zien waar de nieuwe lettergreep begint. De tweede: in een samenstelling blijft elk deel zoals het los is: *thee* + *pot* = *theepot*, *zee* + *ziek* = *zeeziek*. Je kijkt dan naar de losse woorden, niet naar de lettergrepen.',
          rule: 'Uitzondering: *ee* aan het eind blijft *ee* (*zeeën*, *theepot*).',
          quiz: {
            q: 'Wat is het meervoud van ‘idee’?',
            options: ['ideeën', 'ideën', 'ideeen'],
            answer: 'ideeën',
            why: 'idee houdt de dubbele ee. Daarna komt -en, met een trema op de e: ideeën.',
          },
        },
        {
          text: 'De meest gemaakte fout is een dubbele letter in een open lettergreep: *loopen*, *maaken*, *groote*, *buuren*. Die bestaan niet. Andersom gaat het ook mis: in een gesloten lettergreep heb je wél twee letters nodig. Dus niet *ik lop* of *het is grot*, maar *ik loop* en *het is groot*. En wil je een korte klank, dan verdubbel je de medeklinker: *ra-men* (lang) tegenover *ram-men* (kort). Dat oefen je in de les over verdubbelen.',
          show: [
            { wrong: 'wij loopen', right: 'wij lopen' },
            { wrong: 'wij maaken', right: 'wij maken' },
            { wrong: 'de groote stad', right: 'de grote stad' },
            { wrong: 'ik lop', right: 'ik loop' },
          ],
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'ramen', out: 'ra-men: lange a', note: 'Open lettergreep: één a, en die klinkt lang. Het meervoud van raam.' },
              { k: 'rammen', out: 'ram-men: korte a', note: 'De dubbele m sluit de eerste lettergreep: de a blijft kort. Hard ergens tegenaan stoten.' },
              { k: 'bomen', out: 'bo-men: lange o', note: 'Het meervoud van boom.' },
              { k: 'bommen', out: 'bom-men: korte o', note: 'Het meervoud van bom.' },
            ],
          },
        },
        {
          text: 'De regel werkt ook midden in woorden die je niet langer maakt: *ka-mer*, *zo-mer*, *ta-fel*, *bo-ter*, *va-der*, *a-vond*, *pa-pier*. Overal waar een lange klank een lettergreep afsluit, staat één letter. Kijk dus niet alleen naar het meervoud: elke lettergreep telt.',
          mark: {
            q: 'Tik de woorden met een lange klank in een open lettergreep',
            sentence: 'Mijn vader leest elke avond de krant.',
            targets: [1, 4],
            note: 'va-der en a-vond: de a staat aan het eind van de lettergreep, dus één letter. In leest staat de ee in een gesloten lettergreep: twee letters.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje-zee',
      prompt: 'Lees het appje aan Sanne. Tik elke fout aan en verbeter hem.',
      intro: 'Alle fouten hebben te maken met één letter of twee.',
      tokens: [
        { t: 'Hoi' },
        { t: 'Sanne!' },
        { t: 'Zaterdag' },
        { t: 'gaan' },
        { t: 'we' },
        { t: 'naar' },
        { t: 'zee.' },
        { t: 'We' },
        { t: 'vertrekken' },
        { t: 'om' },
        { t: 'negen' },
        { t: 'ur.', fix: 'uur.', why: 'uur is gesloten (r erachter): twee letters.' },
        { t: 'Ik' },
        { t: 'maak' },
        { t: 'broodjes' },
        { t: 'en' },
        { t: 'jij' },
        { t: 'neemt' },
        { t: 'de' },
        { t: 'drankjes' },
        { t: 'mee.' },
        { t: 'De' },
        { t: 'kinderen' },
        { t: 'willen' },
        { t: 'in' },
        { t: 'het' },
        { t: 'zand' },
        { t: 'speelen.', fix: 'spelen.', why: 'spe-len: open lettergreep, één e.' },
        { t: 'Neem' },
        { t: 'ook' },
        { t: 'de' },
        { t: 'groote', fix: 'grote', why: 'gro-te: open lettergreep, één o.' },
        { t: 'handdoeken' },
        { t: 'mee.' },
        { t: 'Mijn' },
        { t: 'buuren', fix: 'buren', why: 'bu-ren: open lettergreep, één u.' },
        { t: 'gaan' },
        { t: 'ook' },
        { t: 'mee.' },
        { t: 'We' },
        { t: 'hoopen', fix: 'hopen', why: 'ho-pen: open lettergreep, één o.' },
        { t: 'op' },
        { t: 'mooi' },
        { t: 'weer!' },
      ],
      done: { title: 'Alles gevonden', text: 'Vier keer een dubbele letter in een open lettergreep, en één keer een enkele letter in een gesloten lettergreep.' },
    },
    {
      kind: 'dictation',
      id: 'buren-ramen',
      prompt: 'Luister en typ de zin.',
      sentence: 'Onze buren hebben bij de gemeente bezwaar gemaakt tegen de grote bomen voor hun ramen.',
      right: 'Goed: bu-ren, gro-te, bo-men en ra-men hebben een open lettergreep met één letter. Ge-meen-te, be-zwaar en ge-maakt hebben een gesloten lettergreep met twee letters.',
      wrong: 'Kijk per woord: staat de lange klank aan het eind van de lettergreep (bu-ren, gro-te, bo-men, ra-men)? Dan één letter. Staat er een medeklinker achter in dezelfde lettergreep (ge-meen-te, be-zwaar, ge-maakt)? Dan twee.',
    },
    {
      kind: 'swipe',
      id: 'zinnen',
      prompt: 'Is deze zin goed geschreven?',
      cards: [
        { t: 'De huur wordt volgend jaar weer duurder.', ok: true, why: 'duur-der: duur is gesloten (r erachter), dus uu.' },
        { t: 'De directeur wil de lonen niet verhoogen.', ok: false, fix: 'verhogen', why: 'ver-ho-gen: ho is open, dus één o.' },
        { t: 'Wij hebben de rekening op tijd betaald.', ok: true, why: 'be-taald: taald is gesloten, dus aa.' },
        { t: 'Zij heeft een vaaste baan bij de gemeente.', ok: false, fix: 'vaste', why: 'De a in vast is kort. Een korte klank schrijf je met één letter.' },
        { t: 'Ik heb het formulier gisteren verstuurd.', ok: true, why: 'ver-stuurd: stuurd is gesloten, dus uu.' },
        { t: 'Ik wil de schade graag met u bespreeken.', ok: false, fix: 'bespreken', why: 'be-spre-ken: spre is open, dus één e.' },
        {
          t: 'Mijn dochter speelt graag met de buurkinderen.',
          ok: true,
          why: 'buur + kinderen: in een samenstelling blijft buur gewoon buur. En speelt is gesloten: ee.',
        },
        { t: 'Die ideën zijn niet nieuw.', ok: false, fix: 'ideeën', why: 'idee houdt de dubbele ee, ook in het meervoud: ideeën.' },
        {
          t: 'De tuinen achter de huizen zijn verwaarloosd.',
          ok: true,
          why: 'ver-waar-loosd: waar en loosd zijn gesloten, dus aa en oo. tui-nen: ui blijft altijd twee letters.',
        },
        {
          t: 'We hebben de woonkamer helemaal opnieuw geverfd.',
          ok: true,
          why: 'woon is gesloten (oo). he-le-maal: he en le zijn open (één e), maal is gesloten (aa).',
        },
        { t: 'Hij kwam tien minuuten te laat.', ok: false, fix: 'minuten', why: 'mi-nu-ten: nu is open, dus één u.' },
        { t: 'De kosten worden jaarlijks verhoogd.', ok: true, why: 'jaar-lijks en ver-hoogd: gesloten lettergrepen, dus aa en oo.' },
      ],
    },
    {
      kind: 'rewrite',
      id: 'wij-vorm',
      prompt: 'Schrijf de zin opnieuw, maar nu met ‘wij’ in plaats van ‘ik’.',
      source: 'Ik bewaar de bonnen en ik vraag het geld terug.',
      accept: ['Wij bewaren de bonnen en wij vragen het geld terug.', 'Wij bewaren de bonnen en vragen het geld terug.'],
      why: 'ik bewaar → wij be-wa-ren, ik vraag → wij vra-gen: de lange a staat nu in een open lettergreep, dus één a.',
    },
    {
      kind: 'type',
      id: 'zeeen',
      prompt: 'Typ het meervoud van ‘zee’.',
      before: 'Dit vrachtschip vaart over alle',
      after: 'van de wereld.',
      hint: 'meervoud',
      answer: 'zeeën',
      why: 'zee houdt de dubbele ee, ook als er -en achter komt. Het trema laat zien waar de nieuwe lettergreep begint: zee-ën.',
    },
    {
      kind: 'choice',
      id: 'regels',
      prompt: 'Welk woord past?',
      before: 'De nieuwe',
      after: 'van de huisbaas hangen in de hal.',
      options: ['regels', 'reegels', 'reggels', 'regel’s'],
      answer: 'regels',
      why: 're-gels: re is open, dus één e. Geen dubbele g, want de e is lang. En na een l komt in het meervoud geen apostrof.',
    },
    {
      kind: 'bet',
      id: 'kameraden',
      prompt: 'Wat is het meervoud van ‘kameraad’?',
      options: ['kameraden', 'kameraaden', 'kammeraden', 'kamerraden'],
      answer: 'kameraden',
      why: 'ka-me-ra-den: de lange a’s staan nu allebei in een open lettergreep. Dus overal één a, en geen dubbele m of r.',
    },
    {
      kind: 'write',
      id: 'appje-weekend',
      prompt: 'Schrijf een appje aan een vriend over je weekend.',
      intro: 'Gebruik woorden waarin een lange klank in een open lettergreep staat.',
      minWords: 25,
      must: [
        {
          label: 'Een werkwoord met wij: lopen, kopen, maken, horen of spelen',
          hint: 'wij lopen, wij kopen',
          test: { anyWord: ['lopen', 'kopen', 'maken', 'horen', 'spelen'] },
        },
        { label: 'Een bijvoeglijk naamwoord met -e: grote, rare, dure of lege', hint: 'een grote taart', test: { anyWord: ['grote', 'rare', 'dure', 'lege'] } },
        { label: 'Een meervoud: ramen, bomen, buren of jaren', hint: 'de buren', test: { anyWord: ['ramen', 'bomen', 'buren', 'jaren'] } },
      ],
      avoid: [
        {
          test: { pattern: '\\b(loopen|koopen|maaken|hooren|speelen|groote|raare|duure|leege|raamen|boomen|buuren|jaaren)\\b', flags: 'i' },
          tip: 'Kijk nog eens naar dit woord: staat de lange klank in een open lettergreep? Dan is één letter genoeg.',
        },
      ],
      why: 'In elk van deze woorden staat de lange klank aan het eind van een lettergreep: één letter is genoeg.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro:
        'Bijna dertig opdrachten door elkaar. Typ het hele woord. Moet je knippen? Zet dan een streepje op elke knip, zoals *bo-men*. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Vul de vorm van *verhogen* in',
          before: 'Vorig jaar is de huur ook al',
          after: '.',
          a: 'verhoogd',
          why: 'ver-hoogd: de g en de d sluiten de lettergreep, dus oo. En de stam verhoog eindigt op een g, die niet in ’t kofschip zit: d.',
        },
        { q: 'Meervoud van *taal*', before: 'Hasan spreekt drie', after: 'vloeiend.', a: 'talen', why: 'ta-len: ta is open, dus één a.' },
        { q: 'Meervoud van *uur*', before: 'Ik heb', after: 'in de wachtkamer gezeten.', a: 'uren', why: 'u-ren: u is open, dus één u.' },
        {
          q: 'Vul de vorm van *vergeten* in',
          before: 'Als ik mijn wachtwoord niet opschrijf,',
          after: 'ik het.',
          a: 'vergeet',
          why: 'ik vergeet: geet is gesloten (t erachter), dus ee.',
        },
        {
          q: 'Knip in lettergrepen (met streepjes): *verbeteren*',
          a: 'ver-be-te-ren',
          why: 'ver- is een eigen lettergreep. Dan telkens één medeklinker, die gaat mee: be-te-ren.',
        },
        {
          q: 'Vul de vorm van *bewaren* in',
          before: 'Vanaf nu',
          after: 'hij alle bonnetjes in een map.',
          a: 'bewaart',
          why: 'stam bewaar + t: bewaart. waart is gesloten, dus aa.',
        },
        { q: 'Vul de vorm van *zwaar* in', before: 'Ik moest drie', after: 'dozen naar boven dragen.', a: 'zware', why: 'zwa-re: zwa is open, dus één a.' },
        {
          q: 'Meervoud van *foto*',
          before: 'Stuur je de',
          after: 'van de schade even door?',
          a: 'foto’s',
          why: 'foto eindigt op o: ’s. Zonder apostrof zou je fotos met een korte o lezen.',
        },
        {
          q: 'Vul de vorm van *duur* in',
          before: 'Het nieuwe abonnement is',
          after: 'dan het oude.',
          a: 'duurder',
          why: 'duur-der: duur is gesloten (r erachter), dus uu.',
        },
        {
          q: 'Vul de vorm van *groot* in',
          before: 'Van alle fouten was dit de',
          after: '.',
          a: 'grootste',
          why: 'groot-ste: groot is gesloten (t erachter), dus oo.',
        },
        {
          q: 'Vul de vorm van *vragen* in',
          before: 'Zij belt morgen de huisarts en',
          after: 'dan om een nieuwe afspraak.',
          a: 'vraagt',
          why: 'stam vraag + t: vraagt. Gesloten lettergreep, dus aa. En een werkwoord met g houdt de g.',
        },
        { q: 'Meervoud van *week*', before: 'De verbouwing duurt nog drie', after: '.', a: 'weken', why: 'we-ken: we is open, dus één e.' },
        {
          q: 'Meervoud van *idee*',
          before: 'Heeft iemand nog',
          after: 'voor het afscheid van Ingrid?',
          a: 'ideeën',
          why: 'idee houdt de dubbele ee, ook als er -en achter komt. Het trema staat waar de nieuwe lettergreep begint: ideeën.',
        },
        {
          q: 'Vul de vorm van *lezen* in',
          before: 'Zij',
          after: 'straks de brief van de gemeente hardop voor.',
          a: 'leest',
          why: 'stam lees + t: leest. Aan het eind nooit z, en lees is gesloten, dus ee.',
        },
        { q: 'Vul de wij-vorm in (ik stuur op)', before: 'Morgen', after: 'wij het formulier op.', a: 'sturen', why: 'stu-ren: stu is open, dus één u.' },
        {
          q: 'Meervoud van *café*',
          before: 'In deze straat zijn drie',
          after: 'en een bakker.',
          a: 'cafés',
          why: 'Na é alleen een s, zonder apostrof: cafés.',
        },
        {
          q: 'Vul de vorm van *verhuren* in',
          before: 'De huisbaas',
          after: 'de kamer vanaf volgende maand aan een student.',
          a: 'verhuurt',
          why: 'stam verhuur + t: verhuurt. huurt is gesloten, dus uu.',
        },
        {
          q: 'Maak één woord van *zee* en *ziek*',
          before: 'Op de boot werd ik',
          after: '.',
          a: 'zeeziek',
          why: 'In een samenstelling blijft elk deel zoals het los is: zee + ziek.',
        },
        {
          q: 'Vul de vorm van *geven* in',
          before: 'Hij',
          after: 'zijn sleutel morgen aan de buurvrouw.',
          a: 'geeft',
          why: 'stam geef + t: geeft. Aan het eind f, en geef is gesloten, dus ee.',
        },
        { q: 'Meervoud van *gebaar*', before: 'Hij praat met zijn handen en maakt grote', after: '.', a: 'gebaren', why: 'ge-ba-ren: ba is open, dus één a.' },
        {
          q: 'Knip in lettergrepen (met streepjes): *voorbereiding*',
          a: 'voor-be-rei-ding',
          why: 'voor + bereiding: eerst tussen de delen. be- is een eigen lettergreep, en ei blijft heel.',
        },
        { q: 'Vul de vorm van *raar* in', before: 'Ik kreeg een', after: 'mail van een onbekend adres.', a: 'rare', why: 'ra-re: ra is open, dus één a.' },
        {
          q: 'Bijvoeglijk naamwoord van *dag*',
          before: 'Na het eten maak ik mijn',
          after: 'wandeling.',
          a: 'dagelijkse',
          why: 'da-ge-lijk-se: da is open, dus één a. En ‘luhk’ schrijf je -lijk.',
        },
        {
          q: 'Vul de vorm van *vinden* in',
          before: 'Ik',
          after: 'het een redelijke prijs, dus ik koop de fiets.',
          a: 'vind',
          why: 'vinden: stam vind, met d. Bij ik komt er niets achter.',
        },
        {
          q: 'Vul het hele werkwoord in (ik spreek af)',
          before: 'Zullen we morgen om tien uur',
          after: '?',
          a: 'afspreken',
          why: 'af-spre-ken: spre is open, dus één e.',
        },
        {
          q: 'Schrijf het woord dat je hoort: daar leen je boeken',
          say: 'de bibliotheek',
          a: 'de bibliotheek',
          also: ['bibliotheek'],
          why: 'bi-bli-o-theek: de i klinkt als ie, maar je schrijft één i, net als in taxi en kilo. o is open (één o), theek is gesloten (ee). En th, net als in thee.',
        },
        {
          q: 'Zelfstandig naamwoord van *eerlijk*',
          before: 'Ik waardeer je',
          after: '.',
          a: 'eerlijkheid',
          why: 'eer-lijk-heid: eer is gesloten, dus ee. -lijk met ij, -heid met ei.',
        },
      ],
      done: { title: 'Reeks klaar', text: 'Open of gesloten, steeds opnieuw beslist, en tussendoor d of t, s of z, f of v, ’s en het trema.' },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail aan de huisbaas aan. Typ elk woord helemaal.',
      intro: 'Kijk goed naar de zin om het gat heen. In het grijs staat soms een hint.',
      title: 'Mail aan de huisbaas',
      text: 'Beste meneer Visser,\n\nIk {schrijf|schrijven, ik-vorm|schrijven: stam schrijf. Aan het eind van een woord nooit v, altijd f.} u over een paar {problemen|meervoud van probleem|pro-ble-men: ble is open, dus één e.} in onze woning. Sinds twee {weken|meervoud van week|we-ken: we is open, dus één e.} lekt het dak boven de {slaapkamer|kamer om te slapen|slaap + kamer: slaap is gesloten, dus aa. ka is open, dus één a.}. Bij {regen|r…gen|re-gen: re is open, dus één e.} staat er water op de vloer, en de {muur|enkelvoud van muren|muur: de r sluit de lettergreep, dus uu. In mu-ren is mu open: één u.} wordt groen. Mijn zoontje slaapt daarom nu in de woonkamer.\n\nOok sluiten de {ramen|meervoud van raam|ra-men: ra is open, dus één a.} in de woonkamer niet goed. Het tocht, en onze {stookkosten|stoken + kosten|stook + kosten: stook is gesloten, dus oo.} worden steeds {hoger|vorm van hoog|ho-ger: ho is open, dus één o.}. Dat {vind|vinden, ik-vorm|vinden: stam vind, met d.} ik niet {redelijk|r…delijk|re-de-lijk: re en de zijn open, dus één e. En ‘luhk’ schrijf je -lijk.}.\n\nWij {betalen|wij-vorm van ik betaal|be-ta-len: ta is open, dus één a.} de huur altijd op tijd. Daarom {vragen|wij-vorm van ik vraag|vra-gen: vra is open, dus één a.} wij u om de {schade|sch…de|scha-de: scha is open, dus één a.} snel te laten herstellen. In de bijlage vindt u drie {foto’s|meervoud van foto|Na een o komt ’s: foto’s. Zo blijft de o lang.} van de natte plekken. Ook de buren {horen|ik hoor, zij …|ho-ren: ho is open, dus één o.} het water druppelen.\n\nIk {hoop|ik-vorm van hopen|hoop: de p sluit de lettergreep, dus oo.} dat u snel {reageert|reageren: u + stam + t|re-a-geert: u + stam + t, dus reageer + t. De ee staat in een gesloten lettergreep.}. Ik ben thuis op maandag, woensdag en vrijdag. U kunt mij ook bellen of een bericht sturen.\n\nMet vriendelijke groet,\nHasan Demir',
      why: 'Open lettergreep, één letter: problemen, weken, regen, ramen, hoger, redelijk, betalen, vragen, schade, horen. Gesloten lettergreep, twee letters: slaapkamer, muur, stookkosten, hoop, reageert. Uit eerdere lessen: schrijf met f, vind met d, redelijk met -lijk en foto’s met een apostrof.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen uit een bericht in de buurtapp. Hoofdletters en leestekens tellen mee.',
      title: 'Bericht in de buurtapp',
      sentences: [
        'Beste buren, volgende week zaterdag worden de grote bomen in onze straat gekapt.',
        'De gemeente zegt dat de wortels de leidingen onder de huizen beschadigen.',
        'Wij vinden het jammer dat de bomen na al die jaren moeten verdwijnen.',
        'Daarom maken we samen een plan voor nieuwe planten en een paar lage struiken.',
        'Op dinsdagavond praten we in het buurthuis verder over het plan.',
        'Neem gerust uw ideeën, foto’s en vragen mee.',
      ],
      right: 'Alles goed: gro-te, bo-men, ja-ren, ma-ken, la-ge, pra-ten en be-scha-di-gen met één letter, straat met twee. En ook gekapt, huizen, dinsdagavond, ideeën en foto’s goed.',
      wrong: 'Kijk de lange klanken na. Open lettergreep, één letter: gro-te, bo-men, ja-ren, ma-ken, la-ge, pra-ten, be-scha-di-gen, vra-gen. Gesloten, twee letters: straat. Uit eerdere lessen: gekapt met t (kappen: ’t kofschip), huizen met z, dinsdagavond met een kleine letter, ideeën met een trema en foto’s met een apostrof.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'juf Annelies', subject: 'Sara is ziek' },
      greeting: 'Beste juf Annelies,',
      signoff: 'Met vriendelijke groet,\nHasan Demir',
      tokens: [
        { t: 'Mijn' },
        { t: 'dochter' },
        { t: 'Sara' },
        { t: 'is' },
        { t: 'sinds' },
        { t: 'gisteren' },
        { t: 'ziek.' },
        { t: 'Ze' },
        { t: 'heeft' },
        { t: 'hooge', fix: 'hoge', why: 'ho-ge: ho is open, dus één o.' },
        { t: 'koorts' },
        { t: 'en' },
        { t: 'moet' },
        { t: 'veel' },
        { t: 'slapen.', trap: 'Goed: sla-pen. sla is open, dus één a.' },
        { t: 'De' },
        { t: 'huisarts' },
        { t: 'zegt', trap: 'Goed: zeggen is een werkwoord met g, dus zegt, niet zecht.' },
        { t: 'dat' },
        { t: 'ze' },
        { t: 'minstens' },
        { t: 'drie' },
        { t: 'daagen', fix: 'dagen', why: 'da-gen: da is open, dus één a.' },
        { t: 'thuis' },
        { t: 'moet' },
        { t: 'blijven.' },
        { t: 'Kunt' },
        { t: 'u' },
        { t: 'haar' },
        { t: 'huiswerk' },
        { t: 'voor' },
        { t: 'deze' },
        { t: 'week' },
        { t: 'naar' },
        { t: 'mij' },
        { t: 'stuuren?', fix: 'sturen?', why: 'stu-ren: stu is open, dus één u.' },
        { t: 'Dan' },
        { t: 'maken' },
        { t: 'we' },
        { t: 'het' },
        { t: 'samen' },
        { t: 'aan' },
        { t: 'de' },
        { t: 'keukentafel.', trap: 'Goed: eu blijft altijd twee letters, en ta-fel is open: één a.' },
        { t: 'Ze' },
        { t: 'leest', trap: 'Goed: lezen, ze leest. Aan het eind een s, en lees is gesloten, dus ee.' },
        { t: 'ook' },
        { t: 'graag,' },
        { t: 'dus' },
        { t: 'misschien' },
        { t: 'kan' },
        { t: 'ze' },
        { t: 'een' },
        { t: 'boek' },
        { t: 'uit' },
        { t: 'de' },
        { t: 'klas' },
        { t: 'leenen.', fix: 'lenen.', why: 'le-nen: le is open, dus één e.' },
        { t: 'Twee' },
        { t: 'vriendinnen' },
        { t: 'willen' },
        { t: 'haar' },
        { t: 'morgen' },
        { t: 'een' },
        { t: 'kart', fix: 'kaart', why: 'kaart: de r en de t sluiten de lettergreep, dus aa. Een kart is iets anders.' },
        { t: 'brengen.' },
        { t: 'Wij' },
        { t: 'hoopen', fix: 'hopen', why: 'ho-pen: ho is open, dus één o.' },
        { t: 'dat' },
        { t: 'ze' },
        { t: 'Maandag', fix: 'maandag', why: 'Dagen van de week schrijf je met een kleine letter.' },
        { t: 'weer' },
        { t: 'naar' },
        { t: 'school' },
        { t: 'kan.' },
        { t: 'Haar' },
        { t: 'broer' },
        { t: 'nemt', fix: 'neemt', why: 'hij neemt: neemt is gesloten (m en t erachter), dus ee.' },
        { t: 'dan' },
        { t: 'haar' },
        { t: 'spullen' },
        { t: 'mee.' },
      ],
      done: {
        title: 'Nagekeken',
        text: 'Vijf keer een dubbele letter in een open lettergreep (hoge, dagen, sturen, lenen, hopen), twee keer een enkele letter in een gesloten lettergreep (kaart, neemt), en maandag met een kleine letter.',
      },
    },
  ],
};
