import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": open en gesloten lettergrepen, en wanneer je aa, ee, oo en uu met één of twee letters schrijft. */
export const LES_G21: LessonInput = {
  id: 'g21',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'Open of gesloten: één letter of twee?',
  skill: 'Spelling',
  icon: 'aa·a',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Eén letter of twee?',
      panels: [
        {
          text: 'Elk woord bestaat uit lettergrepen: *ra-men*, *bo-men*, *ta-fel*. Een lettergreep is *open* als hij eindigt op een klinker: *ra*, *bo*, *ta*. Hij is *gesloten* als hij eindigt op een medeklinker: *raam*, *bom*, *men*, *fel*. Twijfel je of je één of twee letters schrijft? Kijk dan altijd naar de lettergreep waarin de klank staat.',
          rule: 'Open lettergreep: eindigt op een klinker. Gesloten lettergreep: eindigt op een medeklinker.',
          split: { word: 'ramen', answer: 'ra-men', note: 'ra eindigt op de klinker a: open. men eindigt op de n: gesloten.' },
          quiz: {
            q: 'Is de eerste lettergreep van ‘zomer’ open of gesloten?',
            options: ['open', 'gesloten'],
            answer: 'open',
            why: 'zo-mer: zo eindigt op de klinker o. De lettergreep is open, en daarom is één o genoeg.',
          },
        },
        {
          text: 'De lange klanken *aa*, *ee*, *oo* en *uu* schrijf je soms met twee letters en soms met één. Dat hangt af van de lettergreep. In een gesloten lettergreep schrijf je twee letters: *raam*, *been*, *boom*, *muur*. In een open lettergreep is één letter genoeg, want daar klinkt de klinker vanzelf lang: *ra-men*, *be-nen*, *bo-men*, *mu-ren*.',
          rule: 'Lange klank in een gesloten lettergreep: twee letters (*raam*). Lange klank in een open lettergreep: één letter (*ra-men*).',
          lab: {
            label: 'Tik een woord en zie het meervoud',
            chips: [
              { k: 'raam', out: 'ra-men', note: 'raam is gesloten (m erachter): aa. In ra-men gaat de m naar de volgende lettergreep, ra is open: één a.' },
              { k: 'been', out: 'be-nen', note: 'been: ee in een gesloten lettergreep. be-nen: be is open, dus één e.' },
              { k: 'boom', out: 'bo-men', note: 'boom: oo. bo-men: bo is open, dus één o.' },
              { k: 'muur', out: 'mu-ren', note: 'muur: uu. mu-ren: mu is open, dus één u.' },
            ],
          },
        },
        {
          text: 'De regel geldt overal waar een woord langer wordt. Bij het meervoud: *maan*, *manen*. Bij werkwoorden: *ik loop*, *wij lopen*; *ik maak*, *wij maken*. Bij een bijvoeglijk naamwoord met *-e*: *groot*, *een grote tas*; *raar*, *een rare vraag*; *duur*, *dure schoenen*. Steeds schuift de medeklinker naar de volgende lettergreep. De lettergreep met de lange klank wordt open, en er valt een letter weg.',
          rule: 'Wordt het woord langer en schuift de medeklinker door? Dan wordt *aa*, *ee*, *oo*, *uu* één letter.',
          paradigm: {
            q: 'Zet de langere vorm in het goede vakje',
            cols: ['langere vorm'],
            rows: [
              { label: 'ik loop → wij …', cells: [{ fill: 'lopen', hint: 'lo-pen: lo is open, dus één o.' }] },
              { label: 'ik maak → wij …', cells: [{ fill: 'maken', hint: 'ma-ken: ma is open, dus één a.' }] },
              { label: 'ik hoor → wij …', cells: [{ fill: 'horen', hint: 'ho-ren: ho is open, dus één o.' }] },
              { label: 'groot → een … tas', cells: [{ fill: 'grote', hint: 'gro-te: gro is open, dus één o.' }] },
              { label: 'raar → een … vraag', cells: [{ fill: 'rare', hint: 'ra-re: ra is open, dus één a.' }] },
              { label: 'duur → … schoenen', cells: [{ fill: 'dure', hint: 'du-re: du is open, dus één u.' }] },
            ],
            extra: ['loopen', 'maaken', 'groote', 'raare'],
            note: 'Zes keer hetzelfde: zodra de medeklinker naar de volgende lettergreep gaat, schrijf je de lange klank met één letter.',
          },
        },
        {
          text: 'Dit geldt alleen voor *aa*, *ee*, *oo* en *uu*. De klanken *ie*, *oe*, *eu*, *ui*, *ei*, *ij*, *au* en *ou* schrijf je altijd met twee letters, in een open én in een gesloten lettergreep: *boek*, *boe-ken*; *deur*, *deu-ren*; *tuin*, *tui-nen*; *lijn*, *lij-nen*; *vrouw*, *vrou-wen*. Daar valt nooit een letter weg.',
          rule: '*ie*, *oe*, *eu*, *ui*, *ei*, *ij*, *au*, *ou* blijven altijd twee letters.',
          mark: {
            q: 'Tik de meervouden waarin de klank met één letter wordt geschreven',
            sentence: 'boeken ramen tuinen bomen deuren muren lijnen benen',
            targets: [1, 3, 5, 7],
            note: 'ramen, bomen, muren en benen: aa, oo, uu en ee worden één letter in een open lettergreep. boeken, tuinen, deuren en lijnen houden oe, ui, eu en ij.',
          },
        },
        {
          text: 'Aan het eind van een woord is de lettergreep ook open. Daar schrijf je *a*, *o*, *u* en *i* met één letter: *pa*, *ja*, *zo*, *nu*, *menu*, *foto*, *taxi*. Maar de lange *ee* krijgt aan het eind wél twee letters: *zee*, *mee*, *twee*, *thee*, *idee*. Zo zie je het verschil met de doffe e van *de*, *me* en *je*. In gewone Nederlandse woorden schrijf je de klank ie aan het eind als *ie*: *die*, *knie*, *drie*. Alleen in leenwoorden als *taxi* en *ski* staat er één *i*.',
          rule: 'Aan het eind van een woord: *a*, *o*, *u*, *i* met één letter (*foto*), maar *ee* met twee (*zee*).',
          quiz: {
            q: 'Welke zin is goed geschreven?',
            options: ['Wil je nog thee?', 'Wil je nog the?', 'Wil je nog tee?'],
            answer: 'Wil je nog thee?',
            why: 'Een lange ee aan het eind van een woord schrijf je met twee letters. En thee schrijf je met th.',
          },
          deep: {
            q: 'En als er een s achter komt, zoals bij foto?',
            a: 'Dan zou de *o* in een gesloten lettergreep komen te staan, en *fotos* lees je met een korte o. Daarom zet je een apostrof: *foto’s*, *menu’s*, *auto’s*. Meer daarover in de les over het meervoud.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'een-of-twee',
      prompt: 'Eén letter of twee? Kies wat er op de puntjes hoort.',
      buckets: ['één letter (a, e, o, u)', 'twee letters (aa, ee, oo, uu)'],
      items: [
        { t: 'wij l…pen', b: 0 },
        { t: 'ik l…p', b: 1 },
        { t: 'de b…men in het park', b: 0 },
        { t: 'een hoge b…m', b: 1 },
        { t: 'wij m…ken', b: 0 },
        { t: 'ik m…k', b: 1 },
        { t: 'een gr…te auto', b: 0 },
        { t: 'de auto is gr…t', b: 1 },
        { t: 'in de z…mer', b: 0 },
        { t: 'naar z… (strand en water)', b: 1 },
        { t: 'n… of nooit', b: 0 },
        { t: 'r…re vragen', b: 0 },
      ],
      why: 'Open lettergreep, één letter: lo-pen, bo-men, ma-ken, gro-te, zo-mer, ra-re, en nu aan het eind van het woord. Gesloten lettergreep, twee letters: loop, boom, maak, groot. En zee: ee aan het eind van een woord krijgt altijd twee letters.',
    },
    {
      kind: 'type',
      id: 'oren',
      prompt: 'Typ het meervoud.',
      before: 'Eén oor, twee',
      after: '.',
      hint: 'meervoud van oor',
      answer: 'oren',
      why: 'o-ren: de r gaat naar de tweede lettergreep, o is open. Eén o is genoeg.',
    },
    {
      kind: 'choice',
      id: 'rare',
      prompt: 'Welk woord past?',
      before: 'Dat was een',
      after: 'vraag van de docent.',
      options: ['rare', 'raare', 'rarre'],
      answer: 'rare',
      why: 'ra-re: ra is open, dus één a. Met rr zou je de a kort uitspreken.',
    },
    {
      kind: 'fix',
      id: 'spelen',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'De kinderen speelen na school altijd buiten.',
      wrong: 2,
      answer: 'spelen',
      why: 'spe-len: spe is open, dus één e. Ik speel (gesloten: ee), wij spelen (open: e).',
    },
    {
      kind: 'type',
      id: 'kopen',
      prompt: 'Typ de goede vorm van het werkwoord.',
      before: 'Ik koop brood, en wij',
      after: 'samen kaas.',
      hint: 'wij …',
      answer: 'kopen',
      why: 'ko-pen: de p gaat naar de tweede lettergreep, ko is open. Dus één o: kopen, niet koopen.',
    },
    {
      kind: 'bet',
      id: 'sturen',
      prompt: 'Hoe schrijf je het hele werkwoord bij ‘ik stuur’?',
      options: ['sturen', 'stuuren', 'sturren'],
      answer: 'sturen',
      why: 'stu-ren: stu is open, dus één u. Sturren zou je met een korte u lezen, en stuuren bestaat niet.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Twijfel je? Zo doe je het',
      panels: [
        {
          text: 'Twijfel je tussen één en twee letters? Gebruik dit stappenplan. Stap 1: hoor je een lange *aa*, *ee*, *oo* of *uu*? Stap 2: knip het woord in lettergrepen. Stap 3: eindigt de lettergreep op die lange klank? Dan schrijf je één letter. Staat er in dezelfde lettergreep nog een medeklinker achter? Dan schrijf je twee letters. Een lang woord kan allebei hebben: *ka-me-raad*.',
          rule: 'Lange klank + einde van de lettergreep: één letter. Lange klank + medeklinker in dezelfde lettergreep: twee letters.',
          split: {
            q: 'Knip het woord in lettergrepen',
            word: 'kameraad',
            answer: 'ka-me-raad',
            note: 'ka is open: één a. raad is gesloten: twee a’s. Eén woord, allebei de regels.',
          },
        },
        {
          text: 'Twee uitzonderingen. De eerste: woorden die op *ee* eindigen, houden de dubbele *ee*, ook als er iets achter komt: *zee*, *zeeën*; *idee*, *ideeën*; *met z’n tweeën*. Het trema laat zien waar de nieuwe lettergreep begint. De tweede: in een samenstelling blijft elk deel zoals het los is: *thee* + *pot* = *theepot*, *zee* + *ziek* = *zeeziek*. Je kijkt dan naar de losse woorden, niet naar de lettergrepen.',
          rule: 'Uitzondering: *ee* aan het eind blijft *ee* (*zeeën*, *theepot*).',
          quiz: {
            q: 'Wat is het meervoud van ‘idee’?',
            options: ['ideeën', 'ideën', 'ideeen'],
            answer: 'ideeën',
            why: 'idee houdt de dubbele ee. Daarna komt -en, met een trema op de e: ideeën.',
          },
        },
        {
          text: 'De meest gemaakte fout is een dubbele letter in een open lettergreep: *loopen*, *maaken*, *groote*, *buuren*. Die bestaan niet. Andersom gaat het ook mis: in een gesloten lettergreep heb je wél twee letters nodig. Dus niet *ik lop* of *het is grot*, maar *ik loop* en *het is groot*. En wil je een korte klank, dan verdubbel je de medeklinker: *ra-men* (lang) tegenover *ram-men* (kort). Dat oefen je in de les over verdubbelen.',
          show: [
            { wrong: 'wij loopen', right: 'wij lopen' },
            { wrong: 'wij maaken', right: 'wij maken' },
            { wrong: 'de groote stad', right: 'de grote stad' },
            { wrong: 'ik lop', right: 'ik loop' },
          ],
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'ramen', out: 'ra-men: lange a', note: 'Open lettergreep: één a, en die klinkt lang. Het meervoud van raam.' },
              { k: 'rammen', out: 'ram-men: korte a', note: 'De dubbele m sluit de eerste lettergreep: de a blijft kort. Hard ergens tegenaan stoten.' },
              { k: 'bomen', out: 'bo-men: lange o', note: 'Het meervoud van boom.' },
              { k: 'bommen', out: 'bom-men: korte o', note: 'Het meervoud van bom.' },
            ],
          },
        },
        {
          text: 'De regel werkt ook midden in woorden die je niet langer maakt: *ka-mer*, *zo-mer*, *ta-fel*, *bo-ter*, *va-der*, *a-vond*, *pa-pier*. Overal waar een lange klank een lettergreep afsluit, staat één letter. Kijk dus niet alleen naar het meervoud: elke lettergreep telt.',
          mark: {
            q: 'Tik de woorden met een lange klank in een open lettergreep',
            sentence: 'Mijn vader leest elke avond de krant.',
            targets: [1, 4],
            note: 'va-der en a-vond: de a staat aan het eind van de lettergreep, dus één letter. In leest staat de ee in een gesloten lettergreep: twee letters.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje-zee',
      prompt: 'Lees het appje aan Sanne. Tik elke fout aan en verbeter hem.',
      intro: 'Er staan vijf fouten in, allemaal met één of twee letters.',
      tokens: [
        { t: 'Hoi' },
        { t: 'Sanne!' },
        { t: 'Zaterdag' },
        { t: 'gaan' },
        { t: 'we' },
        { t: 'naar' },
        { t: 'zee.' },
        { t: 'We' },
        { t: 'vertrekken' },
        { t: 'om' },
        { t: 'negen' },
        { t: 'ur.', fix: 'uur.', why: 'uur is gesloten (r erachter): twee letters.' },
        { t: 'Ik' },
        { t: 'maak' },
        { t: 'broodjes' },
        { t: 'en' },
        { t: 'jij' },
        { t: 'neemt' },
        { t: 'de' },
        { t: 'drankjes' },
        { t: 'mee.' },
        { t: 'De' },
        { t: 'kinderen' },
        { t: 'willen' },
        { t: 'in' },
        { t: 'het' },
        { t: 'zand' },
        { t: 'speelen.', fix: 'spelen.', why: 'spe-len: open lettergreep, één e.' },
        { t: 'Neem' },
        { t: 'ook' },
        { t: 'de' },
        { t: 'groote', fix: 'grote', why: 'gro-te: open lettergreep, één o.' },
        { t: 'handdoeken' },
        { t: 'mee.' },
        { t: 'Mijn' },
        { t: 'buuren', fix: 'buren', why: 'bu-ren: open lettergreep, één u.' },
        { t: 'gaan' },
        { t: 'ook' },
        { t: 'mee.' },
        { t: 'We' },
        { t: 'hoopen', fix: 'hopen', why: 'ho-pen: open lettergreep, één o.' },
        { t: 'op' },
        { t: 'mooi' },
        { t: 'weer!' },
      ],
      done: { title: 'Alles gevonden', text: 'Vier keer een dubbele letter in een open lettergreep, en één keer een enkele letter in een gesloten lettergreep.' },
    },
    {
      kind: 'dictation',
      id: 'buren-ramen',
      prompt: 'Luister en typ de zin.',
      sentence: 'De buren kopen twee grote ramen voor hun kamer.',
      right: 'Goed: bu-ren, ko-pen, gro-te, ra-men en ka-mer hebben allemaal een open lettergreep met één letter. Twee eindigt op ee: twee letters.',
      wrong: 'Let op: buren, kopen, grote, ramen en kamer schrijf je met één letter, want de lange klank staat in een open lettergreep. Twee schrijf je met ee.',
    },
    {
      kind: 'swipe',
      id: 'zinnen',
      prompt: 'Is deze zin goed geschreven?',
      cards: [
        { t: 'Wij lopen elke dag naar het station.', ok: true, why: 'lo-pen: open lettergreep, één o.' },
        { t: 'De meeste mensen maaken dezelfde fout.', ok: false, fix: 'maken', why: 'ma-ken: open lettergreep, één a.' },
        { t: 'Die schoenen zijn veel te duur.', ok: true, why: 'duur is gesloten: twee letters.' },
        { t: 'Ik heb twee nieuwe ideeën.', ok: true, why: 'idee houdt de dubbele ee, en krijgt een trema: ideeën.' },
        { t: 'Het was een groote verrassing.', ok: false, fix: 'grote', why: 'gro-te: open lettergreep, één o.' },
        { t: 'In de zommer gaan we op vakantie.', ok: false, fix: 'zomer', why: 'zo-mer: de o is lang en staat in een open lettergreep. Geen dubbele m.' },
        { t: 'Ik stuur je morgen de fotos.', ok: false, fix: 'foto’s', why: 'Zonder apostrof lees je een korte o. Met de apostrof blijft de o lang: foto’s.' },
        { t: 'Mijn oom woont vlak bij de zee.', ok: true, why: 'oom en woont zijn gesloten: twee letters. zee eindigt op ee: twee letters.' },
      ],
    },
    {
      kind: 'rewrite',
      id: 'wij-vorm',
      prompt: 'Schrijf de zin opnieuw, maar nu met ‘wij’ in plaats van ‘ik’.',
      source: 'Ik hoor de bel en ik loop naar de deur.',
      accept: ['Wij horen de bel en wij lopen naar de deur.', 'Wij horen de bel en lopen naar de deur.'],
      why: 'ik hoor → wij ho-ren, ik loop → wij lo-pen: de lange o staat nu in een open lettergreep, dus één o.',
    },
    {
      kind: 'type',
      id: 'jaren',
      prompt: 'Typ het goede woord.',
      before: 'Ik woon hier al vijf',
      after: '.',
      hint: 'meervoud van jaar',
      answer: 'jaren',
      why: 'ja-ren: ja is open, dus één a.',
    },
    {
      kind: 'choice',
      id: 'ramen-dicht',
      prompt: 'Welk woord past?',
      before: 'Kun jij de',
      after: 'even dichtdoen? Het tocht.',
      options: ['ramen', 'raamen', 'rammen'],
      answer: 'ramen',
      why: 'ra-men: lange a in een open lettergreep, dus één a. Rammen is een ander woord, met een korte a.',
    },
    {
      kind: 'bet',
      id: 'kameraden',
      prompt: 'Wat is het meervoud van ‘kameraad’?',
      options: ['kameraden', 'kameraaden', 'kammeraden'],
      answer: 'kameraden',
      why: 'ka-me-ra-den: nu staan beide lange a’s in een open lettergreep. Dus overal één a, en geen dubbele m.',
    },
    {
      kind: 'write',
      id: 'appje-weekend',
      prompt: 'Schrijf een appje aan een vriend over je weekend.',
      intro: 'Gebruik woorden waarin een lange klank in een open lettergreep staat.',
      minWords: 25,
      must: [
        { label: 'Een werkwoord met wij: lopen, kopen, maken, horen of spelen', hint: 'wij lopen, wij kopen', test: { anyWord: ['lopen', 'kopen', 'maken', 'horen', 'spelen'] } },
        { label: 'Een bijvoeglijk naamwoord met -e: grote, rare, dure of lege', hint: 'een grote taart', test: { anyWord: ['grote', 'rare', 'dure', 'lege'] } },
        { label: 'Een meervoud: ramen, bomen, buren of jaren', hint: 'de buren', test: { anyWord: ['ramen', 'bomen', 'buren', 'jaren'] } },
      ],
      avoid: [
        {
          test: { pattern: '\\b(loopen|koopen|maaken|hooren|speelen|groote|raare|duure|leege|raamen|boomen|buuren|jaaren)\\b', flags: 'i' },
          tip: 'Kijk nog eens naar dit woord: staat de lange klank in een open lettergreep? Dan is één letter genoeg.',
        },
      ],
      why: 'In elk van deze woorden staat de lange klank aan het eind van een lettergreep: één letter is genoeg.',
    },
  ],
};
