import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": wanneer je een medeklinker verdubbelt (ballen, witte, prettig) en wanneer niet. */
export const LES_G22: LessonInput = {
  id: 'g22',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'Medeklinker verdubbelen',
  skill: 'Spelling',
  icon: 'll',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Korte klank? Dubbele medeklinker',
      panels: [
        {
          text: 'De korte klanken zijn *a*, *e*, *i*, *o* en *u*, zoals in *bal*, *pen*, *vis*, *bom* en *bus*. Komt er na zo’n korte klank één medeklinker, en daarna een klinker, dan schrijf je die medeklinker dubbel: *bal*, *bal-len*; *kat*, *kat-ten*; *pen*, *pen-nen*; *bus*, *bus-sen*. De eerste letter sluit de lettergreep, zodat de klank kort blijft. De tweede begint de volgende lettergreep.',
          rule: 'Korte klank + één medeklinker + er komt een klinker achter: verdubbel de medeklinker.',
          split: { word: 'bakker', answer: 'bak-ker', note: 'bak is gesloten door de eerste k: de a blijft kort. De tweede k begint ker.' },
          lab: {
            label: 'Tik een woord en zie het meervoud',
            chips: [
              { k: 'bal', out: 'ballen', note: 'Korte a + l, en er komt -en achter: ll.' },
              { k: 'kat', out: 'katten', note: 'Korte a + t: tt.' },
              { k: 'pen', out: 'pennen', note: 'Korte e + n: nn.' },
              { k: 'bus', out: 'bussen', note: 'Korte u + s: ss.' },
            ],
          },
        },
        {
          text: 'Waarom is dat nodig? Zonder dubbele letter wordt de lettergreep open, en dan lees je een lange klank. Vergelijk *bo-men* (van *boom*) met *bom-men* (van *bom*), *ma-nen* (van *maan*) met *man-nen* (van *man*), en *ko-pen* met *kop-pen*. Eén letter verschil, een heel ander woord.',
          rule: 'Eén medeklinker: lange klank (*bo-men*). Twee medeklinkers: korte klank (*bom-men*).',
          lab: {
            label: 'Tik een paar',
            chips: [
              { k: 'bomen · bommen', out: 'bo-men · bom-men', note: 'Lange o (boom) tegenover korte o (bom).' },
              { k: 'manen · mannen', out: 'ma-nen · man-nen', note: 'Lange a (maan) tegenover korte a (man).' },
              { k: 'kopen · koppen', out: 'ko-pen · kop-pen', note: 'Lange o (ik koop) tegenover korte o (de kop).' },
              { k: 'stelen · stellen', out: 'ste-len · stel-len', note: 'Lange e (ik steel) tegenover korte e (ik stel).' },
            ],
          },
          quiz: {
            q: 'Je bedoelt het meervoud van ‘bom’. Wat schrijf je?',
            options: ['bommen', 'bomen'],
            answer: 'bommen',
            why: 'bom heeft een korte o. Die blijft kort als je de m verdubbelt: bom-men. Bomen zijn de bomen in het park.',
          },
        },
        {
          text: 'Het geldt niet alleen voor het meervoud. Ook bij werkwoorden: *ik bel*, *wij bellen*; *ik zet*, *wij zetten*; *ik stop*, *wij stoppen*. Bij bijvoeglijke naamwoorden met *-e*: *wit*, *een witte muur*; *dik*, *een dikke trui*; *snel*, *een snelle auto*; *fris*, *frisse lucht*. En bij woorden met *-ig* of *-er*: *geluk*, *gelukkig*; *pret*, *prettig*; *bak*, *bakker*.',
          paradigm: {
            q: 'Zet de langere vorm in het goede vakje',
            cols: ['langere vorm'],
            rows: [
              { label: 'ik bel → wij …', cells: [{ fill: 'bellen', hint: 'Korte e + l: ll.' }] },
              { label: 'ik zet → wij …', cells: [{ fill: 'zetten', hint: 'Korte e + t: tt.' }] },
              { label: 'wit → een … muur', cells: [{ fill: 'witte', hint: 'Korte i + t: tt.' }] },
              { label: 'snel → een … auto', cells: [{ fill: 'snelle', hint: 'Korte e + l: ll.' }] },
              { label: 'geluk → …', cells: [{ fill: 'gelukkig', hint: 'Korte u + k, en -ig erachter: kk.' }] },
              { label: 'pret → …', cells: [{ fill: 'prettig', hint: 'Korte e + t, en -ig erachter: tt.' }] },
            ],
            extra: ['belen', 'zeten', 'wite', 'snele', 'gelukig', 'pretig'],
            note: 'Meervoud, werkwoord, -e, -ig of -er: zodra er een klinker achter komt, verdubbel je na een korte klank.',
          },
        },
        {
          text: 'Aan het eind van een woord verdubbel je niet (op een paar leenwoorden na, zoals *stress* en *jazz*). Daar is de lettergreep al gesloten, en blijft de klank vanzelf kort: *de bal*, *ik zet*, *ik bel*, *het is wit*. Pas als er een klinker achter komt, heb je de tweede letter nodig.',
          rule: 'Aan het eind van een woord: geen dubbele medeklinker (*ik zet*, niet *ik zett*).',
          show: [
            { wrong: 'ik zett', right: 'ik zet' },
            { wrong: 'ik bell je', right: 'ik bel je' },
            { wrong: 'het is witt', right: 'het is wit' },
          ],
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Ik zet koffie.', 'Ik zett koffie.'],
            answer: 'Ik zet koffie.',
            why: 'Na zet komt geen klinker meer. De lettergreep is al gesloten: één t is genoeg.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'wel-of-niet',
      prompt: 'Verdubbel je de medeklinker in de langere vorm?',
      buckets: ['ja, dubbel', 'nee, niet dubbel'],
      items: [
        { t: 'laf → een … smoes', b: 0 },
        { t: 'lief → een … vrouw', b: 1 },
        { t: 'los → … schroeven', b: 0 },
        { t: 'boos → een … klant', b: 1 },
        { t: 'kapot → een … fiets', b: 0 },
        { t: 'zon → … weer (met -ig)', b: 0 },
        { t: 'mist → … weer (met -ig)', b: 1 },
        { t: 'gezellig → een … avond', b: 1 },
        { t: 'sigaret → een pakje …', b: 0 },
        { t: 'lerares → twee …', b: 0 },
        { t: 'ik wandel → wij …', b: 1 },
        { t: 'kennis → drie …', b: 0 },
        { t: 'ik stop → gisteren … hij', b: 1 },
        { t: 'dun → nog … dan papier', b: 0 },
        { t: 'ik zing → wij …', b: 1 },
      ],
      why: 'Dubbel: laffe, losse, kapotte, zonnig, sigaretten, leraressen, kennissen, dunner: korte klank, één medeklinker, en er komt een klinker achter. Niet dubbel: lieve en boze (lange klank), mistig (al twee medeklinkers), gezellige (na -ig nooit), wandelen (doffe e), stopte (na de p komt een t, geen klinker), zingen (ng).',
    },
    {
      kind: 'type',
      id: 'stoffig',
      prompt: 'Typ het bijvoeglijk naamwoord van ‘het stof’.',
      before: 'Na de verbouwing was alles in huis erg',
      after: '.',
      hint: '',
      answer: 'stoffig',
      why: 'stof + -ig: korte o en één f, en er komt een klinker achter. Dus ff: stof-fig.',
    },
    {
      kind: 'choice',
      id: 'prettige',
      prompt: 'Welk woord past?',
      before: 'Ik wens je een',
      after: 'avond!',
      options: ['prettige', 'pretige', 'prettigge', 'pretigge'],
      answer: 'prettige',
      why: 'pret + -ig: korte e, dus tt. De g van -ig verdubbel je niet: de i in -ig klinkt dof.',
    },
    {
      kind: 'fix',
      id: 'berekenen',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'De conciërge heeft de kapotte ramen gemeld en gaat de kosten nu berekkenen.',
      wrong: 12,
      answer: 'berekenen',
      why: 'be-re-ke-nen: de e voor de k is lang (ik reken), dus één k. De e na de k is een doffe e, dus ook geen nn. kapotte is wel goed: korte o + t, met een e erachter.',
    },
    {
      kind: 'type',
      id: 'stopte',
      prompt: 'Typ de verleden tijd van ‘stoppen’.',
      before: 'Gisteren',
      after: 'de bus niet bij onze halte.',
      hint: '',
      answer: 'stopte',
      why: 'stop + te: stopte. Na de p komt een medeklinker (t), dus geen dubbele p. Stoppen heeft pp, stopte niet.',
    },
    {
      kind: 'bet',
      id: 'zangeressen',
      prompt: 'Wat is het meervoud van ‘zangeres’?',
      options: ['zangeressen', 'zangeresen', 'zangerressen', 'zangerresen'],
      answer: 'zangeressen',
      why: 'zangeres heeft de klemtoon op -res: korte e + s, dus ss: zan-ge-res-sen. Maar na de doffe e van zan-ge verdubbel je niet: geen rr.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Wanneer níet verdubbelen',
      panels: [
        {
          text: 'Je verdubbelt alleen na een korte klank met maar één medeklinker. Dus níet na een lange klank: *raam*, *ra-men*; *boot*, *bo-ten*; *ik loop*, *wij lo-pen*. En níet als er al twee medeklinkers staan: *kast*, *kas-ten*; *kant*, *kan-ten*; *hard*, *har-de*; *wolk*, *wol-ken*. Die lettergreep is al gesloten. Ook *ch* en *ng* verdubbel je nooit: *lachen*, *zingen*, *jongen*, *ringen*.',
          rule: 'Niet verdubbelen: na een lange klank, na twee medeklinkers, en bij *ch* en *ng*.',
          mark: {
            q: 'Tik de woorden met een dubbele medeklinker die er níet hoort',
            sentence: 'kassten lachen zingen botten harrde katten jonggen',
            targets: [0, 4, 6],
            note: 'kasten en harde hebben al twee medeklinkers. jongen: ng verdubbel je nooit. botten is goed (het meervoud van bot), net als katten.',
          },
        },
        {
          text: 'Ook na de doffe e verdubbel je niet. De doffe e is de zwakke klank in *-el*, *-em*, *-en* en *-er*: *ik teken*, *wij tekenen*; *ik wandel*, *wij wandelen*; *ik reken*, *wij rekenen*; *ik open*, *wij openen*. Die e klinkt niet als de korte e van *pen*, dus er komt geen tweede letter.',
          rule: 'Na de doffe e: niet verdubbelen (*tekenen*, *wandelen*).',
          build: {
            before: 'Wij gaan vanmiddag samen',
            stem: 'teke',
            endings: ['nen', 'nnen'],
            answer: 'nen',
            note: 'tekenen: de laatste e van teken is een doffe e. Daarna verdubbel je niet.',
          },
        },
        {
          text: 'Woorden op *-nis* verdubbelen tóch, ook zonder klemtoon op die klank: *kennis*, *kennissen*; *getuigenis*, *getuigenissen*. Woorden op *-es* en *-in* hebben de klemtoon juist op het eind, dus die volgen gewoon de regel: *lerares*, *leraressen*; *vriendin*, *vriendinnen*; *koningin*, *koninginnen*. Er zijn ook woorden zonder klemtoon op het eind die je moet leren: *monnik* wordt *monniken*, *perzik* wordt *perziken*. Bij twijfel kijk je in de woordenlijst.',
          rule: '*-nis*, *-es*, *-in*: wel verdubbelen (*vriendinnen*). *monniken* en *perziken*: uitzonderingen.',
          quiz: {
            q: 'Wat is het meervoud van ‘vriendin’?',
            options: ['vriendinnen', 'vriendinen'],
            answer: 'vriendinnen',
            why: 'Woorden op -in verdubbelen de n: vriendin-nen, net als koninginnen.',
          },
        },
        {
          text: 'Twijfel je? Stel drie vragen. Vraag 1: is de klank kort (*a*, *e*, *i*, *o*, *u*)? Vraag 2: staat er maar één medeklinker achter? Vraag 3: komt er een klinker achter, zoals *-en*, *-e*, *-er* of *-ig*? Drie keer ja: verdubbelen. Eén keer nee: niet verdubbelen. Let op: bij *s* en *f* wordt het gewoon *ss* en *ff*: *les*, *lessen*; *straf*, *straffen*.',
          rule: 'Kort? Eén medeklinker? Klinker erachter? Drie keer ja: verdubbelen.',
          lab: {
            label: 'Tik een woord en stel de drie vragen',
            chips: [
              { k: 'bel → bellen', out: 'ja · ja · ja', note: 'Korte e, één l, -en erachter: verdubbelen.' },
              { k: 'boot → boten', out: 'nee', note: 'De oo is lang: niet verdubbelen.' },
              { k: 'kast → kasten', out: 'ja · nee', note: 'Korte a, maar al twee medeklinkers (st): niet verdubbelen.' },
              { k: 'ik zet', out: 'ja · ja · nee', note: 'Er komt niets achter: één t.' },
              { k: 'les → lessen', out: 'ja · ja · ja', note: 'Bij de s wordt het gewoon ss.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-collega',
      prompt: 'Lees de mail aan een collega. Tik elke fout aan en verbeter hem.',
      intro: 'Let op: dubbel waar het moet, en enkel waar het moet.',
      header: { to: 'Mark', subject: 'Vergadering morgen' },
      greeting: 'Hoi Mark,',
      tokens: [
        { t: 'Morgen' },
        { t: 'hebben' },
        { t: 'we' },
        { t: 'om' },
        { t: 'tien' },
        { t: 'uur' },
        { t: 'een' },
        { t: 'vergadering.' },
        { t: 'Wil' },
        { t: 'jij' },
        { t: 'de' },
        { t: 'kopjes' },
        { t: 'en' },
        { t: 'de' },
        { t: 'pennen' },
        { t: 'klaarzeten?', fix: 'klaarzetten?', why: 'ik zet, wij zetten: korte e + t, dus tt.' },
        { t: 'Ik' },
        { t: 'bell', fix: 'bel', why: 'Aan het eind van een woord verdubbel je niet: ik bel.' },
        { t: 'de' },
        { t: 'klant' },
        { t: 'om' },
        { t: 'negen' },
        { t: 'uur.' },
        { t: 'Hij' },
        { t: 'was' },
        { t: 'erg' },
        { t: 'gelukig', fix: 'gelukkig', why: 'geluk + -ig: korte u + k, dus kk.' },
        { t: 'met' },
        { t: 'onze' },
        { t: 'snele', fix: 'snelle', why: 'snel + -e: korte e + l, dus ll.' },
        { t: 'reactie.' },
        { t: 'Neem' },
        { t: 'je' },
        { t: 'ook' },
        { t: 'de' },
        { t: 'witte' },
        { t: 'mappen' },
        { t: 'mee?' },
        { t: 'Die' },
        { t: 'liggen' },
        { t: 'in' },
        { t: 'de' },
        { t: 'kassten', fix: 'kasten', why: 'kast heeft al twee medeklinkers (st): niet verdubbelen.' },
        { t: 'bij' },
        { t: 'de' },
        { t: 'ingang.' },
        { t: 'Groetjes,' },
        { t: 'Esra' },
        { t: '(en' },
        { t: 'haar' },
        { t: 'drie' },
        { t: 'collegaas)', fix: 'collega’s)', also: ['collegae)'], why: 'Na een a komt in het meervoud ’s: collega’s. Zo blijft de a lang. (collegae mag ook.)' },
      ],
      done: { title: 'Goed gezocht', text: 'Vier keer de verdubbelregel, één keer het woordeinde, en één keer een meervoud met apostrof.' },
    },
    {
      kind: 'dictation',
      id: 'leraressen',
      prompt: 'Luister en typ de zin.',
      sentence: 'Na de les zetten de leraressen de kapotte computers in een stoffige kast bij de kantine.',
      right: 'Goed: zetten, leraressen, kapotte en stoffige hebben een dubbele medeklinker na een korte klank. Les aan het eind niet, kast niet (al st), en computers en kantine ook niet.',
      wrong: 'Let op: zet-ten, le-ra-res-sen, ka-pot-te en stof-fi-ge: korte klank, één medeklinker, klinker erachter, dus dubbel. Les aan het eind van het woord: één s. Kast heeft al twee medeklinkers. En de g in stoffige verdubbel je niet: na -ig nooit.',
    },
    {
      kind: 'swipe',
      id: 'zinnen',
      prompt: 'Is deze zin goed geschreven?',
      cards: [
        { t: 'Hij zette de kapotte lamp buiten bij de container.', ok: true, why: 'zet + te: zette. kapot + e: korte o + t, dus tt.' },
        { t: 'Wij wandellen elke zondag in het bos.', ok: false, fix: 'wandelen', why: 'Na de doffe e van wandel verdubbel je niet.' },
        { t: 'Er waren veel leraressen op de ouderavond.', ok: true, why: 'Woorden op -es verdubbelen de s: leraressen.' },
        { t: 'Hij heeft de harrde schijf vervangen.', ok: false, fix: 'harde', why: 'hard heeft al twee medeklinkers: geen dubbele r.' },
        { t: 'Doe het raam open voor wat frise lucht.', ok: false, fix: 'frisse', why: 'fris + e: korte i + s, dus ss.' },
        { t: 'De trein stoppte bij elk station.', ok: false, fix: 'stopte', why: 'stop + te: na de p komt een medeklinker, dus één p.' },
        { t: 'Wij hebben de zakken met afval naast de deur gezet.', ok: true, why: 'zak, zakken: korte a + k, dus kk. gezet: aan het eind één t.' },
        { t: 'De tegels in de badkamer zijn erg glad.', ok: true, why: 'te-gels: lange e in een open lettergreep, dus geen dubbele g.' },
        { t: 'Mijn kennisen komen morgen eten.', ok: false, fix: 'kennissen', why: 'Woorden op -nis verdubbelen de s: kennissen.' },
        { t: 'Dat was echt een gezelligge avond.', ok: false, fix: 'gezellige', why: 'Na -ig verdubbel je nooit: gezellige.' },
        { t: 'Hij belt morgen terug.', ok: true, why: 'bel + t: na de l komt een medeklinker, dus één l.' },
        { t: 'De monniken maken zelf kaas.', ok: true, why: 'monnik, monniken: een uitzondering zonder dubbele k.' },
      ],
    },
    {
      kind: 'rewrite',
      id: 'meervoud-zin',
      prompt: 'Schrijf de zin opnieuw met ‘mijn vriendinnen’ in plaats van ‘mijn vriendin’.',
      source: 'Mijn vriendin zit in de kantine en wacht op de bus.',
      accept: ['Mijn vriendinnen zitten in de kantine en wachten op de bus.'],
      why: 'zit → zitten: korte i + t, dus tt. Maar wacht → wachten: daar staan al twee medeklinkerklanken (ch en t), dus niet verdubbelen.',
    },
    {
      kind: 'type',
      id: 'slimmer',
      prompt: 'Typ de vorm van ‘slim’ die in de zin past.',
      before: 'Mijn dochter is veel',
      after: 'dan ik.',
      hint: '',
      answer: 'slimmer',
      why: 'slim + -er: korte i en één m, en er komt een klinker achter. Dus mm: slim-mer.',
    },
    {
      kind: 'choice',
      id: 'rekenen',
      prompt: 'Welke vorm past?',
      before: 'Mijn zoon vindt',
      after: 'het moeilijkste vak op school.',
      options: ['rekenen', 'rekennen', 'rekkenen', 'reekenen'],
      answer: 'rekenen',
      why: 're-ke-nen: de eerste e is lang en staat in een open lettergreep, de tweede is een doffe e. Nergens verdubbelen, en ook geen ee.',
    },
    {
      kind: 'bet',
      id: 'perziken',
      prompt: 'Een lastige: wat is het meervoud van ‘perzik’?',
      options: ['perziken', 'perzikken', 'perzieken', 'persiken'],
      answer: 'perziken',
      why: 'perzik is een uitzondering: geen verdubbeling, net als monnik en monniken. Dit woord moet je gewoon leren.',
    },
    {
      kind: 'sort',
      id: 'mix',
      prompt: 'Welke spelling is goed?',
      buckets: ['goed', 'fout'],
      items: [
        { t: 'vriendinnen', b: 0 },
        { t: 'ballonen', b: 1 },
        { t: 'stoffige', b: 0 },
        { t: 'tekennen', b: 1 },
        { t: 'stopte', b: 0 },
        { t: 'koninginen', b: 1 },
        { t: 'gezellige', b: 0 },
        { t: 'wolkken', b: 1 },
        { t: 'monniken', b: 0 },
        { t: 'prettigge', b: 1 },
        { t: 'zakken', b: 0 },
        { t: 'witer', b: 1 },
        { t: 'dikker', b: 0 },
        { t: 'bakerij', b: 1 },
      ],
      why: 'Goed: vriendinnen (-in), stoffige, zakken en dikker (korte klank + één medeklinker), stopte (na de p komt een t), gezellige (na -ig nooit dubbel), monniken (uitzondering). Fout: ballonnen of ballons (korte o + n), tekenen (doffe e), koninginnen (-in), wolken (al twee medeklinkers), prettige (na -ig niet), witter (korte i + t), bakkerij (korte a + k).',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro:
        'Bijna dertig opdrachten door elkaar. Typ het hele woord. Moet je knippen? Zet dan een streepje op elke knip, zoals *bo-men*. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Vul de vorm van *laf* in',
          before: 'Dat was een',
          after: 'smoes.',
          a: 'laffe',
          why: 'laf + e: korte a en één f, en er komt een e achter. Dus ff. Je hoort een f, dus geen v.',
        },
        { q: 'Vul de vorm van *los* in', before: 'Er zaten nog wat', after: 'schroeven in de doos.', a: 'losse', why: 'los + e: korte o + s, dus ss.' },
        {
          q: 'Vul de vorm van *kapot* in',
          before: 'Ik breng de',
          after: 'fiets naar de fietsenmaker.',
          a: 'kapotte',
          why: 'ka-pot-te: korte o + t, en er komt een e achter: tt.',
        },
        { q: 'Knip in lettergrepen (met streepjes): *bakkerij*', a: 'bak-ke-rij', why: 'De dubbele k gaat uit elkaar: bak-ke. Dan gaat de r mee: rij.' },
        { q: 'Bijvoeglijk naamwoord van *de zon*', before: 'Morgen wordt het', after: 'en warm.', a: 'zonnig', why: 'zon + -ig: korte o + n, dus nn.' },
        {
          q: 'Verleden tijd van *zetten*',
          before: 'Mijn collega',
          after: 'de dozen in de gang.',
          a: 'zette',
          why: 'Stam zet + -te: zette. De ene t hoort bij de stam, de andere bij -te.',
        },
        {
          q: 'Vul de vorm van *bellen* in',
          before: 'Mijn baas',
          after: 'me morgen om acht uur.',
          a: 'belt',
          why: 'stam bel + t: belt. Na de l komt een medeklinker, dus één l.',
        },
        {
          q: 'Vul de vorm van *lopen* in',
          before: 'Hij',
          after: 'vanaf morgen elke dag naar zijn werk.',
          a: 'loopt',
          why: 'stam loop + t: loopt. De p en de t sluiten de lettergreep, dus oo.',
        },
        {
          q: 'Meervoud van *eigenares*',
          before: 'De twee',
          after: 'van de winkel zijn zussen.',
          a: 'eigenaressen',
          why: 'Woorden op -es verdubbelen de s: eigenaressen.',
        },
        {
          q: 'Meervoud van *boerin*',
          before: 'Op de markt verkopen twee',
          after: 'hun kaas.',
          a: 'boerinnen',
          why: 'Woorden op -in verdubbelen de n: boerinnen.',
        },
        {
          q: 'Vul de wij-vorm in (ik verander)',
          before: 'Morgen',
          after: 'wij het wachtwoord.',
          a: 'veranderen',
          why: 'Na de doffe e van verander verdubbel je niet: veranderen.',
        },
        {
          q: 'Verleden tijd van *praten*',
          before: 'Wij',
          after: 'tot middernacht door.',
          a: 'praatten',
          why: 'Stam praat, en t staat in ’t kofschip: -ten. praat + ten = praatten. praat is gesloten, dus aa.',
        },
        { q: 'Vul de vorm van *dun* in', before: 'Deze muur is nog', after: 'dan die in de keuken.', a: 'dunner', why: 'dun + -er: korte u + n, dus nn.' },
        {
          q: 'Meervoud van *monnik*',
          before: 'In het klooster wonen nog zes',
          after: '.',
          a: 'monniken',
          why: 'monnik is een uitzondering: monniken, met één k.',
        },
        {
          q: 'Vul de vorm van *gezellig* in',
          before: 'Bedankt voor de',
          after: 'avond!',
          a: 'gezellige',
          why: 'gezellig + e: na -ig verdubbel je nooit. gezellige.',
        },
        { q: 'Meervoud van *ski*', before: 'Ik huur twee paar', after: 'voor de vakantie.', a: 'ski’s', why: 'ski eindigt op i: meervoud met ’s.' },
        {
          q: 'Vul de vorm van *narekenen* in',
          before: 'Hij',
          after: 'morgen alles na op zijn telefoon.',
          a: 'rekent',
          why: 'stam reken + t: rekent. Na de doffe e geen dubbele n.',
        },
        {
          q: 'Meervoud van *getuigenis*',
          before: 'De politie verzamelt',
          after: 'van de buren.',
          a: 'getuigenissen',
          why: 'Woorden op -nis verdubbelen de s: getuigenissen.',
        },
        {
          q: 'Vul de vorm van *leggen* in',
          before: 'Hij',
          after: 'de sleutel vanavond onder de mat.',
          a: 'legt',
          why: 'stam leg + t: legt. Aan het eind één g, en een werkwoord met g houdt de g: geen cht.',
        },
        {
          q: 'Vul de vorm van *fris* in',
          before: 'Doe het raam open, dan komt er',
          after: 'lucht binnen.',
          a: 'frisse',
          also: ['frissere'],
          why: 'fris + e: korte i + s, dus ss.',
        },
        {
          q: 'Vul de vorm van *boos* in',
          before: 'Er stond een',
          after: 'klant aan de balie.',
          a: 'boze',
          why: 'bo-ze: de o is lang, dus niet verdubbelen. En je hoort een z.',
        },
        {
          q: 'Knip in lettergrepen (met streepjes): *vriendinnen*',
          a: 'vrien-din-nen',
          why: 'n en d uit elkaar: vrien-din. De dubbele n gaat uit elkaar: din-nen.',
        },
        {
          q: 'Bijvoeglijk naamwoord van *de mist*',
          before: 'Het was',
          after: 'op de snelweg.',
          a: 'mistig',
          why: 'mist + -ig: er staan al twee medeklinkers (st), dus niet verdubbelen.',
        },
        {
          q: 'Vul de vorm van *verhuizen* in',
          before: 'Hij',
          after: 'volgende maand naar Almere.',
          a: 'verhuist',
          why: 'stam verhuis + t: verhuist. Aan het eind van de stam geen z, maar s.',
        },
        {
          q: 'Verleden tijd van *zitten*',
          before: 'Wij',
          after: 'twee uur in de file.',
          a: 'zaten',
          why: 'zitten, zat, zaten: in za-ten is de a lang en staat hij aan het eind van de lettergreep. Dus één t.',
        },
        {
          q: 'Vul de vorm van *spelen* in',
          before: 'Mijn zoon',
          after: 'volgend seizoen elke zaterdag voetbal.',
          a: 'speelt',
          why: 'stam speel + t: speelt. Gesloten lettergreep, dus ee. Geen dubbele l: de klank is lang.',
        },
        {
          q: 'Schrijf het woord dat je hoort: dit bewijs krijg je als je in de winkel betaalt',
          say: 'de kassabon',
          a: 'de kassabon',
          also: ['kassabon', 'bon', 'de bon', 'bonnetje', 'het bonnetje', 'kassabonnetje', 'het kassabonnetje'],
          why: 'kassa + bon: in kas-sa is de a kort, dus ss. bon eindigt op één n.',
        },
        {
          q: 'Bijvoeglijk naamwoord van *plakken*',
          before: 'Mijn handen zijn helemaal',
          after: 'van de jam.',
          a: 'plakkerig',
          why: 'plak + -erig: korte a + k, dus kk. Na de doffe e van -erig: één r.',
        },
      ],
      done: { title: 'Reeks klaar', text: 'Kort of lang, één of twee medeklinkers, -ig, -nis, -es en -in: je hebt het steeds zelf beslist.' },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de nieuwsbrief aan. Typ elk woord helemaal.',
      intro: 'Kijk goed naar de zin om het gat heen. In het grijs staat soms een hint.',
      title: 'Nieuwsbrief van de voetbalclub',
      text: 'Beste leden en ouders,\n\nNa een {zonnige|zon + -ig + -e|zon-ni-ge: korte o en één n, dus nn. Na -ig verdubbel je niet.} zomer beginnen we weer met trainen. Helaas is er in de {kleedkamers|kl___kamers|kleed + kamers: kleed is gesloten, dus ee. Van kleden, dus d. ka is open, dus één a.} veel kapot. Er hangen twee {kapotte|kapot + e|ka-pot-te: korte o + t, en er komt een e achter: tt.} douches, en de {ballen|meervoud van bal|bal-len: korte a + l, en er komt -en achter: ll.} zijn te slap.\n\nDaarom zoeken we {vrijwilligers|mensen die gratis helpen|vrij + willig: wil + -ig, korte i + l, dus ll. En vrij schrijf je met ij.} voor de bar en voor het schoonmaken van de {stoffige|stof + -ig + -e|stof-fi-ge: korte o + f, dus ff. Na -ig geen dubbele g.} kantine. Een paar {vaders~papa’s|ouders, maar dan alleen de mannen|va-ders: lange a in een open lettergreep, dus één d. (papa’s mag ook.)} hebben al nieuwe {netten|meervoud van net|net-ten: korte e + t, dus tt.} in de doelen gehangen. Bedankt!\n\nOp zaterdag {spelen|ik speel, wij …|spe-len: lange e in een open lettergreep, dus één e en één l.} de jongste kinderen hun eerste {wedstrijd|potje tegen een andere club|wed + strijd: van wedden, dus d. En strijd met ij.}. Ouders mogen langs de lijn staan, maar niet op het {natte|nat + e|nat-te: korte a + t, en er komt een e achter: tt.} gras. De {scheidsrechter|sch_dsrechter|van scheiden: scheids met ei en d.} heeft altijd het laatste woord. Na afloop {zetten|ik zet, zij …|zet-ten: korte e + t, dus tt.} de spelers zelf de doelen terug.\n\nWe maken veel {foto’s|meervoud van foto|Na een o komt ’s: foto’s.} voor de website. Wilt u niet dat uw kind daarop staat? {Bel|bellen, als opdracht|Aan het eind van een woord verdubbel je niet: bel.} dan even met de trainer. Heeft u {ideeën|meervoud van idee|idee, ideeën: de ee blijft, met een trema waar de nieuwe lettergreep begint.} voor de club? Wij horen ze graag.\n\nSportieve groet,\nHet bestuur',
      why: 'Dubbel na een korte klank met één medeklinker en een klinker erachter: zonnige, kapotte, ballen, vrijwilligers, stoffige, netten, natte, zetten. Niet dubbel: aan het eind (bel), na een lange klank (vaders, spelen, kleedkamers) en na -ig. Uit eerdere lessen: wedstrijd met d, scheidsrechter met ei, foto’s met een apostrof en ideeën met een trema.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen uit een bericht van school. Hoofdletters en leestekens tellen mee.',
      title: 'Bericht van school: uitje naar het bos',
      sentences: [
        'Morgen stappen de kinderen vroeg in de bus naar het bos.',
        'Geef ze stevige schoenen, een dikke trui en een lunchpakket mee.',
        'Stop ook een extra paar sokken in de tas voor de natte paden.',
        'De juffen zorgen voor warme thee en een paar zakken met lekkere koekjes.',
        'Na de lunch brengt de bus alle kinderen terug naar het hek van de school.',
        'Met vragen kunt u de juffen de hele dag bellen.',
      ],
      right: 'Alles goed: stappen, dikke, sokken, natte, juffen, zakken, lekkere en bellen met een dubbele medeklinker; stop, bus, bos en hek aan het eind met één letter.',
      wrong: 'Kijk na: na een korte klank met één medeklinker en een klinker erachter verdubbel je (stap-pen, dik-ke, sok-ken, nat-te, juf-fen, zak-ken, lek-ke-re, bel-len). Aan het eind niet (stop, bus, bos, hek). En niet na twee medeklinkers (kinderen, warme) of na een lange klank (stevige, paden).',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'Team Inkoop', subject: 'Verhuizing naar de nieuwe kamer' },
      greeting: 'Hallo allemaal,',
      signoff: 'Groet,\nIngrid',
      tokens: [
        { t: 'Vrijdag' },
        { t: 'verhuizen' },
        { t: 'wij' },
        { t: 'naar' },
        { t: 'de' },
        { t: 'nieuwe' },
        { t: 'kamer' },
        { t: 'op' },
        { t: 'de' },
        { t: 'derde' },
        { t: 'verdiepping.', fix: 'verdieping.', why: 'ie is een lange klank: daarna verdubbel je niet. ver-die-ping.' },
        { t: 'Zet', trap: 'Goed: aan het eind van een woord verdubbel je niet. Pas in zetten komt de tweede t.' },
        { t: 'je' },
        { t: 'spullen' },
        { t: 'Donderdag', fix: 'donderdag', why: 'Dagen van de week schrijf je met een kleine letter.' },
        { t: 'in' },
        { t: 'de' },
        { t: 'groenne', fix: 'groene', why: 'oe is een lange klank: daarna verdubbel je niet. groe-ne.' },
        { t: 'dozen.' },
        { t: 'De' },
        { t: 'dozen' },
        { t: 'staan' },
        { t: 'al' },
        { t: 'in' },
        { t: 'de' },
        { t: 'gang,' },
        { t: 'naast' },
        { t: 'de' },
        { t: 'kapote', fix: 'kapotte', why: 'kapot + e: korte o + t, en er komt een e achter. Dus tt.' },
        { t: 'printer.' },
        { t: 'Plak' },
        { t: 'een' },
        { t: 'sticker' },
        { t: 'met' },
        { t: 'je' },
        { t: 'naam' },
        { t: 'op' },
        { t: 'elke' },
        { t: 'doos.' },
        { t: 'Losse', trap: 'Goed: los + e: korte o + s, en er komt een e achter. Dus ss.' },
        { t: 'kabbels', fix: 'kabels', why: 'ka-bels: de a is lang en staat in een open lettergreep. Geen dubbele b.' },
        { t: 'doe' },
        { t: 'je' },
        { t: 'in' },
        { t: 'een' },
        { t: 'aparte' },
        { t: 'zak.', trap: 'Goed: aan het eind van een woord één k. Pas in zakken komt de tweede k.' },
        { t: 'De' },
        { t: 'verhuizers' },
        { t: 'komen' },
        { t: 'om' },
        { t: 'half' },
        { t: 'negen.' },
        { t: 'Zij' },
        { t: 'zetten' },
        { t: 'de' },
        { t: 'kasten' },
        { t: 'en' },
        { t: 'de' },
        { t: 'bureau’s', fix: 'bureaus', why: 'Na eau komt in het meervoud alleen een s, zonder apostrof.' },
        { t: 'op' },
        { t: 'hun' },
        { t: 'plek.' },
        { t: 'Wil' },
        { t: 'je' },
        { t: 'ook' },
        { t: 'je' },
        { t: 'planten' },
        { t: 'water' },
        { t: 'geven?' },
        { t: 'Die' },
        { t: 'mogen', trap: 'Goed: mo-gen. De o is lang en staat in een open lettergreep: één o en één g.' },
        { t: 'niet' },
        { t: 'uitdroogen.', fix: 'uitdrogen.', why: 'uit-dro-gen: dro is open, dus één o.' },
        { t: 'Wie' },
        { t: 'wil,' },
        { t: 'kan' },
        { t: 'zaterdag' },
        { t: 'helpen' },
        { t: 'met' },
        { t: 'uitpaken.', fix: 'uitpakken.', why: 'pak, pakken: korte a + k, en er komt -en achter. Dus kk.' },
        { t: 'Daarna' },
        { t: 'eten' },
        { t: 'we' },
        { t: 'samen' },
        { t: 'een' },
        { t: 'broodje.' },
        { t: 'Dat' },
        { t: 'is' },
        { t: 'altijd' },
        { t: 'gezelig.', fix: 'gezellig.', why: 'ge-zel-lig: korte e + l, en er komt een klinker achter. Dus ll.' },
      ],
      done: {
        title: 'Nagekeken',
        text: 'Verdubbelen waar het moet: kapotte, uitpakken, gezellig. Niet verdubbelen na een lange klank: verdieping, groene, kabels. En uit eerdere lessen: donderdag, bureaus en uitdrogen.',
      },
    },
  ],
};
