import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": wanneer je een medeklinker verdubbelt (ballen, witte, prettig) en wanneer niet. */
export const LES_G22: LessonInput = {
  id: 'g22',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'Medeklinker verdubbelen',
  skill: 'Spelling',
  icon: 'll',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Korte klank? Dubbele medeklinker',
      panels: [
        {
          text: 'De korte klanken zijn *a*, *e*, *i*, *o* en *u*, zoals in *bal*, *pen*, *vis*, *bom* en *bus*. Komt er na zo’n korte klank één medeklinker, en daarna een klinker, dan schrijf je die medeklinker dubbel: *bal*, *bal-len*; *kat*, *kat-ten*; *pen*, *pen-nen*; *bus*, *bus-sen*. De eerste letter sluit de lettergreep, zodat de klank kort blijft. De tweede begint de volgende lettergreep.',
          rule: 'Korte klank + één medeklinker + er komt een klinker achter: verdubbel de medeklinker.',
          split: { word: 'bakker', answer: 'bak-ker', note: 'bak is gesloten door de eerste k: de a blijft kort. De tweede k begint ker.' },
          lab: {
            label: 'Tik een woord en zie het meervoud',
            chips: [
              { k: 'bal', out: 'ballen', note: 'Korte a + l, en er komt -en achter: ll.' },
              { k: 'kat', out: 'katten', note: 'Korte a + t: tt.' },
              { k: 'pen', out: 'pennen', note: 'Korte e + n: nn.' },
              { k: 'bus', out: 'bussen', note: 'Korte u + s: ss.' },
            ],
          },
        },
        {
          text: 'Waarom is dat nodig? Zonder dubbele letter wordt de lettergreep open, en dan lees je een lange klank. Vergelijk *bo-men* (van *boom*) met *bom-men* (van *bom*), *ma-nen* (van *maan*) met *man-nen* (van *man*), en *ko-pen* met *kop-pen*. Eén letter verschil, een heel ander woord.',
          rule: 'Eén medeklinker: lange klank (*bo-men*). Twee medeklinkers: korte klank (*bom-men*).',
          lab: {
            label: 'Tik een paar',
            chips: [
              { k: 'bomen · bommen', out: 'bo-men · bom-men', note: 'Lange o (boom) tegenover korte o (bom).' },
              { k: 'manen · mannen', out: 'ma-nen · man-nen', note: 'Lange a (maan) tegenover korte a (man).' },
              { k: 'kopen · koppen', out: 'ko-pen · kop-pen', note: 'Lange o (ik koop) tegenover korte o (de kop).' },
              { k: 'stelen · stellen', out: 'ste-len · stel-len', note: 'Lange e (ik steel) tegenover korte e (ik stel).' },
            ],
          },
          quiz: {
            q: 'Je bedoelt het meervoud van ‘bom’. Wat schrijf je?',
            options: ['bommen', 'bomen'],
            answer: 'bommen',
            why: 'bom heeft een korte o. Die blijft kort als je de m verdubbelt: bom-men. Bomen zijn de bomen in het park.',
          },
        },
        {
          text: 'Het geldt niet alleen voor het meervoud. Ook bij werkwoorden: *ik bel*, *wij bellen*; *ik zet*, *wij zetten*; *ik stop*, *wij stoppen*. Bij bijvoeglijke naamwoorden met *-e*: *wit*, *een witte muur*; *dik*, *een dikke trui*; *snel*, *een snelle auto*; *fris*, *frisse lucht*. En bij woorden met *-ig* of *-er*: *geluk*, *gelukkig*; *pret*, *prettig*; *bak*, *bakker*.',
          paradigm: {
            q: 'Zet de langere vorm in het goede vakje',
            cols: ['langere vorm'],
            rows: [
              { label: 'ik bel → wij …', cells: [{ fill: 'bellen', hint: 'Korte e + l: ll.' }] },
              { label: 'ik zet → wij …', cells: [{ fill: 'zetten', hint: 'Korte e + t: tt.' }] },
              { label: 'wit → een … muur', cells: [{ fill: 'witte', hint: 'Korte i + t: tt.' }] },
              { label: 'snel → een … auto', cells: [{ fill: 'snelle', hint: 'Korte e + l: ll.' }] },
              { label: 'geluk → …', cells: [{ fill: 'gelukkig', hint: 'Korte u + k, en -ig erachter: kk.' }] },
              { label: 'pret → …', cells: [{ fill: 'prettig', hint: 'Korte e + t, en -ig erachter: tt.' }] },
            ],
            extra: ['belen', 'zeten', 'wite', 'snele', 'gelukig', 'pretig'],
            note: 'Meervoud, werkwoord, -e, -ig of -er: zodra er een klinker achter komt, verdubbel je na een korte klank.',
          },
        },
        {
          text: 'Aan het eind van een woord verdubbel je nooit. Daar is de lettergreep al gesloten, en blijft de klank vanzelf kort: *de bal*, *ik zet*, *ik bel*, *het is wit*. Pas als er een klinker achter komt, heb je de tweede letter nodig.',
          rule: 'Aan het eind van een woord: nooit een dubbele medeklinker (*ik zet*, niet *ik zett*).',
          show: [
            { wrong: 'ik zett', right: 'ik zet' },
            { wrong: 'ik bell je', right: 'ik bel je' },
            { wrong: 'het is witt', right: 'het is wit' },
          ],
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Ik zet koffie.', 'Ik zett koffie.'],
            answer: 'Ik zet koffie.',
            why: 'Na zet komt geen klinker meer. De lettergreep is al gesloten: één t is genoeg.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'wel-of-niet',
      prompt: 'Verdubbel je de medeklinker in de langere vorm?',
      buckets: ['ja, dubbel', 'nee, niet dubbel'],
      items: [
        { t: 'kat → meervoud', b: 0 },
        { t: 'boot → meervoud', b: 1 },
        { t: 'kast → meervoud', b: 1 },
        { t: 'pen → meervoud', b: 0 },
        { t: 'ik zit → wij …', b: 0 },
        { t: 'ik loop → wij …', b: 1 },
        { t: 'dik → een …e man', b: 0 },
        { t: 'groot → een …e man', b: 1 },
        { t: 'hard → een …e wind', b: 1 },
        { t: 'snel → een …e trein', b: 0 },
        { t: 'ik lach → wij …', b: 1 },
        { t: 'ik zing → wij …', b: 1 },
      ],
      why: 'Dubbel: katten, pennen, zitten, dikke, snelle (korte klank + één medeklinker). Niet dubbel: boten en lopen en grote (lange klank), kasten en harde (al twee medeklinkers), lachen en zingen (ch en ng verdubbel je nooit).',
    },
    {
      kind: 'type',
      id: 'bussen',
      prompt: 'Typ het meervoud.',
      before: 'Op het plein staan drie',
      after: 'klaar.',
      hint: 'meervoud van bus',
      answer: 'bussen',
      why: 'bus heeft een korte u. Er komt -en achter: de s wordt dubbel, bus-sen.',
    },
    {
      kind: 'choice',
      id: 'prettige',
      prompt: 'Welk woord past?',
      before: 'Ik wens je een',
      after: 'avond!',
      options: ['prettige', 'pretige', 'prettigge'],
      answer: 'prettige',
      why: 'pret + -ig: korte e, dus tt. De g na -i verdubbel je niet: de i in -ig is een doffe klank.',
    },
    {
      kind: 'fix',
      id: 'zitten',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Wij ziten om zes uur aan tafel.',
      wrong: 1,
      answer: 'zitten',
      why: 'ik zit, wij zit-ten: korte i + t, en er komt -en achter. De t wordt dubbel.',
    },
    {
      kind: 'type',
      id: 'stoppen',
      prompt: 'Typ de goede vorm van het werkwoord.',
      before: 'De bus stopt hier niet. Wij',
      after: 'bij de volgende halte.',
      hint: 'wij …',
      answer: 'stoppen',
      why: 'ik stop, wij stop-pen: korte o + p, dus pp.',
    },
    {
      kind: 'bet',
      id: 'koppen',
      prompt: 'Je zet koffie voor vier collega’s. Hoeveel … zet je klaar?',
      options: ['koppen', 'kopen', 'kooppen'],
      answer: 'koppen',
      why: 'de kop, korte o: kop-pen. Kopen is wat je in de winkel doet.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Wanneer níet verdubbelen',
      panels: [
        {
          text: 'Je verdubbelt alleen na een korte klank met maar één medeklinker. Dus níet na een lange klank: *raam*, *ra-men*; *boot*, *bo-ten*; *ik loop*, *wij lo-pen*. En níet als er al twee medeklinkers staan: *kast*, *kas-ten*; *kant*, *kan-ten*; *hard*, *har-de*; *wolk*, *wol-ken*. Die lettergreep is al gesloten. Ook *ch* en *ng* verdubbel je nooit: *lachen*, *zingen*, *jongen*, *ringen*.',
          rule: 'Niet verdubbelen: na een lange klank, na twee medeklinkers, en bij *ch* en *ng*.',
          mark: {
            q: 'Tik de woorden met een dubbele medeklinker die er níet hoort',
            sentence: 'kassten lachen zingen botten harrde katten jonggen',
            targets: [0, 4, 6],
            note: 'kasten en harde hebben al twee medeklinkers. jongen: ng verdubbel je nooit. botten is goed (het meervoud van bot), net als katten.',
          },
        },
        {
          text: 'Ook na de doffe e verdubbel je niet. De doffe e is de zwakke klank in *-el*, *-em*, *-en* en *-er*: *ik teken*, *wij tekenen*; *ik wandel*, *wij wandelen*; *ik reken*, *wij rekenen*; *ik open*, *wij openen*. Die e klinkt niet als de korte e van *pen*, dus er komt geen tweede letter.',
          rule: 'Na de doffe e: niet verdubbelen (*tekenen*, *wandelen*).',
          build: {
            before: 'Wij gaan vanmiddag samen',
            stem: 'teke',
            endings: ['nen', 'nnen'],
            answer: 'nen',
            note: 'tekenen: de laatste e van teken is een doffe e. Daarna verdubbel je niet.',
          },
        },
        {
          text: 'Een paar woorden hebben geen klemtoon op de korte klank en verdubbelen tóch. Dat zijn woorden op *-is*, *-es* en *-in*: *kennis*, *kennissen*; *lerares*, *leraressen*; *vriendin*, *vriendinnen*; *koningin*, *koninginnen*. Er zijn ook woorden die je moet leren: *monnik* wordt *monniken*, *perzik* wordt *perziken*. Bij twijfel kijk je in de woordenlijst.',
          rule: '*-is*, *-es*, *-in*: wel verdubbelen (*vriendinnen*). *monniken* en *perziken*: uitzonderingen.',
          quiz: {
            q: 'Wat is het meervoud van ‘vriendin’?',
            options: ['vriendinnen', 'vriendinen'],
            answer: 'vriendinnen',
            why: 'Woorden op -in verdubbelen de n: vriendin-nen, net als koninginnen.',
          },
        },
        {
          text: 'Twijfel je? Stel drie vragen. Vraag 1: is de klank kort (*a*, *e*, *i*, *o*, *u*)? Vraag 2: staat er maar één medeklinker achter? Vraag 3: komt er een klinker achter, zoals *-en*, *-e*, *-er* of *-ig*? Drie keer ja: verdubbelen. Eén keer nee: niet verdubbelen. Let op: bij *s* en *f* wordt het gewoon *ss* en *ff*: *les*, *lessen*; *straf*, *straffen*.',
          rule: 'Kort? Eén medeklinker? Klinker erachter? Drie keer ja: verdubbelen.',
          lab: {
            label: 'Tik een woord en stel de drie vragen',
            chips: [
              { k: 'bel → bellen', out: 'ja · ja · ja', note: 'Korte e, één l, -en erachter: verdubbelen.' },
              { k: 'boot → boten', out: 'nee', note: 'De oo is lang: niet verdubbelen.' },
              { k: 'kast → kasten', out: 'ja · nee', note: 'Korte a, maar al twee medeklinkers (st): niet verdubbelen.' },
              { k: 'ik zet', out: 'ja · ja · nee', note: 'Er komt niets achter: één t.' },
              { k: 'les → lessen', out: 'ja · ja · ja', note: 'Bij de s wordt het gewoon ss.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-collega',
      prompt: 'Lees de mail aan een collega. Tik elke fout aan en verbeter hem.',
      intro: 'Er staan zes fouten in. Let op: dubbel waar het moet, en enkel waar het moet.',
      header: { to: 'Mark', subject: 'Vergadering morgen' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Mark,' },
        { t: 'Morgen' },
        { t: 'hebben' },
        { t: 'we' },
        { t: 'om' },
        { t: 'tien' },
        { t: 'uur' },
        { t: 'een' },
        { t: 'vergadering.' },
        { t: 'Wil' },
        { t: 'jij' },
        { t: 'de' },
        { t: 'kopjes' },
        { t: 'en' },
        { t: 'de' },
        { t: 'pennen' },
        { t: 'klaarzeten?', fix: 'klaarzetten?', why: 'ik zet, wij zetten: korte e + t, dus tt.' },
        { t: 'Ik' },
        { t: 'bell', fix: 'bel', why: 'Aan het eind van een woord verdubbel je nooit: ik bel.' },
        { t: 'de' },
        { t: 'klant' },
        { t: 'om' },
        { t: 'negen' },
        { t: 'uur.' },
        { t: 'Hij' },
        { t: 'was' },
        { t: 'erg' },
        { t: 'gelukig', fix: 'gelukkig', why: 'geluk + -ig: korte u + k, dus kk.' },
        { t: 'met' },
        { t: 'onze' },
        { t: 'snele', fix: 'snelle', why: 'snel + -e: korte e + l, dus ll.' },
        { t: 'reactie.' },
        { t: 'Neem' },
        { t: 'je' },
        { t: 'ook' },
        { t: 'de' },
        { t: 'witte' },
        { t: 'mappen' },
        { t: 'mee?' },
        { t: 'Die' },
        { t: 'liggen' },
        { t: 'in' },
        { t: 'de' },
        { t: 'kassten', fix: 'kasten', why: 'kast heeft al twee medeklinkers (st): niet verdubbelen.' },
        { t: 'bij' },
        { t: 'de' },
        { t: 'ingang.' },
        { t: 'Groetjes,' },
        { t: 'Esra' },
        { t: '(en' },
        { t: 'haar' },
        { t: 'drie' },
        { t: 'collegaas)', fix: 'collega’s)', why: 'Na een a komt in het meervoud ’s: collega’s. Zo blijft de a lang.' },
      ],
      done: { title: 'Goed gezocht', text: 'Vier keer de verdubbelregel, één keer het woordeinde, en één keer een meervoud met apostrof.' },
    },
    {
      kind: 'dictation',
      id: 'bakker',
      prompt: 'Luister en typ de zin.',
      sentence: 'De bakker zette een kop sterke koffie op de witte tafel.',
      right: 'Goed: bakker, zette, koffie en witte hebben een dubbele medeklinker na een korte klank. Sterke niet: daar staan al twee medeklinkers (rk).',
      wrong: 'Let op: bak-ker, zet-te, kof-fie en wit-te. Na een korte klank met één medeklinker en een klinker erachter verdubbel je. Tafel heeft een lange a: één f.',
    },
    {
      kind: 'swipe',
      id: 'zinnen',
      prompt: 'Is deze zin goed geschreven?',
      cards: [
        { t: 'We moeten de kinderen om drie uur ophalen.', ok: true, why: 'kinderen: na de i staan al twee medeklinkers (nd), en na de doffe e verdubbel je niet.' },
        { t: 'Wij wandellen elke zondag in het bos.', ok: false, fix: 'wandelen', why: 'Na de doffe e van wandel verdubbel je niet.' },
        { t: 'Mijn zus heeft twee lieve vriendinnen.', ok: true, why: 'Woorden op -in verdubbelen: vriendinnen.' },
        { t: 'Hij heeft de harrde schijf vervangen.', ok: false, fix: 'harde', why: 'hard heeft al twee medeklinkers: geen dubbele r.' },
        { t: 'De zon schijnt, en de lucht is fris.', ok: true, why: 'fris aan het eind: één s.' },
        { t: 'Ik heb frise lucht nodig.', ok: false, fix: 'frisse', why: 'fris + -e: korte i + s, dus ss.' },
        { t: 'Ze zongen samen een liedje.', ok: true, why: 'ng verdubbel je nooit.' },
        { t: 'Wij lachchen om zijn grap.', ok: false, fix: 'lachen', why: 'ch verdubbel je nooit: lachen.' },
      ],
    },
    {
      kind: 'rewrite',
      id: 'meervoud-zin',
      prompt: 'Zet de zin in het meervoud.',
      source: 'De kat zit op het dikke kussen.',
      accept: ['De katten zitten op de dikke kussens.', 'De katten zitten op het dikke kussen.'],
      why: 'kat → katten, zit → zitten: korte klank + één medeklinker, dus verdubbelen. Kussen eindigt op -en zonder klemtoon: kussens.',
    },
    {
      kind: 'type',
      id: 'leraressen',
      prompt: 'Typ het meervoud.',
      before: 'Op deze school werken veel',
      after: '.',
      hint: 'meervoud van lerares',
      answer: 'leraressen',
      why: 'Woorden op -es verdubbelen de s: leraressen.',
    },
    {
      kind: 'choice',
      id: 'rekenen',
      prompt: 'Welke vorm past?',
      before: 'Kun jij even',
      after: 'hoeveel het kost?',
      options: ['rekenen', 'rekennen', 'rekkenen'],
      answer: 'rekenen',
      why: 're-ke-nen: de eerste e is lang, de tweede is doffe e. Nergens verdubbelen.',
    },
    {
      kind: 'bet',
      id: 'perziken',
      prompt: 'Een lastige: wat is het meervoud van ‘perzik’?',
      options: ['perziken', 'perzikken'],
      answer: 'perziken',
      why: 'perzik is een uitzondering: geen verdubbeling, net als monnik en monniken. Dit woord moet je gewoon leren.',
    },
    {
      kind: 'sort',
      id: 'mix',
      prompt: 'Welke spelling is goed?',
      buckets: ['goed', 'fout'],
      items: [
        { t: 'kennissen', b: 0 },
        { t: 'ballonen', b: 1 },
        { t: 'zakken', b: 0 },
        { t: 'jongens', b: 0 },
        { t: 'tekennen', b: 1 },
        { t: 'smalle', b: 0 },
        { t: 'koninginen', b: 1 },
        { t: 'stoppen', b: 0 },
        { t: 'botten', b: 0 },
        { t: 'wolkken', b: 1 },
      ],
      why: 'Goed: kennissen (-is), zakken, jongens (ng), smalle, stoppen, botten. Fout: ballonnen (korte o met klemtoon), tekenen (doffe e), koninginnen (-in), wolken (al twee medeklinkers).',
    },
  ],
};
