import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": het meervoud met -en, -s of ’s, en de woorden die anders gaan. */
export const LES_G23: LessonInput = {
  id: 'g23',
  stage: 'regels',
  domain: 'morf',
  also: ['orth'],
  title: 'Meervoud: -en, -s of ’s?',
  skill: 'Spelling',
  icon: '-en',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Drie manieren om meer te maken',
      panels: [
        {
          text: 'De meeste woorden krijgen in het meervoud *-en*: *boek*, *boeken*; *deur*, *deuren*; *trein*, *treinen*. Als je *-en* toevoegt, gelden meteen de regels van de lettergreep. Een lange klank wordt één letter: *boot*, *bo-ten*. Na een korte klank verdubbel je: *ster*, *ster-ren*; *vis*, *vis-sen*. En een s of f kan een z of v worden: *huis*, *hui-zen*. Probeer het met de voorwerpen.',
          rule: 'Basisregel: meervoud met *-en*, en dan de regels van open en gesloten lettergrepen.',
          morph: {
            q: 'Kies het goede meervoud, en zie het voorwerp vermenigvuldigen',
            rounds: [
              { thing: 'boek', from: 'het boek', ask: 'veel boeken', effect: 'veel', options: ['boeken', 'boeks', 'boekken'], answer: 'boeken', note: 'Gewoon -en. De oe blijft altijd oe.' },
              { thing: 'boot', from: 'de boot', ask: 'veel boten', effect: 'veel', options: ['booten', 'boten', 'botten'], answer: 'boten', note: 'bo-ten: open lettergreep, dus één o.' },
              { thing: 'ster', from: 'de ster', ask: 'veel sterren', effect: 'veel', options: ['steren', 'sterren', 'sters'], answer: 'sterren', note: 'Korte e + r: verdubbelen, ster-ren.' },
              { thing: 'vis', from: 'de vis', ask: 'veel vissen', effect: 'veel', options: ['vissen', 'visen', 'vizen'], answer: 'vissen', note: 'Korte i: de s wordt dubbel. Je hoort een s, dus geen z.' },
              { thing: 'huis', from: 'het huis', ask: 'veel huizen', effect: 'veel', options: ['huisen', 'huizen', 'huissen'], answer: 'huizen', note: 'Je hoort in het meervoud een z: huizen. Na ui verdubbel je nooit.' },
              { thing: 'ei', from: 'het ei', ask: 'veel eieren', effect: 'veel', options: ['eien', 'eieren', 'eis'], answer: 'eieren', note: 'Een uitzondering: ei krijgt -eren. Dat moet je leren.' },
            ],
            note: 'Vijf keer -en met de lettergreepregels, en één uitzondering: eieren.',
          },
        },
        {
          text: 'Woorden die eindigen op *-el*, *-em*, *-en* of *-er* zonder klemtoon, krijgen *-s*: *tafel*, *tafels*; *bezem*, *bezems*; *jongen*, *jongens*; *kamer*, *kamers*. Ook woorden op *-je*: *meisje*, *meisjes*; *huisje*, *huisjes*. Hoor je in de laatste lettergreep een doffe e? Dan is het bijna altijd *-s*. Ligt de klemtoon op het eind, dan krijg je wel *-en*: *kasteel*, *kastelen*.',
          rule: 'Doffe e in de laatste lettergreep (*-el*, *-em*, *-en*, *-er*) of *-je*: meervoud met *-s*.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'tafel', out: 'tafels', note: 'ta-fel: de laatste lettergreep heeft een doffe e. Dus -s.' },
              { k: 'jongen', out: 'jongens', note: 'jon-gen: doffe e. Niet jongenen, maar jongens.' },
              { k: 'kamer', out: 'kamers', note: 'ka-mer: doffe e, dus -s.' },
              { k: 'meisje', out: 'meisjes', note: 'Een verkleinwoord op -je krijgt altijd -s.' },
              { k: 'kasteel', out: 'kastelen', note: 'De klemtoon ligt op teel, en de ee is lang: -en.' },
            ],
          },
        },
        {
          text: 'Eindigt een woord op *a*, *i*, *o*, *u* of *y*, dan krijgt het *’s*: *auto’s*, *ski’s*, *menu’s*, *baby’s*, *pagina’s*, *foto’s*. De apostrof houdt de klinker lang. Zonder apostrof lees je *autos* met een korte o. Eindigt het woord op *é* of *eau*, dan is de klank al duidelijk en zet je alleen *-s*: *café*, *cafés*; *cadeau*, *cadeaus*; *bureau*, *bureaus*. En een doffe e aan het eind krijgt ook gewoon *-s*: *tante*, *tantes*; *garage*, *garages*.',
          rule: '*a*, *i*, *o*, *u*, *y* aan het eind: *’s* (*auto’s*). *é*, *eau* en doffe e: *-s* (*cafés*, *cadeaus*, *tantes*).',
          quiz: {
            q: 'Wat is het meervoud van ‘cadeau’?',
            options: ['cadeaus', 'cadeau’s', 'cadeauen'],
            answer: 'cadeaus',
            why: 'Na eau is de klank al duidelijk, ook met een s erachter. Dus geen apostrof: cadeaus.',
          },
          deep: {
            q: 'En bij een woord op ee of ie?',
            a: 'Dan krijg je *-en* met een trema: *zee*, *zeeën*; *idee*, *ideeën*; *knie*, *knieën*. Bij een *-ie* zonder klemtoon wordt het *-iën*: *bacterie*, *bacteriën*. Je ziet dat in de valkuilen.',
          },
        },
        {
          text: 'Twijfel je? Volg dit stappenplan. Stap 1: eindigt het woord op *-el*, *-em*, *-en*, *-er* of *-je* zonder klemtoon? Dan *-s*. Stap 2: eindigt het op *a*, *i*, *o*, *u* of *y*? Dan *’s*. Stap 3: eindigt het op *é*, *eau* of een doffe e? Dan *-s*. Stap 4: in alle andere gevallen *-en*, en dan let je op één letter of twee, op verdubbelen en op z en v.',
          rule: '-el, -em, -en, -er, -je: *-s*. Klinker a, i, o, u, y: *’s*. Anders: *-en*.',
          mark: {
            q: 'Tik de woorden die in het meervoud alleen -s krijgen (zonder apostrof)',
            sentence: 'lepel trein oma deken boom café oven kast',
            targets: [0, 3, 5, 6],
            note: 'lepels, dekens, ovens: doffe e. cafés: na é alleen -s. treinen, bomen en kasten krijgen -en. oma krijgt ’s: oma’s.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'welk-meervoud',
      prompt: 'Welk meervoud krijgt dit woord?',
      buckets: ['-en', '-s', '’s'],
      items: [
        { t: 'boek', b: 0 },
        { t: 'tafel', b: 1 },
        { t: 'auto', b: 2 },
        { t: 'deur', b: 0 },
        { t: 'kamer', b: 1 },
        { t: 'menu', b: 2 },
        { t: 'gordijn', b: 0 },
        { t: 'bezem', b: 1 },
        { t: 'baby', b: 2 },
        { t: 'kasteel', b: 0 },
        { t: 'meisje', b: 1 },
        { t: 'pagina', b: 2 },
      ],
      why: '-en: boeken, deuren, gordijnen, kastelen (klemtoon op het eind). -s: tafels, kamers, bezems, meisjes (doffe e of -je). ’s: auto’s, menu’s, baby’s, pagina’s (a, u, o, y aan het eind).',
    },
    {
      kind: 'type',
      id: 'glazen',
      prompt: 'Typ het meervoud.',
      before: 'Zet jij zes',
      after: 'op tafel?',
      hint: 'meervoud van glas',
      answer: 'glazen',
      why: 'glas wordt glazen: de a wordt lang (één a in een open lettergreep) en je hoort een z.',
    },
    {
      kind: 'choice',
      id: 'cadeaus',
      prompt: 'Welke spelling is goed?',
      before: 'Voor haar verjaardag kreeg ze veel',
      after: '.',
      options: ['cadeaus', 'cadeau’s', 'cadeauen'],
      answer: 'cadeaus',
      why: 'Na eau alleen -s, zonder apostrof.',
    },
    {
      kind: 'fix',
      id: 'huizen',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'In onze straat staan veel mooie huisen.',
      wrong: 6,
      answer: 'huizen',
      why: 'Je hoort in het meervoud een z: huizen. Zo ook muis, muizen en reis, reizen.',
    },
    {
      kind: 'type',
      id: 'kinderen',
      prompt: 'Typ het meervoud.',
      before: 'Mijn broer heeft drie',
      after: ': twee jongens en een meisje.',
      hint: 'meervoud van kind',
      answer: 'kinderen',
      why: 'kind krijgt -eren: kinderen. Net als ei, eieren en lied, liederen.',
    },
    {
      kind: 'bet',
      id: 'steden',
      prompt: 'Wat is het meervoud van ‘stad’?',
      options: ['steden', 'stadden', 'staden'],
      answer: 'steden',
      why: 'stad is een uitzondering: de klank wordt lang én verandert. Eén stad, twee steden. Zo ook schip, schepen.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Uitzonderingen en valkuilen',
      panels: [
        {
          text: 'Na een korte klank verdubbel je meestal: *kat*, *katten*. Maar een groepje veelgebruikte woorden krijgt in het meervoud een lange klank, en dan verdubbel je dus niet: *dag*, *dagen*; *dak*, *daken*; *glas*, *glazen*; *weg*, *wegen*; *gat*, *gaten*; *bad*, *baden*; *slot*, *sloten*; *spel*, *spelen*; *god*, *goden*; *verbod*, *verboden*. Bij een paar verandert de klinker ook: *schip*, *schepen*; *stad*, *steden*; *lid*, *leden*. Deze woorden moet je leren.',
          rule: 'Leerwoorden met een lange klank in het meervoud: *dagen*, *glazen*, *wegen*, *schepen*, *steden*.',
          paradigm: {
            q: 'Zet het goede meervoud in het vakje',
            cols: ['meervoud'],
            rows: [
              { label: 'de dag', cells: [{ fill: 'dagen', hint: 'Lange a: da-gen.' }] },
              { label: 'het glas', cells: [{ fill: 'glazen', hint: 'Lange a, en de s wordt z.' }] },
              { label: 'het schip', cells: [{ fill: 'schepen', hint: 'De i wordt een lange e.' }] },
              { label: 'de weg', cells: [{ fill: 'wegen', hint: 'Lange e: we-gen.' }] },
              { label: 'het lid', cells: [{ fill: 'leden', hint: 'De i wordt een lange e.' }] },
              { label: 'de kat', cells: [{ fill: 'katten', hint: 'Deze blijft kort: verdubbelen.' }] },
            ],
            extra: ['daggen', 'glassen', 'schippen', 'weggen', 'katen'],
            note: 'Vijf leerwoorden met een lange klank, en kat als gewoon woord: katten.',
          },
        },
        {
          text: 'Een paar woorden krijgen *-eren*: *kind*, *kinderen*; *ei*, *eieren*; *lied*, *liederen*; *kalf*, *kalveren*; *lam*, *lammeren*; *rund*, *runderen*. En een paar krijgen *-ien*: *koe*, *koeien*; *vlo*, *vlooien*. Ook dat zijn leerwoorden.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'kind', out: 'kinderen', note: 'Niet kinden of kinds.' },
              { k: 'ei', out: 'eieren', note: 'Niet eien of eiren.' },
              { k: 'lied', out: 'liederen', note: 'Het koor zingt liederen.' },
              { k: 'kalf', out: 'kalveren', note: 'De f wordt een v, net als in golf, golven.' },
              { k: 'koe', out: 'koeien', note: 'Er komt -ien achter: koeien.' },
            ],
          },
          quiz: {
            q: 'Wat is het meervoud van ‘lam’?',
            options: ['lammeren', 'lammen', 'lams'],
            answer: 'lammeren',
            why: 'lam hoort bij de -eren-groep: lammeren. Korte a, dus ook mm.',
          },
        },
        {
          text: 'Let in het meervoud op de s en de f. Hoor je een z of een v, dan schrijf je die ook: *huis*, *huizen*; *reis*, *reizen*; *prijs*, *prijzen*; *brief*, *brieven*; *golf*, *golven*. Hoor je een s of f, dan blijft het een s of f: *kous*, *kousen*; *mens*, *mensen*; *straf*, *straffen*. Na een korte klank wordt het *ss* of *ff*: *vis*, *vissen*; *bus*, *bussen*.',
          rule: 'Hoor je in het meervoud een z of v? Schrijf z of v. Hoor je s of f? Schrijf s of f.',
          quiz: {
            q: 'Wat is het meervoud van ‘brief’?',
            options: ['brieven', 'briefen', 'brievs'],
            answer: 'brieven',
            why: 'Je hoort een v in het meervoud: brieven.',
          },
        },
        {
          text: 'Woorden op *ee* en *ie* met klemtoon krijgen *-ën*, met een trema: *zee*, *zeeën*; *idee*, *ideeën*; *knie*, *knieën*; *melodie*, *melodieën*. Bij *-ie* zonder klemtoon wordt het *-iën*: *bacterie*, *bacteriën*. Let op: een paar woorden op *-ie* zonder klemtoon krijgen gewoon *-s*: *familie*, *families*. Het trema laat zien waar de nieuwe lettergreep begint.',
          rule: '*ee* en *ie* met klemtoon: *-eeën*, *-ieën*. *-ie* zonder klemtoon: *-iën*.',
          quiz: {
            q: 'Wat is het meervoud van ‘knie’?',
            options: ['knieën', 'kniën', 'knies'],
            answer: 'knieën',
            why: 'knie heeft de klemtoon op ie. Dus ie + ën: knieën.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'kort-of-lang',
      prompt: 'Wat gebeurt er met de korte klank in het meervoud?',
      buckets: ['wordt lang (dagen)', 'blijft kort (katten)'],
      items: [
        { t: 'dag', b: 0 },
        { t: 'kat', b: 1 },
        { t: 'schip', b: 0 },
        { t: 'pit', b: 1 },
        { t: 'weg', b: 0 },
        { t: 'bed', b: 1 },
        { t: 'glas', b: 0 },
        { t: 'bal', b: 1 },
        { t: 'slot', b: 0 },
        { t: 'pot', b: 1 },
        { t: 'spel', b: 0 },
        { t: 'bel', b: 1 },
      ],
      why: 'Leerwoorden met een lange klank: dagen, schepen, wegen, glazen, sloten, spelen. Gewone woorden die kort blijven en verdubbelen: katten, pitten, bedden, ballen, potten, bellen.',
    },
    {
      kind: 'proofread',
      id: 'boodschappen',
      prompt: 'Lees de boodschappenlijst voor het feest. Tik elke fout aan en verbeter hem.',
      intro: 'Er staan vijf fouten in het meervoud.',
      tokens: [
        { t: 'Voor' },
        { t: 'zaterdag:' },
        { t: 'tien' },
        { t: 'eiren,', fix: 'eieren,', why: 'ei krijgt -eren: eieren.' },
        { t: 'twee' },
        { t: 'kaasen,', fix: 'kazen,', why: 'ka-zen: één a in een open lettergreep, en je hoort een z.' },
        { t: 'vijf' },
        { t: 'pizzas,', fix: 'pizza’s,', why: 'Na een a komt ’s: pizza’s.' },
        { t: 'drie' },
        { t: 'taarten,' },
        { t: 'twintig' },
        { t: 'bekers,' },
        { t: 'servetten,' },
        { t: 'tomaaten', fix: 'tomaten', why: 'to-ma-ten: open lettergreep, één a.' },
        { t: 'en' },
        { t: 'vier' },
        { t: 'flessen' },
        { t: 'sap.' },
        { t: 'Vergeet' },
        { t: 'de' },
        { t: 'cadeau’s', fix: 'cadeaus', why: 'Na eau alleen -s, zonder apostrof.' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'kinderen' },
        { t: 'niet!' },
      ],
      done: { title: 'Lijst klopt', text: 'eieren, kazen, pizza’s, tomaten en cadeaus. En bekers, servetten en flessen waren al goed.' },
    },
    {
      kind: 'dictation',
      id: 'steden-cadeaus',
      prompt: 'Luister en typ de zin.',
      sentence: 'De kinderen kochten in twee steden cadeaus voor hun ooms en tantes.',
      right: 'Goed: kinderen (-eren), steden (leerwoord), cadeaus (na eau alleen -s), ooms (-s) en tantes (doffe e: -s).',
      wrong: 'Let op: kinderen, steden, cadeaus zonder apostrof, ooms en tantes.',
    },
    {
      kind: 'swipe',
      id: 'zinnen',
      prompt: 'Is deze zin goed geschreven?',
      cards: [
        { t: 'Ik heb twee nieuwe ideeën voor het project.', ok: true, why: 'idee, ideeën: ee met klemtoon krijgt -ën met trema.' },
        { t: 'We hebben drie dagen vrij.', ok: true, why: 'dag hoort bij de leerwoorden: dagen, met een lange a.' },
        { t: 'De babys slapen allebei.', ok: false, fix: 'baby’s', why: 'Na een y komt ’s: baby’s.' },
        { t: 'In die straat zijn veel cafés.', ok: true, why: 'Na é alleen -s.' },
        { t: 'Mijn zoon heeft zijn knies bezeerd.', ok: false, fix: 'knieën', why: 'knie, knieën: ie met klemtoon krijgt -ën met trema.' },
        { t: 'Er stonden zes koeien in de wei.', ok: true, why: 'koe, koeien: een leerwoord.' },
        { t: 'We hebben twee nieuwe tafelen gekocht.', ok: false, fix: 'tafels', why: 'tafel eindigt op -el zonder klemtoon: tafels.' },
        { t: 'De schippen liggen in de haven.', ok: false, fix: 'schepen', why: 'schip, schepen: de klank wordt lang en verandert.' },
      ],
    },
    {
      kind: 'rewrite',
      id: 'meervoud-zin',
      prompt: 'Zet de zin in het meervoud.',
      source: 'Het kind eet een ei bij het ontbijt.',
      accept: ['De kinderen eten eieren bij het ontbijt.', 'De kinderen eten een ei bij het ontbijt.'],
      why: 'kind → kinderen, ei → eieren: allebei -eren. Het werkwoord wordt ook meervoud: eten.',
    },
    {
      kind: 'type',
      id: 'knieen',
      prompt: 'Typ het meervoud, met het goede teken.',
      before: 'Na het hardlopen doen mijn',
      after: 'pijn.',
      hint: 'meervoud van knie',
      answer: 'knieën',
      why: 'knie heeft de klemtoon op ie: knieën, met een trema op de laatste e.',
    },
    {
      kind: 'choice',
      id: 'liederen',
      prompt: 'Welk woord past?',
      before: 'Het koor zingt vanavond mooie',
      after: '.',
      options: ['liederen', 'lieden', 'lieds'],
      answer: 'liederen',
      why: 'lied krijgt -eren: liederen. Lieden is een ander woord (mensen).',
    },
    {
      kind: 'bet',
      id: 'bacterien',
      prompt: 'Een lastige: wat is het meervoud van ‘bacterie’?',
      intro: 'De klemtoon ligt op te: bac-TE-rie.',
      options: ['bacteriën', 'bacterieën', 'bacteries'],
      answer: 'bacteriën',
      why: 'Op de ie ligt geen klemtoon. Dan wordt het -iën: bacteriën. Met klemtoon op ie krijg je -ieën, zoals knieën.',
    },
    {
      kind: 'write',
      id: 'lijst',
      prompt: 'Schrijf een boodschappenlijst of een appje voor een etentje met vrienden.',
      intro: 'Gebruik verschillende soorten meervoud.',
      minWords: 20,
      must: [
        { label: 'Een meervoud op -en: eieren, glazen, tomaten of borden', hint: 'tien eieren', test: { anyWord: ['eieren', 'glazen', 'tomaten', 'borden', 'aardappelen', 'uien'] } },
        { label: 'Een meervoud op -s: lepels, bekers, appels of hapjes', hint: 'zes lepels', test: { anyWord: ['lepels', 'bekers', 'appels', 'hapjes', 'toetjes', 'komkommers'] } },
        { label: 'Een meervoud met ’s: pizza’s, menu’s of foto’s', hint: 'twee pizza’s', test: { pattern: "\\b(pizza|menu|foto|cola|tortilla|mango|avocado|kiwi)['’]s\\b", flags: 'i' } },
      ],
      avoid: [
        {
          test: { pattern: '\\b(eiren|glassen|tomaaten|kaasen|pizzas|cadeau[\'’]s|babys|fotos|menus)\\b', flags: 'i' },
          tip: 'Kijk nog eens naar dit meervoud. Welke regel hoort erbij?',
        },
      ],
      why: 'Drie soorten meervoud in één lijst: -en, -s en ’s.',
    },
  ],
};
