import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": het meervoud met -en, -s of ’s, en de woorden die anders gaan. */
export const LES_G23: LessonInput = {
  id: 'g23',
  stage: 'regels',
  domain: 'morf',
  also: ['orth'],
  title: 'Meervoud: -en, -s of ’s?',
  skill: 'Spelling',
  icon: '-en',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Drie manieren om meer te maken',
      panels: [
        {
          text: 'De meeste woorden krijgen in het meervoud *-en*: *boek*, *boeken*; *deur*, *deuren*; *trein*, *treinen*. Als je *-en* toevoegt, gelden meteen de regels van de lettergreep. Een lange klank wordt één letter: *boot*, *bo-ten*. Na een korte klank verdubbel je: *ster*, *ster-ren*; *vis*, *vis-sen*. En een s of f kan een z of v worden: *huis*, *hui-zen*. Probeer het met de voorwerpen.',
          rule: 'Basisregel: meervoud met *-en*, en dan de regels van open en gesloten lettergrepen.',
          morph: {
            q: 'Kies het goede meervoud, en zie het voorwerp vermenigvuldigen',
            rounds: [
              { thing: 'boek', from: 'het boek', ask: 'veel boeken', effect: 'veel', options: ['boeken', 'boeks', 'boekken'], answer: 'boeken', note: 'Gewoon -en. De oe blijft altijd oe.' },
              { thing: 'boot', from: 'de boot', ask: 'veel boten', effect: 'veel', options: ['booten', 'boten', 'botten'], answer: 'boten', note: 'bo-ten: open lettergreep, dus één o.' },
              { thing: 'ster', from: 'de ster', ask: 'veel sterren', effect: 'veel', options: ['steren', 'sterren', 'sters'], answer: 'sterren', note: 'Korte e + r: verdubbelen, ster-ren.' },
              { thing: 'vis', from: 'de vis', ask: 'veel vissen', effect: 'veel', options: ['vissen', 'visen', 'vizen'], answer: 'vissen', note: 'Korte i: de s wordt dubbel. Je hoort een s, dus geen z.' },
              { thing: 'huis', from: 'het huis', ask: 'veel huizen', effect: 'veel', options: ['huisen', 'huizen', 'huissen'], answer: 'huizen', note: 'Je hoort in het meervoud een z: huizen. Na ui verdubbel je nooit.' },
              { thing: 'ei', from: 'het ei', ask: 'veel eieren', effect: 'veel', options: ['eien', 'eieren', 'eis'], answer: 'eieren', note: 'Een uitzondering: ei krijgt -eren. Dat moet je leren.' },
            ],
            note: 'Vijf keer -en met de lettergreepregels, en één uitzondering: eieren.',
          },
        },
        {
          text: 'Woorden die eindigen op *-el*, *-em*, *-en* of *-er* zonder klemtoon, krijgen *-s*: *tafel*, *tafels*; *bezem*, *bezems*; *jongen*, *jongens*; *kamer*, *kamers*. Ook woorden op *-je*: *meisje*, *meisjes*; *huisje*, *huisjes*. Hoor je in de laatste lettergreep een doffe e? Dan is het bijna altijd *-s*. Ligt de klemtoon op het eind, dan krijg je wel *-en*: *kasteel*, *kastelen*.',
          rule: 'Doffe e in de laatste lettergreep (*-el*, *-em*, *-en*, *-er*) of *-je*: meervoud met *-s*.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'tafel', out: 'tafels', note: 'ta-fel: de laatste lettergreep heeft een doffe e. Dus -s.' },
              { k: 'jongen', out: 'jongens', note: 'jon-gen: doffe e. Niet jongenen, maar jongens.' },
              { k: 'kamer', out: 'kamers', note: 'ka-mer: doffe e, dus -s.' },
              { k: 'meisje', out: 'meisjes', note: 'Een verkleinwoord op -je krijgt altijd -s.' },
              { k: 'kasteel', out: 'kastelen', note: 'De klemtoon ligt op teel, en de ee is lang: -en.' },
            ],
          },
        },
        {
          text: 'Eindigt een woord op *a*, *i*, *o*, *u* of *y*, dan krijgt het *’s*: *auto’s*, *ski’s*, *menu’s*, *baby’s*, *pagina’s*, *foto’s*. De apostrof houdt de klinker lang. Zonder apostrof lees je *autos* met een korte o. Eindigt het woord op *é* of *eau*, dan is de klank al duidelijk en zet je alleen *-s*: *café*, *cafés*; *cadeau*, *cadeaus*; *bureau*, *bureaus*. En een doffe e aan het eind krijgt ook gewoon *-s*: *tante*, *tantes*; *garage*, *garages*.',
          rule: '*a*, *i*, *o*, *u*, *y* aan het eind: *’s* (*auto’s*). *é*, *eau* en doffe e: *-s* (*cafés*, *cadeaus*, *tantes*).',
          quiz: {
            q: 'Wat is het meervoud van ‘cadeau’?',
            options: ['cadeaus', 'cadeau’s', 'cadeauen'],
            answer: 'cadeaus',
            why: 'Na eau is de klank al duidelijk, ook met een s erachter. Dus geen apostrof: cadeaus.',
          },
          deep: {
            q: 'En bij een woord op ee of ie?',
            a: 'Dan krijg je *-en* met een trema: *zee*, *zeeën*; *idee*, *ideeën*; *knie*, *knieën*. Bij een *-ie* zonder klemtoon wordt het vaak *-iën*: *bacterie*, *bacteriën*. Je ziet dat in de valkuilen.',
          },
        },
        {
          text: 'Twijfel je? Volg dit stappenplan. Stap 1: eindigt het woord op *-el*, *-em*, *-en*, *-er* of *-je* zonder klemtoon? Dan meestal *-s*. Stap 2: eindigt het op *a*, *i*, *o*, *u* of *y*? Dan *’s*. Stap 3: eindigt het op *é*, *eau* of een doffe e? Dan *-s*. Stap 4: in de andere gevallen meestal *-en*, en dan let je op één letter of twee, op verdubbelen en op z en v.',
          rule: '-el, -em, -en, -er, -je: meestal *-s*. Klinker a, i, o, u, y: *’s*. Anders meestal *-en*.',
          mark: {
            q: 'Tik de woorden die in het meervoud alleen -s krijgen (zonder apostrof)',
            sentence: 'lepel trein oma deken boom café oven kast',
            targets: [0, 3, 5, 6],
            note: 'lepels, dekens, ovens: doffe e. cafés: na é alleen -s. treinen, bomen en kasten krijgen -en. oma krijgt ’s: oma’s.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'welk-meervoud',
      prompt: 'Welk meervoud krijgt dit woord?',
      buckets: ['-en', '-s', '’s'],
      items: [
        { t: 'kasteel', b: 0 },
        { t: 'familie', b: 1 },
        { t: 'collega', b: 2 },
        { t: 'idee', b: 0 },
        { t: 'bureau', b: 1 },
        { t: 'paraplu', b: 2 },
        { t: 'bacterie', b: 0 },
        { t: 'garage', b: 1 },
        { t: 'hobby', b: 2 },
        { t: 'formulier', b: 0 },
        { t: 'deken', b: 1 },
        { t: 'risico', b: 2 },
        { t: 'wandeling', b: 0 },
        { t: 'vakantie', b: 1 },
        { t: 'agenda', b: 2 },
      ],
      why: '-en: kastelen, ideeën, bacteriën, formulieren, wandelingen. Ook met een trema is het -en. -s: families, bureaus, garages, dekens, vakanties (vakantie gaat net als familie). ’s: collega’s, paraplu’s, hobby’s, risico’s, agenda’s.',
    },
    {
      kind: 'type',
      id: 'leden',
      prompt: 'Typ het meervoud van lid.',
      before: 'De sportclub heeft dit jaar dertig nieuwe',
      after: 'gekregen.',
      hint: '',
      answer: 'leden',
      why: 'lid is een leerwoord: de korte i wordt een lange e. Eén lid, twee leden. Net als schip, schepen.',
    },
    {
      kind: 'choice',
      id: 'cadeaus',
      prompt: 'Welke spelling is goed?',
      before: 'Voor het afscheid van onze collega hebben we drie',
      after: 'gekocht.',
      options: ['cadeau’s', 'cadeaus', 'kado’s', 'cadeauen'],
      answer: 'cadeaus',
      why: 'Na eau alleen -s, zonder apostrof: cadeaus. De eau houdt de klank al lang. kado is niet de officiële spelling: schrijf cadeau.',
    },
    {
      kind: 'fix',
      id: 'prijzen',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Volgens de gemeente zijn de prijsen van huurhuizen dit jaar weer gestegen.',
      wrong: 5,
      answer: 'prijzen',
      why: 'Je hoort in het meervoud een z: prijzen. huurhuizen was al goed: huis, huizen.',
    },
    {
      kind: 'type',
      id: 'kalveren',
      prompt: 'Typ het meervoud van kalf.',
      before: 'Op de boerderij van mijn zwager zijn deze week drie',
      after: 'geboren.',
      hint: '',
      answer: 'kalveren',
      why: 'kalf krijgt -eren, en de f wordt een v, want die hoor je: kalveren. Twee regels in één woord.',
    },
    {
      kind: 'bet',
      id: 'steden',
      prompt: 'Wat is het meervoud van ‘stad’?',
      options: ['staden', 'steden', 'stadden', 'steeden'],
      answer: 'steden',
      why: 'stad is een leerwoord: de klank wordt lang én verandert. Eén stad, twee steden. In ste-den is de lettergreep open, dus één e. Zo ook schip, schepen.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Uitzonderingen en valkuilen',
      panels: [
        {
          text: 'Na een korte klank verdubbel je meestal: *kat*, *katten*. Maar een groepje veelgebruikte woorden krijgt in het meervoud een lange klank, en dan verdubbel je dus niet: *dag*, *dagen*; *dak*, *daken*; *glas*, *glazen*; *weg*, *wegen*; *gat*, *gaten*; *bad*, *baden*; *slot*, *sloten*; *spel*, *spelen*; *god*, *goden*; *verbod*, *verboden*. Bij een paar verandert de klinker ook: *schip*, *schepen*; *stad*, *steden*; *lid*, *leden*. Deze woorden moet je leren.',
          rule: 'Leerwoorden met een lange klank in het meervoud: *dagen*, *glazen*, *wegen*, *schepen*, *steden*.',
          paradigm: {
            q: 'Zet het goede meervoud in het vakje',
            cols: ['meervoud'],
            rows: [
              { label: 'de dag', cells: [{ fill: 'dagen', hint: 'Lange a: da-gen.' }] },
              { label: 'het glas', cells: [{ fill: 'glazen', hint: 'Lange a, en de s wordt z.' }] },
              { label: 'het schip', cells: [{ fill: 'schepen', hint: 'De i wordt een lange e.' }] },
              { label: 'de weg', cells: [{ fill: 'wegen', hint: 'Lange e: we-gen.' }] },
              { label: 'het lid', cells: [{ fill: 'leden', hint: 'De i wordt een lange e.' }] },
              { label: 'de kat', cells: [{ fill: 'katten', hint: 'Deze blijft kort: verdubbelen.' }] },
            ],
            extra: ['daggen', 'glassen', 'schippen', 'weggen', 'katen'],
            note: 'Vijf leerwoorden met een lange klank, en kat als gewoon woord: katten.',
          },
        },
        {
          text: 'Een paar woorden krijgen *-eren*: *kind*, *kinderen*; *ei*, *eieren*; *lied*, *liederen*; *kalf*, *kalveren*; *lam*, *lammeren*; *rund*, *runderen*. En een paar krijgen *-ien*: *koe*, *koeien*; *vlo*, *vlooien*. Ook dat zijn leerwoorden.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'kind', out: 'kinderen', note: 'Niet kinden of kinds.' },
              { k: 'ei', out: 'eieren', note: 'Niet eien of eiren.' },
              { k: 'lied', out: 'liederen', note: 'Het koor zingt liederen.' },
              { k: 'kalf', out: 'kalveren', note: 'De f wordt een v, net als in golf, golven.' },
              { k: 'koe', out: 'koeien', note: 'Er komt -ien achter: koeien.' },
            ],
          },
          quiz: {
            q: 'Wat is het meervoud van ‘lam’?',
            options: ['lammeren', 'lammen', 'lams'],
            answer: 'lammeren',
            why: 'lam hoort bij de -eren-groep: lammeren. Korte a, dus ook mm.',
          },
        },
        {
          text: 'Let in het meervoud op de s en de f. Hoor je een z of een v, dan schrijf je die ook: *huis*, *huizen*; *reis*, *reizen*; *prijs*, *prijzen*; *brief*, *brieven*; *golf*, *golven*. Hoor je een s of f, dan blijft het een s of f: *kous*, *kousen*; *mens*, *mensen*; *straf*, *straffen*. Na een korte klank wordt het *ss* of *ff*: *vis*, *vissen*; *bus*, *bussen*.',
          rule: 'Hoor je in het meervoud een z of v? Schrijf z of v. Hoor je s of f? Schrijf s of f.',
          quiz: {
            q: 'Wat is het meervoud van ‘brief’?',
            options: ['brieven', 'briefen', 'brievs'],
            answer: 'brieven',
            why: 'Je hoort een v in het meervoud: brieven.',
          },
        },
        {
          text: 'Woorden op *ee* en *ie* met klemtoon krijgen *-ën*, met een trema: *zee*, *zeeën*; *idee*, *ideeën*; *knie*, *knieën*; *melodie*, *melodieën*. Bij *-ie* zonder klemtoon wordt het vaak *-iën*: *bacterie*, *bacteriën*. Let op: veel woorden op *-ie* zonder klemtoon krijgen gewoon *-s*: *familie*, *families*; *vakantie*, *vakanties*. Die moet je leren. Het trema laat zien waar de nieuwe lettergreep begint.',
          rule: '*ee* en *ie* met klemtoon: *-eeën*, *-ieën*. *-ie* zonder klemtoon: *-iën* (*bacteriën*) of *-s* (*families*).',
          quiz: {
            q: 'Wat is het meervoud van ‘knie’?',
            options: ['knieën', 'kniën', 'knies'],
            answer: 'knieën',
            why: 'knie heeft de klemtoon op ie. Dus ie + ën: knieën.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'kort-of-lang',
      prompt: 'Wat gebeurt er met de korte klank in het meervoud?',
      buckets: ['wordt lang (dagen)', 'blijft kort (katten)'],
      items: [
        { t: 'dak', b: 0 },
        { t: 'vak', b: 1 },
        { t: 'weg', b: 0 },
        { t: 'heg', b: 1 },
        { t: 'slot', b: 0 },
        { t: 'pot', b: 1 },
        { t: 'gat', b: 0 },
        { t: 'pit', b: 1 },
        { t: 'bevel', b: 0 },
        { t: 'bel', b: 1 },
        { t: 'gebrek', b: 0 },
        { t: 'vlek', b: 1 },
        { t: 'verbod', b: 0 },
        { t: 'stap', b: 1 },
        { t: 'bedrag', b: 0 },
        { t: 'slak', b: 1 },
        { t: 'lid', b: 0 },
      ],
      why: 'Leerwoorden met een lange klank: daken, wegen, sloten, gaten, bevelen, gebreken, verboden, bedragen, leden. Gewone woorden die kort blijven en verdubbelen: vakken, heggen, potten, pitten, bellen, vlekken, stappen, slakken. Let op de paren: dak, daken maar vak, vakken; bevel, bevelen maar bel, bellen.',
    },
    {
      kind: 'proofread',
      id: 'boodschappen',
      prompt: 'Lees de boodschappenlijst voor het feest. Tik elke fout aan en verbeter hem.',
      intro: 'Kijk bij elk meervoud: -en, -s of ’s? En klopt de rest van het woord?',
      tokens: [
        { t: 'Voor' },
        { t: 'zaterdag:' },
        { t: 'tien' },
        { t: 'eiren,', fix: 'eieren,', why: 'ei krijgt -eren: eieren.' },
        { t: 'twee' },
        { t: 'kaasen,', fix: 'kazen,', why: 'ka-zen: één a in een open lettergreep, en je hoort een z.' },
        { t: 'vijf' },
        { t: 'pizzas,', fix: 'pizza’s,', why: 'Na een a komt ’s: pizza’s.' },
        { t: 'drie' },
        { t: 'taarten,' },
        { t: 'twintig' },
        { t: 'bekers,' },
        { t: 'servetten,' },
        { t: 'tomaaten', fix: 'tomaten', why: 'to-ma-ten: open lettergreep, één a.' },
        { t: 'en' },
        { t: 'vier' },
        { t: 'flessen' },
        { t: 'sap.' },
        { t: 'Vergeet' },
        { t: 'de' },
        { t: 'cadeau’s', fix: 'cadeaus', why: 'Na eau alleen -s, zonder apostrof.' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'kinderen' },
        { t: 'niet!' },
      ],
      done: { title: 'Lijst klopt', text: 'eieren, kazen, pizza’s, tomaten en cadeaus. En bekers, servetten en flessen waren al goed.' },
    },
    {
      kind: 'dictation',
      id: 'steden-cadeaus',
      prompt: 'Luister en typ de zin.',
      sentence: 'Tijdens hun reizen kochten de kinderen in verschillende steden cadeaus voor hun tantes en foto’s van de schepen.',
      right: 'Goed: reizen (z), kinderen (-eren), steden (leerwoord), cadeaus (na eau alleen -s), tantes (doffe e: -s), foto’s (o: ’s) en schepen (leerwoord).',
      wrong: 'Let op: reizen met z, kinderen, steden, cadeaus zonder apostrof, tantes met -s, foto’s met apostrof en schepen met één e.',
    },
    {
      kind: 'swipe',
      id: 'zinnen',
      prompt: 'Is deze zin goed geschreven?',
      cards: [
        { t: 'Vier collega’s van mijn afdeling komen uit Polen.', ok: true, why: 'collega eindigt op a: ’s.' },
        {
          t: 'Er zijn ideëen genoeg, maar er is geen geld.',
          ok: false,
          fix: 'ideeën',
          why: 'idee + ën. Het trema staat op de e waar de nieuwe lettergreep begint: ideeën.',
        },
        { t: 'De nieuwe bureaus worden maandag geleverd.', ok: true, why: 'Na eau alleen -s, zonder apostrof.' },
        { t: 'De hobbies van de kinderen kosten veel geld.', ok: false, fix: 'hobby’s', why: 'hobby eindigt op y: ’s. Dus hobby’s, niet hobbies.' },
        { t: 'De dokter zegt dat het geen bacteriën zijn.', ok: true, why: 'bac-TE-rie: geen klemtoon op ie, dus -iën.' },
        {
          t: 'De gemeente heeft twee nieuwe verbodden ingevoerd.',
          ok: false,
          fix: 'verboden',
          why: 'verbod is een leerwoord: verboden, met een lange o en één d.',
        },
        { t: 'Alle families in de flat kregen een brief van de verhuurder.', ok: true, why: 'familie krijgt gewoon -s: families.' },
        {
          t: 'Op de boerderij lopen koeien, kalveren en lammen.',
          ok: false,
          fix: 'lammeren',
          why: 'lam krijgt -eren, net als kalf en kind: lammeren. Korte a, dus mm. koeien en kalveren waren goed.',
        },
        { t: 'De wegen rond het station zijn vanaf maandag dicht.', ok: true, why: 'weg is een leerwoord: wegen, met een lange e. Geen gg.' },
        { t: 'In de kast staan zes glassen en vier borden.', ok: false, fix: 'glazen', why: 'glas is een leerwoord: lange a in het meervoud, en je hoort een z. glazen.' },
        { t: 'We hebben de menu’s van drie cafés vergeleken.', ok: true, why: 'menu eindigt op u: ’s. café eindigt op é: alleen -s.' },
        { t: 'In Frankrijk hebben we vier oude kasteelen bezocht.', ok: false, fix: 'kastelen', why: 'kas-te-len: de lettergreep is open, dus één e.' },
      ],
    },
    {
      kind: 'rewrite',
      id: 'meervoud-zin',
      prompt: 'Zet het kind, het lam en het kalf in het meervoud. Het werkwoord verandert mee.',
      source: 'Het kind van mijn collega wil het lam en het kalf zien.',
      accept: ['De kinderen van mijn collega willen de lammeren en de kalveren zien.', 'De kinderen van mijn collega willen de lammeren en kalveren zien.'],
      why: 'kind → kinderen, lam → lammeren (korte a, dus mm), kalf → kalveren (f wordt v). Alle drie -eren. Het werkwoord wordt ook meervoud: willen.',
    },
    {
      kind: 'type',
      id: 'knieen',
      prompt: 'Typ het meervoud van knie.',
      before: 'Na het hardlopen doen mijn',
      after: 'pijn.',
      hint: '',
      answer: 'knieën',
      why: 'knie heeft de klemtoon op ie: knieën, met een trema op de laatste e.',
    },
    {
      kind: 'choice',
      id: 'vlooien',
      prompt: 'Welk woord past?',
      before: 'De hond van de buren zit vol',
      after: '.',
      options: ['vlo’s', 'vlooien', 'vlooën', 'vloën'],
      answer: 'vlooien',
      why: 'vlo is een leerwoord, net als koe, koeien: vlooien. De regel voor een o aan het eind (foto’s) geldt hier niet.',
    },
    {
      kind: 'bet',
      id: 'bacterien',
      prompt: 'Een lastige: wat is het meervoud van ‘bacterie’?',
      intro: 'De klemtoon ligt op te: bac-TE-rie.',
      options: ['bacterieën', 'bacteriën', 'bacteries', 'bacterien'],
      answer: 'bacteriën',
      why: 'Op de ie ligt geen klemtoon. Dan wordt het -iën: bacteriën. Met klemtoon op ie krijg je -ieën, zoals knieën.',
    },
    {
      kind: 'write',
      id: 'lijst',
      prompt: 'Schrijf een boodschappenlijst of een appje voor een etentje met vrienden.',
      intro: 'Gebruik verschillende soorten meervoud.',
      minWords: 20,
      must: [
        { label: 'Een meervoud op -en: eieren, glazen, tomaten of borden', hint: 'tien eieren', test: { anyWord: ['eieren', 'glazen', 'tomaten', 'borden', 'aardappelen', 'uien'] } },
        { label: 'Een meervoud op -s: lepels, bekers, appels of hapjes', hint: 'zes lepels', test: { anyWord: ['lepels', 'bekers', 'appels', 'hapjes', 'toetjes', 'komkommers'] } },
        { label: 'Een meervoud met ’s: pizza’s, menu’s of foto’s', hint: 'twee pizza’s', test: { pattern: "\\b(pizza|menu|foto|cola|tortilla|mango|avocado|kiwi)['’]s\\b", flags: 'i' } },
      ],
      avoid: [
        {
          test: { pattern: '\\b(eiren|glassen|tomaaten|kaasen|pizzas|cadeau[\'’]s|babys|fotos|menus)\\b', flags: 'i' },
          tip: 'Kijk nog eens naar dit meervoud. Welke regel hoort erbij?',
        },
      ],
      why: 'Drie soorten meervoud in één lijst: -en, -s en ’s.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Meervouden en woorden uit eerdere lessen door elkaar. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Meervoud van *het gat*',
          before: 'Door de vorst zitten er grote',
          after: 'in de weg.',
          a: 'gaten',
          why: 'gat is een leerwoord: gaten, met een lange a.',
        },
        {
          q: 'Zelfstandig naamwoord bij *gezond*',
          before: 'Roken is slecht voor je',
          after: '.',
          a: 'gezondheid',
          why: 'gezond + heid. De d blijft (gezonde), en -heid schrijf je altijd met ei.',
        },
        {
          q: 'Meervoud van *het verbod*',
          before: 'In het park gelden twee',
          after: ': niet roken en geen glas.',
          a: 'verboden',
          why: 'verbod is een leerwoord: verboden, met een lange o.',
        },
        {
          q: 'Meervoud van *de collega*',
          before: 'Ik heb het nieuwe rooster naar alle',
          after: 'gestuurd.',
          a: 'collega’s',
          also: ['collegae'],
          why: 'collega eindigt op a: ’s. (collegae mag ook, maar collega’s is gewoner.)',
        },
        {
          q: 'Meervoud van *het lam*',
          before: 'In het voorjaar worden er op de boerderij veel',
          after: 'geboren.',
          a: 'lammeren',
          why: 'lam krijgt -eren, en na de korte a wordt de m dubbel: lammeren.',
        },
        {
          q: 'Eén woord voor *elke dag*',
          before: 'De bus rijdt',
          after: 'om de tien minuten.',
          a: 'dagelijks',
          why: 'dag + -lijks. -lijks schrijf je altijd met ij.',
        },
        {
          q: 'Meervoud van *het bureau*',
          before: 'Op de nieuwe afdeling staan twaalf',
          after: 'met een laptop.',
          a: 'bureaus',
          why: 'Na eau alleen -s, zonder apostrof.',
        },
        {
          q: 'Meervoud van *de zee*',
          before: 'Als matroos heeft hij over alle',
          after: 'van de wereld gevaren.',
          a: 'zeeën',
          why: 'zee + ën: zeeën, met een trema op de laatste e.',
        },
        {
          q: 'Vorm van *liggen*',
          before: 'Het pakket',
          after: 'al twee dagen bij de buren. Kun jij het vandaag ophalen?',
          a: 'ligt',
          why: 'liggen: stam lig, en bij het pakket komt er een t bij. Geen cht.',
        },
        {
          q: 'Meervoud van *de categorie*',
          before: 'Het formulier heeft vier',
          after: ': wonen, werk, zorg en vrije tijd.',
          a: 'categorieën',
          why: 'ca-te-go-RIE: klemtoon op ie, dus -ieën met een trema.',
        },
        { q: 'Meervoud van *de golf*', before: 'Door de storm waren de', after: 'op zee meters hoog.', a: 'golven', why: 'Je hoort een v: golven.' },
        {
          q: 'Verleden tijd van *verhuizen*',
          before: 'Vorig jaar',
          after: 'we naar Utrecht.',
          a: 'verhuisden',
          why: 'verhuizen heeft een z: dan -de of -den. De stam is verhuis: verhuisden.',
        },
        { q: 'Meervoud van *de brief*', before: 'De gemeente stuurt alle', after: 'voortaan per mail.', a: 'brieven', why: 'Je hoort een v: brieven.' },
        {
          q: 'Meervoud van *de straf*',
          before: 'De rechter gaf beide mannen zware',
          after: '.',
          a: 'straffen',
          why: 'Je hoort een f, en de a is kort: straffen.',
        },
        { q: 'De fiets is van Anna', before: 'Dat is', after: 'fiets.', a: 'Anna’s', why: 'Een naam op a krijgt ’s: Anna’s fiets.' },
        { q: 'Meervoud van *de koe*', before: 'De boer melkt zijn', after: 'twee keer per dag.', a: 'koeien', why: 'koe is een leerwoord: koeien.' },
        {
          q: 'Meervoud van *het schip*',
          before: 'In de haven van Rotterdam liggen grote',
          after: '.',
          a: 'schepen',
          why: 'schip is een leerwoord: de i wordt een lange e. schepen.',
        },
        {
          q: 'Het land met de steden Gent en Antwerpen',
          before: 'Mijn schoonfamilie woont in',
          after: '.',
          a: 'België',
          why: 'Bel-gi-ë: het trema laat zien dat de ë een nieuwe lettergreep begint.',
        },
        { q: 'Meervoud van *de pagina*', before: 'Het huurcontract telt twaalf', after: '.', a: 'pagina’s', why: 'pagina eindigt op a: ’s.' },
        {
          q: 'Meervoud van *de garage*',
          before: 'Achter de flat staan tien',
          after: 'voor de bewoners.',
          a: 'garages',
          why: 'garage eindigt op een doffe e: alleen -s.',
        },
        {
          q: 'Wie niet liegt en niet vals speelt, is …',
          before: 'Wees altijd',
          after: 'tegen je werkgever.',
          a: 'eerlijk',
          why: 'Je hoort ‘luhk’ aan het eind: -lijk, met ij.',
        },
        {
          q: 'Meervoud van *het probleem*',
          before: 'We hebben de',
          after: 'met de verwarming al twee keer gemeld.',
          a: 'problemen',
          why: 'pro-ble-men: open lettergreep, dus één e.',
        },
        {
          q: 'Meervoud van *de vriendin*',
          before: 'Ze gaat zaterdag uit met twee',
          after: '.',
          a: 'vriendinnen',
          why: '-in heeft de klemtoon en een korte i: de n wordt dubbel. vriendinnen.',
        },
        {
          q: 'Meervoud van *het bedrag*',
          before: 'Alle',
          after: 'op deze rekening zijn inclusief btw.',
          a: 'bedragen',
          why: 'bedrag is een leerwoord: bedragen, met een lange a.',
        },
        {
          q: 'Het tegenovergestelde van *warm*',
          before: 'Zet de verwarming hoger, want het is hier',
          after: '.',
          a: 'koud',
          why: 'koude, dus d. En voor een d staat bijna altijd ou.',
        },
        {
          q: 'Meervoud van *het gebrek*',
          before: 'Bij de keuring vonden ze drie kleine',
          after: 'aan de auto.',
          a: 'gebreken',
          why: 'gebrek is een leerwoord: gebreken, met een lange e.',
        },
      ],
      done: { title: 'Reeks klaar', text: 'Elke keer dezelfde vraag: welke regel geldt hier? Meervoud, d of t, ei of ij, trema of apostrof.' },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de brief van de gemeente aan. Typ elk woord helemaal.',
      intro: 'Kijk goed naar de zin om het gat heen. In het grijs staat soms een hint.',
      title: 'Brief van de gemeente: werk aan de weg',
      text: 'Beste bewoners,\n\nVanaf maandag vernieuwen we de {wegen|meervoud van weg|weg is een leerwoord: wegen, met een lange e. Geen gg.} en de stoepen in uw wijk. Het werk duurt ongeveer zes {weken|meervoud van week|we-ken: open lettergreep, dus één e.}. In die tijd kunt u uw {auto’s|meervoud van auto|auto eindigt op o: ’s.} niet voor de deur parkeren. U kunt ze wel in de {garages|meervoud van garage|garage eindigt op een doffe e: alleen -s, zonder apostrof.} achter de flat zetten. De bushalte bij de school staat tijdelijk aan de andere kant van de straat.\n\nOp de bouwplaats gelden twee {verboden|meervoud van verbod|verbod is een leerwoord: verboden, met een lange o.}: niet roken en geen {kinderen|meervoud van kind|kind krijgt -eren: kinderen.} bij de machines. Dat is voor ieders {veiligheid|van veilig|veilig met -ig, en -heid altijd met ei.}. Het afval halen we in deze periode {dagelijks|elke dag|-lijks schrijf je altijd met ij.} op.\n\nDe {terrassen|meervoud van terras|ter-ras: korte a + s, dus ss: terrassen.} van de {cafés|meervoud van café|Na é alleen -s, zonder apostrof.} op het plein blijven gewoon open. Na afloop krijgt de wijk {nieuwe|niet oud|ie + w schrijf je als ieuw: nieuwe.} lantaarnpalen.\n\nHeeft u vragen of {ideeën|meervoud van idee|idee heeft de klemtoon op ee: ideeën, met een trema.}? Onze {collega’s~collegae|meervoud van collega|collega eindigt op a: ’s. collegae mag ook.} geven u graag meer {informatie|info, voluit|Je hoort tsie: schrijf -tie.}. Alvast bedankt voor uw {geduld|rustig kunnen wachten|geduldig, dus d.}.\n\nMet {vriendelijke~hartelijke|aardig|vrienden, dus d. En ‘luhk’ schrijf je -lijk, met ij. hartelijke is ook goed.} groet,\n\nTeam Openbare Ruimte\nGemeente Zwolle',
      why: 'Meervoud: wegen, weken, verboden en kinderen met -en of -eren, garages en cafés met -s, auto’s en collega’s met ’s, ideeën met een trema. Uit eerdere lessen: veiligheid en dagelijks (ei en ij), nieuwe (ieuw), informatie (-tie), geduld en vriendelijke (langer maken: d).',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen over een uitje met het werk. Hoofdletters en leestekens tellen mee.',
      title: 'Een dag in Rotterdam',
      sentences: [
        'Vorige week gingen alle collega’s van onze afdeling met de bus naar Rotterdam.',
        'We bekeken de grote schepen in de haven en maakten veel foto’s.',
        'Daarna liepen we langs de cafés en de oude huizen aan de kade.',
        'In een restaurant bestelden we pizza’s, salades en grote glazen limonade.',
        'Onze teamleider had cadeaus voor iedereen en vertelde over de ideeën voor volgend jaar.',
        'Op de terugweg in de bus zongen we samen oude liederen.',
      ],
      right:
        'Alles goed. collega’s, foto’s en pizza’s met ’s; cafés en cadeaus met alleen -s; schepen, glazen en liederen als leerwoorden; ideeën met een trema.',
      wrong:
        'Kijk de meervouden na. Na a, o, u, i en y: ’s (collega’s, foto’s, pizza’s). Na é en eau: alleen -s (cafés, cadeaus). Leerwoorden: schepen, glazen, liederen. En ideeën met een trema.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail aan de verhuurder na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'meneer De Vries (verhuurder)', subject: 'Schade na de storm' },
      greeting: 'Beste meneer De Vries,',
      signoff: 'Met vriendelijke groet,\nYusuf Kaya',
      tokens: [
        { t: 'Sinds' },
        { t: 'de' },
        { t: 'storm' },
        { t: 'van' },
        { t: 'vorige' },
        { t: 'week' },
        { t: 'hebben' },
        { t: 'we' },
        { t: 'een' },
        { t: 'paar' },
        { t: 'probleemen', fix: 'problemen', why: 'pro-ble-men: open lettergreep, dus één e.' },
        { t: 'in' },
        { t: 'de' },
        { t: 'woning.' },
        { t: 'Twee' },
        { t: 'ramen', trap: 'Goed: raam, ra-men. Open lettergreep, dus één a.' },
        { t: 'in' },
        { t: 'de' },
        { t: 'slaapkameren', fix: 'slaapkamers', why: 'kamer eindigt op -er zonder klemtoon: slaapkamers.' },
        { t: 'sluiten' },
        { t: 'niet' },
        { t: 'meer' },
        { t: 'goed,' },
        { t: 'en' },
        { t: 'op' },
        { t: 'het' },
        { t: 'dak' },
        { t: 'zijn' },
        { t: 'drie' },
        { t: 'dakpannen', trap: 'Goed: pan heeft een korte a, dus de n wordt dubbel. dakpannen.' },
        { t: 'kapot.' },
        { t: 'Het' },
        { t: 'is' },
        { t: 'daardoor' },
        { t: 'erg' },
        { t: 'kout', fix: 'koud', why: 'koude, dus d.' },
        { t: 'in' },
        { t: 'huis.' },
        { t: 'Op' },
        { t: 'de' },
        { t: 'muren' },
        { t: 'in' },
        { t: 'de' },
        { t: 'gang' },
        { t: 'zitten' },
        { t: 'nu' },
        { t: 'zwarte' },
        { t: 'vleken.', fix: 'vlekken.', why: 'vlek is een gewoon woord: korte e, dus kk. vlekken.' },
        { t: 'Ook' },
        { t: 'de' },
        { t: 'deuren' },
        { t: 'van' },
        { t: 'de' },
        { t: 'garage’s', fix: 'garages', why: 'garage eindigt op een doffe e: alleen -s, zonder apostrof.' },
        { t: 'achter' },
        { t: 'de' },
        { t: 'flat' },
        { t: 'gaan' },
        { t: 'niet' },
        { t: 'meer' },
        { t: 'open.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'fotos', fix: 'foto’s', why: 'foto eindigt op o: ’s. Zonder apostrof lees je een korte o.' },
        { t: 'van' },
        { t: 'de' },
        { t: 'schade' },
        { t: 'en' },
        { t: 'de' },
        { t: 'bedraggen', fix: 'bedragen', why: 'bedrag is een leerwoord: bedragen, met een lange a.' },
        { t: 'van' },
        { t: 'de' },
        { t: 'rekeningen' },
        { t: 'bijgevoegt.', fix: 'bijgevoegd.', why: 'voegen, voegde: geen ’t kofschip, dus bijgevoegd met d.' },
        { t: 'Kan' },
        { t: 'er' },
        { t: 'deze' },
        { t: 'week' },
        { t: 'iemand' },
        { t: 'langskomen?' },
        { t: 'Wij' },
        { t: 'zijn' },
        { t: 'dagelijks', trap: 'Goed: -lijks schrijf je altijd met ij.' },
        { t: 'thuis' },
        { t: 'vanaf' },
        { t: 'drie' },
        { t: 'uur.' },
        { t: 'Als' },
        { t: 'u' },
        { t: 'andere' },
        { t: 'ideeën', trap: 'Goed: idee heeft de klemtoon op ee, dus ideeën met een trema.' },
        { t: 'heeft,' },
        { t: 'hoor' },
        { t: 'ik' },
        { t: 'het' },
        { t: 'graag.' },
      ],
      done: {
        title: 'Mail nagekeken',
        text: 'De fouten: problemen, slaapkamers, koud, vlekken, garages, foto’s, bedragen en bijgevoegd. ramen, dakpannen, dagelijks en ideeën waren goed.',
      },
    },
  ],
};
