import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": verkleinwoorden met -je, -tje, -pje, -etje en -kje, en de woorden die anders gaan. */
export const LES_G24: LessonInput = {
  id: 'g24',
  stage: 'regels',
  domain: 'morf',
  also: ['orth'],
  title: 'Verkleinwoorden: -je, -tje, -pje of -etje?',
  skill: 'Spelling',
  icon: '-tje',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Klein maken: welke uitgang?',
      panels: [
        {
          text: 'Een verkleinwoord maak je met *-je* of een vorm daarvan. Welke vorm je kiest, hangt af van het eind van het woord. De basis is *-je*. Die gebruik je na *p*, *t*, *k*, *f*, *s*, *ch* en *d*: *kopje*, *kastje*, *boekje*, *hofje*, *huisje*, *lachje*, *hoedje*. Belangrijk: een verkleinwoord is altijd een het-woord. *De kast* wordt *het kastje*.',
          rule: 'Na *p*, *t*, *k*, *f*, *s*, *ch* en *d*: *-je*. En een verkleinwoord is altijd een het-woord.',
          morph: {
            q: 'Kies het goede verkleinwoord, en zie het voorwerp krimpen',
            rounds: [
              { thing: 'boek', from: 'het boek', ask: 'een klein boek', effect: 'klein', options: ['een boekje', 'een boektje', 'een boekertje'], answer: 'een boekje', note: 'Na een k: -je.' },
              { thing: 'kast', from: 'de kast', ask: 'een kleine kast', effect: 'klein', options: ['het kastje', 'de kastje'], answer: 'het kastje', note: 'Na een t: -je. En kast is een de-woord, maar kastje is een het-woord.' },
              { thing: 'huis', from: 'het huis', ask: 'een klein huis', effect: 'klein', options: ['een huisje', 'een huizetje', 'een huistje'], answer: 'een huisje', note: 'Na een s: -je.' },
              { thing: 'vis', from: 'de vis', ask: 'een kleine vis', effect: 'klein', options: ['het visje', 'het vissetje', 'de visje'], answer: 'het visje', note: 'Na een s: -je, en het verkleinwoord is een het-woord.' },
              { thing: 'boot', from: 'de boot', ask: 'een kleine boot', effect: 'klein', options: ['een bootje', 'een boottje', 'een bootetje'], answer: 'een bootje', note: 'Na een t: -je. Geen extra t erbij.' },
              { thing: 'koek', from: 'de koek', ask: 'een kleine koek', effect: 'klein', options: ['een koekje', 'een koektje', 'een koekkie'], answer: 'een koekje', note: 'Na een k: -je. Koekkie hoor je wel, maar schrijf je niet.' },
            ],
            note: 'Zes keer -je, want elk woord eindigt op een t, k of s.',
          },
        },
        {
          text: 'Na een klinker of tweeklank komt *-tje*: *ei*, *eitje*; *koe*, *koetje*; *vrouw*, *vrouwtje*; *cadeau*, *cadeautje*. Ook na *l*, *n*, *r* en *w* als daar een lange klank, een tweeklank of een doffe e voor staat: *stoel*, *stoeltje*; *tuin*, *tuintje*; *deur*, *deurtje*; *schoen*, *schoentje*; *tafel*, *tafeltje*; *keuken*, *keukentje*; *kamer*, *kamertje*.',
          rule: 'Na een klinker of tweeklank, en na *l*, *n*, *r*, *w* met een lange klank of doffe e ervoor: *-tje*.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'ei', out: 'eitje', note: 'Tweeklank aan het eind: -tje.' },
              { k: 'stoel', out: 'stoeltje', note: 'oe is lang, daarna een l: -tje.' },
              { k: 'tuin', out: 'tuintje', note: 'ui is een tweeklank, daarna een n: -tje.' },
              { k: 'deur', out: 'deurtje', note: 'eu is lang, daarna een r: -tje.' },
              { k: 'tafel', out: 'tafeltje', note: 'Doffe e + l: -tje.' },
              { k: 'vrouw', out: 'vrouwtje', note: 'Na ouw: -tje.' },
            ],
          },
        },
        {
          text: 'Na een *m* komt *-pje*, als er een lange klank, een tweeklank of een doffe e voor staat: *boom*, *boompje*; *raam*, *raampje*; *duim*, *duimpje*; *bezem*, *bezempje*. Ook na *lm* en *rm*: *film*, *filmpje*; *arm*, *armpje*. Je hoort de p ook echt als je het zegt.',
          rule: 'Na een *m* met een lange klank, tweeklank of doffe e ervoor, of na *lm* en *rm*: *-pje*.',
          build: { before: 'Op het balkon staat een klein', stem: 'boom', endings: ['pje', 'tje', 'je', 'etje'], answer: 'pje', note: 'boompje: lange oo + m, dus -pje.' },
          quiz: {
            q: 'Wat is het verkleinwoord van ‘film’?',
            options: ['filmpje', 'filmetje', 'filmtje'],
            answer: 'filmpje',
            why: 'Na lm komt -pje: filmpje. Zo ook arm, armpje.',
          },
        },
        {
          text: 'Na een korte klank met klemtoon en dan *l*, *m*, *n*, *r* of *ng* komt *-etje*. De medeklinker wordt dubbel, net als bij het meervoud: *bal*, *balletje*; *kam*, *kammetje*; *pen*, *pennetje*; *ster*, *sterretje*; *zon*, *zonnetje*. Alleen *ng* blijft enkel: *ring*, *ringetje*; *ding*, *dingetje*. Sorteer de voorwerpen.',
          rule: 'Korte klank met klemtoon + *l*, *m*, *n*, *r* of *ng*: *-etje*, met een dubbele medeklinker (*balletje*).',
          bins: {
            q: 'Zet elk voorwerp in de bak van zijn verkleinwoord',
            bins: ['-je', '-tje', '-pje', '-etje'],
            items: [
              { thing: 'boek', bin: 0, note: 'boekje: na een k komt -je.' },
              { thing: 'muis', bin: 0, note: 'muisje: na een s komt -je.' },
              { thing: 'ei', bin: 1, note: 'eitje: na een tweeklank komt -tje.' },
              { thing: 'struisvogel', bin: 1, note: 'struisvogeltje: doffe e + l, dus -tje.' },
              { thing: 'bloem', bin: 2, note: 'bloempje: een kleine bloem. oe + m, dus -pje.', hint: 'Het gaat om één kleine bloem, niet om een bos bloemen.' },
              { thing: 'zon', bin: 3, note: 'zonnetje: korte o + n, met klemtoon. De n wordt dubbel.' },
              { thing: 'ster', bin: 3, note: 'sterretje: korte e + r, met klemtoon. De r wordt dubbel.' },
              { thing: 'pan', bin: 3, note: 'pannetje: korte a + n, met klemtoon. De n wordt dubbel.' },
            ],
            note: 'Vier uitgangen, en het eind van het woord kiest. Na een korte klank + l, m, n, r komt -etje met een dubbele letter.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'uitgang',
      prompt: 'Welk verkleinwoord krijgt dit woord?',
      buckets: ['-je', '-tje', '-pje', '-etje'],
      items: [
        { t: 'hoofd', b: 0 },
        { t: 'keuken', b: 1 },
        { t: 'riem', b: 2 },
        { t: 'stem', b: 3 },
        { t: 'bericht', b: 0 },
        { t: 'bureau', b: 1 },
        { t: 'helm', b: 2 },
        { t: 'kar', b: 3 },
        { t: 'park', b: 0 },
        { t: 'kussen', b: 1 },
        { t: 'bezem', b: 2 },
        { t: 'slang', b: 3 },
        { t: 'feest', b: 0 },
        { t: 'zoen', b: 1 },
        { t: 'duim', b: 2 },
        { t: 'pil', b: 3 },
      ],
      why: '-je na d, t en k: hoofdje, berichtje, parkje, feestje. -tje na eau en na een lange klank of doffe e + n: keukentje, bureautje, kussentje, zoentje. -pje na m met een lange klank, tweeklank, doffe e of l ervoor: riempje, helmpje, bezempje, duimpje. -etje na een korte klank met klemtoon: stemmetje, karretje, slangetje, pilletje.',
    },
    {
      kind: 'type',
      id: 'zonnetje',
      prompt: 'Typ het verkleinwoord van zon.',
      before: 'Na de regen kwam het',
      after: 'even door.',
      hint: '',
      answer: 'zonnetje',
      why: 'zon: korte o + n, met klemtoon. Dus -etje, en de n wordt dubbel: zonnetje.',
    },
    {
      kind: 'choice',
      id: 'kopje',
      prompt: 'Welk woord past?',
      before: 'Wil je nog een',
      after: 'koffie voor de vergadering begint?',
      options: ['koppetje', 'koptje', 'kopje', 'koppie'],
      answer: 'kopje',
      why: 'kop eindigt op een p: dan komt gewoon -je, zonder dubbele p. Koppie zeg je wel, maar schrijf je niet.',
    },
    {
      kind: 'fix',
      id: 'raampje',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'In het hotel kreeg ik een klein kamertje met een raamtje aan de achterkant.',
      wrong: 10,
      answer: 'raampje',
      why: 'raam: lange aa + m. Dan komt -pje: raampje. kamertje was goed: doffe e + r, dus -tje.',
    },
    {
      kind: 'type',
      id: 'filmpje',
      prompt: 'Typ het verkleinwoord van film.',
      before: 'Mijn zoon stuurde me een grappig',
      after: 'van de hond.',
      hint: '',
      answer: 'filmpje',
      why: 'Na lm komt -pje: filmpje. Zo ook helm, helmpje en arm, armpje.',
    },
    {
      kind: 'bet',
      id: 'woninkje',
      prompt: 'Wat is het verkleinwoord van ‘woning’?',
      intro: 'Let op de klemtoon: WO-ning.',
      options: ['woningetje', 'woninkje', 'woningje', 'woningkje'],
      answer: 'woninkje',
      why: 'Op -ing ligt geen klemtoon. Dan wordt het -inkje: woninkje, zonder g. Met klemtoon, zoals in ring, krijg je -etje: ringetje.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Uitzonderingen en valkuilen',
      panels: [
        {
          text: 'Eindigt een woord op *a*, *o* of *u*, dan verdubbel je die klinker en zet je er *-tje* achter. Zo blijft de klank lang: *auto*, *autootje*; *oma*, *omaatje*; *menu*, *menuutje*; *paraplu*, *parapluutje*; *foto*, *fotootje*. Eindigt een woord op *i*, dan wordt die *i* een *ie*: *taxi*, *taxietje*; *ski*, *skietje*. Alleen na een *y* zet je een apostrof: *baby’tje*, *hobby’tje*.',
          rule: '*a*, *o*, *u* aan het eind: verdubbelen + *-tje* (*autootje*). *i*: *-ietje* (*taxietje*). *y*: apostrof (*baby’tje*).',
          show: [
            { wrong: 'autotje', right: 'autootje' },
            { wrong: 'omatje', right: 'omaatje' },
            { wrong: 'babytje', right: 'baby’tje' },
          ],
          quiz: {
            q: 'Hoe schrijf je een kleine auto?',
            options: ['autootje', 'autotje', 'auto’tje'],
            answer: 'autootje',
            why: 'Na een o aan het eind verdubbel je de o en komt -tje: autootje. Een apostrof gebruik je alleen na een y.',
          },
        },
        {
          text: 'Een paar woorden met een korte klank krijgen in het meervoud een lange klank: *glas*, *glazen*; *schip*, *schepen*; *gat*, *gaten*; *blad*, *bladen*. Die lange klank houden ze in het verkleinwoord: *glaasje*, *scheepje*, *gaatje*, *blaadje*. Woorden die in het meervoud kort blijven, houden ook een korte klank: *kat*, *katten*, *katje*; *bed*, *bedden*, *bedje*. Let op: het geldt niet voor elk woord. *dag*, *dagen*, maar *dagje*; *dak*, *daken*, maar *dakje*; *bad*, *baden*, maar *badje*.',
          rule: 'Lange klank in het meervoud (*glazen*)? Dan meestal ook in het verkleinwoord (*glaasje*). Maar: *dagje*, *dakje*, *badje*.',
          morph: {
            q: 'Kies het goede verkleinwoord',
            rounds: [
              {
                thing: 'glas',
                from: 'het glas',
                ask: 'een klein glas',
                effect: 'klein',
                options: ['een glasje', 'een glaasje', 'een glassetje'],
                answer: 'een glaasje',
                note: 'Het meervoud is glazen, met een lange a. Die komt terug: glaasje.',
              },
            ],
            note: 'Denk aan het meervoud: glazen, dus glaasje.',
          },
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'schip', out: 'schepen → scheepje', note: 'De lange ee uit het meervoud komt terug.' },
              { k: 'gat', out: 'gaten → gaatje', note: 'Lange aa, net als in gaten.' },
              { k: 'blad', out: 'bladen → blaadje', note: 'Lange aa: een blaadje papier.' },
              { k: 'kat', out: 'katten → katje', note: 'Het meervoud heeft een korte a, dus het verkleinwoord ook.' },
            ],
          },
        },
        {
          text: 'Woorden op *-ing* zonder klemtoon krijgen *-kje*: *koning*, *koninkje*; *woning*, *woninkje*; *ketting*, *kettinkje*. Met klemtoon op *ing* krijg je *-etje*: *ring*, *ringetje*. En let op twee woorden met een eigen betekenis: een *bloempje* is een kleine bloem, een *bloemetje* is een bosje bloemen dat je iemand geeft.',
          rule: '*-ing* zonder klemtoon: *-inkje* (*koninkje*). Met klemtoon: *-ingetje* (*ringetje*).',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'koning', out: 'koninkje', note: 'KO-ning: geen klemtoon op -ing, dus -kje.' },
              { k: 'ketting', out: 'kettinkje', note: 'KET-ting: geen klemtoon op -ing, dus -kje.' },
              { k: 'ring', out: 'ringetje', note: 'Eén lettergreep, met klemtoon: -etje.' },
              { k: 'bloem', out: 'bloempje of bloemetje', note: 'bloempje: een kleine bloem. bloemetje: een bosje bloemen.' },
            ],
          },
          quiz: {
            q: 'Je geeft je buurvrouw een bos bloemen. Wat geef je haar?',
            options: ['een bloemetje', 'een bloempje'],
            answer: 'een bloemetje',
            why: 'Een bloemetje is een bosje bloemen. Een bloempje is één kleine bloem.',
          },
        },
        {
          text: 'Het meervoud van een verkleinwoord is altijd *-s*: *boekjes*, *boompjes*, *balletjes*, *autootjes*. Twijfel je over de uitgang? Stap 1: eindigt het woord op *a*, *o*, *u*, *i* of *y*? Zie hierboven. Stap 2: eindigt het op *p*, *t*, *k*, *f*, *s*, *ch* of *d*? Dan *-je*. Stap 3: korte klank met klemtoon + *l*, *m*, *n*, *r*, *ng*? Dan *-etje*. Stap 4: *m* na een lange klank? Dan *-pje*. Stap 5: anders meestal *-tje*.',
          rule: 'Meervoud van een verkleinwoord: altijd *-s* (*boekjes*).',
          paradigm: {
            q: 'Vul het verkleinwoord en het meervoud in',
            cols: ['verkleinwoord', 'meervoud'],
            rows: [
              { label: 'boek', cells: [{ fill: 'boekje' }, { fill: 'boekjes' }] },
              { label: 'boom', cells: [{ fill: 'boompje', hint: 'Lange oo + m: -pje.' }, { fill: 'boompjes' }] },
              { label: 'bal', cells: [{ fill: 'balletje', hint: 'Korte a + l: -etje.' }, { fill: 'balletjes' }] },
              { label: 'auto', cells: [{ fill: 'autootje', hint: 'o aan het eind: verdubbelen + -tje.' }, { fill: 'autootjes' }] },
              { label: 'deur', cells: [{ fill: 'deurtje', hint: 'eu + r: -tje.' }, { fill: 'deurtjes' }] },
            ],
            extra: ['boomtje', 'baltje', 'autotje', 'boekjen'],
            note: 'Eerst de goede uitgang, dan altijd -s erachter.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje-oma',
      prompt: 'Lees het appje aan oma. Tik elke fout aan en verbeter hem.',
      intro: 'Kijk bij elk verkleinwoord: hoe eindigt het grote woord?',
      tokens: [
        { t: 'Hoi' },
        { t: 'oma!' },
        { t: 'We' },
        { t: 'wonen' },
        { t: 'nu' },
        { t: 'in' },
        { t: 'een' },
        { t: 'leuk' },
        { t: 'huisje.' },
        { t: 'Er' },
        { t: 'is' },
        { t: 'een' },
        { t: 'klein' },
        { t: 'tuinje', fix: 'tuintje', why: 'ui + n: -tje, tuintje.' },
        { t: 'met' },
        { t: 'een' },
        { t: 'boomtje.', fix: 'boompje.', why: 'Lange oo + m: -pje, boompje.' },
        { t: 'Sem' },
        { t: 'heeft' },
        { t: 'een' },
        { t: 'eigen' },
        { t: 'kamertje' },
        { t: 'met' },
        { t: 'een' },
        { t: 'raampje.' },
        { t: 'Hij' },
        { t: 'heeft' },
        { t: 'zijn' },
        { t: 'autotje', fix: 'autootje', why: 'o aan het eind: verdubbelen + -tje, autootje.' },
        { t: 'al' },
        { t: 'op' },
        { t: 'de' },
        { t: 'vensterbank' },
        { t: 'gezet.' },
        { t: 'Morgen' },
        { t: 'kopen' },
        { t: 'we' },
        { t: 'een' },
        { t: 'kastje' },
        { t: 'en' },
        { t: 'een' },
        { t: 'lampetje', fix: 'lampje', why: 'lamp eindigt op een p: -je, lampje.' },
        { t: 'voor' },
        { t: 'naast' },
        { t: 'zijn' },
        { t: 'bed.' },
        { t: 'Kom' },
        { t: 'je' },
        { t: 'snel' },
        { t: 'langs' },
        { t: 'voor' },
        { t: 'een' },
        { t: 'kopje' },
        { t: 'thee' },
        { t: 'of' },
        { t: 'een' },
        { t: 'glasje', fix: 'glaasje', why: 'glazen heeft een lange a, dus glaasje.' },
        { t: 'limonade?' },
      ],
      done: { title: 'Alles gevonden', text: 'tuintje, boompje, autootje, lampje en glaasje. En huisje, kamertje, raampje, kastje en kopje waren al goed.' },
    },
    {
      kind: 'dictation',
      id: 'omaatje',
      prompt: 'Luister en typ de zin.',
      sentence: 'Op haar verjaardag kreeg ons omaatje een bloemetje, een fotootje van de baby en een klein cadeautje.',
      right: 'Goed: ons omaatje (het-woord, en a aan het eind: aa + tje), bloemetje (een bosje bloemen), fotootje (oo + tje) en cadeautje (eau + tje).',
      wrong: 'Let op: ons omaatje (een verkleinwoord is een het-woord), bloemetje als bosje bloemen, fotootje met oo en cadeautje met eau + tje.',
    },
    {
      kind: 'swipe',
      id: 'zinnen',
      prompt: 'Is deze zin goed geschreven?',
      cards: [
        { t: 'Ze woont in een klein dorpje aan de rivier.', ok: true, why: 'dorp eindigt op p: dorpje. En een klein dorpje, want het is een het-woord.' },
        {
          t: 'Mag ik de fietsje van je zus even lenen?',
          ok: false,
          fix: 'het fietsje',
          why: 'Een verkleinwoord is altijd een het-woord: de fiets, maar het fietsje.',
        },
        { t: 'Bij de koffie kregen we een koekje en een chocolaatje.', ok: true, why: 'chocola eindigt op a: verdubbelen + -tje. chocolaatje.' },
        { t: 'Kijk, wat een lief babytje!', ok: false, fix: 'baby’tje', why: 'Na een y komt een apostrof: baby’tje.' },
        { t: 'Hij stuurde me een berichtje met het adres.', ok: true, why: 'bericht eindigt op t: -je. Geen extra t.' },
        { t: 'Er zit een gatje in mijn sok.', ok: false, fix: 'gaatje', why: 'gaten heeft een lange a, dus gaatje.' },
        { t: 'Ik heb het ringetje van mijn oma nog.', ok: true, why: 'ring heeft klemtoon: -etje, en ng blijft enkel. ringetje.' },
        { t: 'Het is maar een kettingetje van de markt.', ok: false, fix: 'kettinkje', why: 'KET-ting: geen klemtoon op -ing, dus -inkje: kettinkje.' },
        { t: 'Mijn oma heeft een klein tuintje met een bankje.', ok: true, why: 'tuin: ui + n, dus -tje. bank: na een k, dus -je.' },
        {
          t: 'Elk kind kreeg op het feest een ballonetje.',
          ok: false,
          fix: 'ballonnetje',
          why: 'bal-LON: korte o + n met klemtoon. -etje, en de n wordt dubbel: ballonnetje.',
        },
        { t: 'Het oude vrouwtje woont alleen in een flatje.', ok: true, why: 'vrouw: na ouw komt -tje. flat: na een t komt -je.' },
        { t: 'Mijn zoon speelt met zijn autotje.', ok: false, fix: 'autootje', why: 'o aan het eind: verdubbelen + -tje. autootje.' },
      ],
    },
    {
      kind: 'rewrite',
      id: 'klein-maken',
      prompt: 'Maak van elk zelfstandig naamwoord een verkleinwoord. Let ook op de lidwoorden.',
      source: 'De vrouw zet de pan en het glas op de plank.',
      accept: ['Het vrouwtje zet het pannetje en het glaasje op het plankje.'],
      why: 'vrouw: -tje. pan: korte a + n, dus pannetje. glas: glazen, dus glaasje. plank: na een k, dus -je. En elk verkleinwoord is een het-woord: het vrouwtje, het pannetje, het plankje.',
    },
    {
      kind: 'type',
      id: 'parapluutje',
      prompt: 'Typ het verkleinwoord van paraplu.',
      before: 'In haar tas zit een klein',
      after: 'voor als het regent.',
      hint: '',
      answer: 'parapluutje',
      why: 'u aan het eind: verdubbelen + -tje. Zo blijft de u lang: parapluutje.',
    },
    {
      kind: 'choice',
      id: 'bloemetje',
      prompt: 'Welk woord past?',
      before: 'Voor haar verjaardag kreeg mijn moeder een mooi',
      after: 'van de buren.',
      options: ['bloempje', 'bloemtje', 'bloemetje', 'bloemmetje'],
      answer: 'bloemetje',
      why: 'Een bos bloemen als cadeau is een bloemetje. Een bloempje is één kleine bloem. bloemtje en bloemmetje bestaan niet.',
    },
    {
      kind: 'type',
      id: 'kommetjes',
      prompt: 'Typ het meervoud van het verkleinwoord van kom.',
      before: 'Zet de soep in kleine',
      after: 'op tafel.',
      hint: '',
      answer: 'kommetjes',
      why: 'kom: korte o + m met klemtoon. Dus -etje met mm: kommetje. Het meervoud van een verkleinwoord is altijd -s: kommetjes.',
    },
    {
      kind: 'bet',
      id: 'ski',
      prompt: 'Een lastige: hoe schrijf je een kleine ski?',
      options: ['skitje', 'ski’tje', 'skietje', 'skiitje'],
      answer: 'skietje',
      why: 'Na een i aan het eind wordt het ie + tje: skietje, net als taxietje. Een apostrof komt alleen na een y (baby’tje), verdubbelen doe je bij a, o en u.',
    },
    {
      kind: 'write',
      id: 'mijn-kamer',
      prompt: 'Beschrijf een kamer in je huis in een paar zinnen. Gebruik verkleinwoorden.',
      intro: 'Bijvoorbeeld: Op mijn bureau staat een lampje.',
      minWords: 25,
      must: [
        { label: 'Een verkleinwoord op -je, zoals kastje of lampje', hint: 'een kastje', test: { pattern: '\\b\\w+[ptkfsd]jes?\\b', flags: 'i' } },
        { label: 'Een verkleinwoord op -tje, zoals tafeltje of deurtje', hint: 'een tafeltje', test: { pattern: '\\b\\w*([aeiou]|[aeiou][lnrw]|e[lnr])tjes?\\b', flags: 'i' } },
        { label: 'Een verkleinwoord op -pje of -etje, zoals raampje of balletje', hint: 'een raampje', test: { pattern: '\\b\\w+(mpjes?|(ll|mm|nn|rr|ng)etjes?)\\b', flags: 'i' } },
      ],
      avoid: [
        {
          test: { pattern: '\\b(boomtje|raamtje|baltje|pentje|zontje|autotje|tuinje|glasje|lampetje|stoelje)\\b', flags: 'i' },
          tip: 'Kijk nog eens naar dit verkleinwoord. Hoe eindigt het grote woord?',
        },
      ],
      why: 'Je gebruikte verschillende uitgangen. Het eind van het woord bepaalt steeds welke.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Verkleinwoorden en woorden uit eerdere lessen door elkaar. Wat je fout doet, komt achteraan terug.',
      items: [
        { q: 'Verkleinwoord van *de keuken*', before: 'We wonen in een flat met een klein', after: '.', a: 'keukentje', why: 'Doffe e + n: -tje. keukentje.' },
        {
          q: 'Verkleinwoord van *de woning*',
          before: 'Na de scheiding huurde hij een',
          after: 'in het centrum.',
          a: 'woninkje',
          why: 'WO-ning: geen klemtoon op -ing, dus -inkje.',
        },
        {
          q: 'Meervoud van *de bacterie*',
          before: 'Was je handen goed, dan krijgen',
          after: 'minder kans.',
          a: 'bacteriën',
          why: 'bac-TE-rie: geen klemtoon op ie, dus -iën.',
        },
        {
          q: 'Verkleinwoord van *de oma*',
          before: 'Ons',
          after: 'wordt volgende week negentig.',
          a: 'omaatje',
          why: 'a aan het eind: verdubbelen + -tje. omaatje.',
        },
        {
          q: 'Verkleinwoord van *het glas*',
          before: 'Op het feest dronk ze maar één',
          after: 'wijn.',
          a: 'glaasje',
          why: 'glazen heeft een lange a, dus glaasje.',
        },
        {
          q: 'Het tegenovergestelde van *jong*',
          before: 'Onze',
          after: 'buurvrouw woont al vijftig jaar in deze straat.',
          a: 'oude',
          also: ['oudere'],
          why: 'oud, oude: voor een d schrijf je ou.',
        },
        { q: 'Verkleinwoord van *de baby*', before: 'De buren hebben net een', after: 'gekregen.', a: 'baby’tje', why: 'y aan het eind: apostrof + -tje.' },
        {
          q: 'Verkleinwoord van *de pan*',
          before: 'Warm de melk op in een klein',
          after: '.',
          a: 'pannetje',
          why: 'pan: korte a + n met klemtoon. -etje met nn.',
        },
        {
          q: 'Verkleinwoord van *het schip*',
          before: 'In de fles zit een',
          after: 'van hout.',
          a: 'scheepje',
          why: 'schepen heeft een lange e, dus scheepje.',
        },
        { q: 'Zelfstandig naamwoord bij *eerlijk*', before: 'Ik waardeer je', after: '.', a: 'eerlijkheid', why: '-lijk met ij, -heid met ei: eerlijkheid.' },
        { q: 'Verkleinwoord van *het raam*', before: 'Het', after: 'van de badkamer moet open blijven.', a: 'raampje', why: 'Lange aa + m: -pje.' },
        { q: 'Verkleinwoord van *het cadeau*', before: 'Ik heb een klein', after: 'voor je meegenomen.', a: 'cadeautje', why: 'Na eau komt -tje.' },
        { q: 'Meervoud van *de reis*', before: 'Hij boekt zijn', after: 'altijd online.', a: 'reizen', why: 'Je hoort een z: reizen.' },
        {
          q: 'Verkleinwoord van *de ketting*',
          before: 'Ze kreeg een gouden',
          after: 'van haar moeder.',
          a: 'kettinkje',
          why: 'KET-ting: geen klemtoon op -ing, dus -inkje.',
        },
        {
          q: 'Verkleinwoord van *het gat*',
          before: 'Er zit een',
          after: 'in de band van mijn fiets.',
          a: 'gaatje',
          why: 'gaten heeft een lange a, dus gaatje.',
        },
        { q: 'Het tegenovergestelde van *negatief*', before: 'Ze heeft een heel', after: 'houding.', a: 'positieve', why: '-ief wordt -ieve: positieve.' },
        {
          q: 'Verkleinwoord van *de foto*',
          before: 'In haar portemonnee zit een',
          after: 'van haar kinderen.',
          a: 'fotootje',
          why: 'o aan het eind: verdubbelen + -tje.',
        },
        {
          q: 'Verkleinwoord van *de kam*',
          before: 'Ze heeft altijd een',
          after: 'in haar tas.',
          a: 'kammetje',
          why: 'kam: korte a + m met klemtoon. -etje met mm.',
        },
        {
          q: 'Verleden tijd van *fietsen*',
          before: 'Gisteren',
          after: 'we samen naar het strand.',
          a: 'fietsten',
          why: 'Stam fiets: de s zit in ’t kofschip. Dus -te of -ten: fietsten.',
        },
        {
          q: 'Verkleinwoord van *de bloem*: een bos bloemen als cadeau',
          before: 'We kochten een',
          after: 'voor de buurvrouw.',
          a: 'bloemetje',
          why: 'Een bosje bloemen is een bloemetje.',
        },
        {
          q: 'Het getal 1, met nadruk',
          before: 'Ik heb nog maar',
          after: 'vraag over het contract.',
          a: 'één',
          why: 'Het getal één schrijf je met accenten als het anders verwarrend is: maar één vraag.',
        },
        { q: 'Meervoud van het verkleinwoord van *boom*', before: 'Langs de nieuwe weg staan jonge', after: '.', a: 'boompjes', why: 'boompje + s: boompjes.' },
        {
          q: 'Verkleinwoord van *de duim*',
          before: 'Als antwoord op mijn appje stuurde ze alleen een',
          after: '.',
          a: 'duimpje',
          why: 'ui + m: -pje. duimpje.',
        },
        {
          q: 'Samenstelling van *zee* en *egel*',
          before: 'Op het strand vonden de kinderen een',
          after: '.',
          a: 'zee-egel',
          why: 'ee + e: zonder streepje lees je het verkeerd. Dus een koppelteken: zee-egel.',
        },
        {
          q: 'Verkleinwoord van *de ring*',
          before: 'Ze draagt een zilveren',
          after: 'aan haar pink.',
          a: 'ringetje',
          why: 'ring heeft klemtoon: -etje, en ng blijft enkel.',
        },
      ],
      done: { title: 'Reeks klaar', text: 'Steeds dezelfde vraag: hoe eindigt het grote woord? En bij de andere woorden: welke regel geldt hier?' },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail aan. Typ elk woord helemaal.',
      intro: 'In het grijs staat wat je moet maken, bijvoorbeeld *kleine tuin*. Typ het ene woord dat in de zin past.',
      title: 'Mail aan de collega’s: feestje in het nieuwe huis',
      text: 'Hoi allemaal,\n\nHet is {eindelijk|na lang wachten|‘luhk’ schrijf je -lijk, met ij. En einde, dus eind met d.} zover: we zijn {verhuisd|van verhuizen: we zijn …|verhuizen heeft een z: verhuisde, dus verhuisd met d.}! Ons nieuwe {huisje|klein huis|Na een s: -je.} is niet groot, maar het heeft een {tuintje|kleine tuin|ui + n: -tje.} met een {boompje|kleine boom|Lange oo + m: -pje.}. Onze zoon heeft boven een eigen {kamertje|kleine kamer|Doffe e + r: -tje.} met een {raampje|klein raam|Lange aa + m: -pje.} aan de achterkant. In de gang staat nog een {stapeltje|kleine stapel|Doffe e + l: -tje.} {dozen|meervoud van doos|Je hoort een z, en do-zen heeft een open lettergreep: één o.}, en het {kastje|kleine kast|Na een t: -je.} in de keuken heeft nog geen deur.\n\nToch geven we zaterdag een {feestje|klein feest|Na een t: -je.} voor alle {collega’s~collegae|meervoud van collega|collega eindigt op a: ’s. Ook goed is collegae.}. Jullie zijn welkom vanaf vier uur. Neem gerust je partner en de kinderen mee, want die kunnen lekker in de tuin {spelen|ik speel, wij …|spe-len: spe is open, dus één e.}. Er zijn drankjes en {hapjes|kleine happen|hap eindigt op p: -je, zonder dubbele p. Meervoud: hapjes.}, en wie wil, krijgt een {rondleiding~rondje|wandeling met uitleg|ronde, dus rond met d. En leiding met ei.} door het huis. {Cadeautjes|kleine cadeaus|Na eau: -tje. Meervoud: cadeautjes.} zijn echt niet nodig!\n\nKom je met de auto? Parkeer dan bij het {pleintje|klein plein|ei + n: -tje.} om de hoek. De {route~routebeschrijving|weg ernaartoe|De oe-klank schrijf je hier als ou: route.} staat onder deze mail. Het wordt vast heel gezellig.\n\nGroetjes,\nSamira',
      why: 'Verkleinwoorden: het eind van het grote woord kiest de uitgang (huisje, tuintje, boompje, kamertje, raampje, stapeltje, kastje, feestje, hapjes, cadeautjes, pleintje). Uit eerdere lessen: eindelijk (-lijk), verhuisd (d), dozen (z), collega’s (’s), spelen (open lettergreep: één e), rondleiding (d) en route (ou).',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen over een weekend aan zee. Hoofdletters en leestekens tellen mee.',
      title: 'Een weekendje weg',
      sentences: [
        'Vorig weekend huurden we een huisje aan zee met een klein tuintje.',
        'De kinderen zochten op het strand naar schelpjes en mooie steentjes.',
        'Mijn zoon liet een vliegertje op en at daarna een ijsje met een wafeltje.',
        'In een restaurantje aan de haven aten we visjes met een sausje.',
        'Oma kreeg een kaartje met een fotootje van de kinderen in een bootje.',
        'Op de laatste avond zagen we de zon als een rood balletje in zee zakken.',
      ],
      right:
        'Alles goed. -je na p, t, k en s (schelpjes, restaurantje, ijsje, sausje), -tje na een lange klank of doffe e (steentjes, vliegertje, wafeltje), oo + tje (fotootje) en -etje met ll (balletje). En een rood balletje: een het-woord.',
      wrong:
        'Kijk de uitgangen na. Na p, t, k, s: -je. Lange klank of doffe e + l, n, r: -tje (steentjes, vliegertje, wafeltje). o aan het eind: fotootje. Korte klank + l: balletje. En een rood balletje, zonder e: het is een het-woord.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk het bericht in de buurtapp na voordat het weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'Buurtapp Lindelaan', subject: 'Rommelmarkt zaterdag' },
      greeting: 'Hallo buren,',
      signoff: 'Groetjes,\nPetra en Mark (nummer 12)',
      tokens: [
        { t: 'Zaterdag' },
        { t: 'houden' },
        { t: 'we' },
        { t: 'een' },
        { t: 'rommelmarkt' },
        { t: 'in' },
        { t: 'onze' },
        { t: 'tuin.' },
        { t: 'We' },
        { t: 'beginnen' },
        { t: 'om' },
        { t: 'tien' },
        { t: 'uur' },
        { t: 'en' },
        { t: 'stoppen' },
        { t: 'om' },
        { t: 'drie' },
        { t: 'uur.' },
        { t: 'We' },
        { t: 'verkoopen', fix: 'verkopen', why: 'ver-ko-pen: open lettergreep, dus één o.' },
        { t: 'van' },
        { t: 'alles:' },
        { t: 'de', fix: 'het', why: 'Een verkleinwoord is altijd een het-woord: de kast, maar het kastje.' },
        { t: 'kastje' },
        { t: 'uit' },
        { t: 'de' },
        { t: 'gang,' },
        { t: 'een' },
        { t: 'lampetje,', fix: 'lampje,', why: 'lamp eindigt op een p: -je. lampje.' },
        { t: 'drie' },
        { t: 'stoeltjes' },
        { t: 'en' },
        { t: 'een' },
        { t: 'klein' },
        { t: 'tafelje.', fix: 'tafeltje.', why: 'Doffe e + l: -tje. tafeltje.' },
        { t: 'Ook' },
        { t: 'hebben' },
        { t: 'we' },
        { t: 'twee' },
        { t: 'kussentjes,', trap: 'Goed: kussen eindigt op doffe e + n, dus -tje. kussentjes.' },
        { t: 'een' },
        { t: 'schilderijtje', trap: 'Goed: schilderij eindigt op ij, een tweeklank. Dan komt -tje.' },
        { t: 'en' },
        { t: 'een' },
        { t: 'radiotje.', fix: 'radiootje.', why: 'o aan het eind: verdubbelen + -tje. radiootje.' },
        { t: 'Op' },
        { t: 'een' },
        { t: 'tafel' },
        { t: 'staan' },
        { t: 'zes' },
        { t: 'glasjes', fix: 'glaasjes', why: 'glazen heeft een lange a, dus glaasjes.' },
        { t: 'en' },
        { t: 'een' },
        { t: 'doos' },
        { t: 'met' },
        { t: 'kommetjes.', trap: 'Goed: kom heeft een korte o met klemtoon. -etje met mm: kommetjes.' },
        { t: 'Voor' },
        { t: 'de' },
        { t: 'kinderen' },
        { t: 'is' },
        { t: 'er' },
        { t: 'een' },
        { t: 'kraampje', trap: 'Goed: kraam heeft een lange aa + m, dus -pje.' },
        { t: 'met' },
        { t: 'boeken' },
        { t: 'en' },
        { t: 'een' },
        { t: 'zilveren' },
        { t: 'kettingetje', fix: 'kettinkje', why: 'KET-ting: geen klemtoon op -ing, dus -inkje.' },
        { t: 'voor' },
        { t: 'één' },
        { t: 'euro.' },
        { t: 'De' },
        { t: 'opbrengst' },
        { t: 'gaat' },
        { t: 'naar' },
        { t: 'een' },
        { t: 'goet', fix: 'goed', why: 'goede, dus d.' },
        { t: 'doel.' },
        { t: 'Het' },
        { t: 'wordt' },
        { t: 'vast' },
        { t: 'gezelig!', fix: 'gezellig!', why: 'ge-zel-lig: korte e, dus ll.' },
        { t: 'Kom' },
        { t: 'gerust' },
        { t: 'even' },
        { t: 'kijken.' },
      ],
      done: {
        title: 'Bericht nagekeken',
        text: 'De fouten: verkopen, het kastje, lampje, tafeltje, radiootje, glaasjes, kettinkje, goed en gezellig. kussentjes, schilderijtje, kommetjes en kraampje waren goed.',
      },
    },
  ],
};
