import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": van het hele werkwoord naar de stam, en de stam in de tegenwoordige tijd (ik, jij, hij, wij). */
export const LES_G25: LessonInput = {
  id: 'g25',
  stage: 'regels',
  domain: 'morf',
  also: ['orth'],
  title: 'Werkwoorden: de stam',
  skill: 'Spelling',
  icon: 'stam',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Zo vind je de stam',
      panels: [
        {
          text: 'Het *hele werkwoord* is de vorm uit het woordenboek: *werken*, *fietsen*, *wachten*. Haal je de *-en* eraf, dan houd je de *stam* over: *werk*, *fiets*, *wacht*. De stam is de vorm bij *ik*: *ik werk*, *ik fiets*, *ik wacht*. Met de stam maak je bijna alle andere vormen. Daarom moet je hem goed kunnen schrijven.',
          rule: 'Stam = hele werkwoord min *-en*. Bij *ik* schrijf je alleen de stam: *ik werk*.',
          build: {
            before: 'Elke dag … ik tot vijf uur. (werken)',
            stem: 'werk',
            endings: ['', 't', 'en', 'e'],
            answer: '',
            note: 'Bij ik komt er niets achter de stam: ik werk. Ik werkt en ik werken zijn fout.',
          },
        },
        {
          text: 'Soms moet je de stam even aanpassen. Dat komt door de regels voor lettergrepen. In *lo-pen* staat de *o* aan het eind van een lettergreep: één letter is genoeg. In de stam *loop* is de lettergreep gesloten: dan heb je twee letters nodig voor de lange klank. Zo ook *maken* → *maak*, *horen* → *hoor*, *sturen* → *stuur*, *eten* → *eet*. En andersom: in *zet-ten* staat een dubbele letter. Aan het eind van een woord schrijf je nooit een dubbele medeklinker. Dus *zetten* → *zet*, *bellen* → *bel*, *pakken* → *pak*.',
          rule: 'Lange klank in de stam: twee letters (*lopen* → *loop*). Dubbele medeklinker aan het eind: één letter (*zetten* → *zet*).',
          paradigm: {
            q: 'Vul de stam in',
            cols: ['ik …'],
            rows: [
              { label: 'lopen', cells: [{ fill: 'loop', hint: 'Lange o in een gesloten lettergreep: twee letters.' }] },
              { label: 'maken', cells: [{ fill: 'maak', hint: 'ma-ken: in de stam wordt de lettergreep gesloten, dus aa.' }] },
              { label: 'sturen', cells: [{ fill: 'stuur', hint: 'Lange u aan het eind van de stam: uu.' }] },
              { label: 'eten', cells: [{ fill: 'eet', hint: 'Lange e in een gesloten lettergreep: ee.' }] },
              { label: 'zetten', cells: [{ fill: 'zet', hint: 'Geen dubbele t aan het eind van een woord.' }] },
              { label: 'bellen', cells: [{ fill: 'bel', hint: 'De dubbele l was er alleen voor de korte klank in bel-len.' }] },
            ],
            extra: ['lop', 'mak', 'stur', 'zett', 'bell'],
            note: 'Lange klank: twee letters (loop, maak, stuur, eet). Dubbele medeklinker: één letter (zet, bel).',
          },
        },
        {
          text: 'Nog een aanpassing: aan het eind van de stam schrijf je nooit een *v* of een *z*. Daar wordt het een *f* of een *s*, want dat hoor je ook. *Leven* → *ik leef*, *geloven* → *ik geloof*, *schrijven* → *ik schrijf*, *reizen* → *ik reis*, *verhuizen* → *ik verhuis*, *lezen* → *ik lees*. Let op: bij *lezen* gebeuren er twee dingen tegelijk: *z* wordt *s* en de lange klank krijgt twee letters. Bij *ch* en *ng* verandert er niets: *lachen* → *ik lach*, *zingen* → *ik zing*.',
          rule: 'Geen *v* of *z* aan het eind van de stam: *leven* → *leef*, *reizen* → *reis*.',
          lab: {
            label: 'Tik een werkwoord',
            chips: [
              { k: 'leven', out: 'ik leef', note: 'v wordt f. De lange e krijgt twee letters: leef.' },
              { k: 'schrijven', out: 'ik schrijf', note: 'v wordt f. ij blijft ij.' },
              { k: 'reizen', out: 'ik reis', note: 'z wordt s. ei blijft ei.' },
              { k: 'lezen', out: 'ik lees', note: 'Twee aanpassingen: z wordt s, en de lange e krijgt twee letters.' },
              { k: 'durven', out: 'ik durf', note: 'v wordt f. De korte u blijft gewoon één letter.' },
              { k: 'lachen', out: 'ik lach', note: 'ch blijft ch. Hier verandert niets.' },
            ],
          },
        },
        {
          text: 'Nu de persoonsvorm in de tegenwoordige tijd. *Ik*: alleen de stam (*ik loop*). *Jij*, *je*, *u*, *hij*, *zij* (één persoon) en *het*: stam + *t* (*jij loopt*, *u loopt*, *hij loopt*). *Wij*, *jullie* en *zij* (meer personen): het hele werkwoord (*wij lopen*, *jullie lopen*). Let op: bij het hele werkwoord gaan de aanpassingen terug: *ik reis*, maar *wij reizen*; *ik zet*, maar *wij zetten*.',
          rule: '*ik* + stam. *jij*, *u*, *hij*, *zij*, *het* + stam + *t*. *wij*, *jullie*, *zij* (meer) + hele werkwoord.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik', 'jij', 'wij'],
            rows: [
              { label: 'lopen', cells: [{ fill: 'loop' }, { fill: 'loopt' }, { fill: 'lopen', hint: 'Het hele werkwoord: lo-pen, met één o.' }] },
              { label: 'reizen', cells: [{ fill: 'reis' }, { fill: 'reist', hint: 'Stam reis + t.' }, { fill: 'reizen', hint: 'Het hele werkwoord heeft weer een z.' }] },
              { label: 'zetten', cells: [{ fill: 'zet' }, { fill: 'zet', hint: 'De stam eindigt al op t. Er komt geen tweede t bij.' }, { fill: 'zetten' }] },
              { label: 'maken', cells: [{ fill: 'maak' }, { fill: 'maakt' }, { fill: 'maken' }] },
            ],
            extra: ['loopen', 'reizt', 'zett', 'maaken'],
            note: 'Eén stam, drie vormen. En het hele werkwoord krijgt zijn eigen spelling terug: lopen, reizen, zetten, maken.',
          },
        },
        {
          text: 'Korte werkwoorden als *gaan*, *staan*, *slaan*, *zien* en *doen* hebben geen *-en* om eraf te halen. Hun stam is: *ga*, *sta*, *sla*, *zie*, *doe*. *Ik ga* schrijf je met één *a*, want aan het eind van een woord is één *a* genoeg (zoals in *pa* en *ja*). Met een *t* erachter wordt de lettergreep gesloten: *hij gaat*, *jij staat*. *Zie* en *doe* blijven gewoon *ie* en *oe*: *hij ziet*, *zij doet*.',
          rule: '*gaan* → *ik ga*, *hij gaat*. *zien* → *ik zie*, *hij ziet*. *doen* → *ik doe*, *hij doet*.',
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Ik ga morgen naar de markt.', 'Ik gaa morgen naar de markt.', 'Ik gaat morgen naar de markt.'],
            answer: 'Ik ga morgen naar de markt.',
            why: 'Bij ik alleen de stam: ga. Aan het eind van een woord schrijf je één a. Hij gaat krijgt wel twee a’s, want daar staat de t achter.',
          },
          deep: {
            q: 'En hebben, zijn en kunnen?',
            a: 'Een paar heel gewone werkwoorden volgen de regel niet. Die leer je apart: *ik heb*, *jij hebt*, *hij heeft*; *ik ben*, *jij bent*, *hij is*; *ik kan*, *ik wil*, *ik zal*, *ik mag*. Je ziet ze zo vaak dat je ze snel kent.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'aanpassing',
      prompt: 'Wat gebeurt er als je de stam maakt?',
      buckets: ['lange klank: twee letters', 'dubbele letter wordt één', 'v of z wordt f of s', 'alleen -en eraf'],
      items: [
        { t: 'wonen', b: 0 },
        { t: 'koken', b: 0 },
        { t: 'horen', b: 0 },
        { t: 'stoppen', b: 1 },
        { t: 'pakken', b: 1 },
        { t: 'vullen', b: 1 },
        { t: 'durven', b: 2 },
        { t: 'kiezen', b: 2 },
        { t: 'blijven', b: 2 },
        { t: 'fietsen', b: 3 },
        { t: 'wachten', b: 3 },
        { t: 'zingen', b: 3 },
      ],
      why: 'woon, kook, hoor: de lange klank krijgt twee letters. stop, pak, vul: geen dubbele letter aan het eind. durf, kies, blijf: v wordt f en z wordt s. fiets, wacht, zing: alleen -en eraf.',
    },
    {
      kind: 'type',
      id: 'slaap',
      prompt: 'Typ de goede vorm van slapen.',
      before: 'Ik',
      after: 'elke nacht acht uur.',
      hint: 'stam van slapen',
      answer: 'slaap',
      why: 'sla-pen: in de stam wordt de lettergreep gesloten, dus twee a’s: ik slaap.',
    },
    {
      kind: 'choice',
      id: 'lees',
      prompt: 'Kies de goede vorm.',
      before: 'Ik',
      after: 'elke ochtend het nieuws op mijn telefoon.',
      options: ['lees', 'leez', 'lies', 'leest'],
      answer: 'lees',
      why: 'lezen → lees: z wordt s en de lange e krijgt twee letters. Bij ik geen t.',
    },
    {
      kind: 'fix',
      id: 'leev',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Ik leev al tien jaar in Utrecht.',
      wrong: 1,
      answer: 'leef',
      why: 'leven → leef. Aan het eind van de stam schrijf je nooit een v, maar een f.',
    },
    {
      kind: 'combine',
      id: 'hij-zetten',
      prompt: 'Maak de goede vorm: onderwerp + werkwoord.',
      a: 'hij',
      b: 'zetten',
      options: ['hij zet', 'hij zett', 'hij zetten', 'hij zets'],
      answer: 'hij zet',
      why: 'Stam zet. Bij hij komt er een t bij, maar de stam eindigt al op t. Twee t’s schrijf je niet: hij zet.',
    },
    {
      kind: 'type',
      id: 'geloof',
      prompt: 'Typ de goede vorm van geloven.',
      before: 'Ik',
      after: 'niet dat de bus nog komt.',
      hint: 'stam van geloven',
      answer: 'geloof',
      why: 'ge-lo-ven → geloof: de v wordt f, en de lange o krijgt in de gesloten lettergreep twee letters.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen: jij, je en de t',
      panels: [
        {
          text: 'Staat *jij* of *je* achter het werkwoord? Dan valt de *t* weg. *Jij werkt thuis*, maar *Werk jij thuis?* en *Morgen werk je thuis.* Dat geldt alleen voor *jij* en *je*. Bij *hij*, *zij*, *u* en *het* blijft de *t* gewoon staan: *Werkt hij thuis?*, *Komt u ook?*',
          rule: '*jij* of *je* achter het werkwoord: geen *t* (*Loop jij mee?*). Bij *hij*, *zij*, *u*: wel een *t* (*Loopt hij mee?*).',
          quiz: {
            q: 'Welke vraag is goed?',
            options: ['Kom jij morgen ook?', 'Komt jij morgen ook?', 'Komen jij morgen ook?'],
            answer: 'Kom jij morgen ook?',
            why: 'jij staat achter het werkwoord, dus alleen de stam: kom jij. Maar: jij komt, en komt hij?',
          },
        },
        {
          text: 'Pas op met *je*. Soms betekent *je* hetzelfde als *jouw*: *je broer*, *je moeder*, *je auto*. Dan is *je* niet het onderwerp. Het onderwerp is *je broer*, en dat is een *hij*. Dus: *Werkt je broer morgen?*, met een *t*. Twijfel je? Vervang *je* door *jouw*. Kan dat, dan blijft de *t* staan.',
          rule: '*je* = *jouw*? Dan blijft de *t*: *Werkt je moeder vandaag?*',
          lab: {
            label: 'Tik een vraag',
            chips: [
              { k: 'Loop je mee?', out: 'je = jij → geen t', note: 'Het onderwerp is je (jij), en het staat achter het werkwoord.' },
              { k: 'Loopt je zus mee?', out: 'je = jouw → wel t', note: 'Het onderwerp is je zus. Jouw zus loopt mee: een hij/zij-vorm.' },
              { k: 'Werk jij vandaag?', out: 'jij achter het werkwoord → geen t', note: 'Alleen de stam: werk jij.' },
              { k: 'Werkt je vader vandaag?', out: 'je = jouw → wel t', note: 'Jouw vader werkt: stam + t.' },
              { k: 'Wordt u geholpen?', out: 'u → wel t', note: 'Bij u blijft de t altijd staan, ook achter het werkwoord.' },
            ],
          },
        },
        {
          text: 'Eindigt de stam al op een *t*? Dan komt er geen tweede *t* bij: *ik zet*, *hij zet*; *ik praat*, *zij praat*; *ik eet*, *hij eet*. Eindigt de stam op een *d*? Dan komt de *t* er wél achter, ook al hoor je hem niet: *ik word*, *hij wordt*; *ik vind*, *zij vindt*. Meer daarover leer je bij Het woord.',
          rule: 'Stam op *t*: geen extra *t* (*hij zet*). Stam op *d*: wel *t* erbij (*hij wordt*).',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik', 'hij'],
            rows: [
              { label: 'praten', cells: [{ fill: 'praat' }, { fill: 'praat', hint: 'De stam eindigt al op t: geen tweede t.' }] },
              { label: 'eten', cells: [{ fill: 'eet' }, { fill: 'eet' }] },
              { label: 'worden', cells: [{ fill: 'word', hint: 'Stam: worden min -en.' }, { fill: 'wordt', hint: 'Stam word + t.' }] },
              { label: 'vinden', cells: [{ fill: 'vind' }, { fill: 'vindt', hint: 'Stam vind + t.' }] },
            ],
            extra: ['praatt', 'eett', 'wort', 'vint'],
            note: 'praat en eet: de t zit al in de stam. wordt en vindt: d + t.',
          },
        },
        {
          text: 'Twijfel je? Gebruik dit stappenplan. 1. Neem het hele werkwoord: *verhuizen*. 2. Haal *-en* eraf: *verhuiz*. 3. Pas aan: *z* wordt *s* (en een lange klank krijgt twee letters, een dubbele letter wordt één): *verhuis*. 4. Kijk naar het onderwerp: *ik* → *ik verhuis*; *jij*, *u*, *hij*, *zij* → *hij verhuist*; *wij*, *jullie*, *zij* → het hele werkwoord: *wij verhuizen*. 5. Staat *jij* of *je* achter het werkwoord? Dan geen *t*: *Verhuis jij ook?*',
          rule: 'Hele werkwoord → *-en* eraf → aanpassen → onderwerp bekijken.',
          build: {
            before: 'Mijn buurvrouw … volgende maand naar Gouda. (verhuizen)',
            stem: 'verhui',
            endings: ['st', 'zt', 's', 'zen'],
            answer: 'st',
            note: 'Stam verhuis, en bij zij (één persoon) komt er een t bij: verhuist. Nooit verhuizt.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje',
      prompt: 'Vind de vijf fouten in dit appje aan een collega.',
      intro: 'Kijk bij elk werkwoord: wie is het onderwerp, en hoe schrijf je de stam?',
      header: { to: 'Sanne (collega)' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Sanne,' },
        { t: 'ik' },
        { t: 'werkt', fix: 'werk', why: 'Bij ik alleen de stam: ik werk.' },
        { t: 'vandaag' },
        { t: 'thuis.' },
        { t: 'Mijn' },
        { t: 'zoon' },
        { t: 'is' },
        { t: 'ziek' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'blijf' },
        { t: 'bij' },
        { t: 'hem.' },
        { t: 'Wij' },
        { t: 'verhuisen', fix: 'verhuizen', why: 'Bij wij het hele werkwoord, en dat schrijf je met een z: verhuizen.' },
        { t: 'zaterdag' },
        { t: 'ook' },
        { t: 'nog,' },
        { t: 'dus' },
        { t: 'ik' },
        { t: 'leev', fix: 'leef', why: 'leven → leef: aan het eind van de stam een f.' },
        { t: 'tussen' },
        { t: 'de' },
        { t: 'dozen!' },
        { t: 'Ik' },
        { t: 'zett', fix: 'zet', why: 'zetten → zet: geen dubbele t aan het eind.' },
        { t: 'de' },
        { t: 'planning' },
        { t: 'vanmiddag' },
        { t: 'online.' },
        { t: 'Komt', fix: 'Kom', why: 'jij staat achter het werkwoord: geen t. Kom jij?' },
        { t: 'jij' },
        { t: 'donderdag' },
        { t: 'naar' },
        { t: 'het' },
        { t: 'overleg?' },
        { t: 'Groetjes,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Alle vijf gevonden',
        text: 'ik werk, wij verhuizen, ik leef, ik zet, kom jij. Steeds dezelfde vraag: wie is het onderwerp, en hoe luidt de stam?',
      },
    },
    {
      kind: 'swipe',
      id: 'stam-swipe',
      prompt: 'Goed of fout?',
      intro: 'Veeg naar rechts als de zin goed is, naar links als hij fout is.',
      cards: [
        { t: 'Ik loopt elke dag naar mijn werk.', ok: false, fix: 'Ik loop', why: 'Bij ik alleen de stam, zonder t.' },
        { t: 'Morgen werk jij toch thuis?', ok: true, why: 'jij staat achter het werkwoord: geen t.' },
        { t: 'Wij loopen samen naar school.', ok: false, fix: 'Wij lopen', why: 'Het hele werkwoord is lopen: lo-pen, open lettergreep, één o.' },
        { t: 'Kookt je vader vanavond?', ok: true, why: 'je = jouw. Het onderwerp is je vader, dus stam + t.' },
        { t: 'Mijn zus reizt veel voor haar werk.', ok: false, fix: 'reist', why: 'reizen → reis. Met t: reist. Nooit zt.' },
        { t: 'Hij praat te snel.', ok: true, why: 'De stam praat eindigt al op t. Er komt geen tweede t bij.' },
        { t: 'Ik geloov je niet.', ok: false, fix: 'Ik geloof', why: 'Geen v aan het eind van de stam: geloof.' },
        { t: 'Ik zie je morgen!', ok: true, why: 'zien → zie. Bij ik geen t.' },
      ],
    },
    {
      kind: 'dictation',
      id: 'dictee-werk',
      prompt: 'Luister en typ de zin.',
      sentence: 'Werk jij morgen thuis of ga je naar kantoor?',
      right: 'Goed: werk jij en ga je, zonder t, want jij en je staan achter het werkwoord.',
      wrong: 'Let op: Werk jij (geen t) en ga je (stam ga, met één a). Vergeet het vraagteken niet.',
    },
    {
      kind: 'bet',
      id: 'je-moeder',
      prompt: 'Welke vraag is goed geschreven?',
      intro: 'Kijk goed wat je hier betekent.',
      options: ['Werkt je moeder morgen?', 'Werk je moeder morgen?'],
      answer: 'Werkt je moeder morgen?',
      why: 'Hier betekent je hetzelfde als jouw. Het onderwerp is je moeder, en dat is een zij. Dus stam + t: werkt.',
    },
    {
      kind: 'rewrite',
      id: 'hij-verhuist',
      prompt: 'Schrijf de zin met Hij in plaats van Wij.',
      source: 'Wij verhuizen in mei naar Almere.',
      accept: ['Hij verhuist in mei naar Almere.'],
      why: 'Stam verhuis (z wordt s), en bij hij komt er een t bij: verhuist.',
    },
    {
      kind: 'type',
      id: 'wordt',
      prompt: 'Typ de goede vorm van worden.',
      before: 'Mijn dochter',
      after: 'morgen tien jaar.',
      hint: 'worden, bij zij',
      answer: 'wordt',
      why: 'Stam word + t: wordt. Je hoort de d niet, maar hij hoort bij de stam.',
    },
    {
      kind: 'choice',
      id: 'ga-jij',
      prompt: 'Kies de goede vorm.',
      before: '',
      after: 'jij zaterdag mee naar de markt?',
      options: ['Ga', 'Gaat', 'Gaa', 'Gaan'],
      answer: 'Ga',
      why: 'jij staat achter het werkwoord: alleen de stam. De stam van gaan is ga, met één a.',
    },
    {
      kind: 'fix',
      id: 'loopen',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Jullie loopen elke ochtend naar het station.',
      wrong: 1,
      answer: 'lopen',
      why: 'Bij jullie het hele werkwoord: lopen. lo-pen eindigt de eerste lettergreep op een klinker, dus één o.',
    },
    {
      kind: 'dictation',
      id: 'dictee-leest',
      prompt: 'Luister en typ de zin.',
      sentence: 'Mijn broer leest graag, maar ik kijk liever een film.',
      right: 'Goed: hij leest (stam lees + t) en ik kijk (alleen de stam).',
      wrong: 'Let op: leest met ee en s (van lezen), en ik kijk zonder t.',
    },
    {
      kind: 'write',
      id: 'mijn-week',
      prompt: 'Schrijf een appje aan een vriend over je week.',
      intro: 'Schrijf minstens 25 woorden. Gebruik een zin met ik, een zin over iemand anders (hij of zij) en een vraag met jij of je.',
      minWords: 25,
      must: [
        { label: 'Een zin met ik', hint: 'ik werk, ik ga', test: { anyWord: ['ik'] } },
        { label: 'Een zin met hij of zij', hint: 'hij werkt, zij leest', test: { anyWord: ['hij', 'zij', 'ze'] } },
        { label: 'Een vraag met jij of je', hint: 'Kom jij…?', test: { pattern: '\\b(jij|je)\\b[^.!?]*\\?', flags: 'i' } },
      ],
      starters: ['Hoi! Deze week werk ik', 'Mijn zus', 'Kom jij'],
      why: 'Controleer elk werkwoord: ik + stam, hij of zij + stam + t, en geen t als jij of je achter het werkwoord staat.',
    },
  ],
};
