import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": van het hele werkwoord naar de stam, en de stam in de tegenwoordige tijd (ik, jij, hij, wij). */
export const LES_G25: LessonInput = {
  id: 'g25',
  stage: 'regels',
  domain: 'morf',
  also: ['orth'],
  title: 'Werkwoorden: de stam',
  skill: 'Spelling',
  icon: 'stam',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Zo vind je de stam',
      panels: [
        {
          text: 'Het *hele werkwoord* is de vorm uit het woordenboek: *werken*, *fietsen*, *wachten*. Haal je de *-en* eraf, dan houd je de *stam* over: *werk*, *fiets*, *wacht*. De stam is de vorm bij *ik*: *ik werk*, *ik fiets*, *ik wacht*. Met de stam maak je bijna alle andere vormen. Daarom moet je hem goed kunnen schrijven.',
          rule: 'Stam = hele werkwoord min *-en*. Bij *ik* schrijf je alleen de stam: *ik werk*.',
          build: {
            before: 'Elke dag … ik tot vijf uur. (werken)',
            stem: 'werk',
            endings: ['', 't', 'en', 'e'],
            answer: '',
            note: 'Bij ik komt er niets achter de stam: ik werk. Ik werkt en ik werken zijn fout.',
          },
        },
        {
          text: 'Soms moet je de stam even aanpassen. Dat komt door de regels voor lettergrepen. In *lo-pen* staat de *o* aan het eind van een lettergreep: één letter is genoeg. In de stam *loop* is de lettergreep gesloten: dan heb je twee letters nodig voor de lange klank. Zo ook *maken* → *maak*, *horen* → *hoor*, *sturen* → *stuur*, *eten* → *eet*. En andersom: in *zet-ten* staat een dubbele letter. Aan het eind van een woord schrijf je geen dubbele medeklinker (op een paar leenwoorden na, zoals *ik stress*). Dus *zetten* → *zet*, *bellen* → *bel*, *pakken* → *pak*.',
          rule: 'Lange klank in de stam: twee letters (*lopen* → *loop*). Dubbele medeklinker aan het eind: één letter (*zetten* → *zet*).',
          paradigm: {
            q: 'Vul de stam in',
            cols: ['ik …'],
            rows: [
              { label: 'lopen', cells: [{ fill: 'loop', hint: 'Lange o in een gesloten lettergreep: twee letters.' }] },
              { label: 'maken', cells: [{ fill: 'maak', hint: 'ma-ken: in de stam wordt de lettergreep gesloten, dus aa.' }] },
              { label: 'sturen', cells: [{ fill: 'stuur', hint: 'Lange u aan het eind van de stam: uu.' }] },
              { label: 'eten', cells: [{ fill: 'eet', hint: 'Lange e in een gesloten lettergreep: ee.' }] },
              { label: 'zetten', cells: [{ fill: 'zet', hint: 'Geen dubbele t aan het eind van een woord.' }] },
              { label: 'bellen', cells: [{ fill: 'bel', hint: 'De dubbele l was er alleen voor de korte klank in bel-len.' }] },
            ],
            extra: ['lop', 'mak', 'stur', 'zett', 'bell'],
            note: 'Lange klank: twee letters (loop, maak, stuur, eet). Dubbele medeklinker: één letter (zet, bel).',
          },
        },
        {
          text: 'Nog een aanpassing: aan het eind van de stam schrijf je nooit een *v* of een *z*. Daar wordt het een *f* of een *s*, want dat hoor je ook. *Leven* → *ik leef*, *geloven* → *ik geloof*, *schrijven* → *ik schrijf*, *reizen* → *ik reis*, *verhuizen* → *ik verhuis*, *lezen* → *ik lees*. Let op: bij *lezen* gebeuren er twee dingen tegelijk: *z* wordt *s* en de lange klank krijgt twee letters. Bij *ch* en *ng* verandert er niets: *lachen* → *ik lach*, *zingen* → *ik zing*.',
          rule: 'Geen *v* of *z* aan het eind van de stam: *leven* → *leef*, *reizen* → *reis*.',
          lab: {
            label: 'Tik een werkwoord',
            chips: [
              { k: 'leven', out: 'ik leef', note: 'v wordt f. De lange e krijgt twee letters: leef.' },
              { k: 'schrijven', out: 'ik schrijf', note: 'v wordt f. ij blijft ij.' },
              { k: 'reizen', out: 'ik reis', note: 'z wordt s. ei blijft ei.' },
              { k: 'lezen', out: 'ik lees', note: 'Twee aanpassingen: z wordt s, en de lange e krijgt twee letters.' },
              { k: 'durven', out: 'ik durf', note: 'v wordt f. De korte u blijft gewoon één letter.' },
              { k: 'lachen', out: 'ik lach', note: 'ch blijft ch. Hier verandert niets.' },
            ],
          },
        },
        {
          text: 'Nu de persoonsvorm in de tegenwoordige tijd. *Ik*: alleen de stam (*ik loop*). *Jij*, *je*, *u*, *hij*, *zij* (één persoon) en *het*: stam + *t* (*jij loopt*, *u loopt*, *hij loopt*). *Wij*, *jullie* en *zij* (meer personen): het hele werkwoord (*wij lopen*, *jullie lopen*). Let op: bij het hele werkwoord gaan de aanpassingen terug: *ik reis*, maar *wij reizen*; *ik zet*, maar *wij zetten*.',
          rule: '*ik* + stam. *jij*, *u*, *hij*, *zij*, *het* + stam + *t*. *wij*, *jullie*, *zij* (meer) + hele werkwoord.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik', 'jij', 'wij'],
            rows: [
              { label: 'lopen', cells: [{ fill: 'loop' }, { fill: 'loopt' }, { fill: 'lopen', hint: 'Het hele werkwoord: lo-pen, met één o.' }] },
              { label: 'reizen', cells: [{ fill: 'reis' }, { fill: 'reist', hint: 'Stam reis + t.' }, { fill: 'reizen', hint: 'Het hele werkwoord heeft weer een z.' }] },
              { label: 'zetten', cells: [{ fill: 'zet' }, { fill: 'zet', hint: 'De stam eindigt al op t. Er komt geen tweede t bij.' }, { fill: 'zetten' }] },
              { label: 'maken', cells: [{ fill: 'maak' }, { fill: 'maakt' }, { fill: 'maken' }] },
            ],
            extra: ['loopen', 'reizt', 'zett', 'maaken'],
            note: 'Eén stam, drie vormen. En het hele werkwoord krijgt zijn eigen spelling terug: lopen, reizen, zetten, maken.',
          },
        },
        {
          text: 'Korte werkwoorden als *gaan*, *staan*, *slaan*, *zien* en *doen* hebben geen *-en* om eraf te halen. Hun stam is: *ga*, *sta*, *sla*, *zie*, *doe*. *Ik ga* schrijf je met één *a*, want aan het eind van een woord is één *a* genoeg (zoals in *pa* en *ja*). Met een *t* erachter wordt de lettergreep gesloten: *hij gaat*, *jij staat*. *Zie* en *doe* blijven gewoon *ie* en *oe*: *hij ziet*, *zij doet*.',
          rule: '*gaan* → *ik ga*, *hij gaat*. *zien* → *ik zie*, *hij ziet*. *doen* → *ik doe*, *hij doet*.',
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Ik ga morgen naar de markt.', 'Ik gaa morgen naar de markt.', 'Ik gaat morgen naar de markt.'],
            answer: 'Ik ga morgen naar de markt.',
            why: 'Bij ik alleen de stam: ga. Aan het eind van een woord schrijf je één a. Hij gaat krijgt wel twee a’s, want daar staat de t achter.',
          },
          deep: {
            q: 'En hebben, zijn en kunnen?',
            a: 'Een paar heel gewone werkwoorden volgen de regel niet. Die leer je apart: *ik heb*, *jij hebt*, *hij heeft*; *ik ben*, *jij bent*, *hij is*; *ik kan*, *ik wil*, *ik zal*, *ik mag*. Je ziet ze zo vaak dat je ze snel kent.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'aanpassing',
      prompt: 'Wat gebeurt er als je de stam maakt?',
      buckets: ['lange klank: twee letters', 'dubbele letter wordt één', 'v of z wordt f of s', 'alleen -en eraf'],
      items: [
        { t: 'vragen', b: 0 },
        { t: 'zeggen', b: 1 },
        { t: 'verven', b: 2 },
        { t: 'vermijden', b: 3 },
        { t: 'huren', b: 0 },
        { t: 'wennen', b: 1 },
        { t: 'verhuizen', b: 2 },
        { t: 'scheiden', b: 3 },
        { t: 'vegen', b: 0 },
        { t: 'missen', b: 1 },
        { t: 'sterven', b: 2 },
        { t: 'antwoorden', b: 3 },
        { t: 'nemen', b: 0 },
        { t: 'liggen', b: 1 },
        { t: 'bewijzen', b: 2 },
        { t: 'bouwen', b: 3 },
      ],
      why: 'vraag, huur, veeg, neem: de lange klank krijgt twee letters. zeg, wen, mis, lig: geen dubbele letter aan het eind. verf, verhuis, sterf, bewijs: v wordt f en z wordt s. vermijd, scheid, antwoord, bouw: alleen -en eraf. De d blijft gewoon staan, ook al hoor je een t.',
    },
    {
      kind: 'type',
      id: 'beloof',
      prompt: 'Typ de goede vorm van beloven, in de tegenwoordige tijd.',
      before: 'Ik',
      after: 'je dat ik morgen op tijd ben.',
      hint: '',
      answer: 'beloof',
      why: 'be-lo-ven → beloof. Twee aanpassingen: de v wordt f, en de lange o krijgt in de gesloten lettergreep twee letters. Bij ik geen t.',
    },
    {
      kind: 'choice',
      id: 'lees',
      prompt: 'Kies de goede vorm.',
      before: 'Elke ochtend',
      after: 'ik het nieuws op mijn telefoon.',
      options: ['leest', 'leez', 'lees', 'les'],
      answer: 'lees',
      why: 'lezen → lees: z wordt s en de lange e krijgt twee letters. Bij ik geen t, ook niet als ik achter het werkwoord staat.',
    },
    {
      kind: 'fix',
      id: 'verhuist',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Sinds de scheiding leeft mijn buurman alleen, en hij verhuisd volgende maand naar Gouda.',
      wrong: 9,
      answer: 'verhuist',
      why: 'Stam verhuis (z wordt s), en bij hij komt er een t bij: hij verhuist. Met een d schrijf je het alleen in: hij is verhuisd. leeft was goed: leven → leef + t.',
    },
    {
      kind: 'combine',
      id: 'hij-zetten',
      prompt: 'Maak de goede vorm: onderwerp + werkwoord.',
      a: 'hij',
      b: 'zetten',
      options: ['hij zet', 'hij zett', 'hij zetten', 'hij zets'],
      answer: 'hij zet',
      why: 'Stam zet. Bij hij komt er een t bij, maar de stam eindigt al op t. Twee t’s schrijf je niet: hij zet.',
    },
    {
      kind: 'type',
      id: 'verliest',
      prompt: 'Typ de goede vorm van verliezen, in de tegenwoordige tijd.',
      before: 'Mijn collega',
      after: 'steeds zijn pasje van de parkeergarage.',
      hint: '',
      answer: 'verliest',
      why: 'ver-lie-zen → verlies: de z wordt s. Bij hij komt er een t bij: verliest. Nooit verliezt.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen: jij, je en de t',
      panels: [
        {
          text: 'Staat *jij* of *je* achter het werkwoord? Dan valt de *t* weg. *Jij werkt thuis*, maar *Werk jij thuis?* en *Morgen werk je thuis.* Dat geldt alleen voor *jij* en *je*. Bij *hij*, *zij*, *u* en *het* blijft de *t* gewoon staan: *Werkt hij thuis?*, *Komt u ook?*',
          rule: '*jij* of *je* achter het werkwoord: geen *t* (*Loop jij mee?*). Bij *hij*, *zij*, *u*: wel een *t* (*Loopt hij mee?*).',
          quiz: {
            q: 'Welke vraag is goed?',
            options: ['Kom jij morgen ook?', 'Komt jij morgen ook?', 'Komen jij morgen ook?'],
            answer: 'Kom jij morgen ook?',
            why: 'jij staat achter het werkwoord, dus alleen de stam: kom jij. Maar: jij komt, en komt hij?',
          },
        },
        {
          text: 'Pas op met *je*. Soms betekent *je* hetzelfde als *jouw*: *je broer*, *je moeder*, *je auto*. Dan is *je* niet het onderwerp. Het onderwerp is *je broer*, en dat is een *hij*. Dus: *Werkt je broer morgen?*, met een *t*. Twijfel je? Vervang *je* door *jouw*. Kan dat, dan blijft de *t* staan.',
          rule: '*je* = *jouw*? Dan blijft de *t*: *Werkt je moeder vandaag?*',
          lab: {
            label: 'Tik een vraag',
            chips: [
              { k: 'Loop je mee?', out: 'je = jij → geen t', note: 'Het onderwerp is je (jij), en het staat achter het werkwoord.' },
              { k: 'Loopt je zus mee?', out: 'je = jouw → wel t', note: 'Het onderwerp is je zus. Jouw zus loopt mee: een hij/zij-vorm.' },
              { k: 'Werk jij vandaag?', out: 'jij achter het werkwoord → geen t', note: 'Alleen de stam: werk jij.' },
              { k: 'Werkt je vader vandaag?', out: 'je = jouw → wel t', note: 'Jouw vader werkt: stam + t.' },
              { k: 'Wordt u geholpen?', out: 'u → wel t', note: 'Bij u blijft de t staan, ook achter het werkwoord.' },
            ],
          },
        },
        {
          text: 'Eindigt de stam al op een *t*? Dan komt er geen tweede *t* bij: *ik zet*, *hij zet*; *ik praat*, *zij praat*; *ik eet*, *hij eet*. Eindigt de stam op een *d*? Dan komt de *t* er wél achter, ook al hoor je hem niet: *ik word*, *hij wordt*; *ik vind*, *zij vindt*. Meer daarover leer je bij Het woord.',
          rule: 'Stam op *t*: geen extra *t* (*hij zet*). Stam op *d*: wel *t* erbij (*hij wordt*).',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik', 'hij'],
            rows: [
              { label: 'praten', cells: [{ fill: 'praat' }, { fill: 'praat', hint: 'De stam eindigt al op t: geen tweede t.' }] },
              { label: 'eten', cells: [{ fill: 'eet' }, { fill: 'eet' }] },
              { label: 'worden', cells: [{ fill: 'word', hint: 'Stam: worden min -en.' }, { fill: 'wordt', hint: 'Stam word + t.' }] },
              { label: 'vinden', cells: [{ fill: 'vind' }, { fill: 'vindt', hint: 'Stam vind + t.' }] },
            ],
            extra: ['praatt', 'eett', 'wort', 'vint'],
            note: 'praat en eet: de t zit al in de stam. wordt en vindt: d + t.',
          },
        },
        {
          text: 'Twijfel je? Gebruik dit stappenplan. 1. Neem het hele werkwoord: *verhuizen*. 2. Haal *-en* eraf: *verhuiz*. 3. Pas aan: *z* wordt *s* (en een lange klank krijgt twee letters, een dubbele letter wordt één): *verhuis*. 4. Kijk naar het onderwerp: *ik* → *ik verhuis*; *jij*, *u*, *hij*, *zij* → *hij verhuist*; *wij*, *jullie*, *zij* → het hele werkwoord: *wij verhuizen*. 5. Staat *jij* of *je* achter het werkwoord? Dan geen *t*: *Verhuis jij ook?*',
          rule: 'Hele werkwoord → *-en* eraf → aanpassen → onderwerp bekijken.',
          build: {
            before: 'Mijn buurvrouw … volgende maand naar Gouda. (verhuizen)',
            stem: 'verhui',
            endings: ['st', 'zt', 's', 'zen'],
            answer: 'st',
            note: 'Stam verhuis, en bij zij (één persoon) komt er een t bij: verhuist. Nooit verhuizt.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje',
      prompt: 'Vind de fouten in dit appje aan een collega.',
      intro: 'Kijk bij elk werkwoord: wie is het onderwerp, en hoe schrijf je de stam?',
      header: { to: 'Sanne (collega)' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Sanne,' },
        { t: 'ik' },
        { t: 'werkt', fix: 'werk', why: 'Bij ik alleen de stam: ik werk.' },
        { t: 'vandaag' },
        { t: 'thuis.' },
        { t: 'Mijn' },
        { t: 'zoon' },
        { t: 'is' },
        { t: 'ziek' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'blijf' },
        { t: 'bij' },
        { t: 'hem.' },
        { t: 'Wij' },
        { t: 'verhuisen', fix: 'verhuizen', why: 'Bij wij het hele werkwoord, en dat schrijf je met een z: verhuizen.' },
        { t: 'zaterdag' },
        { t: 'ook' },
        { t: 'nog,' },
        { t: 'dus' },
        { t: 'ik' },
        { t: 'leev', fix: 'leef', why: 'leven → leef: aan het eind van de stam een f.' },
        { t: 'tussen' },
        { t: 'de' },
        { t: 'dozen!' },
        { t: 'Ik' },
        { t: 'zett', fix: 'zet', why: 'zetten → zet: geen dubbele t aan het eind.' },
        { t: 'de' },
        { t: 'planning' },
        { t: 'vanmiddag' },
        { t: 'online.' },
        { t: 'Komt', fix: 'Kom', why: 'jij staat achter het werkwoord: geen t. Kom jij?' },
        { t: 'jij' },
        { t: 'donderdag' },
        { t: 'naar' },
        { t: 'het' },
        { t: 'overleg?' },
        { t: 'Groetjes,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Alle vijf gevonden',
        text: 'ik werk, wij verhuizen, ik leef, ik zet, kom jij. Steeds dezelfde vraag: wie is het onderwerp, en hoe luidt de stam?',
      },
    },
    {
      kind: 'swipe',
      id: 'stam-swipe',
      prompt: 'Goed of fout?',
      intro: 'Veeg naar rechts als de zin goed is, naar links als hij fout is.',
      cards: [
        { t: 'Morgen werk jij toch thuis?', ok: true, why: 'jij staat achter het werkwoord: geen t.' },
        { t: 'Mijn zus reizt veel voor haar werk.', ok: false, fix: 'reist', why: 'reizen → reis. Met t: reist. Nooit zt.' },
        { t: 'Werkt je broer ook bij de gemeente?', ok: true, why: 'je = jouw. Het onderwerp is je broer, dus stam + t.' },
        {
          t: 'Wordt jij ook zo moe van die vergaderingen?',
          ok: false,
          fix: 'Word jij',
          why: 'jij staat achter het werkwoord: geen t. Alleen de stam: word jij.',
        },
        { t: 'Vind jij dit ook een goed plan?', ok: true, why: 'vinden: stam vind, met d. jij staat achter het werkwoord, dus geen t.' },
        { t: 'Ik geloov er niets van.', ok: false, fix: 'Ik geloof', why: 'Geen v aan het eind van de stam: geloof.' },
        { t: 'Wanneer verhuis je naar Almere?', ok: true, why: 'je staat achter het werkwoord: geen t. En z wordt s: verhuis.' },
        {
          t: 'Mijn buurman zett zijn auto altijd voor onze deur.',
          ok: false,
          fix: 'zet',
          why: 'zetten → zet. De stam eindigt al op t: er komt geen tweede t bij.',
        },
        { t: 'Hoe laat begint je cursus?', ok: true, why: 'je = jouw. Het onderwerp is je cursus, dus stam + t: begint.' },
        { t: 'Wij leeven al twintig jaar in deze wijk.', ok: false, fix: 'leven', why: 'Bij wij het hele werkwoord: le-ven, open lettergreep, één e.' },
        { t: 'Ik vermijd de snelweg in de spits.', ok: true, why: 'vermijden → vermijd. De d blijft, en bij ik komt er geen t bij.' },
        { t: 'Lees u de brief nog even door?', ok: false, fix: 'Leest u', why: 'Bij u blijft de t staan, ook achter het werkwoord: Leest u.' },
      ],
    },
    {
      kind: 'dictation',
      id: 'dictee-werk',
      prompt: 'Luister en typ de zin.',
      sentence: 'Werk jij vrijdag thuis of reis je met je zus naar het kantoor in Leiden?',
      right: 'Goed: werk jij en reis je zonder t, want jij en je staan achter het werkwoord. Bij reis wordt de z een s. En je zus betekent jouw zus.',
      wrong: 'Let op: Werk jij (geen t), reis je (geen t, en z wordt s), en een hoofdletter bij Leiden. Vergeet het vraagteken niet.',
    },
    {
      kind: 'bet',
      id: 'je-moeder',
      prompt: 'Welke vraag is goed geschreven?',
      intro: 'Kijk goed wat je hier betekent.',
      options: ['Vind je moeder het goed?', 'Vindt je moeder het goed?', 'Vint je moeder het goed?', 'Vinden je moeder het goed?'],
      answer: 'Vindt je moeder het goed?',
      why: 'Hier betekent je hetzelfde als jouw. Het onderwerp is je moeder, en dat is een zij. Dus stam + t: vind + t = vindt.',
    },
    {
      kind: 'rewrite',
      id: 'hij-verhuist',
      prompt: 'Schrijf de zin met Hij in plaats van Wij. Pas alle werkwoorden aan.',
      source: 'Wij verhuizen in mei en geloven dat wij het daar fijn vinden.',
      accept: ['Hij verhuist in mei en gelooft dat hij het daar fijn vindt.'],
      why: 'verhuizen → verhuis + t (z wordt s). geloven → geloof + t (v wordt f, lange o: oo). vinden → vind + t: vindt.',
    },
    {
      kind: 'type',
      id: 'wordt',
      prompt: 'Typ de goede vorm van worden.',
      before: 'Mijn dochter',
      after: 'morgen tien jaar.',
      hint: '',
      answer: 'wordt',
      why: 'Stam word + t: wordt. Je hoort de d niet, maar hij hoort bij de stam.',
    },
    {
      kind: 'choice',
      id: 'ga-jij',
      prompt: 'Kies de goede vorm.',
      before: '',
      after: 'jij zaterdag mee naar de markt?',
      options: ['Ga', 'Gaat', 'Gaa', 'Gaan'],
      answer: 'Ga',
      why: 'jij staat achter het werkwoord: alleen de stam. De stam van gaan is ga, met één a.',
    },
    {
      kind: 'fix',
      id: 'jullie-rijden',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Mijn man en ik vinden dat jullie zoons te hard rijdt in onze straat.',
      wrong: 10,
      answer: 'rijden',
      why: 'Hier betekent jullie ‘van jullie’. Het onderwerp is jullie zoons: meer personen (zij). Dan schrijf je het hele werkwoord: rijden, zonder t.',
    },
    {
      kind: 'dictation',
      id: 'dictee-leest',
      prompt: 'Luister en typ de twee zinnen.',
      sentence: 'Mijn broer leest elke avond de krant. Ik kijk liever een film of schrijf een brief.',
      right: 'Goed: hij leest (stam lees + t), ik kijk en ik schrijf (alleen de stam, en v wordt f).',
      wrong: 'Let op: leest met ee en s (van lezen), ik kijk zonder t, en ik schrijf met een f.',
    },
    {
      kind: 'write',
      id: 'mijn-week',
      prompt: 'Schrijf een appje aan een vriend over je week.',
      intro: 'Schrijf minstens 25 woorden. Gebruik een zin met ik, een zin over iemand anders (hij of zij) en een vraag met jij of je.',
      minWords: 25,
      must: [
        { label: 'Een zin met ik', hint: 'ik werk, ik ga', test: { anyWord: ['ik'] } },
        { label: 'Een zin met hij of zij', hint: 'hij werkt, zij leest', test: { anyWord: ['hij', 'zij', 'ze'] } },
        { label: 'Een vraag met jij of je', hint: 'Kom jij…?', test: { pattern: '\\b(jij|je)\\b[^.!?]*\\?', flags: 'i' } },
      ],
      starters: ['Hoi! Deze week werk ik', 'Mijn zus', 'Kom jij'],
      why: 'Controleer elk werkwoord: ik + stam, hij of zij + stam + t, en geen t als jij of je achter het werkwoord staat.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Werkwoorden en woorden uit eerdere lessen door elkaar. Kijk steeds naar het onderwerp. Wat je fout doet, komt achteraan terug.',
      items: [
        { q: 'Tegenwoordige tijd van *vinden*', before: 'Mijn baas', after: 'het een goed plan.', a: 'vindt', why: 'Stam vind + t: vindt.' },
        { q: 'Tegenwoordige tijd van *geloven*', before: 'Ik', after: 'er niets van.', a: 'geloof', why: 'v wordt f, en de lange o krijgt twee letters: geloof.' },
        { q: 'Meervoud van *de stad*', before: 'Amsterdam en Rotterdam zijn grote', after: '.', a: 'steden', why: 'stad is een leerwoord: steden.' },
        { q: 'Vorm van *verhuizen*', before: 'Mijn zus', after: 'volgende maand naar Gouda.', a: 'verhuist', why: 'Stam verhuis (z wordt s) + t: verhuist.' },
        { q: 'Tegenwoordige tijd van *worden*', after: 'jij ook zo moe van die vergaderingen?', a: 'Word', why: 'jij staat achter het werkwoord: alleen de stam, word.' },
        {
          q: 'Verkleinwoord van *de bon*',
          before: 'Bewaar het',
          after: 'van de winkel goed.',
          a: 'bonnetje',
          why: 'bon: korte o + n met klemtoon. -etje met nn.',
        },
        { q: 'Tegenwoordige tijd van *zetten*', before: 'Hij', after: 'de vuilnisbak elke dinsdag buiten.', a: 'zet', why: 'De stam zet eindigt al op t: geen tweede t.' },
        { q: 'Tegenwoordige tijd van *lezen*', before: 'Mijn vrouw', after: 'elke avond een uur.', a: 'leest', why: 'Stam lees (z wordt s, lange e: ee) + t.' },
        {
          q: 'Kan het? Dan is het …',
          before: 'Is het',
          after: 'om de afspraak te verzetten?',
          a: 'mogelijk',
          why: 'Je hoort ‘luhk’ aan het eind: -lijk, met ij.',
        },
        { q: 'Tegenwoordige tijd van *durven*', before: 'Ik', after: 'mijn baas niet te bellen.', a: 'durf', why: 'v wordt f aan het eind van de stam: durf.' },
        {
          q: 'Tegenwoordige tijd van *lopen*',
          after: 'jullie elke ochtend naar het station?',
          a: 'Lopen',
          why: 'Bij jullie het hele werkwoord, ook als jullie achter het werkwoord staat: lo-pen, open lettergreep, één o.',
        },
        {
          q: 'Voltooid deelwoord van *verhuizen*',
          before: 'Wij zijn vorig jaar',
          after: '.',
          a: 'verhuisd',
          why: 'verhuizen heeft een z: verhuisde, dus verhuisd met d.',
        },
        { q: 'Tegenwoordige tijd van *vermijden*', before: 'Ik', after: 'de snelweg tijdens de spits.', a: 'vermijd', why: 'Stam vermijd: de d blijft. Bij ik geen t.' },
        { q: 'Vorm van *bellen*', after: 'u morgen even terug?', a: 'Belt', why: 'Bij u blijft de t staan, ook achter het werkwoord: Belt u.' },
        { q: 'Meervoud van *het menu*', before: 'Vergelijk de', after: 'van de twee restaurants.', a: 'menu’s', why: 'menu eindigt op u: ’s.' },
        { q: 'Vorm van *koken*', after: 'je vader vanavond?', a: 'Kookt', why: 'je = jouw. Het onderwerp is je vader: stam kook + t.' },
        { q: 'Tegenwoordige tijd van *koken*', before: 'Wanneer', after: 'jij weer eens voor ons?', a: 'kook', why: 'jij staat achter het werkwoord: alleen de stam, kook.' },
        {
          q: 'Zelfstandig naamwoord bij *breed*',
          before: 'Wat is de',
          after: 'van de kast?',
          a: 'breedte',
          why: 'brede, dus d. Met -te erachter blijft de d staan: breedte.',
        },
        { q: 'Vorm van *schrijven*', before: 'Ik', after: 'je morgen een mail.', a: 'schrijf', why: 'v wordt f aan het eind van de stam: schrijf.' },
        {
          q: 'Tegenwoordige tijd van *verliezen*',
          after: 'jij ook zo vaak je sleutels?',
          a: 'Verlies',
          why: 'Stam verlies (z wordt s). jij staat achter het werkwoord: geen t.',
        },
        {
          q: 'Je bent een paar weken vrij en gaat weg',
          before: 'In de zomer gaan we drie weken op',
          after: '.',
          a: 'vakantie',
          why: 'Je hoort tsie aan het eind: -tie.',
        },
        { q: 'Tegenwoordige tijd van *scheiden*', before: 'Ik', after: 'het afval: plastic, papier en glas.', a: 'scheid', why: 'Stam scheid: de d blijft. Bij ik geen t.' },
        { q: 'Tegenwoordige tijd van *stoppen*', before: 'Bij welke halte', after: 'deze bus?', a: 'stopt', why: 'Stam stop (geen dubbele p aan het eind) + t: stopt.' },
        {
          q: 'Zelfstandig naamwoord bij *lief*',
          before: 'Met veel',
          after: 'gemaakt door oma.',
          a: 'liefde',
          why: 'Voor een medeklinker schrijf je f: liefde.',
        },
        {
          q: 'Vorm van *beloven*',
          before: 'Hij',
          after: 'van alles, maar hij doet niets.',
          a: 'belooft',
          why: 'Stam beloof (v wordt f, lange o: oo) + t: belooft.',
        },
        { q: 'Verkleinwoord van *de praat*', before: 'Ze maakte een', after: 'met de buurvrouw.', a: 'praatje', why: 'Na een t: -je. praatje.' },
        { q: 'Tegenwoordige tijd van *antwoorden*', before: 'Mijn zoon', after: 'nooit op mijn appjes.', a: 'antwoordt', why: 'Stam antwoord + t: antwoordt.' },
      ],
      done: {
        title: 'Reeks klaar',
        text: 'Bij elk werkwoord dezelfde vragen: wat is de stam, en wie is het onderwerp? En bij de andere woorden: welke regel geldt hier?',
      },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail aan. Typ elk woord helemaal.',
      intro: 'In het grijs staat meestal het hele werkwoord. Kijk naar het onderwerp en maak de goede vorm.',
      title: 'Mail aan een nieuwe collega',
      text: 'Hoi Lisa,\n\nWelkom in ons team! Ik {leg|leggen|Bij ik alleen de stam: leg. Geen dubbele g aan het eind.} je even uit hoe het hier gaat. Ik {werk|werken|Bij ik alleen de stam: werk.} op maandag en dinsdag thuis. Op die dagen {bel|bellen|ik staat achter het werkwoord: alleen de stam. Geen dubbele l aan het eind.} ik vooral met klanten. Mijn {collega’s~collegae|meervoud van collega|collega eindigt op a: collega’s, met ’s. (collegae mag ook.)} Ahmed en Sanne zitten naast jouw bureau. Ahmed {weet|weten|Stam weet eindigt al op t: geen tweede t.} alles van de computers en geeft je morgen je {wachtwoord|wachtwoor_|woorden, dus woord met d.}. {Vind|vinden|jij staat achter het werkwoord: geen t. vinden: stam vind, met d.} jij iets niet? Vraag het dan aan hem.\n\nOp woensdag {lunchen|ik lunch → wij …|Bij we het hele werkwoord: lunchen.} we samen in de kantine. Daarna {bespreken|ik bespreek → wij …|Bij we het hele werkwoord: be-spre-ken, open lettergreep, één e.} we de {afspraken|meervoud van afspraak|af-spra-ken: open lettergreep, één a.} voor de week. Dat is {belangrijk|van groot belang|-rijk schrijf je met ij.}, dus wees op tijd. Onze teamleider {heet|heten|Stam heet eindigt al op t: geen tweede t.} Marco. Hij {leest|lezen|Stam lees (z wordt s, lange e: ee) + t.} elke ochtend om negen uur zijn mail en {antwoordt|antwoorden|Stam antwoord + t: antwoordt.} meestal snel.\n\nBij de koffieautomaat {staat|staan|Stam sta + t: staat, met aa.} altijd wel iemand voor een {praatje|praat, klein|Na een t: -je.}. {Komt|komen|je = jouw: het onderwerp is je partner. Dus stam + t.} je partner ook mee naar het teamuitje in juni? Dat is altijd erg {gezellig|fijn en warm samen|ge-zel-lig: korte e, dus ll. Aan het eind -ig.}.\n\nTot morgen!\nRuben',
      why: 'Werkwoorden: ik + stam (leg, werk, bel), hij + stam + t (weet, heet, leest, antwoordt, staat), geen t als jij achter het werkwoord staat (vind jij), wel een t bij je = jouw (komt je partner), en wij of we + het hele werkwoord (lunchen, bespreken). Uit eerdere lessen: collega’s, wachtwoord, afspraken, belangrijk, praatje en gezellig.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen over een drukke week. Hoofdletters en leestekens tellen mee.',
      title: 'Een drukke week',
      sentences: [
        'Elke ochtend zet mijn man koffie en leest hij de krant.',
        'Ik breng de kinderen naar school en fiets daarna naar mijn werk.',
        'Mijn dochter vindt rekenen moeilijk en durft dat niet te zeggen.',
        'Wordt je zoon ook zo moe van al die toetsen?',
        'Volgende maand verhuizen wij naar een groter huis in Almere.',
        'Kom jij dan ook helpen of reis je die week naar Turkije?',
      ],
      right:
        'Alles goed: zet zonder tweede t, leest en vindt met een t, durft met f, wordt je zoon met dt (je = jouw), verhuizen bij wij, en kom jij en reis je zonder t.',
      wrong:
        'Kijk de werkwoorden na. Stam op t: geen tweede t (zet). Stam op d: wel een t (vindt, wordt). v en z worden f en s (durft, reis). Bij wij het hele werkwoord (verhuizen). jij of je achter het werkwoord: geen t (kom jij, reis je), maar je = jouw: wel een t (wordt je zoon).',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail aan de mentor na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'meneer Bakker (mentor van Daan)', subject: 'Daan is erg moe' },
      greeting: 'Beste meneer Bakker,',
      signoff: 'Met vriendelijke groet,\nNadia Amrani',
      tokens: [
        { t: 'Mijn' },
        { t: 'zoon' },
        { t: 'Daan' },
        { t: 'zit' },
        { t: 'sinds' },
        { t: 'september' },
        { t: 'in' },
        { t: 'uw' },
        { t: 'klas.' },
        { t: 'Hij' },
        { t: 'vind', fix: 'vindt', why: 'Stam vind + t: hij vindt.' },
        { t: 'school' },
        { t: 'leuk,' },
        { t: 'maar' },
        { t: 'hij' },
        { t: 'word', fix: 'wordt', why: 'Stam word + t: hij wordt.' },
        { t: 'erg' },
        { t: 'moe' },
        { t: 'van' },
        { t: 'de' },
        { t: 'lange' },
        { t: 'daggen.', fix: 'dagen.', why: 'dag is een leerwoord: dagen, met een lange a.' },
        { t: '’s' },
        { t: 'Nachts', trap: 'Goed: begint een zin met ’s, dan krijgt het woord erna de hoofdletter: ’s Nachts.' },
        { t: 'slaapt' },
        { t: 'hij' },
        { t: 'slecht,' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'geloov', fix: 'geloof', why: 'geloven → geloof: geen v aan het eind van de stam.' },
        { t: 'dat' },
        { t: 'hij' },
        { t: 'zich' },
        { t: 'zorgen' },
        { t: 'maakt' },
        { t: 'over' },
        { t: 'de' },
        { t: 'toetsen.' },
        { t: 'Thuis' },
        { t: 'praat', trap: 'Goed: de stam praat eindigt al op t. Er komt geen tweede t bij.' },
        { t: 'hij' },
        { t: 'er' },
        { t: 'niet' },
        { t: 'graag' },
        { t: 'over.' },
        { t: 'Op' },
        { t: 'elke' },
        { t: 'vraag' },
        { t: 'antwoordt', trap: 'Goed: stam antwoord + t. Je hoort de d niet, maar hij hoort bij de stam.' },
        { t: 'hij' },
        { t: 'met' },
        { t: '‘weet' },
        { t: 'ik' },
        { t: 'niet’.' },
        { t: 'Ik' },
        { t: 'maak' },
        { t: 'me' },
        { t: 'een' },
        { t: 'beetje' },
        { t: 'zorgen' },
        { t: 'om' },
        { t: 'zijn' },
        { t: 'gezondheit.', fix: 'gezondheid.', why: 'gezond + heid. -heid schrijf je altijd met ei en een d.' },
        { t: 'Heeft' },
        { t: 'u' },
        { t: 'tijd' },
        { t: 'voor' },
        { t: 'een' },
        { t: 'gesprek?' },
        { t: 'Ik' },
        { t: 'werkt', fix: 'werk', why: 'Bij ik alleen de stam: ik werk.' },
        { t: 'op' },
        { t: 'maandag' },
        { t: 'en' },
        { t: 'vrijdag' },
        { t: 'thuis.' },
        { t: 'Mijn' },
        { t: 'man' },
        { t: 'reisd', fix: 'reist', why: 'Stam reis (z wordt s) + t: hij reist.' },
        { t: 'veel' },
        { t: 'voor' },
        { t: 'zijn' },
        { t: 'werk,' },
        { t: 'maar' },
        { t: 'hij' },
        { t: 'leest' },
        { t: 'uw' },
        { t: 'mails' },
        { t: 'altijd.' },
        { t: 'Vind', fix: 'Vindt', why: 'Bij u blijft de t staan, ook achter het werkwoord: Vindt u.' },
        { t: 'u' },
        { t: 'het' },
        { t: 'goed' },
        { t: 'als' },
        { t: 'ik' },
        { t: 'u' },
        { t: 'volgende' },
        { t: 'week' },
        { t: 'bel?' },
      ],
      done: {
        title: 'Mail nagekeken',
        text: 'De fouten: vindt, wordt, dagen, geloof, gezondheid, werk, reist en Vindt u. ’s Nachts, praat en antwoordt waren goed.',
      },
    },
  ],
};
