import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": bijvoeglijke naamwoorden met -e, en hoe de lettergreepregels hun spelling bepalen. */
export const LES_G26: LessonInput = {
  id: 'g26',
  stage: 'regels',
  domain: 'orth',
  also: ['morf'],
  title: 'Grote of groote? Bijvoeglijke naamwoorden met -e',
  skill: 'Spelling',
  icon: '-e',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Er komt een -e achter',
      panels: [
        {
          text: 'Een bijvoeglijk naamwoord zegt hoe iets is: *groot*, *rood*, *nieuw*. Staat het vóór een zelfstandig naamwoord, dan krijgt het bijna altijd een *-e*: *de grote tas*, *het grote huis*, *grote huizen*, *een grote tas*. Geen *-e* krijg je bij een het-woord in het enkelvoud na *een*, *geen* of *elk*, of zonder lidwoord: *een groot huis*, *geen groot huis*, *lekker weer*. En staat het bijvoeglijk naamwoord niet vóór het zelfstandig naamwoord, dan ook geen *-e*: *Het huis is groot.*',
          rule: 'Vóór het zelfstandig naamwoord: *-e* (*de grote tas*). Behalve bij een het-woord na *een* (*een groot huis*). Los in de zin: geen *-e* (*Het huis is groot.*).',
          morph: {
            q: 'Kies de goede vorm en verf het voorwerp',
            rounds: [
              {
                thing: 'boek',
                from: 'het boek',
                ask: 'een … boek (rood)',
                effect: 'kleur',
                paint: 'rood',
                options: ['een rood boek', 'een rode boek', 'een roode boek'],
                answer: 'een rood boek',
                note: 'Boek is een het-woord, en er staat een voor: geen -e.',
              },
              {
                thing: 'kast',
                from: 'de kast',
                ask: 'een … kast (geel)',
                effect: 'kleur',
                paint: 'geel',
                options: ['een geel kast', 'een geele kast', 'een gele kast'],
                answer: 'een gele kast',
                note: 'Een de-woord krijgt altijd -e. ge-le: de lettergreep ge- is open, dus één e.',
              },
              {
                thing: 'huis',
                from: 'het huis',
                ask: 'het … huis (wit)',
                effect: 'kleur',
                paint: 'wit',
                options: ['het wite huis', 'het witte huis', 'het wit huis'],
                answer: 'het witte huis',
                note: 'Met het ervoor krijgt ook een het-woord -e. Korte i + t: de t wordt dubbel, wit-te.',
              },
              {
                thing: 'boot',
                from: 'de boot',
                ask: 'de … boot (groen)',
                effect: 'kleur',
                paint: 'groen',
                options: ['de groene boot', 'de groenne boot', 'de groen boot'],
                answer: 'de groene boot',
                note: 'oe blijft oe, en na een lange klank verdubbel je nooit: groene.',
              },
            ],
            note: 'Bijna altijd -e. Alleen een rood boek: een + het-woord. En kijk ook naar de spelling: gele, witte, groene.',
          },
        },
        {
          text: 'Met de *-e* erachter krijg je een extra lettergreep, en dan gelden de regels van open en gesloten lettergrepen. Heeft het woord een lange klank met twee letters (*aa*, *ee*, *oo*, *uu*)? Dan wordt dat er één: de lettergreep is nu open. *groot* → *gro-te*, *raar* → *ra-re*, *duur* → *du-re*, *geel* → *ge-le*, *laag* → *la-ge*, *breed* → *bre-de*.',
          rule: 'Lange klank + *-e*: één letter (*groot* → *grote*, *duur* → *dure*).',
          paradigm: {
            q: 'Zet de vorm met -e in het vakje',
            cols: ['met -e'],
            rows: [
              { label: 'groot', cells: [{ fill: 'grote', hint: 'gro-te: open lettergreep, één o.' }] },
              { label: 'raar', cells: [{ fill: 'rare' }] },
              { label: 'duur', cells: [{ fill: 'dure' }] },
              { label: 'geel', cells: [{ fill: 'gele' }] },
              { label: 'laag', cells: [{ fill: 'lage' }] },
              { label: 'breed', cells: [{ fill: 'brede', hint: 'bre-de: één e, en de d blijft een d.' }] },
            ],
            extra: ['groote', 'raare', 'duure', 'geele', 'breede'],
            note: 'grote, rare, dure, gele, lage, brede: in een open lettergreep is één letter genoeg voor de lange klank.',
          },
        },
        {
          text: 'Een korte klank met één medeklinker erachter? Dan wordt die medeklinker dubbel, zodat de klank kort blijft: *dik* → *dikke*, *wit* → *witte*, *snel* → *snelle*, *smal* → *smalle*, *nat* → *natte*, *fris* → *frisse*. Staan er al twee medeklinkers? Dan verdubbel je niet: *zacht* → *zachte*, *rond* → *ronde*, *warm* → *warme*. En na klanken als *ie*, *oe*, *ui*, *ei*, *ij*, *ou*, *au*, *ooi* en na een *w* verandert er niets: *diepe*, *kleine*, *oude*, *vrije*, *mooie*, *blauwe*, *nieuwe*.',
          rule: 'Korte klank + één medeklinker: dubbel (*dik* → *dikke*). Twee medeklinkers of een vaste klank: alleen *-e* (*zachte*, *kleine*).',
          build: {
            before: 'Het is koud. Neem je … trui mee? (dik)',
            stem: 'dik',
            endings: ['e', 'ke', 'ge', 'ken'],
            answer: 'ke',
            note: 'Korte i + k: de k wordt dubbel. dik-ke.',
          },
        },
        {
          text: 'Eindigt het woord op *f* of *s*? Hoor je met de *-e* een *v* of *z*, dan schrijf je die ook: *lief* → *lieve*, *doof* → *dove*, *braaf* → *brave*, *half* → *halve*, *boos* → *boze*, *grijs* → *grijze*, *wijs* → *wijze*, *vies* → *vieze*. Hoor je nog steeds een *s* of *f*, dan blijft het een *s* of *f*: *los* → *losse*, *fris* → *frisse*, *vals* → *valse*, *laf* → *laffe*. Een *d* of *t* aan het eind blijft altijd zoals hij is: *rond* → *ronde*, *goed* → *goede*, *wit* → *witte*.',
          rule: 'Hoor je *v* of *z*? Schrijf *v* of *z*: *lieve*, *boze*. Hoor je *f* of *s*? Dan blijft het zo: *losse*, *valse*.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'lief', out: 'een lieve hond', note: 'Je hoort een v: lieve.' },
              { k: 'boos', out: 'een boze klant', note: 'Je hoort een z, en de lange o krijgt één letter: bo-ze.' },
              { k: 'grijs', out: 'een grijze kat', note: 'Je hoort een z: grijze.' },
              { k: 'half', out: 'een halve liter', note: 'Je hoort een v: halve.' },
              { k: 'los', out: 'een losse knoop', note: 'Je hoort een s. Korte o, dus dubbel: los-se.' },
              { k: 'vals', out: 'een valse hond', note: 'Je hoort een s: valse.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'wat-gebeurt',
      prompt: 'Wat gebeurt er als er -e achter komt?',
      buckets: ['medeklinker wordt dubbel', 'één klinker minder', 'alleen -e erbij'],
      items: [
        { t: 'nat', b: 0 },
        { t: 'smal', b: 0 },
        { t: 'fris', b: 0 },
        { t: 'dom', b: 0 },
        { t: 'zwaar', b: 1 },
        { t: 'rood', b: 1 },
        { t: 'puur', b: 1 },
        { t: 'kaal', b: 1 },
        { t: 'mooi', b: 2 },
        { t: 'zacht', b: 2 },
        { t: 'warm', b: 2 },
        { t: 'nieuw', b: 2 },
      ],
      why: 'natte, smalle, frisse, domme: korte klank + één medeklinker. zware, rode, pure, kale: de lange klank staat nu in een open lettergreep. mooie, zachte, warme, nieuwe: daar verandert niets.',
    },
    {
      kind: 'type',
      id: 'warme',
      prompt: 'Typ het bijvoeglijk naamwoord in de goede vorm.',
      before: 'Ik heb een',
      after: 'jas gekocht voor de winter. (warm)',
      hint: 'warm + …',
      answer: 'warme',
      why: 'De jas is een de-woord, dus -e. Na rm verdubbel je niet: warme.',
    },
    {
      kind: 'choice',
      id: 'lieve',
      prompt: 'Kies de goede vorm.',
      before: 'Wat een',
      after: 'kat heb je! (lief)',
      options: ['lieve', 'liefe', 'lieffe', 'lief'],
      answer: 'lieve',
      why: 'Met -e hoor je een v: lieve. En ie is een vaste klank, dus niets dubbel.',
    },
    {
      kind: 'fix',
      id: 'groote',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'We wonen in een groote stad met veel parken.',
      wrong: 4,
      answer: 'grote',
      why: 'gro-te: de eerste lettergreep is open, dus één o.',
    },
    {
      kind: 'type',
      id: 'natte',
      prompt: 'Typ het bijvoeglijk naamwoord in de goede vorm.',
      before: 'Doe die',
      after: 'sokken maar in de wasmand. (nat)',
      hint: 'nat + …',
      answer: 'natte',
      why: 'Korte a + t: de t wordt dubbel, nat-te.',
    },
    {
      kind: 'choice',
      id: 'boze',
      prompt: 'Kies de goede vorm.',
      before: 'De',
      after: 'klant wilde de manager spreken. (boos)',
      options: ['boze', 'booze', 'bose', 'boosse'],
      answer: 'boze',
      why: 'Je hoort een z, en bo- is een open lettergreep: één o. Dus boze.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen en uitzonderingen',
      panels: [
        {
          text: 'Eindigt het woord op *-ig*, *-lijk*, *-er* of *-el*? Daar hoor je een doffe e, ook in *-ig* en *-lijk*. Na een doffe e verdubbel je nooit: *gezellig* → *gezellige*, *handig* → *handige*, *vriendelijk* → *vriendelijke*, *lekker* → *lekkere*, *donker* → *donkere*, *simpel* → *simpele*. Dus niet *gezelligge* of *lekkerre*.',
          rule: 'Na *-ig*, *-lijk*, *-er*, *-el*: alleen *-e* erachter, nooit een dubbele letter.',
          mark: {
            q: 'Tik de drie bijvoeglijke naamwoorden',
            sentence: 'Het was een gezellige avond met lekkere hapjes en vriendelijke mensen.',
            targets: [3, 6, 9],
            note: 'gezellige, lekkere en vriendelijke: alleen een -e erachter. De g, r en k worden niet dubbel.',
          },
        },
        {
          text: 'Woorden op *-eel* worden *-ele*: *geel* → *gele*, *heel* → *hele*. Maar staat er een *i* of een *e* vóór *eel*, dan heb je een trema nodig. Anders lees je de klinkers samen als één klank. *financieel* → *financiële*, *officieel* → *officiële*, *commercieel* → *commerciële*, *reëel* → *reële*. Bij *-aal* gaat het gewoon: *ideaal* → *ideale*, *normaal* → *normale*, *speciaal* → *speciale*.',
          rule: '*-ieel* wordt *-iële* (*financiële*), *reëel* wordt *reële*. *-aal* wordt *-ale* (*ideale*).',
          quiz: {
            q: 'Welke spelling is goed?',
            options: ['een financiële kwestie', 'een financiele kwestie', 'een financieele kwestie'],
            answer: 'een financiële kwestie',
            why: 'Zonder trema lees je ie als één klank (zoals in fiets). Het trema laat zien dat de e los klinkt: fi-nan-ci-ë-le.',
          },
        },
        {
          text: 'Soms komt er nooit een *-e*. Bijvoeglijke naamwoorden van een stof die op *-en* eindigen, blijven gelijk: *een houten tafel*, *een gouden ring*, *een wollen trui*, *een zilveren ketting*, *een stenen muur*. Ook andere woorden op *-en* krijgen geen *-e*: *de open deur*, *de gesloten winkel*, *mijn eigen kamer*. En woorden die op een *-e* of een *-a* eindigen, blijven gelijk: *een roze jurk*, *een oranje bal*, *een lila sjaal*, *een prima plan*, *een extra stoel*.',
          rule: 'Geen *-e* na *-en* (*houten*, *gouden*, *open*) en na een *-e* of *-a* (*roze*, *oranje*, *prima*).',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'hout', out: 'een houten tafel', note: 'Van hout: houten. Nooit houtene.' },
              { k: 'goud', out: 'een gouden ring', note: 'Van goud: gouden. Geen -e erachter.' },
              { k: 'wol', out: 'een wollen trui', note: 'Van wol: wollen, met een dubbele l.' },
              { k: 'open', out: 'de open deur', note: 'Eindigt al op -en: geen -e.' },
              { k: 'roze', out: 'een roze jurk', note: 'Eindigt al op een e: blijft gelijk.' },
              { k: 'oranje', out: 'een oranje bal', note: 'Blijft gelijk: nooit oranjee.' },
            ],
          },
        },
        {
          text: 'Twijfel je? Gebruik dit stappenplan. 1. Moet er een *-e* komen? (Vóór het zelfstandig naamwoord meestal wel; na *een* + het-woord en los in de zin niet; na *-en*, *-e* of *-a* nooit.) 2. Lange klank met twee letters? Maak er één van: *groot* → *grote*. 3. Korte klank + één medeklinker? Maak hem dubbel: *dik* → *dikke*. 4. *f* of *s* aan het eind? Luister: hoor je *v* of *z*, schrijf dan *v* of *z*: *lieve*, *boze*. 5. *-ieel*? Trema: *financiële*.',
          rule: 'Eerst: komt er *-e*? Dan: lang → één letter, kort → dubbel, en luister naar *v*/*z*.',
          quiz: {
            q: 'Welke zin is helemaal goed?',
            options: [
              'Een groot huis met een rode deur en een houten hek.',
              'Een grote huis met een roode deur en een houtene hek.',
              'Een groot huis met een rodde deur en een houtene hek.',
            ],
            answer: 'Een groot huis met een rode deur en een houten hek.',
            why: 'een groot huis: een + het-woord, geen -e. een rode deur: de-woord, -e, en ro-de met één o. een houten hek: stofnaam op -en, geen -e.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-huis',
      prompt: 'Vind de vijf fouten in deze mail.',
      intro: 'Kijk naar elk bijvoeglijk naamwoord: lang of kort, v of f, z of s, en komt er wel een -e?',
      header: { to: 'Fatima', subject: 'Ik heb een huis gevonden!' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Fatima,' },
        { t: 'ik' },
        { t: 'heb' },
        { t: 'een' },
        { t: 'leuk' },
        { t: 'huis' },
        { t: 'gevonden!' },
        { t: 'Het' },
        { t: 'heeft' },
        { t: 'een' },
        { t: 'groote', fix: 'grote', why: 'gro-te: open lettergreep, één o.' },
        { t: 'tuin' },
        { t: 'en' },
        { t: 'een' },
        { t: 'witte' },
        { t: 'keuken.' },
        { t: 'In' },
        { t: 'de' },
        { t: 'kamer' },
        { t: 'staat' },
        { t: 'een' },
        { t: 'houtene', fix: 'houten', why: 'Een stofnaam op -en krijgt geen -e: houten.' },
        { t: 'kast.' },
        { t: 'De' },
        { t: 'buren' },
        { t: 'zijn' },
        { t: 'aardig:' },
        { t: 'een' },
        { t: 'oude' },
        { t: 'man' },
        { t: 'met' },
        { t: 'een' },
        { t: 'lieffe', fix: 'lieve', why: 'Je hoort een v: lieve. En na ie verdubbel je niet.' },
        { t: 'hond.' },
        { t: 'Het' },
        { t: 'is' },
        { t: 'een' },
        { t: 'gezelligge', fix: 'gezellige', why: 'Na -ig verdubbel je niet: gezellige.' },
        { t: 'buurt' },
        { t: 'en' },
        { t: 'de' },
        { t: 'huur' },
        { t: 'is' },
        { t: 'een' },
        { t: 'reele', fix: 'reële', why: 'reëel → reële. Zonder trema lees je ee als één klank.' },
        { t: 'prijs.' },
        { t: 'Groetjes,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Vijf fouten verbeterd',
        text: 'grote, houten, lieve, gezellige en reële. En witte en oude waren al goed.',
      },
    },
    {
      kind: 'swipe',
      id: 'bn-swipe',
      prompt: 'Goed of fout?',
      intro: 'Veeg naar rechts als de woordgroep goed is, naar links als hij fout is.',
      cards: [
        { t: 'een dikke trui', ok: true, why: 'Korte i + k: dubbel, dik-ke.' },
        { t: 'een doofe man', ok: false, fix: 'een dove man', why: 'Je hoort een v, en do- is open: één o.' },
        { t: 'een groot huis', ok: true, why: 'een + het-woord: geen -e.' },
        { t: 'de smale straat', ok: false, fix: 'de smalle straat', why: 'smal heeft een korte a: de l wordt dubbel.' },
        { t: 'een gouden ketting', ok: true, why: 'Stofnaam op -en: geen -e.' },
        { t: 'de grijse lucht', ok: false, fix: 'de grijze lucht', why: 'Je hoort een z: grijze.' },
        { t: 'een frisse neus', ok: true, why: 'Je hoort een s, en de korte i maakt de s dubbel.' },
        { t: 'een lekkerre taart', ok: false, fix: 'een lekkere taart', why: 'Na -er (doffe e) verdubbel je niet.' },
      ],
    },
    {
      kind: 'dictation',
      id: 'dictee-buurvrouw',
      prompt: 'Luister en typ de zin.',
      sentence: 'Onze lieve buurvrouw heeft een grijze kat en twee dikke honden.',
      right: 'Goed: lieve met v, grijze met z en dikke met kk.',
      wrong: 'Let op: lieve (v), grijze (z) en dikke (korte i, dus kk).',
    },
    {
      kind: 'bet',
      id: 'wollen',
      prompt: 'Je oma breit een trui van wol. Hoe schrijf je het?',
      options: ['een wollen trui', 'een wollene trui', 'een wolle trui'],
      answer: 'een wollen trui',
      why: 'Een stofnaam op -en krijgt geen -e: wollen, houten, gouden, zilveren.',
    },
    {
      kind: 'type',
      id: 'financiele',
      prompt: 'Typ het bijvoeglijk naamwoord in de goede vorm.',
      before: 'Ik zoek een',
      after: 'adviseur voor mijn bedrijf. (financieel)',
      hint: 'met trema',
      answer: 'financiële',
      why: 'financieel → financiële. Het trema op de e laat zien dat ie hier geen ie-klank is: fi-nan-ci-ë-le.',
    },
    {
      kind: 'speed',
      id: 'los-of-vast',
      prompt: 'Aan elkaar of los?',
      intro: 'Met -e staat het bijvoeglijk naamwoord los: een grote tas. Zonder -e plakt het soms vast aan het woord, en dan is het één woord met een eigen betekenis: grootmoeder (je oma).',
      seconds: 40,
      items: [
        { a: 'groot', b: 'moeder', joined: true, tip: 'grootmoeder: je oma. Eén woord.' },
        { a: 'grote', b: 'tas', joined: false, tip: 'een grote tas: een tas die groot is.' },
        { a: 'rood', b: 'borst', joined: true, tip: 'roodborst: de vogel.' },
        { a: 'rode', b: 'wijn', joined: false, tip: 'rode wijn: twee woorden.' },
        { a: 'snel', b: 'weg', joined: true, tip: 'snelweg: de autoweg.' },
        { a: 'snelle', b: 'trein', joined: false, tip: 'een snelle trein: een trein die snel is.' },
        { a: 'klein', b: 'geld', joined: true, tip: 'kleingeld: munten.' },
        { a: 'kleine', b: 'kinderen', joined: false, tip: 'kleine kinderen: twee woorden.' },
      ],
      done: {
        title: 'Los of vast',
        text: 'Met -e bijna altijd los. Zonder -e en met een eigen betekenis: één woord, zoals grootmoeder, snelweg en kleingeld.',
      },
    },
    {
      kind: 'rewrite',
      id: 'kleine-kamer',
      prompt: 'Schrijf de zin opnieuw. Begin met: Het is een … kamer. Gebruik beide bijvoeglijke naamwoorden, met en ertussen.',
      source: 'De kamer is klein en donker.',
      accept: ['Het is een kleine en donkere kamer.'],
      why: 'Vóór kamer (een de-woord) krijgen beide een -e: kleine en donkere. Na -er geen dubbele r.',
    },
    {
      kind: 'choice',
      id: 'ideale',
      prompt: 'Kies de goede vorm.',
      before: 'Dit is de',
      after: 'plek voor een picknick. (ideaal)',
      options: ['ideale', 'ideaale', 'idealle', 'ideaal'],
      answer: 'ideale',
      why: 'i-de-a-le: de lange a staat in een open lettergreep, dus één a.',
    },
    {
      kind: 'fix',
      id: 'zachtte',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Dit kussen heeft een heel zachtte stof.',
      wrong: 5,
      answer: 'zachte',
      why: 'zacht eindigt op twee medeklinkers (ch en t). Dan verdubbel je niet: zachte.',
    },
  ],
};
