import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": bijvoeglijke naamwoorden met -e, en hoe de lettergreepregels hun spelling bepalen. */
export const LES_G26: LessonInput = {
  id: 'g26',
  stage: 'regels',
  domain: 'orth',
  also: ['morf'],
  title: 'Grote of groote? Bijvoeglijke naamwoorden met -e',
  skill: 'Spelling',
  icon: '-e',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Er komt een -e achter',
      panels: [
        {
          text: 'Een bijvoeglijk naamwoord zegt hoe iets is: *groot*, *rood*, *nieuw*. Staat het vóór een zelfstandig naamwoord, dan krijgt het bijna altijd een *-e*: *de grote tas*, *het grote huis*, *grote huizen*, *een grote tas*. Geen *-e* krijg je bij een het-woord in het enkelvoud na *een*, *geen* of *elk*, of zonder lidwoord: *een groot huis*, *geen groot huis*, *lekker weer*. En staat het bijvoeglijk naamwoord niet vóór het zelfstandig naamwoord, dan ook geen *-e*: *Het huis is groot.*',
          rule: 'Vóór het zelfstandig naamwoord: *-e* (*de grote tas*). Behalve bij een het-woord na *een* (*een groot huis*). Los in de zin: geen *-e* (*Het huis is groot.*).',
          morph: {
            q: 'Kies de goede vorm en verf het voorwerp',
            rounds: [
              {
                thing: 'boek',
                from: 'het boek',
                ask: 'een … boek (rood)',
                effect: 'kleur',
                paint: 'rood',
                options: ['een rood boek', 'een rode boek', 'een roode boek'],
                answer: 'een rood boek',
                note: 'Boek is een het-woord, en er staat een voor: geen -e.',
              },
              {
                thing: 'kast',
                from: 'de kast',
                ask: 'een … kast (geel)',
                effect: 'kleur',
                paint: 'geel',
                options: ['een geel kast', 'een geele kast', 'een gele kast'],
                answer: 'een gele kast',
                note: 'Kast is een de-woord: er komt -e achter. ge-le: de lettergreep ge- is open, dus één e.',
              },
              {
                thing: 'huis',
                from: 'het huis',
                ask: 'het … huis (wit)',
                effect: 'kleur',
                paint: 'wit',
                options: ['het wite huis', 'het witte huis', 'het wit huis'],
                answer: 'het witte huis',
                note: 'Met het ervoor krijgt ook een het-woord -e. Korte i + t: de t wordt dubbel, wit-te.',
              },
              {
                thing: 'boot',
                from: 'de boot',
                ask: 'de … boot (groen)',
                effect: 'kleur',
                paint: 'groen',
                options: ['de groene boot', 'de groenne boot', 'de groen boot'],
                answer: 'de groene boot',
                note: 'oe blijft oe, en na een lange klank verdubbel je nooit: groene.',
              },
            ],
            note: 'Bijna altijd -e. Alleen een rood boek: een + het-woord. En kijk ook naar de spelling: gele, witte, groene.',
          },
        },
        {
          text: 'Met de *-e* erachter krijg je een extra lettergreep, en dan gelden de regels van open en gesloten lettergrepen. Heeft het woord een lange klank met twee letters (*aa*, *ee*, *oo*, *uu*)? Dan wordt dat er één: de lettergreep is nu open. *groot* → *gro-te*, *raar* → *ra-re*, *duur* → *du-re*, *geel* → *ge-le*, *laag* → *la-ge*, *breed* → *bre-de*.',
          rule: 'Lange klank + *-e*: één letter (*groot* → *grote*, *duur* → *dure*).',
          paradigm: {
            q: 'Zet de vorm met -e in het vakje',
            cols: ['met -e'],
            rows: [
              { label: 'groot', cells: [{ fill: 'grote', hint: 'gro-te: open lettergreep, één o.' }] },
              { label: 'raar', cells: [{ fill: 'rare' }] },
              { label: 'duur', cells: [{ fill: 'dure' }] },
              { label: 'geel', cells: [{ fill: 'gele' }] },
              { label: 'laag', cells: [{ fill: 'lage' }] },
              { label: 'breed', cells: [{ fill: 'brede', hint: 'bre-de: één e, en de d blijft een d.' }] },
            ],
            extra: ['groote', 'raare', 'duure', 'geele', 'breede'],
            note: 'grote, rare, dure, gele, lage, brede: in een open lettergreep is één letter genoeg voor de lange klank.',
          },
        },
        {
          text: 'Een korte klank met één medeklinker erachter? Dan wordt die medeklinker dubbel, zodat de klank kort blijft: *dik* → *dikke*, *wit* → *witte*, *snel* → *snelle*, *smal* → *smalle*, *nat* → *natte*, *fris* → *frisse*. Staan er al twee medeklinkers? Dan verdubbel je niet: *zacht* → *zachte*, *rond* → *ronde*, *warm* → *warme*. En na klanken als *ie*, *oe*, *ui*, *ei*, *ij*, *ou*, *au*, *ooi* en na een *w* verandert er niets: *diepe*, *kleine*, *oude*, *vrije*, *mooie*, *blauwe*, *nieuwe*.',
          rule: 'Korte klank + één medeklinker: dubbel (*dik* → *dikke*). Twee medeklinkers of een vaste klank: alleen *-e* (*zachte*, *kleine*).',
          build: {
            before: 'Het is koud. Neem je … trui mee? (dik)',
            stem: 'dik',
            endings: ['e', 'ke', 'ge', 'ken'],
            answer: 'ke',
            note: 'Korte i + k: de k wordt dubbel. dik-ke.',
          },
        },
        {
          text: 'Eindigt het woord op *f* of *s*? Hoor je met de *-e* een *v* of *z*, dan schrijf je die ook: *lief* → *lieve*, *doof* → *dove*, *braaf* → *brave*, *half* → *halve*, *boos* → *boze*, *grijs* → *grijze*, *wijs* → *wijze*, *vies* → *vieze*. Hoor je nog steeds een *s* of *f*, dan blijft het een *s* of *f*: *los* → *losse*, *fris* → *frisse*, *vals* → *valse*, *laf* → *laffe*. Een *d* of *t* aan het eind blijft altijd zoals hij is: *rond* → *ronde*, *goed* → *goede*, *wit* → *witte*.',
          rule: 'Hoor je *v* of *z*? Schrijf *v* of *z*: *lieve*, *boze*. Hoor je *f* of *s*? Dan blijft het zo: *losse*, *valse*.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'lief', out: 'een lieve hond', note: 'Je hoort een v: lieve.' },
              { k: 'boos', out: 'een boze klant', note: 'Je hoort een z, en de lange o krijgt één letter: bo-ze.' },
              { k: 'grijs', out: 'een grijze kat', note: 'Je hoort een z: grijze.' },
              { k: 'half', out: 'een halve liter', note: 'Je hoort een v: halve.' },
              { k: 'los', out: 'een losse knoop', note: 'Je hoort een s. Korte o, dus dubbel: los-se.' },
              { k: 'vals', out: 'een valse hond', note: 'Je hoort een s: valse.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'wat-gebeurt',
      prompt: 'Wat gebeurt er als er -e achter komt?',
      buckets: ['medeklinker wordt dubbel', 'één klinker minder', 'f wordt v, s wordt z', 'alleen -e erbij'],
      items: [
        { t: 'stug', b: 0 },
        { t: 'glad', b: 0 },
        { t: 'los', b: 0 },
        { t: 'stom', b: 0 },
        { t: 'kaal', b: 1 },
        { t: 'wreed', b: 1 },
        { t: 'traag', b: 1 },
        { t: 'gemeen', b: 1 },
        { t: 'vies', b: 2 },
        { t: 'actief', b: 2 },
        { t: 'grijs', b: 2 },
        { t: 'nerveus', b: 2 },
        { t: 'bang', b: 3 },
        { t: 'praktisch', b: 3 },
        { t: 'nieuw', b: 3 },
        { t: 'stevig', b: 3 },
      ],
      why: 'stugge, gladde, losse, stomme: korte klank + één medeklinker, dus dubbel. Bij los hoor je nog een s. kale, wrede, trage, gemene: de lange klank staat nu in een open lettergreep. vieze, actieve, grijze, nerveuze: je hoort een z of een v. bange, praktische, nieuwe, stevige: na ng, sch, w en -ig verandert er niets.',
    },
    {
      kind: 'type',
      id: 'kosteloze',
      prompt: 'Typ het bijvoeglijk naamwoord in de goede vorm.',
      before: 'Maak gebruik van ons',
      after: 'advies. (kosteloos)',
      hint: '',
      answer: 'kosteloze',
      why: 'Na ons krijgt ook een het-woord een -e. Je hoort een z, en lo- is een open lettergreep: één o. Dus kosteloze.',
    },
    {
      kind: 'choice',
      id: 'lief-hondje',
      prompt: 'Kies de goede vorm.',
      before: 'Wat een',
      after: 'hondje heb je! (lief)',
      options: ['lieve', 'lief', 'lieffe', 'liefe'],
      answer: 'lief',
      why: 'Een verkleinwoord is altijd een het-woord. Na een (ook in wat een) krijgt een het-woord geen -e: een lief hondje.',
    },
    {
      kind: 'fix',
      id: 'nieuw-toilet',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Na de verbouwing hebben we een nieuwe badkamer en een nieuwe toilet.',
      wrong: 10,
      answer: 'nieuw',
      why: 'Het toilet is een het-woord, en er staat een voor: geen -e. De badkamer is een de-woord, dus daar is nieuwe goed.',
    },
    {
      kind: 'type',
      id: 'draadloos',
      prompt: 'Typ het bijvoeglijk naamwoord in de goede vorm.',
      before: 'Het hotel biedt gratis',
      after: 'internet. (draadloos)',
      hint: '',
      answer: 'draadloos',
      why: 'Internet is een het-woord, en er staat geen lidwoord voor: geen -e. Met een de-woord wordt het wel draadloze: de draadloze muis.',
    },
    {
      kind: 'choice',
      id: 'boze',
      prompt: 'Kies de goede vorm.',
      before: 'De',
      after: 'klant wilde de manager spreken. (boos)',
      options: ['booze', 'boze', 'bose', 'boos'],
      answer: 'boze',
      why: 'De klant is een de-woord, dus -e. Je hoort een z, en bo- is een open lettergreep: één o. Dus boze.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen en uitzonderingen',
      panels: [
        {
          text: 'Eindigt het woord op *-ig*, *-lijk*, *-er* of *-el*? Daar hoor je een doffe e, ook in *-ig* en *-lijk*. Na een doffe e verdubbel je nooit: *gezellig* → *gezellige*, *handig* → *handige*, *vriendelijk* → *vriendelijke*, *lekker* → *lekkere*, *donker* → *donkere*, *simpel* → *simpele*. Dus niet *gezelligge* of *lekkerre*.',
          rule: 'Na *-ig*, *-lijk*, *-er*, *-el*: alleen *-e* erachter, nooit een dubbele letter.',
          mark: {
            q: 'Tik de drie bijvoeglijke naamwoorden',
            sentence: 'Het was een gezellige avond met lekkere hapjes en vriendelijke mensen.',
            targets: [3, 6, 9],
            note: 'gezellige, lekkere en vriendelijke: alleen een -e erachter. De g, r en k worden niet dubbel.',
          },
        },
        {
          text: 'Woorden op *-eel* worden *-ele*: *geel* → *gele*, *heel* → *hele*. Maar staat er een *i* of een *e* vóór *eel*, dan heb je een trema nodig. Anders lees je de klinkers samen als één klank. *financieel* → *financiële*, *officieel* → *officiële*, *commercieel* → *commerciële*, *reëel* → *reële*. Bij *-aal* gaat het gewoon: *ideaal* → *ideale*, *normaal* → *normale*, *speciaal* → *speciale*.',
          rule: '*-ieel* wordt *-iële* (*financiële*), *reëel* wordt *reële*. *-aal* wordt *-ale* (*ideale*).',
          quiz: {
            q: 'Welke spelling is goed?',
            options: ['een financiële kwestie', 'een financiele kwestie', 'een financieele kwestie'],
            answer: 'een financiële kwestie',
            why: 'Zonder trema lees je ie als één klank (zoals in fiets). Het trema laat zien dat de e los klinkt: fi-nan-ci-ë-le.',
          },
        },
        {
          text: 'Soms komt er nooit een *-e*. Bijvoeglijke naamwoorden van een stof die op *-en* eindigen, blijven gelijk: *een houten tafel*, *een gouden ring*, *een wollen trui*, *een zilveren ketting*, *een stenen muur*. Ook andere woorden op *-en* krijgen geen *-e*: *de open deur*, *de gesloten winkel*, *mijn eigen kamer*. En woorden die op een *-e* of een *-a* eindigen, blijven gelijk: *een roze jurk*, *een oranje bal*, *een lila sjaal*, *een prima plan*, *een extra stoel*.',
          rule: 'Geen *-e* na *-en* (*houten*, *gouden*, *open*) en na een *-e* of *-a* (*roze*, *oranje*, *prima*).',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'hout', out: 'een houten tafel', note: 'Van hout: houten. Nooit houtene.' },
              { k: 'goud', out: 'een gouden ring', note: 'Van goud: gouden. Geen -e erachter.' },
              { k: 'wol', out: 'een wollen trui', note: 'Van wol: wollen, met een dubbele l.' },
              { k: 'open', out: 'de open deur', note: 'Eindigt al op -en: geen -e.' },
              { k: 'roze', out: 'een roze jurk', note: 'Eindigt al op een e: blijft gelijk.' },
              { k: 'oranje', out: 'een oranje bal', note: 'Blijft gelijk: nooit oranjee.' },
            ],
          },
        },
        {
          text: 'Twijfel je? Gebruik dit stappenplan. 1. Moet er een *-e* komen? (Vóór het zelfstandig naamwoord meestal wel; na *een* + het-woord en los in de zin niet; na *-en*, *-e* of *-a* nooit.) 2. Lange klank met twee letters? Maak er één van: *groot* → *grote*. 3. Korte klank + één medeklinker? Maak hem dubbel: *dik* → *dikke*. 4. *f* of *s* aan het eind? Luister: hoor je *v* of *z*, schrijf dan *v* of *z*: *lieve*, *boze*. 5. *-ieel*? Trema: *financiële*.',
          rule: 'Eerst: komt er *-e*? Dan: lang → één letter, kort → dubbel, en luister naar *v*/*z*.',
          quiz: {
            q: 'Welke zin is helemaal goed?',
            options: [
              'Een groot huis met een rode deur en een houten hek.',
              'Een grote huis met een roode deur en een houtene hek.',
              'Een groot huis met een rodde deur en een houtene hek.',
            ],
            answer: 'Een groot huis met een rode deur en een houten hek.',
            why: 'een groot huis: een + het-woord, geen -e. een rode deur: de-woord, -e, en ro-de met één o. een houten hek: stofnaam op -en, geen -e.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-huis',
      prompt: 'Vind de fouten in deze mail.',
      intro: 'Kijk naar elk bijvoeglijk naamwoord: lang of kort, v of f, z of s, en komt er wel een -e?',
      header: { to: 'Fatima', subject: 'Ik heb een huis gevonden!' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Fatima,' },
        { t: 'ik' },
        { t: 'heb' },
        { t: 'een' },
        { t: 'leuk' },
        { t: 'huis' },
        { t: 'gevonden!' },
        { t: 'Het' },
        { t: 'heeft' },
        { t: 'een' },
        { t: 'groote', fix: 'grote', why: 'gro-te: open lettergreep, één o.' },
        { t: 'tuin' },
        { t: 'en' },
        { t: 'een' },
        { t: 'witte' },
        { t: 'keuken.' },
        { t: 'In' },
        { t: 'de' },
        { t: 'kamer' },
        { t: 'staat' },
        { t: 'een' },
        { t: 'houtene', fix: 'houten', why: 'Een stofnaam op -en krijgt geen -e: houten.' },
        { t: 'kast.' },
        { t: 'De' },
        { t: 'buren' },
        { t: 'zijn' },
        { t: 'aardig:' },
        { t: 'een' },
        { t: 'oude' },
        { t: 'man' },
        { t: 'met' },
        { t: 'een' },
        { t: 'lieffe', fix: 'lieve', why: 'Je hoort een v: lieve. En na ie verdubbel je niet.' },
        { t: 'hond.' },
        { t: 'Het' },
        { t: 'is' },
        { t: 'een' },
        { t: 'gezelligge', fix: 'gezellige', why: 'Na -ig verdubbel je niet: gezellige.' },
        { t: 'buurt' },
        { t: 'en' },
        { t: 'de' },
        { t: 'huur' },
        { t: 'is' },
        { t: 'een' },
        { t: 'reele', fix: 'reële', why: 'reëel → reële. Zonder trema lees je ee als één klank.' },
        { t: 'prijs.' },
        { t: 'Groetjes,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Vijf fouten verbeterd',
        text: 'grote, houten, lieve, gezellige en reële. En witte en oude waren al goed.',
      },
    },
    {
      kind: 'swipe',
      id: 'bn-swipe',
      prompt: 'Goed of fout?',
      intro: 'Veeg naar rechts als de woordgroep goed is, naar links als hij fout is.',
      cards: [
        { t: 'een financieel probleem', ok: true, why: 'Het probleem, met een ervoor: geen -e. En zonder -e is er ook geen trema nodig.' },
        { t: 'de financiele afdeling', ok: false, fix: 'de financiële afdeling', why: 'Met -e wordt -ieel -iële, met een trema.' },
        {
          t: 'eventuële kosten',
          ok: false,
          fix: 'eventuele kosten',
          why: 'Na u is geen trema nodig: ue lees je toch al los. Bij -eel komt er alleen een trema als er een i of e voor staat: financiële, reële.',
        },
        { t: 'twee volwassen kinderen', ok: true, why: 'volwassen eindigt al op -en: er komt geen -e achter.' },
        { t: 'een grove fout', ok: true, why: 'grof: met -e hoor je een v. gro-ve heeft een open lettergreep, dus één o.' },
        { t: 'een doffe klap', ok: true, why: 'dof: je hoort nog steeds een f. Korte o, dus de f wordt dubbel.' },
        {
          t: 'het draadloos netwerk',
          ok: false,
          fix: 'het draadloze netwerk',
          why: 'Met het ervoor krijgt ook een het-woord -e. Je hoort een z, en lo- is open: draadloze.',
        },
        { t: 'een leuke cadeautje', ok: false, fix: 'een leuk cadeautje', why: 'Een verkleinwoord is een het-woord. Na een: geen -e.' },
        { t: 'mijn nieuw adres', ok: false, fix: 'mijn nieuwe adres', why: 'Na mijn, ons, dit en dat krijgt ook een het-woord -e.' },
        { t: 'de verhuurde kamer', ok: true, why: 'verhuurd + e. De lettergreep huur- is gesloten, dus uu blijft twee letters.' },
        { t: 'een heele dag', ok: false, fix: 'een hele dag', why: 'he-le: open lettergreep, dus één e.' },
        { t: 'een ambitieuse collega', ok: false, fix: 'een ambitieuze collega', why: 'Met -e hoor je een z: ambitieuze. eu blijft twee letters.' },
      ],
    },
    {
      kind: 'dictation',
      id: 'dictee-buurvrouw',
      prompt: 'Luister en typ de zin.',
      sentence: 'Onze dove buurvrouw zoekt een betaalbare woning met een groot balkon en een smalle tuin.',
      right: 'Goed: dove met v en één o, betaalbare met één a, groot zonder -e (een + het balkon) en smalle met ll.',
      wrong: 'Let op: dove (v, één o), betaalbare (ba-re), een groot balkon (het-woord na een: geen -e) en smalle (korte a, dus ll).',
    },
    {
      kind: 'bet',
      id: 'wollen',
      prompt: 'Je oma breit een trui van wol. Hoe schrijf je het?',
      options: ['een wollene trui', 'een wollen trui', 'een wolen trui', 'een wolle trui'],
      answer: 'een wollen trui',
      why: 'Een stofnaam op -en krijgt geen -e: wollen, houten, gouden, zilveren. Korte o, dus ll.',
    },
    {
      kind: 'type',
      id: 'financiele',
      prompt: 'Typ het bijvoeglijk naamwoord in de goede vorm.',
      before: 'Voor mijn bedrijf zoek ik',
      after: 'hulp. (financieel)',
      hint: '',
      answer: 'financiële',
      why: 'De hulp is een de-woord, zonder lidwoord: -e. financieel → financiële. Het trema op de e laat zien dat ie hier geen ie-klank is: fi-nan-ci-ë-le.',
    },
    {
      kind: 'speed',
      id: 'los-of-vast',
      prompt: 'Aan elkaar of los?',
      intro:
        'Met -e staat het bijvoeglijk naamwoord meestal los: een grote tas. Zonder -e plakt het soms vast aan het woord, en dan is het één woord met een eigen betekenis: grootmoeder (je oma).',
      seconds: 40,
      items: [
        { a: 'groot', b: 'moeder', joined: true, tip: 'grootmoeder: je oma. Eén woord.' },
        { a: 'grote', b: 'tas', joined: false, tip: 'een grote tas: een tas die groot is.' },
        { a: 'rood', b: 'borst', joined: true, tip: 'roodborst: de vogel.' },
        { a: 'rode', b: 'wijn', joined: false, tip: 'rode wijn: twee woorden.' },
        { a: 'snel', b: 'weg', joined: true, tip: 'snelweg: de autoweg.' },
        { a: 'snelle', b: 'trein', joined: false, tip: 'een snelle trein: een trein die snel is.' },
        { a: 'klein', b: 'geld', joined: true, tip: 'kleingeld: munten.' },
        { a: 'kleine', b: 'kinderen', joined: false, tip: 'kleine kinderen: twee woorden.' },
      ],
      done: {
        title: 'Los of vast',
        text: 'Met -e bijna altijd los. Zonder -e en met een eigen betekenis: één woord, zoals grootmoeder, snelweg en kleingeld.',
      },
    },
    {
      kind: 'rewrite',
      id: 'kleine-kamer',
      prompt: 'Schrijf de zin opnieuw. Begin met: Het is een … kamer. Gebruik beide bijvoeglijke naamwoorden, met en ertussen.',
      source: 'De kamer is klein en donker.',
      accept: ['Het is een kleine en donkere kamer.', 'Het is een donkere en kleine kamer.'],
      why: 'Vóór kamer (een de-woord) krijgen beide een -e: kleine en donkere. Na -er geen dubbele r.',
    },
    {
      kind: 'choice',
      id: 'ideale',
      prompt: 'Kies de goede vorm.',
      before: 'Dit is de',
      after: 'plek voor een picknick. (ideaal)',
      options: ['ideale', 'ideaale', 'idealle', 'ideaal'],
      answer: 'ideale',
      why: 'i-de-a-le: de lange a staat in een open lettergreep, dus één a.',
    },
    {
      kind: 'fix',
      id: 'zachtte',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Dit kussen heeft een heel zachtte stof.',
      wrong: 5,
      answer: 'zachte',
      why: 'zacht eindigt op twee medeklinkers (ch en t). Dan verdubbel je niet: zachte.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord in de goede vorm',
      intro: 'Vijfentwintig opdrachten door elkaar, ook uit eerdere lessen. Typ alleen het woord dat in het vak hoort. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Goede vorm van *grof*',
          before: 'Dat was een',
          after: 'fout van de bank.',
          a: 'grove',
          why: 'De fout is een de-woord: -e. Met -e hoor je een v, en gro- is open: grove.',
        },
        { q: 'Meervoud van *het bedrag*', a: 'bedragen', why: 'Net als dag → dagen: in het meervoud hoor je een lange a. Dus be-dra-gen, met één a en één g.' },
        {
          q: 'Goede vorm van *commercieel*',
          before: 'Hij werkt bij een',
          after: 'bedrijf.',
          a: 'commercieel',
          why: 'Het bedrijf, met een ervoor: geen -e. Zonder -e ook geen trema.',
        },
        {
          q: 'Goede vorm van *dakloos*',
          before: 'De gemeente opent een nachtopvang voor',
          after: 'mensen.',
          a: 'dakloze',
          why: 'Meervoud: -e. Je hoort een z, en lo- is open: één o. dakloze.',
        },
        {
          q: 'Vul de vorm van *verhuizen* in',
          before: 'Volgende maand',
          after: 'mijn zus naar Utrecht.',
          a: 'verhuist',
          why: 'mijn zus = zij: stam + t. De stam van verhuizen is verhuis (geen z aan het eind). Dus verhuist.',
        },
        {
          q: 'Goede vorm van *volwassen*',
          before: 'Ze heeft drie',
          after: 'kinderen.',
          a: 'volwassen',
          why: 'volwassen eindigt al op -en: er komt geen -e achter.',
        },
        {
          q: 'Goede vorm van *eventueel*',
          before: 'Stuur uw',
          after: 'vragen naar de klantenservice.',
          a: 'eventuele',
          why: 'Vóór vragen: -e. Na u is geen trema nodig, want ue lees je toch al los. Bij -eel komt er alleen een trema als er een i of e voor staat: officiële, reële.',
        },
        { q: 'Goede vorm van *nieuw*', before: 'Na de proeftijd kreeg ik een', after: 'contract.', a: 'nieuw', why: 'Het contract, met een ervoor: geen -e.' },
        { q: 'Verkleinwoord van *de bon*', a: 'bonnetje', why: 'Korte o + n met klemtoon: -etje, en de n wordt dubbel. bonnetje.' },
        {
          q: 'Goede vorm van *klein*',
          before: 'Ik heb een',
          after: 'probleempje met de printer.',
          a: 'klein',
          why: 'Een verkleinwoord is altijd een het-woord. Met een ervoor: geen -e.',
        },
        {
          q: 'Goede vorm van *serieus*',
          before: 'Dit is een',
          after: 'klacht.',
          a: 'serieuze',
          why: 'De klacht is een de-woord: -e. Met -e hoor je een z: serieuze. eu blijft twee letters.',
        },
        {
          q: 'Vul de vorm van *repareren* in',
          before: 'De',
          after: 'wasmachine lekt alweer.',
          a: 'gerepareerde',
          why: 'repareren: de r zit niet in ’t kofschip, dus gerepareerd. Vóór wasmachine komt er -e achter: gerepareerde.',
        },
        {
          q: 'Goede vorm van *nieuw*',
          before: 'Mijn',
          after: 'adres is Kerkstraat 12.',
          a: 'nieuwe',
          why: 'Na mijn, ons, dit en dat krijgt ook een het-woord een -e: mijn nieuwe adres.',
        },
        {
          q: 'Goede vorm van *precies*',
          before: 'Weet u de',
          after: 'datum van de afspraak nog?',
          a: 'precieze',
          why: 'De datum: -e. Met -e hoor je een z: precieze.',
        },
        { q: 'Schrijf als één woord: *auto* + *ongeluk*', a: 'auto-ongeluk', why: 'De o van auto en de o van ongeluk botsen: daar komt een koppelteken.' },
        {
          q: 'Goede vorm van *duurzaam*',
          before: 'De gemeente geeft subsidie voor',
          after: 'energie.',
          a: 'duurzame',
          why: 'Energie is een de-woord: -e, ook zonder lidwoord. duur-za-me: één a in de open lettergreep, uu blijft in de gesloten lettergreep.',
        },
        {
          q: 'Goede vorm van *gesloten*',
          before: 'Achter de',
          after: 'deur hoorde ik de buren schreeuwen.',
          a: 'gesloten',
          why: 'gesloten eindigt al op -en: geen -e.',
        },
        {
          q: 'Vul de vorm van *antwoorden* in',
          before: 'Mijn huisbaas',
          after: 'nu al drie weken niet op mijn mails.',
          a: 'antwoordt',
          why: 'De stam is antwoord. Bij hij (mijn huisbaas) komt er een t bij: antwoordt.',
        },
        {
          q: 'Goede vorm van *betaalbaar*',
          before: 'We zoeken een',
          after: 'woning in de buurt van het station.',
          a: 'betaalbare',
          why: 'De woning: -e. ba-re: open lettergreep, dus één a. In be-taal- blijft aa.',
        },
        { q: 'Meervoud van *de baby*', a: 'baby’s', why: 'baby eindigt op een y: meervoud met apostrof en s.' },
        {
          q: 'Goede vorm van *zorgvuldig*',
          before: 'Bedankt voor uw',
          after: 'antwoord.',
          a: 'zorgvuldige',
          why: 'Na uw krijgt ook een het-woord -e. Na -ig verdubbel je niet: zorgvuldige.',
        },
        {
          q: 'Vul de vorm van *scheiden* in',
          before: 'Mijn ouders zijn al tien jaar',
          after: 'en wonen nu apart.',
          a: 'gescheiden',
          why: 'ge + scheid + en. scheiden schrijf je met ei.',
        },
        {
          q: 'Goede vorm van *laf*',
          before: 'Wat een',
          after: 'opmerking van de buurman!',
          a: 'laffe',
          why: 'De opmerking: -e. Je hoort nog een f, en na de korte a wordt die dubbel: laffe.',
        },
        {
          q: 'Bijvoeglijk naamwoord van *hout*',
          before: 'We hebben een',
          after: 'vloer in de woonkamer.',
          a: 'houten',
          why: 'Van hout: houten. Een stofnaam op -en krijgt geen -e.',
        },
        {
          q: 'Goede vorm van *vrijwillig*',
          before: 'Voor het schoolreisje vragen we een',
          after: 'bijdrage van 25 euro.',
          a: 'vrijwillige',
          why: 'De bijdrage: -e. vrij met ij, en na -ig verdubbel je niet: vrijwillige.',
        },
      ],
      done: { title: 'Reeks klaar', text: 'Eerst kijken of er een -e komt, dan pas naar de spelling. En bij elk woord zelf bepalen welke regel geldt.' },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail aan. Typ elk woord helemaal.',
      intro: 'In het grijs staat het woord dat je nodig hebt, bv. *ruim (-e?)*. Bepaal zelf de vorm: met of zonder *-e*, en hoe je hem spelt.',
      title: 'Mail van de verhuurder',
      text: 'Beste meneer Rahimi,\n\nBedankt voor uw {snelle|snel (-e?)|De reactie is een de-woord: -e. Korte e + l: de l wordt dubbel, snel-le.} reactie. Het appartement is nog vrij. Het is een {licht|licht (-e?)|Het appartement, met een ervoor: geen -e.} appartement met een {ruime|ruim (-e?)|De woonkamer is een de-woord: -e. Na ui verandert er niets.} woonkamer en twee {smalle|smal (-e?)|Meervoud: -e. Korte a + l: de l wordt dubbel, smal-le.} slaapkamers. Het {grote|groot (-e?)|Met het ervoor krijgt ook een het-woord -e. gro-te: open lettergreep, één o.} balkon ligt op het zuiden. De keuken is vorig jaar {gerenoveerd|renoveren|renoveren: de r zit niet in ’t kofschip, dus een d.} en is nu helemaal {nieuw|nieuw (-e?)|Het staat los in de zin, na is: geen -e.}. In de badkamer ligt een {stenen|van steen|Een stofnaam op -en krijgt geen -e: stenen.} vloer. Het appartement ligt op de derde verdieping van een rustig gebouw, vlak bij het station. U kunt het woensdag of donderdag na zes uur komen bekijken.\n\nDe huur is 950 euro per maand en {wordt|worden|De huur = hij: stam word + t.} elk jaar in juli aangepast. U betaalt ook een {eenmalige|eenmalig (-e?)|De borg is een de-woord: -e. Na -ig verdubbel je niet.} borg van twee maanden huur. Bij de bezichtiging {verwacht|verwachten|Ik + stam: verwacht. De stam eindigt al op een t, er komt niets bij.} ik een {recent|recent (-e?)|Een loonstrookje is een verkleinwoord, dus een het-woord. Met een ervoor: geen -e.} loonstrookje, of {bijvoorbeeld|b__voorbeeld|bij met ij: bijvoorbeeld.} een {officieel|officieel (-e?)|Het bewijs, met een ervoor: geen -e. En zonder -e ook geen trema.} bewijs van inkomen. {Eventuele|eventueel (-e?)|Meervoud: -e. Na u is geen trema nodig.} vragen kunt u altijd mailen. Ik stuur u alvast een paar {foto’s|meervoud van foto|foto eindigt op o: apostrof en s.} van de keuken.\n\nMet {vriendelijke|vriendelijk (-e?)|De groet is een de-woord: -e. Na -lijk verdubbel je niet.} groet,\nPeter de Vries',
      why: 'Vóór een zelfstandig naamwoord komt er meestal -e, met de regels van de lettergreep: snelle, smalle, grote, eenmalige, eventuele (zonder trema), vriendelijke. Geen -e bij een het-woord na een (een licht appartement, een recent loonstrookje, een officieel bewijs), los in de zin (is nieuw) en na -en (stenen). Uit eerdere lessen: gerenoveerd (’t kofschip), wordt (stam + t), verwacht (stam op t), bijvoorbeeld (ij) en foto’s (apostrof).',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen uit een bericht in de buurtapp. Hoofdletters en leestekens tellen mee.',
      title: 'Kat vermist',
      sentences: [
        'Sinds dinsdagavond is onze grijze kat Moos verdwenen.',
        'Hij heeft een witte vlek op zijn neus en een heel kort staartje.',
        'Moos is nog maar een jong katje en helemaal doof.',
        'Hij draagt een rode halsband met een klein zilveren belletje.',
        'Misschien zit hij opgesloten in een donkere schuur of in een lege garage.',
        'De eerlijke vinder krijgt van ons een grote doos lekkere bonbons.',
      ],
      right:
        'Alles goed: grijze, witte, rode, donkere, lege, eerlijke, grote en lekkere met -e, en kort, jong, klein en doof zonder -e. Zilveren en opgesloten eindigen al op -en.',
      wrong:
        'Kijk na: komt er een -e? Een het-woord na een krijgt er geen (een heel kort staartje, een jong katje, een klein belletje), en los in de zin ook niet (doof). Let op de spelling: grijze (z), witte (tt), lege en grote (één klinker). Zilveren en opgesloten krijgen nooit een -e.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'Klantenservice woningcorporatie', subject: 'Lekkage en kapot raam' },
      greeting: 'Geachte heer, mevrouw,',
      signoff: 'Met vriendelijke groet,\nHasan Rahimi',
      tokens: [
        { t: 'Sinds' },
        { t: 'vorige' },
        { t: 'week' },
        { t: 'lekt' },
        { t: 'het' },
        { t: 'plate', fix: 'platte', why: 'plat heeft een korte a. Met -e wordt de t dubbel: plat-te.' },
        { t: 'dak' },
        { t: 'boven' },
        { t: 'onze' },
        { t: 'slaapkamer.' },
        { t: 'Er' },
        { t: 'zit' },
        { t: 'nu' },
        { t: 'een' },
        { t: 'groote', fix: 'grote', why: 'gro-te: open lettergreep, dus één o.' },
        { t: 'natte' },
        { t: 'plek' },
        { t: 'op' },
        { t: 'het' },
        { t: 'plafond' },
        { t: 'en' },
        { t: 'de' },
        { t: 'witte' },
        { t: 'verf' },
        { t: 'bladdert' },
        { t: 'af.' },
        { t: 'Ook' },
        { t: 'sluit' },
        { t: 'het' },
        { t: 'houtene', fix: 'houten', why: 'Een stofnaam op -en krijgt geen -e: houten.' },
        { t: 'raam' },
        { t: 'in' },
        { t: 'de' },
        { t: 'keuken' },
        { t: 'niet' },
        { t: 'goed' },
        { t: 'meer.' },
        { t: 'Door' },
        { t: 'een' },
        { t: 'smalle' },
        { t: 'kier' },
        { t: 'komt' },
        { t: 'er' },
        { t: 'koud', fix: 'koude', why: 'De lucht is een de-woord, dus -e: koude lucht.' },
        { t: 'lucht' },
        { t: 'binnen,' },
        { t: 'en' },
        { t: 'het' },
        { t: 'word', fix: 'wordt', why: 'het = hij: stam word + t. Dus het wordt.' },
        { t: '’s' },
        { t: 'nachts' },
        { t: 'erg' },
        { t: 'koud.' },
        { t: 'Wij' },
        { t: 'hebben' },
        { t: 'twee' },
        { t: 'volwassen', trap: 'Goed: volwassen eindigt al op -en. Daar komt nooit een -e achter.' },
        { t: 'kinderen' },
        { t: 'en' },
        { t: 'een' },
        { t: 'doofe', fix: 'dove', why: 'Met -e hoor je een v, en do- is open: dove, met één o.' },
        { t: 'opa' },
        { t: 'in' },
        { t: 'huis.' },
        { t: 'Een' },
        { t: 'snele', fix: 'snelle', why: 'snel heeft een korte e. Met -e wordt de l dubbel: snel-le.' },
        { t: 'reparatie' },
        { t: 'is' },
        { t: 'dus' },
        { t: 'belangrijk.' },
        { t: 'Kunt' },
        { t: 'u' },
        { t: 'een' },
        { t: 'vakman' },
        { t: 'sturen?' },
        {
          t: 'Eventuele',
          trap: 'Goed: na u is geen trema nodig, want ue lees je toch al los. Bij -eel komt er alleen een trema als er een i of e voor staat: officiële, reële.',
        },
        { t: 'schade' },
        { t: 'aan' },
        { t: 'onze' },
        { t: 'spullen' },
        { t: 'meld' },
        { t: 'ik' },
        { t: 'later.' },
        { t: 'Wij' },
        { t: 'hebben' },
        { t: 'ook' },
        { t: 'een' },
        { t: 'nieuw', trap: 'Goed: het slot is een het-woord, en er staat een voor. Dus geen -e.' },
        { t: 'slot' },
        { t: 'nodig' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'achterdeur.' },
        { t: 'Ik' },
        { t: 'stuur' },
        { t: 'twee' },
        { t: 'fotos', fix: 'foto’s', why: 'foto eindigt op een o: meervoud met apostrof en s, foto’s.' },
        { t: 'mee' },
        { t: 'als' },
        { t: 'duidelijk', trap: 'Goed: bewijs is een het-woord, en er staat geen lidwoord voor. Dus geen -e: duidelijk bewijs.' },
        { t: 'bewijs.' },
      ],
    },
  ],
};
