import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": een woord afbreken aan het eind van de regel, met de regels, uitzonderingen en een stappenplan. */
export const LES_G27: LessonInput = {
  id: 'g27',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'Afbreken aan het eind van de regel',
  skill: 'Spelling',
  icon: 'ma-',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Waar mag het streepje?',
      panels: [
        {
          text: 'Past een woord niet meer op de regel? Dan mag je het *afbreken*. Je zet een koppelteken aan het eind van de regel en schrijft de rest van het woord op de volgende regel. Je breekt af op de grens van twee lettergrepen: *ma-ken*, *bo-men*, *ta-fel*. Op de computer en de telefoon doet het programma dit meestal zelf. Maar bij schrijven met de hand, op een formulier of op een bord moet je het zelf kunnen.',
          rule: 'Afbreken doe je op een lettergreepgrens, met een koppelteken aan het eind van de regel: *ma-ken*.',
          split: {
            q: 'Breek het woord af',
            word: 'maken',
            answer: 'ma-ken',
            note: 'Eén medeklinker tussen de klinkers: de k gaat naar de volgende lettergreep.',
          },
        },
        {
          text: 'Staat er één medeklinker tussen twee klinkers? Dan gaat die mee naar de volgende lettergreep: *bo-men*, *le-zen*, *ta-fel*. Staan er twee medeklinkers? Dan gaat er meestal één mee en blijft er één staan: *kan-ten*, *kas-ten*, *har-ten*. Een dubbele medeklinker gaat dus uit elkaar: *bak-ker*, *kat-ten*, *kof-fie*.',
          rule: 'Eén medeklinker: die gaat mee (*bo-men*). Twee medeklinkers: meestal één aan elke kant (*bak-ker*, *kan-ten*).',
          split: { q: 'Breek het woord af', word: 'bakker', answer: 'bak-ker', note: 'Twee k’s: één aan elke kant van het streepje.' },
        },
        {
          text: 'Letters die samen één klank maken, haal je nooit uit elkaar: *oe*, *ie*, *ij*, *ui*, *eu*, *ei*, *aa*, *ou*. Dus *blij-ven*, *boe-ken*, *hui-zen*, *keu-ken*. Ook de *ch* blijft altijd heel: *la-chen*, nooit *lac-hen*. Maar de *ng* gaat wél uit elkaar, ook al hoor je één klank: *zin-gen*, *jon-gen*.',
          rule: '*ch*, *oe*, *ij*, *ui* en andere klanken van twee letters blijven heel. *ng* gaat uit elkaar: *zin-gen*.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'lachen', out: 'la-chen', note: 'ch blijft heel. Nooit lac-hen.' },
              { k: 'zingen', out: 'zin-gen', note: 'ng gaat uit elkaar: n op de eerste regel, g op de volgende.' },
              { k: 'blijven', out: 'blij-ven', note: 'ij blijft heel. Nooit bli-jven.' },
              { k: 'huizen', out: 'hui-zen', note: 'ui blijft heel.' },
              { k: 'jongen', out: 'jon-gen', note: 'Weer ng: uit elkaar.' },
            ],
          },
        },
        {
          text: 'Bestaat een woord uit twee woorden, of heeft het een voorvoegsel als *ver-*, *her-*, *be-* of *ont-*? Dan knip je eerst tussen de delen. *fiets-pomp*, *boe-ken-kast*, *aard-ap-pel*. Bij *veranderen* zeg je misschien *ve-ran-de-ren*, maar je breekt af als *ver-an-de-ren*, want *ver-* is één deel. Zo ook *her-in-ne-ren* en *ont-bijt*.',
          rule: 'Samenstelling of voorvoegsel: eerst tussen de delen knippen (*aard-ap-pel*, *ver-an-de-ren*).',
          split: {
            q: 'Breek het woord af, op alle plekken waar het mag',
            word: 'aardappel',
            answer: 'aard-ap-pel',
            note: 'aard + appel. Eerst tussen de twee woorden, dan in appel: ap-pel.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'goed-fout',
      prompt: 'Goed of fout afgebroken?',
      buckets: ['goed', 'fout'],
      items: [
        { t: 'tand-arts', b: 0 },
        { t: 'spree-kuur', b: 1 },
        { t: 'vrien-din', b: 0 },
        { t: 'zing-en', b: 1 },
        { t: 'waar-om', b: 0 },
        { t: 'ver-keer-son-ge-luk', b: 1 },
        { t: 'ma-chi-ne', b: 0 },
        { t: 'po-ëzie', b: 1 },
        { t: 'ver-schil-len', b: 0 },
        { t: 'mens-en', b: 1 },
        { t: 'zee-en', b: 0 },
        { t: 'be-an-twoor-den', b: 1 },
        { t: 'ach-ter-af', b: 0 },
        { t: 'ges-chie-de-nis', b: 1 },
        { t: 'kin-de-ren', b: 0 },
        { t: 're-ünie', b: 1 },
      ],
      why: 'Goed: tand-arts, waar-om, ach-ter-af en ver-schil-len (eerst tussen de delen), vrien-din en kin-de-ren (gewoon de lettergrepen), ma-chi-ne (ch blijft heel) en zee-en (trema weg). Fout: spreek-uur, ver-keers-on-ge-luk en ge-schie-de-nis (eerst tussen de delen), be-ant-woor-den (be + antwoorden, en in antwoord zit woord: ant-woord), zin-gen en men-sen (twee medeklinkers: één aan elke kant), po-ezie en re-unie (op de plek van het trema valt het trema weg).',
    },
    {
      kind: 'choice',
      id: 'beschrijving',
      prompt: 'Welke afbreking is goed?',
      before: 'Lees eerst de',
      after: 'van de functie.',
      options: ['bes-chrij-ving', 'be-schrij-ving', 'besch-rij-ving', 'be-schri-jving'],
      answer: 'be-schrij-ving',
      why: 'be- is een voorvoegsel: be + schrijving. Eerst tussen de delen, dan schrij-ving. sch en ij blijven heel.',
    },
    {
      kind: 'type',
      id: 'verantwoordelijk',
      prompt: 'Breek het woord af op alle plekken waar het mag. Typ het met koppeltekens, bv. ka-mer.',
      before: 'verantwoordelijk =',
      after: '',
      hint: '',
      answer: 'ver-ant-woor-de-lijk',
      why: 'ver- is een voorvoegsel en blijft heel: ver-ant, niet ve-rant. In antwoord zit het woord woord: ant-woord, niet an-twoord. Dan de-lijk: de d gaat mee.',
    },
    {
      kind: 'bet',
      id: 'koningin',
      prompt: 'Hoe breek je koningin af, op alle plekken waar het mag?',
      options: ['ko-ning-in', 'ko-nin-gin', 'kon-in-gin', 'ko-ni-ngin'],
      answer: 'ko-nin-gin',
      why: '-in is een uitgang, geen los woord. Dus je volgt gewoon de lettergrepen, en ng gaat uit elkaar: ko-nin-gin. Zo ook vrien-din.',
    },
    {
      kind: 'type',
      id: 'ontvangstbevestiging',
      prompt: 'Breek het woord af op alle plekken waar het mag. Typ het met koppeltekens, bv. ka-mer.',
      before: 'ontvangstbevestiging =',
      after: '',
      hint: '',
      answer: 'ont-vangst-be-ves-ti-ging',
      why: 'ontvangst + bevestiging. ont- en be- zijn voorvoegsels. vangst is één lettergreep. ves-ti-ging: s en t, één aan elke kant.',
    },
    {
      kind: 'choice',
      id: 'huisarts',
      prompt: 'Welke afbreking is goed?',
      before: 'Morgen heb ik een afspraak bij de',
      after: '.',
      options: ['hui-sarts', 'huisa-rts', 'huis-arts', 'hu-is-arts'],
      answer: 'huis-arts',
      why: 'huis + arts: een samenstelling. Je knipt eerst tussen de twee woorden. hui-sarts is fout, en ui blijft altijd heel.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Lastige gevallen en een stappenplan',
      panels: [
        {
          text: 'Breek je af op de plek van een trema? Dan valt het trema weg. Het koppelteken laat nu al zien dat de klinkers los klinken. *ruïne* wordt *ru-ine*, *knieën* wordt *knie-en*. Breek je op een andere plek af, dan blijft het trema gewoon staan.',
          rule: 'Afbreken op de plek van het trema: het trema valt weg (*ru-ine*, *knie-en*).',
          quiz: {
            q: 'Je breekt knieën af op de plek van het trema. Wat schrijf je?',
            options: ['knie-en', 'knie-ën', 'kni-eën'],
            answer: 'knie-en',
            why: 'Op de plek van het trema afbreken: het trema valt weg. ie blijft heel.',
          },
        },
        {
          text: 'Heeft een woord al een koppelteken, zoals *Noord-Holland*, *zee-egel* of *tv-programma*? Breek je het af op dat koppelteken, dan blijft het koppelteken aan het eind van de regel staan, en je zet er geen tweede bij: *Noord-* op de eerste regel, *Holland* op de volgende. Breek je op een andere plek af, dan blijft het koppelteken gewoon staan en komt er aan het eind van de regel een streepje bij: *tv-pro-* en dan *gramma*.',
          rule: 'Afbreken op het koppelteken: geen extra streepje (*Noord-*). Op een andere plek: het koppelteken blijft (*tv-pro-*).',
          quiz: {
            q: 'Je breekt Noord-Holland af op het koppelteken. Wat zet je aan het eind van de regel?',
            options: ['Noord-', 'Noord--', 'Noord'],
            answer: 'Noord-',
            why: 'Je breekt af op het koppelteken dat er al staat. Holland komt op de volgende regel.',
          },
        },
        {
          text: 'Laat nooit één losse letter alleen staan, aan het eind van de regel of aan het begin van de volgende: niet *a-pen*, *e-zel* of *aline-a*. Kan het nergens anders? Zet dan het hele woord op de volgende regel. Een naam, een getal, een datum of een afkorting breek je *liever niet* af. En breek alleen af als het echt moet.',
          rule: 'Nooit een losse letter (*a-pen*, *aline-a*). Liever niet: een naam, getal of afkorting afbreken.',
          lab: {
            label: 'Tik een afbreking',
            chips: [
              { k: 'a-pen', out: 'niet doen', note: 'Een losse a op de regel. apen breek je niet af: het hele woord gaat naar de volgende regel.' },
              { k: 'aline-a', out: 'niet doen', note: 'Een losse a op de volgende regel. Alleen ali-nea mag.' },
              { k: 'ta-fel', out: 'prima', note: 'Twee letters op de eerste regel: dat mag.' },
              { k: 'Fati-ma', out: 'liever niet', note: 'Een naam breek je liever niet af.' },
            ],
          },
        },
        {
          text: 'Twijfel je? Gebruik dit stappenplan. 1. Past het woord echt niet meer? Breek dan pas af. 2. Bestaat het woord uit delen (samenstelling of voorvoegsel)? Knip eerst tussen de delen. 3. Zoek de klinkerklanken. Eén medeklinker ertussen: die gaat mee. Twee: één aan elke kant. 4. *ch*, *oe*, *ij*, *ui* en de andere klanken van twee letters blijven heel. *ng* gaat uit elkaar. 5. Laat geen losse letter achter.',
          rule: 'Delen → klinkers → medeklinkers verdelen → klanken heel laten → geen losse letter.',
          split: {
            q: 'Breek het woord af, op alle plekken waar het mag',
            word: 'ziekenhuis',
            answer: 'zie-ken-huis',
            note: 'zieken + huis. Eerst tussen de delen, dan in zieken: zie-ken. ie en ui blijven heel.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'printer',
      prompt: 'Een oud programma heeft deze woorden afgebroken. Vind de fouten.',
      intro: 'Kijk bij elk woord: staat het streepje op een goede plek?',
      tokens: [
        { t: 'boe-ken,' },
        { t: 'zi-ngen,', fix: 'zin-gen,', why: 'ng gaat uit elkaar: zin-gen.' },
        { t: 'fiets-pomp,' },
        { t: 'lac-hen,', fix: 'la-chen,', why: 'ch blijft heel: la-chen.' },
        { t: 'ka-tten,', fix: 'kat-ten,', why: 'Een dubbele medeklinker gaat uit elkaar: kat-ten.' },
        { t: 'ver-an-de-ren,' },
        { t: 'ru-ïne,', fix: 'ru-ine,', why: 'Op de plek van het trema afbreken: het trema valt weg.' },
        { t: 'ta-fel,' },
        { t: 'bli-jven,', fix: 'blij-ven,', why: 'ij blijft heel: blij-ven.' },
        { t: 'kas-ten.' },
      ],
      done: {
        title: 'Beter dan het programma',
        text: 'zin-gen, la-chen, kat-ten, ru-ine en blij-ven. De andere vijf waren goed.',
      },
    },
    {
      kind: 'swipe',
      id: 'afbreek-swipe',
      prompt: 'Goed of fout?',
      intro: 'Veeg naar rechts als de bewering of afbreking klopt, naar links als hij niet klopt.',
      cards: [
        { t: 'schoolarts breek je af als schoo-larts.', ok: false, fix: 'school-arts', why: 'school + arts: eerst tussen de delen. De l hoort bij school.' },
        {
          t: 'dienstrooster breek je af als dienst-roos-ter.',
          ok: true,
          why: 'dienst + rooster. In rooster gaat de s naar links en de t naar rechts: roos-ter.',
        },
        { t: 'wandelingen breek je af als wan-de-ling-en.', ok: false, fix: 'wan-de-lin-gen', why: 'ng gaat bij afbreken uit elkaar: lin-gen.' },
        {
          t: 'Breek je beïnvloeden af na be-, dan staat op de volgende regel invloeden.',
          ok: true,
          why: 'Je breekt af op de plek van het trema. Dan valt het trema weg.',
        },
        {
          t: 'Breek je ruïne af als ruï-ne, dan valt het trema weg.',
          ok: false,
          fix: 'ruï-ne: het trema blijft staan',
          why: 'Het trema valt alleen weg als je precies op de plek van het trema afbreekt: ru-ine. Bij ruï-ne blijft het staan.',
        },
        { t: 'schoolreisje breek je af als school-reis-je.', ok: true, why: 'school + reisje. In reisje gaat de s naar links en de j naar rechts.' },
        { t: 'aardbeien breek je af als aard-bei-en.', ok: true, why: 'aard + beien. ei blijft heel, en de e erna begint een nieuwe lettergreep.' },
        {
          t: 'Breek je Noord-Brabant af op het koppelteken, dan zet je aan het eind van de regel Noord--.',
          ok: false,
          fix: 'Noord-',
          why: 'Je breekt af op het koppelteken dat er al staat. Er komt geen tweede streepje bij.',
        },
        {
          t: 'alinea breek je af als aline-a.',
          ok: false,
          fix: 'ali-nea',
          why: 'Bij aline-a staat de a alleen op de volgende regel. Een losse letter laat je nooit alleen staan: ali-nea.',
        },
        { t: 'kachel breek je af als kac-hel.', ok: false, fix: 'ka-chel', why: 'ch blijft heel en gaat mee naar de volgende lettergreep: ka-chel.' },
        {
          t: 'onafhankelijk breek je af als on-af-han-ke-lijk.',
          ok: true,
          why: 'on- en af- zijn voorvoegsels. Daarna han-ke-lijk: n en k, één aan elke kant.',
        },
        { t: 'Een naam als Mohammed breek je liever niet af.', ok: true, why: 'Namen, getallen, datums en afkortingen breek je liever niet af.' },
      ],
    },
    {
      kind: 'type',
      id: 'werkervaring',
      prompt: 'Breek het woord af op alle plekken waar het mag. Typ het met koppeltekens, bv. ka-mer.',
      before: 'werkervaring =',
      after: '',
      hint: '',
      answer: 'werk-er-va-ring',
      why: 'werk + ervaring: eerst tussen de delen, dus niet wer-ker. Dan er-va-ring: er- blijft heel, en de v en de r gaan mee.',
    },
    {
      kind: 'bet',
      id: 'ruine',
      prompt: 'Je breekt ruïne af op de plek van het trema. Wat schrijf je?',
      options: ['ru-ïne', 'ru-ine', 'rui-ne', 'ruï-ne'],
      answer: 'ru-ine',
      why: 'Op de plek van het trema afbreken: het trema valt weg, want het koppelteken laat al zien dat u en i los klinken. rui-ne is fout: dan lees je ui. ruï-ne mag wel, maar dan breek je niet op de plek van het trema af.',
    },
    {
      kind: 'type',
      id: 'kinderopvang',
      prompt: 'Breek het woord af op alle plekken waar het mag. Typ het met koppeltekens, bv. ka-mer.',
      before: 'kinderopvang =',
      after: '',
      hint: '',
      answer: 'kin-der-op-vang',
      why: 'kinder + opvang: eerst tussen de delen, dus niet kin-de-rop. Dan kin-der (n en d, één aan elke kant) en op-vang.',
    },
    {
      kind: 'sort',
      id: 'eerst-delen',
      prompt: 'Waar knip je eerst?',
      buckets: ['tussen twee delen van het woord', 'gewoon tussen de lettergrepen'],
      items: [
        { t: 'fiets-pomp', b: 0 },
        { t: 'ko-nin-gin', b: 1 },
        { t: 'ver-an-de-ren', b: 0 },
        { t: 'be-ter', b: 1 },
        { t: 'aard-ap-pel', b: 0 },
        { t: 'le-raar', b: 1 },
        { t: 'ont-bijt', b: 0 },
        { t: 'ge-ven', b: 1 },
        { t: 'her-in-ne-ren', b: 0 },
        { t: 'wo-ning', b: 1 },
        { t: 'daar-om', b: 0 },
        { t: 'vrien-din-nen', b: 1 },
        { t: 'be-ant-woor-den', b: 0 },
        { t: 'la-chen', b: 1 },
      ],
      why: 'fiets + pomp, aard + appel en daar + om zijn samenstellingen. ver-, ont-, her- en be- in beantwoorden zijn voorvoegsels. Daar knip je eerst tussen de delen. -in, -aar en -ing zijn uitgangen, geen losse delen: in koningin, leraar, woning en vriendinnen volg je gewoon de lettergrepen. En in beter en geven zijn be- en ge- geen voorvoegsel.',
    },
    {
      kind: 'type',
      id: 'herinnering',
      prompt: 'Breek het woord af op alle plekken waar het mag. Typ het met koppeltekens, bv. ka-mer.',
      before: 'herinnering =',
      after: '',
      hint: '',
      answer: 'her-in-ne-ring',
      why: 'her- is een voorvoegsel en blijft heel: her-in, niet he-rin. Dan gaat de dubbele n uit elkaar: in-ne-ring.',
    },
    {
      kind: 'rewrite',
      id: 'belastingaangifte',
      prompt: 'Breek het woord af op alle plekken waar het mag. Zet een koppelteken op elk afbreekpunt.',
      source: 'belastingaangifte',
      accept: ['be-las-ting-aan-gif-te'],
      why: 'belasting + aangifte: eerst tussen de delen. be-las-ting: be- blijft heel, s en t één aan elke kant. aan-gif-te: aan + gifte, f en t één aan elke kant.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: breek af of typ het woord',
      intro:
        'Vijfentwintig opdrachten door elkaar, ook uit eerdere lessen. Bij afbreken typ je het woord met een koppelteken op elke plek waar het mag, bv. *ka-mer*. Bij de andere opdrachten typ je alleen het woord. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Breek af op alle plekken: *huurachterstand*',
          a: 'huur-ach-ter-stand',
          why: 'huur + achter + stand: eerst tussen de delen. ch blijft heel: ach-ter.',
        },
        { q: 'Meervoud van *de categorie*', a: 'categorieën', why: 'De klemtoon ligt op -rie: meervoud -ieën, met een trema op de e na ie.' },
        {
          q: 'Breek af op alle plekken: *ziekenhuisopname*',
          a: 'zie-ken-huis-op-na-me',
          why: 'zieken + huis + opname. Dus huis-op, niet hui-sop. op-na-me: op + name.',
        },
        {
          q: 'Breek *beëindigen* af op de plek van het trema',
          a: 'be-eindigen',
          why: 'Op de plek van het trema afbreken: het trema valt weg. Het koppelteken laat al zien dat de e en ei los klinken.',
        },
        {
          q: 'Breek af op alle plekken: *bijeenkomst*',
          a: 'bij-een-komst',
          why: 'bij + een + komst: eerst tussen de delen. Niet bi-jeen-komst: ij blijft heel.',
        },
        { q: 'Meervoud van *de alinea*', a: 'alinea’s', why: 'alinea eindigt op een a: ’s. De apostrof houdt de a lang.' },
        { q: 'Breek af op alle plekken: *oneerlijk*', a: 'on-eer-lijk', why: 'on- is een voorvoegsel: on + eerlijk. Dus niet o-neer-lijk.' },
        {
          q: 'Je breekt *e-mailadres* af tussen *mail* en *adres*. Wat zet je aan het eind van de eerste regel?',
          a: 'e-mail-',
          why: 'Je breekt niet af op het koppelteken dat er al staat. Dat koppelteken blijft dus staan, en aan het eind van de regel komt een streepje bij: e-mail- en dan adres.',
        },
        {
          q: 'Vul de vorm van *verhuizen* in',
          before: 'Wij zijn vorig jaar',
          after: 'naar Almere.',
          a: 'verhuisd',
          why: 'verhuizen: de z zit niet in ’t kofschip, dus een d. In de stam schrijf je een s: verhuisd.',
        },
        { q: 'Breek af op alle plekken: *ontwikkeling*', a: 'ont-wik-ke-ling', why: 'ont- blijft heel. Dan gaat de dubbele k uit elkaar: wik-ke-ling.' },
        { q: 'Breek *ideeën* af op de plek van het trema', a: 'idee-en', why: 'idee + en. Op de plek van het trema afbreken: het trema valt weg.' },
        { q: 'Verkleinwoord van *de film*', a: 'filmpje', why: 'Na lm: -pje. filmpje.' },
        {
          q: 'Breek af op alle plekken: *aanvraagformulier*',
          a: 'aan-vraag-for-mu-lier',
          why: 'aan + vraag + formulier: eerst tussen de delen. Dan for-mu-lier: r en m één aan elke kant, de l gaat mee.',
        },
        {
          q: 'Breek af op alle plekken: *verontschuldiging*',
          a: 'ver-ont-schul-di-ging',
          why: 'ver- en ont- zijn allebei voorvoegsels. Dan schul-di-ging: sch blijft heel.',
        },
        { q: 'Goede vorm van *dwaas*', before: 'Wat een', after: 'vraag!', a: 'dwaze', why: 'De vraag: -e. Je hoort een z, en dwa- is open: één a. dwaze.' },
        { q: 'Breek af op alle plekken: *uitnodiging*', a: 'uit-no-di-ging', why: 'uit- blijft heel. Daarna gaat één medeklinker steeds mee: no-di-ging.' },
        { q: 'Breek *coördinator* af op de plek van het trema', a: 'co-ordinator', why: 'Op de plek van het trema afbreken: het trema valt weg.' },
        { q: 'Meervoud van *de vriendin*', a: 'vriendinnen', why: 'vriendin heeft een korte i. Die blijft kort als je de n verdubbelt: vriendinnen.' },
        {
          q: 'Breek af op alle plekken: *gemeentehuis*',
          a: 'ge-meen-te-huis',
          why: 'gemeente + huis. ge- blijft heel, en de n en t gaan uit elkaar: meen-te.',
        },
        {
          q: 'Vul de vorm van *beantwoorden* in',
          before: 'Mijn collega',
          after: 'mijn mail als ik op vakantie ben.',
          a: 'beantwoordt',
          why: 'Mijn collega = hij: stam beantwoord + t. Dus beantwoordt.',
        },
        {
          q: 'Breek af op alle plekken: *huisartsenpost*',
          a: 'huis-art-sen-post',
          why: 'huis + artsen + post: eerst tussen de delen. art-sen: alleen de s gaat mee.',
        },
        { q: 'Schrijf als één woord: *video* + *opname*', a: 'video-opname', why: 'De o van video en de o van opname botsen: daar komt een koppelteken.' },
        {
          q: 'Breek af op alle plekken: *zorgverzekering*',
          a: 'zorg-ver-ze-ke-ring',
          why: 'zorg + verzekering. ver- blijft heel, en daarna gaat één medeklinker steeds mee.',
        },
        { q: 'Goede vorm van *eigen*', before: 'Ze heeft haar', after: 'bedrijf.', a: 'eigen', why: 'eigen eindigt al op -en: er komt nooit een -e achter.' },
        { q: 'Breek af op alle plekken: *werkgever*', a: 'werk-ge-ver', why: 'werk + gever: eerst tussen de delen. Dan ge-ver: de v gaat mee.' },
      ],
      done: {
        title: 'Reeks klaar',
        text: 'Eerst de delen, dan de lettergrepen. Klanken van twee letters blijven heel, ng gaat uit elkaar, en op de plek van het trema valt het trema weg.',
      },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul het briefje aan. Typ elk woord helemaal.',
      intro:
        'Je schrijft dit briefje met de hand, op een smal vel. Staat er *afbreken:* in het grijs? Typ dan het woord met een koppelteken op elke plek waar je het mag afbreken, bv. *ka-mer*. De andere gaten vul je gewoon in.',
      title: 'Briefje op het prikbord in de hal',
      text: 'Beste {be-wo-ners|afbreken: bewoners|be- is een voorvoegsel en blijft heel. Daarna gaat de n mee: wo-ners.},\n\nOp zaterdag om tien uur houden we een bijeenkomst in de {ge-meen-schaps-ruim-te|afbreken: gemeenschapsruimte|ge- blijft heel. Dan eerst tussen gemeenschaps en ruimte, en daarna ruim-te.}. Het gaat over de {huur-ver-ho-ging|afbreken: huurverhoging|huur + verhoging. ver- blijft heel, en de h gaat mee: ho-ging.} en over de {kapotte|kapot|De lift is een de-woord: -e. Korte o + t: de t wordt dubbel.} lift. De {ei-ge-naar|afbreken: eigenaar|ei blijft heel. Eén medeklinker gaat steeds mee: ei-ge-naar.} heeft in maart {beloofd|beloven|beloven: de v zit niet in ’t kofschip, dus een d. In de stam schrijf je een f: beloofd.} dat er snel een {mon-teur|afbreken: monteur|n en t: één aan elke kant. eu blijft heel.} zou komen. Maar we wachten nu al zes {weken|meervoud van week|we-ken: open lettergreep, dus één e.}. Voor {ou-de-ren|afbreken: ouderen|ou blijft heel, en de d gaat mee: ou-de-ren.} met slechte {knieën|meervoud van knie|knie + en: de ie en de e botsen, dus een trema op de e.} en ouders met een {kin-der-wa-gen|afbreken: kinderwagen|kinder + wagen. n en d: één aan elke kant.} is dat een groot probleem. Sommige bewoners lopen nu elke dag met hun boodschappen de trap op.\n\nOok zijn er {klach-ten|afbreken: klachten|ch blijft heel en blijft hier links staan: klach-ten.} over de {ver-lich-ting|afbreken: verlichting|ver- blijft heel. ch blijft heel: lich-ting.} in de {fiet-sen-stal-ling|afbreken: fietsenstalling|fietsen + stalling. t en s, en de dubbele l: één aan elke kant.}. Wie wil {mee-den-ken|afbreken: meedenken|mee + denken. n en k: één aan elke kant.} over een {op-los-sing|afbreken: oplossing|op + lossing. Dubbele s: één aan elke kant.}? De bijeenkomst {duurt|duren|De bijeenkomst = hij: stam + t. In duur is de lettergreep gesloten, dus uu.} ongeveer een uur. Iedereen is welkom, en er is koffie met appeltaart. Kunt u niet komen? Mail dan uw vragen of ideeën uiterlijk vrijdag naar het bestuur.\n\nMet {vriendelijke|vriendelijk|De groet is een de-woord: -e. Na -lijk verdubbel je niet.} groet,\nHet bestuur van de huurdersvereniging',
      why: 'Afbreken: eerst tussen de delen (huur-ver-ho-ging, kin-der-wa-gen, fiet-sen-stal-ling, mee-den-ken, op-los-sing) en na een voorvoegsel (be-wo-ners, ge-meen-schaps-ruim-te, ver-lich-ting). Dan de lettergrepen: één medeklinker gaat mee (ei-ge-naar, ou-de-ren), twee: één aan elke kant (mon-teur). ch, ei, ou en eu blijven heel. Uit eerdere lessen: kapotte (-e en tt), beloofd (d), weken (één e), knieën (trema), duurt (stam + t) en vriendelijke (-e).',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen uit een sollicitatiemail. Hoofdletters en leestekens tellen mee.',
      title: 'Een sollicitatie bij de kinderopvang',
      sentences: [
        'Beste coördinator, ik ben erg geïnteresseerd in de vacature bij uw kinderopvang.',
        'Ik heb ruime werkervaring als pedagogisch medewerker in Noord-Holland.',
        'Daar was ik ook verantwoordelijk voor het contact met de ouders.',
        'Ik heb veel ideeën over creatieve activiteiten voor jonge kinderen.',
        'In de bijlage vindt u mijn diploma’s en een aanbevelingsbrief van mijn vorige werkgever.',
        'Ik zie uit naar een uitnodiging voor een kennismakingsgesprek.',
      ],
      right:
        'Alles goed: coördinator, geïnteresseerd en ideeën met trema, Noord-Holland met koppelteken en twee hoofdletters, vindt met dt, diploma’s met apostrof, en de lange samenstellingen aan elkaar.',
      wrong:
        'Kijk na: het trema in coördinator, geïnteresseerd en ideeën. Noord-Holland met koppelteken en twee hoofdletters. u vindt: stam + t. diploma’s met apostrof. creatieve (v), ruime en jonge (-e). En samenstellingen schrijf je aan elkaar: kinderopvang, werkervaring, aanbevelingsbrief, kennismakingsgesprek.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de nieuwsbrief na voordat hij verstuurd wordt',
      intro:
        'Een collega typte deze tekst over uit een smalle kolom. Waar een woord over twee regels ging, staat nog het streepje. Kijk of elk streepje goed staat, en kijk ook de spelling na. Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'alle patiënten', subject: 'Nieuws van de huisartsenpraktijk' },
      greeting: 'Beste patiënten,',
      signoff: 'Met vriendelijke groet,\nhet team van de huisartsenpraktijk',
      tokens: [
        { t: 'Vanaf' },
        { t: 'volgende' },
        { t: 'week' },
        { t: 've-randert', fix: 'ver-andert', also: ['veran-dert', 'verandert'], why: 'ver- is een voorvoegsel en blijft heel: ver-an-dert.' },
        { t: 'het' },
        { t: 'spree-kuur', fix: 'spreek-uur', also: ['spreekuur'], why: 'spreek + uur: eerst tussen de delen. De k hoort bij spreek.' },
        { t: 'van' },
        { t: 'onze' },
        { t: 'praktijk.' },
        { t: 'U' },
        { t: 'kunt' },
        { t: 'dan' },
        { t: 'alleen' },
        { t: 'nog' },
        { t: 'op' },
        { t: 'afspraak' },
        { t: 'komen.' },
        { t: 'Bel' },
        { t: 'daarvoor' },
        { t: 'op' },
        { t: 'werkdagen' },
        { t: 'tussen' },
        { t: 'acht' },
        { t: 'en' },
        { t: 'tien' },
        { t: 'uur.' },
        { t: 'Ook' },
        { t: 'onze' },
        { t: 'nieuw', fix: 'nieuwe', why: 'Na onze krijgt het bijvoeglijk naamwoord een -e: onze nieuwe praktijkondersteuner.' },
        {
          t: 'praktij-kondersteuner',
          fix: 'praktijk-ondersteuner',
          also: ['prak-tijkondersteuner', 'praktijkon-dersteuner', 'praktijkonder-steuner', 'praktijkondersteu-ner', 'praktijkondersteuner'],
          why: 'praktijk + ondersteuner: eerst tussen de delen. De k hoort bij praktijk.',
        },
        { t: 'begint' },
        { t: 'dan.' },
        { t: 'Zij' },
        { t: 'is' },
        { t: 'erg' },
        { t: 'ge-interesseerd', trap: 'Goed: hier is afgebroken op de plek van het trema. Dan valt het trema weg: ge-interesseerd.' },
        { t: 'in' },
        { t: 'uw' },
        {
          t: 'ervaring-en.',
          fix: 'ervarin-gen.',
          also: ['er-varingen.', 'erva-ringen.', 'ervaringen.'],
          why: 'ng gaat bij afbreken uit elkaar: er-va-rin-gen.',
        },
        { t: 'Daar-om', trap: 'Goed: daar + om. Eerst tussen de delen, dus niet daa-rom.' },
        { t: 'vragen' },
        { t: 'wij' },
        { t: 'u' },
        { t: 'een' },
        { t: 'korte' },
        { t: 'vragenlijst' },
        { t: 'in' },
        { t: 'te' },
        { t: 'vullen.' },
        { t: 'Die' },
        { t: 'ligt' },
        { t: 'in' },
        { t: 'de' },
        { t: 'wachtkamer.' },
        { t: 'Ook' },
        { t: 'jon-geren', trap: 'Goed: ng gaat bij afbreken uit elkaar: jon-ge-ren.' },
        { t: 'mogen' },
        { t: 'meedoen.' },
        { t: 'Heeft' },
        { t: 'u' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: de e’s botsen. Het trema laat zien dat ën een nieuwe lettergreep is: ideeën.' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'praktijk?' },
        { t: 'Mail' },
        { t: 'ze' },
        { t: 'naar' },
        { t: 'onze' },
        { t: 'co-ordinator.', trap: 'Goed: hier is afgebroken op de plek van het trema. Dan valt het trema weg: co-ordinator.' },
        { t: 'De' },
        { t: 'apotheek' },
        { t: 'naast' },
        { t: 'de' },
        { t: 'praktijk' },
        { t: 'word', fix: 'wordt', why: 'De apotheek = hij: stam word + t. Dus wordt.' },
        { t: 'volgende' },
        { t: 'maand' },
        { t: 'verbouwd.' },
        { t: 'Op' },
        { t: 'Maandag', fix: 'maandag', why: 'De dagen van de week schrijf je met een kleine letter.' },
        { t: 'en' },
        { t: 'dinsdag' },
        { t: 'is' },
        { t: 'hij' },
        { t: 'dan' },
        { t: 'dicht.' },
      ],
    },
  ],
};
