import type { LessonInput } from '../../schema';

/** Praktijkles voor "De lettergreep": een woord afbreken aan het eind van de regel, met de regels, uitzonderingen en een stappenplan. */
export const LES_G27: LessonInput = {
  id: 'g27',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'Afbreken aan het eind van de regel',
  skill: 'Spelling',
  icon: 'ma-',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Waar mag het streepje?',
      panels: [
        {
          text: 'Past een woord niet meer op de regel? Dan mag je het *afbreken*. Je zet een koppelteken aan het eind van de regel en schrijft de rest van het woord op de volgende regel. Je breekt af op de grens van twee lettergrepen: *ma-ken*, *bo-men*, *ta-fel*. Op de computer en de telefoon doet het programma dit meestal zelf. Maar bij schrijven met de hand, op een formulier of op een bord moet je het zelf kunnen.',
          rule: 'Afbreken doe je op een lettergreepgrens, met een koppelteken aan het eind van de regel: *ma-ken*.',
          split: { q: 'Breek het woord af', word: 'maken', answer: 'ma-ken', note: 'Eén medeklinker tussen de klinkers: de k gaat naar de volgende lettergreep.' },
        },
        {
          text: 'Staat er één medeklinker tussen twee klinkers? Dan gaat die mee naar de volgende lettergreep: *bo-men*, *le-zen*, *ta-fel*. Staan er twee medeklinkers? Dan gaat er één mee en blijft er één staan: *kan-ten*, *kas-ten*, *har-ten*. Een dubbele medeklinker gaat dus uit elkaar: *bak-ker*, *kat-ten*, *kof-fie*.',
          rule: 'Eén medeklinker: die gaat mee (*bo-men*). Twee medeklinkers: één aan elke kant (*bak-ker*, *kan-ten*).',
          split: { q: 'Breek het woord af', word: 'bakker', answer: 'bak-ker', note: 'Twee k’s: één aan elke kant van het streepje.' },
        },
        {
          text: 'Letters die samen één klank maken, haal je nooit uit elkaar: *oe*, *ie*, *ij*, *ui*, *eu*, *ei*, *aa*, *ou*. Dus *blij-ven*, *boe-ken*, *hui-zen*, *keu-ken*. Ook de *ch* blijft altijd heel: *la-chen*, nooit *lac-hen*. Maar de *ng* gaat wél uit elkaar, ook al hoor je één klank: *zin-gen*, *jon-gen*.',
          rule: '*ch*, *oe*, *ij*, *ui* en andere klanken van twee letters blijven heel. *ng* gaat uit elkaar: *zin-gen*.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'lachen', out: 'la-chen', note: 'ch blijft heel. Nooit lac-hen.' },
              { k: 'zingen', out: 'zin-gen', note: 'ng gaat uit elkaar: n op de eerste regel, g op de volgende.' },
              { k: 'blijven', out: 'blij-ven', note: 'ij blijft heel. Nooit bli-jven.' },
              { k: 'huizen', out: 'hui-zen', note: 'ui blijft heel.' },
              { k: 'jongen', out: 'jon-gen', note: 'Weer ng: uit elkaar.' },
            ],
          },
        },
        {
          text: 'Bestaat een woord uit twee woorden, of heeft het een voorvoegsel als *ver-*, *her-*, *be-* of *ont-*? Dan knip je eerst tussen de delen. *fiets-pomp*, *boe-ken-kast*, *aard-ap-pel*. Bij *veranderen* zeg je misschien *ve-ran-de-ren*, maar je breekt af als *ver-an-de-ren*, want *ver-* is één deel. Zo ook *her-in-ne-ren* en *ont-bijt*.',
          rule: 'Samenstelling of voorvoegsel: eerst tussen de delen knippen (*aard-ap-pel*, *ver-an-de-ren*).',
          split: { q: 'Breek het woord af, op alle plekken waar het mag', word: 'aardappel', answer: 'aard-ap-pel', note: 'aard + appel. Eerst tussen de twee woorden, dan in appel: ap-pel.' },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'goed-fout',
      prompt: 'Goed of fout afgebroken?',
      buckets: ['goed', 'fout'],
      items: [
        { t: 'la-chen', b: 0 },
        { t: 'lac-hen', b: 1 },
        { t: 'zin-gen', b: 0 },
        { t: 'zi-ngen', b: 1 },
        { t: 'bli-jven', b: 1 },
        { t: 'kat-ten', b: 0 },
        { t: 'ka-tten', b: 1 },
        { t: 'boe-ken', b: 0 },
        { t: 'bo-eken', b: 1 },
        { t: 'ver-an-de-ren', b: 0 },
        { t: 've-ran-de-ren', b: 1 },
        { t: 'kas-ten', b: 0 },
      ],
      why: 'ch, ij en oe blijven heel; ng gaat uit elkaar; een dubbele medeklinker gaat uit elkaar (kat-ten); bij twee medeklinkers één aan elke kant (kas-ten); en ver- blijft heel.',
    },
    {
      kind: 'choice',
      id: 'lachen',
      prompt: 'Welke afbreking is goed?',
      before: 'Wat moesten we',
      after: 'om die film!',
      options: ['la-chen', 'lac-hen', 'lach-en'],
      answer: 'la-chen',
      why: 'ch blijft heel en gaat mee naar de volgende lettergreep: la-chen.',
    },
    {
      kind: 'type',
      id: 'boterham',
      prompt: 'Breek het woord af. Zet een koppelteken op elk afbreekpunt.',
      before: 'boterham =',
      after: '',
      hint: 'met koppeltekens',
      answer: 'bo-ter-ham',
      why: 'Eén medeklinker tussen de klinkers gaat steeds mee: bo-ter-ham.',
    },
    {
      kind: 'bet',
      id: 'zingen',
      prompt: 'Je hoort in zingen maar één klank voor ng. Hoe breek je het af?',
      options: ['zin-gen', 'zi-ngen', 'zing-en'],
      answer: 'zin-gen',
      why: 'ng gaat bij afbreken uit elkaar: zin-gen. Dat is anders dan bij ch, die heel blijft.',
    },
    {
      kind: 'type',
      id: 'vakantie',
      prompt: 'Breek het woord af. Zet een koppelteken op elk afbreekpunt.',
      before: 'vakantie =',
      after: '',
      hint: 'met koppeltekens',
      answer: 'va-kan-tie',
      why: 'va: één medeklinker, die gaat mee. kan-tie: twee medeklinkers (n en t), één aan elke kant. ie blijft heel.',
    },
    {
      kind: 'choice',
      id: 'fietspomp',
      prompt: 'Waar breek je fietspomp af?',
      before: 'Mag ik je',
      after: 'even lenen?',
      options: ['fiets-pomp', 'fiet-spomp', 'fietsp-omp'],
      answer: 'fiets-pomp',
      why: 'fiets + pomp: een samenstelling. Je knipt tussen de twee woorden.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Lastige gevallen en een stappenplan',
      panels: [
        {
          text: 'Breek je af op de plek van een trema? Dan valt het trema weg. Het koppelteken laat nu al zien dat de klinkers los klinken. *ruïne* wordt *ru-ine*, *knieën* wordt *knie-en*. Breek je op een andere plek af, dan blijft het trema gewoon staan.',
          rule: 'Afbreken op de plek van het trema: het trema valt weg (*ru-ine*, *knie-en*).',
          quiz: {
            q: 'Je breekt knieën af op de plek van het trema. Wat schrijf je?',
            options: ['knie-en', 'knie-ën', 'kni-eën'],
            answer: 'knie-en',
            why: 'Op de plek van het trema afbreken: het trema valt weg. ie blijft heel.',
          },
        },
        {
          text: 'Heeft een woord al een koppelteken, zoals *Noord-Holland*, *zee-egel* of *tv-programma*? Breek het dan af op dat koppelteken. Het koppelteken blijft aan het eind van de regel staan, en je zet er geen tweede bij: *Noord-* op de eerste regel, *Holland* op de volgende.',
          rule: 'Woord met koppelteken: afbreken op dat koppelteken, zonder extra streepje.',
          quiz: {
            q: 'Wat zet je aan het eind van de regel als je Noord-Holland afbreekt?',
            options: ['Noord-', 'Noord--', 'Noor-'],
            answer: 'Noord-',
            why: 'Je breekt af op het koppelteken dat er al staat. Holland komt op de volgende regel.',
          },
        },
        {
          text: 'Sommige afbrekingen zijn niet fout, maar je doet ze *liever niet*. Laat geen losse letter achter op een regel: *a-pen* of *e-zel* spaart bijna geen ruimte en leest rommelig. Breek een naam, een getal, een datum of een afkorting liever niet af. En breek alleen af als het echt moet.',
          rule: 'Liever niet: een losse letter (*a-pen*), en geen naam, getal of afkorting afbreken.',
          lab: {
            label: 'Tik een afbreking',
            chips: [
              { k: 'a-pen', out: 'liever niet', note: 'Een losse a op de regel: dan zet je liever het hele woord op de volgende regel.' },
              { k: 'e-zel', out: 'liever niet', note: 'Ook een losse letter. Niet fout, maar niet mooi.' },
              { k: 'ta-fel', out: 'prima', note: 'Twee letters op de eerste regel: dat mag.' },
              { k: 'Fati-ma', out: 'liever niet', note: 'Een naam breek je liever niet af.' },
            ],
          },
        },
        {
          text: 'Twijfel je? Gebruik dit stappenplan. 1. Past het woord echt niet meer? Breek dan pas af. 2. Bestaat het woord uit delen (samenstelling of voorvoegsel)? Knip eerst tussen de delen. 3. Zoek de klinkerklanken. Eén medeklinker ertussen: die gaat mee. Twee: één aan elke kant. 4. *ch*, *oe*, *ij*, *ui* en de andere klanken van twee letters blijven heel. *ng* gaat uit elkaar. 5. Laat geen losse letter achter.',
          rule: 'Delen → klinkers → medeklinkers verdelen → klanken heel laten → geen losse letter.',
          split: {
            q: 'Breek het woord af, op alle plekken waar het mag',
            word: 'ziekenhuis',
            answer: 'zie-ken-huis',
            note: 'zieken + huis. Eerst tussen de delen, dan in zieken: zie-ken. ie en ui blijven heel.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'printer',
      prompt: 'Een oud programma heeft deze woorden afgebroken. Vind de vijf fouten.',
      intro: 'Kijk bij elk woord: staat het streepje op een goede plek?',
      tokens: [
        { t: 'boe-ken,' },
        { t: 'zi-ngen,', fix: 'zin-gen,', why: 'ng gaat uit elkaar: zin-gen.' },
        { t: 'fiets-pomp,' },
        { t: 'lac-hen,', fix: 'la-chen,', why: 'ch blijft heel: la-chen.' },
        { t: 'ka-tten,', fix: 'kat-ten,', why: 'Een dubbele medeklinker gaat uit elkaar: kat-ten.' },
        { t: 'ver-an-de-ren,' },
        { t: 'ru-ïne,', fix: 'ru-ine,', why: 'Op de plek van het trema afbreken: het trema valt weg.' },
        { t: 'ta-fel,' },
        { t: 'bli-jven,', fix: 'blij-ven,', why: 'ij blijft heel: blij-ven.' },
        { t: 'kas-ten.' },
      ],
      done: {
        title: 'Beter dan het programma',
        text: 'zin-gen, la-chen, kat-ten, ru-ine en blij-ven. De andere vijf waren goed.',
      },
    },
    {
      kind: 'swipe',
      id: 'afbreek-swipe',
      prompt: 'Goed of fout?',
      intro: 'Veeg naar rechts als de bewering of afbreking klopt, naar links als hij niet klopt.',
      cards: [
        { t: 'herinneren breek je af als her-in-ne-ren.', ok: true, why: 'her- is een voorvoegsel en blijft heel. Daarna gaat de dubbele n uit elkaar.' },
        { t: 'Bij afbreken blijft de ng altijd heel.', ok: false, fix: 'ng gaat uit elkaar: zin-gen', why: 'ch blijft heel, ng niet.' },
        { t: 'kinderen breek je af als kin-de-ren.', ok: true, why: 'Twee medeklinkers (n en d): één aan elke kant. Daarna één medeklinker: de-ren.' },
        { t: 'keuken breek je af als ke-uken.', ok: false, fix: 'keu-ken', why: 'eu blijft heel: keu-ken.' },
        { t: 'Bij Noord-Holland zet je aan het eind van de regel Noord-.', ok: true, why: 'Je breekt af op het koppelteken dat er al staat.' },
        { t: 'ontbijt breek je af als on-tbijt.', ok: false, fix: 'ont-bijt', why: 'ont- is een voorvoegsel: dat blijft heel.' },
        { t: 'a-pen is een afbreking die je liever niet maakt.', ok: true, why: 'Een losse letter op de regel spaart bijna niets en leest rommelig.' },
        { t: 'koffie breek je af als ko-ffie.', ok: false, fix: 'kof-fie', why: 'Een dubbele medeklinker gaat uit elkaar.' },
      ],
    },
    {
      kind: 'type',
      id: 'verhuizen',
      prompt: 'Breek het woord af. Zet een koppelteken op elk afbreekpunt.',
      before: 'verhuizen =',
      after: '',
      hint: 'met koppeltekens',
      answer: 'ver-hui-zen',
      why: 'ver- is een voorvoegsel en blijft heel. ui blijft heel, en de z gaat mee: hui-zen.',
    },
    {
      kind: 'bet',
      id: 'ruine',
      prompt: 'Je breekt ruïne af op de plek van het trema. Wat schrijf je?',
      options: ['ru-ine', 'ru-ïne', 'rui-ne'],
      answer: 'ru-ine',
      why: 'Op de plek van het trema afbreken: het trema valt weg, want het koppelteken laat al zien dat u en i los klinken. rui-ne is fout: dan lees je ui.',
    },
    {
      kind: 'type',
      id: 'boekenkast',
      prompt: 'Breek het woord af. Zet een koppelteken op elk afbreekpunt.',
      before: 'boekenkast =',
      after: '',
      hint: 'met koppeltekens',
      answer: 'boe-ken-kast',
      why: 'boeken + kast. Eerst tussen de delen, dan in boeken: boe-ken. oe blijft heel.',
    },
    {
      kind: 'sort',
      id: 'eerst-delen',
      prompt: 'Waar knip je eerst?',
      buckets: ['tussen twee delen van het woord', 'gewoon tussen de lettergrepen'],
      items: [
        { t: 'fiets-pomp', b: 0 },
        { t: 'ver-an-de-ren', b: 0 },
        { t: 'aard-ap-pel', b: 0 },
        { t: 'ont-bijt', b: 0 },
        { t: 'zie-ken-huis', b: 0 },
        { t: 'bo-men', b: 1 },
        { t: 'kat-ten', b: 1 },
        { t: 'la-chen', b: 1 },
        { t: 'zin-gen', b: 1 },
        { t: 'va-kan-tie', b: 1 },
      ],
      why: 'fiets + pomp, aard + appel en zieken + huis zijn samenstellingen; ver- en ont- zijn voorvoegsels: daar knip je eerst tussen de delen. bomen, katten, lachen, zingen en vakantie hebben geen losse delen: je volgt gewoon de lettergrepen.',
    },
    {
      kind: 'type',
      id: 'oefenen',
      prompt: 'Breek het woord af. Zet een koppelteken op elk afbreekpunt.',
      before: 'oefenen =',
      after: '',
      hint: 'met koppeltekens',
      answer: 'oe-fe-nen',
      why: 'Drie klinkerklanken: oe, e, e. Steeds één medeklinker ertussen, en die gaat mee: oe-fe-nen. Een losse oe vooraan is twee letters, dus dat mag.',
    },
    {
      kind: 'rewrite',
      id: 'appeltaart',
      prompt: 'Breek het woord af op alle plekken waar het mag. Zet een koppelteken op elk afbreekpunt.',
      source: 'appeltaart',
      accept: ['ap-pel-taart'],
      why: 'appel + taart. In appel gaat de dubbele p uit elkaar: ap-pel. aa blijft heel.',
    },
  ],
};
