import type { LessonInput } from '../../schema';

/** Toets voor "De lettergreep": lettergrepen, open en gesloten, verdubbelen, meervoud, verkleinwoord, stam, bijvoeglijk naamwoord met -e en afbreken door elkaar. */
export const LES_G28: LessonInput = {
  id: 'g28',
  stage: 'toets',
  domain: 'orth',
  also: ['morf'],
  title: 'Toets: De lettergreep',
  skill: 'Spelling',
  icon: 'toets',
  steps: [
    {
      kind: 'explain',
      id: 'overzicht',
      title: 'De regels op een rij',
      panels: [
        {
          text: 'Elke lettergreep heeft één klinkerklank. *ie*, *ui*, *aai* en *eeuw* tellen als één klank. Eindigt een lettergreep op een klinker, dan is hij *open*: daar schrijf je een lange klank met één letter (*ra-men*, *bo-men*, *mu-ren*). Eindigt hij op een medeklinker, dan is hij *gesloten*: daar heb je twee letters nodig (*raam*, *boom*, *muur*). Aan het eind van een woord schrijf je *a*, *o*, *u* en *i* met één letter (*pa*, *foto*, *menu*, *taxi*), maar *ee* met twee (*zee*, *twee*, *idee*).',
          rule: 'Open lettergreep: één letter (*bo-men*). Gesloten: twee (*boom*).',
          split: {
            q: 'Knip het woord in lettergrepen',
            word: 'kinderen',
            answer: 'kin-de-ren',
            note: 'Drie klinkerklanken, dus drie lettergrepen. Bij nd gaat er één medeklinker mee.',
          },
        },
        {
          text: 'Na een korte klank met één medeklinker wordt die medeklinker dubbel als er een klinker achter komt, zodat de klank kort blijft: *bal* → *ballen*, *wit* → *witte*. Niet na een lange klank (*raam* → *ramen*), niet na twee medeklinkers (*kast* → *kasten*) en niet na een doffe e (*gezellige*). Het meervoud is meestal *-en* (*boeken*). Na *-el*, *-em*, *-en*, *-er* en *-je* zonder klemtoon: *-s* (*tafels*, *kamers*, *huisjes*). Na *a*, *i*, *o*, *u* en *y*: *’s* (*auto’s*, *menu’s*, *baby’s*). En *zee* wordt *zeeën*.',
          rule: 'Korte klank + één medeklinker: dubbel (*ballen*). Meervoud: *-en*, *-s* of *’s*.',
          quiz: {
            q: 'Welk meervoud is goed?',
            options: ['twee foto’s', 'twee fotos', 'twee fotoos'],
            answer: 'twee foto’s',
            why: 'foto eindigt op een o. Met alleen een s zou je fo-tos lezen, met een korte o. De apostrof houdt de o lang: foto’s.',
          },
        },
        {
          text: 'Het verkleinwoord hangt af van het eind van het woord. Meestal *-je* (*boekje*, *kastje*, *hoedje*). Na een lange klank, een tweeklank of een doffe e + *l*, *n* of *r*: *-tje* (*stoeltje*, *treintje*, *tafeltje*). Na een *m*: *-pje* (*boompje*, *bezempje*, *filmpje*), behalve na een korte klank met klemtoon. Na een korte klank met klemtoon + *l*, *m*, *n*, *r* of *ng*: *-etje* (*balletje*, *zonnetje*, *ringetje*). Woorden op *a*, *o*, *u*: klinker dubbel + *tje* (*autootje*, *omaatje*).',
          rule: '*-je*, *-tje*, *-pje*, *-etje* of *-kje*: kijk naar de laatste klank en de klemtoon.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'boek', out: 'boekje', note: 'Na een k: -je.' },
              { k: 'stoel', out: 'stoeltje', note: 'oe + l: -tje.' },
              { k: 'boom', out: 'boompje', note: 'Lange o + m: -pje.' },
              { k: 'bal', out: 'balletje', note: 'Korte a + l, met klemtoon: -etje, en de l wordt dubbel.' },
              { k: 'koning', out: 'koninkje', note: '-ing zonder klemtoon: -kje.' },
              { k: 'auto', out: 'autootje', note: 'Eindigt op o: de o wordt dubbel, dan -tje.' },
            ],
          },
        },
        {
          text: 'De stam is het hele werkwoord min *-en*, met dezelfde regels: *lopen* → *loop*, *zetten* → *zet*, *leven* → *leef*, *reizen* → *reis*. *Ik* + stam, *jij*/*hij*/*zij*/*u* + stam + *t*, *wij*/*jullie*/*zij* + hele werkwoord. Geen *t* als *jij* of *je* achter het werkwoord staat: *Kom jij?* En bij een bijvoeglijk naamwoord met *-e* gebeurt hetzelfde: *groot* → *grote*, *dik* → *dikke*, *lief* → *lieve*. Stofnamen op *-en* krijgen geen *-e*: *een houten tafel*.',
          rule: 'Stam: *lopen* → *loop*. Bijvoeglijk naamwoord: *groot* → *grote*, *dik* → *dikke*.',
          build: {
            before: 'Mijn broer … elke dag naar zijn werk. (lopen)',
            stem: 'loop',
            endings: ['', 't', 'en', 'pt'],
            answer: 't',
            note: 'Stam loop (gesloten lettergreep, twee o’s), en bij hij komt er een t bij: loopt.',
          },
        },
        {
          text: 'Afbreken doe je op een lettergreepgrens, met een koppelteken aan het eind van de regel. Eén medeklinker gaat mee (*ma-ken*), bij twee gaat er één mee (*bak-ker*, *kan-ten*). *ch* en klanken als *oe*, *ij*, *ui* blijven heel (*la-chen*, *blij-ven*), *ng* gaat uit elkaar (*zin-gen*). Samenstellingen en voorvoegsels knip je eerst tussen de delen (*ver-an-de-ren*). Op de plek van een trema valt het trema weg (*knie-en*).',
          rule: 'Lettergreepgrens; *ch* heel, *ng* los; eerst tussen de delen.',
          split: {
            q: 'Breek het woord af, op alle plekken waar het mag',
            word: 'boodschappen',
            answer: 'bood-schap-pen',
            note: 'bood + schappen: eerst tussen de delen. Dan gaat de dubbele p uit elkaar: schap-pen.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'meervoud',
      prompt: 'Welk meervoud krijgt het woord?',
      buckets: ['-en', '-s', '’s'],
      items: [
        { t: 'kasteel', b: 0 },
        { t: 'bezem', b: 1 },
        { t: 'pagina', b: 2 },
        { t: 'vriendin', b: 0 },
        { t: 'café', b: 1 },
        { t: 'collega', b: 2 },
        { t: 'monnik', b: 0 },
        { t: 'cadeau', b: 1 },
        { t: 'paraplu', b: 2 },
        { t: 'probleem', b: 0 },
        { t: 'garage', b: 1 },
        { t: 'hobby', b: 2 },
        { t: 'cursus', b: 0 },
        { t: 'lepel', b: 1 },
        { t: 'euro', b: 2 },
      ],
      why: 'kastelen, vriendinnen, monniken, problemen, cursussen: -en. bezems en lepels: -em en -el zonder klemtoon. cafés, cadeaus, garages: na é, eau en een doffe e alleen -s. pagina’s, collega’s, paraplu’s, hobby’s, euro’s: na a, u, y en o een apostrof.',
    },
    {
      kind: 'type',
      id: 'sterretje',
      prompt: 'Typ het verkleinwoord van ster.',
      before: 'Voor elk goed antwoord kreeg mijn zoon een',
      after: 'in zijn schrift.',
      hint: '',
      answer: 'sterretje',
      why: 'Korte e + r, met klemtoon: -etje. De r wordt dubbel, zodat de e kort blijft: ster-re-tje.',
    },
    {
      kind: 'proofread',
      id: 'mail-school',
      prompt: 'Vind de fouten in deze mail aan de juf.',
      header: { to: 'juf Anna', subject: 'Lina is ziek' },
      greeting: 'Beste juf Anna,',
      signoff: 'Met vriendelijke groet,\nHasan',
      tokens: [
        { t: 'Mijn' },
        { t: 'dochter' },
        { t: 'Lina' },
        { t: 'is' },
        { t: 'vandaag' },
        { t: 'ziek.' },
        { t: 'Ze' },
        { t: 'heeft' },
        { t: 'hooge', fix: 'hoge', why: 'ho-ge: open lettergreep, één o.' },
        { t: 'koorts' },
        { t: 'en' },
        { t: 'slaapt' },
        { t: 'bijna' },
        { t: 'de' },
        { t: 'hele' },
        { t: 'dag.' },
        { t: 'Ik' },
        { t: 'werkt', fix: 'werk', why: 'Bij ik alleen de stam: ik werk.' },
        { t: 'thuis' },
        { t: 'en' },
        { t: 'blijf' },
        { t: 'bij' },
        { t: 'haar.' },
        { t: 'Ze' },
        { t: 'is' },
        { t: 'misschien' },
        { t: 'twee' },
        { t: 'daggen', fix: 'dagen', why: 'dag → dagen: een woord uit het rijtje met een lange klank in het meervoud. da-gen, één g.' },
        { t: 'thuis.' },
        { t: 'Kunt' },
        { t: 'u' },
        { t: 'de' },
        { t: 'nieuwe' },
        { t: 'boekken', fix: 'boeken', why: 'oe is een vaste klank: daarna verdubbel je nooit. boe-ken.' },
        { t: 'meegeven' },
        { t: 'aan' },
        { t: 'haar' },
        { t: 'vriendinnetje' },
        { t: 'Sara?' },
        { t: 'Ze' },
        { t: 'mist' },
        { t: 'haar' },
        { t: 'klasgenooten', fix: 'klasgenoten', why: 'ge-no-ten: open lettergreep, één o.' },
        { t: 'nu' },
        { t: 'al.' },
      ],
      done: {
        title: 'Mail verbeterd',
        text: 'hoge, werk, dagen, boeken en klasgenoten. En vriendinnetje, nieuwe en hele waren goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-tuin',
      prompt: 'Luister en typ de zin.',
      sentence: 'In de herfst spelen de kinderen van de buren met hun nieuwe ballen in onze smalle en vochtige tuin.',
      right: 'Goed: herfst met een kleine letter, spelen met één e, ballen en smalle met ll, en vochtige zonder dubbele g.',
      wrong:
        'Let op: herfst klein (een seizoen), spe-len met één e (open lettergreep), bal-len en smal-le met ll (korte a), nieuwe met ieuw, en vochtige: na -ig nooit een dubbele g.',
    },
    {
      kind: 'choice',
      id: 'steden',
      prompt: 'Kies het goede meervoud.',
      before: 'Amsterdam en Rotterdam zijn grote',
      after: '.',
      options: ['steden', 'stadden', 'staden', 'stads'],
      answer: 'steden',
      why: 'stad → steden: een uitzondering die je moet leren. De a wordt een lange e.',
    },
    {
      kind: 'fix',
      id: 'dekens',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'De verpleegkundige bracht ons twee warme dekkens voor de nacht.',
      wrong: 6,
      answer: 'dekens',
      why: 'de-ken: de eerste e is lang en sluit de lettergreep af, dus één k. deken eindigt op -en zonder klemtoon: meervoud met -s. Dus dekens.',
    },
    {
      kind: 'swipe',
      id: 'toets-swipe',
      prompt: 'Goed of fout?',
      intro: 'Veeg naar rechts als de zin helemaal klopt, naar links als er een fout in staat.',
      cards: [
        {
          t: 'Wordt je broer ook uitgenodigd voor de bruiloft?',
          ok: true,
          why: 'Hier betekent je jouw. Het onderwerp is je broer (hij): stam word + t = wordt.',
        },
        { t: 'Hoelang werkt jij al bij dit bedrijf?', ok: false, fix: 'werkt → werk', why: 'jij staat achter het werkwoord: geen t. Werk jij?' },
        {
          t: 'Alle kinderen kregen een ijsje en een ballonnetje.',
          ok: true,
          why: 'ballon heeft de klemtoon op lon: korte o + n met klemtoon, dus -etje en een dubbele n.',
        },
        { t: 'Op tafel lagen vier nieuwe agenda’s.', ok: true, why: 'agenda eindigt op een a: meervoud met ’s.' },
        {
          t: 'Het restaurant heeft drie verschillende menus.',
          ok: false,
          fix: 'menus → menu’s',
          why: 'menu eindigt op een u: ’s. Zonder apostrof lees je een korte u.',
        },
        { t: 'Mijn dochter kreeg een gouden ringetje van haar oma.', ok: true, why: 'gouden is een stofnaam op -en: geen -e. ring heeft klemtoon: ringetje.' },
        { t: 'De vergaderring begint om negen uur.', ok: false, fix: 'vergaderring → vergadering', why: 'ver-ga-de-ring: na de doffe e verdubbel je niet.' },
        {
          t: 'Wij hebben de lekke band zelf gerepareert.',
          ok: false,
          fix: 'gerepareert → gerepareerd',
          why: 'Stam repareer eindigt op een r. Die staat niet in ’t kofschip: -d. gerepareerd.',
        },
        {
          t: 'Je breekt veranderen af als ve-ran-de-ren.',
          ok: false,
          fix: 've-ran-de-ren → ver-an-de-ren',
          why: 'ver- is een voorvoegsel: dat knip je eerst los. ver-an-de-ren.',
        },
        {
          t: 'Zij kreeg een financiëel voordeel.',
          ok: false,
          fix: 'financiëel → financieel',
          why: 'het voordeel, na een: geen -e. Zonder -e komt er geen trema: een financieel voordeel.',
        },
        { t: 'Ze wonen in een vrolijk, gezellig huisje aan zee.', ok: true, why: 'het huisje is een het-woord: na een geen -e. Dus vrolijk en gezellig.' },
        {
          t: 'De cursussen van de bibliotheek beginnen in september.',
          ok: true,
          why: 'cursus → cursussen: korte u + s, dus ss. september is een maand: kleine letter.',
        },
        { t: 'Wij vieren het Suikerfeest en Pasen met de hele familie.', ok: true, why: 'Feestdagen krijgen een hoofdletter: Suikerfeest, Pasen.' },
      ],
    },
    {
      kind: 'speed',
      id: 'los-vast',
      prompt: 'Aan elkaar of los?',
      intro: 'Met -e staat het bijvoeglijk naamwoord meestal los: een grote broer. Zonder -e en met een eigen betekenis is het één woord: grootvader.',
      seconds: 40,
      items: [
        { a: 'groot', b: 'vader', joined: true, tip: 'grootvader: je opa.' },
        { a: 'grote', b: 'broer', joined: false, tip: 'een grote broer: twee woorden.' },
        { a: 'zuur', b: 'kool', joined: true, tip: 'zuurkool: een gerecht.' },
        { a: 'zure', b: 'appels', joined: false, tip: 'zure appels: appels die zuur zijn.' },
        { a: 'wit', b: 'brood', joined: true, tip: 'witbrood: een soort brood.' },
        { a: 'witte', b: 'muren', joined: false, tip: 'witte muren: muren die wit zijn.' },
        { a: 'snel', b: 'weg', joined: true, tip: 'snelweg: de autoweg.' },
        { a: 'snelle', b: 'auto', joined: false, tip: 'een snelle auto: twee woorden.' },
      ],
      done: {
        title: 'Los of vast',
        text: 'Met -e meestal los, zonder -e en met een eigen betekenis vast: grootvader, zuurkool, witbrood, snelweg.',
      },
    },
    {
      kind: 'bet',
      id: 'woninkje',
      prompt: 'Een kleine woning is een…',
      options: ['woninkje', 'woningetje', 'woningje', 'woningkje'],
      answer: 'woninkje',
      why: '-ing zonder klemtoon krijgt -kje, en de g valt weg: woninkje, net als koninkje. Bij ring (met klemtoon) is het ringetje.',
    },
    {
      kind: 'proofread',
      id: 'boodschappen',
      prompt: 'Vind de fouten in dit appje.',
      header: { to: 'Samira' },
      tokens: [
        { t: 'Hoi,' },
        { t: 'wil' },
        { t: 'jij' },
        { t: 'boodschappen' },
        { t: 'doen?' },
        { t: 'We' },
        { t: 'hebben' },
        { t: 'nodig:' },
        { t: 'zes' },
        { t: 'eiers,', fix: 'eieren,', why: 'ei → eieren: een woord met -eren in het meervoud.' },
        { t: 'drie' },
        { t: 'paprikas,', fix: 'paprika’s,', why: 'Na een a komt ’s: paprika’s.' },
        { t: 'twee' },
        { t: 'brooden,', fix: 'broden,', why: 'bro-den: open lettergreep, één o.' },
        { t: 'twee' },
        { t: 'flessjes', fix: 'flesjes', why: 'Bij -je verdubbel je niet: fles → flesje.' },
        { t: 'water,' },
        { t: 'tomaatjes' },
        { t: 'en' },
        { t: 'een' },
        { t: 'groote', fix: 'grote', why: 'gro-te: open lettergreep, één o.' },
        { t: 'zak' },
        { t: 'chips.' },
        { t: 'Dank' },
        { t: 'je!' },
      ],
      done: {
        title: 'Lijstje klopt',
        text: 'eieren, paprika’s, broden, flesjes en grote. En tomaatjes was goed: tomaat → tomaatje.',
      },
    },
    {
      kind: 'rewrite',
      id: 'wij-verhuizen',
      prompt: 'Schrijf de zin met wij in plaats van ik.',
      source: 'Ik verhuis in mei, dus ik verkoop mijn grote kast en mijn oude bed.',
      accept: [
        'Wij verhuizen in mei, dus wij verkopen onze grote kast en ons oude bed.',
        'Wij verhuizen in mei, dus verkopen wij onze grote kast en ons oude bed.',
      ],
      why: 'Bij wij het hele werkwoord: verhuizen (weer met z) en verkopen (open lettergreep, één o). mijn wordt onze bij een de-woord (de kast) en ons bij een het-woord (het bed).',
    },
    {
      kind: 'type',
      id: 'belastingaangifte',
      prompt: 'Breek het woord af. Zet een koppelteken op elk afbreekpunt.',
      before: 'belastingaangifte =',
      after: '',
      hint: 'met koppeltekens',
      answer: 'be-las-ting-aan-gif-te',
      why: 'Eerst tussen de delen: belasting + aangifte. Dan be- (voorvoegsel), las-ting (st: één aan elke kant), aan-gif-te (ft: één aan elke kant).',
    },
    {
      kind: 'dictation',
      id: 'dictee-bakker',
      prompt: 'Luister en typ de zin.',
      sentence: 'De vriendelijke bakker op de hoek geeft mijn zoontje elke zaterdag een warm broodje en een koekje.',
      right: 'Goed: vriendelijke zonder dubbele k, zoontje met -tje, broodje met d, warm zonder -e en zaterdag met een kleine letter.',
      wrong:
        'Let op: vriendelijke (na -lijk geen dubbele letter), zoontje (oo + n: -tje), een warm broodje (het broodje, na een: geen -e; brood met d), koekje (na k: -je) en zaterdag klein.',
    },
    {
      kind: 'choice',
      id: 'leden',
      prompt: 'Kies het goede meervoud.',
      before: 'Alle',
      after: 'van de sportclub krijgen deze week een mail over de nieuwe contributie.',
      options: ['leden', 'lidden', 'liden', 'lids'],
      answer: 'leden',
      why: 'lid → leden: een leerwoord, net als schip → schepen. De korte i wordt een lange e.',
    },
    {
      kind: 'type',
      id: 'verhuist',
      prompt: 'Typ de goede vorm van verhuizen.',
      before: 'Wanneer',
      after: 'je collega naar Rotterdam? Al volgende week?',
      hint: '',
      answer: 'verhuist',
      why: 'Hier betekent je jouw: het onderwerp is je collega (hij). Stam verhuis (geen z aan het eind) + t: verhuist.',
    },
    {
      kind: 'sort',
      id: 'verkleinwoord',
      prompt: 'Welk verkleinwoord krijgt het woord?',
      buckets: ['-je', '-tje', '-pje', '-etje'],
      items: [
        { t: 'hoofd', b: 0 },
        { t: 'keuken', b: 1 },
        { t: 'bezem', b: 2 },
        { t: 'bel', b: 3 },
        { t: 'krant', b: 0 },
        { t: 'vrouw', b: 1 },
        { t: 'duim', b: 2 },
        { t: 'ding', b: 3 },
        { t: 'lach', b: 0 },
        { t: 'ei', b: 1 },
        { t: 'arm', b: 2 },
        { t: 'vriendin', b: 3 },
        { t: 'dorp', b: 0 },
        { t: 'schoen', b: 1 },
        { t: 'helm', b: 2 },
        { t: 'bon', b: 3 },
      ],
      why: 'hoofdje, krantje, lachje, dorpje: na d, t, ch en p. keukentje, vrouwtje, eitje, schoentje: na een doffe e + n, na een tweeklank en na oe + n. bezempje, duimpje, armpje, helmpje: m na een doffe e of tweeklank, en na rm en lm. belletje, dingetje, vriendinnetje, bonnetje: korte klank met klemtoon + l, ng of n.',
    },
    {
      kind: 'bet',
      id: 'geinteresseerd',
      prompt: 'Hoeveel lettergrepen heeft geïnteresseerd?',
      options: ['drie', 'vier', 'vijf', 'zes'],
      answer: 'vijf',
      why: 'ge-ïn-te-res-seerd: vijf klinkerklanken. Het trema begint een nieuwe lettergreep, en de dubbele s gaat uit elkaar.',
    },
    {
      kind: 'choice',
      id: 'dove',
      prompt: 'Kies de goede vorm.',
      before: 'Mijn opa is een beetje',
      after: ', dus praat maar wat harder. (doof)',
      options: ['doof', 'dove', 'doove', 'doofe'],
      answer: 'doof',
      why: 'Het bijvoeglijk naamwoord staat niet vóór een zelfstandig naamwoord. Dan komt er geen -e: mijn opa is doof. Maar: een dove man.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks 1: typ elk woord goed',
      intro: 'Alle regels door elkaar. Bij elk woord bepaal je zelf welke regel geldt. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Meervoud van *het slot*',
          before: 'Na de inbraak vervangt de huisbaas alle',
          after: 'in het gebouw.',
          a: 'sloten',
          why: 'slot is een leerwoord met een lange o in het meervoud: slo-ten, één o en één t.',
        },
        {
          q: 'Vul de vorm van *houden* in',
          before: 'Mijn buurman',
          after: 'zijn hond tegenwoordig nooit aan de lijn.',
          a: 'houdt',
          why: 'Stam houd (van houden). Bij hij komt er een t bij: houdt.',
        },
        {
          q: 'Vul de vorm van *werken* in',
          before: 'Hoeveel uur',
          after: 'jij op dit moment per week?',
          a: 'werk',
          why: 'jij staat achter het werkwoord: geen t. Werk jij?',
        },
        {
          q: 'Vul de goede vorm van *financieel* in',
          before: 'De gemeente stuurt gezinnen een brief over',
          after: 'hulp.',
          a: 'financiële',
          why: 'Vóór hulp komt een -e. -ieel + e wordt -iële, met een trema: financiële.',
        },
        {
          q: 'Vul de goede vorm van *braaf* in',
          before: 'Onze buren hebben een heel',
          after: 'hond.',
          a: 'brave',
          why: 'de hond: er komt een -e. Dan hoor je een v, en bra- is open: één a. brave.',
        },
        {
          q: 'Breek af op alle plekken waar het mag: *herinneringen*',
          a: 'her-in-ne-rin-gen',
          why: 'her- is een voorvoegsel: dat knip je eerst los. Dan in-ne (de nn gaat uit elkaar) en rin-gen (ng gaat uit elkaar).',
        },
        {
          q: 'Hoeveel lettergrepen heeft *beëindigen*? Typ het getal in letters.',
          say: 'beëindigen',
          a: 'vier',
          also: ['4'],
          why: 'be-ëin-di-gen: vier klinkerklanken. ei is één klank; het trema laat zien dat daar een nieuwe lettergreep begint.',
        },
        {
          q: 'Meervoud van *de lerares*',
          before: 'Op de school van mijn zoon werken zes',
          after: '.',
          a: 'leraressen',
          why: 'lerares heeft de klemtoon op -res: korte e + één s, dus ss. leraressen.',
        },
        {
          q: 'Meervoud van *de knie*',
          before: 'Na het voetballen deden allebei mijn',
          after: 'pijn.',
          a: 'knieën',
          why: 'ie met klemtoon + en: -ieën. Het trema staat op de e waar de nieuwe lettergreep begint.',
        },
        {
          q: 'Verkleinwoord van *het glas*',
          before: 'Wil je een',
          after: 'water?',
          a: 'glaasje',
          why: 'glas → glazen: lange a. Die lange a komt terug in het verkleinwoord: glaasje.',
        },
        {
          q: 'Verkleinwoord van *de paraplu*',
          before: 'Mijn dochter neemt haar roze',
          after: 'mee naar school.',
          a: 'parapluutje',
          why: 'Eindigt op een u: de u wordt dubbel, dan -tje. parapluutje.',
        },
        {
          q: 'Vul de vorm van *verven* in',
          before: 'Volgend weekend',
          after: 'ik de slaapkamer.',
          a: 'verf',
          why: 'verven min -en is verv. Aan het eind van de stam nooit een v: verf. Bij ik alleen de stam.',
        },
        {
          q: 'Schrijf het woord dat je hoort: pijn boven je ogen',
          say: 'hoofdpijn',
          a: 'hoofdpijn',
          why: 'hoofd + pijn: elk deel houdt zijn letters. hoofden, dus d.',
        },
        {
          q: 'Verkleinwoord van het woord dat je hoort: een open plek in de stad, waar vaak een markt is',
          say: 'het plein',
          a: 'pleintje',
          why: 'plein is een ei-woord. ei + n: -tje. pleintje.',
        },
        {
          q: 'Vul de goede vorm in van het woord voor *niet gekookt*',
          say: 'rauw',
          before: 'Bij sushi eet je vaak',
          after: 'vis.',
          a: 'rauwe',
          also: ['ongekookte'],
          why: 'rauw is een van de -auw-woorden (blauw, flauw, lauw, rauw …). Vóór vis komt een -e: rauwe.',
        },
        {
          q: 'Meervoud van het wilde dier dat de koning van de dieren heet',
          say: 'de leeuw',
          before: 'In de dierentuin liggen twee',
          after: 'in de zon.',
          a: 'leeuwen',
          why: 'ee + w: eeuw. Dat blijft zo in het meervoud: leeuwen.',
        },
        {
          q: 'Vul het bijvoeglijk naamwoord van *eer* met -lijk in',
          before: 'Hij gaf een',
          after: 'antwoord.',
          a: 'eerlijk',
          why: 'het antwoord is een het-woord: na een komt er geen -e. Dus eerlijk, niet eerlijke.',
        },
        {
          q: 'Vul de goede vorm van *gezellig* in',
          before: 'Bedankt voor de',
          after: 'avond!',
          a: 'gezellige',
          why: 'de avond: er komt een -e. Na -ig verdubbel je niet: gezellige.',
        },
        {
          q: 'Vul de vorm van *verhuizen* in',
          before: 'Wij zijn vorig jaar',
          after: '.',
          a: 'verhuisd',
          why: 'In het hele werkwoord hoor je een z. Die staat niet in ’t kofschip: -d. verhuisd.',
        },
        {
          q: 'Vul de vorm van *fietsen* in',
          before: 'Gisteren',
          after: 'ik in de regen naar mijn werk.',
          a: 'fietste',
          why: 'Stam fiets eindigt op een s, en die staat in ’t kofschip: -te. fietste.',
        },
        { q: 'Vul in: de auto van *Anna*', before: 'Ik leen vandaag', after: 'auto.', a: 'Anna’s', why: 'Anna eindigt op een a: ’s. Anna’s auto.' },
        { q: 'Maak één woord van *zee* en *egel*', a: 'zee-egel', why: 'ee + e zou je samen lezen: daarom een koppelteken. zee-egel.' },
        {
          q: 'Vul de vorm van *irriteren* in',
          before: 'De klant was erg',
          after: 'over de lange wachttijd.',
          a: 'geïrriteerd',
          why: 'ge + i: trema op de i. Stam irriteer eindigt op een r: -d. geïrriteerd.',
        },
        {
          q: 'Vul de vorm van *sturen* in',
          before: 'Morgen',
          after: 'ik u de nieuwe planning.',
          a: 'stuur',
          why: 'stu-ren is open. In de stam is de lettergreep gesloten: stuur, met twee u’s.',
        },
        {
          q: 'Vul de goede vorm van *grof* in',
          before: 'Dat was een',
          after: 'fout van mij.',
          a: 'grove',
          why: 'de fout: er komt een -e. Je hoort een v, en gro- is open: grove.',
        },
        {
          q: 'Breek af op alle plekken waar het mag: *beoordelen*',
          a: 'be-oor-de-len',
          why: 'be- is een voorvoegsel: be-oor. Dan oor-de-len: één medeklinker gaat mee. Geen trema: eo lees je niet als één klank.',
        },
      ],
      done: {
        title: 'Reeks 1 klaar',
        text: 'Meervoud, verkleinwoord, stam, -e, afbreken, en ook ei, auw, eeuw, d of t, ’t kofschip, trema en apostrof: allemaal door elkaar.',
      },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail aan. Typ elk woord helemaal.',
      intro: 'Kijk goed naar de zin om het gat heen. De grijze aanwijzing geeft de grondvorm of de betekenis.',
      title: 'Mail aan de verhuurder',
      text: 'Geachte heer Bakker,\n\nSinds vorige week lekt het dak boven de slaapkamer van onze {kinderen|meervoud van kind|kind krijgt -eren in het meervoud: kinderen.}. Bij elke bui vallen er dikke {druppels|meervoud van druppel|-el zonder klemtoon: -s. Dus druppels.} op de vloer. We hebben al {geprobeerd|proberen, voltooid deelwoord|Stam probeer eindigt op een r. Die staat niet in ’t kofschip: -d. Dus geprobeerd.} om het water op te vangen met oude {handdoeken|meervoud van handdoek|hand + doek: elk deel houdt zijn letters (handen, dus d). Meervoud met -en.} en twee {emmers|meervoud van emmer|-er zonder klemtoon: -s. Dus emmers.}. Toch {wordt|worden|Stam word (van worden). Het onderwerp is de muur (hij), dus er komt een t bij: wordt.} de muur nu elke dag {natter|nat, maar nog meer|Korte a + één t, en er komt -er achter: de t wordt dubbel. nat-ter.}. Er zitten nu donkere {plekken|meervoud van plek|Korte e + één k: verdubbelen. plek-ken.} op het behang, en ook het {raampje|verkleinwoord van raam|Lange a + m: -pje. raampje.} in de badkamer gaat niet meer goed dicht.\n\nIk maak me zorgen over de {gezondheid|als je niet ziek bent|gezond → gezonde: d. Met -heid blijft de d: gezondheid.} van mijn {zoontje|verkleinwoord van zoon|Lange o + n: -tje. zoontje.}, want hij hoest al een week. In de bijlage {stuur|sturen|Bij ik alleen de stam. stu-ren is open; in de stam is de lettergreep gesloten: stuur.} ik u vier {foto’s|meervoud van foto|foto eindigt op een o: ’s. Zonder apostrof lees je een korte o.}. Kunt u deze week een dakdekker sturen? Ik ben woensdag en donderdag de hele dag thuis. Heeft u betere {ideeën|meervoud van idee|idee + en: ideeën. Het trema laat zien waar de nieuwe lettergreep begint.}, dan hoor ik dat graag.\n\nAlvast bedankt voor uw {snelle|snel|de reactie: er komt een -e. Korte e + één l: verdubbelen. snelle.} reactie.\n\nMet {vriendelijke|vriendelijk|Na -lijk alleen een -e, nooit een dubbele k: vriendelijke.} groet,\nHasan',
      why: 'In deze mail: meervoud (kinderen, druppels, emmers, plekken, foto’s, ideeën), verdubbelen (natter, plekken, snelle), verkleinwoord (raampje, zoontje), de stam (stuur, wordt), d door langer maken (handdoeken, gezondheid) en ’t kofschip (geprobeerd).',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort negen zinnen uit een briefje aan de buren. Hoofdletters en leestekens tellen mee.',
      title: 'Briefje aan de buren',
      sentences: [
        'Volgende week verbouwen wij onze keuken en de kleine badkamer.',
        'De bouwvakkers beginnen ’s ochtends vroeg en stoppen aan het eind van de middag.',
        'Op maandag en dinsdag geeft het slopen van de oude tegels veel lawaai.',
        'De grote container voor het afval staat een paar weken op de stoep.',
        'Heeft u betere ideeën voor de plek van de container?',
        'Stuur ons dan gerust een appje of bel even bij ons aan.',
        'Onze kinderen logeren die week bij hun opa en oma in Den Haag.',
        'Na de verbouwing nodigen we u graag uit voor een drankje en een hapje.',
        'Onze excuses voor de overlast en alvast bedankt voor uw geduld.',
      ],
      right:
        'Alles goed. ’s ochtends met apostrof, lawaai met aai, slopen en grote met één letter, ideeën met trema, maandag en dinsdag klein, en appje en hapje met -je.',
      wrong:
        'Kijk deze woorden na: verbouwen (ou), bouwvakkers (kk), ’s ochtends (apostrof), maandag en dinsdag (klein), lawaai (aai), slopen en grote (open lettergreep: één letter), ideeën (trema), appje (app + je) en hapje (hap + je), nodigen (-ig, geen dubbele g), Den Haag (twee hoofdletters) en excuses (één s).',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'Karin de Vries', subject: 'Rooster en teamuitje' },
      greeting: 'Beste Karin,',
      signoff: 'Groet,\nHasan',
      tokens: [
        { t: 'Bedankt' },
        { t: 'voor' },
        { t: 'het' },
        { t: 'nieuwe' },
        { t: 'rooster.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'het' },
        { t: 'al' },
        { t: 'met' },
        { t: 'de' },
        { t: 'twee' },
        { t: 'nieuwe' },
        { t: 'collegas', fix: 'collega’s', also: ['collegae'], why: 'collega eindigt op een a: meervoud met ’s.' },
        { t: 'besproken.' },
        { t: 'Zij' },
        { t: 'werken' },
        { t: 'allebei' },
        { t: 'op' },
        { t: 'de' },
        { t: 'kerstdagen,', trap: 'Goed: een samenstelling met een feestdag schrijf je met een kleine letter: kerstdagen.' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'werkt', fix: 'werk', why: 'Bij ik alleen de stam: ik werk.' },
        { t: 'de' },
        { t: 'week' },
        { t: 'daarna.' },
        { t: 'Is' },
        { t: 'dat' },
        { t: 'goed?' },
        { t: 'Over' },
        { t: 'het' },
        { t: 'teamuitje:' },
        { t: 'ik' },
        { t: 'heb' },
        { t: 'een' },
        { t: 'paar' },
        { t: 'ideeen.', fix: 'ideeën.', why: 'idee + en: ideeën. Het trema laat zien waar de nieuwe lettergreep begint.' },
        { t: 'We' },
        { t: 'kunnen' },
        { t: 'gaan' },
        { t: 'bowlen,' },
        { t: 'of' },
        { t: 'een' },
        { t: 'rondvaart' },
        { t: 'maken' },
        { t: 'door' },
        { t: 'de' },
        { t: 'grachten' },
        { t: 'van' },
        { t: 'Utrecht.' },
        { t: 'Eigelijk', fix: 'Eigenlijk', why: 'eigen + -lijk: eigenlijk. De n van eigen blijft staan.' },
        { t: 'heb' },
        { t: 'ik' },
        { t: 'het' },
        { t: 'al' },
        { t: 'bijna' },
        { t: 'geregeld.' },
        { t: 'De' },
        { t: 'rederij' },
        { t: 'heeft' },
        { t: 'ons' },
        { t: 'een' },
        { t: 'aanbod' },
        { t: 'gestuurt', fix: 'gestuurd', why: 'Stam stuur eindigt op een r. Die staat niet in ’t kofschip: -d. gestuurd.' },
        { t: 'voor' },
        { t: 'groote', fix: 'grote', why: 'gro-te: open lettergreep, één o.' },
        { t: 'groepen.' },
        { t: 'Wil', trap: 'Goed: jij staat achter het werkwoord, dus geen t. Wil jij?' },
        { t: 'jij' },
        { t: 'het' },
        { t: 'even' },
        { t: 'aan' },
        { t: 'de' },
        { t: 'directie' },
        { t: 'vragen?' },
        { t: 'En' },
        { t: 'vind', trap: 'Goed: jij staat achter het werkwoord, dus geen t. Vind jij?' },
        { t: 'jij' },
        { t: 'het' },
        { t: 'goed' },
        { t: 'als' },
        { t: 'ik' },
        { t: 'de' },
        { t: 'kaartjes' },
        { t: 'alvast' },
        { t: 'bestel?' },
        { t: 'De' },
        { t: 'rekening' },
        { t: 'kan' },
        { t: 'naar' },
        { t: 'de' },
        { t: 'financiele', fix: 'financiële', why: 'de afdeling: er komt een -e. -ieel + e wordt -iële, met een trema.' },
        { t: 'afdeling.' },
        { t: 'Ruben' },
        { t: 'doet' },
        { t: 'ook' },
        { t: 'mee:' },
        { t: 'hij' },
        { t: 'word', fix: 'wordt', why: 'Stam word (van worden). Bij hij komt er een t bij: wordt.' },
        { t: 'in' },
        { t: 'maart', trap: 'Goed: een maand schrijf je met een kleine letter.' },
        { t: 'vijftig' },
        { t: 'en' },
        { t: 'wil' },
        { t: 'dat' },
        { t: 'graag' },
        { t: 'vieren.' },
      ],
      done: {
        title: 'Mail kan weg',
        text: 'collega’s, werk, ideeën, eigenlijk, gestuurd, grote, financiële en wordt. En kerstdagen, Wil jij, vind jij en maart waren goed.',
      },
    },
    {
      kind: 'drill',
      id: 'reeks-2',
      prompt: 'Reeks 2: typ elk woord goed',
      intro: 'Nog een reeks, met meer valkuilen. Lees de hele zin voordat je typt.',
      items: [
        {
          q: 'Meervoud van *de kennis*',
          before: 'Op het feest kwamen veel vrienden en',
          after: '.',
          a: 'kennissen',
          why: 'Woorden op -nis krijgen ss in het meervoud: kennissen, getuigenissen.',
        },
        {
          q: 'Meervoud van *het schip*',
          before: 'In de haven liggen grote',
          after: 'uit China.',
          a: 'schepen',
          why: 'schip → schepen: een leerwoord. De korte i wordt een lange e: sche-pen.',
        },
        {
          q: 'Meervoud van *het lied*',
          before: 'Op de bruiloft zongen de gasten oude',
          after: '.',
          a: 'liederen',
          why: 'lied krijgt -eren in het meervoud: liederen.',
        },
        {
          q: 'Meervoud van *de melodie*',
          before: 'De pianist speelde twee bekende',
          after: '.',
          a: 'melodieën',
          why: 'De klemtoon ligt op ie: -ieën, met een trema.',
        },
        {
          q: 'Meervoud van *de bacterie*',
          before: 'Op een vieze snijplank zitten veel',
          after: '.',
          a: 'bacteriën',
          why: 'Geen klemtoon op ie: -iën, met een trema.',
        },
        {
          q: 'Meervoud van *het café*',
          before: 'In onze straat zijn drie',
          after: 'en een bakkerij.',
          a: 'cafés',
          why: 'Na é alleen een s, zonder apostrof: cafés.',
        },
        {
          q: 'Meervoud van *de agenda*',
          before: 'Leg de',
          after: 'voor de vergadering op tafel.',
          a: 'agenda’s',
          why: 'agenda eindigt op een a: ’s. Met alleen een s zou je een korte a lezen.',
        },
        {
          q: 'Verkleinwoord van *de ketting*',
          before: 'Ze droeg een dun',
          after: 'om haar nek.',
          a: 'kettinkje',
          why: '-ing zonder klemtoon: -kje, en de g valt weg: kettinkje.',
        },
        {
          q: 'Verkleinwoord van *het blad*',
          before: 'In de herfst valt er elke dag een',
          after: 'van de boom.',
          a: 'blaadje',
          why: 'blad → bladen: lange a. Dus ook in het verkleinwoord: blaadje.',
        },
        {
          q: 'Verkleinwoord van *de schep*',
          before: 'Mijn zoontje speelt op het strand met een',
          after: 'en een emmertje.',
          a: 'schepje',
          why: 'Na een p: -je. Vóór -je verdubbel je niet: schepje.',
        },
        {
          q: 'Verkleinwoord van *de kam*',
          before: 'In haar tas zit altijd een',
          after: '.',
          a: 'kammetje',
          why: 'Korte a + m, met klemtoon: -etje, en de m wordt dubbel.',
        },
        {
          q: 'Verkleinwoord van *de taxi*',
          before: 'Om drie uur ’s nachts namen we een',
          after: 'naar huis.',
          a: 'taxietje',
          why: 'Eindigt op een i: de i wordt ie, dan -tje: taxietje. Een apostrof komt alleen na een y (baby’tje).',
        },
        {
          q: 'Vul de vorm van *vinden* in',
          before: 'Wat',
          after: 'jij ervan als we morgen samen lunchen?',
          a: 'vind',
          why: 'jij staat achter het werkwoord: geen t. Stam vind (van vinden).',
        },
        {
          q: 'Vul de vorm van *vinden* in',
          before: 'Wat',
          after: 'je moeder ervan als we zondag bij haar komen eten?',
          a: 'vindt',
          why: 'Hier betekent je jouw. Het onderwerp is je moeder (zij): stam vind + t.',
        },
        {
          q: 'Vul de vorm van *reizen* in',
          before: 'Mijn zus',
          after: 'sinds kort elke maand voor haar werk naar Brussel.',
          a: 'reist',
          why: 'Stam reis (geen z aan het eind), en bij zij + t: reist.',
        },
        {
          q: 'Vul de vorm van *zetten* in',
          before: 'De conciërge',
          after: 'morgen de stoelen voor de ouderavond klaar.',
          a: 'zet',
          why: 'Stam zet: aan het eind geen dubbele t. Bij hij komt er een t bij, maar de stam eindigt al op t: zet.',
        },
        {
          q: 'Vul de vorm van *antwoorden* in',
          before: 'De huisbaas',
          after: 'tegenwoordig nooit op mijn mails.',
          a: 'antwoordt',
          why: 'Stam antwoord, bij hij + t: antwoordt.',
        },
        {
          q: 'Vul de vorm van *beantwoorden* in',
          before: 'Heeft u mijn vraag al',
          after: '?',
          a: 'beantwoord',
          why: 'Na be- komt er geen ge-. De stam eindigt al op een d: beantwoord, zonder extra letter.',
        },
        {
          q: 'Vul de goede vorm van *officieel* in',
          before: 'Binnen twee weken krijgt u een',
          after: 'brief.',
          a: 'officiële',
          why: 'de brief: er komt een -e. -ieel wordt -iële: officiële.',
        },
        {
          q: 'Vul de goede vorm van *wijs* in',
          before: 'Dat was een',
          after: 'besluit van de directie.',
          a: 'wijs',
          why: 'het besluit is een het-woord: na een geen -e. Dus wijs.',
        },
        {
          q: 'Vul de goede vorm van *los* in',
          before: 'In de badkamer liggen twee',
          after: 'tegels.',
          a: 'losse',
          why: 'Korte o + s, en je hoort een s: losse.',
        },
        {
          q: 'Vul het bijvoeglijk naamwoord van *zilver* in',
          before: 'Ze kreeg een',
          after: 'armband van haar oma.',
          a: 'zilveren',
          why: 'Een stofnaam op -en krijgt geen -e: een zilveren armband.',
        },
        {
          q: 'Vul de goede vorm van *serieus* in',
          before: 'De huurders hebben een',
          after: 'klacht ingediend.',
          a: 'serieuze',
          why: 'de klacht: er komt een -e. -eus wordt -euze: serieuze.',
        },
        {
          q: 'Breek af op alle plekken waar het mag: *verantwoordelijk*',
          a: 'ver-ant-woor-de-lijk',
          why: 'ver- is een voorvoegsel: ver-ant. Dan woor-de-lijk: één medeklinker gaat mee.',
        },
        { q: 'Breek af op de plek van het trema: *ruïne*', a: 'ru-ine', why: 'Op de plek van het trema valt het trema weg: ru-ine.' },
        {
          q: 'Schrijf het woord dat je hoort: het gevoel dat je te veel alleen bent',
          say: 'de eenzaamheid',
          a: 'eenzaamheid',
          also: ['de eenzaamheid'],
          why: 'een + zaam + heid. -heid schrijf je altijd met ei.',
        },
        {
          q: 'Vul de vorm in van het werkwoord voor *eten fijnmaken met je tanden*',
          say: 'kauwen',
          before: 'Mijn zoon is al tien, maar hij',
          after: 'nog steeds met zijn mond open.',
          a: 'kauwt',
          why: 'kauwen is een -auw-woord. Stam kauw, bij hij + t: kauwt.',
        },
        {
          q: 'Vul de vorm van *liggen* in',
          before: 'Het pakket',
          after: 'nu al twee dagen bij de buren.',
          a: 'ligt',
          why: 'liggen heeft een g in de stam: lig + t = ligt.',
        },
        {
          q: 'Schrijf het woord dat je hoort: het gebouw waar je boeken leent (het hele woord)',
          say: 'de bibliotheek',
          a: 'bibliotheek',
          also: ['de bibliotheek'],
          why: 'th klinkt als t. -theek: gesloten lettergreep, dus ee.',
        },
      ],
      done: {
        title: 'Reeks 2 klaar',
        text: 'Meer valkuilen: je achter het werkwoord, -e of geen -e, -kje, ’s of s, en d of t aan het eind van de stam.',
      },
    },
    {
      kind: 'cloze',
      id: 'invultekst-2',
      prompt: 'Vul het bericht van de gemeente aan. Typ elk woord helemaal.',
      intro: 'Kijk goed naar de zin om het gat heen. De grijze aanwijzing geeft de grondvorm, de betekenis of een deel van het woord.',
      title: 'Bericht van de gemeente',
      text: 'Beste bewoners van de Lindelaan,\n\nVanaf volgende maandag vernieuwt de gemeente de {wegen|meervoud van weg|weg → wegen: een leerwoord met een lange e in het meervoud. Eén g.} en de {fietspaden|meervoud van fietspad|pad → paden: lange a in het meervoud, dus één a en één d.} in uw wijk. Het werk duurt ongeveer zes weken. De straat is {tijdelijk|voor een korte periode|tijd + -elijk: de d blijft, en -lijk schrijf je altijd met ij.} afgesloten voor {auto’s|meervoud van auto|auto eindigt op een o: ’s.}. U kunt parkeren op het {pleintje|verkleinwoord van plein|plein is een ei-woord. ei + n: -tje.} achter de bibliotheek.\n\nHet werk begint {’s ochtends~’s morgens|in de ochtend|Er zijn letters weggelaten (des ochtends, des morgens): apostrof.} om half acht. Eerst {legt|leggen|leggen heeft een g in de stam: leg + t = legt.} de aannemer nieuwe {rioolbuizen|meervoud van rioolbuis|In het meervoud hoor je een z: buis → buizen.}. Daarna {verbreedt|verbreden|Stam verbreed: gesloten lettergreep, dus ee. Het onderwerp is de gemeente (zij), dus er komt een t bij: verbreedt.} de gemeente de {smalle|smal|de stoep: er komt een -e. Korte a + één l: verdubbelen.} stoep, zodat mensen met een rolstoel of een kinderwagen er beter langs kunnen. Langs de stoep komen jonge {bomen|meervoud van boom|bo-men: open lettergreep, één o.}. Uw huis blijft altijd {bereikbaar|ber__kbaar|bereiken schrijf je met ei. Met -baar: bereikbaar.} voor de brandweer en de ambulance.\n\nAlle bewoners krijgen deze week ook een {briefje|verkleinwoord van brief|Na een f: -je. briefje.} met een plattegrond. Zo is iedereen op tijd {gewaarschuwd|waarschuwen, voltooid deelwoord|Stam waarschuw eindigt op een w. Die staat niet in ’t kofschip: -d.}. Heeft u vragen? Stuur dan een mail naar het {e-mailadres|e + mail + adres|Een losse letter + een woord: koppelteken na de e. e-mailadres.} hieronder, of bel met onze {coördinator|co_rdinator|co-or: die klinkers spreek je los uit. Zonder trema lees je oo. Dus coördinator.}, mevrouw Yilmaz. Wat {vindt|vinden|Stam vind (van vinden). Bij u komt er een t bij: vindt.} u ervan als we langs de stoep ook een paar bankjes zetten? Laat het ons weten.\n\nMet vriendelijke groet,\nAfdeling Wegen',
      why: 'In dit bericht: meervoud (wegen, fietspaden, auto’s, rioolbuizen, bomen), verkleinwoord (pleintje, briefje), de stam + t (legt, verbreedt, vindt), -e en verdubbelen (smalle), plus ei en ij (tijdelijk, bereikbaar), apostrof (’s ochtends), ’t kofschip (gewaarschuwd), koppelteken (e-mailadres) en trema (coördinator).',
    },
    {
      kind: 'proofread',
      id: 'nakijken-2',
      prompt: 'Kijk het bericht in de buurtapp na',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'Buurtapp Esdoornstraat' },
      signoff: 'Groetjes,\nFatima (nummer 12)',
      tokens: [
        { t: 'Hallo' },
        { t: 'allemaal!' },
        { t: 'Volgende' },
        { t: 'Zaterdag', fix: 'zaterdag', why: 'Dagen van de week schrijf je met een kleine letter, behalve aan het begin van een zin.' },
        { t: 'houden' },
        { t: 'we' },
        { t: 'weer' },
        { t: 'een' },
        { t: 'buurtfeest' },
        { t: 'op' },
        { t: 'het' },
        { t: 'pleintje' },
        { t: 'bij' },
        { t: 'de' },
        { t: 'speeltuin.' },
        { t: 'Er' },
        { t: 'komen' },
        { t: 'kramen', trap: 'Goed: kraam → kra-men. Open lettergreep, dus één a.' },
        { t: 'met' },
        { t: 'eten' },
        { t: 'en' },
        { t: 'drinken,' },
        { t: 'en' },
        { t: 'de' },
        { t: 'kinderen' },
        { t: 'mogen' },
        { t: 'hun' },
        { t: 'oude' },
        { t: 'speelgoed' },
        { t: 'verkoopen', fix: 'verkopen', why: 'ver-ko-pen: open lettergreep, één o.' },
        { t: 'in' },
        { t: 'een' },
        { t: 'eigen' },
        { t: 'kraampje.', trap: 'Goed: lange a + m geeft -pje. In kraampje is de lettergreep gesloten, dus aa.' },
        { t: 'Wie' },
        { t: 'wil,' },
        { t: 'kan' },
        { t: 'een' },
        { t: 'taart' },
        { t: 'of' },
        { t: 'lekkerre', fix: 'lekkere', why: 'Na -er verdubbel je niet: lekkere.' },
        { t: 'hapjes' },
        { t: 'meenemen.' },
        { t: 'We' },
        { t: 'zoeken' },
        { t: 'nog' },
        { t: 'hulp.' },
        { t: 'Wie' },
        { t: 'heeft' },
        { t: 'er' },
        { t: 'tafel’s', fix: 'tafels', why: 'tafel eindigt op een medeklinker: gewoon -s, zonder apostrof. tafels.' },
        { t: 'en' },
        { t: 'stoelen?' },
        { t: 'En' },
        { t: 'wie' },
        { t: 'wil' },
        { t: 'er' },
        { t: 'helpen' },
        { t: 'met' },
        { t: 'opbauwen?', fix: 'opbouwen?', why: 'bouwen schrijf je met ou. auw staat alleen in een klein rijtje woorden, zoals blauw, flauw en rauw.' },
        { t: 'We' },
        { t: 'beginen', fix: 'beginnen', why: 'be-gin-nen: korte i + één n, en er komt een klinker achter. Dus nn.' },
        { t: 'om' },
        { t: 'tien' },
        { t: 'uur.' },
        { t: 'Bij' },
        { t: 'regen' },
        { t: 'gaan' },
        { t: 'we' },
        { t: 'naar' },
        { t: 'de' },
        { t: 'gymzaal' },
        { t: 'van' },
        { t: 'de' },
        { t: 'basisschool.', trap: 'Goed: basis + school. Elk deel houdt zijn letters, dus ss.' },
        { t: 'De' },
        { t: 'directeur' },
        { t: 'heeft' },
        { t: 'dat' },
        { t: 'al' },
        { t: 'goedgekeurt.', fix: 'goedgekeurd.', why: 'Stam keur eindigt op een r. Die staat niet in ’t kofschip: -d. goedgekeurd.' },
        { t: 'De' },
        { t: 'gemeente' },
        { t: 'heeft' },
        { t: 'de' },
        { t: 'stoep' },
        { t: 'vorige' },
        { t: 'maand' },
        { t: 'verbreed,', trap: 'Goed: verbreden, stam verbreed. Die eindigt al op een d, en na ver- komt er geen ge-: verbreed.' },
        { t: 'dus' },
        { t: 'er' },
        { t: 'is' },
        { t: 'ook' },
        { t: 'ruimte' },
        { t: 'voor' },
        { t: 'een' },
        { t: 'springkussen.' },
        { t: 'Wil' },
        { t: 'iedereen' },
        { t: 'zijn' },
        { t: 'autos', fix: 'auto’s', why: 'auto eindigt op een o: meervoud met ’s.' },
        { t: 'die' },
        { t: 'dag' },
        { t: 'ergens' },
        { t: 'anders' },
        { t: 'parkeren?' },
      ],
      done: {
        title: 'Bericht kan de app in',
        text: 'zaterdag, verkopen, lekkere, tafels, opbouwen, beginnen, goedgekeurd en auto’s. En kramen, kraampje, basisschool en verbreed waren goed.',
      },
    },
  ],
};
