import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": kiezen tussen au en ou, ook in -auw en -ouw, met rijtjes en een stappenplan. */
export const LES_K32: LessonInput = {
  id: 'k32',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'au of ou?',
  skill: 'Spelling',
  icon: 'au/ou',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Zelfde klank, twee spellingen',
      panels: [
        {
          text: '*au* en *ou* klinken precies hetzelfde. Zeg *blauw* en *vrouw*: dezelfde klank. Net als bij *ei* en *ij* moet je het woord dus kennen. Maar hier heb je meer hulp: *ou* komt veel vaker voor dan *au*. De *au*-woorden vormen twee korte rijtjes. Ken je die rijtjes, dan schrijf je de rest met *ou*.',
          rule: '*ou* is de gewone spelling. *au* alleen in twee korte rijtjes die je uit je hoofd leert.',
          quiz: {
            q: 'Welke spelling komt het vaakst voor?',
            options: ['ou', 'au', 'allebei even vaak'],
            answer: 'ou',
            why: 'ou is veel gewoner: oud, koud, hout, vrouw, jou, kous, ouders. au staat maar in een klein aantal woorden.',
          },
        },
        {
          text: 'De handigste regel: komt er direct een *d* of *t* na de klank, dan schrijf je bijna altijd *ou*. Denk aan *oud*, *koud*, *goud*, *hout*, *zout*, *fout*, *stout*. Dat blijft zo als het woord langer wordt: *oude*, *ouder*, *gouden*, *houten*, *zouten*. Alleen een paar leenwoorden, zoals *astronaut*, doen het anders. Draai aan het wiel en kijk welke woorden met *z* … *t* bestaan.',
          rule: 'Direct een *d* of *t* na de klank? Dan *ou*: *oud*, *koud*, *hout*, *zout*, *fout*.',
          wheel: {
            start: 'z',
            end: 't',
            options: [
              { v: 'ou', mean: 'zout: wat je op je eten strooit' },
              { v: 'au' },
              { v: 'oe', mean: 'zoet: zoals suiker' },
              { v: 'ie', mean: 'ziet: hij ziet de bus' },
              { v: 'a', mean: 'zat: ik zat op een stoel' },
            ],
            need: 3,
            note: 'zout bestaat, zaut niet: voor de t staat ou.',
          },
        },
        {
          text: 'Hoor je na de klank nog een *w*, zoals in *vrouw* en *blauw*? Ook dan is *ouw* het gewoonst: *vrouw*, *trouw*, *bouw*, *touw*, *mouw*, *jouw*, *rouw*. Maar er is een rijtje met *auw*. Leer het met een ezelsbruggetje: *De flauwe pauw kauwt gauw op een rauwe, lauwe, blauwe klauw.* Ook *nauw*, *grauw* en *dauw* horen erbij.',
          rule: '*-ouw* is gewoon (*vrouw*, *bouw*). *-auw* alleen in: *blauw*, *flauw*, *lauw*, *rauw*, *gauw*, *nauw*, *grauw*, *pauw*, *klauw*, *dauw*, *kauwen*.',
          lab: {
            label: 'Tik een groep',
            chips: [
              { k: '-ouw', out: 'vrouw, trouw, bouw, touw, mouw, jouw, rouw', note: 'De gewone spelling. Ook in langere woorden: vrouwen, trouwen, gebouw, vertrouwen.' },
              { k: '-auw (kleuren en smaak)', out: 'blauw, grauw, flauw, lauw, rauw', note: 'blauw en grauw zijn kleuren. Flauw, lauw en rauw zeg je vaak over eten: de soep is lauw.' },
              { k: '-auw (dieren)', out: 'pauw, klauw', note: 'Een pauw is een vogel met een mooie staart. Een klauw is de poot van een kat of een beer.' },
              { k: '-auw (overig)', out: 'gauw, nauw, dauw, kauwen', note: 'gauw = snel. nauw = smal. dauw ligt ’s ochtends op het gras. kauwen doe je met je tanden.' },
            ],
          },
        },
        {
          text: 'Het tweede rijtje: *au* zonder *w* erachter. Ook dat is kort: *auto*, *augustus*, *saus*, *pauze*, *paus*, *augurk*, *applaus*. Ezelsbruggetje: *In augustus houdt de paus in zijn auto pauze met een augurk in de saus.* Bijna alle andere woorden zonder *w*: *ou*. Bijvoorbeeld *kous*, *nou*, *jou*, *kou*, *schouder*, *ouders*, *kabouter*.',
          rule: '*au* zonder *w*: *auto*, *augustus*, *saus*, *pauze*, *paus*, *augurk*, *applaus*. De rest: bijna altijd *ou*.',
          quiz: {
            q: 'Welk woord schrijf je met au?',
            options: ['saus', 'kous', 'schouder', 'ouders'],
            answer: 'saus',
            why: 'saus staat in het au-rijtje. kous, schouder en ouders schrijf je met ou.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'ou-au-basis',
      prompt: 'ou of au? Kies wat er op de lijn hoort.',
      buckets: ['ou', 'au'],
      items: [
        { t: 'k_d', b: 0 },
        { t: 'bl_w', b: 1 },
        { t: 'vr_w', b: 0 },
        { t: 's_s', b: 1 },
        { t: 'h_t', b: 0 },
        { t: 'p_ze', b: 1 },
        { t: 'z_t', b: 0 },
        { t: 'fl_w', b: 1 },
        { t: 't_w', b: 0 },
        { t: 'g_d', b: 0 },
        { t: '_to', b: 1 },
        { t: 'm_w', b: 0 },
      ],
      why: 'ou: koud, vrouw, hout, zout, touw, goud, mouw. au: blauw, saus, pauze, flauw, auto. Voor d en t staat bijna altijd ou.',
    },
    {
      kind: 'choice',
      id: 'koud',
      prompt: 'Kies de goede spelling.',
      before: 'Doe je jas aan, het is buiten erg',
      after: '.',
      options: ['koud', 'kaud', 'kout'],
      answer: 'koud',
      why: 'Een d direct na de klank: ou. En met een d, want het wordt kou-de, kou-der.',
    },
    {
      kind: 'type',
      id: 'hout',
      prompt: 'Typ het ontbrekende woord.',
      before: 'Deze tafel is gemaakt van',
      after: '.',
      hint: 'h…t',
      answer: 'hout',
      why: 'Direct een t na de klank: ou. hout, en een houten tafel.',
    },
    {
      kind: 'fix',
      id: 'vrouw',
      prompt: 'Tik het fout gespelde woord aan en verbeter het.',
      sentence: 'Mijn vrauw werkt drie dagen per week in het ziekenhuis.',
      wrong: 1,
      answer: 'vrouw',
      why: 'vrouw staat niet in het auw-rijtje, dus ouw. Net als trouw, bouw en touw.',
    },
    {
      kind: 'choice',
      id: 'pauze',
      prompt: 'Kies de goede spelling.',
      before: 'Om twaalf uur hebben we een half uur',
      after: '.',
      options: ['pauze', 'pouze', 'pauwze'],
      answer: 'pauze',
      why: 'pauze staat in het au-rijtje: auto, augustus, saus, pauze, paus, augurk, applaus.',
    },
    {
      kind: 'bet',
      id: 'benauwd',
      prompt: 'Een lastige: ‘Het is hier warm en ik heb het ….’ Welke spelling is goed?',
      intro: 'Pas op: er staat een d aan het eind.',
      options: ['benauwd', 'benouwd', 'benaud'],
      answer: 'benauwd',
      why: 'De d staat niet direct na de klank, maar na de w. Dan helpt de d-regel niet. Denk aan nauw (krap, smal): be-nauw-d, met auw.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen en een stappenplan',
      panels: [
        {
          text: 'Let op deze paren. *rauw* (niet gekookt) en *rouw* (verdriet als iemand is overleden) bestaan allebei. *jou* en *jouw* ook: *jou* zeg je als iemand iets met jou doet (*ik bel jou*), *jouw* betekent *van jou* (*jouw jas*). En *kou* is het zelfstandig naamwoord (*de kou*), *koud* het bijvoeglijk naamwoord (*het is koud*).',
          rule: '*rauw* = niet gekookt, *rouw* = verdriet. *jou* = ik bel jou, *jouw* = van jou.',
          lab: {
            label: 'Tik een paar',
            chips: [
              { k: 'rauw – rouw', out: 'niet gekookt – verdriet', note: 'Eet geen rauwe kip. De familie is in de rouw.' },
              { k: 'jou – jouw', out: 'ik bel jou – jouw jas', note: 'Kun je jouw jas pakken? Dan breng ik jou naar huis.' },
              { k: 'kou – koud', out: 'de kou – het is koud', note: 'Ik heb het koud. Ik kan niet tegen de kou.' },
            ],
          },
        },
        {
          text: 'Wordt het woord langer, dan blijft de spelling gewoon staan: *vrouw* → *vrouwen*, *blauw* → *blauwe*, *saus* → *sauzen*, *kous* → *kousen*, *oud* → *ouder*. Je hoeft dus niet opnieuw te kiezen. Vul de tabel in.',
          rule: 'Langer woord, zelfde spelling: *vrouw* → *vrouwen*, *pauw* → *pauwen*.',
          paradigm: {
            q: 'Vul het meervoud in',
            cols: ['meervoud'],
            rows: [
              { label: 'de vrouw', cells: [{ fill: 'vrouwen' }] },
              { label: 'de pauw', cells: [{ fill: 'pauwen', hint: 'pauw staat in het auw-rijtje, ook in het meervoud.' }] },
              { label: 'de mouw', cells: [{ fill: 'mouwen' }] },
              { label: 'de klauw', cells: [{ fill: 'klauwen' }] },
              { label: 'de kous', cells: [{ fill: 'kousen' }] },
              { label: 'het gebouw', cells: [{ fill: 'gebouwen' }] },
            ],
            extra: ['vrauwen', 'pouwen', 'mauwen', 'klouwen', 'kausen', 'gebauwen'],
            note: 'De spelling van de klank verandert nooit als het woord langer wordt: vrouwen, pauwen, mouwen, klauwen, kousen, gebouwen.',
          },
        },
        {
          text: 'Veelgemaakte fouten zijn *vrauw*, *blouw*, *kaud* en *auto* met *ou*. Kijk naar de goede vorm en onthoud het woordbeeld.',
          show: [
            { wrong: 'Mijn vrauw heeft een blouwe auto.', right: 'Mijn vrouw heeft een blauwe auto.' },
            { wrong: 'Het water is kaud.', right: 'Het water is koud.' },
            { wrong: 'Ik eet patat met saus en een augourk.', right: 'Ik eet patat met saus en een augurk.' },
          ],
          quiz: {
            q: 'Welke zin is helemaal goed?',
            options: ['De oude vrouw draagt een blauwe sjaal.', 'De aude vrouw draagt een blauwe sjaal.', 'De oude vrauw draagt een blouwe sjaal.'],
            answer: 'De oude vrouw draagt een blauwe sjaal.',
            why: 'oude: d na de klank, dus ou. vrouw: gewone ouw. blauwe: in het auw-rijtje.',
          },
        },
        {
          text: 'Twijfel je? Gebruik dit stappenplan. 1. Komt er direct een *d* of *t* na de klank? Dan *ou* (*oud*, *zout*). 2. Hoor je een *w* erachter? Staat het woord in het *auw*-rijtje (*blauw*, *flauw*, *lauw*, *rauw*, *gauw*, *nauw*, *grauw*, *pauw*, *klauw*, *dauw*, *kauwen*)? Dan *auw*, anders *ouw*. 3. Geen *w*? Staat het in het *au*-rijtje (*auto*, *augustus*, *saus*, *pauze*, *paus*, *augurk*, *applaus*)? Dan *au*, anders *ou*. 4. Nog twijfel: zoek het op. Tik in de zin de woorden aan waarbij stap 1 je meteen het antwoord geeft.',
          rule: 'Eerst *d* of *t*? Dan *ou*. Daarna de twee *au*-rijtjes. De rest: *ou*.',
          mark: {
            q: 'Tik de woorden waarbij stap 1 (d of t na de klank) het antwoord geeft',
            sentence: 'Mijn oude buurvrouw zet zout op tafel, want de soep is flauw.',
            targets: [1, 4],
            note: 'oude en zout: een d of t direct na de klank, dus ou. Bij buurvrouw en flauw helpt pas stap 2.',
          },
        },
      ],
    },
    {
      kind: 'choice',
      id: 'rauw',
      prompt: 'Kies het goede woord.',
      before: 'Kip moet je goed bakken. Eet hem nooit',
      after: '.',
      options: ['rauw', 'rouw'],
      answer: 'rauw',
      why: 'rauw = niet gekookt, met auw. rouw (met ouw) is het verdriet als iemand is overleden.',
    },
    {
      kind: 'proofread',
      id: 'appje',
      prompt: 'Een appje over de boodschappen. Tik de vijf fouten met au of ou aan en verbeter ze.',
      tokens: [
        { t: 'Hoi!' },
        { t: 'Wil' },
        { t: 'jij' },
        { t: 'na' },
        { t: 'je' },
        { t: 'werk' },
        { t: 'nog' },
        { t: 'boodschappen' },
        { t: 'doen?' },
        { t: 'We' },
        { t: 'hebben' },
        { t: 'zaut,', fix: 'zout,', why: 'Een t direct na de klank: ou.' },
        { t: 'tomatensous', fix: 'tomatensaus', why: 'saus staat in het au-rijtje, ook in tomatensaus.' },
        { t: 'en' },
        { t: 'augurken' },
        { t: 'nodig.' },
        { t: 'Neem' },
        { t: 'ook' },
        { t: 'hout' },
        { t: 'mee' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'kachel,' },
        { t: 'want' },
        { t: 'het' },
        { t: 'wordt' },
        { t: 'vanavond' },
        { t: 'kaud.', fix: 'koud.', why: 'Een d direct na de klank: ou.' },
        { t: 'Mijn' },
        { t: 'auders', fix: 'ouders', why: 'ouders: d direct na de klank, dus ou. Net als oud.' },
        { t: 'komen' },
        { t: 'om' },
        { t: 'zeven' },
        { t: 'uur.' },
        { t: 'Pak' },
        { t: 'je' },
        { t: 'de' },
        { t: 'blouwe', fix: 'blauwe', why: 'blauw staat in het auw-rijtje.' },
        { t: 'tas?' },
        { t: 'Hij' },
        { t: 'hangt' },
        { t: 'in' },
        { t: 'de' },
        { t: 'gang.' },
      ],
      done: {
        title: 'Vijf verbeterd',
        text: 'zout, tomatensaus, koud, ouders en blauwe. augurken en hout stonden er goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ de zin.',
      intro: 'In deze zin hoor je de klank vier keer.',
      sentence: 'In augustus gaat mijn oude buurvrouw met de auto naar Frankrijk.',
      right: 'Goed: augustus en auto uit het au-rijtje, oude met ou voor de d, buurvrouw met gewone ouw. En augustus met een kleine letter.',
      wrong: 'Kijk nog eens: augustus en auto schrijf je met au, oude met ou (d erachter), buurvrouw met ouw. Maanden krijgen een kleine letter, landen een hoofdletter: Frankrijk.',
    },
    {
      kind: 'swipe',
      id: 'goed-of-fout',
      prompt: 'Is de zin goed gespeld?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in staat.',
      cards: [
        { t: 'Ik heb een fout gemaakt in de mail.', ok: true, why: 'fout: t na de klank, dus ou.' },
        { t: 'De lucht is vandaag grouw.', ok: false, fix: 'grouw → grauw', why: 'grauw staat in het auw-rijtje.' },
        { t: 'Kom gauw terug!', ok: true, why: 'gauw (snel) staat in het auw-rijtje.' },
        { t: 'Mijn zoon heeft een gauden medaille.', ok: false, fix: 'gauden → gouden', why: 'goud, gouden: d na de klank, dus ou.' },
        { t: 'Ze gaan in juni trouwen.', ok: true, why: 'trouwen: gewone ouw.' },
        { t: 'De kat krabt met zijn klouw.', ok: false, fix: 'klouw → klauw', why: 'klauw staat in het auw-rijtje.' },
        { t: 'Na het concert klonk er een luid applous.', ok: false, fix: 'applous → applaus', why: 'applaus staat in het au-rijtje.' },
        { t: 'Ik heb nieuwe kousen gekocht.', ok: true, why: 'kous, kousen: ou, want kous staat niet in het au-rijtje.' },
      ],
    },
    {
      kind: 'type',
      id: 'jouw',
      prompt: 'Typ het ontbrekende woord.',
      before: 'Is dit',
      after: 'fiets of die van je broer?',
      hint: 'j…w',
      answer: 'jouw',
      why: 'Van jou = jouw, met ouw. jou gebruik je in ik zie jou.',
    },
    {
      kind: 'sort',
      id: 'ou-au-lastig',
      prompt: 'Moeilijker: ou of au?',
      buckets: ['ou', 'au'],
      items: [
        { t: 'sch_der', b: 0 },
        { t: 'appl_s', b: 1 },
        { t: 'k_s (aan je voet)', b: 0 },
        { t: 'kab_ter', b: 0 },
        { t: '_gurk', b: 1 },
        { t: 'n_w (smal, krap)', b: 1 },
        { t: 'k_wgom', b: 1 },
        { t: 'vertr_wen', b: 0 },
        { t: 'geb_w', b: 0 },
        { t: 'p_s (in Rome)', b: 1 },
        { t: 'gr_w (bijna grijs)', b: 1 },
        { t: 'beh_den', b: 0 },
      ],
      why: 'ou: schouder, kous, kabouter, vertrouwen, gebouw, behouden. au: applaus, augurk, nauw, kauwgom (van kauwen), paus, grauw.',
    },
    {
      kind: 'rewrite',
      id: 'verbeter',
      prompt: 'Schrijf de zin goed over. Er staan drie fouten in.',
      source: 'De vrauw met de blouwe jas heeft het kaud.',
      accept: ['De vrouw met de blauwe jas heeft het koud.'],
      why: 'vrouw: gewone ouw. blauwe: auw-rijtje. koud: d na de klank, dus ou.',
    },
    {
      kind: 'write',
      id: 'schrijf',
      prompt: 'Schrijf een boodschappenlijstje met een kort berichtje erbij voor een huisgenoot.',
      intro: 'Gebruik woorden met au en met ou. Controleer ze met het stappenplan.',
      minWords: 25,
      must: [
        { label: 'Een woord met ou voor een d of t (bijvoorbeeld zout, koud, oude)', hint: 'zout, koud, hout, oude', test: { pattern: 'ou[dt]', flags: 'i' } },
        { label: 'Een woord met ouw (bijvoorbeeld vrouw, trouw, gebouw)', hint: 'vrouw, jouw, mouw', test: { pattern: 'ouw', flags: 'i' } },
        { label: 'Een woord uit een au-rijtje (bijvoorbeeld saus, blauw, auto)', hint: 'saus, augurk, blauw, gauw', test: { pattern: 'au', flags: 'i' } },
      ],
      starters: ['Hoi! Kun jij', 'We hebben nodig:', 'Tot straks!'],
      why: 'Loop elk woord met de klank langs het stappenplan: d of t, dan de twee au-rijtjes, de rest ou.',
    },
  ],
};
