import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": ng en nk, aai/ooi/oei en eeuw/ieuw/uw goed schrijven, ook als het woord langer wordt. */
export const LES_K33: LessonInput = {
  id: 'k33',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'ng/nk, aai/ooi/oei, eeuw/ieuw/uw',
  skill: 'Spelling',
  icon: 'ng',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Vaste lettergroepen',
      panels: [
        {
          text: 'Zeg *ring*, *lang*, *jongen*, *zingen* en *koning*. Aan het eind of in het midden hoor je één klank achter in je mond. Die klank schrijf je met twee letters: *ng*. Je hoort geen losse *n* en geen losse *g*, maar je schrijft ze wel allebei. Andere woorden: *bang*, *jong*, *tong*, *slang*, *ding*, *woning*.',
          rule: 'Eén klank, twee letters: *ng* (*ring*, *lang*, *zingen*, *koning*).',
          build: {
            before: 'Hij geeft haar een gouden',
            stem: 'ri',
            endings: ['ng', 'nk', 'ngk', 'n'],
            answer: 'ng',
            note: 'ring: je hoort alleen de ng-klank, zonder k erachter.',
          },
        },
        {
          text: 'Hoor je na die klank nog een *k*, zoals in *bank*, *dank*, *denken* en *drinken*? Dan schrijf je *nk*. Dus niet *ngk*: de *k* zorgt er al voor dat de *n* als *ng* klinkt. Vergelijk *bang* (je bent bang) en *bank* (je zit op de bank), *tang* (gereedschap) en *tank*. Draai aan het wiel.',
          rule: 'ng-klank + k = *nk* (*bank*, *denken*). Nooit *ngk*.',
          wheel: {
            start: 'ba',
            end: '',
            options: [
              { v: 'ng', mean: 'bang: je bent bang voor de hond' },
              { v: 'nk', mean: 'bank: je zit op de bank, of je geld staat op de bank' },
              { v: 'nd', mean: 'band: de band van je fiets' },
              { v: 'l', mean: 'bal: een bal om mee te voetballen' },
              { v: 'ngk' },
            ],
            need: 3,
            note: 'bang, bank, band, bal. bangk bestaat niet: ng-klank + k schrijf je als nk.',
          },
          deep: {
            q: 'En bij woorden als ingang en aangeven?',
            a: 'Daar hoor je een gewone *n* en daarna een *g*, want het zijn twee woorden aan elkaar: *in* + *gang*, *aan* + *geven*. Je schrijft gewoon wat je hoort: *ingang*, *aangeven*, *aangenaam*.',
          },
        },
        {
          text: 'Nu *aai*, *ooi* en *oei*. Je hoort een lange klank met een soort *j* erachter: *haai*, *mooi*, *roeien*. Je schrijft die *j*-klank altijd als *i*: *aa* + *i*, *oo* + *i*, *oe* + *i*. Dus nooit *mooj* of *haaj*. Woorden: *haai*, *fraai*, *saai*, *draaien*, *zwaaien*, *kraai*; *mooi*, *nooit*, *ooit*, *kooi*, *hooi*, *gooien*; *roeien*, *groeien*, *bloeien*, *boei*, *moeilijk*.',
          rule: '*aa*, *oo* of *oe* met een *j*-klank erachter: schrijf *aai*, *ooi*, *oei* (*haai*, *mooi*, *roeien*).',
          blend: {
            letters: ['aa', 'oo', 'oe', 'i'],
            pairs: [
              { s: 'aai', ex: 'haai, saai, draaien, zwaaien' },
              { s: 'ooi', ex: 'mooi, nooit, kooi, gooien' },
              { s: 'oei', ex: 'roeien, groeien, moeilijk' },
            ],
            note: 'Telkens een lange klank (aa, oo, oe) met een i erachter: aai, ooi, oei.',
          },
        },
        {
          text: 'Tot slot de klanken met een *w* erachter. Hoor je *ee* + *w*, dan schrijf je *eeuw*: *leeuw*, *sneeuw*, *eeuw*, *meeuw*, *schreeuwen*. Hoor je *ie* + *w*, dan *ieuw*: *nieuw*, *nieuws*, *kieuw*. Hoor je *uu* + *w*, dan alleen *uw*, met één *u*: *duwen*, *ruw*, *uw*, *sluw*, *schuw*. Nooit *eew*, *iew* of *uuw*. En als het woord langer wordt, blijft het gelijk: *meeuwen*, *nieuwe*, *ruwe*.',
          rule: '*ee* + w = *eeuw*, *ie* + w = *ieuw*, *uu* + w = *uw*. Langer woord: blijft gelijk (*meeuwen*, *nieuwe*).',
          paradigm: {
            q: 'Maak het woord langer',
            cols: ['langer woord'],
            rows: [
              { label: 'de leeuw (meervoud)', cells: [{ fill: 'leeuwen' }] },
              { label: 'de meeuw (meervoud)', cells: [{ fill: 'meeuwen' }] },
              { label: 'nieuw (een … fiets)', cells: [{ fill: 'nieuwe', hint: 'ieuw blijft staan, er komt alleen een e achter.' }] },
              { label: 'ruw (een … zee)', cells: [{ fill: 'ruwe', hint: 'uw met één u, ook in het langere woord.' }] },
              { label: 'ik duw (het hele werkwoord)', cells: [{ fill: 'duwen' }] },
            ],
            extra: ['leewen', 'meeuwwen', 'niewe', 'ruuwe', 'duuwen'],
            note: 'leeuwen, meeuwen, nieuwe, ruwe, duwen: de lettergroep blijft precies gelijk.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'ng-nk',
      prompt: 'ng of nk? Lees de uitleg tussen haakjes.',
      buckets: ['ng', 'nk'],
      items: [
        { t: 'zi_en (een lied)', b: 0 },
        { t: 'de_en (nadenken)', b: 1 },
        { t: 'pla_ (een stuk hout)', b: 1 },
        { t: 'ri_ (om je vinger)', b: 0 },
        { t: 'jo_ (niet oud)', b: 0 },
        { t: 'dri_en (water)', b: 1 },
        { t: 'wo_ing (je huis)', b: 0 },
        { t: 'pi_ (je kleinste vinger)', b: 1 },
        { t: 'to_ (in je mond)', b: 0 },
        { t: 'da_ je wel', b: 1 },
        { t: 'sla_ (een dier zonder poten)', b: 0 },
        { t: 'sti_en (vies ruiken)', b: 1 },
      ],
      why: 'ng: zingen, ring, jong, woning, tong, slang. nk: denken, plank, drinken, pink, dank, stinken. Hoor je een k na de ng-klank, dan nk.',
    },
    {
      kind: 'choice',
      id: 'bang',
      prompt: 'Kies het goede woord.',
      before: 'Mijn dochter is',
      after: 'voor grote honden.',
      options: ['bang', 'bank', 'bangk'],
      answer: 'bang',
      why: 'bang: alleen de ng-klank, geen k. Op een bank zit je.',
    },
    {
      kind: 'type',
      id: 'drinken',
      prompt: 'Typ het ontbrekende woord.',
      before: 'Wil je iets',
      after: '? Koffie of thee?',
      hint: 'dri…en',
      answer: 'drinken',
      why: 'Je hoort de ng-klank en dan een k: nk. Dus drinken, niet dringken.',
    },
    {
      kind: 'sort',
      id: 'aai-ooi-oei',
      prompt: 'aai, ooi of oei? Lees de uitleg tussen haakjes.',
      buckets: ['aai', 'ooi', 'oei'],
      items: [
        { t: 'dr_en (aan de knop)', b: 0 },
        { t: 'm_ (prachtig)', b: 1 },
        { t: 'r_en (in een bootje)', b: 2 },
        { t: 'h_ (een vis met scherpe tanden)', b: 0 },
        { t: 'h_ (gedroogd gras)', b: 1 },
        { t: 'gr_en (groter worden)', b: 2 },
        { t: 'k_ (voor een vogel)', b: 1 },
        { t: 'zw_en (met je hand)', b: 0 },
        { t: 'm_lijk (niet makkelijk)', b: 2 },
        { t: 'g_en (met een bal)', b: 1 },
        { t: 'bl_en (zoals een bloem)', b: 2 },
        { t: 'kr_ (een zwarte vogel)', b: 0 },
      ],
      why: 'aai: draaien, haai, zwaaien, kraai. ooi: mooi, hooi, kooi, gooien. oei: roeien, groeien, moeilijk, bloeien.',
    },
    {
      kind: 'fix',
      id: 'mooi',
      prompt: 'Tik het fout gespelde woord aan en verbeter het.',
      sentence: 'Het is vandaag heel mooj weer aan zee.',
      wrong: 4,
      answer: 'mooi',
      why: 'De j-klank na oo schrijf je als i: mooi.',
    },
    {
      kind: 'bet',
      id: 'huwelijk',
      prompt: 'Een lastige: welke spelling is goed?',
      intro: 'Ze zijn al vijftig jaar getrouwd: wat een lang …!',
      options: ['huwelijk', 'huuwelijk', 'huwlijk'],
      answer: 'huwelijk',
      why: 'Je hoort uu + w, en dat schrijf je als uw met één u: hu-we-lijk. En -lijk met ij.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen en een stappenplan',
      panels: [
        {
          text: 'Een woord op *-ing* eindigt altijd op *ng*, ook als het in snelle spraak bijna als *ink* klinkt: *koning*, *woning*, *oefening*, *vergadering*, *opleiding*, *verwarming*. Je schrijft nooit *konink* of *woonink*. In het meervoud hoor je het meteen: *koningen*, *woningen*.',
          rule: 'Woorden op *-ing* (*woning*, *oefening*): altijd *ng*, nooit *nk*.',
          quiz: {
            q: 'Welke spelling is goed?',
            options: ['vergadering', 'vergaderink', 'vergaderingk'],
            answer: 'vergadering',
            why: 'Het meervoud is vergaderingen: daar hoor je ng zonder k. Dus vergadering.',
          },
          deep: {
            q: 'En het verkleinwoord van koning?',
            a: 'Dat is *koninkje*, met *nk*. Dat is een aparte regel bij verkleinwoorden; die leer je in de les over verkleinwoorden. Het hele woord blijft *koning*.',
          },
        },
        {
          text: 'Bij werkwoorden blijft de lettergroep in elke vorm staan. *draaien* → *ik draai*, *hij draait*. *gooien* → *ik gooi*, *hij gooit*. *groeien* → *het groeit*. *duwen* → *ik duw*, *hij duwt*. *schreeuwen* → *ik schreeuw*. *denken* → *ik denk*, *hij denkt*. Vul de tabel in.',
          rule: 'In elke vorm van het werkwoord blijft *aai*, *ooi*, *oei*, *eeuw*, *uw* of *nk* staan.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik …', 'hij …'],
            rows: [
              { label: 'draaien', cells: [{ fill: 'draai' }, { fill: 'draait' }] },
              { label: 'gooien', cells: [{ fill: 'gooi' }, { fill: 'gooit' }] },
              { label: 'duwen', cells: [{ fill: 'duw', hint: 'uw met één u.' }, { fill: 'duwt' }] },
              { label: 'schreeuwen', cells: [{ fill: 'schreeuw' }, { fill: 'schreeuwt' }] },
              { label: 'denken', cells: [{ fill: 'denk' }, { fill: 'denkt' }] },
            ],
            extra: ['draaj', 'gooiet', 'duuw', 'schreewt', 'dengk'],
            note: 'ik draai, ik gooi, ik duw, ik schreeuw, ik denk: de lettergroep verandert niet, er komt alleen een t bij hij.',
          },
        },
        {
          text: 'Dit zijn de fouten die het vaakst voorkomen. Kijk goed naar de goede vorm.',
          show: [
            { wrong: 'Dat is moeielijk.', right: 'Dat is moeilijk.' },
            { wrong: 'Ik heb een niewe telefoon.', right: 'Ik heb een nieuwe telefoon.' },
            { wrong: 'Het gaat vannacht sneewen.', right: 'Het gaat vannacht sneeuwen.' },
            { wrong: 'De zee is ruuw.', right: 'De zee is ruw.' },
            { wrong: 'Ik dengk aan je.', right: 'Ik denk aan je.' },
          ],
          quiz: {
            q: 'Welke zin is helemaal goed?',
            options: ['Ik heb nog nooit een leeuw gezien.', 'Ik heb nog nooid een leew gezien.', 'Ik heb nog nooit een lieuw gezien.'],
            answer: 'Ik heb nog nooit een leeuw gezien.',
            why: 'nooit met ooi en een t. leeuw: ee + w schrijf je als eeuw.',
          },
        },
        {
          text: 'Twijfel je? Gebruik dit stappenplan. 1. Hoor je de *ng*-klank? Komt er een *k* achter, dan *nk*; anders *ng*. 2. Hoor je *aa*, *oo* of *oe* met een *j*-klank? Schrijf *aai*, *ooi*, *oei*. 3. Hoor je *ee*, *ie* of *uu* met een *w*? Schrijf *eeuw*, *ieuw*, *uw*. 4. Twijfel je nog? Maak het woord langer (*vergadering* → *vergaderingen*) of zoek het op. Tik in de zin alle woorden waarin je de ng-klank hoort, met of zonder k.',
          rule: 'ng-klank + k = *nk*. aa/oo/oe + j-klank = *aai*/*ooi*/*oei*. ee/ie/uu + w = *eeuw*/*ieuw*/*uw*.',
          mark: {
            q: 'Tik de woorden waarin je de ng-klank hoort',
            sentence: 'De jongen dronk een glas melk op de bank en zong een lied.',
            targets: [1, 2, 8, 10],
            note: 'jongen en zong met ng; dronk en bank met nk, want daar komt een k achter. In melk hoor je geen ng-klank.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje',
      prompt: 'Een appje aan een collega. Tik de zes fouten aan en verbeter ze.',
      intro: 'Let op ng en nk, aai, ooi, oei en eeuw, ieuw, uw.',
      tokens: [
        { t: 'Hoi' },
        { t: 'Lisa!' },
        { t: 'Heb' },
        { t: 'je' },
        { t: 'het' },
        { t: 'niews', fix: 'nieuws', why: 'ie + w schrijf je als ieuw: nieuws.' },
        { t: 'gezien?' },
        { t: 'Morgen' },
        { t: 'gaat' },
        { t: 'het' },
        { t: 'sneewen,', fix: 'sneeuwen,', why: 'ee + w schrijf je als eeuw: sneeuwen.' },
        { t: 'dus' },
        { t: 'fietsen' },
        { t: 'wordt' },
        { t: 'moijlijk.', fix: 'moeilijk.', why: 'oe met een j-klank: oei. moeilijk.' },
        { t: 'Ik' },
        { t: 'dengk', fix: 'denk', why: 'ng-klank + k schrijf je als nk, nooit ngk.' },
        { t: 'dat' },
        { t: 'ik' },
        { t: 'de' },
        { t: 'bus' },
        { t: 'neem.' },
        { t: 'Zet' },
        { t: 'jij' },
        { t: 'de' },
        { t: 'verwarmink', fix: 'verwarming', why: 'Woorden op -ing eindigen altijd op ng.' },
        { t: 'vast' },
        { t: 'aan?' },
        { t: 'Het' },
        { t: 'wordt' },
        { t: 'vast' },
        { t: 'een' },
        { t: 'saaije', fix: 'saaie', why: 'saai + e = saaie. De i staat er al, er komt geen j bij.' },
        { t: 'dag,' },
        { t: 'maar' },
        { t: 'buiten' },
        { t: 'is' },
        { t: 'het' },
        { t: 'mooi:' },
        { t: 'alles' },
        { t: 'wit!' },
      ],
      done: {
        title: 'Zes verbeterd',
        text: 'nieuws, sneeuwen, moeilijk, denk, verwarming en saaie. mooi stond er goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ de zin.',
      intro: 'Let op ng, nk, ooi en ieuw.',
      sentence: 'Op de bank in de tuin zingt een jongen een mooi nieuw liedje.',
      right: 'Goed: bank met nk, zingt en jongen met ng, mooi met ooi en nieuw met ieuw.',
      wrong: 'Kijk nog eens: bank met nk (er komt een k achter), zingt en jongen met ng, mooi met ooi en nieuw met ieuw. Begin met een hoofdletter en eindig met een punt.',
    },
    {
      kind: 'swipe',
      id: 'goed-of-fout',
      prompt: 'Is de zin goed gespeld?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in staat.',
      cards: [
        { t: 'De meeuwen vliegen boven de haven.', ok: true, why: 'ee + w = eeuw, ook in het meervoud: meeuwen.' },
        { t: 'Ik heb nog nooit zo veel sneew gezien.', ok: false, fix: 'sneew → sneeuw', why: 'ee + w schrijf je als eeuw.' },
        { t: 'Kun je de kar even duwen?', ok: true, why: 'uu + w = uw, met één u.' },
        { t: 'Ze heeft een nieuwe woning gekocht.', ok: true, why: 'nieuwe met ieuw, woning op -ing.' },
        { t: 'Bedankt voor het mooie cadeau, ik ben je heel dangkbaar.', ok: false, fix: 'dangkbaar → dankbaar', why: 'ng-klank + k = nk.' },
        { t: 'De bloemen bloejen in het voorjaar.', ok: false, fix: 'bloejen → bloeien', why: 'oe met een j-klank schrijf je als oei.' },
        { t: 'In de dierentuin zagen we een leeuw en een slang.', ok: true, why: 'leeuw met eeuw, slang met ng.' },
        { t: 'Hij zwaait naar zijn vriend aan de overkant.', ok: true, why: 'zwaaien → hij zwaait: aai blijft staan.' },
      ],
    },
    {
      kind: 'type',
      id: 'eeuw',
      prompt: 'Typ het ontbrekende woord.',
      before: 'Honderd jaar is een',
      after: '.',
      hint: 'e…',
      answer: 'eeuw',
      why: 'ee + w schrijf je als eeuw: vier letters, net als in leeuw en sneeuw.',
    },
    {
      kind: 'choice',
      id: 'koning',
      prompt: 'Kies de goede spelling.',
      before: 'Op 27 april vieren we de verjaardag van de',
      after: '.',
      options: ['koning', 'konink', 'koningk'],
      answer: 'koning',
      why: 'Een woord op -ing: altijd ng. In het meervoud hoor je het: koningen.',
    },
    {
      kind: 'sort',
      id: 'w-woorden',
      prompt: 'eeuw, ieuw of uw?',
      buckets: ['eeuw', 'ieuw', 'uw'],
      items: [
        { t: 'l_ (een groot katachtig dier)', b: 0 },
        { t: 'n_s (op tv of in de krant)', b: 1 },
        { t: 'd_en (tegen iets aan)', b: 2 },
        { t: 'schr_en (heel hard roepen)', b: 0 },
        { t: 'r_ (niet glad)', b: 2 },
        { t: 'k_ (een vis ademt erdoor)', b: 1 },
        { t: 'g_en (moe zijn, je mond wijd open)', b: 0 },
        { t: 'n_sgierig', b: 1 },
        { t: '_ (van u: … auto)', b: 2 },
        { t: 'sn_bal', b: 0 },
      ],
      why: 'eeuw: leeuw, schreeuwen, geeuwen, sneeuwbal. ieuw: nieuws, kieuw, nieuwsgierig. uw: duwen, ruw, uw.',
    },
    {
      kind: 'rewrite',
      id: 'verbeter',
      prompt: 'Schrijf de zin goed over. Er staan drie fouten in.',
      source: 'De jongen dengkt dat de leew heel mooj is.',
      accept: ['De jongen denkt dat de leeuw heel mooi is.'],
      why: 'denkt: ng-klank + k = nk. leeuw: ee + w = eeuw. mooi: oo + j-klank = ooi.',
    },
    {
      kind: 'write',
      id: 'schrijf',
      prompt: 'Schrijf een appje aan een vriend over het weer en wat je vandaag gaat doen.',
      intro: 'Gebruik woorden uit deze les. Controleer ze daarna met het stappenplan.',
      minWords: 25,
      must: [
        { label: 'Een woord met ng (bijvoorbeeld lang, koning, woning)', hint: 'lang, jongen, vergadering', test: { pattern: 'ng', flags: 'i' } },
        { label: 'Een woord met nk (bijvoorbeeld denk, drinken, bank)', hint: 'denk, drinken, dank', test: { pattern: 'nk', flags: 'i' } },
        { label: 'Een woord met aai, ooi of oei', hint: 'mooi, saai, moeilijk', test: { pattern: 'aai|ooi|oei', flags: 'i' } },
        { label: 'Een woord met eeuw, ieuw of uw', hint: 'sneeuw, nieuw, ruw', test: { pattern: 'eeuw|ieuw|uw', flags: 'i' } },
      ],
      starters: ['Hoi! Het weer is', 'Vandaag ga ik', 'Ik denk dat'],
      why: 'Loop de woorden langs het stappenplan: ng of nk, aai/ooi/oei, eeuw/ieuw/uw.',
    },
  ],
};
