import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": ng en nk, aai/ooi/oei en eeuw/ieuw/uw goed schrijven, ook als het woord langer wordt. */
export const LES_K33: LessonInput = {
  id: 'k33',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'ng/nk, aai/ooi/oei, eeuw/ieuw/uw',
  skill: 'Spelling',
  icon: 'ng',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Vaste lettergroepen',
      panels: [
        {
          text: 'Zeg *ring*, *lang*, *jongen*, *zingen* en *koning*. Aan het eind of in het midden hoor je één klank achter in je mond. Die klank schrijf je met twee letters: *ng*. Je hoort geen losse *n* en geen losse *g*, maar je schrijft ze wel allebei. Andere woorden: *bang*, *jong*, *tong*, *slang*, *ding*, *woning*.',
          rule: 'Eén klank, twee letters: *ng* (*ring*, *lang*, *zingen*, *koning*).',
          build: {
            before: 'Hij geeft haar een gouden',
            stem: 'ri',
            endings: ['ng', 'nk', 'ngk', 'n'],
            answer: 'ng',
            note: 'ring: je hoort alleen de ng-klank, zonder k erachter.',
          },
        },
        {
          text: 'Hoor je na die klank nog een *k*, zoals in *bank*, *dank*, *denken* en *drinken*? Dan schrijf je *nk*. Dus niet *ngk*: de *k* zorgt er al voor dat de *n* als *ng* klinkt. Vergelijk *bang* (je bent bang) en *bank* (je zit op de bank), *tang* (gereedschap) en *tank*. Draai aan het wiel.',
          rule: 'ng-klank + k = *nk* (*bank*, *denken*). Nooit *ngk*.',
          wheel: {
            start: 'ba',
            end: '',
            options: [
              { v: 'ng', mean: 'bang: je bent bang voor de hond' },
              { v: 'nk', mean: 'bank: je zit op de bank, of je geld staat op de bank' },
              { v: 'nd', mean: 'band: de band van je fiets' },
              { v: 'l', mean: 'bal: een bal om mee te voetballen' },
              { v: 'ngk' },
            ],
            need: 3,
            note: 'bang, bank, band, bal. bangk bestaat niet: ng-klank + k schrijf je als nk.',
          },
          deep: {
            q: 'En bij woorden als ingang en aangeven?',
            a: 'Daar hoor je een gewone *n* en daarna een *g*, want het zijn twee woorden aan elkaar: *in* + *gang*, *aan* + *geven*. Je schrijft gewoon wat je hoort: *ingang*, *aangeven*, *aangenaam*.',
          },
        },
        {
          text: 'Nu *aai*, *ooi* en *oei*. Je hoort een lange klank met een soort *j* erachter: *haai*, *mooi*, *roeien*. Je schrijft die *j*-klank altijd als *i*: *aa* + *i*, *oo* + *i*, *oe* + *i*. Dus nooit *mooj* of *haaj*. Woorden: *haai*, *fraai*, *saai*, *draaien*, *zwaaien*, *kraai*; *mooi*, *nooit*, *ooit*, *kooi*, *hooi*, *gooien*; *roeien*, *groeien*, *bloeien*, *boei*, *moeilijk*.',
          rule: '*aa*, *oo* of *oe* met een *j*-klank erachter: schrijf *aai*, *ooi*, *oei* (*haai*, *mooi*, *roeien*).',
          blend: {
            letters: ['aa', 'oo', 'oe', 'i'],
            pairs: [
              { s: 'aai', ex: 'haai, saai, draaien, zwaaien' },
              { s: 'ooi', ex: 'mooi, nooit, kooi, gooien' },
              { s: 'oei', ex: 'roeien, groeien, moeilijk' },
            ],
            note: 'Telkens een lange klank (aa, oo, oe) met een i erachter: aai, ooi, oei.',
          },
        },
        {
          text: 'Tot slot de klanken met een *w* erachter. Hoor je *ee* + *w*, dan schrijf je *eeuw*: *leeuw*, *sneeuw*, *eeuw*, *meeuw*, *schreeuwen*. Hoor je *ie* + *w*, dan *ieuw*: *nieuw*, *nieuws*, *kieuw*. Hoor je *uu* + *w*, dan alleen *uw*, met één *u*: *duwen*, *ruw*, *uw*, *sluw*, *schuw*. Nooit *eew*, *iew* of *uuw*. En als het woord langer wordt, blijft het gelijk: *meeuwen*, *nieuwe*, *ruwe*.',
          rule: '*ee* + w = *eeuw*, *ie* + w = *ieuw*, *uu* + w = *uw*. Langer woord: blijft gelijk (*meeuwen*, *nieuwe*).',
          paradigm: {
            q: 'Maak het woord langer',
            cols: ['langer woord'],
            rows: [
              { label: 'de leeuw (meervoud)', cells: [{ fill: 'leeuwen' }] },
              { label: 'de meeuw (meervoud)', cells: [{ fill: 'meeuwen' }] },
              { label: 'nieuw (een … fiets)', cells: [{ fill: 'nieuwe', hint: 'ieuw blijft staan, er komt alleen een e achter.' }] },
              { label: 'ruw (een … zee)', cells: [{ fill: 'ruwe', hint: 'uw met één u, ook in het langere woord.' }] },
              { label: 'ik duw (het hele werkwoord)', cells: [{ fill: 'duwen' }] },
            ],
            extra: ['leewen', 'meeuwwen', 'niewe', 'ruuwe', 'duuwen'],
            note: 'leeuwen, meeuwen, nieuwe, ruwe, duwen: de lettergroep blijft precies gelijk.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'ng-nk',
      prompt: 'ng of nk? Lees de uitleg tussen haakjes.',
      buckets: ['ng', 'nk'],
      items: [
        { t: 'de wa_ (naast je neus)', b: 0 },
        { t: 'de kli_ van de deur', b: 1 },
        { t: 'de sta_ van het afval (een vieze geur)', b: 1 },
        { t: 'het he_sel van de tas', b: 0 },
        { t: 'de i_t van een pen', b: 1 },
        { t: 'Hij loopt ma_ (hij heeft pijn aan zijn been).', b: 1 },
        { t: 'de ga_ naar de vergaderzaal', b: 0 },
        { t: 'Hij dro_ een glas water.', b: 1 },
        { t: 'De fans dro_en naar voren.', b: 0 },
        { t: 'Ik heb ho_er.', b: 0 },
        { t: 'een sla_e vrouw (dun)', b: 1 },
        { t: 'de e_el met vleugels', b: 0 },
        { t: 'de ri_weg om de stad', b: 0 },
      ],
      why: 'ng: wang, hengsel, gang, drongen (van dringen), honger, engel, ringweg. nk: klink, stank, inkt, mank, dronk (van drinken), slanke. Hoor je een k na de ng-klank, dan nk.',
    },
    {
      kind: 'choice',
      id: 'belangstelling',
      prompt: 'Kies de goede spelling.',
      before: 'Bedankt voor uw',
      after: 'voor de functie van magazijnmedewerker.',
      options: ['belangstelling', 'belankstelling', 'belangstellink', 'belangkstelling'],
      answer: 'belangstelling',
      why: 'be + lang + stelling: twee keer ng, zonder k. Je hoort na lang geen k, dus ook geen ngk of nk. Een woord op -ing eindigt op ng.',
    },
    {
      kind: 'type',
      id: 'zonk',
      prompt: 'Typ de verleden tijd van zinken.',
      before: 'Het lekke schip',
      after: 'binnen tien minuten naar de bodem.',
      hint: '',
      answer: 'zonk',
      why: 'zinken → zonk. Je hoort de ng-klank en dan een k: nk. Vergelijk zingen → zong, zonder k.',
    },
    {
      kind: 'sort',
      id: 'aai-ooi-oei',
      prompt: 'aai, ooi of oei? Lees de uitleg tussen haakjes.',
      buckets: ['aai', 'ooi', 'oei'],
      items: [
        { t: 'de papeg_ (een vogel die kan praten)', b: 0 },
        { t: 'veel law_ van de buren (herrie)', b: 0 },
        { t: 'Het vlees is t_ (moeilijk te kauwen).', b: 0 },
        { t: 'zaden z_en in de moestuin', b: 0 },
        { t: 'de b_ (een bocht in de kust)', b: 0 },
        { t: 'de pr_ van een leeuw', b: 1 },
        { t: 'h_koorts in het voorjaar', b: 1 },
        { t: 'De hond heeft vl_en.', b: 1 },
        { t: 'Na de vorst komt de d_.', b: 1 },
        { t: 'De rozen staan in volle bl_.', b: 2 },
        { t: 'de k_en in de wei', b: 2 },
        { t: 'Het is de m_te waard.', b: 2 },
        { t: 'Hij zit te kn_en met de verf.', b: 2 },
      ],
      why: 'aai: papegaai, lawaai, taai, zaaien, baai. ooi: prooi, hooikoorts, vlooien, dooi. oei: bloei, koeien, moeite, knoeien.',
    },
    {
      kind: 'fix',
      id: 'nieuwe',
      prompt: 'Eén woord in de zin is fout gespeld. Tik het aan en verbeter het.',
      sentence: 'Tijdens de lange vergadering gaapte de directeur twee keer, maar niemand durfde iets te zeggen over de niewe planning.',
      wrong: 17,
      answer: 'nieuwe',
      why: 'ie + w schrijf je als ieuw: nieuw, nieuwe. lange, vergadering en planning met ng waren goed.',
    },
    {
      kind: 'bet',
      id: 'huwelijk',
      prompt: 'Een lastige: welke spelling is goed?',
      intro: 'Ze zijn al vijftig jaar getrouwd: wat een lang …!',
      options: ['huwelijk', 'huuwelijk', 'huwelik', 'huwlijk'],
      answer: 'huwelijk',
      why: 'Je hoort uu + w, en dat schrijf je als uw met één u: hu-we-lijk. En -lijk met ij.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen en een stappenplan',
      panels: [
        {
          text: 'Een woord op *-ing* eindigt altijd op *ng*, ook als het in snelle spraak bijna als *ink* klinkt: *koning*, *woning*, *oefening*, *vergadering*, *opleiding*, *verwarming*. Je schrijft nooit *konink* of *woonink*. In het meervoud hoor je het meteen: *koningen*, *woningen*.',
          rule: 'Woorden op *-ing* (*woning*, *oefening*): altijd *ng*, nooit *nk*.',
          quiz: {
            q: 'Welke spelling is goed?',
            options: ['vergadering', 'vergaderink', 'vergaderingk'],
            answer: 'vergadering',
            why: 'Het meervoud is vergaderingen: daar hoor je ng zonder k. Dus vergadering.',
          },
          deep: {
            q: 'En het verkleinwoord van koning?',
            a: 'Dat is *koninkje*, met *nk*. Dat is een aparte regel bij verkleinwoorden; die leer je in de les over verkleinwoorden. Het hele woord blijft *koning*.',
          },
        },
        {
          text: 'Bij werkwoorden blijft de lettergroep in elke vorm staan. *draaien* → *ik draai*, *hij draait*. *gooien* → *ik gooi*, *hij gooit*. *groeien* → *het groeit*. *duwen* → *ik duw*, *hij duwt*. *schreeuwen* → *ik schreeuw*. *denken* → *ik denk*, *hij denkt*. Vul de tabel in.',
          rule: 'In elke vorm van het werkwoord blijft *aai*, *ooi*, *oei*, *eeuw*, *uw* of *nk* staan.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik …', 'hij …'],
            rows: [
              { label: 'draaien', cells: [{ fill: 'draai' }, { fill: 'draait' }] },
              { label: 'gooien', cells: [{ fill: 'gooi' }, { fill: 'gooit' }] },
              { label: 'duwen', cells: [{ fill: 'duw', hint: 'uw met één u.' }, { fill: 'duwt' }] },
              { label: 'schreeuwen', cells: [{ fill: 'schreeuw' }, { fill: 'schreeuwt' }] },
              { label: 'denken', cells: [{ fill: 'denk' }, { fill: 'denkt' }] },
            ],
            extra: ['draaj', 'gooiet', 'duuw', 'schreewt', 'dengk'],
            note: 'ik draai, ik gooi, ik duw, ik schreeuw, ik denk: de lettergroep verandert niet, er komt alleen een t bij hij.',
          },
        },
        {
          text: 'Dit zijn de fouten die het vaakst voorkomen. Kijk goed naar de goede vorm.',
          show: [
            { wrong: 'Dat is moeielijk.', right: 'Dat is moeilijk.' },
            { wrong: 'Ik heb een niewe telefoon.', right: 'Ik heb een nieuwe telefoon.' },
            { wrong: 'Het gaat vannacht sneewen.', right: 'Het gaat vannacht sneeuwen.' },
            { wrong: 'De zee is ruuw.', right: 'De zee is ruw.' },
            { wrong: 'Ik dengk aan je.', right: 'Ik denk aan je.' },
          ],
          quiz: {
            q: 'Welke zin is helemaal goed?',
            options: ['Ik heb nog nooit een leeuw gezien.', 'Ik heb nog nooid een leew gezien.', 'Ik heb nog nooit een lieuw gezien.'],
            answer: 'Ik heb nog nooit een leeuw gezien.',
            why: 'nooit met ooi en een t. leeuw: ee + w schrijf je als eeuw.',
          },
        },
        {
          text: 'Twijfel je? Gebruik dit stappenplan. 1. Hoor je de *ng*-klank? Komt er een *k* achter, dan *nk*; anders *ng*. 2. Hoor je *aa*, *oo* of *oe* met een *j*-klank? Schrijf *aai*, *ooi*, *oei*. 3. Hoor je *ee*, *ie* of *uu* met een *w*? Schrijf *eeuw*, *ieuw*, *uw*. 4. Twijfel je nog? Maak het woord langer (*vergadering* → *vergaderingen*) of zoek het op. Tik in de zin alle woorden waarin je de ng-klank hoort, met of zonder k.',
          rule: 'ng-klank + k = *nk*. aa/oo/oe + j-klank = *aai*/*ooi*/*oei*. ee/ie/uu + w = *eeuw*/*ieuw*/*uw*.',
          mark: {
            q: 'Tik de woorden waarin je de ng-klank hoort',
            sentence: 'De jongen dronk een glas melk op de bank en zong een lied.',
            targets: [1, 2, 8, 10],
            note: 'jongen en zong met ng; dronk en bank met nk, want daar komt een k achter. In melk hoor je geen ng-klank.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje',
      prompt: 'Een appje aan een collega. Tik de fouten aan en verbeter ze.',
      intro: 'Let op ng en nk, aai, ooi, oei en eeuw, ieuw, uw.',
      tokens: [
        { t: 'Hoi' },
        { t: 'Lisa!' },
        { t: 'Heb' },
        { t: 'je' },
        { t: 'het' },
        { t: 'niews', fix: 'nieuws', why: 'ie + w schrijf je als ieuw: nieuws.' },
        { t: 'gezien?' },
        { t: 'Vandaag' },
        { t: 'blijft' },
        { t: 'het' },
        { t: 'sneewen,', fix: 'sneeuwen,', why: 'ee + w schrijf je als eeuw: sneeuwen.' },
        { t: 'dus' },
        { t: 'fietsen' },
        { t: 'wordt' },
        { t: 'moijlijk.', fix: 'moeilijk.', why: 'oe met een j-klank: oei. moeilijk.' },
        { t: 'Ik' },
        { t: 'dengk', fix: 'denk', why: 'ng-klank + k schrijf je als nk, nooit ngk.' },
        { t: 'dat' },
        { t: 'ik' },
        { t: 'de' },
        { t: 'bus' },
        { t: 'neem.' },
        { t: 'Zet' },
        { t: 'jij' },
        { t: 'de' },
        { t: 'verwarmink', fix: 'verwarming', why: 'Woorden op -ing eindigen altijd op ng.' },
        { t: 'vast' },
        { t: 'aan?' },
        { t: 'Het' },
        { t: 'wordt' },
        { t: 'vast' },
        { t: 'een' },
        { t: 'saaije', fix: 'saaie', why: 'saai + e = saaie. De i staat er al, er komt geen j bij.' },
        { t: 'dag,' },
        { t: 'maar' },
        { t: 'buiten' },
        { t: 'is' },
        { t: 'het' },
        { t: 'mooi:' },
        { t: 'alles' },
        { t: 'wit!' },
      ],
      done: {
        title: 'Zes verbeterd',
        text: 'nieuws, sneeuwen, moeilijk, denk, verwarming en saaie. mooi stond er goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ de zin.',
      intro: 'Eén lange zin. Hoofdletters en leestekens tellen mee.',
      sentence: 'De nieuwe buurman zwaait naar mijn jongste zoon en duwt hem op de slee door de sneeuw.',
      right: 'Goed: nieuwe met ieuw, jongste met ng, zwaait met aai, duwt met uw, en sneeuw met eeuw.',
      wrong:
        'Kijk nog eens: nieuwe met ieuw, jongste met ng (geen k erachter), zwaait met aai, duwt met uw (één u), slee met ee aan het eind, en sneeuw met eeuw. Begin met een hoofdletter en eindig met een punt.',
    },
    {
      kind: 'swipe',
      id: 'goed-of-fout',
      prompt: 'Is de zin goed gespeld?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in staat.',
      cards: [
        {
          t: 'De leeuwen in de dierentuin lagen de hele middag te geeuwen.',
          ok: true,
          why: 'leeuwen en geeuwen: ee + w = eeuw, ook als het woord langer wordt.',
        },
        {
          t: 'Hij pakte een tank uit de gereedschapskist om de spijker eruit te trekken.',
          ok: false,
          fix: 'tank → tang',
          why: 'Het gereedschap is een tang: alleen de ng-klank, geen k. In een tank zit benzine of water.',
        },
        { t: 'Kunt u uw fiets bij de ingang neerzetten?', ok: true, why: 'uw met één u. ingang is in + gang: gewoon wat je hoort.' },
        {
          t: 'De tomaten in de kas groejen goed door het warme weer.',
          ok: false,
          fix: 'groejen → groeien',
          why: 'oe met een j-klank schrijf je als oei: groeien.',
        },
        { t: 'Na de lange wandeling waren de kinderen moe en hongerig.', ok: true, why: 'lange en hongerig: alleen de ng-klank, geen k erachter.' },
        { t: 'Pas op, het hout van die oude tafel is nog ruuw.', ok: false, fix: 'ruuw → ruw', why: 'uu + w schrijf je als uw, met één u: ruw, ruwe.' },
        { t: 'De sirene loeide de hele nacht door de straat.', ok: true, why: 'loeien → loeide: oei blijft staan.' },
        {
          t: 'Tijdens de vergaderink viel de stroom uit.',
          ok: false,
          fix: 'vergaderink → vergadering',
          why: 'Woorden op -ing eindigen altijd op ng: vergaderingen, dus vergadering.',
        },
        { t: 'De ober kreeg een flinke fooi van de gasten.', ok: true, why: 'fooi: oo + j-klank = ooi.' },
        { t: 'In de vorige eew was dit gebouw een fabriek.', ok: false, fix: 'eew → eeuw', why: 'ee + w schrijf je als eeuw.' },
        { t: 'Ik ben benieuwd naar de uitslag van de verkiezingen.', ok: true, why: 'benieuwd met ieuw, net als nieuw. verkiezingen met ng.' },
        {
          t: 'Ze is nieuwsgierig naar de ideën van haar collega’s.',
          ok: false,
          fix: 'ideën → ideeën',
          why: 'i-dee-en: de laatste lettergreep begint met een e die je los uitspreekt. Die krijgt een trema: ideeën.',
        },
        { t: 'Het vliegtuig draaide twee rondjes boven Schiphol.', ok: true, why: 'draaien → draaide: aai blijft staan.' },
        {
          t: 'De meeuwen schreewden de hele ochtend boven de haven.',
          ok: false,
          fix: 'schreewden → schreeuwden',
          why: 'schreeuwen heeft eeuw, in elke vorm: schreeuwden.',
        },
      ],
    },
    {
      kind: 'type',
      id: 'eeuwen',
      prompt: 'Typ het woord voor honderd jaar, in het meervoud.',
      before: 'Deze boerderij staat hier al drie',
      after: '.',
      hint: '',
      answer: 'eeuwen',
      why: 'ee + w schrijf je als eeuw. In het meervoud blijft eeuw staan: eeuwen.',
    },
    {
      kind: 'choice',
      id: 'koning',
      prompt: 'Kies de goede spelling.',
      before: 'Op 27 april vieren we de verjaardag van de',
      after: '.',
      options: ['koning', 'konink', 'konieng', 'koningk'],
      answer: 'koning',
      why: 'Een woord op -ing: altijd ng, zonder k. In het meervoud hoor je het: koningen. En de i is kort: één letter, geen ie.',
    },
    {
      kind: 'sort',
      id: 'w-woorden',
      prompt: 'eeuw, ieuw of uw?',
      buckets: ['eeuw', 'ieuw', 'uw'],
      items: [
        { t: 'de spr_ (een zwarte vogel met witte stipjes)', b: 0 },
        { t: 'de l_erik (een vogel die hoog in de lucht zingt)', b: 0 },
        { t: 'een _enoude kerk', b: 0 },
        { t: 'g_en tijdens een saaie les', b: 0 },
        { t: 'de sn_schuiver op de weg', b: 0 },
        { t: 'opn_ beginnen', b: 1 },
        { t: 'je paspoort laten vern_en', b: 1 },
        { t: 'een n_komer in Nederland', b: 1 },
        { t: 'de n_sbrief van school', b: 1 },
        { t: 'een sl_e vos (slim en gemeen)', b: 2 },
        { t: 'r_weg de helft (ongeveer)', b: 2 },
        { t: 'een sch_ hert (snel bang)', b: 2 },
        { t: 'Geef de schommel een d_.', b: 2 },
      ],
      why: 'eeuw: spreeuw, leeuwerik, eeuwenoud, geeuwen, sneeuwschuiver. ieuw: opnieuw, vernieuwen, nieuwkomer, nieuwsbrief. uw: sluwe, ruwweg, schuw, duw.',
    },
    {
      kind: 'rewrite',
      id: 'verbeter',
      prompt: 'Schrijf de zin goed over. Verbeter alle fouten.',
      source: 'Mijn collega dengkt dat de oefenink te moejelijk is voor de groep.',
      accept: ['Mijn collega denkt dat de oefening te moeilijk is voor de groep.'],
      why: 'denkt: ng-klank + k = nk. oefening: een woord op -ing eindigt op ng. moeilijk: oe + j-klank = oei, en -lijk met ij.',
    },
    {
      kind: 'write',
      id: 'schrijf',
      prompt: 'Schrijf een appje aan een vriend over het weer en wat je vandaag gaat doen.',
      intro: 'Gebruik woorden uit deze les. Controleer ze daarna met het stappenplan.',
      minWords: 25,
      must: [
        { label: 'Een woord met ng (bijvoorbeeld lang, koning, woning)', hint: 'lang, jongen, vergadering', test: { pattern: 'ng', flags: 'i' } },
        { label: 'Een woord met nk (bijvoorbeeld denk, drinken, bank)', hint: 'denk, drinken, dank', test: { pattern: 'nk', flags: 'i' } },
        { label: 'Een woord met aai, ooi of oei', hint: 'mooi, saai, moeilijk', test: { pattern: 'aai|ooi|oei', flags: 'i' } },
        { label: 'Een woord met eeuw, ieuw of uw', hint: 'sneeuw, nieuw, ruw', test: { pattern: 'eeuw|ieuw|uw', flags: 'i' } },
      ],
      starters: ['Hoi! Het weer is', 'Vandaag ga ik', 'Ik denk dat'],
      why: 'Loop de woorden langs het stappenplan: ng of nk, aai/ooi/oei, eeuw/ieuw/uw.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Vijfentwintig woorden door elkaar, ook van eerdere lessen. Hoofdletters tellen mee. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Typ de vorm van *duwen*',
          before: 'De motor doet het niet. Ik',
          after: 'de auto en jij stuurt.',
          a: 'duw',
          why: 'uw met één u, in elke vorm: duwen, ik duw, hij duwt.',
        },
        {
          q: 'Typ de verleden tijd van *stinken*',
          before: 'Het hele huis',
          after: 'naar verbrand eten.',
          a: 'stonk',
          why: 'stinken → stonk: ng-klank + k = nk.',
        },
        {
          q: 'Typ het meervoud van *auto*',
          before: 'Er staan te veel',
          after: 'in onze straat.',
          a: 'auto’s',
          why: 'Een woord op a, i, o, u of y krijgt in het meervoud ’s: auto’s.',
        },
        {
          q: 'Typ de vorm van het werkwoord: met riemen een boot vooruit laten gaan',
          before: 'Elke zaterdag',
          after: 'mijn buurman op de rivier, ook als het regent.',
          a: 'roeit',
          why: 'roeien → hij roeit: oe + j-klank = oei, en die blijft staan.',
        },
        {
          q: 'De grote witte vogel met lange rode poten die zijn nest op een paal of een dak bouwt',
          a: 'ooievaar',
          also: ['de ooievaar'],
          why: 'oo + j-klank = ooi: ooievaar.',
        },
        {
          q: 'Het tegenovergestelde van *vast*, bij een contract',
          before: 'Ik heb een',
          after: 'contract van zes maanden.',
          a: 'tijdelijk',
          why: 'tijd met ij, en -lijk aan het eind ook met ij: tijdelijk.',
        },
        {
          q: 'Schrijf het woord dat je hoort. Het hoort bij *moe*: waar je heel moe van wordt.',
          say: 'vermoeiende',
          before: 'Het was een',
          after: 'week met veel overuren.',
          a: 'vermoeiende',
          why: 'vermoeien + d + e: vermoeiende. oe + j-klank = oei.',
        },
        {
          q: 'Een grote witte of grijze vogel die je aan zee ziet',
          before: 'Pas op je patat, die',
          after: 'pakt hem zo uit je hand!',
          a: 'meeuw',
          also: ['zeemeeuw'],
          why: 'ee + w schrijf je als eeuw: meeuw.',
        },
        {
          q: 'Typ het zelfstandig naamwoord van *uitnodigen*',
          before: 'Bedankt voor de',
          after: 'voor je verjaardag!',
          a: 'uitnodiging',
          why: 'uitnodigen + ing: uitnodiging. Een woord op -ing eindigt op ng.',
        },
        {
          q: 'Typ het tegenovergestelde van *warm*, met de goede uitgang',
          before: 'Na een',
          after: 'nacht zat er ijs op de auto.',
          a: 'koude',
          also: ['ijskoude'],
          why: 'Direct een d na de klank: ou. koud + e = koude.',
        },
        {
          q: 'Typ het bijvoeglijk naamwoord van *koning*',
          before: 'De',
          after: 'familie is op staatsbezoek in Japan.',
          a: 'koninklijke',
          why: 'koning + lijk: je hoort de ng-klank en dan een k, dus nk. Nooit ngk. Met -e: koninklijke.',
        },
        { q: 'Een vis ademt door zijn …', a: 'kieuwen', also: ['kieuw'], why: 'ie + w schrijf je als ieuw: kieuw, kieuwen.' },
        {
          q: 'Typ het tegenovergestelde van *spannend*, met de goede uitgang',
          before: 'Het was zo’n',
          after: 'film dat ik in slaap viel.',
          a: 'saaie',
          why: 'saai + e = saaie. De i staat er al: er komt geen j bij.',
        },
        {
          q: 'Typ het woord: niet gekookt, met de goede uitgang',
          before: 'Sushi is vaak met',
          after: 'vis.',
          a: 'rauwe',
          why: 'rauw staat in het rijtje met auw (flauw, pauw, rauw …). rauw + e = rauwe.',
        },
        {
          q: 'Typ het tegenovergestelde van *ouder*',
          before: 'Mijn zus is twee jaar',
          after: 'dan ik.',
          a: 'jonger',
          why: 'jong → jonger: alleen de ng-klank, geen k erachter.',
        },
        {
          q: 'Typ de verleden tijd van *hangen*',
          before: 'Mijn natte jas',
          after: 'de hele nacht aan de kapstok.',
          a: 'hing',
          why: 'hangen → hing: alleen de ng-klank, geen k.',
        },
        {
          q: 'Typ de verleden tijd van *schenken*',
          before: 'De ober',
          after: 'de glazen nog een keer vol.',
          a: 'schonk',
          why: 'schenken → schonk: je hoort een k na de ng-klank, dus nk.',
        },
        {
          q: 'De korte rust in een vergadering of tussen twee lessen',
          before: 'Om half elf is er een',
          after: 'van een kwartier.',
          a: 'pauze',
          why: 'pauze hoort bij het rijtje au zonder w: auto, augustus, saus, pauze.',
        },
        {
          q: 'Wat doe je met je hand als je iemand groet die ver weg is? Typ de vorm die past.',
          before: 'Kijk, daar staat oma op het perron! Ze',
          after: 'naar ons.',
          a: 'zwaait',
          also: ['wuift'],
          why: 'zwaaien → ze zwaait: aai blijft in elke vorm staan, er komt alleen een t bij.',
        },
        {
          q: 'Het getal 1, met nadruk',
          before: 'Er is nog maar',
          after: 'plek vrij in de cursus.',
          a: 'één',
          why: 'Het getal 1: één, met accenten. een zonder accenten is het lidwoord.',
        },
        { q: 'Gedroogd gras als voer voor koeien en paarden', a: 'hooi', also: ['het hooi'], why: 'oo + j-klank = ooi: hooi.' },
        {
          q: 'Typ het woord bij *u*: van u',
          before: 'Mag ik',
          after: 'paspoort even zien?',
          a: 'uw',
          why: 'uu + w schrijf je als uw, met één u. En midden in de zin klein.',
        },
        { q: 'Iemand die nooit liegt, is …', a: 'eerlijk', why: 'eer + lijk: -lijk schrijf je altijd met ij.' },
        {
          q: 'Een lange versiering van papier die je bij een verjaardag aan het plafond hangt',
          a: 'slinger',
          also: ['slingers', 'de slinger'],
          why: 'slinger: alleen de ng-klank, geen k erachter.',
        },
        {
          q: 'Het buurland met Brussel als hoofdstad',
          a: 'België',
          why: 'Bel-gi-ë: de e begint een nieuwe lettergreep en spreek je los uit. Daarom een trema.',
        },
      ],
      caps: true,
      done: { title: 'Reeks klaar', text: 'ng of nk, aai, ooi, oei, eeuw, ieuw en uw, en de regels van eerder: allemaal zelf getypt.' },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail aan de huisbaas aan. Typ elk woord helemaal.',
      intro: 'Kijk goed naar de zin om het gat heen. Het grijze woord in het vakje is een hulp, niet het antwoord.',
      title: 'Mail aan de huisbaas',
      text: 'Beste meneer Bakker,\n\nSinds de {sneeuw|witte vlokken|ee + w schrijf je als eeuw: sneeuw.} van vorige week doet de {verwarming|verwarmen, zelfstandig naamwoord|Een woord op -ing eindigt altijd op ng: verwarming.} in onze {woning|won…|Een woord op -ing: ng, nooit nk. In het meervoud hoor je het: woningen.} het niet meer. Het wordt binnen {nooit|niet één keer|oo + j-klank = ooi, met een t erachter: nooit.} warmer dan veertien graden. Mijn {jongste|tegenovergestelde van oudste|jong heeft ng zonder k. Met -ste erachter: jongste.} zoon is al een week ziek, en mijn {vrouw|echtgenote|Gewoon ouw: vrouw hoort niet bij het korte rijtje met auw (blauw, flauw, pauw …).} slaapt met haar jas aan.\n\nIk heb de ketel al {opnieuw|opn…|ie + w schrijf je als ieuw: opnieuw.} aangezet. Elke ochtend {draai|rond laten gaan, ik-vorm|draaien: aai blijft in elke vorm staan. ik draai.} ik een paar keer aan de knop, maar er gebeurt niets. Het is ook {moeilijk|mo…|oe + j-klank = oei, en -lijk met ij: moeilijk.} om het raam in de slaapkamer te openen. Het {oude|niet nieuw, met de goede uitgang|Direct een d na de klank: ou. Je hoort de d in oude.} hout is {ruw|niet glad|uu + w schrijf je als uw, met één u: ruw.} en het raam zit vast. Een elektrisch kacheltje is niet veilig met {kleine|niet groot, met de goede uitgang|klein is een ei-woord: kleine.} kinderen in huis.\n\nWilt u zo snel {mogelijk||-lijk schrijf je altijd met ij: mogelijk.} een monteur sturen? Ik ben elke dag thuis, behalve {’s middags|in de middag|Er zijn letters weggelaten: daarom een apostrof. ’s middags.}. Ik {denk|de…|ng-klank + k schrijf je als nk: denk. Nooit dengk.} dat de reparatie niet lang duurt.\n\nIk ben u erg {dankbaar|da…baar|ng-klank + k = nk: dankbaar.} voor uw hulp.\n\nMet vriendelijke groet,\nSamir Haddad',
      why: 'ng of nk: hoor je een k na de ng-klank, dan nk. aai, ooi en oei: de j-klank schrijf je als i. eeuw, ieuw en uw: uw met één u. En van eerder: vrouw en oude met ou, kleine met ei, -lijk met ij en de apostrof in ’s middags.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen uit de buurtapp. Hoofdletters en leestekens tellen mee.',
      title: 'Bericht in de buurtapp',
      sentences: [
        'Door de sneeuw is fietsen in onze straat heel moeilijk.',
        'De stoep bij de nieuwe woningen is een ijsbaan.',
        'Mijn jongste zoon gooit al zout bij de ingang.',
        'Wie helpt er morgen mee om de sneeuw opzij te duwen?',
        'Daarna drinken we bij mij iets warms tegen de kou.',
        'Zwaai na het werk maar naar mijn keukenraam.',
      ],
      right:
        'Alles goed: sneeuw met eeuw, nieuwe met ieuw, duwen met uw, moeilijk met oei, gooit met ooi en zwaai met aai. woningen, jongste en ingang met ng, drinken met nk. En van eerder: ijsbaan en opzij met ij, zout en kou met ou, keukenraam aan elkaar.',
      wrong:
        'Kijk de lastige woorden na: sneeuw (eeuw), nieuwe (ieuw), duwen (uw, één u), moeilijk (oei, en -lijk met ij), gooit (ooi), zwaai (aai), woningen, jongste en ingang (ng), drinken (nk). En van eerder: ijsbaan en opzij met ij, zout en kou met ou, en keukenraam als één woord.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail na voordat Ingrid hem naar het team stuurt',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'team magazijn', subject: 'Volgende week' },
      greeting: 'Hallo allemaal,',
      signoff: 'Groet,\nIngrid',
      tokens: [
        { t: 'Volgende' },
        { t: 'week' },
        { t: 'begint' },
        { t: 'de' },
        { t: 'niewe', fix: 'nieuwe', why: 'ie + w schrijf je als ieuw: nieuw, nieuwe.' },
        { t: 'planning.' },
        { t: 'Op' },
        { t: 'Maandag', fix: 'maandag', why: 'Dagen schrijf je met een kleine letter, behalve aan het begin van de zin.' },
        { t: 'is' },
        { t: 'er' },
        { t: 'om' },
        { t: 'negen' },
        { t: 'uur' },
        { t: 'een' },
        { t: 'vergaderink', fix: 'vergadering', why: 'Een woord op -ing eindigt altijd op ng: vergaderingen, dus vergadering.' },
        { t: 'in' },
        { t: 'de' },
        { t: 'grote' },
        { t: 'zaal.' },
        { t: 'Daar' },
        { t: 'vertel' },
        { t: 'ik' },
        { t: 'meer' },
        { t: 'over' },
        { t: 'de' },
        { t: 'opleijding', fix: 'opleiding', why: 'opleiding komt van leiden, met ei. Nooit ei en ij samen.' },
        { t: 'die' },
        { t: 'we' },
        { t: 'in' },
        { t: 'het' },
        { t: 'voorjaar' },
        { t: 'krijgen.' },
        { t: 'Het' },
        { t: 'wordt' },
        { t: 'geen' },
        { t: 'saaije', fix: 'saaie', why: 'saai + e = saaie. De i staat er al: er komt geen j bij.' },
        { t: 'dag:' },
        { t: 'de' },
        { t: 'trainer' },
        { t: 'is' },
        { t: 'nieuwsgierig', trap: 'Goed: nieuws + gierig, met ieuw. Het lijkt lang, maar er klopt alles.' },
        { t: 'naar' },
        { t: 'jullie' },
        { t: 'ideeën.', trap: 'Goed: i-dee-ën. De e van de laatste lettergreep spreek je los uit, dus een trema.' },
        { t: 'Neem' },
        { t: 'wel' },
        { t: 'een' },
        { t: 'eigen' },
        { t: 'lunch' },
        { t: 'mee,' },
        { t: 'want' },
        { t: 'de' },
        { t: 'kantine' },
        { t: 'is' },
        { t: 'die' },
        { t: 'dag' },
        { t: 'dicht.' },
        { t: 'Ik' },
        { t: 'weet' },
        { t: 'dat' },
        { t: 'de' },
        { t: 'diensten' },
        { t: 'nu' },
        { t: 'vermoeijend', fix: 'vermoeiend', why: 'oe met een j-klank schrijf je als oei: vermoeiend.' },
        { t: 'zijn,' },
        { t: 'zeker' },
        { t: 'met' },
        { t: 'kleine' },
        { t: 'kinderen.' },
        { t: 'Bij' },
        { t: 'ruw', trap: 'Goed: uu + w schrijf je als uw, met één u. ruuw bestaat niet.' },
        { t: 'weer' },
        { t: 'of' },
        { t: 'als' },
        { t: 'het' },
        { t: 'flink' },
        { t: 'sneeuwt,', trap: 'Goed: sneeuwen → het sneeuwt. eeuw blijft staan en er komt een t bij.' },
        { t: 'mag' },
        { t: 'je' },
        { t: 'later' },
        { t: 'beginnen.' },
        { t: 'Laat' },
        { t: 'het' },
        { t: 'me' },
        { t: 'dan' },
        { t: 'wel' },
        { t: 'gouw', fix: 'gauw', why: 'gauw hoort bij het korte rijtje met auw: flauw, pauw, kauwen, rauw, lauw, blauw, gauw.' },
        { t: 'weten.' },
        { t: 'Alvast' },
        { t: 'bedangkt', fix: 'bedankt', why: 'ng-klank + k schrijf je als nk: bedankt. Nooit ngk.' },
        { t: 'voor' },
        { t: 'jullie' },
        { t: 'inzet!' },
      ],
      done: {
        title: 'Nagekeken',
        text: 'De fouten: nieuwe, maandag, vergadering, opleiding, saaie, vermoeiend, gauw en bedankt. nieuwsgierig, ideeën, ruw en sneeuwt waren goed.',
      },
    },
  ],
};
