import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": g of ch, cht of gt, en sch en -isch. */
export const LES_K34: LessonInput = {
  id: 'k34',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'g, ch en cht',
  skill: 'Spelling',
  icon: 'g/ch',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Dezelfde klank, twee spellingen',
      panels: [
        {
          text: 'Zeg *dag* en *lach*. Aan het eind hoor je dezelfde klank. De *g* en de *ch* klinken bijna overal hetzelfde. Je moet dus kiezen. Aan het begin van een Nederlands woord is dat makkelijk: daar schrijf je bijna altijd *g*: *geld*, *groot*, *goed*, *graag*, *gisteren*, *gezond*. Een *ch* vooraan zie je alleen in leenwoorden, zoals *chaos*, *chef* en *chauffeur*. Die komen terug in de les over leenwoorden.',
          rule: 'Aan het begin van een Nederlands woord schrijf je *g*: *geld*, *groot*, *gisteren*.',
          quiz: {
            q: 'Je hoort het begin van de dag vóór vandaag: ‘…isteren’. Hoe begint het woord?',
            options: ['g', 'ch'],
            answer: 'g',
            why: 'gisteren. Aan het begin van een Nederlands woord staat de g. Een ch vooraan is voor leenwoorden zoals chef.',
          },
        },
        {
          text: 'In het midden en aan het eind kan het allebei: *dag* en *lach*, *regen* en *lachen*. Hier helpt één ding: een woord houdt zijn letter. Ken je één vorm, dan ken je ze allemaal. *dagen* heeft een *g*, dus ook *dag*, *dagje* en *dagelijks*. *lachen* heeft een *ch*, dus ook *ik lach* en *hij lacht*. En onthoud: *g* kan dubbel (*vlaggen*, *zeggen*, *liggen*, *bruggen*), *ch* nooit (*lachen*, *kachel*). Veelgebruikte woorden met *ch*: *lachen*, *kachel*, *pech*, *toch*, *zich*, *ochtend*, *dochter*, *lichaam*. Een woord op *-ig* heeft altijd een *g*: *gezellig*, *nodig*.',
          rule: 'Een woord houdt zijn letter: *dagen* → *dag*, *lachen* → *hij lacht*. De *ch* wordt nooit dubbel.',
          paradigm: {
            q: 'Zet het langere woord in het vakje',
            cols: ['langer woord'],
            rows: [
              { label: 'dag (meervoud)', cells: [{ fill: 'dagen', hint: 'dag heeft een g, dus het meervoud ook.' }] },
              { label: 'vlag (meervoud)', cells: [{ fill: 'vlaggen', hint: 'Korte a: de g wordt dubbel.' }] },
              { label: 'brug (meervoud)', cells: [{ fill: 'bruggen', hint: 'Korte u: de g wordt dubbel.' }] },
              { label: 'oog (meervoud)', cells: [{ fill: 'ogen', hint: 'Open lettergreep: één o, en de g blijft.' }] },
              { label: 'ik lach (hele werkwoord)', cells: [{ fill: 'lachen', hint: 'ch blijft ch, en wordt nooit dubbel.' }] },
            ],
            extra: ['dachen', 'vlachen', 'bruchen', 'oochen', 'lagen'],
            note: 'Elk woord houdt zijn eigen letter: dag en dagen, lach en lachen. Alleen de g kan dubbel: vlaggen, bruggen.',
          },
        },
        {
          text: 'Hoor je *cht*, zoals in *lucht*? Dan schrijf je bijna altijd *ch*: *lucht*, *licht*, *nacht*, *acht*, *recht*, *zacht*, *gracht*, *echt*, *slecht*, *gezicht*. Er is één groot geval met *gt*: een vorm van een werkwoord waarvan de stam op *g* eindigt. Je plakt dan een *t* aan de *g*: *liggen* → *hij ligt*, *leggen* → *hij legt*, *zeggen* → *zij zegt*, *vragen* → *hij vraagt*, *dragen* → *zij draagt*, *volgen* → *hij volgt*, *zorgen* → *zij zorgt*. En twee woorden om te onthouden: *hoogte* (van *hoog*) en *laagte* (van *laag*).',
          rule: 'Je hoort *cht*: is het een werkwoord met een *g* in de stam (*liggen* → *ligt*)? Dan *gt*. Anders bijna altijd *cht*.',
          mark: {
            q: 'Tik de woorden met gt: de vormen van een werkwoord met g',
            sentence: 'Mijn dochter zegt dat het licht in de nacht te fel is en ze legt een doek over de lamp.',
            targets: [2, 14],
            note: 'zegt (zeggen) en legt (leggen): stam op g + t. dochter, licht en nacht hebben geen werkwoord met g: daar schrijf je ch.',
          },
        },
        {
          text: 'Aan het begin van een woord staat vaak *sch*: *school*, *schrijven*, *schip*, *schoen*, *schoon*, *schaar*. Je hoort een *s* en daarna de *g*-klank. Aan het eind van een bijvoeglijk naamwoord staat vaak *-isch*. Daar hoor je de *ch* niet: je hoort alleen ‘ies’. Toch schrijf je *-isch*: *logisch*, *praktisch*, *typisch*, *elektrisch*, *fantastisch*, *medisch*, *Arabisch*. Met een *-e* erachter blijft de *sch* staan: *een logische vraag*, *de elektrische fiets*.',
          rule: 'Een bijvoeglijk naamwoord dat eindigt op ‘ies’ schrijf je met *-isch*: *logisch*, *praktisch*.',
          quiz: {
            q: 'Je hoort ‘prak-ties’. Hoe schrijf je het?',
            options: ['praktisch', 'prakties', 'praktiesch'],
            answer: 'praktisch',
            why: 'praktisch is een bijvoeglijk naamwoord op -isch. De ch hoor je niet, maar je schrijft hem wel. En met -e: een praktische tas.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'g-of-ch',
      prompt: 'g of ch? Kies wat er op de plek van _ hoort.',
      buckets: ['g', 'ch'],
      items: [
        { t: 'da_ (van dagen)', b: 0 },
        { t: 'vla_ (van vlaggen)', b: 0 },
        { t: 'la_en (om een grap)', b: 1 },
        { t: 'ber_ (van bergen)', b: 0 },
        { t: 'Kom je to_?', b: 1 },
        { t: 're_en (het regent)', b: 0 },
        { t: 'ka_el (in de kamer, voor warmte)', b: 1 },
        { t: 'do_ter (je kind, een meisje)', b: 1 },
        { t: 'vo_el (een dier met veren)', b: 0 },
        { t: 'pe_ (ik heb ... gehad)', b: 1 },
        { t: 'o_tend (voor de middag)', b: 1 },
        { t: 'spie_el (in de badkamer)', b: 0 },
      ],
      why: 'Met g: dag, vlag, berg, regen, vogel, spiegel. Met ch: lachen, toch, kachel, dochter, pech, ochtend. Je hoort het verschil niet: deze woorden moet je kennen.',
    },
    {
      kind: 'choice',
      id: 'licht-ligt',
      prompt: 'Kies de goede spelling.',
      before: 'Doe het',
      after: 'maar uit, ik ga slapen.',
      options: ['licht', 'ligt'],
      answer: 'licht',
      why: 'Het licht van de lamp: een zelfstandig naamwoord, dus cht. ligt is een vorm van liggen: het boek ligt op tafel.',
    },
    {
      kind: 'type',
      id: 'brug',
      prompt: 'Typ het enkelvoud.',
      before: 'Twee bruggen, één',
      after: '.',
      hint: 'woord',
      answer: 'brug',
      why: 'bruggen heeft een g, dus brug ook. Aan het eind hoor je hetzelfde als bij lach, maar het woord houdt zijn letter.',
    },
    {
      kind: 'fix',
      id: 'zegt',
      prompt: 'Tik het fout gespelde woord en verbeter het.',
      sentence: 'Mijn collega zecht dat de vergadering later begint.',
      wrong: 2,
      answer: 'zegt',
      why: 'zeggen heeft een g. De stam is zeg, en voor zij of hij komt er een t bij: zegt.',
    },
    {
      kind: 'sort',
      id: 'cht-of-gt',
      prompt: 'cht of gt? Kies wat er op de plek van _ hoort.',
      buckets: ['cht', 'gt'],
      items: [
        { t: 'Hij le_ het boek op tafel.', b: 1 },
        { t: 'Er is geen wolk in de lu_.', b: 0 },
        { t: 'Mijn zus vraa_ of je komt.', b: 1 },
        { t: 'Het kussen is heel za_.', b: 0 },
        { t: 'De baby li_ in bed.', b: 1 },
        { t: 'Het is al a_ uur.', b: 0 },
        { t: 'Wie zor_ voor de hond?', b: 1 },
        { t: 'Hij la_ om de grap.', b: 0 },
        { t: 'Ze vol_ een cursus Nederlands.', b: 1 },
        { t: 'Dat is e_ waar.', b: 0 },
        { t: 'De hoo_e van de toren is vijftig meter.', b: 1 },
        { t: 'Het eten is niet sle_.', b: 0 },
      ],
      why: 'gt bij werkwoorden met een g in de stam: legt (leggen), vraagt (vragen), ligt (liggen), zorgt (zorgen), volgt (volgen), en hoogte (hoog). cht in lucht, zacht, acht, echt en slecht. En lacht komt van lachen: dat heeft al een ch.',
    },
    {
      kind: 'bet',
      id: 'hoogte',
      prompt: 'Hoe schrijf je het woord voor ‘hoe hoog iets is’?',
      options: ['hoogte', 'hochte', 'hoogde'],
      answer: 'hoogte',
      why: 'hoogte komt van hoog, met een g. Je hoort cht, maar je schrijft gt. Zo ook laagte, van laag.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen en een stappenplan',
      panels: [
        {
          text: 'Een paar veelgebruikte werkwoorden hebben in de verleden tijd *cht*. Ook als het hele werkwoord een *g* heeft. Ze eindigen altijd op *-cht*: *kopen* → *kocht*, *zoeken* → *zocht*, *denken* → *dacht*, *brengen* → *bracht*, *mogen* → *mocht*, *vechten* → *vocht*. In het meervoud: *kochten*, *zochten*, *dachten*. Leer ze als rijtje. Maar *vragen* → *vroeg* en *dragen* → *droeg* eindigen gewoon op *g*.',
          rule: '*kocht*, *zocht*, *dacht*, *bracht*, *mocht*: altijd met *ch*.',
          lab: {
            label: 'Tik een werkwoord',
            chips: [
              { k: 'kopen', out: 'ik kocht, wij kochten', note: 'Geen g in kopen, en toch ch: kocht.' },
              { k: 'brengen', out: 'ik bracht, wij brachten', note: 'brengen heeft een g, maar de verleden tijd is bracht, met ch.' },
              { k: 'mogen', out: 'ik mocht, wij mochten', note: 'Nu: ik mag, met g. Verleden tijd: ik mocht, met ch.' },
              { k: 'denken', out: 'ik dacht, wij dachten', note: 'Ook dacht: altijd ch.' },
              { k: 'vragen', out: 'ik vroeg, wij vroegen', note: 'Hier geen cht: vroeg eindigt gewoon op g.' },
            ],
          },
        },
        {
          text: 'Pas op met woorden die op elkaar lijken. *het licht* (van de lamp) en *hij ligt* (van *liggen*) klinken precies hetzelfde. En een zelfstandig naamwoord krijgt *cht*, ook als er een werkwoord met *g* bij hoort: *de klacht* (maar *hij klaagt*), *de jacht* (maar *de hond jaagt*), *het gewicht* (maar *hij weegt*). Vraag jezelf: is het een vorm van een werkwoord? Pas dan *gt*. Werkwoorden met *ch* in de stam houden hun *ch*: *lachen* → *hij lacht*, *wachten* → *hij wacht*, *zuchten* → *zij zucht*.',
          rule: 'Een vorm van een werkwoord met *g*: *gt* (*hij klaagt*). Een zelfstandig naamwoord: *cht* (*de klacht*).',
          quiz: {
            q: 'De sleutel … op de kast.',
            options: ['ligt', 'licht'],
            answer: 'ligt',
            why: 'Een vorm van liggen: de stam lig + t. licht is wat een lamp geeft.',
          },
        },
        {
          text: 'Alleen bijvoeglijke naamwoorden krijgen *-isch*. Een zelfstandig naamwoord op ‘-nis’ heeft gewoon *-nis*: *de kennis*, *de gebeurtenis*, *de begrafenis*. Korte woorden als *fris*, *vis* en *mis* krijgen ook gewoon een *s*. Bij talen en landen moet je goed kijken: *Arabisch*, *Russisch* en *Belgisch* met *-isch*, maar *Turks*, *Frans* en *Duits* zonder.',
          rule: '*-isch* alleen aan het eind van een bijvoeglijk naamwoord dat op ‘ies’ klinkt.',
          mark: {
            q: 'Tik de woorden met -isch of -ische',
            sentence: 'Het was een fantastische dag met frisse lucht en een typisch Belgisch ontbijt.',
            targets: [3, 10, 11],
            note: 'fantastische, typisch en Belgisch. frisse komt van fris: een kort woord met gewoon een s, dubbel na de korte i.',
          },
        },
        {
          text: 'Twijfel je tussen *g* en *ch*? Loop dit stappenplan af. 1. Begint het woord ermee? Dan *g*, behalve in leenwoorden. 2. Ken je een andere vorm van het woord? Die heeft dezelfde letter: *dagen* → *dag*, *lachen* → *lacht*. 3. Hoor je *cht*? Is het een vorm van een werkwoord met *g*, dan *gt* (*zegt*); anders *cht* (*lucht*, *klacht*). Let op *kocht*, *zocht*, *dacht*, *bracht*, *mocht*. 4. Een bijvoeglijk naamwoord op ‘ies’? Dan *-isch*. 5. Nog steeds twijfel? Zoek het woord op.',
          rule: 'Begin: *g*. Midden en eind: ken het woord. *cht*, behalve bij een werkwoord met *g*: *gt*.',
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Ik heb een klacht over de rekening.', 'Ik heb een klaagt over de rekening.', 'Ik heb een klagt over de rekening.'],
            answer: 'Ik heb een klacht over de rekening.',
            why: 'de klacht is een zelfstandig naamwoord: cht. Alleen het werkwoord krijgt gt: hij klaagt.',
          },
        },
      ],
    },
    {
      kind: 'swipe',
      id: 'goed-of-fout',
      prompt: 'Is de zin goed gespeld?',
      intro: 'Veeg naar rechts als de zin goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'Ik heb het boek gisteren gekocht.', ok: true, why: 'gekocht van kopen: altijd met ch.' },
        { t: 'Hij brag de kinderen naar school.', ok: false, fix: 'bracht', why: 'De verleden tijd van brengen is bracht, met cht.' },
        { t: 'Sara zegt dat ze ziek is.', ok: true, why: 'zeggen: stam zeg + t = zegt.' },
        { t: 'Het boek licht op de bank.', ok: false, fix: 'ligt', why: 'Een vorm van liggen: ligt. licht komt van een lamp.' },
        { t: 'Dat is een logies antwoord.', ok: false, fix: 'logisch', why: 'Een bijvoeglijk naamwoord op ‘ies’: -isch.' },
        { t: 'Mijn moeder klacht over de buren.', ok: false, fix: 'klaagt', why: 'Hier is het een werkwoord: klagen → zij klaagt. de klacht is het zelfstandig naamwoord.' },
        { t: 'We hebben een elektrische fiets gekocht.', ok: true, why: 'elektrisch + e = elektrische; de sch blijft staan.' },
        { t: 'Vroeger mogt ik niet alleen naar buiten.', ok: false, fix: 'mocht', why: 'De verleden tijd van mogen is mocht, met ch.' },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje',
      prompt: 'Vind de vijf fouten in het appje en verbeter ze.',
      intro: 'Let op g, ch, cht, gt en -isch.',
      header: { to: 'Sanne' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Sanne!' },
        { t: 'Ik' },
        { t: 'kom' },
        { t: 'iets' },
        { t: 'later,' },
        { t: 'want' },
        { t: 'ik' },
        { t: 'heb' },
        { t: 'slegt', fix: 'slecht', why: 'slecht heeft geen werkwoord met g: cht.' },
        { t: 'geslapen.' },
        { t: 'Mijn' },
        { t: 'buurman' },
        { t: 'zecht', fix: 'zegt', why: 'zeggen → hij zegt: stam op g + t.' },
        { t: 'dat' },
        { t: 'de' },
        { t: 'bruch', fix: 'brug', why: 'bruggen, dus brug: het woord houdt zijn g.' },
        { t: 'bij' },
        { t: 'het' },
        { t: 'station' },
        { t: 'dicht' },
        { t: 'is.' },
        { t: 'Ik' },
        { t: 'neem' },
        { t: 'de' },
        { t: 'bus' },
        { t: 'van' },
        { t: 'acht' },
        { t: 'uur.' },
        { t: 'Ik' },
        { t: 'vraach', fix: 'vraag', why: 'vragen heeft een g: ik vraag.' },
        { t: 'Tim' },
        { t: 'straks' },
        { t: 'of' },
        { t: 'de' },
        { t: 'les' },
        { t: 'om' },
        { t: 'negen' },
        { t: 'uur' },
        { t: 'begint.' },
        { t: 'Dat' },
        { t: 'lijkt' },
        { t: 'me' },
        { t: 'logies.', fix: 'logisch.', why: 'Een bijvoeglijk naamwoord op ‘ies’: -isch.' },
        { t: 'Tot' },
        { t: 'zo!' },
      ],
      done: {
        title: 'Alle vijf gevonden',
        text: 'slecht, zegt, brug, vraag en logisch. dicht en acht waren al goed: geen werkwoord met g, dus cht.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ de zin.',
      sentence: 'Mijn dochter vraagt of ze het licht in de keuken mag aandoen.',
      right: 'Goed: dochter en licht met ch, vraagt met gt (van vragen), en mag met g.',
      wrong: 'Let op: dochter en licht met ch; vraagt met gt, want vragen heeft een g; mag eindigt op g, net als mogen.',
    },
    {
      kind: 'type',
      id: 'logische',
      prompt: 'Typ het woord dat hoort bij ‘logisch’, met de goede uitgang.',
      before: 'Dat is een heel',
      after: 'vraag.',
      hint: 'logisch…',
      answer: 'logische',
      why: 'logisch + e = logische. De sch blijft staan, ook als je hem niet hoort.',
    },
    {
      kind: 'choice',
      id: 'mocht',
      prompt: 'Kies de goede vorm.',
      before: 'Vroeger',
      after: 'ik niet alleen naar de stad.',
      options: ['mocht', 'mogt', 'mochte'],
      answer: 'mocht',
      why: 'mogen → ik mocht. Net als kocht, zocht, dacht en bracht: altijd -cht.',
    },
    {
      kind: 'rewrite',
      id: 'hij-legt',
      prompt: 'Begin de zin met ‘Hij’ en pas het werkwoord aan.',
      source: 'Ik leg de sleutel op de kast.',
      accept: ['Hij legt de sleutel op de kast.'],
      why: 'leggen: stam leg, met hij + t: hij legt. Je hoort cht, maar het is een werkwoord met g.',
    },
    {
      kind: 'sort',
      id: 'isch-of-s',
      prompt: 'sch of s? Kies wat er op de plek van _ hoort.',
      buckets: ['sch', 's'],
      items: [
        { t: 'een logi_ antwoord', b: 0 },
        { t: 'de kenni_', b: 1 },
        { t: 'een fri_ drankje', b: 1 },
        { t: 'een typi_ fout', b: 0 },
        { t: 'de gebeurteni_', b: 1 },
        { t: 'een elektri_ fiets', b: 0 },
        { t: 'Hij spreekt Arabi_.', b: 0 },
        { t: 'een gla_ water', b: 1 },
        { t: 'een fantasti_ idee', b: 0 },
        { t: 'de begrafeni_', b: 1 },
      ],
      why: 'sch aan het eind van bijvoeglijke naamwoorden (en talen) op ‘ies’: logisch, typisch, elektrisch, Arabisch, fantastisch. Gewoon s in fris, glas en in de zelfstandige naamwoorden op -nis: kennis, gebeurtenis, begrafenis.',
    },
    {
      kind: 'bet',
      id: 'gewicht',
      prompt: 'wegen heeft een g. Hoe schrijf je: ‘Wat is het … van de koffer?’',
      options: ['gewicht', 'gewigt'],
      answer: 'gewicht',
      why: 'het gewicht is een zelfstandig naamwoord, geen vorm van wegen. Daarom cht. Alleen het werkwoord krijgt gt: hij weegt de koffer.',
    },
    {
      kind: 'write',
      id: 'appje-schrijven',
      prompt: 'Schrijf een appje aan een collega: je komt later, en je legt uit waarom.',
      intro: 'Schrijf minstens 25 woorden. Gebruik de woorden uit deze les.',
      minWords: 25,
      must: [
        { label: 'Een woord met cht', hint: 'acht, echt, licht, nacht, slecht', test: { pattern: '\\b\\w*cht\\w*\\b', flags: 'i' } },
        { label: 'Een werkwoord met gt', hint: 'zegt, ligt, vraagt, zorgt', test: { pattern: '\\b\\w+gt\\b', flags: 'i' } },
        { label: 'Een woord op -isch of -ische', hint: 'logisch, praktisch, typisch', test: { pattern: '\\b\\w+ische?\\b', flags: 'i' } },
      ],
      starters: ['Hoi, ik kom vandaag wat later,', 'Mijn buurman zegt dat', 'Dat is wel zo praktisch,'],
      why: 'Lees je appje nog één keer na: cht bij lucht, echt en nacht; gt alleen bij een werkwoord met g; -isch bij een bijvoeglijk naamwoord op ‘ies’.',
    },
  ],
};
