import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": d of t en b of p aan het eind, door het woord langer te maken. */
export const LES_K35: LessonInput = {
  id: 'k35',
  stage: 'regels',
  domain: 'orth',
  also: ['morf'],
  title: 'Langer maken: d of t, b of p',
  skill: 'Spelling',
  icon: 'd/t',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Je hoort t, maar je schrijft soms d',
      panels: [
        {
          text: 'Zeg *hond* en *pot*. Aan het eind hoor je allebei een *t*. Toch schrijf je *hond* met een *d*. Aan het eind van een woord hoor je nooit een *d* of een *b*: je hoort altijd *t* of *p*. Wat je moet schrijven, hoor je pas als je het woord langer maakt. Dan staat de letter niet meer aan het eind en hoor je hem wel: *honden* met *d*, *potten* met *t*.',
          rule: 'Twijfel je aan het eind tussen *d* en *t*, of *b* en *p*? Maak het woord langer en luister.',
          build: {
            before: 'Mijn',
            stem: 'hon',
            endings: ['d', 't', 'dt'],
            answer: 'd',
            note: 'honden, dus hond. Het woord houdt in het enkelvoud dezelfde letter als in het meervoud.',
          },
        },
        {
          text: 'Er zijn drie manieren om een woord langer te maken. 1. Maak er een meervoud van: *hand* → *handen*, *kaart* → *kaarten*. 2. Zet er bij een bijvoeglijk naamwoord een *-e* achter: *goed* → *goede*, *rond* → *ronde*, *wit* → *witte*. 3. Zoek een familiewoord: *goud* → *gouden*, *hout* → *houten*, *ik heb* → *hebben*. Welke manier je kiest, maakt niet uit. Als je de letter maar hoort.',
          rule: 'Langer maken: meervoud (*handen*), *-e* (*goede*) of een familiewoord (*gouden*).',
          paradigm: {
            q: 'Vul het langere woord in en daarna het korte woord',
            cols: ['langer woord', 'dus'],
            rows: [
              { label: 'paar_ (in de wei)', cells: [{ fill: 'paarden' }, { fill: 'paard', hint: 'In paarden hoor je een d.' }] },
              { label: 'kaar_ (voor de trein)', cells: [{ fill: 'kaarten' }, { fill: 'kaart', hint: 'In kaarten hoor je een t.' }] },
              { label: 'goe_ (niet slecht)', cells: [{ fill: 'goede' }, { fill: 'goed', hint: 'een goede vriend: d.' }] },
              { label: 'wi_ (een kleur)', cells: [{ fill: 'witte', hint: 'Korte i: de t wordt dubbel.' }, { fill: 'wit' }] },
              { label: 'hou_ (van een boom)', cells: [{ fill: 'houten', hint: 'een houten tafel: t.' }, { fill: 'hout' }] },
            ],
            extra: ['paarten', 'kaarden', 'goet', 'paart', 'kaard', 'wid'],
            note: 'paarden, kaarten, goede, witte en houten. Zodra er een klinker achter komt, hoor je of het d of t is.',
          },
        },
        {
          text: 'Bij *b* en *p* werkt het net zo. Aan het eind hoor je altijd *p*. Maak het woord langer: *web* → *webben*, *krab* → *krabben*, *rib* → *ribben*, *ik heb* → *hebben*. Tegenover: *kop* → *koppen*, *lamp* → *lampen*, *trap* → *trappen*, *schaap* → *schapen*. Een *b* aan het eind komt niet vaak voor. Een *p* veel vaker.',
          rule: 'Aan het eind hoor je *p*. In het langere woord hoor je of het *b* of *p* is: *webben*, *koppen*.',
          quiz: {
            q: 'Twee krabben, één …',
            options: ['krab', 'krap'],
            answer: 'krab',
            why: 'krabben, dus krab. krap is een ander woord: te klein of te nauw, zoals een krappe broek.',
          },
        },
        {
          text: 'Sommige woorden kun je niet langer maken. Dat zijn vooral korte woordjes, en die eindigen op *t*: *dat*, *wat*, *het*, *met*, *niet*, *tot*, *uit*, *nooit*. Leer ze zoals ze zijn. Alle andere woorden maak je in je hoofd even langer. Oefen het hier: welke woorden eindigen op een *d*?',
          rule: 'Korte woordjes als *dat*, *wat*, *met*, *niet* en *tot*: altijd *t*.',
          mark: {
            q: 'Tik de woorden die op een d eindigen',
            sentence: 'Het brood ligt op de rand van het bord, naast een goed mes.',
            targets: [1, 5, 8, 11],
            note: 'brood (broden), rand (randen), bord (borden) en goed (goede). Het en ligt eindigen op een t.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'd-of-t',
      prompt: 'd of t? Maak het woord in je hoofd langer.',
      buckets: ['d', 't'],
      items: [
        { t: 'het gebie_ rond de stad', b: 0 },
        { t: 'met veel gedul_ wachten', b: 0 },
        { t: 'een schul_ bij de bank', b: 0 },
        { t: 'een dunne draa_ om een knoop aan te naaien', b: 0 },
        { t: 'Hij is kwaa_ op zijn broer.', b: 0 },
        { t: 'het zaa_ voor de moestuin', b: 0 },
        { t: 'de moe_ om nee te zeggen', b: 0 },
        { t: 'de flui_ van de scheidsrechter', b: 1 },
        { t: 'mijn maa_ van het voetbal (vriend)', b: 1 },
        { t: 'De staa_ betaalt de toeslag.', b: 1 },
        { t: 'het zwee_ op je voorhoofd', b: 1 },
        { t: 'een kapotte rui_ in de achterdeur', b: 1 },
        { t: 'Met vriendelijke groe_,', b: 1 },
        { t: 'een bou_ en een moer', b: 1 },
      ],
      why: 'Met d: gebieden, geduldig, schulden, draden, kwade, zaden, moedig. Met t: fluiten, maten, staten, zweten, ruiten, groeten, bouten. Zoek een meervoud, een vorm met -e of een familiewoord, en luister.',
    },
    {
      kind: 'choice',
      id: 'gescheiden',
      prompt: 'Kies de goede spelling.',
      before: 'Mijn ouders zijn al tien jaar',
      after: '.',
      options: ['gescheiden', 'gescheiten', 'gescheidt', 'gescheide'],
      answer: 'gescheiden',
      why: 'scheiden heeft een d, en die blijft in elke vorm: gescheiden. Het eindigt hier op -en, net als het hele werkwoord.',
    },
    {
      kind: 'type',
      id: 'breed',
      prompt: 'Typ het tegenovergestelde van smal.',
      before: 'De rivier is hier tweehonderd meter',
      after: '.',
      hint: '',
      answer: 'breed',
      why: 'Maak het langer: een brede rivier. Daar hoor je een d, dus breed.',
    },
    {
      kind: 'fix',
      id: 'bruid',
      prompt: 'Eén woord in de zin is fout gespeld. Tik het aan en verbeter het.',
      sentence: 'Na de bruiloft kreeg het bruidspaar een prachtige taart van de beste vriendin van de bruit.',
      wrong: 15,
      answer: 'bruid',
      why: 'bruiden, dus bruid, net als in bruidspaar. bruiloft eindigt wel op een t: bruiloften.',
    },
    {
      kind: 'sort',
      id: 'b-of-p',
      prompt: 'b of p? Maak het woord in je hoofd langer.',
      buckets: ['b', 'p'],
      items: [
        { t: 'de kra_ op het strand', b: 0 },
        { t: 'het we_ van de spin', b: 0 },
        { t: 'een gebroken ri_', b: 0 },
        { t: 'Ik he_ geen tijd.', b: 0 },
        { t: 'de ro_ op de zandbank (een zeedier)', b: 0 },
        { t: 'de schu_ van een vis', b: 0 },
        { t: 'de sla_ om de nek van de baby', b: 0 },
        { t: 'de kle_ van de motor', b: 1 },
        { t: 'de do_ van de fles', b: 1 },
        { t: 'de lam_ boven de tafel', b: 1 },
        { t: 'de kno_ van je jas', b: 1 },
        { t: 'het scha_ in de wei', b: 1 },
        { t: 'een goede gra_', b: 1 },
        { t: 'Het water is hier die_.', b: 1 },
      ],
      why: 'Met b: krabben, webben, ribben, hebben, robben, schubben, slabben. Met p: kleppen, doppen, lampen, knoppen, schapen, grappen, diepe. Een b aan het eind is zeldzaam: ken deze woorden goed.',
    },
    {
      kind: 'bet',
      id: 'verbod',
      prompt: 'Er geldt een … op vuurwerk in het centrum.',
      options: ['verbod', 'verbot', 'verbodt', 'verboot'],
      answer: 'verbod',
      why: 'Verboden toegang: in verboden hoor je een d, dus verbod. En in verbod hoor je een korte o: één letter.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen: samenstellingen, uitgangen en werkwoorden',
      panels: [
        {
          text: 'In een samenstelling schrijf je elk deel zoals het los is. Ook als je iets anders hoort. *hand* + *doek* = *handdoek*: twee keer *d*, al hoor je er maar één. Zo ook *hoofdpijn* (*hoofd*), *avondeten* (*avond*), *landkaart* (*land*), *stadhuis* (*stad*), *bordspel* (*bord*), *tandarts* (*tand*), *goudvis* (*goud*). Een veelgemaakte fout is *hoofpijn*: daar ontbreekt de *d* van *hoofd*.',
          rule: 'In een samenstelling houdt elk deel zijn eigen spelling: *hand* + *doek* = *handdoek*.',
          split: {
            q: 'Knip het woord in zijn twee delen',
            word: 'handdoek',
            answer: 'hand-doek',
            note: 'hand + doek. Je hoort één d, maar je schrijft er twee: één van hand, één van doek.',
          },
        },
        {
          text: 'Ook met een uitgang erachter blijft de letter van het woord staan. *-je*: *hoedje*, *broodje*, *handje*, *kindje*. Je hoort vaak ‘-tje’, maar je schrijft *d* + *je*. *-heid*, *-elijk*, *-ste* en *-te*: *gezondheid* (*gezond*), *vriendelijk* (*vriend*), *eindelijk* (*einde*), *oudste* (*oud*), *breedte* (*breed*).',
          rule: 'Met *-je*, *-heid*, *-elijk*, *-ste* of *-te* blijft de *d*: *broodje*, *gezondheid*, *oudste*.',
          paradigm: {
            q: 'Plak het stuk erachter en kies de goede spelling',
            cols: ['samen'],
            rows: [
              { label: 'brood + je', cells: [{ fill: 'broodje', hint: 'brood houdt zijn d: broodje.' }] },
              { label: 'gezond + heid', cells: [{ fill: 'gezondheid', hint: 'gezonde, dus gezond, dus gezondheid.' }] },
              { label: 'vriend + elijk', cells: [{ fill: 'vriendelijk', hint: 'vrienden: d.' }] },
              { label: 'oud + ste', cells: [{ fill: 'oudste', hint: 'oude: d.' }] },
              { label: 'breed + te', cells: [{ fill: 'breedte', hint: 'brede: d.' }] },
            ],
            extra: ['brootje', 'gezontheid', 'vrientelijk', 'outste', 'breette'],
            note: 'Je hoort overal een t, maar het woord houdt zijn d: broodje, gezondheid, vriendelijk, oudste, breedte.',
          },
        },
        {
          text: 'Ook bij werkwoorden werkt langer maken, voor de stam: *worden* → *ik word*, *vinden* → *ik vind*, *hebben* → *ik heb*, *antwoorden* → *ik antwoord*. Of er bij *hij* of *jij* nog een *t* achter komt (*hij wordt*, *hij vindt*), leer je in de lessen over werkwoorden. Hier gaat het om de stam: daar staat de letter van het hele werkwoord.',
          rule: 'De stam van een werkwoord houdt de letter van het hele werkwoord: *vinden* → *ik vind*.',
          quiz: {
            q: 'Ik … het een mooie film.',
            options: ['vind', 'vint', 'vindt'],
            answer: 'vind',
            why: 'vinden → stam vind. Bij ik komt er niets achter: ik vind.',
          },
        },
        {
          text: 'Twijfel je? Loop dit stappenplan af. 1. Maak een meervoud. 2. Gaat dat niet? Zet er een *-e* achter. 3. Gaat dat ook niet? Zoek een familiewoord (*goud* → *gouden*). 4. Niets te vinden? Dan is het meestal een kort woordje met *t* (*dat*, *met*). Let op: in het meervoud kan de klinker veranderen. Dat maakt niet uit: je kijkt alleen naar de medeklinker aan het eind.',
          rule: 'Meervoud, *-e* of familiewoord: de medeklinker die je dan hoort, schrijf je ook aan het eind.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'stad', out: 'steden', note: 'De a wordt ee, maar de d blijft: stad.' },
              { k: 'schip', out: 'schepen', note: 'De i wordt ee, maar je hoort een p: schip.' },
              { k: 'bad', out: 'baden', note: 'De a wordt lang, de d blijft: bad.' },
              { k: 'lid', out: 'leden', note: 'Lid van een club: leden, met d.' },
              { k: 'pet', out: 'petten', note: 'Korte e, t wordt dubbel: pet.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'swipe',
      id: 'goed-of-fout',
      prompt: 'Is de zin goed gespeld?',
      intro: 'Veeg naar rechts als de zin goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'Hij gaf me een goede raad voor mijn sollicitatie.', ok: true, why: 'raad: aanraden, met een d.' },
        { t: 'Het verwijd van mijn baas was niet eerlijk.', ok: false, fix: 'verwijd → verwijt', why: 'verwijten, dus het verwijt: t.' },
        { t: 'Ze hebben een rond tafeltje voor de keuken gekocht.', ok: true, why: 'een ronde tafel: d. Dus rond.' },
        { t: 'De optocht trok in een lange stoed door de stad.', ok: false, fix: 'stoed → stoet', why: 'stoeten, dus stoet: t.' },
        { t: 'Ze kreeg een gouden horloge voor haar verjaardag.', ok: true, why: 'goud + en: gouden. De d van goud blijft.' },
        { t: 'Mijn handoek ligt nog op het strand.', ok: false, fix: 'handoek → handdoek', why: 'hand + doek: twee keer d, ook al hoor je er maar één.' },
        {
          t: 'De kosten van de gezontheidszorg stijgen elk jaar.',
          ok: false,
          fix: 'gezontheidszorg → gezondheidszorg',
          why: 'gezonde, dus gezond. In gezondheidszorg blijft die d staan.',
        },
        { t: 'Ik hep morgen een afspraak bij de huisarts.', ok: false, fix: 'hep → heb', why: 'hebben, dus ik heb: b.' },
        { t: 'De dokter zei dat mijn bloeddruk goed is.', ok: true, why: 'bloed + druk: bloeden, dus d. goede, dus goed.' },
        { t: 'Het hondje sliep de hele avond in zijn mand.', ok: true, why: 'hond + je, avonden, manden: overal d.' },
        { t: 'De kinderen spelen een bordspel aan de keukentafel.', ok: true, why: 'bord + spel: borden, dus d.' },
        { t: 'We gaan dit weekent met de kinderen naar zee.', ok: false, fix: 'weekent → weekend', why: 'weekenden, dus weekend: d.' },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-school',
      prompt: 'Vind de fouten in de mail en verbeter ze.',
      intro: 'Maak elk woord in je hoofd langer.',
      header: { to: 'meneer Smit', subject: 'Adam is ziek' },
      greeting: 'Beste meneer Smit,',
      tokens: [
        { t: 'Mijn' },
        { t: 'zoon' },
        { t: 'Adam' },
        { t: 'kan' },
        { t: 'vandaag' },
        { t: 'niet' },
        { t: 'naar' },
        { t: 'school' },
        { t: 'komen.' },
        { t: 'Hij' },
        { t: 'heeft' },
        { t: 'sinds' },
        { t: 'gisteravont', fix: 'gisteravond', also: ['gisterenavond'], why: 'gisteren + avond, en avonden heeft een d.' },
        { t: 'koorts' },
        { t: 'en' },
        { t: 'hoofpijn.', fix: 'hoofdpijn.', why: 'hoofd + pijn: de d van hoofd blijft staan.' },
        { t: 'Hij' },
        { t: 'moet' },
        { t: 'een' },
        { t: 'paar' },
        { t: 'dagen' },
        { t: 'in' },
        { t: 'bet', fix: 'bed', why: 'bedden, dus bed.' },
        { t: 'blijven.' },
        { t: 'Ik' },
        { t: 'hoop' },
        { t: 'dat' },
        { t: 'hij' },
        { t: 'volgende' },
        { t: 'week' },
        { t: 'weer' },
        { t: 'gezont', fix: 'gezond', why: 'gezonde, dus gezond.' },
        { t: 'is.' },
        { t: 'Zijn' },
        { t: 'vrient', fix: 'vriend', why: 'vrienden, dus vriend.' },
        { t: 'Daan' },
        { t: 'neemt' },
        { t: 'het' },
        { t: 'huiswerk' },
        { t: 'voor' },
        { t: 'hem' },
        { t: 'mee.' },
        { t: 'Met' },
        { t: 'vriendelijke' },
        { t: 'groet,' },
        { t: 'Fatima' },
      ],
      done: {
        title: 'Alle vijf gevonden',
        text: 'gisteravond, hoofdpijn, bed, gezond en vriend. moet, dat en het waren goed: daar hoor je een t in het langere woord, of het is een kort woordje.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ de zin.',
      intro: 'Eén lange zin. Hoofdletters en leestekens tellen mee.',
      sentence: 'Op de brede vensterbank staat een rond glas met de goudvis van de oudste zoon van mijn vriendin.',
      right: 'Goed: brede (breed), rond (ronde), goudvis (gouden), oudste (oude) en vriendin (vrienden).',
      wrong:
        'Maak de woorden langer: ronde, gouden, oude, vrienden. Dan hoor je overal een d. goudvis is goud + vis en oudste is oud + ste: de d blijft staan. En brede met een d, net als breed.',
    },
    {
      kind: 'type',
      id: 'gezondheid',
      prompt: 'Typ het zelfstandig naamwoord van gezond.',
      before: 'Sporten is goed voor je',
      after: '.',
      hint: '',
      answer: 'gezondheid',
      why: 'gezond (gezonde) + heid: gezondheid. De d blijft staan, ook al hoor je een t.',
    },
    {
      kind: 'rewrite',
      id: 'ik-vorm',
      prompt: 'Begin de zin met ‘Ik’ en pas de werkwoorden aan.',
      source: 'Wij vinden de nieuwe regels raar en antwoorden morgen op de brief.',
      accept: ['Ik vind de nieuwe regels raar en antwoord morgen op de brief.'],
      why: 'vinden → ik vind, antwoorden → ik antwoord. De stam houdt de d van het hele werkwoord, ook al hoor je een t.',
    },
    {
      kind: 'choice',
      id: 'eindelijk',
      prompt: 'Kies de goede spelling.',
      before: 'Het is',
      after: 'weekend!',
      options: ['eindelijk', 'eintelijk', 'eindelik', 'eijndelijk'],
      answer: 'eindelijk',
      why: 'eindelijk komt van einde: d. Het begint met ei, nooit ei en ij samen. En de uitgang is -lijk, met ij.',
    },
    {
      kind: 'type',
      id: 'oudste',
      prompt: 'Typ het woord dat in de zin past.',
      before: 'Mijn broer is vijftig, mijn zus is vijfenveertig en ik ben veertig: hij is de',
      after: 'van ons drieën.',
      hint: '',
      answer: 'oudste',
      why: 'oud (oude) + ste: oudste. Je hoort een t, maar de d van oud blijft staan.',
    },
    {
      kind: 'bet',
      id: 'hout',
      prompt: 'Deze tafel is van …',
      options: ['hout', 'houd', 'houdt', 'haut'],
      answer: 'hout',
      why: 'een houten tafel: je hoort een t, dus hout. houd en houdt zijn vormen van het werkwoord houden: ik houd van koffie. haut bestaat niet: na de klank komt een t, dus ou.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Zesentwintig woorden door elkaar, ook van eerdere lessen. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Typ de vorm van *vermijden*',
          before: 'Ik',
          after: 'de snelweg in de spits.',
          a: 'vermijd',
          why: 'vermijden: de stam is vermijd, met de d van het hele werkwoord. Bij ik komt er niets achter.',
        },
        { q: 'Het rode vocht in je aderen', a: 'bloed', also: ['het bloed'], why: 'bloeden, bloedig: je hoort een d, dus bloed.' },
        {
          q: 'Hoe hoog iets is',
          before: 'De',
          after: 'van het plafond is drie meter.',
          a: 'hoogte',
          why: 'hoogte komt van hoog: je hoort cht, maar je schrijft gt.',
        },
        {
          q: 'Typ de vorm van *verwijten*',
          before: 'Ik',
          after: 'het mezelf dat ik niet eerder heb gebeld.',
          a: 'verwijt',
          why: 'verwijten: de stam is verwijt, met een t. Bij ik komt er niets achter.',
        },
        { q: 'De belangrijkste stad van een land', a: 'hoofdstad', also: ['de hoofdstad'], why: 'hoofd + stad: hoofden en steden, dus twee keer een d.' },
        { q: 'Wat er in de winter in witte vlokken uit de lucht valt', a: 'sneeuw', also: ['de sneeuw'], why: 'ee + w schrijf je als eeuw.' },
        {
          q: 'Typ de vorm van *worden*',
          before: 'Ik',
          after: 'volgende maand veertig.',
          a: 'word',
          why: 'worden: de stam is word. Bij ik komt er niets achter.',
        },
        { q: 'Het verkleinwoord van *brood*', a: 'broodje', also: ['het broodje'], why: 'brood + je: de d van brood blijft staan, ook al hoor je ‘-tje’.' },
        {
          q: 'Iets wat echt waar is',
          before: 'Dat is een',
          after: ', geen mening.',
          a: 'feit',
          why: 'feiten, dus feit met een t. En feit met ei: ken het woord.',
        },
        {
          q: 'Schrijf het woord dat je hoort: een gebouw met huisartsen, een apotheek en een fysiotherapeut',
          say: 'gezondheidscentrum',
          before: 'Ik moet om tien uur naar het',
          after: 'in de wijk.',
          a: 'gezondheidscentrum',
          why: 'gezond (gezonde) + heid + s + centrum: de d van gezond blijft staan.',
        },
        {
          q: 'Hoe breed iets is',
          before: 'De',
          after: 'van de kamer is vier meter.',
          a: 'breedte',
          why: 'breed (brede) + te: breedte. De d blijft, ook al hoor je een t.',
        },
        {
          q: 'Typ het bijvoeglijk naamwoord bij *de logica*, met de goede uitgang',
          before: 'Dat is een',
          after: 'keuze.',
          a: 'logische',
          why: 'logisch is een bijvoeglijk naamwoord op ‘ies’: -isch. Met -e: logische.',
        },
        {
          q: 'De avond van gisteren',
          after: 'ben ik vroeg naar bed gegaan.',
          a: 'gisteravond',
          also: ['gisterenavond'],
          why: 'gisteren + avond: avonden, dus d. En aan elkaar: gisteravond.',
        },
        { q: 'Typ de vorm van *hebben*', before: 'Ik', after: 'geen zin in de vergadering.', a: 'heb', why: 'hebben, dus ik heb: b.' },
        {
          q: 'Het witte poeder dat je op je patat strooit',
          a: 'zout',
          also: ['het zout'],
          why: 'zouten, zoute haring: je hoort een t. En direct een t na de klank: ou.',
        },
        {
          q: 'Typ het enkelvoud',
          before: 'Twee schepen in de haven, één',
          after: 'op zee.',
          a: 'schip',
          why: 'schepen: je hoort een p, dus schip. De klinker verandert, maar de p blijft.',
        },
        { q: 'Typ de verleden tijd van *denken*', before: 'Ik', after: 'dat de winkel al dicht was.', a: 'dacht', why: 'denken → dacht: altijd met ch.' },
        {
          q: 'De aarde met alle landen en mensen',
          before: 'Hij wil een reis rond de',
          after: 'maken.',
          a: 'wereld',
          why: 'werelden: je hoort een d, dus wereld.',
        },
        { q: 'Ongeveer dertig dagen', a: 'maand', also: ['een maand'], why: 'maanden: d. En aa, want je hoort een lange klank: maand.' },
        { q: 'Het orgaan in je borst dat klopt', a: 'hart', also: ['het hart'], why: 'harten, hartje: t. Niet verwarren met hard (harde).' },
        {
          q: 'Typ het zelfstandig naamwoord bij *verwarmen*',
          before: 'Zet de',
          after: 'wat hoger, het is koud.',
          a: 'verwarming',
          why: 'Een woord op -ing eindigt altijd op ng: verwarming.',
        },
        {
          q: 'Het tegenovergestelde van *zacht*',
          before: 'Deze matras is veel te',
          after: '.',
          a: 'hard',
          why: 'een harde matras: d. Niet verwarren met het hart (harten).',
        },
        {
          q: 'Typ het meervoud van *het café*',
          before: 'In deze straat zijn drie',
          after: '.',
          a: 'cafés',
          why: 'café + s: het accent blijft, en na é komt geen apostrof: cafés.',
        },
        { q: 'Het tegenovergestelde van *eb*', a: 'vloed', also: ['de vloed'], why: 'vloeden: d. Eb en vloed.' },
        {
          q: 'Typ het meervoud van *de baby*',
          before: 'Op de afdeling liggen vijf',
          after: '.',
          a: 'baby’s',
          why: 'Een woord op y krijgt in het meervoud ’s: baby’s.',
        },
        {
          q: 'Wat je hebt als je bij een vereniging hoort (niet *abonnement*)',
          before: 'Ik heb mijn',
          after: 'van de tennisclub opgezegd.',
          a: 'lidmaatschap',
          why: 'lid (leden) + maatschap: de d van lid blijft staan.',
        },
      ],
      done: { title: 'Reeks klaar', text: 'd of t, b of p door langer maken, en de regels van eerder: allemaal zelf getypt.' },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul het bericht van de gemeente aan. Typ elk woord helemaal.',
      intro: 'Maak elk woord in je hoofd langer. Het grijze woord in het vakje is een hulp, niet het antwoord.',
      title: 'Bericht van de gemeente: feest in het centrum',
      text: 'Beste bewoners,\n\nOp zaterdag viert onze {stad|plaats, groter dan een dorp|steden, dus stad.} haar verjaardag met een groot feest. Om twee uur opent de burgemeester het feest op de {trap|de treden voor de deur|trappen, dus trap.} van het {stadhuis|sta_huis|stad + huis: de d van stad blijft staan.}. Daarna vertrekt de {stoet|stoe_|stoeten, dus stoet.} via de {hoofdstraat|de belangrijkste straat|hoofd + straat: hoofden, dus d.} naar het park. Die straat is vorig jaar {verbreed|breder gemaakt|brede, dus breed. Met ver- ervoor: verbreed.}, dus er is plek genoeg.\n\nVan twaalf tot zes uur geldt een {verbod|het mag niet|verboden, dus verbod.} op parkeren in het hele {gebied|gebie_|gebieden, dus gebied.}. {Auto’s|meervoud van de auto|Een woord op o krijgt in het meervoud ’s: auto’s.} die er toch staan, worden weggesleept.\n\nIn het park opent de burgemeester ook de {nieuwe|niet oud, met de goede uitgang|ie + w = ieuw: nieuw, nieuwe.} speeltuin. Kinderen krijgen er gratis een zakje {snoep~snoepjes|zoetigheid|snoepen: je hoort een p, dus snoep.}, en om vier uur is er een {zangwedstrijd|wie zingt het mooist?|zang met ng. wedstrijd: twee keer een d (wed + strijd, denk aan wedden en strijden).}. Om tien uur {’s avonds|in de avond|Er is een stukje weggelaten (des avonds): apostrof.} is er vuurwerk boven de vijver. Heeft u last van het {geluid|gelui_|geluiden, dus geluid.}? Bel dan de {wijkagent|w_kagent|wijk met ij: ken het woord.}. Hij is de hele dag in het park.\n\nWe hopen op een {droge|niet nat, met de goede uitgang|droog met g: droge.} en zonnige dag!\n\nMet vriendelijke groet,\nTeam Evenementen',
      why: 'd of t, b of p: maak het woord langer (steden, trappen, verboden, gebieden, geluiden) of kijk naar de delen van een samenstelling (stad + huis, hoofd + straat). En van eerder: auto’s, nieuwe, zangwedstrijd, ’s avonds, wijkagent en droge.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen over een bezoek aan de tandarts. Hoofdletters en leestekens tellen mee.',
      title: 'Naar de tandarts',
      sentences: [
        'Mijn dochter heeft sinds vannacht kiespijn aan de linkerkant van haar mond.',
        'Ze kon van de pijn niet slapen en at vanochtend ook geen brood.',
        'Even later zaten we in de volle wachtkamer van de tandarts.',
        'De tandarts was vriendelijk en zei dat haar gebit verder gezond is.',
        'Ze kreeg een vulling en mag een week lang geen hard snoep eten.',
        'Op de terugweg kochten we soep en een goed boek voor in bed.',
      ],
      right:
        'Alles goed: mond, vanochtend, brood, tandarts, vriendelijk, gezond, hard, goed en bed met d, gebit met t, soep met p. En wachtkamer en kochten met ch, kreeg met g.',
      wrong:
        'Maak de woorden langer: monden, ochtenden, broden, tanden, vrienden, gezonde, harde, goede, bedden (d); gebitten (t); soepen (p). Let ook op wachtkamer en kochten (ch) en op kreeg (g, van krijgen).',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de sollicitatiemail na voordat Amira hem verstuurt',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'mevrouw Visser', subject: 'Sollicitatie verkoper' },
      greeting: 'Geachte mevrouw Visser,',
      signoff: 'Met vriendelijke groet,\nAmira El Idrissi',
      tokens: [
        { t: 'Met' },
        { t: 'veel' },
        { t: 'plezier' },
        { t: 'reageer' },
        { t: 'ik' },
        { t: 'op' },
        { t: 'uw' },
        { t: 'vacature' },
        { t: 'voor' },
        { t: 'een' },
        { t: 'verkoper' },
        { t: 'in' },
        { t: 'de' },
        { t: 'bakkerij.' },
        { t: 'Ik' },
        { t: 'woon' },
        { t: 'sinds' },
        { t: 'vorig' },
        { t: 'jaar' },
        { t: 'in' },
        { t: 'het' },
        { t: 'centrum' },
        { t: 'van' },
        { t: 'de' },
        { t: 'stat.', fix: 'stad.', why: 'steden, dus stad: d.' },
        { t: 'Ik' },
        { t: 'hep', fix: 'heb', why: 'hebben, dus ik heb: b.' },
        { t: 'al' },
        { t: 'drie' },
        { t: 'jaar' },
        { t: 'ervaring' },
        { t: 'in' },
        { t: 'een' },
        { t: 'bakkerij' },
        { t: 'in' },
        { t: 'Utrecht.' },
        { t: 'Daar' },
        { t: 'verkocht' },
        { t: 'ik' },
        { t: 'brood,' },
        { t: 'taart', trap: 'Goed: taarten, dus taart met een t.' },
        { t: 'en' },
        { t: 'brootjes,', fix: 'broodjes,', why: 'brood + je: de d van brood blijft staan.' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'hielp' },
        { t: 'met' },
        { t: 'de' },
        { t: 'bestellingen' },
        { t: 'van' },
        { t: 'de' },
        { t: 'webwinkel.', trap: 'Goed: web + winkel. webben, dus web met een b.' },
        { t: 'Mijn' },
        { t: 'oude' },
        { t: 'baas' },
        { t: 'is' },
        { t: 'nu' },
        { t: 'met' },
        { t: 'pensioen' },
        { t: 'en' },
        { t: 'de' },
        { t: 'zaak' },
        { t: 'is' },
        { t: 'dicht.' },
        { t: 'Ik' },
        { t: 'werk' },
        { t: 'hart', fix: 'hard', why: 'Hier betekent het: met veel inzet. Dat is hard (harde), met een d. Het hart (harten) klopt in je borst.' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'doe' },
        { t: 'mijn' },
        { t: 'werk' },
        { t: 'met' },
        { t: 'hart', trap: 'Goed: met hart en ziel. Dat is het hart (harten), met een t.' },
        { t: 'en' },
        { t: 'ziel.' },
        { t: 'Ook' },
        { t: 'ben' },
        { t: 'ik' },
        { t: 'altijd' },
        { t: 'vrientelijk', fix: 'vriendelijk', why: 'vriend (vrienden) + elijk: de d blijft staan.' },
        { t: 'tegen' },
        { t: 'klanten.' },
        { t: 'Ik' },
        { t: 'kan' },
        { t: 'elke' },
        { t: 'dag' },
        { t: 'beginnen,' },
        { t: 'ook' },
        { t: 'vroeg' },
        { t: 'in' },
        { t: 'de' },
        { t: 'ochtent.', fix: 'ochtend.', why: 'ochtenden, dus ochtend: d.' },
        { t: 'Avonddiensten', trap: 'Goed: avond + diensten. avonden, dus avond met een d, en dienst begint met een d: twee keer d.' },
        { t: 'vind' },
        { t: 'ik' },
        { t: 'geen' },
        { t: 'probleem.' },
        { t: 'Mijn' },
        { t: 'huidige' },
        { t: 'contract' },
        { t: 'loopt' },
        { t: 'eint', fix: 'eind', why: 'het einde: d. Dus eind.' },
        { t: 'Mei', fix: 'mei', why: 'Maanden schrijf je met een kleine letter.' },
        { t: 'af.' },
        { t: 'Ik' },
        { t: 'hoop' },
        { t: 'op' },
        { t: 'een' },
        { t: 'goed' },
        { t: 'gesprek.' },
      ],
      done: {
        title: 'Nagekeken',
        text: 'De fouten: stad, heb, broodjes, hard, vriendelijk, ochtend, eind en mei. taart, webwinkel, hart (met hart en ziel) en avonddiensten waren goed.',
      },
    },
  ],
};
