import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": s of z en f of v, aan het begin, aan het eind en in langere vormen. */
export const LES_K36: LessonInput = {
  id: 'k36',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 's of z, f of v',
  skill: 'Spelling',
  icon: 's/z',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Nooit een z of v aan het eind',
      panels: [
        {
          text: 'Aan het begin van een woord moet je het woord kennen. Met *z*: *zee*, *zon*, *zout*, *zaterdag*, *zeep*. Met *s*: *soep*, *suiker*, *slapen*, *september*. Met *v*: *vader*, *vis*, *veel*, *vrij*, *vlees*. Met *f*: *fiets*, *feest*, *fout*, *fijn*, *film*. Maar aan het eind van een woord is het simpel: daar staat nooit een *z* of een *v* (alleen in een paar leenwoorden, zoals *quiz*). Daar schrijf je altijd *s* of *f*: *huis*, *kaas*, *reis*, *brief*, *lief*, *neef*.',
          rule: 'Aan het eind van een woord: nooit *z* of *v*, altijd *s* of *f*: *huis*, *brief*.',
          quiz: {
            q: 'Welke spelling is goed?',
            options: ['de brief', 'de briev', 'de brieff'],
            answer: 'de brief',
            why: 'Aan het eind van een woord staat nooit een v. En na ie komt geen dubbele f.',
          },
        },
        {
          text: 'Maak je het woord langer, dan hoor je soms een *z* of een *v*. Die schrijf je dan ook: *huis* → *huizen*, *kaas* → *kazen*, *prijs* → *prijzen*, *reis* → *reizen*, *brief* → *brieven*, *neef* → *neven*, *wolf* → *wolven*. Dat geldt ook voor een bijvoeglijk naamwoord met *-e*: *lief* → *lieve*, *boos* → *boze*, *grijs* → *grijze*, *doof* → *dove*, *half* → *halve*.',
          rule: 'Hoor je in het langere woord een *z* of *v*? Schrijf dan *z* of *v*: *huizen*, *brieven*, *lieve*.',
          paradigm: {
            q: 'Zet de langere vorm in het vakje',
            cols: ['langere vorm'],
            rows: [
              { label: 'huis (meervoud)', cells: [{ fill: 'huizen', hint: 'Je hoort een z: huizen.' }] },
              { label: 'muis (meervoud)', cells: [{ fill: 'muizen', hint: 'Net als huis: muizen.' }] },
              { label: 'brief (meervoud)', cells: [{ fill: 'brieven', hint: 'Je hoort een v: brieven.' }] },
              { label: 'wolf (meervoud)', cells: [{ fill: 'wolven', hint: 'Na de l hoor je een v: wolven.' }] },
              { label: 'boos (de … buurman)', cells: [{ fill: 'boze', hint: 'Open lettergreep: één o, en een z.' }] },
            ],
            extra: ['huisen', 'muisen', 'brieffen', 'wolfen', 'boosse'],
            note: 'huizen, muizen, brieven, wolven en boze. Aan het eind s of f, met een klinker erachter komt de z of v terug.',
          },
        },
        {
          text: 'Maar niet elk woord krijgt een *z* of *v*. Hoor je in het langere woord een *s* of *f*, dan blijft het *s* of *f*: *kous* → *kousen*, *dans* → *dansen*, *mens* → *mensen*, *kruis* → *kruisen*, *eis* → *eisen*, *fotograaf* → *fotografen*. Aan het korte woord zie je dat niet: *huis* wordt *huizen*, maar *kruis* wordt *kruisen*. Leer daarom het meervoud mee. En na een korte klank wordt de *s* of *f* dubbel: *vis* → *vissen*, *bus* → *bussen*, *straf* → *straffen*.',
          rule: 'Hoor je *s* of *f* in het langere woord? Dan blijft het *s* of *f*. Na een korte klank: *ss* of *ff*.',
          lab: {
            label: 'Tik een woord en zie het meervoud',
            chips: [
              { k: 'huis', out: 'huizen', note: 'Met z.' },
              { k: 'kruis', out: 'kruisen', note: 'Zelfde klank als huis, maar met s. Leer het meervoud mee.' },
              { k: 'reis', out: 'reizen', note: 'Met z.' },
              { k: 'eis', out: 'eisen', note: 'Met s, net als kruis.' },
              { k: 'gans', out: 'ganzen', note: 'Na de n een z.' },
              { k: 'dans', out: 'dansen', note: 'Ook na de n, maar nu met s.' },
            ],
          },
        },
        {
          text: 'Bij werkwoorden geldt hetzelfde. Haal *-en* van het hele werkwoord af, dan staat de *z* of *v* aan het eind. Die wordt *s* of *f*: *leven* → *ik leef*, *reizen* → *ik reis*, *geloven* → *ik geloof*, *verhuizen* → *ik verhuis*, *lezen* → *ik lees*, *geven* → *ik geef*. Komt er een *t* achter, dan blijft het *s* of *f*: *hij leeft*, *zij reist*, *het vriest*. Bij *wij* hoor je de *z* of *v* weer: *wij leven*, *wij reizen*.',
          rule: 'Stam van een werkwoord: *s* en *f*, ook met *t*: *ik leef*, *hij leeft*, *zij reist*.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik', 'hij'],
            rows: [
              { label: 'leven', cells: [{ fill: 'leef' }, { fill: 'leeft', hint: 'Geen v voor de t: leeft.' }] },
              { label: 'reizen', cells: [{ fill: 'reis' }, { fill: 'reist', hint: 'Geen z voor de t: reist.' }] },
              { label: 'geven', cells: [{ fill: 'geef' }, { fill: 'geeft' }] },
              { label: 'lezen', cells: [{ fill: 'lees' }, { fill: 'leest' }] },
              { label: 'verhuizen', cells: [{ fill: 'verhuis' }, { fill: 'verhuist' }] },
            ],
            extra: ['leev', 'reiz', 'geevt', 'leezt', 'verhuiz'],
            note: 'ik leef, hij leeft; ik reis, hij reist. Aan het eind en vóór de t: altijd s of f.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'z-of-s',
      prompt: 'Krijgt het meervoud een z of een s?',
      buckets: ['meervoud met z', 'meervoud met s'],
      items: [
        { t: 'laars', b: 0 },
        { t: 'kaars', b: 1 },
        { t: 'saus', b: 0 },
        { t: 'paus', b: 1 },
        { t: 'sluis', b: 0 },
        { t: 'kruis', b: 1 },
        { t: 'beurs', b: 0 },
        { t: 'koers', b: 1 },
        { t: 'lens', b: 0 },
        { t: 'wens', b: 1 },
        { t: 'hals', b: 0 },
        { t: 'pols', b: 1 },
        { t: 'glas', b: 0 },
        { t: 'eis', b: 1 },
      ],
      why: 'Met z: laarzen, sauzen, sluizen, beurzen, lenzen, halzen, glazen. Met s: kaarsen, pausen, kruisen, koersen, wensen, polsen, eisen. Paren als laars en kaars, of saus en paus, klinken hetzelfde: leer het meervoud mee. En glas wordt glazen: een lange a en een z.',
    },
    {
      kind: 'type',
      id: 'tarieven',
      prompt: 'Typ het meervoud van tarief.',
      before: 'De',
      after: 'voor gas en stroom gaan in januari omhoog.',
      hint: '',
      answer: 'tarieven',
      why: 'tarief → tarieven: in het meervoud hoor je een v. Na ie wordt de v niet dubbel. Zo ook archief → archieven.',
    },
    {
      kind: 'choice',
      id: 'reis',
      prompt: 'Kies de goede vorm.',
      before: '',
      after: 'jij volgend jaar weer naar Marokko?',
      options: ['Reis', 'Reist', 'Reiz', 'Rijs'],
      answer: 'Reis',
      why: 'reizen → stam reis, met ei. Aan het eind staat nooit een z. En staat jij achter het werkwoord, dan komt er geen t: Reis jij?',
    },
    {
      kind: 'fix',
      id: 'serieuze',
      prompt: 'Tik het fout gespelde woord en verbeter het.',
      sentence: 'Na de klacht over de muizen stuurde de huisbaas een serieuse brief aan alle huurders.',
      wrong: 10,
      answer: 'serieuze',
      why: 'serieus + e: je hoort een z, dus serieuze. Net als nerveus → nerveuze. muizen, huisbaas en brief waren goed.',
    },
    {
      kind: 'sort',
      id: 'v-of-f',
      prompt: 'Krijgt het meervoud een v of een f?',
      buckets: ['meervoud met v', 'meervoud met f'],
      items: [
        { t: 'graf', b: 0 },
        { t: 'straf', b: 1 },
        { t: 'hof', b: 0 },
        { t: 'stof', b: 1 },
        { t: 'archief', b: 0 },
        { t: 'fotograaf', b: 1 },
        { t: 'schroef', b: 0 },
        { t: 'giraf', b: 1 },
        { t: 'zalf', b: 0 },
        { t: 'paragraaf', b: 1 },
        { t: 'proef', b: 0 },
        { t: 'klif', b: 1 },
        { t: 'korf', b: 0 },
        { t: 'biograaf', b: 1 },
      ],
      why: 'Met v: graven, hoven, archieven, schroeven, zalven, proeven, korven. Met f: straffen, stoffen, giraffen en kliffen (korte klank: ff), fotografen, paragrafen en biografen (je hoort een f). Let op graf en hof: een korte klank, maar het meervoud is graven en hoven, met een lange klank (één letter) en een v.',
    },
    {
      kind: 'bet',
      id: 'grenzen-wensen',
      prompt: 'Meervoud van grens en wens: welk rijtje is goed?',
      options: ['grenzen en wensen', 'grensen en wensen', 'grenzen en wenzen', 'grensen en wenzen'],
      answer: 'grenzen en wensen',
      why: 'grens → grenzen: je hoort een z. wens → wensen: je hoort een s. Na een n moet je het woord kennen: gans → ganzen, maar dans → dansen.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen en een stappenplan',
      panels: [
        {
          text: 'Ook midden in een woord schrijf je *s* en *f* als ze aan het eind van een deel staan, met een medeklinker erachter. Dat zie je bij het verkleinwoord: *huisje*, *briefje*, *doosje*, *neefje*. En in samenstellingen: elk deel houdt de vorm die het los heeft. *huis* + *deur* = *huisdeur*, *kaas* + *boer* = *kaasboer*, *brief* + *papier* = *briefpapier*. Ook *liefde* schrijf je met *f*, al zeg je *lieve*. Vooraan in een woord of deel kan wel een *z* of *v* vóór een medeklinker staan: *zwart*, *vrij*.',
          rule: 'Aan het eind van een deel, vóór een medeklinker: *s* en *f*: *huisje*, *briefje*, *huisdeur*, *liefde*.',
          mark: {
            q: 'Tik de woorden met een s of f die in een andere vorm een z of v hebben',
            sentence: 'Ik schrijf een briefje aan mijn neef en leg het in een doosje bij de huisdeur.',
            targets: [1, 3, 6, 12, 15],
            note: 'schrijf (schrijven), briefje (brieven), neef (neven), doosje (dozen) en huisdeur (huizen). Aan het eind van een woord of van een deel: s of f.',
          },
        },
        {
          text: 'Veel bijvoeglijke naamwoorden krijgen met *-e* een *v* of *z*. Vooral woorden op *-ief* en *-eus*: *positief* → *positieve*, *actief* → *actieve*, *negatief* → *negatieve*, *serieus* → *serieuze*, *nerveus* → *nerveuze*. En ook *wijs* → *wijze*, *vies* → *vieze*, *grijs* → *grijze*. Maar let op: *fris* → *frisse*, *los* → *losse* (korte klank: dubbel), *vals* → *valse*, *Duits* → *Duitse*.',
          rule: '*-ief* wordt *-ieve*, *-eus* wordt *-euze*: *positieve*, *serieuze*.',
          quiz: {
            q: 'Ik heb een … ervaring gehad.',
            options: ['positieve', 'positiefe', 'positiev'],
            answer: 'positieve',
            why: 'positief + e: je hoort een v, dus positieve. Net als actieve en negatieve.',
          },
        },
        {
          text: 'Een veelgemaakte fout is een *v* of *z* in een werkwoord met *t*: *hij leevt*, *zij reizt*. Aan het eind en vóór de *t* van *hij*, *zij* en *jij* staat nooit een *v* of *z*: *hij leeft*, *zij reist*, *jij leest*, *het vriest*, *zij kiest*. Ook in een vraag: *Leef jij gezond?*, *Reis jij vaak?*',
          rule: 'Vóór de *t*: *ft* en *st*, nooit *vt* of *zt*: *hij leeft*, *zij reist*.',
          build: {
            before: 'Mijn oma',
            stem: 'lee',
            endings: ['ft', 'vt', 'fft', 'ven'],
            answer: 'ft',
            note: 'leven → stam leef + t: leeft. Een v vóór de t bestaat niet.',
          },
        },
        {
          text: 'Twijfel je? Loop dit stappenplan af. 1. Staat de letter aan het eind van het woord, of aan het eind van een deel met een medeklinker erachter (*huisje*, *hij leeft*)? Dan altijd *s* of *f*. 2. Komt er een klinker achter (meervoud, *-e*, *wij*-vorm, hele werkwoord)? Luister: hoor je een *z* of *v*, schrijf die dan. 3. Na een korte klank wordt het *ss* of *ff*: *vissen*, *straffen*, *bussen*. Een dubbele *z* of *v* zie je bijna nooit, alleen in een paar leenwoorden zoals *pizza*. 4. Twijfel je bij het meervoud tussen *s* en *z*? Zoek het op en leer het meervoud mee.',
          rule: 'Eind van een woord of deel: *s*/*f*. Klinker erachter: luister. Korte klank: *ss*/*ff*.',
          quiz: {
            q: 'Wat is het meervoud van bus?',
            options: ['bussen', 'buzen', 'buzzen'],
            answer: 'bussen',
            why: 'Korte u: de s wordt dubbel. Een dubbele z zie je bijna nooit, alleen in een paar leenwoorden zoals pizza.',
          },
        },
      ],
    },
    {
      kind: 'swipe',
      id: 'goed-of-fout',
      prompt: 'Is de zin goed gespeld?',
      intro: 'Veeg naar rechts als de zin goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'Mijn zus verhuist volgende week naar Gent.', ok: true, why: 'verhuizen → stam verhuis + t: verhuist. Vóór de t nooit een z.' },
        { t: 'Wij verhuisen in het voorjaar.', ok: false, fix: 'verhuizen', why: 'Het hele werkwoord: je hoort een z, dus verhuizen.' },
        { t: 'Op tafel staan twaalf glazen en zes borden.', ok: true, why: 'glas → glazen: in het meervoud een lange a (één letter) en een z.' },
        { t: 'Hij draagt altijd een grijse jas.', ok: false, fix: 'grijze', why: 'grijs + e: je hoort een z, dus grijze.' },
        { t: 'De huisbazen willen de huur verhogen.', ok: true, why: 'huis + baas: huis blijft huis, baas wordt bazen. Dus huisbazen.' },
        { t: 'Het vriezt vannacht zeker vijf graden.', ok: false, fix: 'vriest', why: 'vriezen → stam vries + t: vriest. Vóór de t nooit een z.' },
        { t: 'In het archief liggen nog veel oude brieven.', ok: true, why: 'archief: aan het eind een f. brieven: met -en hoor je een v.' },
        { t: 'Mijn buurman verfd zijn schuur.', ok: false, fix: 'verft', why: 'verven → stam verf. Bij hij komt er een t achter: verft.' },
        { t: 'Ze was erg nerveus voor haar eerste werkdag.', ok: true, why: 'Aan het eind een s. Pas met -e wordt het een z: een nerveuze vrouw.' },
        { t: 'Onze dove buurvrouw hoorde de brandweer niet.', ok: true, why: 'doof + e: je hoort een v, dus dove.' },
        { t: 'Het was een negatiefe ervaring.', ok: false, fix: 'negatieve', why: '-ief + e wordt -ieve: negatieve.' },
        { t: 'Ik geloof dat de prijsen weer stijgen.', ok: false, fix: 'prijzen', why: 'prijs → prijzen: in het meervoud hoor je een z. geloof was goed.' },
        { t: 'Kies jij vanavond de film?', ok: true, why: 'kiezen → stam kies. Staat jij achter het werkwoord, dan komt er geen t: Kies jij?' },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-verhuizing',
      prompt: 'Kijk de mail na en verbeter elke fout.',
      intro: 'Let op s en z, f en v.',
      header: { to: 'Mark', subject: 'Ik ga verhuizen' },
      greeting: 'Beste Mark,',
      tokens: [
        { t: 'Volgende' },
        { t: 'maand' },
        { t: 'verhuiz', fix: 'verhuis', why: 'De stam van verhuizen eindigt op s: ik verhuis.' },
        { t: 'ik' },
        { t: 'naar' },
        { t: 'Utrecht.' },
        { t: 'Mijn' },
        { t: 'nieuwe' },
        { t: 'huis' },
        { t: 'is' },
        { t: 'klein,' },
        { t: 'maar' },
        { t: 'de' },
        { t: 'prijsen', fix: 'prijzen', why: 'prijs → prijzen: in het meervoud hoor je een z.' },
        { t: 'zijn' },
        { t: 'daar' },
        { t: 'niet' },
        { t: 'zo' },
        { t: 'hoog.' },
        { t: 'Mijn' },
        { t: 'twee' },
        { t: 'neeven', fix: 'neven', why: 'neef → neven: open lettergreep, dus één e, en een v.' },
        { t: 'helpen' },
        { t: 'mee' },
        { t: 'met' },
        { t: 'de' },
        { t: 'dozen.' },
        { t: 'Ik' },
        { t: 'leev', fix: 'leef', why: 'leven → ik leef: aan het eind nooit een v.' },
        { t: 'graag' },
        { t: 'rustig,' },
        { t: 'dus' },
        { t: 'dat' },
        { t: 'past' },
        { t: 'goed.' },
        { t: 'Ik' },
        { t: 'geloov', fix: 'geloof', why: 'geloven → ik geloof: aan het eind een f.' },
        { t: 'dat' },
        { t: 'het' },
        { t: 'een' },
        { t: 'mooie' },
        { t: 'tijd' },
        { t: 'wordt.' },
        { t: 'Ik' },
        { t: 'stuur' },
        { t: 'je' },
        { t: 'nog' },
        { t: 'een' },
        { t: 'briefje' },
        { t: 'met' },
        { t: 'mijn' },
        { t: 'adres.' },
        { t: 'Lieve' },
        { t: 'groet,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Alles gevonden',
        text: 'verhuis, prijzen, neven, leef en geloof. dozen, briefje en Lieve waren al goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ de zin.',
      sentence: 'Mijn nerveuze neef gelooft dat de prijzen van de huizen in onze wijk nog verder stijgen.',
      right: 'Goed: nerveuze, prijzen en huizen met z, neef met f aan het eind, en gelooft met ft.',
      wrong:
        'Let op: nerveuze (met -e hoor je een z), neef (aan het eind f), gelooft (vóór de t een f), prijzen en huizen (in het meervoud hoor je een z) en wijk (met ij).',
    },
    {
      kind: 'type',
      id: 'halve',
      prompt: 'Typ de vorm van half die hier past.',
      before: 'Sinds de operatie werk ik',
      after: 'dagen.',
      hint: '',
      answer: 'halve',
      why: 'half + e: na de l hoor je een v, dus halve. Net als wolf → wolven.',
    },
    {
      kind: 'rewrite',
      id: 'meervoud',
      prompt: 'Zet neef en brief in het meervoud en pas het werkwoord aan.',
      source: 'Mijn neef leest de brief van de gemeente.',
      accept: ['Mijn neven lezen de brieven van de gemeente.'],
      why: 'neef → neven, brief → brieven, en bij een meervoud hoort lezen. Komt er -en achter, dan hoor je de v en de z weer.',
    },
    {
      kind: 'type',
      id: 'kiest',
      prompt: 'Typ de goede vorm van kiezen.',
      before: 'Welke sport',
      after: 'jouw dochter volgend jaar?',
      hint: '',
      answer: 'kiest',
      why: 'kiezen → stam kies + t: kiest. Jouw dochter is geen jij, dus de t blijft, ook in een vraag. Vóór de t nooit een z.',
    },
    {
      kind: 'choice',
      id: 'durft',
      prompt: 'Kies de goede vorm.',
      before: 'Mijn zoon',
      after: 'niet alleen in het donker te fietsen.',
      options: ['durft', 'durfd', 'durvt', 'durf'],
      answer: 'durft',
      why: 'durven → stam durf + t: durft. Vóór de t nooit een v, en bij hij hoort een t, geen d.',
    },
    {
      kind: 'bet',
      id: 'reist-reizen',
      prompt: 'Welke zin is goed gespeld?',
      options: [
        'Zij reist graag, maar haar ouders reizen nooit.',
        'Zij reisd graag, maar haar ouders reizen nooit.',
        'Zij reizt graag, maar haar ouders reizen nooit.',
        'Zij reist graag, maar haar ouders reisen nooit.',
      ],
      answer: 'Zij reist graag, maar haar ouders reizen nooit.',
      why: 'zij reist: stam reis + t, vóór de t nooit een z. haar ouders reizen: het hele werkwoord, en daar hoor je de z.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Zevenentwintig opdrachten door elkaar, ook uit eerdere lessen. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Meervoud van *prijs*',
          before: 'De',
          after: 'in deze supermarkt zijn flink gestegen.',
          a: 'prijzen',
          why: 'prijs → prijzen: in het meervoud hoor je een z.',
        },
        {
          q: 'Vorm van *vinden* (nu)',
          before: 'Hoe',
          after: 'jij de nieuwe buurt?',
          a: 'vind',
          why: 'vinden → stam vind. Staat jij achter het werkwoord, dan komt er geen t.',
        },
        {
          q: 'Meervoud van *eis*',
          before: 'De huurders sturen een lijst met',
          after: 'naar de huisbaas.',
          a: 'eisen',
          why: 'eis → eisen: je hoort een s, net als kruis → kruisen.',
        },
        {
          q: 'Vorm van *vriezen*',
          before: 'Volgens het weerbericht',
          after: 'het vannacht vijf graden.',
          a: 'vriest',
          why: 'vriezen → stam vries + t: vriest. Vóór de t nooit een z.',
        },
        { q: 'Meervoud van *laars*', before: 'Mijn', after: 'lekken.', a: 'laarzen', why: 'laars → laarzen, met z. Maar kaars → kaarsen.' },
        {
          q: 'Zelfstandig naamwoord van *gezond*',
          before: 'Roken is slecht voor je',
          after: '.',
          a: 'gezondheid',
          why: 'gezonde, dus d. Met -heid blijft de d: gezondheid.',
        },
        {
          q: 'Vul *vies* in, in de goede vorm',
          before: 'Wie heeft die',
          after: 'borden in de gootsteen gezet?',
          a: 'vieze',
          why: 'vies + e: je hoort een z, dus vieze.',
        },
        {
          q: 'Meervoud van *kaars*',
          before: 'Bij een stroomstoring heb je',
          after: 'nodig.',
          a: 'kaarsen',
          why: 'kaars → kaarsen, met s. Maar laars → laarzen.',
        },
        {
          q: 'Vorm van *durven* (nu)',
          before: 'Waarom',
          after: 'jij de buurman niet te bellen?',
          a: 'durf',
          why: 'durven → stam durf. Staat jij achter het werkwoord, dan komt er geen t.',
        },
        { q: 'Vorm van *liggen* (nu)', before: 'De sleutel', after: 'onder de mat.', a: 'ligt', why: 'liggen → stam lig + t: ligt. Met g, niet ch.' },
        {
          q: 'Meervoud van *graf*',
          before: 'Op de oude begraafplaats liggen honderden',
          after: '.',
          a: 'graven',
          why: 'graf → graven: een lange a (één letter, open lettergreep) en een v.',
        },
        {
          q: 'Vul *serieus* in, in de goede vorm',
          before: 'De directeur noemt het een',
          after: 'zaak.',
          a: 'serieuze',
          why: '-eus + e wordt -euze: serieuze.',
        },
        { q: 'Meervoud van *idee*', before: 'Heeft u nog', after: 'voor het feest?', a: 'ideeën', why: 'idee + en: ideeën, met een trema op de e van -en.' },
        {
          q: 'Vorm van *verhuizen*',
          before: 'Mijn zus',
          after: 'volgende week naar Gent.',
          a: 'verhuist',
          why: 'verhuizen → stam verhuis + t: verhuist. Vóór de t nooit een z.',
        },
        {
          q: 'Meervoud van *sluis*',
          before: 'Nederland heeft honderden',
          after: 'om het water te regelen.',
          a: 'sluizen',
          why: 'sluis → sluizen, net als huis → huizen.',
        },
        { q: 'Het tegenovergestelde van *heet*', before: 'Het is buiten erg', after: '.', a: 'koud', why: 'Vóór de d schrijf je ou. En koude, dus d.' },
        { q: 'Verkleinwoord van *brief*', before: 'Ik leg een', after: 'op de keukentafel.', a: 'briefje', why: 'Vóór een medeklinker een f: briefje.' },
        { q: 'Vul *actief* in, in de goede vorm', before: 'De sportclub zoekt', after: 'vrijwilligers.', a: 'actieve', why: '-ief + e wordt -ieve: actieve.' },
        { q: 'Meervoud van *auto*', before: 'Er staan twee', after: 'voor de garage.', a: 'auto’s', why: 'auto eindigt op o: meervoud met ’s.' },
        { q: 'Vorm van *geloven* (nu)', before: 'Ik', after: 'er niets van.', a: 'geloof', why: 'geloven → stam geloof. Aan het eind nooit een v.' },
        {
          q: 'Meervoud van *huisbaas*',
          before: 'Veel',
          after: 'verhogen elk jaar de huur.',
          a: 'huisbazen',
          why: 'huis + baas: huis blijft huis, baas wordt bazen.',
        },
        {
          q: 'Zelfstandig naamwoord van *vrij*',
          before: 'In Nederland heb je',
          after: 'van godsdienst.',
          a: 'vrijheid',
          why: 'vrij met ij, -heid met ei: vrijheid.',
        },
        {
          q: 'Vul *fris* in, in de goede vorm',
          before: 'Zet het raam open voor wat',
          after: 'lucht.',
          a: 'frisse',
          why: 'fris + e: korte i, dus ss. Je hoort geen z.',
        },
        {
          q: 'Meervoud van *fotograaf*',
          before: 'Op de bruiloft waren twee',
          after: '.',
          a: 'fotografen',
          why: 'fotograaf → fotografen: je hoort een f, en één a in de open lettergreep.',
        },
        { q: 'Vul *nieuw* in, in de goede vorm', before: 'Wij zoeken een', after: 'huurder.', a: 'nieuwe', why: 'nieuw + e: nieuwe. De ieuw blijft staan.' },
        {
          q: 'Zelfstandig naamwoord bij *lief*',
          before: 'Ze zorgt met veel',
          after: 'voor haar moeder.',
          a: 'liefde',
          why: 'Vóór de d een f: liefde, al zeg je lieve.',
        },
        { q: 'Samenstelling van *tv* en *gids*', before: 'Waar ligt de', after: '?', a: 'tv-gids', why: 'Afkorting + woord: koppelteken.' },
      ],
      done: {
        title: 'Reeks klaar',
        text: 'Aan het eind van een woord of van een deel: s en f. Komt er een klinker achter, luister dan: z of v, of toch s of f.',
      },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail aan. Typ elk woord helemaal.',
      intro: 'Kijk goed naar de zin om het gat heen.',
      title: 'Mail aan de huisbaas',
      text: 'Beste meneer Smit,\n\nSinds een paar weken zitten er {muizen|meervoud van muis|muis → muizen: in het meervoud hoor je een z.} in onze kelder. Mijn vrouw {gelooft|geloven, nu|zij + stam geloof + t: gelooft. Vóór de t nooit een v.} dat ze via de oude {buizen|meervoud van buis|buis → buizen, net als huis → huizen.} naar binnen komen. Ze knagen ook aan de {dozen|meervoud van doos|doos → dozen: je hoort een z, en één o in de open lettergreep.} met onze spullen. Gisteren vond ik zelfs twee {dode|dood + e|dood → dode: je hoort een d.} muizen naast de wasmachine. Onze kinderen {durven|ik durf, zij …|Bij een meervoud hoort het hele werkwoord: durven, met v.} nu niet meer alleen naar beneden.\n\nIk heb u hierover al twee {brieven|meervoud van brief|brief → brieven: je hoort een v.} gestuurd, maar ik heb nog niets gehoord. Nu het ’s nachts {vriest|vriezen|vriezen → stam vries + t: vriest. Vóór de t nooit een z.}, komen de dieren steeds verder naar binnen. In de gang hangt een {vieze|vies|vies + e: je hoort een z, dus vieze.} lucht, en dat is niet {gezond|gezo__|gezonde, gezondheid: dus d.} voor ons gezin. Wij {leven|ik leef, wij …|Bij wij hoort het hele werkwoord: leven, met v.} hier al tien jaar met veel plezier en willen graag blijven.\n\nHeeft u {ideeën|meervoud van idee|idee + en: ideeën, met een trema.} om dit snel op te lossen? Mijn buurvrouw {zei|zeggen, verleden tijd|zeggen → zei, met ei. zij met ij is een persoon.} dat zij ook last heeft van muizen. De sleutel van de kelder {ligt|liggen, nu|liggen → stam lig + t: ligt. Met g.} bij haar, op nummer twaalf.\n\nIk leg vandaag ook een {briefje|verkleinwoord van brief|Vóór een medeklinker een f: briefje.} met mijn telefoonnummer bij u in de bus. Ik hoop op een {positieve|positief|-ief + e wordt -ieve: positieve.} reactie.\n\nMet vriendelijke groet,\nHasan',
      why: 'Aan het eind van een woord of van een deel schrijf je s en f: gelooft, vriest, briefje. Komt er een klinker achter, dan hoor je vaak een z of v: muizen, buizen, dozen, brieven, vieze, positieve, durven, leven. Daarnaast regels uit eerdere lessen: dode en gezond met d, ideeën met trema, zei met ei en ligt met g.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen. Hoofdletters en leestekens tellen mee.',
      title: 'Bericht in de buurtapp',
      sentences: [
        'Beste buren, zaterdag verhuist onze familie naar een groter huis in Zwolle.',
        'Wilt u niet parkeren op de plek waar de verhuiswagen staat?',
        'Onze nerveuze hond is bang voor herrie en blijft die dag bij mijn neef.',
        'Wij beloven dat er geen vieze dozen of oude kasten op de stoep blijven staan.',
        'Alle helpers krijgen van ons een stuk taart en een glas frisse limonade.',
        'We wonen hier al jaren en geloven niet dat we ooit zulke lieve buren vinden.',
      ],
      right: 'Alles goed: verhuist, huis, verhuiswagen, neef en glas met s of f, en nerveuze, vieze, dozen, beloven, geloven en lieve met z of v.',
      wrong:
        'Kijk na: aan het eind van een woord of van een deel s of f (verhuist, huis, verhuiswagen, neef, glas). Met een klinker erachter vaak z of v (nerveuze, vieze, dozen, beloven, geloven, lieve). frisse heeft ss na de korte i. En zaterdag schrijf je klein.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail van school na voordat hij naar de ouders gaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'ouders van groep 6', subject: 'Schoolreis op vrijdag' },
      greeting: 'Beste ouders,',
      signoff: 'Met vriendelijke groet,\njuf Sanne',
      tokens: [
        { t: 'Vrijdag' },
        { t: 'gaat' },
        { t: 'groep' },
        { t: 'zes' },
        { t: 'op' },
        { t: 'schoolreis' },
        { t: 'naar' },
        { t: 'het' },
        { t: 'bos.' },
        { t: 'Het' },
        { t: 'vriezt', fix: 'vriest', why: 'vriezen → stam vries + t: vriest. Vóór de t nooit een z.' },
        { t: '’s' },
        { t: 'ochtends' },
        { t: 'nog,' },
        { t: 'dus' },
        { t: 'geef' },
        { t: 'uw' },
        { t: 'kind' },
        { t: 'warme' },
        { t: 'kousen', trap: 'Goed: kous → kousen. Hier hoor je een s, geen z.' },
        { t: 'en' },
        { t: 'laarsen', fix: 'laarzen', why: 'laars → laarzen: in het meervoud hoor je een z.' },
        { t: 'mee.' },
        { t: 'Glazen', trap: 'Goed: flessen van glas zijn glazen flessen. Met -en erachter hoor je een z, net als in het meervoud glazen.' },
        { t: 'flessen' },
        { t: 'mogen' },
        { t: 'niet' },
        { t: 'mee' },
        { t: 'in' },
        { t: 'de' },
        { t: 'bus.' },
        { t: 'Sommige' },
        { t: 'kinderen' },
        { t: 'zijn' },
        { t: 'nerveus', trap: 'Goed: aan het eind een s. Pas met -e wordt het een z: nerveuze kinderen.' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'lange' },
        { t: 'rit.' },
        { t: 'Praat' },
        { t: 'er' },
        { t: 'thuis' },
        { t: 'rustig' },
        { t: 'over,' },
        { t: 'dan' },
        { t: 'geloov', fix: 'geloof', why: 'geloven → stam geloof. Aan het eind nooit een v.' },
        { t: 'ik' },
        { t: 'dat' },
        { t: 'het' },
        { t: 'goed' },
        { t: 'gaat.' },
        { t: 'Wij' },
        { t: 'rijzen', fix: 'reizen', why: 'reizen (op reis gaan) schrijf je met ei. rijzen met ij betekent omhoog gaan, zoals deeg.' },
        { t: 'met' },
        { t: 'twee' },
        { t: 'bussen' },
        { t: 'en' },
        { t: 'zijn' },
        { t: 'om' },
        { t: 'vier' },
        { t: 'uur' },
        { t: 'terug.' },
        { t: 'Een' },
        { t: 'boswachter' },
        { t: 'geevt', fix: 'geeft', why: 'geven → stam geef + t: geeft. Vóór de t nooit een v.' },
        { t: 'de' },
        { t: 'kinderen' },
        { t: 'een' },
        { t: 'halfe', fix: 'halve', why: 'half + e: je hoort een v, dus halve.' },
        { t: 'dag' },
        { t: 'les.' },
        { t: 'Het' },
        { t: 'wordt' },
        { t: 'een' },
        { t: 'actiefe', fix: 'actieve', why: '-ief + e wordt -ieve: actieve.' },
        { t: 'dag,' },
        { t: 'dus' },
        { t: 'geef' },
        { t: 'genoeg' },
        { t: 'water' },
        { t: 'mee.' },
        { t: 'Zorg' },
        { t: 'ook' },
        { t: 'voor' },
        { t: 'een' },
        { t: 'gezont', fix: 'gezond', why: 'gezonde, gezondheid: dus d.' },
        { t: 'lunchpakket.' },
        { t: 'Elk' },
        { t: 'kind' },
        { t: 'krijgt', trap: 'Goed: krijgen → stam krijg + t: krijgt. Met g, niet ch.' },
        { t: 'een' },
        { t: 'briefje' },
        { t: 'met' },
        { t: 'het' },
        { t: 'nummer' },
        { t: 'van' },
        { t: 'de' },
        { t: 'school.' },
        { t: 'Na' },
        { t: 'afloop' },
        { t: 'gaan' },
        { t: 'viese', fix: 'vieze', why: 'vies + e: je hoort een z, dus vieze.' },
        { t: 'kleren' },
        { t: 'in' },
        { t: 'een' },
        { t: 'aparte' },
        { t: 'tas' },
        { t: 'mee' },
        { t: 'naar' },
        { t: 'huis.' },
      ],
      done: {
        title: 'Nagekeken',
        text: 'De fouten: vriest, laarzen, geloof, reizen, geeft, halve, actieve, gezond en vieze. kousen, Glazen, nerveus en krijgt waren goed.',
      },
    },
  ],
};
