import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": s of z en f of v, aan het begin, aan het eind en in langere vormen. */
export const LES_K36: LessonInput = {
  id: 'k36',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 's of z, f of v',
  skill: 'Spelling',
  icon: 's/z',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Nooit een z of v aan het eind',
      panels: [
        {
          text: 'Aan het begin van een woord moet je het woord kennen. Met *z*: *zee*, *zon*, *zout*, *zaterdag*, *zeep*. Met *s*: *soep*, *suiker*, *slapen*, *september*. Met *v*: *vader*, *vis*, *veel*, *vrij*, *vlees*. Met *f*: *fiets*, *feest*, *fout*, *fijn*, *film*. Maar aan het eind van een woord is het simpel: daar staat nooit een *z* of een *v* (alleen in een paar leenwoorden, zoals *quiz*). Daar schrijf je altijd *s* of *f*: *huis*, *kaas*, *reis*, *brief*, *lief*, *neef*.',
          rule: 'Aan het eind van een woord: nooit *z* of *v*, altijd *s* of *f*: *huis*, *brief*.',
          quiz: {
            q: 'Welke spelling is goed?',
            options: ['de brief', 'de briev', 'de brieff'],
            answer: 'de brief',
            why: 'Aan het eind van een woord staat nooit een v. En na ie komt geen dubbele f.',
          },
        },
        {
          text: 'Maak je het woord langer, dan hoor je soms een *z* of een *v*. Die schrijf je dan ook: *huis* → *huizen*, *kaas* → *kazen*, *prijs* → *prijzen*, *reis* → *reizen*, *brief* → *brieven*, *neef* → *neven*, *wolf* → *wolven*. Dat geldt ook voor een bijvoeglijk naamwoord met *-e*: *lief* → *lieve*, *boos* → *boze*, *grijs* → *grijze*, *doof* → *dove*, *half* → *halve*.',
          rule: 'Hoor je in het langere woord een *z* of *v*? Schrijf dan *z* of *v*: *huizen*, *brieven*, *lieve*.',
          paradigm: {
            q: 'Zet de langere vorm in het vakje',
            cols: ['langere vorm'],
            rows: [
              { label: 'huis (meervoud)', cells: [{ fill: 'huizen', hint: 'Je hoort een z: huizen.' }] },
              { label: 'muis (meervoud)', cells: [{ fill: 'muizen', hint: 'Net als huis: muizen.' }] },
              { label: 'brief (meervoud)', cells: [{ fill: 'brieven', hint: 'Je hoort een v: brieven.' }] },
              { label: 'wolf (meervoud)', cells: [{ fill: 'wolven', hint: 'Na de l hoor je een v: wolven.' }] },
              { label: 'boos (de … buurman)', cells: [{ fill: 'boze', hint: 'Open lettergreep: één o, en een z.' }] },
            ],
            extra: ['huisen', 'muisen', 'brieffen', 'wolfen', 'boosse'],
            note: 'huizen, muizen, brieven, wolven en boze. Aan het eind s of f, met een klinker erachter komt de z of v terug.',
          },
        },
        {
          text: 'Maar niet elk woord krijgt een *z* of *v*. Hoor je in het langere woord een *s* of *f*, dan blijft het *s* of *f*: *kous* → *kousen*, *dans* → *dansen*, *mens* → *mensen*, *kruis* → *kruisen*, *eis* → *eisen*, *fotograaf* → *fotografen*. Aan het korte woord zie je dat niet: *huis* wordt *huizen*, maar *kruis* wordt *kruisen*. Leer daarom het meervoud mee. En na een korte klank wordt de *s* of *f* dubbel: *vis* → *vissen*, *bus* → *bussen*, *straf* → *straffen*.',
          rule: 'Hoor je *s* of *f* in het langere woord? Dan blijft het *s* of *f*. Na een korte klank: *ss* of *ff*.',
          lab: {
            label: 'Tik een woord en zie het meervoud',
            chips: [
              { k: 'huis', out: 'huizen', note: 'Met z.' },
              { k: 'kruis', out: 'kruisen', note: 'Zelfde klank als huis, maar met s. Leer het meervoud mee.' },
              { k: 'reis', out: 'reizen', note: 'Met z.' },
              { k: 'eis', out: 'eisen', note: 'Met s, net als kruis.' },
              { k: 'gans', out: 'ganzen', note: 'Na de n een z.' },
              { k: 'dans', out: 'dansen', note: 'Ook na de n, maar nu met s.' },
            ],
          },
        },
        {
          text: 'Bij werkwoorden geldt hetzelfde. Haal *-en* van het hele werkwoord af, dan staat de *z* of *v* aan het eind. Die wordt *s* of *f*: *leven* → *ik leef*, *reizen* → *ik reis*, *geloven* → *ik geloof*, *verhuizen* → *ik verhuis*, *lezen* → *ik lees*, *geven* → *ik geef*. Komt er een *t* achter, dan blijft het *s* of *f*: *hij leeft*, *zij reist*, *het vriest*. Bij *wij* hoor je de *z* of *v* weer: *wij leven*, *wij reizen*.',
          rule: 'Stam van een werkwoord: *s* en *f*, ook met *t*: *ik leef*, *hij leeft*, *zij reist*.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik', 'hij'],
            rows: [
              { label: 'leven', cells: [{ fill: 'leef' }, { fill: 'leeft', hint: 'Geen v voor de t: leeft.' }] },
              { label: 'reizen', cells: [{ fill: 'reis' }, { fill: 'reist', hint: 'Geen z voor de t: reist.' }] },
              { label: 'geven', cells: [{ fill: 'geef' }, { fill: 'geeft' }] },
              { label: 'lezen', cells: [{ fill: 'lees' }, { fill: 'leest' }] },
              { label: 'verhuizen', cells: [{ fill: 'verhuis' }, { fill: 'verhuist' }] },
            ],
            extra: ['leev', 'reiz', 'geevt', 'leezt', 'verhuiz'],
            note: 'ik leef, hij leeft; ik reis, hij reist. Aan het eind en vóór de t: altijd s of f.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'z-of-s',
      prompt: 'Krijgt het meervoud een z of een s?',
      buckets: ['meervoud met z', 'meervoud met s'],
      items: [
        { t: 'kaas', b: 0 },
        { t: 'kous', b: 1 },
        { t: 'huis', b: 0 },
        { t: 'kruis', b: 1 },
        { t: 'roos', b: 0 },
        { t: 'dans', b: 1 },
        { t: 'neus', b: 0 },
        { t: 'mens', b: 1 },
        { t: 'gans', b: 0 },
        { t: 'kaars', b: 1 },
        { t: 'reus', b: 0 },
        { t: 'eis', b: 1 },
      ],
      why: 'Met z: kazen, huizen, rozen, neuzen, ganzen, reuzen. Met s: kousen, kruisen, dansen, mensen, kaarsen, eisen. Aan het enkelvoud zie je het niet: leer het meervoud mee.',
    },
    {
      kind: 'type',
      id: 'brieven',
      prompt: 'Typ het meervoud van brief.',
      before: 'Ik heb vandaag drie',
      after: 'gekregen.',
      hint: 'brief…',
      answer: 'brieven',
      why: 'In het meervoud hoor je een v: brieven. Aan het eind van het woord blijft het brief.',
    },
    {
      kind: 'choice',
      id: 'reis',
      prompt: 'Kies de goede vorm.',
      before: 'Ik',
      after: 'elk jaar naar Marokko.',
      options: ['reis', 'reiz', 'reist'],
      answer: 'reis',
      why: 'reizen → stam reis. Aan het eind staat nooit een z. En bij ik komt er geen t achter.',
    },
    {
      kind: 'fix',
      id: 'lieve',
      prompt: 'Tik het fout gespelde woord en verbeter het.',
      sentence: 'Wat een lieffe hond heb jij!',
      wrong: 2,
      answer: 'lieve',
      why: 'lief + e: je hoort een v, dus lieve. Na ie wordt een medeklinker nooit dubbel.',
    },
    {
      kind: 'sort',
      id: 'v-of-f',
      prompt: 'Krijgt het meervoud een v of een f?',
      buckets: ['meervoud met v', 'meervoud met f'],
      items: [
        { t: 'wolf', b: 0 },
        { t: 'brief', b: 0 },
        { t: 'straf', b: 1 },
        { t: 'duif', b: 0 },
        { t: 'giraf', b: 1 },
        { t: 'druif', b: 0 },
        { t: 'fotograaf', b: 1 },
        { t: 'neef', b: 0 },
        { t: 'dief', b: 0 },
        { t: 'paragraaf', b: 1 },
      ],
      why: 'Met v: wolven, brieven, duiven, druiven, neven, dieven. Met f: straffen en giraffen (korte klank: ff), fotografen en paragrafen (je hoort een f).',
    },
    {
      kind: 'bet',
      id: 'grenzen',
      prompt: 'Wat is het meervoud van grens?',
      options: ['grenzen', 'grensen', 'grenssen'],
      answer: 'grenzen',
      why: 'In het meervoud hoor je een z: grenzen. Net als gans → ganzen. Maar dans → dansen: na een n moet je het woord kennen.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen en een stappenplan',
      panels: [
        {
          text: 'Ook midden in een woord, vóór een medeklinker, schrijf je *s* en *f*. Dat zie je bij het verkleinwoord: *huisje*, *briefje*, *doosje*, *neefje*. En in samenstellingen: elk deel houdt de vorm die het los heeft. *huis* + *deur* = *huisdeur*, *kaas* + *boer* = *kaasboer*, *brief* + *papier* = *briefpapier*. Ook *liefde* schrijf je met *f*, al zeg je *lieve*.',
          rule: 'Vóór een medeklinker: *s* en *f*: *huisje*, *briefje*, *huisdeur*, *liefde*.',
          mark: {
            q: 'Tik de woorden met een s of f die in een andere vorm een z of v hebben',
            sentence: 'Ik schrijf een briefje aan mijn neef en leg het in een doosje bij de huisdeur.',
            targets: [1, 3, 6, 12, 15],
            note: 'schrijf (schrijven), briefje (brieven), neef (neven), doosje (dozen) en huisdeur (huizen). Aan het eind en vóór een medeklinker: s of f.',
          },
        },
        {
          text: 'Veel bijvoeglijke naamwoorden krijgen met *-e* een *v* of *z*. Vooral woorden op *-ief* en *-eus*: *positief* → *positieve*, *actief* → *actieve*, *negatief* → *negatieve*, *serieus* → *serieuze*, *nerveus* → *nerveuze*. En ook *wijs* → *wijze*, *vies* → *vieze*, *grijs* → *grijze*. Maar let op: *fris* → *frisse*, *los* → *losse* (korte klank: dubbel), *vals* → *valse*, *Duits* → *Duitse*.',
          rule: '*-ief* wordt *-ieve*, *-eus* wordt *-euze*: *positieve*, *serieuze*.',
          quiz: {
            q: 'Ik heb een … ervaring gehad.',
            options: ['positieve', 'positiefe', 'positiev'],
            answer: 'positieve',
            why: 'positief + e: je hoort een v, dus positieve. Net als actieve en negatieve.',
          },
        },
        {
          text: 'Een veelgemaakte fout is een *v* of *z* in een werkwoord met *t*: *hij leevt*, *zij reizt*. Aan het eind en vóór de *t* van *hij*, *zij* en *jij* staat nooit een *v* of *z*: *hij leeft*, *zij reist*, *jij leest*, *het vriest*, *zij kiest*. Ook in een vraag: *Leef jij gezond?*, *Reis jij vaak?*',
          rule: 'Vóór de *t*: *ft* en *st*, nooit *vt* of *zt*: *hij leeft*, *zij reist*.',
          build: {
            before: 'Mijn oma',
            stem: 'lee',
            endings: ['ft', 'vt', 'fft', 'ven'],
            answer: 'ft',
            note: 'leven → stam leef + t: leeft. Een v vóór de t bestaat niet.',
          },
        },
        {
          text: 'Twijfel je? Loop dit stappenplan af. 1. Staat de letter aan het eind of vóór een medeklinker? Dan altijd *s* of *f*. 2. Komt er een klinker achter (meervoud, *-e*, *wij*-vorm, hele werkwoord)? Luister: hoor je een *z* of *v*, schrijf die dan. 3. Na een korte klank wordt het *ss* of *ff*: *vissen*, *straffen*, *bussen*. Een dubbele *z* of *v* bestaat in Nederlandse woorden niet. 4. Twijfel je bij het meervoud tussen *s* en *z*? Zoek het op en leer het meervoud mee.',
          rule: 'Eind of vóór een medeklinker: *s*/*f*. Klinker erachter: luister. Korte klank: *ss*/*ff*.',
          quiz: {
            q: 'Wat is het meervoud van bus?',
            options: ['bussen', 'buzen', 'buzzen'],
            answer: 'bussen',
            why: 'Korte u: de s wordt dubbel. Een dubbele z komt in Nederlandse woorden niet voor.',
          },
        },
      ],
    },
    {
      kind: 'swipe',
      id: 'goed-of-fout',
      prompt: 'Is de zin goed gespeld?',
      intro: 'Veeg naar rechts als de zin goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'Wij gaan volgende week verhuizen.', ok: true, why: 'Het hele werkwoord: je hoort de z.' },
        { t: 'Ik verhuiz naar Utrecht.', ok: false, fix: 'verhuis', why: 'De stam eindigt nooit op z: ik verhuis.' },
        { t: 'Op de markt liggen veel kazen.', ok: true, why: 'kaas → kazen: met z en één a.' },
        { t: 'Zij leevt heel gezond.', ok: false, fix: 'leeft', why: 'Vóór de t staat nooit een v: zij leeft.' },
        { t: 'Ik heb twee lieve neven.', ok: true, why: 'lief → lieve, neef → neven.' },
        { t: 'Ik heb een briev van de gemeente gekregen.', ok: false, fix: 'brief', why: 'Aan het eind staat nooit een v.' },
        { t: 'Er zitten muisen in de schuur.', ok: false, fix: 'muizen', why: 'muis → muizen: je hoort een z.' },
        { t: 'Hij was erg nerveus voor zijn examen.', ok: true, why: 'Aan het eind: s. Met -e zou het nerveuze zijn.' },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-verhuizing',
      prompt: 'Vind de vijf fouten in de mail en verbeter ze.',
      intro: 'Let op s en z, f en v.',
      header: { to: 'Mark', subject: 'Ik ga verhuizen' },
      tokens: [
        { t: 'Beste' },
        { t: 'Mark,' },
        { t: 'Volgende' },
        { t: 'maand' },
        { t: 'verhuiz', fix: 'verhuis', why: 'De stam van verhuizen eindigt op s: ik verhuis.' },
        { t: 'ik' },
        { t: 'naar' },
        { t: 'Utrecht.' },
        { t: 'Mijn' },
        { t: 'nieuwe' },
        { t: 'huis' },
        { t: 'is' },
        { t: 'klein,' },
        { t: 'maar' },
        { t: 'de' },
        { t: 'prijsen', fix: 'prijzen', why: 'prijs → prijzen: in het meervoud hoor je een z.' },
        { t: 'zijn' },
        { t: 'daar' },
        { t: 'niet' },
        { t: 'zo' },
        { t: 'hoog.' },
        { t: 'Mijn' },
        { t: 'twee' },
        { t: 'neeven', fix: 'neven', why: 'neef → neven: open lettergreep, dus één e, en een v.' },
        { t: 'helpen' },
        { t: 'mee' },
        { t: 'met' },
        { t: 'de' },
        { t: 'dozen.' },
        { t: 'Ik' },
        { t: 'leev', fix: 'leef', why: 'leven → ik leef: aan het eind nooit een v.' },
        { t: 'graag' },
        { t: 'rustig,' },
        { t: 'dus' },
        { t: 'dat' },
        { t: 'past' },
        { t: 'goed.' },
        { t: 'Ik' },
        { t: 'geloov', fix: 'geloof', why: 'geloven → ik geloof: aan het eind een f.' },
        { t: 'dat' },
        { t: 'het' },
        { t: 'een' },
        { t: 'mooie' },
        { t: 'tijd' },
        { t: 'wordt.' },
        { t: 'Ik' },
        { t: 'stuur' },
        { t: 'je' },
        { t: 'nog' },
        { t: 'een' },
        { t: 'briefje' },
        { t: 'met' },
        { t: 'mijn' },
        { t: 'adres.' },
        { t: 'Lieve' },
        { t: 'groet,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Alle vijf gevonden',
        text: 'verhuis, prijzen, neven, leef en geloof. dozen, briefje en Lieve waren al goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ de zin.',
      sentence: 'Mijn neef reist elke week met de bus naar zijn lieve oma.',
      right: 'Goed: neef met f aan het eind, reist met st, bus met één s en lieve met v.',
      wrong: 'Let op: neef (aan het eind f), reist (vóór de t een s), bus (één s aan het eind) en lieve (met -e hoor je de v).',
    },
    {
      kind: 'type',
      id: 'boze',
      prompt: 'Typ de vorm van boos die hier past.',
      before: 'De',
      after: 'buurman belde aan.',
      hint: 'bo…',
      answer: 'boze',
      why: 'boos + e: je hoort een z, en in de open lettergreep is één o genoeg: boze.',
    },
    {
      kind: 'rewrite',
      id: 'meervoud',
      prompt: 'Zet de zin in het meervoud.',
      source: 'Het huis is groot.',
      accept: ['De huizen zijn groot.'],
      why: 'huis → huizen: in het meervoud hoor je een z. En is wordt zijn.',
    },
    {
      kind: 'type',
      id: 'leest',
      prompt: 'Typ de goede vorm van lezen.',
      before: 'Mijn dochter',
      after: 'elke avond een boek.',
      hint: 'le…',
      answer: 'leest',
      why: 'lezen → stam lees + t: leest. Vóór de t staat nooit een z.',
    },
    {
      kind: 'choice',
      id: 'durf',
      prompt: 'Kies de goede vorm.',
      before: 'Ik',
      after: 'niet alleen in het donker te fietsen.',
      options: ['durf', 'durv', 'durft'],
      answer: 'durf',
      why: 'durven → stam durf. Aan het eind een f, en bij ik geen t.',
    },
    {
      kind: 'bet',
      id: 'kaarsen',
      prompt: 'Op de verjaardagstaart staan tien …',
      options: ['kaarsen', 'kaarzen'],
      answer: 'kaarsen',
      why: 'kaars → kaarsen, met s. Lastig, want laars → laarzen heeft wel een z. Zulke paren moet je per woord leren.',
    },
  ],
};
