import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": de doffe e als e, -ig, -lijk en -lijks, en de n van -en die je niet hoort. */
export const LES_K37: LessonInput = {
  id: 'k37',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'De doffe e',
  skill: 'Spelling',
  icon: '-ig',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Eén klank, vier spellingen',
      panels: [
        {
          text: 'De klank ‘uh’ hoor je heel vaak. In kleine woorden: *de*, *te*, *je*, *me*, *ze*, *we*. Aan het eind van een woord: *lopen*, *grote*, *tafel*, *bezem*, *kamer*. En vooraan in *gezond*, *betalen*, *vergeten*. Dat is de *doffe e*. Hij krijgt nooit de klemtoon. Meestal schrijf je hem gewoon met een *e*. Maar op een paar vaste plekken niet: daarover gaat de rest van de les.',
          rule: 'De doffe e (‘uh’) schrijf je meestal als *e*: *de*, *lopen*, *tafel*, *gezond*.',
          lab: {
            label: 'Tik een woord en zie waar de doffe e zit',
            chips: [
              { k: 'lopen', out: 'lo-pen', note: 'In -pen: de e is dof, en de n hoor je vaak niet.' },
              { k: 'tafel', out: 'ta-fel', note: 'In -fel: dof. De klemtoon ligt op ta.' },
              { k: 'gezond', out: 'ge-zond', note: 'In ge-: dof. De klemtoon ligt op zond.' },
              { k: 'vergeten', out: 'ver-ge-ten', note: 'ver- en -ten zijn dof. De ge in het midden heeft de klemtoon: daar hoor je een lange ee.' },
              { k: 'kamer', out: 'ka-mer', note: 'In -mer: dof.' },
            ],
          },
        },
        {
          text: 'Aan het eind van veel bijvoeglijke naamwoorden hoor je ‘uhg’. Dat schrijf je altijd als *-ig*: *gezellig*, *nodig*, *handig*, *prettig*, *aardig*, *lastig*, *zuinig*, *gelukkig*, *prachtig*. Ook de tientallen: *twintig*, *dertig*, *veertig*, *vijftig*. Nooit *-ug*, *-ich*, *-eg* of *-uch*. Na een korte klank wordt de medeklinker dubbel: *gezellig*, *prettig*, *gelukkig*.',
          rule: 'Je hoort ‘uhg’ aan het eind: schrijf *-ig*. Nooit *-ug* of *-ich*.',
          build: {
            before: 'Wat is het hier',
            stem: 'gezell',
            endings: ['ig', 'ug', 'ich', 'eg'],
            answer: 'ig',
            note: 'gezellig: de doffe klank aan het eind schrijf je altijd als -ig.',
          },
        },
        {
          text: 'Hoor je ‘luhk’ aan het eind? Dan schrijf je *-lijk*. De *ij* klinkt hier als een doffe e: *vriendelijk*, *eerlijk*, *duidelijk*, *mogelijk*, *moeilijk*, *makkelijk*, *gevaarlijk*, *natuurlijk*, *waarschijnlijk*, *persoonlijk*. Met een *s* erachter wordt het *-lijks*: *dagelijks*, *wekelijks*, *maandelijks*, *jaarlijks*, *nauwelijks*.',
          rule: '‘luhk’ aan het eind: *-lijk*. ‘luhks’: *-lijks*.',
          quiz: {
            q: 'Je hoort ‘dui-duh-luhk’. Hoe schrijf je het?',
            options: ['duidelijk', 'duidelik', 'duidelek'],
            answer: 'duidelijk',
            why: 'De uitgang -lijk schrijf je altijd met ij, ook al hoor je een doffe e.',
          },
        },
        {
          text: 'In gewone spraak hoor je de *n* van *-en* vaak niet. *Wij lopen* klinkt als ‘wij lope’. Toch schrijf je hem. *-en* schrijf je bij het hele werkwoord en de *wij*-, *jullie*- en *zij*-vorm (*lopen*, *wij werken*), bij het meervoud (*boeken*, *kinderen*), en bij stoffen (*een houten tafel*, *een gouden ring*). Andere bijvoeglijke naamwoorden krijgen geen *-en*, hooguit *-e*: *de grote tafel*, *een kleine auto*.',
          rule: 'Werkwoord met *wij*/*jullie*/*zij* en meervoud: *-en*, ook als je de *n* niet hoort.',
          mark: {
            q: 'Tik de woorden die op -en eindigen',
            sentence: 'Wij lopen met de kleine kinderen naar de grote speeltuin.',
            targets: [1, 5],
            note: 'lopen (wij-vorm) en kinderen (meervoud). kleine en grote zijn bijvoeglijke naamwoorden: alleen -e.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'ig-of-lijk',
      prompt: '-ig of -lijk? Maak het woord af.',
      buckets: ['-ig', '-lijk'],
      items: [
        { t: 'nod…', b: 0 },
        { t: 'eer…', b: 1 },
        { t: 'hand…', b: 0 },
        { t: 'moei…', b: 1 },
        { t: 'zuin…', b: 0 },
        { t: 'duide…', b: 1 },
        { t: 'aard…', b: 0 },
        { t: 'gevaar…', b: 1 },
        { t: 'last…', b: 0 },
        { t: 'natuur…', b: 1 },
        { t: 'prett…', b: 0 },
        { t: 'makke…', b: 1 },
      ],
      why: 'Met -ig: nodig, handig, zuinig, aardig, lastig, prettig. Met -lijk: eerlijk, moeilijk, duidelijk, gevaarlijk, natuurlijk, makkelijk.',
    },
    {
      kind: 'type',
      id: 'gezellige',
      prompt: 'Typ het woord dat bij gezellig hoort, met de goede uitgang.',
      before: 'Bedankt voor de',
      after: 'avond!',
      hint: 'gezellig…',
      answer: 'gezellige',
      why: 'gezellig + e = gezellige. De g wordt niet dubbel, want -ig heeft geen klemtoon.',
    },
    {
      kind: 'choice',
      id: 'een-of-een',
      prompt: 'Kies de spelling die laat zien dat het om het getal gaat.',
      before: 'Ik heb maar',
      after: 'broer, geen twee.',
      options: ['één', 'een', 'eén'],
      answer: 'één',
      why: 'Hier gaat het om het getal: één, met een lange ee en accenten op beide e’s. Het lidwoord een klinkt als ‘un’ en krijgt geen accent.',
    },
    {
      kind: 'fix',
      id: 'lopen',
      prompt: 'Tik het fout gespelde woord en verbeter het.',
      sentence: 'Wij lope elke ochtend naar het station.',
      wrong: 1,
      answer: 'lopen',
      why: 'Na wij komt het hele werkwoord: lopen. Je hoort de n vaak niet, maar je schrijft hem wel.',
    },
    {
      kind: 'bet',
      id: 'dagelijks',
      prompt: 'Ik sport … (elke dag).',
      options: ['dagelijks', 'dagelijk', 'dageluks'],
      answer: 'dagelijks',
      why: 'Elke dag: dagelijks, met -lijks. Zo ook wekelijks, maandelijks en jaarlijks.',
    },
    {
      kind: 'type',
      id: 'twintig',
      prompt: 'Schrijf het getal in letters.',
      before: 'Mijn zoon is',
      after: 'jaar.',
      hint: '20',
      answer: 'twintig',
      why: 'De tientallen eindigen op -tig: twintig, dertig, veertig. Nooit -tug of -tich.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen en een stappenplan',
      panels: [
        {
          text: 'Komt er iets achter *-ig* of *-lijk*, dan blijft de spelling gewoon staan: *gezellige*, *gezelliger*, *gezelligheid*; *vriendelijke*, *vriendelijker*, *vriendelijkheid*. De *g* en de *k* worden niet dubbel, want *-ig* en *-lijk* hebben geen klemtoon. Dus *gezellige*, niet *gezelligge*; *eerlijke*, niet *eerlijkke*.',
          rule: '*-ig* en *-lijk* met een uitgang: nooit dubbel. *gezellige*, *eerlijker*.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['met -e', 'met -er'],
            rows: [
              { label: 'gezellig', cells: [{ fill: 'gezellige' }, { fill: 'gezelliger', hint: 'Geen dubbele g.' }] },
              { label: 'vriendelijk', cells: [{ fill: 'vriendelijke' }, { fill: 'vriendelijker', hint: 'Geen dubbele k.' }] },
              { label: 'eerlijk', cells: [{ fill: 'eerlijke' }, { fill: 'eerlijker' }] },
              { label: 'handig', cells: [{ fill: 'handige' }, { fill: 'handiger' }] },
            ],
            extra: ['gezelligge', 'vriendelijkke', 'eerlijkker', 'handigger', 'gezellegere'],
            note: 'Geen klemtoon op -ig en -lijk, dus niets wordt dubbel: gezellige, vriendelijker, eerlijke, handiger.',
          },
        },
        {
          text: 'Niet elke *ij* is een doffe e. In *-lijk* aan het eind wel. Maar in *gelijk*, *rijk*, *kijk* en *blij* hoor je een gewone *ij*, want daar ligt de klemtoon op. En een paar zelfstandige naamwoorden eindigen op *-ik*, niet op *-ig*: *perzik*, *monnik*, *havik*. Die moet je kennen. Woorden op *-ing* (*koning*, *woning*, *honing*) hebben weer een andere klank: daar hoor je de *ng*.',
          rule: 'Doffe ij alleen in *-lijk* en *-lijks*. In *gelijk* en *rijk* hoor je een gewone *ij*.',
          mark: {
            q: 'Tik de woorden waarin de ij als doffe e klinkt',
            sentence: 'Het is eerlijk gezegd moeilijk om gelijk te krijgen bij een rijke klant.',
            targets: [2, 4],
            note: 'eerlijk en moeilijk: -lijk met een doffe e. In gelijk, krijgen, bij en rijke hoor je een gewone ij.',
          },
        },
        {
          text: 'Het lidwoord *een* spreek je uit als ‘un’, met een doffe e. Het getal *één* zeg je met een lange *ee*. De accenten schrijf je alleen als het anders niet duidelijk is: *Ik heb één broer* (niet twee). En let op *-e* tegenover *-en*. Een gewoon bijvoeglijk naamwoord (geen stof zoals *houten*) krijgt hooguit *-e*, nooit *-en*: *de oude fiets*, *de oude fietsen*. Een meervoud en een werkwoord krijgen *-en*: *twee fietsen*, *wij fietsen*.',
          rule: 'Bijvoeglijk naamwoord: hooguit *-e* (*de oude fiets*). Meervoud en *wij*-vorm: *-en* (*wij fietsen*).',
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Wij fietsen naar de grote stad.', 'Wij fietse naar de grote stad.', 'Wij fietsen naar de groten stad.'],
            answer: 'Wij fietsen naar de grote stad.',
            why: 'wij fietsen: werkwoord met -en. grote: bijvoeglijk naamwoord, alleen -e.',
          },
        },
        {
          text: 'Je hoort ‘uh’ en twijfelt? Loop dit stappenplan af. 1. Hoor je ‘uhg’ aan het eind? Dan *-ig*. 2. Hoor je ‘luhk’ of ‘luhks’? Dan *-lijk* of *-lijks*. 3. Is het een werkwoord met *wij*, *jullie* of *zij*, een hele werkwoord, een meervoud of een stof? Dan *-en*, ook als je de *n* niet hoort. 4. In alle andere gevallen: *e* (*de*, *be-*, *ge-*, *ver-*, *tafel*, *kamer*, *grote*). Tik hieronder op de typische fouten.',
          rule: '‘uhg’ → *-ig*. ‘luhk’ → *-lijk*. Werkwoord of meervoud → *-en*. Anders → *e*.',
          lab: {
            label: 'Tik een fout',
            chips: [
              { k: 'gezellug', out: 'gezellig', note: '‘uhg’ aan het eind: -ig.' },
              { k: 'vriendelek', out: 'vriendelijk', note: '‘luhk’ aan het eind: -lijk.' },
              { k: 'wij lope', out: 'wij lopen', note: 'Na wij: het hele werkwoord, met -en.' },
              { k: 'handich', out: 'handig', note: 'Nooit -ich: -ig.' },
              { k: 'mogelek', out: 'mogelijk', note: 'Ook hier: -lijk met ij.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'swipe',
      id: 'goed-of-fout',
      prompt: 'Is de zin goed gespeld?',
      intro: 'Veeg naar rechts als de zin goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'Het was een gezellug feestje.', ok: false, fix: 'gezellig', why: '‘uhg’ aan het eind: -ig.' },
        { t: 'Dat is heel vriendelijk van je.', ok: true, why: '-lijk met ij.' },
        { t: 'Wij werke vandaag thuis.', ok: false, fix: 'werken', why: 'Na wij: werken, met -en.' },
        { t: 'Ik ga wekelijks naar de sportschool.', ok: true, why: 'Elke week: wekelijks, met -lijks.' },
        { t: 'Hij is een eerlijke man.', ok: true, why: 'eerlijk + e = eerlijke, zonder dubbele k.' },
        { t: 'Dat is waarschijnlijk niet nodich.', ok: false, fix: 'nodig', why: 'Nooit -ich: nodig.' },
        { t: 'Ze heeft een prachtige jurk gekocht.', ok: true, why: 'prachtig + e = prachtige.' },
        { t: 'De kinderen spele buiten.', ok: false, fix: 'spelen', why: 'Meervoud onderwerp, dus het werkwoord krijgt -en: spelen.' },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje-collega',
      prompt: 'Vind de vijf fouten in het appje en verbeter ze.',
      intro: 'Let op -ig, -lijk en -en.',
      header: { to: 'Lisa' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Lisa,' },
        { t: 'bedankt' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'gezellug', fix: 'gezellige', why: '-ig, en met -e omdat er de … avond staat: de gezellige avond.' },
        { t: 'avond!' },
        { t: 'Het' },
        { t: 'eten' },
        { t: 'was' },
        { t: 'heerlek.', fix: 'heerlijk.', why: '‘luhk’ aan het eind: -lijk.' },
        { t: 'Morgen' },
        { t: 'werke', fix: 'werken', why: 'Bij we hoort het hele werkwoord: werken.' },
        { t: 'we' },
        { t: 'thuis,' },
        { t: 'want' },
        { t: 'het' },
        { t: 'kantoor' },
        { t: 'is' },
        { t: 'dicht.' },
        { t: 'Ik' },
        { t: 'ben' },
        { t: 'natuurluk', fix: 'natuurlijk', why: '‘luhk’ aan het eind: -lijk.' },
        { t: 'wel' },
        { t: 'bereikbaar.' },
        { t: 'Het' },
        { t: 'is' },
        { t: 'lastich,', fix: 'lastig,', why: 'Nooit -ich: lastig.' },
        { t: 'maar' },
        { t: 'we' },
        { t: 'vinden' },
        { t: 'vast' },
        { t: 'een' },
        { t: 'oplossing.' },
        { t: 'Groetjes,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Alle vijf gevonden',
        text: 'gezellige, heerlijk, werken, natuurlijk en lastig. vinden en oplossing waren al goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ de zin.',
      sentence: 'Het is gezellig, maar eerlijk gezegd vind ik de lessen moeilijk.',
      right: 'Goed: gezellig met -ig, eerlijk en moeilijk met -lijk, en lessen met -en.',
      wrong: 'Let op: gezellig (-ig), eerlijk en moeilijk (-lijk) en lessen (meervoud met -en, ook al hoor je de n niet).',
    },
    {
      kind: 'type',
      id: 'jaarlijkse',
      prompt: 'Typ het woord voor ‘elk jaar’, met de goede uitgang.',
      before: 'De',
      after: 'vergadering is in maart.',
      hint: '…lijkse',
      answer: 'jaarlijkse',
      why: 'jaarlijks + e = jaarlijkse. De ij blijft, ook al klinkt hij dof.',
    },
    {
      kind: 'rewrite',
      id: 'wij-vorm',
      prompt: 'Begin de zin met ‘Wij’ en pas het werkwoord aan.',
      source: 'Ik werk morgen thuis.',
      accept: ['Wij werken morgen thuis.'],
      why: 'Bij wij hoort het hele werkwoord: werken. Je hoort de n vaak niet, maar je schrijft hem wel.',
    },
    {
      kind: 'choice',
      id: 'moeilijke',
      prompt: 'Kies de goede spelling.',
      before: 'Dat is een',
      after: 'vraag.',
      options: ['moeilijke', 'moeilijkke', 'moeiluke'],
      answer: 'moeilijke',
      why: 'moeilijk + e = moeilijke. -lijk heeft geen klemtoon, dus de k wordt niet dubbel.',
    },
    {
      kind: 'sort',
      id: 'e-of-en',
      prompt: '-e of -en? Kies wat er op de plek van _ hoort.',
      buckets: ['-e', '-en'],
      items: [
        { t: 'de grot_ stad', b: 0 },
        { t: 'wij werk_', b: 1 },
        { t: 'twee boek_', b: 1 },
        { t: 'een gezellig_ avond', b: 0 },
        { t: 'een hout_ tafel', b: 1 },
        { t: 'jullie lop_', b: 1 },
        { t: 'de nieuw_ buren', b: 0 },
        { t: 'een goud_ ring', b: 1 },
        { t: 'het klein_ kind', b: 0 },
        { t: 'de kinderen zing_ samen', b: 1 },
      ],
      why: 'Met -e: bijvoeglijke naamwoorden voor een zelfstandig naamwoord (grote, gezellige, nieuwe, kleine). Met -en: werkwoorden (werken, lopen, zingen), meervouden (boeken) en stoffen (houten, gouden).',
    },
    {
      kind: 'bet',
      id: 'perzik',
      prompt: 'Welke spelling is goed? ‘Ik eet een sappige …’',
      options: ['perzik', 'perzig'],
      answer: 'perzik',
      why: 'perzik is een zelfstandig naamwoord op -ik, net als monnik en havik. Die moet je kennen. Bijvoeglijke naamwoorden krijgen -ig: sappig.',
    },
    {
      kind: 'write',
      id: 'bedankje',
      prompt: 'Schrijf een kort bedankje aan een collega of buurvrouw.',
      intro: 'Schrijf minstens 25 woorden. Gebruik een woord op -ig, een woord op -lijk en een werkwoord met wij of we.',
      minWords: 25,
      must: [
        { label: 'Een woord op -ig of -ige', hint: 'gezellig, prettig, handig', test: { pattern: '\\b\\w+ige?\\b', flags: 'i' } },
        { label: 'Een woord op -lijk of -lijke', hint: 'vriendelijk, heerlijk, duidelijk', test: { pattern: '\\b\\w+lijke?\\b', flags: 'i' } },
        { label: 'Wij of we met een werkwoord op -en', hint: 'we werken, eten we', test: { pattern: '\\b(wij|we)\\s+\\w+en\\b|\\b\\w+en\\s+(wij|we)\\b', flags: 'i' } },
      ],
      starters: ['Bedankt voor de gezellige', 'Het was heel vriendelijk van je', 'Volgende keer eten we'],
      why: 'Lees je tekst nog één keer na: -ig en -lijk zonder dubbele letter, en -en bij wij en we, ook als je de n niet hoort.',
    },
  ],
};
