import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": leenwoorden, waarin je een klank hoort die je met andere letters schrijft (c, ch, g, ou, eau, -tie, th, y, x, qu). */
export const LES_K38: LessonInput = {
  id: 'k38',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'Leenwoorden: je hoort sj, je schrijft ch',
  skill: 'Spelling',
  icon: 'eau',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Andere letters voor een bekende klank',
      panels: [
        {
          text: 'Sommige woorden spreek je anders uit dan je ze schrijft: *café*, *douche*, *cadeau*, *vakantie*. Dat zijn leenwoorden. Je kunt ze niet schrijven zoals je ze hoort. Begin met de *c*. Voor *a*, *o*, *u*, *l*, *r* en *t* klinkt de c als een *k*: *café*, *cola*, *computer*, *cultuur*, *clown*, *crème*, *product*. Voor *e*, *i*, *y* en *ij* klinkt de c als een *s*: *centrum*, *cent*, *citroen*, *cirkel*, *december*, *procent*, *cijfer*.',
          rule: 'c + a, o, u, l, r, t klinkt als *k*. c + e, i, y, ij klinkt als *s*.',
          mark: {
            q: 'Tik de woorden waarin de c klinkt als een s',
            sentence: 'café centrum computer citroen cultuur december cola procent',
            targets: [1, 3, 5, 7],
            note: 'centrum, citroen, december en procent: c voor e of i, dus een s-klank. In café, computer, cultuur en cola staat de c voor a, o of u: een k-klank.',
          },
        },
        {
          text: 'Hoor je *sj* in een leenwoord? Dan schrijf je meestal *ch*: *chef*, *douche*, *machine*, *chauffeur*, *chocola*, *brochure*. Hoor je *zj*? Dan schrijf je *g* of *j*: *garage*, *bagage*, *horloge*, *etage*, *massage*, *logeren*, en *journalist*, *journaal*. De leenwoorden op *-age* klinken allemaal als *aazje*.',
          rule: 'sj-klank: *ch* (*chef*). zj-klank: *g* (*garage*) of *j* (*journalist*).',
          quiz: {
            q: 'Je hoort: "de sjef van het restaurant". Hoe schrijf je het?',
            options: ['chef', 'sjef', 'shef'],
            answer: 'chef',
            why: 'De sj-klank in een leenwoord schrijf je met ch: chef, net als douche en machine.',
          },
          deep: {
            q: 'Klinkt ch altijd als sj?',
            a: 'Nee. In gewone woorden als *lachen* en *school* hoor je de gewone ch. Ook in *chaos*, *chemie* en *christelijk* hoor je die gewone ch, al staat hij vooraan. En in *chips* en *checken* hoor je *tsj*. Ken je het woord niet, zoek het dan op.',
          },
        },
        {
          text: 'Drie klinkerklanken met verrassende letters. Hoor je *oe*, dan staat er vaak *ou*: *douche*, *route*, *souvenir*, *routine*, *journalist*. Hoor je *oo* aan het eind van het woord, dan staat er vaak *eau*: *cadeau*, *bureau*, *niveau*, *plateau*. En soms schrijf je *oo* als *au*: *restaurant*, *chauffeur*. Het meervoud van een woord op *-eau* krijgt alleen een *s*, zonder apostrof: *cadeaus*, *bureaus*, *niveaus*.',
          rule: 'oe-klank: vaak *ou* (*route*). oo aan het eind: vaak *eau* (*cadeau*). Meervoud: *cadeaus*, zonder apostrof.',
          build: {
            before: 'Voor je verjaardag krijg je een',
            stem: 'cad',
            endings: ['eau', 'o', 'oo', 'ow'],
            answer: 'eau',
            note: 'cadeau: de oo-klank aan het eind schrijf je hier als eau. Kado en cadoo zijn fout.',
          },
        },
        {
          text: 'Veel leenwoorden eindigen op *-tie*. Na een klinker hoor je dan *tsie*: *politie*, *informatie*, *situatie*, *traditie*. Na een *c*, *n* of *p* hoor je vaak *sie*, maar je schrijft meestal toch *-tie*: *actie*, *functie*, *reactie*, *vakantie*, *receptie*. Hoor je aan het eind *zie*, of *sie* na een *r*, dan schrijf je meestal *-sie*: *televisie*, *conclusie*, *versie*, *excursie*. Na een korte klank: *-ssie* (*discussie*). Woorden op *-teit* schrijf je zoals je ze hoort: *kwaliteit*, *universiteit*, *activiteit*, *identiteit*.',
          rule: 'Je hoort *tsie*, of *sie* na *c*, *n* of *p*: meestal *-tie* (*informatie*, *actie*, *vakantie*). Je hoort *zie*: *-sie* (*televisie*).',
          lab: {
            label: 'Tik wat je hoort',
            chips: [
              { k: 'va-kan-sie', out: 'vakantie', note: 'Na de n hoor je vaak sie, maar je schrijft -tie. Niet vakansie.' },
              { k: 'in-for-maa-tsie', out: 'informatie', note: 'tsie-klank na een klinker: -tie.' },
              { k: 're-ak-sie', out: 'reactie', note: 'Na de k-klank hoor je sie, maar je schrijft -tie, met een c ervoor.' },
              { k: 'te-le-vie-zie', out: 'televisie', note: 'zie-klank zonder t: -sie.' },
              { k: 'ver-sie', out: 'versie', note: 'sie na een r: -sie.' },
              { k: 'kwa-lie-teit', out: 'kwaliteit', note: 'Je schrijft wat je hoort: kw vooraan en -teit aan het eind.' },
            ],
          },
        },
        {
          text: 'Nog vier vaste koppels. *th* klinkt als *t*: *thee*, *theater*, *thema*, *apotheek*, *methode*, en ook in *thuis*. *y* klinkt als *ie* of *i*: *baby*, *hobby*, *type*, *typisch*, *systeem*. *x* klinkt als *ks*: *taxi*, *examen*, *extra*, *excuus*, *luxe*. En *qu* klinkt als *kw*: *aquarium*, *quiz*. Let op: in *enquête* klinkt qu als een k.',
          rule: '*th* = t (*thee*), *y* = ie of i (*baby*), *x* = ks (*taxi*), *qu* = kw (*aquarium*).',
          quiz: {
            q: 'Je hoort: "Dat is echt tie-pies voor hem." Hoe schrijf je het?',
            options: ['typisch', 'tiepies', 'typies'],
            answer: 'typisch',
            why: 'De ie-klank schrijf je hier met y, en het woord eindigt op -isch, net als logisch en praktisch.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'sj-zj',
      prompt: 'Je hoort sj of zj. Welke letters horen op de puntjes?',
      buckets: ['ch', 'sj', 'g', 'j'],
      items: [
        { t: 'dou…e', b: 0 },
        { t: 'ma…ine', b: 0 },
        { t: '…auffeur', b: 0 },
        { t: 'bro…ure', b: 0 },
        { t: '…ampignon', b: 0 },
        { t: '…agrijnig', b: 0 },
        { t: '…aal', b: 1 },
        { t: '…ouwen', b: 1 },
        { t: '…abloon', b: 1 },
        { t: 'gara…e', b: 2 },
        { t: 'bou…ie', b: 2 },
        { t: 'lo…eren', b: 2 },
        { t: 're…ie', b: 2 },
        { t: 'colle…e', b: 2 },
        { t: '…ournaal', b: 3 },
        { t: '…ury', b: 3 },
        { t: '…aloers', b: 3 },
      ],
      why: 'ch: douche, machine, chauffeur, brochure, champignon en chagrijnig. sj: sjaal, sjouwen en sjabloon; die schrijf je zoals je ze hoort, en die leer je uit je hoofd. g: garage, bougie, logeren, regie en college. j: journaal, jury en jaloers.',
    },
    {
      kind: 'choice',
      id: 'receptie',
      prompt: 'Welke zin is helemaal goed?',
      before: '',
      after: '',
      options: [
        'De chauffeur bracht de bagage naar de receptie.',
        'De chauffeur bracht de baggage naar de receptie.',
        'De chaufeur bracht de bagage naar de receptie.',
        'De chauffeur bracht de bagage naar de recepsie.',
      ],
      answer: 'De chauffeur bracht de bagage naar de receptie.',
      why: 'chauffeur met ff, bagage met één g in het midden en receptie met -tie aan het eind.',
    },
    {
      kind: 'swipe',
      id: 'c-klank',
      prompt: 'Goed of fout geschreven?',
      intro: 'Let op elke c en k. Sommige zinnen lijken fout, maar zijn goed.',
      cards: [
        { t: 'U krijgt tien procent korting op uw abonnement.', ok: true, why: 'procent: c voor e klinkt als s. De spelling klopt.' },
        { t: 'Neem een kopie van uw paspoort mee.', ok: true, why: 'kopie schrijf je met een k, niet met een c. Dat leer je per woord.' },
        {
          t: 'Hij kreeg een kompliment van zijn leidinggevende.',
          ok: false,
          fix: 'kompliment → compliment',
          why: 'compliment schrijf je met een c. Een k-klank vooraan kan c of k zijn: dat leer je per woord.',
        },
        { t: 'Mijn kollega is vandaag ziek.', ok: false, fix: 'kollega → collega', why: 'collega schrijf je met een c en ll.' },
        { t: 'Stuur ons uw akkoord per mail.', ok: true, why: 'akkoord schrijf je met kk, niet met cc.' },
        {
          t: 'Het produkt wordt morgen bezorgd.',
          ok: false,
          fix: 'produkt → product',
          why: 'In leenwoorden is een k-klank voor een t meestal een c: product, net als actie en contact.',
        },
        { t: 'Neem uw certificaten mee naar het gesprek.', ok: true, why: 'certificaat: de eerste c (voor e) klinkt als s, de tweede (voor a) als k.' },
        {
          t: 'Ik wens je veel sukses met je examen.',
          ok: false,
          fix: 'sukses → succes',
          why: 'succes: cc. De eerste c klinkt als k, de tweede (voor e) als s.',
        },
        { t: 'De fabriek ligt aan de rand van de stad.', ok: true, why: 'Woorden op -iek schrijf je met een k: fabriek, muziek, techniek.' },
        { t: 'De klant accepteert de nieuwe prijs niet.', ok: true, why: 'accepteren: cc, een k-klank en een s-klank. Net als accent.' },
        {
          t: 'Ik heb een afspraak bij de huisarts in het sentrum.',
          ok: false,
          fix: 'sentrum → centrum',
          why: 'centrum schrijf je met een c: c voor e klinkt als s.',
        },
        { t: 'We lunchen samen in de kantine.', ok: true, why: 'kantine schrijf je met een k. Dat leer je per woord.' },
      ],
    },
    {
      kind: 'sort',
      id: 'tie-sie',
      prompt: '-tie, -sie of -ssie?',
      buckets: ['-tie', '-sie', '-ssie'],
      items: [
        { t: 'vakan…', b: 0 },
        { t: 'situa…', b: 0 },
        { t: 'func…', b: 0 },
        { t: 'garan…', b: 0 },
        { t: 'kwes…', b: 0 },
        { t: 'sugges…', b: 0 },
        { t: 'sollicita…', b: 0 },
        { t: 'adverten…', b: 0 },
        { t: 'televi…', b: 1 },
        { t: 'ver…', b: 1 },
        { t: 'conclu…', b: 1 },
        { t: 'excur…', b: 1 },
        { t: 'illu…', b: 1 },
        { t: 'discu…', b: 2 },
        { t: 'commi…', b: 2 },
        { t: 'agre…', b: 2 },
        { t: 'depre…', b: 2 },
      ],
      why: 'vakantie, situatie, functie, garantie, sollicitatie en advertentie: -tie. In kwestie en suggestie hoor je de t gewoon: ook -tie. televisie, versie, conclusie, excursie en illusie: -sie. discussie, commissie, agressie en depressie: -ssie, want de klank ervoor is kort.',
    },
    {
      kind: 'type',
      id: 'sollicitatiegesprek',
      prompt: 'Typ het woord dat je hoort: so-lie-sie-taa-tsie-ge-sprek.',
      before: 'Morgen heb ik mijn eerste',
      after: 'bij een bank.',
      hint: '',
      answer: 'sollicitatiegesprek',
      why: 'sollicitatie: ll, twee keer een c voor i (s-klank) en -tie aan het eind. Met gesprek erachter is het één woord: sollicitatiegesprek.',
    },
    {
      kind: 'fix',
      id: 'actueel',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Bij de receptie lag een brochure over de excursie, maar de informatie over de route was niet aktueel.',
      wrong: 17,
      answer: 'actueel',
      why: 'In leenwoorden is een k-klank voor een t meestal een c: actueel, net als actie en product. De andere leenwoorden in de zin zijn goed.',
    },
    {
      kind: 'bet',
      id: 'officiele',
      prompt: 'Je hebt een … brief van de gemeente gekregen. Welke spelling is goed?',
      intro: 'Kijk naar elke letter.',
      options: ['officiële', 'officiele', 'offisiële', 'officieele'],
      answer: 'officiële',
      why: '-ieel + e wordt -iële, met een trema: officiële, net als financiële. De s-klank voor i schrijf je hier met c, en je schrijft ff.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen en een stappenplan',
      panels: [
        {
          text: 'Hoor je een *k* vooraan, dan kan het een *c* of een *k* zijn: *café*, *computer*, *camping*, *contact*, maar *kantoor*, *kopie*, *kassa*. Dat moet je per woord leren. Twee houvasten. Hoor je in een leenwoord een k-klank vlak voor een *t*, dan is dat meestal een *c*: *actie*, *product*, *contact*, *direct*, *correct*, *effect*. Maar *praktisch*, *elektrisch* en *dokter* hebben een *k*. En woorden op *-iek* schrijf je met een k: *muziek*, *fabriek*, *politiek*, *techniek*, *kritiek*.',
          rule: 'k-klank voor *t*: meestal *c* (*actie*, *product*). Aan het eind *-iek* met k: *muziek*, *fabriek*.',
          quiz: {
            q: 'Welke rij is helemaal goed?',
            options: ['product, muziek, actie', 'produkt, muziek, aktie', 'product, muziec, actie'],
            answer: 'product, muziek, actie',
            why: 'product en actie: in deze leenwoorden is de k-klank voor de t een c. muziek eindigt op -iek, met een k.',
          },
        },
        {
          text: 'Twee keer c achter elkaar: de eerste klinkt als k, de tweede als s voor e of i: *accent* (ak-sent), *accepteren*, *succes* (suk-ses). Voor a, o of u klinken ze samen als één k: *accu*, *accommodatie*. Hoor je *ks*, dan schrijf je in leenwoorden vaak een *x* (*taxi*, *extra*, *examen*), maar in veel gewone woorden *ks*: *tekst*, *heks*, *links*, *bliksem*. Een s-klank voor i kan ook gewoon een s zijn: *situatie*, *sigaret*, *sinaasappel*. En een f-klank schrijf je bijna altijd met f: *foto*, *telefoon*, *fysiek*.',
          rule: 'Je hoort *suk-ses*: schrijf *succes*. Je hoort *ks*: *taxi*, maar *tekst*. Je hoort f: bijna altijd *f* (*foto*).',
          quiz: {
            q: 'Je wenst iemand veel suk-ses. Hoe schrijf je het?',
            options: ['succes', 'sukses', 'succses'],
            answer: 'succes',
            why: 'succes: cc, waarvan de eerste als k en de tweede (voor e) als s klinkt. Precies wat je hoort: suk-ses.',
          },
        },
        {
          text: 'Deze fouten zie je het vaakst in mails en appjes. Je schrijft het woord zoals je het hoort, maar bij een leenwoord gaat dat mis.',
          show: [
            { wrong: 'kado', right: 'cadeau' },
            { wrong: 'buro', right: 'bureau' },
            { wrong: 'nivo', right: 'niveau' },
            { wrong: 'vakansie', right: 'vakantie' },
            { wrong: 'informatsie', right: 'informatie' },
            { wrong: 'garaasje', right: 'garage' },
            { wrong: 'doesje', right: 'douche' },
            { wrong: 'cadeau’s', right: 'cadeaus' },
          ],
          quiz: {
            q: 'Je appt: "Ik zit nu op een hoger …" Wat typ je?',
            options: ['niveau', 'nivo', 'niveaux'],
            answer: 'niveau',
            why: 'niveau: de oo-klank aan het eind schrijf je als eau. Nivo is fout.',
          },
        },
        {
          text: 'Twijfel je bij een woord dat niet klinkt als een gewoon Nederlands woord? Gebruik dit stappenplan. 1. Welke klank hoor je? 2. Denk aan de vaste koppels: sj → *ch*, zj → *g* of *j*, oe → *ou*, oo aan het eind → *eau*, tsie → *-tie*, t → soms *th*, ie → soms *y*, ks → soms *x*. 3. Ken je het woord niet zeker? Zoek het op in de Woordenlijst (woordenlijst.org) of in een woordenboek.',
          rule: 'Klank horen, koppel kiezen, en bij twijfel opzoeken.',
          lab: {
            label: 'Tik wat je hoort',
            chips: [
              { k: 'sjo-feur', out: 'chauffeur', note: 'sj → ch, oo → au, en eu blijft eu.' },
              { k: 'roe-te', out: 'route', note: 'oe → ou.' },
              { k: 'bu-roo', out: 'bureau', note: 'oo aan het eind → eau.' },
              { k: 'a-po-teek', out: 'apotheek', note: 't → th.' },
              { k: 'hob-bie', out: 'hobby', note: 'ie aan het eind → y.' },
              { k: 'tak-sie', out: 'taxi', note: 'ks → x, en de ie-klank aan het eind is een i.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-sanne',
      prompt: 'Vind de fouten in dit mailtje.',
      intro: 'Tik een fout woord aan en verbeter het.',
      header: { to: 'Sanne', subject: 'Een cadeautje' },
      greeting: 'Hoi Sanne,',
      tokens: [
        { t: 'Na' },
        { t: 'mijn' },
        { t: 'vakansie', fix: 'vakantie', why: 'Na de n schrijf je hier -tie, ook als je sie hoort: vakantie.' },
        { t: 'heb' },
        { t: 'ik' },
        { t: 'een' },
        { t: 'kado', fix: 'cadeau', why: 'Leenwoord: c vooraan en eau aan het eind.' },
        { t: 'voor' },
        { t: 'je' },
        { t: 'meegenomen.' },
        { t: 'Het' },
        { t: 'ligt' },
        { t: 'op' },
        { t: 'je' },
        { t: 'buro.', fix: 'bureau.', why: 'oo aan het eind: eau.' },
        { t: 'Ik' },
        { t: 'vond' },
        { t: 'het' },
        { t: 'in' },
        { t: 'een' },
        { t: 'winkeltje' },
        { t: 'naast' },
        { t: 'een' },
        { t: 'restorant.', fix: 'restaurant.', why: 'De oo-klank schrijf je hier als au: restaurant.' },
        { t: 'Er' },
        { t: 'zit' },
        { t: 'ook' },
        { t: 'een' },
        { t: 'brosjure', fix: 'brochure', why: 'sj-klank in een leenwoord: ch.' },
        { t: 'bij' },
        { t: 'met' },
        { t: 'informatie' },
        { t: 'over' },
        { t: 'de' },
        { t: 'route.' },
        { t: 'Groetjes,' },
        { t: 'Fatima' },
      ],
      done: {
        title: 'Leenwoorden gecontroleerd',
        text: 'vakantie, cadeau, bureau, restaurant en brochure. informatie en route stonden al goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-chauffeur',
      prompt: 'Luister en typ de zin.',
      sentence: 'Na de excursie bracht de chauffeur de bagage van de journalist naar de receptie.',
      right: 'Goed: excursie (x, c en -sie), chauffeur (ch, au, ff en eu), bagage (g), journalist (j en ou) en receptie (c en -tie).',
      wrong: 'Let op: excursie (x, c en -sie), chauffeur (ch, au, ff en eu), bagage (één g in het midden), journalist (j en ou) en receptie (-tie).',
    },
    {
      kind: 'sort',
      id: 'x-ks',
      prompt: 'Je hoort ks. Schrijf je x of ks?',
      buckets: ['x', 'ks'],
      items: [
        { t: 'ta…i', b: 0 },
        { t: 'e…amen', b: 0 },
        { t: 'e…cuus', b: 0 },
        { t: 'lu…e', b: 0 },
        { t: 'e…pert', b: 0 },
        { t: 'ma…imaal', b: 0 },
        { t: 'comple…', b: 0 },
        { t: 'e…act', b: 0 },
        { t: 'te…t', b: 1 },
        { t: 'he…', b: 1 },
        { t: 'lin…', b: 1 },
        { t: 'bli…em', b: 1 },
        { t: 'ree…', b: 1 },
        { t: 'o…el', b: 1 },
      ],
      why: 'taxi, examen, excuus, luxe, expert, maximaal, complex en exact: leenwoorden met x. tekst, heks, links, bliksem, reeks en oksel: gewone woorden met ks. Dat moet je per woord kennen.',
    },
    {
      kind: 'swipe',
      id: 'gemengd',
      prompt: 'Goed of fout geschreven?',
      intro: 'Sommige zinnen lijken fout, maar zijn goed.',
      cards: [
        { t: 'Mijn hobby’s zijn koken en fotograferen.', ok: true, why: 'hobby: y voor de ie-klank. Meervoud: hobby’s, met apostrof na de y.' },
        { t: 'We hebben veel cadeau’s gekregen.', ok: false, fix: 'cadeau’s → cadeaus', why: 'Na eau komt geen apostrof: cadeaus, net als bureaus.' },
        { t: 'De chauffeur rijdt via de snelste route naar het station.', ok: true, why: 'chauffeur: ch, au, ff en eu. route: ou voor de oe-klank.' },
        { t: 'Ik zoek een baan op hoog nivo.', ok: false, fix: 'nivo → niveau', why: 'De oo-klank aan het eind schrijf je hier als eau: niveau.' },
        { t: 'Lees de informatie in de brochure goed door.', ok: true, why: 'informatie met -tie, brochure met ch.' },
        {
          t: 'Ik heb een souvenier voor je meegenomen.',
          ok: false,
          fix: 'souvenier → souvenir',
          why: 'souvenir eindigt op -ir, niet op -ier. Vooraan ou voor de oe-klank.',
        },
        { t: 'Hij is vanochtend erg chagrijnig.', ok: true, why: 'chagrijnig schrijf je met ch, al hoor je sj.' },
        { t: 'De apoteek is op zondag gesloten.', ok: false, fix: 'apoteek → apotheek', why: 'apotheek schrijf je met th.' },
        { t: 'De fysiotherapeut heeft om drie uur tijd.', ok: true, why: 'fysiotherapeut: f, y en th.' },
        {
          t: 'Vul eerst de enquete in.',
          ok: false,
          fix: 'enquete → enquête',
          why: 'enquête heeft een accent op de tweede e. Dat accent hoort vast bij het woord.',
        },
        { t: 'Dat is typisch iets voor hem.', ok: true, why: 'typisch: y voor de ie-klank en -isch aan het eind.' },
        { t: 'Er staan drie taxi’s voor het hotel.', ok: true, why: 'taxi: x voor de ks-klank. Meervoud: taxi’s, met apostrof na de i.' },
      ],
    },
    {
      kind: 'rewrite',
      id: 'chauffeur-route',
      prompt: 'Schrijf de zin over zonder fouten.',
      source: 'De sjauffeur gaf ons een brosjure met informatsie over de roete naar het restorant.',
      accept: ['De chauffeur gaf ons een brochure met informatie over de route naar het restaurant.'],
      why: 'chauffeur (sj → ch, oo → au), brochure (sj → ch), informatie (-tie), route (oe → ou) en restaurant (oo → au).',
    },
    {
      kind: 'choice',
      id: 'kwaliteit',
      prompt: 'Kies de goede spelling.',
      before: 'De',
      after: 'van het product is gecontroleerd.',
      options: ['kwaliteit', 'qualiteit', 'kwalitijt', 'kwaliteid'],
      answer: 'kwaliteit',
      why: 'kwaliteit schrijf je met kw, niet met qu. -teit schrijf je met ei, en met een t: kwaliteiten.',
    },
    {
      kind: 'type',
      id: 'bureaus',
      prompt: 'Typ het meervoud van het woord dat je hoort: bu-roo.',
      before: 'Op onze afdeling staan acht',
      after: 'met elk een computer.',
      hint: 'meervoud',
      answer: 'bureaus',
      why: 'bureau + s = bureaus. Na eau komt geen apostrof.',
    },
    {
      kind: 'dictation',
      id: 'dictee-apotheek',
      prompt: 'Luister en typ de zin.',
      sentence: 'Bij de apotheek kreeg ik een brochure met praktische informatie over de therapie en de medicijnen.',
      right: 'Goed: apotheek en therapie met th, brochure met ch, praktische met -isch, informatie met -tie en medicijnen met c en ij.',
      wrong: 'Let op: apotheek en therapie (th), brochure (ch), praktische (-isch + e), informatie (-tie) en medicijnen (c voor i, en ij).',
    },
    {
      kind: 'bet',
      id: 'fysiotherapeut',
      prompt: 'Je hebt last van je rug. Waar maak je een afspraak?',
      intro: 'Een lastig woord: drie koppels in één woord.',
      options: ['bij de fysiotherapeut', 'bij de fysioterapeut', 'bij de physiotherapeut', 'bij de fisiotherapeut'],
      answer: 'bij de fysiotherapeut',
      why: 'fysiotherapeut: de f-klank met f, de ie-klank met y, en de t met th.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Vierentwintig woorden door elkaar, ook uit eerdere lessen. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'De man of vrouw die de bus of een taxi rijdt (je hoort *sjo-feur*)',
          say: 'chauffeur',
          before: 'De',
          after: 'zet de koffers in de auto.',
          a: 'chauffeur',
          why: 'sj → ch, oo → au, dan ff en eu: chauffeur.',
        },
        {
          q: 'Zelfstandig naamwoord van *reageren*',
          before: 'Ik wacht nog op een',
          after: 'van de huisbaas.',
          a: 'reactie',
          why: 'De k-klank voor de t is hier een c, net als in actie. En het eind is -tie, al hoor je sie: reactie.',
        },
        { q: 'Meervoud van *taxi*', before: 'Er staan geen', after: 'bij het station.', a: 'taxi’s', why: 'Woord op i: meervoud met ’s.' },
        {
          q: 'Meervoud van het woord dat je hoort: *nie-voo*',
          before: 'Deze cursus bestaat uit drie',
          after: 'en duurt een jaar.',
          a: 'niveaus',
          why: 'niveau + s, zonder apostrof: niveaus.',
        },
        {
          q: 'Zelfstandig naamwoord van *concluderen*',
          before: 'Wat is jouw',
          after: 'na dit gesprek?',
          a: 'conclusie',
          why: 'Je hoort zie, zonder t: -sie. conclusie.',
        },
        {
          q: 'Bijvoeglijk naamwoord: zoals je mag verwachten (je hoort *loo-gies*)',
          before: 'Dat is toch',
          after: '!',
          a: 'logisch',
          why: 'ies aan het eind van een bijvoeglijk naamwoord: -isch.',
        },
        {
          q: 'Daar sta je onder na het sporten',
          say: 'douche',
          before: 'Na de training neem ik een',
          after: 'in de kleedkamer.',
          a: 'douche',
          why: 'oe → ou en sj → ch: douche.',
        },
        {
          q: 'Zelfstandig naamwoord van *garanderen*',
          before: 'Op deze wasmachine zit twee jaar',
          after: '.',
          a: 'garantie',
          why: 'Na de n schrijf je -tie, ook als je sie hoort. garanderen heeft een d, garantie een t.',
        },
        { q: 'Meervoud van *café*', before: 'In deze straat zijn drie', after: '.', a: 'cafés', why: 'Na é komt geen apostrof: cafés.' },
        {
          q: 'Dat wens je iemand voor een examen (je hoort *suk-ses*)',
          before: 'Veel',
          after: 'morgen!',
          a: 'succes',
          why: 'cc: de eerste c klinkt als k, de tweede (voor e) als s.',
        },
        {
          q: 'Alle koffers en tassen die je meeneemt op reis',
          say: 'bagage',
          before: 'Je mag twintig kilo',
          after: 'meenemen in het vliegtuig.',
          a: 'bagage',
          why: 'Eén g in het midden, en g voor de zj-klank: bagage.',
        },
        {
          q: 'Werkwoord: goedvinden, aannemen (je hoort *ak-sep-te-ren*)',
          before: 'Wij',
          after: 'uw voorstel.',
          a: 'accepteren',
          why: 'cc: een k-klank en een s-klank, net als in accent.',
        },
        {
          q: 'Meervoud van *idee*',
          before: 'Heb jij nog',
          after: 'voor het feest?',
          a: 'ideeën',
          why: 'idee + en: ideeën. Het trema op de laatste e laat zien dat die los klinkt.',
        },
        {
          q: 'Je hoort *ga-raa-zje*: hier repareren ze je auto',
          before: 'Mijn auto staat bij de',
          after: 'voor een grote beurt.',
          a: 'garage',
          why: 'De zj-klank in -age schrijf je met g: garage.',
        },
        {
          q: 'Iets wat een fabriek maakt (je hoort *pro-dukt*)',
          before: 'Dit',
          after: 'is niet meer leverbaar.',
          a: 'product',
          why: 'In leenwoorden is een k-klank voor een t meestal een c: product.',
        },
        { q: 'Elk jaar (van *jaar*)', before: 'De huur gaat', after: 'omhoog.', a: 'jaarlijks', why: 'luhks aan het eind: -lijks, met ij.' },
        {
          q: 'Wat je zegt als je iets niet goed vindt (je hoort *krie-tiek*)',
          before: 'Hij kan slecht tegen',
          after: 'van zijn baas.',
          a: 'kritiek',
          why: 'Vooraan een k, en -iek aan het eind ook met k: kritiek.',
        },
        {
          q: 'De winkel waar je medicijnen op recept haalt',
          say: 'apotheek',
          before: 'Je recept ligt klaar bij de',
          after: '.',
          a: 'apotheek',
          why: 'De t-klank schrijf je hier met th: apotheek.',
        },
        { q: 'Zelfstandig naamwoord van *verbieden*', before: 'Hier geldt een', after: 'op parkeren.', a: 'verbod', why: 'verboden: dus d.' },
        {
          q: 'Een vaste manier van werken (je hoort *sis-teem*)',
          before: 'Het nieuwe',
          after: 'werkt nog niet goed.',
          a: 'systeem',
          why: 'De i-klank schrijf je hier met y: systeem.',
        },
        {
          q: 'Meervoud van het woord voor pillen of drankjes van de dokter',
          say: 'medicijnen',
          before: 'Neem je',
          after: 'mee naar het ziekenhuis.',
          a: 'medicijnen',
          also: ['geneesmiddelen'],
          why: 'c voor i klinkt als s, en -ijn schrijf je met ij: medicijnen.',
        },
        {
          q: 'Een lijst met vragen die je invult (je hoort *ang-kè-te*)',
          before: 'Vul na de cursus de',
          after: 'in.',
          a: 'enquête',
          why: 'qu klinkt hier als k, en het accent op de ê hoort vast bij het woord: enquête.',
        },
        {
          q: 'De korte rust tussen twee lessen',
          before: 'In de',
          after: 'drinken we koffie.',
          a: 'pauze',
          why: 'au, net als in auto. En je hoort een z: pauze.',
        },
        {
          q: 'Een uitstapje met je cursus of je werk, bijvoorbeeld naar een museum',
          say: 'excursie',
          before: 'Vrijdag gaan we met de cursus op',
          after: 'naar het museum.',
          a: 'excursie',
          why: 'ks → x, de k-klank voor u → c, en sie na een r → -sie: excursie.',
        },
      ],
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail van het hotel aan. Typ elk woord helemaal.',
      intro: 'In het grijs staat wat je hoort of waar het woord van komt.',
      title: 'Mail van het hotel',
      text: 'Beste mevrouw Yilmaz,\n\nBedankt voor uw boeking. In deze mail vindt u alle {informatie|van informeren|Je hoort tsie aan het eind: -tie.} over uw {verblijf|van verblijven|Aan het eind nooit een v: verblijf. En ij, net als in blijven.} bij ons.\n\nUw kamer ligt op de derde {etage|ee-taa-zje|De zj-klank in -age schrijf je met g: etage.} en heeft een eigen {douche|doe-sje|oe → ou en sj → ch: douche.}. Vanaf het balkon kijkt u uit over het {strand|zand aan zee|stranden: dus d.}. Het ontbijt staat elke ochtend tot tien uur klaar in ons {restaurant|res-too-rant|De oo-klank schrijf je hier als au: restaurant.}. Komt u met de auto? Dan parkeert u in de {garage|ga-raa-zje|-age klinkt als aazje: garage, met g.} onder het hotel. Na het uitchecken kunt u uw {bagage|ba-gaa-zje|Eén g in het midden en g voor de zj-klank: bagage.} nog bij de {receptie|re-sep-sie|c voor e klinkt als s. Na de p hoor je sie, maar je schrijft -tie: receptie.} laten staan.\n\nWilt u de stad bekijken? Elke zaterdag is er een {excursie|eks-kur-sie|ks → x, k-klank voor u → c, en -sie: excursie.}. Voor de deur staan altijd {taxi’s|meervoud van taxi|Woord op i: meervoud met ’s.}. Heeft u een allergie? Laat het ons weten, dan past onze {chef|sjef|De sj-klank in een leenwoord schrijf je met ch: chef.} het menu voor u aan.\n\nVoor vaste gasten ligt er een klein {cadeautje|ka-doo-tje|cadeau + tje: cadeautje. De eau blijft staan.} op de kamer. Na uw vertrek krijgt u een korte {enquête|ang-kè-te|qu klinkt hier als k, en het accent op de ê hoort bij het woord.}. Heeft u {ideeën|meervoud van idee|idee + en: ideeën, met een trema op de laatste e.} om ons hotel nog {gezelliger|gezellig + er|-ig blijft -ig, ook met -er erachter: gezelliger.} te maken? Dan horen wij dat graag.\n\nMet vriendelijke groet,\n\nKevin de Bruin\nHotel Zeezicht',
      why: 'Leenwoorden: -tie (informatie, receptie), -sie (excursie), g voor de zj-klank (etage, garage, bagage), ou en ch (douche), au (restaurant), eau (cadeautje) en qu met ê (enquête). Verder: f aan het eind (verblijf), d door langer maken (strand), ’s na een i (taxi’s), een trema (ideeën) en -ig (gezelliger).',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen. Hoofdletters en leestekens tellen mee.',
      title: 'Een spannende dag',
      sentences: [
        'Op maandag had ik een sollicitatiegesprek bij een reclamebureau in het centrum.',
        'De receptioniste bracht me naar de bovenste etage en gaf me een kop thee.',
        'De directeur vroeg naar mijn ervaring, mijn hobby’s en mijn kennis van computers.',
        'Daarna kreeg ik een korte enquête over mijn ideeën voor nieuwe producten.',
        'Ze vond mijn antwoorden heel origineel en gaf me een mooi compliment.',
        'Morgen hoor ik van de directeur of ik de functie krijg.',
      ],
      right:
        'Alles goed: sollicitatiegesprek, reclamebureau, centrum, receptioniste, etage, thee, directeur, hobby’s, enquête, ideeën, producten, origineel, compliment en functie.',
      wrong:
        'Kijk na: sollicitatiegesprek (ll, twee keer c, -tie, aan elkaar), reclamebureau (c en eau), receptioniste (c en t, net als receptie), directeur (c), etage (g), thee (th), hobby’s (y en ’s), enquête (qu en ê), ideeën (trema), origineel (g voor de zj-klank), compliment (c) en functie (-tie). En maandag met een kleine letter.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail na voordat hij naar het team gaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'Team Financiën', subject: 'Uitje vrijdag' },
      greeting: 'Hoi allemaal,',
      signoff: 'Groetjes,\nNadia',
      tokens: [
        { t: 'We' },
        { t: 'gaan' },
        { t: 'Vrijdag', fix: 'vrijdag', why: 'Een dag schrijf je met een kleine letter, behalve aan het begin van een zin.' },
        { t: 'met' },
        { t: 'de' },
        { t: 'hele' },
        { t: 'afdeling' },
        { t: 'op' },
        { t: 'excursie' },
        { t: 'naar' },
        { t: 'Utrecht.' },
        { t: 'De' },
        { t: 'bus' },
        { t: 'vertrekt' },
        { t: 'om' },
        { t: 'half' },
        { t: 'negen' },
        { t: 'bij' },
        { t: 'het' },
        { t: 'kantoor.', trap: 'Goed: kantoor schrijf je met een k. Een k-klank vooraan kan c of k zijn; dit woord heeft een k.' },
        { t: 'De' },
        { t: 'chaufeur', fix: 'chauffeur', why: 'chauffeur met ff: ch, au, ff en eu.' },
        { t: 'wacht' },
        { t: 'op' },
        { t: 'de' },
        { t: 'parkeerplaats' },
        { t: 'achter' },
        { t: 'de' },
        { t: 'garage.' },
        { t: 'Neem' },
        { t: 'niet' },
        { t: 'te' },
        { t: 'veel' },
        { t: 'baggage', fix: 'bagage', why: 'bagage met één g in het midden en g voor de zj-klank.' },
        { t: 'mee,' },
        { t: 'want' },
        { t: 'we' },
        { t: 'lopen' },
        { t: 'veel.' },
        { t: 'Eerst' },
        { t: 'bezoeken' },
        { t: 'we' },
        { t: 'een' },
        { t: 'fabriek', trap: 'Goed: woorden op -iek schrijf je met een k, zoals muziek en techniek.' },
        { t: 'waar' },
        { t: 'ze' },
        { t: 'chocola' },
        { t: 'maken.' },
        { t: 'Daarna' },
        { t: 'lunchen' },
        { t: 'we' },
        { t: 'in' },
        { t: 'een' },
        { t: 'restaurant' },
        { t: 'in' },
        { t: 'het' },
        { t: 'sentrum.', fix: 'centrum.', why: 'centrum schrijf je met een c: c voor e klinkt als s.' },
        { t: 'Heb' },
        { t: 'je' },
        { t: 'een' },
        { t: 'allergie?' },
        { t: 'Geef' },
        { t: 'het' },
        { t: 'dan' },
        { t: 'op' },
        { t: 'tijd' },
        { t: 'aan' },
        { t: 'mij' },
        { t: 'door.' },
        { t: 'Na' },
        { t: 'de' },
        { t: 'lunch' },
        { t: 'doen' },
        { t: 'we' },
        { t: 'een' },
        { t: 'quiz', trap: 'Goed: quiz schrijf je met qu, net als aquarium.' },
        { t: 'op' },
        { t: 'hoog' },
        { t: 'nivo,', fix: 'niveau,', why: 'De oo-klank aan het eind schrijf je hier als eau: niveau.' },
        { t: 'met' },
        { t: 'mooije', fix: 'mooie', why: 'oo + j-klank: ooi. mooi + e = mooie, zonder j.' },
        { t: 'cadeaus', trap: 'Goed: na eau komt alleen een s, zonder apostrof.' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'winnaars.' },
        { t: 'Laat' },
        { t: 'even' },
        { t: 'een' },
        { t: 'reaktie', fix: 'reactie', why: 'reactie, net als actie: in leenwoorden is een k-klank voor een t meestal een c.' },
        { t: 'achter' },
        { t: 'als' },
        { t: 'je' },
        { t: 'niet' },
        { t: 'mee' },
        { t: 'kunt.' },
        { t: 'Meer' },
        { t: 'informatie' },
        { t: 'over' },
        { t: 'de' },
        { t: 'route' },
        { t: 'staat' },
        { t: 'in' },
        { t: 'de' },
        { t: 'brosjure', fix: 'brochure', why: 'De sj-klank in een leenwoord schrijf je met ch: brochure.' },
        { t: 'in' },
        { t: 'de' },
        { t: 'bijlage.' },
        { t: 'Het' },
        { t: 'wordt' },
        { t: 'vast' },
        { t: 'gezellich!', fix: 'gezellig!', why: 'Je hoort uhg aan het eind: -ig, nooit -ich.' },
      ],
      done: {
        title: 'De mail kan weg',
        text: 'vrijdag, chauffeur, bagage, centrum, niveau, mooie, reactie, brochure en gezellig. kantoor, fabriek, quiz en cadeaus stonden al goed.',
      },
    },
  ],
};
