import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": ’t kofschip, de verleden tijd (-te of -de) en het voltooid deelwoord (-t of -d) van zwakke werkwoorden. */
export const LES_K39: LessonInput = {
  id: 'k39',
  stage: 'regels',
  domain: 'orth',
  also: ['morf'],
  title: '’t Kofschip: -te of -de, -t of -d?',
  skill: 'Spelling',
  icon: '-te',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Van stam naar verleden tijd',
      panels: [
        {
          text: 'Veel werkwoorden maken de verleden tijd met *-te* of *-de*: *ik werkte*, *ik belde*. Het voltooid deelwoord krijgt *ge-* en een *t* of *d*: *gewerkt*, *gebeld*. Dat zijn de *zwakke* werkwoorden. Je begint altijd bij de *stam*: het hele werkwoord min *-en*. Daarbij gelden de gewone spellingregels: *maken* → *maak*, *stoppen* → *stop*, *leven* → *leef*, *reizen* → *reis*.',
          rule: 'Stam = hele werkwoord min *-en*: *werken* → *werk*, *maken* → *maak*, *stoppen* → *stop*.',
          lab: {
            label: 'Tik een werkwoord',
            chips: [
              { k: 'werken', out: 'stam: werk', note: 'werken min -en.' },
              { k: 'maken', out: 'stam: maak', note: 'Gesloten lettergreep: twee a’s.' },
              { k: 'stoppen', out: 'stam: stop', note: 'Geen dubbele p aan het eind.' },
              { k: 'leven', out: 'stam: leef', note: 'Aan het eind schrijf je f, geen v.' },
              { k: 'reizen', out: 'stam: reis', note: 'Aan het eind schrijf je s, geen z.' },
              { k: 'praten', out: 'stam: praat', note: 'De stam eindigt op een t.' },
            ],
          },
        },
        {
          text: 'Kijk nu naar de laatste letter van de stam. Zit die in *’t kofschip* (*t*, *k*, *f*, *s*, *ch*, *p*), dan krijg je *-te* in de verleden tijd en *-t* in het voltooid deelwoord: *werk-te*, *gewerkt*. Zit hij er niet in, dan *-de* en *-d*: *bel-de*, *gebeld*. Ook *x* en *sh* tellen mee: *faxen* → *faxte*, *gefaxt*; *crashen* → *crashte*, *gecrasht*.',
          rule: 'Laatste letter van de stam in ’t kofschip (+ x, sh): *-te*, *ge-…-t*. Anders: *-de*, *ge-…-d*.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik … (gisteren)', 'ik heb …'],
            rows: [
              { label: 'werken', cells: [{ fill: 'werkte' }, { fill: 'gewerkt', hint: 'k zit in ’t kofschip: -t.' }] },
              {
                label: 'bellen',
                cells: [
                  { fill: 'belde', hint: 'l zit niet in ’t kofschip: -de.' },
                  { fill: 'gebeld', hint: 'l zit niet in ’t kofschip: -d.' },
                ],
              },
              { label: 'stoppen', cells: [{ fill: 'stopte', hint: 'Stam stop, p zit in ’t kofschip.' }, { fill: 'gestopt' }] },
              { label: 'wonen', cells: [{ fill: 'woonde', hint: 'Stam woon, n zit niet in ’t kofschip.' }, { fill: 'gewoond' }] },
              { label: 'fietsen', cells: [{ fill: 'fietste' }, { fill: 'gefietst', hint: 's zit in ’t kofschip: -t.' }] },
              { label: 'faxen', cells: [{ fill: 'faxte', hint: 'x telt mee met ’t kofschip.' }, { fill: 'gefaxt' }] },
            ],
            extra: ['werkde', 'gebelt', 'stopde', 'woonte', 'gefietsd'],
            note: 'werk, stop, fiets en fax: -te en -t. bel en woon: -de en -d.',
          },
        },
        {
          text: 'In het meervoud komt er een *n* achter: *wij werkten*, *jullie belden*, *zij woonden*. Het voltooid deelwoord gebruik je met *hebben* of *zijn*: *ik heb gewerkt*, *ik ben verhuisd*. Begint het werkwoord met *be-*, *ver-*, *her-*, *ont-* of *ge-*, dan komt er geen extra *ge-* bij. De t of d volgt gewoon dezelfde regel: *betalen* → *betaald*, *vertalen* → *vertaald*, *herhalen* → *herhaald*, *gebeuren* → *gebeurd*. Let op: in *bellen* en *verven* zijn *be* en *ver* geen los stukje. Die krijgen wel *ge-*: *gebeld*, *geverfd*.',
          rule: 'Meervoud: *-ten* of *-den*. Voltooid deelwoord zonder ge- bij be-, ver-, her-, ont-, ge-: *betaald*, *gebeurd*.',
          build: {
            before: 'Tien jaar geleden: wij',
            stem: 'woon',
            endings: ['den', 'ten', 'de', 'te'],
            answer: 'den',
            note: 'wij woonden: n zit niet in ’t kofschip, dus -de, en in het meervoud -den.',
          },
          quiz: {
            q: 'Je collega vraagt: "Wat is er …?"',
            options: ['gebeurd', 'gebeurt', 'gebeurdt'],
            answer: 'gebeurd',
            why: 'Voltooid deelwoord van gebeuren: stam gebeur, r zit niet in ’t kofschip, dus -d. Geen extra ge-, want het begint al met ge-.',
          },
        },
        {
          text: 'Onthoud de letters met een ezelsbruggetje: *’t kofschip* of *soft ketchup*. In beide zitten *t*, *k*, *f*, *s*, *ch* en *p*; de klinkers tellen niet mee. Let op: dit geldt alleen voor zwakke werkwoorden. *Sterke* werkwoorden veranderen hun klinker en krijgen geen *-te* of *-de*: *lopen* → *liep*, *gelopen*; *kijken* → *keek*, *gekeken*; *kopen* → *kocht*, *gekocht*. Die leer je uit je hoofd.',
          rule: '’t kofschip of soft ketchup: t, k, f, s, ch, p. Alleen voor zwakke werkwoorden.',
          quiz: {
            q: 'Gisteren … ik de hele avond met mijn vrienden. (dansen)',
            options: ['danste', 'dansde', 'dans'],
            answer: 'danste',
            why: 'Stam dans, s zit in ’t kofschip: danste. In dansen hoor en schrijf je een s, geen z.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'te-de',
      prompt: 'Krijgt de verleden tijd -te of -de?',
      buckets: ['-te', '-de'],
      items: [
        { t: 'kuchen', b: 0 },
        { t: 'boffen', b: 0 },
        { t: 'klappen', b: 0 },
        { t: 'mixen', b: 0 },
        { t: 'poetsen', b: 0 },
        { t: 'knikken', b: 0 },
        { t: 'rapen', b: 0 },
        { t: 'kletsen', b: 0 },
        { t: 'plagen', b: 1 },
        { t: 'volgen', b: 1 },
        { t: 'leggen', b: 1 },
        { t: 'vlaggen', b: 1 },
        { t: 'krabben', b: 1 },
        { t: 'schrobben', b: 1 },
        { t: 'dweilen', b: 1 },
        { t: 'zeilen', b: 1 },
      ],
      why: 'kuchte, bofte, klapte, mixte, poetste, knikte, raapte, kletste: stam op ch, f, p, x, s of k. plaagde, volgde, legde, vlagde, krabde, schrobde, dweilde, zeilde: stam op g, b of l. Let op: g en b zitten niet in ’t kofschip, ook al klinken ze aan het eind als ch en p.',
    },
    {
      kind: 'type',
      id: 'stofzuigde',
      prompt: 'Typ de verleden tijd van stofzuigen.',
      before: 'Zaterdag',
      after: 'ik het hele huis.',
      hint: '',
      answer: 'stofzuigde',
      why: 'Stam stofzuig, g zit niet in ’t kofschip: -de. Ook al klinkt de g aan het eind als ch.',
    },
    {
      kind: 'choice',
      id: 'overgemaakt',
      prompt: 'Kies de goede vorm.',
      before: 'Het geld is gisteren al naar uw rekening',
      after: '.',
      options: ['overgemaakt', 'overgemaakd', 'over gemaakt', 'overgemaakte'],
      answer: 'overgemaakt',
      why: 'Stam maak, k zit in ’t kofschip: gemaakt. Met over ervoor is het één woord: overgemaakt. Zonder zelfstandig naamwoord erachter komt er geen -e bij.',
    },
    {
      kind: 'swipe',
      id: 'kofschip-zinnen',
      prompt: 'Klopt de werkwoordsvorm?',
      intro: 'Sommige zinnen lijken fout, maar zijn goed.',
      cards: [
        { t: 'Na drie trappen hijgde ik als een oude man.', ok: true, why: 'Stam hijg, g zit niet in ’t kofschip: hijgde.' },
        { t: 'Ik heb mijn moeder gisteren gebelt.', ok: false, fix: 'gebelt → gebeld', why: 'Stam bel, l zit niet in ’t kofschip: gebeld.' },
        { t: 'Mijn man snurkte de hele nacht.', ok: true, why: 'Stam snurk, k zit in ’t kofschip: snurkte.' },
        { t: 'Het water ebte langzaam weg.', ok: false, fix: 'ebte → ebde', why: 'Stam eb, b zit niet in ’t kofschip: ebde.' },
        { t: 'Wij hoopten op beter weer.', ok: true, why: 'Stam hoop, p zit in ’t kofschip: hoopte, meervoud hoopten.' },
        { t: 'Ik zorgte vroeger voor mijn opa.', ok: false, fix: 'zorgte → zorgde', why: 'Stam zorg, g zit niet in ’t kofschip: zorgde.' },
        { t: 'Hij heeft zijn rijbewijs gehaald.', ok: true, why: 'Stam haal, l zit niet in ’t kofschip: gehaald.' },
        {
          t: 'De klant heeft de rekening nog niet betaalt.',
          ok: false,
          fix: 'betaalt → betaald',
          why: 'Stam betaal, l zit niet in ’t kofschip: betaald. Betaalt is de tegenwoordige tijd: hij betaalt.',
        },
        { t: 'Mijn laptop crashte gisteren twee keer.', ok: true, why: 'sh telt mee met ’t kofschip: crashte.' },
        { t: 'Ik heb het formulier al gecheckt.', ok: true, why: 'Stam check, k zit in ’t kofschip: gecheckt.' },
        { t: 'Het publiek juichde na het doelpunt.', ok: false, fix: 'juichde → juichte', why: 'Stam juich, ch zit in ’t kofschip: juichte.' },
        { t: 'We hebben de hele middag dozen gesjouwd.', ok: true, why: 'Stam sjouw, w zit niet in ’t kofschip: gesjouwd.' },
      ],
    },
    {
      kind: 'fix',
      id: 'gerepareerd',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'De monteur kwam om negen uur, belde aan en heeft de verwarming snel gerepareert.',
      wrong: 13,
      answer: 'gerepareerd',
      why: 'Stam repareer, r zit niet in ’t kofschip: gerepareerd. Belde is goed: stam bel, dus -de.',
    },
    {
      kind: 'type',
      id: 'tobden',
      prompt: 'Typ de verleden tijd van tobben.',
      before: 'Wij',
      after: 'wekenlang over de verhuizing.',
      hint: '',
      answer: 'tobden',
      why: 'Stam tob (één b), b zit niet in ’t kofschip: -de. Bij wij komt er -n achter: tobden.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'De valkuilen van ’t kofschip',
      panels: [
        {
          text: 'Valkuil 1: de *v* en de *z*. De stam van *leven* is *leef* en die van *reizen* is *reis*. De f en de s zitten in ’t kofschip, maar toch schrijf je *-de*. Kijk daarom bij een stam op *f* of *s* naar het hele werkwoord. Staat daar een *v* of *z*, dan krijg je *-de* en *-d*: *leefde*, *geleefd*; *reisde*, *gereisd*. Staat er een f of s, dan blijft het *-te*: *fietsen* → *fietste*, *blaffen* → *blafte*.',
          rule: 'v of z in het hele werkwoord: *-de*, *-d*. Dus *leven* → *leefde*, *reizen* → *reisde*.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik … (gisteren)', 'ik heb / ben …'],
            rows: [
              { label: 'leven', cells: [{ fill: 'leefde', hint: 'In leven staat een v: -de.' }, { fill: 'geleefd' }] },
              {
                label: 'reizen',
                cells: [
                  { fill: 'reisde', hint: 'In reizen staat een z: -de.' },
                  { fill: 'gereisd', hint: 'In reizen staat een z: -d.' },
                ],
              },
              { label: 'verhuizen', cells: [{ fill: 'verhuisde' }, { fill: 'verhuisd', hint: 'Geen ge-, en de z in verhuizen geeft -d.' }] },
              { label: 'beloven', cells: [{ fill: 'beloofde' }, { fill: 'beloofd', hint: 'Geen ge-, en de v in beloven geeft -d.' }] },
              { label: 'durven', cells: [{ fill: 'durfde', hint: 'In durven staat een v: -de.' }, { fill: 'gedurfd' }] },
            ],
            extra: ['leefte', 'gereist', 'verhuiste', 'beloofte', 'gedurft'],
            note: 'Alle vijf hebben een v of z in het hele werkwoord. Daarom -de en -d, ook al eindigt de stam op f of s.',
          },
        },
        {
          text: 'Valkuil 2: de stam eindigt al op *t* of *d*. In de verleden tijd plak je er gewoon *-te* of *-de* achter. Dan krijg je twee t’s of twee d’s: *praten* → *praatte*, *wachten* → *wachtte*, *zetten* → *zette*, *antwoorden* → *antwoordde*, *landen* → *landde*, *melden* → *meldde*. In het voltooid deelwoord komt er niets bij: *gepraat*, *gewacht*, *gezet*, *geantwoord*, *geland*, *gemeld*.',
          rule: 'Stam op t: *-te* (*praatte*), deelwoord *gepraat*. Stam op d: *-de* (*antwoordde*), deelwoord *geantwoord*.',
          build: {
            before: 'Gisteren',
            stem: 'antwoord',
            endings: ['de', 'te', 'e', ''],
            answer: 'de',
            note: 'Stam antwoord + de = antwoordde. Twee d’s, want je plakt -de achter een stam die al op d eindigt.',
          },
          deep: {
            q: 'En zetten → zette, met één t?',
            a: 'De stam is *zet* (één t, want een stam eindigt niet op twee dezelfde medeklinkers). *zet* + *te* = *zette*. Zo ook *redden* → *red* + *de* = *redde*, en het deelwoord *gered*.',
          },
        },
        {
          text: 'Valkuil 3: het voltooid deelwoord als bijvoeglijk naamwoord. De t of d blijft staan, en er komt een *-e* achter: *geplakt* → *de geplakte foto*, *gestopt* → *de gestopte trein*, *verwarmd* → *het verwarmde huis*, *betaald* → *de betaalde rekening*. Ook Engelse werkwoorden volgen ’t kofschip: *mailen* → *mailde*, *gemaild*; *scoren* → *scoorde*, *gescoord*; *printen* → *printte*, *geprint*; *downloaden* → *downloadde*, *gedownload*; *crashen* → *crashte*, *gecrasht*.',
          rule: 'De t of d blijft: *de geplakte foto*, *het verwarmde huis*. Engelse werkwoorden: ook ’t kofschip (*gemaild*, *gecrasht*).',
          lab: {
            label: 'Tik een werkwoord',
            chips: [
              { k: 'mailen', out: 'mailde · gemaild', note: 'Stam mail, l: -de en -d.' },
              { k: 'scoren', out: 'scoorde · gescoord', note: 'Stam scoor, r: -de en -d.' },
              { k: 'printen', out: 'printte · geprint', note: 'Stam print, t: -te, en in het deelwoord geen extra t.' },
              { k: 'downloaden', out: 'downloadde · gedownload', note: 'Stam download, d: -de, en in het deelwoord geen extra d.' },
              { k: 'crashen', out: 'crashte · gecrasht', note: 'Stam crash, sh telt mee: -te en -t.' },
              { k: 'plakken', out: 'de geplakte foto', note: 'geplakt + e: de t blijft staan.' },
            ],
          },
          deep: {
            q: 'En updaten of liken?',
            a: 'Daar eindigt de stam op een e die je niet hoort: *update*, *like*. Dan kijk je naar de laatste klank die je wel hoort: een t-klank en een k-klank. Dus *updatete*, *geüpdatet* en *likete*, *geliket*.',
          },
        },
        {
          text: 'Stappenplan bij twijfel. 1. Verandert de klinker (*lopen* → *liep*)? Dan is het een sterk werkwoord: leren. 2. Maak de stam. 3. Staat er een v of z in het hele werkwoord? Dan *-de* en *-d*. 4. Laatste letter van de stam in ’t kofschip? Dan *-te* en *-t*, anders *-de* en *-d*. Handige controle voor het voltooid deelwoord: je hoort de t of d aan het eind niet goed, maar de verleden tijd vertelt het je: *belde* → *gebeld*, *werkte* → *gewerkt*.',
          rule: 'Twijfel je over -t of -d aan het eind? Maak de verleden tijd: *-de* → *-d*, *-te* → *-t*.',
          quiz: {
            q: 'Ik heb het pakket gisteren …',
            options: ['verstuurd', 'verstuurt', 'verstuurdt'],
            answer: 'verstuurd',
            why: 'Verleden tijd: verstuurde, met -de. Dus het voltooid deelwoord is verstuurd. Verstuurt is de tegenwoordige tijd: hij verstuurt.',
          },
          deep: {
            q: 'Zijn er werkwoorden die half zwak, half sterk zijn?',
            a: 'Ja, een paar. Ze krijgen *-te* of *-de* in de verleden tijd, maar een voltooid deelwoord op *-en*: *lachen* → *lachte*, *gelachen*; *bakken* → *bakte*, *gebakken*; *wassen* → *waste*, *gewassen*. Die leer je uit je hoofd.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'v-z',
      prompt: 'Kijk naar het hele werkwoord. -te of -de?',
      buckets: ['-te', '-de'],
      items: [
        { t: 'fietsen', b: 0 },
        { t: 'dansen', b: 0 },
        { t: 'missen', b: 0 },
        { t: 'straffen', b: 0 },
        { t: 'kussen', b: 0 },
        { t: 'blaffen', b: 0 },
        { t: 'bluffen', b: 0 },
        { t: 'ruisen', b: 0 },
        { t: 'leven', b: 1 },
        { t: 'reizen', b: 1 },
        { t: 'verhuizen', b: 1 },
        { t: 'geloven', b: 1 },
        { t: 'verven', b: 1 },
        { t: 'vrezen', b: 1 },
        { t: 'niezen', b: 1 },
        { t: 'zweven', b: 1 },
      ],
      why: 'fietste, danste, miste, strafte, kuste, blafte, blufte, ruiste: s of f in het hele werkwoord. leefde, reisde, verhuisde, geloofde, verfde, vreesde, niesde, zweefde: v of z in het hele werkwoord.',
    },
    {
      kind: 'proofread',
      id: 'mail-mark',
      prompt: 'Vind de fouten in dit mailtje.',
      intro: 'Kijk naar elk werkwoord in de verleden tijd en elk voltooid deelwoord.',
      header: { to: 'Mark', subject: 'Gisteren' },
      greeting: 'Hoi Mark,',
      signoff: 'Groet,\nIlse',
      tokens: [
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'gisteren' },
        { t: 'de' },
        { t: 'hele' },
        { t: 'dag' },
        { t: 'gewerkd.', fix: 'gewerkt.', why: 'Stam werk, k zit in ’t kofschip: gewerkt.' },
        { t: 'Daarna' },
        { t: 'fietste' },
        { t: 'ik' },
        { t: 'naar' },
        { t: 'huis.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'je' },
        { t: 'gebelt,', fix: 'gebeld,', why: 'Stam bel, l zit niet in ’t kofschip: gebeld.' },
        { t: 'maar' },
        { t: 'je' },
        { t: 'antwoorde', fix: 'antwoordde', why: 'Stam antwoord + de: antwoordde, met twee d’s.' },
        { t: 'niet.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'het' },
        { t: 'pakket' },
        { t: 'verstuurt', fix: 'verstuurd', why: 'Verleden tijd verstuurde, dus voltooid deelwoord verstuurd.' },
        { t: 'en' },
        { t: 'de' },
        { t: 'rekening' },
        { t: 'betaald.' },
        { t: 'Wat' },
        { t: 'is' },
        { t: 'er' },
        { t: 'gebeurt?', fix: 'gebeurd?', why: 'Voltooid deelwoord van gebeuren: gebeurd.' },
      ],
      done: {
        title: 'Alle werkwoorden gecontroleerd',
        text: 'gewerkt, gebeld, antwoordde, verstuurd en gebeurd. fietste en betaald stonden al goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-verhuisde',
      prompt: 'Luister en typ de zin.',
      sentence: 'Vorige week verhuisde mijn zus. Ik verfde haar keuken en sjouwde alle dozen naar boven.',
      right: 'Goed: verhuisde en verfde met -de, want in verhuizen staat een z en in verven een v. En sjouwde met -de: w zit niet in ’t kofschip.',
      wrong: 'Let op: verhuisde (verhuizen, met z), verfde (verven, met v) en sjouwde (stam sjouw). Alle drie -de.',
    },
    {
      kind: 'fix',
      id: 'beantwoord',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Hij heeft mijn mail van vorige week nog steeds niet beantwoordt.',
      wrong: 10,
      answer: 'beantwoord',
      why: 'Stam beantwoord eindigt al op d. In het voltooid deelwoord komt er niets bij, ook geen t: beantwoord.',
    },
    {
      kind: 'rewrite',
      id: 'wachtten',
      prompt: 'Zet de zin in de verleden tijd.',
      source: 'Wij wachten op de monteur, praten over het werk en zetten koffie.',
      accept: ['Wij wachtten op de monteur, praatten over het werk en zetten koffie.'],
      why: 'wacht + te = wachtte, praat + te = praatte, zet + te = zette. Bij wij komt er -n achter: wachtten, praatten, zetten. Zetten ziet er in de verleden tijd dus hetzelfde uit als nu.',
    },
    {
      kind: 'swipe',
      id: 'valkuil-zinnen',
      prompt: 'Klopt de werkwoordsvorm?',
      intro: 'Sommige zinnen lijken fout, maar zijn goed.',
      cards: [
        { t: 'Wij verhuisden vorig jaar naar Almere.', ok: true, why: 'verhuizen heeft een z: -de, meervoud -den.' },
        { t: 'Ze reiste drie weken door Marokko.', ok: false, fix: 'reiste → reisde', why: 'In reizen staat een z: reisde.' },
        { t: 'Hij praatte de hele vergadering door.', ok: true, why: 'Stam praat + te: praatte.' },
        { t: 'Wie heeft de wekker op zes uur gezet?', ok: true, why: 'Stam zet eindigt al op t: in het deelwoord komt er niets bij. gezet.' },
        { t: 'Het vliegtuig landde precies op tijd.', ok: true, why: 'Stam land + de: landde.' },
        { t: 'Ik heb het bestand gisteren gedownload.', ok: true, why: 'Stam download eindigt op d: er komt niets bij.' },
        { t: 'Wie heeft het laatste doelpunt gescoort?', ok: false, fix: 'gescoort → gescoord', why: 'Stam scoor, r zit niet in ’t kofschip: gescoord.' },
        { t: 'De directeur antwoorde niet op mijn vraag.', ok: false, fix: 'antwoorde → antwoordde', why: 'Stam antwoord + de: antwoordde, met twee d’s.' },
        { t: 'Ik heb de app vanochtend geüpdatet.', ok: true, why: 'Bij update hoor je aan het eind een t-klank: -t. En ge + u krijgt een trema: geüpdatet.' },
        { t: 'Mijn opa durfte nooit te vliegen.', ok: false, fix: 'durfte → durfde', why: 'In durven staat een v: durfde.' },
        { t: 'De geverfde deur is nog nat.', ok: true, why: 'geverfd (verven, met v) + e: geverfde. De d blijft staan.' },
        { t: 'Na de les heb ik mijn docent gemailt.', ok: false, fix: 'gemailt → gemaild', why: 'Stam mail, l zit niet in ’t kofschip: gemaild.' },
      ],
    },
    {
      kind: 'type',
      id: 'geirriteerde',
      prompt: 'Maak van het voltooid deelwoord van irriteren een bijvoeglijk naamwoord.',
      before: 'De',
      after: 'klant wilde de manager spreken.',
      hint: '',
      answer: 'geïrriteerde',
      why: 'Stam irriteer, r zit niet in ’t kofschip: geïrriteerd. Met -e erachter: geïrriteerde. En ge + i krijgt een trema: geï.',
    },
    {
      kind: 'bet',
      id: 'downloadde',
      prompt: 'Ik … gisteren een nieuwe app.',
      intro: 'Welke vorm van downloaden is goed?',
      options: ['downloadde', 'downloadte', 'downloade', 'downloadden'],
      answer: 'downloadde',
      why: 'Stam download, d zit niet in ’t kofschip: download + de = downloadde. Net als antwoordde. Downloadden is het meervoud: wij downloadden.',
    },
    {
      kind: 'dictation',
      id: 'dictee-gebeurd',
      prompt: 'Luister en typ de zin.',
      sentence: 'Wat is er gebeurd? De trein stopte plotseling. Pas na tien minuten verontschuldigde de conducteur zich.',
      right: 'Goed: gebeurd met d, stopte met -te en verontschuldigde met -de. En conducteur met c.',
      wrong:
        'Let op: gebeurd (gebeurde, dus -d), stopte (p zit in ’t kofschip), verontschuldigde (stam verontschuldig, g zit niet in ’t kofschip) en conducteur (c).',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Vierentwintig opdrachten door elkaar, ook uit eerdere lessen. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Verleden tijd van *verhuizen*',
          before: 'Vorig jaar',
          after: 'mijn ouders naar Groningen.',
          a: 'verhuisden',
          why: 'In verhuizen staat een z: -de. Meervoud: verhuisden.',
        },
        {
          q: 'Voltooid deelwoord van *coachen*',
          before: 'Zij heeft ons team drie jaar',
          after: '.',
          a: 'gecoacht',
          why: 'Stam coach eindigt op ch, en ch zit in ’t kofschip: gecoacht.',
        },
        {
          q: 'Vul de vorm van *leven* in (nu)',
          before: 'Mijn oom',
          after: 'heel gezond.',
          a: 'leeft',
          why: 'Stam leef: aan het eind nooit een v. Met t erachter: leeft.',
        },
        {
          q: 'Verleden tijd van *melden*',
          before: 'Gisteren',
          after: 'zij zich ziek bij haar baas.',
          a: 'meldde',
          why: 'Stam meld + de: meldde, met twee d’s.',
        },
        {
          q: 'Voltooid deelwoord van *haasten*',
          before: 'Ik heb me erg',
          after: 'en toch was de bus al weg.',
          a: 'gehaast',
          why: 'Stam haast eindigt al op t: er komt niets bij. gehaast.',
        },
        {
          q: 'Zelfstandig naamwoord van *opereren*',
          before: 'Na de',
          after: 'mag u een week niet werken.',
          a: 'operatie',
          why: 'Je hoort tsie aan het eind: -tie. operatie.',
        },
        {
          q: 'Verleden tijd van *verven*',
          before: 'Wij',
          after: 'de muren van de woonkamer wit.',
          a: 'verfden',
          why: 'In verven staat een v: -de. verfde, meervoud verfden.',
        },
        {
          q: 'Voltooid deelwoord van *storen*',
          before: 'Sorry dat ik je',
          after: 'heb.',
          a: 'gestoord',
          why: 'Stam stoor, r zit niet in ’t kofschip: gestoord.',
        },
        { q: 'Meervoud van *knie*', before: 'Na het voetballen deden mijn', after: 'pijn.', a: 'knieën', why: 'knie + en: knieën, met een trema op de e.' },
        { q: 'Verleden tijd van *redden*', before: 'De brandweer', after: 'twee kinderen uit het huis.', a: 'redde', why: 'Stam red (één d) + de: redde.' },
        {
          q: 'Voltooid deelwoord van *branden*',
          before: 'Het lampje heeft de hele nacht',
          after: '.',
          a: 'gebrand',
          why: 'Stam brand eindigt al op d: er komt niets bij. gebrand.',
        },
        { q: 'Vul de vorm van *liggen* in (nu)', before: 'De sleutel', after: 'onder de mat.', a: 'ligt', why: 'liggen heeft een g: ligt, niet licht.' },
        {
          q: 'Verleden tijd van *bonzen*',
          before: 'De buren',
          after: 'midden in de nacht op de deur.',
          a: 'bonsden',
          why: 'In bonzen staat een z: -de. bonsde, meervoud bonsden.',
        },
        {
          q: 'Verleden tijd van *pinnen*',
          before: 'Ik',
          after: 'vijftig euro bij de automaat.',
          a: 'pinde',
          why: 'Stam pin (één n), n zit niet in ’t kofschip: pinde.',
        },
        {
          q: 'Leenwoord: wie de vrachtwagen rijdt. Je hoort ‘sjoo-feur’.',
          say: 'chauffeur',
          before: 'De',
          after: 'stopte bij het tankstation.',
          a: 'chauffeur',
          why: 'sj → ch, oo → au, dan ff en eu: chauffeur.',
        },
        {
          q: 'Bijvoeglijk naamwoord van *beschadigen*',
          before: 'Breng het',
          after: 'pakket terug naar de winkel.',
          a: 'beschadigde',
          why: 'Stam beschadig, g zit niet in ’t kofschip: beschadigd. Met -e: beschadigde.',
        },
        {
          q: 'Elke week (van *week*)',
          before: 'Het team vergadert',
          after: '.',
          a: 'wekelijks',
          why: 'week + e + lijks: we-ke-lijks. Eén e in we-, en -lijks met ij en s.',
        },
        {
          q: 'Voltooid deelwoord van *updaten*',
          before: 'Ik heb mijn telefoon gisteren',
          after: '.',
          a: 'geüpdatet',
          why: 'Je hoort een t-klank aan het eind van de stam: -t. En ge + u krijgt een trema: geüpdatet.',
        },
        {
          q: 'Verleden tijd van *beven*',
          before: 'Haar handen',
          after: 'van de zenuwen.',
          a: 'beefden',
          why: 'In beven staat een v: -de. beefde, meervoud beefden.',
        },
        { q: 'Meervoud van *menu*', before: 'De', after: 'liggen al op tafel.', a: 'menu’s', why: 'Woord op u: meervoud met ’s.' },
        {
          q: 'Voltooid deelwoord van *ontmoeten*',
          before: 'Ik heb haar op een feest',
          after: '.',
          a: 'ontmoet',
          why: 'Geen ge-, want het begint met ont-. De stam ontmoet eindigt al op t: er komt niets bij.',
        },
        {
          q: 'Bijvoeglijk naamwoord van *drukken*',
          before: 'Ik wil graag de',
          after: 'versie van het contract.',
          a: 'gedrukte',
          why: 'gedrukt (stam druk, k) + e: gedrukte. De t blijft staan.',
        },
        {
          q: 'Zelfstandig naamwoord: wat de dokter om een wond doet',
          say: 'verband',
          before: 'De huisarts legde een',
          after: 'om mijn arm.',
          a: 'verband',
          also: ['zwachtel'],
          why: 'verbanden: dus d.',
        },
        {
          q: 'Verleden tijd van *schreeuwen*',
          before: 'De buurman',
          after: 'door het trappenhuis.',
          a: 'schreeuwde',
          why: 'eeuw blijft staan. Stam schreeuw, w zit niet in ’t kofschip: schreeuwde.',
        },
      ],
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail aan de verhuurder aan. Typ elk woord helemaal.',
      intro: 'In het grijs staat het hele werkwoord, de betekenis of waar het woord van komt.',
      title: 'Klacht over de verwarming',
      text: 'Beste meneer Visser,\n\nOp maandag 3 februari {meldde|melden|Stam meld + de: meldde, met twee d’s.} ik u dat de verwarming in onze woning het niet meer deed. U {beloofde|beloven|In beloven staat een v: -de. beloofde.} toen dat er snel een monteur zou komen. Daarna {wachtten|wachten|Stam wacht + te: wachtte. Bij wij: wachtten.} wij een hele week in een {koud|tegenovergestelde van warm|koude: dus d. En ou, want er staat een d na de klank.} huis. Ik heb in die week twee keer {gebeld|bellen|Stam bel, l zit niet in ’t kofschip: gebeld.}, maar niemand nam op. Mijn dochter werd ziek, en dat was niet goed voor haar {gezondheid|van gezond|gezond blijft gezond, ook met -heid erachter: gezondheid.}.\n\nAfgelopen dinsdag kwam de monteur eindelijk. Hij {repareerde|repareren|Stam repareer, r zit niet in ’t kofschip: repareerde.} de ketel binnen een uur. Daarbij {beschadigde|beschadigen|Stam beschadig, g zit niet in ’t kofschip: beschadigde.} hij de muur in de {badkamer|kamer met bad of douche|baden: dus d. Aan elkaar: badkamer.}, en hij {verontschuldigde|verontschuldigen|Stam verontschuldig, g zit niet in ’t kofschip: -de.} zich niet eens. Ik heb de schade {gefotografeerd|fotograferen|Stam fotografeer, r zit niet in ’t kofschip: gefotografeerd.} en de {foto’s|meervoud van foto|Woord op o: meervoud met ’s.} naar uw kantoor {gestuurd|sturen|Stam stuur, r zit niet in ’t kofschip: gestuurd.}. Tot nu toe heb ik nog geen {reactie|van reageren|c voor de t en -tie aan het eind: reactie.} gehad.\n\nDe huur van februari heb ik gewoon {betaald|betalen|Stam betaal, l zit niet in ’t kofschip: betaald. Geen ge-, want het begint met be-.}. Ik verwacht dus dat u de muur snel laat herstellen. Kunt u mij laten weten wat er nu {gebeurt|gebeuren|Hier is het de tegenwoordige tijd: het gebeurt nu. Stam gebeur + t.}?\n\nMet vriendelijke groet,\n\nSamira El Idrissi',
      why: 'Verleden tijd: -te na een stam uit ’t kofschip (wachtten), anders -de (meldde, beloofde, repareerde, beschadigde, verontschuldigde). Voltooid deelwoord: -d na een stam die niet in ’t kofschip zit (gebeld, gefotografeerd, gestuurd, betaald). Let op: gebeurt in de laatste zin is de tegenwoordige tijd. Verder: koud en gezondheid (d door langer maken), badkamer (d), foto’s (’s) en reactie (-tie).',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen. Hoofdletters en leestekens tellen mee.',
      title: 'Mijn eerste werkdag',
      sentences: [
        'Op mijn eerste werkdag fietste ik om half acht naar het kantoor in het centrum.',
        'Mijn nieuwe collega’s begroetten me hartelijk en zetten meteen koffie voor me.',
        'Daarna legde mijn leidinggevende uit hoe het nieuwe systeem werkte.',
        'Ik oefende de hele ochtend en vergiste me gelukkig bijna nooit.',
        'In de middag beantwoordde ik mijn eerste mails en belde ik twee klanten.',
        'Thuis vertelde ik alles aan mijn man, die al had gekookt en de tafel had gedekt.',
      ],
      right:
        'Alles goed: fietste, begroetten, zetten, legde, werkte, oefende, vergiste, beantwoordde, belde, vertelde, gekookt en gedekt. En collega’s en systeem.',
      wrong:
        'Kijk na: -te bij een stam uit ’t kofschip (fietste, werkte, vergiste), -de bij de rest (legde, oefende, belde, vertelde). Stam op t of d: begroet + ten = begroetten, zet + ten = zetten, beantwoord + de = beantwoordde. Deelwoord: gekookt en gedekt. En collega’s (’s) en systeem (y).',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail na voordat je hem verstuurt',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'Kees', subject: 'Verhuizing afdeling' },
      greeting: 'Hoi Kees,',
      signoff: 'Groet,\nMarieke',
      tokens: [
        { t: 'Vorige' },
        { t: 'week' },
        { t: 'is' },
        { t: 'onze' },
        { t: 'afdeling' },
        { t: 'verhuisd', trap: 'Goed: in verhuizen staat een z. Dus -d: verhuisd.' },
        { t: 'naar' },
        { t: 'de' },
        { t: 'tweede' },
        { t: 'verdieping.' },
        { t: 'Op' },
        { t: 'maandag' },
        { t: 'pakden', fix: 'pakten', why: 'Stam pak, k zit in ’t kofschip: pakte, meervoud pakten.' },
        { t: 'we' },
        { t: 'alle' },
        { t: 'dozen' },
        { t: 'in,' },
        { t: 'en' },
        { t: 'op' },
        { t: 'dinsdag' },
        { t: 'sjouwden' },
        { t: 'de' },
        { t: 'verhuizers' },
        { t: 'alles' },
        { t: 'naar' },
        { t: 'boven.' },
        { t: 'Daarbij' },
        { t: 'beschadigden', trap: 'Goed: stam beschadig, g zit niet in ’t kofschip. Dus -de, meervoud -den.' },
        { t: 'ze' },
        { t: 'een' },
        { t: 'buro,', fix: 'bureau,', why: 'De oo-klank aan het eind schrijf je hier als eau: bureau.' },
        { t: 'maar' },
        { t: 'dat' },
        { t: 'heb' },
        { t: 'ik' },
        { t: 'al' },
        { t: 'gemelt.', fix: 'gemeld.', why: 'Stam meld eindigt al op d: er komt niets bij. gemeld.' },
        { t: 'Het' },
        { t: 'was' },
        { t: 'zwaar' },
        { t: 'werk,' },
        { t: 'maar' },
        { t: 'niemand' },
        { t: 'durfte', fix: 'durfde', also: ['dorst'], why: 'In durven staat een v: durfde.' },
        { t: 'te' },
        { t: 'klagen.' },
        { t: 'Woensdag' },
        { t: 'repareerde' },
        { t: 'de' },
        { t: 'monteur' },
        { t: 'de' },
        { t: 'printer,' },
        { t: 'die' },
        { t: 'steeds' },
        { t: 'crashde.', fix: 'crashte.', why: 'sh telt mee met ’t kofschip: crashte.' },
        { t: 'Hij' },
        { t: 'heeft' },
        { t: 'ook' },
        { t: 'alle' },
        { t: 'kabels' },
        { t: 'getest.', trap: 'Goed: stam test eindigt al op t. Er komt niets bij: getest.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'de' },
        { t: 'nieuwe' },
        { t: 'plattegrond' },
        { t: 'gisteren' },
        { t: 'naar' },
        { t: 'iedereen' },
        { t: 'gemaild.', trap: 'Goed: stam mail, l zit niet in ’t kofschip. Dus gemaild, met een d.' },
        { t: 'Wat' },
        { t: 'ik' },
        { t: 'nog' },
        { t: 'niet' },
        { t: 'heb' },
        { t: 'geregelt,', fix: 'geregeld,', why: 'Stam regel, l zit niet in ’t kofschip: geregeld.' },
        { t: 'is' },
        { t: 'de' },
        { t: 'sleutel' },
        { t: 'van' },
        { t: 'de' },
        { t: 'archiefkast.' },
        { t: 'De' },
        { t: 'verhuurder' },
        { t: 'beloofte', fix: 'beloofde', why: 'In beloven staat een v: beloofde.' },
        { t: 'dat' },
        { t: 'die' },
        { t: 'vrijdag' },
        { t: 'komt.' },
        { t: 'Tot' },
        { t: 'die' },
        { t: 'tijd' },
        { t: 'blijft' },
        { t: 'de' },
        { t: 'kast' },
        { t: 'dicht,' },
        { t: 'en' },
        { t: 'dat' },
        { t: 'is' },
        { t: 'vervelent.', fix: 'vervelend.', why: 'vervelende: dus d.' },
        { t: 'Heb' },
        { t: 'jij' },
        { t: 'nog' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: ideeën. Het trema laat zien dat de laatste e los klinkt.' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'inrichting?' },
        { t: 'Dan' },
        { t: 'hoor' },
        { t: 'ik' },
        { t: 'het' },
        { t: 'graag.' },
      ],
      done: {
        title: 'De mail kan weg',
        text: 'pakten, bureau, gemeld, durfde, crashte, geregeld, beloofde, vervelend en ideeën. verhuisd, beschadigden, getest en gemaild stonden al goed.',
      },
    },
  ],
};
