import type { LessonInput } from '../../schema';

/** Praktijkles voor "Klank en letter": ’t kofschip, de verleden tijd (-te of -de) en het voltooid deelwoord (-t of -d) van zwakke werkwoorden. */
export const LES_K39: LessonInput = {
  id: 'k39',
  stage: 'regels',
  domain: 'orth',
  also: ['morf'],
  title: '’t Kofschip: -te of -de, -t of -d?',
  skill: 'Spelling',
  icon: '-te',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Van stam naar verleden tijd',
      panels: [
        {
          text: 'Veel werkwoorden maken de verleden tijd met *-te* of *-de*: *ik werkte*, *ik belde*. Het voltooid deelwoord krijgt *ge-* en een *t* of *d*: *gewerkt*, *gebeld*. Dat zijn de *zwakke* werkwoorden. Je begint altijd bij de *stam*: het hele werkwoord min *-en*. Daarbij gelden de gewone spellingregels: *maken* → *maak*, *stoppen* → *stop*, *leven* → *leef*, *reizen* → *reis*.',
          rule: 'Stam = hele werkwoord min *-en*: *werken* → *werk*, *maken* → *maak*, *stoppen* → *stop*.',
          lab: {
            label: 'Tik een werkwoord',
            chips: [
              { k: 'werken', out: 'stam: werk', note: 'werken min -en.' },
              { k: 'maken', out: 'stam: maak', note: 'Gesloten lettergreep: twee a’s.' },
              { k: 'stoppen', out: 'stam: stop', note: 'Geen dubbele p aan het eind.' },
              { k: 'leven', out: 'stam: leef', note: 'Aan het eind schrijf je f, geen v.' },
              { k: 'reizen', out: 'stam: reis', note: 'Aan het eind schrijf je s, geen z.' },
              { k: 'praten', out: 'stam: praat', note: 'De stam eindigt op een t.' },
            ],
          },
        },
        {
          text: 'Kijk nu naar de laatste letter van de stam. Zit die in *’t kofschip* (*t*, *k*, *f*, *s*, *ch*, *p*), dan krijg je *-te* in de verleden tijd en *-t* in het voltooid deelwoord: *werk-te*, *gewerkt*. Zit hij er niet in, dan *-de* en *-d*: *bel-de*, *gebeld*. Ook *x* en *sh* tellen mee: *faxen* → *faxte*, *gefaxt*; *crashen* → *crashte*, *gecrasht*.',
          rule: 'Laatste letter van de stam in ’t kofschip (+ x, sh): *-te*, *ge-…-t*. Anders: *-de*, *ge-…-d*.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik … (gisteren)', 'ik heb …'],
            rows: [
              { label: 'werken', cells: [{ fill: 'werkte' }, { fill: 'gewerkt', hint: 'k zit in ’t kofschip: -t.' }] },
              { label: 'bellen', cells: [{ fill: 'belde', hint: 'l zit niet in ’t kofschip: -de.' }, { fill: 'gebeld', hint: 'l zit niet in ’t kofschip: -d.' }] },
              { label: 'stoppen', cells: [{ fill: 'stopte', hint: 'Stam stop, p zit in ’t kofschip.' }, { fill: 'gestopt' }] },
              { label: 'wonen', cells: [{ fill: 'woonde', hint: 'Stam woon, n zit niet in ’t kofschip.' }, { fill: 'gewoond' }] },
              { label: 'fietsen', cells: [{ fill: 'fietste' }, { fill: 'gefietst', hint: 's zit in ’t kofschip: -t.' }] },
              { label: 'faxen', cells: [{ fill: 'faxte', hint: 'x telt mee met ’t kofschip.' }, { fill: 'gefaxt' }] },
            ],
            extra: ['werkde', 'gebelt', 'stopde', 'woonte', 'gefietsd'],
            note: 'werk, stop, fiets en fax: -te en -t. bel en woon: -de en -d.',
          },
        },
        {
          text: 'In het meervoud komt er een *n* achter: *wij werkten*, *jullie belden*, *zij woonden*. Het voltooid deelwoord gebruik je met *hebben* of *zijn*: *ik heb gewerkt*, *ik ben verhuisd*. Begint het werkwoord met *be-*, *ver-*, *her-*, *ont-* of *ge-*, dan komt er geen extra *ge-* bij. De t of d volgt gewoon dezelfde regel: *betalen* → *betaald*, *vertalen* → *vertaald*, *herhalen* → *herhaald*, *gebeuren* → *gebeurd*.',
          rule: 'Meervoud: *-ten* of *-den*. Voltooid deelwoord zonder ge- bij be-, ver-, her-, ont-, ge-: *betaald*, *gebeurd*.',
          build: {
            before: 'Tien jaar geleden: wij',
            stem: 'woon',
            endings: ['den', 'ten', 'de', 'te'],
            answer: 'den',
            note: 'wij woonden: n zit niet in ’t kofschip, dus -de, en in het meervoud -den.',
          },
          quiz: {
            q: 'Je collega vraagt: "Wat is er …?"',
            options: ['gebeurd', 'gebeurt', 'gebeurdt'],
            answer: 'gebeurd',
            why: 'Voltooid deelwoord van gebeuren: stam gebeur, r zit niet in ’t kofschip, dus -d. Geen extra ge-, want het begint al met ge-.',
          },
        },
        {
          text: 'Onthoud de letters met een ezelsbruggetje: *’t kofschip* of *soft ketchup*. In beide zitten *t*, *k*, *f*, *s*, *ch* en *p*; de klinkers tellen niet mee. Let op: dit geldt alleen voor zwakke werkwoorden. *Sterke* werkwoorden veranderen hun klinker en krijgen geen *-te* of *-de*: *lopen* → *liep*, *gelopen*; *kijken* → *keek*, *gekeken*; *kopen* → *kocht*, *gekocht*. Die leer je uit je hoofd.',
          rule: '’t kofschip of soft ketchup: t, k, f, s, ch, p. Alleen voor zwakke werkwoorden.',
          quiz: {
            q: 'Gisteren … ik de hele avond met mijn vrienden. (dansen)',
            options: ['danste', 'dansde', 'dans'],
            answer: 'danste',
            why: 'Stam dans, s zit in ’t kofschip: danste. In dansen hoor en schrijf je een s, geen z.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'te-de',
      prompt: 'Krijgt de verleden tijd -te of -de?',
      buckets: ['-te', '-de'],
      items: [
        { t: 'werken', b: 0 },
        { t: 'koken', b: 0 },
        { t: 'missen', b: 0 },
        { t: 'juichen', b: 0 },
        { t: 'blaffen', b: 0 },
        { t: 'stoppen', b: 0 },
        { t: 'bellen', b: 1 },
        { t: 'horen', b: 1 },
        { t: 'bouwen', b: 1 },
        { t: 'regenen', b: 1 },
        { t: 'leren', b: 1 },
        { t: 'tekenen', b: 1 },
      ],
      why: 'werkte, kookte, miste, juichte, blafte, stopte: stam op k, s, ch, f of p. belde, hoorde, bouwde, regende, leerde, tekende: stam op l, r, w of n.',
    },
    {
      kind: 'type',
      id: 'werkte',
      prompt: 'Typ de verleden tijd van werken.',
      before: 'Gisteren',
      after: 'ik tot zes uur.',
      hint: 'werk…',
      answer: 'werkte',
      why: 'Stam werk, k zit in ’t kofschip: werkte.',
    },
    {
      kind: 'choice',
      id: 'gefietst',
      prompt: 'Kies de goede vorm.',
      before: 'Hij heeft vandaag twintig kilometer',
      after: '.',
      options: ['gefietst', 'gefietsd', 'gefiets'],
      answer: 'gefietst',
      why: 'Stam fiets, s zit in ’t kofschip: gefietst, met een t aan het eind.',
    },
    {
      kind: 'swipe',
      id: 'kofschip-zinnen',
      prompt: 'Klopt de werkwoordsvorm?',
      cards: [
        { t: 'Gisteren werkte ik tot zes uur.', ok: true, why: 'Stam werk: -te.' },
        { t: 'Ik heb mijn moeder gebelt.', ok: false, fix: 'gebelt → gebeld', why: 'Stam bel, l zit niet in ’t kofschip: gebeld.' },
        { t: 'Wij stopten bij een tankstation.', ok: true, why: 'Stam stop: -te, in het meervoud -ten.' },
        { t: 'Hij woonde vroeger in Rotterdam.', ok: true, why: 'Stam woon: -de.' },
        { t: 'De hond blafde de hele nacht.', ok: false, fix: 'blafde → blafte', why: 'Stam blaf, f zit in ’t kofschip: blafte.' },
        { t: 'Ze hebben de hele avond gedanst.', ok: true, why: 'Stam dans: gedanst.' },
        { t: 'Mijn zus kookte en ik dekde de tafel.', ok: false, fix: 'dekde → dekte', why: 'Stam dek, k zit in ’t kofschip: dekte.' },
        { t: 'We hebben vandaag veel geleerd.', ok: true, why: 'Stam leer, r zit niet in ’t kofschip: geleerd.' },
      ],
    },
    {
      kind: 'fix',
      id: 'gebeurd',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Wat is er gisteren op je werk gebeurt?',
      wrong: 7,
      answer: 'gebeurd',
      why: 'Voltooid deelwoord van gebeuren: stam gebeur, r zit niet in ’t kofschip, dus gebeurd. Gebeurt is de tegenwoordige tijd: het gebeurt nu.',
    },
    {
      kind: 'type',
      id: 'woonden',
      prompt: 'Typ de verleden tijd van wonen.',
      before: 'Wij',
      after: 'vroeger in een klein dorp.',
      hint: 'woon…',
      answer: 'woonden',
      why: 'Stam woon, n zit niet in ’t kofschip: -de. Meervoud: woonden.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'De valkuilen van ’t kofschip',
      panels: [
        {
          text: 'Valkuil 1: de *v* en de *z*. De stam van *leven* is *leef* en die van *reizen* is *reis*. De f en de s zitten in ’t kofschip, maar toch schrijf je *-de*. Kijk daarom bij een stam op *f* of *s* naar het hele werkwoord. Staat daar een *v* of *z*, dan krijg je *-de* en *-d*: *leefde*, *geleefd*; *reisde*, *gereisd*. Staat er een f of s, dan blijft het *-te*: *fietsen* → *fietste*, *blaffen* → *blafte*.',
          rule: 'v of z in het hele werkwoord: *-de*, *-d*. Dus *leven* → *leefde*, *reizen* → *reisde*.',
          paradigm: {
            q: 'Vul de vormen in',
            cols: ['ik … (gisteren)', 'ik heb / ben …'],
            rows: [
              { label: 'leven', cells: [{ fill: 'leefde', hint: 'In leven staat een v: -de.' }, { fill: 'geleefd' }] },
              { label: 'reizen', cells: [{ fill: 'reisde', hint: 'In reizen staat een z: -de.' }, { fill: 'gereisd', hint: 'In reizen staat een z: -d.' }] },
              { label: 'verhuizen', cells: [{ fill: 'verhuisde' }, { fill: 'verhuisd', hint: 'Geen ge-, en de z in verhuizen geeft -d.' }] },
              { label: 'beloven', cells: [{ fill: 'beloofde' }, { fill: 'beloofd', hint: 'Geen ge-, en de v in beloven geeft -d.' }] },
              { label: 'durven', cells: [{ fill: 'durfde', hint: 'In durven staat een v: -de.' }, { fill: 'gedurfd' }] },
            ],
            extra: ['leefte', 'gereist', 'verhuiste', 'beloofte', 'gedurft'],
            note: 'Alle vijf hebben een v of z in het hele werkwoord. Daarom -de en -d, ook al eindigt de stam op f of s.',
          },
        },
        {
          text: 'Valkuil 2: de stam eindigt al op *t* of *d*. In de verleden tijd plak je er gewoon *-te* of *-de* achter. Dan krijg je twee t’s of twee d’s: *praten* → *praatte*, *wachten* → *wachtte*, *zetten* → *zette*, *antwoorden* → *antwoordde*, *landen* → *landde*, *melden* → *meldde*. In het voltooid deelwoord komt er niets bij: *gepraat*, *gewacht*, *gezet*, *geantwoord*, *geland*, *gemeld*.',
          rule: 'Stam op t: *-te* (*praatte*), deelwoord *gepraat*. Stam op d: *-de* (*antwoordde*), deelwoord *geantwoord*.',
          build: {
            before: 'Gisteren',
            stem: 'antwoord',
            endings: ['de', 'te', 'e', ''],
            answer: 'de',
            note: 'Stam antwoord + de = antwoordde. Twee d’s, want je plakt -de achter een stam die al op d eindigt.',
          },
          deep: {
            q: 'En zetten → zette, met één t?',
            a: 'De stam is *zet* (één t, want een stam eindigt niet op twee dezelfde medeklinkers). *zet* + *te* = *zette*. Zo ook *redden* → *red* + *de* = *redde*, en het deelwoord *gered*.',
          },
        },
        {
          text: 'Valkuil 3: het voltooid deelwoord als bijvoeglijk naamwoord. De t of d blijft staan, en er komt een *-e* achter: *geplakt* → *de geplakte foto*, *gestopt* → *de gestopte trein*, *verwarmd* → *het verwarmde huis*, *betaald* → *de betaalde rekening*. Ook Engelse werkwoorden volgen ’t kofschip: *mailen* → *mailde*, *gemaild*; *scoren* → *scoorde*, *gescoord*; *printen* → *printte*, *geprint*; *downloaden* → *downloadde*, *gedownload*; *crashen* → *crashte*, *gecrasht*.',
          rule: 'De t of d blijft: *de geplakte foto*, *het verwarmde huis*. Engelse werkwoorden: ook ’t kofschip (*gemaild*, *gecrasht*).',
          lab: {
            label: 'Tik een werkwoord',
            chips: [
              { k: 'mailen', out: 'mailde · gemaild', note: 'Stam mail, l: -de en -d.' },
              { k: 'scoren', out: 'scoorde · gescoord', note: 'Stam scoor, r: -de en -d.' },
              { k: 'printen', out: 'printte · geprint', note: 'Stam print, t: -te, en in het deelwoord geen extra t.' },
              { k: 'downloaden', out: 'downloadde · gedownload', note: 'Stam download, d: -de, en in het deelwoord geen extra d.' },
              { k: 'crashen', out: 'crashte · gecrasht', note: 'Stam crash, sh telt mee: -te en -t.' },
              { k: 'plakken', out: 'de geplakte foto', note: 'geplakt + e: de t blijft staan.' },
            ],
          },
          deep: {
            q: 'En updaten of liken?',
            a: 'Daar eindigt de stam op een e die je niet hoort: *update*, *like*. Dan kijk je naar de laatste klank die je wel hoort: een t-klank en een k-klank. Dus *updatete*, *geüpdatet* en *likete*, *geliket*.',
          },
        },
        {
          text: 'Stappenplan bij twijfel. 1. Verandert de klinker (*lopen* → *liep*)? Dan is het een sterk werkwoord: leren. 2. Maak de stam. 3. Staat er een v of z in het hele werkwoord? Dan *-de* en *-d*. 4. Laatste letter van de stam in ’t kofschip? Dan *-te* en *-t*, anders *-de* en *-d*. Handige controle voor het voltooid deelwoord: je hoort de t of d aan het eind niet goed, maar de verleden tijd vertelt het je: *belde* → *gebeld*, *werkte* → *gewerkt*.',
          rule: 'Twijfel je over -t of -d aan het eind? Maak de verleden tijd: *-de* → *-d*, *-te* → *-t*.',
          quiz: {
            q: 'Ik heb het pakket gisteren …',
            options: ['verstuurd', 'verstuurt', 'verstuurdt'],
            answer: 'verstuurd',
            why: 'Verleden tijd: verstuurde, met -de. Dus het voltooid deelwoord is verstuurd. Verstuurt is de tegenwoordige tijd: hij verstuurt.',
          },
          deep: {
            q: 'Zijn er werkwoorden die half zwak, half sterk zijn?',
            a: 'Ja, een paar. Ze krijgen *-te* of *-de* in de verleden tijd, maar een voltooid deelwoord op *-en*: *lachen* → *lachte*, *gelachen*; *bakken* → *bakte*, *gebakken*; *wassen* → *waste*, *gewassen*. Die leer je uit je hoofd.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'v-z',
      prompt: 'Kijk naar het hele werkwoord. -te of -de?',
      buckets: ['-te', '-de'],
      items: [
        { t: 'fietsen', b: 0 },
        { t: 'dansen', b: 0 },
        { t: 'missen', b: 0 },
        { t: 'straffen', b: 0 },
        { t: 'kussen', b: 0 },
        { t: 'blaffen', b: 0 },
        { t: 'leven', b: 1 },
        { t: 'reizen', b: 1 },
        { t: 'verhuizen', b: 1 },
        { t: 'geloven', b: 1 },
        { t: 'verven', b: 1 },
        { t: 'vrezen', b: 1 },
      ],
      why: 'fietste, danste, miste, strafte, kuste, blafte: s of f in het hele werkwoord. leefde, reisde, verhuisde, geloofde, verfde, vreesde: v of z in het hele werkwoord.',
    },
    {
      kind: 'proofread',
      id: 'mail-mark',
      prompt: 'Vind de vijf fouten in dit mailtje.',
      intro: 'Kijk naar elk werkwoord in de verleden tijd en elk voltooid deelwoord.',
      header: { to: 'Mark', subject: 'Gisteren' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Mark,' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'gisteren' },
        { t: 'de' },
        { t: 'hele' },
        { t: 'dag' },
        { t: 'gewerkd.', fix: 'gewerkt.', why: 'Stam werk, k zit in ’t kofschip: gewerkt.' },
        { t: 'Daarna' },
        { t: 'fietste' },
        { t: 'ik' },
        { t: 'naar' },
        { t: 'huis.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'je' },
        { t: 'gebelt,', fix: 'gebeld,', why: 'Stam bel, l zit niet in ’t kofschip: gebeld.' },
        { t: 'maar' },
        { t: 'je' },
        { t: 'antwoorde', fix: 'antwoordde', why: 'Stam antwoord + de: antwoordde, met twee d’s.' },
        { t: 'niet.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'het' },
        { t: 'pakket' },
        { t: 'verstuurt', fix: 'verstuurd', why: 'Verleden tijd verstuurde, dus voltooid deelwoord verstuurd.' },
        { t: 'en' },
        { t: 'de' },
        { t: 'rekening' },
        { t: 'betaald.' },
        { t: 'Wat' },
        { t: 'is' },
        { t: 'er' },
        { t: 'gebeurt?', fix: 'gebeurd?', why: 'Voltooid deelwoord van gebeuren: gebeurd.' },
        { t: 'Groet,' },
        { t: 'Ilse' },
      ],
      done: {
        title: 'Alle werkwoorden gecontroleerd',
        text: 'gewerkt, gebeld, antwoordde, verstuurd en gebeurd. fietste en betaald stonden al goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-verhuisde',
      prompt: 'Luister en typ de zin.',
      sentence: 'Vorige week verhuisde mijn zus en ik verfde haar keuken.',
      right: 'Goed: verhuisde en verfde, allebei met -de, want in verhuizen en verven staat een z en een v.',
      wrong: 'Let op: verhuisde (verhuizen, met z) en verfde (verven, met v). Allebei -de.',
    },
    {
      kind: 'fix',
      id: 'beantwoord',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Zij heeft alle vragen goed beantwoordt.',
      wrong: 5,
      answer: 'beantwoord',
      why: 'Stam beantwoord eindigt al op d. In het voltooid deelwoord komt er niets bij, ook geen t: beantwoord.',
    },
    {
      kind: 'rewrite',
      id: 'wachtten',
      prompt: 'Zet de zin in de verleden tijd.',
      source: 'Wij wachten op de trein en praten over het werk.',
      accept: ['Wij wachtten op de trein en praatten over het werk.'],
      why: 'Stam wacht en praat eindigen op t: -te erachter geeft wachtte en praatte, in het meervoud wachtten en praatten.',
    },
    {
      kind: 'swipe',
      id: 'valkuil-zinnen',
      prompt: 'Klopt de werkwoordsvorm?',
      intro: 'Pas op voor v en z, stammen op t en d, en Engelse werkwoorden.',
      cards: [
        { t: 'Wij verhuisden vorig jaar naar Almere.', ok: true, why: 'verhuizen heeft een z: -de, meervoud -den.' },
        { t: 'Ze reiste drie weken door Marokko.', ok: false, fix: 'reiste → reisde', why: 'In reizen staat een z: reisde.' },
        { t: 'Ik heb het hem beloofd.', ok: true, why: 'beloven heeft een v: beloofd.' },
        { t: 'Hij praatte de hele les.', ok: true, why: 'Stam praat + te: praatte.' },
        { t: 'Ik heb de koffie al gezett.', ok: false, fix: 'gezett → gezet', why: 'Stam zet eindigt al op t: in het deelwoord komt er niets bij.' },
        { t: 'Het vliegtuig landde precies op tijd.', ok: true, why: 'Stam land + de: landde.' },
        { t: 'Ik heb het bestand gedownload.', ok: true, why: 'Stam download eindigt op d: er komt niets bij.' },
        { t: 'Wie heeft het laatste doelpunt gescoort?', ok: false, fix: 'gescoort → gescoord', why: 'Stam scoor, r zit niet in ’t kofschip: gescoord.' },
      ],
    },
    {
      kind: 'type',
      id: 'geplakte',
      prompt: 'Maak van plakken een bijvoeglijk naamwoord.',
      before: 'De',
      after: 'foto valt steeds van de muur.',
      hint: 'ge…e',
      answer: 'geplakte',
      why: 'geplakt (stam plak, k zit in ’t kofschip) + e = geplakte. De t blijft staan.',
    },
    {
      kind: 'bet',
      id: 'downloadde',
      prompt: 'Ik … gisteren een nieuwe app.',
      intro: 'Een Engels werkwoord met een stam op d.',
      options: ['downloadde', 'downloadte', 'downloade'],
      answer: 'downloadde',
      why: 'Stam download, d zit niet in ’t kofschip: download + de = downloadde. Net als antwoordde.',
    },
    {
      kind: 'dictation',
      id: 'dictee-gebeurd',
      prompt: 'Luister en typ de zin.',
      sentence: 'Wat is er gebeurd? De trein stopte en wij wachtten een uur.',
      right: 'Goed: gebeurd met d, stopte met -te, en wachtten met twee t’s en -en.',
      wrong: 'Let op: gebeurd (gebeurde → gebeurd), stopte (p in ’t kofschip) en wachtten (wacht + ten).',
    },
  ],
};
