import type { LessonInput } from '../../schema';

/**
 * Toets voor "Klank en letter": alle regels van k30–k39 door elkaar, van klinkers en medeklinkers tot leenwoorden en
 * ’t kofschip, met regels uit De letter (hoofdletters, accenten, trema, apostrof en koppelteken) ertussen.
 */
export const LES_K40: LessonInput = {
  id: 'k40',
  stage: 'toets',
  domain: 'orth',
  also: ['fon'],
  title: 'Toets: klank en letter',
  skill: 'Spelling',
  icon: 'toets',
  steps: [
    {
      kind: 'explain',
      id: 'overzicht',
      title: 'Alle regels op een rij',
      panels: [
        {
          text: 'De klinkers. Een lange klank met een medeklinker erachter in dezelfde lettergreep schrijf je met twee letters: *raam*, *been*, *boom*, *muur* (tegenover *ram*, *ben*, *bom*). *ie*, *oe*, *eu* en *ui* hebben altijd twee letters (alleen in woorden als *taxi* en *kilo* schrijf je de ie-klank met één *i*). Bij *ei* en *ij* hoor je geen verschil: woord kennen, maar *-lijk* is altijd ij en *-heid* altijd ei. Bij *ou* en *au*: voor een d of t bijna altijd *ou* (*oud*, *hout*); *vrouw*, *bouwen*, maar *blauw*, *gauw*, *saus*. En onthoud *eeuw*, *ieuw* en *uw*: *sneeuw*, *nieuw*, *duwen*.',
          rule: 'Lange klank met een medeklinker erachter in dezelfde lettergreep: twee letters (*raam*). *-lijk* met ij, *-heid* met ei. Voor d en t: bijna altijd *ou*.',
          quiz: {
            q: 'Welke rij is helemaal goed?',
            options: ['vrouw, blauw, koud', 'vrauw, blouw, kaud', 'vrouw, blouw, koud'],
            answer: 'vrouw, blauw, koud',
            why: 'vrouw met ouw, blauw met auw, en koud met ou voor de d.',
          },
        },
        {
          text: 'De medeklinkers. Aan het eind hoor je bij een d altijd een *t*-klank en bij een b een *p*-klank: maak het woord langer om te horen wat je schrijft (*hond* → *honden*, *web* → *webben*). Aan het eind schrijf je geen *z* of *v* (alleen in een paar leenwoorden, zoals *quiz*), maar *s* en *f*: *huis* → *huizen*, *brief* → *brieven*, *ik reis*, *ik leef*. Je hoort *cht*: meestal *ch* (*lucht*, *nacht*, *de klacht*), behalve bij een vorm van een werkwoord met g (*ligt* van *liggen*, *zegt* van *zeggen*). Nooit *ngk*: *bank*, *denken*. En *-isch*: *logisch*, *praktisch*.',
          rule: 'Langer maken: *hond* → *honden*. Aan het eind s en f: *huis*, *brief*. *ligt* van liggen, *licht* van het licht.',
          quiz: {
            q: 'Je sleutel … nog op tafel.',
            options: ['ligt', 'licht', 'ligd'],
            answer: 'ligt',
            why: 'Van liggen, met een g: ligt. Licht (met ch) is het licht van de lamp.',
          },
        },
        {
          text: 'De doffe e. Meestal schrijf je hem als *e*: *de*, *tafel*, *lopen*, *grote*. Maar in *-ig* schrijf je *i* (*gezellig*, *nodig*, *handig*), in *-lijk* en *-lijks* schrijf je *ij* (*vriendelijk*, *eerlijk*, *dagelijks*). De *n* van *-en* hoor je vaak niet, maar je schrijft hem wel: *wij werken*, *de boeken*.',
          rule: '*-ig*, *-lijk*, *-lijks*: daar is de doffe e een i of ij. Elders meestal een e. De n van -en altijd schrijven.',
          quiz: {
            q: 'Het feest was heel …',
            options: ['gezellig', 'gezellug', 'gezellich'],
            answer: 'gezellig',
            why: 'De uitgang -ig schrijf je altijd met i en g.',
          },
        },
        {
          text: 'Leenwoorden. Je hoort een klank die je met andere letters schrijft: *c* als k of s (*café*, *centrum*), *ch* als sj (*chef*), *g* als zj (*garage*), *ou* als oe (*route*), *eau* als oo (*cadeau*, meervoud *cadeaus*), *-tie* als tsie (*vakantie*), *th* als t (*thee*), *y* als ie (*baby*), *x* als ks (*taxi*).',
          rule: 'Klank horen, vast koppel kiezen, en bij twijfel opzoeken.',
          lab: {
            label: 'Tik wat je hoort',
            chips: [
              { k: 'sjo-feur', out: 'chauffeur', note: 'sj → ch, oo → au.' },
              { k: 'ka-doo', out: 'cadeau', note: 'k → c, oo aan het eind → eau.' },
              { k: 'in-for-maa-tsie', out: 'informatie', note: 'tsie → -tie.' },
              { k: 'ga-raa-zje', out: 'garage', note: 'zj → g.' },
            ],
          },
        },
        {
          text: '’t Kofschip. Zwakke werkwoorden: eindigt de stam op *t*, *k*, *f*, *s*, *ch* of *p* (en *x*, *sh*), dan *-te* en *ge-…-t* (*werkte*, *gewerkt*). Anders *-de* en *ge-…-d* (*belde*, *gebeld*). Bij v of z in het hele werkwoord: *-de* (*leefde*, *reisde*). Stam op t of d: *praatte*, *gepraat*; *antwoordde*, *geantwoord*.',
          rule: 'Stam in ’t kofschip: *-te*, *-t*. Anders *-de*, *-d*. Let op v en z in het hele werkwoord.',
          quiz: {
            q: 'Ik heb drie weken door Spanje …',
            options: ['gereisd', 'gereist', 'gereizd'],
            answer: 'gereisd',
            why: 'In reizen staat een z: dan -de en -d. De stam schrijf je met s: gereisd.',
          },
        },
      ],
    },
    {
      kind: 'swipe',
      id: 'mix',
      prompt: 'Goed of fout geschreven?',
      intro: 'Alle regels door elkaar. Let op: sommige zinnen zien er vreemd uit, maar zijn helemaal goed.',
      cards: [
        {
          t: 'Het pakket is al betaald, maar het is nog niet bezorgt.',
          ok: false,
          fix: 'bezorgt → bezorgd',
          why: 'bezorgen: stam bezorg, de g zit niet in ’t kofschip. bezorgde, dus bezorgd.',
        },
        { t: 'Hij praatte de hele avond over zijn nieuwe baan.', ok: true, why: 'Stam praat eindigt op t: praat + te = praatte, met twee t’s.' },
        {
          t: 'Mijn buurvrouw antwoorde meteen op mijn mail.',
          ok: false,
          fix: 'antwoorde → antwoordde',
          why: 'Stam antwoord eindigt op d: antwoord + de = antwoordde, met twee d’s.',
        },
        {
          t: 'Ik heb het water gekookt en de thee gezet.',
          ok: true,
          why: 'koken: stam kook, kookte, dus gekookt. zetten: stam zet, zette, dus gezet. Er komt geen extra t bij.',
        },
        {
          t: 'De kinderen hebben in de tuin een hut gebouwt.',
          ok: false,
          fix: 'gebouwt → gebouwd',
          why: 'bouwen: stam bouw, de w zit niet in ’t kofschip. bouwde, dus gebouwd.',
        },
        {
          t: 'We hebben drie nachten bij mijn zus gelogeerd.',
          ok: true,
          why: 'logeren: je hoort zj, je schrijft g. Stam logeer: logeerde, dus gelogeerd.',
        },
        {
          t: 'Dat lijkt me een heel logiese keuze.',
          ok: false,
          fix: 'logiese → logische',
          why: '‘ies’ aan het eind van een bijvoeglijk naamwoord: -isch. Met -e: logische.',
        },
        {
          t: 'De buren schreeuwden tot diep in de nacht.',
          ok: true,
          why: 'schreeuwen met eeuw. Stam schreeuw: -de, en in het meervoud -den. nacht met ch.',
        },
        {
          t: 'In de trein was het warm en erg benouwd.',
          ok: false,
          fix: 'benouwd → benauwd',
          why: 'benauwd komt van nauw, en nauw staat in het auw-rijtje. De d staat na de w, dus de d-regel helpt hier niet.',
        },
        {
          t: 'Op Koningsdag verkopen de kinderen hun oude boeken en dvd’s.',
          ok: true,
          why: 'Koningsdag is een feestdag: hoofdletter. dvd is een afkorting: meervoud dvd’s, met apostrof.',
        },
        {
          t: 'Zij heeft al twee ideeën voor de reünie.',
          ok: true,
          why: 'idee → ideeën: trema op de e van -ën. reünie: zonder trema lees je eu.',
        },
        {
          t: 'In de zomer rijden we met de auto naar Italie.',
          ok: false,
          fix: 'Italie → Italië',
          why: 'Ita-li-ë: zonder trema lees je ie. Landen op -ië krijgen een trema.',
        },
        {
          t: 'De vergadering is verplaatst naar donderdag.',
          ok: true,
          why: 'verplaatsen: stam verplaats, de s zit in ’t kofschip en er staat geen z in het werkwoord. Dus verplaatst. donderdag: een dag, klein.',
        },
      ],
    },
    {
      kind: 'choice',
      id: 'leiden',
      prompt: 'Kies de goede vorm.',
      before: 'Mijn collega heeft het team tien jaar lang',
      after: '.',
      options: ['geleid', 'geleidt', 'gelijd', 'geleden'],
      answer: 'geleid',
      why: 'leiden (met ei) is de baas zijn. Stam leid, de d zit niet in ’t kofschip: leidde, geleid. Er komt geen t achter. lijden (pijn hebben) is een sterk werkwoord: leed, geleden.',
    },
    {
      kind: 'dictation',
      id: 'dictee-buurvrouw',
      prompt: 'Luister en typ de zin.',
      sentence: 'Mijn vriendelijke buurvrouw heeft haar kleinzoon ’s ochtends met de auto naar de crèche gebracht.',
      right: 'Goed: vriendelijke met -lijk, buurvrouw met ouw, kleinzoon met ei, ’s ochtends met een apostrof, crèche met è en ch, en gebracht met cht.',
      wrong:
        'Kijk deze woorden na: vriendelijke (-lijk), buurvrouw (ouw), kleinzoon (ei), ’s ochtends (apostrof, klein midden in de zin), auto (au), crèche (accent naar links, ch) en gebracht (van brengen: cht).',
    },
    {
      kind: 'proofread',
      id: 'appje-sanne',
      prompt: 'Kijk het appje van Omar na voordat hij het verstuurt.',
      intro: 'Tik een fout woord aan en verbeter het.',
      greeting: 'Hoi Sanne,',
      signoff: 'Groetjes,\nOmar',
      tokens: [
        { t: 'Het' },
        { t: 'feest' },
        { t: 'was' },
        { t: 'echt' },
        { t: 'gezellug!', fix: 'gezellig!', why: 'De uitgang -ig schrijf je met i.' },
        { t: 'Je' },
        { t: 'sleutel' },
        { t: 'licht', fix: 'ligt', why: 'Van liggen: ligt, met g.' },
        { t: 'nog' },
        { t: 'bij' },
        { t: 'mij.' },
        { t: 'Mijn' },
        { t: 'vrauw', fix: 'vrouw', why: 'vrouw schrijf je met ouw.' },
        { t: 'vond' },
        { t: 'je' },
        { t: 'kado', fix: 'cadeau', why: 'Leenwoord: c vooraan en eau aan het eind.' },
        { t: 'heel' },
        { t: 'mooi.' },
        { t: 'Ik' },
        { t: 'breng' },
        { t: 'de' },
        { t: 'sleutel' },
        { t: 'morgen' },
        { t: 'langs' },
        { t: 'als' },
        { t: 'ik' },
        { t: 'met' },
        { t: 'de' },
        { t: 'hont', fix: 'hond', why: 'Maak het langer: honden. Dus hond, met d.' },
        { t: 'ga' },
        { t: 'wandelen.' },
      ],
      done: {
        title: 'Alle fouten gevonden',
        text: 'gezellig, ligt, vrouw, cadeau en hond.',
      },
    },
    {
      kind: 'sort',
      id: 'ou-au',
      prompt: 'ou of au?',
      buckets: ['ou', 'au'],
      items: [
        { t: 'verk…dheid', b: 0 },
        { t: 'ben…wd', b: 1 },
        { t: 'sch…wburg', b: 0 },
        { t: 'n…wkeurig', b: 1 },
        { t: 'r…wkaart (na een overlijden)', b: 0 },
        { t: 'r…wkost (niet gekookt)', b: 1 },
        { t: 'astron…t', b: 1 },
        { t: 'vertr…wen', b: 0 },
        { t: 'k…wgom', b: 1 },
        { t: 'kab…ter', b: 0 },
        { t: 'appl…s', b: 1 },
        { t: 'h…dbaar (lang goed blijven)', b: 0 },
        { t: 'l…w (niet warm, niet koud)', b: 1 },
        { t: 'k…sen (aan je voeten)', b: 0 },
      ],
      why: 'ou: verkoudheid en houdbaar (d na de klank), schouwburg, rouwkaart, vertrouwen, kabouter, kousen. au: benauwd (van nauw), nauwkeurig, rauwkost, kauwgom en lauw (auw-rijtje), applaus, en astronaut: een leenwoord met au voor de t.',
    },
    {
      kind: 'type',
      id: 'fotografen',
      prompt: 'Typ het meervoud van fotograaf.',
      before: 'Op de bruiloft liepen twee',
      after: 'rond.',
      hint: 'meervoud',
      answer: 'fotografen',
      why: 'In het meervoud hoor je een f, geen v: fotografen. Aan het korte woord zie je dat niet (brief → brieven, maar fotograaf → fotografen). Leer het meervoud mee.',
    },
    {
      kind: 'fix',
      id: 'klacht',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Hij legt uit dat hij een klagt heeft over het licht in de gang.',
      wrong: 6,
      answer: 'klacht',
      why: 'Een klacht is een zelfstandig naamwoord: cht. Alleen een vorm van een werkwoord met g krijgt gt: hij legt (leggen), hij klaagt (klagen). licht (van de lamp) is goed.',
    },
    {
      kind: 'dictation',
      id: 'dictee-reisde',
      prompt: 'Luister en typ de zin.',
      sentence: 'Mijn neef reisde in augustus met de trein naar België en fietste daar elke dag.',
      right: 'Goed: augustus klein en met au, reisde met -de (reizen heeft een z), trein met ei, België met hoofdletter en trema, en fietste met -te.',
      wrong:
        'Let op: augustus (een maand: klein, met au), reisde (in reizen staat een z: -de), trein (ei), België (hoofdletter en trema) en fietste (stam fiets: -te).',
    },
    {
      kind: 'speed',
      id: 'samenstellingen',
      prompt: 'Aan elkaar of los?',
      intro: 'Een samenstelling schrijf je aan elkaar, en elk deel blijft zoals het los is.',
      seconds: 40,
      items: [
        { a: 'hand', b: 'doek', joined: true, tip: 'handdoek: hand + doek, twee d’s.' },
        { a: 'goed', b: 'idee', joined: false, tip: 'Een goed idee: twee woorden.' },
        { a: 'hoofd', b: 'pijn', joined: true, tip: 'hoofdpijn: hoofd houdt zijn d.' },
        { a: 'koude', b: 'thee', joined: false, tip: 'Bijvoeglijk naamwoord + zelfstandig naamwoord: los.' },
        { a: 'klanten', b: 'service', joined: true, tip: 'klantenservice: één ding, dus één woord.' },
        { a: 'stad', b: 'huis', joined: true, tip: 'stadhuis: stad met d, want steden.' },
        { a: 'lieve', b: 'vrouw', joined: false, tip: 'Een lieve vrouw: los.' },
        { a: 'bloed', b: 'druk', joined: true, tip: 'bloeddruk: bloed + druk, twee d’s.' },
        { a: 'land', b: 'kaart', joined: true, tip: 'landkaart: land met d, want landen.' },
        { a: 'oude', b: 'stad', joined: false, tip: 'De oude stad: los.' },
        { a: 'zieken', b: 'huis', joined: true, tip: 'ziekenhuis: één gebouw, één woord.' },
        { a: 'nieuwe', b: 'baan', joined: false, tip: 'Een nieuwe baan: bijvoeglijk naamwoord + zelfstandig naamwoord, los.' },
      ],
    },
    {
      kind: 'bet',
      id: 'geverfd',
      prompt: 'We hebben de muur blauw …',
      intro: 'Twee regels in één woord.',
      options: ['geverfd', 'geverft', 'gevervd', 'gevervt'],
      answer: 'geverfd',
      why: 'Stam verf (aan het eind f, geen v). In verven staat een v, dus -d: geverfd.',
    },
    {
      kind: 'sort',
      id: 'eeuw-ieuw-uw',
      prompt: 'eeuw, ieuw of uw?',
      buckets: ['eeuw', 'ieuw', 'uw'],
      items: [
        { t: 'l… (een groot roofdier)', b: 0 },
        { t: 'spr… (een zwarte vogel met witte stippen)', b: 0 },
        { t: '…ig (voor altijd)', b: 0 },
        { t: 'geschr… (hard roepen)', b: 0 },
        { t: 'm…en (vogels aan zee)', b: 0 },
        { t: 'n…sgierig', b: 1 },
        { t: 'vern…en', b: 1 },
        { t: 'opn… (nog een keer)', b: 1 },
        { t: 'k…en (een vis ademt ermee)', b: 1 },
        { t: 'gr…elijk', b: 2 },
        { t: 'sl… (slim en een beetje gemeen)', b: 2 },
        { t: 'sch… (bang voor mensen)', b: 2 },
        { t: 'r…weg (ongeveer)', b: 2 },
        { t: 'd…tje (een kleine duw)', b: 2 },
      ],
      why: 'eeuw: leeuw, spreeuw, eeuwig, geschreeuw, meeuwen. ieuw: nieuwsgierig, vernieuwen, opnieuw, kieuwen. uw: gruwelijk, sluw, schuw, ruwweg, duwtje. Nooit eew, iew of uuw, ook niet in een lang woord.',
    },
    {
      kind: 'rewrite',
      id: 'chef',
      prompt: 'Schrijf de zin over zonder fouten.',
      source: 'De sjef van het restorant zij dat de soep te lou was en de biefstuk te rouw.',
      accept: ['De chef van het restaurant zei dat de soep te lauw was en de biefstuk te rauw.'],
      why: 'chef (sj → ch), restaurant (oo → au), zei (van zeggen), lauw en rauw (auw-rijtje). rouw (met ou) is verdriet.',
    },
    {
      kind: 'choice',
      id: 'schonken',
      prompt: 'Kies de goede vorm.',
      before: 'Voor mijn verjaardag',
      after: 'mijn collega’s mij een mooi boek.',
      options: ['schonken', 'schongken', 'schenkten', 'schonkten'],
      answer: 'schonken',
      why: 'schenken is een sterk werkwoord: schonk, schonken, geschonken. Je hoort de ng-klank met een k: nk, nooit ngk. En er komt geen -te achter.',
    },
    {
      kind: 'proofread',
      id: 'mail-gemeente',
      prompt: 'Kijk de mail van Youssef aan de gemeente na voordat hij weggaat.',
      header: { to: 'Gemeente', subject: 'Nieuw adres' },
      greeting: 'Geachte heer, mevrouw,',
      signoff: 'Met vriendelijke groet,\nYoussef El Amrani',
      tokens: [
        { t: 'Vorige' },
        { t: 'week' },
        { t: 'ben' },
        { t: 'ik' },
        { t: 'verhuist', fix: 'verhuisd', why: 'In verhuizen staat een z: -d. Verhuisd.' },
        { t: 'naar' },
        { t: 'de' },
        { t: 'Dorpsstraat.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'het' },
        { t: 'formulier' },
        { t: 'al' },
        { t: 'gemailt,', fix: 'gemaild,', why: 'Stam mail, l zit niet in ’t kofschip: gemaild.' },
        { t: 'maar' },
        { t: 'ik' },
        { t: 'heb' },
        { t: 'nog' },
        { t: 'geen' },
        { t: 'informatsie', fix: 'informatie', why: 'tsie schrijf je als -tie.' },
        { t: 'ontvangen.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'mijn' },
        { t: 'nieuwe' },
        { t: 'reibewijs', fix: 'rijbewijs', why: 'rijbewijs komt van rijden: ij.' },
        { t: 'snel' },
        { t: 'nodig' },
        { t: 'voor' },
        { t: 'mijn' },
        { t: 'werk.' },
        { t: 'Alvast' },
        { t: 'vriendelek', fix: 'vriendelijk', why: '‘luhk’ aan het eind: -lijk, altijd met ij.' },
        { t: 'bedankt.' },
      ],
      done: {
        title: 'Klaar om te versturen',
        text: 'verhuisd, gemaild, informatie, rijbewijs en vriendelijk. nieuwe en nodig stonden al goed.',
      },
    },
    {
      kind: 'choice',
      id: 'gezondheidscentrum',
      prompt: 'Kies de goede spelling.',
      before: 'Mijn huisarts zit sinds kort in het nieuwe',
      after: '.',
      options: ['gezondheidscentrum', 'gezondheitscentrum', 'gezondhijdscentrum', 'gezondheidssentrum'],
      answer: 'gezondheidscentrum',
      why: '-heid schrijf je altijd met ei en een d (meervoud -heden). centrum met c: een c voor e klinkt als s.',
    },
    {
      kind: 'type',
      id: 'positieve',
      prompt: 'Typ de goede vorm van positief.',
      before: 'We kregen een heel',
      after: 'reactie van de klant.',
      hint: '',
      answer: 'positieve',
      why: '-ief met een -e erachter wordt -ieve: positieve. Net als actieve en negatieve.',
    },
    {
      kind: 'fix',
      id: 'logisch',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Mijn Belgische collega vindt de nieuwe regels heel logies en praktisch.',
      wrong: 8,
      answer: 'logisch',
      why: '‘ies’ aan het eind van een bijvoeglijk naamwoord: -isch, net als praktisch. Belgische is goed: van een land komt een hoofdletter, en -isch met -e erachter.',
    },
    {
      kind: 'type',
      id: 'verhuisden',
      prompt: 'Typ de verleden tijd van verhuizen.',
      before: 'Vorig jaar',
      after: 'mijn ouders naar een kleiner huis.',
      hint: '',
      answer: 'verhuisden',
      why: 'In verhuizen staat een z: -de. De stam schrijf je met s: verhuis. Meervoud: verhuisden.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro:
        'Zevenentwintig opdrachten: alle regels van Klank en letter door elkaar, met accenten, trema, apostrof en koppelteken uit De letter. Wat je fout doet, komt achteraan terug.',
      items: [
        {
          q: 'Vul de vorm van *beantwoorden* in',
          before: 'Ik heb uw vraag gisteren al',
          after: '.',
          a: 'beantwoord',
          why: 'Stam beantwoord. Met be- komt er geen ge- bij, en achter de d komt niets: beantwoord. Geen trema: ea is geen klank.',
        },
        {
          q: 'Meervoud van *idee*',
          before: 'Heb jij nog goede',
          after: 'voor het personeelsfeest?',
          a: 'ideeën',
          why: 'Een woord op ee krijgt in het meervoud meestal -ën, met een trema: ideeën.',
        },
        {
          q: 'Vul de verleden tijd van *durven* in',
          before: 'Hij',
          after: 'het niet te vragen.',
          a: 'durfde',
          also: ['dorst'],
          why: 'Stam durf, maar in durven staat een v: -de. Dus durfde. (De oudere vorm dorst is ook goed.)',
        },
        {
          q: 'Schrijf het woord dat je hoort: hij rijdt voor zijn werk de auto of bus van een ander (je hoort: sjo-feur)',
          say: 'de chauffeur',
          a: 'chauffeur',
          also: ['de chauffeur'],
          why: 'sj in een leenwoord: ch. oo: au. En ff, eu: chauffeur.',
        },
        {
          q: 'Vul de vorm van *uploaden* in',
          before: 'Ik heb het formulier gisteren',
          after: '.',
          a: 'geüpload',
          why: 'ge- + upload: trema op de u, anders lees je eu. Stam upload eindigt op d: er komt niets achter.',
        },
        {
          q: 'Meervoud van *eis*',
          before: 'De vakbond heeft drie',
          after: 'voor de nieuwe cao.',
          a: 'eisen',
          why: 'eis → eisen: je hoort een s, geen z. Net als kous → kousen en kruis → kruisen.',
        },
        { q: 'Honderd jaar, in het meervoud', before: 'Deze kerk is meer dan vijf', after: 'oud.', a: 'eeuwen', why: 'ee + w: eeuw. Meervoud: eeuwen.' },
        {
          q: 'Vul de verleden tijd van *zetten* in',
          before: 'Zij',
          after: 'koffie voor de hele afdeling.',
          a: 'zette',
          why: 'Stam zet + -te: zette. De stam heeft al een t, de uitgang brengt de tweede.',
        },
        {
          q: 'Vul *financieel* in met -e',
          before: 'Wij hebben',
          after: 'hulp nodig van de gemeente.',
          a: 'financiële',
          why: '-ieel + e wordt -iële, met een trema: anders lees je ie.',
        },
        {
          q: 'Zelfstandig naamwoord bij *wegen*',
          before: 'Let op je',
          after: ': de dokter zegt dat je te zwaar bent.',
          a: 'gewicht',
          why: 'Een zelfstandig naamwoord: cht. Alleen een vorm van het werkwoord krijgt gt: hij weegt.',
        },
        {
          q: 'Schrijf het woord dat je hoort: een dun boekje met informatie (je hoort: bro-sjuu-ruh)',
          say: 'de brochure',
          a: 'brochure',
          also: ['de brochure'],
          why: 'sj in een leenwoord: ch. brochure.',
        },
        {
          q: 'Meervoud van *menu*',
          before: 'De ober bracht ons twee',
          after: '.',
          a: 'menu’s',
          why: 'Woord op u: meervoud met ’s, anders lees je een korte u.',
        },
        {
          q: 'Vul de vorm in van *be-* + *eindigen*',
          before: 'Mijn contract wordt in maart',
          after: '.',
          a: 'beëindigd',
          why: 'be- + eindigen: trema op de e, anders lees je ei. Stam beëindig, de g zit niet in ’t kofschip: beëindigde, dus beëindigd.',
        },
        {
          q: 'Schrijf het woord dat je hoort: bijna niet (een ander woord dan *amper*)',
          say: 'nauwelijks',
          before: 'Ik heb vannacht',
          after: 'geslapen.',
          a: 'nauwelijks',
          why: 'nauw staat in het auw-rijtje, en ‘luhks’ aan het eind is -lijks: nauwelijks.',
        },
        { q: 'Verkleinwoord van *hoed*', before: 'Ze droeg een klein rood', after: '.', a: 'hoedje', why: 'hoed (hoeden) houdt zijn d, ook met -je: hoedje.' },
        {
          q: 'Maak één woord van *zee* en *egel*',
          before: 'Op het strand trapte ik op een',
          after: '.',
          a: 'zee-egel',
          why: 'Drie e’s botsen: zonder streepje lees je het verkeerd. Dus een koppelteken: zee-egel.',
        },
        {
          q: 'Vul de vorm van *verbreden* in',
          before: 'De weg naar het station wordt volgend jaar',
          after: '.',
          a: 'verbreed',
          why: 'Stam verbreed. Met ver- komt er geen ge- bij, en na de d komt niets: verbreed.',
        },
        {
          q: 'Vul de vorm van *bloeien* in',
          before: 'De rozen hebben dit jaar heel lang',
          after: '.',
          a: 'gebloeid',
          why: 'oe + j-klank: oei. Stam bloei, de i zit niet in ’t kofschip: gebloeid.',
        },
        {
          q: 'Meervoud van *druif*',
          before: 'Ik koop een tros',
          after: 'op de markt.',
          a: 'druiven',
          why: 'In het meervoud hoor je een v: druiven. Aan het eind van druif staat een f.',
        },
        {
          q: 'Bezit: de fiets van Thomas',
          before: '',
          after: 'fiets staat nog bij school.',
          a: 'Thomas’',
          why: 'Naam op s: alleen een apostrof. Thomas’ fiets.',
        },
        {
          q: 'Schrijf het woord dat je hoort: echt iets voor hem (je hoort: tie-pies)',
          say: 'typisch',
          before: 'Dat is weer',
          after: 'mijn broer: altijd te laat.',
          a: 'typisch',
          why: 'y klinkt hier als ie, en ‘ies’ aan het eind van een bijvoeglijk naamwoord is -isch: typisch.',
        },
        {
          q: 'Vul de verleden tijd van *fietsen* in',
          before: 'Vroeger',
          after: 'wij elke dag naar ons werk.',
          a: 'fietsten',
          why: 'Stam fiets, de s zit in ’t kofschip en fietsen heeft geen z: -te. Meervoud: fietsten.',
        },
        {
          q: 'Schrijf het woord dat je hoort: een gebouw voor toneel en shows (je hoort: tee-jaa-ter)',
          say: 'het theater',
          a: 'theater',
          also: ['het theater'],
          why: 'th klinkt als t: theater.',
        },
        {
          q: 'Vul het getal in, in letters',
          before: 'Ik heb maar',
          after: 'vraag, niet twee.',
          a: 'één',
          why: 'Het getal 1, tegenover twee: één, met een accent op beide e’s. Het lidwoord een heeft geen accent.',
        },
        {
          q: 'Vul de vorm van *interesseren* in',
          before: 'Ik ben erg',
          after: 'in deze baan.',
          a: 'geïnteresseerd',
          why: 'ge- + interesseren: trema op de i, anders lees je ei. Stam interesseer: -de, dus geïnteresseerd.',
        },
        {
          q: 'Schrijf het woord dat je hoort: daar sta je onder om je te wassen (je hoort: doesj)',
          say: 'de douche',
          a: 'douche',
          also: ['de douche'],
          why: 'oe in een leenwoord: ou. sj: ch. douche.',
        },
        {
          q: 'Vul de verleden tijd van *kopen* in',
          before: 'Gisteren',
          after: 'ik een nieuwe winterjas.',
          a: 'kocht',
          why: 'kopen is een sterk werkwoord: kocht, met ch. Nooit koopte of kochte.',
        },
      ],
      done: {
        title: 'Reeks klaar',
        text: '’t Kofschip, langer maken, ei of ij, au of ou, -isch, -lijks en leenwoorden, met trema, apostrof en koppelteken ertussen.',
      },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de mail aan de verhuurder aan. Typ elk woord helemaal.',
      intro: 'Kijk goed naar de zin om het gat heen. Alle regels door elkaar.',
      title: 'Mail aan de verhuurder',
      text: 'Beste meneer Bakker,\n\nOp 2 maart heb ik u al {gemaild|mailen|Stam mail: de l zit niet in ’t kofschip. Dus mailde en gemaild.} over de {cv-ketel|cv + ketel|Afkorting + woord: koppelteken. cv-ketel.} in mijn woning. Sindsdien is er niets {gebeurd|gebeuren|gebeuren begint al met ge-: er komt geen ge- bij. gebeurde, dus gebeurd.}. De {verwarming|verwarmen → de …|Een woord op -ing: altijd ng.} doet het nog steeds niet. Vooral {’s avonds|in de avond|Weggelaten letters: ’s avonds, met een apostrof. Midden in de zin klein.} is het koud, en mijn dochter is al een week {verkouden|verk__den|ou voor de d, net als koud: verkouden.}. De muur van de badkamer is ook {vochtig|vocht → …|‘uhg’ aan het eind: -ig. vocht + ig.}.\n\nGisteren kwam er een monteur langs. Hij {zei|zeggen, verleden tijd|Van zeggen: zei, met ei. zij is een persoon.} dat de ketel te oud is. Een nieuwe ketel is volgens hem de enige {oplossing|oplossen → de …|Een woord op -ing: ng. En ss, zoals in oplossen.}. In deze {situatie|situ…|Je hoort tsie: -tie. situatie.} wil ik niet wachten tot de zomer.\n\nIk heb twee {ideeën|meervoud van idee|idee → ideeën: -ën met een trema.}. U laat de ketel deze maand vervangen, of u geeft mij een {financiële|financieel + e|-ieel + e wordt -iële, met een trema. Anders lees je ie.} vergoeding voor een {elektrische|werkt op stroom|‘ies’ aan het eind van een bijvoeglijk naamwoord: -isch. Met -e: elektrische.} kachel.\n\nIk ben {dagelijks|elke dag (één woord)|dagen met g, dus dagelijks. ‘luhks’ aan het eind: -lijks.} na vier uur {bereikbaar|te bereiken|bereiken met ei, dus ook bereikbaar.} op mijn {06-nummer|nul zes + nummer|Cijfers + woord: koppelteken. 06-nummer.}. Wilt u mij laten weten wat u hebt {beslist|beslissen|Stam beslis: de s zit in ’t kofschip en er staat geen z in beslissen. besliste, dus beslist.}?\n\nMet {vriendelijke|vriend + …|‘luhk’ aan het eind: -lijk. Met -e: vriendelijke.} groet,\nSamira El Idrissi',
      why: 'In deze mail: ’t kofschip (gemaild, gebeurd, beslist), -ing (verwarming, oplossing), ou voor d (verkouden), -ig, -lijk en -lijks, -isch, -tie, ei (zei, bereikbaar), trema (ideeën, financiële), apostrof (’s avonds) en koppelteken (cv-ketel, 06-nummer).',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort tien zinnen: een mail aan de juf van je zoon. Hoofdletters en leestekens tellen mee.',
      title: 'Een mail aan de juf',
      sentences: [
        'Vanmorgen werd mijn zoon wakker met hoofdpijn en een zere keel.',
        'Ik heb meteen de huisarts gebeld en kon om elf uur met hem langskomen.',
        'Gelukkig is hij volgens de dokter alleen flink verkouden.',
        'Bij de apotheek hebben we een neusspray en wat paracetamol gehaald.',
        'Hij moet de rest van de week thuisblijven en ’s avonds een warme douche nemen.',
        'Daarom mist hij woensdag de excursie naar het Rijksmuseum in Amsterdam.',
        'Mijn vrouw had het formulier voor die dag al ondertekend en geüpload.',
        'Kunt u zijn huiswerk en de ideeën voor het project naar mij mailen?',
        'Hij had zich al weken op dit uitje verheugd en baalt er nu erg van.',
        'Alvast hartelijk bedankt voor uw begrip.',
      ],
      right:
        'Alles goed: hoofdpijn met d, gelukkig met -ig, gebeld, gehaald, ondertekend, geüpload en verheugd met -d, verkouden met ou, apotheek en thuisblijven met th, douche en excursie als leenwoord, ideeën met trema, ’s avonds met apostrof, Rijksmuseum groot en woensdag klein.',
      wrong:
        'Kijk deze regels na. Langer maken: hoofdpijn (hoofden). ’t Kofschip: gebeld, gehaald, ondertekend, geüpload en verheugd krijgen -d. ou voor d: verkouden. Leenwoorden: apotheek en thuisblijven (th), douche (ou, ch), excursie (-sie). Trema: geüpload, ideeën. Apostrof: ’s avonds. Hoofdletter: Rijksmuseum en Amsterdam, maar woensdag klein. En -ig in gelukkig, -lijk in hartelijk.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail aan je teamleider na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'Karin Bos', subject: 'Ziek vandaag' },
      greeting: 'Hoi Karin,',
      signoff: 'Groet,\nHasan',
      tokens: [
        { t: 'Vanochtend' },
        { t: 'werd', trap: 'Goed: werd is de verleden tijd van worden, met een d. Er komt geen t achter.' },
        { t: 'ik' },
        { t: 'wakker' },
        { t: 'met' },
        { t: 'koorts' },
        { t: 'en' },
        { t: 'hooftpijn.', fix: 'hoofdpijn.', why: 'hoofd + pijn: hoofd houdt zijn d (hoofden). hoofdpijn.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'me' },
        { t: 'om' },
        { t: 'half' },
        { t: 'acht' },
        { t: 'ziek' },
        { t: 'gemelt', fix: 'gemeld', why: 'Stam meld eindigt op d: gemeld. Er komt geen t bij.' },
        { t: 'bij' },
        { t: 'de' },
        { t: 'receptie.' },
        { t: 'Mijn' },
        { t: 'huisarts' },
        { t: 'zij', fix: 'zei', also: ['zegt'], why: 'Van zeggen: zei, met ei. zij is een persoon.' },
        { t: 'dat' },
        { t: 'ik' },
        { t: 'deze' },
        { t: 'week' },
        { t: 'thuis', trap: 'Goed: thuis schrijf je met th, ook al hoor je alleen een t.' },
        { t: 'moet' },
        { t: 'blijven.' },
        { t: 'De' },
        { t: 'presentatie' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'klant' },
        { t: 'uit' },
        { t: 'Antwerpen' },
        { t: 'licht', fix: 'ligt', why: 'Van liggen: ligt, met g. licht (met ch) is van de lamp.' },
        { t: 'op' },
        { t: 'mijn' },
        { t: 'bureau.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'hem' },
        { t: 'gisteren' },
        { t: 'al' },
        { t: 'geprint.', trap: 'Goed: printen, stam print. printte, dus geprint. Er komt geen extra t bij.' },
        { t: 'Wil' },
        { t: 'jij' },
        { t: 'hem' },
        { t: 'Woensdag', fix: 'woensdag', why: 'Een dag schrijf je klein. Alleen aan het begin van een zin krijgt hij een hoofdletter.' },
        { t: 'met' },
        { t: 'de' },
        { t: 'collegas', fix: 'collega’s', also: ['collegae'], why: 'Woord op a: meervoud met ’s. Zonder apostrof lees je een korte a. (collegae mag ook.)' },
        { t: 'doornemen?' },
        { t: 'Al' },
        { t: 'hun' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + ën: ideeën, met een trema op de e van -ën.' },
        { t: 'staan' },
        { t: 'op' },
        { t: 'de' },
        { t: 'laatste' },
        { t: 'pagina.' },
        { t: 'De' },
        { t: 'mails' },
        { t: 'van' },
        { t: 'de' },
        { t: 'klant' },
        { t: 'heb' },
        { t: 'ik' },
        { t: 'allemaal' },
        { t: 'beantwoordt.', fix: 'beantwoord.', why: 'Voltooid deelwoord van beantwoorden: stam beantwoord, er komt niets achter.' },
        { t: 'Ik' },
        { t: 'kan' },
        { t: 'nauwelijks', trap: 'Goed: nauw staat in het auw-rijtje, en ‘luhks’ aan het eind is -lijks.' },
        { t: 'iets' },
        { t: 'doen,' },
        { t: 'maar' },
        { t: 'ik' },
        { t: 'ben' },
        { t: 'wel' },
        { t: 'bereikbaar' },
        { t: 'via' },
        { t: 'de' },
        { t: 'mail.' },
      ],
      done: {
        title: 'Mail kan weg',
        text: 'hoofdpijn, gemeld, zei, ligt, woensdag, collega’s, ideeën en beantwoord. werd, thuis, geprint en nauwelijks stonden al goed.',
      },
    },
    {
      kind: 'drill',
      id: 'reeks-2',
      prompt: 'Reeks 2: typ elk woord goed, met hoofdletters',
      intro:
        'Dertig opdrachten. Nu tellen hoofdletters mee: is het een naam of een gewoon woord, het begin van een zin of niet? Wat je fout doet, komt achteraan terug.',
      caps: true,
      items: [
        {
          q: 'Vul de taal in die ze in Egypte spreken',
          before: 'Mijn buurvrouw geeft les in',
          after: '.',
          a: 'Arabisch',
          why: 'Een taal krijgt een hoofdletter. En ‘ies’ aan het eind: -isch. Arabisch.',
        },
        {
          q: 'Vul de dag in: de dag na dinsdag',
          before: 'De vergadering is verplaatst naar',
          after: 'om negen uur.',
          a: 'woensdag',
          why: 'Dagen schrijf je klein, ook in een afspraak. Alleen aan het begin van een zin groot.',
        },
        {
          q: 'Vul de vorm van *wachten* in',
          before: 'Gisteren',
          after: 'wij een uur op de bus.',
          a: 'wachtten',
          why: 'Stam wacht eindigt op t: wacht + ten = wachtten.',
        },
        {
          q: 'Vul het buurland in waar Brussel ligt',
          before: 'Volgende week rijden we naar',
          after: '.',
          a: 'België',
          why: 'Een land: hoofdletter. Bel-gi-ë: trema, anders lees je ie.',
        },
        {
          q: 'Enkelvoud van *leden*',
          before: 'Ik ben al tien jaar',
          after: 'van de voetbalclub.',
          a: 'lid',
          why: 'leden met een d, dus lid met d. De klinker verandert, maar de d blijft.',
        },
        {
          q: 'Vul het feest in aan het eind van de ramadan',
          before: 'Met het',
          after: 'komt de hele familie bij ons eten.',
          a: 'Suikerfeest',
          why: 'Een feestdag is een naam: hoofdletter. Suikerfeest, met ui en ei.',
        },
        { q: 'Zelfstandig naamwoord bij *verbieden*', before: 'Op het plein geldt een', after: 'op alcohol.', a: 'verbod', why: 'verboden, dus verbod met d.' },
        {
          q: 'Vul de vorm van *vermijden* in',
          before: 'Ik',
          after: 'drukke wegen als het kan.',
          a: 'vermijd',
          why: 'Stam van vermijden: vermijd, met ij en d. Bij ik komt er niets achter.',
        },
        {
          q: 'Vul het woord in: de vakantie rond Kerstmis',
          before: 'In de',
          after: 'gaan we naar mijn ouders.',
          a: 'kerstvakantie',
          why: 'Een samenstelling met een feest is een gewoon woord: klein en aan elkaar. vakantie met -tie.',
        },
        {
          q: 'Zelfstandig naamwoord bij *verwijten*',
          before: 'Dit is geen',
          after: ', maar een tip voor de volgende keer.',
          a: 'verwijt',
          why: 'verwijten, dus verwijt met ij en t.',
        },
        {
          q: 'Vul de achternaam in van Jan de Vries',
          before: 'Ik heb een afspraak met meneer',
          after: 'van de gemeente.',
          a: 'De Vries',
          why: 'Geen voornaam of voorletter ervoor: het tussenvoegsel krijgt een hoofdletter. meneer De Vries.',
        },
        {
          q: 'Vul de vorm van *scheiden* in',
          before: 'Mijn ouders zijn al jaren',
          after: '.',
          a: 'gescheiden',
          why: 'scheiden met ei. Het voltooid deelwoord eindigt op -en: gescheiden.',
        },
        {
          q: 'Vul *serieus* in met de goede uitgang',
          before: 'Dat is een',
          after: 'klacht.',
          a: 'serieuze',
          why: '-eus met -e wordt -euze: serieuze. Je hoort een z.',
        },
        {
          q: 'Vul het land in: het eiland met vulkanen tussen Noorwegen en Groenland',
          before: 'Mijn collega gaat op vakantie naar',
          after: '.',
          a: 'IJsland',
          why: 'Een land: hoofdletter. ij is één letter: IJ, allebei groot.',
        },
        {
          q: 'Vul de verleden tijd van *gooien* in',
          before: 'Hij',
          after: 'de bal over het hek.',
          a: 'gooide',
          why: 'oo + j-klank: ooi. Stam gooi, de i zit niet in ’t kofschip: gooide.',
        },
        {
          q: 'Vul de verleden tijd van *zoeken* in',
          before: 'Wij',
          after: 'de hele avond naar de sleutels.',
          a: 'zochten',
          why: 'zoeken → zocht, meervoud zochten. Altijd ch.',
        },
        {
          q: 'Vul de windstreek in',
          before: 'Mijn zus woont in het',
          after: 'van het land, vlak bij Groningen.',
          a: 'noorden',
          why: 'Een windstreek schrijf je klein: het noorden. Alleen in een naam groot, zoals Noord-Holland.',
        },
        {
          q: 'Schrijf het woord dat je hoort: hoe goed je iets kunt, bijvoorbeeld een taal (je hoort: nie-voo)',
          say: 'het niveau',
          a: 'niveau',
          also: ['het niveau'],
          why: 'oo aan het eind van een leenwoord: eau. niveau.',
        },
        {
          q: 'Vul de functie in: de baas van de gemeente',
          before: 'Morgen opent',
          after: 'Visser het nieuwe zwembad.',
          a: 'burgemeester',
          why: 'Een titel of functie blijft klein, ook vóór een naam.',
        },
        {
          q: 'Schrijf het woord dat je hoort: daar studeer je na de middelbare school (je hoort: u-nie-ver-sie-teit)',
          say: 'de universiteit',
          a: 'universiteit',
          also: ['de universiteit'],
          why: '-teit schrijf je zoals je het hoort, met ei. universiteit.',
        },
        {
          q: 'Vul het woord in: zonder gevaar',
          before: 'Is het hier',
          after: 'om ’s avonds te fietsen?',
          a: 'veilig',
          why: 'veilig staat in het ei-rijtje. En ‘uhg’ aan het eind: -ig.',
        },
        {
          q: 'Zelfde vorm als *’s morgens*, maar dan voor de avond',
          before: '',
          after: 'werk ik in een restaurant.',
          a: '’s Avonds',
          why: '’s avonds met een apostrof. Aan het begin van de zin krijgt het woord na ’s de hoofdletter: ’s Avonds.',
        },
        {
          q: 'Vul het woord in: elke dag, met -e',
          before: 'Ik maak een',
          after: 'wandeling van een half uur.',
          a: 'dagelijkse',
          why: 'dagen met g, dus ook dagelijks. ‘luhks’: -lijks. Met -e: dagelijkse.',
        },
        {
          q: 'Vul het woord in: de dochter van je broer',
          before: 'Mijn',
          after: 'studeert rechten in Leiden.',
          a: 'nicht',
          also: ['nichtje'],
          why: 'Je hoort cht en het is geen vorm van een werkwoord met g: nicht, met ch. (nichtje is ook goed.)',
        },
        {
          q: 'Vul de vorm van *uitleggen* in',
          before: 'Mijn collega',
          after: 'de nieuwe regels morgen uit.',
          a: 'legt',
          why: 'Van leggen: stam leg + t. Een werkwoord met g: gt, geen cht.',
        },
        {
          q: 'Schrijf het woord dat je hoort (je hoort: suk-ses)',
          say: 'succes',
          before: 'Veel',
          after: 'met je examen!',
          a: 'succes',
          why: 'Twee c’s: de eerste klinkt als k, de tweede als s. succes.',
        },
        {
          q: 'Vul het woord in: niet gekookt',
          before: 'Eet geen',
          after: 'kip: dat is gevaarlijk.',
          a: 'rauwe',
          why: 'rauw staat in het auw-rijtje. rouw (met ou) is verdriet. Met -e: rauwe.',
        },
        {
          q: 'Vul de verleden tijd van *leven* in',
          before: 'Mijn grootouders',
          after: 'van wat ze zelf op het land verbouwden.',
          a: 'leefden',
          why: 'In leven staat een v: -de. De stam schrijf je met f: leef. Meervoud: leefden.',
        },
        {
          q: 'Vul de vorm van *melden* in',
          before: 'Heb jij je al ziek',
          after: 'bij je baas?',
          a: 'gemeld',
          why: 'Stam meld eindigt op d: ge + meld, er komt niets bij.',
        },
        {
          q: 'Schrijf de vrucht die je hoort: zacht en rond, met een pit en een fluwelen schil (je hoort: per-zuk)',
          say: 'de perzik',
          a: 'perzik',
          also: ['de perzik'],
          why: 'Een zelfstandig naamwoord op -ik, niet op -ig: perzik. Dat moet je kennen.',
        },
      ],
      done: {
        title: 'Tweede reeks klaar',
        text: 'Namen, talen, landen en feesten groot; dagen, windstreken en functies klein. En ertussen weer langer maken, ’t kofschip, ei of ij en leenwoorden.',
      },
    },
    {
      kind: 'cloze',
      id: 'invultekst-2',
      prompt: 'Vul het nieuwsbericht aan. Typ elk woord helemaal.',
      intro: 'In deze tekst tellen hoofdletters mee.',
      title: 'Nieuws uit de wijk: vrijmarkt op het plein',
      caps: true,
      text: 'Op {Koningsdag|het feest op 27 april|Een feestdag is een naam: hoofdletter. Koning + s + dag.} was het plein voor het {stadhuis|sta_huis|steden, dus stad met d. In een samenstelling houdt stad zijn d.} vol. Om negen uur opende {burgemeester|de baas van de gemeente|Een functie blijft klein, ook vóór een naam.} Visser de vrijmarkt. Kinderen {verkochten|verkopen, verleden tijd|verkopen → verkocht, met ch. Meervoud: verkochten.} oude boeken, speelgoed en kleren. Een jongen van tien {verdiende|verdienen, verleden tijd|Stam verdien: de n zit niet in ’t kofschip. Dus -de: verdiende.} in één ochtend dertig euro met zijn oude spelletjes. Bij de kraam van de buurvrouw kon je {Turkse|uit Turkije|Een bijvoeglijk naamwoord van een land: hoofdletter. Turks + e.} pizza en thee kopen.\n\n{’s Middags|in de middag|’s middags met een apostrof. Aan het begin van de zin krijgt het woord na ’s de hoofdletter: ’s Middags.} zong een koor uit {IJmuiden|__muiden|Een plaatsnaam met ij vooraan: IJ, allebei groot.} Nederlandse en {Arabische|taal van Marokko en Egypte|Een taal: hoofdletter. ‘ies’ aan het eind: -isch, met -e: Arabische.} liedjes. Veel mensen {dansten|dansen, verleden tijd|Stam dans: de s zit in ’t kofschip en dansen heeft geen z. danste, meervoud dansten.} mee. Ook de {politie|pol…|Je hoort tsie: -tie. politie.} kwam even kijken. Het was {gezellig|gezel…|‘uhg’ aan het eind: -ig, nooit -ich of -ug.} en het bleef de hele dag droog.\n\nDe markt {bracht|brengen, verleden tijd|brengen → bracht, met ch. Nooit brengde.} vierhonderd euro op. Dat geld gaat naar {nieuwe|niet oud|ie + w: ieuw. nieuwe.} boeken voor de {bibliotheek|waar je boeken leent|th klinkt als t: bibliotheek.} in het buurthuis. De organisatie wil alle {vrijwilligers|mensen die werken zonder loon|vrij met ij: vrijwilligers.} heel {hartelijk|met heel je hart|‘luhk’ aan het eind: -lijk. harte + lijk.} bedanken. In {mei|de maand na april|Een maand schrijf je klein. mei met ei; mij met ij is een persoon.} houdt het buurthuis een fietsenmarkt. Wie wil helpen, kan zich nu al aanmelden.',
      why: 'Hoofdletters: een feestdag (Koningsdag), een land en een taal (Turkse, Arabische), een plaatsnaam met IJ, en ’s Middags aan het begin van de zin. Klein: burgemeester en mei. Verder: stad met d, verkochten en bracht met ch, ’t kofschip (verdiende, dansten), -tie, -ig, -lijk, ieuw en th.',
    },
    {
      kind: 'proofread',
      id: 'nakijken-2',
      prompt: 'Kijk de brief aan de buren na voordat je hem rondbrengt',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      greeting: 'Beste buren,',
      signoff: 'Met vriendelijke groet,\nNadia en Kees, nummer 14',
      tokens: [
        { t: 'Volgende' },
        { t: 'week' },
        { t: 'wordt' },
        { t: 'onze' },
        { t: 'keuken' },
        { t: 'verbouwt.', fix: 'verbouwd.', why: 'verbouwen: stam verbouw, de w zit niet in ’t kofschip. verbouwde, dus verbouwd.' },
        { t: 'De' },
        { t: 'aannemer' },
        { t: 'begint' },
        { t: 'maandag' },
        { t: 'om' },
        { t: 'acht' },
        { t: 'uur' },
        { t: 'en' },
        { t: 'heeft' },
        { t: 'belooft', fix: 'beloofd', why: 'In beloven staat een v: -de en -d. beloofde, dus beloofd.' },
        { t: 'dat' },
        { t: 'hij' },
        { t: 'elke' },
        { t: 'dag' },
        { t: 'om' },
        { t: 'vijf' },
        { t: 'uur' },
        { t: 'stopt.' },
        { t: 'Er' },
        { t: 'komt' },
        { t: 'een' },
        { t: 'container', trap: 'Goed: een c voor o klinkt als k. container.' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'deur,' },
        { t: 'dus' },
        { t: 's’ochtends', fix: '’s ochtends', why: 'Eerst de apostrof, dan de s, en daarna een spatie: ’s ochtends.' },
        { t: 'is' },
        { t: 'parkeren' },
        { t: 'in' },
        { t: 'de' },
        { t: 'straat' },
        { t: 'lastich.', fix: 'lastig.', why: '‘uhg’ aan het eind: -ig, nooit -ich.' },
        { t: 'Onze' },
        { t: 'autos', fix: 'auto’s', why: 'Woord op o: meervoud met ’s. Zonder apostrof lees je een korte o.' },
        { t: 'staan' },
        { t: 'zolang' },
        { t: 'bij' },
        { t: 'het' },
        { t: 'station.' },
        { t: 'Vooral' },
        { t: 'op' },
        { t: 'dinsdag' },
        { t: 'maakt' },
        { t: 'het' },
        { t: 'slopen' },
        { t: 'veel' },
        { t: 'lawaai.', trap: 'Goed: aa + j-klank schrijf je als aai. lawaai.' },
        { t: 'Daarna' },
        { t: 'worden' },
        { t: 'de' },
        { t: 'muren' },
        { t: 'geverfd.', trap: 'Goed: in verven staat een v, dus -d. Aan het eind f: geverfd.' },
        { t: 'Hebt' },
        { t: 'u' },
        { t: 'last' },
        { t: 'van' },
        { t: 'het' },
        { t: 'geluit', fix: 'geluid', why: 'geluiden, dus geluid met d.' },
        { t: 'of' },
        { t: 'het' },
        { t: 'stof?' },
        { t: 'Stuur' },
        { t: 'ons' },
        { t: 'dan' },
        { t: 'gerust' },
        { t: 'een' },
        { t: 'email', fix: 'e-mail', also: ['mail'], why: 'Losse letter + woord: koppelteken. e-mail. (Het email is de laag op een pan.)' },
        { t: 'of' },
        { t: 'bel' },
        { t: 'even' },
        { t: 'aan.' },
        { t: 'Op' },
        { t: 'vrijdag' },
        { t: 'geven' },
        { t: 'we' },
        { t: 'als' },
        { t: 'dank' },
        { t: 'een' },
        { t: 'klein' },
        { t: 'feestje' },
        { t: 'met' },
        { t: 'turkse', fix: 'Turkse', why: 'Van een land: hoofdletter. Turkse hapjes.' },
        { t: 'hapjes.' },
        { t: 'U' },
        { t: 'bent' },
        { t: 'van' },
        { t: 'harte' },
        { t: 'welkom!' },
      ],
      done: {
        title: 'Brief kan rond',
        text: 'verbouwd, beloofd, ’s ochtends, lastig, auto’s, geluid, e-mail en Turkse. container, lawaai en geverfd stonden al goed.',
      },
    },
  ],
};
