import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": het alfabet, letternamen, spellen aan de telefoon, alfabetisch ordenen en opzoeken. */
export const LES_L20: LessonInput = {
  id: 'l20',
  stage: 'regels',
  domain: 'orth',
  title: 'Het alfabet en spellen',
  skill: 'Spelling',
  icon: 'abc',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Letters, namen en spellen',
      panels: [
        {
          text: 'Het alfabet heeft 26 letters. Elke letter heeft een naam. Die namen heb je nodig als je een woord hardop spelt: *aa*, *bee*, *cee*, *dee*, *ee*, *ef*, *gee*, *ha*, *ie*, *jee*, *ka*, *el*, *em*, *en*, *oo*, *pee*, *ku*, *er*, *es*, *tee*, *uu*, *vee*, *wee*, *iks*, *i-grec* en *zet*. De klinkers zijn *a*, *e*, *i*, *o* en *u*; de andere letters zijn medeklinkers. Let op: veel namen eindigen op dezelfde klank. Dat maakt spellen lastig.',
          rule: 'Spel je een woord, dan zeg je de naam van elke letter: *Hasan* is *ha, aa, es, aa, en*.',
          alpha: {
            q: 'Tik alle letters waarvan de naam eindigt op ee',
            targets: ['b', 'c', 'd', 'e', 'g', 'j', 'p', 't', 'v', 'w'],
            note: 'bee, cee, dee, ee, gee, jee, pee, tee, vee, wee: tien namen die bijna hetzelfde klinken. Aan de telefoon hoort de ander dan snel een verkeerde letter.',
          },
          deep: {
            q: 'En in België?',
            a: 'Daar heet de *j* meestal *jot*. De andere namen zijn hetzelfde. De *y* heet *i-grec* of *Griekse ij*.',
          },
        },
        {
          text: 'Aan de telefoon klinken *bee*, *dee*, *pee* en *tee* bijna gelijk. Daarom gebruik je een spelalfabet: bij elke letter een vast woord. Het Nederlandse spelalfabet is: *Anton*, *Bernard*, *Cornelis*, *Dirk*, *Eduard*, *Ferdinand*, *Gerard*, *Hendrik*, *Izaak*, *Johan*, *Karel*, *Lodewijk*, *Marie*, *Nico*, *Otto*, *Pieter*, *Quotiënt*, *Rudolf*, *Simon*, *Teunis*, *Utrecht*, *Victor*, *Willem*, *Xantippe*, *Ypsilon*, *Zaandam*. Voor de *ij* zeg je *IJmuiden*. Je zegt dan: *B van Bernard*.',
          rule: 'Spellen aan de telefoon: *letter + van + woord*, bijvoorbeeld *D van Dirk*.',
          lab: {
            label: 'Tik een letter die vaak misgaat',
            chips: [
              { k: 'b', out: 'B van Bernard', note: 'Zonder spelalfabet hoort de ander misschien een d, p of t.' },
              { k: 'd', out: 'D van Dirk', note: 'dee en tee klinken aan de telefoon bijna gelijk.' },
              { k: 'm', out: 'M van Marie', note: 'em en en lijken op elkaar.' },
              { k: 'f', out: 'F van Ferdinand', note: 'ef en es lijken op elkaar.' },
              { k: 'v', out: 'V van Victor', note: 'vee en wee lijken op elkaar.' },
              { k: 'ij', out: 'IJ van IJmuiden', note: 'De ij heeft een eigen woord. Zo weet de ander dat het geen ei is.' },
            ],
          },
          quiz: {
            q: 'Je spelt je achternaam Dekker aan de telefoon. Wat zeg je bij de eerste letter?',
            options: ['D van Dirk', 'dee', 'D van Teunis', 'Dee van Dekker'],
            answer: 'D van Dirk',
            why: 'Zeg je alleen dee, dan kan de ander tee horen. D van Dirk is altijd duidelijk.',
          },
        },
        {
          text: 'Bij spellen zeg je ook dingen als *hoofdletter*, *dubbele s* of *twee keer de e*. Voor een mailadres heb je de tekens nodig: *@* heet *apenstaartje*, *.* heet *punt*, *-* heet *streepje* en *_* heet *laag streepje*. En let op het verschil tussen de *ij* en de *y*: de *ij* noem je de *lange ij*, de *y* de *Griekse ij*. In woorden als *baby* en *hobby* klinkt de *y* als *ie*, in *yoghurt* en *yoga* als *j*.',
          rule: '*ij* = *lange ij* (*wijn*), *y* = *Griekse ij* (*baby*).',
          lab: {
            label: 'Tik een mailadres',
            chips: [
              { k: 'eva.smit@mail.nl', out: 'eva punt smit apenstaartje mail punt en el', note: 'Zeg elk teken: punt en apenstaartje.' },
              { k: 'jan-de-wit@mail.nl', out: 'jan streepje de streepje wit apenstaartje mail punt en el', note: 'Het korte streepje noem je gewoon streepje.' },
              { k: 'sara_bos@mail.nl', out: 'sara laag streepje bos apenstaartje mail punt en el', note: 'Het lage streepje staat onderaan de regel.' },
              { k: 'wijnhuis@mail.nl', out: 'wee, lange ij, en, ha, uu, ie, es …', note: 'Zeg lange ij, anders typt de ander misschien een y.' },
            ],
          },
          quiz: {
            q: 'Je spelt de naam Yasmin. Wat zeg je bij de eerste letter?',
            options: ['Griekse ij', 'lange ij', 'jee'],
            answer: 'Griekse ij',
            why: 'Yasmin begint met een y: de Griekse ij, of Y van Ypsilon. De lange ij is de ij van wijn.',
          },
        },
        {
          text: 'In een woordenlijst, een adresboek of een lijst met namen staan de woorden op alfabet. Je vergelijkt ze letter voor letter. Is de eerste letter gelijk, dan kijk je naar de tweede, en zo verder. Het eerste verschil beslist. Is een woord het begin van een ander woord, dan komt het kortste eerst: *boek* vóór *boeken*.',
          rule: 'Vergelijk letter voor letter: het eerste verschil beslist, en het kortste woord gaat voor.',
          swap: {
            goal: 'Zet de woorden op alfabet',
            blocks: ['kast', 'kat', 'kaas', 'kassa'],
            accept: ['kaas kassa kast kat'],
            note: 'kaas: de derde letter is een a. kassa en kast beginnen allebei met kas; dan beslist de vierde letter: s vóór t. kat: de derde letter t komt na de s.',
          },
        },
      ],
    },
    {
      kind: 'type',
      id: 'naam-w',
      prompt: 'Typ de naam van de letter.',
      before: 'De letter w heet',
      after: '.',
      hint: 'letternaam',
      answer: 'wee',
      why: 'De w heet wee. Aan de telefoon lijkt dat op vee (de v): zeg daarom W van Willem.',
    },
    {
      kind: 'type',
      id: 'naam-q',
      prompt: 'Typ de naam van de letter.',
      before: 'De letter q heet',
      after: '.',
      hint: 'letternaam',
      answer: 'ku',
      why: 'De q heet ku, met de klank van de u in nu. Niet koe. Je ziet de q bijna alleen in woorden als quiz en squash.',
    },
    {
      kind: 'type',
      id: 'kast',
      prompt: 'Iemand spelt een woord aan de telefoon. Typ het woord.',
      before: 'Karel, Anton, Simon, Teunis. Het woord is',
      after: '.',
      hint: 'woord',
      answer: 'kast',
      why: 'K van Karel, A van Anton, S van Simon, T van Teunis: kast.',
    },
    {
      kind: 'choice',
      id: 'postcode',
      prompt: 'Je geeft je postcode 3512 BD door aan de telefoon. Wat zeg je bij de letters?',
      before: '',
      after: '',
      options: ['B van Bernard, D van Dirk', 'bee, dee', 'B van Dirk, D van Bernard', 'Bernard, Dirk, snel achter elkaar zonder letter'],
      answer: 'B van Bernard, D van Dirk',
      why: 'bee en dee lijken aan de telefoon op pee en tee. Zeg de letter en het woord uit het spelalfabet erbij, in de goede volgorde.',
    },
    {
      kind: 'sort',
      id: 'y-klank',
      prompt: 'Hoe klinkt de y in dit woord?',
      buckets: ['als ie', 'als j'],
      items: [
        { t: 'baby', b: 0 },
        { t: 'yoghurt', b: 1 },
        { t: 'hobby', b: 0 },
        { t: 'yoga', b: 1 },
        { t: 'pony', b: 0 },
        { t: 'Yasmin', b: 1 },
        { t: 'jury', b: 0 },
        { t: 'Yusuf', b: 1 },
        { t: 'typisch', b: 0 },
      ],
      why: 'Aan het eind van een woord en tussen medeklinkers klinkt de y meestal als ie: baby, hobby, pony, jury, typisch. Aan het begin van een woord of naam klinkt hij meestal als j: yoghurt, yoga, Yasmin, Yusuf. Je schrijft in al die woorden een y, geen ij en geen ie.',
    },
    {
      kind: 'order',
      id: 'boek-rij',
      prompt: 'Zet de woorden op alfabet, zoals in een woordenlijst.',
      tiles: ['boekje', 'boer', 'boeken', 'boek', 'boekenkast'],
      answer: 'boek boeken boekenkast boekje boer',
      why: 'boek is het kortst en gaat voor. boeken komt vóór boekenkast. Daarna boekje: na boek komt een j, en de j komt na de e van boeken. boer als laatste: de vierde letter r komt na de k.',
    },
    {
      kind: 'chat',
      id: 'klantenservice',
      prompt: 'Je belt met de klantenservice',
      intro: 'Je bent Sanne Bakker. Je mailadres is sanne.bakker@mail.nl en je postcode is 3512 BD. Kies steeds het antwoord waarmee de medewerker het goed kan opschrijven.',
      contact: { name: 'Klantenservice', role: 'energiebedrijf', initials: 'KS' },
      rounds: [
        {
          say: 'Goedemiddag! Hoe spelt u uw achternaam?',
          options: ['Bakker: bee, aa, ka, ka, ee, er.', 'Bakker: bee, aa, kee, kee, ee, er.'],
          right: 0,
          fix: 'kee → ka',
          why: 'De k heet ka, niet kee.',
        },
        {
          say: 'En uw voornaam?',
          options: ['Sanne: es, aa, em, em, ee.', 'Sanne: es, aa, dubbele n, ee.'],
          right: 1,
          fix: 'em, em → dubbele n',
          why: 'Sanne heeft twee keer een n (en), geen m (em). Dubbele n is duidelijk en kort.',
        },
        {
          say: 'Wat is uw e-mailadres?',
          options: ['sanne punt bakker apenstaartje mail punt en el', 'sanne apenstaartje bakker punt mail punt en el'],
          right: 0,
          fix: 'sanne punt bakker apenstaartje …',
          why: 'Het adres is sanne.bakker@mail.nl: eerst de punt, dan pas het apenstaartje.',
        },
        {
          say: 'En uw postcode is 3512 BD?',
          options: ['Ja: B van Bernard, D van Dirk.', 'Ja: B van Dirk, D van Bernard.'],
          right: 0,
          fix: 'B van Bernard, D van Dirk',
          why: 'Het woord uit het spelalfabet begint met dezelfde letter: B van Bernard, D van Dirk.',
        },
      ],
      bye: 'Dank u wel, mevrouw Bakker. Ik heb alles goed genoteerd.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen bij ordenen en opzoeken',
      panels: [
        {
          text: 'De *ij* is een valkuil. In een woordenlijst en een woordenboek telt de *ij* als twee letters: een *i* en een *j*. Je zoekt *ijs* dus bij de *i*, en niet bij de *y*. *ijs* staat na *iglo* (*g* vóór *j*) en vóór *ik* (*j* vóór *k*).',
          rule: 'Bij het ordenen is *ij* gewoon *i* + *j*.',
          swap: {
            goal: 'Zet de woorden op alfabet',
            blocks: ['ik', 'ijs', 'iglo', 'iets'],
            accept: ['iets iglo ijs ik'],
            note: 'Kijk naar de tweede letter: iets (e), iglo (g), ijs (j), ik (k).',
          },
        },
        {
          text: 'Accenten, hoofdletters, streepjes en spaties tellen bij het ordenen niet mee. Je leest *één* als *een*, *e-mail* als *email* en *Ede* als *ede*. Alleen de letters zelf beslissen.',
          rule: 'Bij het ordenen tellen alleen de letters: geen accent, geen hoofdletter, geen streepje.',
          swap: {
            goal: 'Zet de woorden op alfabet',
            blocks: ['e-mail', 'eerlijk', 'één', 'echt'],
            accept: ['echt één eerlijk e-mail'],
            note: 'Lees echt, een, eerlijk, email. echt: c als tweede letter. één en eerlijk beginnen met ee; dan beslist de derde letter: n vóór r. email als laatste: m komt na e.',
          },
        },
        {
          text: 'Achternamen met *de*, *van*, *van der* of *ten* sorteer je in Nederland op het hoofdwoord van de achternaam. Het kleine woordje zet je erachter: *Jan de Vries* staat als *Vries, Jan de* onder de *V*. *Eva van Dijk* staat onder de *D*.',
          rule: 'Nederland: sorteer op het hoofdwoord. *Jan de Vries* → *Vries, Jan de*.',
          lab: {
            label: 'Tik een naam',
            chips: [
              { k: 'Jan de Vries', out: 'Vries, Jan de', note: 'Onder de V.' },
              { k: 'Eva van Dijk', out: 'Dijk, Eva van', note: 'Onder de D.' },
              { k: 'Sam van der Berg', out: 'Berg, Sam van der', note: 'Ook twee woordjes ervoor tellen niet mee: onder de B.' },
              { k: 'Ria ten Brink', out: 'Brink, Ria ten', note: 'ten telt niet mee: onder de B.' },
              { k: 'Tom Bakker', out: 'Bakker, Tom', note: 'Geen tussenvoegsel: gewoon onder de B.' },
            ],
          },
          quiz: {
            q: 'Een Nederlandse ledenlijst. Onder welke letter staat Kees van den Broek?',
            options: ['B', 'V', 'D', 'K'],
            answer: 'B',
            why: 'van den telt niet mee. Je sorteert op Broek: Broek, Kees van den.',
          },
          deep: {
            q: 'En in België?',
            a: 'In België hoort het woordje bij de achternaam. Je sorteert op de hele naam zoals hij in het paspoort staat: *Van den Broek* staat onder de *V*, *De Smet* onder de *D*.',
          },
        },
        {
          text: 'Twijfel je over een spelling? Zoek het woord op in de officiële woordenlijst (*woordenlijst.org*) of in een woordenboek. Stappenplan: 1. Zoek de basisvorm: het enkelvoud (*huizen* → *huis*), het hele werkwoord (*liep* → *lopen*) of het woord zonder *-e* (*grote* → *groot*). 2. Ga letter voor letter: eerste letter, tweede letter, derde letter. 3. Een woord met *ij* zoek je bij de *i*. 4. Bij de basisvorm staan vaak ook het meervoud en het verkleinwoord.',
          rule: 'Opzoeken: eerst de basisvorm, dan letter voor letter.',
          quiz: {
            q: 'Je leest: ‘Wij gingen naar huis.’ Welk woord zoek je op om gingen te controleren?',
            options: ['gaan', 'ging', 'gingen', 'gegaan'],
            answer: 'gaan',
            why: 'Werkwoorden staan in het woordenboek als hele werkwoord: gaan. Daar vind je ook ging, gingen en gegaan.',
          },
        },
      ],
    },
    {
      kind: 'order',
      id: 'ij-rij',
      prompt: 'Zet de woorden op alfabet, zoals in een woordenlijst.',
      tiles: ['ijzer', 'in', 'iglo', 'idee', 'ik'],
      answer: 'idee iglo ijzer ik in',
      why: 'De ij telt als i + j. Kijk dus naar de tweede letter: idee (d), iglo (g), ijzer (j), ik (k), in (n).',
    },
    {
      kind: 'bet',
      id: 'iets-ijs',
      prompt: 'Welk woord staat in het woordenboek het eerst?',
      intro: 'Denk aan de ij. Hoe zeker ben je?',
      options: ['ijs', 'iets', 'ik'],
      answer: 'iets',
      why: 'iets begint met i + e, ijs met i + j en ik met i + k. De e komt vóór de j en de k, dus iets staat het eerst.',
    },
    {
      kind: 'order',
      id: 'namen',
      prompt: 'Zet de namen op volgorde, zoals in een Nederlandse lijst.',
      tiles: ['Lisa de Vries', 'Tom Bakker', 'Eva van Dijk', 'Sam van der Berg', 'Noor Dekker'],
      answer: 'Tom Bakker Sam van der Berg Noor Dekker Eva van Dijk Lisa de Vries',
      why: 'Sorteer op Bakker, Berg, Dekker, Dijk, Vries. de, van en van der tellen niet mee. Dekker vóór Dijk: de tweede letter e komt vóór de i.',
    },
    {
      kind: 'sort',
      id: 'onder-welke-letter',
      prompt: 'Een Nederlandse lijst. Onder welke letter staat de naam?',
      buckets: ['B', 'D', 'V'],
      items: [
        { t: 'Jan de Vries', b: 2 },
        { t: 'Anna van Dam', b: 1 },
        { t: 'Piet Vos', b: 2 },
        { t: 'Els van den Berg', b: 0 },
        { t: 'Tim Dekker', b: 1 },
        { t: 'Sara de Boer', b: 0 },
        { t: 'Mark van Vliet', b: 2 },
        { t: 'Ilse van Doorn', b: 1 },
        { t: 'Bram Verhoeven', b: 2 },
        { t: 'Lotte de Bruin', b: 0 },
      ],
      why: 'Sorteer op het hoofdwoord: Vries, Vos, Vliet en Verhoeven onder de V; Dam, Dekker en Doorn onder de D; Berg, Boer en Bruin onder de B. Let op: Verhoeven is één woord zonder tussenvoegsel, dus gewoon de V.',
    },
    {
      kind: 'order',
      id: 'tekens-rij',
      prompt: 'Zet de woorden op alfabet, zoals in een woordenlijst.',
      tiles: ['café', 'cacao', 'cake', 'cadeau'],
      answer: 'cacao cadeau café cake',
      why: 'Lees cafe zonder accent. Alle vier beginnen met ca; de derde letter beslist: c, d, f, k.',
    },
    {
      kind: 'choice',
      id: 'opzoeken',
      prompt: 'Je wilt de spelling van ‘grotere’ controleren. Welk woord zoek je op?',
      before: '',
      after: '',
      options: ['groot', 'grote', 'grotere', 'groter'],
      answer: 'groot',
      why: 'Bijvoeglijke naamwoorden staan in het woordenboek zonder -e en zonder -er: groot. Daar staan ook grote, groter en grootst.',
    },
    {
      kind: 'swipe',
      id: 'alfabet-waar',
      prompt: 'Klopt het?',
      intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
      cards: [
        { t: 'Het alfabet heeft 26 letters.', ok: true, why: 'Van a tot en met z: 26 letters.' },
        { t: 'In het woordenboek zoek je ijs bij de y.', ok: false, fix: 'ijs zoek je bij de i: i + j', why: 'Bij het ordenen telt de ij als i + j.' },
        { t: 'De k heet ka en de h heet ha.', ok: true, why: 'Net als de a (aa) eindigen ka en ha op een a-klank.' },
        { t: 'In een Nederlandse lijst staat Kees van Dam onder de V.', ok: false, fix: 'onder de D: Dam, Kees van', why: 'In Nederland tellen de, van en van der niet mee bij het sorteren.' },
        { t: 'Het teken @ in een mailadres heet apenstaartje.', ok: true, why: 'Je zegt bijvoorbeeld: sanne apenstaartje mail punt en el.' },
        { t: 'In baby klinkt de y als een j.', ok: false, fix: 'de y klinkt hier als ie', why: 'Aan het eind van baby, hobby en pony klinkt de y als ie. Als j klinkt hij in yoghurt en yoga.' },
        { t: 'Bij het ordenen staat één op dezelfde plek als een.', ok: true, why: 'Accenten tellen bij het ordenen niet mee.' },
        { t: 'Aan de telefoon zeg je: D van Dirk.', ok: true, why: 'Letter, van, en het woord uit het spelalfabet.' },
      ],
    },
    {
      kind: 'type',
      id: 'wijn',
      prompt: 'Iemand spelt een woord aan de telefoon. Typ het woord.',
      before: 'Willem, IJmuiden, Nico. Het woord is',
      after: '.',
      hint: 'woord',
      answer: 'wijn',
      why: 'W van Willem, IJ van IJmuiden, N van Nico: wijn. Met IJmuiden weet je zeker dat het geen ei is.',
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ precies wat je hoort.',
      intro: 'Let op de hoofdletter aan het begin en de punt aan het eind.',
      sentence: 'In het woordenboek staat ijs tussen iglo en ik.',
      right: 'Goed. ijs met ij, en de woorden staan op de goede plek: de ij telt als i + j.',
      wrong: 'Kijk nog eens: In het woordenboek staat ijs tussen iglo en ik. Een hoofdletter aan het begin, ijs met ij en een punt aan het eind.',
    },
  ],
};
