import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": het alfabet, letternamen, spellen aan de telefoon, alfabetisch ordenen en opzoeken. */
export const LES_L20: LessonInput = {
  id: 'l20',
  stage: 'regels',
  domain: 'orth',
  title: 'Het alfabet en spellen',
  skill: 'Spelling',
  icon: 'abc',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Letters, namen en spellen',
      panels: [
        {
          text: 'Het alfabet heeft 26 letters. Elke letter heeft een naam. Die namen heb je nodig als je een woord hardop spelt: *aa*, *bee*, *cee*, *dee*, *ee*, *ef*, *gee*, *ha*, *ie*, *jee*, *ka*, *el*, *em*, *en*, *oo*, *pee*, *ku*, *er*, *es*, *tee*, *uu*, *vee*, *wee*, *iks*, *i-grec* en *zet*. De klinkers zijn *a*, *e*, *i*, *o* en *u*; de andere letters zijn medeklinkers, behalve de *y*: die is soms een klinker. Let op: veel namen eindigen op dezelfde klank. Dat maakt spellen lastig.',
          rule: 'Spel je een woord, dan zeg je de naam van elke letter: *Hasan* is *ha, aa, es, aa, en*.',
          alpha: {
            q: 'Tik alle letters waarvan de naam eindigt op ee',
            targets: ['b', 'c', 'd', 'e', 'g', 'j', 'p', 't', 'v', 'w'],
            note: 'bee, cee, dee, ee, gee, jee, pee, tee, vee, wee: tien namen die bijna hetzelfde klinken. Aan de telefoon hoort de ander dan snel een verkeerde letter.',
          },
          deep: {
            q: 'En in België?',
            a: 'Daar heet de *j* meestal *jot*. De andere namen zijn hetzelfde. De *y* heet *i-grec* of *Griekse ij*.',
          },
        },
        {
          text: 'Aan de telefoon klinken *bee*, *dee*, *pee* en *tee* bijna gelijk. Daarom gebruik je een spelalfabet: bij elke letter een vast woord. Het Nederlandse spelalfabet is: *Anton*, *Bernard*, *Cornelis*, *Dirk*, *Eduard*, *Ferdinand*, *Gerard*, *Hendrik*, *Izaak*, *Johan*, *Karel*, *Lodewijk*, *Marie*, *Nico*, *Otto*, *Pieter*, *Quotiënt*, *Rudolf*, *Simon*, *Teunis*, *Utrecht*, *Victor*, *Willem*, *Xantippe*, *Ypsilon*, *Zaandam*. Voor de *ij* zeg je *IJmuiden*. Je zegt dan: *B van Bernard*.',
          rule: 'Spellen aan de telefoon: *letter + van + woord*, bijvoorbeeld *D van Dirk*.',
          lab: {
            label: 'Tik een letter die vaak misgaat',
            chips: [
              { k: 'b', out: 'B van Bernard', note: 'Zonder spelalfabet hoort de ander misschien een d, p of t.' },
              { k: 'd', out: 'D van Dirk', note: 'dee en tee klinken aan de telefoon bijna gelijk.' },
              { k: 'm', out: 'M van Marie', note: 'em en en lijken op elkaar.' },
              { k: 'f', out: 'F van Ferdinand', note: 'ef en es lijken op elkaar.' },
              { k: 'v', out: 'V van Victor', note: 'vee en wee lijken op elkaar.' },
              { k: 'ij', out: 'IJ van IJmuiden', note: 'De ij heeft een eigen woord. Zo weet de ander dat het geen ei is.' },
            ],
          },
          quiz: {
            q: 'Je spelt je achternaam Dekker aan de telefoon. Wat zeg je bij de eerste letter?',
            options: ['D van Dirk', 'dee', 'D van Teunis', 'Dee van Dekker'],
            answer: 'D van Dirk',
            why: 'Zeg je alleen dee, dan kan de ander tee horen. D van Dirk is altijd duidelijk.',
          },
        },
        {
          text: 'Bij spellen zeg je ook dingen als *hoofdletter*, *dubbele s* of *twee keer de e*. Voor een mailadres heb je de tekens nodig: *@* heet *apenstaartje*, *.* heet *punt*, *-* heet *streepje* en *_* heet *laag streepje*. En let op het verschil tussen de *ij* en de *y*: de *ij* noem je de *lange ij*, de *y* de *Griekse ij*. In woorden als *baby* en *hobby* klinkt de *y* als *ie*, in *yoghurt* en *yoga* als *j*.',
          rule: '*ij* = *lange ij* (*wijn*), *y* = *Griekse ij* (*baby*).',
          lab: {
            label: 'Tik een mailadres',
            chips: [
              { k: 'eva.smit@mail.nl', out: 'eva punt smit apenstaartje mail punt en el', note: 'Zeg elk teken: punt en apenstaartje.' },
              {
                k: 'jan-de-wit@mail.nl',
                out: 'jan streepje de streepje wit apenstaartje mail punt en el',
                note: 'Het korte streepje noem je gewoon streepje.',
              },
              { k: 'sara_bos@mail.nl', out: 'sara laag streepje bos apenstaartje mail punt en el', note: 'Het lage streepje staat onderaan de regel.' },
              { k: 'wijnhuis@mail.nl', out: 'wee, lange ij, en, ha, uu, ie, es …', note: 'Zeg lange ij, anders typt de ander misschien een y.' },
            ],
          },
          quiz: {
            q: 'Je spelt de naam Yasmin. Wat zeg je bij de eerste letter?',
            options: ['Griekse ij', 'lange ij', 'jee'],
            answer: 'Griekse ij',
            why: 'Yasmin begint met een y: de Griekse ij, of Y van Ypsilon. De lange ij is de ij van wijn.',
          },
        },
        {
          text: 'In een woordenlijst, een adresboek of een lijst met namen staan de woorden op alfabet. Je vergelijkt ze letter voor letter. Is de eerste letter gelijk, dan kijk je naar de tweede, en zo verder. Het eerste verschil beslist. Is een woord het begin van een ander woord, dan komt het kortste eerst: *boek* vóór *boeken*.',
          rule: 'Vergelijk letter voor letter: het eerste verschil beslist, en het kortste woord gaat voor.',
          swap: {
            goal: 'Zet de woorden op alfabet',
            blocks: ['kast', 'kat', 'kaas', 'kassa'],
            accept: ['kaas kassa kast kat'],
            note: 'kaas: de derde letter is een a. kassa en kast beginnen allebei met kas; dan beslist de vierde letter: s vóór t. kat: de derde letter t komt na de s.',
          },
        },
      ],
    },
    {
      kind: 'type',
      id: 'naam-q',
      prompt: 'Typ de naam van de letter.',
      before: 'De letter q heet',
      after: '.',
      hint: 'letternaam',
      answer: 'ku',
      why: 'De q heet ku, met de klank van de u in nu. Niet koe. Je ziet de q bijna alleen in woorden als quiz en squash.',
    },
    {
      kind: 'type',
      id: 'spel-vrijheid',
      prompt: 'Iemand spelt een woord aan de telefoon. Typ het woord.',
      before: 'vee, er, lange ij, ha, ee, ie, dee. Het woord is',
      after: '.',
      hint: '',
      answer: 'vrijheid',
      why: 'vee = v, er = r, lange ij = ij, ha = h, ee + ie = ei, dee = d: vrijheid. De ij heeft een eigen naam (lange ij); de ei spel je als twee letters: ee, ie.',
    },
    {
      kind: 'type',
      id: 'spelalfabet-x',
      prompt: 'Welk woord uit het spelalfabet zeg je bij deze letter?',
      before: 'Je postcode eindigt op KX. Je zegt: K van Karel, X van',
      after: '.',
      hint: '',
      answer: 'Xantippe',
      why: 'X van Xantippe: een x vooraan, dubbele p en een e aan het eind.',
    },
    {
      kind: 'choice',
      id: 'postcode',
      prompt: 'Je geeft je postcode 3512 BD door aan de telefoon. Wat zeg je bij de letters?',
      before: '',
      after: '',
      options: ['B van Bernard, D van Dirk', 'bee, dee', 'B van Dirk, D van Bernard', 'Bernard, Dirk, snel achter elkaar zonder letter'],
      answer: 'B van Bernard, D van Dirk',
      why: 'bee en dee lijken aan de telefoon op pee en tee. Zeg de letter en het woord uit het spelalfabet erbij, in de goede volgorde.',
    },
    {
      kind: 'sort',
      id: 'y-klank',
      prompt: 'Hoe klinkt de y in dit woord?',
      buckets: ['als ie', 'als j'],
      items: [
        { t: 'baby', b: 0 },
        { t: 'yoghurt', b: 1 },
        { t: 'cyclus', b: 0 },
        { t: 'royaal', b: 1 },
        { t: 'Yvonne', b: 0 },
        { t: 'Yusuf', b: 1 },
        { t: 'jury', b: 0 },
        { t: 'loyaal', b: 1 },
        { t: 'analyse', b: 0 },
        { t: 'yoga', b: 1 },
        { t: 'typisch', b: 0 },
        { t: 'Yasmin', b: 1 },
        { t: 'hobby', b: 0 },
        { t: 'pony', b: 0 },
      ],
      why: 'Kijk naar de letter na de y. Staat er een klinker na, dan klinkt de y meestal als j: yoghurt, yoga, Yasmin, Yusuf, royaal, loyaal. Staat er een medeklinker na of niets, dan klinkt hij meestal als ie: baby, hobby, pony, jury, typisch, cyclus, analyse, en ook Yvonne. In al deze woorden schrijf je een y: geen ij, geen ie en geen j.',
    },
    {
      kind: 'order',
      id: 'boek-rij',
      prompt: 'Zet de woorden op alfabet, zoals in een woordenlijst.',
      tiles: ['boekje', 'boer', 'boeken', 'boei', 'boek', 'boekhouder', 'boekenkast'],
      answer: 'boei boek boeken boekenkast boekhouder boekje boer',
      why: 'boei gaat voor: de vierde letter i komt vóór de k. boek is het begin van boeken, en boeken is het begin van boekenkast: het kortste woord eerst. Daarna beslist de vijfde letter: boeke(nkast), boekh(ouder), boekj(e): e, h, j. boer als laatste: de vierde letter r komt na de k.',
    },
    {
      kind: 'chat',
      id: 'klantenservice',
      prompt: 'Je belt met de klantenservice',
      intro:
        'Je bent Sanne Bakker. Je mailadres is sanne.bakker@mail.nl en je postcode is 3512 BD. Kies steeds het antwoord waarmee de medewerker het goed kan opschrijven.',
      contact: { name: 'Klantenservice', role: 'energiebedrijf', initials: 'KS' },
      rounds: [
        {
          say: 'Goedemiddag! Hoe spelt u uw achternaam?',
          options: ['Bakker: bee, aa, kee, kee, ee, er.', 'Bakker: bee, aa, ka, ka, ee, er.', 'Bakker: bee, aa, ka, ka, ie, er.'],
          right: 1,
          fix: 'bee, aa, ka, ka, ee, er',
          why: 'De k heet ka, niet kee. De e heet ee; ie is de naam van de i.',
        },
        {
          say: 'En uw voornaam?',
          options: ['Sanne: es, aa, em, em, ee.', 'Sanne: es, aa, en, ie.', 'Sanne: es, aa, dubbele n, ee.'],
          right: 2,
          fix: 'es, aa, dubbele n, ee',
          why: 'Sanne heeft twee keer een n (en), geen m (em). Dubbele n is duidelijk en kort. Aan het eind staat een e (ee), geen i (ie).',
        },
        {
          say: 'Wat is uw e-mailadres?',
          options: [
            'sanne punt bakker apenstaartje mail punt en el',
            'sanne apenstaartje bakker punt mail punt en el',
            'sanne streepje bakker apenstaartje mail punt en el',
          ],
          right: 0,
          fix: 'sanne punt bakker apenstaartje …',
          why: 'Het adres is sanne.bakker@mail.nl: eerst de punt, dan pas het apenstaartje. Een streepje is het teken -, dat staat er niet in.',
        },
        {
          say: 'En uw postcode is 3512 BD?',
          options: ['Ja: B van Dirk, D van Bernard.', 'Ja: bee, dee.', 'Ja: B van Bernard, D van Dirk.'],
          right: 2,
          fix: 'B van Bernard, D van Dirk',
          why: 'Het woord uit het spelalfabet begint met dezelfde letter: B van Bernard, D van Dirk. Alleen bee, dee kan de ander horen als pee, tee.',
        },
      ],
      bye: 'Dank u wel, mevrouw Bakker. Ik heb alles goed genoteerd.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Valkuilen bij ordenen en opzoeken',
      panels: [
        {
          text: 'De *ij* is een valkuil. In een woordenlijst en een woordenboek telt de *ij* als twee letters: een *i* en een *j*. Je zoekt *ijs* dus bij de *i*, en niet bij de *y*. *ijs* staat na *iglo* (*g* vóór *j*) en vóór *ik* (*j* vóór *k*).',
          rule: 'Bij het ordenen is *ij* gewoon *i* + *j*.',
          swap: {
            goal: 'Zet de woorden op alfabet',
            blocks: ['ik', 'ijs', 'iglo', 'iets'],
            accept: ['iets iglo ijs ik'],
            note: 'Kijk naar de tweede letter: iets (e), iglo (g), ijs (j), ik (k).',
          },
        },
        {
          text: 'Accenten, hoofdletters, streepjes en spaties tellen bij het ordenen niet mee. Je leest *één* als *een*, *e-mail* als *email* en *Ede* als *ede*. Alleen de letters zelf beslissen.',
          rule: 'Bij het ordenen tellen alleen de letters: geen accent, geen hoofdletter, geen streepje.',
          swap: {
            goal: 'Zet de woorden op alfabet',
            blocks: ['e-mail', 'eerlijk', 'één', 'echt'],
            accept: ['echt één eerlijk e-mail'],
            note: 'Lees echt, een, eerlijk, email. echt: c als tweede letter. één en eerlijk beginnen met ee; dan beslist de derde letter: n vóór r. email als laatste: m komt na e.',
          },
        },
        {
          text: 'Achternamen met *de*, *van*, *van der* of *ten* sorteer je in Nederland op het hoofdwoord van de achternaam. Het kleine woordje zet je erachter: *Jan de Vries* staat als *Vries, Jan de* onder de *V*. *Eva van Dijk* staat onder de *D*.',
          rule: 'Nederland: sorteer op het hoofdwoord. *Jan de Vries* → *Vries, Jan de*.',
          lab: {
            label: 'Tik een naam',
            chips: [
              { k: 'Jan de Vries', out: 'Vries, Jan de', note: 'Onder de V.' },
              { k: 'Eva van Dijk', out: 'Dijk, Eva van', note: 'Onder de D.' },
              { k: 'Sam van den Berg', out: 'Berg, Sam van den', note: 'Ook twee woordjes ervoor tellen niet mee: onder de B.' },
              { k: 'Ria ten Brink', out: 'Brink, Ria ten', note: 'ten telt niet mee: onder de B.' },
              { k: 'Tom Bakker', out: 'Bakker, Tom', note: 'Geen tussenvoegsel: gewoon onder de B.' },
            ],
          },
          quiz: {
            q: 'Een Nederlandse ledenlijst. Onder welke letter staat Kees van den Broek?',
            options: ['B', 'V', 'D', 'K'],
            answer: 'B',
            why: 'van den telt niet mee. Je sorteert op Broek: Broek, Kees van den.',
          },
          deep: {
            q: 'En in België?',
            a: 'In België hoort het woordje bij de achternaam. Je sorteert op de hele naam zoals hij in het paspoort staat: *Van den Broek* staat onder de *V*, *De Smet* onder de *D*.',
          },
        },
        {
          text: 'Twijfel je over een spelling? Zoek het woord op in de officiële woordenlijst (*woordenlijst.org*) of in een woordenboek. Stappenplan: 1. Zoek de basisvorm: het enkelvoud (*huizen* → *huis*), het hele werkwoord (*liep* → *lopen*) of het woord zonder *-e* (*grote* → *groot*). 2. Ga letter voor letter: eerste letter, tweede letter, derde letter. 3. Een woord met *ij* zoek je bij de *i*. 4. Bij de basisvorm staan vaak ook het meervoud en het verkleinwoord.',
          rule: 'Opzoeken: eerst de basisvorm, dan letter voor letter.',
          quiz: {
            q: 'Je leest: ‘Wij gingen naar huis.’ Welk woord zoek je op om gingen te controleren?',
            options: ['gaan', 'ging', 'gingen', 'gegaan'],
            answer: 'gaan',
            why: 'Werkwoorden staan in het woordenboek als hele werkwoord: gaan. Daar vind je ook ging, gingen en gegaan.',
          },
        },
      ],
    },
    {
      kind: 'order',
      id: 'ij-rij',
      prompt: 'Zet de woorden op alfabet, zoals in een woordenlijst.',
      tiles: ['ijzer', 'in', 'IJsland', 'iglo', 'idee', 'ik', 'ijs'],
      answer: 'idee iglo ijs IJsland ijzer ik in',
      why: 'De ij telt als i + j, en een hoofdletter telt niet mee. Kijk eerst naar de tweede letter: idee (d), iglo (g), dan de woorden met ij (j), ik (k), in (n). Bij de woorden met ij: ijs is het begin van IJsland, dus ijs eerst. ijzer als laatste: z komt na s.',
    },
    {
      kind: 'bet',
      id: 'wie-eerst',
      prompt: 'Welk woord staat in een alfabetische lijst het eerst?',
      intro: 'Hoe zeker ben je?',
      options: ['ijverig', 'iets', 'Ierland', 'ivoor'],
      answer: 'Ierland',
      why: 'Vergelijk letter voor letter; de hoofdletter telt niet mee. Ierland en iets beginnen allebei met ie. Dan beslist de derde letter: r komt vóór t. ijverig (i + j) en ivoor (i + v) komen later.',
    },
    {
      kind: 'order',
      id: 'namen',
      prompt: 'Zet de namen op volgorde, zoals in een Nederlandse lijst.',
      tiles: ['Lisa de Vries', 'Tom Bakker', 'Ilse Verhoeven', 'Eva van Dijk', 'Kees van den Broek', 'Sam van den Berg', 'Noor Dekker'],
      answer: 'Tom Bakker Sam van den Berg Kees van den Broek Noor Dekker Eva van Dijk Ilse Verhoeven Lisa de Vries',
      why: 'Sorteer op Bakker, Berg, Broek, Dekker, Dijk, Verhoeven, Vries. de, van, van der en van den tellen niet mee. Dekker vóór Dijk: e komt vóór i. Verhoeven is één woord zonder klein woordje ervoor; e komt vóór r, dus Verhoeven vóór Vries.',
    },
    {
      kind: 'sort',
      id: 'onder-welke-letter',
      prompt: 'Een Nederlandse lijst. Onder welke letter staat de naam?',
      buckets: ['B', 'D', 'V'],
      items: [
        { t: 'Jan de Vries', b: 2 },
        { t: 'Anna van Dam', b: 1 },
        { t: 'Piet Vos', b: 2 },
        { t: 'Els van den Berg', b: 0 },
        { t: 'Tim Dekker', b: 1 },
        { t: 'Sara de Boer', b: 0 },
        { t: 'Mark van Vliet', b: 2 },
        { t: 'Ilse van Doorn', b: 1 },
        { t: 'Bram Verhoeven', b: 2 },
        { t: 'Lotte de Bruin', b: 0 },
        { t: 'Daan de Valk', b: 2 },
        { t: 'Mila van Beek', b: 0 },
        { t: 'Ruud van Dongen', b: 1 },
        { t: 'Johan van de Velde', b: 2 },
      ],
      why: 'Sorteer op het hoofdwoord van de achternaam. B: Berg, Boer, Bruin, Beek. D: Dam, Dekker, Doorn, Dongen. V: Vries, Vos, Vliet, Verhoeven, Valk, Velde. de, van, van de en van den tellen niet mee. Verhoeven is één woord zonder klein woordje ervoor, dus gewoon de V.',
    },
    {
      kind: 'order',
      id: 'tekens-rij',
      prompt: 'Zet de woorden op alfabet, zoals in een woordenlijst.',
      tiles: ['café', 'cd-speler', 'cacao', 'Canada', 'cake', 'cadeau'],
      answer: 'cacao cadeau café cake Canada cd-speler',
      why: 'Lees zonder accent, hoofdletter en streepje: cafe, canada, cdspeler. De eerste vijf beginnen met ca; de derde letter beslist: c, d, f, k, n. cdspeler als laatste: de tweede letter d komt na de a.',
    },
    {
      kind: 'choice',
      id: 'opzoeken',
      prompt: 'Je wilt de spelling van ‘grotere’ controleren. Welk woord zoek je op?',
      before: '',
      after: '',
      options: ['groot', 'grote', 'grotere', 'groter'],
      answer: 'groot',
      why: 'Bijvoeglijke naamwoorden staan in het woordenboek zonder -e en zonder -er: groot. Daar staan ook grote, groter en grootst.',
    },
    {
      kind: 'swipe',
      id: 'alfabet-waar',
      prompt: 'Klopt het?',
      intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
      cards: [
        { t: 'Om liep te controleren, zoek je lopen op.', ok: true, why: 'Een werkwoord zoek je op als hele werkwoord: lopen.' },
        { t: 'In het woordenboek zoek je ijs bij de y.', ok: false, fix: 'ijs zoek je bij de i: i + j', why: 'Bij het ordenen telt de ij als i + j.' },
        { t: 'De k heet ka en de h heet ha.', ok: true, why: 'Net als de a (aa) eindigen ka en ha op een a-klank.' },
        {
          t: 'In een Nederlandse lijst staat Kees van Dam onder de V.',
          ok: false,
          fix: 'onder de D: Dam, Kees van',
          why: 'In Nederland tellen de, van en van der niet mee bij het sorteren.',
        },
        { t: 'Het teken _ in een mailadres heet laag streepje.', ok: true, why: 'Het gewone - heet streepje; het _ onderaan de regel heet laag streepje.' },
        {
          t: 'In Yvonne klinkt de y als een j.',
          ok: false,
          fix: 'de y klinkt hier als ie',
          why: 'Na de y staat een medeklinker (v): dan klinkt hij als ie. Als j klinkt hij vóór een klinker, zoals in yoga.',
        },
        { t: 'Bij het ordenen staat één op dezelfde plek als een.', ok: true, why: 'Accenten tellen bij het ordenen niet mee.' },
        { t: 'In een woordenlijst staat ijzer vóór ik.', ok: true, why: 'ij telt als i + j, en de j komt vóór de k.' },
        {
          t: 'In een woordenlijst staat boekje vóór boekenkast.',
          ok: false,
          fix: 'boekenkast staat vóór boekje',
          why: 'Na boek beslist de vijfde letter: e (boekenkast) komt vóór j (boekje).',
        },
        { t: 'De j heet in Nederland jot.', ok: false, fix: 'de j heet jee', why: 'jot zeggen ze in België. In Nederland heet de j jee.' },
        { t: 'In een Nederlandse lijst staat Bram Verhoeven onder de V.', ok: true, why: 'Verhoeven is één woord, zonder klein woordje ervoor.' },
        {
          t: 'In een woordenlijst staat e-mail vóór eerlijk.',
          ok: false,
          fix: 'eerlijk staat vóór e-mail',
          why: 'Lees email, zonder streepje. Dan beslist de tweede letter: e (eerlijk) komt vóór m (email).',
        },
      ],
    },
    {
      kind: 'dictation',
      id: 'dictee',
      prompt: 'Luister en typ precies wat je hoort.',
      intro: 'Let op hoofdletters, komma’s en de punt aan het eind.',
      sentence: 'Bij het spellen van mijn mailadres noem ik de punt, het streepje en het apenstaartje apart.',
      right: 'Goed. mailadres en apenstaartje schrijf je als één woord. En de komma staat goed: tussen de eerste twee dingen van de rij, niet voor en.',
      wrong:
        'Kijk nog eens: Bij het spellen van mijn mailadres noem ik de punt, het streepje en het apenstaartje apart. mailadres en apenstaartje zijn één woord. In een rij van drie staat een komma na het eerste ding (punt), niet voor en.',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk antwoord zelf',
      intro: 'Vierentwintig opdrachten door elkaar: letternamen, spelalfabet, ordenen en opzoeken. Wat je fout doet, komt achteraan terug.',
      items: [
        { q: 'Iemand spelt een woord: *gee, ee, ha, ee, ie, em*. Typ het woord.', a: 'geheim', why: 'gee = g, ha = h, em = m. ee + ie is de ei: geheim.' },
        { q: 'Welke letter heet *ku*?', a: 'q', why: 'ku is de naam van de q, met de u van nu. Niet koe.' },
        {
          q: 'Welke basisvorm zoek je op als je *vermeden* wilt controleren?',
          a: 'vermijden',
          why: 'vermeden is een vorm van vermijden. Een werkwoord zoek je op als hele werkwoord.',
        },
        { q: 'Welk woord uit het spelalfabet zeg je bij de *l*?', a: 'Lodewijk', why: 'L van Lodewijk: met ij en een k aan het eind.' },
        {
          q: 'Zo staat *Kees van den Broek* in een Nederlandse lijst. Typ: achternaam, komma, de rest.',
          a: 'Broek, Kees van den',
          why: 'Het hoofdwoord Broek gaat voorop. Het kleine woordje van den komt achter de voornaam.',
        },
        {
          q: 'Iemand spelt een woord: *es, Griekse ij, es, tee, ee, ee, em*. Typ het woord.',
          a: 'systeem',
          why: 'Griekse ij = y. ee, ee = twee keer de e: systeem.',
        },
        { q: 'Hoe heet de *x* als je een woord hardop spelt?', a: 'iks', why: 'De x heet iks.' },
        {
          q: 'Schrijf het mailadres dat je hoort: *em punt bakker apenstaartje gemeente punt en el*',
          say: 'em punt bakker apenstaartje gemeente punt en el',
          a: 'm.bakker@gemeente.nl',
          why: 'em = m, punt = ., apenstaartje = @, en el = nl.',
        },
        {
          q: 'Welke basisvorm zoek je op als je *steden* wilt controleren?',
          a: 'stad',
          why: 'Een zelfstandig naamwoord zoek je op in het enkelvoud: één stad, twee steden.',
        },
        { q: 'Onder welke letter staat *Ilse van Doorn* in een Nederlandse lijst?', a: 'd', why: 'van telt niet mee: Doorn, Ilse van. Dus onder de D.' },
        { q: 'Iemand spelt een woord: *jee, uu, er, ie, es, tee*. Typ het woord.', a: 'jurist', why: 'jee = j. Let op: gee is de g. uu = u, ie = i: jurist.' },
        { q: 'Welk woord uit het spelalfabet zeg je bij de *f*?', a: 'Ferdinand', why: 'F van Ferdinand, met een d aan het eind.' },
        {
          q: 'Hoe heet het teken *_* als je een mailadres spelt?',
          a: 'laag streepje',
          also: ['underscore'],
          why: 'Het streepje onderaan de regel heet laag streepje. Het gewone - heet streepje.',
        },
        {
          q: 'Zet *iglo*, *ik*, *iets*, *ijzer* en *in* op alfabet. Typ het woord dat in het midden staat.',
          a: 'ijzer',
          why: 'iets (e), iglo (g), ijzer (j), ik (k), in (n). De ij telt als i + j.',
        },
        {
          q: 'Iemand spelt een woord: *vee, ee, er, ha, uu, ie, es, wee, aa, gee, ee, en*. Typ het woord.',
          say: 'vee, ee, er, ha, uu, ie, es, wee, aa, gee, ee, en',
          a: 'verhuiswagen',
          why: 'vee = v en wee = w: die lijken op elkaar. uu + ie is de ui: verhuiswagen.',
        },
        { q: 'Welke basisvorm zoek je op als je *leeuwen* wilt controleren?', a: 'leeuw', why: 'Enkelvoud: één leeuw, twee leeuwen.' },
        { q: 'Welk woord uit het spelalfabet zeg je bij de *ij*?', a: 'IJmuiden', why: 'IJ van IJmuiden. Zo weet de ander dat het geen ei is.' },
        { q: 'Hoe heet de *z* als je een woord hardop spelt?', a: 'zet', why: 'De z heet zet.' },
        {
          q: 'Welke basisvorm zoek je op als je *bleef* wilt controleren?',
          a: 'blijven',
          why: 'bleef is een vorm van blijven. Een werkwoord zoek je op als hele werkwoord.',
        },
        {
          q: 'Onder welke letter staat *Bram Verhoeven* in een Nederlandse lijst?',
          a: 'v',
          why: 'Verhoeven is één woord, zonder klein woordje ervoor: gewoon onder de V.',
        },
        { q: 'Iemand spelt een woord: *ku, uu, ie, zet*. Typ het woord.', a: 'quiz', why: 'ku = q, uu = u, ie = i, zet = z: quiz.' },
        {
          q: 'Schrijf het mailadres dat je hoort: *sara laag streepje bos apenstaartje school punt en el*',
          say: 'sara laag streepje bos apenstaartje school punt en el',
          a: 'sara_bos@school.nl',
          why: 'laag streepje = _, apenstaartje = @, en el = nl.',
        },
        {
          q: 'Welke basisvorm zoek je op als je *oudste* wilt controleren?',
          a: 'oud',
          why: 'Een bijvoeglijk naamwoord zoek je op zonder -e, -er of -st: oud.',
        },
        { q: 'Hoe heet de *g* als je een woord hardop spelt?', a: 'gee', why: 'De g heet gee. De j heet jee: die twee lijken op elkaar.' },
      ],
      done: { title: 'Reeks klaar', text: 'Letternamen, spelalfabet, ordenen en opzoeken: alles door elkaar. Wat fout ging, heb je nog een keer gedaan.' },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de werkinstructie aan. Typ elk woord helemaal.',
      intro: 'Je begint als receptionist bij een huisarts. Kijk goed naar de zin om het gat heen.',
      title: 'Werkinstructie: namen noteren aan de telefoon',
      text:
        'Welkom bij huisartsenpraktijk De Linde! Aan de telefoon noteer je elke dag namen en mailadressen. Met deze tips gaat dat goed.\n\n' +
        'Vraag altijd of de beller zijn achternaam wil spellen. Let op letters die op elkaar lijken. De v heet vee en de w heet {wee|naam van de w|De w heet wee. Aan de telefoon lijkt dat op vee.}. ' +
        'Twijfel je? Vraag dan: ‘V van {Victor|spelalfabet|V van Victor.} of W van {Willem|spelalfabet|W van Willem.}?’ ' +
        'Zegt iemand ‘lange ij’, dan schrijf je {ij||De lange ij is de ij van wijn.}. Zegt iemand ‘Griekse ij’, dan schrijf je een {y||De Griekse ij is de y, zoals in baby.}. ' +
        'En de q heet {ku|naam van de q|De q heet ku, met de u van nu.}, niet koe.\n\n' +
        'Geeft iemand een postcode met de letters PT door, herhaal dan: ‘P van {Pieter|spelalfabet|P van Pieter.}, T van {Teunis|spelalfabet|T van Teunis.}.’ ' +
        'In een mailadres noteer je elk teken. Het teken @ heet {apenstaartje|naam van @|Het teken @ heet apenstaartje.}, en het teken _ heet laag {streepje||Het teken _ heet laag streepje; het gewone - heet streepje.}.\n\n' +
        'In ons systeem zijn alle namen gesorteerd op achternaam. Kees van den Broek vind je onder de {b|letter|van den telt niet mee: Broek, Kees van den.}, ' +
        'Bram Verhoeven onder de {v|letter|Verhoeven is één woord, zonder klein woordje ervoor.} en de familie IJzerman onder de {i|letter|Bij het ordenen telt de ij als i + j. IJzerman staat dus bij de i.}.\n\n' +
        'Twijfel je over een woord in een brief? Zoek dan de basisvorm op. Bij ‘schreef’ zoek je {schrijven|hele werkwoord|Een werkwoord zoek je op als hele werkwoord: schrijven.}, ' +
        'bij ‘klachten’ zoek je {klacht|enkelvoud|Een zelfstandig naamwoord zoek je op in het enkelvoud: één klacht.} ' +
        'en bij ‘zwaardere’ zoek je {zwaar|zonder -e en -er|Een bijvoeglijk naamwoord zoek je op zonder -e en zonder -er: zwaar.}.',
      why: 'Letternamen: wee en ku. Het spelalfabet: Victor, Willem, Pieter, Teunis. Lange ij = ij, Griekse ij = y. Bij het ordenen telt het hoofdwoord van de achternaam, en de ij is gewoon i + j. Opzoeken doe je met de basisvorm: hele werkwoord, enkelvoud, zonder -e en -er.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen. Hoofdletters en leestekens tellen mee. Griekse schrijf je met een hoofdletter, net als Griekenland.',
      title: 'Een telefoontje met de gemeente',
      sentences: [
        'Vanochtend belde ik de gemeente over mijn nieuwe adres.',
        'Ik vertelde dat mijn achternaam met een Griekse ij begint.',
        'Daarom spelde ik hem heel langzaam met het spelalfabet.',
        'Aan de telefoon klinken veel letters bijna hetzelfde.',
        'Daarna gaf ik mijn mailadres en mijn telefoonnummer door.',
        'Na het gesprek zocht ik nog een paar woorden op in de woordenlijst.',
      ],
      right:
        'Alles goed. spelalfabet, hetzelfde, mailadres, telefoonnummer en woordenlijst zijn allemaal één woord. En Griekse ij schrijf je met een hoofdletter G.',
      wrong:
        'Kijk de woorden met een fout nog eens na. spelalfabet, hetzelfde, mailadres, telefoonnummer en woordenlijst zijn één woord. Griekse schrijf je met een hoofdletter. spelde schrijf je met één l, net als ik spel.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'ledenadministratie', subject: 'Mijn gegevens' },
      greeting: 'Beste mevrouw Smit,',
      signoff: 'Met vriendelijke groet,\nJoris Yilmaz',
      tokens: [
        { t: 'Hierbij' },
        { t: 'mijn' },
        { t: 'gegevens' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'ledenlijst.' },
        { t: 'Mijn' },
        { t: 'achternaam' },
        { t: 'is' },
        { t: 'Yilmaz.' },
        { t: 'Aan' },
        { t: 'de' },
        { t: 'telefoon' },
        { t: 'spel' },
        { t: 'ik' },
        { t: 'die' },
        { t: 'zo:' },
        { t: '‘Y' },
        { t: 'van' },
        { t: 'Ypsilon,', trap: 'Goed: in het spelalfabet hoort Ypsilon bij de y.' },
        { t: 'I' },
        { t: 'van' },
        { t: 'Izaak,', trap: 'Goed: I van Izaak, met een z en dubbele a.' },
        { t: 'L' },
        { t: 'van' },
        { t: 'Lodewyk,', fix: 'Lodewijk,', why: 'L van Lodewijk, met een lange ij.' },
        { t: 'M' },
        { t: 'van' },
        { t: 'Marie,' },
        { t: 'A' },
        { t: 'van' },
        { t: 'Anton,' },
        { t: 'Z' },
        { t: 'van' },
        { t: 'Zaandam.’' },
        { t: 'In' },
        { t: 'jullie' },
        { t: 'lijst' },
        { t: 'sta' },
        { t: 'ik' },
        { t: 'dus' },
        { t: 'onder' },
        { t: 'de' },
        { t: 'J.', fix: 'Y.', why: 'Yilmaz begint met een y. De y klinkt hier als j, maar je ordent op de letter die er staat: de Y.' },
        { t: 'Mijn' },
        { t: 'voornaam' },
        { t: 'Joris' },
        { t: 'spel' },
        { t: 'je' },
        { t: 'zo:' },
        { t: 'gee,', fix: 'jee,', why: 'De j heet jee. gee is de g: dan schrijft de ander Goris.' },
        { t: 'oo,', trap: 'Goed: de o heet oo.' },
        { t: 'er,' },
        { t: 'ie,' },
        { t: 'es.' },
        { t: 'Mijn' },
        { t: 'vrouw' },
        { t: 'heet' },
        { t: 'Eva' },
        { t: 'van' },
        { t: 'Dijk.' },
        { t: 'Haar' },
        { t: 'voornaam' },
        { t: 'spel' },
        { t: 'je' },
        { t: 'zo:' },
        { t: 'ie,', fix: 'ee,', why: 'Eva begint met een e, en de e heet ee. ie is de naam van de i.' },
        { t: 'vee,' },
        { t: 'aa.' },
        { t: 'In' },
        { t: 'een' },
        { t: 'Nederlandse' },
        { t: 'lijst' },
        { t: 'staat' },
        { t: 'zij' },
        { t: 'onder' },
        { t: 'de' },
        { t: 'V.', fix: 'D.', why: 'van telt in een Nederlandse lijst niet mee: Dijk, Eva van. Zij staat onder de D.' },
        { t: 'Onze' },
        { t: 'postcode' },
        { t: 'is' },
        { t: '3512' },
        { t: 'BD,' },
        { t: 'dus' },
        { t: 'B' },
        { t: 'van' },
        { t: 'Bernard', trap: 'Goed: B van Bernard, zonder h.' },
        { t: 'en' },
        { t: 'D' },
        { t: 'van' },
        { t: 'Teunis.', fix: 'Dirk.', why: 'D van Dirk. Teunis hoort bij de t.' },
        { t: 'Ons' },
        { t: 'mailadres' },
        { t: 'spel' },
        { t: 'je' },
        { t: 'zo:' },
        { t: 'yilmaz' },
        { t: 'punt' },
        { t: 'thuis' },
        { t: 'apenstaartje' },
        { t: 'mail' },
        { t: 'punt' },
        { t: 'em', fix: 'en', why: 'nl spel je en, el. em is de naam van de m.' },
        { t: 'el.' },
      ],
      done: {
        title: 'Nagekeken',
        text: 'Zeven fouten: Lodewijk, de Y, jee, ee, de D, Dirk, en de en van nl. Goed waren: Ypsilon, Izaak, oo en Bernard.',
      },
    },
  ],
};
