import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": de hoofdletter aan het begin van de zin en bij namen, tussenvoegsels, IJ, u en titels. */
export const LES_L21: LessonInput = {
  id: 'l21',
  stage: 'regels',
  domain: 'orth',
  title: 'Hoofdletters: de zin en namen',
  skill: 'Spelling',
  icon: 'Aa',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Waar komt een hoofdletter?',
      panels: [
        {
          text: 'Een zin begint altijd met een hoofdletter. Na een punt, een vraagteken of een uitroepteken begint een nieuwe zin, dus komt er weer een hoofdletter. Dat geldt ook in een appje of een korte mail.',
          rule: 'Begin van de zin, ook na *?* en *!*: hoofdletter.',
          show: [
            { wrong: 'Kom je ook? ik ben er om acht uur.', right: 'Kom je ook? Ik ben er om acht uur.' },
            { wrong: 'Gefeliciteerd! het is je gelukt.', right: 'Gefeliciteerd! Het is je gelukt.' },
          ],
          mark: {
            q: 'Tik de woorden die een hoofdletter krijgen',
            sentence: 'ben je thuis? ik sta voor de deur. doe snel open!',
            targets: [0, 3, 8],
            note: 'Ben, Ik en Doe: drie zinnen, dus drie hoofdletters.',
          },
          deep: {
            q: 'En als er na de vraag nog iets volgt?',
            a: 'Staat de vraag tussen aanhalingstekens en loopt de zin daarna door, dan schrijf je klein verder: *‘Kom je ook?’ vroeg ze.* Het woord *vroeg* hoort nog bij dezelfde zin.',
          },
        },
        {
          text: 'Na een dubbele punt schrijf je een kleine letter: *Eén ding is zeker: het wordt laat.* Alleen een citaat (wat iemand letterlijk zegt) of een naam begint na de dubbele punt met een hoofdletter: *Hij zei: ‘Kom binnen.’* Begint een zin met *’s* of *’t*, dan krijgt niet het weggelaten stukje de hoofdletter, maar het woord erna: *’s Morgens*, *’t Is koud*.',
          rule: 'Na een dubbele punt: klein, behalve bij een citaat of een naam. Zin met *’s* of *’t* vooraan: hoofdletter op het tweede woord.',
          lab: {
            label: 'Tik een geval',
            chips: [
              { k: 'dubbele punt', out: 'Ik heb drie dingen nodig: brood, kaas en melk.', note: 'Geen citaat en geen naam: kleine letter.' },
              { k: 'citaat', out: 'Hij zei: ‘Kom binnen.’', note: 'Letterlijk wat hij zegt: hoofdletter.' },
              { k: 'naam', out: 'Er mist nog één persoon: Eva.', note: 'Een naam houdt altijd zijn hoofdletter.' },
              { k: '’s vooraan', out: '’s Avonds lees ik een boek.', note: 'De hoofdletter gaat naar Avonds.' },
              { k: '’t vooraan', out: '’t Is koud buiten.', note: 'De hoofdletter gaat naar Is.' },
            ],
          },
          quiz: {
            q: 'Hoe begin je deze zin goed?',
            options: ['’s Morgens drink ik thee.', '’S morgens drink ik thee.', '’s morgens drink ik thee.'],
            answer: '’s Morgens drink ik thee.',
            why: 'De ’s blijft klein. Het woord erna krijgt de hoofdletter: Morgens.',
          },
        },
        {
          text: 'Namen krijgen een hoofdletter. Een naam wijst één bepaalde persoon, één dier of één plek aan: *Sara*, *onze hond Max*, *de Kerkstraat*, *Utrecht*, *Marokko*, *de Maas*, *het Rijksmuseum*. Het gewone woord blijft klein: *de hond*, *de straat*, *de stad*, *het land*, *de rivier*, *het museum*.',
          rule: 'De naam van een persoon, dier, straat, plaats, land, rivier of gebouw: hoofdletter. Het gewone woord: klein.',
          mark: {
            q: 'Tik de woorden die een hoofdletter krijgen',
            sentence: 'onze hond max loopt elke dag met mij door de kerkstraat naar de maas in maastricht.',
            targets: [0, 2, 10, 13, 15],
            note: 'Onze (begin van de zin), Max, Kerkstraat, Maas en Maastricht. hond blijft klein: dat is geen naam.',
          },
        },
        {
          text: 'De *ij* is in het Nederlands één letter. Krijgt een woord met *ij* vooraan een hoofdletter, dan worden de *i* en de *j* allebei groot: *IJsland*, *de IJssel*, *IJmuiden*, *het IJsselmeer*. Ook aan het begin van een zin: *IJs is koud.* Schrijf dus nooit *Ijsland*.',
          rule: 'Hoofdletter op een *ij*: allebei groot, *IJ*.',
          quiz: {
            q: 'Welke schrijfwijze is goed?',
            options: ['IJsland', 'Ijsland', 'IJSland', 'ijsland'],
            answer: 'IJsland',
            why: 'De ij is één letter: hoofdletter I en hoofdletter J, de rest klein.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'naam-of-niet',
      prompt: 'Hoofdletter of kleine letter?',
      buckets: ['hoofdletter', 'kleine letter'],
      items: [
        { t: 'we wonen in de (k/K)erkstraat', b: 0 },
        { t: 'een drukke (s/S)traat', b: 1 },
        { t: 'onze hond (b/B)uddy', b: 0 },
        { t: 'onze (h/H)ond', b: 1 },
        { t: 'het (r/R)ijksmuseum', b: 0 },
        { t: 'een mooi (m/M)useum', b: 1 },
        { t: 'langs de (r/R)ijn', b: 0 },
        { t: 'naar (d/D)uitsland', b: 0 },
        { t: 'een grote (s/S)tad', b: 1 },
        { t: 'Kunt (u/U) mij helpen?', b: 1 },
        { t: 'Ze bidt tot (g/G)od.', b: 0 },
      ],
      why: 'Kerkstraat, Buddy, Rijksmuseum, Rijn en Duitsland zijn namen. straat, hond, museum en stad zijn gewone woorden. u schrijf je klein. God, de naam van de ene God, krijgt een hoofdletter.',
    },
    {
      kind: 'choice',
      id: 'na-vraagteken',
      prompt: 'Kies de goede vorm.',
      before: 'Heb je mijn mail gelezen?',
      after: 'het me even weten.',
      options: ['Laat', 'laat'],
      answer: 'Laat',
      why: 'Na het vraagteken begint een nieuwe zin: hoofdletter.',
    },
    {
      kind: 'rewrite',
      id: 'zinsbegin',
      prompt: 'Zet de hoofdletters goed.',
      source: '’s morgens fiets ik naar mijn werk. ’t is twintig minuten. lekker!',
      accept: ['’s Morgens fiets ik naar mijn werk. ’t Is twintig minuten. Lekker!'],
      why: 'Drie zinnen, drie hoofdletters. Bij ’s en ’t vooraan krijgt het woord erna de hoofdletter: Morgens en Is.',
    },
    {
      kind: 'choice',
      id: 'dubbele-punt',
      prompt: 'Welke zin is goed geschreven?',
      before: '',
      after: '',
      options: ['Ik heb drie dingen nodig: brood, kaas en melk.', 'Ik heb drie dingen nodig: Brood, kaas en melk.', 'Ik heb drie dingen nodig: Brood, Kaas en Melk.'],
      answer: 'Ik heb drie dingen nodig: brood, kaas en melk.',
      why: 'Na een dubbele punt schrijf je klein. Een opsomming is geen citaat en geen naam.',
    },
    {
      kind: 'dictation',
      id: 'dictee-ijmuiden',
      prompt: 'Luister en typ precies wat je hoort.',
      intro: 'Let op de hoofdletters.',
      sentence: 'Mijn broer woont in IJmuiden en werkt in Amsterdam.',
      right: 'Goed: IJmuiden met hoofdletter I en hoofdletter J, en Amsterdam met een hoofdletter.',
      wrong: 'Kijk nog eens: Mijn broer woont in IJmuiden en werkt in Amsterdam. De ij is één letter, dus IJ allebei groot.',
    },
    {
      kind: 'swipe',
      id: 'hoofdletters-waar',
      prompt: 'Goed of fout geschreven?',
      intro: 'Veeg naar rechts als de zin goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'Ik woon in Ijmuiden.', ok: false, fix: 'IJmuiden', why: 'De ij is één letter: allebei groot.' },
        { t: 'Mijn kat heet Minoes.', ok: true, why: 'Een dier met een naam: hoofdletter. kat blijft klein.' },
        { t: 'We wonen in de Kerkstraat.', ok: true, why: 'De naam van de straat: hoofdletter.' },
        { t: 'Kunt U mij helpen?', ok: false, fix: 'Kunt u mij helpen?', why: 'u schrijf je klein, ook als je beleefd bent.' },
        { t: 'Ik heb een afspraak met Dokter Jansen.', ok: false, fix: 'dokter Jansen', why: 'Een functie of titel is geen naam: klein. Jansen is de naam.' },
        { t: '’s Avonds kijk ik naar het nieuws.', ok: true, why: 'De hoofdletter staat op het woord na ’s.' },
        { t: 'Eén ding is zeker: Het wordt laat.', ok: false, fix: 'het wordt laat', why: 'Na een dubbele punt schrijf je klein, behalve bij een citaat of een naam.' },
        { t: 'We varen over de Maas.', ok: true, why: 'De naam van een rivier: hoofdletter.' },
      ],
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Tussenvoegsels, u en titels',
      panels: [
        {
          text: 'Woordjes als *de*, *van*, *van der* en *ten* in een Nederlandse achternaam heten tussenvoegsels. Staat er een voornaam of een voorletter voor, dan schrijf je ze klein: *Jan de Vries*, *J. de Vries*. Staat er geen voornaam of voorletter voor, dan krijgt het eerste woordje een hoofdletter: *meneer De Vries*, *mevrouw Van Dijk*, *de familie De Vries*, *Van Dijk heeft gebeld*. Bij twee woordjes wordt alleen het eerste groot: *mevrouw Van der Berg*.',
          rule: 'Voornaam of voorletter ervoor: klein (*Jan de Vries*). Niets ervoor: groot (*meneer De Vries*).',
          lab: {
            label: 'Tik een naam',
            chips: [
              { k: 'met voornaam', out: 'Ik heb Eva van Dijk gesproken.', note: 'Voornaam ervoor: van klein.' },
              { k: 'met voorletter', out: 'Afzender: E. van Dijk', note: 'Voorletter ervoor: ook klein.' },
              { k: 'met mevrouw', out: 'Ik heb mevrouw Van Dijk gesproken.', note: 'mevrouw is geen voornaam: Van groot.' },
              { k: 'alleen achternaam', out: 'Van Dijk komt morgen.', note: 'Niets ervoor: Van groot.' },
              { k: 'twee woordjes', out: 'Geachte heer Van der Berg,', note: 'Alleen het eerste woordje groot: Van der.' },
            ],
          },
          quiz: {
            q: 'Welke zin is goed geschreven (in Nederland)?',
            options: ['Morgen komt de familie De Boer eten.', 'Morgen komt de familie de Boer eten.', 'Morgen komt de Familie de Boer eten.'],
            answer: 'Morgen komt de familie De Boer eten.',
            why: 'Er staat geen voornaam of voorletter voor de: dus De met hoofdletter. familie is een gewoon woord.',
          },
          deep: {
            q: 'En in België?',
            a: 'Daar schrijf je de achternaam altijd zoals hij in het paspoort staat. Staat er *De Smet*, dan schrijf je ook *Jan De Smet*. Staat er *de Smet*, dan schrijf je *de Smet*.',
          },
        },
        {
          text: 'Titels en functies zijn geen namen. Ze blijven klein, ook als ze voor een naam staan: *koning Willem-Alexander*, *de koning*, *dokter Jansen*, *minister Bakker*, *burgemeester Visser*, *meneer Ali*, *tante Fatima*. De beleefde vorm *u* en *uw* schrijf je klein, ook in een officiële brief. *God* krijgt wel een hoofdletter als je de ene God bedoelt; *de goden* is een gewoon woord.',
          rule: 'Titel of functie: klein (*dokter Jansen*). *u* en *uw*: klein. *God*: groot.',
          mark: {
            q: 'Tik de woorden die een hoofdletter krijgen',
            sentence: 'gisteren sprak dokter jansen met koning willem-alexander en de burgemeester van utrecht.',
            targets: [0, 3, 6, 11],
            note: 'Gisteren (begin van de zin), Jansen, Willem-Alexander (beide delen groot) en Utrecht. dokter, koning en burgemeester zijn functies: klein.',
          },
          quiz: {
            q: 'Welke zin is goed geschreven?',
            options: ['Wij sturen u de factuur per post.', 'Wij sturen U de factuur per post.', 'Wij sturen u de Factuur per post.'],
            answer: 'Wij sturen u de factuur per post.',
            why: 'u schrijf je klein, ook in een brief van een bedrijf. factuur is een gewoon woord.',
          },
        },
        {
          text: 'Twijfel je? Loop dit stappenplan langs. 1. Begint hier een nieuwe zin, ook na *?* of *!*? Hoofdletter. 2. Staat er *’s* of *’t* vooraan? Dan het woord erna. 3. Staat er een dubbele punt voor? Klein, behalve bij een citaat of een naam. 4. Is het de naam van één bepaalde persoon, dier, straat, plaats, land, rivier of gebouw? Hoofdletter. 5. Is het een titel of functie (*koning*, *dokter*, *meneer*)? Klein. 6. Een tussenvoegsel? Voornaam of voorletter ervoor: klein; anders groot.',
          rule: 'Zinsbegin, naam: groot. Titel, functie, *u*, na een dubbele punt: klein.',
          lab: {
            label: 'Tik een twijfelgeval',
            chips: [
              { k: 'mevrouw van dijk', out: 'mevrouw Van Dijk', note: 'Stap 5 en 6: mevrouw is een titel (klein), en er staat geen voornaam voor van (groot).' },
              { k: 'ijsselmeer', out: 'het IJsselmeer', note: 'Stap 4: een naam. En de ij wordt allebei groot.' },
              { k: 'minister', out: 'de minister, minister Bakker', note: 'Stap 5: een functie, dus klein.' },
              { k: 'hij zei: ‘ja.’', out: 'Hij zei: ‘Ja.’', note: 'Stap 3: na de dubbele punt komt een citaat, dus hoofdletter.' },
              { k: '’t is laat', out: '’t Is laat.', note: 'Stap 2: de hoofdletter gaat naar het woord na ’t.' },
            ],
          },
          quiz: {
            q: 'Welke zin is helemaal goed?',
            options: [
              'Gisteren belde meneer De Wit: hij komt morgen.',
              'Gisteren belde Meneer de Wit: hij komt morgen.',
              'Gisteren belde meneer de Wit: Hij komt morgen.',
            ],
            answer: 'Gisteren belde meneer De Wit: hij komt morgen.',
            why: 'meneer is een titel: klein. Geen voornaam voor de: De groot. Na de dubbele punt geen citaat: klein.',
          },
        },
      ],
    },
    {
      kind: 'choice',
      id: 'aanhef-van',
      prompt: 'Kies de goede vorm.',
      before: 'Beste mevrouw',
      after: 'Dijk,',
      options: ['Van', 'van'],
      answer: 'Van',
      why: 'mevrouw is geen voornaam en geen voorletter. Dus krijgt het tussenvoegsel een hoofdletter: mevrouw Van Dijk.',
    },
    {
      kind: 'sort',
      id: 'tussenvoegsel',
      prompt: 'Klein of groot tussenvoegsel? (Nederland)',
      buckets: ['klein: de, van', 'groot: De, Van'],
      items: [
        { t: 'Jan (d/D)e Vries', b: 0 },
        { t: 'meneer (d/D)e Vries', b: 1 },
        { t: 'J. (d/D)e Vries', b: 0 },
        { t: 'de familie (v/V)an Dam', b: 1 },
        { t: '(v/V)an Dijk heeft gebeld.', b: 1 },
        { t: 'Eva (v/V)an Dijk', b: 0 },
        { t: 'Geachte heer (v/V)an der Berg,', b: 1 },
        { t: 'dokter (d/D)e Boer', b: 1 },
        { t: 'Sanne (t/T)en Brink', b: 0 },
        { t: 'S. (t/T)en Brink', b: 0 },
      ],
      why: 'Een voornaam (Jan, Eva, Sanne) of een voorletter (J., S.) ervoor: klein. Een titel (meneer, heer, dokter), familie of niets ervoor: groot.',
    },
    {
      kind: 'proofread',
      id: 'mail-school',
      prompt: 'Lees de mail na',
      intro: 'Er zitten zes hoofdletterfouten in. Tik ze aan.',
      header: { to: 'meneer De Jong', subject: 'Sara is ziek' },
      tokens: [
        { t: 'Beste' },
        { t: 'meneer' },
        { t: 'de', fix: 'De', why: 'Geen voornaam of voorletter ervoor: het tussenvoegsel krijgt een hoofdletter.' },
        { t: 'Jong,' },
        { t: 'Mijn' },
        { t: 'dochter' },
        { t: 'Sara' },
        { t: 'is' },
        { t: 'vandaag' },
        { t: 'ziek.' },
        { t: 'ze', fix: 'Ze', why: 'Na een punt begint een nieuwe zin: hoofdletter.' },
        { t: 'heeft' },
        { t: 'koorts' },
        { t: 'en' },
        { t: 'moet' },
        { t: 'morgen' },
        { t: 'naar' },
        { t: 'Dokter', fix: 'dokter', why: 'Een functie is geen naam: klein.' },
        { t: 'Smit.' },
        { t: 'Kunt' },
        { t: 'U', fix: 'u', why: 'u schrijf je klein, ook in een beleefde mail.' },
        { t: 'haar' },
        { t: 'huiswerk' },
        { t: 'mailen?' },
        { t: 'Let' },
        { t: 'op:' },
        { t: 'we' },
        { t: 'wonen' },
        { t: 'nu' },
        { t: 'in' },
        { t: 'de' },
        { t: 'dorpsstraat', fix: 'Dorpsstraat', why: 'De naam van een straat: hoofdletter.' },
        { t: 'in' },
        { t: 'Ijsselstein.', fix: 'IJsselstein.', why: 'Hoofdletter op een ij: allebei groot.' },
        { t: 'Met' },
        { t: 'vriendelijke' },
        { t: 'groet,' },
        { t: 'Hasan' },
        { t: 'Yilmaz' },
      ],
      done: {
        title: 'Netjes',
        text: 'meneer De Jong, Ze, dokter Smit, u, Dorpsstraat en IJsselstein. Na Let op: staat geen citaat, dus we blijft klein.',
      },
    },
    {
      kind: 'bet',
      id: 'citaat',
      prompt: 'Welke zin is goed geschreven?',
      intro: 'Een lastig geval: een dubbele punt met een citaat. Hoe zeker ben je?',
      options: ['Ze vroeg: ‘Kom je ook?’', 'Ze vroeg: ‘kom je ook?’', 'Ze Vroeg: ‘kom je ook?’'],
      answer: 'Ze vroeg: ‘Kom je ook?’',
      why: 'Na de dubbele punt komt letterlijk wat ze zegt, tussen aanhalingstekens. Een citaat begint met een hoofdletter.',
    },
    {
      kind: 'rewrite',
      id: 'namen-zin',
      prompt: 'Zet de hoofdletters goed.',
      source: 'op zaterdag gaan oom ali en tante fatima met hun kat minoes naar de ijssel bij deventer.',
      accept: ['Op zaterdag gaan oom Ali en tante Fatima met hun kat Minoes naar de IJssel bij Deventer.'],
      why: 'Zinsbegin, de namen Ali, Fatima en Minoes, de rivier IJssel (allebei groot) en de stad Deventer. oom, tante, kat en zaterdag blijven klein.',
    },
    {
      kind: 'dictation',
      id: 'dictee-van-dijk',
      prompt: 'Luister en typ precies wat je hoort.',
      intro: 'Let op het tussenvoegsel en de functie.',
      sentence: 'Gisteren sprak meneer Van Dijk met burgemeester Jansen.',
      right: 'Goed: meneer Van Dijk (geen voornaam, dus Van groot) en burgemeester Jansen (functie klein, naam groot).',
      wrong: 'Kijk nog eens: Gisteren sprak meneer Van Dijk met burgemeester Jansen. Geen voornaam voor van, dus Van. burgemeester is een functie: klein.',
    },
    {
      kind: 'choice',
      id: 'god',
      prompt: 'Kies de goede vorm.',
      before: 'Ze bidt elke avond tot',
      after: '.',
      options: ['God', 'god'],
      answer: 'God',
      why: 'God is hier de naam van de ene God: hoofdletter. Spreek je over goden in het algemeen, dan schrijf je klein: de goden.',
    },
    {
      kind: 'write',
      id: 'appje-buren',
      prompt: 'Schrijf een appje aan je nieuwe buren.',
      intro: 'Stel jezelf voor. Noem je naam, je straat en de stad of het land waar je vandaan komt. Stel ook een vraag en schrijf daarna nog een zin.',
      minWords: 25,
      must: [
        { label: 'Je begint met een hoofdletter', test: { pattern: '^\\s*[A-Z]' } },
        { label: 'Een straatnaam met een hoofdletter', hint: 'Kerkstraat, Dorpsweg, Stationsplein', test: { pattern: '\\b[A-Z][a-z]*(straat|laan|weg|plein|gracht|kade|dreef|singel)\\b' } },
        { label: 'Een vraag, en daarna een nieuwe zin met een hoofdletter', hint: 'Hebben jullie zin? Dan …', test: { pattern: '\\?\\s+[A-Z]' } },
      ],
      starters: ['Hallo buren!', 'Ik ben … en ik woon sinds kort in de …', 'Ik kom uit …', 'Hebben jullie zin in koffie?'],
      why: 'Een appje is kort, maar de hoofdletters horen er gewoon bij: aan het begin van elke zin, bij namen van personen, straten, plaatsen en landen.',
      done: {
        title: 'Verstuurd',
        text: 'Lees je appje nog één keer na met het stappenplan: zinsbegin, namen, en na een vraagteken weer een hoofdletter.',
      },
    },
  ],
};
