import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": hoofdletters bij talen, inwoners, dagen, feesten, windstreken, instellingen, merken en in een mail. */
export const LES_L22: LessonInput = {
  id: 'l22',
  stage: 'regels',
  domain: 'orth',
  title: 'Hoofdletters: talen, dagen en feesten',
  skill: 'Spelling',
  icon: 'Pa',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Groot of klein?',
      panels: [
        {
          text: 'Talen en inwoners krijgen een hoofdletter: *het Nederlands*, *Arabisch*, *Turks*, *Engels*, *een Nederlander*, *een Marokkaan*, *een Fransman*, *een Amsterdammer*. Ook het bijvoeglijk naamwoord dat van een land of plaats komt, krijgt een hoofdletter: *Franse kaas*, *Turkse thee*, *Marokkaanse soep*, *Amsterdamse grachten*. Dat geldt ook voor een vak op school: *ik heb les in Nederlands*.',
          rule: 'Taal, inwoner of bijvoeglijk naamwoord van een land of plaats: hoofdletter.',
          lab: {
            label: 'Tik een land of plaats',
            chips: [
              { k: 'Nederland', out: 'het Nederlands, een Nederlander, de Nederlandse taal', note: 'Taal, inwoner en bijvoeglijk naamwoord: alle drie groot.' },
              { k: 'Turkije', out: 'het Turks, een Turk, Turkse thee', note: 'Ook hier: alle drie groot.' },
              { k: 'Frankrijk', out: 'het Frans, een Fransman, Franse kaas', note: 'Groot, ook midden in de zin.' },
              { k: 'Marokko', out: 'een Marokkaan, Marokkaanse soep', note: 'Inwoner en bijvoeglijk naamwoord: groot.' },
              { k: 'Amsterdam', out: 'een Amsterdammer, Amsterdamse grachten', note: 'Bij een stad werkt het net zo.' },
            ],
          },
          quiz: {
            q: 'Welke zin is goed geschreven?',
            options: [
              'Ik spreek Arabisch en een beetje Nederlands.',
              'Ik spreek arabisch en een beetje nederlands.',
              'Ik spreek Arabisch en een beetje nederlands.',
            ],
            answer: 'Ik spreek Arabisch en een beetje Nederlands.',
            why: 'Namen van talen krijgen altijd een hoofdletter.',
          },
        },
        {
          text: 'Dagen, maanden en seizoenen schrijf je klein: *maandag*, *zaterdag*, *januari*, *augustus*, *de lente*, *de zomer*, *de herfst*, *de winter*. Ook in een datum: *dinsdag 2 april*. Alleen aan het begin van een zin krijgen ze een hoofdletter: *Maandag begint de cursus.*',
          rule: 'Dag, maand, seizoen: klein. Alleen aan het begin van de zin groot.',
          show: [
            { wrong: 'Maandag 5 Januari', right: 'maandag 5 januari' },
            { wrong: 'in de Zomer', right: 'in de zomer' },
          ],
          mark: {
            q: 'Tik de woorden die een hoofdletter krijgen',
            sentence: 'op dinsdag 2 april vliegen we in de lente naar turkije en in augustus naar marokko.',
            targets: [0, 10, 15],
            note: 'Op (begin van de zin), Turkije en Marokko. dinsdag, april, lente en augustus blijven klein.',
          },
        },
        {
          text: 'Feestdagen zijn namen. Ze krijgen een hoofdletter: *Kerstmis*, *Pasen*, *Pinksteren*, *Koningsdag*, *Bevrijdingsdag*, *het Suikerfeest*, *het Offerfeest*, *Sinterklaas*. Maar een samenstelling met een feestdag is een gewoon woord en blijft klein: *de kerstboom*, *de kerstvakantie*, *een paasei*, *het pinksterweekend*.',
          rule: 'Feestdag: hoofdletter (*Pasen*). Samenstelling met een feestdag: klein (*paasei*).',
          mark: {
            q: 'Tik de woorden die een hoofdletter krijgen',
            sentence: 'op koningsdag en met pinksteren zijn we vrij, en in de kerstvakantie vieren we kerstmis.',
            targets: [0, 1, 4, 14],
            note: 'Op (begin van de zin), Koningsdag, Pinksteren en Kerstmis. kerstvakantie is een samenstelling: klein.',
          },
          deep: {
            q: 'En Sinterklaas?',
            a: 'Het feest en de persoon schrijf je allebei met een hoofdletter: *Wat krijg je met Sinterklaas?* Een samenstelling is weer klein: *een sinterklaascadeau*.',
          },
        },
        {
          text: 'Windstreken schrijf je klein: *het noorden*, *het zuiden*, *naar het oosten*, *in het westen van het land*. Maar in de naam van een gebied horen ze bij de naam. Dan krijgen ze een hoofdletter en een koppelteken: *Noord-Holland*, *Zuid-Afrika*, *Noord-Amerika*, *Oost-Europa*. En in één woord: *de Noordzee*.',
          rule: 'Windstreek: klein (*het noorden*). In een naam: groot (*Noord-Holland*).',
          quiz: {
            q: 'Welke zin is goed geschreven?',
            options: [
              'Mijn zus woont in het noorden van Noord-Holland.',
              'Mijn zus woont in het Noorden van Noord-Holland.',
              'Mijn zus woont in het noorden van noord-Holland.',
            ],
            answer: 'Mijn zus woont in het noorden van Noord-Holland.',
            why: 'het noorden is een richting: klein. Noord-Holland is een naam: groot.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'groot-klein',
      prompt: 'Hoofdletter of kleine letter?',
      buckets: ['hoofdletter', 'kleine letter'],
      items: [
        { t: '(n/N)ederlands (de taal)', b: 0 },
        { t: 'een (m/M)arokkaan', b: 0 },
        { t: '(t/T)urkse thee', b: 0 },
        { t: 'op (z/Z)aterdag', b: 1 },
        { t: 'in (o/O)ktober', b: 1 },
        { t: 'de (w/W)inter', b: 1 },
        { t: 'met (p/P)asen', b: 0 },
        { t: 'het (s/S)uikerfeest', b: 0 },
        { t: 'een (k/K)erstboom', b: 1 },
        { t: 'het (n/N)oorden', b: 1 },
        { t: '(z/Z)uid-Afrika', b: 0 },
        { t: '(a/A)msterdamse grachten', b: 0 },
      ],
      why: 'Taal, inwoner, bijvoeglijk naamwoord van een land of stad, feestdagen en namen van gebieden: hoofdletter. Dagen, maanden, seizoenen, windstreken en samenstellingen als kerstboom: klein.',
    },
    {
      kind: 'choice',
      id: 'taal',
      prompt: 'Kies de goede vorm.',
      before: 'Mijn vrouw spreekt heel goed',
      after: '.',
      options: ['Arabisch', 'arabisch'],
      answer: 'Arabisch',
      why: 'Een taal krijgt altijd een hoofdletter, ook midden in de zin.',
    },
    {
      kind: 'rewrite',
      id: 'vakantie',
      prompt: 'Zet de hoofdletters goed.',
      source: 'in de zomer gaan we met de kinderen naar turkije. in december vieren we kerstmis bij mijn schoonouders in friesland.',
      accept: ['In de zomer gaan we met de kinderen naar Turkije. In december vieren we Kerstmis bij mijn schoonouders in Friesland.'],
      why: 'Twee zinnen, dus twee keer een hoofdletter aan het begin. Turkije en Friesland zijn namen, Kerstmis is een feestdag. zomer en december blijven klein.',
    },
    {
      kind: 'choice',
      id: 'windstreek',
      prompt: 'Kies de goede vorm.',
      before: 'We gaan op vakantie naar het',
      after: 'van Frankrijk.',
      options: ['zuiden', 'Zuiden'],
      answer: 'zuiden',
      why: 'het zuiden is een windstreek, geen naam: klein.',
    },
    {
      kind: 'dictation',
      id: 'dictee-thee',
      prompt: 'Luister en typ precies wat je hoort.',
      intro: 'Let op de dag en op de woorden die van een land komen.',
      sentence: 'Op maandag eten we Franse kaas en drinken we Turkse thee.',
      right: 'Goed: maandag klein, Franse en Turkse groot.',
      wrong: 'Kijk nog eens: Op maandag eten we Franse kaas en drinken we Turkse thee. Een dag is klein; Franse en Turkse komen van een land en krijgen een hoofdletter.',
    },
    {
      kind: 'swipe',
      id: 'groot-klein-waar',
      prompt: 'Goed of fout geschreven?',
      intro: 'Veeg naar rechts als de zin goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'Ik volg een cursus Nederlands.', ok: true, why: 'Een taal: hoofdletter.' },
        { t: 'Mijn verjaardag is in Juni.', ok: false, fix: 'juni', why: 'Maanden schrijf je klein.' },
        { t: 'We drinken Turkse thee.', ok: true, why: 'Turkse komt van Turkije: hoofdletter.' },
        { t: 'Op zondag gaan we naar het strand.', ok: true, why: 'Op staat aan het begin van de zin; zondag blijft klein.' },
        { t: 'Met het suikerfeest komt de hele familie.', ok: false, fix: 'het Suikerfeest', why: 'Een feestdag krijgt een hoofdletter.' },
        { t: 'We wonen in het Noorden van het land.', ok: false, fix: 'het noorden', why: 'Een windstreek is geen naam: klein.' },
        { t: 'Mijn neef woont in Zuid-Afrika.', ok: true, why: 'De naam van een land: Zuid groot, met een koppelteken.' },
        { t: 'In de Winter is het vroeg donker.', ok: false, fix: 'de winter', why: 'Seizoenen schrijf je klein.' },
      ],
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Instellingen, merken en je mail',
      panels: [
        {
          text: 'De naam van één bepaalde gebeurtenis, instelling of één bepaald merk krijgt een hoofdletter: *de Tweede Wereldoorlog*, *de Elfstedentocht*, *de Tweede Kamer*, *de Belastingdienst*, *de Nederlandse Spoorwegen*, *Philips*, *Albert Heijn*. Het gewone woord blijft klein: *de oorlog*, *de gemeente*, *de politie*, *het ziekenhuis*, *de supermarkt*. Godsdiensten en hun gelovigen schrijf je ook klein: *de islam*, *het christendom*, *een moslim*, *een christen*.',
          rule: 'Naam van een gebeurtenis, instelling of merk: groot. Het gewone woord, een godsdienst of een gelovige: klein.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'Belastingdienst', out: 'een brief van de Belastingdienst', note: 'De naam van één instelling: groot.' },
              { k: 'gemeente', out: 'een brief van de gemeente Utrecht', note: 'gemeente is een gewoon woord: klein. Utrecht is de naam.' },
              { k: 'Albert Heijn', out: 'boodschappen bij Albert Heijn', note: 'Een merk of winkelnaam: groot.' },
              { k: 'supermarkt', out: 'boodschappen in de supermarkt', note: 'Een gewoon woord: klein.' },
              { k: 'islam', out: 'de islam, een moslim', note: 'Godsdienst en gelovige: klein.' },
            ],
          },
          quiz: {
            q: 'Welke zin is goed geschreven?',
            options: [
              'Ik heb een brief van de Belastingdienst en van de gemeente.',
              'Ik heb een brief van de belastingdienst en van de Gemeente.',
              'Ik heb een brief van de Belastingdienst en van de Gemeente.',
            ],
            answer: 'Ik heb een brief van de Belastingdienst en van de gemeente.',
            why: 'De Belastingdienst is de naam van één instelling. gemeente is een gewoon woord.',
          },
        },
        {
          text: 'In een mail of brief begin je met een aanhef met een komma: *Beste Sara,* of *Geachte heer De Vries,*. Op de volgende regel begin je met een hoofdletter: *Bedankt voor je mail.* Je sluit af met *Met vriendelijke groet,* of *Groetjes,* en op de regel daaronder je naam. Alleen het eerste woord van de afsluiting krijgt een hoofdletter.',
          rule: 'Aanhef met komma; de volgende regel begint met een hoofdletter. Afsluiting: *Met vriendelijke groet,*',
          show: [
            { wrong: 'Met Vriendelijke Groet,', right: 'Met vriendelijke groet,' },
            { wrong: 'Beste Sara, bedankt voor je mail.', right: 'Beste Sara, (nieuwe regel) Bedankt voor je mail.' },
          ],
          mark: {
            q: 'Dit is een korte mail in vier regels. Tik de woorden die een hoofdletter krijgen',
            sentence: 'beste sara, bedankt voor je mail. met vriendelijke groet, hasan',
            targets: [0, 1, 2, 6, 9],
            note: 'Beste en Sara (aanhef), Bedankt (nieuwe regel na de aanhef), Met (de afsluiting) en Hasan (je naam). vriendelijke en groet blijven klein.',
          },
        },
        {
          text: 'Twijfel je? Stel jezelf deze vragen. 1. Is het een taal, een inwoner of een woord dat van een land of plaats komt? Groot. 2. Is het een dag, maand of seizoen? Klein. 3. Is het een feestdag? Groot. Een samenstelling ermee (*kerstboom*)? Klein. 4. Een windstreek? Klein, behalve in een naam (*Noord-Holland*). 5. De naam van een instelling, gebeurtenis of merk? Groot. Het gewone woord? Klein.',
          rule: 'Een naam of iets wat van een naam komt: groot. Een gewoon woord: klein.',
          lab: {
            label: 'Tik een twijfelgeval',
            chips: [
              { k: 'Kerstmis / kerstboom', out: 'met Kerstmis staat er een kerstboom', note: 'Vraag 3: de feestdag groot, de samenstelling klein.' },
              { k: 'zuiden / Zuid-Afrika', out: 'in het zuiden van Zuid-Afrika', note: 'Vraag 4: de richting klein, de naam groot.' },
              { k: 'Turks / Turkse', out: 'Turks spreken en Turkse thee drinken', note: 'Vraag 1: allebei groot.' },
              { k: 'ziekenhuis', out: 'naar het ziekenhuis', note: 'Vraag 5: een gewoon woord, klein.' },
              { k: 'Offerfeest', out: 'met het Offerfeest', note: 'Vraag 3: een feestdag, groot.' },
            ],
          },
          quiz: {
            q: 'Welke zin is helemaal goed?',
            options: [
              'Na de kerstvakantie begint in januari mijn cursus Nederlands.',
              'Na de Kerstvakantie begint in januari mijn cursus Nederlands.',
              'Na de kerstvakantie begint in Januari mijn cursus nederlands.',
            ],
            answer: 'Na de kerstvakantie begint in januari mijn cursus Nederlands.',
            why: 'kerstvakantie is een samenstelling (klein), januari is een maand (klein), Nederlands is een taal (groot).',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'uitnodiging',
      prompt: 'Lees de uitnodiging na',
      intro: 'Er zitten zes hoofdletterfouten in. Tik ze aan.',
      header: { to: 'alle collega’s', subject: 'Feest op het werk' },
      tokens: [
        { t: 'Beste' },
        { t: 'collega’s,' },
        { t: 'Volgende' },
        { t: 'week' },
        { t: 'Vrijdag', fix: 'vrijdag', why: 'Dagen schrijf je klein.' },
        { t: 'vieren' },
        { t: 'we' },
        { t: 'het' },
        { t: 'suikerfeest', fix: 'Suikerfeest', why: 'Een feestdag krijgt een hoofdletter.' },
        { t: 'op' },
        { t: 'het' },
        { t: 'werk.' },
        { t: 'Iedereen' },
        { t: 'neemt' },
        { t: 'iets' },
        { t: 'lekkers' },
        { t: 'mee:' },
        { t: 'Turkse' },
        { t: 'baklava,' },
        { t: 'marokkaanse', fix: 'Marokkaanse', why: 'Komt van Marokko: hoofdletter.' },
        { t: 'koekjes' },
        { t: 'of' },
        { t: 'Hollandse' },
        { t: 'stroopwafels.' },
        { t: 'De' },
        { t: 'drankjes' },
        { t: 'halen' },
        { t: 'we' },
        { t: 'bij' },
        { t: 'albert', fix: 'Albert', why: 'Een winkelnaam: hoofdletter op elk deel, Albert Heijn.' },
        { t: 'Heijn.' },
        { t: 'Na' },
        { t: 'de' },
        { t: 'Zomervakantie', fix: 'zomervakantie', why: 'Een gewoon woord, net als zomer: klein.' },
        { t: 'doen' },
        { t: 'we' },
        { t: 'het' },
        { t: 'met' },
        { t: 'Kerstmis' },
        { t: 'nog' },
        { t: 'een' },
        { t: 'keer.' },
        { t: 'Met' },
        { t: 'Vriendelijke', fix: 'vriendelijke', why: 'In de afsluiting krijgt alleen het eerste woord een hoofdletter.' },
        { t: 'groet,' },
        { t: 'Noor' },
      ],
      done: {
        title: 'Klaar om te versturen',
        text: 'vrijdag, Suikerfeest, Marokkaanse, Albert Heijn, zomervakantie en Met vriendelijke groet. Turkse, Hollandse en Kerstmis waren al goed.',
      },
    },
    {
      kind: 'bet',
      id: 'kerst',
      prompt: 'Welke zin is goed geschreven?',
      intro: 'Een feestdag en een samenstelling in één zin. Hoe zeker ben je?',
      options: [
        'In de kerstvakantie vieren we Kerstmis.',
        'In de Kerstvakantie vieren we Kerstmis.',
        'In de kerstvakantie vieren we kerstmis.',
      ],
      answer: 'In de kerstvakantie vieren we Kerstmis.',
      why: 'Kerstmis is de naam van de feestdag: groot. kerstvakantie is een samenstelling, een gewoon woord: klein.',
    },
    {
      kind: 'sort',
      id: 'instellingen',
      prompt: 'Hoofdletter of kleine letter?',
      buckets: ['hoofdletter', 'kleine letter'],
      items: [
        { t: 'de (b/B)elastingdienst', b: 0 },
        { t: 'een brief van de (g/G)emeente', b: 1 },
        { t: 'de (t/T)weede Kamer', b: 0 },
        { t: 'de (p/P)olitie bellen', b: 1 },
        { t: 'boodschappen bij (a/A)lbert Heijn', b: 0 },
        { t: 'naar het (z/Z)iekenhuis', b: 1 },
        { t: 'de (t/T)weede Wereldoorlog', b: 0 },
        { t: 'de (i/I)slam', b: 1 },
        { t: 'een (m/M)oslim', b: 1 },
        { t: 'een lamp van (p/P)hilips', b: 0 },
      ],
      why: 'Belastingdienst, Tweede Kamer, Albert Heijn, Tweede Wereldoorlog en Philips zijn namen van één instelling, gebeurtenis of merk. gemeente, politie en ziekenhuis zijn gewone woorden; islam en moslim schrijf je klein.',
    },
    {
      kind: 'rewrite',
      id: 'noorden',
      prompt: 'Zet de hoofdletters goed.',
      source: 'in het noorden van nederland spreken veel mensen fries; in noord-brabant hoor je vaak brabants.',
      accept: ['In het noorden van Nederland spreken veel mensen Fries; in Noord-Brabant hoor je vaak Brabants.'],
      why: 'het noorden is een richting: klein. Nederland en Noord-Brabant zijn namen. Fries (een taal) en Brabants (een dialect) komen van een naam: groot.',
    },
    {
      kind: 'chat',
      id: 'mail-gemeente',
      prompt: 'Je schrijft een mail aan de gemeente',
      intro: 'Je taalcoach kijkt mee. Kies steeds de goede schrijfwijze.',
      contact: { name: 'Lotte', role: 'je taalcoach', initials: 'L' },
      rounds: [
        {
          say: 'Je weet niet wie de mail leest. Hoe begin je?',
          options: ['Geachte heer, mevrouw,', 'Geachte Heer, Mevrouw,'],
          right: 0,
          fix: 'Heer, Mevrouw → heer, mevrouw',
          why: 'heer en mevrouw zijn geen namen: klein. Hier krijgt alleen het eerste woord, Geachte, een hoofdletter.',
        },
        {
          say: 'En de eerste zin, op de regel na de aanhef?',
          options: ['graag wil ik een afspraak maken.', 'Graag wil ik een afspraak maken.'],
          right: 1,
          fix: 'graag → Graag',
          why: 'Na de aanhef begin je op een nieuwe regel met een hoofdletter.',
        },
        {
          say: 'Noem een dag waarop je kunt.',
          options: ['Kan het op Dinsdag 14 Mei?', 'Kan het op dinsdag 14 mei?'],
          right: 1,
          fix: 'Dinsdag 14 Mei → dinsdag 14 mei',
          why: 'Dagen en maanden schrijf je klein, ook in een datum.',
        },
        {
          say: 'En hoe sluit je af?',
          options: ['Met vriendelijke groet,', 'Met Vriendelijke Groet,'],
          right: 0,
          fix: 'Vriendelijke Groet → vriendelijke groet',
          why: 'Alleen het eerste woord van de afsluiting krijgt een hoofdletter.',
        },
      ],
      bye: 'Mooi! Zo kun je de mail versturen.',
    },
    {
      kind: 'dictation',
      id: 'dictee-cursus',
      prompt: 'Luister en typ precies wat je hoort.',
      intro: 'Let op het seizoen, de taal en de maand.',
      sentence: 'Na de zomervakantie begint mijn cursus Nederlands in september.',
      right: 'Goed: zomervakantie en september klein, Nederlands groot.',
      wrong: 'Kijk nog eens: Na de zomervakantie begint mijn cursus Nederlands in september. Een vakantie en een maand zijn klein, een taal is groot.',
    },
    {
      kind: 'write',
      id: 'uitnodiging-schrijven',
      prompt: 'Schrijf een korte uitnodiging aan een collega of buurvrouw.',
      intro: 'Nodig haar uit voor een feest. Begin met een aanhef, noem de dag en het feest, en sluit netjes af.',
      minWords: 30,
      must: [
        { label: 'Een aanhef met een naam, bijvoorbeeld Beste Sara,', hint: 'Beste …, Hoi …, Lieve …', test: { pattern: '^\\s*(Beste|Hoi|Hallo|Lieve|Geachte) [A-Z]' } },
        { label: 'Een dag met een kleine letter', hint: 'zaterdag, zondag', test: { pattern: '\\b(maandag|dinsdag|woensdag|donderdag|vrijdag|zaterdag|zondag)\\b' } },
        {
          label: 'Een feestdag met een hoofdletter',
          hint: 'Suikerfeest, Kerstmis, Koningsdag',
          test: { pattern: '\\b(Kerstmis|Pasen|Pinksteren|Koningsdag|Bevrijdingsdag|Suikerfeest|Offerfeest|Sinterklaas)\\b' },
        },
        { label: 'Een afsluiting', hint: 'Met vriendelijke groet, Groetjes', test: { pattern: '(Met vriendelijke groet|Groetjes|Hartelijke groet)' } },
      ],
      starters: ['Beste Sara,', 'Op zaterdag vieren we het Suikerfeest.', 'Je bent van harte welkom!', 'Groetjes,'],
      why: 'Een uitnodiging bevat bijna alle regels van deze les: een aanhef, een dag (klein), een feestdag (groot) en een afsluiting.',
      done: {
        title: 'Uitnodiging klaar',
        text: 'Lees nog één keer na: dag en maand klein, feestdag en namen groot, en na de aanhef een nieuwe regel met een hoofdletter.',
      },
    },
  ],
};
