import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": accenttekens voor nadruk (één, vóór), in leenwoorden (café, crème, à) en hoe je ze typt. */
export const LES_L23: LessonInput = {
  id: 'l23',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'Accenten: één, vóór en café',
  skill: 'Spelling',
  icon: 'é',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Een streepje op de klinker',
      panels: [
        {
          text: 'Een accent is een streepje op een klinker. Het belangrijkste accent in het Nederlands is het streepje naar rechts (´). Daarmee laat je zien dat een woord nadruk krijgt. Het bekendste voorbeeld: *een* en *één*. *Een* is het lidwoord: *Ik heb een fiets.* Met accenten is het het getal 1: *Ik heb één fiets, niet twee.* Aan het begin van een zin schrijf je *Eén*: meestal zonder accent op de hoofdletter, maar wel met een accent op de tweede *e*.',
          rule: '*een* = lidwoord (*een fiets*). *één* = het getal 1 (*één fiets, niet twee*).',
          lab: {
            label: 'Tik een zin',
            chips: [
              { k: 'een', out: 'Ik heb een fiets.', note: 'Lidwoord: zomaar een fiets.' },
              { k: 'één', out: 'Ik heb één fiets, niet twee.', note: 'Het getal: precies één.' },
              { k: 'Eén', out: 'Eén ding is zeker: ik kom.', note: 'Begin van de zin: hoofdletter E, accent op de tweede e.' },
              { k: 'één winnaar', out: 'Er kan maar één winnaar zijn.', note: 'Het getal: maar één, dus accenten.' },
            ],
          },
          quiz: {
            q: 'In welke zin hoort één, met accenten?',
            options: ['Er past maar … persoon in de lift.', 'Het is … mooie dag.', 'Hij is … aardige man.'],
            answer: 'Er past maar … persoon in de lift.',
            why: 'Hier gaat het om het getal: maar één persoon. In de andere zinnen is een het lidwoord.',
          },
        },
        {
          text: 'Je kunt ook andere woorden nadruk geven met een accent: *vóór*, *dé*, *wél*, *zó*, *dáár*, *véél*. Let op: bij *aa*, *ee*, *oo* en *uu* zet je het accent op allebei de letters: *één*, *vóór*, *dáár*, *véél*. Gebruik zo’n accent alleen als het nodig is: als de zin anders verkeerd gelezen kan worden, of als je echt nadruk wilt. *Hij kwam vóór mij binnen* (eerder dan ik) is iets anders dan *Hij kwam voor mij* (om mij te zien).',
          rule: 'Klemtoonaccent alleen als het nodig is. Bij *aa*, *ee*, *oo*, *uu*: op beide letters (*vóór*, *véél*).',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'vóór', out: 'Zet je fiets vóór het huis, niet erachter.', note: 'Aan de voorkant. Twee o’s, dus twee accenten.' },
              { k: 'voor', out: 'Dit cadeau is voor jou.', note: 'Gewoon voor: geen accent.' },
              { k: 'dé', out: 'Dit is dé bakker van de stad.', note: 'De beste, de bekendste.' },
              { k: 'wél', out: 'Ik kom niet vandaag, maar wél morgen.', note: 'Nadruk op wel, tegenover niet.' },
              { k: 'véél', out: 'Dat is véél te duur!', note: 'Sterke nadruk. Twee e’s, twee accenten.' },
            ],
          },
          quiz: {
            q: 'Je wilt nadruk op daar. Hoe schrijf je het?',
            options: ['dáár', 'dáar', 'daár', 'dàar'],
            answer: 'dáár',
            why: 'aa is één klank met twee letters: beide letters krijgen het accent.',
          },
        },
        {
          text: 'Veel woorden uit het Frans houden hun accent. Met het streepje naar rechts (é): *café*, *privé*, *coupé*, *comité*, *cliché*, *rosé*. Met het streepje naar links (è): *crème*, *scène*, *carrière*, *première*, *barrière*. En het woordje *à* betekent *per stuk* of *tot*: *broodjes à 2 euro*, *twee à drie dagen*. In het meervoud blijft het accent staan en komt er gewoon een *s* achter: *cafés*, *comités*, *clichés*.',
          rule: 'In leenwoorden is het accent vast: *café*, *crème*. Meervoud: accent blijft, plus *s* (*cafés*).',
          build: {
            before: 'In deze straat zijn drie',
            stem: 'café',
            endings: ['s', '’s', 'en'],
            answer: 's',
            note: 'cafés: de é blijft staan en je plakt er alleen een s achter. Een apostrof is niet nodig.',
          },
          deep: {
            q: 'Hoe weet je welk streepje het is?',
            a: 'Op een *e* aan het eind van het woord staat meestal *é*: *café*, *privé*. In het woord, voor een medeklinker en een *e*, staat meestal *è*: *crème*, *scène*, *carrière*. Twijfel je: zoek het op in de woordenlijst.',
          },
        },
        {
          text: "Hoe typ je een accent? Op een telefoon houd je de letter ingedrukt: er komt een rijtje met *é*, *è*, *ê* en *ë*. Schuif naar het goede teken. Op een Windows-computer met het toetsenbord *Verenigde Staten (internationaal)* typ je eerst *'* en dan *e*: dat wordt *é*. Met *`* en dan *e* krijg je *è*. Op een Mac druk je *Option* + *e* en daarna *e* voor *é*. Wil je op Windows alleen een apostrof, typ dan *'* en daarna een spatie.",
          rule: "Telefoon: letter ingedrukt houden. Windows (internationaal): *'* + *e* = *é*. Mac: *Option* + *e*, dan *e*.",
          lab: {
            label: 'Tik een apparaat',
            chips: [
              { k: 'telefoon', out: 'e ingedrukt houden → é è ê ë', note: 'Schuif met je vinger naar het goede teken.' },
              { k: 'Windows é', out: "' en dan e → é", note: 'Met het toetsenbord Verenigde Staten (internationaal).' },
              { k: 'Windows è', out: '` en dan e → è', note: 'De ` staat links naast de 1.' },
              { k: 'Mac', out: 'Option + e, dan e → é', note: 'Option + ` en dan e geeft è.' },
            ],
          },
          quiz: {
            q: 'Je typt op een telefoon. Hoe krijg je de é van café?',
            options: ['De e ingedrukt houden en é kiezen', 'Twee keer op de e tikken', 'Eerst een punt en dan de e'],
            answer: 'De e ingedrukt houden en é kiezen',
            why: 'Op bijna elke telefoon verschijnen de accenten als je de letter even vasthoudt.',
          },
        },
      ],
    },
    {
      kind: 'choice',
      id: 'niet-twee',
      prompt: 'Kies de goede vorm.',
      before: 'Niet twee, maar',
      after: 'kaartje, alstublieft.',
      options: ['één', 'een', 'eén', 'ééen'],
      answer: 'één',
      why: 'Het gaat om het getal: niet twee, maar één. Twee e’s, dus op allebei een accent.',
    },
    {
      kind: 'type',
      id: 'cafe',
      prompt: 'Typ het woord met het goede accent.',
      before: 'We drinken koffie in het',
      after: 'op de hoek.',
      hint: 'cafe',
      answer: 'café',
      why: 'café heeft altijd een accent op de e. Zonder accent is het fout.',
    },
    {
      kind: 'sort',
      id: 'accent-of-niet',
      prompt: 'Krijgt dit woord een accent?',
      buckets: ['met accent', 'zonder accent'],
      items: [
        { t: 'cafe', b: 0 },
        { t: 'puree', b: 1 },
        { t: 'prive', b: 0 },
        { t: 'entree', b: 1 },
        { t: 'creme', b: 0 },
        { t: 'dossier', b: 1 },
        { t: 'scene', b: 0 },
        { t: 'abonnee', b: 1 },
        { t: 'carriere', b: 0 },
        { t: 'atelier', b: 1 },
        { t: 'comite', b: 0 },
        { t: 'cadeau', b: 1 },
      ],
      why: 'Met accent: café, privé, crème, scène, carrière, comité. Zonder accent, ook al lijken ze Frans: puree, entree, dossier, abonnee, atelier, cadeau. Bij twijfel: opzoeken.',
    },
    {
      kind: 'choice',
      id: 'voor-mij',
      prompt: 'Hij was eerder dan ik. Kies de goede vorm.',
      before: 'Hij kwam',
      after: 'mij binnen.',
      options: ['vóór', 'voor', 'vòòr', 'vóor'],
      answer: 'vóór',
      why: 'Zonder accent kun je het lezen als: hij kwam om mij te zien. Met vóór is duidelijk: eerder dan ik. Twee o’s, dus twee accenten.',
    },
    {
      kind: 'dictation',
      id: 'dictee-rose',
      prompt: 'Luister en typ precies wat je hoort.',
      intro: 'Twee woorden in deze zin hebben een accent.',
      sentence: 'In het café bestellen we twee glazen rosé.',
      right: 'Goed: café en rosé, allebei met é.',
      wrong: 'Kijk nog eens: In het café bestellen we twee glazen rosé. Op je telefoon houd je de e ingedrukt.',
    },
    {
      kind: 'swipe',
      id: 'accent-waar',
      prompt: 'Klopt het?',
      intro: 'Veeg naar rechts als het klopt, naar links als het niet klopt.',
      cards: [
        { t: 'Het meervoud van café is cafés.', ok: true, why: 'Het accent blijft, en er komt alleen een s achter.' },
        { t: 'Je schrijft: Hij is één aardige jongen.', ok: false, fix: 'een aardige jongen', why: 'Hier is een het lidwoord, niet het getal: geen accent.' },
        { t: 'Bij nadruk op veel schrijf je véél, met twee accenten.', ok: true, why: 'Bij ee krijgen beide letters een accent.' },
        { t: 'crème schrijf je met hetzelfde streepje als café: créme.', ok: false, fix: 'crème', why: 'In crème staat het streepje naar links: è.' },
        { t: 'puree schrijf je zonder accent.', ok: true, why: 'Het lijkt Frans, maar de officiële spelling is puree.' },
        { t: 'Op je telefoon krijg je é door de e ingedrukt te houden.', ok: true, why: 'Dan verschijnen é, è, ê en ë.' },
        { t: 'Aan het begin van de zin schrijf je: Eén ding is zeker.', ok: true, why: 'Hoofdletter E zonder accent, de tweede e met accent.' },
        { t: 'Je schrijft: twee broodjes a 3 euro.', ok: false, fix: 'à 3 euro', why: 'à (per stuk) heeft een streepje naar links.' },
      ],
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Typische fouten met accenten',
      panels: [
        {
          text: 'De meest gemaakte fouten: het accent vergeten in een leenwoord (*cafe*), het verkeerde streepje (*créme*), en *één* schrijven als je het lidwoord bedoelt. Schrijf *één* alleen als je het getal bedoelt. En schrijf geen accent als er geen nadruk nodig is: in *Ik heb een vraag over de les* is *een* gewoon het lidwoord.',
          rule: 'Leenwoord: vast accent. Nadruk: alleen als het nodig is. *één* alleen voor het getal.',
          show: [
            { wrong: 'een kopje koffie in het cafe', right: 'een kopje koffie in het café' },
            { wrong: 'een taart met créme', right: 'een taart met crème' },
            { wrong: 'Hij is één aardige man.', right: 'Hij is een aardige man.' },
            { wrong: 'twee cafe’s', right: 'twee cafés' },
          ],
          quiz: {
            q: 'Welke zin is helemaal goed?',
            options: [
              'Na de première drinken we koffie in een café.',
              'Na de premiere drinken we koffie in één café.',
              'Na de premiére drinken we koffie in een cafe.',
            ],
            answer: 'Na de première drinken we koffie in een café.',
            why: 'première met è, café met é, en een is hier het lidwoord: geen accent.',
          },
        },
        {
          text: 'Niet elk woord dat Frans klinkt, heeft een accent. In de officiële spelling schrijf je zonder accent: *puree*, *entree*, *abonnee*, *dossier*, *atelier*, *cadeau*. Met accent blijven: *café*, *privé*, *comité*, *crème*, *scène*, *carrière*. Twijfel je? Zoek het woord op in de woordenlijst.',
          rule: 'Frans klinkend woord? Niet altijd een accent: *puree*, *entree*, *abonnee*. Bij twijfel: opzoeken.',
          mark: {
            q: 'Tik de woorden die een accent nodig hebben',
            sentence: 'cafe puree prive entree creme dossier scene abonnee',
            targets: [0, 2, 4, 6],
            note: 'café, privé, crème en scène hebben een accent. puree, entree, dossier en abonnee niet.',
          },
        },
        {
          text: 'Soms maakt het accent een ander woord. *Hé!* is een groet of roep (*Hé, hoe gaat het?*). *Hè?* vraag je als je instemming wilt (*Lekker weer, hè?*). Een *coupe* is een ijsje in een glas; een *coupé* is een stuk van een trein. En *één* tegenover *een*, *vóór* tegenover *voor*.',
          rule: '*hé* = groet, *hè* = toch? Let op: het accent kan de betekenis veranderen.',
          lab: {
            label: 'Tik een paar',
            chips: [
              { k: 'hé / hè', out: 'Hé, Sara! · Mooi, hè?', note: 'hé roept iemand, hè vraagt om instemming.' },
              { k: 'coupe / coupé', out: 'een coupe ijs · een coupé in de trein', note: 'Zonder accent een ijsje, met accent een treincoupé.' },
              { k: 'een / één', out: 'een fiets · één fiets', note: 'Lidwoord tegenover getal.' },
              { k: 'voor / vóór', out: 'voor jou · vóór jou', note: 'Om jou, tegenover eerder dan jij of aan de voorkant.' },
            ],
          },
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Lekker weer vandaag, hè?', 'Lekker weer vandaag, hé?', 'Lekker weer vandaag, he?'],
            answer: 'Lekker weer vandaag, hè?',
            why: 'Je vraagt om instemming: hè, met het streepje naar links.',
          },
        },
        {
          text: 'Twijfel je over een accent? Gebruik dit stappenplan. 1. Is het een leenwoord (*café*, *crème*, *privé*)? Dan hoort het accent erbij; zoek het op als je het niet zeker weet. 2. Is het een gewoon Nederlands woord? Dan alleen een accent als de zin anders verkeerd gelezen kan worden, of als je echt nadruk wilt. 3. Twee klinkers (*aa*, *ee*, *oo*, *uu*)? Accent op allebei: *één*, *vóór*. 4. Staat *één* aan het begin van de zin? Schrijf *Eén*.',
          rule: 'Leenwoord: accent vast. Nadruk: alleen als het nodig is, en bij twee klinkers op allebei.',
          lab: {
            label: 'Tik een twijfelgeval',
            chips: [
              { k: 'carriere', out: 'carrière', note: 'Stap 1: een leenwoord, met è.' },
              { k: 'een (getal)', out: 'Ik heb maar één uur pauze.', note: 'Stap 2 en 3: het getal, nadruk nodig, twee accenten.' },
              { k: 'een (lidwoord)', out: 'Ik heb een uur pauze gehad.', note: 'Stap 2: hier is geen nadruk nodig. Gewoon een.' },
              { k: 'een aan het begin', out: 'Eén vraag nog: hoe laat begint het?', note: 'Stap 4: hoofdletter E, accent op de tweede e.' },
            ],
          },
          quiz: {
            q: 'Welke vorm schrijf je aan het begin van een zin?',
            options: ['Eén', 'Een', 'EEN'],
            answer: 'Eén',
            why: 'Je bedoelt het getal: een accent op de tweede e. Op de hoofdletter E laat je het accent meestal weg.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'een-of-een',
      prompt: 'Lidwoord of getal?',
      buckets: ['een (lidwoord)', 'één (getal)'],
      items: [
        { t: 'Niet twee, maar … .', b: 1 },
        { t: 'Het is … mooie dag.', b: 0 },
        { t: 'Ik zoek … huis in Utrecht.', b: 0 },
        { t: 'Het staat drie tegen … .', b: 1 },
        { t: 'Hij is … aardige man.', b: 0 },
        { t: 'Ik heb nog maar … euro, geen twee.', b: 1 },
        { t: 'Wil je … kopje thee?', b: 0 },
        { t: 'Er past maar … persoon in de lift.', b: 1 },
      ],
      why: 'één schrijf je als het om het getal gaat, vooral als je het tegenover twee of drie zet: maar één, drie tegen één. Zomaar een dag, een huis of een kopje: het lidwoord, zonder accent.',
    },
    {
      kind: 'proofread',
      id: 'appje-sara',
      prompt: 'Lees het appje na',
      intro: 'Er zitten zes fouten met accenten in. Tik ze aan.',
      tokens: [
        { t: 'Hoi' },
        { t: 'Sara!' },
        { t: 'Zullen' },
        { t: 'we' },
        { t: 'morgen' },
        { t: 'lunchen' },
        { t: 'in' },
        { t: 'dat' },
        { t: 'nieuwe' },
        { t: 'cafe', fix: 'café', why: 'café heeft altijd een accent op de e.' },
        { t: 'bij' },
        { t: 'het' },
        { t: 'station?' },
        { t: 'Ze' },
        { t: 'hebben' },
        { t: 'broodjes' },
        { t: 'a', fix: 'à', why: 'à betekent hier per stuk: met het streepje naar links.' },
        { t: '3' },
        { t: 'euro.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'maar' },
        { t: 'één' },
        { t: 'uur' },
        { t: 'pauze.' },
        { t: 'Daarna' },
        { t: 'ga' },
        { t: 'ik' },
        { t: 'naar' },
        { t: 'de' },
        { t: 'premiere', fix: 'première', why: 'première met è.' },
        { t: 'van' },
        { t: 'de' },
        { t: 'film' },
        { t: 'van' },
        { t: 'mijn' },
        { t: 'neef.' },
        { t: 'Hij' },
        { t: 'speelt' },
        { t: 'in' },
        { t: 'de' },
        { t: 'laatste' },
        { t: 'scene', fix: 'scène', why: 'scène met è.' },
        { t: 'een' },
        { t: 'agent.' },
        { t: 'Het' },
        { t: 'is' },
        { t: 'één', fix: 'een', why: 'Hier is een het lidwoord, niet het getal: geen accent.' },
        { t: 'heel' },
        { t: 'spannende' },
        { t: 'film,' },
        { t: 'zegt' },
        { t: 'hij.' },
        { t: 'Leuk,' },
        { t: 'he?', fix: 'hè?', why: 'Je vraagt om instemming: hè, met het streepje naar links.' },
      ],
      done: {
        title: 'Netjes',
        text: 'café, à, première, scène, een en hè. De één van maar één uur pauze was goed: daar gaat het om het getal.',
      },
    },
    {
      kind: 'type',
      id: 'prive',
      prompt: 'Typ het woord met het goede accent.',
      before: 'Dit gesprek is',
      after: ': vertel het aan niemand.',
      hint: 'prive',
      answer: 'privé',
      why: 'privé heeft een accent op de laatste e, met het streepje naar rechts.',
    },
    {
      kind: 'type',
      id: 'cafes',
      prompt: 'Typ het meervoud.',
      before: 'In de binnenstad zijn veel gezellige',
      after: '.',
      hint: 'meervoud van café',
      answer: 'cafés',
      why: 'Het accent blijft staan en je plakt er een s achter: cafés. Geen apostrof, want de é blijft ook zo goed leesbaar.',
    },
    {
      kind: 'bet',
      id: 'daar',
      prompt: 'Nee, niet hier! … staat mijn auto. Hoe schrijf je daar met nadruk?',
      intro: 'Een lastig geval: een klank van twee letters. Hoe zeker ben je?',
      options: ['Dáár', 'Dáar', 'Daár'],
      answer: 'Dáár',
      why: 'aa is één klank met twee letters, dus krijgen beide letters een accent. De hoofdletter D verandert daar niets aan.',
    },
    {
      kind: 'rewrite',
      id: 'comite',
      prompt: 'Zet de accenten goed.',
      source: 'Het comite organiseert een premiere in het cafe.',
      accept: ['Het comité organiseert een première in het café.'],
      why: 'comité en café met é, première met è. een is hier het lidwoord: geen accent.',
    },
    {
      kind: 'dictation',
      id: 'dictee-broodjes',
      prompt: 'Luister en typ precies wat je hoort.',
      intro: 'Let op het kleine woordje voor de prijs.',
      sentence: 'Ik bestel twee broodjes à vier euro in het café.',
      right: 'Goed: à met het streepje naar links, café met het streepje naar rechts.',
      wrong: 'Kijk nog eens: Ik bestel twee broodjes à vier euro in het café. à betekent per stuk.',
    },
    {
      kind: 'choice',
      id: 'he-sara',
      prompt: 'Je ziet je vriendin op straat en roept haar. Kies de goede vorm.',
      before: '',
      after: ', Sara! Wacht even!',
      options: ['Hé', 'Hè', 'He'],
      answer: 'Hé',
      why: 'Je roept iemand: hé, met het streepje naar rechts. hè gebruik je als je om instemming vraagt: mooi, hè?',
    },
  ],
};
