import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": het trema, wanneer je het zet en wanneer juist niet. */
export const LES_L24: LessonInput = {
  id: 'l24',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'Het trema: ideeën en België',
  skill: 'Spelling',
  icon: 'ë',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Twee puntjes: hier begint iets nieuws',
      panels: [
        {
          text: 'Soms staan er twee klinkers naast elkaar die je *los* uitspreekt, terwijl je ze samen als één klank zou lezen. Schrijf je *ruine*, dan lees je *ui* zoals in *huis*. Schrijf je *Belgie*, dan lees je *ie* zoals in *die*. Het trema (de twee puntjes) zegt: hier begint een nieuwe lettergreep. Je zet het op de eerste klinker van die nieuwe lettergreep: *ru-ïne*, *Bel-gi-ë*, *i-dee-ën*.',
          rule: 'Trema: twee klinkers die samen één klank lijken, maar die je los uitspreekt. Het trema staat op de eerste letter van de nieuwe lettergreep.',
          show: [
            { wrong: 'ruine', right: 'ruïne' },
            { wrong: 'Belgie', right: 'België' },
            { wrong: 'ideeen', right: 'ideeën' },
          ],
          quiz: {
            q: 'Op welke letter staat het trema in poëzie?',
            options: ['op de o', 'op de e', 'op de i'],
            answer: 'op de e',
            why: 'po-ë-zie: met de e begint een nieuwe lettergreep. Zonder trema lees je oe, zoals in boek.',
          },
        },
        {
          text: 'Een trema is alleen nodig als de twee klinkers samen een bekende klank kunnen vormen, zoals *ee*, *oo*, *ie*, *oe*, *eu*, *ui*, *ei*, *ai* of *oi*. Kijk maar: *reünie* (niet *eu*), *ruïne* (niet *ui*), *poëzie* (niet *oe*), *naïef* (niet *ai*), *egoïst* (niet *oi*), *coördinatie* (niet *oo*), *reëel* (niet *ee*). Vormen de twee klinkers samen géén klank, zoals *ea* in *oceaan* of *eo* in *geopend*, dan lees je ze vanzelf los. Dan komt er geen trema.',
          rule: 'Geen bekende klank samen (*ea*, *eo*, *ia*)? Dan geen trema: *oceaan*, *geopend*, *piano*.',
          mark: {
            q: 'Tik de woorden die een trema nodig hebben',
            sentence: 'poezie beamen ruine geopend reunie oceaan naief beantwoorden',
            targets: [0, 2, 4, 6],
            note: 'poëzie, ruïne, reünie en naïef: daar staan oe, ui, eu en ai, die je anders samen leest. In beamen, geopend, oceaan en beantwoorden staan ea en eo: geen klank, dus geen trema.',
          },
        },
        {
          text: 'Achter *ge-* en *be-* botst de *e* vaak met de volgende klinker. Begint het werkwoord met een *e*, *i* of *u*, dan krijgt die letter een trema: *geëmigreerd*, *geëerd*, *beëindigen*, *geïnteresseerd*, *geïnformeerd*, *beïnvloeden*, *geïnd* (van *innen*), *geüpload*. Zonder trema zou je *ee*, *ei* of *eu* lezen: in *geinformeerd* lees je *ei* zoals in *klein*.',
          rule: '*ge-* of *be-* + een werkwoord dat begint met *e*, *i* of *u*: trema op die letter.',
          build: {
            before: 'Ik ben goed',
            stem: 'ge',
            endings: ['informeerd', 'ïnformeerd', '-informeerd'],
            answer: 'ïnformeerd',
            note: 'geïnformeerd. Zonder trema lees je ei, zoals in klein. Een koppelteken kan niet: ge- is geen los woord.',
          },
          deep: {
            q: 'En bij een werkwoord met a of o?',
            a: 'Dan is er niets aan de hand: *ea* en *eo* vormen geen klank. Dus *geopend*, *geoefend*, *geadresseerd*, *beantwoorden* en *beoordelen*: geen trema.',
          },
        },
        {
          text: 'Een woord op *ee* krijgt in het meervoud *-ën*: *idee* → *ideeën*, *zee* → *zeeën*, *trofee* → *trofeeën*. Bij woorden op *-ie* kijk je naar de klemtoon. Ligt de klemtoon op *ie*, dan krijg je *-ieën*: *knie* → *knieën*, *melodie* → *melodieën*, *industrie* → *industrieën*, *categorie* → *categorieën*. Ligt de klemtoon ergens anders, dan wordt het *-iën*: *bacterie* → *bacteriën*, *provincie* → *provinciën* (of *provincies*). Let op: veel woorden zonder klemtoon op *ie* krijgen gewoon een *-s*: *familie* → *families*, *studie* → *studies*.',
          rule: 'Klemtoon op *ie*: *-ieën* (*knieën*). Geen klemtoon op *ie*: *-iën* (*bacteriën*) of *-s* (*families*).',
          paradigm: {
            q: 'Zet elk meervoud in de tabel',
            cols: ['meervoud'],
            rows: [
              { label: 'idee', cells: [{ fill: 'ideeën' }] },
              { label: 'zee', cells: [{ fill: 'zeeën' }] },
              { label: 'knie', cells: [{ fill: 'knieën', hint: 'knie + en: de ie blijft staan, de e van -en krijgt het trema.' }] },
              { label: 'melodie', cells: [{ fill: 'melodieën', hint: 'me-lo-DIE: klemtoon op die, dus -ieën.' }] },
              { label: 'categorie', cells: [{ fill: 'categorieën' }] },
              { label: 'bacterie', cells: [{ fill: 'bacteriën', hint: 'bac-TE-rie: de klemtoon ligt niet op ie, dus -iën.' }] },
            ],
            extra: ['ideeen', 'knieen', 'bacterieën', 'melodiën'],
            note: 'ideeën, zeeën, knieën, melodieën, categorieën: klemtoon op het eind, dus de hele ee of ie blijft staan en -ën komt erachter. bacteriën: geen klemtoon op ie, dus alleen -ën na de i.',
          },
        },
        {
          text: 'Veel landen eindigen op *-ië*: *België*, *Italië*, *Australië*, *Indonesië*, *Tunesië*. De inwoner heeft soms ook een trema: *een Australiër*, *een Indonesiër*, *een Tunesiër*. Maar niet altijd: *een Belg*, *een Italiaan*. Ook bijvoeglijke naamwoorden op *-ieel* krijgen een trema als er een *-e* achter komt: *financieel* → *financiële*, *officieel* → *officiële*, *reëel* → *reële*.',
          rule: '*-ieel* + *e* wordt *-iële*: *een financiële afspraak*, *de officiële brief*.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'België', out: 'een Belg, Belgische chocola', note: 'Het land heeft een trema, de inwoner niet.' },
              { k: 'Italië', out: 'een Italiaan, Italiaanse pasta', note: 'ia is geen klank: geen trema nodig.' },
              { k: 'Australië', out: 'een Australiër', note: 'Hier houdt de inwoner het trema: Austra-li-ër.' },
              { k: 'financieel', out: 'een financiële afspraak', note: 'Met de e begint een nieuwe lettergreep: fi-nan-ci-ë-le. Het trema komt op de e.' },
              { k: 'officieel', out: 'de officiële brief', note: 'Zelfde patroon: officiële.' },
              { k: 'reëel', out: 'een reële kans', note: 'reëel heeft zelf al een trema. Met -e erachter: reële.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'ge-be',
      prompt: 'Plak de delen aan elkaar. Komt er een trema?',
      buckets: ['met trema', 'zonder trema'],
      items: [
        { t: 'ge + interesseerd', b: 0 },
        { t: 'ge + opend', b: 1 },
        { t: 'be + eindigen', b: 0 },
        { t: 'be + antwoorden', b: 1 },
        { t: 'ge + emigreerd', b: 0 },
        { t: 'ge + oefend', b: 1 },
        { t: 'be + invloeden', b: 0 },
        { t: 'ge + adresseerd', b: 1 },
        { t: 'ge + ind', b: 0 },
        { t: 'be + oordelen', b: 1 },
        { t: 'ge + upload', b: 0 },
      ],
      why: 'Met trema: geïnteresseerd, beëindigen, geëmigreerd, beïnvloeden, geïnd en geüpload, want ei, ee en eu zou je samen lezen. Zonder trema: geopend, beantwoorden, geoefend, geadresseerd en beoordelen, want eo en ea vormen geen klank.',
    },
    {
      kind: 'choice',
      id: 'geinteresseerd',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'Ik ben erg',
      after: 'in deze vacature.',
      options: ['geinteresseerd', 'geïnteresseerd', 'ge-interesseerd', 'geïnteresseërd'],
      answer: 'geïnteresseerd',
      why: 'ge + interesseerd: zonder trema lees je ei. Het trema komt op de i. Een koppelteken kan niet, want ge- is geen los woord. Verder in het woord is geen trema nodig.',
    },
    {
      kind: 'fix',
      id: 'ideeen',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Mijn collega heeft twee goede ideeen voor het feest.',
      wrong: 5,
      answer: 'ideeën',
      why: 'idee + en: drie keer e achter elkaar. Het trema op de laatste e laat zien waar de nieuwe lettergreep begint: i-dee-ën.',
    },
    {
      kind: 'type',
      id: 'knieen',
      prompt: 'Typ het meervoud van knie.',
      before: 'Na het voetballen deden allebei mijn',
      after: 'pijn.',
      hint: 'meervoud van knie',
      answer: 'knieën',
      why: 'knie heeft de klemtoon op ie. Dan blijft ie staan en komt -ën erachter: knieën.',
    },
    {
      kind: 'type',
      id: 'beeindigd',
      prompt: 'Typ het voltooid deelwoord van beëindigen.',
      before: 'De gemeente heeft het contract',
      after: '.',
      hint: 'be…',
      answer: 'beëindigd',
      why: 'be + eindigd: zonder trema lees je bee-indigd. Het trema komt op de e van eindigen. Aan het eind een d, want de stam eindig eindigt op g.',
    },
    {
      kind: 'bet',
      id: 'bacterie',
      prompt: 'Wat is het meervoud van bacterie?',
      options: ['bacterieën', 'bacteriën', 'bacterien'],
      answer: 'bacteriën',
      why: 'bac-TE-rie: de klemtoon ligt niet op ie. Dan wordt het -iën, met het trema op de e. bacterieën zou alleen kunnen met klemtoon op ie, zoals bij knieën.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Niet te veel, niet te weinig',
      panels: [
        {
          text: 'Een trema staat er alleen als je het woord anders verkeerd zou lezen. Veel mensen zetten er juist een te veel. In *geopend*, *beantwoorden*, *geoefend*, *oceaan*, *Italiaan* en *piano* lees je de klinkers vanzelf los, want *eo*, *ea* en *ia* vormen samen geen klank. Daar komt dus geen trema.',
          rule: 'Lees je het woord ook zonder trema goed? Dan geen trema.',
          show: [
            { wrong: 'geöpend', right: 'geopend' },
            { wrong: 'beäntwoorden', right: 'beantwoorden' },
            { wrong: 'Italiäan', right: 'Italiaan' },
          ],
          quiz: {
            q: 'Welk woord is goed geschreven?',
            options: ['geoefend', 'geöefend', 'geoëfend'],
            answer: 'geoefend',
            why: 'ge + oefend: eo is geen klank, dus geen trema. De oe hoort gewoon bij elkaar: oe-fe-nen.',
          },
        },
        {
          text: 'Plak je twee hele woorden aan elkaar en botsen de klinkers, dan gebruik je geen trema maar een koppelteken: *zee-egel*, *auto-ongeluk*, *zonne-energie*. Een trema zet je alleen binnen één woord: bij een uitgang zoals *-en* (*zeeën*) of na *ge-* en *be-* (*beëindigen*). Meer daarover in de les over het koppelteken.',
          rule: 'Twee woorden aan elkaar: koppelteken. Een uitgang of *ge-*/*be-* ervoor: trema.',
          lab: {
            label: 'Tik een combinatie',
            chips: [
              { k: 'zee + en', out: 'zeeën', note: '-en is een uitgang, geen woord: trema.' },
              { k: 'zee + egel', out: 'zee-egel', note: 'egel is een woord: koppelteken.' },
              { k: 'be + eindigen', out: 'beëindigen', note: 'be- is geen los woord: trema.' },
              { k: 'auto + ongeluk', out: 'auto-ongeluk', note: 'Twee woorden: koppelteken.' },
              { k: 'idee + en', out: 'ideeën', note: 'Uitgang: trema.' },
              { k: 'zonne + energie', out: 'zonne-energie', note: 'energie is een woord: koppelteken.' },
            ],
          },
        },
        {
          text: 'Moet je een woord afbreken aan het eind van de regel, precies op de plek van het trema? Dan verdwijnt het trema. Het afbreekstreepje laat al zien dat daar een nieuwe lettergreep begint: *ru-* en op de volgende regel *ine*, *knie-* en dan *en*. Meestal doet je computer of telefoon dit vanzelf. Meer daarover in de les over afbreken.',
          rule: 'Afbreken op de plek van het trema: het trema valt weg (*ru-ine*, *knie-en*).',
          quiz: {
            q: 'Je moet ruïne afbreken aan het eind van de regel. Wat schrijf je?',
            options: ['ru-ine', 'ru-ïne', 'ruï-ne'],
            answer: 'ru-ine',
            why: 'Je breekt af op de lettergreepgrens ru | ine. Het streepje doet nu het werk van het trema, dus de puntjes vallen weg.',
          },
        },
        {
          text: 'Twijfel je? Loop deze vragen langs. 1. Staan er twee klinkers naast elkaar? 2. Kunnen ze samen één klank zijn, zoals *ee*, *oo*, *ie*, *oe*, *eu* of *ui*? Nee: geen trema. 3. Spreek je ze los uit? Nee: geen trema. 4. Zijn het twee hele woorden? Dan een koppelteken. Anders: een trema op de eerste klinker van de nieuwe lettergreep.',
          rule: 'Klank samen + los uitspreken + binnen één woord = trema.',
          lab: {
            label: 'Tik een woord en loop het stappenplan langs',
            chips: [
              { k: 'coordinatie', out: 'coördinatie', note: 'oo is een klank, maar je zegt co-or. Binnen één woord: trema op de tweede o.' },
              { k: 'geopend', out: 'geopend', note: 'eo is geen klank: je bent al klaar bij vraag 2. Geen trema.' },
              { k: 'zeeegel', out: 'zee-egel', note: 'Twee hele woorden: zee en egel. Dus een koppelteken.' },
              { k: 'financiele', out: 'financiële', note: 'ie is een klank, maar hier begint met de e een nieuwe lettergreep: fi-nan-ci-ë-le. Trema op de e.' },
              { k: 'reunie', out: 'reünie', note: 'eu is een klank, maar je zegt re-u-nie. Trema op de u.' },
              { k: 'egoist', out: 'egoïst', note: 'oi lees je samen, maar je zegt e-go-ist. Trema op de i.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-school',
      prompt: 'Lees de mail na',
      intro: 'Hasan mailt de mentor van zijn zoon. Er zitten zes fouten in met het trema: vijf keer ontbreekt het, één keer staat het er onnodig. Tik ze aan.',
      header: { to: 'meneer Bakker', subject: 'Ouderavond' },
      tokens: [
        { t: 'Beste' },
        { t: 'meneer' },
        { t: 'Bakker,' },
        { t: 'Bedankt' },
        { t: 'dat' },
        { t: 'u' },
        { t: 'ons' },
        { t: 'hebt' },
        { t: 'geinformeerd', fix: 'geïnformeerd', why: 'ge + informeerd: zonder trema lees je ei. Trema op de i.' },
        { t: 'over' },
        { t: 'de' },
        { t: 'ouderavond.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'uw' },
        { t: 'mail' },
        { t: 'pas' },
        { t: 'gisteren' },
        { t: 'geöpend,', fix: 'geopend,', why: 'eo is geen klank: je leest het zonder trema al goed. Geen trema.' },
        { t: 'excuses' },
        { t: 'daarvoor.' },
        { t: 'Mijn' },
        { t: 'vrouw' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'hebben' },
        { t: 'wel' },
        { t: 'een' },
        { t: 'paar' },
        { t: 'vragen' },
        { t: 'over' },
        { t: 'de' },
        { t: 'financiele', fix: 'financiële', why: 'financieel + e: ie + e botsen. Trema op de e: financiële.' },
        { t: 'kant' },
        { t: 'van' },
        { t: 'de' },
        { t: 'schoolreis' },
        { t: 'naar' },
        { t: 'Italie.', fix: 'Italië.', why: 'Het land eindigt op -ië: Italië.' },
        { t: 'Kunt' },
        { t: 'u' },
        { t: 'ons' },
        { t: 'de' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: trema op de laatste e.' },
        { t: 'van' },
        { t: 'de' },
        { t: 'coordinator', fix: 'coördinator', why: 'co + ordinator: zonder trema lees je coor, zoals in door. Trema op de tweede o.' },
        { t: 'sturen?' },
        { t: 'Met' },
        { t: 'vriendelijke' },
        { t: 'groet,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Zes keer goed gekeken',
        text: 'geïnformeerd, financiële, Italië, ideeën en coördinator misten een trema. In geopend hoort er geen: eo is geen klank.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-reunie',
      prompt: 'Luister en typ de zin precies over.',
      intro: 'Let op hoofdletters, trema’s en de punt.',
      sentence: 'Na de reünie in België deden mijn knieën pijn.',
      right: 'Goed: reünie (eu los), België (land op -ië) en knieën (klemtoon op ie, dus -ieën).',
      wrong: 'Kijk naar de drie trema’s: re-ü-nie, Bel-gi-ë en knie-ën. België krijgt ook een hoofdletter.',
    },
    {
      kind: 'sort',
      id: 'klemtoon-ie',
      prompt: 'Ligt de klemtoon op ie? Dat bepaalt het meervoud.',
      buckets: ['klemtoon op ie: -ieën', 'geen klemtoon op ie: -iën of -s'],
      items: [
        { t: 'knie', b: 0 },
        { t: 'melodie', b: 0 },
        { t: 'industrie', b: 0 },
        { t: 'categorie', b: 0 },
        { t: 'kopie', b: 0 },
        { t: 'calorie', b: 0 },
        { t: 'theorie', b: 0 },
        { t: 'bacterie', b: 1 },
        { t: 'provincie', b: 1 },
        { t: 'familie', b: 1 },
        { t: 'studie', b: 1 },
      ],
      why: 'knieën, melodieën, industrieën, categorieën, kopieën, calorieën en theorieën: klemtoon op ie. bacteriën, provinciën (of provincies), families en studies: de klemtoon ligt eerder in het woord.',
    },
    {
      kind: 'swipe',
      id: 'trema-waar',
      prompt: 'Klopt de schrijfwijze?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'In de zomer zwemmen we graag in de zeeën rond Griekenland.', ok: true, why: 'zee + en: zeeën, met trema.' },
        { t: 'Ik ben erg geinteresseerd in die cursus.', ok: false, fix: 'geinteresseerd → geïnteresseerd', why: 'ge + interesseerd: trema op de i.' },
        { t: 'Ik heb de doos voorzichtig geöpend.', ok: false, fix: 'geöpend → geopend', why: 'eo is geen klank: geen trema nodig.' },
        { t: 'We zagen een zeeëgel op het strand.', ok: false, fix: 'zeeëgel → zee-egel', why: 'zee en egel zijn twee woorden: koppelteken, geen trema.' },
        { t: 'Mijn tante woont in Belgie.', ok: false, fix: 'Belgie → België', why: 'Zonder trema lees je ie zoals in die.' },
        { t: 'Hij heeft de brief nog niet beantwoord.', ok: true, why: 'ea is geen klank: geen trema.' },
        { t: 'Dat is een reële kans.', ok: true, why: 'reëel + e: reële.' },
        { t: 'Mijn buurman is een Italiaan.', ok: true, why: 'ia is geen klank: Italiaan zonder trema, ook al heeft Italië er wel een.' },
      ],
    },
    {
      kind: 'rewrite',
      id: 'meervoud-knie',
      prompt: 'Zet de zin in het meervoud: van één speler naar alle spelers.',
      source: 'De knie van de speler is gezwollen.',
      accept: ['De knieën van de spelers zijn gezwollen.', 'De knieën van alle spelers zijn gezwollen.'],
      why: 'knie wordt knieën (klemtoon op ie), speler wordt spelers, en is wordt zijn.',
    },
    {
      kind: 'choice',
      id: 'australier',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'Mijn nieuwe collega komt uit Australië. Hij is',
      after: '.',
      options: ['Australier', 'Australiër', 'australiër', 'Austraaliër'],
      answer: 'Australiër',
      why: 'Austra-li-ër: zonder trema lees je ie. De hoofdletter blijft, want het is een inwoner van een land.',
    },
    {
      kind: 'fix',
      id: 'coordinatie',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Sanne doet de coordinatie van het project.',
      wrong: 3,
      answer: 'coördinatie',
      why: 'co + ordinatie: zonder trema lees je coor, zoals in door. Trema op de tweede o.',
    },
    {
      kind: 'write',
      id: 'appje-uitje',
      prompt: 'Schrijf je collega’s een bericht over het personeelsuitje.',
      intro: 'Schrijf minstens 25 woorden. Gebruik minstens drie woorden met een trema.',
      minWords: 25,
      must: [
        {
          label: 'Het woord ideeën',
          hint: 'ideeën',
          test: { anyWord: ['ideeën'] },
        },
        {
          label: 'Een werkwoord met ge- of be- en een trema',
          hint: 'geïnteresseerd, geïnformeerd, beëindigen',
          test: { pattern: '(?:^|\\s)(?:ge|be)[ëïü]\\p{L}+', flags: 'iu' },
        },
        {
          label: 'Een land op -ië of een woord op -iële',
          hint: 'België, Italië, financiële',
          test: { pattern: '\\p{L}+i(?:ë|ële)(?!\\p{L})', flags: 'iu' },
        },
      ],
      starters: ['Hoi allemaal, ik heb een paar ideeën voor het uitje.', 'Wie is er geïnteresseerd in', 'Over de financiële kant:'],
      why: 'Check nog één keer elk trema: staat het op de eerste letter van de nieuwe lettergreep? En heb je er geen gezet in woorden als geopend of beantwoorden?',
    },
  ],
};
