import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": het trema, wanneer je het zet en wanneer juist niet. */
export const LES_L24: LessonInput = {
  id: 'l24',
  stage: 'regels',
  domain: 'orth',
  also: ['fon'],
  title: 'Het trema: ideeën en België',
  skill: 'Spelling',
  icon: 'ë',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Twee puntjes: hier begint iets nieuws',
      panels: [
        {
          text: 'Soms staan er twee klinkers naast elkaar die je *los* uitspreekt, terwijl je ze samen als één klank zou lezen. Schrijf je *ruine*, dan lees je *ui* zoals in *huis*. Schrijf je *Belgie*, dan lees je *ie* zoals in *die*. Het trema (de twee puntjes) zegt: hier begint een nieuwe lettergreep. Je zet het op de eerste klinker van die nieuwe lettergreep: *ru-ïne*, *Bel-gi-ë*, *i-dee-ën*.',
          rule: 'Trema: twee klinkers die samen één klank lijken, maar die je los uitspreekt. Het trema staat op de eerste letter van de nieuwe lettergreep.',
          show: [
            { wrong: 'ruine', right: 'ruïne' },
            { wrong: 'Belgie', right: 'België' },
            { wrong: 'ideeen', right: 'ideeën' },
          ],
          quiz: {
            q: 'Op welke letter staat het trema in poëzie?',
            options: ['op de o', 'op de e', 'op de i'],
            answer: 'op de e',
            why: 'po-ë-zie: met de e begint een nieuwe lettergreep. Zonder trema lees je oe, zoals in boek.',
          },
        },
        {
          text: 'Een trema is alleen nodig als de twee klinkers samen een bekende klank kunnen vormen, zoals *ee*, *oo*, *ie*, *oe*, *eu*, *ui*, *ei*, *ai* of *oi*. Kijk maar: *reünie* (niet *eu*), *ruïne* (niet *ui*), *poëzie* (niet *oe*), *naïef* (niet *ai*), *egoïst* (niet *oi*), *coördinatie* (niet *oo*), *reëel* (niet *ee*). Vormen de twee klinkers samen géén klank, zoals *ea* in *oceaan* of *eo* in *geopend*, dan lees je ze vanzelf los. Dan komt er geen trema.',
          rule: 'Geen bekende klank samen (*ea*, *eo*, *ia*)? Dan geen trema: *oceaan*, *geopend*, *piano*.',
          mark: {
            q: 'Tik de woorden die een trema nodig hebben',
            sentence: 'poezie beamen ruine geopend reunie oceaan naief beantwoorden',
            targets: [0, 2, 4, 6],
            note: 'poëzie, ruïne, reünie en naïef: daar staan oe, ui, eu en ai, die je anders samen leest. In beamen, geopend, oceaan en beantwoorden staan ea en eo: geen klank, dus geen trema.',
          },
        },
        {
          text: 'Achter *ge-* en *be-* botst de *e* vaak met de volgende klinker. Begint het werkwoord met een *e*, *i* of *u*, dan krijgt die letter een trema: *geëmigreerd*, *geëerd*, *beëindigen*, *geïnteresseerd*, *geïnformeerd*, *beïnvloeden*, *geïnd* (van *innen*), *geüpload*. Zonder trema zou je *ee*, *ei* of *eu* lezen: in *geinformeerd* lees je *ei* zoals in *klein*. Let op: begint het werkwoord met *ui*, dan komt er geen trema: *geuit* (van *uiten*). De *ui* blijft vanzelf bij elkaar.',
          rule: '*ge-* of *be-* + een werkwoord dat begint met *e*, *i* of *u*: trema op die letter. Behalve bij *ui*: *geuit*.',
          build: {
            before: 'Ik ben goed',
            stem: 'ge',
            endings: ['informeerd', 'ïnformeerd', '-informeerd'],
            answer: 'ïnformeerd',
            note: 'geïnformeerd. Zonder trema lees je ei, zoals in klein. Een koppelteken kan niet: ge- is geen los woord.',
          },
          deep: {
            q: 'En bij een werkwoord met a of o?',
            a: 'Dan is er niets aan de hand: *ea* en *eo* vormen geen klank. Dus *geopend*, *geoefend*, *geadresseerd*, *beantwoorden* en *beoordelen*: geen trema.',
          },
        },
        {
          text: 'Een woord op *ee* krijgt in het meervoud meestal *-ën*: *idee* → *ideeën*, *zee* → *zeeën*, *trofee* → *trofeeën*. Bij woorden op *-ie* kijk je naar de klemtoon. Ligt de klemtoon op *ie*, dan krijg je *-ieën*: *knie* → *knieën*, *melodie* → *melodieën*, *industrie* → *industrieën*, *categorie* → *categorieën*. Ligt de klemtoon ergens anders, dan wordt het *-iën*: *bacterie* → *bacteriën*, *provincie* → *provinciën* (of *provincies*). Let op: veel woorden zonder klemtoon op *ie* krijgen gewoon een *-s*: *familie* → *families*, *studie* → *studies*.',
          rule: 'Klemtoon op *ie*: *-ieën* (*knieën*). Geen klemtoon op *ie*: *-iën* (*bacteriën*) of *-s* (*families*).',
          paradigm: {
            q: 'Zet elk meervoud in de tabel',
            cols: ['meervoud'],
            rows: [
              { label: 'idee', cells: [{ fill: 'ideeën' }] },
              { label: 'zee', cells: [{ fill: 'zeeën' }] },
              { label: 'knie', cells: [{ fill: 'knieën', hint: 'knie + en: de ie blijft staan, de e van -en krijgt het trema.' }] },
              { label: 'melodie', cells: [{ fill: 'melodieën', hint: 'me-lo-DIE: klemtoon op die, dus -ieën.' }] },
              { label: 'categorie', cells: [{ fill: 'categorieën' }] },
              { label: 'bacterie', cells: [{ fill: 'bacteriën', hint: 'bac-TE-rie: de klemtoon ligt niet op ie, dus -iën.' }] },
            ],
            extra: ['ideeen', 'knieen', 'bacterieën', 'melodiën'],
            note: 'ideeën, zeeën, knieën, melodieën, categorieën: klemtoon op het eind, dus de hele ee of ie blijft staan en -ën komt erachter. bacteriën: geen klemtoon op ie, dus alleen -ën na de i.',
          },
        },
        {
          text: 'Veel landen eindigen op *-ië*: *België*, *Italië*, *Australië*, *Indonesië*, *Tunesië*. De inwoner heeft soms ook een trema: *een Australiër*, *een Indonesiër*, *een Tunesiër*. Maar niet altijd: *een Belg*, *een Italiaan*. Ook bijvoeglijke naamwoorden op *-ieel* krijgen een trema als er een *-e* achter komt: *financieel* → *financiële*, *officieel* → *officiële*, *reëel* → *reële*.',
          rule: '*-ieel* + *e* wordt *-iële*: *een financiële afspraak*, *de officiële brief*.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'België', out: 'een Belg, Belgische chocola', note: 'Het land heeft een trema, de inwoner niet.' },
              { k: 'Italië', out: 'een Italiaan, Italiaanse pasta', note: 'ia is geen klank: geen trema nodig.' },
              { k: 'Australië', out: 'een Australiër', note: 'Hier houdt de inwoner het trema: Austra-li-ër.' },
              { k: 'financieel', out: 'een financiële afspraak', note: 'Met de e begint een nieuwe lettergreep: fi-nan-ci-ë-le. Het trema komt op de e.' },
              { k: 'officieel', out: 'de officiële brief', note: 'Zelfde patroon: officiële.' },
              { k: 'reëel', out: 'een reële kans', note: 'reëel heeft zelf al een trema. Met -e erachter: reële.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'ge-be',
      prompt: 'Plak de delen aan elkaar. Komt er een trema?',
      buckets: ['met trema', 'zonder trema'],
      items: [
        { t: 'ge + interesseerd', b: 0 },
        { t: 'ge + opend', b: 1 },
        { t: 'be + eindigen', b: 0 },
        { t: 'be + antwoorden', b: 1 },
        { t: 'ge + emigreerd', b: 0 },
        { t: 'ge + oefend', b: 1 },
        { t: 'be + invloeden', b: 0 },
        { t: 'ge + adresseerd', b: 1 },
        { t: 'ge + ind', b: 0 },
        { t: 'be + oordelen', b: 1 },
        { t: 'ge + upload', b: 0 },
        { t: 'ge + organiseerd', b: 1 },
        { t: 'ge + eist', b: 0 },
        { t: 'ge + oogst', b: 1 },
        { t: 'ge + isoleerd', b: 0 },
        { t: 'ge + uit (van uiten)', b: 1 },
      ],
      why: 'Met trema: geïnteresseerd, beëindigen, geëmigreerd, beïnvloeden, geïnd, geüpload, geëist en geïsoleerd, want ee, ei en eu zou je samen lezen. Zonder trema: geopend, beantwoorden, geoefend, geadresseerd, beoordelen, georganiseerd en geoogst, want eo en ea vormen geen klank. En geuit: begint het werkwoord met ui, dan komt er geen trema. De ui blijft vanzelf bij elkaar.',
    },
    {
      kind: 'choice',
      id: 'geinteresseerd',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'Ik ben erg',
      after: 'in deze vacature.',
      options: ['geinteresseerd', 'geïnteresseerd', 'ge-interesseerd', 'geïntresseerd'],
      answer: 'geïnteresseerd',
      why: 'ge + interesseerd: zonder trema lees je ei. Het trema komt op de i. Een koppelteken kan niet, want ge- is geen los woord. En vergeet de e na de t niet: in-te-res-se-ren.',
    },
    {
      kind: 'fix',
      id: 'ideeen',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Na het overleg met de coördinator heeft het team twee nieuwe ideeen uitgewerkt.',
      wrong: 11,
      answer: 'ideeën',
      why: 'idee + en: drie keer e achter elkaar. Het trema op de laatste e laat zien waar de nieuwe lettergreep begint: i-dee-ën.',
    },
    {
      kind: 'type',
      id: 'strategieen',
      prompt: 'Typ het meervoud van strategie.',
      before: 'Het bedrijf probeert twee nieuwe',
      after: 'om meer klanten te krijgen.',
      hint: 'meervoud',
      answer: 'strategieën',
      why: 'stra-te-GIE: de klemtoon ligt op ie. Dan blijft ie staan en komt -ën erachter, met het trema op de e: strategieën.',
    },
    {
      kind: 'type',
      id: 'beeindigd',
      prompt: 'Typ het voltooid deelwoord.',
      before: 'De gemeente heeft het contract met de schoonmaakfirma',
      after: ', want het werk was slecht.',
      hint: 'be + eindigd',
      answer: 'beëindigd',
      why: 'be + eindigd: zonder trema lees je ee, zoals in been. Het trema komt op de e van eindigd.',
    },
    {
      kind: 'bet',
      id: 'bacterie',
      prompt: 'Wat is het meervoud van bacterie?',
      options: ['bacterieën', 'bacteriën', 'bacterien', 'bacteriëen'],
      answer: 'bacteriën',
      why: 'bac-TE-rie: de klemtoon ligt niet op ie. Dan wordt het -iën, met het trema op de e. bacterieën zou alleen kunnen met klemtoon op ie, zoals bij knieën. Zonder trema lees je ie, en bacteriëen heeft een e te veel.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Niet te veel, niet te weinig',
      panels: [
        {
          text: 'Een trema staat er alleen als je het woord anders verkeerd zou lezen. Veel mensen zetten er juist een te veel. In *geopend*, *beantwoorden*, *geoefend*, *oceaan*, *Italiaan* en *piano* lees je de klinkers vanzelf los, want *eo*, *ea* en *ia* vormen samen geen klank. Daar komt dus geen trema.',
          rule: 'Lees je het woord ook zonder trema goed? Dan geen trema.',
          show: [
            { wrong: 'geöpend', right: 'geopend' },
            { wrong: 'beäntwoorden', right: 'beantwoorden' },
            { wrong: 'Italiäan', right: 'Italiaan' },
          ],
          quiz: {
            q: 'Welk woord is goed geschreven?',
            options: ['geoefend', 'geöefend', 'geoëfend'],
            answer: 'geoefend',
            why: 'ge + oefend: eo is geen klank, dus geen trema. De oe hoort gewoon bij elkaar: oe-fe-nen.',
          },
        },
        {
          text: 'Plak je twee hele woorden aan elkaar en botsen de klinkers, dan gebruik je geen trema maar een koppelteken: *zee-egel*, *auto-ongeluk*, *zonne-energie*. Een trema zet je alleen binnen één woord: bij een uitgang zoals *-en* (*zeeën*) of na *ge-* en *be-* (*beëindigen*). Meer daarover in de les over het koppelteken.',
          rule: 'Twee woorden aan elkaar: koppelteken. Een uitgang of *ge-*/*be-* ervoor: trema.',
          lab: {
            label: 'Tik een combinatie',
            chips: [
              { k: 'zee + en', out: 'zeeën', note: '-en is een uitgang, geen woord: trema.' },
              { k: 'zee + egel', out: 'zee-egel', note: 'egel is een woord: koppelteken.' },
              { k: 'be + eindigen', out: 'beëindigen', note: 'be- is geen los woord: trema.' },
              { k: 'auto + ongeluk', out: 'auto-ongeluk', note: 'Twee woorden: koppelteken.' },
              { k: 'idee + en', out: 'ideeën', note: 'Uitgang: trema.' },
              { k: 'zonne + energie', out: 'zonne-energie', note: 'energie is een woord: koppelteken.' },
            ],
          },
        },
        {
          text: 'Moet je een woord afbreken aan het eind van de regel, precies op de plek van het trema? Dan verdwijnt het trema. Het afbreekstreepje laat al zien dat daar een nieuwe lettergreep begint: *ru-* en op de volgende regel *ine*, *knie-* en dan *en*. Meestal doet je computer of telefoon dit vanzelf. Meer daarover in de les over afbreken.',
          rule: 'Afbreken op de plek van het trema: het trema valt weg (*ru-ine*, *knie-en*).',
          quiz: {
            q: 'Je moet ruïne afbreken aan het eind van de regel. Wat schrijf je?',
            options: ['ru-ine', 'ru-ïne', 'ruï-ne'],
            answer: 'ru-ine',
            why: 'Je breekt af op de lettergreepgrens ru | ine. Het streepje doet nu het werk van het trema, dus de puntjes vallen weg.',
          },
        },
        {
          text: 'Twijfel je? Loop deze vragen langs. 1. Staan er twee klinkers naast elkaar? 2. Kunnen ze samen één klank zijn, zoals *ee*, *oo*, *ie*, *oe*, *eu* of *ui*? Nee: geen trema. 3. Spreek je ze los uit? Nee: geen trema. 4. Zijn het twee hele woorden? Dan een koppelteken. Anders: een trema op de eerste klinker van de nieuwe lettergreep.',
          rule: 'Klank samen + los uitspreken + binnen één woord = trema.',
          lab: {
            label: 'Tik een woord en loop het stappenplan langs',
            chips: [
              { k: 'coordinatie', out: 'coördinatie', note: 'oo is een klank, maar je zegt co-or. Binnen één woord: trema op de tweede o.' },
              { k: 'geopend', out: 'geopend', note: 'eo is geen klank: je bent al klaar bij vraag 2. Geen trema.' },
              { k: 'zeeegel', out: 'zee-egel', note: 'Twee hele woorden: zee en egel. Dus een koppelteken.' },
              { k: 'financiele', out: 'financiële', note: 'ie is een klank, maar hier begint met de e een nieuwe lettergreep: fi-nan-ci-ë-le. Trema op de e.' },
              { k: 'reunie', out: 'reünie', note: 'eu is een klank, maar je zegt re-u-nie. Trema op de u.' },
              { k: 'egoist', out: 'egoïst', note: 'oi lees je samen, maar je zegt e-go-ist. Trema op de i.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-school',
      prompt: 'Lees de mail na',
      intro: 'Hasan mailt de mentor van zijn zoon. Er zitten fouten in met het trema: soms ontbreekt het, soms staat het er onnodig. Tik ze aan.',
      header: { to: 'meneer Bakker', subject: 'Ouderavond' },
      greeting: 'Beste meneer Bakker,',
      tokens: [
        { t: 'Bedankt' },
        { t: 'dat' },
        { t: 'u' },
        { t: 'ons' },
        { t: 'hebt' },
        { t: 'geinformeerd', fix: 'geïnformeerd', why: 'ge + informeerd: zonder trema lees je ei. Trema op de i.' },
        { t: 'over' },
        { t: 'de' },
        { t: 'ouderavond.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'uw' },
        { t: 'mail' },
        { t: 'pas' },
        { t: 'gisteren' },
        { t: 'geöpend,', fix: 'geopend,', why: 'eo is geen klank: je leest het zonder trema al goed. Geen trema.' },
        { t: 'excuses' },
        { t: 'daarvoor.' },
        { t: 'Mijn' },
        { t: 'vrouw' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'hebben' },
        { t: 'wel' },
        { t: 'een' },
        { t: 'paar' },
        { t: 'vragen' },
        { t: 'over' },
        { t: 'de' },
        { t: 'financiele', fix: 'financiële', why: 'financieel + e: ie + e botsen. Trema op de e: financiële.' },
        { t: 'kant' },
        { t: 'van' },
        { t: 'de' },
        { t: 'schoolreis' },
        { t: 'naar' },
        { t: 'Italie.', fix: 'Italië.', why: 'Het land eindigt op -ië: Italië.' },
        { t: 'Kunt' },
        { t: 'u' },
        { t: 'ons' },
        { t: 'de' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: trema op de laatste e.' },
        { t: 'van' },
        { t: 'de' },
        { t: 'coordinator', fix: 'coördinator', why: 'co + ordinator: zonder trema lees je coor, zoals in door. Trema op de tweede o.' },
        { t: 'sturen?' },
        { t: 'Met' },
        { t: 'vriendelijke' },
        { t: 'groet,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Goed gekeken',
        text: 'geïnformeerd, financiële, Italië, ideeën en coördinator misten een trema. In geopend hoort er geen: eo is geen klank.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-reunie',
      prompt: 'Luister en typ de zin precies over.',
      intro: 'Let op hoofdletters, trema’s en de punt. Niet elk woord met twee klinkers naast elkaar krijgt een trema.',
      sentence: 'Na de reünie in België heeft de coördinator onze ideeën beoordeeld en de financiële kant geëvalueerd.',
      right: 'Goed: reünie, België, coördinator, ideeën, financiële en geëvalueerd met een trema. En beoordeeld zonder, want eo is geen klank.',
      wrong:
        'Loop de woorden na: re-ü-nie, Bel-gi-ë (met hoofdletter), co-ör-di-na-tor, i-dee-ën, fi-nan-ci-ë-le en ge-ë-va-lu-eerd. In beoordeeld komt geen trema: eo vormt geen klank.',
    },
    {
      kind: 'sort',
      id: 'klemtoon-ie',
      prompt: 'Ligt de klemtoon op ie? Dat bepaalt het meervoud.',
      buckets: ['klemtoon op ie: -ieën', 'geen klemtoon op ie: -iën of -s'],
      items: [
        { t: 'knie', b: 0 },
        { t: 'melodie', b: 0 },
        { t: 'industrie', b: 0 },
        { t: 'categorie', b: 0 },
        { t: 'kopie', b: 0 },
        { t: 'calorie', b: 0 },
        { t: 'theorie', b: 0 },
        { t: 'allergie', b: 0 },
        { t: 'therapie', b: 0 },
        { t: 'bacterie', b: 1 },
        { t: 'provincie', b: 1 },
        { t: 'familie', b: 1 },
        { t: 'studie', b: 1 },
        { t: 'porie', b: 1 },
        { t: 'serie', b: 1 },
        { t: 'garantie', b: 1 },
      ],
      why: 'knieën, melodieën, industrieën, categorieën, kopieën, calorieën, theorieën, allergieën en therapieën: klemtoon op ie. bacteriën, provinciën (of provincies), families, studies, poriën, series en garanties: de klemtoon ligt eerder in het woord.',
    },
    {
      kind: 'swipe',
      id: 'trema-waar',
      prompt: 'Klopt de schrijfwijze?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in zit.',
      cards: [
        {
          t: 'De diëtist zegt dat ik een strenger dieet moet volgen.',
          ok: true,
          why: 'diëtist: zonder trema lees je ie. In dieet lees je vanzelf di-eet: geen trema nodig.',
        },
        {
          t: 'Wij betalen de eventuële reiskosten terug.',
          ok: false,
          fix: 'eventuële → eventuele',
          why: 'ue is geen klank: je leest e-ven-tu-e-le vanzelf goed. Geen trema. Wel in financiële en reële: daar zou je ie of ee samen lezen.',
        },
        {
          t: 'Het museum is op maandag gesloten.',
          ok: true,
          why: 'Vaste uitzondering: woorden op -eum, zoals museum, jubileum en lyceum, krijgen geen trema.',
        },
        {
          t: 'De bank wil de verbouwing niet financiëren.',
          ok: false,
          fix: 'financiëren → financieren',
          why: 'fi-nan-cie-ren: hier hoort ie bij elkaar, je zegt ie. Geen trema. Wel in financiële en de financiën.',
        },
        {
          t: 'Mijn buren zijn naar Algerië verhuisd.',
          ok: false,
          fix: 'Algerië → Algerije',
          why: 'Niet elk land eindigt op -ië. Algerije eindigt op -ije, net als Turkije en Bulgarije. Daar hoort geen trema.',
        },
        {
          t: 'Ze heeft haar zorgen geuit bij de huisbaas.',
          ok: true,
          why: 'Begint het werkwoord met ui, dan komt er geen trema: geuit. De ui blijft vanzelf bij elkaar.',
        },
        { t: 'We zagen een zeeëgel op het strand.', ok: false, fix: 'zeeëgel → zee-egel', why: 'zee en egel zijn twee woorden: koppelteken, geen trema.' },
        {
          t: 'De krant heeft er duizend nieuwe abonnees bij.',
          ok: true,
          why: 'Niet elk woord op ee krijgt -ën. abonnee krijgt gewoon -s: abonnees. Twijfel je? Zoek het op.',
        },
        { t: 'Het huurcontract is per 1 mei beëindigd.', ok: true, why: 'be + eindigd: zonder trema lees je ee. Trema op de e van eindigen.' },
        {
          t: 'Mijn moeder heeft al jaren last van reüma.',
          ok: false,
          fix: 'reüma → reuma',
          why: 'In reuma zeg je eu als één klank, zoals in neus. Je spreekt de klinkers niet los uit, dus geen trema.',
        },
        { t: 'Ik ben gisteren aan mijn knie geopereerd.', ok: true, why: 'ge + opereerd: eo is geen klank. Geen trema.' },
        {
          t: 'Ons team heeft al drie trofeëen gewonnen.',
          ok: false,
          fix: 'trofeëen → trofeeën',
          why: 'trofee + en: de ee blijft heel, en het trema komt op de e van -en: tro-fee-ën.',
        },
      ],
    },
    {
      kind: 'rewrite',
      id: 'meervoud-knie',
      prompt: 'Zet de hele zin in het meervoud: elk zelfstandig naamwoord en elk werkwoord.',
      source: 'De knie van de speler is gezwollen en de therapie van de fysiotherapeut helpt niet.',
      accept: ['De knieën van de spelers zijn gezwollen en de therapieën van de fysiotherapeuten helpen niet.'],
      why: 'knie wordt knieën en therapie wordt therapieën: klemtoon op ie, dus -ieën. fysiotherapeut krijgt geen trema: eu is daar gewoon de klank eu. En is wordt zijn, helpt wordt helpen.',
    },
    {
      kind: 'choice',
      id: 'australier',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'Mijn nieuwe collega komt uit Australië. Hij is',
      after: '.',
      options: ['Australier', 'Australiër', 'australiër', 'Australieër'],
      answer: 'Australiër',
      why: 'Austra-li-ër: zonder trema lees je ie. Het trema komt op de e, en er komt geen extra e bij. De hoofdletter blijft, want het is een inwoner van een land.',
    },
    {
      kind: 'fix',
      id: 'coordinatie',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Sanne regelt de coordinatie van het project met de Italiaanse en Belgische partners.',
      wrong: 3,
      answer: 'coördinatie',
      why: 'co + ordinatie: zonder trema lees je coor, zoals in door. Trema op de tweede o.',
    },
    {
      kind: 'write',
      id: 'appje-uitje',
      prompt: 'Schrijf je collega’s een bericht over het personeelsuitje.',
      intro: 'Schrijf minstens 25 woorden. Gebruik minstens drie woorden met een trema.',
      minWords: 25,
      must: [
        {
          label: 'Het woord ideeën',
          hint: 'ideeën',
          test: { anyWord: ['ideeën'] },
        },
        {
          label: 'Een werkwoord met ge- of be- en een trema',
          hint: 'geïnteresseerd, geïnformeerd, beëindigen',
          test: { pattern: '(?:^|\\s)(?:ge|be)[ëïü]\\p{L}+', flags: 'iu' },
        },
        {
          label: 'Een land op -ië of een woord op -iële',
          hint: 'België, Italië, financiële',
          test: { pattern: '\\p{L}+i(?:ë|ële)(?!\\p{L})', flags: 'iu' },
        },
      ],
      starters: ['Hoi allemaal, ik heb een paar ideeën voor het uitje.', 'Wie is er geïnteresseerd in', 'Over de financiële kant:'],
      why: 'Check nog één keer elk trema: staat het op de eerste letter van de nieuwe lettergreep? En heb je er geen gezet in woorden als geopend of beantwoorden?',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Trema’s, woorden zonder trema en woorden uit eerdere lessen door elkaar. Hoofdletters tellen mee. Wat je fout doet, komt achteraan terug.',
      caps: true,
      items: [
        {
          q: 'Meervoud van *categorie*',
          before: 'Op het formulier kun je kiezen uit vier',
          after: '.',
          a: 'categorieën',
          why: 'ca-te-go-RIE: de klemtoon ligt op ie. Dan blijft ie staan en komt -ën erachter.',
        },
        {
          q: 'Meervoud van *café*',
          before: 'Op het plein zitten drie',
          after: '.',
          a: 'cafés',
          why: 'Het accent blijft en er komt alleen een s achter: cafés. De é is een accent, geen trema.',
        },
        {
          q: 'Voltooid deelwoord van *uiten*',
          before: 'Tijdens de vergadering heeft de wijkagent veel kritiek',
          after: '.',
          a: 'geuit',
          why: 'Begint het werkwoord met ui, dan komt er geen trema: geuit. De ui blijft vanzelf bij elkaar.',
        },
        {
          q: 'Het land met de hoofdstad Damascus',
          before: 'Onze nieuwe buren komen uit',
          after: '.',
          a: 'Syrië',
          why: 'Sy-ri-ë: zonder trema lees je ie. En een land krijgt een hoofdletter.',
        },
        {
          q: 'Vul *officieel* in, met de goede uitgang',
          before: 'Binnen twee weken krijgt u een',
          after: 'brief van de gemeente.',
          a: 'officiële',
          why: 'officieel + e: met de e begint een nieuwe lettergreep, of-fi-ci-ë-le. Trema op de e.',
        },
        {
          q: 'De vakantie rond Kerstmis',
          before: 'In de',
          after: 'gaan we naar mijn schoonouders.',
          a: 'kerstvakantie',
          why: 'Kerstmis is een feestdag: hoofdletter. Een samenstelling ermee is een gewoon woord: kerstvakantie, klein.',
        },
        {
          q: 'Plak aan elkaar: *ge* + *evalueerd*',
          before: 'Het project wordt na een jaar',
          after: '.',
          a: 'geëvalueerd',
          why: 'ge + evalueerd: zonder trema lees je ee. Trema op de e van evalueren. Verder geen trema: ue is geen klank.',
        },
        {
          q: 'Vul *actueel* in, met de goede uitgang',
          before: 'Op de website staat de',
          after: 'informatie over de staking.',
          a: 'actuele',
          why: 'ue is geen klank: je leest ac-tu-e-le vanzelf goed. Geen trema. Wel in officiële en reële: daar zou je ie of ee samen lezen.',
        },
        {
          q: 'Schrijf het woord dat je hoort: een gebouw met kunst of geschiedenis',
          say: 'museum',
          before: 'Op zondag gaan we met de kinderen naar het',
          after: '.',
          a: 'museum',
          why: 'Vaste uitzondering: woorden op -eum, zoals museum en jubileum, krijgen geen trema.',
        },
        {
          q: 'Het land met de hoofdstad Reykjavik',
          before: 'Mijn zus werkt deze zomer in',
          after: '.',
          a: 'IJsland',
          why: 'Een naam met ij vooraan: allebei groot, IJ.',
        },
        {
          q: 'Iemand die alleen aan zichzelf denkt',
          before: 'Hij deelt nooit iets met anderen. Hij is een echte',
          after: '.',
          a: 'egoïst',
          why: 'e-go-ist: zonder trema lees je oi, zoals in hoi. Trema op de i.',
        },
        {
          q: 'Het werkwoord bij *de financiën*: geld voor iets regelen',
          before: 'Wie gaat de nieuwe sporthal',
          after: '? De gemeente of de club?',
          a: 'financieren',
          why: 'fi-nan-cie-ren: hier hoort ie bij elkaar, je zegt ie. Geen trema. Wel in financiële en financiën, want daar begint met de e een nieuwe lettergreep.',
        },
        {
          q: 'Schrijf het woord dat je hoort: een stuk van een film, en ook in *een … maken* (ruzie maken waar anderen bij zijn)',
          say: 'scène',
          before: 'De laatste',
          after: 'van de film was het spannendst.',
          a: 'scène',
          why: 'scène heeft een vast accent: het streepje naar links op de e.',
        },
        {
          q: 'Meervoud van *porie*',
          before: 'Deze zeep maakt verstopte',
          after: 'weer schoon.',
          a: 'poriën',
          why: 'PO-rie: de klemtoon ligt niet op ie. Dan wordt het -iën: po-ri-ën.',
        },
        {
          q: 'Plak aan elkaar: *ge* + *organiseerd*',
          before: 'De buurtvereniging heeft een straatfeest',
          after: '.',
          a: 'georganiseerd',
          why: 'ge + organiseerd: eo is geen klank, dus je leest het vanzelf goed. Geen trema.',
        },
        {
          q: 'Het getal 1, met nadruk',
          before: 'Er is maar',
          after: 'parkeerplek, niet twee.',
          a: 'één',
          why: 'Het gaat om het getal: één, met een accent op allebei de e’s.',
        },
        {
          q: 'Inwoner van het land met de hoofdstad Jakarta',
          before: 'Mijn schoonvader is een',
          after: '.',
          a: 'Indonesiër',
          why: 'In-do-ne-si-ër: zonder trema lees je ie. Een inwoner krijgt een hoofdletter.',
        },
        {
          q: 'Plak aan elkaar: *ge* + *upload*',
          before: 'Ik heb mijn cv gisteren op de website',
          after: '.',
          a: 'geüpload',
          why: 'ge + upload: zonder trema lees je eu, zoals in neus. Trema op de u.',
        },
        {
          q: 'Je loopbaan in je werk',
          before: 'Ze wil in de zorg',
          after: 'maken.',
          a: 'carrière',
          why: 'carrière heeft een vast accent: het streepje naar links op de e, en dubbel r. Geen trema.',
        },
        {
          q: 'Het land met de hoofdstad Algiers',
          before: 'Mijn collega is geboren in',
          after: '.',
          a: 'Algerije',
          why: 'Niet elk land eindigt op -ië. Algerije eindigt op -ije, net als Turkije. Geen trema.',
        },
        {
          q: 'Bijvoeglijk naamwoord: iemand die te snel alles gelooft (het korte woord, niet *goedgelovig*)',
          before: 'Je gelooft alles wat de verkoper zegt. Je bent veel te',
          after: '.',
          a: 'naïef',
          why: 'na-ïef: zonder trema lees je ai samen. Trema op de i.',
        },
        {
          q: 'De functie van de baas van de gemeente',
          before: 'Morgen opent',
          after: 'Visser het nieuwe zwembad.',
          a: 'burgemeester',
          why: 'Een functie is geen naam: klein, ook vóór de naam.',
        },
        {
          q: 'Plak aan elkaar: *be* + *invloed*',
          before: 'Haar keuze is sterk',
          after: 'door haar ouders.',
          a: 'beïnvloed',
          why: 'be + invloed: zonder trema lees je ei, zoals in klein. Trema op de i.',
        },
        {
          q: 'Schrijf het woord dat je hoort: een feest waar oude klasgenoten elkaar terugzien',
          say: 'reünie',
          a: 'reünie',
          why: 're-u-nie: zonder trema lees je eu, zoals in neus. Trema op de u.',
        },
        {
          q: 'Fijngestampte aardappels met melk en boter (een woord dat Frans klinkt)',
          before: 'Bij de vis eten we',
          after: '.',
          a: 'puree',
          also: ['aardappelpuree'],
          why: 'puree klinkt Frans, maar heeft geen accent en geen trema: puree.',
        },
        {
          q: 'Bijvoeglijk naamwoord bij *Australië*',
          before: 'Ze heeft de',
          after: 'nationaliteit.',
          a: 'Australische',
          why: 'Australisch: hier botsen geen klinkers, dus geen trema. Wel een hoofdletter, want het woord komt van een land.',
        },
        {
          q: 'Vul *reëel* in, met de goede uitgang',
          before: 'Er is een',
          after: 'kans dat de trein vandaag uitvalt.',
          a: 'reële',
          why: 'reëel + e: reële. Het trema blijft staan: re-ë-le.',
        },
        {
          q: 'Je spelt je mailadres aan de telefoon. Hoe heet het teken @?',
          a: 'apenstaartje',
          why: '@ heet apenstaartje. Een . heet punt en een - heet streepje.',
        },
      ],
      done: {
        title: 'Reeks klaar',
        text: 'Je moest elke keer zelf kiezen: trema, accent, hoofdletter of niets. Een trema alleen als twee klinkers samen een klank lijken maar je ze los uitspreekt.',
      },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de nieuwsbrief aan. Typ elk woord helemaal.',
      intro: 'Hoofdletters tellen mee. Kijk goed naar de zin om elk gat heen. In het grijs staat soms een hint.',
      title: 'Nieuwsbrief van de huisartsenpraktijk',
      caps: true,
      text: 'Beste {patiënten|meervoud: wie bij de huisarts komt|pa-ti-ent: zonder trema lees je ie, zoals in niet. Trema op de e: patiënten.},\n\nGraag houden we u {geïnformeerd|ge + informeerd|ge + informeerd: zonder trema lees je ei, zoals in klein. Trema op de i.} over een paar veranderingen. Vanaf {maandag|de dag na het weekend|Een dag schrijf je met een kleine letter, ook midden in een brief.} 3 maart is onze nieuwe praktijk aan de Stationsweg in {IJsselstein|ijssel + stein|Een naam met ij vooraan: allebei groot, IJ.} {geopend|ge + opend|ge + opend: eo is geen klank, dus je leest het vanzelf goed. Geen trema.}. U vindt daar dokter {Van|van (tussenvoegsel)|Dokter is een titel, geen voornaam. Zonder voornaam of voorletter ervoor krijgt het tussenvoegsel een hoofdletter.} Dijk en onze nieuwe {diëtist|beroep, van het woord dieet|di-ë-tist: zonder trema lees je ie, zoals in niet. Trema op de e.}. Hij helpt mensen met {allergieën|meervoud van allergie|al-ler-GIE: de klemtoon ligt op ie. Dan blijft ie staan en komt -ën erachter.} en maakt {diëten|meervoud van dieet|Eén dieet, twee diëten: di-ë-ten. In dieet zelf staat geen trema, want di-eet lees je vanzelf goed.} voor mensen met suikerziekte. Hij spreekt ook {Italiaans|taal van Italië|Een taal krijgt een hoofdletter. Geen trema: ia is geen klank.}. De fysiotherapeut heeft nieuwe {therapieën|meervoud van therapie|the-ra-PIE: de klemtoon ligt op ie, dus -ieën.} voor rugklachten.\n\nEn de {financiële|financieel + e|In fi-nan-ci-ë-le begint met de e een nieuwe lettergreep. Trema op de e.} kant? De meeste behandelingen worden vergoed door uw zorgverzekering. Over {eventuele|eventueel + e|ue is geen klank: je leest e-ven-tu-e-le vanzelf goed. Geen trema.} extra kosten hoort u altijd vooraf.\n\nLet op: met {Pasen|feestdag in het voorjaar, met eieren zoeken|Een feestdag is een naam: hoofdletter.} is de praktijk dicht. Op vrijdag werkt er maar {één|het getal 1|Het gaat om het getal: één assistente in plaats van twee. Dan schrijf je één, met accenten.} assistente in plaats van twee. U moet dan soms wat langer wachten.\n\nWilt u ons {beoordelen|be + oordelen|eo is geen klank: geen trema.}? Vul dan de vragenlijst op onze website in. Uw {ideeën|meervoud van idee|idee + en: drie keer e. Trema op de laatste e: i-dee-ën.} zijn van harte welkom!\n\nMet vriendelijke groet,\nHuisartsenpraktijk De Linde',
      why: 'Trema: patiënten, geïnformeerd, diëtist, allergieën, diëten, therapieën, financiële en ideeën. Geen trema: geopend, eventuele, beoordelen en Italiaans, want eo, ue en ia vormen geen klank. Uit eerdere lessen: maandag klein, Pasen, IJsselstein en Italiaans groot, dokter Van Dijk met een hoofdletter op het tussenvoegsel, en één met accenten voor het getal.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen over oude buren. Hoofdletters, trema’s en leestekens tellen mee.',
      title: 'Bezoek uit Australië',
      sentences: [
        'Onze oude buren zijn vorig jaar naar Australië geëmigreerd.',
        'Met Kerstmis komen ze terug voor een reünie in België.',
        'We zijn erg geïnteresseerd in hun ideeën over het leven daar.',
        'De coördinator van de reünie heeft de financiële kant goed geregeld.',
        'Hun dochter werkt als diëtist en geeft patiënten advies over hun dieet.',
        'Op maandagavond heb ik hun mail geopend en meteen beantwoord.',
      ],
      right:
        'Alles goed: elk trema op de goede plek, en geen trema in dieet, geopend en beantwoord. Ook Kerstmis, Australië en België met een hoofdletter, en maandagavond klein.',
      wrong:
        'Kijk de rode woorden na. Trema: Australië, geëmigreerd, reünie, België, geïnteresseerd, ideeën, coördinator, financiële, diëtist en patiënten. Geen trema: dieet, geopend en beantwoord. Kerstmis is een feestdag (groot), maandagavond niet (klein).',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'Karin de Boer', subject: 'Cursus in maart' },
      greeting: 'Beste Karin,',
      signoff: 'Met vriendelijke groet,\nHasan',
      tokens: [
        { t: 'Bedankt' },
        { t: 'voor' },
        { t: 'je' },
        { t: 'mail.' },
        { t: 'Ik' },
        { t: 'ben' },
        { t: 'erg' },
        { t: 'geinteresseerd', fix: 'geïnteresseerd', why: 'ge + interesseerd: zonder trema lees je ei, zoals in klein. Trema op de i.' },
        { t: 'in' },
        { t: 'de' },
        { t: 'cursus' },
        { t: 'over' },
        { t: 'projectleiding.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'je' },
        { t: 'bijlage' },
        { t: 'gisteren' },
        { t: 'geöpend', fix: 'geopend', why: 'eo is geen klank: je leest ge-o-pend vanzelf goed. Geen trema.' },
        { t: 'en' },
        { t: 'de' },
        { t: 'twee' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: trema op de laatste e, i-dee-ën.' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'planning' },
        { t: 'gelezen.' },
        { t: 'Over' },
        { t: 'de' },
        { t: 'financiele', fix: 'financiële', why: 'financieel + e: met de e begint een nieuwe lettergreep. Trema op de e.' },
        { t: 'kant' },
        { t: 'heb' },
        { t: 'ik' },
        { t: 'nog' },
        { t: 'een' },
        { t: 'vraag:' },
        { t: 'wie' },
        { t: 'gaat' },
        { t: 'de' },
        { t: 'reis' },
        { t: 'financieren?', trap: 'Goed: in fi-nan-cie-ren hoort ie bij elkaar. Geen trema; dat staat alleen in financiële en financiën.' },
        { t: 'De' },
        { t: 'cursus' },
        { t: 'is' },
        { t: 'in' },
        { t: 'Rome,' },
        { t: 'in' },
        { t: 'Italie,', fix: 'Italië,', why: 'Land op -ië: zonder trema lees je ie. Italië.' },
        { t: 'vlak' },
        { t: 'bij' },
        { t: 'een' },
        { t: 'museum.', trap: 'Goed: woorden op -eum, zoals museum en jubileum, krijgen nooit een trema.' },
        { t: 'Mijn' },
        { t: 'Italiaanse', trap: 'Goed: ia is geen klank, dus geen trema. En een hoofdletter, want het woord komt van een land.' },
        { t: 'collega' },
        { t: 'heeft' },
        { t: 'al' },
        { t: 'zorgen' },
        { t: 'geuit', trap: 'Goed: begint het werkwoord met ui, dan komt er geen trema. De ui blijft vanzelf bij elkaar.' },
        { t: 'over' },
        { t: 'de' },
        { t: 'eventuële', fix: 'eventuele', why: 'ue is geen klank: je leest e-ven-tu-e-le vanzelf goed. Geen trema.' },
        { t: 'hotelkosten.' },
        { t: 'Kan' },
        { t: 'de' },
        { t: 'coordinator', fix: 'coördinator', why: 'co + ordinator: zonder trema lees je oo, zoals in door. Trema op de tweede o.' },
        { t: 'ons' },
        { t: 'een' },
        { t: 'lijst' },
        { t: 'met' },
        { t: 'alle' },
        { t: 'categorieen', fix: 'categorieën', why: 'ca-te-go-RIE: klemtoon op ie, dus -ieën. Het trema komt op de e van -en.' },
        { t: 'van' },
        { t: 'kosten' },
        { t: 'sturen?' },
        { t: 'Dan' },
        { t: 'kan' },
        { t: 'ik' },
        { t: 'op' },
        { t: 'Dinsdag', fix: 'dinsdag', why: 'Een dag schrijf je met een kleine letter, ook midden in een mail.' },
        { t: 'een' },
        { t: 'voorstel' },
        { t: 'doen' },
        { t: 'aan' },
        { t: 'de' },
        { t: 'afdeling.' },
      ],
      done: {
        title: 'Mail nagekeken',
        text: 'Fouten: geïnteresseerd, geopend, ideeën, financiële, Italië, eventuele, coördinator, categorieën en dinsdag. Goed waren financieren, museum, Italiaanse en geuit: daar hoort geen trema.',
      },
    },
  ],
};
