import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": de apostrof in het meervoud, bij bezit, bij weglating, bij afkortingen en in het verkleinwoord. */
export const LES_L25: LessonInput = {
  id: 'l25',
  stage: 'regels',
  domain: 'orth',
  also: ['morf'],
  title: 'De apostrof: auto’s en Anna’s fiets',
  skill: 'Spelling',
  icon: '’s',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Een klein teken dat een klank beschermt',
      panels: [
        {
          text: 'Eindigt een woord op *a*, *i*, *o*, *u* of *y*, dan krijgt het meervoud *’s*. Zonder apostrof zou je de klinker kort lezen: *autos* lees je als *au-tos*, met de korte *o* van *pot*. De apostrof houdt de klank lang: *auto’s*. Zo ook *pizza’s*, *pagina’s*, *ski’s*, *taxi’s*, *foto’s*, *euro’s*, *menu’s*, *paraplu’s*, *baby’s* en *hobby’s*.',
          rule: 'Woord op *a*, *i*, *o*, *u* of *y*: meervoud met *’s* (*auto’s*, *menu’s*, *baby’s*).',
          show: [
            { wrong: 'autos', right: 'auto’s' },
            { wrong: 'menus', right: 'menu’s' },
            { wrong: 'babys', right: 'baby’s' },
          ],
          build: {
            before: 'Op het plein staan drie',
            stem: 'taxi',
            endings: ['s', '’s', 'en', 'es'],
            answer: '’s',
            note: 'taxi’s. Zonder apostrof lees je ta-xis, met een korte i.',
          },
        },
        {
          text: 'Na andere klanken is de apostrof niet nodig, want daar lees je het meervoud vanzelf goed. Na een *é*: *cafés*, *coupés*. Na een doffe *e*: *tantes*, *garages*. Na *eau*: *cadeaus*, *bureaus*. En woorden op *ee* krijgen *-ën*: *zeeën*, *ideeën*. Let op: *collega* eindigt gewoon op een *a*, dus *collega’s*.',
          rule: 'Geen apostrof na *é* (*cafés*), na een doffe *e* (*tantes*) en na *eau* (*cadeaus*).',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'foto', out: 'foto’s', note: 'Eindigt op een o: apostrof.' },
              { k: 'café', out: 'cafés', note: 'De é blijft ook zonder apostrof lang: gewoon -s.' },
              { k: 'tante', out: 'tantes', note: 'Doffe e aan het eind: gewoon -s.' },
              { k: 'cadeau', out: 'cadeaus', note: 'eau klinkt als oo, maar je ziet geen losse o: gewoon -s.' },
              { k: 'bureau', out: 'bureaus', note: 'Net als cadeau: -s zonder apostrof.' },
              { k: 'idee', out: 'ideeën', note: 'Woord op ee: -ën met trema, geen apostrof.' },
            ],
          },
        },
        {
          text: 'Bij een naam zet je een *s* om te laten zien van wie iets is: *Jans fiets*, *Hasans auto*, *Sannes jas*, *Renés boek*. Een apostrof komt er alleen in twee gevallen. Eindigt de naam op *a*, *i*, *o*, *u* of *y*, dan schrijf je *’s*: *Anna’s fiets*, *Hugo’s jas*, *Willy’s kamer*. Eindigt de naam op een *s*, *x* of *z*, dan zet je alleen een apostrof: *Klaas’ auto*, *Max’ jas*, *Thomas’ telefoon*, *Inez’ tas*.',
          rule: 'Bezit bij een naam: gewoon *s* (*Jans*). Op *a, i, o, u, y*: *’s* (*Anna’s*). Op *s, x, z*: alleen *’* (*Max’*).',
          paradigm: {
            q: 'Van wie is de fiets?',
            cols: ['… fiets'],
            rows: [
              { label: 'Anna', cells: [{ fill: 'Anna’s', hint: 'Eindigt op a: ’s.' }] },
              { label: 'Hugo', cells: [{ fill: 'Hugo’s' }] },
              { label: 'Jan', cells: [{ fill: 'Jans', hint: 'Eindigt op een medeklinker: gewoon s, geen apostrof.' }] },
              { label: 'Sanne', cells: [{ fill: 'Sannes', hint: 'Doffe e aan het eind: gewoon s.' }] },
              { label: 'Max', cells: [{ fill: 'Max’', hint: 'Eindigt op x: alleen een apostrof.' }] },
              { label: 'Klaas', cells: [{ fill: 'Klaas’', hint: 'Eindigt op s: alleen een apostrof.' }] },
            ],
            extra: ['Jan’s', 'Sanne’s', 'Maxs', 'Klaas’s'],
            note: 'Anna’s en Hugo’s: lange klank aan het eind. Jans en Sannes: gewoon een s. Max’ en Klaas’: er staat al een s-klank, dus alleen de apostrof.',
          },
        },
        {
          text: 'Een apostrof laat ook zien dat er letters weg zijn. *’s ochtends*, *’s middags*, *’s avonds* en *’s nachts* betekenen: in de ochtend, middag, avond of nacht. Ook *’s zomers*, *’s winters* en *’s maandags*. Verder: *zo’n* (zo een), *m’n* (mijn), *z’n* (zijn), *d’r* (haar) en *’t* (het). Begint een zin met *’s* of *’t*, dan krijgt het woord erna de hoofdletter: *’s Avonds werk ik.*',
          rule: 'Weggelaten letters: apostrof (*’s avonds*, *zo’n*, *m’n*). Aan het begin van de zin krijgt het volgende woord de hoofdletter.',
          lab: {
            label: 'Tik een korte vorm',
            chips: [
              { k: 'zo’n', out: 'Ik wil ook zo’n jas.', note: 'Van zo een. Zonder apostrof staat er zon, en dat is de zon aan de hemel.' },
              { k: 'm’n', out: 'Ik ben m’n sleutels kwijt.', note: 'Van mijn. Prima in een appje; in een formele brief schrijf je mijn.' },
              { k: 'z’n', out: 'Hij pakt z’n tas.', note: 'Van zijn. Ook informeel.' },
              { k: '’s avonds', out: 'Ik werk ’s avonds.', note: 'Midden in de zin: kleine s, kleine a.' },
              { k: '’s Avonds', out: '’s Avonds werk ik.', note: 'Begin van de zin: de ’s blijft klein, Avonds krijgt de hoofdletter.' },
            ],
          },
        },
        {
          text: 'Bij een afkorting die je letter voor letter uitspreekt, zet je een apostrof voor de uitgang: *tv’s*, *cd’s*, *wc’s*, *pc’s*, *sms’je*, *A4’tje*. Ook in het verkleinwoord van woorden op *i* en *y*: *ski’tje*, *taxi’tje*, *baby’tje*, *hobby’tje*. Maar woorden op *a*, *o* en *u* krijgen in het verkleinwoord een extra klinker, zonder apostrof: *autootje*, *fotootje*, *omaatje*, *menuutje*.',
          rule: 'Afkorting + uitgang: apostrof (*tv’s*). Verkleinwoord: *i* en *y* met apostrof (*ski’tje*), *a, o, u* dubbel (*autootje*).',
          build: {
            before: 'Kijk, wat een klein',
            stem: 'auto',
            endings: ['’tje', 'tje', 'otje', '-tje'],
            answer: 'otje',
            note: 'autootje. Bij a, o en u verdubbel je de klinker: autootje, omaatje, menuutje. Alleen bij i en y komt er een apostrof: ski’tje, baby’tje.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'meervoud',
      prompt: 'Hoe maak je het meervoud?',
      buckets: ['met ’s', 'met -s, zonder apostrof', 'met -ën'],
      items: [
        { t: 'auto', b: 0 },
        { t: 'menu', b: 0 },
        { t: 'baby', b: 0 },
        { t: 'pagina', b: 0 },
        { t: 'ski', b: 0 },
        { t: 'café', b: 1 },
        { t: 'tante', b: 1 },
        { t: 'cadeau', b: 1 },
        { t: 'garage', b: 1 },
        { t: 'bureau', b: 1 },
        { t: 'idee', b: 2 },
        { t: 'zee', b: 2 },
      ],
      why: 'auto’s, menu’s, baby’s, pagina’s en ski’s: a, i, o, u of y aan het eind. cafés, tantes, cadeaus, garages en bureaus: de klank blijft vanzelf goed. ideeën en zeeën: ee + -ën.',
    },
    {
      kind: 'choice',
      id: 'paraplu',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'Het regent hard. Gelukkig hebben we twee',
      after: 'bij ons.',
      options: ['paraplus', 'paraplu’s', 'parapluus', 'paraplu-s'],
      answer: 'paraplu’s',
      why: 'paraplu eindigt op een u. Meervoud met ’s, anders lees je pa-ra-plus met een korte u.',
    },
    {
      kind: 'type',
      id: 'max-jas',
      prompt: 'Schrijf het bezit kort op: de jas van Max.',
      before: 'Dit is',
      after: 'jas.',
      hint: 'Max…',
      answer: 'Max’',
      why: 'Max eindigt op x, een s-klank. Dan zet je alleen een apostrof: Max’ jas.',
    },
    {
      kind: 'type',
      id: 'autootje',
      prompt: 'Typ het verkleinwoord van auto.',
      before: 'Mijn zoontje speelt met een rood',
      after: '.',
      hint: 'verkleinwoord van auto',
      answer: 'autootje',
      why: 'Woord op o: de o wordt verdubbeld en -tje komt erachter. Geen apostrof: autootje.',
    },
    {
      kind: 'swipe',
      id: 'apostrof-waar',
      prompt: 'Klopt de schrijfwijze?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'We hebben drie pizza’s besteld.', ok: true, why: 'pizza eindigt op a: ’s.' },
        { t: 'Peter’s fiets staat voor de deur.', ok: false, fix: 'Peter’s → Peters', why: 'Peter eindigt op een medeklinker: gewoon s, zonder apostrof.' },
        { t: 'In deze straat zitten veel café’s.', ok: false, fix: 'café’s → cafés', why: 'Na een é: gewoon -s.' },
        { t: 'Ik heb al mijn cadeaus ingepakt.', ok: true, why: 'Na eau: -s zonder apostrof.' },
        { t: 'Sanne’s moeder werkt in het ziekenhuis.', ok: false, fix: 'Sanne’s → Sannes', why: 'Sanne eindigt op een doffe e: gewoon s.' },
        { t: 'De baby’s slapen allebei.', ok: true, why: 'baby eindigt op y: ’s.' },
        { t: 'Zet je appels in de koelkast?', ok: true, why: 'appel eindigt op een medeklinker: gewoon -s.' },
        { t: 'Hoeveel euros kost dat?', ok: false, fix: 'euros → euro’s', why: 'euro eindigt op o: ’s.' },
      ],
    },
    {
      kind: 'bet',
      id: 'cadeaus',
      prompt: 'Wat is het meervoud van cadeau?',
      options: ['cadeau’s', 'cadeaus', 'cadeauen'],
      answer: 'cadeaus',
      why: 'Na eau komt gewoon -s, zonder apostrof. eau klinkt als oo, maar er staat geen losse o aan het eind. Hetzelfde bij bureaus en niveaus.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Waar het vaak misgaat',
      panels: [
        {
          text: 'De grootste fout: een apostrof waar hij niet hoort. Woorden die op een medeklinker eindigen, krijgen gewoon *-s* of *-en*, nooit *’s*: *appels*, *tafels*, *jongens*, *broodjes*. Ook een naam op een medeklinker: *Peters fiets*, *Ahmeds huis*, *Hasans auto*. En na *é* en *eau* ook niet: *cafés*, *cadeaus*.',
          rule: 'Eindigt het woord op een medeklinker, een *é* of *eau*? Geen apostrof.',
          show: [
            { wrong: 'appel’s', right: 'appels' },
            { wrong: 'Peter’s fiets', right: 'Peters fiets' },
            { wrong: 'café’s', right: 'cafés' },
            { wrong: 'cadeau’s', right: 'cadeaus' },
          ],
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Ahmeds broer verkoopt broodjes.', 'Ahmed’s broer verkoopt broodjes.', 'Ahmeds broer verkoopt broodje’s.'],
            answer: 'Ahmeds broer verkoopt broodjes.',
            why: 'Ahmed en broodje eindigen niet op a, i, o, u of y. Dus gewoon s, zonder apostrof.',
          },
        },
        {
          text: 'Bezit bij een naam in drie vragen. 1. Eindigt de naam op *a*, *i*, *o*, *u* of *y*? Dan *’s*: *Fatima’s*, *Mo’s*, *Willy’s*. 2. Eindigt de naam op *s*, *x* of *z*? Dan alleen *’*: *Joris’*, *Max’*, *Inez’*. 3. Iets anders, ook een doffe *e* of een *é*? Dan gewoon *s*: *Jans*, *Sannes*, *Renés*.',
          rule: 'Naam op *a, i, o, u, y*: *’s*. Op *s, x, z*: *’*. Anders: *s*.',
          mark: {
            q: 'Tik de vormen die goed geschreven zijn',
            sentence: 'Fatima’s Peter’s Mo’s Hasans Max’ Sanne’s Joris’ Renés',
            targets: [0, 2, 3, 4, 6, 7],
            note: 'Goed: Fatima’s, Mo’s, Hasans, Max’, Joris’ en Renés. Fout: Peter’s (moet Peters) en Sanne’s (moet Sannes).',
          },
        },
        {
          text: 'Afkorting of samenstelling? Plak je een uitgang aan een afkorting, dan komt er een apostrof: *twee tv’s*, *een sms’je*, *drie cd’s*. Maak je er een nieuw woord mee, dan komt er een koppelteken: *tv-programma*, *cd-speler*, *A4-papier*. Dat leer je in de les over het koppelteken.',
          rule: 'Afkorting + uitgang (*-s*, *-je*, *-tje*): apostrof. Afkorting + woord: koppelteken.',
          quiz: {
            q: 'Welke schrijfwijze is goed?',
            options: ['twee A4’tjes en een tv-gids', 'twee A4-tjes en een tv’gids', 'twee A4tjes en een tvgids'],
            answer: 'twee A4’tjes en een tv-gids',
            why: '-tjes is een uitgang: apostrof. gids is een woord: koppelteken.',
          },
        },
        {
          text: 'Let op de kleine verschillen. *zo’n* (zo een) is iets anders dan *zon* (de zon). Vergeet ook de apostrof in *’s avonds* niet: *s avonds* is fout. En in een formele brief of mail schrijf je liever *mijn*, *zijn* en *het* voluit: *m’n*, *z’n* en *’t* passen in een appje, niet in een sollicitatiebrief. Begin je een zin met *’s*, dan krijgt het tweede woord de hoofdletter: *’s Morgens*, nooit *’S morgens*.',
          rule: 'Formeel: *mijn*, *zijn*, *het*. Begin van de zin: *’s Morgens*.',
          show: [
            { wrong: 'zon fiets', right: 'zo’n fiets' },
            { wrong: '’S morgens', right: '’s Morgens' },
            { wrong: 's avonds', right: '’s avonds' },
          ],
          quiz: {
            q: 'Je schrijft een sollicitatiebrief. Welke zin past?',
            options: ['Ik heb mijn diploma in juni gehaald.', 'Ik heb m’n diploma in juni gehaald.', 'Ik heb mn diploma in juni gehaald.'],
            answer: 'Ik heb mijn diploma in juni gehaald.',
            why: 'm’n is goed gespeld, maar informeel. In een brief schrijf je mijn voluit. mn is altijd fout.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje-collega',
      prompt: 'Lees het appje na',
      intro: 'Hasan appt zijn collega Ruben. Er zitten vijf fouten in met de apostrof. Tik ze aan.',
      header: { to: 'Ruben' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Ruben,' },
        { t: 'kun' },
        { t: 'je' },
        { t: 'morgen' },
        { t: 's', fix: '’s', why: '’s ochtends: de apostrof laat zien dat er letters weg zijn.' },
        { t: 'ochtends' },
        { t: 'mijn' },
        { t: 'dienst' },
        { t: 'overnemen?' },
        { t: 'Ik' },
        { t: 'moet' },
        { t: 'met' },
        { t: 'de' },
        { t: 'auto' },
        { t: 'naar' },
        { t: 'de' },
        { t: 'garage.' },
        { t: 'Daarna' },
        { t: 'haal' },
        { t: 'ik' },
        { t: 'de' },
        { t: 'pizzas', fix: 'pizza’s', why: 'pizza eindigt op a: meervoud met ’s.' },
        { t: 'voor' },
        { t: 'het' },
        { t: 'afscheid' },
        { t: 'van' },
        { t: 'Joris.' },
        { t: 'Ik' },
        { t: 'neem' },
        { t: 'ook' },
        { t: 'Anna’s' },
        { t: 'laptop' },
        { t: 'mee,' },
        { t: 'en' },
        { t: 'de' },
        { t: 'fotos', fix: 'foto’s', why: 'foto eindigt op o: meervoud met ’s.' },
        { t: 'van' },
        { t: 'het' },
        { t: 'uitje.' },
        { t: 'Maxs', fix: 'Max’', why: 'Max eindigt op x: alleen een apostrof.' },
        { t: 'cadeau' },
        { t: 'ligt' },
        { t: 'nog' },
        { t: 'in' },
        { t: 'zon', fix: 'zo’n', why: 'zo’n komt van zo een. zon is de zon aan de hemel.' },
        { t: 'grote' },
        { t: 'tas' },
        { t: 'op' },
        { t: 'het' },
        { t: 'bureau.' },
        { t: 'Groetjes,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Vijf apostrofs terug op hun plek',
        text: '’s ochtends, pizza’s, foto’s, Max’ en zo’n. Anna’s, cadeau en bureau waren al goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-avonds',
      prompt: 'Luister en typ de zin precies over.',
      intro: 'Let op de apostrofs en de hoofdletters.',
      sentence: '’s Avonds eten we pizza’s bij Anna’s ouders.',
      right: 'Goed: ’s Avonds (hoofdletter op het tweede woord), pizza’s (meervoud op a) en Anna’s (bezit, naam op a).',
      wrong: 'Kijk naar de drie apostrofs. De zin begint met ’s, dus Avonds krijgt de hoofdletter. pizza’s en Anna’s eindigen op een a: ’s.',
    },
    {
      kind: 'type',
      id: 'tvs',
      prompt: 'Typ het meervoud van tv.',
      before: 'In de winkel hangen wel twintig',
      after: 'aan de muur.',
      hint: 'meervoud van tv',
      answer: 'tv’s',
      why: 'tv is een afkorting die je letter voor letter uitspreekt. Een uitgang erachter: apostrof. tv’s.',
    },
    {
      kind: 'rewrite',
      id: 'apostrofs-terug',
      prompt: 'Zet de apostrofs en de hoofdletter goed.',
      source: 's zomers maakt Hugos zus fotos van de cafés.',
      accept: ['’s Zomers maakt Hugo’s zus foto’s van de cafés.'],
      why: '’s Zomers: weggelaten letters, en de hoofdletter op het tweede woord. Hugo’s: naam op o. foto’s: meervoud op o. cafés blijft zonder apostrof.',
    },
    {
      kind: 'sort',
      id: 'bezit-namen',
      prompt: 'Hoe schrijf je het bezit? (… telefoon)',
      buckets: ['’s', 'alleen ’', 'gewoon s'],
      items: [
        { t: 'Anna', b: 0 },
        { t: 'Hugo', b: 0 },
        { t: 'Willy', b: 0 },
        { t: 'Fatima', b: 0 },
        { t: 'Max', b: 1 },
        { t: 'Klaas', b: 1 },
        { t: 'Thomas', b: 1 },
        { t: 'Inez', b: 1 },
        { t: 'Jan', b: 2 },
        { t: 'Sanne', b: 2 },
        { t: 'Hasan', b: 2 },
        { t: 'René', b: 2 },
      ],
      why: 'Anna’s, Hugo’s, Willy’s en Fatima’s: naam op a, o of y. Max’, Klaas’, Thomas’ en Inez’: naam op x, s of z. Jans, Sannes, Hasans en Renés: gewoon s, ook na een doffe e of een é.',
    },
    {
      kind: 'choice',
      id: 'taxitje',
      prompt: 'Kies het goede verkleinwoord.',
      before: 'We namen een klein',
      after: 'naar het station.',
      options: ['taxitje', 'taxi’tje', 'taxiitje', 'taxi-tje'],
      answer: 'taxi’tje',
      why: 'Woord op i: in het verkleinwoord een apostrof, net als ski’tje en baby’tje. Alleen a, o en u worden verdubbeld (autootje).',
    },
    {
      kind: 'bet',
      id: 'smsjes',
      prompt: 'Je hebt twee korte berichtjes gekregen. Hoe schrijf je dat?',
      options: ['twee smsjes', 'twee sms’jes', 'twee sms-jes'],
      answer: 'twee sms’jes',
      why: 'sms is een afkorting. Een uitgang zoals -je of -jes krijgt een apostrof: sms’je, sms’jes.',
    },
    {
      kind: 'write',
      id: 'appje-vriend',
      prompt: 'App een vriend over je weekend.',
      intro: 'Schrijf minstens 25 woorden. Gebruik ’s ochtends, ’s middags of ’s avonds, een meervoud met ’s en een naam met bezit.',
      minWords: 25,
      must: [
        {
          label: '’s ochtends, ’s middags, ’s avonds of ’s nachts',
          hint: '’s avonds',
          test: { pattern: '[’\']s\\s+(?:ochtends|middags|avonds|nachts|morgens)', flags: 'iu' },
        },
        {
          label: 'Een meervoud met ’s',
          hint: 'pizza’s, foto’s, auto’s',
          test: { pattern: '\\p{L}+[aiouy][’\']s(?!\\p{L})', flags: 'iu' },
        },
        {
          label: 'Een naam met bezit',
          hint: 'Anna’s fiets, Jans huis, Max’ jas',
          test: { pattern: '\\p{Lu}\\p{Ll}+(?:[aiouy][’\']s|[sxz][’\'](?!\\p{L})|[^aiouysxz\\s]s)\\s+\\p{Ll}+', flags: 'u' },
        },
      ],
      starters: ['Hoi! Zaterdag ’s ochtends heb ik', 'We hebben veel foto’s gemaakt', 'In Anna’s tuin'],
      why: 'Lees je appje nog één keer na: staat er alleen een apostrof na a, i, o, u of y, na een afkorting en waar letters weg zijn?',
    },
  ],
};
