import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": de apostrof in het meervoud, bij bezit, bij weglating, bij afkortingen en in het verkleinwoord. */
export const LES_L25: LessonInput = {
  id: 'l25',
  stage: 'regels',
  domain: 'orth',
  also: ['morf'],
  title: 'De apostrof: auto’s en Anna’s fiets',
  skill: 'Spelling',
  icon: '’s',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Een klein teken dat een klank beschermt',
      panels: [
        {
          text: 'Eindigt een woord op *a*, *i*, *o*, *u* of *y*, dan krijgt het meervoud *’s*. Zonder apostrof zou je de klinker kort lezen: *autos* lees je als *au-tos*, met de korte *o* van *pot*. De apostrof houdt de klank lang: *auto’s*. Zo ook *pizza’s*, *pagina’s*, *ski’s*, *taxi’s*, *foto’s*, *euro’s*, *menu’s*, *paraplu’s*, *baby’s* en *hobby’s*.',
          rule: 'Woord op *a*, *i*, *o*, *u* of *y*: meervoud met *’s* (*auto’s*, *menu’s*, *baby’s*).',
          show: [
            { wrong: 'autos', right: 'auto’s' },
            { wrong: 'menus', right: 'menu’s' },
            { wrong: 'babys', right: 'baby’s' },
          ],
          build: {
            before: 'Op het plein staan drie',
            stem: 'taxi',
            endings: ['s', '’s', 'en', 'es'],
            answer: '’s',
            note: 'taxi’s. Zonder apostrof lees je ta-xis, met een korte i.',
          },
        },
        {
          text: 'Na andere klanken is de apostrof niet nodig, want daar lees je het meervoud vanzelf goed. Na een *é*: *cafés*, *coupés*. Na een doffe *e*: *tantes*, *garages*. Na *eau*: *cadeaus*, *bureaus*. En veel woorden op *ee* krijgen *-ën*: *zeeën*, *ideeën*. Let op: *collega* eindigt gewoon op een *a*, dus *collega’s* (*collegae* mag ook).',
          rule: 'Geen apostrof na *é* (*cafés*), na een doffe *e* (*tantes*) en na *eau* (*cadeaus*).',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'foto', out: 'foto’s', note: 'Eindigt op een o: apostrof.' },
              { k: 'café', out: 'cafés', note: 'De é blijft ook zonder apostrof lang: gewoon -s.' },
              { k: 'tante', out: 'tantes', note: 'Doffe e aan het eind: gewoon -s.' },
              { k: 'cadeau', out: 'cadeaus', note: 'eau klinkt als oo, maar je ziet geen losse o: gewoon -s.' },
              { k: 'bureau', out: 'bureaus', note: 'Net als cadeau: -s zonder apostrof.' },
              { k: 'idee', out: 'ideeën', note: 'Woord op ee: -ën met trema, geen apostrof.' },
            ],
          },
        },
        {
          text: 'Bij een naam zet je een *s* om te laten zien van wie iets is: *Jans fiets*, *Hasans auto*, *Sannes jas*, *Renés boek*. Een apostrof komt er alleen in twee gevallen. Eindigt de naam op *a*, *i*, *o*, *u* of *y*, dan schrijf je *’s*: *Anna’s fiets*, *Hugo’s jas*, *Willy’s kamer*. Eindigt de naam op een *s*, *x* of *z*, dan zet je alleen een apostrof: *Klaas’ auto*, *Max’ jas*, *Thomas’ telefoon*, *Inez’ tas*.',
          rule: 'Bezit bij een naam: gewoon *s* (*Jans*). Op *a, i, o, u, y*: *’s* (*Anna’s*). Op *s, x, z*: alleen *’* (*Max’*).',
          paradigm: {
            q: 'Van wie is de fiets?',
            cols: ['… fiets'],
            rows: [
              { label: 'Anna', cells: [{ fill: 'Anna’s', hint: 'Eindigt op a: ’s.' }] },
              { label: 'Hugo', cells: [{ fill: 'Hugo’s' }] },
              { label: 'Jan', cells: [{ fill: 'Jans', hint: 'Eindigt op een medeklinker: gewoon s, geen apostrof.' }] },
              { label: 'Sanne', cells: [{ fill: 'Sannes', hint: 'Doffe e aan het eind: gewoon s.' }] },
              { label: 'Max', cells: [{ fill: 'Max’', hint: 'Eindigt op x: alleen een apostrof.' }] },
              { label: 'Klaas', cells: [{ fill: 'Klaas’', hint: 'Eindigt op s: alleen een apostrof.' }] },
            ],
            extra: ['Jan’s', 'Sanne’s', 'Maxs', 'Klaas’s'],
            note: 'Anna’s en Hugo’s: lange klank aan het eind. Jans en Sannes: gewoon een s. Max’ en Klaas’: er staat al een s-klank, dus alleen de apostrof.',
          },
        },
        {
          text: 'Een apostrof laat ook zien dat er letters weg zijn. *’s ochtends*, *’s middags*, *’s avonds* en *’s nachts* betekenen: in de ochtend, middag, avond of nacht. Ook *’s zomers*, *’s winters* en *’s maandags*. Verder: *zo’n* (zo een), *m’n* (mijn), *z’n* (zijn), *d’r* (haar) en *’t* (het). Begint een zin met *’s* of *’t*, dan krijgt het woord erna de hoofdletter: *’s Avonds werk ik.*',
          rule: 'Weggelaten letters: apostrof (*’s avonds*, *zo’n*, *m’n*). Aan het begin van de zin krijgt het volgende woord de hoofdletter.',
          lab: {
            label: 'Tik een korte vorm',
            chips: [
              { k: 'zo’n', out: 'Ik wil ook zo’n jas.', note: 'Van zo een. Zonder apostrof staat er zon, en dat is de zon aan de hemel.' },
              { k: 'm’n', out: 'Ik ben m’n sleutels kwijt.', note: 'Van mijn. Prima in een appje; in een formele brief schrijf je mijn.' },
              { k: 'z’n', out: 'Hij pakt z’n tas.', note: 'Van zijn. Ook informeel.' },
              { k: '’s avonds', out: 'Ik werk ’s avonds.', note: 'Midden in de zin: kleine s, kleine a.' },
              { k: '’s Avonds', out: '’s Avonds werk ik.', note: 'Begin van de zin: de ’s blijft klein, Avonds krijgt de hoofdletter.' },
            ],
          },
        },
        {
          text: 'Bij een afkorting die je letter voor letter uitspreekt, zet je een apostrof voor de uitgang: *tv’s*, *cd’s*, *wc’s*, *pc’s*, *sms’je*, *A4’tje*. Ook in het verkleinwoord van woorden op *y*: *baby’tje*, *hobby’tje*. Maar woorden op *a*, *o* en *u* krijgen in het verkleinwoord een extra klinker, zonder apostrof: *autootje*, *fotootje*, *omaatje*, *menuutje*. En bij een woord op *i* komt er een *e* bij, ook zonder apostrof: *taxietje*, *skietje*.',
          rule: 'Afkorting + uitgang: apostrof (*tv’s*). Verkleinwoord: *y* met apostrof (*baby’tje*), *a, o, u* dubbel (*autootje*), *i* + *e* (*taxietje*).',
          build: {
            before: 'Kijk, wat een klein',
            stem: 'auto',
            endings: ['’tje', 'tje', 'otje', '-tje'],
            answer: 'otje',
            note: 'autootje. Bij a, o en u verdubbel je de klinker: autootje, omaatje, menuutje. Alleen bij y komt er een apostrof: baby’tje. Bij i komt er een e bij: taxietje.',
          },
        },
      ],
    },
    {
      kind: 'sort',
      id: 'meervoud',
      prompt: 'Hoe maak je het meervoud?',
      buckets: ['met ’s', 'met -s, zonder apostrof', 'met -ën'],
      items: [
        { t: 'pagina', b: 0 },
        { t: 'accu', b: 0 },
        { t: 'baby', b: 0 },
        { t: 'logo', b: 0 },
        { t: 'taxi', b: 0 },
        { t: 'tv', b: 0 },
        { t: 'café', b: 1 },
        { t: 'garage', b: 1 },
        { t: 'cadeau', b: 1 },
        { t: 'smoothie', b: 1 },
        { t: 'brochure', b: 1 },
        { t: 'coupé', b: 1 },
        { t: 'idee', b: 2 },
        { t: 'orchidee', b: 2 },
        { t: 'knie', b: 2 },
      ],
      why: 'pagina’s, accu’s, baby’s, logo’s en taxi’s: a, u, y, o of i aan het eind. tv’s: een afkorting met een uitgang. cafés, garages, cadeaus, smoothies, brochures en coupés: na é, eau of een e lees je het meervoud vanzelf goed. ideeën, orchideeën en knieën: -ën met een trema.',
    },
    {
      kind: 'choice',
      id: 'paraplu',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'Het regent hard. Gelukkig hebben we twee',
      after: 'bij ons.',
      options: ['paraplus', 'paraplu’s', 'parapluus', 'paraplu-s'],
      answer: 'paraplu’s',
      why: 'paraplu eindigt op een u. Meervoud met ’s, anders lees je pa-ra-plus met een korte u. Een streepje hoort niet voor een meervoud.',
    },
    {
      kind: 'type',
      id: 'inez-kantoor',
      prompt: 'Schrijf het bezit kort op: het kantoor van Inez.',
      before: 'Morgen werk ik in',
      after: 'kantoor.',
      hint: 'bezit',
      answer: 'Inez’',
      why: 'Inez eindigt op een z, een s-klank. Dan zet je alleen een apostrof: Inez’ kantoor. Inez’s en Inezs zijn fout.',
    },
    {
      kind: 'type',
      id: 'fotootje',
      prompt: 'Typ het verkleinwoord van foto.',
      before: 'In zijn portemonnee zit een',
      after: 'van zijn dochter.',
      hint: 'verkleinwoord',
      answer: 'fotootje',
      why: 'Woord op o: de o wordt verdubbeld en -tje komt erachter. Geen apostrof: fotootje, net als autootje.',
    },
    {
      kind: 'swipe',
      id: 'apostrof-waar',
      prompt: 'Klopt de schrijfwijze?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in zit.',
      cards: [
        {
          t: 'Op de bruiloft maakten we honderd selfie’s.',
          ok: false,
          fix: 'selfie’s → selfies',
          why: 'selfie eindigt op een e: gewoon -s. Alleen na a, i, o, u of y komt ’s.',
        },
        { t: 'Peter’s fiets staat voor de deur.', ok: false, fix: 'Peter’s → Peters', why: 'Peter eindigt op een medeklinker: gewoon s, zonder apostrof.' },
        { t: 'In deze straat zitten veel café’s.', ok: false, fix: 'café’s → cafés', why: 'Na een é: gewoon -s.' },
        { t: 'Ik heb al mijn cadeaus ingepakt.', ok: true, why: 'Na eau: -s zonder apostrof.' },
        { t: 'Sanne’s moeder werkt in het ziekenhuis.', ok: false, fix: 'Sanne’s → Sannes', why: 'Sanne eindigt op een doffe e: gewoon s.' },
        {
          t: 'Kun je me straks even sms’en?',
          ok: true,
          why: 'sms is een afkorting die je letter voor letter zegt. Komt er een uitgang achter, ook -en van een werkwoord, dan een apostrof: sms’en.',
        },
        { t: 'Thomas’ dochter is morgen jarig.', ok: true, why: 'Thomas eindigt op een s: alleen een apostrof.' },
        { t: 'Hoeveel euros kost dat?', ok: false, fix: 'euros → euro’s', why: 'euro eindigt op o: ’s.' },
        {
          t: 'Verse broodje’s, twee euro per stuk.',
          ok: false,
          fix: 'broodje’s → broodjes',
          why: 'broodje eindigt op een doffe e: gewoon -s. Deze fout zie je vaak op borden.',
        },
        { t: 'Op woensdag werk ik thuis, maar ’s maandags ben ik op kantoor.', ok: true, why: 'Weggelaten letters: ’s. Een dag blijft klein.' },
        {
          t: 'Mijn collega’s gaan ’S avonds sporten.',
          ok: false,
          fix: '’S avonds → ’s avonds',
          why: 'De ’s is altijd klein. Midden in de zin is avonds ook klein; aan het begin van een zin krijgt alleen avonds een hoofdletter.',
        },
        { t: 'In onze familie zijn twee nieuwe baby’tjes.', ok: true, why: 'baby eindigt op y: ook in het verkleinwoord een apostrof, baby’tje, baby’tjes.' },
        {
          t: 'In de kerstvakantie gaan we ski’en in Oostenrijk.',
          ok: false,
          fix: 'ski’en → skiën',
          why: 'Het werkwoord is ski + en: een trema, geen apostrof. Alleen het meervoud van de ski is ski’s.',
        },
      ],
    },
    {
      kind: 'bet',
      id: 'cadeaus',
      prompt: 'Wat is het meervoud van cadeau?',
      options: ['cadeau’s', 'cadeaus', 'kado’s', 'cadeauen'],
      answer: 'cadeaus',
      why: 'Na eau komt gewoon -s, zonder apostrof. eau klinkt als oo, maar er staat geen losse o aan het eind. Hetzelfde bij bureaus en niveaus. kado is geen officiële spelling: schrijf cadeau.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'Waar het vaak misgaat',
      panels: [
        {
          text: 'De grootste fout: een apostrof waar hij niet hoort. Gewone woorden die op een medeklinker eindigen, krijgen gewoon *-s* of *-en*, nooit *’s*: *appels*, *tafels*, *jongens*. Op een doffe *e* ook: *broodjes*. Ook een naam op een medeklinker: *Peters fiets*, *Ahmeds huis*, *Hasans auto*. En na *é* en *eau* ook niet: *cafés*, *cadeaus*.',
          rule: 'Eindigt het woord (geen afkorting) op een medeklinker, een doffe *e*, een *é* of *eau*? Geen apostrof.',
          show: [
            { wrong: 'appel’s', right: 'appels' },
            { wrong: 'Peter’s fiets', right: 'Peters fiets' },
            { wrong: 'café’s', right: 'cafés' },
            { wrong: 'cadeau’s', right: 'cadeaus' },
          ],
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Ahmeds broer verkoopt broodjes.', 'Ahmed’s broer verkoopt broodjes.', 'Ahmeds broer verkoopt broodje’s.'],
            answer: 'Ahmeds broer verkoopt broodjes.',
            why: 'Ahmed en broodje eindigen niet op a, i, o, u of y. Dus gewoon s, zonder apostrof.',
          },
        },
        {
          text: 'Bezit bij een naam in drie vragen. 1. Eindigt de naam op *a*, *i*, *o*, *u* of *y*? Dan *’s*: *Fatima’s*, *Mo’s*, *Willy’s*. 2. Eindigt de naam op *s*, *x* of *z*? Dan alleen *’*: *Joris’*, *Max’*, *Inez’*. 3. Iets anders, ook een doffe *e* of een *é*? Dan gewoon *s*: *Jans*, *Sannes*, *Renés*.',
          rule: 'Naam op *a, i, o, u, y*: *’s*. Op *s, x, z*: *’*. Anders: *s*.',
          mark: {
            q: 'Tik de vormen die goed geschreven zijn',
            sentence: 'Fatima’s Peter’s Mo’s Hasans Max’ Sanne’s Joris’ Renés',
            targets: [0, 2, 3, 4, 6, 7],
            note: 'Goed: Fatima’s, Mo’s, Hasans, Max’, Joris’ en Renés. Fout: Peter’s (moet Peters) en Sanne’s (moet Sannes).',
          },
        },
        {
          text: 'Afkorting of samenstelling? Plak je een uitgang aan een afkorting, dan komt er een apostrof: *twee tv’s*, *een sms’je*, *drie cd’s*. Maak je er een nieuw woord mee, dan komt er een koppelteken: *tv-programma*, *cd-speler*, *A4-papier*. Dat leer je in de les over het koppelteken.',
          rule: 'Afkorting + uitgang (*-s*, *-je*, *-tje*): apostrof. Afkorting + woord: koppelteken.',
          quiz: {
            q: 'Welke schrijfwijze is goed?',
            options: ['twee A4’tjes en een tv-gids', 'twee A4-tjes en een tv’gids', 'twee A4tjes en een tvgids'],
            answer: 'twee A4’tjes en een tv-gids',
            why: '-tjes is een uitgang: apostrof. gids is een woord: koppelteken.',
          },
        },
        {
          text: 'Let op de kleine verschillen. *zo’n* (zo een) is iets anders dan *zon* (de zon). Vergeet ook de apostrof in *’s avonds* niet: *s avonds* is fout. En in een formele brief of mail schrijf je liever *mijn*, *zijn* en *het* voluit: *m’n*, *z’n* en *’t* passen in een appje, niet in een sollicitatiebrief. Begin je een zin met *’s*, dan krijgt het tweede woord de hoofdletter: *’s Morgens*, nooit *’S morgens*.',
          rule: 'Formeel: *mijn*, *zijn*, *het*. Begin van de zin: *’s Morgens*.',
          show: [
            { wrong: 'zon fiets', right: 'zo’n fiets' },
            { wrong: '’S morgens', right: '’s Morgens' },
            { wrong: 's avonds', right: '’s avonds' },
          ],
          quiz: {
            q: 'Je schrijft een sollicitatiebrief. Welke zin past?',
            options: ['Ik heb mijn diploma in juni gehaald.', 'Ik heb m’n diploma in juni gehaald.', 'Ik heb mn diploma in juni gehaald.'],
            answer: 'Ik heb mijn diploma in juni gehaald.',
            why: 'm’n is goed gespeld, maar informeel. In een brief schrijf je mijn voluit. mn is altijd fout.',
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje-collega',
      prompt: 'Lees het appje na',
      intro: 'Hasan appt zijn collega Ruben. Er zitten fouten in met de apostrof. Tik ze aan.',
      header: { to: 'Ruben' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Ruben,' },
        { t: 'kun' },
        { t: 'je' },
        { t: 'morgen' },
        { t: 's', fix: '’s', why: '’s ochtends: de apostrof laat zien dat er letters weg zijn.' },
        { t: 'ochtends' },
        { t: 'mijn' },
        { t: 'dienst' },
        { t: 'overnemen?' },
        { t: 'Ik' },
        { t: 'moet' },
        { t: 'met' },
        { t: 'de' },
        { t: 'auto' },
        { t: 'naar' },
        { t: 'de' },
        { t: 'garage.' },
        { t: 'Daarna' },
        { t: 'haal' },
        { t: 'ik' },
        { t: 'de' },
        { t: 'pizzas', fix: 'pizza’s', why: 'pizza eindigt op a: meervoud met ’s.' },
        { t: 'voor' },
        { t: 'het' },
        { t: 'afscheid' },
        { t: 'van' },
        { t: 'Joris.' },
        { t: 'Ik' },
        { t: 'neem' },
        { t: 'ook' },
        { t: 'Anna’s' },
        { t: 'laptop' },
        { t: 'mee,' },
        { t: 'en' },
        { t: 'de' },
        { t: 'fotos', fix: 'foto’s', why: 'foto eindigt op o: meervoud met ’s.' },
        { t: 'van' },
        { t: 'het' },
        { t: 'uitje.' },
        { t: 'Maxs', fix: 'Max’', why: 'Max eindigt op x: alleen een apostrof.' },
        { t: 'cadeau' },
        { t: 'ligt' },
        { t: 'nog' },
        { t: 'in' },
        { t: 'zon', fix: 'zo’n', why: 'zo’n komt van zo een. zon is de zon aan de hemel.' },
        { t: 'grote' },
        { t: 'tas' },
        { t: 'op' },
        { t: 'het' },
        { t: 'bureau.' },
        { t: 'Groetjes,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Alle apostrofs op hun plek',
        text: '’s ochtends, pizza’s, foto’s, Max’ en zo’n. Anna’s, cadeau en bureau waren al goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-avonds',
      prompt: 'Luister en typ de zin precies over.',
      intro: 'Let op de apostrofs en de hoofdletters. Niet elke s krijgt een apostrof.',
      sentence: '’s Middags lunchen Hugo’s collega’s met broodjes in Sannes café naast Max’ kapsalon.',
      right: 'Goed: ’s Middags (hoofdletter op het tweede woord), Hugo’s en collega’s (op o en a), Max’ (op x). En zonder apostrof: broodjes, Sannes en café.',
      wrong:
        'Loop de woorden na. ’s Middags: de ’s blijft klein, Middags krijgt de hoofdletter. Hugo’s en collega’s: ’s na o en a. Max’: alleen een apostrof na x. broodjes en Sannes: gewoon s na een doffe e.',
    },
    {
      kind: 'type',
      id: 'pcs',
      prompt: 'Typ het meervoud van pc.',
      before: 'Op de afdeling staan tien oude',
      after: 'die weg moeten.',
      hint: 'meervoud',
      answer: 'pc’s',
      why: 'pc is een afkorting die je letter voor letter uitspreekt. Een uitgang erachter: apostrof. pc’s.',
    },
    {
      kind: 'rewrite',
      id: 'apostrofs-terug',
      prompt: 'Zet de apostrofs en de hoofdletters goed. Verander verder niets.',
      source: 's zomers maakt Hugos zus fotos van de cafés en taxis voor Peters website.',
      accept: ['’s Zomers maakt Hugo’s zus foto’s van de cafés en taxi’s voor Peters website.'],
      why: '’s Zomers: weggelaten letters, en de hoofdletter op het tweede woord. Hugo’s: naam op o. foto’s en taxi’s: meervoud op o en i. cafés blijft zonder apostrof (na é), en Peters ook (naam op een medeklinker).',
    },
    {
      kind: 'sort',
      id: 'bezit-namen',
      prompt: 'Hoe schrijf je het bezit? (… telefoon)',
      buckets: ['’s', 'alleen ’', 'gewoon s'],
      items: [
        { t: 'Anna', b: 0 },
        { t: 'Hugo', b: 0 },
        { t: 'Willy', b: 0 },
        { t: 'Fatima', b: 0 },
        { t: 'Ali', b: 0 },
        { t: 'Max', b: 1 },
        { t: 'Klaas', b: 1 },
        { t: 'Thomas', b: 1 },
        { t: 'Inez', b: 1 },
        { t: 'Joris', b: 1 },
        { t: 'Jan', b: 2 },
        { t: 'Sanne', b: 2 },
        { t: 'Hasan', b: 2 },
        { t: 'René', b: 2 },
        { t: 'Sophie', b: 2 },
      ],
      why: 'Anna’s, Hugo’s, Willy’s, Fatima’s en Ali’s: naam op a, o, y of i. Max’, Klaas’, Thomas’, Inez’ en Joris’: naam op x, s of z. Jans, Sannes, Hasans, Renés en Sophies: gewoon s, ook na een doffe e, een é of ie.',
    },
    {
      kind: 'choice',
      id: 'taxitje',
      prompt: 'Kies het goede verkleinwoord.',
      before: 'Het regent. Zullen we even een',
      after: 'naar het station nemen?',
      options: ['taxi’tje', 'taxitje', 'taxietje', 'taxiitje'],
      answer: 'taxietje',
      why: 'Woord op i: in het verkleinwoord komt er een e bij, zodat je ie blijft lezen: taxietje, net als skietje. Een apostrof komt alleen bij een woord op y (baby’tje). a, o en u verdubbel je (autootje), maar een dubbele i bestaat niet.',
    },
    {
      kind: 'bet',
      id: 'smsjes',
      prompt: 'Je hebt twee korte berichtjes gekregen. Hoe schrijf je dat?',
      options: ['twee smsjes', 'twee sms’jes', 'twee sms-jes', 'twee sms’tjes'],
      answer: 'twee sms’jes',
      why: 'sms is een afkorting. Een uitgang zoals -je of -jes krijgt een apostrof: sms’je, sms’jes. Het is -jes en niet -tjes, net als bij bus: busje.',
    },
    {
      kind: 'write',
      id: 'appje-vriend',
      prompt: 'App een vriend over je weekend.',
      intro: 'Schrijf minstens 25 woorden. Gebruik ’s ochtends, ’s middags of ’s avonds, een meervoud met ’s en een naam met bezit.',
      minWords: 25,
      must: [
        {
          label: '’s ochtends, ’s middags, ’s avonds of ’s nachts',
          hint: '’s avonds',
          test: { pattern: "[’']s\\s+(?:ochtends|middags|avonds|nachts|morgens)", flags: 'iu' },
        },
        {
          label: 'Een meervoud met ’s',
          hint: 'pizza’s, foto’s, auto’s',
          test: { pattern: "\\p{L}+[aiouy][’']s(?!\\p{L})", flags: 'iu' },
        },
        {
          label: 'Een naam met bezit',
          hint: 'Anna’s fiets, Jans huis, Max’ jas',
          test: { pattern: "\\p{Lu}\\p{Ll}+(?:[aiouy][’']s|[sxz][’'](?!\\p{L})|[^aiouysxz\\s]s)\\s+\\p{Ll}+", flags: 'u' },
        },
      ],
      starters: ['Hoi! Zaterdag ’s ochtends heb ik', 'We hebben veel foto’s gemaakt', 'In Anna’s tuin'],
      why: 'Lees je appje nog één keer na: staat er alleen een apostrof na a, i, o, u of y, na een afkorting en waar letters weg zijn?',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Met apostrof, zonder apostrof en woorden uit eerdere lessen door elkaar. Hoofdletters tellen mee. Wat je fout doet, komt achteraan terug.',
      caps: true,
      items: [
        {
          q: 'Meervoud van *pagina*',
          before: 'Het nieuwe huurcontract telt twaalf',
          after: '.',
          a: 'pagina’s',
          why: 'pagina eindigt op een a: ’s. Zonder apostrof lees je pa-gi-nas, met een korte a.',
        },
        {
          q: 'Meervoud van *idee*',
          before: 'Heb jij nog',
          after: 'voor het teamuitje?',
          a: 'ideeën',
          why: 'idee eindigt op ee: -ën met een trema, geen apostrof.',
        },
        {
          q: 'Meervoud van *selfie*',
          before: 'Op de bruiloft maakte iedereen',
          after: 'met het bruidspaar.',
          a: 'selfies',
          why: 'selfie eindigt op een e: gewoon -s. Alleen na a, i, o, u of y komt ’s.',
        },
        {
          q: 'Het kantoor van Esra',
          before: 'De vergadering is in',
          after: 'kantoor.',
          a: 'Esra’s',
          why: 'Esra eindigt op een a: ’s. En een naam houdt zijn hoofdletter.',
        },
        {
          q: 'Schrijf kort: in de avond',
          before: 'Ik werk vaak',
          after: 'in een restaurant.',
          a: '’s avonds',
          why: 'De apostrof laat zien dat er letters weg zijn. Midden in de zin is alles klein: ’s avonds.',
        },
        {
          q: 'Schrijf het woord dat je hoort: het werkwoord bij *de ski*',
          say: 'skiën',
          before: 'In de voorjaarsvakantie gaan we',
          after: 'in Oostenrijk.',
          a: 'skiën',
          why: 'ski + en: het werkwoord krijgt een trema, geen apostrof. Alleen het meervoud van de ski is ski’s.',
        },
        {
          q: 'Meervoud van *ski*',
          before: 'Onze',
          after: 'staan nog in de schuur.',
          a: 'ski’s',
          why: 'ski eindigt op een i: meervoud met ’s.',
        },
        {
          q: 'Meervoud van *niveau*',
          before: 'De taalcursus heeft drie',
          after: ': A1, A2 en B1.',
          a: 'niveaus',
          why: 'Na eau: gewoon -s, geen apostrof. Net als cadeaus en bureaus.',
        },
        {
          q: 'De auto van Lucas',
          before: 'Vandaag rijd ik in',
          after: 'auto.',
          a: 'Lucas’',
          why: 'Lucas eindigt op een s: alleen een apostrof.',
        },
        {
          q: 'Verkleinwoord van *A4*',
          before: 'Mag ik een',
          after: 'van je lenen?',
          a: 'A4’tje',
          why: 'A4 is een afkorting: een apostrof voor -tje.',
        },
        {
          q: 'De taal van Turkije',
          before: 'Mijn buurvrouw spreekt',
          after: 'en Nederlands.',
          a: 'Turks',
          why: 'Een taal krijgt een hoofdletter.',
        },
        {
          q: 'Schrijf kort: in de ochtend',
          after: 'begint mijn dienst om zes uur.',
          a: '’s Ochtends',
          why: 'Begin van de zin: de ’s blijft klein, het woord erna krijgt de hoofdletter.',
        },
        {
          q: 'Verkleinwoord van *oma*',
          before: 'Op het bankje in het park zit een lief',
          after: '.',
          a: 'omaatje',
          why: 'Woord op a: de a wordt dubbel en -tje komt erachter. Geen apostrof: omaatje, net als autootje.',
        },
        {
          q: 'De fiets van Lotte',
          before: 'Ik heb',
          after: 'fiets geleend.',
          a: 'Lottes',
          why: 'Lotte eindigt op een doffe e: gewoon s, geen apostrof.',
        },
        {
          q: 'Inwoner van Italië',
          before: 'Onze nieuwe buurman is een',
          after: '.',
          a: 'Italiaan',
          why: 'Een inwoner krijgt een hoofdletter. Geen trema: ia is geen klank, ook al heeft Italië er wel een.',
        },
        {
          q: 'Meervoud van *kopie*',
          before: 'Neem twee',
          after: 'van je paspoort mee.',
          a: 'kopieën',
          why: 'ko-PIE: de klemtoon ligt op ie, dus -ieën. Een trema, geen apostrof.',
        },
        {
          q: 'Meervoud van *hobby*',
          before: 'In het sollicitatiegesprek vroegen ze naar mijn',
          after: '.',
          a: 'hobby’s',
          why: 'hobby eindigt op een y: ’s, net als baby’s.',
        },
        {
          q: 'Verkleinwoord van *menu*',
          before: 'Voor de kinderen is er een apart',
          after: '.',
          a: 'menuutje',
          why: 'Woord op u: de u wordt dubbel en -tje komt erachter. Geen apostrof.',
        },
        {
          q: 'Het getal 1, met nadruk',
          before: 'Ik heb maar',
          after: 'sleutel, niet twee.',
          a: 'één',
          why: 'Het gaat om het getal: één, met een accent op allebei de e’s.',
        },
        {
          q: 'Het rapport van André',
          before: 'Ik heb',
          after: 'rapport al gelezen.',
          a: 'Andrés',
          why: 'André eindigt op é: gewoon s, net als Renés.',
        },
        {
          q: 'Meervoud van *cv*',
          before: 'Voor deze vacature hebben we al veertig',
          after: 'ontvangen.',
          a: 'cv’s',
          why: 'cv is een afkorting die je letter voor letter zegt. Een uitgang erachter: apostrof.',
        },
        {
          q: 'De rivier langs Deventer en Zutphen',
          before: 'Zondag fietsen we langs de',
          after: '.',
          a: 'IJssel',
          why: 'Een naam met ij vooraan: allebei groot, IJ.',
        },
        {
          q: 'Schrijf kort: *zo een*',
          before: 'Ik wil ook',
          after: 'jas.',
          a: 'zo’n',
          why: 'zo’n is kort voor zo een. Zonder apostrof staat er zon.',
        },
        {
          q: 'Meervoud van *comité*',
          before: 'In onze wijk zijn twee',
          after: 'actief.',
          a: 'comités',
          why: 'Na é: gewoon -s. Het accent blijft staan.',
        },
        {
          q: 'De verjaardag van Marie',
          before: 'Zaterdag vieren we',
          after: 'verjaardag.',
          a: 'Maries',
          why: 'Marie eindigt op een e: gewoon s, net als Sannes. Alleen na a, i, o, u of y aan het eind komt ’s.',
        },
        {
          q: 'Vul *financieel* in, met de goede uitgang',
          before: 'Hij heeft',
          after: 'problemen.',
          a: 'financiële',
          why: 'financieel + e: met de e begint een nieuwe lettergreep. Trema op de e.',
        },
        {
          q: 'Verkleinwoord van *baby*',
          before: 'Wat een lief',
          after: '!',
          a: 'baby’tje',
          why: 'Woord op y: een apostrof en dan -tje. Een y kun je niet verdubbelen zoals de a, o en u (omaatje, autootje).',
        },
        {
          q: 'Schrijf kort: elke zondag',
          before: 'De bakker is',
          after: 'dicht.',
          a: '’s zondags',
          also: ['zondags'],
          why: '’s zondags: een apostrof voor de weggelaten letters. Een dag schrijf je klein. Korter mag ook: zondags.',
        },
        {
          q: 'Meervoud van *risico*',
          before: 'De verzekering dekt niet alle',
          after: '.',
          a: 'risico’s',
          why: 'risico eindigt op een o: ’s.',
        },
        {
          q: 'Het feest aan het eind van de ramadan',
          before: 'Met het',
          after: 'eten we bij mijn schoonouders.',
          a: 'Suikerfeest',
          why: 'Een feestdag is een naam: hoofdletter.',
        },
      ],
      done: {
        title: 'Reeks klaar',
        text: 'Je moest elke keer zelf kiezen: ’s, alleen ’, gewoon s, een trema of een hoofdletter. Een apostrof alleen na a, i, o, u of y, na een afkorting en waar letters weg zijn.',
      },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de nieuwsbrief aan. Typ elk woord helemaal.',
      intro: 'Hoofdletters en apostrofs tellen mee. Kijk goed naar de zin om elk gat heen. In het grijs staat soms een hint.',
      title: 'Nieuwsbrief van de voetbalclub',
      caps: true,
      text: 'Beste leden en ouders,\n\nWat een seizoen! Ons eerste team heeft een toernooi in {België|land met Brussel|Een land krijgt een hoofdletter. Zonder trema lees je ie: Bel-gi-ë.} gewonnen. Op de website staan de {foto’s|meervoud van foto|foto eindigt op een o: ’s. Zonder apostrof lees je fo-tos, met een korte o.} van de finale. Dank aan alle trainers, vrijwilligers en ouders die elke week klaarstaan.\n\n{’s Zaterdags~Zaterdags|kort: elke zaterdag|De zin begint met ’s: de ’s blijft klein en het woord erna krijgt de hoofdletter. Zaterdags zonder ’s mag ook.} trainen de jeugdteams om negen uur. Kunt u rijden naar een uitwedstrijd? Geef het door aan {Thomas’|van Thomas|Thomas eindigt op een s: alleen een apostrof.} vader. Hij maakt het schema voor de {auto’s|meervoud van auto|auto eindigt op een o: ’s.}.\n\nIn de kantine hangen nu twee {tv’s|meervoud van tv|tv is een afkorting die je letter voor letter zegt. Een uitgang erachter: apostrof.}. Op de nieuwe kaart staan verse {broodjes|meervoud van broodje|broodje eindigt op een doffe e: gewoon -s. Geen apostrof.} en {Italiaanse|uit Italië|Een woord dat van een land komt, krijgt een hoofdletter. Geen trema: ia is geen klank.} {pizza’s|meervoud van pizza|pizza eindigt op een a: ’s.}. De {cadeaus|meervoud van cadeau|Na eau: gewoon -s, geen apostrof.} voor de vrijwilligers liggen in {Anna’s|van Anna|Anna eindigt op een a: ’s.} kantoor.\n\nMet {Pasen|feest met eieren|Een feestdag is een naam: hoofdletter.} spelen we een toernooi aan het {IJsselmeer|ijssel + meer|Een naam met ij vooraan: allebei groot, IJ.}. Dat wordt weer {zo’n|zo + een|zo’n is kort voor zo een. zon zonder apostrof is de zon aan de hemel.} dag waar iedereen nog lang over praat. Hebt u {ideeën|meervoud van idee|idee eindigt op ee: -ën met een trema, geen apostrof.} voor het toernooi? Stuur dan een {sms’je|verkleinwoord van sms|sms is een afkorting: een apostrof voor -je.} naar {Jans|van Jan|Jan eindigt op een medeklinker: gewoon s, geen apostrof.} nummer. Dat staat op de website.\n\nMet sportieve groet,\nHet bestuur',
      why: 'Met apostrof: foto’s, ’s Zaterdags, Thomas’, auto’s, tv’s, pizza’s, Anna’s, zo’n en sms’je. Zonder apostrof: broodjes, cadeaus en Jans. Uit eerdere lessen: België met een hoofdletter en een trema, ideeën met een trema, en Italiaanse, Pasen en IJsselmeer met een hoofdletter.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen over een verhuizing. Hoofdletters, apostrofs en leestekens tellen mee.',
      title: 'De verhuizing',
      sentences: [
        '’s Ochtends hebben we alle foto’s en cadeaus in dozen gedaan.',
        'Anna’s broer uit België kwam helpen met twee auto’s en een busje.',
        'Joris’ dochter droeg de tv’s en de radio’s naar boven.',
        'Daarna aten we pizza’s bij Sannes ouders in de tuin.',
        '’s Avonds stuurde ik Jans moeder een sms’je om haar te bedanken.',
        'Volgende week geven we een feest met Fatima’s Italiaanse hapjes en zo’n twintig collega’s.',
      ],
      right:
        'Alles goed: ’s na a en o en na een afkorting (tv’s, sms’je), alleen ’ na Joris, gewoon s bij cadeaus, Sannes, Jans en hapjes, en de hoofdletter na ’s aan het begin van de zin.',
      wrong:
        'Kijk de rode woorden na. ’s Ochtends en ’s Avonds: de ’s klein, het woord erna groot. foto’s, auto’s, tv’s, radio’s, pizza’s, sms’je, zo’n en collega’s: met apostrof. Anna’s en Fatima’s: naam op a. Joris’: alleen ’. cadeaus, Sannes, Jans en hapjes: zonder apostrof.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'afdeling Inkoop', subject: 'Teamuitje vrijdag' },
      greeting: 'Hoi allemaal,',
      signoff: 'Groetjes,\nSanne',
      tokens: [
        { t: 'Vrijdag' },
        { t: 'is' },
        { t: 'ons' },
        { t: 'teamuitje.' },
        { t: 'We' },
        { t: 'vertrekken' },
        { t: 's’middags', fix: '’s middags', why: 'De apostrof staat vóór de s, op de plek van de weggelaten letters: ’s middags, met een spatie.' },
        { t: 'om' },
        { t: 'twee' },
        { t: 'uur' },
        { t: 'met' },
        { t: 'drie' },
        { t: 'autos', fix: 'auto’s', why: 'auto eindigt op een o: meervoud met ’s.' },
        { t: 'vanaf' },
        { t: 'kantoor.' },
        { t: 'Ruben' },
        { t: 'rijdt' },
        { t: 'in' },
        { t: 'Max', fix: 'Max’', why: 'De auto van Max: Max eindigt op x, dus alleen een apostrof. Max’ auto.' },
        { t: 'auto,' },
        { t: 'want' },
        { t: 'die' },
        { t: 'van' },
        { t: 'hem' },
        { t: 'staat' },
        { t: 'bij' },
        { t: 'de' },
        { t: 'garage.' },
        { t: 'Eerst' },
        { t: 'bezoeken' },
        { t: 'we' },
        { t: 'de' },
        { t: 'kaasmarkt' },
        { t: 'in' },
        { t: 'Gouda.' },
        { t: 'Daarna' },
        { t: 'kun' },
        { t: 'je' },
        { t: 'kiezen' },
        { t: 'uit' },
        { t: 'twee' },
        { t: 'cafés', trap: 'Goed: na een é komt gewoon -s, zonder apostrof.' },
        { t: 'op' },
        { t: 'het' },
        { t: 'plein.' },
        { t: 'Er' },
        { t: 'zijn' },
        { t: 'menus', fix: 'menu’s', why: 'menu eindigt op een u: meervoud met ’s.' },
        { t: 'met' },
        { t: 'broodje’s', fix: 'broodjes', why: 'broodje eindigt op een doffe e: gewoon -s, geen apostrof.' },
        { t: 'en' },
        { t: 'soep.' },
        { t: 'Wie' },
        { t: 'vegetarisch' },
        { t: 'eet,' },
        { t: 'zet' },
        { t: 'zijn' },
        { t: 'naam' },
        { t: 'op' },
        { t: 'Klaas’', trap: 'Goed: de lijst van Klaas. Klaas eindigt op een s, dus alleen een apostrof.' },
        { t: 'lijst.' },
        { t: 'Neem' },
        { t: 'gerust' },
        { t: 'je' },
        { t: 'telefoon' },
        { t: 'mee' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'selfies.', trap: 'Goed: selfie eindigt op een e, dus gewoon -s.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'nog' },
        { t: 'een' },
        { t: 'paar' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: een trema op de laatste e, geen apostrof.' },
        { t: 'voor' },
        { t: 'een' },
        { t: 'quiz.' },
        { t: 'Ik' },
        { t: 'neem' },
        { t: 'zon', fix: 'zo’n', why: 'zo’n is kort voor zo een. zon zonder apostrof is de zon aan de hemel.' },
        { t: 'bel' },
        { t: 'mee,' },
        { t: 'net' },
        { t: 'als' },
        { t: 'bij' },
        { t: 'een' },
        { t: 'spelshow.' },
        { t: 'De' },
        { t: 'cadeau’s', fix: 'cadeaus', why: 'Na eau: gewoon -s, geen apostrof.' },
        { t: 'voor' },
        { t: 'Anna' },
        { t: 'liggen' },
        { t: 'al' },
        { t: 'klaar' },
        { t: 'in' },
        { t: 'Peter’s', fix: 'Peters', why: 'Peter eindigt op een medeklinker: gewoon s, geen apostrof.' },
        { t: 'kamer.' },
        { t: 'Het' },
        { t: 'programma' },
        { t: 'hangt' },
        { t: 'op' },
        { t: 'een' },
        { t: 'A4’tje', trap: 'Goed: A4 is een afkorting. Voor de uitgang -tje komt een apostrof.' },
        { t: 'bij' },
        { t: 'de' },
        { t: 'koffieautomaat.' },
      ],
      done: {
        title: 'Mail nagekeken',
        text: 'Fouten: ’s middags, auto’s, Max’, menu’s, broodjes, ideeën, zo’n, cadeaus en Peters. Goed waren cafés, Klaas’, selfies en A4’tje.',
      },
    },
  ],
};
