import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": samenstellingen aan elkaar, en wanneer je toch een koppelteken zet. */
export const LES_L26: LessonInput = {
  id: 'l26',
  stage: 'regels',
  domain: 'orth',
  also: ['morf'],
  title: 'Het koppelteken: zee-egel en tv-gids',
  skill: 'Spelling',
  icon: 'a-b',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Eerst aan elkaar, soms een streepje',
      panels: [
        {
          text: 'Eerst de belangrijkste regel. Plak je twee woorden aan elkaar tot één nieuw woord (een samenstelling), dan schrijf je ze *aan elkaar*. Niet los, en ook niet met een koppelteken: *fietsenrek*, *zonnebril*, *boekenkast*, *ziekenhuis*, *verjaardagsfeest*, *boodschappenlijst*. Ook lange woorden schrijf je in één keer: *verjaardagscadeau*, *klantenservicemedewerker*. Een koppelteken zet je alleen in de gevallen die hierna komen.',
          rule: 'Een samenstelling schrijf je aan elkaar: *fietsenrek*, *ziekenhuis*. Niet *fietsen rek*, niet *fietsen-rek*.',
          compound: {
            q: 'Bouw de samenstelling en kies de goede spelling',
            rounds: [
              {
                clue: 'Een kast voor boeken',
                parts: ['boek', 'kast'],
                result: 'boekenkast',
                options: ['boekenkast', 'boeken kast', 'boeken-kast'],
                answer: 'boekenkast',
                note: 'Eén ding, één woord: boekenkast. Geen spatie en geen streepje.',
                swap: 'Een kastboek bestaat niet: het laatste deel zegt wat het is. Het is een kast.',
              },
              {
                clue: 'Een koek uit de pan',
                parts: ['pan', 'koek'],
                result: 'pannenkoek',
                options: ['pannen koek', 'pannenkoek', 'pannen-koek'],
                answer: 'pannenkoek',
                note: 'pannenkoek: aan elkaar.',
              },
              {
                clue: 'Een bloem die op de zon lijkt',
                parts: ['zon', 'bloem'],
                result: 'zonnebloem',
                options: ['zonne-bloem', 'zonne bloem', 'zonnebloem'],
                answer: 'zonnebloem',
                note: 'zonnebloem: aan elkaar, zoals zonnebril en zonnebrandcrème.',
              },
              {
                clue: 'Een pot voor een bloem',
                parts: ['bloem', 'pot'],
                result: 'bloempot',
                options: ['bloempot', 'bloem pot', 'bloem-pot'],
                answer: 'bloempot',
                note: 'bloempot: aan elkaar.',
              },
            ],
            note: 'Vier samenstellingen, vier keer aan elkaar. Het laatste deel zegt wat het is: een kast, een koek, een bloem, een pot.',
          },
        },
        {
          text: 'Een koppelteken komt er wel als er in een samenstelling twee klinkers botsen die je samen verkeerd zou lezen. In *zeeegel* zie je drie e’s, in *autoongeluk* lees je *oo*. Daarom: *zee-egel*, *auto-ongeluk*, *na-apen*, *mee-eten*, *thee-ei*, *zonne-energie*, *radio-uitzending*, *privé-eigendom*. Maar botsen de klinkers niet zo, dan schrijf je gewoon aan elkaar: *politieagent* (*ea* is geen klank), *fotoalbum* (*oa* is geen klank).',
          rule: 'Samenstelling waarin de klinkers samen verkeerd gelezen worden: koppelteken (*zee-egel*). Anders aan elkaar (*politieagent*).',
          lab: {
            label: 'Tik een combinatie',
            chips: [
              { k: 'zee + egel', out: 'zee-egel', note: 'ee + e: zonder streepje lees je zeeegel. Koppelteken.' },
              { k: 'auto + ongeluk', out: 'auto-ongeluk', note: 'o + o lees je als oo. Koppelteken.' },
              { k: 'thee + ei', out: 'thee-ei', note: 'ee + ei: koppelteken.' },
              { k: 'radio + uitzending', out: 'radio-uitzending', note: 'o + u lees je als ou. Koppelteken.' },
              { k: 'politie + agent', out: 'politieagent', note: 'e + a is geen klank. Je leest het goed: aan elkaar.' },
              { k: 'foto + album', out: 'fotoalbum', note: 'o + a is geen klank: aan elkaar.' },
            ],
          },
        },
        {
          text: 'Zit er een afkorting, een losse letter of een cijfer in de samenstelling, dan komt er een koppelteken: *tv-programma*, *cd-speler*, *btw-nummer*, *wc-papier*, *ov-chipkaart*, *A4-formaat*, *06-nummer*, *e-mail*, *T-shirt*, *x-as*, *3D-film*, *20-jarig*.',
          rule: 'Afkorting, letter of cijfer + woord: koppelteken (*tv-gids*, *e-mail*, *06-nummer*).',
          build: {
            before: 'Ik kijk graag naar dit',
            stem: 'tv',
            endings: ['-programma', 'programma', '’programma'],
            answer: '-programma',
            note: 'tv-programma: een afkorting plus een woord krijgt een koppelteken. Een apostrof komt alleen voor een uitgang: tv’s.',
          },
        },
        {
          text: 'Ook bij aardrijkskundige namen met *Noord*, *Zuid*, *Oost*, *West* of *Midden*: *Noord-Holland*, *Zuid-Afrika*, *Oost-Europa*, *Noord-Brabant*, *het Midden-Oosten*. En bij het bijvoeglijk naamwoord: *Noord-Hollandse kaas*, *Zuid-Afrikaanse wijn*. Verder na *ex-*, *oud-* (in de betekenis van vroeger) en *niet-*: *ex-man*, *ex-collega*, *oud-leerling*, *oud-burgemeester*, *niet-roker*. Let op: *de Noordzee* is één woord, want *zee* is geen naam.',
          rule: '*Noord-*, *Zuid-*, *Oost-*, *West-* + naam, en *ex-*, *oud-*, *niet-*: koppelteken.',
          mark: {
            q: 'Tik de woorden die fout geschreven zijn',
            sentence: 'Noord-Holland exman oud-leerling nietroker Zuid-Afrika Oosteuropa Noordzee ex-collega',
            targets: [1, 3, 5],
            note: 'Fout: exman (ex-man), nietroker (niet-roker) en Oosteuropa (Oost-Europa). Noordzee is goed: zee is geen naam.',
          },
        },
        {
          text: 'Laat je in een opsomming een deel weg, dan zet je op die plek een koppelteken: *de in- en uitgang* (ingang en uitgang), *zomer- en wintertijd*, *voor- en nadelen*, *land- en tuinbouw*. Het streepje zegt: hier hoort nog iets bij. En bij twee gelijkwaardige delen: *de Nederlands-Belgische grens*, *een Arabisch-Nederlands woordenboek*, *een zwart-witfoto*.',
          rule: 'Weggelaten deel in een opsomming: koppelteken (*in- en uitgang*). Twee gelijke delen: koppelteken (*Nederlands-Belgisch*).',
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Let op de voor- en nadelen.', 'Let op de voor en nadelen.', 'Let op de voor-en nadelen.'],
            answer: 'Let op de voor- en nadelen.',
            why: 'voor- staat voor voordelen: het koppelteken staat direct achter voor, en dan volgt een spatie.',
          },
          deep: {
            q: 'En als het laatste deel wegvalt?',
            a: 'Dan staat het koppelteken vóór het deel dat overblijft: *tuinstoelen en -tafels* (tuintafels), *zomerjassen en -broeken*.',
          },
        },
      ],
    },
    {
      kind: 'speed',
      id: 'aan-of-los',
      prompt: 'Aan elkaar of los?',
      intro: 'Is het één samenstelling, of zijn het twee losse woorden?',
      seconds: 40,
      items: [
        { a: 'fietsen', b: 'rek', joined: true, tip: 'fietsenrek: één ding.' },
        { a: 'heel', b: 'mooi', joined: false, tip: 'heel zegt hoe mooi: twee woorden.' },
        { a: 'verjaardags', b: 'feest', joined: true, tip: 'verjaardagsfeest.' },
        { a: 'een', b: 'paar', joined: false, tip: 'een paar: twee woorden.' },
        { a: 'koffie', b: 'machine', joined: true, tip: 'koffiemachine.' },
        { a: 'te', b: 'laat', joined: false, tip: 'te laat: altijd los.' },
        { a: 'bus', b: 'halte', joined: true, tip: 'bushalte.' },
        { a: 'tand', b: 'arts', joined: true, tip: 'tandarts: d + a botsen niet.' },
        { a: 'nieuwe', b: 'jas', joined: false, tip: 'Bijvoeglijk naamwoord + zelfstandig naamwoord: los.' },
        { a: 'boodschappen', b: 'lijst', joined: true, tip: 'boodschappenlijst.' },
      ],
    },
    {
      kind: 'sort',
      id: 'drie-manieren',
      prompt: 'Hoe schrijf je de twee delen?',
      buckets: ['aan elkaar', 'met koppelteken', 'los'],
      items: [
        { t: 'zee + egel', b: 1 },
        { t: 'fiets + pomp', b: 0 },
        { t: 'tv + gids', b: 1 },
        { t: 'Noord + Holland', b: 1 },
        { t: 'politie + agent', b: 0 },
        { t: 'ex + man', b: 1 },
        { t: 'zonne + bril', b: 0 },
        { t: 'auto + ongeluk', b: 1 },
        { t: 'foto + album', b: 0 },
        { t: 'te + veel', b: 2 },
        { t: 'heel + groot', b: 2 },
        { t: 'e + mail', b: 1 },
      ],
      why: 'Aan elkaar: fietspomp, politieagent, zonnebril en fotoalbum. Koppelteken: zee-egel (klinkers botsen), tv-gids en e-mail (afkorting of letter), Noord-Holland (naam), ex-man, auto-ongeluk. Los: te veel en heel groot zijn geen samenstellingen.',
    },
    {
      kind: 'choice',
      id: 'nummer',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'Mag ik je',
      after: '?',
      options: ['06 nummer', '06nummer', '06-nummer', '06’nummer'],
      answer: '06-nummer',
      why: 'Een cijfer + een woord: koppelteken. 06-nummer.',
    },
    {
      kind: 'fix',
      id: 'tvprogramma',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Mijn neef werkt bij een tvprogramma als cameraman.',
      wrong: 5,
      answer: 'tv-programma',
      why: 'tv is een afkorting. Afkorting + woord: koppelteken.',
    },
    {
      kind: 'type',
      id: 'email',
      prompt: 'Typ het woord voor een elektronische brief.',
      before: 'Ik stuur je morgen een',
      after: 'met alle informatie.',
      hint: 'e…',
      answer: 'e-mail',
      why: 'Een losse letter + woord: koppelteken. Zo ook e-mailadres.',
    },
    {
      kind: 'fix',
      id: 'autoongeluk',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Er was een autoongeluk op de snelweg.',
      wrong: 3,
      answer: 'auto-ongeluk',
      why: 'auto + ongeluk: o + o lees je als oo. In een samenstelling komt er dan een koppelteken.',
    },
    {
      kind: 'bet',
      id: 'politieagent',
      prompt: 'Welke schrijfwijze is goed?',
      options: ['politie-agent', 'politieagent', 'politie agent'],
      answer: 'politieagent',
      why: 'e + a vormen samen geen klank: je leest het woord ook zonder streepje goed. Een samenstelling schrijf je dan gewoon aan elkaar.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'De drie grootste fouten',
      panels: [
        {
          text: 'Fout één, en de meest gemaakte: een samenstelling los schrijven. Je ziet het overal, op borden en in mails: *zieken huis*, *klanten service*, *verjaardags feest*. Fout. Is het één ding, dan is het één woord. Twijfel je? Zet *de* of *het* ervoor en kijk of het één ding is: *de klantenservice*, *het ziekenhuis*. En de klemtoon ligt meestal op het eerste deel: *ZIEkenhuis*, *KLANtenservice*.',
          rule: 'Eén ding = één woord: *ziekenhuis*, *klantenservice*, *belastingdienst*.',
          show: [
            { wrong: 'zieken huis', right: 'ziekenhuis' },
            { wrong: 'klanten service', right: 'klantenservice' },
            { wrong: 'verjaardags feest', right: 'verjaardagsfeest' },
            { wrong: 'belasting dienst', right: 'belastingdienst' },
          ],
          quiz: {
            q: 'Welke zin is goed?',
            options: [
              'Bel de klantenservice van de energieleverancier.',
              'Bel de klanten service van de energie leverancier.',
              'Bel de klanten-service van de energie-leverancier.',
            ],
            answer: 'Bel de klantenservice van de energieleverancier.',
            why: 'Twee samenstellingen, allebei aan elkaar. In energieleverancier botsen e en l niet, dus geen koppelteken.',
          },
        },
        {
          text: 'Fout twee: een koppelteken waar het niet hoort. Veel mensen zetten een streepje in een lang woord, maar dat is alleen goed in de gevallen die je net leerde. Dus *fietsenrek*, niet *fietsen-rek*. *Politieagent*, niet *politie-agent*. En binnen één woord met een uitgang of met *ge-* of *be-* komt er nooit een koppelteken, maar een trema: *zeeën*, *beëindigen*.',
          rule: 'Geen klinkerbotsing, afkorting, cijfer, naam, *ex-*/*oud-*/*niet-* of weglating? Dan geen koppelteken.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'fietsen + rek', out: 'fietsenrek', note: 'n + r: niets bijzonders. Aan elkaar.' },
              { k: 'politie + agent', out: 'politieagent', note: 'e + a is geen klank: aan elkaar.' },
              { k: 'zee + en', out: 'zeeën', note: '-en is een uitgang: trema, geen koppelteken.' },
              { k: 'be + eindigen', out: 'beëindigen', note: 'be- is geen los woord: trema.' },
              { k: 'noord + zee', out: 'Noordzee', note: 'zee is geen naam: één woord, wel met hoofdletter.' },
            ],
          },
        },
        {
          text: 'Fout drie: de spatie bij een opsomming vergeten, of het streepje op de verkeerde plek zetten. Het koppelteken staat vast aan het deel dat je inkort, en daarna komt een spatie: *in- en uitgang*. Niet *in-en uitgang*, niet *in en uitgang*. En bij twee namen met *Noord-* of *Zuid-* zet je bij elke naam een koppelteken: *Noord- en Zuid-Holland*.',
          rule: 'Opsomming: koppelteken vast aan het ingekorte deel, dan een spatie: *zomer- en wintertijd*.',
          swap: {
            goal: 'Maak: de ingang en de uitgang, maar korter',
            blocks: ['uitgang', 'de', 'en', 'in-'],
            accept: ['de in- en uitgang'],
            note: 'de in- en uitgang: in- staat voor ingang. Het streepje zit vast aan in.',
          },
        },
        {
          text: 'Twijfel je? Loop dit stappenplan langs. 1. Is het één ding? Dan aan elkaar. 2. Botsen er klinkers die je samen verkeerd leest? Koppelteken. 3. Zit er een afkorting, losse letter of cijfer in? Koppelteken. 4. *Noord-*, *Zuid-*, *Oost-*, *West-* voor een naam, of *ex-*, *oud-*, *niet-*? Koppelteken. 5. Laat je in een opsomming een deel weg? Koppelteken. Is het nergens ja? Dan gewoon aan elkaar.',
          rule: 'Basis: aan elkaar. Koppelteken alleen bij botsing, afkorting/cijfer, naam, *ex-*/*oud-*/*niet-* of weglating.',
          lab: {
            label: 'Tik een woord en loop het stappenplan langs',
            chips: [
              { k: 'boodschappenlijst', out: 'aan elkaar', note: 'Eén ding, geen botsing, geen afkorting: aan elkaar.' },
              { k: 'zee-egel', out: 'koppelteken (stap 2)', note: 'ee + e botsen.' },
              { k: 'A4-formaat', out: 'koppelteken (stap 3)', note: 'Een letter en een cijfer.' },
              { k: 'oud-leerling', out: 'koppelteken (stap 4)', note: 'oud- in de betekenis van vroeger.' },
              { k: 'in- en uitgang', out: 'koppelteken (stap 5)', note: 'Een deel is weggelaten.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-sollicitatie',
      prompt: 'Lees de mail na',
      intro: 'Hasan stuurt een open sollicitatie. Er zitten vijf fouten in met het koppelteken of met aan elkaar schrijven. Tik ze aan.',
      header: { to: 'Personeelszaken', subject: 'Open sollicitatie' },
      tokens: [
        { t: 'Geachte' },
        { t: 'mevrouw' },
        { t: 'De' },
        { t: 'Groot,' },
        { t: 'Mijn' },
        { t: 'oudcollega', fix: 'oud-collega', why: 'oud- in de betekenis van vroeger: koppelteken.' },
        { t: 'Sanne' },
        { t: 'gaf' },
        { t: 'mij' },
        { t: 'uw' },
        { t: 'emailadres.', fix: 'e-mailadres.', why: 'Een losse letter + woord: koppelteken. e-mail, e-mailadres.' },
        { t: 'Ik' },
        { t: 'woon' },
        { t: 'sinds' },
        { t: 'kort' },
        { t: 'in' },
        { t: 'Noord-Holland' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'zoek' },
        { t: 'werk' },
        { t: 'als' },
        { t: 'baliemedewerker' },
        { t: 'in' },
        { t: 'het' },
        { t: 'zieken-huis.', fix: 'ziekenhuis.', why: 'Een samenstelling zonder botsing of afkorting: gewoon aan elkaar.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'ervaring' },
        { t: 'met' },
        { t: 'klanten-service', fix: 'klantenservice', why: 'Aan elkaar: n + s botsen niet.' },
        { t: 'en' },
        { t: 'met' },
        { t: 'het' },
        { t: 'maken' },
        { t: 'van' },
        { t: 'werk-' },
        { t: 'en' },
        { t: 'vakantieroosters.' },
        { t: 'U' },
        { t: 'kunt' },
        { t: 'mij' },
        { t: 'bellen' },
        { t: 'op' },
        { t: 'mijn' },
        { t: '06nummer.', fix: '06-nummer.', why: 'Een cijfer + woord: koppelteken.' },
        { t: 'Met' },
        { t: 'vriendelijke' },
        { t: 'groet,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Netjes verstuurd',
        text: 'oud-collega, e-mailadres, ziekenhuis, klantenservice en 06-nummer. Noord-Holland, baliemedewerker en werk- en vakantieroosters waren al goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-ingang',
      prompt: 'Luister en typ de zin precies over.',
      intro: 'Let op wat aan elkaar moet en waar een koppelteken staat.',
      sentence: 'Bij de in- en uitgang van het ziekenhuis staat een groot fietsenrek.',
      right: 'Goed: in- en uitgang (weggelaten deel), ziekenhuis en fietsenrek (aan elkaar).',
      wrong: 'Kijk naar in- en uitgang: koppelteken vast aan in, dan een spatie. ziekenhuis en fietsenrek schrijf je aan elkaar.',
    },
    {
      kind: 'swipe',
      id: 'koppelteken-waar',
      prompt: 'Klopt de schrijfwijze?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'We gaan op vakantie naar Zuid-Afrika.', ok: true, why: 'Zuid + naam: koppelteken.' },
        { t: 'Mijn ex vrouw woont in Utrecht.', ok: false, fix: 'ex vrouw → ex-vrouw', why: 'ex-: altijd met koppelteken.' },
        { t: 'De bus stopt bij de bushalte.', ok: true, why: 'bushalte: gewoon aan elkaar.' },
        { t: 'Ik heb een nieuwe zonne-bril gekocht.', ok: false, fix: 'zonne-bril → zonnebril', why: 'e + b botsen niet: aan elkaar.' },
        { t: 'Hij betaalt met zijn ov-chipkaart.', ok: true, why: 'ov is een afkorting: koppelteken.' },
        { t: 'We bespraken de voor en nadelen.', ok: false, fix: 'voor en nadelen → voor- en nadelen', why: 'voor- staat voor voordelen: koppelteken.' },
        { t: 'De Nederlands-Duitse grens is vlakbij.', ok: true, why: 'Twee gelijkwaardige delen: koppelteken.' },
        { t: 'Ze heeft een auto ongeluk gehad.', ok: false, fix: 'auto ongeluk → auto-ongeluk', why: 'Samenstelling waarin o + o botsen: koppelteken.' },
      ],
    },
    {
      kind: 'type',
      id: 'ov-chipkaart',
      prompt: 'Typ het woord voor de pas waarmee je in bus en trein betaalt.',
      before: 'Ik ben mijn',
      after: 'kwijt.',
      hint: 'ov…',
      answer: 'ov-chipkaart',
      why: 'ov is een afkorting (openbaar vervoer). Afkorting + woord: koppelteken. chipkaart zelf is gewoon één woord.',
    },
    {
      kind: 'rewrite',
      id: 'opsomming',
      prompt: 'Maak de zin korter door een deel weg te laten.',
      source: 'We praten over de zomertijd en de wintertijd.',
      accept: ['We praten over de zomer- en wintertijd.', 'We praten over de zomer- en de wintertijd.'],
      why: 'zomer- staat voor zomertijd. Het koppelteken zit vast aan zomer, en daarna volgt een spatie.',
    },
    {
      kind: 'choice',
      id: 'grens',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'We wonen vlak bij de',
      after: 'grens.',
      options: ['Nederlands Duitse', 'Nederlands-Duitse', 'Nederlandsduitse', 'nederlands-duitse'],
      answer: 'Nederlands-Duitse',
      why: 'Twee gelijkwaardige delen: koppelteken. Allebei met een hoofdletter, want ze komen van namen.',
    },
    {
      kind: 'bet',
      id: 'exman',
      prompt: 'De man met wie je vroeger getrouwd was, is je …',
      options: ['exman', 'ex-man', 'ex man'],
      answer: 'ex-man',
      why: 'ex- krijgt altijd een koppelteken: ex-man, ex-vriendin, ex-collega.',
    },
    {
      kind: 'write',
      id: 'buurtfeest',
      prompt: 'Nodig je buren uit voor een buurtfeest.',
      intro: 'Schrijf minstens 25 woorden. Gebruik een opsomming met een weggelaten deel, een woord met een afkorting, letter of cijfer, en een samenstelling die je aan elkaar schrijft.',
      minWords: 25,
      must: [
        {
          label: 'Een opsomming met een weggelaten deel',
          hint: 'voor- en achtertuin, in- en uitgang',
          test: { pattern: '\\p{L}+-\\s+(?:en|of)\\s+\\p{L}+', flags: 'iu' },
        },
        {
          label: 'Een afkorting, letter of cijfer met koppelteken',
          hint: 'e-mail, 06-nummer, tv-scherm',
          test: { pattern: '(?:^|\\s)(?:\\p{Ll}{1,3}|\\d+\\p{L}?|\\p{Lu}\\d?)-\\p{L}+', flags: 'u' },
        },
        {
          label: 'Een samenstelling aan elkaar',
          hint: 'buurtfeest, speeltuin, barbecue',
          test: { anyWord: ['buurtfeest', 'buurtfeestje', 'speeltuin', 'straatfeest', 'zomerfeest', 'fietsenrek', 'achtertuin', 'voortuin', 'buurthuis', 'springkussen'] },
        },
      ],
      starters: ['Beste buren, op zaterdag houden we een buurtfeest.', 'Je bent welkom in de voor- en achtertuin', 'Vragen? Stuur een e-mail of bel mijn 06-nummer:'],
      why: 'Lees je uitnodiging nog één keer na: staan alle samenstellingen aan elkaar, en staat er alleen een koppelteken waar de regels het vragen?',
    },
  ],
};
