import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": samenstellingen aan elkaar, en wanneer je toch een koppelteken zet. */
export const LES_L26: LessonInput = {
  id: 'l26',
  stage: 'regels',
  domain: 'orth',
  also: ['morf'],
  title: 'Het koppelteken: zee-egel en tv-gids',
  skill: 'Spelling',
  icon: 'a-b',
  steps: [
    {
      kind: 'explain',
      id: 'uitleg',
      title: 'Eerst aan elkaar, soms een streepje',
      panels: [
        {
          text: 'Eerst de belangrijkste regel. Plak je twee woorden aan elkaar tot één nieuw woord (een samenstelling), dan schrijf je ze *aan elkaar*. Niet los, en ook niet met een koppelteken: *fietsenrek*, *zonnebril*, *boekenkast*, *ziekenhuis*, *verjaardagsfeest*, *boodschappenlijst*. Ook lange woorden schrijf je in één keer: *verjaardagscadeau*, *klantenservicemedewerker*. Een koppelteken zet je alleen in de gevallen die hierna komen.',
          rule: 'Een samenstelling schrijf je aan elkaar: *fietsenrek*, *ziekenhuis*. Niet *fietsen rek*, niet *fietsen-rek*.',
          compound: {
            q: 'Bouw de samenstelling en kies de goede spelling',
            rounds: [
              {
                clue: 'Een kast voor boeken',
                parts: ['boek', 'kast'],
                result: 'boekenkast',
                options: ['boekenkast', 'boeken kast', 'boeken-kast'],
                answer: 'boekenkast',
                note: 'Eén ding, één woord: boekenkast. Geen spatie en geen streepje.',
                swap: 'Een kastboek bestaat niet: het laatste deel zegt wat het is. Het is een kast.',
              },
              {
                clue: 'Een koek uit de pan',
                parts: ['pan', 'koek'],
                result: 'pannenkoek',
                options: ['pannen koek', 'pannenkoek', 'pannen-koek'],
                answer: 'pannenkoek',
                note: 'pannenkoek: aan elkaar.',
              },
              {
                clue: 'Een bloem die op de zon lijkt',
                parts: ['zon', 'bloem'],
                result: 'zonnebloem',
                options: ['zonne-bloem', 'zonne bloem', 'zonnebloem'],
                answer: 'zonnebloem',
                note: 'zonnebloem: aan elkaar, zoals zonnebril en zonnebrandcrème.',
              },
              {
                clue: 'Een pot voor een bloem',
                parts: ['bloem', 'pot'],
                result: 'bloempot',
                options: ['bloempot', 'bloem pot', 'bloem-pot'],
                answer: 'bloempot',
                note: 'bloempot: aan elkaar.',
              },
            ],
            note: 'Vier samenstellingen, vier keer aan elkaar. Het laatste deel zegt wat het is: een kast, een koek, een bloem, een pot.',
          },
        },
        {
          text: 'Een koppelteken komt er wel als er in een samenstelling twee klinkers botsen die je samen verkeerd zou lezen. In *zeeegel* zie je drie e’s, in *autoongeluk* lees je *oo*. Daarom: *zee-egel*, *auto-ongeluk*, *na-apen*, *mee-eten*, *thee-ei*, *zonne-energie*, *radio-uitzending*, *privé-eigendom*. Maar botsen de klinkers niet zo, dan schrijf je gewoon aan elkaar: *politieagent* (*ea* is geen klank), *fotoalbum* (*oa* is geen klank).',
          rule: 'Samenstelling waarin de klinkers samen verkeerd gelezen worden: koppelteken (*zee-egel*). Anders aan elkaar (*politieagent*).',
          lab: {
            label: 'Tik een combinatie',
            chips: [
              { k: 'zee + egel', out: 'zee-egel', note: 'ee + e: zonder streepje lees je zeeegel. Koppelteken.' },
              { k: 'auto + ongeluk', out: 'auto-ongeluk', note: 'o + o lees je als oo. Koppelteken.' },
              { k: 'thee + ei', out: 'thee-ei', note: 'ee + ei: koppelteken.' },
              { k: 'radio + uitzending', out: 'radio-uitzending', note: 'o + u lees je als ou. Koppelteken.' },
              { k: 'politie + agent', out: 'politieagent', note: 'e + a is geen klank. Je leest het goed: aan elkaar.' },
              { k: 'foto + album', out: 'fotoalbum', note: 'o + a is geen klank: aan elkaar.' },
            ],
          },
        },
        {
          text: 'Zit er een afkorting, een losse letter of een cijfer in de samenstelling, dan komt er een koppelteken: *tv-programma*, *cd-speler*, *btw-nummer*, *wc-papier*, *ov-chipkaart*, *A4-formaat*, *06-nummer*, *e-mail*, *T-shirt*, *x-as*, *3D-film*, *20-jarig*. Let op: een afkorting die je als een gewoon woord uitspreekt, schrijf je er gewoon aan vast: *pinpas*, *pincode*.',
          rule: 'Afkorting, letter of cijfer + woord: koppelteken (*tv-gids*, *e-mail*, *06-nummer*). Spreek je de afkorting uit als een woord? Aan elkaar (*pinpas*).',
          build: {
            before: 'Ik kijk graag naar dit',
            stem: 'tv',
            endings: ['-programma', 'programma', '’programma'],
            answer: '-programma',
            note: 'tv-programma: een afkorting plus een woord krijgt een koppelteken. Een apostrof komt alleen voor een uitgang: tv’s.',
          },
        },
        {
          text: 'Ook bij aardrijkskundige namen met *Noord*, *Zuid*, *Oost*, *West* of *Midden*: *Noord-Holland*, *Zuid-Afrika*, *Oost-Europa*, *Noord-Brabant*, *het Midden-Oosten*. En bij het bijvoeglijk naamwoord: *Noord-Hollandse kaas*, *Zuid-Afrikaanse wijn*. Verder na *ex-*, *oud-* (in de betekenis van vroeger) en *niet-*: *ex-man*, *ex-collega*, *oud-leerling*, *oud-burgemeester*, *niet-roker*. Let op: *de Noordzee* is één woord, want *zee* is geen naam.',
          rule: '*Noord-*, *Zuid-*, *Oost-*, *West-* + naam, en *ex-*, *oud-*, *niet-*: koppelteken.',
          mark: {
            q: 'Tik de woorden die fout geschreven zijn',
            sentence: 'Noord-Holland exman oud-leerling nietroker Zuid-Afrika Oosteuropa Noordzee ex-collega',
            targets: [1, 3, 5],
            note: 'Fout: exman (ex-man), nietroker (niet-roker) en Oosteuropa (Oost-Europa). Noordzee is goed: zee is geen naam.',
          },
        },
        {
          text: 'Laat je in een opsomming een deel weg, dan zet je op die plek een koppelteken: *de in- en uitgang* (ingang en uitgang), *zomer- en wintertijd*, *voor- en nadelen*, *land- en tuinbouw*. Het streepje zegt: hier hoort nog iets bij. En bij twee gelijkwaardige delen: *de Nederlands-Belgische grens*, *een Arabisch-Nederlands woordenboek*, *een zwart-witfoto*.',
          rule: 'Weggelaten deel in een opsomming: koppelteken (*in- en uitgang*). Twee gelijke delen: koppelteken (*Nederlands-Belgisch*).',
          quiz: {
            q: 'Welke zin is goed?',
            options: ['Let op de voor- en nadelen.', 'Let op de voor en nadelen.', 'Let op de voor-en nadelen.'],
            answer: 'Let op de voor- en nadelen.',
            why: 'voor- staat voor voordelen: het koppelteken staat direct achter voor, en dan volgt een spatie.',
          },
          deep: {
            q: 'En als het laatste deel wegvalt?',
            a: 'Dan staat het koppelteken vóór het deel dat overblijft: *tuinstoelen en -tafels* (tuintafels), *zomerjassen en -broeken*.',
          },
        },
      ],
    },
    {
      kind: 'speed',
      id: 'aan-of-los',
      prompt: 'Aan elkaar of los?',
      intro: 'Is het één samenstelling, of zijn het twee losse woorden?',
      seconds: 40,
      items: [
        { a: 'zorg', b: 'verzekeraar', joined: true, tip: 'zorgverzekeraar: één ding.' },
        { a: 'eigen', b: 'risico', joined: false, tip: 'het eigen risico: twee woorden, ook bij de zorgverzekering.' },
        { a: 'huur', b: 'toeslag', joined: true, tip: 'huurtoeslag.' },
        { a: 'nieuwe', b: 'huurder', joined: false, tip: 'Bijvoeglijk naamwoord + zelfstandig naamwoord: los.' },
        { a: 'sollicitatie', b: 'gesprek', joined: true, tip: 'sollicitatiegesprek: e + g botsen niet.' },
        { a: 'vast', b: 'contract', joined: false, tip: 'een vast contract: twee woorden.' },
        { a: 'parkeer', b: 'vergunning', joined: true, tip: 'parkeervergunning.' },
        { a: 'kinder', b: 'bijslag', joined: true, tip: 'kinderbijslag.' },
        { a: 'lange', b: 'wachtlijst', joined: false, tip: 'een lange wachtlijst: bijvoeglijk naamwoord + zelfstandig naamwoord, dus los.' },
        { a: 'gemeente', b: 'huis', joined: true, tip: 'gemeentehuis: e + h botsen niet.' },
        { a: 'energie', b: 'leverancier', joined: true, tip: 'energieleverancier: e + l botsen niet.' },
        { a: 'heel', b: 'snel', joined: false, tip: 'heel zegt hoe snel: twee woorden.' },
      ],
    },
    {
      kind: 'sort',
      id: 'drie-manieren',
      prompt: 'Hoe schrijf je de twee delen?',
      buckets: ['aan elkaar', 'met koppelteken', 'los'],
      items: [
        { t: 'zee + egel', b: 1 },
        { t: 'zee + arend', b: 0 },
        { t: 'auto + industrie', b: 1 },
        { t: 'auto + alarm', b: 0 },
        { t: 'pin + pas', b: 0 },
        { t: 'btw + nummer', b: 1 },
        { t: 'Zuid + Afrikaans', b: 1 },
        { t: 'noord + zee', b: 0 },
        { t: 'oud + leerling', b: 1 },
        { t: 'oud + jaar', b: 0 },
        { t: 'niet + roker', b: 1 },
        { t: 'eigen + risico', b: 2 },
        { t: 'heel + duur', b: 2 },
        { t: 'politie + agent', b: 0 },
        { t: 'mee + eten', b: 1 },
        { t: 'kinder + opvang', b: 0 },
        { t: 'nieuwe + collega', b: 2 },
      ],
      why: 'Aan elkaar: zeearend en autoalarm (e + a en o + a zijn geen klank), pinpas (pin zeg je als een gewoon woord), Noordzee (zee is geen naam), oudjaar (oud betekent hier niet vroeger), politieagent en kinderopvang. Koppelteken: zee-egel, auto-industrie en mee-eten (klinkers botsen), btw-nummer (afkorting), Zuid-Afrikaans (naam), oud-leerling en niet-roker. Los: eigen risico, heel duur en nieuwe collega zijn geen samenstellingen.',
    },
    {
      kind: 'choice',
      id: 'nummer',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'In de app van de sportclub staan de',
      after: 'van alle trainers.',
      options: ['06-nummer’s', '06 nummers', '06-nummers', '06nummers'],
      answer: '06-nummers',
      why: 'Een cijfer + een woord: koppelteken. nummer eindigt op r, dus het meervoud krijgt gewoon -s, zonder apostrof.',
    },
    {
      kind: 'fix',
      id: 'tvprogramma',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Mijn ex-collega werkt als cameraman bij een tvprogramma over de Noordzee.',
      wrong: 7,
      answer: 'tv-programma',
      why: 'tv is een afkorting. Afkorting + woord: koppelteken. ex-collega en Noordzee waren al goed.',
    },
    {
      kind: 'type',
      id: 'email',
      prompt: 'Maak één woord van e + mail + adres.',
      before: 'Wilt u uw nieuwe',
      after: 'doorgeven aan de administratie?',
      hint: '',
      answer: 'e-mailadres',
      why: 'Een losse letter + woord: koppelteken (e-mail). Het woord adres plak je er gewoon aan vast: e-mailadres.',
    },
    {
      kind: 'fix',
      id: 'autoongeluk',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Na twee autoongelukken op de snelweg sloot de politieagent de oprit af.',
      wrong: 2,
      answer: 'auto-ongelukken',
      why: 'auto + ongelukken: o + o lees je als oo. Koppelteken. politieagent is goed: e + a is geen klank.',
    },
    {
      kind: 'bet',
      id: 'politieagent',
      prompt: 'Welke rij is helemaal goed?',
      options: [
        'politie-agent – fotoalbum – zee-egel',
        'politieagent – foto-album – zeeëgel',
        'politieagent – fotoalbum – zee-egel',
        'politie-agent – foto-album – zee-egel',
      ],
      answer: 'politieagent – fotoalbum – zee-egel',
      why: 'In politieagent en fotoalbum vormen de klinkers (e + a, o + a) geen klank: aan elkaar. In zee-egel botsen ee + e: koppelteken. Een trema komt alleen binnen één woord.',
    },
    {
      kind: 'explain',
      id: 'valkuilen',
      title: 'De drie grootste fouten',
      panels: [
        {
          text: 'Fout één, en de meest gemaakte: een samenstelling los schrijven. Je ziet het overal, op borden en in mails: *zieken huis*, *klanten service*, *verjaardags feest*. Fout. Is het één ding, dan is het één woord. Twijfel je? Zet *de* of *het* ervoor en kijk of het één ding is: *de klantenservice*, *het ziekenhuis*. En de klemtoon ligt meestal op het eerste deel: *ZIEkenhuis*, *KLANtenservice*.',
          rule: 'Eén ding = één woord: *ziekenhuis*, *klantenservice*, *belastingdienst*.',
          show: [
            { wrong: 'zieken huis', right: 'ziekenhuis' },
            { wrong: 'klanten service', right: 'klantenservice' },
            { wrong: 'verjaardags feest', right: 'verjaardagsfeest' },
            { wrong: 'belasting dienst', right: 'belastingdienst' },
          ],
          quiz: {
            q: 'Welke zin is goed?',
            options: [
              'Bel de klantenservice van de energieleverancier.',
              'Bel de klanten service van de energie leverancier.',
              'Bel de klanten-service van de energie-leverancier.',
            ],
            answer: 'Bel de klantenservice van de energieleverancier.',
            why: 'Twee samenstellingen, allebei aan elkaar. In energieleverancier botsen e en l niet, dus geen koppelteken.',
          },
        },
        {
          text: 'Fout twee: een koppelteken waar het niet hoort. Veel mensen zetten een streepje in een lang woord, maar dat is alleen goed in de gevallen die je net leerde. Dus *fietsenrek*, niet *fietsen-rek*. *Politieagent*, niet *politie-agent*. En binnen één woord met een uitgang of met *ge-* of *be-* komt er geen koppelteken, maar een trema: *zeeën*, *beëindigen*. Alleen voor een woord dat met een losse letter begint, zoals *e-mail*, komt na *ge-* een koppelteken: *ge-e-maild*.',
          rule: 'Geen klinkerbotsing, afkorting, cijfer, naam, *ex-*/*oud-*/*niet-* of weglating? Dan geen koppelteken.',
          lab: {
            label: 'Tik een woord',
            chips: [
              { k: 'fietsen + rek', out: 'fietsenrek', note: 'n + r: niets bijzonders. Aan elkaar.' },
              { k: 'politie + agent', out: 'politieagent', note: 'e + a is geen klank: aan elkaar.' },
              { k: 'zee + en', out: 'zeeën', note: '-en is een uitgang: trema, geen koppelteken.' },
              { k: 'be + eindigen', out: 'beëindigen', note: 'be- is geen los woord: trema.' },
              { k: 'noord + zee', out: 'Noordzee', note: 'zee is geen naam: één woord, wel met hoofdletter.' },
            ],
          },
        },
        {
          text: 'Fout drie: de spatie bij een opsomming vergeten, of het streepje op de verkeerde plek zetten. Het koppelteken staat vast aan het deel dat je inkort, en daarna komt een spatie: *in- en uitgang*. Niet *in-en uitgang*, niet *in en uitgang*. En bij twee namen met *Noord-* of *Zuid-* zet je bij elke naam een koppelteken: *Noord- en Zuid-Holland*.',
          rule: 'Opsomming: koppelteken vast aan het ingekorte deel, dan een spatie: *zomer- en wintertijd*.',
          swap: {
            goal: 'Maak: de ingang en de uitgang, maar korter',
            blocks: ['uitgang', 'de', 'en', 'in-'],
            accept: ['de in- en uitgang'],
            note: 'de in- en uitgang: in- staat voor ingang. Het streepje zit vast aan in.',
          },
        },
        {
          text: 'Twijfel je? Loop dit stappenplan langs. 1. Is het één ding? Dan aan elkaar. 2. Botsen er klinkers die je samen verkeerd leest? Koppelteken. 3. Zit er een afkorting, losse letter of cijfer in? Koppelteken. 4. *Noord-*, *Zuid-*, *Oost-*, *West-* voor een naam, of *ex-*, *oud-*, *niet-*? Koppelteken. 5. Laat je in een opsomming een deel weg? Koppelteken. Is het nergens ja? Dan gewoon aan elkaar.',
          rule: 'Basis: aan elkaar. Koppelteken alleen bij botsing, afkorting/cijfer, naam, *ex-*/*oud-*/*niet-* of weglating.',
          lab: {
            label: 'Tik een woord en loop het stappenplan langs',
            chips: [
              { k: 'boodschappenlijst', out: 'aan elkaar', note: 'Eén ding, geen botsing, geen afkorting: aan elkaar.' },
              { k: 'zee-egel', out: 'koppelteken (stap 2)', note: 'ee + e botsen.' },
              { k: 'A4-formaat', out: 'koppelteken (stap 3)', note: 'Een letter en een cijfer.' },
              { k: 'oud-leerling', out: 'koppelteken (stap 4)', note: 'oud- in de betekenis van vroeger.' },
              { k: 'in- en uitgang', out: 'koppelteken (stap 5)', note: 'Een deel is weggelaten.' },
            ],
          },
        },
      ],
    },
    {
      kind: 'proofread',
      id: 'mail-sollicitatie',
      prompt: 'Lees de mail na',
      intro: 'Hasan stuurt een open sollicitatie. Er zitten fouten in met het koppelteken of met aan elkaar schrijven. Tik ze aan.',
      header: { to: 'Personeelszaken', subject: 'Open sollicitatie' },
      greeting: 'Geachte mevrouw De Groot,',
      tokens: [
        { t: 'Mijn' },
        { t: 'oudcollega', fix: 'oud-collega', why: 'oud- in de betekenis van vroeger: koppelteken.' },
        { t: 'Sanne' },
        { t: 'gaf' },
        { t: 'mij' },
        { t: 'uw' },
        { t: 'emailadres.', fix: 'e-mailadres.', why: 'Een losse letter + woord: koppelteken. e-mail, e-mailadres.' },
        { t: 'Ik' },
        { t: 'woon' },
        { t: 'sinds' },
        { t: 'kort' },
        { t: 'in' },
        { t: 'Noord-Holland' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'zoek' },
        { t: 'werk' },
        { t: 'als' },
        { t: 'baliemedewerker' },
        { t: 'in' },
        { t: 'het' },
        { t: 'zieken-huis.', fix: 'ziekenhuis.', why: 'Een samenstelling zonder botsing of afkorting: gewoon aan elkaar.' },
        { t: 'Ik' },
        { t: 'heb' },
        { t: 'ervaring' },
        { t: 'met' },
        { t: 'klanten-service', fix: 'klantenservice', why: 'Aan elkaar: n + s botsen niet.' },
        { t: 'en' },
        { t: 'met' },
        { t: 'het' },
        { t: 'maken' },
        { t: 'van' },
        { t: 'werk-' },
        { t: 'en' },
        { t: 'vakantieroosters.' },
        { t: 'U' },
        { t: 'kunt' },
        { t: 'mij' },
        { t: 'bellen' },
        { t: 'op' },
        { t: 'mijn' },
        { t: '06nummer.', fix: '06-nummer.', why: 'Een cijfer + woord: koppelteken.' },
        { t: 'Met' },
        { t: 'vriendelijke' },
        { t: 'groet,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Netjes verstuurd',
        text: 'oud-collega, e-mailadres, ziekenhuis, klantenservice en 06-nummer. Noord-Holland, baliemedewerker en werk- en vakantieroosters waren al goed.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-ingang',
      prompt: 'Luister en typ de zin precies over.',
      intro: 'Let op wat aan elkaar moet, waar een koppelteken staat en waar een hoofdletter hoort.',
      sentence: 'Onze oud-voorzitter uit Zuid-Afrika zag bij de in- en uitgang van het ziekenhuis een auto-ongeluk.',
      right: 'Goed: oud-voorzitter, Zuid-Afrika, in- en uitgang en auto-ongeluk met koppelteken, en ziekenhuis aan elkaar.',
      wrong: 'Kijk na: oud-voorzitter (oud- = vroeger), Zuid-Afrika (naam), in- en uitgang (koppelteken vast aan in, dan een spatie), ziekenhuis (aan elkaar) en auto-ongeluk (o + o botsen).',
    },
    {
      kind: 'swipe',
      id: 'koppelteken-waar',
      prompt: 'Klopt de schrijfwijze?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in zit.',
      cards: [
        { t: 'Om drie uur ’s nachts ging het autoalarm van de buren af.', ok: true, why: 'autoalarm: o + a is geen klank, dus aan elkaar. ’s nachts met apostrof.' },
        {
          t: 'Mijn ex vriendin werkt nu in de auto-industrie.',
          ok: false,
          fix: 'ex vriendin → ex-vriendin',
          why: 'ex- krijgt altijd een koppelteken. auto-industrie is goed: o + i botsen.',
        },
        {
          t: 'Ik betaal in de winkel altijd met mijn pin-pas.',
          ok: false,
          fix: 'pin-pas → pinpas',
          why: 'pin zeg je als een gewoon woord, niet letter voor letter. Dan geen koppelteken: pinpas, pincode.',
        },
        { t: 'Op zon- en feestdagen is de apotheek gesloten.', ok: true, why: 'zon- staat voor zondagen: koppelteken vast aan zon, dan een spatie.' },
        { t: 'Bespreek de voor-en nadelen met je teamleider.', ok: false, fix: 'voor-en → voor- en', why: 'Na het koppelteken komt een spatie: voor- en nadelen.' },
        {
          t: 'Ik heb je gisteren een email gestuurd.',
          ok: false,
          fix: 'email → e-mail',
          why: 'Hier gaat het om een bericht: e-mail, een losse letter + woord, dus een koppelteken. Het woord email zonder streepje bestaat ook, maar dat is iets anders: een glanzende laag op metaal.',
        },
        { t: 'Zij woont in noord-Brabant, vlak bij Eindhoven.', ok: false, fix: 'noord-Brabant → Noord-Brabant', why: 'Noord hoort bij de naam: hoofdletter en koppelteken.' },
        { t: 'We zagen zeehonden in de Noordzee.', ok: true, why: 'Noordzee: één woord met hoofdletter. zee is geen naam, dus geen koppelteken.' },
        {
          t: 'Met zonne energie bespaar je veel op de energierekening.',
          ok: false,
          fix: 'zonne energie → zonne-energie',
          why: 'Eén samenstelling waarin e + e botsen: koppelteken. energierekening is goed: aan elkaar.',
        },
        { t: 'De Nederlands-Marokkaanse buurtvereniging zoekt vrijwilligers.', ok: true, why: 'Twee gelijkwaardige delen: koppelteken, en allebei met een hoofdletter.' },
        { t: 'De oud-burgemeester opende het nieuwe gemeentehuis.', ok: true, why: 'oud- in de betekenis van vroeger: koppelteken. gemeentehuis aan elkaar.' },
        { t: 'Stuur je cv als pdf-bestand mee met je sollicitatie.', ok: true, why: 'pdf is een afkorting: koppelteken. cv schrijf je klein, zonder punten.' },
        { t: 'De politie-agent vroeg om mijn rijbewijs.', ok: false, fix: 'politie-agent → politieagent', why: 'e + a is geen klank: je leest het goed zonder streepje. Aan elkaar.' },
      ],
    },
    {
      kind: 'type',
      id: 'ov-chipkaart',
      prompt: 'Typ het woord: de afkorting van openbaar vervoer + chipkaart.',
      before: 'Ik ben mijn',
      after: 'kwijt.',
      hint: '',
      answer: 'ov-chipkaart',
      why: 'ov is een afkorting (openbaar vervoer). Afkorting + woord: koppelteken. chipkaart zelf is gewoon één woord.',
    },
    {
      kind: 'rewrite',
      id: 'opsomming',
      prompt: 'Maak de zin korter: laat op twee plekken een deel weg.',
      source: 'Op zondagen en feestdagen zijn de ingang en de uitgang aan de achterkant.',
      accept: ['Op zon- en feestdagen zijn de in- en uitgang aan de achterkant.', 'Op zon- en feestdagen zijn de in- en de uitgang aan de achterkant.'],
      why: 'zon- staat voor zondagen, in- voor ingang. Het koppelteken zit vast aan het ingekorte deel, en daarna komt een spatie.',
    },
    {
      kind: 'choice',
      id: 'grens',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'We wonen vlak bij de',
      after: 'grens.',
      options: ['Nederlands Duitse', 'Nederlands-Duitse', 'Nederlandsduitse', 'nederlands-duitse'],
      answer: 'Nederlands-Duitse',
      why: 'Twee gelijkwaardige delen: koppelteken. Allebei met een hoofdletter, want ze komen van namen.',
    },
    {
      kind: 'bet',
      id: 'exman',
      prompt: 'Welke zin is helemaal goed?',
      options: [
        'Mijn exman en mijn oud-collega kennen elkaar.',
        'Mijn ex-man en mijn oudcollega kennen elkaar.',
        'Mijn ex-man en mijn oud collega kennen elkaar.',
        'Mijn ex-man en mijn oud-collega kennen elkaar.',
      ],
      answer: 'Mijn ex-man en mijn oud-collega kennen elkaar.',
      why: 'ex- en oud- (in de betekenis van vroeger) krijgen allebei een koppelteken: ex-man, oud-collega.',
    },
    {
      kind: 'write',
      id: 'buurtfeest',
      prompt: 'Nodig je buren uit voor een buurtfeest.',
      intro: 'Schrijf minstens 25 woorden. Gebruik een opsomming met een weggelaten deel, een woord met een afkorting, letter of cijfer, en een samenstelling die je aan elkaar schrijft.',
      minWords: 25,
      must: [
        {
          label: 'Een opsomming met een weggelaten deel',
          hint: 'voor- en achtertuin, in- en uitgang',
          test: { pattern: '\\p{L}+-\\s+(?:en|of)\\s+\\p{L}+', flags: 'iu' },
        },
        {
          label: 'Een afkorting, letter of cijfer met koppelteken',
          hint: 'e-mail, 06-nummer, tv-scherm',
          test: { pattern: '(?:^|\\s)(?:\\p{Ll}{1,3}|\\d+\\p{L}?|\\p{Lu}\\d?)-\\p{L}+', flags: 'u' },
        },
        {
          label: 'Een samenstelling aan elkaar',
          hint: 'buurtfeest, speeltuin, barbecue',
          test: { anyWord: ['buurtfeest', 'buurtfeestje', 'speeltuin', 'straatfeest', 'zomerfeest', 'fietsenrek', 'achtertuin', 'voortuin', 'buurthuis', 'springkussen'] },
        },
      ],
      starters: ['Beste buren, op zaterdag houden we een buurtfeest.', 'Je bent welkom in de voor- en achtertuin', 'Vragen? Stuur een e-mail of bel mijn 06-nummer:'],
      why: 'Lees je uitnodiging nog één keer na: staan alle samenstellingen aan elkaar, en staat er alleen een koppelteken waar de regels het vragen?',
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks: typ elk woord goed',
      intro: 'Zesentwintig woorden door elkaar, ook met regels uit de vorige lessen. Hoofdletters tellen mee. Wat je fout doet, komt achteraan terug.',
      caps: true,
      items: [
        { q: 'Meervoud: een ongeluk met een auto', before: 'Op de A12 waren vanochtend twee', after: '.', a: 'auto-ongelukken', why: 'auto + ongelukken: o + o lees je samen als oo. Koppelteken.' },
        {
          q: 'Schrijf de achternaam van Jan de Vries',
          before: 'Morgen heb ik een afspraak met meneer',
          after: 'van de woningcorporatie.',
          a: 'De Vries',
          why: 'Er staat geen voornaam voor: het tussenvoegsel krijgt een hoofdletter. meneer De Vries.',
        },
        {
          q: 'Schrijf de samenstelling: pin + pas',
          before: 'Ik ben mijn',
          after: 'kwijt en kan niet betalen.',
          a: 'pinpas',
          why: 'pin zeg je als een gewoon woord, niet letter voor letter. Dan geen koppelteken: pinpas, pincode.',
        },
        {
          q: 'Maak korter: zondagen en feestdagen',
          before: 'De apotheek is op',
          after: 'gesloten.',
          say: 'zon- en feestdagen',
          a: 'zon- en feestdagen',
          why: 'zon- staat voor zondagen. Koppelteken vast aan zon, dan een spatie.',
        },
        { q: 'Plak aan elkaar: *ge* + *informeerd*', before: 'U wordt binnen twee weken per brief', after: '.', a: 'geïnformeerd', why: 'ge + informeerd: zonder trema lees je ei. Trema op de i.' },
        {
          q: 'Bijvoeglijk naamwoord: uit het land met Kaapstad',
          before: 'Bij het eten drinken we een',
          after: 'wijn.',
          a: 'Zuid-Afrikaanse',
          why: 'Zuid hoort bij de naam: koppelteken en twee hoofdletters. Met -e, want het is de wijn.',
        },
        {
          q: 'Schrijf de samenstelling: btw + nummer',
          before: 'Zet uw',
          after: 'onder aan elke factuur.',
          a: 'btw-nummer',
          why: 'btw is een afkorting die je letter voor letter zegt. Afkorting + woord: koppelteken.',
        },
        {
          q: 'Schrijf *in de avond* korter, zoals je het zegt',
          after: 'werk ik in een restaurant.',
          a: '’s Avonds',
          why: 'Apostrof voor de weggelaten letters. Aan het begin van de zin krijgt het tweede woord de hoofdletter: ’s Avonds.',
        },
        {
          q: 'Schrijf de samenstelling: politie + agent',
          before: 'Een',
          after: 'hield ons staande op de snelweg.',
          a: 'politieagent',
          why: 'e + a lees je niet als één klank. Geen botsing, dus aan elkaar.',
        },
        {
          q: 'Plak aan elkaar: *ge* + *e-maild*',
          before: 'Ik heb u gisteren al',
          after: '.',
          a: 'ge-e-maild',
          why: 'ge + e-maild: e-mail begint met een losse letter. Dan komt er na ge- ook een koppelteken: ge-e-maild, met twee koppeltekens. Zo blijft e-mail herkenbaar.',
        },
        {
          q: 'Schrijf de samenstelling: meervoud van *idee* + bus',
          before: 'Stop je voorstel in de',
          after: 'bij de kantine.',
          a: 'ideeënbus',
          why: 'ideeën met trema (idee + en), en de samenstelling schrijf je aan elkaar.',
        },
        { q: 'Meervoud: iemand die niet rookt', before: 'Deze kamers zijn alleen voor', after: '.', a: 'niet-rokers', why: 'niet- + zelfstandig naamwoord: koppelteken. niet-roker, niet-rokers.' },
        {
          q: 'Maak korter: de ingang en de uitgang',
          before: 'Tijdens de verbouwing zijn de',
          after: 'aan de achterkant.',
          say: 'in- en uitgang',
          a: 'in- en uitgang',
          also: ['in- en de uitgang'],
          why: 'in- staat voor ingang. Het koppelteken zit vast aan in, en dan komt een spatie.',
        },
        { q: 'Het feest aan het eind van de ramadan: suiker + feest', before: 'Na de ramadan vieren we het', after: 'met de hele familie.', a: 'Suikerfeest', why: 'Een feestdag is een naam: hoofdletter.' },
        {
          q: 'Iemand die vroeger je collega was. Gebruik *oud*.',
          before: 'Mijn',
          after: 'Sanne heeft me getipt voor deze baan.',
          a: 'oud-collega',
          why: 'oud- in de betekenis van vroeger: koppelteken.',
        },
        {
          q: 'De zee tussen Nederland en Engeland',
          before: 'In de zomer zwemmen we in de',
          after: '.',
          a: 'Noordzee',
          why: 'Eén naam: aan elkaar, met hoofdletter. zee is geen naam, dus geen koppelteken.',
        },
        { q: 'Schrijf kort: de jas van Thomas', before: 'Is dit', after: 'jas?', a: 'Thomas’', why: 'Thomas eindigt op s: alleen een apostrof.' },
        { q: 'Schrijf de samenstelling: zonne + energie', before: 'Met de panelen op ons dak wekken we', after: 'op.', a: 'zonne-energie', why: 'zonne + energie: e + e botsen. Koppelteken, net als zee-egel.' },
        {
          q: 'Maak korter: tuinstoelen en tuintafels',
          before: 'Deze week in de aanbieding: alle',
          after: '.',
          a: 'tuinstoelen en -tafels',
          why: 'Van tuintafels valt het eerste deel weg. Dan staat het koppelteken vóór het deel dat overblijft: en -tafels.',
        },
        { q: 'Vul het woord in dat past', before: 'Er is nog maar', after: 'parkeerplaats vrij, niet twee.', a: 'één', why: 'Het gaat om het getal (niet twee): accenten op allebei de e’s.' },
        {
          q: 'Schrijf het werkwoord: mee + eten',
          before: 'Mijn schoonouders komen zondag',
          after: '.',
          say: 'mee-eten',
          a: 'mee-eten',
          why: 'mee + eten: e + e botsen. Koppelteken. Een trema komt alleen binnen één woord, zoals in zeeën.',
        },
        {
          q: 'Meervoud van tv + programma',
          before: 'Mijn moeder kijkt elke avond naar Turkse',
          after: '.',
          a: 'tv-programma’s',
          why: 'tv is een afkorting: koppelteken. programma eindigt op a: meervoud met ’s.',
        },
        { q: 'Meervoud van *café*', before: 'In onze straat zijn drie nieuwe', after: 'geopend.', a: 'cafés', why: 'Na é gewoon -s, zonder apostrof. Het accent blijft staan.' },
        { q: 'Schrijf de samenstelling: ex + vrouw', before: 'Mijn', after: 'haalt de kinderen vrijdag op.', a: 'ex-vrouw', why: 'ex- krijgt altijd een koppelteken: ex-vrouw, ex-man.' },
        {
          q: 'De naam van het zuidoosten van Azië (Thailand, Vietnam)',
          before: 'Mijn collega reist drie weken door',
          after: '.',
          say: 'Zuidoost-Azië',
          a: 'Zuidoost-Azië',
          why: 'Zuidoost is één deel, met een hoofdletter. Dan een koppelteken voor de naam. Azië met trema.',
        },
        { q: 'Vul *officieel* in de goede vorm in', before: 'U krijgt de', after: 'uitslag per post.', a: 'officiële', why: 'officieel + e wordt officiële: trema op de e.' },
      ],
      done: {
        title: 'Reeks klaar',
        text: 'Basis: aan elkaar. Koppelteken bij botsing, afkorting, naam, ex-/oud-/niet- en weglating. En vergeet de hoofdletters, het trema en de apostrof niet.',
      },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de brief aan. Typ elk woord helemaal.',
      intro: 'Hoofdletters tellen mee. Kijk goed naar de zin om het gat heen.',
      title: 'Brief van de woningcorporatie',
      caps: true,
      text: 'Beste bewoners,\n\nVanaf maandag 13 april leggen we zonnepanelen op alle daken in de Kerkstraat. Het werk doet een bedrijf uit {Zuid-Limburg|het zuiden van Limburg|Windstreek + naam van een gebied: koppelteken en twee hoofdletters.}. Met {zonne-energie|zon + energie|zonne + energie: e + e botsen. Koppelteken.} wordt uw {energierekening|energie + rekening|e + r botsen niet. Gewone samenstelling: aan elkaar.} lager.\n\nTijdens het werk is de {in- en uitgang|ingang en uitgang, korter|in- staat voor ingang: koppelteken vast aan in, dan een spatie.} aan de voorkant dicht. Gebruik dan de achterdeur bij het {fietsenrek~fietsrek|rek voor fietsen|Eén ding, geen botsing: aan elkaar.}. Op {zon- en feestdagen|zondagen en feestdagen, korter|zon- staat voor zondagen: koppelteken, dan een spatie.} werken we niet, dus ook niet op {Koningsdag|27 april|Een feestdag is een naam: hoofdletter. Eén woord.}.\n\nLet op: in de parkeergarage waren deze maand drie {auto-inbraken|auto + inbraken|auto + inbraken: o + i lees je als oi. Koppelteken.}. Laat geen tas in uw auto liggen en zet uw {autoalarm|auto + alarm|o + a is geen klank: aan elkaar, zonder streepje.} aan.\n\nOp woensdag 22 april is er een bewonersavond in het buurthuis. Ook onze {oud-voorzitter~ex-voorzitter|vroegere voorzitter|oud- in de betekenis van vroeger: koppelteken.}, mevrouw Bakker, is er. We horen graag uw {ideeën|meervoud van idee|idee + en: trema op de laatste e.} over de nieuwe tuin. Er is koffie en {Turkse|uit Turkije|Een bijvoeglijk naamwoord van een land: hoofdletter.} thee.\n\nVragen? Bel onze huismeester, meneer {De Vries|Jan de Vries|Zonder voornaam krijgt het tussenvoegsel een hoofdletter.}, of stuur hem een {sms’je|verkleinwoord van sms|Afkorting + uitgang: apostrof.}. {’s Avonds|in de avond|Apostrof voor de weggelaten letters. Begin van de zin: hoofdletter op avonds.} is hij niet bereikbaar. Liever mailen? Ons nieuwe {e-mailadres|e + mail + adres|Een losse letter + woord: koppelteken. adres plak je eraan vast.} staat op de website.\n\nMet vriendelijke groet,\nWoonstichting De Linde',
      why: 'Koppelteken: Zuid-Limburg (naam), zonne-energie en auto-inbraken (klinkers botsen), in- en uitgang en zon- en feestdagen (weggelaten deel), oud-voorzitter en e-mailadres. Aan elkaar: energierekening, fietsenrek en autoalarm. Verder: Koningsdag, Turkse en De Vries (hoofdletter), ideeën (trema), sms’je en ’s Avonds (apostrof).',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort zes zinnen. Hoofdletters en leestekens tellen mee.',
      title: 'Nieuws van Sanne',
      sentences: [
        'Mijn ex-collega Sanne werkt sinds de zomer in de auto-industrie in Zuid-Duitsland.',
        'Gisteren stuurde ze ons een lange e-mail met foto’s van haar nieuwe kantoor.',
        'Ze ontwerpt daar kleine auto’s op zonne-energie.',
        'Op zon- en feestdagen maakt ze lange fietstochten in het Zwarte Woud.',
        'In november praat ze in een Nederlands tv-programma over haar werk.',
        'Haar nieuwe e-mailadres kun je ’s avonds aan mij vragen.',
      ],
      right: 'Alles goed: ex-collega, auto-industrie, Zuid-Duitsland, e-mail, zonne-energie, tv-programma en e-mailadres met koppelteken, zon- en feestdagen met weglating, het Zwarte Woud met twee hoofdletters, en foto’s, auto’s en ’s avonds met apostrof.',
      wrong: 'Kijk deze woorden na: ex-collega, auto-industrie en zonne-energie (koppelteken), Zuid-Duitsland (naam: twee hoofdletters en koppelteken), zon- en feestdagen (koppelteken, dan een spatie), tv-programma, e-mail en e-mailadres (afkorting of letter), foto’s, auto’s en ’s avonds (apostrof), zomer en november (klein), Nederlands en het Zwarte Woud (groot).',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk het bericht na voordat het naar het team gaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'Team werkplaats', subject: 'Ahmed komt terug' },
      greeting: 'Hallo allemaal,',
      signoff: 'Groet,\nFatima',
      tokens: [
        { t: 'Vanaf' },
        { t: 'Dinsdag', fix: 'dinsdag', why: 'Dagen van de week schrijf je klein.' },
        { t: 'komt' },
        { t: 'onze' },
        { t: 'ex collega', fix: 'ex-collega', why: 'ex- krijgt altijd een koppelteken.' },
        { t: 'Ahmed' },
        { t: 'ons' },
        { t: 'weer' },
        { t: 'helpen.' },
        { t: 'Hij' },
        { t: 'woont' },
        { t: 'nu' },
        { t: 'in' },
        { t: 'Noord Brabant,', fix: 'Noord-Brabant,', why: 'Noord hoort bij de naam van de provincie: koppelteken.' },
        { t: 'maar' },
        { t: 'hij' },
        { t: 'rijdt' },
        { t: 'twee' },
        { t: 'keer' },
        { t: 'per' },
        { t: 'week' },
        { t: 'naar' },
        { t: 'ons' },
        { t: 'toe.' },
        { t: 'Ahmed' },
        { t: 'weet' },
        { t: 'alles' },
        { t: 'van' },
        { t: 'auto onderdelen', fix: 'auto-onderdelen', why: 'Eén samenstelling waarin o + o botsen: koppelteken.' },
        { t: 'en' },
        { t: 'van' },
        { t: 'elk' },
        { t: 'autoalarm.', trap: 'Goed: o + a is geen klank. Je leest het ook zonder streepje goed, dus aan elkaar.' },
        { t: 'Klanten' },
        { t: 'met' },
        { t: 'vragen' },
        { t: 'over' },
        { t: 'laadpalen' },
        { t: 'en' },
        { t: 'zonne energie', fix: 'zonne-energie', why: 'Eén samenstelling waarin e + e botsen: koppelteken.' },
        { t: 'stuur' },
        { t: 'je' },
        { t: 'naar' },
        { t: 'hem' },
        { t: 'door.' },
        { t: 'Let' },
        { t: 'op:' },
        { t: 'de', trap: 'Goed: na een dubbele punt schrijf je klein, behalve bij een citaat of een naam.' },
        { t: 'in', fix: 'in-', why: 'in- staat voor ingang. Het koppelteken laat zien dat er een deel weg is.' },
        { t: 'en' },
        { t: 'uitgang' },
        { t: 'van' },
        { t: 'de' },
        { t: 'werkplaats' },
        { t: 'zijn' },
        { t: 'tot' },
        { t: 'vrijdag' },
        { t: 'dicht.' },
        { t: 'Gebruik' },
        { t: 'de' },
        { t: 'deur' },
        { t: 'bij' },
        { t: 'de' },
        { t: 'klanten-service.', fix: 'klantenservice.', why: 'Gewone samenstelling zonder botsing of afkorting: aan elkaar.' },
        { t: 'Ook' },
        { t: 'de' },
        { t: 'politie-agent', fix: 'politieagent', why: 'e + a is geen klank: aan elkaar, zonder streepje.' },
        { t: 'die' },
        { t: 'zijn' },
        { t: 'auto' },
        { t: 'komt' },
        { t: 'ophalen,' },
        { t: 'moet' },
        { t: 'daar' },
        { t: 'naar' },
        { t: 'binnen.' },
        { t: 'Betalen' },
        { t: 'kan' },
        { t: 'alleen' },
        { t: 'met' },
        { t: 'een' },
        { t: 'pinpas.', trap: 'Goed: pin zeg je als een gewoon woord, niet letter voor letter. Dus aan elkaar.' },
        { t: 'Vragen?' },
        { t: 'Stuur' },
        { t: 'me' },
        { t: 'een' },
        { t: 'sms’je', trap: 'Goed: afkorting + uitgang krijgt een apostrof. Een koppelteken komt alleen voor een heel woord: sms-bericht.' },
        { t: 'of' },
        { t: 'mail' },
        { t: 'naar' },
        { t: 'mijn' },
        { t: 'nieuwe' },
        { t: 'e-mail adres.', fix: 'e-mailadres.', why: 'Eén samenstelling: e-mail + adres schrijf je aan elkaar, met alleen het koppelteken na de e.' },
      ],
      done: {
        title: 'Klaar om te versturen',
        text: 'dinsdag, ex-collega, Noord-Brabant, auto-onderdelen, zonne-energie, in- en uitgang, klantenservice, politieagent en e-mailadres. autoalarm, de na de dubbele punt, pinpas en sms’je waren al goed.',
      },
    },
  ],
};
