import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": de toets met alfabet, hoofdletters, accenten, trema, apostrof en koppelteken door elkaar. */
export const LES_L27: LessonInput = {
  id: 'l27',
  stage: 'toets',
  domain: 'orth',
  also: ['morf'],
  title: 'Toets: De letter',
  skill: 'Spelling',
  icon: 'Aa’',
  steps: [
    {
      kind: 'explain',
      id: 'overzicht',
      title: 'Alle regels op een rij',
      panels: [
        {
          text: 'Het alfabet heeft 26 letters. In een woordenlijst staat *ij* als *i* + *j*: *ijs* staat na *iglo* en vóór *ik*. Accenten tellen niet mee bij het ordenen: *café* staat op de plek van *cafe*. En in een Nederlandse telefoonlijst staan achternamen met *de*, *van* of *van der* bij het hoofdwoord: *Vries, de* vind je bij de V.',
          rule: 'Ordenen: *ij* = *i* + *j*, accenten tellen niet, *de Vries* staat bij de V.',
          quiz: {
            q: 'Welke rij staat in de volgorde van de woordenlijst?',
            options: ['idee – ijs – ik', 'idee – ik – ijs', 'ijs – idee – ik'],
            answer: 'idee – ijs – ik',
            why: 'id, ij, ik: de tweede letter beslist, en ij telt als i + j. De j komt vóór de k.',
          },
        },
        {
          text: 'Een hoofdletter krijgen: het begin van een zin; namen van personen, dieren, straten, plaatsen, landen en rivieren; talen en inwoners (*Nederlands*, *een Marokkaan*); bijvoeglijke naamwoorden van namen (*Turkse thee*); feestdagen (*Pasen*, *Suikerfeest*, *Koningsdag*); instellingen (*de Belastingdienst*). Klein blijven: dagen, maanden en seizoenen (*maandag*, *januari*, *zomer*), windstreken (*het noorden*) en titels (*koning Willem-Alexander*, *dokter Jansen*). Tussenvoegsels: *Jan de Vries*, maar *meneer De Vries*. En *IJ* is één letter: *IJsland*, *IJmuiden*.',
          rule: 'Namen, talen, inwoners en feestdagen: hoofdletter. Dagen, maanden, seizoenen en titels: klein.',
          quiz: {
            q: 'Welke zin is goed?',
            options: [
              'Op maandag vieren we Pasen bij meneer De Vries.',
              'Op Maandag vieren we pasen bij meneer de Vries.',
              'Op maandag vieren we Pasen bij Meneer de Vries.',
            ],
            answer: 'Op maandag vieren we Pasen bij meneer De Vries.',
            why: 'maandag klein, Pasen groot. meneer is een gewoon woord, en zonder voornaam krijgt de in De Vries een hoofdletter.',
          },
        },
        {
          text: 'Een klemtoonaccent zet je alleen als het nodig is voor de betekenis: *één* (het getal) tegenover *een*, *vóór* tegenover *voor*. In leenwoorden hoort het accent bij het woord: *café*, *privé*, *crème*, *scène*. Het trema staat op de eerste klinker van een nieuwe lettergreep als je de klinkers anders samen zou lezen: *ideeën*, *België*, *geïnteresseerd*, *financiële*. Maar niet als je het woord ook zo goed leest: *geopend*, *beantwoorden*.',
          rule: 'Accent: alleen voor nadruk of in leenwoorden (*café*). Trema: twee klinkers los, binnen één woord (*ideeën*).',
          quiz: {
            q: 'Welke rij is helemaal goed?',
            options: ['café – ideeën – geopend', 'cafe – ideeën – geöpend', 'café – ideeen – geopend'],
            answer: 'café – ideeën – geopend',
            why: 'café met accent, ideeën met trema, en geopend zonder trema: eo is geen klank.',
          },
        },
        {
          text: 'De apostrof: meervoud met *’s* na *a*, *i*, *o*, *u* en *y* (*auto’s*, *menu’s*, *baby’s*), maar niet na *é*, een doffe *e* of *eau* (*cafés*, *tantes*, *cadeaus*). Bezit bij een naam: *Anna’s*, maar *Jans* en *Sannes*, en na *s*, *x*, *z* alleen *’* (*Max’ jas*). Weggelaten letters: *’s avonds*, *zo’n*, *m’n*. Afkortingen: *tv’s*, *sms’je*. Verkleinwoord: *baby’tje*, maar *autootje*.',
          rule: 'Apostrof alleen na *a, i, o, u, y*, bij afkortingen, en waar letters weg zijn.',
          quiz: {
            q: 'Welke rij is helemaal goed?',
            options: ['auto’s – cafés – Max’ jas', 'auto’s – café’s – Maxs jas', 'autos – cafés – Max’s jas'],
            answer: 'auto’s – cafés – Max’ jas',
            why: 'auto eindigt op o: ’s. café eindigt op é: gewoon s. Max eindigt op x: alleen een apostrof.',
          },
        },
        {
          text: 'Het koppelteken: een samenstelling schrijf je in principe *aan elkaar* (*ziekenhuis*, *fietsenrek*). Een koppelteken komt er alleen bij botsende klinkers (*zee-egel*, *auto-ongeluk*), bij een afkorting, letter of cijfer (*tv-gids*, *e-mail*, *06-nummer*), bij *Noord-*, *Zuid-*, *Oost-* en *West-* voor een naam (*Noord-Holland*), na *ex-*, *oud-* en *niet-* (*ex-man*), bij weglating (*in- en uitgang*) en bij twee gelijkwaardige delen (*Nederlands-Belgisch*).',
          rule: 'Basis: aan elkaar. Koppelteken bij botsing, afkorting of cijfer, naam, *ex-*/*oud-*/*niet-*, weglating of twee gelijke delen.',
          quiz: {
            q: 'Welke rij is helemaal goed?',
            options: ['ziekenhuis – zee-egel – tv-gids', 'zieken huis – zee-egel – tv gids', 'ziekenhuis – zeeëgel – tvgids'],
            answer: 'ziekenhuis – zee-egel – tv-gids',
            why: 'ziekenhuis aan elkaar, zee-egel met koppelteken (twee woorden die botsen) en tv-gids met koppelteken (afkorting).',
          },
        },
      ],
    },
    {
      kind: 'swipe',
      id: 'alles-door-elkaar',
      prompt: 'Klopt de zin?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in zit. Let op hoofdletters én tekens.',
      cards: [
        { t: 'Mijn buurvrouw spreekt Arabisch, Turks en een beetje Pools.', ok: true, why: 'Talen krijgen een hoofdletter.' },
        {
          t: 'In de Zomervakantie gaan we naar IJsland.',
          ok: false,
          fix: 'Zomervakantie → zomervakantie',
          why: 'Een seizoen schrijf je klein, ook in een samenstelling. IJsland is goed: IJ is één letter.',
        },
        { t: 'Hij zei: ‘Kom maar binnen.’', ok: true, why: 'Na een dubbele punt klein, behalve bij een letterlijk citaat. Dat begint met een hoofdletter.' },
        { t: 'Er zijn in deze straat drie café’s.', ok: false, fix: 'café’s → cafés', why: 'Na een é gewoon -s, zonder apostrof.' },
        { t: 'Mevrouw van Dijk is onze nieuwe buurvrouw.', ok: false, fix: 'van Dijk → Van Dijk', why: 'Zonder voornaam krijgt het tussenvoegsel een hoofdletter: mevrouw Van Dijk.' },
        { t: 'Ze heeft haar contract vorige week beëindigd.', ok: true, why: 'be + eindigd: trema op de e.' },
        {
          t: 'Er staat nog een geöpende fles wijn in de koelkast.',
          ok: false,
          fix: 'geöpende → geopende',
          why: 'eo is geen klank: je leest het woord ook zonder trema goed. Dus geen trema.',
        },
        { t: 'Op Koningsdag verkopen de kinderen hun oude speelgoed.', ok: true, why: 'Koningsdag is een feestdag: hoofdletter.' },
        {
          t: 'Mijn ex-collega’s uit Noord-Holland komen ook.',
          ok: true,
          why: 'ex- met koppelteken, en collega eindigt op a: ’s. Noord-Holland: naam met koppelteken en twee hoofdletters.',
        },
        { t: 'De dokter zegt dat er een reele kans op herstel is.', ok: false, fix: 'reele → reële', why: 'reëel + e wordt reële: trema op de tweede e, anders lees je ee.' },
        { t: 'Max’ moeder werkt bij de Belastingdienst.', ok: true, why: 'Max eindigt op x: alleen een apostrof. De Belastingdienst is een instelling: hoofdletter.' },
        {
          t: 'In de kerstvakantie gaan we naar mijn schoonouders in Den Bosch.',
          ok: true,
          why: 'kerstvakantie is een samenstelling met een feestdag: klein. Den Bosch is een plaatsnaam: Den met hoofdletter.',
        },
        { t: 'De vergadering is op Dinsdag 3 maart.', ok: false, fix: 'Dinsdag → dinsdag', why: 'Dagen schrijf je klein, ook in een datum.' },
        { t: 'Hij is moslim en viert het Suikerfeest met zijn familie.', ok: true, why: 'Een gelovige schrijf je klein (moslim), een feestdag groot (Suikerfeest).' },
        {
          t: 'Kun je de kopieën op A4 formaat maken?',
          ok: false,
          fix: 'A4 formaat → A4-formaat',
          why: 'Letter en cijfer + woord: koppelteken. kopieën is goed: trema.',
        },
      ],
    },
    {
      kind: 'choice',
      id: 'suikerfeest',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'Volgende week vieren we het',
      after: 'met de hele familie.',
      options: ['suikerfeest', 'Suikerfeest', 'Suiker feest', 'suiker-feest'],
      answer: 'Suikerfeest',
      why: 'Een feestdag krijgt een hoofdletter, net als Pasen, Kerstmis en Koningsdag. Het is één samenstelling: aan elkaar.',
    },
    {
      kind: 'order',
      id: 'telefoonlijst',
      prompt: 'Zet de achternamen in de volgorde van een Nederlandse telefoonlijst.',
      tiles: ['Jansen', 'De Boer', 'Van Dijk', 'Smit', 'Bakker', 'Van den Berg'],
      answer: 'Bakker Van den Berg De Boer Van Dijk Jansen Smit',
      why: 'In Nederland orden je op het hoofdwoord: Bakker, Berg (Van den), Boer (De), Dijk (Van), Jansen, Smit. Berg komt vóór Boer: e vóór o. De tussenvoegsels tellen niet mee. Zonder voornaam krijgt het eerste woordje een hoofdletter.',
    },
    {
      kind: 'choice',
      id: 'derde-woord',
      prompt: 'Zet in gedachten in de volgorde van de woordenlijst: iets, ik, ijzer, idee. Welk woord komt als derde?',
      before: '',
      after: '',
      options: ['iets', 'ik', 'ijzer', 'idee'],
      answer: 'ijzer',
      why: 'idee (id), iets (ie), ijzer (ij), ik (ik). ij telt als i + j, en de j staat vóór de k.',
    },
    {
      kind: 'type',
      id: 'een-getal',
      prompt: 'Typ het woord dat past.',
      before: 'Ik heb maar',
      after: 'kaartje gekocht, niet twee.',
      hint: '',
      answer: 'één',
      why: 'Het gaat om het getal: niet twee. Dan zet je accenten op allebei de e’s: één.',
    },
    {
      kind: 'fix',
      id: 'beinvloeden',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Een negatieve beoordeling kan je carrière sterk beinvloeden.',
      wrong: 7,
      answer: 'beïnvloeden',
      why: 'be + invloeden: zonder trema lees je ei. Trema op de i. beoordeling (eo is geen klank) en carrière (accent) waren al goed.',
    },
    {
      kind: 'sort',
      id: 'welk-teken',
      prompt: 'Welk teken heb je nodig?',
      buckets: ['trema', 'apostrof', 'koppelteken', 'geen teken'],
      items: [
        { t: 'meervoud van knie', b: 0 },
        { t: 'meervoud van baby', b: 1 },
        { t: 'auto + industrie', b: 2 },
        { t: 'meervoud van cadeau', b: 3 },
        { t: 'be + eindigen', b: 0 },
        { t: 'verkleinwoord van sms', b: 1 },
        { t: 'oud + burgemeester', b: 2 },
        { t: 'ge + opend', b: 3 },
        { t: 'officieel met -e', b: 0 },
        { t: 'de tas van Inez, kort', b: 1 },
        { t: 'cd + speler', b: 2 },
        { t: 'verkleinwoord van auto', b: 3 },
        { t: 'een inwoner van Indonesië', b: 0 },
        { t: 'meervoud van paraplu', b: 1 },
        { t: 'Zuid + Afrikaans', b: 2 },
        { t: 'foto + album', b: 3 },
      ],
      why: 'Trema: knieën, beëindigen, officiële, Indonesiër. Apostrof: baby’s, sms’je, Inez’ tas, paraplu’s. Koppelteken: auto-industrie, oud-burgemeester, cd-speler, Zuid-Afrikaans. Geen teken: cadeaus, geopend, autootje, fotoalbum.',
    },
    {
      kind: 'proofread',
      id: 'mail-gemeente',
      prompt: 'Lees de mail aan de gemeente na',
      intro: 'Let op hoofdletters en accenten. Tik elke fout aan.',
      header: { to: 'Gemeente, afdeling Burgerzaken', subject: 'Verhuizing' },
      greeting: 'Geachte heer, mevrouw,',
      tokens: [
        { t: 'Op' },
        { t: 'maandag' },
        { t: '3' },
        { t: 'Maart', fix: 'maart', why: 'Maanden schrijf je klein.' },
        { t: 'verhuis' },
        { t: 'ik' },
        { t: 'van' },
        { t: 'Rotterdam' },
        { t: 'naar' },
        { t: 'utrecht.', fix: 'Utrecht.', why: 'Een plaatsnaam krijgt een hoofdletter.' },
        { t: 'Ik' },
        { t: 'ben' },
        { t: 'geboren' },
        { t: 'in' },
        { t: 'marokko', fix: 'Marokko', why: 'Een land krijgt een hoofdletter.' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'spreek' },
        { t: 'Nederlands' },
        { t: 'en' },
        { t: 'arabisch.', fix: 'Arabisch.', why: 'Een taal krijgt een hoofdletter.' },
        { t: 'Kan' },
        { t: 'ik' },
        { t: 'op' },
        { t: 'Dinsdag', fix: 'dinsdag', why: 'Dagen van de week schrijf je klein.' },
        { t: 'langskomen' },
        { t: 'om' },
        { t: 'mijn' },
        { t: 'adres' },
        { t: 'door' },
        { t: 'te' },
        { t: 'geven?' },
        { t: 'Mijn' },
        { t: 'vrouw' },
        { t: 'komt' },
        { t: 'een' },
        { t: 'week' },
        { t: 'later,' },
        { t: 'want' },
        { t: 'ze' },
        { t: 'werkt' },
        { t: 'tot' },
        { t: 'de' },
        { t: 'zomer' },
        { t: 'nog' },
        { t: 'in' },
        { t: 'een' },
        { t: 'cafe', fix: 'café', why: 'café is een leenwoord met een vast accent.' },
        { t: 'in' },
        { t: 'Rotterdam.' },
        { t: 'Met' },
        { t: 'vriendelijke' },
        { t: 'groet,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Klaar voor de gemeente',
        text: 'maart en dinsdag klein; Utrecht, Marokko en Arabisch met een hoofdletter; café met accent. zomer was al goed: seizoenen blijven klein.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-verjaardag',
      prompt: 'Luister en typ de zin precies over.',
      intro: 'Hoofdletters, accenten, trema’s en apostrofs tellen allemaal mee.',
      sentence: 'Op de eerste maandag van juni vieren we Anna’s verjaardag in een Turks café in België.',
      right: 'Goed: maandag en juni klein, Anna’s met apostrof, Turks met hoofdletter, café met accent en België met hoofdletter en trema.',
      wrong: 'Loop de zin na: maandag en juni (klein), Anna’s (naam op a: ’s), Turks (komt van een naam: groot), café (accent) en België (hoofdletter en trema).',
    },
    {
      kind: 'speed',
      id: 'snel-aan-elkaar',
      prompt: 'Aan elkaar of los?',
      intro: 'Snel: is het één samenstelling of zijn het twee woorden?',
      seconds: 30,
      items: [
        { a: 'eigen', b: 'bijdrage', joined: false, tip: 'de eigen bijdrage: twee woorden.' },
        { a: 'klanten', b: 'service', joined: true, tip: 'klantenservice.' },
        { a: 'belasting', b: 'aangifte', joined: true, tip: 'belastingaangifte: g + a botsen niet.' },
        { a: 'vaste', b: 'klant', joined: false, tip: 'een vaste klant: twee woorden.' },
        { a: 'verjaardags', b: 'cadeau', joined: true, tip: 'verjaardagscadeau.' },
        { a: 'nieuwe', b: 'baan', joined: false, tip: 'Bijvoeglijk naamwoord + zelfstandig naamwoord: los.' },
        { a: 'zorg', b: 'toeslag', joined: true, tip: 'zorgtoeslag.' },
        { a: 'gemeente', b: 'raad', joined: true, tip: 'gemeenteraad: e + r botsen niet.' },
        { a: 'grote', b: 'broer', joined: false, tip: 'mijn grote broer: twee woorden.' },
        { a: 'kinder', b: 'opvang', joined: true, tip: 'kinderopvang: r + o botsen niet.' },
        { a: 'zonne', b: 'bril', joined: true, tip: 'zonnebril.' },
        { a: 'heel', b: 'goed', joined: false, tip: 'heel goed: los.' },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje-collega',
      prompt: 'Lees het appje na',
      intro: 'Sara appt haar collega Mo. Let op de apostrof, het trema en het koppelteken. Tik elke fout aan.',
      header: { to: 'Mo' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Mo!' },
        { t: 'Ik' },
        { t: 'sta' },
        { t: 'in' },
        { t: 'de' },
        { t: 'file' },
        { t: 'door' },
        { t: 'een' },
        { t: 'autoongeluk.', fix: 'auto-ongeluk.', why: 'auto + ongeluk: o + o botsen. Koppelteken.' },
        { t: 'Dat' },
        { t: 'gebeurt' },
        { t: 'hier' },
        { t: 's', fix: '’s', why: '’s ochtends: apostrof voor de weggelaten letters.' },
        { t: 'ochtends' },
        { t: 'vaak.' },
        { t: 'Kun' },
        { t: 'jij' },
        { t: 'de' },
        { t: 'vergadering' },
        { t: 'openen?' },
        { t: 'De' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: trema op de laatste e.' },
        { t: 'voor' },
        { t: 'het' },
        { t: 'project' },
        { t: 'staan' },
        { t: 'in' },
        { t: 'm’n' },
        { t: 'mail.' },
        { t: 'Thomas’' },
        { t: 'laptop' },
        { t: 'ligt' },
        { t: 'op' },
        { t: 'mijn' },
        { t: 'bureau.' },
        { t: 'Zet' },
        { t: 'je' },
        { t: 'de' },
        { t: 'koffie-machine', fix: 'koffiemachine', why: 'e + m botsen niet: een samenstelling schrijf je aan elkaar.' },
        { t: 'aan?' },
        { t: 'En' },
        { t: 'stuur' },
        { t: 'je' },
        { t: 'me' },
        { t: 'de' },
        { t: 'fotos', fix: 'foto’s', why: 'foto eindigt op o: meervoud met ’s.' },
        { t: 'van' },
        { t: 'gisteren?' },
        { t: 'Groetjes,' },
        { t: 'Sara' },
      ],
      done: {
        title: 'Appje verbeterd',
        text: 'auto-ongeluk, ’s ochtends, ideeën, koffiemachine en foto’s. m’n mag in een appje, en Thomas’ laptop was al goed.',
      },
    },
    {
      kind: 'type',
      id: 'noord-brabant',
      prompt: 'Typ de naam van de provincie waarin Eindhoven en Tilburg liggen.',
      before: 'Eindhoven ligt in de provincie',
      after: '.',
      hint: '',
      answer: 'Noord-Brabant',
      why: 'Noord + een aardrijkskundige naam: koppelteken, en allebei met een hoofdletter.',
    },
    {
      kind: 'rewrite',
      id: 'hoofdletters',
      prompt: 'Zet alle hoofdletters goed.',
      source: '’s zondags eten we met dokter van dijk en zijn vrouw in een turks restaurant in den haag.',
      accept: ['’s Zondags eten we met dokter Van Dijk en zijn vrouw in een Turks restaurant in Den Haag.'],
      why: '’s Zondags: de zin begint met ’s, dus het tweede woord krijgt de hoofdletter. dokter is een titel: klein. Van Dijk: geen voornaam ervoor, dus ook Van met hoofdletter. Turks komt van een naam. Den Haag: plaatsnaam.',
    },
    {
      kind: 'proofread',
      id: 'boodschappenlijst',
      prompt: 'Lees de boodschappenlijst na',
      intro: 'Tik elke fout aan.',
      header: { subject: 'Boodschappen voor zaterdag' },
      tokens: [
        { t: 'zes' },
        { t: 'eieren,' },
        { t: 'twee' },
        { t: 'pizzas,', fix: 'pizza’s,', why: 'pizza eindigt op a: ’s.' },
        { t: 'mango’s,' },
        { t: 'kiwis,', fix: 'kiwi’s,', why: 'kiwi eindigt op i: ’s.' },
        { t: 'turkse', fix: 'Turkse', why: 'Een bijvoeglijk naamwoord van een naam (Turkije) krijgt een hoofdletter.' },
        { t: 'yoghurt,' },
        { t: 'Italiaanse' },
        { t: 'pasta,' },
        { t: 'Franse' },
        { t: 'kaas,' },
        { t: 'zonnebloem-olie,', fix: 'zonnebloemolie,', why: 'm + o botsen niet: aan elkaar.' },
        { t: 'drie' },
        { t: 'avocados', fix: 'avocado’s', why: 'avocado eindigt op o: ’s.' },
        { t: 'en' },
        { t: 'een' },
        { t: 'tv-gids.' },
      ],
      done: {
        title: 'De lijst klopt',
        text: 'pizza’s, kiwi’s, Turkse, zonnebloemolie en avocado’s. mango’s, Italiaanse, Franse en tv-gids waren al goed.',
      },
    },
    {
      kind: 'bet',
      id: 'zomers',
      prompt: 'Welke zin is helemaal goed?',
      options: ['’S zomers gaan we naar Italië.', '’s zomers gaan we naar Italië.', '’s Zomers gaan we naar Italië.', '’s Zomers gaan we naar Italie.'],
      answer: '’s Zomers gaan we naar Italië.',
      why: 'Begint de zin met ’s, dan krijgt het tweede woord de hoofdletter. Italië heeft een trema.',
    },
    {
      kind: 'type',
      id: 'thomas',
      prompt: 'Schrijf het bezit kort op: de telefoon van Thomas.',
      before: 'Dit is',
      after: 'telefoon.',
      hint: '',
      answer: 'Thomas’',
      why: 'Thomas eindigt op s: alleen een apostrof. Thomas’ telefoon.',
    },
    {
      kind: 'dictation',
      id: 'dictee-tv',
      prompt: 'Luister en typ de zin precies over.',
      intro: 'Een moeilijke: apostrofs, koppeltekens en hoofdletters.',
      sentence: '’s Avonds kijken mijn ex-collega’s naar een Zuid-Afrikaans tv-programma over de ideeën van de oud-burgemeester.',
      right: 'Goed: ’s Avonds, ex-collega’s (koppelteken én apostrof), Zuid-Afrikaans, tv-programma, ideeën en oud-burgemeester.',
      wrong: 'Loop de zin na: ’s Avonds (hoofdletter op het tweede woord), ex-collega’s (ex- met koppelteken, collega op a: ’s), Zuid-Afrikaans (naam), tv-programma (afkorting), ideeën (trema) en oud-burgemeester (oud- = vroeger).',
    },
    {
      kind: 'proofread',
      id: 'uitnodiging',
      prompt: 'Lees de uitnodiging na',
      intro: 'Let op hoofdletters, apostrofs, het trema en aan elkaar schrijven. Tik elke fout aan.',
      header: { to: 'de buren', subject: 'Uitnodiging' },
      greeting: 'Beste buren,',
      tokens: [
        { t: 'Op' },
        { t: 'zaterdag' },
        { t: '12' },
        { t: 'Juli', fix: 'juli', why: 'Maanden schrijf je klein.' },
        { t: 'vieren' },
        { t: 'we' },
        { t: 'Annas', fix: 'Anna’s', why: 'Anna eindigt op a: bezit met ’s.' },
        { t: 'verjaardag' },
        { t: 'in' },
        { t: 'het' },
        { t: 'buurthuis.' },
        { t: 'Het' },
        { t: 'feest' },
        { t: 'begint' },
        { t: 's', fix: '’s', why: '’s avonds: apostrof voor de weggelaten letters.' },
        { t: 'avonds' },
        { t: 'om' },
        { t: 'acht' },
        { t: 'uur.' },
        { t: 'Er' },
        { t: 'is' },
        { t: 'muziek,' },
        { t: 'een' },
        { t: 'springkussen' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'kinderen' },
        { t: 'en' },
        { t: 'eten' },
        { t: 'van' },
        { t: 'een' },
        { t: 'Surinaams-Chinese' },
        { t: 'kok.' },
        { t: 'We' },
        { t: 'zijn' },
        { t: 'benieuwd' },
        { t: 'naar' },
        { t: 'jullie' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: trema op de laatste e.' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'muziek.' },
        { t: 'Je' },
        { t: 'fiets' },
        { t: 'kun' },
        { t: 'je' },
        { t: 'kwijt' },
        { t: 'in' },
        { t: 'het' },
        { t: 'fietsen-rek', fix: 'fietsenrek', why: 'Een gewone samenstelling: aan elkaar.' },
        { t: 'naast' },
        { t: 'de' },
        { t: 'ingang.' },
        { t: 'Tot' },
        { t: 'dan!' },
        { t: 'Fatima' },
        { t: 'en' },
        { t: 'Joris' },
      ],
      done: {
        title: 'Iedereen is welkom',
        text: 'juli, Anna’s, ’s avonds, ideeën en fietsenrek. Surinaams-Chinese (twee gelijke delen, allebei van een naam) was al goed.',
      },
    },
    {
      kind: 'drill',
      id: 'reeks',
      prompt: 'Reeks 1: typ elk woord goed',
      intro: 'Zesentwintig woorden met alle regels van De letter door elkaar. Hoofdletters tellen mee. Wat je fout doet, komt achteraan terug.',
      caps: true,
      items: [
        { q: 'Meervoud van *taxi*', before: 'Voor het station staan altijd veel', after: '.', a: 'taxi’s', why: 'taxi eindigt op i: meervoud met ’s.' },
        {
          q: 'Meervoud. Schrijf de samenstelling: zee + egel',
          before: 'Pas op voor de',
          after: 'tussen de rotsen.',
          a: 'zee-egels',
          why: 'zee + egels: e + e botsen. Koppelteken.',
        },
        { q: 'De dag na zaterdag', before: 'De markt is elke', after: 'open.', a: 'zondag', why: 'Dagen schrijf je klein.' },
        { q: 'Vul de vorm van *interesseren* in', before: 'Ik ben erg', after: 'in deze functie.', a: 'geïnteresseerd', why: 'ge + interesseerd: zonder trema lees je ei. Trema op de i.' },
        { q: 'Schrijf kort: de tas van Inez', before: 'Is dit', after: 'tas?', a: 'Inez’', why: 'Inez eindigt op z: alleen een apostrof.' },
        { q: 'De provincie met Den Haag en Rotterdam', before: 'Delft ligt in', after: '.', a: 'Zuid-Holland', why: 'Zuid hoort bij de naam: koppelteken en twee hoofdletters.' },
        {
          q: 'Fijngestampte aardappels met melk en boter',
          before: 'Bij de vis eten we',
          after: 'met spinazie.',
          say: 'puree',
          a: 'puree',
          also: ['aardappelpuree'],
          why: 'puree klinkt Frans, maar in de officiële spelling staat er geen accent op.',
        },
        {
          q: 'Bijvoeglijk naamwoord bij het land met Brussel',
          before: 'Ik eet graag',
          after: 'frieten.',
          a: 'Belgische',
          why: 'Komt van een landnaam: hoofdletter. Er staan geen twee klinkers naast elkaar, dus geen trema (anders dan in België).',
        },
        {
          q: 'Maak korter: voordelen en nadelen',
          before: 'We bespreken de',
          after: 'van thuiswerken.',
          a: 'voor- en nadelen',
          why: 'voor- staat voor voordelen: koppelteken vast aan voor, dan een spatie.',
        },
        { q: 'Meervoud van *knie*', before: 'Na het hardlopen doen mijn', after: 'pijn.', say: 'knieën', a: 'knieën', why: 'De klemtoon ligt op ie: meervoud -ieën, met trema.' },
        {
          q: 'Schrijf de achternaam van Eva van Dijk',
          before: 'Morgen komt mevrouw',
          after: 'de meterstand opnemen.',
          a: 'Van Dijk',
          why: 'Geen voornaam ervoor: het tussenvoegsel krijgt een hoofdletter.',
        },
        {
          q: 'Verkleinwoord van *auto*',
          before: 'Mijn zoon speelt met een rood',
          after: '.',
          a: 'autootje',
          why: 'auto eindigt op o: in het verkleinwoord komt er een o bij, zonder apostrof.',
        },
        { q: 'Schrijf de samenstelling: A4 + formaat', before: 'Print de brief op', after: '.', a: 'A4-formaat', why: 'Letter en cijfer + woord: koppelteken.' },
        { q: 'De feestdag op 5 mei', before: 'Op', after: 'zijn er in veel steden festivals.', a: 'Bevrijdingsdag', why: 'Een feestdag is een naam: hoofdletter. Eén woord.' },
        {
          q: 'Vul de vorm van *emigreren* in',
          before: 'Mijn oom is twintig jaar geleden naar Canada',
          after: '.',
          say: 'geëmigreerd',
          a: 'geëmigreerd',
          why: 'ge + emigreerd: zonder trema lees je gee. Trema op de e.',
        },
        { q: 'Meervoud van *tante*', before: 'Mijn drie', after: 'wonen in Rotterdam.', a: 'tantes', why: 'Na een doffe e gewoon -s, zonder apostrof.' },
        {
          q: 'Meervoud. Schrijf de samenstelling: politie + agent',
          before: 'Op het plein stonden vier',
          after: '.',
          a: 'politieagenten',
          why: 'e + a is geen klank: aan elkaar, zonder streepje.',
        },
        {
          q: 'Het getal na nul',
          after: 'ding weet ik zeker: ik kom.',
          a: 'Eén',
          also: ['Één'],
          why: 'Het getal, met accenten. Aan het begin van de zin schrijf je meestal Eén: zonder accent op de hoofdletter. Één mag ook.',
        },
        {
          q: 'Vul *financieel* in de goede vorm in',
          before: 'We hebben een gesprek over de',
          after: 'situatie van de club.',
          a: 'financiële',
          why: 'financieel + e wordt financiële: trema op de e.',
        },
        { q: 'Schrijf: in de ochtend', before: 'Ik werk', after: 'in de bakkerij.', a: '’s ochtends', why: 'Apostrof voor de weggelaten letters. Midden in de zin alles klein.' },
        {
          q: 'Schrijf de samenstelling: oud + burgemeester',
          before: 'De',
          after: 'opent de nieuwe sporthal.',
          a: 'oud-burgemeester',
          why: 'oud- in de betekenis van vroeger: koppelteken.',
        },
        { q: 'De taal van Marokko en Egypte', before: 'Mijn kinderen leren', after: 'op de zaterdagschool.', a: 'Arabisch', why: 'Een taal krijgt een hoofdletter.' },
        {
          q: 'Leenwoord: een stuk uit een film of toneelstuk',
          before: 'De laatste',
          after: 'van de film was heel spannend.',
          say: 'scène',
          a: 'scène',
          why: 'scène houdt het accent: è, met het streepje naar links.',
        },
        { q: 'Verkleinwoord van *sms*', before: 'Stuur me even een', after: 'als je er bent.', a: 'sms’je', why: 'Afkorting + uitgang: apostrof.' },
        {
          q: 'Schrijf het werkwoord: na + apen',
          before: 'Het is normaal dat kinderen hun ouders',
          after: '.',
          say: 'na-apen',
          a: 'na-apen',
          why: 'na + apen: a + a lees je als aa. Koppelteken.',
        },
        { q: 'Hoe heet het teken @ als je een mailadres spelt?', a: 'apenstaartje', why: 'Het teken @ heet apenstaartje.' },
      ],
      done: { title: 'Reeks 1 klaar', text: 'Hoofdletters, accenten, trema, apostrof en koppelteken door elkaar. Op naar de invultekst.' },
    },
    {
      kind: 'cloze',
      id: 'invultekst',
      prompt: 'Vul de nieuwsbrief aan. Typ elk woord helemaal.',
      intro: 'Hoofdletters tellen mee. Kijk goed naar de zin om het gat heen.',
      title: 'Nieuwsbrief van de basisschool',
      caps: true,
      text: 'Beste ouders,\n\nOp {woensdag|dag na dinsdag|Dagen schrijf je klein, ook in een datum.} 11 maart is er een {informatieavond|avond met informatie|e + a is geen klank: aan elkaar.} over de middelbare school. Meester {De Jong|Peter de Jong|Zonder voornaam krijgt het tussenvoegsel een hoofdletter.} vertelt over de {voor- en nadelen|voordelen en nadelen, korter|voor- staat voor voordelen: koppelteken vast aan voor, dan een spatie.} van elk schooltype. Ook twee {oud-leerlingen~ex-leerlingen|vroegere leerlingen|oud- in de betekenis van vroeger: koppelteken.} vertellen over hun eerste jaar.\n\nNeem uw kind gerust mee, want de {ideeën|meervoud van idee|idee + en: trema op de laatste e.} van kinderen zelf zijn ook belangrijk. {Yasmina’s|van Yasmina|Yasmina eindigt op a: bezit met ’s.} moeder bakt {Marokkaanse|uit Marokko|Bijvoeglijk naamwoord van een land: hoofdletter.} koekjes. Na de avond krijgt elk kind een {officiële|officieel, met -e|officieel + e wordt officiële: trema op de e.} brief met het advies.\n\nOp {Goede Vrijdag|de vrijdag voor Pasen|De naam van een feestdag: allebei met een hoofdletter.} zijn de kinderen vrij. Na de {meivakantie|vakantie in mei|Een maand schrijf je klein, ook in een samenstelling.} gaat groep 8 op kamp aan de {Noordzee|zee tussen Nederland en Engeland|Eén naam: aan elkaar, met hoofdletter. zee is geen naam.}. Ze fietsen langs de kust en bezoeken een oude {ruïne~kasteelruïne|resten van een kasteel|Zonder trema lees je ui. Trema op de i: ru-ï-ne.}. {’s Avonds|in de avond|Apostrof voor de weggelaten letters. Begin van de zin: hoofdletter op het tweede woord.} zitten ze rond een kampvuur. De {foto’s|meervoud van foto|foto eindigt op o: meervoud met ’s.} zetten we in de schoolapp.\n\nVragen? Stuur een {e-mail|e + mail|Een losse letter + woord: koppelteken.} naar juf Sanne of bel haar {06-nummer|06 + nummer|Cijfer + woord: koppelteken.}.\n\nMet vriendelijke groet,\nJuf Sanne en meester De Jong',
      why: 'Hoofdletters: De Jong, Marokkaanse, Goede Vrijdag, Noordzee en ’s Avonds; klein: woensdag en meivakantie. Trema: ideeën, officiële, ruïne. Apostrof: Yasmina’s, ’s Avonds, foto’s. Koppelteken: voor- en nadelen, oud-leerlingen, e-mail, 06-nummer. Aan elkaar: informatieavond.',
    },
    {
      kind: 'passage',
      id: 'tekstdictee',
      prompt: 'Tekstdictee: luister en typ elke zin',
      intro: 'Je hoort negen zinnen. Hoofdletters en leestekens tellen mee.',
      title: 'Een nieuwe baan voor Fatima',
      sentences: [
        'In maart begon mijn ex-collega Fatima aan een nieuwe baan in Den Haag.',
        'Ze werkt nu als coördinator bij een Nederlands-Belgisch bedrijf in de auto-industrie.',
        'Haar ideeën over zonne-energie vinden haar nieuwe collega’s erg interessant.',
        '’s Ochtends brengt ze haar zoontje naar de kinderopvang van mevrouw Van Dijk.',
        'Op vrijdag eten ze samen Turkse pizza’s in een café bij het station.',
        'In de zomervakantie gaan ze met de auto naar Zuid-Frankrijk.',
        'Fatima’s man is geëmigreerd uit Indonesië en spreekt vloeiend Engels.',
        'Het hele gezin heeft maar één auto.',
        'Op Koningsdag verkopen ze samen oude cd’s en dvd’s op de vrijmarkt.',
      ],
      right: 'Alles goed. Je hebt hoofdletters, accenten, trema’s, apostrofs en koppeltekens door elkaar goed geschreven.',
      wrong: 'Kijk deze woorden na. Klein: maart, vrijdag, zomervakantie. Groot: Den Haag, Van Dijk, Turkse, Engels, Koningsdag. Trema: coördinator, ideeën, geëmigreerd, Indonesië. Accent: café, één. Apostrof: collega’s, ’s Ochtends, pizza’s, Fatima’s, cd’s, dvd’s. Koppelteken: ex-collega, Nederlands-Belgisch, auto-industrie, zonne-energie, Zuid-Frankrijk.',
    },
    {
      kind: 'proofread',
      id: 'nakijken',
      prompt: 'Kijk de mail aan de huisbaas na voordat hij weggaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { to: 'meneer De Graaf', subject: 'Verwarming kapot' },
      greeting: 'Geachte heer De Graaf,',
      signoff: 'Met vriendelijke groet,\nHasan',
      tokens: [
        { t: 'Sinds' },
        { t: 'Zaterdag', fix: 'zaterdag', why: 'Dagen van de week schrijf je klein.' },
        { t: 'doet' },
        { t: 'de' },
        { t: 'verwarming' },
        { t: 'het' },
        { t: 'niet' },
        { t: 'meer.' },
        { t: 'Volgens' },
        { t: 'mij' },
        { t: 'is' },
        { t: 'de' },
        { t: 'cv-ketel', trap: 'Goed: cv is een afkorting (centrale verwarming). Afkorting + woord: koppelteken.' },
        { t: 'kapot.' },
        { t: 'Mijn' },
        { t: 'twee' },
        { t: 'babys', fix: 'baby’s', why: 'baby eindigt op y: meervoud met ’s.' },
        { t: 'slapen' },
        { t: 'nu' },
        { t: 'bij' },
        { t: 'ons,' },
        { t: 'want' },
        { t: '’s', trap: 'Goed: ’s nachts, met een apostrof voor de weggelaten letters. Midden in de zin klein.' },
        { t: 'nachts' },
        { t: 'wordt' },
        { t: 'het' },
        { t: 'in' },
        { t: 'hun' },
        { t: 'kamer' },
        { t: 'erg' },
        { t: 'koud.' },
        { t: 'De' },
        { t: 'monteur' },
        { t: 'van' },
        { t: 'de' },
        { t: 'energie-leverancier', fix: 'energieleverancier', why: 'e + l botsen niet: een gewone samenstelling schrijf je aan elkaar.' },
        { t: 'kan' },
        { t: 'pas' },
        { t: 'na' },
        { t: 'de' },
        { t: 'Kerstvakantie', fix: 'kerstvakantie', why: 'Een samenstelling met een feestdag is een gewoon woord: klein.' },
        { t: 'komen.' },
        { t: 'Dat' },
        { t: 'is' },
        { t: 'te' },
        { t: 'laat.' },
        { t: 'Kunt' },
        { t: 'u', trap: 'Goed: u en uw schrijf je klein, ook in een officiële brief.' },
        { t: 'een' },
        { t: 'andere' },
        { t: 'monteur' },
        { t: 'sturen?' },
        { t: 'Ik' },
        { t: 'ben' },
        { t: 'ook' },
        { t: 'geinteresseerd', fix: 'geïnteresseerd', why: 'ge + interesseerd: zonder trema lees je ei. Trema op de i.' },
        { t: 'in' },
        { t: 'een' },
        { t: 'tijdelijke' },
        { t: 'oplossing,' },
        { t: 'zoals' },
        { t: 'een' },
        { t: 'elektrische' },
        { t: 'kachel.' },
        { t: 'U' },
        { t: 'kunt' },
        { t: 'mij' },
        { t: 'bellen' },
        { t: 'op' },
        { t: 'mijn' },
        { t: '06 nummer', fix: '06-nummer', why: 'Cijfer + woord: koppelteken.' },
        { t: 'of' },
        { t: 'mij' },
        { t: 'e-mailen.', trap: 'Goed: e-mailen komt van e-mail. Een losse letter + woord: koppelteken.' },
        { t: 'Mijn' },
        { t: 'buurvrouw,' },
        { t: 'mevrouw' },
        { t: 'van', fix: 'Van', why: 'Er staat geen voornaam voor: het tussenvoegsel krijgt een hoofdletter. mevrouw Van Leeuwen.' },
        { t: 'Leeuwen,' },
        { t: 'heeft' },
        { t: 'hetzelfde' },
        { t: 'probleem.' },
        { t: 'Zij' },
        { t: 'spreekt' },
        { t: 'alleen' },
        { t: 'Turks' },
        { t: 'en' },
        { t: 'arabisch.', fix: 'Arabisch.', why: 'Een taal krijgt een hoofdletter.' },
        { t: 'Wilt' },
        { t: 'u' },
        { t: 'haar' },
        { t: 'ook' },
        { t: 'een' },
        { t: 'antwoord' },
        { t: 'sturen?' },
      ],
      done: {
        title: 'De mail kan weg',
        text: 'zaterdag, baby’s, energieleverancier, kerstvakantie, geïnteresseerd, 06-nummer, Van Leeuwen en Arabisch. cv-ketel, ’s nachts, u en e-mailen waren al goed.',
      },
    },
    {
      kind: 'drill',
      id: 'reeks-2',
      prompt: 'Reeks 2: typ elk woord goed',
      intro: 'Nog zesentwintig woorden, weer alles door elkaar. Hoofdletters tellen mee. Wat je fout doet, komt achteraan terug.',
      caps: true,
      items: [
        {
          q: 'Meervoud. Schrijf de samenstelling: ex + collega',
          before: 'Vrijdag ga ik uit eten met twee',
          after: '.',
          a: 'ex-collega’s',
          also: ['ex-collegae'],
          why: 'ex- met koppelteken, en collega eindigt op a: meervoud met ’s. ex-collegae mag ook.',
        },
        { q: 'Vul de titel in', before: 'Gisteren sprak', after: 'Willem-Alexander het land toe.', a: 'koning', why: 'Een titel is geen naam: klein, ook vlak voor de naam.' },
        {
          q: 'Meervoud van *categorie*',
          before: 'De prijzen zijn verdeeld in drie',
          after: '.',
          say: 'categorieën',
          a: 'categorieën',
          why: 'De klemtoon ligt op ie: meervoud -ieën, met trema.',
        },
        {
          q: 'Zo staat Eva van Dijk in een Nederlandse telefoonlijst. Typ: achternaam, komma, de rest.',
          a: 'Dijk, Eva van',
          why: 'Je zoekt op het hoofdwoord. Het tussenvoegsel komt achter de voornaam, met een kleine letter.',
        },
        {
          q: 'Schrijf de samenstelling: radio + uitzending',
          before: 'Ik hoorde het nieuws in een',
          after: '.',
          a: 'radio-uitzending',
          why: 'radio + uitzending: o + u lees je als ou. Koppelteken.',
        },
        { q: 'Schrijf kort: de auto van Hugo', before: 'Vandaag leen ik', after: 'auto.', a: 'Hugo’s', why: 'Hugo eindigt op o: bezit met ’s.' },
        {
          q: 'De vakantie rond Kerstmis',
          before: 'In de',
          after: 'gaan we naar mijn ouders.',
          a: 'kerstvakantie',
          why: 'Een samenstelling met een feestdag is een gewoon woord: klein.',
        },
        {
          q: 'Iemand spelt een land: Bernard, Eduard, Lodewijk, Gerard, Izaak, Eduard. Typ het land.',
          say: 'Bernard, Eduard, Lodewijk, Gerard, Izaak, Eduard',
          a: 'België',
          why: 'De letters zijn b, e, l, g, i, e. Het land schrijf je met een hoofdletter en een trema: België.',
        },
        {
          q: 'Maak korter: inschrijven en uitschrijven',
          before: 'Bij de gemeente kun je je online',
          after: '.',
          a: 'in- en uitschrijven',
          why: 'in- staat voor inschrijven: koppelteken vast aan in, dan een spatie.',
        },
        { q: 'Leenwoord voor loopbaan', before: 'Ze wil een', after: 'in de zorg.', say: 'carrière', a: 'carrière', why: 'carrière houdt het accent: è, met het streepje naar links.' },
        { q: 'De godsdienst van moslims', before: 'De docent vertelt over de', after: '.', a: 'islam', why: 'Een godsdienst schrijf je klein.' },
        { q: 'Meervoud van *cd*', before: 'Ik heb al mijn oude', after: 'weggegeven.', a: 'cd’s', why: 'Afkorting + uitgang: apostrof.' },
        {
          q: 'Schrijf de samenstelling: cd + speler',
          before: 'Mijn oude',
          after: 'doet het niet meer.',
          a: 'cd-speler',
          why: 'Afkorting + woord: koppelteken. Afkorting + uitgang (cd’s): apostrof.',
        },
        { q: 'Een inwoner van Indonesië', before: 'Mijn schoonvader is', after: '.', a: 'Indonesiër', why: 'Indonesië → Indonesiër: hoofdletter, en het trema blijft.' },
        { q: 'Schrijf de samenstelling: foto + album', before: 'Oma bewaart alles in een oud', after: '.', a: 'fotoalbum', why: 'o + a is geen klank: aan elkaar.' },
        {
          q: 'Het korte woordje met een accent waarmee je om instemming vraagt',
          before: 'Lekker weer vandaag,',
          after: '?',
          say: 'hè',
          a: 'hè',
          why: 'hè (toch?) met het streepje naar links. hé is een groet of een roep.',
        },
        {
          q: 'Bijvoeglijk naamwoord: uit het oosten van Europa',
          before: 'Deze supermarkt verkoopt',
          after: 'producten uit Polen en Roemenië.',
          a: 'Oost-Europese',
          why: 'Oost hoort bij de naam: koppelteken en twee hoofdletters. Met -e: de producten.',
        },
        { q: 'Vul in: be + eindigd', before: 'De huurder heeft het contract', after: '.', a: 'beëindigd', why: 'be + eindigd: zonder trema lees je ee. Trema op de e.' },
        {
          q: 'Schrijf kort: de fiets van Jan',
          before: 'Kun je',
          after: 'fiets even binnenzetten?',
          a: 'Jans',
          why: 'Jan eindigt op een medeklinker: gewoon s, zonder apostrof.',
        },
        { q: 'Iemand die in Amsterdam woont', before: 'Mijn buurman is een echte', after: '.', a: 'Amsterdammer', why: 'Een inwoner van een plaats: hoofdletter.' },
        {
          q: 'Schrijf de samenstelling: video + opname',
          before: 'De politie bekijkt een',
          after: 'van de inbraak.',
          say: 'video-opname',
          a: 'video-opname',
          why: 'video + opname: o + o lees je als oo. Koppelteken.',
        },
        {
          q: 'Schrijf: in de middag',
          after: 'is de apotheek een uur dicht.',
          a: '’s Middags',
          why: 'Apostrof voor de weggelaten letters. Begin van de zin: hoofdletter op het tweede woord.',
        },
        { q: 'Meervoud van *menu*', before: 'Alle', after: 'staan op de website.', a: 'menu’s', why: 'menu eindigt op u: meervoud met ’s.' },
        { q: 'De taal die je in Brazilië spreekt', before: 'Mijn collega spreekt vloeiend', after: '.', a: 'Portugees', why: 'Een taal krijgt een hoofdletter.' },
        {
          q: 'Schrijf de samenstelling: contra + indicatie',
          before: 'Zwangerschap is een',
          after: 'voor dit medicijn.',
          a: 'contra-indicatie',
          why: 'contra + indicatie: a + i lees je als ai. Koppelteken.',
        },
        {
          q: 'Welk woord komt in de woordenlijst als laatste: idee, ijzer, ik of iets?',
          a: 'ik',
          why: 'id, ie, ij, ik: ij telt als i + j, en de j komt vóór de k.',
        },
      ],
      done: { title: 'Reeks 2 klaar', text: 'Twee reeksen door elkaar: zo zie je welke regels al vastzitten en welke nog niet.' },
    },
    {
      kind: 'cloze',
      id: 'invultekst-2',
      prompt: 'Vul het bericht van de huisarts aan. Typ elk woord helemaal.',
      intro: 'Hoofdletters tellen mee. Kijk goed naar de zin om het gat heen.',
      title: 'Bericht van de huisartsenpraktijk',
      caps: true,
      text: 'Beste {patiënt|pati_nt|Zonder trema lees je ie. Trema op de e: pa-ti-ënt.},\n\nVanaf 1 juni is de praktijk ook op {zaterdag|dag na vrijdag|Dagen schrijf je klein.} van negen tot twaalf uur {geopend|voltooid deelwoord van openen|eo is geen klank: je leest het goed zonder trema.}. Dan werkt {dokter~huisarts|titel|Een titel is geen naam: klein, ook voor de naam.} Visser. Met {Pinksteren|feest, zeven weken na Pasen|Een feestdag is een naam: hoofdletter.} zijn we dicht.\n\n{’s Avonds|in de avond|Apostrof voor de weggelaten letters. Begin van de zin: hoofdletter op het tweede woord.}, ’s nachts en in het weekend belt u de {huisartsenpost|post van de huisartsen|Gewone samenstelling: aan elkaar.}. Na een {auto-ongeluk|ongeluk met een auto|auto + ongeluk: o + o botsen. Koppelteken.} of bij hevige pijn belt u altijd 112.\n\nHeeft u een vraag zonder haast? Stel die dan via een {e-consult|e + consult|Een losse letter + woord: koppelteken.} op onze website. Uitslagen van bloedonderzoek krijgt u als {pdf-bestand|pdf + bestand|Afkorting + woord: koppelteken.}. Een bloedafname duurt vijf {à|leenwoordje voor tot|à betekent hier tot. Het accent is het streepje naar links.} tien minuten.\n\nWilt u stoppen met roken? Doe mee aan onze cursus en word {niet-roker|iemand die niet rookt|niet- + zelfstandig naamwoord: koppelteken.}. U wordt per brief {geïnformeerd|van informeren|ge + informeerd: zonder trema lees je ei. Trema op de i.} over de data.\n\nHet consultatiebureau voor {baby’s|meervoud van baby|baby eindigt op y: meervoud met ’s.} zit vanaf juni in ons gebouw. Onze nieuwe {coördinator|co_rdinator|Zonder trema lees je oo. Trema op de tweede o.}, mevrouw {De Wit|Anna de Wit|Zonder voornaam krijgt het tussenvoegsel een hoofdletter.}, spreekt ook {Turks|taal van Turkije|Een taal krijgt een hoofdletter.} en {Arabisch|taal van Marokko en Egypte|Een taal krijgt een hoofdletter.}.\n\nMet vriendelijke groet,\nHuisartsenpraktijk Oosterpark',
      why: 'Trema: patiënt, geïnformeerd, coördinator; geen trema in geopend. Hoofdletters: Pinksteren, ’s Avonds, De Wit, Turks, Arabisch; klein: zaterdag en dokter. Koppelteken: auto-ongeluk, e-consult, pdf-bestand, niet-roker. Aan elkaar: huisartsenpost. Accent: à. Apostrof: ’s Avonds, baby’s.',
    },
    {
      kind: 'proofread',
      id: 'nakijken-2',
      prompt: 'Kijk het clubnieuws na voordat het online gaat',
      intro: 'Je weet niet hoeveel fouten erin zitten. Tik een fout woord aan en typ de verbetering. Klaar? Tik op ‘Ik ben klaar’.',
      blind: true,
      header: { subject: 'Nieuws van de voetbalclub' },
      signoff: 'Sportieve groet,\nHet bestuur',
      tokens: [
        { t: 'Vorige' },
        { t: 'week' },
        { t: 'was' },
        { t: 'de' },
        { t: 'jaarvergadering' },
        { t: 'van' },
        { t: 'onze' },
        { t: 'club.' },
        { t: 'De' },
        { t: 'oud voorzitter,', fix: 'oud-voorzitter,', also: ['ex-voorzitter,'], why: 'oud- in de betekenis van vroeger: koppelteken.' },
        { t: 'meneer' },
        { t: 'Bakker,' },
        { t: 'bedankte' },
        { t: 'alle' },
        { t: 'vrijwilligers.' },
        { t: 'Daarna' },
        { t: 'vertelde' },
        { t: 'de' },
        { t: 'nieuwe' },
        { t: 'voorzitter' },
        { t: 'over' },
        { t: 'de' },
        { t: 'plannen' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'Zomer.', fix: 'zomer.', why: 'Seizoenen schrijf je klein.' },
        { t: 'Er' },
        { t: 'komen' },
        { t: 'panelen' },
        { t: 'op' },
        { t: 'het' },
        { t: 'dak' },
        { t: 'van' },
        { t: 'de' },
        { t: 'kantine,' },
        { t: 'zodat' },
        { t: 'we' },
        { t: 'zonne energie', fix: 'zonne-energie', why: 'Eén samenstelling waarin e + e botsen: koppelteken.' },
        { t: 'gebruiken.' },
        { t: 'Ook' },
        { t: 'komt' },
        { t: 'er' },
        { t: 'een' },
        { t: 'groot' },
        { t: 'fietsen-rek', fix: 'fietsenrek', why: 'Gewone samenstelling zonder botsing: aan elkaar.' },
        { t: 'bij' },
        { t: 'de' },
        { t: 'ingang.' },
        { t: 'In' },
        { t: 'de' },
        { t: 'kantine' },
        { t: 'betaal' },
        { t: 'je' },
        { t: 'voortaan' },
        { t: 'alleen' },
        { t: 'nog' },
        { t: 'met' },
        { t: 'je' },
        { t: 'pinpas.', trap: 'Goed: pin zeg je als een gewoon woord, niet letter voor letter. Dus aan elkaar.' },
        { t: 'De' },
        { t: 'kantine' },
        { t: 'is' },
        { t: '’s', trap: 'Goed: ’s avonds, met een apostrof voor de weggelaten letters. Midden in de zin klein.' },
        { t: 'avonds' },
        { t: 'open' },
        { t: 'tot' },
        { t: 'elf' },
        { t: 'uur.' },
        { t: 'Op' },
        { t: 'Koningsdag', trap: 'Goed: Koningsdag is een feestdag, en een feestdag krijgt een hoofdletter.' },
        { t: 'is' },
        { t: 'er' },
        { t: 'een' },
        { t: 'toernooi' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'jeugd.' },
        { t: 'Kinderen' },
        { t: 'kunnen' },
        { t: 'zich' },
        { t: 'aan-', trap: 'Goed: aan- staat voor aanmelden. Bij een weggelaten deel komt er een koppelteken, en dan een spatie.' },
        { t: 'en' },
        { t: 'afmelden' },
        { t: 'bij' },
        { t: 'de' },
        { t: 'coordinator', fix: 'coördinator', why: 'Zonder trema lees je oo. Trema op de tweede o.' },
        { t: 'van' },
        { t: 'de' },
        { t: 'jeugd.' },
        { t: 'De' },
        { t: 'fotos', fix: 'foto’s', why: 'foto eindigt op o: meervoud met ’s.' },
        { t: 'van' },
        { t: 'de' },
        { t: 'vergadering' },
        { t: 'staan' },
        { t: 'in' },
        { t: 'de' },
        { t: 'app.' },
        { t: 'Heb' },
        { t: 'je' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: trema op de laatste e.' },
        { t: 'voor' },
        { t: 'het' },
        { t: 'nieuwe' },
        { t: 'seizoen?' },
        { t: 'Mail' },
        { t: 'ze' },
        { t: 'naar' },
        { t: 'ons' },
        { t: 'nieuwe' },
        { t: 'emailadres.', fix: 'e-mailadres.', also: ['mailadres.'], why: 'Een losse letter + woord: koppelteken. e-mail, e-mailadres.' },
      ],
      done: {
        title: 'Het nieuws kan online',
        text: 'oud-voorzitter, zomer, zonne-energie, fietsenrek, coördinator, foto’s, ideeën en e-mailadres. pinpas, ’s avonds, Koningsdag en aan- en afmelden waren al goed.',
      },
    },
  ],
};
