import type { LessonInput } from '../../schema';

/** Praktijkles voor "De letter": de toets met alfabet, hoofdletters, accenten, trema, apostrof en koppelteken door elkaar. */
export const LES_L27: LessonInput = {
  id: 'l27',
  stage: 'toets',
  domain: 'orth',
  also: ['morf'],
  title: 'Toets: De letter',
  skill: 'Spelling',
  icon: 'Aa’',
  steps: [
    {
      kind: 'explain',
      id: 'overzicht',
      title: 'Alle regels op een rij',
      panels: [
        {
          text: 'Het alfabet heeft 26 letters. In een woordenlijst staat *ij* als *i* + *j*: *ijs* staat na *iglo* en vóór *ik*. Accenten tellen niet mee bij het ordenen: *café* staat op de plek van *cafe*. En in een Nederlandse telefoonlijst staan achternamen met *de*, *van* of *van der* bij het hoofdwoord: *Vries, de* vind je bij de V.',
          rule: 'Ordenen: *ij* = *i* + *j*, accenten tellen niet, *de Vries* staat bij de V.',
          quiz: {
            q: 'Welke rij staat in de volgorde van de woordenlijst?',
            options: ['idee – ijs – ik', 'idee – ik – ijs', 'ijs – idee – ik'],
            answer: 'idee – ijs – ik',
            why: 'id, ij, ik: de tweede letter beslist, en ij telt als i + j. De j komt vóór de k.',
          },
        },
        {
          text: 'Een hoofdletter krijgen: het begin van een zin; namen van personen, dieren, straten, plaatsen, landen en rivieren; talen en inwoners (*Nederlands*, *een Marokkaan*); bijvoeglijke naamwoorden van namen (*Turkse thee*); feestdagen (*Pasen*, *Suikerfeest*, *Koningsdag*); instellingen (*de Belastingdienst*). Klein blijven: dagen, maanden en seizoenen (*maandag*, *januari*, *zomer*), windstreken (*het noorden*) en titels (*koning Willem-Alexander*, *dokter Jansen*). Tussenvoegsels: *Jan de Vries*, maar *meneer De Vries*. En *IJ* is één letter: *IJsland*, *IJmuiden*.',
          rule: 'Namen, talen, inwoners en feestdagen: hoofdletter. Dagen, maanden, seizoenen en titels: klein.',
          quiz: {
            q: 'Welke zin is goed?',
            options: [
              'Op maandag vieren we Pasen bij meneer De Vries.',
              'Op Maandag vieren we pasen bij meneer de Vries.',
              'Op maandag vieren we Pasen bij Meneer de Vries.',
            ],
            answer: 'Op maandag vieren we Pasen bij meneer De Vries.',
            why: 'maandag klein, Pasen groot. meneer is een gewoon woord, en zonder voornaam krijgt de in De Vries een hoofdletter.',
          },
        },
        {
          text: 'Een klemtoonaccent zet je alleen als het nodig is voor de betekenis: *één* (het getal) tegenover *een*, *vóór* tegenover *voor*. In leenwoorden hoort het accent bij het woord: *café*, *privé*, *crème*, *scène*. Het trema staat op de eerste klinker van een nieuwe lettergreep als je de klinkers anders samen zou lezen: *ideeën*, *België*, *geïnteresseerd*, *financiële*. Maar niet als je het woord ook zo goed leest: *geopend*, *beantwoorden*.',
          rule: 'Accent: alleen voor nadruk of in leenwoorden (*café*). Trema: twee klinkers los, binnen één woord (*ideeën*).',
          quiz: {
            q: 'Welke rij is helemaal goed?',
            options: ['café – ideeën – geopend', 'cafe – ideeën – geöpend', 'café – ideeen – geopend'],
            answer: 'café – ideeën – geopend',
            why: 'café met accent, ideeën met trema, en geopend zonder trema: eo is geen klank.',
          },
        },
        {
          text: 'De apostrof: meervoud met *’s* na *a*, *i*, *o*, *u* en *y* (*auto’s*, *menu’s*, *baby’s*), maar niet na *é*, een doffe *e* of *eau* (*cafés*, *tantes*, *cadeaus*). Bezit bij een naam: *Anna’s*, maar *Jans* en *Sannes*, en na *s*, *x*, *z* alleen *’* (*Max’ jas*). Weggelaten letters: *’s avonds*, *zo’n*, *m’n*. Afkortingen: *tv’s*, *sms’je*. Verkleinwoord: *ski’tje*, maar *autootje*.',
          rule: 'Apostrof alleen na *a, i, o, u, y*, bij afkortingen, en waar letters weg zijn.',
          quiz: {
            q: 'Welke rij is helemaal goed?',
            options: ['auto’s – cafés – Max’ jas', 'auto’s – café’s – Maxs jas', 'autos – cafés – Max’s jas'],
            answer: 'auto’s – cafés – Max’ jas',
            why: 'auto eindigt op o: ’s. café eindigt op é: gewoon s. Max eindigt op x: alleen een apostrof.',
          },
        },
        {
          text: 'Het koppelteken: een samenstelling schrijf je in principe *aan elkaar* (*ziekenhuis*, *fietsenrek*). Een koppelteken komt er alleen bij botsende klinkers (*zee-egel*, *auto-ongeluk*), bij een afkorting, letter of cijfer (*tv-gids*, *e-mail*, *06-nummer*), bij *Noord-*, *Zuid-*, *Oost-* en *West-* voor een naam (*Noord-Holland*), na *ex-*, *oud-* en *niet-* (*ex-man*), bij weglating (*in- en uitgang*) en bij twee gelijke delen (*Nederlands-Belgisch*).',
          rule: 'Basis: aan elkaar. Koppelteken bij botsing, afkorting of cijfer, naam, *ex-*/*oud-*/*niet-*, weglating of twee gelijke delen.',
          quiz: {
            q: 'Welke rij is helemaal goed?',
            options: ['ziekenhuis – zee-egel – tv-gids', 'zieken huis – zee-egel – tv gids', 'ziekenhuis – zeeëgel – tvgids'],
            answer: 'ziekenhuis – zee-egel – tv-gids',
            why: 'ziekenhuis aan elkaar, zee-egel met koppelteken (twee woorden die botsen) en tv-gids met koppelteken (afkorting).',
          },
        },
      ],
    },
    {
      kind: 'swipe',
      id: 'alles-door-elkaar',
      prompt: 'Klopt de zin?',
      intro: 'Veeg naar rechts als alles goed is, naar links als er een fout in zit. Let op hoofdletters én tekens.',
      cards: [
        { t: 'Mijn buurvrouw spreekt Arabisch en Turks.', ok: true, why: 'Talen krijgen een hoofdletter.' },
        { t: 'In de Zomer gaan we naar IJsland.', ok: false, fix: 'Zomer → zomer', why: 'Seizoenen schrijf je klein. IJsland is goed: IJ is één letter.' },
        { t: 'We wonen in de provincie noord-holland.', ok: false, fix: 'noord-holland → Noord-Holland', why: 'Een naam: beide delen met een hoofdletter, met koppelteken.' },
        { t: 'Hij zei: ‘Kom binnen.’', ok: true, why: 'Na een dubbele punt klein, behalve bij een letterlijk citaat. Dat begint met een hoofdletter.' },
        { t: 'Er zijn hier twee café’s.', ok: false, fix: 'café’s → cafés', why: 'Na een é gewoon -s, zonder apostrof.' },
        { t: 'Mevrouw van Dijk is onze nieuwe buurvrouw.', ok: false, fix: 'van Dijk → Van Dijk', why: 'Zonder voornaam krijgt het tussenvoegsel een hoofdletter: mevrouw Van Dijk.' },
        { t: 'Ze heeft het contract beëindigd.', ok: true, why: 'be + eindigd: trema op de e.' },
        { t: 'Op Dinsdag heb ik vrij.', ok: false, fix: 'Dinsdag → dinsdag', why: 'Dagen van de week schrijf je klein.' },
      ],
    },
    {
      kind: 'choice',
      id: 'suikerfeest',
      prompt: 'Kies de goede schrijfwijze.',
      before: 'Volgende week vieren we het',
      after: 'met de hele familie.',
      options: ['suikerfeest', 'Suikerfeest', 'SuikerFeest', 'suiker-feest'],
      answer: 'Suikerfeest',
      why: 'Een feestdag krijgt een hoofdletter, net als Pasen, Kerstmis en Koningsdag. Het is één samenstelling: aan elkaar.',
    },
    {
      kind: 'order',
      id: 'telefoonlijst',
      prompt: 'Zet de achternamen in de volgorde van een Nederlandse telefoonlijst.',
      tiles: ['Jansen', 'De Boer', 'Van Dijk', 'Smit', 'Bakker'],
      answer: 'Bakker De Boer Van Dijk Jansen Smit',
      why: 'In Nederland orden je op het hoofdwoord: Bakker, Boer (De), Dijk (Van), Jansen, Smit. De en Van tellen niet mee. Ze krijgen hier een hoofdletter, want er staat geen voornaam voor.',
    },
    {
      kind: 'choice',
      id: 'derde-woord',
      prompt: 'Zet in gedachten in de volgorde van de woordenlijst: iets, ik, ijzer, idee. Welk woord komt als derde?',
      before: '',
      after: '',
      options: ['iets', 'ik', 'ijzer', 'idee'],
      answer: 'ijzer',
      why: 'idee (id), iets (ie), ijzer (ij), ik (ik). ij telt als i + j, en de j staat vóór de k.',
    },
    {
      kind: 'type',
      id: 'een-getal',
      prompt: 'Typ het woord, met een accent als dat nodig is.',
      before: 'Ik heb maar',
      after: 'kaartje gekocht, niet twee.',
      hint: 'een of één?',
      answer: 'één',
      why: 'Het gaat om het getal: niet twee. Dan zet je accenten op allebei de e’s: één.',
    },
    {
      kind: 'fix',
      id: 'beinvloeden',
      prompt: 'Tik het foute woord aan en verbeter het.',
      sentence: 'Het weer kan je humeur sterk beinvloeden.',
      wrong: 6,
      answer: 'beïnvloeden',
      why: 'be + invloeden: zonder trema lees je ei. Trema op de i.',
    },
    {
      kind: 'sort',
      id: 'welk-teken',
      prompt: 'Welk teken heb je nodig?',
      buckets: ['trema', 'apostrof', 'koppelteken', 'geen teken'],
      items: [
        { t: 'meervoud van idee', b: 0 },
        { t: 'meervoud van foto', b: 1 },
        { t: 'e + mail', b: 2 },
        { t: 'meervoud van cadeau', b: 3 },
        { t: 'ge + interesseerd', b: 0 },
        { t: 'de jas van Max, kort', b: 1 },
        { t: 'Noord + Holland', b: 2 },
        { t: 'politie + agent', b: 3 },
        { t: 'financieel met -e', b: 0 },
        { t: 'verkleinwoord van ski', b: 1 },
        { t: 'ex + man', b: 2 },
        { t: 'meervoud van tafel', b: 3 },
      ],
      why: 'Trema: ideeën, geïnteresseerd, financiële. Apostrof: foto’s, Max’ jas, ski’tje. Koppelteken: e-mail, Noord-Holland, ex-man. Geen teken: cadeaus, politieagent, tafels.',
    },
    {
      kind: 'proofread',
      id: 'mail-gemeente',
      prompt: 'Lees de mail aan de gemeente na',
      intro: 'Er zitten zes fouten in: vijf met hoofdletters en één met een accent. Tik ze aan.',
      header: { to: 'Gemeente, afdeling Burgerzaken', subject: 'Verhuizing' },
      tokens: [
        { t: 'Geachte' },
        { t: 'heer,' },
        { t: 'mevrouw,' },
        { t: 'Op' },
        { t: 'maandag' },
        { t: '3' },
        { t: 'Maart', fix: 'maart', why: 'Maanden schrijf je klein.' },
        { t: 'verhuis' },
        { t: 'ik' },
        { t: 'van' },
        { t: 'Rotterdam' },
        { t: 'naar' },
        { t: 'utrecht.', fix: 'Utrecht.', why: 'Een plaatsnaam krijgt een hoofdletter.' },
        { t: 'Ik' },
        { t: 'ben' },
        { t: 'geboren' },
        { t: 'in' },
        { t: 'marokko', fix: 'Marokko', why: 'Een land krijgt een hoofdletter.' },
        { t: 'en' },
        { t: 'ik' },
        { t: 'spreek' },
        { t: 'Nederlands' },
        { t: 'en' },
        { t: 'arabisch.', fix: 'Arabisch.', why: 'Een taal krijgt een hoofdletter.' },
        { t: 'Kan' },
        { t: 'ik' },
        { t: 'op' },
        { t: 'Dinsdag', fix: 'dinsdag', why: 'Dagen van de week schrijf je klein.' },
        { t: 'langskomen' },
        { t: 'om' },
        { t: 'mijn' },
        { t: 'adres' },
        { t: 'door' },
        { t: 'te' },
        { t: 'geven?' },
        { t: 'Mijn' },
        { t: 'vrouw' },
        { t: 'komt' },
        { t: 'een' },
        { t: 'week' },
        { t: 'later,' },
        { t: 'want' },
        { t: 'ze' },
        { t: 'werkt' },
        { t: 'tot' },
        { t: 'de' },
        { t: 'zomer' },
        { t: 'nog' },
        { t: 'in' },
        { t: 'een' },
        { t: 'cafe', fix: 'café', why: 'café is een leenwoord met een vast accent.' },
        { t: 'in' },
        { t: 'Rotterdam.' },
        { t: 'Met' },
        { t: 'vriendelijke' },
        { t: 'groet,' },
        { t: 'Hasan' },
      ],
      done: {
        title: 'Klaar voor de gemeente',
        text: 'maart en dinsdag klein; Utrecht, Marokko en Arabisch met een hoofdletter; café met accent. zomer was al goed: seizoenen blijven klein.',
      },
    },
    {
      kind: 'dictation',
      id: 'dictee-verjaardag',
      prompt: 'Luister en typ de zin precies over.',
      intro: 'Hoofdletters, accenten, trema’s en apostrofs tellen allemaal mee.',
      sentence: 'Op maandag vieren we Anna’s verjaardag in een café in België.',
      right: 'Goed: maandag klein, Anna’s met apostrof, café met accent en België met hoofdletter en trema.',
      wrong: 'Loop de zin na: maandag (klein), Anna’s (naam op a: ’s), café (accent) en België (hoofdletter en trema).',
    },
    {
      kind: 'speed',
      id: 'snel-aan-elkaar',
      prompt: 'Aan elkaar of los?',
      intro: 'Snel: is het één samenstelling of zijn het twee woorden?',
      seconds: 30,
      items: [
        { a: 'zonne', b: 'bril', joined: true, tip: 'zonnebril.' },
        { a: 'te', b: 'veel', joined: false, tip: 'te veel: los.' },
        { a: 'klanten', b: 'service', joined: true, tip: 'klantenservice.' },
        { a: 'belasting', b: 'dienst', joined: true, tip: 'belastingdienst.' },
        { a: 'een', b: 'beetje', joined: false, tip: 'een beetje: twee woorden.' },
        { a: 'verjaardags', b: 'cadeau', joined: true, tip: 'verjaardagscadeau.' },
        { a: 'heel', b: 'goed', joined: false, tip: 'heel goed: los.' },
        { a: 'tand', b: 'pasta', joined: true, tip: 'tandpasta.' },
        { a: 'kinder', b: 'opvang', joined: true, tip: 'kinderopvang: r + o botsen niet.' },
        { a: 'nieuwe', b: 'fiets', joined: false, tip: 'Bijvoeglijk naamwoord + zelfstandig naamwoord: los.' },
      ],
    },
    {
      kind: 'proofread',
      id: 'appje-collega',
      prompt: 'Lees het appje na',
      intro: 'Sara appt haar collega Mo. Er zitten vijf fouten in met de apostrof, het trema en het koppelteken. Tik ze aan.',
      header: { to: 'Mo' },
      tokens: [
        { t: 'Hoi' },
        { t: 'Mo!' },
        { t: 'Ik' },
        { t: 'sta' },
        { t: 'in' },
        { t: 'de' },
        { t: 'file' },
        { t: 'door' },
        { t: 'een' },
        { t: 'autoongeluk.', fix: 'auto-ongeluk.', why: 'auto + ongeluk: o + o botsen. Koppelteken.' },
        { t: 'Kun' },
        { t: 'jij' },
        { t: 's', fix: '’s', why: '’s ochtends: apostrof voor de weggelaten letters.' },
        { t: 'ochtends' },
        { t: 'de' },
        { t: 'vergadering' },
        { t: 'openen?' },
        { t: 'De' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: trema op de laatste e.' },
        { t: 'voor' },
        { t: 'het' },
        { t: 'project' },
        { t: 'staan' },
        { t: 'in' },
        { t: 'm’n' },
        { t: 'mail.' },
        { t: 'Thomas’' },
        { t: 'laptop' },
        { t: 'ligt' },
        { t: 'op' },
        { t: 'mijn' },
        { t: 'bureau.' },
        { t: 'Zet' },
        { t: 'je' },
        { t: 'de' },
        { t: 'koffie-machine', fix: 'koffiemachine', why: 'e + m botsen niet: een samenstelling schrijf je aan elkaar.' },
        { t: 'aan?' },
        { t: 'En' },
        { t: 'stuur' },
        { t: 'je' },
        { t: 'me' },
        { t: 'de' },
        { t: 'fotos', fix: 'foto’s', why: 'foto eindigt op o: meervoud met ’s.' },
        { t: 'van' },
        { t: 'gisteren?' },
        { t: 'Groetjes,' },
        { t: 'Sara' },
      ],
      done: {
        title: 'Appje verbeterd',
        text: 'auto-ongeluk, ’s ochtends, ideeën, koffiemachine en foto’s. m’n mag in een appje, en Thomas’ laptop was al goed.',
      },
    },
    {
      kind: 'type',
      id: 'noord-brabant',
      prompt: 'Typ de naam van de provincie: Noord + Brabant.',
      before: 'Eindhoven ligt in de provincie',
      after: '.',
      hint: 'Noord…',
      answer: 'Noord-Brabant',
      why: 'Noord + een aardrijkskundige naam: koppelteken, en allebei met een hoofdletter.',
    },
    {
      kind: 'rewrite',
      id: 'hoofdletters',
      prompt: 'Zet alle hoofdletters goed.',
      source: 'op dinsdag ga ik met meneer de vries naar het arabische restaurant in den haag.',
      accept: ['Op dinsdag ga ik met meneer De Vries naar het Arabische restaurant in Den Haag.'],
      why: 'Op: begin van de zin. dinsdag en meneer blijven klein. De Vries: achternaam zonder voornaam, dus ook De met hoofdletter. Arabische: komt van een naam. Den Haag: plaatsnaam.',
    },
    {
      kind: 'proofread',
      id: 'boodschappenlijst',
      prompt: 'Lees de boodschappenlijst na',
      intro: 'Er zitten vijf fouten in. Tik ze aan.',
      header: { subject: 'Boodschappen voor zaterdag' },
      tokens: [
        { t: 'zes' },
        { t: 'eieren,' },
        { t: 'twee' },
        { t: 'pizzas,', fix: 'pizza’s,', why: 'pizza eindigt op a: ’s.' },
        { t: 'mango’s,' },
        { t: 'kiwis,', fix: 'kiwi’s,', why: 'kiwi eindigt op i: ’s.' },
        { t: 'turkse', fix: 'Turkse', why: 'Een bijvoeglijk naamwoord van een naam (Turkije) krijgt een hoofdletter.' },
        { t: 'yoghurt,' },
        { t: 'Italiaanse' },
        { t: 'pasta,' },
        { t: 'Franse' },
        { t: 'kaas,' },
        { t: 'zonnebloem-olie,', fix: 'zonnebloemolie,', why: 'm + o botsen niet: aan elkaar.' },
        { t: 'drie' },
        { t: 'avocados', fix: 'avocado’s', why: 'avocado eindigt op o: ’s.' },
        { t: 'en' },
        { t: 'een' },
        { t: 'tv-gids.' },
      ],
      done: {
        title: 'De lijst klopt',
        text: 'pizza’s, kiwi’s, Turkse, zonnebloemolie en avocado’s. mango’s, Italiaanse, Franse en tv-gids waren al goed.',
      },
    },
    {
      kind: 'bet',
      id: 'zomers',
      prompt: 'Welke zin is helemaal goed?',
      options: ['’s Zomers gaan we naar Italië.', '’S zomers gaan we naar Italië.', '’s zomers gaan we naar Italie.'],
      answer: '’s Zomers gaan we naar Italië.',
      why: 'Begint de zin met ’s, dan krijgt het tweede woord de hoofdletter. Italië heeft een trema.',
    },
    {
      kind: 'type',
      id: 'thomas',
      prompt: 'Schrijf het bezit kort op: de telefoon van Thomas.',
      before: 'Dit is',
      after: 'telefoon.',
      hint: 'Thomas…',
      answer: 'Thomas’',
      why: 'Thomas eindigt op s: alleen een apostrof. Thomas’ telefoon.',
    },
    {
      kind: 'dictation',
      id: 'dictee-tv',
      prompt: 'Luister en typ de zin precies over.',
      intro: 'Een moeilijke: apostrofs, koppeltekens en hoofdletters.',
      sentence: '’s Avonds kijken mijn ex-collega’s naar een tv-programma over Zuid-Afrika.',
      right: 'Goed: ’s Avonds, ex-collega’s (koppelteken én apostrof), tv-programma en Zuid-Afrika.',
      wrong: 'Loop de zin na: ’s Avonds (hoofdletter op het tweede woord), ex-collega’s (ex- met koppelteken, collega op a: ’s), tv-programma (afkorting) en Zuid-Afrika (naam).',
    },
    {
      kind: 'proofread',
      id: 'uitnodiging',
      prompt: 'Lees de uitnodiging na',
      intro: 'Er zitten vijf fouten in, met hoofdletters, apostrofs, het trema en aan elkaar schrijven. Tik ze aan.',
      header: { to: 'de buren', subject: 'Uitnodiging' },
      tokens: [
        { t: 'Beste' },
        { t: 'buren,' },
        { t: 'Op' },
        { t: 'zaterdag' },
        { t: '12' },
        { t: 'Juli', fix: 'juli', why: 'Maanden schrijf je klein.' },
        { t: 'vieren' },
        { t: 'we' },
        { t: 'Annas', fix: 'Anna’s', why: 'Anna eindigt op a: bezit met ’s.' },
        { t: 'verjaardag' },
        { t: 'in' },
        { t: 'het' },
        { t: 'buurthuis.' },
        { t: 'Het' },
        { t: 'feest' },
        { t: 'begint' },
        { t: 's', fix: '’s', why: '’s avonds: apostrof voor de weggelaten letters.' },
        { t: 'avonds' },
        { t: 'om' },
        { t: 'acht' },
        { t: 'uur.' },
        { t: 'Er' },
        { t: 'is' },
        { t: 'muziek,' },
        { t: 'een' },
        { t: 'springkussen' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'kinderen' },
        { t: 'en' },
        { t: 'eten' },
        { t: 'van' },
        { t: 'een' },
        { t: 'Surinaams-Chinese' },
        { t: 'kok.' },
        { t: 'We' },
        { t: 'zijn' },
        { t: 'benieuwd' },
        { t: 'naar' },
        { t: 'jullie' },
        { t: 'ideeen', fix: 'ideeën', why: 'idee + en: trema op de laatste e.' },
        { t: 'voor' },
        { t: 'de' },
        { t: 'muziek.' },
        { t: 'Je' },
        { t: 'fiets' },
        { t: 'kun' },
        { t: 'je' },
        { t: 'kwijt' },
        { t: 'in' },
        { t: 'het' },
        { t: 'fietsen-rek', fix: 'fietsenrek', why: 'Een gewone samenstelling: aan elkaar.' },
        { t: 'naast' },
        { t: 'de' },
        { t: 'ingang.' },
        { t: 'Tot' },
        { t: 'dan!' },
        { t: 'Fatima' },
        { t: 'en' },
        { t: 'Joris' },
      ],
      done: {
        title: 'Iedereen is welkom',
        text: 'juli, Anna’s, ’s avonds, ideeën en fietsenrek. Surinaams-Chinese (twee gelijke delen, allebei van een naam) was al goed.',
      },
    },
  ],
};
