import type { LessonInput } from '../schema';

/**
 * Masterlessen voor het niveau "Het betekenisvolle woorddeel": drie modellen van morfologie,
 * inheemse en geleerde lagen met het haakjesparadox, productiviteit meten, prosodische
 * morfologie met een OT-tableau, het mentale lexicon (met de d/t-fout als bewijs) en
 * woordvorming in beweging. Ze bouwen voort op `deel.ts`.
 *
 * Eisnamen in OT-tableaus volgen de literatuur (Engels). Het sterretje van een verbod is het
 * teken ∗ (U+2217), omdat * in lesteksten een taalvoorbeeld markeert.
 */
export const DEEL_MASTER_LESSONS: LessonInput[] = [
  {
    id: 'd13',
    stage: 'master',
    domain: 'morf',
    also: ['syn'],
    title: 'Morfeem, proces of paradigma?',
    skill: 'Woorden',
    icon: 'IA',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Drie modellen van morfologie',
        panels: [
          {
            text: 'Welkom in de master, waar het morfeem verhoord wordt. Charles Hockett (1954) beschreef twee modellen en noemde een derde, veel ouder model. *Item-and-Arrangement*: een woord is een rijtje morfemen, *boek + en*. *Item-and-Process*: een woord ontstaat door een bewerking op een stam, zoals *loop* → *liep* (de klinker verandert). *Word-and-Paradigm*: het woord als geheel vult een cel in een tabel.',
            lab: {
              label: 'Tik een vorm',
              chips: [
                { k: 'boeken', out: 'Item-and-Arrangement', note: 'Netjes te knippen: boek + en.' },
                { k: 'liep', out: 'Item-and-Process', note: 'Niets te knippen: de klinker verandert. Waar is het morfeem ‘verleden tijd’?' },
                { k: 'loopt', out: 'Word-and-Paradigm', note: 'Eén -t voor jij én hij: de vorm hoort bij cellen, niet bij één betekenis.' },
              ],
            },
          },
          {
            text: 'Kijk naar het paradigma van *lopen*. Twee cellen delen dezelfde vorm: *jij loopt* en *hij loopt*. Dat heet *syncretisme*. En *ik loop* heeft geen uitgang: moet je daar een *nulmorfeem* aannemen? In een paradigma-model hoeft dat niet. De vorm *loop* vult gewoon die cel.',
            grid: {
              q: 'Tik de cellen met dezelfde werkwoordsvorm als ‘hij loopt’',
              cols: ['enkelvoud', 'meervoud'],
              rows: ['1e persoon', '2e persoon', '3e persoon'],
              cells: [
                { t: 'ik loop', row: 0, col: 0 },
                { t: 'jij loopt', row: 1, col: 0 },
                { t: 'hij loopt', row: 2, col: 0 },
                { t: 'wij lopen', row: 0, col: 1 },
                { t: 'jullie lopen', row: 1, col: 1 },
                { t: 'zij lopen', row: 2, col: 1 },
              ],
              targets: ['jij loopt', 'hij loopt'],
              note: 'Zes cellen, maar drie vormen. Het meervoud heeft er zelfs maar één voor drie personen.',
            },
            rule: 'Syncretisme: verschillende cellen van een paradigma met dezelfde vorm.',
          },
          {
            text: 'Nu het bewijsstuk. In een vraag verdwijnt de -t bij *jij*: *Loop jij?* Maar niet bij *hij*: *Loopt hij?* Als *-t* een morfeem was voor ‘tweede persoon’, zou het niet zomaar mogen verdwijnen. De vorm hangt af van de *cel*: tweede persoon, enkelvoud, mét het onderwerp erachter.',
            quiz: {
              q: 'Welke zin is goed?',
              options: ['Loop jij morgen mee?', 'Loopt jij morgen mee?'],
              answer: 'Loop jij morgen mee?',
              why: 'Staat jij achter de persoonsvorm, dan valt de -t weg. Bij hij blijft hij staan: Loopt hij mee?',
            },
            deep: {
              q: 'Wie verdedigt het paradigma vandaag?',
              a: 'Gregory Stump (*Inflectional Morphology*, 2001) en James Blevins (*Word and Paradigm Morphology*, 2016). Hun argument: talen zitten vol vormen die je niet netjes in morfemen kunt knippen. In het Latijnse *amō* (ik heb lief) betekent de *-ō* tegelijk eerste persoon, enkelvoud, tegenwoordige tijd, bedrijvende vorm. Dat heet *cumulatieve exponentie*: één stukje, vier betekenissen.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'model',
        prompt: 'Welk model beschrijft dit het makkelijkst?',
        buckets: ['Item-and-Arrangement', 'Item-and-Process', 'Word-and-Paradigm'],
        items: [
          { t: 'boek + en', b: 0 },
          { t: 'lees + baar', b: 0 },
          { t: 'loop → liep', b: 1 },
          { t: 'schip → schepen', b: 1 },
          { t: 'loopt (jij én hij)', b: 2 },
          { t: 'Loop jij?', b: 2 },
          { t: 'hond + je', b: 0 },
          { t: 'zing → zong', b: 1 },
          { t: 'wij, jullie, zij lopen', b: 2 },
        ],
        why: 'Knipbaar: IA. Klinkerwissel: IP. Syncretisme en een vorm die van de zin afhangt: WP.',
      },
      {
        kind: 'fix',
        id: 'jij',
        prompt: 'Tik het foute woord aan en verbeter het.',
        sentence: 'Wordt jij ook moe van al die regels?',
        wrong: 0,
        answer: 'word',
        why: 'jij staat achter de persoonsvorm: dan geen -t. Word jij ook moe?',
      },
      {
        kind: 'bet',
        id: 'nul',
        prompt: 'Heeft ‘ik loop’ een nulmorfeem?',
        options: ['Alleen in een morfeemmodel; in een paradigmamodel is dat niet nodig', 'Ja, altijd', 'Nee, ik loop heeft een uitgang -∅ die je kunt horen'],
        answer: 'Alleen in een morfeemmodel; in een paradigmamodel is dat niet nodig',
        why: 'Een nulmorfeem is een hulpmiddel van het IA-model. Het paradigmamodel zegt gewoon: deze cel heeft de vorm loop.',
      },
      {
        kind: 'rewrite',
        id: 'inversie',
        prompt: 'Maak er een vraag van: zet de persoonsvorm vooraan.',
        source: 'Jij loopt morgen mee.',
        accept: ['Loop jij morgen mee?'],
        why: 'Met jij achter de persoonsvorm valt de -t weg: Loop jij? De vorm hangt af van de cel én van de plek in de zin.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Exponentie en voorspelbaarheid',
        panels: [
          {
            text: 'Het omgekeerde van cumulatieve exponentie bestaat ook. In *gezongen* wordt ‘voltooid deelwoord’ drie keer uitgedrukt: door *ge-*, door de klinker *o* en door *-en*. Peter Matthews (1972) noemde dat *uitgebreide exponentie*: één betekenis, verspreid over meerdere stukken. Voor een model met één morfeem per betekenis is dat een probleem: welk stuk is nu het ‘echte’ morfeem?',
            split: {
              q: 'Knip gezongen in de stukken die ‘voltooid’ uitdrukken',
              word: 'gezongen',
              answer: 'ge-zong-en',
              note: 'ge-, de klinkerwissel naar o en -en: drie exponenten voor één cel van het paradigma.',
            },
            rule: 'Cumulatief: één stuk, meer betekenissen. Uitgebreid: één betekenis, meer stukken.',
          },
          {
            text: 'Gregory Stump (2001) ordende de theorieën in twee keuzes. *Lexicaal of inferentieel*: zijn affixen opgeslagen dingen, of regels die een stam veranderen? *Incrementeel of realisationeel*: voegt een affix betekenis toe, of drukt het een betekenis uit die al vastligt? *Distributed Morphology* van Morris Halle en Alec Marantz (1993) is lexicaal-realisationeel. Stumps eigen theorie is inferentieel-realisationeel, net als *A-Morphous Morphology* van Stephen Anderson (1992).',
            grid: {
              q: 'Tik de realisationele theorieën',
              cols: ['incrementeel', 'realisationeel'],
              rows: ['lexicaal', 'inferentieel'],
              cells: [
                { t: 'Lieber (1992)', row: 0, col: 0 },
                { t: 'Distributed Morphology', row: 0, col: 1 },
                { t: 'Stump (2001)', row: 1, col: 1 },
                { t: 'Anderson (1992)', row: 1, col: 1 },
              ],
              targets: ['Distributed Morphology', 'Stump (2001)', 'Anderson (1992)'],
              note: 'Realisationele theorieën verklaren uitgebreide exponentie makkelijker: de betekenis ligt vast, en meerdere regels mogen hem uitdrukken.',
            },
          },
          {
            text: 'Waarom leer je op school *stamtijden*: *zingen, zong, gezongen*? Omdat uit een paar cellen de rest volgt. Farrell Ackerman en Robert Malouf (2013) maten dat met informatietheorie. Hoe onvoorspelbaar een cel is als je een andere cel kent, heet de *voorwaardelijke entropie*. Hun stelling: in alle talen blijft die laag, hoe ingewikkeld het paradigma er ook uitziet. Vul de stamtijden in.',
            paradigm: {
              q: 'Vul de stamtijden in',
              cols: ['verleden tijd', 'voltooid deelwoord'],
              rows: [
                { label: 'zingen', cells: [{ fill: 'zong' }, 'gezongen'] },
                { label: 'vechten', cells: ['vocht', { fill: 'gevochten' }] },
                { label: 'schrijven', cells: [{ fill: 'schreef' }, { fill: 'geschreven' }] },
              ],
              extra: ['zingde', 'gevecht', 'geschrijfd'],
              note: 'Wie zong kent, raadt gezongen bijna zeker. Het paradigma is groot, maar de onzekerheid per cel klein.',
            },
          },
          {
            text: 'Hoe verklaart Distributed Morphology het raadsel van *Loop jij?* Een vorm als *-t* wordt opgeslagen met de kenmerken die hij nodig heeft: enkelvoud plus een persoon (2e of 3e). *∅* is de vorm voor ‘enkelvoud, verder niets’. Staat *jij* achter het werkwoord, dan schrapt een regel het kenmerk ‘2e persoon’. Bij *Loopt hij?* gebeurt dat niet. Daarna past *-t* niet meer en wint *∅*. Dat schrappen heet *verarming* (impoverishment).',
            quiz: {
              q: 'Wat gebeurt er volgens DM in ‘Loop jij?’',
              options: ['Een kenmerk wordt geschrapt, daarna past de vorm zonder -t', 'Het werkwoord krijgt een nulmorfeem voor jij', 'Jij wordt een voorvoegsel'],
              answer: 'Een kenmerk wordt geschrapt, daarna past de vorm zonder -t',
              why: 'Verarming haalt een kenmerk weg vóór de vormen worden ingevuld. Zo verklaart een morfeemmodel toch een verschijnsel dat bij het paradigma hoort.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'exponentie',
        prompt: 'Welk soort exponentie?',
        buckets: ['cumulatief', 'uitgebreid', 'nul'],
        items: [
          { t: 'Latijn amō: -ō', b: 0 },
          { t: 'Latijn rosārum: -ārum (meervoud + bezit)', b: 0 },
          { t: 'gezongen: ge- + o + -en', b: 1 },
          { t: 'kinderen: -er + -en', b: 1 },
          { t: 'ik loop: geen uitgang', b: 2 },
          { t: 'Engels two sheep: geen uitgang', b: 2 },
        ],
        why: 'Eén stuk voor meer betekenissen is cumulatief. Meer stukken voor één betekenis is uitgebreid. Een betekenis zonder hoorbaar stuk is nul.',
      },
      {
        kind: 'type',
        id: 'gezwommen',
        prompt: 'Typ de derde stamtijd.',
        before: 'zwemmen, zwom,',
        after: '',
        hint: 'ge…',
        answer: 'gezwommen',
        why: 'Wie zwom kent, raadt gezwommen: dezelfde o, plus ge- en -en. Weer uitgebreide exponentie.',
      },
      {
        kind: 'choice',
        id: 'dm',
        prompt: 'Welke theorie is lexicaal én realisationeel?',
        before: '',
        after: '',
        options: ['Distributed Morphology', 'A-Morphous Morphology', 'Item-and-Process'],
        answer: 'Distributed Morphology',
        why: 'DM slaat vormen op (lexicaal) en vult ze in voor kenmerken die al vastliggen (realisationeel). Anderson werkt met regels, niet met opgeslagen affixen.',
      },
      {
        kind: 'swipe',
        id: 'modellen',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'In gezongen wordt één betekenis door drie stukken uitgedrukt.', ok: true, why: 'Uitgebreide exponentie: ge-, o, -en.' },
          { t: 'Cumulatieve exponentie betekent: veel stukken, één betekenis.', ok: false, fix: 'Cumulatief is één stuk, veel betekenissen', why: 'Zoals Latijn -ō in amō.' },
          { t: 'Distributed Morphology is van Halle en Marantz.', ok: true, why: 'Uit 1993.' },
          { t: 'Volgens Ackerman en Malouf zijn paradigma’s nauwelijks voorspelbaar.', ok: false, fix: 'Ze zijn juist goed voorspelbaar: de voorwaardelijke entropie is laag', why: 'Uit een paar cellen volgt de rest.' },
          { t: 'Verarming schrapt een kenmerk voordat de vorm wordt ingevuld.', ok: true, why: 'Zo verklaart DM Loop jij?' },
          { t: 'Stump verdeelt theorieën in lexicaal of inferentieel, en incrementeel of realisationeel.', ok: true, why: 'Twee keuzes, vier vakjes.' },
        ],
      },
      {
        kind: 'bet',
        id: 'entropie',
        prompt: 'Waarom zijn stamtijden een goede leerstrategie?',
        options: [
          'De voorwaardelijke entropie is laag: uit enkele cellen volgt de rest',
          'Elke cel van het paradigma is willekeurig',
          'Het Nederlands heeft maar drie werkwoordsvormen',
        ],
        answer: 'De voorwaardelijke entropie is laag: uit enkele cellen volgt de rest',
        why: 'Dat is de stelling van Ackerman en Malouf (2013): paradigma’s zijn groot, maar intern goed voorspelbaar.',
      },
    ],
  },
  {
    id: 'd14',
    stage: 'master',
    domain: 'morf',
    also: ['fon', 'sem'],
    title: 'Inheems, geleerd en een paradox',
    skill: 'Woorden',
    icon: 'Ⅰ|Ⅱ',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Lagen in het woord',
        panels: [
          {
            text: 'Het Nederlands heeft twee soorten achtervoegsels. *Inheemse*, uit het Germaans: *-heid*, *-baar*, *-ig*. Ze laten de klemtoon met rust: *WAAR* → *WAARheid*. En *geleerde*, uit het Latijn en Frans: *-iteit*, *-isch*, *-atie*. Die trekken de klemtoon naar zich toe: *neuTRAAL* → *neutraliTEIT*. Bouw *productiviteit* op.',
            bracket: {
              tree: '[[product ief] iteit]',
              nodes: [
                { w: 'productief', cat: 'bn', note: 'Geleerd achtervoegsel -ief op een geleerde stam.' },
                { w: 'productiefiteit', form: 'productiviteit', cat: 'zn', note: '-iteit vraagt een geleerde stam en neemt de klemtoon: productiviTEIT. De f wordt v.' },
              ],
              traps: [{ w: 'iefiteit', note: 'Twee achtervoegsels zonder stam vormen geen woord. Begin bij product.' }],
              note: 'product → productief → productiviteit: de klemtoon schuift steeds mee naar rechts.',
            },
          },
          {
            text: 'De lagen hebben een volgorde. Een inheems achtervoegsel mag om een geleerd heen: *absurd-heid*. Andersom niet: *waarheiditeit* is onmogelijk. Ook bij voorvoegsels: geleerd *in-* past alleen op geleerde stammen en past zich aan: *inactief*, *illegaal*, *irreëel*. Inheems *on-* past overal: *onmogelijk*, *onlogisch*.',
            rule: 'Geleerde affixen zitten binnenin en verschuiven de klemtoon; inheemse affixen zitten erbuiten en laten de klemtoon met rust.',
            deep: {
              q: 'Waar komt dat idee vandaan?',
              a: 'Uit de *lexicale fonologie* van Paul Kiparsky (1982): het lexicon heeft niveaus, en klemtoonregels werken alleen op niveau 1, waar de geleerde affixen zitten. Jennifer Hay (2002) gaf een psychologische verklaring: affixen die je makkelijk loshaalt (*-heid*) staan buiten affixen die vergroeid zijn met hun stam (*-iteit*). Dat heet *complexity-based ordering*.',
            },
            quiz: {
              q: 'Welk woord is onmogelijk?',
              options: ['waarheiditeit', 'absurdheid', 'onlogisch'],
              answer: 'waarheiditeit',
              why: 'Een geleerd achtervoegsel (-iteit) kan niet om een inheems achtervoegsel (-heid) heen.',
            },
          },
          {
            text: 'Nu het raadsel. *Blauwogig* betekent ‘met blauwe ogen’. De betekenis zegt: [[blauw oog] ig]. Maar *blauwoog* bestaat niet als woord. En *ogig* ook niet. Dit heet een *haakjesparadox*: de betekenis wil de ene boom, de vorm kan geen van beide maken. Bouw de betekenisboom.',
            bracket: {
              q: 'Bouw de betekenis: met blauwe ogen',
              tree: '[[blauw oog] ig]',
              nodes: [
                { w: 'blauwoog', form: 'blauw oog', cat: 'groep', note: 'Eerst de woordgroep blauw oog: daar gaat het over.' },
                { w: 'blauwoogig', form: 'blauwogig', cat: 'bn', note: '-ig plakt aan de hele groep: met een blauw oog.' },
              ],
              traps: [{ w: 'oogig', note: 'ogig bestaat niet los. Toch plakt -ig in de klank aan oog: dat is precies de paradox.' }],
              note: '[[blauw oog] ig]: de betekenis plakt -ig aan een woordgroep. Ook in langharig en beeldend kunstenaar (iemand van de beeldende kunst).',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'klemtoon',
        prompt: 'Verschuift het achtervoegsel de klemtoon?',
        buckets: ['ja (geleerd)', 'nee (inheems)'],
        items: [
          { t: 'neutraal → neutraliteit', b: 0 },
          { t: 'idee → ideaal', b: 0 },
          { t: 'vriend → vriendelijk', b: 1 },
          { t: 'waar → waarheid', b: 1 },
          { t: 'lees → leesbaar', b: 1 },
          { t: 'stabiel → stabiliteit', b: 0 },
          { t: 'drama → dramatisch', b: 0 },
          { t: 'hoop → hopeloos', b: 1 },
        ],
        why: '-iteit en -aal nemen de klemtoon: neutraliTEIT, ideAAL, stabiliTEIT. -isch trekt hem naar zich toe: draMAtisch. -heid, -baar, -elijk en -loos laten hem staan.',
      },
      {
        kind: 'choice',
        id: 'in',
        prompt: 'Welk voorvoegsel past?',
        before: 'Een besluit dat niet rationeel is, is',
        after: '.',
        options: ['irrationeel', 'onrationeel', 'inrationeel'],
        answer: 'irrationeel',
        why: 'rationeel is geleerd, dus in-, en dat wordt ir- voor een r.',
      },
      {
        kind: 'bet',
        id: 'paradox',
        prompt: 'Waarom is ‘beeldend kunstenaar’ een haakjesparadox?',
        options: ['Het is iemand van de beeldende kunst, niet een kunstenaar die beeldend is', 'Het heeft twee klemtonen', 'Kunstenaar is geen woord'],
        answer: 'Het is iemand van de beeldende kunst, niet een kunstenaar die beeldend is',
        why: 'De betekenis is [[beeldende kunst] enaar], maar de vorm zet beeldend los voor kunstenaar.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Klemtoon, stamvorm en kritiek',
        panels: [
          {
            text: 'De klemtoon alleen bepaalt de laag niet. Er zijn drie soorten gedrag. *Klemtoonneutraal*: *WAARheid*, *HOpeloos*. *Zelf beklemtoond*: het achtervoegsel neemt de klemtoon, zoals *neutraliTEIT*. Maar ook de inheemse *-erij* en *-in* doen dat: *bakkeRIJ*, *vriendIN*. En *klemtoon ervóór*: *-isch* zet de klemtoon op de lettergreep vlak voor zich: *DRAma* → *draMAtisch*, *econoMIE* → *ecoNOmisch*.',
            lab: {
              label: 'Tik een achtervoegsel',
              chips: [
                { k: '-heid', out: 'neutraal: WAARheid', note: 'De stam houdt zijn klemtoon.' },
                { k: '-iteit', out: 'zelf beklemtoond: stabiliTEIT', note: 'Geleerd, en het neemt de klemtoon.' },
                { k: '-erij', out: 'zelf beklemtoond: bakkeRIJ', note: 'Inheems, en toch beklemtoond. Dus klemtoon is niet hetzelfde als herkomst.' },
                { k: '-isch', out: 'klemtoon ervóór: draMAtisch', note: 'De klemtoon springt naar de lettergreep vlak voor -isch.' },
              ],
            },
            rule: 'Beter criterium voor de geleerde laag: het affix kiest een geleerde stam en verandert vaak de vorm van die stam.',
          },
          {
            text: 'Geleerde achtervoegsels nemen hun eigen stamvormen mee uit het Latijn en Frans. *Nerveus* wordt *nervos-* in *nervositeit*, *variabel* wordt *variabil-* in *variabiliteit*. Een inheems achtervoegsel laat de stam zoals hij is: *nerveusheid* zou de stam niet veranderen. Vul de geleerde vormen in.',
            paradigm: {
              q: 'Maak het zelfstandig naamwoord op -iteit',
              cols: ['met -iteit'],
              rows: [
                { label: 'nerveus', cells: [{ fill: 'nervositeit', hint: 'eus wordt os.' }] },
                { label: 'curieus', cells: [{ fill: 'curiositeit' }] },
                { label: 'variabel', cells: [{ fill: 'variabiliteit', hint: 'abel wordt abil.' }] },
                { label: 'stabiel', cells: ['stabiliteit'] },
              ],
              extra: ['nerveusiteit', 'curieusiteit', 'variabeliteit'],
              note: '-eus → -os-, -abel → -abil-, -iel → -il-: de geleerde laag heeft zijn eigen stamallomorfen, geleend met de woorden zelf.',
            },
          },
          {
            text: 'Het Engels heeft precies dezelfde twee lagen. Dorothy Siegel (1974) noemde ze *klasse I* (Latijns-Frans, zoals *-ity*) en *klasse II* (Germaans, zoals *-ness*). *proDUCtive* → *producTIVity*: de klemtoon schuift. *proDUCtiveness*: hij blijft. Siegels volgorde (klasse I binnen, klasse II buiten) werd de basis van de lexicale fonologie van Kiparsky.',
            quiz: {
              q: 'Welk Engels woord houdt de klemtoon van ‘productive’?',
              options: ['productiveness', 'productivity'],
              answer: 'productiveness',
              why: '-ness is klasse II (Germaans): klemtoonneutraal, net als -heid. -ity is klasse I, net als -iteit.',
            },
          },
          {
            text: 'Is de strenge volgorde van de lagen wel waar? Nigel Fabb (1988) telde Engelse achtervoegsels en concludeerde dat elk achtervoegsel gewoon zijn eigen eisen stelt; lagen zijn niet nodig. Jennifer Hay en Ingo Plag (2004) vonden een tussenweg. Achtervoegsels staan in een vaste rangorde, van ‘vergroeid met de stam’ tot ‘makkelijk los te halen’. Wat je makkelijk loshaalt, staat buiten.',
            quiz: {
              q: 'Wat bepaalt volgens Hay en Plag de volgorde van achtervoegsels?',
              options: ['Hoe makkelijk je ze loshaalt', 'Alleen de herkomst', 'Het alfabet'],
              answer: 'Hoe makkelijk je ze loshaalt',
              why: 'Een goed herkenbaar achtervoegsel (zoals -heid of -ness) staat buiten een vergroeid achtervoegsel (zoals -iteit of -ity).',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'drie-soorten',
        prompt: 'Wat doet het achtervoegsel met de klemtoon?',
        buckets: ['neutraal', 'zelf beklemtoond', 'klemtoon ervóór'],
        items: [
          { t: 'waar → waarheid', b: 0 },
          { t: 'lees → leesbaar', b: 0 },
          { t: 'hoop → hopeloos', b: 0 },
          { t: 'stabiel → stabiliteit', b: 1 },
          { t: 'bakker → bakkerij', b: 1 },
          { t: 'vriend → vriendin', b: 1 },
          { t: 'drama → dramatisch', b: 2 },
          { t: 'economie → economisch', b: 2 },
          { t: 'fotografie → fotografisch', b: 2 },
        ],
        why: 'Neutraal: de stam houdt zijn klemtoon. Zelf beklemtoond: stabiliTEIT, bakkeRIJ, vriendIN. Klemtoon ervóór: draMAtisch, ecoNOmisch, fotoGRAfisch.',
      },
      {
        kind: 'choice',
        id: 'dramatisch',
        prompt: 'Waar ligt de klemtoon?',
        before: 'Het was een',
        after: 'einde.',
        options: ['draMAtisch', 'DRAmatisch', 'dramaTISCH'],
        answer: 'draMAtisch',
        why: '-isch zet de klemtoon op de lettergreep vlak ervoor.',
      },
      {
        kind: 'type',
        id: 'generositeit',
        prompt: 'Maak een zelfstandig naamwoord van genereus met -iteit.',
        before: 'Iedereen sprak over haar grote',
        after: '.',
        hint: 'gener…iteit',
        answer: 'generositeit',
        why: 'Net als nerveus → nervositeit: -eus wordt -os- voor -iteit.',
      },
      {
        kind: 'fix',
        id: 'stabiliteit',
        prompt: 'Tik het foute woord aan en verbeter het.',
        sentence: 'De stabieliteit van het netwerk is eindelijk goed.',
        wrong: 1,
        answer: 'stabiliteit',
        why: 'Voor -iteit gebruik je de geleerde stam stabil-: stabiliteit.',
      },
      {
        kind: 'swipe',
        id: 'lagen',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Alle beklemtoonde achtervoegsels zijn geleerd.', ok: false, fix: 'Ook inheemse -erij en -in zijn beklemtoond', why: 'bakkeRIJ, vriendIN.' },
          { t: '-isch zet de klemtoon op de lettergreep vlak ervoor.', ok: true, why: 'draMAtisch, ecoNOmisch.' },
          { t: 'Nervositeit gebruikt een geleerde stamvorm.', ok: true, why: 'nerveus → nervos-.' },
          { t: 'Siegel onderscheidde klasse I en klasse II in het Engels.', ok: true, why: 'Latijns-Frans binnen, Germaans buiten.' },
          { t: 'Fabb vond dat lagen onmisbaar zijn.', ok: false, fix: 'Fabb vond lagen overbodig: elk achtervoegsel stelt eigen eisen', why: 'Zijn kritiek uit 1988.' },
          { t: '-ness in productiveness laat de klemtoon staan.', ok: true, why: 'Klasse II, net als -heid.' },
        ],
      },
      {
        kind: 'bet',
        id: 'hay',
        prompt: 'Welke volgorde voorspellen Hay en Plag?',
        options: [
          'Het herkenbaarste achtervoegsel staat het verst van de stam',
          'Het oudste achtervoegsel staat het verst van de stam',
          'Het langste achtervoegsel staat het verst van de stam',
        ],
        answer: 'Het herkenbaarste achtervoegsel staat het verst van de stam',
        why: 'Wat je makkelijk loshaalt, staat buiten: absurd-iteit kan, waar-heid-iteit niet.',
      },
    ],
  },
  {
    id: 'd15',
    stage: 'master',
    domain: 'morf',
    title: 'Productiviteit meten',
    skill: 'Woorden',
    icon: 'P',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Hoe levend is een achtervoegsel?',
        panels: [
          {
            text: 'Eerst een experiment uit 1958. Jean Berko liet kinderen een verzonnen diertje zien: *Dit is een wug.* Dan twee: *Nu zijn er twee…* Kinderen zeiden zonder aarzelen *wugs*. Ze hadden *wugs* nooit gehoord, dus ze pasten een regel toe. Dat is de kern van productiviteit: nieuwe woorden maken.',
            quiz: {
              q: 'Wat zeg jij? Dit is een wug. Nu zijn er twee…',
              options: ['wuggen', 'wugs', 'wugen'],
              answer: 'wuggen',
              why: 'Eén beklemtoonde lettergreep met een korte klinker: -en, met een dubbele g. Net als bus, bussen.',
            },
          },
          {
            text: 'Harald Baayen bedacht hoe je productiviteit meet in een corpus. Tel alle woorden met het achtervoegsel (N). Tel dan de *hapaxen*: woorden die maar één keer voorkomen (n1). Zeldzame woorden zijn vaak net nieuw gemaakt. De productiviteit is *P = n1 / N*.',
            lab: {
              label: 'Tik een achtervoegsel (een bedacht minicorpus)',
              chips: [
                { k: '-heid', out: 'n1 = 40, N = 1000, P = 0,04', note: 'Veel eenmalige woorden: er worden nog steeds nieuwe gemaakt.' },
                { k: '-te', out: 'n1 = 1, N = 1000, P = 0,001', note: 'Vaak gebruikt (warmte, lengte), maar bijna nooit nieuw.' },
                { k: '-baar', out: 'n1 = 30, N = 600, P = 0,05', note: 'Minder vaak, maar zeer productief.' },
              ],
            },
            rule: 'Productiviteit P = aantal hapaxen / aantal voorkomens van het achtervoegsel.',
            deep: {
              q: 'Waarom juist hapaxen?',
              a: 'Een nieuw gevormd woord is per definitie zeldzaam. Het aandeel woorden dat maar één keer voorkomt, voorspelt hoe groot de kans is dat het volgende woord met dit achtervoegsel nieuw is. Baayen noemt dit de *potentiële productiviteit*. Laurie Bauer (2001) onderscheidt daarnaast *beschikbaarheid* (kan het nog?) en *rendabiliteit* (hoeveel gebeurt het?).',
            },
          },
          {
            text: 'Twee achtervoegsels kunnen even vaak voorkomen en toch heel anders leven. Dat zie je aan de verhouding. Reken zelf: een achtervoegsel komt 400 keer voor, en 20 van die woorden zijn hapaxen.',
            quiz: {
              q: 'Wat is P?',
              options: ['0,05', '0,5', '20'],
              answer: '0,05',
              why: '20 / 400 = 0,05.',
            },
          },
        ],
      },
      {
        kind: 'swipe',
        id: 'productief',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Een achtervoegsel dat vaak voorkomt, is altijd productief.', ok: false, fix: 'Vaak voorkomen is iets anders dan productief zijn', why: '-te zit in veel gewone woorden, maar maakt geen nieuwe meer.' },
          { t: 'Hapaxen zijn woorden die één keer in een corpus voorkomen.', ok: true, why: 'Grieks hapax legomenon: één keer gezegd.' },
          { t: 'De wug-test laat zien dat kinderen regels toepassen.', ok: true, why: 'Ze maakten een meervoud voor een woord dat ze nooit gehoord hadden.' },
          { t: 'Een hoge P betekent dat er nog vaak nieuwe woorden met het achtervoegsel bij komen.', ok: true, why: 'Veel hapaxen: veel net gemaakte woorden.' },
          { t: 'Met -te maak je vandaag makkelijk nieuwe woorden, zoals blauwte.', ok: false, fix: 'Met -te maak je bijna geen nieuwe woorden meer', why: 'warmte en lengte zijn oud; blauwte zegt niemand.' },
          { t: 'Jean Berko deed de wug-test in 1958.', ok: true, why: 'Met Engelstalige kinderen.' },
        ],
      },
      {
        kind: 'sort',
        id: 'levend',
        prompt: 'Productief of niet meer?',
        buckets: ['productief', 'niet meer'],
        items: [
          { t: '-heid', b: 0 },
          { t: '-baar', b: 0 },
          { t: '-er (lezer)', b: 0 },
          { t: '-te (warmte)', b: 1 },
          { t: '-sel (baksel)', b: 1 },
          { t: '-nis (kennis)', b: 1 },
          { t: '-ing (planning)', b: 0 },
          { t: '-de (liefde)', b: 1 },
        ],
        why: 'Met -heid, -baar en -er maak je dagelijks nieuwe woorden. -te, -sel en -nis zitten vooral in oude woorden.',
      },
      {
        kind: 'bet',
        id: 'swipebaar',
        prompt: 'Is ‘swipebaar’ een mogelijk Nederlands woord?',
        options: ['Ja: je swipet iets, en -baar is productief', 'Nee: Engelse stammen kunnen geen -baar krijgen'],
        answer: 'Ja: je swipet iets, en -baar is productief',
        why: 'Overgankelijk werkwoord + productief achtervoegsel: zo komt een nieuw woord de taal in.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Drie maten en hun valkuilen',
        panels: [
          {
            text: 'Baayen (1993) onderscheidde drie maten. *V*: hoeveel verschillende woorden met het achtervoegsel er al zijn (de *gerealiseerde* productiviteit). *P*: hapaxen gedeeld door alle voorkomens van het achtervoegsel (de *potentiële* productiviteit, die je al kent). *P∗*: hapaxen van het achtervoegsel gedeeld door álle hapaxen in het corpus. Die laatste zegt hoeveel het achtervoegsel bijdraagt aan de groei van de hele woordenschat.',
            lab: {
              label: 'Tik een maat (een bedacht corpus met 20.000 hapaxen)',
              chips: [
                { k: 'V', out: '-heid: 500 verschillende woorden', note: 'De omvang van de familie: hoeveel er al gemaakt is.' },
                { k: 'P', out: '-heid: 200 / 10.000 = 0,02', note: 'De kans dat het volgende -heid-woord nieuw is.' },
                { k: 'P∗', out: '-heid: 200 / 20.000 = 0,01', note: 'Eén op de honderd nieuwe woorden in het corpus is een -heid-woord.' },
              ],
            },
            rule: 'V: hoeveel er is. P: hoe groot de kans op iets nieuws is. P∗: hoeveel het affix bijdraagt aan alles wat nieuw is.',
          },
          {
            text: 'Een valkuil: P hangt af van de grootte van het corpus. Hoe meer tekst je leest, hoe vaker je een woord al eerder zag, dus hoe minder hapaxen. P daalt dus als N stijgt. Je mag twee achtervoegsels daarom alleen vergelijken bij dezelfde N. Baayen gebruikt daarvoor *groeicurven*: hoeveel nieuwe woorden er bijkomen terwijl je door het corpus leest. P is de helling aan het eind van die curve.',
            quiz: {
              q: 'A: N = 100, n1 = 20. B: N = 10.000, n1 = 500. Is A productiever?',
              options: ['Dat weet je niet: P moet je bij dezelfde N vergelijken', 'Ja, want 0,2 is meer dan 0,05', 'Nee, want 500 is meer dan 20'],
              answer: 'Dat weet je niet: P moet je bij dezelfde N vergelijken',
              why: 'Bij een kleine N is bijna alles nog een hapax. Neem van B ook de eerste 100 voorkomens, en vergelijk dan.',
            },
          },
          {
            text: 'Waarom is een afgeleid woord soms niet meer ‘doorzichtig’? Jennifer Hay (2001) keek naar de verhouding tussen een woord en zijn basis. Komt het afgeleide woord *vaker* voor dan de basis, zoals Engels *government* naast *govern*, dan halen mensen het minder uit elkaar. Zulke woorden dragen weinig bij aan de productiviteit: het affix wordt er niet in ‘gezien’.',
            quiz: {
              q: 'Welk afgeleid woord wordt volgens Hay het minst uit elkaar gehaald?',
              options: ['Een woord dat vaker voorkomt dan zijn basis', 'Een woord dat zeldzamer is dan zijn basis', 'Een hapax'],
              answer: 'Een woord dat vaker voorkomt dan zijn basis',
              why: 'Dan haal je het als geheel uit je geheugen. Een zeldzaam woord met een frequente basis bouw je juist op, en dan zie je het affix.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'maten',
        prompt: 'Welke maat hoort hierbij?',
        buckets: ['V', 'P', 'P∗'],
        items: [
          { t: 'aantal verschillende woorden met -heid', b: 0 },
          { t: 'hoe groot de -heid-familie al is', b: 0 },
          { t: 'hapaxen met -heid / alle voorkomens van -heid', b: 1 },
          { t: 'kans dat het volgende -heid-woord nieuw is', b: 1 },
          { t: 'hapaxen met -heid / alle hapaxen in het corpus', b: 2 },
          { t: 'aandeel van -heid in alle nieuwe woorden', b: 2 },
        ],
        why: 'V meet wat er al is, P de kans op iets nieuws binnen het affix, P∗ het aandeel van het affix in de groei van de hele woordenschat.',
      },
      {
        kind: 'choice',
        id: 'pster',
        prompt: 'Een corpus heeft 1000 hapaxen. Daarvan eindigen er 30 op -baar. Wat is P∗ van -baar?',
        before: '',
        after: '',
        options: ['0,03', '0,3', '30'],
        answer: '0,03',
        why: '30 / 1000 = 0,03: drie procent van alle nieuwe woorden is een -baar-woord.',
      },
      {
        kind: 'choice',
        id: 'pgetal',
        prompt: 'Een achtervoegsel komt 250 keer voor, met 50 hapaxen. Wat is P?',
        before: '',
        after: '',
        options: ['0,2', '0,02', '5'],
        answer: '0,2',
        why: '50 / 250 = 0,2. Let op: alleen vergelijken met andere affixen bij dezelfde N.',
      },
      {
        kind: 'order',
        id: 'rangorde',
        prompt: 'Zet van meest naar minst productief (bij dezelfde N): -heid P = 0,04, -te P = 0,001, -baar P = 0,05.',
        tiles: ['-heid', '-te', '-baar'],
        answer: '-baar -heid -te',
        why: '0,05 > 0,04 > 0,001. -te komt vaak voor, maar bijna nooit in een nieuw woord.',
      },
      {
        kind: 'swipe',
        id: 'valkuilen',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'P daalt meestal als het corpus groter wordt.', ok: true, why: 'Hoe meer je leest, hoe minder woorden nog maar één keer voorkomen.' },
          { t: 'Een groot V betekent dat een achtervoegsel nog productief is.', ok: false, fix: 'V meet alleen hoeveel er al is', why: '-te heeft veel woorden, maar maakt geen nieuwe meer.' },
          { t: 'P∗ deelt door alle hapaxen in het corpus.', ok: true, why: 'Zo zie je het aandeel van het affix in alles wat nieuw is.' },
          { t: 'Government wordt volgens Hay makkelijker uit elkaar gehaald dan een zeldzame afleiding.', ok: false, fix: 'Juist minder makkelijk, omdat het vaker voorkomt dan govern', why: 'Frequente afleidingen sla je als geheel op.' },
          { t: 'P is de helling aan het eind van de groeicurve.', ok: true, why: 'Hoe steil de curve nog stijgt, zo groot is de kans op een nieuw woord.' },
          { t: 'Je mag P van twee affixen altijd direct vergelijken.', ok: false, fix: 'Alleen bij dezelfde N', why: 'P hangt af van de grootte van de steekproef.' },
        ],
      },
      {
        kind: 'bet',
        id: 'zelfde-n',
        prompt: 'Een onderzoeker vergelijkt P van -heid in een krant van één dag met P van -baar in tien jaar kranten. Wat is het probleem?',
        options: ['De N verschilt enorm, dus de P-waarden zijn niet vergelijkbaar', 'Er is geen probleem', 'Kranten bevatten geen hapaxen'],
        answer: 'De N verschilt enorm, dus de P-waarden zijn niet vergelijkbaar',
        why: 'In een kleine steekproef is bijna alles een hapax. Vergelijk bij dezelfde N, bijvoorbeeld met groeicurven.',
      },
    ],
  },
  {
    id: 'd16',
    stage: 'master',
    domain: 'morf',
    also: ['fon'],
    title: 'Woordbouw met een maatlat',
    skill: 'Woorden',
    icon: 'σσ',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Prosodische morfologie',
        panels: [
          {
            text: 'Waarom heet je professor *prof* en niet *profes*? Afkortingen volgen een maat. *Prof*, *lab*, *info*, *uni*, *aso*: één zware lettergreep, of een sterke plus een zwakke. Dat is het *minimale woord* uit De lettergreep, nu als mal voor morfologie.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'professor', out: 'prof', note: 'Eén zware lettergreep: korte klinker plus coda.' },
                { k: 'laboratorium', out: 'lab', note: 'Weer één zware lettergreep.' },
                { k: 'informatie', out: 'info', note: 'Sterk-zwak: een trochee.' },
                { k: 'universiteit', out: 'uni', note: 'Ook een trochee.' },
              ],
            },
          },
          {
            text: 'Roepnamen doen hetzelfde, maar ze bewaren de *beklemtoonde* lettergreep. *E-LI-sa-beth* wordt *Lies*. *Mar-ga-RE-tha* wordt *Griet*. *Wil-hel-MI-na* wordt *Mien*. De morfologie knipt hier geen morfeem af, maar een prosodische eenheid.',
            quiz: {
              q: 'Welke roepnaam past bij Jo-HAN-na?',
              options: ['Hanna', 'Jo', 'Johan'],
              answer: 'Hanna',
              why: 'De beklemtoonde lettergreep blijft, aangevuld tot een trochee: HAN-na.',
            },
            rule: 'Prosodische morfologie: de vorm van een woord wordt bepaald door een maat (lettergreep, voet, minimaal woord), niet door een morfeem.',
          },
          {
            text: 'Ook het meervoud luistert naar een maat. Na een onbeklemtoonde lettergreep kiest het Nederlands *-s*: *tafels*, niet *tafelen*. Met *-en* zouden er twee zwakke lettergrepen achter elkaar staan. Zet de eisen in de goede volgorde.',
            tableau: {
              input: '/taːfəl + MV/',
              constraints: [
                { name: 'MV=-EN', note: 'Gebruik -en, de gewone meervoudsvorm.' },
                { name: '∗LAPSE', note: 'Geen twee onbeklemtoonde lettergrepen achter elkaar.' },
              ],
              candidates: [
                { form: '[TAː.fə.lən]', marks: [0, 1] },
                { form: '[TAː.fəls]', marks: [1, 0] },
              ],
              winner: 1,
              goal: 'Laat tafels winnen',
              note: '∗LAPSE boven MV=-EN: het ritme wint van de standaardvorm. Bij boeken is er geen conflict, dus daar wint -en.',
            },
            deep: {
              q: 'Wie werkte dit uit?',
              a: 'Geert Booij (1998) liet zien dat de Nederlandse meervoudskeuze een *prosodische outputeis* is: het woord eindigt het liefst op een trochee. Marc van Oostendorp en anderen werkten dat uit in Optimaliteitstheorie. Bij *leraren* en *vijanden* wint toch *-en*: zulke uitzonderingen sla je per woord op in je lexicon.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'maat',
        prompt: 'Welke maat heeft de afkorting?',
        buckets: ['één zware lettergreep', 'sterk + zwak'],
        items: [
          { t: 'prof', b: 0 },
          { t: 'lab', b: 0 },
          { t: 'Lies', b: 0 },
          { t: 'info', b: 1 },
          { t: 'uni', b: 1 },
          { t: 'Hanna', b: 1 },
          { t: 'bieb', b: 0 },
          { t: 'Griet', b: 0 },
          { t: 'demo', b: 1 },
        ],
        why: 'Allebei zijn het minimale woorden: minstens twee moras, en nooit langer dan één voet.',
      },
      {
        kind: 'bet',
        id: 'bezem',
        prompt: 'Welk meervoud voorspelt ∗LAPSE voor ‘bezem’?',
        options: ['bezems', 'bezemen'],
        answer: 'bezems',
        why: 'BE-zem eindigt onbeklemtoond. Met -en kreeg je BE-ze-men: twee zwakke lettergrepen.',
      },
      {
        kind: 'type',
        id: 'lies',
        prompt: 'Typ de roepnaam.',
        before: 'Elisabeth wordt vaak',
        after: 'genoemd.',
        hint: 'één lettergreep',
        answer: 'Lies',
        why: 'e-LI-sa-beth: de beklemtoonde lettergreep LI, aangevuld tot een zware lettergreep: Lies.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Mallen in andere talen',
        panels: [
          {
            text: 'Prosodische morfologie begon bij het Arabisch. Daar bestaat een woord uit een *wortel* van medeklinkers, zoals *k-t-b* (schrijven), en een *patroon* van klinkers en plekken. John McCarthy (1981) liet zien dat dat patroon een prosodische mal is: een vaste reeks lettergrepen waar de medeklinkers in vallen. Dezelfde wortel levert zo heel verschillende woorden.',
            lab: {
              label: 'Tik een mal voor de wortel k-t-b',
              chips: [
                { k: 'CaCaCa', out: 'kataba', note: 'Hij schreef.' },
                { k: 'CaaCiC', out: 'kaatib', note: 'Schrijver: iemand die het doet.' },
                { k: 'CiCaaC', out: 'kitaab', note: 'Boek.' },
                { k: 'maCCaC', out: 'maktab', note: 'Kantoor: de plek waar je schrijft.' },
                { k: 'CuCuC', out: 'kutub', note: 'Boeken: het meervoud is een andere mal, geen achtervoegsel.' },
              ],
            },
            rule: 'In het Arabisch is een woord een wortel van medeklinkers in een prosodische mal.',
          },
          {
            text: 'Ook *reduplicatie* (verdubbeling) werkt met een mal. Het Indonesisch verdubbelt het hele woord: *rumah* (huis), *rumah-rumah* (huizen). Het Ilokano, een taal van de Filipijnen, verdubbelt alleen een stuk: *púsa* (kat), *puspúsa* (katten). Welk stuk? Precies één zware lettergreep. McCarthy en Alan Prince (1986) zagen daarin hetzelfde patroon als in jouw *prof*.',
            quiz: {
              q: 'Wat verdubbelt het Ilokano in puspúsa?',
              options: ['Eén zware lettergreep: pus', 'Het hele woord', 'Alleen de klinker u'],
              answer: 'Eén zware lettergreep: pus',
              why: 'De mal is een zware lettergreep: pu + s. Net als prof een zware lettergreep is.',
            },
          },
          {
            text: 'In het Tagalog wordt het stukje *um* een *tussenvoegsel*: *sulat* (schrijven) wordt *sumulat*. Waarom niet gewoon *umsulat*? Omdat een lettergreep het liefst op een klinker eindigt (NOCODA, uit De lettergreep). In *um.su.lat* sluit de *m* een lettergreep af; in *su.mu.lat* niet. Het tussenvoegsel schuift dus net zover naar binnen als nodig. Zet de eisen in de goede volgorde.',
            tableau: {
              input: '/um + sulat/',
              constraints: [
                { name: 'ALIGN-L(um)', note: 'um staat helemaal vooraan in het woord.' },
                { name: 'NOCODA', note: 'Een lettergreep eindigt op een klinker.' },
              ],
              candidates: [
                { form: '[um.su.lat]', marks: [0, 2] },
                { form: '[su.mu.lat]', marks: [1, 1] },
              ],
              winner: 1,
              goal: 'Laat sumulat winnen',
              note: 'NOCODA boven ALIGN-L: um schuift één klank naar binnen, zodat de m geen lettergreep meer afsluit. De t van lat blijft voor allebei een coda. Zo analyseerden Prince en Smolensky (1993) het Tagalog.',
            },
          },
          {
            text: 'Het Engels heeft één levend tussenvoegsel: een krachtterm. *Abso-bloody-lutely*, *fan-bloody-tastic*. McCarthy (1982) liet zien dat de krachtterm altijd vóór de beklemtoonde voet komt: *abso-LUTE-ly* wordt *abso-bloody-LUTE-ly*. *Ab-bloody-solutely* zegt niemand, want daar breekt hij de voet *abso* in tweeën.',
            quiz: {
              q: 'Welke vorm klinkt natuurlijk?',
              options: ['fan-bloody-tastic', 'fanta-bloody-stic', 'fantas-bloody-tic'],
              answer: 'fan-bloody-tastic',
              why: 'fan-TAS-tic: de klemtoon ligt op tas. De krachtterm gaat vlak voor de beklemtoonde voet.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'proces',
        prompt: 'Welk prosodisch proces?',
        buckets: ['afkapping', 'reduplicatie', 'tussenvoegsel', 'mal met wortel'],
        items: [
          { t: 'professor → prof', b: 0 },
          { t: 'Elisabeth → Lies', b: 0 },
          { t: 'púsa → puspúsa', b: 1 },
          { t: 'rumah → rumah-rumah', b: 1 },
          { t: 'sulat → sumulat', b: 2 },
          { t: 'absolutely → abso-bloody-lutely', b: 2 },
          { t: 'k-t-b → kitaab', b: 3 },
          { t: 'k-t-b → kaatib', b: 3 },
        ],
        why: 'Afkappen tot een minimaal woord, verdubbelen volgens een mal, een tussenvoegsel op een prosodische plek, en medeklinkers in een mal gieten.',
      },
      {
        kind: 'choice',
        id: 'bumili',
        prompt: 'In het Tagalog is bili ‘kopen’. Welke vorm met um is goed?',
        before: '',
        after: '',
        options: ['bumili', 'umbili', 'bilium'],
        answer: 'bumili',
        why: 'Net als sumulat: um schuift achter de eerste medeklinker. Zo wordt de m het begin van een lettergreep (bu.mi.li) in plaats van een coda.',
      },
      {
        kind: 'type',
        id: 'orang',
        prompt: 'In het Indonesisch is orang ‘mens’. Typ ‘mensen’.',
        before: '',
        after: '',
        hint: 'verdubbel',
        answer: 'orang-orang',
        why: 'Het Indonesisch verdubbelt het hele woord voor een meervoud: orang-orang.',
      },
      {
        kind: 'choice',
        id: 'krachtterm',
        prompt: 'Waar komt de krachtterm in ‘incredible’ (in-CRED-i-ble)?',
        before: '',
        after: '',
        options: ['in-bloody-credible', 'incred-bloody-ible', 'incredi-bloody-ble'],
        answer: 'in-bloody-credible',
        why: 'De klemtoon ligt op cred. De krachtterm gaat vlak voor de beklemtoonde voet.',
      },
      {
        kind: 'swipe',
        id: 'mallen',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'In het Arabisch maak je het meervoud kutub met een achtervoegsel.', ok: false, fix: 'kutub gebruikt een andere mal, geen achtervoegsel', why: 'kitaab → kutub: andere klinkers en plekken rond k-t-b.' },
          { t: 'Het Ilokano verdubbelt een zware lettergreep.', ok: true, why: 'púsa → puspúsa.' },
          { t: 'In sumulat wint NOCODA van ALIGN-L.', ok: true, why: 'Daarom schuift um naar binnen: su.mu.lat heeft een coda minder dan um.su.lat.' },
          { t: 'McCarthy (1981) werkte de Arabische mallen uit.', ok: true, why: 'Het begin van de prosodische morfologie.' },
          { t: 'Ab-bloody-solutely is de natuurlijke Engelse vorm.', ok: false, fix: 'abso-bloody-lutely', why: 'De krachtterm komt vlak voor de beklemtoonde voet.' },
          { t: 'Prof en puspúsa gebruiken allebei een zware lettergreep als mal.', ok: true, why: 'Dezelfde prosodische eenheid in twee heel verschillende talen.' },
        ],
      },
      {
        kind: 'bet',
        id: 'daaris',
        prompt: 'De wortel d-r-s betekent ‘studeren’. Welke vorm betekent ‘iemand die studeert’?',
        options: ['daaris', 'darasa', 'madrasa'],
        answer: 'daaris',
        why: 'Dezelfde mal als kaatib (CaaCiC): de doener. darasa is ‘hij studeerde’, madrasa ‘school’: de plek, met ma- zoals maktab.',
      },
    ],
  },
  {
    id: 'd17',
    stage: 'master',
    domain: 'morf',
    also: ['orth'],
    title: 'Opslaan of opbouwen?',
    skill: 'Spelling',
    icon: 'ψ',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Het mentale lexicon',
        panels: [
          {
            text: 'Haal je *boeken* als één geheel uit je geheugen, of bouw je het elke keer op uit *boek + en*? Steven Pinker zei: onregelmatige vormen (*liep*) sla je op, regelmatige (*werkte*) bouw je met een regel. Maar Nederlands onderzoek van Baayen, Dijkstra en Schreuder (1997) liet zien dat je ook regelmatige meervouden sneller herkent als ze vaak voorkomen. Die zijn dus ook opgeslagen.',
            quiz: {
              q: 'Wat bewijst een frequentie-effect bij regelmatige vormen?',
              options: ['Dat ook regelmatige vormen als geheel opgeslagen worden', 'Dat alles met regels gaat', 'Dat frequentie niet uitmaakt'],
              answer: 'Dat ook regelmatige vormen als geheel opgeslagen worden',
              why: 'Een regel heeft geen geheugen. Als vaak gebruikte vormen sneller gaan, liggen ze klaar.',
            },
          },
          {
            text: 'Ook de *familie* van een woord telt. *Werk* heeft een grote familie: *werker*, *werkplaats*, *bewerken*, *werkloos*. Schreuder en Baayen (1997) vonden dat je woorden met een grote familie sneller herkent, ook als het woord zelf zeldzaam is. En je brein knipt al op vorm voordat het de betekenis kent: in het Engels helpt *corner* je om *corn* te herkennen (Rastle en collega’s, 2004), ook al heeft een hoek niets met maïs te maken.',
            rule: 'Je mentale lexicon slaat veel op én knipt: twee routes die tegelijk racen.',
            quiz: {
              q: 'Welk woord herken je volgens Schreuder en Baayen sneller?',
              options: ['een zeldzaam woord met een grote familie', 'een even zeldzaam woord met een kleine familie'],
              answer: 'een zeldzaam woord met een grote familie',
              why: 'De familie helpt mee: alle verwante woorden maken de stam sterker in je geheugen.',
            },
          },
          {
            text: 'Nu het deel dat elke schrijver raakt: de d/t-fout. *Hij vind* in plaats van *hij vindt*. Dominiek Sandra, Steven Frisson en Frans Daems (1999) lieten zien dat zulke fouten vooral gebeuren als de foute vorm *vaker voorkomt* dan de goede, en als er woorden tussen het onderwerp en het werkwoord staan. Je brein grijpt dan de opgeslagen vorm, in plaats van de regel toe te passen.',
            mark: {
              q: 'Tik het werkwoord waar je brein zich makkelijk vergist',
              sentence: 'Mijn broer die in Gent woont vindt het boek mooi.',
              targets: [6],
              note: 'Tussen broer en vindt staan vier woorden. Hoe langer de afstand, hoe groter de kans op hij vind.',
            },
            deep: {
              q: 'Hoe vermijd je de fout dan?',
              a: 'Vertrouw niet op wat er ‘goed uitziet’, want dat is juist de opgeslagen vorm. Zoek het onderwerp, zet het naast het werkwoord en pas de regel bewust toe: *hij* + *vind* + *t*. Vervang bij twijfel door *lopen*: *hij loopt*, dus *hij vindt*. Zo schakel je de tweede route in.',
            },
          },
        ],
      },
      {
        kind: 'fix',
        id: 'vindt',
        prompt: 'Tik het foute woord aan en verbeter het.',
        sentence: 'De man die naast ons woont vind ons te luidruchtig.',
        wrong: 6,
        answer: 'vindt',
        why: 'Onderwerp: de man (hij). Hij loopt, dus hij vindt. De bijzin ertussen lokt de fout uit.',
      },
      {
        kind: 'swipe',
        id: 'dt',
        prompt: 'Goed of fout?',
        cards: [
          { t: 'Het boek dat ik gisteren las word verfilmd.', ok: false, fix: 'word → wordt', why: 'Onderwerp het boek: het wordt.' },
          { t: 'Word jij ook zo moe van dat geluid?', ok: true, why: 'jij achter de persoonsvorm: geen -t.' },
          { t: 'Mijn zus die in Leiden studeert, vindt dat ook.', ok: true, why: 'Onderwerp mijn zus: zij vindt.' },
          { t: 'Hij antwoord niet op mijn berichten.', ok: false, fix: 'antwoord → antwoordt', why: 'Stam antwoord + t.' },
          { t: 'Wat jij vindt, vind ik ook.', ok: true, why: 'jij vindt (jij voor het werkwoord), vind ik (ik: alleen de stam).' },
          { t: 'Het pakket dat gisteren kwam, word vandaag teruggestuurd.', ok: false, fix: 'word → wordt', why: 'Onderwerp het pakket: het wordt. De bijzin ertussen lokt de fout uit.' },
          { t: 'Vind jij dat ook?', ok: true, why: 'jij achter de persoonsvorm: geen -t.' },
        ],
      },
      {
        kind: 'bet',
        id: 'route',
        prompt: 'Waarom schrijft een goede speller toch soms ‘hij vind’?',
        options: ['De opgeslagen vorm vind is sneller dan de regel', 'Hij kent de regel niet', 'Vind en vindt klinken anders'],
        answer: 'De opgeslagen vorm vind is sneller dan de regel',
        why: 'Twee routes racen. Onder tijdsdruk wint de snelle geheugenroute, en die levert de vaakst geziene vorm.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Modellen, netwerken en patiënten',
        panels: [
          {
            text: 'Hoe ziet zo’n race eruit? Uli Frauenfelder en Robert Schreuder (1992) stelden een *morfologisch racemodel* voor. Bij elk woord starten twee routes tegelijk: de *geheugenroute* zoekt het hele woord, de *opbouwroute* knipt het in stukken. De snelste wint. Al eerder lieten Marcus Taft en Kenneth Forster (1975) zien dat lezers voorvoegsels proberen af te strippen, ook bij woorden waar dat niet klopt.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'boeken', out: 'geheugenroute wint', note: 'Een vaak gebruikte vorm ligt klaar.' },
                { k: 'kerkbanken', out: 'opbouwroute wint', note: 'Zeldzaam als geheel, maar de stukken zijn bekend.' },
                { k: 'gezongen', out: 'geheugenroute wint', note: 'Onregelmatig: knippen helpt weinig.' },
                { k: 'swipebaar', out: 'alleen de opbouwroute', note: 'Een nieuw woord staat nog niet in je geheugen.' },
              ],
            },
            rule: 'Racemodel: geheugen en opbouw starten tegelijk; frequentie en doorzichtigheid bepalen wie wint.',
          },
          {
            text: 'Moeten er wel regels zijn? David Rumelhart en James McClelland (1986) bouwden een *neuraal netwerk* dat Engelse verleden tijden leerde, zonder één regel. Steven Pinker en Alan Prince (1988) vielen het model hard aan: het maakte fouten die geen mens maakt. Michael Ullman en collega’s (1997) vonden steun voor twee systemen: patiënten met Parkinson hadden meer moeite met regelmatige vormen, patiënten met Alzheimer met onregelmatige.',
            quiz: {
              q: 'Wat suggereren de patiënten van Ullman?',
              options: ['Regelmatig en onregelmatig gebruiken deels verschillende systemen in het brein', 'Alle vormen worden op dezelfde manier gemaakt', 'Onregelmatige vormen bestaan niet'],
              answer: 'Regelmatig en onregelmatig gebruiken deels verschillende systemen in het brein',
              why: 'Een dubbele dissociatie: het ene systeem kan uitvallen terwijl het andere werkt. Dat past bij woorden plus regels, al blijft het debat open.',
            },
          },
          {
            text: 'Knipt je brein ook als de betekenis niet klopt? Bij snel, half onbewust lezen wel: *corner* helpt *corn* (zie de eerste uitleg). Maar William Marslen-Wilson en collega’s (1994) vonden dat bij luisteren, met meer tijd voor de betekenis, alleen *doorzichtige* paren elkaar helpen. *Departure* helpt *depart*. *Department* helpt *depart* niet, want een afdeling heeft niets met vertrekken te maken.',
            quiz: {
              q: 'Helpt het horen van ‘department’ je om ‘depart’ te herkennen?',
              options: ['Nee: de betekenis is niet doorzichtig', 'Ja: de vorm is gelijk', 'Alleen als je Engels moedertaal is'],
              answer: 'Nee: de betekenis is niet doorzichtig',
              why: 'Vroeg in het lezen telt de vorm, later de betekenis. Twee fasen, twee soorten knippen.',
            },
          },
          {
            text: 'Het geheugen-effect raakt ook *gebeurd* en *gebeurt*. Je hoort ze precies hetzelfde. *Het is gebeurd* is een voltooid deelwoord: *gebeuren* begint al met het voorvoegsel *ge-*, dus er komt geen extra *ge-* bij, alleen *-d*. *Het gebeurt* is de persoonsvorm: stam + *t*. Omdat de twee vormen allebei vaak voorkomen, grijpt je geheugen makkelijk de verkeerde. Zoek dus eerst: is het een voltooid deelwoord of een persoonsvorm?',
            mark: {
              q: 'Tik het voltooid deelwoord',
              sentence: 'Wat er gisteren gebeurd is, gebeurt vandaag nooit meer.',
              targets: [3],
              note: 'gebeurd hoort bij is: voltooid deelwoord, met d (gebeurde, dus gebeurd). gebeurt is de persoonsvorm: het gebeurt.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'pinker',
        prompt: 'Volgens Pinker: komt de vorm uit het geheugen of uit een regel?',
        buckets: ['geheugen', 'regel'],
        items: [
          { t: 'liep', b: 0 },
          { t: 'ging', b: 0 },
          { t: 'gezongen', b: 0 },
          { t: 'kinderen', b: 0 },
          { t: 'werkte', b: 1 },
          { t: 'gefietst', b: 1 },
          { t: 'geappt', b: 1 },
          { t: 'tafels', b: 1 },
        ],
        why: 'Onregelmatig: geheugen. Regelmatig: regel. Maar onthoud Baayen: ook vaak gebruikte regelmatige vormen liggen klaar in je geheugen.',
      },
      {
        kind: 'proofread',
        id: 'nalezen',
        prompt: 'Lees de tekst na',
        intro: 'Er zitten drie werkwoordsfouten in. Tik ze aan.',
        tokens: [
          { t: 'Wat' },
          { t: 'er' },
          { t: 'gisteren' },
          { t: 'gebeurt', fix: 'gebeurd', why: 'Voltooid deelwoord bij is: gebeurde, dus gebeurd.' },
          { t: 'is,' },
          { t: 'weet' },
          { t: 'niemand.' },
          { t: 'Mijn' },
          { t: 'broer,' },
          { t: 'die' },
          { t: 'alles' },
          { t: 'beter' },
          { t: 'weet,' },
          { t: 'vind', fix: 'vindt', why: 'Onderwerp mijn broer: hij vindt. De bijzin ertussen lokt de fout uit.' },
          { t: 'het' },
          { t: 'niet' },
          { t: 'erg.' },
          { t: 'Hij' },
          { t: 'word', fix: 'wordt', why: 'hij + stam + t: wordt.' },
          { t: 'daar' },
          { t: 'nooit' },
          { t: 'boos' },
          { t: 'over.' },
        ],
        done: { title: 'Alle drie gevonden', text: 'Elke fout was een vorm die je even vaak ziet als de goede. Daarom helpt alleen de regel: zoek het onderwerp, en kijk of het een deelwoord is.' },
      },
      {
        kind: 'choice',
        id: 'gebeurd',
        prompt: 'Kies de goede vorm.',
        before: 'Niemand weet precies wat er die nacht is',
        after: '.',
        options: ['gebeurd', 'gebeurt'],
        answer: 'gebeurd',
        why: 'Hoort bij is: voltooid deelwoord. Gebeurde, dus gebeurd.',
      },
      {
        kind: 'dictation',
        id: 'dictee',
        prompt: 'Luister en typ de zin.',
        sentence: 'Wat hij vindt, wordt nooit gevraagd.',
        right: 'Goed: hij vindt en het wordt, allebei stam + t.',
        wrong: 'Let op: hij vindt (stam vind + t) en wat … wordt (stam word + t). Je hoort de t niet, dus de regel moet het werk doen.',
      },
      {
        kind: 'swipe',
        id: 'modellen',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'In het racemodel starten de geheugenroute en de opbouwroute tegelijk.', ok: true, why: 'De snelste route levert het woord.' },
          { t: 'Het netwerk van Rumelhart en McClelland gebruikte regels.', ok: false, fix: 'Het leerde zonder regels', why: 'Dat was juist het punt: patronen zonder regels.' },
          { t: 'Het horen van department helpt om depart te herkennen.', ok: false, fix: 'Alleen doorzichtige paren helpen dan', why: 'Een afdeling heeft niets met vertrekken te maken.' },
          { t: 'Taft en Forster vonden dat lezers voorvoegsels proberen af te strippen.', ok: true, why: 'Ook bij woorden waar dat niet klopt.' },
          { t: 'Gebeurd en gebeurt klinken hetzelfde.', ok: true, why: 'Daarom grijpt je geheugen makkelijk de verkeerde.' },
          { t: 'Ullman vond dat Parkinson vooral onregelmatige vormen raakt.', ok: false, fix: 'Parkinson raakt vooral regelmatige vormen', why: 'Alzheimer raakte juist de onregelmatige.' },
        ],
      },
      {
        kind: 'bet',
        id: 'department',
        prompt: 'Wanneer helpt het lezen van ‘corner’ wél om ‘corn’ te herkennen?',
        options: ['Bij heel snel, half onbewust lezen', 'Alleen als je aan maïs denkt', 'Nooit'],
        answer: 'Bij heel snel, half onbewust lezen',
        why: 'Vroeg in het lezen knipt je brein op vorm (Rastle en collega’s). Later telt de betekenis (Marslen-Wilson en collega’s).',
      },
    ],
  },
  {
    id: 'd18',
    stage: 'master',
    domain: 'morf',
    also: ['orth', 'prag'],
    title: 'Woorden in beweging',
    skill: 'Spelling',
    icon: '↻',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Hoe affixen ontstaan en leenwoorden landen',
        panels: [
          {
            text: 'Achtervoegsels vallen niet uit de lucht. Het waren ooit gewone woorden. *-lijk* komt van een oud woord voor lichaam of gedaante (vergelijk *lijk* en Engels *like*): *vriendelijk* is ‘met de gedaante van een vriend’. *-heid* was een woord voor ‘wijze, staat’. Een woord dat een achtervoegsel wordt, heet *grammaticalisatie*.',
            lab: {
              label: 'Tik een achtervoegsel',
              chips: [
                { k: '-lijk', out: 'van lic: lichaam, gedaante', note: 'vriendelijk: met de gedaante van een vriend.' },
                { k: '-heid', out: 'van heid: wijze, staat', note: 'vrijheid: de staat van vrij zijn.' },
                { k: '-dom', out: 'van dom: oordeel, toestand', note: 'rijkdom, christendom. Engels kingdom.' },
              ],
            },
          },
          {
            text: 'Het gebeurt nog steeds. *Reuze-*, *kei-*, *mega-* en *top-* zijn woorden die als voorvoegsel gaan werken: *reuzeleuk*, *keigoed*, *topprestatie*. Geert Booij noemt ze *affixoïden*: half woord, half affix. En soms gaat woordvorming achteruit: van *stofzuiger* maakten mensen het werkwoord *stofzuigen*. Dat heet *terugvorming*.',
            quiz: {
              q: 'Wat kwam eerst?',
              options: ['beeldhouwer', 'beeldhouwen'],
              answer: 'beeldhouwer',
              why: 'Terugvorming: uit beeldhouwer ontstond het werkwoord beeldhouwen.',
            },
          },
          {
            text: 'Leenwoorden moeten door de Nederlandse morfologie, en dan geldt ’t kofschip gewoon. *Downloaden*: de stam is *download*, eindigt op d, dus *gedownload* (geen extra d). *Updaten*: stam *update*, je hoort een t, dus *geüpdatet*. *Liken*: stam *like*, je hoort een k, dus *geliket*.',
            rule: 'Bij een Engels werkwoord kijk je naar de klank van de stam: stemloos (’t kofschip) → -t, anders -d.',
            quiz: {
              q: 'Wat is het voltooid deelwoord van skypen?',
              options: ['geskypet', 'geskyped', 'geskypt'],
              answer: 'geskypet',
              why: 'Stam skype, je hoort een p: ’t kofschip, dus -t. De Engelse spelling van de stam blijft staan.',
            },
            deep: {
              q: 'Waarom niet gewoon de Engelse vorm?',
              a: 'Omdat de Nederlandse buiging contextueel is: de zin eist een voltooid deelwoord met *ge-* en een *-d* of *-t*. Een leenwoord kan zijn eigen spelling houden (*like*), maar moet de Nederlandse buiging accepteren (*geliket*). Zo zie je het verschil tussen het lexicon (dat leent) en de grammatica (die beslist).',
            },
          },
        ],
      },
      {
        kind: 'choice',
        id: 'update',
        prompt: 'Kies de goede vorm.',
        before: 'Ik heb de app gisteren',
        after: '.',
        options: ['geüpdatet', 'geüpdated', 'geupdate'],
        answer: 'geüpdatet',
        why: 'Stam update, je hoort een t. ge + update + t, met een trema omdat e en u botsen.',
      },
      {
        kind: 'type',
        id: 'download',
        prompt: 'Typ het voltooid deelwoord van downloaden.',
        before: 'Heb je het bestand al',
        after: '?',
        hint: 'ge…',
        answer: 'gedownload',
        why: 'Stam download eindigt op d: ge + download. Geen extra d, net als gebrand of geland.',
      },
      {
        kind: 'sort',
        id: 'proces',
        prompt: 'Welk proces?',
        buckets: ['grammaticalisatie', 'affixoïde', 'terugvorming'],
        items: [
          { t: 'lijk → -lijk', b: 0 },
          { t: 'heid → -heid', b: 0 },
          { t: 'reuzeleuk', b: 1 },
          { t: 'keigoed', b: 1 },
          { t: 'stofzuiger → stofzuigen', b: 2 },
          { t: 'beeldhouwer → beeldhouwen', b: 2 },
          { t: 'dom → -dom', b: 0 },
          { t: 'megagoed', b: 1 },
        ],
        why: 'Woorden worden affixen, woorden gaan op affixen lijken, en afleidingen worden teruggerekend.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Nieuwe stukjes, oude stukjes',
        panels: [
          {
            text: 'Soms wordt een brokstuk van één woord een nieuw achtervoegsel. Na het Amerikaanse *Watergate*-schandaal heet elk schandaal *-gate*. Uit *alcoholic* kwam *-holic*: *workaholic*. Uit *entertainment* kwam *-tainment*: *infotainment*. De Amerikaanse taalkundige Arnold Zwicky noemde zulke stukjes *libfixen*: losgemaakte affixen. Het Nederlands neemt ze graag over.',
            lab: {
              label: 'Tik een libfix',
              chips: [
                { k: '-gate', out: 'uit Watergate', note: 'Watergate was een gebouwencomplex, geen schandaal. Toch draagt het stukje nu die betekenis.' },
                { k: '-holic', out: 'uit alcoholic', note: 'Het knippunt klopt niet met de echte morfemen: alcohol + ic.' },
                { k: '-tainment', out: 'uit entertainment', note: 'infotainment: informatie als vermaak.' },
              ],
            },
          },
          {
            text: 'Paul Hopper en Elizabeth Traugott (1993) beschreven de weg van grammaticalisatie als een helling: *inhoudswoord* → *functiewoord* → *klitisch* → *affix*. Die weg zou maar in één richting gaan. Muriel Norde (2009) verzamelde tegenvoorbeelden: *degrammaticalisatie*. Het Nederlands heeft er mooie: *tig* uit *twintig* en *dertig* (*ik heb het tig keer gezegd*), en *mijn ex*, waar het voorvoegsel *ex-* een zelfstandig naamwoord werd.',
            quiz: {
              q: 'Welk woord is een voorbeeld van degrammaticalisatie?',
              options: ['tig (ik heb het tig keer gezegd)', '-lijk (vriendelijk)', '-heid (vrijheid)'],
              answer: 'tig (ik heb het tig keer gezegd)',
              why: 'Een stukje van een woord (-tig) werd een zelfstandig woord. Dat is de omgekeerde richting van -lijk en -heid.',
            },
            rule: 'Grammaticalisatie: woord → affix. Degrammaticalisatie: affix → woord. De eerste richting is veel vaker.',
          },
          {
            text: 'Sprekers knippen woorden soms anders dan ze ooit gebouwd waren. Dat heet *heranalyse*. *Hamburger* betekent ‘uit Hamburg’, maar werd gelezen als *ham* + *burger*. Zo kwamen *kaasburger* en *visburger*. En *hangmat* komt van Spaans *hamaca*: Nederlanders maakten er iets van wat betekenis leek te hebben, een mat die hangt. Zo’n heranalyse heet ook *volksetymologie*.',
            quiz: {
              q: 'Hoe ontstond ‘kaasburger’?',
              options: ['Hamburger werd anders geknipt: ham + burger', 'Burger is een oud Nederlands woord voor brood', 'Kaas + burg + er: iemand uit een kaasstad'],
              answer: 'Hamburger werd anders geknipt: ham + burger',
              why: 'Eigenlijk Hamburg + er. Na de heranalyse werd burger een eigen bouwsteen.',
            },
          },
          {
            text: 'Morfologie verschilt ook per regio. In Brabant en Antwerpen hoor je het verkleinwoord op *-ke*: *manneke*, *boekske*. Het beroemde beeldje in Brussel heet niet voor niets *Manneken Pis*. De standaardtaal koos *-tje*, uit Holland. In Hollandse spreektaal hoor je ook *-ie*: *meissie*. Dezelfde betekenis, verschillende allomorfen per streek.',
            quiz: {
              q: 'Waar komt de vorm ‘manneke’ vandaan?',
              options: ['Uit het zuiden: Brabant en Antwerpen', 'Uit het Fries', 'Uit het Engels'],
              answer: 'Uit het zuiden: Brabant en Antwerpen',
              why: 'Het zuidelijke verkleinwoord op -ke, zoals in Manneken Pis.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'verandering',
        prompt: 'Welke verandering?',
        buckets: ['grammaticalisatie', 'degrammaticalisatie', 'heranalyse', 'libfix'],
        items: [
          { t: 'lijk → -lijk', b: 0 },
          { t: 'heid → -heid', b: 0 },
          { t: '-tig → tig', b: 1 },
          { t: 'ex- → mijn ex', b: 1 },
          { t: 'hamburger → kaasburger', b: 2 },
          { t: 'hamaca → hangmat', b: 2 },
          { t: 'Watergate → -gate', b: 3 },
          { t: 'alcoholic → workaholic', b: 3 },
        ],
        why: 'Woord wordt affix, affix wordt woord, een woord wordt anders geknipt, of een brokstuk wordt een nieuw affix.',
      },
      {
        kind: 'type',
        id: 'gereset',
        prompt: 'Typ het voltooid deelwoord van resetten.',
        before: 'Ik heb mijn wachtwoord al twee keer',
        after: '.',
        hint: 'ge…',
        answer: 'gereset',
        why: 'Stam reset eindigt op t: ge + reset, zonder extra t. Net als gezet.',
      },
      {
        kind: 'choice',
        id: 'gescoord',
        prompt: 'Kies de goede vorm.',
        before: 'In de laatste minuut heeft ze nog',
        after: '.',
        options: ['gescoord', 'gescoort', 'gescored'],
        answer: 'gescoord',
        why: 'Stam scoor eindigt op een r: niet in ’t kofschip, dus -d. Het werkwoord is helemaal ingeburgerd: scoren, scoorde, gescoord.',
      },
      {
        kind: 'proofread',
        id: 'leenwoorden',
        prompt: 'Lees het bericht na',
        intro: 'Er zitten drie fouten in Engelse werkwoorden. Tik ze aan.',
        tokens: [
          { t: 'Ik' },
          { t: 'heb' },
          { t: 'het' },
          { t: 'bestand' },
          { t: 'gedownloadt', fix: 'gedownload', why: 'Stam download eindigt op d: geen extra letter.' },
          { t: 'en' },
          { t: 'de' },
          { t: 'app' },
          { t: 'geüpdated.', fix: 'geüpdatet.', why: 'Stam update, je hoort een t: -t.' },
          { t: 'Daarna' },
          { t: 'heb' },
          { t: 'ik' },
          { t: 'jouw' },
          { t: 'foto' },
          { t: 'geliked.', fix: 'geliket.', why: 'Stam like, je hoort een k: ’t kofschip, dus -t.' },
        ],
        done: { title: 'Ingeburgerd', text: 'De spelling van de stam blijft Engels, de buiging is Nederlands: gedownload, geüpdatet, geliket.' },
      },
      {
        kind: 'swipe',
        id: 'beweging',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Volgens Hopper en Traugott gaat grammaticalisatie meestal van woord naar affix.', ok: true, why: 'Inhoudswoord, functiewoord, klitisch, affix.' },
          { t: 'Tig is een voorbeeld van grammaticalisatie.', ok: false, fix: 'tig is degrammaticalisatie', why: 'Een stukje van een woord werd een zelfstandig woord.' },
          { t: 'Hamburger betekende oorspronkelijk iets met ham.', ok: false, fix: 'Het betekende ‘uit Hamburg’', why: 'Pas door heranalyse werd burger een eigen stuk.' },
          { t: 'Arnold Zwicky noemde stukjes als -gate libfixen.', ok: true, why: 'Losgemaakte affixen.' },
          { t: 'Manneke is een zuidelijk verkleinwoord.', ok: true, why: 'Brabants en Antwerps -ke.' },
          { t: 'Gereset krijgt een extra t: geresett.', ok: false, fix: 'gereset, zonder extra t', why: 'De stam eindigt al op t.' },
        ],
      },
      {
        kind: 'highlight',
        id: 'eindbaas',
        prompt: 'Eindbaas: kleur de stukken van ‘onvriendelijkheden’',
        intro: 'Alles uit dit niveau in één woord: stam, afleiding, buiging en een allomorf.',
        pens: [
          { id: 'stam', label: 'stam', tag: 'kern', ask: 'Is dit de kern van het woord?', accent: 'blue' },
          { id: 'afl', label: 'afleiding', tag: 'nieuw woord', ask: 'Maakt dit stuk een nieuw woord?', accent: 'purple' },
          { id: 'buig', label: 'buiging', tag: 'vorm', ask: 'Maakt dit stuk alleen een andere vorm?', accent: 'orange' },
        ],
        words: [
          { t: 'on', role: 'afl' },
          { t: 'vriend', role: 'stam' },
          { t: 'elijk', role: 'afl' },
          { t: 'hed', role: 'afl' },
          { t: 'en', role: 'buig' },
        ],
        done: { title: 'Niveau uitgespeeld', text: 'on | vriend | elijk | hed | en: een stam, drie afleidingen (waarvan hed een allomorf van heid is, en -lijk ooit een woord was) en buiging buitenaan.' },
      },
    ],
  },
];
