import type { LessonInput } from '../schema';

/**
 * Bachelorlessen voor het niveau "De lettergreep": bewijs voor de lettergreep, de opbouw
 * (onset, kern, coda), grenzen en fonotaxis, de volle rijm en de appendix, hiaat en
 * glottisslag, schwa-epenthese, verkleinwoord en meervoud, en lettergreepschriften.
 * Ze bouwen voort op de lessen over sonoriteit en ambisyllabiciteit in "Klank en letter"
 * en beginnen meteen op bachelorniveau. De masterlessen staan in `greep-master.ts`.
 *
 * Sonoriteit in de berg: 1 plofklank, 2 wrijfklank, 3 neusklank, 4 l of r, 5 glijklank, 6 klinker.
 */
export const GREEP_LESSONS: LessonInput[] = [
  {
    id: 'g4',
    stage: 'bachelor',
    domain: 'fon',
    title: 'Bestaat de lettergreep eigenlijk?',
    skill: 'Spelling',
    icon: 'σ?',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Bewijs voor iets onzichtbaars',
        panels: [
          {
            text: 'Een raadsel om mee te beginnen: niemand heeft ooit een lettergreep *gezien*. In het geluid van *water* zit geen pauze tussen *wa* en *ter*. Toch klapt elk kind van vier het moeiteloos. In 1974 testten Liberman en collega’s dat: 46 procent van de vierjarigen kon woorden in lettergrepen tikken. Woorden in losse klanken tikken? *Niemand*.',
            split: { word: 'olifant', answer: 'o-li-fant', note: 'Drie klappen. Je hoeft niet te weten wat een klinker is om dit te kunnen.' },
            deep: {
              q: 'En bij oudere kinderen?',
              a: 'Bij de vijfjarigen tikte 48 procent lettergrepen en 17 procent klanken. Bij de zesjarigen, na een jaar leesles, was het 90 tegen 70 procent. Losse klanken leer je pas echt *horen* door het alfabet. De lettergreep was er al (Liberman, Shankweiler, Fischer en Carter 1974).',
            },
          },
          {
            text: 'Tweede bewijs: taalspelletjes. In een veelgespeelde versie van de *P-taal* zet je na elke klinker een *p* en dezelfde klinker nog eens: *hal-lo* wordt *ha-pa-llo-po*. Wie dat vloeiend speelt, rekent in lettergrepen, zonder ooit een regel te hebben geleerd.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'kaas', out: 'kaa-paas', note: 'Eén lettergreep, één keer p.' },
                { k: 'water', out: 'wa-pa-te-per', note: 'Twee lettergrepen, twee keer p.' },
                { k: 'olifant', out: 'o-po-li-pi-fa-pant', note: 'Drie lettergrepen, drie keer p. Het spel volgt de lettergrepen, niet de letters.' },
              ],
            },
          },
          {
            text: 'Nog twee bewijzen. Een Nederlandse haiku telt lettergrepen: vijf, zeven, vijf. En als je je verspreekt, ruilen klanken bijna altijd van gelijke plek: een begin met een begin, zoals *mork en ves* voor *vork en mes*. Je brein plant spraak dus in lettergrepen, ook al hoor je ze niet als losse stukken.',
            rule: 'De lettergreep zit niet in het geluid, maar in de planning van je brein.',
            quiz: {
              q: 'Wat bewijst de P-taal?',
              options: ['Sprekers delen woorden vanzelf in lettergrepen in', 'Elke letter is een klank', 'Kinderen leren eerst klanken, dan lettergrepen'],
              answer: 'Sprekers delen woorden vanzelf in lettergrepen in',
              why: 'Het spel plakt iets achter elke lettergreep. Dat lukt alleen als je de grenzen al voelt.',
            },
            deep: {
              q: 'Zijn versprekingen echt zo netjes?',
              a: 'Ja, dat is een van de stevigste patronen uit het onderzoek naar versprekingen. Een beginklank ruilt met een beginklank, een kern met een kern; een begin dat met een eind ruilt, is zeldzaam. Sieb Nooteboom verzamelde in 1969 al Nederlandse versprekingen, Stefanie Shattuck-Hufnagel (1979) deed het voor het Engels.',
            },
          },
        ],
      },
      {
        kind: 'type',
        id: 'p-taal',
        prompt: 'Zeg ‘lopen’ in de P-taal.',
        before: '',
        after: '',
        hint: 'lo-pen',
        answer: 'lopopepen',
        why: 'lo-pen wordt lo-po + pe-pen. Twee lettergrepen, twee keer p.',
      },
      {
        kind: 'sort',
        id: 'tellen',
        prompt: 'Hoeveel lettergrepen?',
        buckets: ['twee', 'drie', 'vier'],
        items: [
          { t: 'banaan', b: 0 },
          { t: 'vriendschap', b: 0 },
          { t: 'idee', b: 0 },
          { t: 'paraplu', b: 1 },
          { t: 'ziekenhuis', b: 1 },
          { t: 'ruïne', b: 1 },
          { t: 'poëzie', b: 1 },
          { t: 'televisie', b: 2 },
          { t: 'chocolade', b: 2 },
          { t: 'beëindigen', b: 2 },
        ],
        why: 'Tel de klinkerkernen, niet de klinkerletters: ie, ui en ei zijn één kern. ba-naan, vriend-schap, i-dee; pa-ra-plu, zie-ken-huis, ru-ï-ne, po-ë-zie; te-le-vi-sie, cho-co-la-de, be-ëin-di-gen. Het trema zegt: hier begint een nieuwe kern.',
      },
      {
        kind: 'swipe',
        id: 'bewijs',
        prompt: 'Klopt deze zin?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Tussen twee lettergrepen hoor je een korte pauze.', ok: false, fix: 'Er zit geen pauze tussen lettergrepen', why: 'Spraak is één doorlopende stroom. De grens zit in je hoofd.' },
          { t: 'Vierjarigen tikken makkelijker lettergrepen dan losse klanken.', ok: true, why: '46 procent tegen 0 procent in het onderzoek van Liberman en collega’s.' },
          { t: 'Een Nederlandse haiku telt woorden: vijf, zeven, vijf.', ok: false, fix: 'Een Nederlandse haiku telt lettergrepen', why: 'Vijf, zeven, vijf lettergrepen. (Het Japans telt nog iets anders: moras. Dat komt in de master.)' },
          { t: 'In een verspreking ruilt een beginklank meestal met een beginklank.', ok: true, why: 'Klanken houden hun plek in de lettergreep, ook als ze ontsporen.' },
        ],
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Een eeuw ruzie over de lettergreep',
        panels: [
          {
            text: 'Fonetici zochten de lettergreep eerst in het lichaam. De Amerikaan R.H. Stetson stelde in zijn *Motor Phonetics* voor dat elke lettergreep één *borstpuls* is: één duwtje van de ademspieren. Peter Ladefoged en collega’s maten eind jaren vijftig de spieren tussen de ribben. Ze vonden geen vaste puls per lettergreep. Een andere poging, de lettergreep als *sonoriteitstop* (Otto Jespersen, 1904), werkt veel beter. Die ken je uit de les over de berg in elke lettergreep in Klank en letter.',
            quiz: {
              q: 'Wat vonden de metingen van de ademspieren?',
              options: ['Geen vaste spierpuls per lettergreep', 'Precies één puls per lettergreep', 'Eén puls per woord'],
              answer: 'Geen vaste spierpuls per lettergreep',
              why: 'De borstpulstheorie hield geen stand. De lettergreep laat zich niet zo direct in het lichaam aanwijzen.',
            },
          },
          {
            text: 'Toen kwam de grote twijfel. In het invloedrijke boek *The Sound Pattern of English* (Chomsky en Halle, 1968) komt de lettergreep niet voor: alle regels werken met rijtjes klanken en woordgrenzen. Daniel Kahn bracht de lettergreep in 1976 terug met een eenvoudig argument uit het Engels. Een *p*, *t* of *k* krijgt een pufje lucht, *aspiratie*, als hij een beklemtoonde lettergreep begint: *pin* [pʰɪn]. Na een *s* in dezelfde lettergreep niet: *spin* [spɪn]. Zonder lettergreep moet je die regel met een lange lijst omwegen beschrijven.',
            lab: {
              label: 'Tik een Engels woord',
              chips: [
                { k: 'pin', out: '[pʰɪn]', note: 'De p begint de lettergreep: pufje lucht.' },
                { k: 'spin', out: '[spɪn]', note: 'De s staat ervoor in dezelfde onset: geen pufje.' },
                { k: 'appear', out: '[əˈpʰɪɹ]', note: 'Midden in het woord, maar aan het begin van de beklemtoonde lettergreep: weer een pufje.' },
              ],
            },
            deep: {
              q: 'Is de discussie daarmee voorbij?',
              a: 'Niet helemaal. Donca Steriade (1999) liet zien dat veel regels over medeklinkergroepen net zo goed werken met *woordranden*: wat midden in een woord mag, is vaak wat een woord mag beginnen of eindigen. Volgens haar is de lettergreep dus minder nodig dan Kahn dacht. Bijna alle fonologen gebruiken hem nog, maar de vraag wat hij precies verklaart, is een echte onderzoeksvraag.',
            },
          },
          {
            text: 'Ook het Nederlands levert bewijs. Veel sprekers in Nederland zeggen een *r* aan het eind van een lettergreep anders dan aan het begin. In *raar* rolt of schraapt de eerste r, de laatste klinkt zacht en Engels-achtig: de *Gooise r*. En de *l* in *lol* is aan het begin helder, aan het eind donkerder. Dezelfde klank, twee uitspraken, en de plek in de lettergreep beslist.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'raar', out: 'r … ɹ', note: 'Onset-r tegenover coda-r: bij veel sprekers in Nederland twee verschillende klanken.' },
                { k: 'rare', out: 'r … r', note: 'ra-re: de tweede r is nu de onset van re. Dan klinkt hij weer als een begin-r.' },
                { k: 'lol', out: 'l … ɫ', note: 'De l in de coda is donkerder: de tongrug gaat omhoog.' },
              ],
            },
            deep: {
              q: 'Wie heeft dat onderzocht?',
              a: 'Koen Sebregts schreef in 2014 een proefschrift over de enorme variatie in de Nederlandse r, in Nederland en Vlaanderen. De plek in de lettergreep bleek een van de sterkste factoren. In Vlaanderen is de zachte coda-r veel zeldzamer. Zo’n regel kun je alleen opschrijven als je weet waar lettergrepen beginnen en eindigen.',
            },
          },
          {
            text: 'Taalspelletjes bestaan overal, en ze knippen bijna altijd op lettergrepen. In Frankrijk spreken jongeren *verlan*: je draait de lettergrepen om. Het woord *verlan* is zelf *l’envers* (‘de omgekeerde’) achterstevoren. *Louche* wordt *chelou*, *femme* wordt *meuf*. Wie het spel speelt, moet woorden eerst in lettergrepen hakken.',
            lab: {
              label: 'Tik een Frans woord',
              chips: [
                { k: 'l’envers', out: 'verlan', note: 'len-vers wordt vers-len, uitgesproken als verlan.' },
                { k: 'louche', out: 'chelou', note: 'lou-che wordt che-lou.' },
                { k: 'femme', out: 'meuf', note: 'Een eenlettergrepig woord krijgt eerst een extra schwa (fem-me), dan omdraaien en inkorten.' },
              ],
            },
          },
        ],
      },
      {
        kind: 'type',
        id: 'verlan',
        prompt: 'Het Franse ‘pourri’ (rot, corrupt) in verlan?',
        before: 'pou-ri wordt',
        after: '',
        hint: 'draai de lettergrepen om',
        answer: 'ripou',
        why: 'pou-ri wordt ri-pou. In het meervoud werd het de titel van een Franse film over corrupte agenten: Les Ripoux (1984).',
      },
      {
        kind: 'sort',
        id: 'soort-bewijs',
        prompt: 'Wat voor bewijs voor de lettergreep is dit?',
        buckets: ['gedrag van sprekers', 'een klankregel', 'een meting in het lichaam'],
        items: [
          { t: 'de P-taal', b: 0 },
          { t: 'verlan', b: 0 },
          { t: 'versprekingen', b: 0 },
          { t: 'kinderen tikken lettergrepen', b: 0 },
          { t: 'aspiratie in pin', b: 1 },
          { t: 'de Gooise r in de coda', b: 1 },
          { t: 'de donkere l in lol', b: 1 },
          { t: 'spieractiviteit tussen de ribben', b: 2 },
        ],
        why: 'Spelletjes, versprekingen en tikken laten zien wat sprekers doen. Aspiratie, r en l zijn regels die de plek in de lettergreep nodig hebben. De spiermetingen zochten de lettergreep in het lichaam, zonder succes.',
      },
      {
        kind: 'choice',
        id: 'aspiratie',
        prompt: 'Waarom krijgt de p in het Engelse ‘spin’ geen pufje lucht?',
        before: '',
        after: '',
        options: ['De p begint de lettergreep niet: de s staat ervoor', 'De p staat aan het eind van het woord', 'In het Engels heeft een p nooit aspiratie'],
        answer: 'De p begint de lettergreep niet: de s staat ervoor',
        why: 'Aspiratie hoort bij de eerste klank van een beklemtoonde lettergreep. In spin is dat de s.',
      },
      {
        kind: 'order',
        id: 'geschiedenis',
        prompt: 'Zet de ideeën over de lettergreep in de tijd.',
        tiles: ['Kahn: lettergreep terug', 'Jespersen: sonoriteitstop', 'SPE: geen lettergreep', 'Steriade: woordranden'],
        answer: 'Jespersen: sonoriteitstop SPE: geen lettergreep Kahn: lettergreep terug Steriade: woordranden',
        why: 'Jespersen 1904, Chomsky en Halle 1968, Kahn 1976, Steriade 1999. De lettergreep ging weg en kwam terug, en wordt nog altijd bevraagd.',
      },
      {
        kind: 'swipe',
        id: 'debat',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'In The Sound Pattern of English speelt de lettergreep een hoofdrol.', ok: false, fix: 'De lettergreep komt er niet in voor', why: 'Chomsky en Halle werkten met rijtjes klanken en grenzen.' },
          { t: 'Kahn gebruikte de Engelse aspiratie als argument voor de lettergreep.', ok: true, why: 'pin tegenover spin: de regel kijkt naar het begin van de lettergreep.' },
          { t: 'Metingen bevestigden dat elke lettergreep één borstpuls is.', ok: false, fix: 'Ze vonden geen vaste puls per lettergreep', why: 'De theorie van Stetson hield geen stand.' },
          { t: 'Bij veel sprekers in Nederland klinkt de r in de coda anders dan in de onset.', ok: true, why: 'De Gooise r verschijnt aan het eind van een lettergreep.' },
          { t: 'In verlan draai je losse letters om.', ok: false, fix: 'Je draait lettergrepen om', why: 'lou-che wordt che-lou.' },
          { t: 'Steriade betoogde dat veel regels ook met woordranden werken.', ok: true, why: 'Wat midden in een woord mag, lijkt op wat een woord mag beginnen of eindigen.' },
        ],
      },
      {
        kind: 'bet',
        id: 'rare',
        prompt: 'Iemand met een Gooise r zegt ‘raar’ met een zachte r aan het eind. En in ‘rare’?',
        intro: 'Denk aan de plek van de tweede r.',
        options: ['Daar wordt de tweede r een gewone begin-r', 'Daar blijft de tweede r zacht', 'Daar valt de tweede r weg'],
        answer: 'Daar wordt de tweede r een gewone begin-r',
        why: 'ra-re: de r schuift naar de onset van re. Dezelfde klank wisselt van uitspraak omdat hij van plek in de lettergreep wisselt.',
      },
    ],
  },
  {
    id: 'g5',
    stage: 'bachelor',
    domain: 'fon',
    title: 'Onset, kern en coda',
    skill: 'Spelling',
    icon: 'O·K·C',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'De bouwtekening van een lettergreep',
        panels: [
          {
            text: 'Een lettergreep is geen rijtje kralen, maar een boompje. Bovenaan staat σ, *sigma*, het symbool voor lettergreep. Die splitst in een *onset* (het begin) en een *rijm*. De rijm splitst weer in de *kern* (de klinker) en de *coda* (wat erna komt). Alleen de kern is verplicht: *ei* is een complete lettergreep.',
            tree: {
              q: 'Hang de klanken van ‘plant’ in de boom',
              segs: [
                { t: 'p', role: 'onset' },
                { t: 'l', role: 'onset' },
                { t: 'a', role: 'kern' },
                { t: 'n', role: 'coda' },
                { t: 't', role: 'coda' },
              ],
              note: 'pl is de onset, a de kern, nt de coda. Kern en coda samen: de rijm ant.',
            },
          },
          {
            text: 'Waarom een aparte rijm? Omdat rijm in een gedicht precies dat stuk is: *maan* rijmt op *baan* omdat kern en coda gelijk zijn; de onset mag verschillen. *Alliteratie* doet het omgekeerde: gelijke onsets, zoals in *met man en macht*. Dichters knippen al eeuwen op de grens tussen onset en rijm.',
            lab: {
              label: 'Tik een stijlfiguur',
              chips: [
                { k: 'rijm', out: 'maan · baan · traan', note: 'Zelfde rijm (aan), andere onset.' },
                { k: 'alliteratie', out: 'met man en macht', note: 'Zelfde onset (m), andere rijm.' },
                { k: 'assonantie', out: 'kat · lag', note: 'Alleen de kern is gelijk. Een halfrijm.' },
              ],
            },
            quiz: {
              q: 'Welk woord rijmt op ‘trein’?',
              options: ['klein', 'trap', 'tram'],
              answer: 'klein',
              why: 'ein = ein. Rijm is kern plus coda; de onset (tr, kl) telt niet mee.',
            },
          },
          {
            text: 'Nog een bewijs: *mengwoorden*. *Brunch* is *breakfast* plus *lunch*: de onset van het ene woord, de rijm van het andere. *Smog* is *smoke* plus *fog*, *Brexit* is *Britain* plus *exit*. Mengwoorden worden bijna altijd op de grens onset-rijm gelast, niet midden in een rijm.',
            quiz: {
              q: 'Welk mengwoord is gelast op de grens van onset en rijm?',
              options: ['smog: sm uit smoke + og uit fog', 'smog: s uit smoke + mog uit fog', 'smog: smo uit smoke + g uit fog'],
              answer: 'smog: sm uit smoke + og uit fog',
              why: 'De onset sm van smoke en de rijm og van fog. De las valt precies op de grens.',
            },
            rule: 'Lettergreep = onset + rijm. Rijm = kern + coda. Alleen de kern is verplicht.',
            deep: {
              q: 'Is die boom de enige mogelijkheid?',
              a: 'Nee. Het *onset-rijmmodel* (onder anderen Selkirk 1982) ziet de rijm als eenheid. Het *moramodel* (Hyman 1985, Hayes 1989) telt alleen gewichtseenheden en hangt de onset direct aan de lettergreep. Experimenten van Rebecca Treiman lieten zien dat mensen woorden makkelijker op de grens onset-rijm knippen dan ergens anders. Het moramodel komt terug in de master.',
            },
          },
        ],
      },
      {
        kind: 'highlight',
        id: 'struik',
        prompt: 'Kleur de klanken van ‘struik’',
        intro: 'Kies een stift en tik de klanken aan.',
        pens: [
          { id: 'onset', label: 'onset', tag: 'begin', ask: 'Komt deze klank vóór de klinker?', accent: 'blue' },
          { id: 'kern', label: 'kern', tag: 'klinker', ask: 'Is dit het hart van de lettergreep?', accent: 'purple' },
          { id: 'coda', label: 'coda', tag: 'eind', ask: 'Komt deze klank na de klinker?', accent: 'orange' },
        ],
        words: [
          { t: 's', role: 'onset' },
          { t: 't', role: 'onset' },
          { t: 'r', role: 'onset' },
          { t: 'ui', role: 'kern' },
          { t: 'k', role: 'coda' },
        ],
        done: { title: 'Een volle onset', text: 'str is een onset van drie klanken, het maximum in het Nederlands. ui is de kern, k de coda.' },
      },
      {
        kind: 'sort',
        id: 'rijm-alliteratie',
        prompt: 'Rijm of alliteratie?',
        buckets: ['rijm', 'alliteratie'],
        items: [
          { t: 'kip · rip', b: 0 },
          { t: 'kip · kap', b: 1 },
          { t: 'blauw · flauw', b: 0 },
          { t: 'stoer · sterk', b: 1 },
          { t: 'zon · ton', b: 0 },
          { t: 'groen · grijs', b: 1 },
          { t: 'vlucht · lucht', b: 0 },
          { t: 'school · schaal', b: 1 },
          { t: 'droom · stroom', b: 0 },
          { t: 'sprong · sprak', b: 1 },
        ],
        why: 'Rijm: gelijke rijm (ip, auw, on, ucht, oom). Alliteratie: gelijke onset (k, st, gr, sch, spr). Let op vlucht · lucht: de onsets vl en l verschillen, de rijm ucht is gelijk.',
      },
      {
        kind: 'choice',
        id: 'rijm-van',
        prompt: 'Wat is de rijm van ‘vlecht’?',
        before: '',
        after: '',
        options: ['echt', 'vl', 'e', 'cht'],
        answer: 'echt',
        why: 'Rijm = kern + coda: e + cht. vl is de onset.',
      },
      {
        kind: 'swipe',
        id: 'boom',
        prompt: 'Klopt deze zin?',
        intro: 'Veeg naar rechts als de zin klopt.',
        cards: [
          { t: 'Elke lettergreep heeft een onset.', ok: false, fix: 'Niet elke lettergreep heeft een onset', why: 'ei, oog en uit beginnen met de kern. Alleen de kern is verplicht.' },
          { t: 'Maan en baan rijmen omdat hun rijm gelijk is.', ok: true, why: 'Kern aa, coda n: allebei aan.' },
          { t: 'De coda staat vóór de kern.', ok: false, fix: 'De coda staat na de kern', why: 'Onset, kern, coda: in die volgorde.' },
          { t: 'In brunch komt de onset uit breakfast.', ok: true, why: 'br uit breakfast, unch uit lunch.' },
        ],
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Hoe hecht is de rijm?',
        panels: [
          {
            text: 'Kinderen horen rijm lang voordat ze losse klanken horen. Lynette Bradley en Peter Bryant (1983) lieten vier- en vijfjarigen het vreemde woord uit een rijtje kiezen, zoals *kat, mat, rat, pen*. Kinderen die dat goed konden, lazen drie jaar later beter. Een groep die extra oefende met rijm en alliteratie, ging ook beter lezen. De grens tussen onset en rijm is dus een opstapje naar het alfabet.',
            quiz: {
              q: 'Welk woord hoort er niet bij: zon, ton, kom, bon?',
              options: ['kom', 'zon', 'ton', 'bon'],
              answer: 'kom',
              why: 'zon, ton en bon delen de rijm on. kom heeft de rijm om: dezelfde kern, een andere coda.',
            },
          },
          {
            text: 'Binnen de rijm zijn klanken kieskeurig over hun buren, tussen onset en kern bijna niet. Elke onset past voor elke klinker: *pa, pie, poe, puin*. Maar de *ng* [ŋ] staat alleen na een korte klinker: *ring*, *zang*, nooit *riing* of *zaang*. En de *h* staat alleen in de onset: geen Nederlands woord eindigt op een hoorbare h. Kern en coda vormen dus een team, de onset staat los.',
            lab: {
              label: 'Tik een klank',
              chips: [
                { k: 'ng', out: 'alleen in de rijm, na een korte klinker', note: 'ring, zang, tong: nooit aan het begin van een woord, nooit na aa of ie.' },
                { k: 'h', out: 'alleen in de onset', note: 'hoed, hand, be-houd: nooit aan het eind.' },
                { k: 'pl', out: 'alleen in de onset', note: 'plant, ple-zier: pl begint lettergrepen, maar eindigt ze nooit.' },
              ],
            },
          },
          {
            text: 'De kern is meestal een klinker, maar niet altijd. In het Tsjechisch is *vlk* ‘wolf’ en *prst* ‘vinger’. Daar is de *l* of *r* de kern. Ook het Engels kent zulke kernen: in *button* [bʌtn̩] vormt de n een eigen lettergreep. Het streepje onder de n in het IPA betekent: deze medeklinker is een kern.',
            tree: {
              q: 'Hang het Tsjechische ‘vlk’ (wolf) in de boom',
              segs: [
                { t: 'v', role: 'onset' },
                { t: 'l', role: 'kern' },
                { t: 'k', role: 'coda' },
              ],
              note: 'De l is de meest sonore klank, dus hij wordt de kern. Geen klinker nodig.',
            },
          },
          {
            text: 'Is de rijm universeel? Misschien niet. In het Koreaans vonden onderzoekers het omgekeerde. Koreaanse sprekers knippen een lettergreep liever *na* de klinker: *ka|n*, niet *k|an* (Yoon en Derwing 2001). Dat stuk onset plus kern heet de *body*. Ook het Koreaanse schrift zet onset en kern naast elkaar en de coda eronder. Hoe hecht onset, kern en coda samenhangen, verschilt dus misschien per taal.',
            quiz: {
              q: 'Waar knippen Koreaanse sprekers in experimenten het liefst?',
              options: ['tussen kern en coda: ka|n', 'tussen onset en kern: k|an', 'helemaal niet'],
              answer: 'tussen kern en coda: ka|n',
              why: 'Voor hen hangen onset en kern sterker samen: de body.',
            },
          },
        ],
      },
      {
        kind: 'highlight',
        id: 'schrift',
        prompt: 'Kleur de klanken van ‘schrift’',
        intro: 'Let op: sch is hier twee klanken, s en ch.',
        pens: [
          { id: 'onset', label: 'onset', tag: 'begin', ask: 'Komt deze klank vóór de klinker?', accent: 'blue' },
          { id: 'kern', label: 'kern', tag: 'klinker', ask: 'Is dit het hart van de lettergreep?', accent: 'purple' },
          { id: 'coda', label: 'coda', tag: 'eind', ask: 'Komt deze klank na de klinker?', accent: 'orange' },
        ],
        words: [
          { t: 's', role: 'onset' },
          { t: 'ch', role: 'onset' },
          { t: 'r', role: 'onset' },
          { t: 'i', role: 'kern' },
          { t: 'f', role: 'coda' },
          { t: 't', role: 'coda' },
        ],
        done: { title: 'Zes klanken, één kern', text: 's, ch en r vormen een onset van drie: [sxr]. i is de kern, f en t de coda.' },
      },
      {
        kind: 'sort',
        id: 'plek',
        prompt: 'Waar in de lettergreep kan dit staan?',
        buckets: ['alleen aan het begin', 'alleen aan het eind', 'allebei'],
        items: [
          { t: 'h', b: 0 },
          { t: 'kn', b: 0 },
          { t: 'pl', b: 0 },
          { t: 'ng', b: 1 },
          { t: 'nk', b: 1 },
          { t: 'rst', b: 1 },
          { t: 'k', b: 2 },
          { t: 's', b: 2 },
          { t: 'm', b: 2 },
        ],
        why: 'h, kn en pl: alleen onset (hoed, knie, plant). ng, nk en rst: alleen in de rijm (ring, bank, dorst). k, s en m kunnen allebei: kat en bak, sok en kas, mat en kam.',
      },
      {
        kind: 'choice',
        id: 'prst',
        prompt: 'Wat is de kern van het Tsjechische ‘prst’ (vinger)?',
        before: '',
        after: '',
        options: ['r', 'p', 's', 't'],
        answer: 'r',
        why: 'De r is de meest sonore klank. p-r-s-t: de r staat op de top van de berg.',
      },
      {
        kind: 'type',
        id: 'spork',
        prompt: 'Een Engels mengwoord: de onset van ‘spoon’ en de rijm van ‘fork’.',
        before: 'Een lepelvork heet in het Engels een',
        after: '.',
        hint: 'sp + ork',
        answer: 'spork',
        why: 'sp uit spoon, ork uit fork. Weer een las op de grens onset-rijm.',
      },
      {
        kind: 'swipe',
        id: 'rijm-bewijs',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Kinderen horen rijm meestal eerder dan losse klanken.', ok: true, why: 'Rijm en alliteratie komen vóór het fonembewustzijn.' },
          { t: 'Bradley en Bryant vonden dat rijmgevoel niets zegt over later lezen.', ok: false, fix: 'Rijmgevoel voorspelde later lezen', why: 'Goede rijmers lazen drie jaar later beter.' },
          { t: 'De ng kan in het Nederlands een woord beginnen.', ok: false, fix: 'De ng staat alleen in de rijm', why: 'ring en zang: altijd na een korte klinker.' },
          { t: 'In button is de n de kern van de tweede lettergreep.', ok: true, why: '[bʌtn̩]: de n is een lettergreepvormende medeklinker.' },
          { t: 'Elke kern is een klinker.', ok: false, fix: 'Ook een medeklinker kan een kern zijn', why: 'vlk en prst in het Tsjechisch hebben een l of r als kern.' },
          { t: 'Koreaanse sprekers knippen liever na de klinker dan ervoor.', ok: true, why: 'ka|n: de body hangt bij hen samen.' },
        ],
      },
      {
        kind: 'bet',
        id: 'riing',
        prompt: 'Een merk wil een nieuwe naam. Welke kan geen Nederlands woord worden?',
        options: ['plaang', 'plang', 'plaan', 'plank'],
        answer: 'plaang',
        why: 'ng staat alleen na een korte klinker. plaang heeft een lange aa: dat mag de rijm niet.',
      },
    ],
  },
  {
    id: 'g6',
    stage: 'bachelor',
    domain: 'fon',
    also: ['orth'],
    title: 'Waar valt de grens?',
    skill: 'Spelling',
    icon: 'ze|bra',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Drie wetten voor de grens',
        panels: [
          {
            text: 'Lettergrepen vechten om medeklinkers. Drie wetten beslissen wie wint. Wet één: geef zoveel mogelijk medeklinkers aan de *volgende* lettergreep, het *Maximale-Onsetprincipe*. In *zebra* gaan b én r naar de tweede lettergreep: *ze-bra*. Kijk naar de berg: elke lettergreep heeft één top.',
            sonority: {
              segs: [
                { t: 'z', s: 2 },
                { t: 'e', s: 6 },
                { t: 'b', s: 1 },
                { t: 'r', s: 4 },
                { t: 'a', s: 6 },
              ],
              cuts: [2],
              note: 'br klimt netjes omhoog naar de a: een prima onset.',
            },
          },
          {
            text: 'Wet twee: een onset moet een *toegestaan woordbegin* zijn. *br* mag (*brood*), *nd* niet: geen Nederlands woord begint met *nd*. Dus *pinda* wordt *pin-da*, niet *pi-nda*. En *tl* stijgt wel in sonoriteit, maar het Nederlands verbiedt het aan het begin: daarom *At-las*.',
            sonority: {
              segs: [
                { t: 'p', s: 1 },
                { t: 'i', s: 6 },
                { t: 'n', s: 3 },
                { t: 'd', s: 1 },
                { t: 'a', s: 6 },
              ],
              cuts: [3],
              note: 'De n daalt van de i af: hij hoort bij de eerste top. nd kan geen woord beginnen.',
            },
          },
          {
            text: 'Wet drie: een *korte* klinker moet in een *gesloten* lettergreep staan, met een coda. Kijk naar *ekster*. Wet één wil zoveel mogelijk naar rechts, maar *kst* is geen woordbegin. *st* wel (*stoel*), en de korte e krijgt de k als coda. Zie je de s? Hij is hoger dan de t ernaast: de bekende rebel aan de rand van een onset.',
            sonority: {
              segs: [
                { t: 'e', s: 6 },
                { t: 'k', s: 1 },
                { t: 's', s: 2 },
                { t: 't', s: 1 },
                { t: 'ə', s: 6 },
                { t: 'r', s: 4 },
              ],
              cuts: [2],
              note: 'ek-stər: de korte e houdt de k, st begint de tweede lettergreep.',
            },
            rule: 'Zoveel mogelijk naar rechts, maar alleen als het een woordbegin is, en een korte klinker houdt een coda.',
            deep: {
              q: 'Botsen de wetten weleens?',
              a: 'Ja, en dan wordt het interessant. In *bommen* wil de korte o de m als coda, maar de tweede lettergreep wil ook een onset. De oplossing, de *ambisyllabische* m, ken je uit Klank en letter. Optimaliteitstheorie maakt zulke botsingen expliciet: welke wet wint, hangt af van de rangorde. Daarover gaat de master.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'woordbegin',
        prompt: 'Mag een Nederlands woord hiermee beginnen?',
        buckets: ['mag', 'mag niet'],
        items: [
          { t: 'kn', b: 0 },
          { t: 'tl', b: 1 },
          { t: 'dw', b: 0 },
          { t: 'rk', b: 1 },
          { t: 'zw', b: 0 },
          { t: 'nd', b: 1 },
          { t: 'vl', b: 0 },
          { t: 'dl', b: 1 },
          { t: 'wr', b: 0 },
          { t: 'lp', b: 1 },
        ],
        why: 'knie, dwerg, zwaan, vlag, wrak: toegestaan. tl, dl, rk, nd en lp beginnen geen enkel Nederlands woord. rk, nd en lp dalen in sonoriteit; tl en dl stijgen wel, maar het Nederlands verbiedt ze toch.',
      },
      {
        kind: 'choice',
        id: 'monster',
        prompt: 'Hoe deel je ‘monster’ in lettergrepen?',
        before: '',
        after: '',
        options: ['mon-ster', 'mons-ter', 'mo-nster'],
        answer: 'mon-ster',
        why: 'st mag een woord beginnen (stoel), dus maximaal naar rechts: mon-ster. nst kan geen woordbegin zijn.',
      },
      {
        kind: 'choice',
        id: 'akte',
        prompt: 'En ‘akte’?',
        before: '',
        after: '',
        options: ['ak-te', 'a-kte'],
        answer: 'ak-te',
        why: 'kt is geen woordbegin, en de korte a heeft een coda nodig.',
      },
      {
        kind: 'bet',
        id: 'kadral',
        prompt: 'Een verzonnen woord: ‘kadral’. Waar valt de grens?',
        intro: 'Een woord dat je nooit hoorde, dus je moet rekenen met de wetten.',
        options: ['ka-dral', 'kad-ral', 'kadr-al'],
        answer: 'ka-dral',
        why: 'dr mag een woord beginnen (droom) en de a in een open lettergreep is lang. Dus ka-dral.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Als de wetten niet genoeg zijn',
        panels: [
          {
            text: 'De drie wetten werken binnen één stam. Zodra er woordbouw in het spel is, wint vaak de woordgrens. *Opeten* zou volgens wet één *o-pe-ten* worden, maar je zegt *op-e-ten*, met een knakje vóór de e. Zo ook *in-ademen*, *ont-eigenen* en *zee-egel*. Ook als je op papier afbreekt, splits je samenstellingen en voorvoegsels op hun grens. Waarom de woordgrens zo sterk is, zie je in de master bij het prosodische woord.',
            split: { q: 'Knip zoals je het zorgvuldig zegt', word: 'opeten', answer: 'op-e-ten', note: 'De p blijft bij op. De e begint een nieuwe lettergreep, met een glottisslag ervoor.' },
          },
          {
            text: 'Wet twee rekent met *toegestane woordbegins*, en die verschillen per taal. In het Spaans van Spanje zeg je *at-las*. In het Spaans van Mexico begint een woord wél met *tl*, dankzij leenwoorden uit het Nahuatl, de taal van de Azteken. Daar zegt men *a-tlas*. En het Grieks begint woorden met *pt*: *pteron* is ‘vleugel’, en een *helikopter* is een *helico-pter*, een ‘schroefvleugel’. Engelstaligen knippen het als *heli-copter*, omdat *pt* bij hen geen woord kan beginnen.',
            sonority: {
              q: 'Knip ‘atlas’ zoals een Nederlander',
              segs: [
                { t: 'ɑ', s: 6 },
                { t: 't', s: 1 },
                { t: 'l', s: 4 },
                { t: 'ɑ', s: 6 },
                { t: 's', s: 2 },
              ],
              cuts: [2],
              note: 'tl klimt wel, maar is in het Nederlands geen woordbegin. Dus at-las. In Mexico zou de knip vóór de t vallen.',
            },
          },
          {
            text: 'Wet drie zegt dat een korte klinker een coda wil. Maar er is één korte klinker die zich daar niets van aantrekt: de *schwa*. In *ge-be-den* staan twee schwa’s in open lettergrepen, en niemand schrijft *gebbedden*. De schwa is kort, maar telt in de fonologie niet mee als ‘ongespannen’ klinker. Daarom verdubbel je na een schwa nooit: *be-ter*, *ge-ven*.',
            quiz: {
              q: 'Hoe deel je ‘gebeden’ in lettergrepen?',
              options: ['ge-be-den', 'geb-ed-en', 'ge-bed-en'],
              answer: 'ge-be-den',
              why: 'De schwa mag een lettergreep open laten eindigen. De ee in be is lang, dus ook die lettergreep is open.',
            },
            deep: {
              q: 'Zijn sprekers het altijd eens over de grens?',
              a: 'Nee. In experimenten van onder anderen Schiller, Meyer en Levelt (1997) moesten Nederlanders woorden in lettergrepen opdelen. Na een lange klinker was dat eenduidig: *ka-mer*. Na een korte klinker met één medeklinker ertussen, zoals in *kammen*, kozen sprekers verschillend. Dat past bij de ambisyllabische medeklinker uit Klank en letter: hij hoort bij allebei, dus elke keuze is half goed.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'clusters',
        prompt: 'Waar valt de grens bij twee medeklinkers?',
        buckets: ['allebei naar rechts', 'één links, één rechts'],
        items: [
          { t: 'zebra', b: 0 },
          { t: 'april', b: 0 },
          { t: 'cobra', b: 0 },
          { t: 'Afrika', b: 0 },
          { t: 'pinda', b: 1 },
          { t: 'akte', b: 1 },
          { t: 'atlas', b: 1 },
          { t: 'harnas', b: 1 },
          { t: 'kalkoen', b: 1 },
        ],
        why: 'br, pr en fr mogen een woord beginnen: ze-bra, a-pril, co-bra, A-fri-ka. nd, kt, tl, rn en lk niet: pin-da, ak-te, at-las, har-nas, kal-koen.',
      },
      {
        kind: 'choice',
        id: 'opeten',
        prompt: 'Hoe deel je ‘opeten’ in zorgvuldige spraak?',
        before: '',
        after: '',
        options: ['op-e-ten', 'o-pe-ten', 'ope-ten'],
        answer: 'op-e-ten',
        why: 'op is een eigen woorddeel. De woordgrens wint van het Maximale-Onsetprincipe.',
      },
      {
        kind: 'proofread',
        id: 'afbreken',
        prompt: 'Een leerling knipte deze woorden in lettergrepen. Tik de fouten aan.',
        intro: 'Drie woorden zijn fout geknipt.',
        tokens: [
          { t: 'In' },
          { t: 'a-pril' },
          { t: 'zag' },
          { t: 'ik' },
          { t: 'een' },
          { t: 'eks-ter', fix: 'ek-ster', why: 'st mag een woord beginnen en de korte e houdt de k: ek-ster.' },
          { t: 'die' },
          { t: 'een' },
          { t: 'pi-nda', fix: 'pin-da', why: 'nd is geen woordbegin: pin-da.' },
          { t: 'wilde' },
          { t: 'o-pe-ten', fix: 'op-e-ten', why: 'De woordgrens van op wint: op-e-ten.' },
          { t: 'naast' },
          { t: 'de' },
          { t: 'at-las.' },
        ],
        done: { title: 'Drie gevonden', text: 'ek-ster, pin-da en op-e-ten. a-pril en at-las waren goed.' },
      },
      {
        kind: 'swipe',
        id: 'grens-wetten',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'In samenstellingen wint vaak de woordgrens van het Maximale-Onsetprincipe.', ok: true, why: 'op-e-ten, zee-egel, in-ademen.' },
          { t: 'In het Spaans van Mexico mag een woord met tl beginnen.', ok: true, why: 'Door leenwoorden uit het Nahuatl. Daarom a-tlas.' },
          { t: 'Na een schwa moet je de medeklinker verdubbelen.', ok: false, fix: 'Na een schwa verdubbel je nooit', why: 'ge-ven, be-ter: de schwa mag een open lettergreep hebben.' },
          { t: 'Toegestane woordbegins zijn in alle talen hetzelfde.', ok: false, fix: 'Ze verschillen per taal', why: 'pt mag in het Grieks, tl in Mexicaans Spaans, kn wel in het Nederlands maar niet meer in het Engels.' },
          { t: 'Na een korte klinker met één medeklinker kiezen sprekers in experimenten niet altijd dezelfde grens.', ok: true, why: 'De medeklinker in kammen is ambisyllabisch.' },
          { t: 'Pinda deel je als pi-nda, omdat de i lang is.', ok: false, fix: 'pin-da', why: 'nd kan geen woord beginnen, en de i is kort.' },
        ],
      },
      {
        kind: 'bet',
        id: 'helikopter',
        prompt: 'Uit welke Griekse delen komt ‘helikopter’ eigenlijk?',
        options: ['helico + pter', 'heli + copter', 'helic + opter'],
        answer: 'helico + pter',
        why: 'helix is ‘schroef’ en pteron ‘vleugel’. In het Grieks mag pt een woord beginnen. Engelstaligen knippen heli-copter, omdat pt bij hen geen woordbegin is.',
      },
    ],
  },
  {
    id: 'g7',
    stage: 'bachelor',
    domain: 'fon',
    title: 'Hoe vol mag een rijm?',
    skill: 'Spelling',
    icon: '3',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Het plafond van drie plekken',
        panels: [
          {
            text: 'Tijd om te rekenen. Geef een korte klinker *één plek*, een lange klinker of tweeklank *twee plekken*, en elke medeklinker *één plek*. Tel dan de rijm. *kaap*: aa + p = 3. *kamp*: a + m + p = 3. En *kaamp*? aa + m + p = 4. Kijk: *kaamp*, *boomp* en *pijlk* bestaan niet. Het Nederlands heeft een plafond: een rijm van hoogstens *drie plekken*.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'kaap', out: 'aa + p = 3', note: 'Past onder het plafond.' },
                { k: 'kamp', out: 'a + m + p = 3', note: 'Past ook.' },
                { k: 'kaamp', out: 'aa + m + p = 4', note: 'Te vol. Zo’n woord bestaat niet.' },
              ],
            },
          },
          {
            text: 'Maar wacht: *herfst*, *oogst*, *maand*. Die tellen meer dan drie! Kijk wat er overblijft: altijd *t*, *d* of *s*. Klanken die je met je tongpunt maakt, *coronalen*. Fonologen hangen ze buiten de rijm, in een *appendix*: een aanhangsel aan de rand van de lettergreep.',
            tree: {
              q: 'Hang ‘herfst’ in de boom',
              segs: [
                { t: 'h', role: 'onset' },
                { t: 'e', role: 'kern' },
                { t: 'r', role: 'coda' },
                { t: 'f', role: 'coda' },
                { t: 's', role: 'appendix' },
                { t: 't', role: 'appendix' },
              ],
              note: 'De rijm is e + r + f: drie plekken. De st hangt erbuiten, in de appendix.',
            },
          },
          {
            text: 'De appendix is precies de plek waar uitgangen landen. *Kookt*: oo + k = 3, en de *t* van de vervoeging hangt in de appendix. *Ergst*: e + r + ch = 3, en de *st* van de overtreffende trap past er nog bij. Zo werken klank en woordbouw samen: de uitgangen die het Nederlands achter woorden plakt, zijn juist de klanken die altijd nog passen.',
            quiz: {
              q: 'Waar hangt de t van ‘kookt’?',
              options: ['in de appendix', 'in de rijm', 'in de onset'],
              answer: 'in de appendix',
              why: 'oo + k vult de drie plekken van de rijm al. De t van de vervoeging hangt erbuiten.',
            },
            rule: 'Een rijm heeft hoogstens drie plekken. Wat erna komt is coronaal (t, d, s) en hangt in de appendix.',
            deep: {
              q: 'Wie bedacht dat plafond?',
              a: 'De rijm van drie plekken is uitgewerkt door Mieke Trommelen (*The Syllable in Dutch*, 1984) en Harry van der Hulst (1984). Er zijn randgevallen, zoals *doorn* en *hoorn*, waar een *n* volgt op lange klinker plus *r*. Maar ook dat is een klank van de tongpunt: de rand van de lettergreep blijft coronaal.',
            },
          },
        ],
      },
      {
        kind: 'swipe',
        id: 'kan-het',
        prompt: 'Kan dit een Nederlands woord zijn?',
        intro: 'Allemaal verzonnen. Tel de plekken van de rijm.',
        cards: [
          { t: 'kaamp kan een Nederlands woord zijn.', ok: false, fix: 'kaamp kan het niet zijn', why: 'aa + m + p = 4, en de p is geen coronaal.' },
          { t: 'flaant kan een Nederlands woord zijn.', ok: true, why: 'aa + n = 3. De t gaat in de appendix.' },
          { t: 'stoelk kan een Nederlands woord zijn.', ok: false, fix: 'stoelk kan het niet zijn', why: 'oe + l + k = 4, en k is niet coronaal.' },
          { t: 'gerfst kan een Nederlands woord zijn.', ok: true, why: 'Net als herfst: e + r + f, plus st in de appendix.' },
          { t: 'buulp kan een Nederlands woord zijn.', ok: false, fix: 'buulp kan het niet zijn', why: 'uu + l + p = 4.' },
        ],
      },
      {
        kind: 'sort',
        id: 'plekken',
        prompt: 'Hoeveel plekken heeft de rijm?',
        buckets: ['twee', 'drie'],
        items: [
          { t: 'kat', b: 0 },
          { t: 'zee', b: 0 },
          { t: 'kaas', b: 1 },
          { t: 'melk', b: 1 },
          { t: 'tuin', b: 1 },
          { t: 'bus', b: 0 },
          { t: 'pen', b: 0 },
          { t: 'ei', b: 0 },
          { t: 'kalf', b: 1 },
          { t: 'boom', b: 1 },
        ],
        why: 'kat: a + t. zee: ee. bus: u + s. pen: e + n. ei: een tweeklank, twee plekken. kaas: aa + s. melk: e + l + k. tuin: ui + n. kalf: a + l + f. boom: oo + m.',
      },
      {
        kind: 'choice',
        id: 'oogst',
        prompt: 'Wat hangt in de appendix van ‘oogst’?',
        before: '',
        after: '',
        options: ['st', 'gst', 'oo', 'g'],
        answer: 'st',
        why: 'oo + g (een ch-klank) = 3 plekken. De st blijft over, en die is coronaal.',
      },
      {
        kind: 'bet',
        id: 'kaamp',
        prompt: 'Waarom bestaat ‘kamp’ wel en ‘kaamp’ niet?',
        options: ['kaamp heeft een rijm van vier plekken', 'kaamp heeft geen onset', 'kaamp heeft de klemtoon verkeerd'],
        answer: 'kaamp heeft een rijm van vier plekken',
        why: 'aa telt dubbel. Met m en p erbij zit je boven het plafond, en p mag niet in de appendix.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Plafonds aan beide kanten',
        panels: [
          {
            text: 'Ook de onset heeft een plafond: hoogstens *drie* medeklinkers. En bij drie is de eerste altijd een *s*: *straat*, *sprong*, *splinter*, *schrijven* [sxr]. Zonder s blijft het bij twee: *pl*, *kr*, *tw*. De s is de rebel uit de les over sonoriteit in Klank en letter: hij staat aan de rand van de onset, zoals t, d en s aan de rand van de rijm. Twee randen, allebei met een tongpuntklank.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'straat', out: 's + tr', note: 'De s staat vóór een gewone onset van twee: tr.' },
                { k: 'splinter', out: 's + pl', note: 'Weer s plus twee. Een onset van drie zonder s bestaat niet.' },
                { k: 'schrijven', out: 's + chr', note: 'sch is hier [sx]: s plus de onset chr.' },
                { k: 'ptr…', out: 'onmogelijk', note: 'Drie medeklinkers zonder s vooraan: geen Nederlands woord.' },
              ],
            },
          },
          {
            text: 'Een raadsel uit Klank en letter: de *ie* in *piet* is fonetisch even kort als de *i* in *pit*. Toch telt *ie* in de rijm als twee plekken. *stoelk*, *kiemp* en *buulp* bestaan niet, terwijl *melk* en *kamp* wel bestaan. De telling is dus *fonologisch*: gespannen klinkers gedragen zich als lange, ook als je stopwatch iets anders zegt.',
            vowels: {
              q: 'Tik de drie klinkers die kort klinken maar twee plekken tellen',
              targets: ['i', 'y', 'u'],
              note: 'ie, uu en oe: fonetisch kort, behalve vóór r. In de rijm tellen ze als twee plekken, net als aa en oo.',
            },
            deep: {
              q: 'Is het verschil dan lengte of spanning?',
              a: 'Daarover verschillen fonologen. In de traditie van Trommelen en Van der Hulst tellen gespannen klinkers als twee plekken, ook als ze kort klinken. Marc van Oostendorp (1995) betoogde dat het echte verschil een kwestie van *kwaliteit* is: ongespannen klinkers moeten in een gesloten lettergreep staan. Beide analyses voorspellen dat *kiemp* niet kan; ze verschillen in de reden. De master komt hierop terug bij het gewicht van lettergrepen.',
            },
          },
          {
            text: 'Het Engels heeft bijna hetzelfde plafond. Na een lange klinker of tweeklank volgt hoogstens nog één medeklinker, plus tongpuntklanken: *find*, *point*, *mind*. Een woord als *faimp* zou raar zijn. En de Engelse appendix kan heel lang worden: in *sixths* [sɪksθs] volgen op *ik* nog s, θ en s, allemaal coronaal.',
            lab: {
              label: 'Tik een Engels woord',
              chips: [
                { k: 'find', out: 'ai + n | d', note: 'Tweeklank plus n is vol. De d hangt in de appendix.' },
                { k: 'sixths', out: 'i + k | s θ s', note: 'Drie tongpuntklanken achter elkaar in de appendix.' },
                { k: 'faimp', out: 'onmogelijk', note: 'De p na ai + m past niet: hij is geen tongpuntklank.' },
              ],
            },
          },
          {
            text: 'Waarom juist tongpuntklanken? *Coronalen* zijn in veel talen de meest gewone medeklinkers. Ze komen het vaakst voor, passen zich het makkelijkst aan hun buren aan, en duiken op waar andere medeklinkers niet mogen. Het boek *The Special Status of Coronals* (Paradis en Prunet, 1991) verzamelde daar het bewijs voor. Ook de Nederlandse uitgangen *-t*, *-d*, *-s* en *-st* zijn allemaal coronaal. Dat is geen toeval: ze passen altijd nog achter een stam.',
            quiz: {
              q: 'Welke uitgang past altijd nog achter een volle rijm?',
              options: ['-st, zoals in ergst', '-p', '-k'],
              answer: '-st, zoals in ergst',
              why: 'Coronalen mogen in de appendix. Daarom kan elke stam -t, -s of -st krijgen.',
            },
          },
        ],
      },
      {
        kind: 'type',
        id: 'ruimst',
        prompt: 'Hoeveel plekken heeft de rijm van ‘ruimst’ (zonder appendix)?',
        before: 'De rijm heeft',
        after: 'plekken.',
        hint: 'getal',
        answer: '3',
        why: 'ui telt twee plekken, m één: samen drie. De st hangt in de appendix.',
      },
      {
        kind: 'sort',
        id: 'plafond',
        prompt: 'Verzonnen woorden: kan dit Nederlands zijn?',
        buckets: ['kan', 'kan niet'],
        items: [
          { t: 'traant', b: 0 },
          { t: 'blonk', b: 0 },
          { t: 'spraaks', b: 0 },
          { t: 'splink', b: 0 },
          { t: 'straamst', b: 0 },
          { t: 'kuilp', b: 1 },
          { t: 'pielf', b: 1 },
          { t: 'stroemp', b: 1 },
          { t: 'faalm', b: 1 },
          { t: 'ptrak', b: 1 },
        ],
        why: 'traant (aa+n, t), blonk (o+n+k), spraaks (aa+k, s), splink (i+n+k), straamst (aa+m, st): ze passen. kuilp, pielf, stroemp en faalm hebben vier plekken met een niet-coronaal eind. ptrak heeft een onset van drie zonder s.',
      },
      {
        kind: 'choice',
        id: 'sixths',
        prompt: 'Wat hebben de klanken na de rijm in het Engelse ‘sixths’ gemeen?',
        before: '',
        after: '',
        options: ['Ze zijn allemaal coronaal', 'Ze zijn allemaal stemhebbend', 'Ze zijn allemaal plofklanken'],
        answer: 'Ze zijn allemaal coronaal',
        why: 's, θ en s maak je met je tongpunt. Net als in het Nederlands is de appendix coronaal.',
      },
      {
        kind: 'swipe',
        id: 'randen',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Een Nederlandse onset van drie medeklinkers begint altijd met een s.', ok: true, why: 'straat, sprong, splinter, schrijven.' },
          { t: 'De ie in piet telt in de rijm als één plek, omdat hij kort klinkt.', ok: false, fix: 'Hij telt als twee plekken', why: 'kiemp kan niet: ie gedraagt zich als een lange klinker.' },
          { t: 'Het Engels heeft geen appendix.', ok: false, fix: 'Het Engels heeft ook een coronale appendix', why: 'find, sixths: tongpuntklanken aan de rand.' },
          { t: 'De uitgangen -t, -s en -st zijn allemaal coronaal.', ok: true, why: 'Daarom passen ze altijd nog achter een stam.' },
          { t: 'stroemp kan een Nederlands woord zijn.', ok: false, fix: 'stroemp kan het niet zijn', why: 'oe + m + p is vier plekken, en p is niet coronaal.' },
          { t: 'Van Oostendorp zag het verschil tussen ie en i vooral als een verschil in kwaliteit.', ok: true, why: 'Gespannen tegenover ongespannen, niet lang tegenover kort.' },
        ],
      },
      {
        kind: 'bet',
        id: 'kiemp',
        prompt: 'piet en pit klinken even lang. Waarom bestaat ‘kimp’ dan wel als mogelijk woord en ‘kiemp’ niet?',
        options: ['ie telt fonologisch als twee plekken', 'ie is fonetisch langer dan i', 'mp mag nooit aan het eind'],
        answer: 'ie telt fonologisch als twee plekken',
        why: 'De stopwatch zegt kort, de fonologie zegt twee plekken. ie + m + p = 4, en de p mag niet in de appendix. mp mag wel: kamp.',
      },
    ],
  },
  {
    id: 'g8',
    stage: 'bachelor',
    domain: 'fon',
    also: ['orth'],
    title: 'De lettergreep wil een begin',
    skill: 'Spelling',
    icon: 'ʔ',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Hiaat, glijklank en glottisslag',
        panels: [
          {
            text: 'Lettergrepen hebben een voorkeur: ze beginnen graag met een medeklinker. Botsen twee klinkers, een *hiaat*, dan schuift je mond er stiekem iets tussen. Je zegt *zeeën* als [zeː.jən], met een j. En *boa* als [boː.wa], met een w.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'zeeën', out: '[zeː.jən]', note: 'Na een voorklinker als ee glijdt er een j tussen.' },
                { k: 'boa', out: '[boː.wa]', note: 'Na een achterklinker als oo komt er een w tussen.' },
                { k: 'chaos', out: '[xaː.ʔɔs]', note: 'Na een a past j noch w. Dan komt er een glottisslag: het knakje in je keel.' },
              ],
            },
          },
          {
            text: 'Die glottisslag [ʔ] hoor je ook in *beamen*: [bə.ʔaː.mən]. De spelling markeert precies deze plekken. Het *trema* (*zeeën*, *ruïne*) en het koppelteken (*na-apen*, *zee-egel*) staan waar een nieuwe lettergreep zonder onset begint.',
            rule: 'Een lettergreep zonder onset na een klinker krijgt een j, w of ʔ. Trema en koppelteken markeren die plek.',
            quiz: {
              q: 'Wat hoor je in het midden van ‘piano’?',
              options: ['een j: [pi.jaː.no]', 'een w: [pi.waː.no]', 'niets: [pi.aː.no]'],
              answer: 'een j: [pi.jaː.no]',
              why: 'Na de voorklinker i glijdt er een j tussen.',
            },
          },
          {
            text: 'Het gaat zelfs over woordgrenzen heen. Zeg snel *heb ik*: je zegt [hɛ.bɪk], met een *b*! Los klinkt *heb* als [hɛp], want aan het eind van een lettergreep wordt een b een p. Maar hier springt de b naar *ik*, dat geen onset had. Daar is hij geen eindklank meer, dus blijft hij stemhebbend.',
            split: { q: 'Knip zoals je het snel zegt', word: 'hebik', answer: 'he-bik', note: 'De b springt naar ik. Daarom hoor je b, geen p.' },
            deep: {
              q: 'Gebeurt dat bij elk woord?',
              a: 'Vooral bij kleine, onbeklemtoonde woordjes als *ik*, *er* en *het*: *heb er* klinkt als [hɛ.bər]. Booij (1995) noemt ze *clitica*: woordjes die tegen een buurwoord aan leunen. Voor een vol woord als *Anna* zeg je in zorgvuldige spraak eerder [hɛp.ʔɑ.naː], met een glottisslag. Daar blijft de grens dus staan.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'tussenklank',
        prompt: 'Welke klank schuift ertussen?',
        buckets: ['j', 'w', 'ʔ'],
        items: [
          { t: 'zeeën', b: 0 },
          { t: 'piano', b: 0 },
          { t: 'boa', b: 1 },
          { t: 'kanoën', b: 1 },
          { t: 'chaos', b: 2 },
          { t: 'beamen', b: 2 },
          { t: 'bioscoop', b: 0 },
          { t: 'Leo', b: 0 },
          { t: 'oase', b: 1 },
          { t: 'aorta', b: 2 },
        ],
        why: 'Na ee en i: j (zeeën, piano, bioscoop, Leo). Na oo: w (boa, kanoën, oase). Na a en na de schwa van be-: een glottisslag (chaos, aorta, beamen).',
      },
      {
        kind: 'choice',
        id: 'heb-ik',
        prompt: 'Waarom klinkt de b in ‘heb ik’ niet als p?',
        before: '',
        after: '',
        options: ['De b staat in de onset van de lettergreep bik', 'ik maakt elke klank ervoor stemhebbend', 'In vragen is alles stemhebbend'],
        answer: 'De b staat in de onset van de lettergreep bik',
        why: 'Eindklankverscherping geldt aan het eind van een lettergreep. In de onset blijft de b een b.',
      },
      {
        kind: 'fix',
        id: 'trema',
        prompt: 'Tik het fout gespelde woord en verbeter het.',
        sentence: 'We hebben twee nieuwe ideeen voor de zee-egel.',
        wrong: 4,
        answer: 'ideeën',
        why: 'idee-en: een nieuwe lettergreep zonder onset. Het trema markeert die grens.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Elke taal repareert anders',
        panels: [
          {
            text: 'Elke taal heeft last van hiaten, maar de reparatie verschilt. Het Nederlands *voegt in*: een j, w of ʔ. Veel sprekers van Brits Engels voegen een *r* in die er niet staat: *law and order* klinkt als *law-r-and order*. Het Frans *laat weg*: niet *le ami*, maar *l’ami*. En soms duikt een slapende medeklinker op: *les* klinkt als [le], maar *les amis* als [le.za.mi]. Die *liaison* geeft *amis* een onset.',
            lab: {
              label: 'Tik een reparatie',
              chips: [
                { k: 'Nederlands', out: 'zee-j-en', note: 'Invoegen van een glijklank.' },
                { k: 'Brits Engels', out: 'law-r-and order', note: 'Invoegen van een r die niet in de spelling staat: de intrusieve r.' },
                { k: 'Frans: elisie', out: 'l’ami', note: 'Weglaten: de klinker van le verdwijnt.' },
                { k: 'Frans: liaison', out: 'le-z-amis', note: 'De slapende s van les wordt wakker als onset.' },
              ],
            },
          },
          {
            text: 'Het Duits is strenger dan het Nederlands. Elke beklemtoonde lettergreep die met een klinker begint, krijgt in de standaarduitspraak een glottisslag, ook midden in een woord en ook aan het begin van een zin: *Verein* [fɛɐ̯ˈʔaɪ̯n], *beachten* [bəˈʔaxtn̩]. Het Nederlands doet dat vooral in zorgvuldige spraak en na een klinker. In snelle spraak verdwijnt hij vaak. Hetzelfde doel, ONSET, maar een andere strengheid. In de master zie je hoe Optimaliteitstheorie dat met rangordes beschrijft.',
            quiz: {
              q: 'Hoe klinkt het Duitse ‘Verein’ in de standaarduitspraak?',
              options: ['met een glottisslag: Ver-ʔein', 'met een j: Ver-jein', 'met de r als onset: Ve-rein'],
              answer: 'met een glottisslag: Ver-ʔein',
              why: 'ver- is een voorvoegsel. De beklemtoonde lettergreep ein krijgt zijn eigen ʔ als begin.',
            },
          },
          {
            text: 'Soms schrijft de spelling de glijklank gewoon op. Na *aa*, *oo* en *oe* met een *i* erachter hoor je een j-klank, en die schrijf je: *kraaien*, *mooie*, *groeien*. Na *au*, *ou* en *ie* staat soms een *w*: *blauwe*, *rouwen*, *nieuwe*. De glijklank zit dan al in de stam: *mooi* eindigt op een j-klank, die in *mooie* de onset van de tweede lettergreep wordt.',
            mark: {
              q: 'Tik de woorden waarin de spelling een glijklank opschrijft',
              sentence: 'De mooie blauwe ruïne had nieuwe kraaien',
              targets: [1, 2, 5, 6],
              note: 'mooie, kraaien (een j-klank) en blauwe, nieuwe (een w). In ruïne staat geen glijklank, maar een trema.',
            },
          },
          {
            text: 'Wanneer trema, wanneer koppelteken? Het trema staat binnen een woord als twee klinkerletters anders als één klank gelezen zouden worden: *ideeën*, *ruïne*, *geïnd*, *België*. In een samenstelling gebruik je een koppelteken: *zee-egel*, *auto-ongeluk*, *radio-omroep*. Leest niemand het verkeerd? Dan geen teken: *beamen*, *theater*, *politieagent*.',
            rule: 'Trema binnen een woord, koppelteken in een samenstelling, en niets als niemand het verkeerd kan lezen.',
            quiz: {
              q: 'Welk woord schrijf je zonder trema of koppelteken?',
              options: ['politieagent', 'auto-ongeluk', 'ideeën'],
              answer: 'politieagent',
              why: 'ie + a kun je niet als één klank lezen, dus er is geen teken nodig.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'teken',
        prompt: 'Trema, koppelteken of geen teken?',
        buckets: ['trema', 'koppelteken', 'geen teken'],
        items: [
          { t: 'ideeën', b: 0 },
          { t: 'ruïne', b: 0 },
          { t: 'geïnd', b: 0 },
          { t: 'knieën', b: 0 },
          { t: 'zee-egel', b: 1 },
          { t: 'auto-ongeluk', b: 1 },
          { t: 'radio-omroep', b: 1 },
          { t: 'beamen', b: 2 },
          { t: 'theater', b: 2 },
          { t: 'politieagent', b: 2 },
        ],
        why: 'Trema binnen een woord (eee, ui, ei, iee zouden verkeerd gelezen worden). Koppelteken in samenstellingen (ee-e, o-o). Geen teken als ea of iea niet als één klank te lezen is.',
      },
      {
        kind: 'rewrite',
        id: 'zeeegels',
        prompt: 'Zet de trema’s en koppeltekens goed.',
        source: 'De zeeen waren te koud voor de zeeegels.',
        accept: ['De zeeën waren te koud voor de zee-egels.'],
        why: 'zeeën: trema binnen een woord. zee-egels: koppelteken in een samenstelling.',
      },
      {
        kind: 'type',
        id: 'knieen',
        prompt: 'Typ het meervoud.',
        before: 'Eén knie, twee',
        after: '.',
        hint: 'knie + en',
        answer: 'knieën',
        why: 'knie-en: de e begint een nieuwe lettergreep zonder onset (je hoort een j). Zonder trema lees je iee als één klank.',
      },
      {
        kind: 'choice',
        id: 'frans',
        prompt: 'Hoe lost het Frans het hiaat in ‘le ami’ op?',
        before: '',
        after: '',
        options: ['Het laat de klinker van le weg: l’ami', 'Het voegt een j in: le-j-ami', 'Het voegt een glottisslag in: le-ʔami'],
        answer: 'Het laat de klinker van le weg: l’ami',
        why: 'Elisie: weglaten in plaats van invoegen. De a van ami krijgt de l als onset.',
      },
      {
        kind: 'swipe',
        id: 'hiaat-talen',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'In les amis wordt de s van les hoorbaar.', ok: true, why: 'Liaison: [le.za.mi]. De s wordt de onset van amis.' },
          { t: 'Het Duits gebruikt minder glottisslagen dan het Nederlands.', ok: false, fix: 'Het Duits gebruikt er meer', why: 'In het Duits krijgt elke beklemtoonde klinker aan het begin van een lettergreep een ʔ.' },
          { t: 'De intrusieve r in law and order staat niet in de spelling.', ok: true, why: 'Hij wordt ingevoegd om het hiaat te vullen.' },
          { t: 'In mooie schrijf je de glijklank op.', ok: true, why: 'De i na oo is de j-klank, en die wordt de onset van de tweede lettergreep.' },
          { t: 'Theater schrijf je met een trema.', ok: false, fix: 'theater, zonder trema', why: 'ea lees je niet als één klank, dus geen teken nodig.' },
          { t: 'In auto-ongeluk staat een koppelteken omdat het een samenstelling is.', ok: true, why: 'o-o zou je anders als oo lezen.' },
        ],
      },
      {
        kind: 'bet',
        id: 'beachten',
        prompt: 'Een Duitser zegt ‘beachten’ (opletten) zorgvuldig. Wat hoor je tussen be en achten?',
        options: ['een glottisslag', 'een j', 'niets: beach-ten'],
        answer: 'een glottisslag',
        why: 'be-ʔach-ten. Net als het Nederlandse beamen, maar in het Duits is de ʔ verplicht.',
      },
    ],
  },
  {
    id: 'g9',
    stage: 'bachelor',
    domain: 'fon',
    title: 'Melluk: de schwa als reddingsboei',
    skill: 'Spelling',
    icon: 'ə',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Schwa-epenthese',
        panels: [
          {
            text: 'Zeg eens heel gewoon *melk*. Grote kans dat je [mɛlək] zegt, met een stiekeme schwa. *Film* wordt [fɪləm], *arm* wordt [ɑrəm]. Niemand schrijft het, bijna iedereen zegt het weleens. Het heet *schwa-epenthese*: een klinker erbij.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'melk', out: '[mɛlək]', note: 'l + k: een schwa ertussen.' },
                { k: 'film', out: '[fɪləm]', note: 'l + m: een schwa ertussen.' },
                { k: 'hals', out: '[hɑls]', note: 'l + s: geen schwa. De s maak je met je tongpunt.' },
              ],
            },
          },
          {
            text: 'Wanneer gebeurt het? Na een *l* of *r*, vóór een medeklinker die je *niet* met je tongpunt maakt: *k, p, f, m, ch*. Dus *melk*, *hulp*, *wolf*, *erg*, *arm*. Bij *hals*, *hart* en *wals* niet: s en t zijn coronaal. Eén uitzondering valt op: ook *rn* doet mee, zoals in *hoorn* [hoːrən].',
            rule: 'Na l of r, vóór een niet-coronale medeklinker, kan een schwa verschijnen: melk, film, arm.',
            quiz: {
              q: 'In welk woord kan een extra schwa komen?',
              options: ['hulp', 'hals', 'hart'],
              answer: 'hulp',
              why: 'l + p: de p is niet coronaal. In hals en hart volgt een tongpuntklank.',
            },
          },
          {
            text: 'En de lettergreep? Vergelijk *melk* met *melken*. In *melken* staat de k in de onset van de volgende lettergreep. Dan is de extra schwa veel zeldzamer, en in de standaardtaal ongewoon. De regel voelt zich thuis in de *coda*: daar breekt hij een zware eindgroep open.',
            split: { word: 'melken', answer: 'mel-ken', note: 'l en k zitten in verschillende lettergrepen. Een schwa ertussen is hier zeldzaam.' },
            deep: {
              q: 'Is dat niet gewoon slordig?',
              a: 'Nee, het is variatie met een systeem. Onderzoek aan het Max Planck Instituut in Nijmegen liet zien dat de schwa sterk wisselt: per dialect, per spreker, zelfs per keer dat iemand hetzelfde woord zegt. Spreektempo en formaliteit verklaren het niet. Wat vastligt, is de *plek*: na l of r, vóór een niet-coronale medeklinker.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'schwa-of-niet',
        prompt: 'Kan hier een extra schwa komen?',
        buckets: ['ja', 'nee'],
        items: [
          { t: 'melk', b: 0 },
          { t: 'wolf', b: 0 },
          { t: 'arm', b: 0 },
          { t: 'kerk', b: 0 },
          { t: 'hals', b: 1 },
          { t: 'hart', b: 1 },
          { t: 'wals', b: 1 },
          { t: 'barst', b: 1 },
        ],
        why: 'melk, wolf, arm, kerk: l of r + k, f of m. hals, hart, wals, barst: l of r + s of t, en die zijn coronaal.',
      },
      {
        kind: 'choice',
        id: 'coronaal',
        prompt: 'Wat hebben s, t en d gemeen, zodat ze geen schwa uitlokken?',
        before: '',
        after: '',
        options: ['Je maakt ze met je tongpunt: ze zijn coronaal', 'Ze zijn stemloos', 'Het zijn klinkers'],
        answer: 'Je maakt ze met je tongpunt: ze zijn coronaal',
        why: 'De d is stemhebbend, dus het gaat niet om de stem. Het gaat om de plaats: de tongpunt.',
      },
      {
        kind: 'bet',
        id: 'holp',
        prompt: 'Verzonnen woord: ‘holp’. Hoe kan een Nederlander het uitspreken?',
        options: ['zowel [hɔlp] als [hɔləp]', 'alleen [hɔləp]', 'alleen [hɔlp]'],
        answer: 'zowel [hɔlp] als [hɔləp]',
        why: 'l + p in de coda: de schwa kan, maar hoeft niet. Epenthese is optioneel.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Waarom juist daar, en wat nog meer?',
        panels: [
          {
            text: 'Waarom blokkeren juist tongpuntklanken de schwa? Omdat *l* en *r* zelf ook met de tongpunt gemaakt worden. In *hals* en *hart* blijft je tongpunt op zijn plek en glijdt hij naar de volgende klank: één beweging. In *halm* en *melk* moet je mond helemaal van plek wisselen, naar de lippen of naar achteren. Daar valt een schwa als overgang tussen. Ook na een lange klinker gebeurt het: *twaalf* klinkt vaak als [tʋaːləf].',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'hals', out: 'l → s: zelfde plek', note: 'Tongpunt naar tongpunt: geen schwa nodig.' },
                { k: 'halm', out: 'l → m: andere plek', note: 'Van de tongpunt naar de lippen: ruimte voor een schwa, [hɑləm].' },
                { k: 'twaalf', out: '[tʋaːləf]', note: 'Ook na een lange klinker: l + f.' },
                { k: 'veld', out: '[vɛlt]', note: 'l + d: de d is coronaal, dus geen schwa.' },
              ],
            },
          },
          {
            text: 'Het Nederlands is niet de enige taal met zo’n tussenklinker. Het verschijnsel heeft zelfs een Sanskrietnaam: *svarabhakti*. In het Schots-Gaelisch klinkt *Alba* (Schotland) met twee a’s in de eerste helft: ongeveer [alapə]. Veel sprekers van Iers Engels zeggen *film* als [fɪləm]. Steeds dezelfde plek: tussen een l of r en een medeklinker erna.',
            quiz: {
              q: 'Hoe zeggen veel sprekers van Iers Engels het woord ‘film’?',
              options: ['[fɪləm]', '[fɪm]', '[əfɪlm]'],
              answer: '[fɪləm]',
              why: 'Precies dezelfde schwa als in het Nederlands, op dezelfde plek: tussen l en m.',
            },
          },
          {
            text: 'Het Nederlands voegt nog een klank in: een *d*. De vergrotende trap van *duur* is niet *duurer*, maar *duurder*. Zo ook *zwaarder*, *verder* en *raarder*. Na een r komt er vóór de uitgang *-er* een d. Je krijgt dan geen twee r’s rond een schwa. Taalkundigen noemen dit *d-epenthese*. Het staat gewoon in de spelling, anders dan de schwa in *melk*.',
            build: { before: 'Citroen is zuur, maar azijn is nog…', stem: 'zuur', endings: ['er', 'der', 'ter', 'eder'], answer: 'der', note: 'zuurder: na een r schuift er een d tussen.' },
          },
          {
            text: 'De schwa kan er ook *af*. In snelle spraak wordt *natuurlijk* vaak *tuurlijk*, en *mogelijk* klinkt als [moːx.lək]: twee lettergrepen in plaats van drie. Het Nederlands voegt dus schwa’s toe én haalt ze weg. Allebei maken ze de lettergreepbouw makkelijker voor je mond, alleen op verschillende plekken.',
            quiz: {
              q: 'Hoeveel lettergrepen hoor je vaak in ‘mogelijk’ in snelle spraak?',
              options: ['2', '3', '4'],
              answer: '2',
              why: 'mo-ge-lijk heeft er drie, maar de middelste schwa valt vaak weg: [moːx.lək].',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'schwa-lang',
        prompt: 'Kan hier een extra schwa komen?',
        buckets: ['ja', 'nee'],
        items: [
          { t: 'twaalf', b: 0 },
          { t: 'hoorn', b: 0 },
          { t: 'wolk', b: 0 },
          { t: 'halm', b: 0 },
          { t: 'dorp', b: 0 },
          { t: 'erg', b: 0 },
          { t: 'veld', b: 1 },
          { t: 'paars', b: 1 },
          { t: 'koord', b: 1 },
          { t: 'pols', b: 1 },
        ],
        why: 'twaalf, wolk, halm, dorp en erg: l of r plus een niet-coronale medeklinker. hoorn is de bekende uitzondering met n. veld, paars, koord en pols: l of r plus een tongpuntklank, dus geen schwa.',
      },
      {
        kind: 'type',
        id: 'raarder',
        prompt: 'Typ de vergrotende trap.',
        before: 'Dit verhaal is nog',
        after: 'dan het vorige.',
        hint: 'raar',
        answer: 'raarder',
        why: 'raar + er: na de r komt er een d tussen, raarder.',
      },
      {
        kind: 'dictation',
        id: 'melk-dictee',
        prompt: 'Luister en typ de zin.',
        intro: 'Je hoort misschien een extra schwa. Schrijf hem niet op.',
        sentence: 'In het dorp is de melk duurder dan in de stad.',
        right: 'Goed. De schwa in dorp en melk zeg je soms, maar schrijf je nooit. De d in duurder schrijf je wel.',
        wrong: 'Let op: dorp en melk schrijf je zonder extra e, en duurder krijgt een d tussen duur en -er.',
      },
      {
        kind: 'swipe',
        id: 'invoegen',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'In halm kan een schwa komen, in hals niet.', ok: true, why: 'l + m wisselt van plek, l + s niet.' },
          { t: 'Schwa-epenthese gebeurt alleen na een korte klinker.', ok: false, fix: 'Ook na een lange klinker, zoals in twaalf', why: '[tʋaːləf]: het gaat om l of r plus de volgende medeklinker.' },
          { t: 'Svarabhakti is de naam voor zo’n tussenklinker.', ok: true, why: 'Een term uit de Sanskrietgrammatica.' },
          { t: 'De vergrotende trap van duur is duurer.', ok: false, fix: 'duurder', why: 'Na een r komt er een d vóór -er.' },
          { t: 'In snelle spraak kan een schwa ook verdwijnen.', ok: true, why: 'mogelijk: [moːx.lək].' },
          { t: 'De schwa in melk schrijf je in nette spelling op.', ok: false, fix: 'Die schrijf je nooit op', why: 'De spelling is melk. De schwa zit alleen in de uitspraak.' },
        ],
      },
      {
        kind: 'fix',
        id: 'melluk',
        prompt: 'Iemand schreef op wat hij hoorde. Tik het fout gespelde woord en verbeter het.',
        sentence: 'Hij kocht een liter melluk bij de boer.',
        wrong: 4,
        answer: 'melk',
        why: 'De schwa tussen l en k zeg je soms, maar je schrijft hem nooit: melk.',
      },
      {
        kind: 'bet',
        id: 'verder',
        prompt: 'Wat is de vergrotende trap van ‘ver’?',
        options: ['verder', 'verrer', 'veerder'],
        answer: 'verder',
        why: 'Ook hier d-epenthese: ver + er wordt verder. Je zegt het zo vaak dat je de d niet meer opmerkt.',
      },
    ],
  },
  {
    id: 'g10',
    stage: 'bachelor',
    domain: 'morf',
    also: ['fon'],
    title: 'Balletje of baltje?',
    skill: 'Woorden',
    icon: '-etje',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Woordbouw die lettergrepen telt',
        panels: [
          {
            text: 'Waarom *balletje* maar *stoeltje*? Beide eindigen op een l. Het verschil zit in de lettergreep ervoor: *bal* heeft een korte klinker en de klemtoon, *stoel* een lange klank. Het verkleinwoord rekent dus met de *rijm* van de laatste lettergreep, niet met de laatste letter.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'bal', out: 'balletje', note: 'Korte klinker + l, met klemtoon: -etje.' },
                { k: 'stoel', out: 'stoeltje', note: 'Lange klank + l: -tje.' },
                { k: 'boom', out: 'boompje', note: 'Lange klank + m: -pje.' },
                { k: 'boek', out: 'boekje', note: 'Na een plof- of wrijfklank: -je.' },
              ],
            },
          },
          {
            text: 'Ook de klemtoon telt mee. *Ring* wordt *ringetje*, maar *koning* wordt *koninkje*. De *ning* van *koning* is onbeklemtoond. Zelfde rijm, andere plek in het ritme, andere uitgang.',
            build: { before: 'Een kleine koning is een…', stem: 'konin', endings: ['gje', 'gtje', 'getje', 'kje'], answer: 'kje', note: 'koninkje: een onbeklemtoonde -ing krijgt -kje.' },
            rule: '-etje: korte klinker + l, r, m, n of ng, met klemtoon. -pje: lange klank + m. -tje: klinker, of lange klank + l, r, n. -je: na plof- en wrijfklanken.',
            deep: {
              q: 'Waarom is dit belangrijk voor taalkundigen?',
              a: 'Het verkleinwoord is een klassiek bewijsstuk voor de lettergreep. Mieke Trommelen schreef er een heel proefschrift over: *The Syllable in Dutch, with special reference to diminutive formation* (1984). De kern: welke uitgang je kiest, hangt af van de rijm en de klemtoon van de laatste lettergreep. Dat kun je niet uit letters afleiden, alleen uit lettergreepstructuur.',
            },
          },
          {
            text: 'Ook het meervoud luistert naar ritme. Na een beklemtoonde laatste lettergreep: *-en* (*boe-ken*, *ka-non-nen*). Na een onbeklemtoonde lettergreep met schwa: *-s* (*ta-fels*, *be-zems*). Zo eindigt het meervoud bijna altijd op een sterke plus een zwakke lettergreep: *BOE-ken*, *TA-fels*. Met *-en* kreeg je *ta-fe-len*: twee zwakke lettergrepen achter elkaar.',
            quiz: {
              q: 'Wat is het meervoud van ‘lepel’?',
              options: ['lepels', 'lepelen'],
              answer: 'lepels',
              why: 'le-pel eindigt onbeklemtoond met een schwa, dus -s. Zo eindigt het op sterk-zwak: LE-pels.',
            },
            deep: {
              q: 'Is dat een harde regel?',
              a: 'Nee, een sterke neiging. *Leraar* wordt *leraren* en *vijand* wordt *vijanden*, ook al valt de klemtoon vooraan. Taalkundigen als Geert Booij beschrijven het daarom als een ritmische voorkeur: het meervoud eindigt het liefst op een *trochee*, sterk-zwak.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'verkleinwoord',
        prompt: 'Welk verkleinwoord?',
        buckets: ['-etje', '-pje', '-tje', '-je'],
        items: [
          { t: 'kam', b: 0 },
          { t: 'zon', b: 0 },
          { t: 'raam', b: 1 },
          { t: 'bezem', b: 1 },
          { t: 'deur', b: 2 },
          { t: 'trein', b: 2 },
          { t: 'kast', b: 3 },
          { t: 'hoed', b: 3 },
          { t: 'ballon', b: 0 },
          { t: 'film', b: 1 },
        ],
        why: 'kammetje, zonnetje, ballonnetje (beklemtoonde korte o + n); raampje, bezempje, filmpje (na een m komt -pje, behalve direct na een beklemtoonde korte klinker, zoals in kam); deurtje, treintje; kastje, hoedje.',
      },
      {
        kind: 'type',
        id: 'ster',
        prompt: 'Typ het verkleinwoord.',
        before: 'Een kleine ster is een',
        after: '.',
        hint: 'ster',
        answer: 'sterretje',
        why: 'ster: korte e + r, met klemtoon. Dus -etje, met een verdubbelde r: ster-re-tje.',
      },
      {
        kind: 'sort',
        id: 'meervoud',
        prompt: 'Meervoud op -en of op -s?',
        buckets: ['-en', '-s'],
        items: [
          { t: 'boek', b: 0 },
          { t: 'gordijn', b: 0 },
          { t: 'kanon (wapen)', b: 0 },
          { t: 'tafel', b: 1 },
          { t: 'bezem', b: 1 },
          { t: 'wortel', b: 1 },
          { t: 'kanaal', b: 0 },
          { t: 'appel', b: 1 },
          { t: 'auto', b: 1 },
        ],
        why: 'Beklemtoonde laatste lettergreep: -en (boeken, gordijnen, kanonnen, kanalen). Onbeklemtoond met schwa: -s (tafels, bezems, wortels, appels). Na een klinker ook -s, met apostrof: auto’s.',
      },
      {
        kind: 'bet',
        id: 'plom',
        prompt: 'Een ‘plom’ is een verzonnen diertje. Hoe noem je een kleine plom?',
        intro: 'Een woord dat niemand kent: dan zie je of de regel echt in je hoofd zit.',
        options: ['plommetje', 'plompje', 'plomtje'],
        answer: 'plommetje',
        why: 'Korte o + m in een beklemtoonde lettergreep: -etje, net als kammetje.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Eén achtervoegsel, vijf gezichten',
        panels: [
          {
            text: 'Fonologen zien de vijf vormen als *één* achtervoegsel, *-tje*, dat zich aanpast aan zijn buren. Na een m wordt de t een p: allebei met de lippen, *boompje*. Na een onbeklemtoonde *ng* wordt hij een k: allebei achter in de mond, *koninkje*. Na een plof- of wrijfklank valt de t weg: *boekje*. En na een beklemtoonde korte klinker plus l, r, m, n of ng komt er een lettergreep bij: *balletje*. Dat zijn assimilatie, weglating en invoeging, de processen uit Klank en letter.',
            paradigm: {
              q: 'Zet elk verkleinwoord in het goede vakje',
              cols: ['verkleinwoord'],
              rows: [
                { label: 'boom', cells: [{ fill: 'boompje', hint: 'Na een m worden t en m allebei lipklanken.' }] },
                { label: 'koning', cells: [{ fill: 'koninkje', hint: 'Onbeklemtoonde -ing: de t wordt een k.' }] },
                { label: 'boek', cells: [{ fill: 'boekje', hint: 'Na een plofklank valt de t weg.' }] },
                { label: 'bal', cells: [{ fill: 'balletje', hint: 'Beklemtoonde korte a + l: er komt een lettergreep bij.' }] },
                { label: 'stoel', cells: [{ fill: 'stoeltje', hint: 'Lange klank + l: gewoon -tje.' }] },
              ],
              extra: ['boomtje', 'koningetje', 'stoelletje'],
              note: 'Eén achtervoegsel, vijf vormen. Welke je krijgt, hangt af van de laatste lettergreep van de stam.',
            },
          },
          {
            text: 'In Vlaanderen hoor je vaak een heel ander verkleinwoord: *-ke*. Het beroemde beeldje in Brussel heet *Manneken Pis*, en een Vlaming zegt eerder *een boekske* dan *een boekje*. Die vorm is ouder. In het Middelnederlands was *-ken* het gewone verkleinachtervoegsel. In Holland veranderde de k later in een tj-klank, en daaruit groeide het standaard *-tje*.',
            lab: {
              label: 'Tik een vorm',
              chips: [
                { k: 'mannetje', out: 'standaard: -tje', note: 'De Hollandse vorm die standaardtaal werd.' },
                { k: 'manneke', out: 'Vlaams: -ke', note: 'Zoals in Manneken Pis. De oudere vorm met k.' },
                { k: 'boekske', out: 'Vlaams: -ske', note: 'Na een k komt in veel zuidelijke variëteiten -ske.' },
              ],
            },
          },
          {
            text: 'Hoe weet je dat zo’n regel echt in je hoofd zit, en niet alleen in je geheugen? Jean Berko liet in 1958 Amerikaanse kinderen een verzonnen diertje zien: *This is a wug. Now there are two…* De kinderen zeiden *wugs*. Ze hadden dat woord nooit gehoord, dus ze pasten een regel toe. Deze *wugtest* is sindsdien in tientallen talen gedaan. In de oefening met *plom* deed jij hetzelfde.',
            quiz: {
              q: 'Een verzonnen woord: een ‘toven’, met de klemtoon op to. Wat is het meervoud?',
              options: ['tovens', 'tovenen', 'tovenden'],
              answer: 'tovens',
              why: 'De laatste lettergreep is onbeklemtoond met een schwa: -s. Zo eindigt het op sterk-zwak: TO-vens.',
            },
          },
          {
            text: 'Het verkleinwoord leunt soms op het meervoud. *Schip* wordt niet *schipje*, maar *scheepje*: met de lange klinker van *schepen*. Zo ook *glas*, *glazen*, *glaasje*; *gat*, *gaten*, *gaatje*; *blad*, *bladen*, *blaadje*. En bij *kind* gebruik je in het meervoud de stam van *kinderen*: *kindertjes*. Het meervoud geeft de stam een open lettergreep, en het verkleinwoord neemt die klinker mee.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'schip', out: 'schepen → scheepje', note: 'De lange ee uit het meervoud komt terug.' },
                { k: 'glas', out: 'glazen → glaasje', note: 'Lange aa, en de z wordt weer s.' },
                { k: 'kat', out: 'katten → katje', note: 'Het meervoud heeft een korte a, dus het verkleinwoord ook.' },
                { k: 'kind', out: 'kinderen → kindertjes', note: 'Het meervoud van het verkleinwoord bouwt op de stam kinder-.' },
              ],
            },
          },
        ],
      },
      {
        kind: 'type',
        id: 'scheepje',
        prompt: 'Typ het verkleinwoord.',
        before: 'Een klein schip is een',
        after: '.',
        hint: 'denk aan schepen',
        answer: 'scheepje',
        why: 'De lange ee van schepen komt terug in scheepje.',
      },
      {
        kind: 'sort',
        id: 'lange-klinker',
        prompt: 'Wat doet de klinker in het verkleinwoord?',
        buckets: ['hij wordt lang', 'hij blijft kort'],
        items: [
          { t: 'gat', b: 0 },
          { t: 'glas', b: 0 },
          { t: 'schip', b: 0 },
          { t: 'blad', b: 0 },
          { t: 'kat', b: 1 },
          { t: 'bed', b: 1 },
          { t: 'hok', b: 1 },
          { t: 'pit', b: 1 },
        ],
        why: 'gaten, glazen, schepen, bladen: lange klinker, dus gaatje, glaasje, scheepje, blaadje. katten, bedden, hokken, pitten: korte klinker, dus katje, bedje, hokje, pitje.',
      },
      {
        kind: 'choice',
        id: 'bloemetje',
        prompt: 'Je koopt een bos bloemen voor iemand. Wat geef je?',
        before: 'Ik geef je een',
        after: '.',
        options: ['bloemetje', 'bloempje'],
        answer: 'bloemetje',
        why: 'Een bloempje is een kleine bloem. Een bloemetje is een bosje bloemen: hier hebben de twee vormen een eigen betekenis gekregen.',
      },
      {
        kind: 'swipe',
        id: 'verklein-diep',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'De p in boompje is een t die zich aanpast aan de m.', ok: true, why: 'Allebei lipklanken: assimilatie.' },
          { t: 'Het Vlaamse -ke is jonger dan het standaard -tje.', ok: false, fix: '-ke is de oudere vorm', why: 'Middelnederlands -ken; de tj-klank ontstond later in Holland.' },
          { t: 'In de wugtest gebruik je verzonnen woorden.', ok: true, why: 'Alleen zo zie je of een kind een regel toepast en niet een woord onthoudt.' },
          { t: 'Het verkleinwoord van glas is glasje.', ok: false, fix: 'glaasje', why: 'De lange aa van glazen komt terug.' },
          { t: 'Het meervoud van kindje is kindertjes.', ok: true, why: 'De stam kinder- uit het meervoud krijgt -tjes.' },
          { t: 'Koninkje en kammetje krijgen dezelfde uitgang.', ok: false, fix: 'Ze krijgen een andere uitgang', why: 'Onbeklemtoonde -ing: -kje. Beklemtoonde korte a + m: -etje.' },
        ],
      },
      {
        kind: 'dictation',
        id: 'koninkje',
        prompt: 'Luister en typ de zin.',
        sentence: 'Het koninkje gaf de kindertjes een scheepje en een bloemetje.',
        right: 'Goed: koninkje met nk, kindertjes met de stam kinder-, scheepje met ee en bloemetje als bosje bloemen.',
        wrong: 'Let op: koninkje met nk, kindertjes, scheepje met ee, en bloemetje met -etje.',
      },
      {
        kind: 'bet',
        id: 'glof',
        prompt: 'Een ‘glof’ is een verzonnen dier. Hoe noem je een kleine glof?',
        options: ['glofje', 'gloffetje', 'gloftje'],
        answer: 'glofje',
        why: 'De stam eindigt op een wrijfklank, f. Daar valt de t weg: -je, net als in hofje.',
      },
    ],
  },
  {
    id: 'g11',
    stage: 'bachelor',
    domain: 'orth',
    also: ['fon'],
    title: 'Schrijven in lettergrepen',
    skill: 'Spelling',
    icon: 'か',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Syllabaria en blokjesschrift',
        panels: [
          {
            text: 'Het alfabet is maar één manier om te schrijven. Veel schriften hebben een teken per *lettergreep*: een *syllabarium*. Het Japans gebruikt *kana*: か is *ka*, き is *ki*, す is *su*. Eén teken, een hele lettergreep.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'すし', out: 'su · shi', note: 'Twee tekens, twee lettergrepen.' },
                { k: 'さくら', out: 'sa · ku · ra', note: 'Drie tekens: kersenbloesem.' },
                { k: 'かき', out: 'ka · ki', note: 'Twee tekens: de kakivrucht.' },
              ],
            },
          },
          {
            text: 'In 1821 voltooide Sequoyah, die zelf nooit had leren lezen, een syllabarium voor het Cherokee: zo’n 85 tekens. Binnen een paar jaar konden duizenden Cherokee lezen. Voor het Nederlands zou dat nooit werken: het Japans heeft een paar honderd verschillende lettergrepen, het Nederlands *duizenden* (Levelt en Wheeldon 1994). Met *str*, *mpst* en *herfst* erbij heb je een woordenboek aan tekens nodig.',
            rule: 'Een syllabarium past bij een taal met weinig en eenvoudige lettergrepen. Het Nederlands heeft er te veel.',
            quiz: {
              q: 'Waarom schrijft het Nederlands met een alfabet en niet met een syllabarium?',
              options: ['Het heeft duizenden verschillende lettergrepen', 'Het heeft geen lettergrepen', 'Nederlandse lettergrepen hebben geen klinker'],
              answer: 'Het heeft duizenden verschillende lettergrepen',
              why: 'Met een alfabet bouw je elke lettergreep uit zo’n dertig letters.',
            },
          },
          {
            text: 'Het Koreaanse *hangeul* (1446) is een slimme tussenvorm. Het heeft letters, maar stapelt ze per lettergreep in een blokje: 한 = ㅎ (h) + ㅏ (a) + ㄴ (n). Onset linksboven, kern ernaast, coda eronder. Het schrift tekent dus de lettergreepboom!',
            lab: {
              label: 'Tik een blokje',
              chips: [
                { k: '한', out: 'ㅎ + ㅏ + ㄴ = han', note: 'Onset h, kern a, coda n.' },
                { k: '글', out: 'ㄱ + ㅡ + ㄹ = geul', note: 'Onset g, kern eu, coda l.' },
                { k: '아', out: 'ㅇ + ㅏ = a', note: 'Geen onset? Dan staat er een stille ㅇ als plaatshouder.' },
              ],
            },
            deep: {
              q: 'Zijn er nog meer?',
              a: 'Het oudste geschreven Grieks, *Lineair B* (rond 1400 voor Christus), was ook een syllabarium. Het Grieks had veel medeklinkergroepen, dus schrijvers lieten codaklanken vaak gewoon weg. Michael Ventris ontcijferde het schrift in 1952. Ook het Devanagari van het Hindi werkt per lettergreep: een medeklinker heeft er standaard een a achter zich.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'schriften',
        prompt: 'Wat voor schrift is dit?',
        buckets: ['alfabet', 'syllabarium', 'letters in lettergreepblokjes'],
        items: [
          { t: 'Nederlands', b: 0 },
          { t: 'Russisch (cyrillisch)', b: 0 },
          { t: 'Japanse kana', b: 1 },
          { t: 'Cherokee', b: 1 },
          { t: 'Lineair B', b: 1 },
          { t: 'Koreaans hangeul', b: 2 },
        ],
        why: 'Nederlands en Russisch: een teken per klank. Kana, Cherokee en Lineair B: een teken per lettergreep. Hangeul: letters, gestapeld per lettergreep.',
      },
      {
        kind: 'choice',
        id: 'hangeul',
        prompt: 'Welk deel van de lettergreep staat in hangeul onderaan het blokje?',
        before: '',
        after: '',
        options: ['de coda', 'de onset', 'de kern'],
        answer: 'de coda',
        why: 'Onset linksboven, kern ernaast of eronder, coda helemaal onderaan.',
      },
      {
        kind: 'bet',
        id: 'sakura',
        prompt: 'Hoeveel kana heb je nodig voor ‘sakura’?',
        options: ['3', '6', '2'],
        answer: '3',
        why: 'sa-ku-ra: drie lettergrepen, drie tekens: さくら.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Een stamboom van schriften',
        panels: [
          {
            text: 'Tussen alfabet en syllabarium liggen nog twee soorten schrift. Een *abjad* schrijft alleen medeklinkers; de lezer vult de klinkers zelf in. Zo werken het Arabisch en het Hebreeuws. Een *abugida* geeft elke medeklinker een standaardklinker, en een klein tekentje verandert die: in het Devanagari is क *ka*, कि *ki* en कु *ku*. De namen komen van de schrifthistoricus Peter Daniels. *Abugida* zijn de eerste tekens van het Ethiopische schrift: a, bu, gi, da.',
            lab: {
              label: 'Tik een schrift',
              chips: [
                { k: 'Hebreeuws', out: 'abjad', note: 'Alleen medeklinkers. Klinkers kunnen met puntjes, maar meestal niet.' },
                { k: 'Devanagari', out: 'abugida', note: 'क = ka. Een tekentje verandert de a: कि = ki.' },
                { k: 'Ge’ez', out: 'abugida', note: 'Het Ethiopische schrift: elke medeklinker heeft zeven vormen, één per klinker.' },
                { k: 'Grieks', out: 'alfabet', note: 'Medeklinkers én klinkers als eigen letters.' },
              ],
            },
          },
          {
            text: 'Ons alfabet begon als abjad. De Feniciërs schreven rond 1000 voor Christus alleen medeklinkers. De Grieken namen dat schrift over, maar sommige Fenicische medeklinkers bestonden in het Grieks niet. De eerste letter, *aleph*, stond voor een glottisslag. De Grieken gebruikten hem voor de klinker *a*: *alfa*. Zo ontstond het eerste schrift met vaste tekens voor medeklinkers én klinkers.',
            quiz: {
              q: 'Waar kwam de Griekse letter alfa vandaan?',
              options: ['van een Fenicische medeklinker voor de glottisslag', 'van een Egyptisch teken voor de zon', 'van de Latijnse a'],
              answer: 'van een Fenicische medeklinker voor de glottisslag',
              why: 'Aleph was een medeklinker. De Grieken hoorden die klank niet als eigen klank en maakten er een klinker van.',
            },
          },
          {
            text: 'Japanse kana zijn eigenlijk geen zuivere lettergreeptekens. Een coda past er niet in, dus het Japans gebruikt trucs: een klein *っ* voor de eerste helft van een dubbele medeklinker, en *ん* voor een slot-n. *Kippu* (kaartje) schrijf je als *きっぷ*: drie tekens voor twee lettergrepen. Kana tellen dus *moras*, een eenheid die je in de master leert kennen.',
            quiz: {
              q: 'Hoeveel kana heb je nodig voor ‘kippu’ (kaartje)?',
              options: ['3', '2', '5'],
              answer: '3',
              why: 'き + っ + ぷ: de kleine っ maakt de p dubbel. Twee lettergrepen, drie tekens.',
            },
          },
          {
            text: 'En het Chinees? Elk karakter staat voor één lettergreep én één betekenisdeel: 山 is *shān*, ‘berg’. Het Mandarijn heeft maar ongeveer 400 verschillende lettergrepen zonder toon, en ruim duizend met toon. Daardoor delen veel woorden dezelfde lettergreep, en het karakter maakt het verschil zichtbaar. Taalkundigen noemen dit een *morfosyllabisch* schrift.',
            quiz: {
              q: 'Waar staat één Chinees karakter meestal voor?',
              options: ['één lettergreep met een betekenis', 'één klank', 'één zin'],
              answer: 'één lettergreep met een betekenis',
              why: 'Een karakter is lettergreep en betekenisdeel tegelijk: morfosyllabisch.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'vier-soorten',
        prompt: 'Welk soort schrift?',
        buckets: ['abjad', 'abugida', 'alfabet', 'syllabarium'],
        items: [
          { t: 'Arabisch', b: 0 },
          { t: 'Hebreeuws', b: 0 },
          { t: 'Devanagari (Hindi)', b: 1 },
          { t: 'Ge’ez (Ethiopisch)', b: 1 },
          { t: 'Grieks', b: 2 },
          { t: 'Nederlands', b: 2 },
          { t: 'Japanse kana', b: 3 },
          { t: 'Cherokee', b: 3 },
        ],
        why: 'Abjad: alleen medeklinkers. Abugida: medeklinker met een standaardklinker die je kunt aanpassen. Alfabet: medeklinkers en klinkers. Syllabarium: één teken per lettergreep (of mora).',
      },
      {
        kind: 'order',
        id: 'schrifttijd',
        prompt: 'Zet de schriften in de volgorde waarin ze ontstonden.',
        tiles: ['hangeul', 'Grieks alfabet', 'Cherokee-syllabarium', 'Lineair B', 'Fenicisch abjad'],
        answer: 'Lineair B Fenicisch abjad Grieks alfabet hangeul Cherokee-syllabarium',
        why: 'Lineair B rond 1400 voor Christus, het Fenicisch rond 1000 voor Christus, het Griekse alfabet rond 800 voor Christus, hangeul in 1446 en het Cherokee-syllabarium in 1821.',
      },
      {
        kind: 'choice',
        id: 'devanagari',
        prompt: 'Het Devanagari is een abugida. Hoe lees je het losse teken क?',
        before: '',
        after: '',
        options: ['ka', 'k', 'a'],
        answer: 'ka',
        why: 'Een medeklinker draagt standaard een a. Voor ki of ku komt er een tekentje bij.',
      },
      {
        kind: 'type',
        id: 'kimono',
        prompt: 'Hoeveel kana heb je nodig voor ‘kimono’?',
        before: 'Kimono schrijf je met',
        after: 'kana.',
        hint: 'getal',
        answer: '3',
        why: 'ki-mo-no: drie open lettergrepen, drie tekens: きもの.',
      },
      {
        kind: 'swipe',
        id: 'schriften-waar',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Een abjad schrijft alleen medeklinkers.', ok: true, why: 'Zoals het Arabisch en Hebreeuws.' },
          { t: 'De Feniciërs schreven al vaste tekens voor klinkers.', ok: false, fix: 'Dat deden pas de Grieken', why: 'Het Fenicisch was een abjad.' },
          { t: 'Het woord abugida komt van de eerste tekens van het Ethiopische schrift.', ok: true, why: 'a, bu, gi, da.' },
          { t: 'Elk Japans kana-teken is precies één lettergreep.', ok: false, fix: 'Kana tellen moras', why: 'っ en ん zijn eigen tekens, maar geen eigen lettergreep.' },
          { t: 'Het Mandarijn heeft veel minder verschillende lettergrepen dan het Nederlands.', ok: true, why: 'Ongeveer 400 zonder toon, tegen duizenden in het Nederlands.' },
          { t: 'De Griekse alfa was in het Fenicisch al een klinker.', ok: false, fix: 'Het was een medeklinker', why: 'Aleph stond voor een glottisslag.' },
        ],
      },
      {
        kind: 'bet',
        id: 'karakter',
        prompt: 'Waarom zou een Chinees syllabarium zonder karakters lastig te lezen zijn?',
        options: ['Veel woorden delen dezelfde lettergreep', 'Het Chinees heeft duizenden lettergrepen', 'Chinese lettergrepen hebben geen klinker'],
        answer: 'Veel woorden delen dezelfde lettergreep',
        why: 'Met maar een paar honderd lettergrepen klinken veel woorden hetzelfde. Het karakter laat de betekenis zien.',
      },
    ],
  },
];
