import type { LessonInput } from '../schema';

/**
 * Masterlessen voor het niveau "De lettergreep": moras en het minimale woord, typologie en
 * verwerving, ONSET en NOCODA in Optimaliteitstheorie, het prosodische woord, ritmeklassen
 * en de lettergreep in spraakproductie. Ze bouwen voort op `greep.ts`.
 *
 * Eisnamen in OT-tableaus volgen de literatuur (Engels). Het sterretje van een verbod is het
 * teken ∗ (U+2217), omdat * in lesteksten een taalvoorbeeld markeert.
 */
export const GREEP_MASTER_LESSONS: LessonInput[] = [
  {
    id: 'g12',
    stage: 'master',
    domain: 'fon',
    title: 'Hoe zwaar is een lettergreep?',
    skill: 'Spelling',
    icon: 'μμ',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Moras en het minimale woord',
        panels: [
          {
            text: 'Welkom in de master, waar we lettergrepen gaan wegen. De eenheid heet *mora* (μ). Een korte klinker: één mora. Een lange klinker: twee. Een medeklinker in de coda telt in veel talen ook als mora. Een *lichte* lettergreep weegt één mora, een *zware* twee.',
            lab: {
              label: 'Tik een lettergreep',
              chips: [
                { k: 'zee', out: 'ee = μμ', note: 'Lange klinker: twee moras, zwaar.' },
                { k: 'pak', out: 'a + k = μμ', note: 'Korte klinker plus coda: ook zwaar.' },
                { k: 'de', out: 'ə = μ', note: 'Een schwa zonder coda: één mora, licht.' },
              ],
            },
            deep: {
              q: 'En de onset dan?',
              a: 'De onset telt in bijna geen enkele taal mee voor gewicht: *pa* en *spra* wegen hetzelfde. Dat is een sterk argument voor de rijm als eenheid, en voor het *moramodel* (Hyman 1985, Hayes 1989), dat de onset direct aan de lettergreep hangt en alleen de rijm in moras verdeelt.',
            },
          },
          {
            text: 'Het Japans telt geen lettergrepen, maar moras. Een Japanse haiku is vijf-zeven-vijf *moras*. *Tōkyō* heeft twee lettergrepen maar vier moras: to-o-kyo-o. *Nippon*: ni-p-po-n, ook vier. Een slot-n en de eerste helft van een dubbele medeklinker krijgen een eigen kana: にっぽん.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'sushi', out: 'su · shi = 2 moras', note: 'Twee lichte lettergrepen.' },
                { k: 'Tōkyō', out: 'to · o · kyo · o = 4 moras', note: 'Twee lettergrepen, maar allebei lang.' },
                { k: 'kitte', out: 'ki · t · te = 3 moras', note: 'Kitte is een postzegel. De dubbele t telt als eigen mora.' },
              ],
            },
            quiz: {
              q: 'Hoeveel moras heeft ‘Ōsaka’?',
              options: ['4', '3', '2'],
              answer: '4',
              why: 'o-o-sa-ka: de lange ō telt dubbel.',
            },
          },
          {
            text: 'Terug naar het Nederlands. Een inhoudswoord eindigt nooit op een korte klinker. *Ja* en *zo* hebben lange klinkers, en [bɑ] bestaat niet als woord. Fonologen zeggen: een woord weegt minstens twee moras, het *minimale woord*. Een korte klinker weegt maar één mora, dus hij heeft een coda nodig: *bak*, *bal*, *bad*. Dat is de diepere reden achter de dubbele medeklinker in *bom-men*.',
            rule: 'Een Nederlands inhoudswoord weegt minstens twee moras: een lange klinker, of een korte klinker met coda.',
            quiz: {
              q: 'Welk verzonnen woord kan geen Nederlands inhoudswoord zijn?',
              options: ['[bɪ]', '[biː]', '[bɪk]'],
              answer: '[bɪ]',
              why: '[ɪ] is kort: één mora. Een inhoudswoord heeft er minstens twee nodig.',
            },
            deep: {
              q: 'En de, je en te?',
              a: 'Dat zijn *functiewoorden*. Ze dragen nooit zelf de klemtoon en leunen op een buurwoord. De eis van twee moras geldt voor inhoudswoorden: zelfstandige naamwoorden, werkwoorden en bijvoeglijke naamwoorden. Een paar tussenwerpsels zoals *hè* glippen erdoorheen; tussenwerpsels zijn in veel talen de vrijbuiters van de fonologie.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'gewicht',
        prompt: 'Licht of zwaar?',
        buckets: ['licht (μ)', 'zwaar (μμ)'],
        items: [
          { t: 'de', b: 0 },
          { t: 'je', b: 0 },
          { t: 'te', b: 0 },
          { t: 'zee', b: 1 },
          { t: 'kat', b: 1 },
          { t: 'ui', b: 1 },
          { t: 'ge', b: 0 },
          { t: 'strik', b: 1 },
          { t: 'pit', b: 1 },
        ],
        why: 'de, je, te en ge: een schwa zonder coda. zee en ui: lange klank. kat en pit: korte klinker plus coda. strik: de grote onset str telt niet, alleen de rijm ik: μμ, net als kat.',
      },
      {
        kind: 'type',
        id: 'nippon',
        prompt: 'Hoeveel moras heeft ‘Nippon’?',
        before: 'Nippon heeft',
        after: 'moras.',
        hint: 'getal',
        answer: '4',
        why: 'ni-p-po-n: de eerste p en de slot-n tellen als eigen mora.',
      },
      {
        kind: 'swipe',
        id: 'moras',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'De onset telt mee voor het gewicht van een lettergreep.', ok: false, fix: 'De onset telt (bijna) nooit mee', why: 'pa en spra wegen hetzelfde. Alleen de rijm telt.' },
          { t: 'Tōkyō heeft twee lettergrepen en vier moras.', ok: true, why: 'to-o-kyo-o.' },
          { t: 'Een Nederlands inhoudswoord kan eindigen op een korte klinker, zoals [bɑ].', ok: false, fix: 'Het eindigt op een lange klinker of een medeklinker', why: 'Een korte klinker weegt één mora; het minimale woord weegt er twee.' },
        ],
      },
      {
        kind: 'bet',
        id: 'bommen',
        prompt: 'Welke eis zit achter de dubbele m van ‘bommen’?',
        options: ['Een korte klinker weegt één mora en heeft een coda nodig', 'De o in bommen is lang', 'De m is twee klanken'],
        answer: 'Een korte klinker weegt één mora en heeft een coda nodig',
        why: 'Daarom moet de m ook bij de eerste lettergreep horen. De spelling tekent dat met mm.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Moras die niet verdwijnen',
        panels: [
          {
            text: 'Het sterkste bewijs voor moras komt uit klankgeschiedenis. Verdwijnt een coda, dan wordt de klinker ervoor vaak *lang*: de mora blijft staan en de klinker neemt hem over. Latijn *kasnus* werd *cānus* (grijs), Grieks *esmi* werd *ēmi* (ik ben). Dat heet *compenserende verlenging*. Bruce Hayes (1989) wees op het omgekeerde: verdwijnt een *onset*, dan wordt er niets verlengd. Grieks *wanax* (heer) werd gewoon *anax*. De onset had geen mora om achter te laten.',
            lab: {
              label: 'Tik een verandering',
              chips: [
                { k: 'kasnus → cānus', out: 'coda weg, klinker lang', note: 'De s had een mora. De a erft hem: ā.' },
                { k: 'esmi → ēmi', out: 'coda weg, klinker lang', note: 'Zelfde patroon in het Oudgrieks.' },
                { k: 'wanax → anax', out: 'onset weg, niets lang', note: 'De w had geen mora. Er valt niets te compenseren.' },
              ],
            },
          },
          {
            text: 'De Romeinse dichters telden geen lettergrepen, maar gewicht. Een lettergreep is *lang* als de klinker lang is, of als er een coda volgt: *positione longa*, ‘lang door de plek’. De hexameter van Vergilius begint zo: *ar-ma vi-rum-que ca-no*. *Ar* is lang door de r, *ma* en *vi* zijn kort: lang-kort-kort, een *dactylus*. Dezelfde rekensom als bij moras, tweeduizend jaar eerder.',
            quiz: {
              q: 'Waarom telt ‘ar’ in ‘arma’ als lang, al is de a kort?',
              options: ['Er volgt een coda: de r', 'De a heeft klemtoon', 'Het is de eerste lettergreep van het vers'],
              answer: 'Er volgt een coda: de r',
              why: 'Positione longa: een korte klinker plus coda weegt zwaar, net als in het moramodel.',
            },
          },
          {
            text: 'Het minimale woord zie je ook bij afkortingen. Junko Itô (1990) liet zien dat Japanse afkortingen nooit korter zijn dan twee moras. *Demonsutoreeshon* wordt *demo*, *terebijon* (televisie) wordt *terebi*, maar nooit *de* of *te*. Het Nederlands doet iets vergelijkbaars: *informatie* wordt *info*, *abonnement* wordt *abo*. Elke afkorting begint met een zware lettergreep of heeft er twee.',
            quiz: {
              q: 'Waarom kort het Japans ‘demonsutoreeshon’ af tot ‘demo’ en niet tot ‘de’?',
              options: ['Een woord moet minstens twee moras wegen', 'Japans heeft geen woorden van één lettergreep', 'De klemtoon valt op mo'],
              answer: 'Een woord moet minstens twee moras wegen',
              why: 'de is één mora. demo is twee: het minimale woord.',
            },
          },
        ],
      },
      {
        kind: 'type',
        id: 'hokkaido',
        prompt: 'Hoeveel moras heeft ‘Hokkaidō’ (ほっかいどう)?',
        before: 'Hokkaidō heeft',
        after: 'moras.',
        hint: 'getal',
        answer: '6',
        why: 'ho-k-ka-i-do-o: de dubbele k geeft een extra mora, en de lange ō telt dubbel. Zes kana, zes moras.',
      },
      {
        kind: 'choice',
        id: 'esmi',
        prompt: 'Waarom werd Grieks ‘esmi’ ‘ēmi’, met een lange e?',
        before: '',
        after: '',
        options: ['De s verdween, en de e nam zijn mora over', 'De e kreeg klemtoon', 'De m werd een klinker'],
        answer: 'De s verdween, en de e nam zijn mora over',
        why: 'Compenserende verlenging: het gewicht van de lettergreep blijft gelijk.',
      },
      {
        kind: 'sort',
        id: 'latijn',
        prompt: 'Latijnse lettergrepen: kort of lang in de dichtkunst?',
        buckets: ['kort', 'lang'],
        items: [
          { t: 'ma in arma', b: 0 },
          { t: 'vi in virum', b: 0 },
          { t: 'ca in cano', b: 0 },
          { t: 'ar in arma', b: 1 },
          { t: 'rum in virum', b: 1 },
          { t: 'nō in canō', b: 1 },
          { t: 'est', b: 1 },
          { t: 'Troi in Troiae', b: 1 },
        ],
        why: 'Kort: korte klinker zonder coda (ma, vi, ca). Lang: een coda (ar, rum, est), een lange klinker (nō) of een tweeklank (Troi).',
      },
      {
        kind: 'swipe',
        id: 'moras-diep',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Als een coda verdwijnt, wordt de klinker ervoor vaak langer.', ok: true, why: 'Compenserende verlenging: kasnus werd cānus.' },
          { t: 'Als een onset verdwijnt, wordt de klinker erna ook langer.', ok: false, fix: 'Dan wordt er niets verlengd', why: 'wanax werd anax: de onset had geen mora.' },
          { t: 'In de Latijnse dichtkunst telt een korte klinker met coda als lang.', ok: true, why: 'Positione longa.' },
          { t: 'Japanse afkortingen kunnen één mora lang zijn.', ok: false, fix: 'Ze zijn minstens twee moras lang', why: 'terebi, demo: nooit te of de.' },
          { t: 'Info en abo voldoen aan het minimale woord.', ok: true, why: 'Ze beginnen met een zware lettergreep: in, a met lange aa.' },
          { t: 'Hayes gebruikte compenserende verlenging als argument tegen moras.', ok: false, fix: 'Hij gebruikte het als argument vóór moras', why: 'Alleen een mora verklaart waarom coda en onset zich anders gedragen.' },
        ],
      },
      {
        kind: 'bet',
        id: 'terebi',
        prompt: 'Welke afkorting van ‘terebijon’ (televisie) kan het Japans niet maken?',
        options: ['te', 'tere', 'terebi'],
        answer: 'te',
        why: 'te weegt één mora, onder het minimale woord. tere en terebi wegen twee en drie.',
      },
    ],
  },
  {
    id: 'g13',
    stage: 'master',
    domain: 'fon',
    title: 'Lettergrepen van de wereld',
    skill: 'Spelling',
    icon: 'CV',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Typologie en verwerving',
        panels: [
          {
            text: 'Er is één lettergreep die in *elke* bekende taal voorkomt: *CV*, een medeklinker plus een klinker. Daarboven lopen talen uiteen. Het Hawaïaans kent geen codas en geen medeklinkergroepen. Daarom werd *Merry Christmas* daar *Mele Kalikimaka*.',
            lab: {
              label: 'Tik een taal',
              chips: [
                { k: 'Hawaïaans', out: 'Mele Kalikimaka', note: 'Geen codas, geen clusters, en geen r of s: elke klank wordt in CV geperst.' },
                { k: 'Japans', out: 'kurisumasu', note: 'Codas en clusters worden opgelost met extra klinkers: ku-ri-su-ma-su.' },
                { k: 'Spaans', out: 'escuela', note: 'Een woord mag niet met s + medeklinker beginnen: Latijn scola werd escuela.' },
              ],
            },
          },
          {
            text: 'Aan het andere uiterste staat het Georgisch: *gvprtskvni*, ‘je pelt ons’, begint met acht medeklinkers op rij. En het Tashlhiyt-Berbers in Marokko heeft hele woorden zonder klinker: *tftktstt*, ‘je hebt het verstuikt’. Daar wordt een *f* of *t* de kern van een lettergreep.',
            quiz: {
              q: 'Welk sjabloon komt in elke bekende taal voor?',
              options: ['CV', 'CVC', 'V', 'CCVCC'],
              answer: 'CV',
              why: 'Roman Jakobson zag het al: elke taal heeft CV. Talen verschillen in wat ze daarbovenop toelaten.',
            },
            deep: {
              q: 'Hoe weet je dat tftktstt lettergrepen heeft?',
              a: 'Dell en Elmedlaoui (1985) lieten zien dat de grenzen de sonoriteit volgen: de meest sonore klank in de buurt wordt de kern, ook als het een medeklinker is. Ridouane (2008) bevestigde met akoestisch en fysiologisch onderzoek dat er geen verborgen klinkers in zulke woorden zitten.',
            },
          },
          {
            text: 'Kinderen lopen die wereldkaart na. Nederlandse kinderen beginnen met CV, dan CVC, dan V en VC. Daarna splitst de route: de ene groep leert eerst complexe codas (CVCC), de andere eerst complexe onsets (CCV). CCVCC, zoals *sterk*, komt bij iedereen als laatste (Levelt, Schiller en Levelt 2000).',
            swap: {
              goal: 'Zet in de volgorde waarin Nederlandse kinderen ze leren',
              blocks: ['VC', 'CV', 'V', 'CVC'],
              accept: ['CV CVC V VC'],
              note: 'CV eerst, dan CVC, V en VC. Daarna nemen kinderen verschillende routes naar CCVCC.',
            },
            rule: 'Elke taal heeft CV. Complexere lettergrepen veronderstellen de eenvoudigere, in talen én bij kinderen.',
          },
        ],
      },
      {
        kind: 'choice',
        id: 'strike',
        prompt: 'Het honkbalwoord ‘strike’ is geleend door het Japans. Hoe klinkt het daar?',
        before: '',
        after: '',
        options: ['sutoraiku', 'sraik', 'tsraiku'],
        answer: 'sutoraiku',
        why: 'Elke medeklinker krijgt een eigen klinker: su-to-ra-i-ku. Geen clusters, geen coda.',
      },
      {
        kind: 'sort',
        id: 'hawaiaans',
        prompt: 'Zou het Hawaïaans dit woord toestaan?',
        buckets: ['ja', 'nee'],
        items: [
          { t: 'mama', b: 0 },
          { t: 'aloha', b: 0 },
          { t: 'kala', b: 0 },
          { t: 'pak', b: 1 },
          { t: 'strand', b: 1 },
          { t: 'herfst', b: 1 },
          { t: 'hula', b: 0 },
          { t: 'kai', b: 0 },
          { t: 'kalk', b: 1 },
        ],
        why: 'Het Hawaïaans staat CV en V toe (a-lo-ha, ka-i), maar geen coda (pak, kalk) en geen clusters (strand, herfst).',
      },
      {
        kind: 'bet',
        id: 'implicatie',
        prompt: 'Een taal heeft lettergrepen als CCVC. Wat heeft die taal dan zeker ook?',
        options: ['CV-lettergrepen', 'geen CV-lettergrepen', 'alleen V-lettergrepen'],
        answer: 'CV-lettergrepen',
        why: 'Complexere sjablonen veronderstellen de eenvoudigere. Een taal met CCVC heeft, voor zover bekend, altijd CV.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Reparaties, rebellen en kinderen',
        panels: [
          {
            text: 'Leent een taal een woord met een verboden cluster, dan kiest ze een reparatie. Het Spaans zet een klinker *vóór* s + medeklinker: *escuela*, *estrés*, *esnob*. Het Turks doet dat ook: Frans *station* werd *istasyon*. Het Japans zet klinkers *tussen* de medeklinkers: *sutoraiku*. Welke plek een taal kiest, is een vaste eigenschap van die taal. Fonologen zoeken nog naar de beste verklaring waarom de ene taal vóór en de andere tussen kiest.',
            lab: {
              label: 'Tik een leenwoord',
              chips: [
                { k: 'Spaans estrés', out: 'e + stres', note: 'Een klinker vooraan: de s wordt de coda van de eerste lettergreep.' },
                { k: 'Turks istasyon', out: 'i + stasyon', note: 'Ook vooraan: is-tas-yon.' },
                { k: 'Japans sutoraiku', out: 's-u-t-o-raiku', note: 'Klinkers ertussen: elke medeklinker krijgt zijn eigen lettergreep.' },
              ],
            },
          },
          {
            text: 'Het sonoriteitsprincipe is een sterke neiging, geen ijzeren wet. Het Russisch heeft *rtut’* (kwik): de r staat vóór de t, de berg gaat eerst omlaag. Het Pools heeft *mgła* (mist), waar de m vóór de g staat. Sommige fonologen hangen zulke beginklanken buiten de lettergreep, net als de Nederlandse s in *straat*. Anderen zeggen: talen mogen het principe overtreden, maar het blijft gemarkeerd en zeldzaam.',
            quiz: {
              q: 'Waarom is het Russische ‘rtut’’ bijzonder?',
              options: ['De sonoriteit daalt eerst: r is sonoorder dan t', 'Het heeft geen klinker', 'Het is een leenwoord uit het Japans'],
              answer: 'De sonoriteit daalt eerst: r is sonoorder dan t',
              why: 'In een gewone onset stijgt de sonoriteit naar de kern. Hier gaat hij eerst omlaag.',
            },
          },
          {
            text: 'Kinderen tonen het principe juist heel strikt. Gitanjali, de dochter van fonoloog Amalia Gnanadesikan (2004), maakte van elk cluster één klank. *Blue* werd [bu], *sleep* [sip] en *snow* [so]. Ze hield steeds de klank met de *laagste* sonoriteit: b boven l, s boven l, s boven n. Zo wordt de stijging naar de klinker zo groot mogelijk, de beste onset volgens de sonoriteitsberg.',
            quiz: {
              q: 'Wat zei Gitanjali waarschijnlijk voor ‘please’?',
              options: ['[piz]', '[liz]', '[pliz]'],
              answer: '[piz]',
              why: 'p is minder sonoor dan l. Ze houdt de p: de grootste sprong naar de klinker.',
            },
          },
          {
            text: 'Hoe zijn lettergrepen over de wereld verdeeld? De *World Atlas of Language Structures* (WALS) deelt talen in drie groepen. *Eenvoudig*: hoogstens CV. *Gemiddeld complex*: bijvoorbeeld CVC of een onset van een medeklinker plus r, l of w. *Complex*: grotere clusters, zoals het Nederlands en het Georgisch. De middelste groep is de grootste. Ian Maddieson vond bovendien dat talen met complexe lettergrepen gemiddeld meer verschillende medeklinkers hebben.',
            quiz: {
              q: 'In welke WALS-groep valt het Nederlands?',
              options: ['complex', 'gemiddeld complex', 'eenvoudig'],
              answer: 'complex',
              why: 'Onsets als str en codas als rfst gaan ver voorbij CVC.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'reparatie',
        prompt: 'Waar komt de nieuwe klinker?',
        buckets: ['vóór het cluster', 'tussen de medeklinkers'],
        items: [
          { t: 'escuela (Spaans)', b: 0 },
          { t: 'estrés (Spaans)', b: 0 },
          { t: 'esnob (Spaans)', b: 0 },
          { t: 'istasyon (Turks)', b: 0 },
          { t: 'kurisumasu (Japans)', b: 1 },
          { t: 'sutoraiku (Japans)', b: 1 },
          { t: 'Kalikimaka (Hawaïaans)', b: 1 },
        ],
        why: 'Spaans en Turks zetten een klinker vóór s + medeklinker. Japans en Hawaïaans breken het cluster open met een klinker ertussen.',
      },
      {
        kind: 'choice',
        id: 'snow',
        prompt: 'Een peuter die clusters vereenvoudigt zoals Gitanjali: wat wordt ‘snow’?',
        before: '',
        after: '',
        options: ['[so]', '[no]', '[sno]'],
        answer: '[so]',
        why: 's is minder sonoor dan n. De klank met de laagste sonoriteit blijft.',
      },
      {
        kind: 'chat',
        id: 'yuki',
        prompt: 'Help Yuki met Japanse leenwoorden.',
        contact: { name: 'Yuki', role: 'een Japanse studiegenoot', initials: 'Y' },
        rounds: [
          {
            say: 'Wij zeggen gorufu voor golf. Weet jij waarom?',
            options: ['Het Japans verbiedt codas en clusters, dus er komen klinkers bij', 'Het Japans heeft geen l', 'Het woord kwam via het Spaans'],
            right: 0,
            fix: 'Elke medeklinker krijgt een eigen klinker: go-ru-fu.',
            why: 'De l werd r, en de clusters lf en de slot-f kregen een u.',
          },
          {
            say: 'En hoe denk je dat wij bed zeggen?',
            options: ['beddo', 'betto', 'bedu'],
            right: 0,
            fix: 'beddo: na een d komt een o, en de d wordt dubbel.',
            why: 'Na t en d gebruikt het Japans meestal o, omdat tu en du anders klinken. De dubbele d houdt de korte e.',
          },
          {
            say: 'Laatste: ice cream heet bij ons aisu kuriimu. Hoeveel klinkers zijn erbij gekomen?',
            options: ['drie', 'één', 'geen'],
            right: 0,
            fix: 'ai-su ku-rii-mu: een u na de s, een u tussen k en r, en een u na de m.',
            why: 'Elke coda en elk cluster krijgt een klinker.',
          },
        ],
        bye: 'Arigatō! Nu snap ik mijn eigen leenwoorden beter.',
      },
      {
        kind: 'swipe',
        id: 'typologie-diep',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Het Turks maakte van station istasyon.', ok: true, why: 'Een klinker vóór s + t, net als in het Spaans.' },
          { t: 'Het sonoriteitsprincipe wordt in geen enkele taal overtreden.', ok: false, fix: 'Sommige talen overtreden het', why: 'Russisch rtut’, Pools mgła.' },
          { t: 'Gitanjali hield bij een cluster de meest sonore klank.', ok: false, fix: 'Ze hield de minst sonore klank', why: 'blue werd [bu], snow werd [so].' },
          { t: 'In de WALS is gemiddeld complex de grootste groep.', ok: true, why: 'De meeste talen staan meer toe dan CV, maar geen grote clusters.' },
          { t: 'Talen met complexe lettergrepen hebben gemiddeld meer medeklinkers.', ok: true, why: 'Dat verband vond Ian Maddieson.' },
          { t: 'Het Japans zet een klinker vóór s + medeklinker, net als het Spaans.', ok: false, fix: 'Het Japans zet klinkers tussen de medeklinkers', why: 'sutoraiku, niet esutoraiku.' },
        ],
      },
      {
        kind: 'order',
        id: 'verwerving',
        prompt: 'In welke volgorde leren Nederlandse kinderen deze lettergrepen?',
        tiles: ['VC', 'CCVCC', 'CV', 'V', 'CVC'],
        answer: 'CV CVC V VC CCVCC',
        why: 'CV eerst, dan CVC, V en VC. CCVCC, zoals sterk, komt bij iedereen als laatste (Levelt, Schiller en Levelt 2000).',
      },
      {
        kind: 'bet',
        id: 'spaans-ski',
        prompt: 'Hoe heet ‘ski’ waarschijnlijk in het Spaans?',
        options: ['esquí', 'sukii', 'sikí'],
        answer: 'esquí',
        why: 'Het Spaans zet een e vóór s + medeklinker: es-quí. Sukii is de Japanse oplossing: een klinker tussen s en k.',
      },
    ],
  },
  {
    id: 'g14',
    stage: 'master',
    domain: 'fon',
    title: 'ONSET tegen NOCODA',
    skill: 'Spelling',
    icon: '☞σ',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Lettergrepen in Optimaliteitstheorie',
        panels: [
          {
            text: 'Prince en Smolensky gebruikten in 1993 juist de lettergreep als eerste testcase voor Optimaliteitstheorie. Twee *markeringseisen* sturen alles: *ONSET* (een lettergreep heeft een begin) en *NOCODA* (een lettergreep heeft geen eind). Daartegenover staan *trouweisen*: *MAX* (laat niets weg) en *DEP* (voeg niets toe). Begin bij *zeeën*.',
            tableau: {
              input: '/zeː+ən/',
              constraints: [
                { name: 'DEP', note: 'Voeg geen klank toe.' },
                { name: 'MAX', note: 'Laat geen klank weg.' },
                { name: 'ONSET', note: 'Een lettergreep begint met een medeklinker.' },
              ],
              candidates: [
                { form: '[zeː.ən]', marks: [0, 0, 1] },
                { form: '[zeː.jən]', marks: [1, 0, 0] },
                { form: '[zeːn]', marks: [0, 1, 0] },
              ],
              winner: 1,
              goal: 'Laat [zeː.jən] winnen',
              note: 'ONSET en MAX staan boven DEP: liever een j erbij dan een lettergreep zonder begin, of een klank kwijt.',
            },
          },
          {
            text: 'Nu het Japans, met het Engelse *Christmas* als input. Het Japans verbiedt clusters en codas zo streng dat het liever drie klinkers toevoegt. Zoek de rangorde waarbij *kurisumasu* wint.',
            tableau: {
              input: '/krɪsməs/',
              constraints: [
                { name: 'DEP', note: 'Voeg geen klank toe.' },
                { name: 'MAX', note: 'Laat geen klank weg.' },
                { name: '∗COMPLEX', note: 'Geen medeklinkergroep in onset of coda.' },
                { name: 'NOCODA', note: 'Een lettergreep eindigt op een klinker.' },
              ],
              candidates: [
                { form: '[kris.mas]', marks: [0, 0, 1, 2] },
                { form: '[ku.ri.su.ma.su]', marks: [3, 0, 0, 0] },
                { form: '[ri.ma]', marks: [0, 3, 0, 0] },
              ],
              winner: 1,
              goal: 'Laat de Japanse vorm winnen',
              note: 'MAX en de markeringseisen staan boven DEP: liever klinkers erbij dan klanken kwijt of een cluster.',
            },
            deep: {
              q: 'Waarom is dit zo krachtig?',
              a: 'Met dezelfde eisen en een *andere rangorde* krijg je een andere taal. Dat heet *factoriële typologie*: elke rangorde is een mogelijke taal. Een taal die geen enkele rangorde voorspelt, zou niet mogen bestaan. Daardoor is de theorie toetsbaar.',
            },
          },
          {
            text: 'Speel taalontwerper. Zet ONSET en NOCODA hoog (boven de trouweisen) of laag. Vier rangordes, vier soorten talen. Precies het rijtje dat Jakobson al in de talen van de wereld zag.',
            lab: {
              label: 'Tik een rangorde',
              chips: [
                { k: 'allebei hoog', out: 'alleen CV', note: 'Elke lettergreep een begin en geen eind: het strengste sjabloon.' },
                { k: 'ONSET hoog', out: 'CV en CVC', note: 'Begin verplicht, eind mag. Zo werkt bijvoorbeeld het klassiek Arabisch.' },
                { k: 'NOCODA hoog', out: 'CV en V', note: 'Begin mag ontbreken, eind niet. Het Hawaïaans komt in de buurt.' },
                { k: 'allebei laag', out: 'CV, V, CVC en VC', note: 'Alles mag, zoals in het Nederlands: pa, ei, pak, ook.' },
              ],
            },
            rule: 'Geen enkele rangorde straft CV: het overtreedt ONSET noch NOCODA. Daarom heeft elke taal CV.',
          },
        ],
      },
      {
        kind: 'sort',
        id: 'overtreding',
        prompt: 'Welke eis overtreedt deze lettergreep?',
        buckets: ['ONSET', 'NOCODA', 'allebei', 'geen van beide'],
        items: [
          { t: 'ei', b: 0 },
          { t: 'pak', b: 1 },
          { t: 'ook', b: 2 },
          { t: 'uit', b: 2 },
          { t: 'pa', b: 3 },
          { t: 'zee', b: 3 },
          { t: 'dak', b: 1 },
          { t: 'in', b: 2 },
          { t: 'kou', b: 3 },
        ],
        why: 'ei: geen begin. pak en dak: wel een eind. ook, uit en in: allebei. pa, zee en kou: de perfecte CV, ook met een tweeklank als kern.',
      },
      {
        kind: 'choice',
        id: 'welke-eis',
        prompt: 'Een taal laat V en CV toe, maar nooit CVC. Welke eis staat hoog?',
        before: '',
        after: '',
        options: ['NOCODA', 'ONSET', 'DEP'],
        answer: 'NOCODA',
        why: 'Een begin mag ontbreken (V), een eind nooit. Dus NOCODA staat boven de trouweisen, ONSET eronder.',
      },
      {
        kind: 'bet',
        id: 'zonder-cv',
        prompt: 'Kan er een taal bestaan met alleen V en VC, en zonder CV?',
        intro: 'Denk na met de eisen, niet met je geheugen.',
        options: ['Nee, geen enkele rangorde levert dat op', 'Ja, als ONSET hoog staat', 'Ja, als NOCODA hoog staat'],
        answer: 'Nee, geen enkele rangorde levert dat op',
        why: 'CV overtreedt ONSET noch NOCODA. Er is dus geen eis die CV kan laten verliezen van V. Zo voorspelt OT de universele CV.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Eén doel, veel wegen, en de kritiek',
        panels: [
          {
            text: 'Al in 1970 zag Charles Kisseberth iets vreemds. In één taal werkten verschillende regels samen aan hetzelfde doel, als een *samenzwering*: de ene voegde klinkers in, de andere liet medeklinkers weg, en allebei voorkwamen ze clusters. In de regelfonologie was dat toeval. In OT is het logisch: één markeringseis, en de trouweisen bepalen de reparatie. Een peuter die *poes* als [pu] zegt, heeft dezelfde NOCODA als het Japans, maar MAX staat bij hem laag.',
            tableau: {
              input: '/pus/',
              constraints: [
                { name: 'MAX', note: 'Laat geen klank weg.' },
                { name: 'DEP', note: 'Voeg geen klank toe.' },
                { name: 'NOCODA', note: 'Een lettergreep eindigt op een klinker.' },
              ],
              candidates: [
                { form: '[pus]', marks: [0, 0, 1] },
                { form: '[pu.sə]', marks: [0, 1, 0] },
                { form: '[pu]', marks: [1, 0, 0] },
              ],
              winner: 2,
              goal: 'Laat de peutervorm [pu] winnen',
              note: 'NOCODA en DEP boven MAX: liever een klank kwijt dan een coda of een extra klinker. Het Japans heeft DEP onderaan en kiest invoegen.',
            },
          },
          {
            text: 'Klassieke OT geeft per rangorde één winnaar. Maar *melk* klinkt soms als [mɛlk] en soms als [mɛlək]. Paul Boersma (1997) stelde *stochastische OT* voor: elke eis heeft een plek op een getallenlijn, en bij elke uiting schuift die plek een beetje. Liggen twee eisen dicht bij elkaar, dan wisselen ze soms van volgorde, en krijg je variatie. Met hun *Gradual Learning Algorithm* lieten Boersma en Hayes (2001) zien hoe een lerner zulke plekken uit de frequenties in zijn invoer haalt.',
            lab: {
              label: 'Tik een afstand tussen DEP en de eis tegen lk',
              chips: [
                { k: 'ver uit elkaar', out: 'altijd [mɛlk]', note: 'DEP staat ver boven: de schwa komt er nooit in.' },
                { k: 'dicht bij elkaar', out: 'soms [mɛlk], soms [mɛlək]', note: 'Door de ruis wisselen ze soms van plek: optionele epenthese.' },
                { k: 'omgekeerd ver', out: 'altijd [mɛlək]', note: 'Een spreker voor wie de schwa vast is.' },
              ],
            },
          },
          {
            text: 'Een lastige vraag voor OT is het *too-many-solutions-probleem* (Steriade 2001). Een stemhebbende eindklank als in /hɔnd/ kun je op veel manieren oplossen: stemloos maken [hɔnt], weglaten [hɔn], of een klinker toevoegen [hɔndə]. Een vrije rangorde voorspelt al die talen. Maar talen kiezen bijna altijd voor stemloos maken. Steriade stelde een *P-map* voor: sprekers kiezen de reparatie die het minst *hoorbaar* afwijkt van de invoer.',
            quiz: {
              q: 'Welke reparatie van /hɔnd/ ligt volgens de P-map het dichtst bij de invoer?',
              options: ['[hɔnt]', '[hɔn]', '[hɔndə]'],
              answer: '[hɔnt]',
              why: 'Alleen de stem verandert: het kleinste hoorbare verschil. Weglaten of toevoegen valt veel meer op.',
            },
          },
          {
            text: 'Een ander alternatief is *Harmonische Grammatica* (Legendre, Miyata en Smolensky 1990). Daar hebben eisen geen strikte rangorde, maar *gewichten* die je optelt. In OT kunnen honderd overtredingen van een lage eis nooit opwegen tegen één overtreding van een hogere. In Harmonische Grammatica wel: twee lichtere eisen samen kunnen een zwaardere verslaan. Dat heet een *gang effect*. Of talen zulke effecten echt vertonen, is een levendig debat.',
            quiz: {
              q: 'Eis A weegt 3, eisen B en C wegen elk 2. Kandidaat 1 overtreedt A, kandidaat 2 overtreedt B en C. Wie wint in Harmonische Grammatica?',
              options: ['kandidaat 1 (strafpunten 3 tegen 4)', 'kandidaat 2 (A is het zwaarst)', 'gelijkspel'],
              answer: 'kandidaat 1 (strafpunten 3 tegen 4)',
              why: 'B en C samen kosten 4, meer dan A. In OT met A bovenaan zou kandidaat 2 winnen: een gang effect.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'reparatie-ot',
        prompt: 'Welke trouweis staat laag bij deze reparatie?',
        buckets: ['DEP laag: invoegen', 'MAX laag: weglaten'],
        items: [
          { t: 'kurisumasu (Japans)', b: 0 },
          { t: 'zeeën als [zeː.jən]', b: 0 },
          { t: 'escuela (Spaans)', b: 0 },
          { t: 'law-r-and order', b: 0 },
          { t: 'l’ami (Frans)', b: 1 },
          { t: 'blue als [bu] (peuter)', b: 1 },
          { t: 'poes als [pu] (peuter)', b: 1 },
        ],
        why: 'Invoegen kost DEP: die staat dan laag. Weglaten kost MAX. Dezelfde markeringseisen, andere reparaties.',
      },
      {
        kind: 'type',
        id: 'rangordes',
        prompt: 'Hoeveel rangordes kun je maken met vier eisen?',
        before: 'Met vier eisen zijn er',
        after: 'rangordes.',
        hint: 'getal',
        answer: '24',
        why: '4 × 3 × 2 × 1 = 24. Elke rangorde is een mogelijke taal: de factoriële typologie.',
      },
      {
        kind: 'choice',
        id: 'gang',
        prompt: 'Wat kan in Harmonische Grammatica wel en in klassieke OT niet?',
        before: '',
        after: '',
        options: ['Twee lagere eisen samen verslaan één hogere', 'Een kandidaat wint zonder overtredingen', 'Eisen hebben een volgorde'],
        answer: 'Twee lagere eisen samen verslaan één hogere',
        why: 'Gewichten tel je op. In OT beslist de hoogste eis waar kandidaten verschillen, ongeacht het aantal lagere sterren.',
      },
      {
        kind: 'order',
        id: 'ot-tijd',
        prompt: 'Zet de ideeën in de tijd.',
        tiles: ['stochastische OT en GLA', 'Kisseberth: samenzweringen', 'Optimaliteitstheorie', 'Harmonische Grammatica'],
        answer: 'Kisseberth: samenzweringen Harmonische Grammatica Optimaliteitstheorie stochastische OT en GLA',
        why: 'Kisseberth 1970, Legendre, Miyata en Smolensky 1990, Prince en Smolensky 1993, Boersma 1997 en Boersma en Hayes 2001.',
      },
      {
        kind: 'swipe',
        id: 'ot-kritiek',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'In OT verklaart één markeringseis met verschillende trouweisen verschillende reparaties.', ok: true, why: 'Japans voegt in, de peuter laat weg: zelfde NOCODA.' },
          { t: 'Klassieke OT voorspelt vanzelf optionele variatie zoals melk en melluk.', ok: false, fix: 'Daarvoor is bijvoorbeeld stochastische OT nodig', why: 'Eén vaste rangorde geeft één winnaar.' },
          { t: 'Het too-many-solutions-probleem gaat over reparaties die talen nooit kiezen.', ok: true, why: 'Weglaten of toevoegen bij /hɔnd/ komt bijna niet voor.' },
          { t: 'De P-map kiest de reparatie die het meest opvalt.', ok: false, fix: 'De reparatie die het minst opvalt', why: 'De kleinste hoorbare afwijking van de invoer.' },
          { t: 'In Harmonische Grammatica hebben eisen gewichten.', ok: true, why: 'Strafpunten worden opgeteld.' },
          { t: 'Kisseberth schreef over samenzweringen ná de komst van OT.', ok: false, fix: 'Hij schreef erover in 1970, ruim vóór OT', why: 'Zijn probleem was een van de redenen om OT te bedenken.' },
        ],
      },
      {
        kind: 'bet',
        id: 'stochastisch',
        prompt: 'In stochastische OT liggen DEP en een eis tegen lk-codas heel dicht bij elkaar. Wat voorspel je voor ‘melk’?',
        options: ['Soms [mɛlk], soms [mɛlək]', 'Altijd [mɛlək]', 'Altijd [mɛlk]'],
        answer: 'Soms [mɛlk], soms [mɛlək]',
        why: 'Door de ruis bij elke uiting wisselen de twee eisen soms van plek. Zo beschrijf je optionele epenthese.',
      },
    ],
  },
  {
    id: 'g15',
    stage: 'master',
    domain: 'fon',
    also: ['morf'],
    title: 'Het prosodische woord',
    skill: 'Spelling',
    icon: 'ω',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'De toren boven de lettergreep',
        panels: [
          {
            text: 'De lettergreep is niet de top van de toren. Fonologen stapelen verder: lettergrepen vormen *voeten*, voeten vormen een *prosodisch woord* (ω), en daarboven komen de *fonologische frase* en de *intonatiefrase* (Nespor en Vogel 1986). Elke laag is het domein van eigen regels.',
            swap: {
              goal: 'Stapel van klein naar groot',
              blocks: ['voet', 'intonatiefrase', 'lettergreep', 'prosodisch woord', 'fonologische frase'],
              accept: ['lettergreep voet prosodisch woord fonologische frase intonatiefrase'],
              note: 'σ < voet < ω < fonologische frase < intonatiefrase: de prosodische hiërarchie.',
            },
          },
          {
            text: 'Nu het slimme stuk. Zeg *honden*: [hɔn.dən]. De d schuift naar de onset en blijft een d. Zeg nu *hondachtig*: [hɔnt.ɑx.təx]. De d wordt een t! Waarom springt hij niet door, zoals in *heb ik*? Omdat *-achtig* een eigen prosodisch woord vormt. Over de grens tussen twee ω’s springt geen medeklinker.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'honden', out: '[hɔn.dən]', note: '-en hoort bij hetzelfde prosodische woord: de d schuift door en blijft stemhebbend.' },
                { k: 'hondachtig', out: '[hɔnt.ɑx.təx]', note: '-achtig is een eigen ω: de d blijft in de coda en wordt t.' },
                { k: 'rode', out: '[roː.də]', note: 'De d van rood schuift door.' },
                { k: 'roodachtig', out: '[roːt.ɑx.təx]', note: 'Hier niet: je hoort een t.' },
              ],
            },
            rule: 'Een samenhangend achtervoegsel (-en, -e, -ig) smelt samen met de stam. Een niet-samenhangend achtervoegsel (-achtig) en elk deel van een samenstelling vormt een eigen prosodisch woord.',
            quiz: {
              q: 'Hoe zeg je ‘eindexamen’ in zorgvuldige spraak?',
              options: ['[ɛint.ɛk.saː.mən]', '[ɛin.dɛk.saː.mən]'],
              answer: '[ɛint.ɛk.saː.mən]',
              why: 'eind en examen zijn twee prosodische woorden. De d blijft in de coda en wordt t.',
            },
          },
          {
            text: 'Hetzelfde zie je aan het begin van woorddelen. *Be-amen* krijgt een glottisslag: [bə.ʔaː.mən]. Ook *geërfd* klinkt als [ɣə.ʔɛrft]. De lettergreep zonder onset krijgt geen medeklinker van links, maar een eigen ʔ. Zo blijft de bouw van een woord hoorbaar, dankzij de prosodische grenzen.',
            quiz: {
              q: 'Wat hoor je tussen ge en erfd in ‘geërfd’?',
              options: ['een glottisslag', 'een j', 'een r'],
              answer: 'een glottisslag',
              why: 'De lettergreep erfd begint zonder onset en krijgt geen klank van links: [ɣə.ʔɛrft].',
            },
            deep: {
              q: 'Wie werkte dit uit?',
              a: 'Het onderscheid tussen samenhangende (*cohering*) en niet-samenhangende (*non-cohering*) affixen is voor het Nederlands vooral uitgewerkt door Geert Booij, onder meer in *The Phonology of Dutch* (1995). In heel snelle spraak kan de grens toch vervagen; de analyse gaat over de structuur, niet over elk spraakmoment.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'doorschuiven',
        prompt: 'Schuift de laatste medeklinker van de stam door naar de volgende lettergreep?',
        buckets: ['ja: hij blijft stemhebbend', 'nee: hij wordt stemloos'],
        items: [
          { t: 'honden', b: 0 },
          { t: 'rode', b: 0 },
          { t: 'handig', b: 0 },
          { t: 'hondachtig', b: 1 },
          { t: 'roodachtig', b: 1 },
          { t: 'eindexamen', b: 1 },
          { t: 'binding', b: 0 },
          { t: 'rijder', b: 0 },
          { t: 'bloedarm', b: 1 },
        ],
        why: '-en, -e, -ig, -ing en -er smelten samen met de stam: [hɔn.dən], [roː.də], [hɑn.dəx], [bɪn.dɪŋ], [rɛi.dər]. -achtig en de delen van een samenstelling (eind-examen, bloed-arm) vormen een eigen ω: de d blijft eindklank en wordt t.',
      },
      {
        kind: 'choice',
        id: 'waarom-t',
        prompt: 'Waarom wordt de d in ‘hondachtig’ een t?',
        before: '',
        after: '',
        options: [
          '-achtig is een eigen prosodisch woord, dus de d blijft aan het eind van een lettergreep',
          '-achtig begint met een medeklinker',
          'De klemtoon valt op -achtig',
        ],
        answer: '-achtig is een eigen prosodisch woord, dus de d blijft aan het eind van een lettergreep',
        why: 'Eindklankverscherping geldt aan het eind van een lettergreep. De ω-grens houdt de d daar vast.',
      },
      {
        kind: 'bet',
        id: 'webachtig',
        prompt: 'Hoe klinkt ‘webachtig’?',
        options: ['[wɛp.ɑx.təx]', '[wɛ.bɑx.təx]'],
        answer: '[wɛp.ɑx.təx]',
        why: 'Net als hondachtig: -achtig is een eigen ω, dus de b blijft in de coda en wordt p.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Grenzen, frasen en recursie',
        panels: [
          {
            text: 'Ook voorvoegsels houden in zorgvuldige spraak hun grens. Vergelijk *veren* [veː.rən] met *vereren* [vər.ʔeː.rən]. In *veren* schuift de r naar de volgende lettergreep. In *vereren* blijft hij bij *ver-*, en *eren* krijgt een glottisslag. Zo ook *on-aardig* [ɔn.ʔaːr.dəx], niet *o-naardig*. De lettergreepgrens volgt hier de bouw van het woord, niet het Maximale-Onsetprincipe.',
            split: { q: 'Knip ‘vereren’ zoals je het zorgvuldig zegt', word: 'vereren', answer: 'ver-e-ren', note: 'De r blijft bij ver-. Vóór eren hoor je een glottisslag: [vər.ʔeː.rən].' },
          },
          {
            text: 'Hoger in de toren werken andere regels. Neem de Engelse *ritmeregel* (Liberman en Prince 1977). Los zeg je *thir-TEEN*, maar in *THIR-teen MEN* schuift de klemtoon naar voren, zodat twee klemtonen niet botsen. Dat gebeurt alleen binnen een *fonologische frase*. Ligt er een frasegrens tussen, dan blijft de klemtoon staan. Nespor en Vogel (1986) gebruikten zulke regels om elke laag van de toren te bewijzen.',
            lab: {
              label: 'Tik een uiting',
              chips: [
                { k: 'thirteen', out: 'thir-TEEN', note: 'Los: klemtoon achteraan.' },
                { k: 'thirteen men', out: 'THIR-teen MEN', note: 'Binnen één fonologische frase schuift de klemtoon weg van de botsing.' },
                { k: 'Joan’s thirteen', out: 'thir-TEEN', note: 'Aan het eind van de frase is er geen botsing, dus geen verschuiving.' },
              ],
            },
          },
          {
            text: 'De klassieke toren volgt de *Strikte-Lagenhypothese* (Selkirk 1984, Nespor en Vogel 1986): elke laag bestaat precies uit eenheden van de laag eronder, zonder lagen over te slaan of te herhalen. Maar kleine functiewoorden passen daar slecht in. Selkirk (1996) liet zien dat een lidwoord als *de* vaak geen eigen prosodisch woord is, maar direct aan de frase hangt. Itô en Mester bouwden later een toren met *recursie*: een prosodisch woord binnen een prosodisch woord, zoals *hond* binnen *hondachtig*.',
            quiz: {
              q: 'Welk geval past slecht bij de Strikte-Lagenhypothese?',
              options: ['Een lidwoord dat direct aan de frase hangt', 'Een lettergreep binnen een voet', 'Een voet binnen een prosodisch woord'],
              answer: 'Een lidwoord dat direct aan de frase hangt',
              why: 'Dan wordt de laag van het prosodische woord overgeslagen. Daarom kwamen voorstellen met zwakkere lagen en recursie.',
            },
          },
          {
            text: 'Welke achtervoegsels zijn samenhangend? Booij (1995) beschrijft een duidelijk patroon. Achtervoegsels met een schwa of een korte klinker vooraan, zoals *-en*, *-e*, *-er*, *-ig* en *-ing*, smelten samen met de stam. Achtervoegsels die zelf een volle, klemtoondragende vorm hebben, zoals *-achtig*, en veel achtervoegsels met een medeklinker vooraan, zoals *-heid*, *-loos* en *-schap*, vormen een eigen prosodisch woord. Klinkt een achtervoegsel als een woord, dan gedraagt het zich ook zo.',
            quiz: {
              q: 'Hoe zeg je ‘binding’?',
              options: ['[bɪn.dɪŋ], met een d', '[bɪnt.ɪŋ], met een t'],
              answer: '[bɪn.dɪŋ], met een d',
              why: '-ing is samenhangend. De d schuift door en blijft stemhebbend, anders dan in hondachtig.',
            },
          },
        ],
      },
      {
        kind: 'choice',
        id: 'vereren',
        prompt: 'Waarom hoor je in ‘vereren’ een glottisslag en in ‘veren’ niet?',
        before: '',
        after: '',
        options: [
          'In vereren houdt het voorvoegsel ver- zijn grens, dus eren begint zonder onset',
          'vereren heeft meer lettergrepen',
          'In veren valt de klemtoon op de laatste lettergreep',
        ],
        answer: 'In vereren houdt het voorvoegsel ver- zijn grens, dus eren begint zonder onset',
        why: 'De r van ver- schuift niet door. De lettergreep e krijgt daarom een eigen begin: ʔ.',
      },
      {
        kind: 'sort',
        id: 'samenhang',
        prompt: 'Samenhangend of een eigen prosodisch woord (volgens Booij)?',
        buckets: ['samenhangend', 'eigen prosodisch woord'],
        items: [
          { t: '-en', b: 0 },
          { t: '-e', b: 0 },
          { t: '-ig', b: 0 },
          { t: '-ing', b: 0 },
          { t: '-er', b: 0 },
          { t: '-achtig', b: 1 },
          { t: '-heid', b: 1 },
          { t: '-loos', b: 1 },
          { t: '-schap', b: 1 },
        ],
        why: 'Schwa en korte klinkers vooraan smelten samen: honden, handig, binding, rijder. -achtig, -heid, -loos en -schap gedragen zich als woorden.',
      },
      {
        kind: 'type',
        id: 'voetbalveld',
        prompt: 'Uit hoeveel prosodische woorden bestaat ‘voetbalveld’?',
        before: 'voetbalveld bevat',
        after: 'prosodische woorden.',
        hint: 'getal',
        answer: '3',
        why: 'voet, bal en veld: elk deel van een samenstelling vormt een eigen ω. Samen vormen ze weer een groter, recursief prosodisch woord.',
      },
      {
        kind: 'swipe',
        id: 'toren-diep',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'In vereren schuift de r van ver- door naar de volgende lettergreep.', ok: false, fix: 'De r blijft bij ver-', why: '[vər.ʔeː.rən]: de voorvoegselgrens houdt hem tegen.' },
          { t: 'De Engelse ritmeregel werkt binnen een fonologische frase.', ok: true, why: 'THIR-teen MEN: binnen de frase schuift de klemtoon.' },
          { t: 'Volgens de Strikte-Lagenhypothese mag een laag worden overgeslagen.', ok: false, fix: 'Volgens die hypothese mag dat niet', why: 'Elke laag bestaat uit eenheden van de laag direct eronder.' },
          { t: 'Selkirk liet zien dat functiewoorden vaak geen eigen prosodisch woord zijn.', ok: true, why: 'Een lidwoord leunt op zijn buren.' },
          { t: '-ing in binding vormt een eigen prosodisch woord.', ok: false, fix: '-ing is samenhangend', why: 'De d schuift door: [bɪn.dɪŋ].' },
          { t: 'Recursie betekent dat een prosodisch woord een ander prosodisch woord kan bevatten.', ok: true, why: 'hond binnen hondachtig, voet binnen voetbal.' },
        ],
      },
      {
        kind: 'choice',
        id: 'onaardig',
        prompt: 'Hoe zeg je ‘onaardig’ in zorgvuldige spraak?',
        before: '',
        after: '',
        options: ['[ɔn.ʔaːr.dəx]', '[ɔ.naːr.dəx]'],
        answer: '[ɔn.ʔaːr.dəx]',
        why: 'De n blijft bij on-. aardig begint zonder onset en krijgt een glottisslag.',
      },
      {
        kind: 'bet',
        id: 'ritmeregel',
        prompt: 'Waar ligt de klemtoon van ‘thirteen’ in ‘thirteen men’?',
        options: ['vooraan: THIR-teen', 'achteraan: thir-TEEN'],
        answer: 'vooraan: THIR-teen',
        why: 'De ritmeregel vermijdt twee klemtonen naast elkaar (teen MEN). Binnen de fonologische frase schuift de klemtoon naar voren.',
      },
    ],
  },
  {
    id: 'g16',
    stage: 'master',
    domain: 'fon',
    title: 'Ritme: het Nederlands telt klemtonen',
    skill: 'Spelling',
    icon: '♪',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Ritmeklassen',
        panels: [
          {
            text: 'Zeg *banaan* eens snel: [bəˈnaːn]. De a van de eerste lettergreep verdwijnt in een schwa. Het Nederlands knijpt onbeklemtoonde lettergrepen samen. Het Spaans en Italiaans doen dat veel minder: *banana* houdt drie volle a’s.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'banaan', out: '[bəˈnaːn]', note: 'Onbeklemtoonde a wordt schwa.' },
                { k: 'politie', out: '[pəˈli(t)si]', note: 'Zeker in snelle spraak: de o wordt schwa.' },
                { k: 'banana (Spaans)', out: '[baˈnana]', note: 'Drie volle klinkers, ook zonder klemtoon.' },
              ],
            },
          },
          {
            text: 'Taalkundigen deelden talen ooit in drie ritmeklassen: *klemtoontellend* (Engels, Nederlands), *lettergreeptellend* (Spaans, Frans, Italiaans) en *moratellend* (Japans) (Pike 1945, Abercrombie 1967). Dat klemtonen op precies gelijke afstand vallen, bleek bij metingen niet te kloppen. Ramus, Nespor en Mehler (1999) vonden een betere maat: welk deel van de tijd klinkers innemen, *%V*. Talen met veel clusters en gereduceerde klinkers, zoals het Nederlands, scoren laag.',
            quiz: {
              q: 'Welke taal heeft waarschijnlijk de hoogste %V?',
              options: ['Japans', 'Nederlands', 'Engels'],
              answer: 'Japans',
              why: 'Bijna alleen CV-lettergrepen: veel klinker, weinig clusters.',
            },
          },
          {
            text: 'Het verrassende: baby’s horen dit al. Nazzi, Bertoncini en Mehler (1998) lieten Franse pasgeborenen talen horen. Engels en Japans hielden ze uit elkaar, Engels en Nederlands niet: die klinken in hetzelfde ritme. Je oor kende het ritme van je moedertaal dus al voordat je één woord begreep.',
            quiz: {
              q: 'Wat voorspelt dit onderzoek voor Nederlands tegenover Japans?',
              options: ['Pasgeborenen kunnen ze waarschijnlijk uit elkaar houden', 'Pasgeborenen kunnen ze niet uit elkaar houden'],
              answer: 'Pasgeborenen kunnen ze waarschijnlijk uit elkaar houden',
              why: 'Het gaat om de ritmeklasse, niet om kennis van de taal. Nederlands is klemtoontellend, Japans moratellend.',
            },
            rule: 'Het Nederlands is klemtoontellend: sterke lettergrepen met daartussen gereduceerde, zwakke.',
            deep: {
              q: 'Is dat nog de stand van de wetenschap?',
              a: 'De klassen zijn eerder een glijdende schaal dan drie bakjes. Het Pools heeft bijvoorbeeld veel clusters maar weinig klinkerreductie. En nieuwer onderzoek vraagt zich af of pasgeborenen echt ritme horen, of andere eigenschappen van het geluid. Het debat loopt nog: precies het soort vraag waar een masterscriptie over gaat.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'reductie',
        prompt: 'Volle klinker of schwa, in gewone spraak?',
        buckets: ['volle klinker', 'schwa'],
        items: [
          { t: 'de naan in banaan', b: 0 },
          { t: 'de zond in gezond', b: 0 },
          { t: 'de ta in tafel', b: 0 },
          { t: 'de ba in banaan', b: 1 },
          { t: 'de ge in gezond', b: 1 },
          { t: 'de fel in tafel', b: 1 },
          { t: 'de nijn in konijn', b: 0 },
          { t: 'de ko in konijn', b: 1 },
          { t: 'de ver in vertellen', b: 1 },
        ],
        why: 'De beklemtoonde lettergreep houdt zijn volle klinker. De andere worden schwa: bə-naan, gə-zond, ta-fəl, kə-nijn, vər-tel-len.',
      },
      {
        kind: 'choice',
        id: 'nazzi',
        prompt: 'Welk paar hielden pasgeborenen in het onderzoek van Nazzi en collega’s níet uit elkaar?',
        before: '',
        after: '',
        options: ['Engels en Nederlands', 'Engels en Japans'],
        answer: 'Engels en Nederlands',
        why: 'Allebei klemtoontellend. Japans heeft een heel ander ritme.',
      },
      {
        kind: 'bet',
        id: 'klasse',
        prompt: 'Welke ritmeklasse past bij het Japans?',
        options: ['moratellend', 'klemtoontellend', 'lettergreeptellend'],
        answer: 'moratellend',
        why: 'Het Japans telt moras, zoals in de haiku: to-o-kyo-o.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Ritme meten, horen en spelen',
        panels: [
          {
            text: 'Esther Grabe en Ee Ling Low (2002) bedachten een andere maat: de *Pairwise Variability Index* (PVI). Je vergelijkt de duur van elke klinker met die van de volgende. In het Nederlands, Duits en Engels wisselen lange en korte klinkers elkaar sterk af: hoge PVI. In het Frans en Spaans zijn opeenvolgende klinkers ongeveer even lang: lage PVI. Maar Amalia Arvaniti (2012) liet zien dat zulke maten sterk afhangen van de gekozen zinnen en sprekers. Met andere teksten schuiven talen soms van plek.',
            quiz: {
              q: 'Wat meet de PVI?',
              options: ['hoe sterk de duur van opeenvolgende klinkers verschilt', 'hoeveel lettergrepen per seconde iemand zegt', 'hoe hoog de toon is'],
              answer: 'hoe sterk de duur van opeenvolgende klinkers verschilt',
              why: 'Lang-kort-lang geeft een hoge PVI, zoals in het Nederlands.',
            },
          },
          {
            text: 'Ritme stuurt hoe je woorden uit de klankstroom vist. Mehler en collega’s (1981) lieten Franse luisteraars op *pa* of *pal* drukken. In *pa-lace* vonden ze *pa* sneller, in *pal-mier* juist *pal*: ze luisterden per lettergreep. Engelse luisteraars deden dat niet. Zij beginnen een nieuw woord bij elke *sterke* lettergreep (Cutler en Norris 1988). En Japanse luisteraars bleken per *mora* te knippen (Otake en collega’s 1993). Elk oor gebruikt het ritme van zijn eigen taal.',
            lab: {
              label: 'Tik een luisteraar',
              chips: [
                { k: 'Frans', out: 'per lettergreep', note: 'pa sneller in pa-lace, pal sneller in pal-mier.' },
                { k: 'Engels', out: 'per sterke lettergreep', note: 'Een volle, beklemtoonde lettergreep is het teken: hier begint misschien een woord.' },
                { k: 'Japans', out: 'per mora', note: 'Het ritme van de haiku is ook het ritme van het luisteren.' },
                { k: 'Nederlands', out: 'per sterke lettergreep', note: 'Net als het Engels: ook Nederlandse inhoudswoorden beginnen meestal met een sterke lettergreep.' },
              ],
            },
          },
          {
            text: 'Wanneer leren baby’s dit? Peter Jusczyk, Anne Cutler en Nancy Redanz (1993) lieten Amerikaanse baby’s woordjes horen met het patroon sterk-zwak (*TA-fel*) en zwak-sterk (*ba-NAAN*). Baby’s van negen maanden luisterden langer naar sterk-zwak, het gewone patroon van het Engels. Baby’s van zes maanden hadden nog geen voorkeur. Tussen zes en negen maanden leert een baby dus het woordritme van zijn taal.',
            quiz: {
              q: 'Op welke leeftijd vonden Jusczyk en collega’s een voorkeur voor sterk-zwak?',
              options: ['negen maanden', 'zes maanden', 'bij de geboorte'],
              answer: 'negen maanden',
              why: 'Met zes maanden nog niet, met negen maanden wel.',
            },
          },
          {
            text: 'Hoor je het taalritme ook in muziek? Aniruddh Patel en Joseph Daniele (2003) pasten de PVI toe op thema’s van Engelse en Franse componisten van rond 1900. De Engelse muziek had een hogere PVI dan de Franse, net als de talen zelf. Componisten nemen het ritme van hun moedertaal dus mee in hun melodieën, zonder dat ze het merken.',
            quiz: {
              q: 'Welke muziek had in het onderzoek van Patel en Daniele de hoogste PVI?',
              options: ['die van Engelse componisten', 'die van Franse componisten', 'er was geen verschil'],
              answer: 'die van Engelse componisten',
              why: 'Net als het Engels zelf: sterkere afwisseling tussen lange en korte noten.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'pvi',
        prompt: 'Hoge of lage klinker-PVI?',
        buckets: ['hoog: lang en kort wisselen sterk', 'laag: klinkers ongeveer even lang'],
        items: [
          { t: 'Nederlands', b: 0 },
          { t: 'Engels', b: 0 },
          { t: 'Duits', b: 0 },
          { t: 'Frans', b: 1 },
          { t: 'Spaans', b: 1 },
        ],
        why: 'Klinkerreductie maakt de afwisseling groot in het Nederlands, Engels en Duits. Frans en Spaans houden hun klinkers voller en gelijkmatiger.',
      },
      {
        kind: 'choice',
        id: 'palmier',
        prompt: 'Een Franse luisteraar zoekt het stukje ‘pal’. In welk woord vindt hij het het snelst?',
        before: '',
        after: '',
        options: ['palmier', 'palace'],
        answer: 'palmier',
        why: 'pal-mier: pal is daar een hele lettergreep. In pa-lace loopt pal over de grens.',
      },
      {
        kind: 'order',
        id: 'ritme-tijd',
        prompt: 'Zet de ideeën over ritme in de tijd.',
        tiles: ['Arvaniti: maten zijn wankel', 'Pike: twee ritmeklassen', 'Ramus en collega’s: %V', 'Grabe en Low: PVI'],
        answer: 'Pike: twee ritmeklassen Ramus en collega’s: %V Grabe en Low: PVI Arvaniti: maten zijn wankel',
        why: 'Pike 1945, Ramus, Nespor en Mehler 1999, Grabe en Low 2002, Arvaniti 2012.',
      },
      {
        kind: 'swipe',
        id: 'ritme-diep',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Franse luisteraars knippen de klankstroom vooral per lettergreep.', ok: true, why: 'pa in pa-lace, pal in pal-mier.' },
          { t: 'Engelse luisteraars knippen per mora.', ok: false, fix: 'Ze knippen bij sterke lettergrepen', why: 'Per mora knippen Japanse luisteraars.' },
          { t: 'Baby’s van zes maanden hebben al een voorkeur voor sterk-zwak.', ok: false, fix: 'Pas rond negen maanden', why: 'Met zes maanden vonden Jusczyk en collega’s nog geen voorkeur.' },
          { t: 'Arvaniti vond dat ritmematen sterk afhangen van de gekozen zinnen.', ok: true, why: 'Daarom zijn de klassen minder hard dan ze leken.' },
          { t: 'In de muziek van Engelse componisten vonden Patel en Daniele een hogere PVI dan in Franse.', ok: true, why: 'De muziek volgt het taalritme.' },
          { t: 'Een hoge PVI betekent dat alle klinkers even lang zijn.', ok: false, fix: 'Een hoge PVI betekent grote verschillen', why: 'Lang-kort-lang geeft een hoge PVI.' },
        ],
      },
      {
        kind: 'type',
        id: 'pvi-naam',
        prompt: 'Hoe heet de ritmemaat van Grabe en Low (de afkorting)?',
        before: 'De',
        after: 'vergelijkt de duur van opeenvolgende klinkers.',
        hint: 'drie letters',
        answer: 'PVI',
        why: 'Pairwise Variability Index: hoe groot het verschil is tussen buren.',
      },
      {
        kind: 'bet',
        id: 'sterk-begin',
        prompt: 'Je hoort in een snelle Nederlandse zin een volle, beklemtoonde lettergreep. Wat doet je brein waarschijnlijk?',
        options: ['Het gokt dat daar een nieuw woord begint', 'Het gokt dat daar een woord eindigt', 'Niets bijzonders'],
        answer: 'Het gokt dat daar een nieuw woord begint',
        why: 'De meeste inhoudswoorden beginnen met een sterke lettergreep. Daarom is een sterke lettergreep een goede gok voor een woordbegin.',
      },
    ],
  },
  {
    id: 'g17',
    stage: 'master',
    domain: 'fon',
    also: ['orth'],
    title: 'De lettergreep in je hoofd',
    skill: 'Spelling',
    icon: 'σ→',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Spreken, leren en spellen',
        panels: [
          {
            text: 'Hoe spreek je zo snel? Volgens Willem Levelt heb je een *mentaal syllabarium*: een voorraad kant-en-klare mondbewegingen voor de lettergrepen die je het vaakst gebruikt. Levelt en Wheeldon (1994) toonden het aan in het Nederlands: woorden die eindigen op een veelvoorkomende lettergreep, zeg je zo’n 15 milliseconden sneller, los van hoe vaak het woord zelf voorkomt.',
            quiz: {
              q: 'Welk woord zeg je volgens deze theorie iets sneller?',
              options: ['Een woord dat eindigt op een veelvoorkomende lettergreep', 'Een woord dat eindigt op een zeldzame lettergreep'],
              answer: 'Een woord dat eindigt op een veelvoorkomende lettergreep',
              why: 'Die lettergreep ligt kant-en-klaar in je syllabarium en hoeft niet opnieuw te worden samengesteld.',
            },
            deep: {
              q: 'Hoe groot is dat syllabarium?',
              a: 'Een paar honderd lettergrepen in het Chinees of Japans, enkele duizenden in het Nederlands of Engels. De veelgebruikte lettergrepen liggen klaar; een zeldzame lettergreep bouw je klank voor klank op. Daarom zeg je een nieuw woord als *kadral* net iets trager dan *kader*.',
            },
          },
          {
            text: 'Kinderen knippen ook op lettergrepen, en ze bewaren vooral het sterke stuk. *Banaan* wordt *naan*, *giraf* wordt *raf*, *tomaat* wordt *maat*. De beklemtoonde lettergreep blijft, het zwakke begin valt weg. Paula Fikkert (1994) liet zien dat Nederlandse peuters woorden eerst in één voet persen: sterk, eventueel gevolgd door zwak.',
            quiz: {
              q: 'Wat zegt een peuter waarschijnlijk voor ‘konijn’?',
              options: ['nijn', 'ko', 'konij'],
              answer: 'nijn',
              why: 'De beklemtoonde lettergreep blijft: ko-NIJN wordt nijn.',
            },
          },
          {
            text: 'En op school? Bij spelling heet de lettergreep vaak een *klankgroep*. Kinderen leren hakken en plakken: *bo-men* is een open klankgroep, dus één o; *bom-men* is gesloten, dus een korte o. Dat is de fonologie van dit hele niveau, verpakt als spellingstrategie. Zo kom je terug bij waar De lettergreep begon: open en dicht.',
            tree: {
              q: 'Een laatste boom: hang ‘sterk’ op',
              segs: [
                { t: 's', role: 'onset' },
                { t: 't', role: 'onset' },
                { t: 'e', role: 'kern' },
                { t: 'r', role: 'coda' },
                { t: 'k', role: 'coda' },
              ],
              note: 'CCVCC: het type dat Nederlandse kinderen als laatste leren. En met r + k kun je er nog een schwa in horen: [stɛrək].',
            },
            rule: 'Je brein plant in lettergrepen, kinderen leren in lettergrepen, en de spelling rekent met lettergrepen.',
          },
        ],
      },
      {
        kind: 'swipe',
        id: 'hoofd',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Levelt en Wheeldon vonden effecten van lettergreepfrequentie in het Nederlands.', ok: true, why: 'Woorden met een veelvoorkomende laatste lettergreep werden sneller uitgesproken.' },
          { t: 'Peuters laten meestal de beklemtoonde lettergreep weg.', ok: false, fix: 'Ze laten de onbeklemtoonde lettergreep weg', why: 'banaan wordt naan: het sterke stuk blijft.' },
          { t: 'Het mentale syllabarium bevat een aparte beweging voor elk woord.', ok: false, fix: 'Het bevat bewegingen per lettergreep', why: 'Daarom heet het een syllabarium: een voorraad lettergrepen.' },
          { t: 'Een klankgroep op school is in de fonologie een lettergreep.', ok: true, why: 'Andere naam, zelfde eenheid.' },
        ],
      },
      {
        kind: 'bet',
        id: 'tomaat',
        prompt: 'Wat zegt een peuter waarschijnlijk voor ‘tomaat’?',
        options: ['maat', 'to', 'toma'],
        answer: 'maat',
        why: 'to-MAAT: de beklemtoonde lettergreep blijft.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Lettergrepen in het lab',
        panels: [
          {
            text: 'Staan lettergrepen in je woordgeheugen? Volgens het model van Levelt, Roelofs en Meyer (1999) niet. Je geheugen bewaart de *klanken* van een woord. Pas tijdens het spreken worden ze in lettergrepen verdeeld, en dat gebeurt over woordgrenzen heen. *Geef* is één lettergreep, maar in *geef het* zeg je [ɣeː.vət]: de v schuift naar *het*. Een opgeslagen lettergreep *geef* zou daar in de weg zitten. Pas ná dat rekenwerk haalt je brein de mondbewegingen uit het syllabarium.',
            lab: {
              label: 'Tik een uiting',
              chips: [
                { k: 'geef', out: '[ɣeːf]', note: 'Eén lettergreep, met f aan het eind.' },
                { k: 'geef het', out: '[ɣeː.vət]', note: 'De v wordt de onset van ət: de lettergreep loopt over de woordgrens.' },
                { k: 'geven', out: '[ɣeː.vən]', note: 'Binnen het woord: dezelfde verdeling als in geef het.' },
              ],
            },
          },
          {
            text: 'Kun je een lettergreep in het lab *aanzetten*? Ferrand, Segui en Grainger (1996) lieten Franse lezers heel kort een onzichtbaar stukje zien vóór een woord. Een stukje dat precies de eerste lettergreep was, versnelde het uitspreken het meest. Niels Schiller (1998) probeerde hetzelfde in het Nederlands en vond dat effect niet: alleen het aantal gedeelde klanken telde. Later vonden Cholin, Levelt en Schiller (2006) wel weer een effect van hoe vaak een lettergreep voorkomt. Het bewijs voor het syllabarium is dus sterk, maar niet elke proef werkt.',
            quiz: {
              q: 'Wat vond Schiller (1998) in het Nederlands?',
              options: ['Geen lettergreepeffect, wel een effect van gedeelde klanken', 'Een sterk lettergreepeffect, zoals in het Frans', 'Geen enkel effect'],
              answer: 'Geen lettergreepeffect, wel een effect van gedeelde klanken',
              why: 'Hoe meer klanken het stukje deelde met het woord, hoe sneller. Of het precies een lettergreep was, maakte niet uit.',
            },
          },
          {
            text: 'Ook je hersengolven lijken lettergrepen te volgen. In gewone spraak zeg je ongeveer vier tot vijf lettergrepen per seconde. Dat is precies het tempo van de *theta-golven* in je hersenen, vier tot acht trillingen per seconde. Anne-Lise Giraud en David Poeppel (2012) betoogden dat de hersenschors zijn ritme aan dat van de lettergrepen koppelt. Zo hakt je brein de stroom in lettergreephapjes, nog voordat je weet welke woorden het zijn.',
            quiz: {
              q: 'Hoeveel lettergrepen zeg je ongeveer per seconde in gewone spraak?',
              options: ['vier à vijf', 'één', 'twintig'],
              answer: 'vier à vijf',
              why: 'Dat valt samen met het tempo van theta-golven: vier tot acht per seconde.',
            },
          },
          {
            text: 'Wat als het syllabarium beschadigd raakt? Bij *apraxie van de spraak*, vaak na een beroerte, weten mensen wat ze willen zeggen, maar plannen ze de mondbewegingen moeizaam. Aichert en Ziegler (2004) vonden dat zulke patiënten veelvoorkomende lettergrepen beter uitspraken dan zeldzame, ook als de klanken even moeilijk waren. Dat past bij het idee dat vaste lettergrepen als kant-en-klare pakketjes klaarliggen.',
            quiz: {
              q: 'Welke lettergreep zegt iemand met apraxie van de spraak waarschijnlijk beter?',
              options: ['een veelvoorkomende', 'een zeldzame', 'geen verschil'],
              answer: 'een veelvoorkomende',
              why: 'Die ligt kant-en-klaar in het syllabarium. Een zeldzame moet klank voor klank worden gebouwd.',
            },
          },
        ],
      },
      {
        kind: 'order',
        id: 'spreken',
        prompt: 'Zet de stappen van het spreken in de volgorde van Levelts model.',
        tiles: ['lettergrepen maken', 'begrip kiezen', 'mondbewegingen', 'klanken ophalen', 'woord kiezen'],
        answer: 'begrip kiezen woord kiezen klanken ophalen lettergrepen maken mondbewegingen',
        why: 'Eerst wat je bedoelt, dan het woord, dan de klanken. Pas dan worden lettergrepen gemaakt, en die halen de mondbewegingen uit het syllabarium.',
      },
      {
        kind: 'sort',
        id: 'opgeslagen',
        prompt: 'Waar zit dit volgens Levelts model?',
        buckets: ['in het woordgeheugen', 'berekend tijdens het spreken', 'in het syllabarium'],
        items: [
          { t: 'de klanken van geven', b: 0 },
          { t: 'de betekenis van geven', b: 0 },
          { t: 'de grens in geef het', b: 1 },
          { t: 'heb ik als he-bik', b: 1 },
          { t: 'een zeldzame lettergreep als kwolm', b: 1 },
          { t: 'de mondbeweging voor de', b: 2 },
          { t: 'de mondbeweging voor ta', b: 2 },
        ],
        why: 'Klanken en betekenis staan in het woordgeheugen. Lettergrepen worden tijdens het spreken berekend, ook over woordgrenzen heen. Veelvoorkomende lettergrepen hebben een kant-en-klare beweging in het syllabarium; een zeldzame bouw je zelf.',
      },
      {
        kind: 'swipe',
        id: 'lab',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Volgens Levelt staan lettergrepen kant-en-klaar in het woordgeheugen.', ok: false, fix: 'Ze worden tijdens het spreken berekend', why: 'Anders kon geef het geen [ɣeː.vət] worden.' },
          { t: 'In geef het loopt een lettergreep over de woordgrens.', ok: true, why: 'De v wordt de onset van ət.' },
          { t: 'Schiller vond in het Nederlands hetzelfde lettergreepeffect als Ferrand in het Frans.', ok: false, fix: 'Hij vond het niet', why: 'Alleen het aantal gedeelde klanken telde.' },
          { t: 'Theta-golven hebben ongeveer het tempo van lettergrepen.', ok: true, why: 'Vier tot acht per seconde, tegen vier à vijf lettergrepen per seconde.' },
          { t: 'Bij apraxie van de spraak gaan veelvoorkomende lettergrepen vaak beter.', ok: true, why: 'Ze liggen klaar in het syllabarium.' },
          { t: 'Cholin, Levelt en Schiller vonden geen enkel effect van lettergreepfrequentie.', ok: false, fix: 'Ze vonden wel een effect', why: 'Veelvoorkomende lettergrepen werden sneller gezegd.' },
        ],
      },
      {
        kind: 'type',
        id: 'geef-het',
        prompt: 'Hoeveel lettergrepen zeg je in ‘geef het’?',
        before: 'geef het heeft',
        after: 'lettergrepen.',
        hint: 'getal',
        answer: '2',
        why: 'gee-vət: twee lettergrepen, en de grens ligt midden in het woord geef.',
      },
      {
        kind: 'choice',
        id: 'apraxie',
        prompt: 'Een patiënt met apraxie van de spraak zegt ‘de’ vlot, maar ‘kwolm’ moeizaam. Welke verklaring past bij het syllabarium?',
        before: '',
        after: '',
        options: [
          'de ligt kant-en-klaar, kwolm moet klank voor klank worden gebouwd',
          'kwolm heeft meer betekenis',
          'de is een functiewoord en heeft geen lettergreep',
        ],
        answer: 'de ligt kant-en-klaar, kwolm moet klank voor klank worden gebouwd',
        why: 'Een veelvoorkomende lettergreep haal je als pakketje op. Een zeldzame moet je zelf samenstellen, en juist dat plannen is bij apraxie moeizaam.',
      },
      {
        kind: 'bet',
        id: 'heb-het',
        prompt: 'Hoe verdeelt een spreker ‘heb het’ in snelle spraak?',
        options: ['he-bət', 'hep-ət', 'heb-hət'],
        answer: 'he-bət',
        why: 'Het onbeklemtoonde het verliest zijn h en leunt op heb. De b wordt de onset en blijft stemhebbend, net als in heb ik.',
      },
      {
        kind: 'highlight',
        id: 'herfst',
        prompt: 'Eindbaas: kleur de klanken van ‘herfst’',
        intro: 'Alles uit dit niveau in één woord: onset, kern, coda en appendix.',
        pens: [
          { id: 'onset', label: 'onset', tag: 'begin', ask: 'Komt deze klank vóór de kern?', accent: 'blue' },
          { id: 'kern', label: 'kern', tag: 'klinker', ask: 'Is dit het hart van de lettergreep?', accent: 'purple' },
          { id: 'coda', label: 'coda', tag: 'in de rijm', ask: 'Past deze klank nog binnen de drie plekken van de rijm?', accent: 'orange' },
          { id: 'appendix', label: 'appendix', tag: 'aan de rand', ask: 'Valt deze tongpuntklank buiten de rijm?', accent: 'teal' },
        ],
        words: [
          { t: 'h', role: 'onset' },
          { t: 'e', role: 'kern' },
          { t: 'r', role: 'coda' },
          { t: 'f', role: 'coda' },
          { t: 's', role: 'appendix' },
          { t: 't', role: 'appendix' },
        ],
        done: { title: 'Niveau uitgespeeld', text: 'h | e r f | s t: een volle rijm van drie plekken en een appendix. Je kunt nu een lettergreep tekenen, wegen en verklaren.' },
      },
    ],
  },
];
