import type { LessonInput } from '../schema';

/**
 * De woordgroep, bachelor p7–p10: de voorzetselgroep (achterzetsels, omzetsels, R-woorden,
 * vaste voorzetsels), complement of bepaling (de doen-test, volgorde, die-vervanging),
 * de bijvoeglijke en bijwoordelijke groep (gradeerwoorden, vergelijking, bijvoeglijk tegenover
 * bijwoordelijk gebruik) en lange bepalingen voor en na (uitgebreide bijvoeglijke bepaling,
 * naamwoordstijl, bijstelling, beperkende en uitbreidende bijzin).
 */
export const GROEP_BOUW_LESSONS: LessonInput[] = [
  {
    id: 'p7',
    stage: 'bachelor',
    domain: 'syn',
    also: ['sem', 'orth'],
    title: 'De voorzetselgroep',
    skill: 'Zinsbouw',
    icon: 'PP',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Een voorzetsel komt nooit alleen',
        panels: [
          {
            text: 'Voorzetsels zijn klein, maar ze gaan nooit alleen de deur uit: ze slepen altijd een groep mee. *Op de tafel*, *met mijn zus*, *na het eten*. Zo’n groep heet een *voorzetselgroep* (Engels: *prepositional phrase*, kort *PP*). Het voorzetsel is de *kern*: het woord dat bepaalt wat voor groep het is. Wat erachter komt, meestal een naamwoordgroep, heet het *complement*: het stuk dat de kern nodig heeft om af te zijn.',
            rule: 'Voorzetselgroep = voorzetsel (kern) + complement, meestal een naamwoordgroep.',
            phrase: {
              q: 'Vind alle drie de voorzetselgroepen',
              sentence: 'Na het eten liep Sara met haar broer naar het station.',
              groups: [
                { span: [0, 2], cat: 'voorzetselgroep', head: 0, note: 'Kern na, complement het eten.' },
                { span: [5, 7], cat: 'voorzetselgroep', head: 5, note: 'Kern met, complement haar broer.' },
                { span: [8, 10], cat: 'voorzetselgroep', head: 8, note: 'Kern naar, complement het station.' },
              ],
              traps: [
                { span: [1, 2], note: 'het eten is een naamwoordgroep: het complement van na, niet de hele voorzetselgroep.' },
                { span: [5, 10], note: 'Dat zijn twee voorzetselgroepen naast elkaar: met haar broer en naar het station.' },
              ],
              note: 'Elke voorzetselgroep begint hier met zijn kern. In de verdieping zie je dat het Nederlands ook anders kan.',
            },
          },
          {
            text: 'Het Nederlands heeft ook *achterzetsels*: het voorzetsel staat dan áchter de naamwoordgroep. *De berg op*, *het bos in*, *de trap af*. Een achterzetsel geeft bijna altijd een *richting* aan, een voorzetsel vaak een *plaats*: *in het bos lopen* (je bent er al) tegenover *het bos in lopen* (je gaat erheen). En er zijn *omzetsels*, met een stuk ervoor en een stuk erachter: *om het huis heen*, *tegen de muur aan*, *naar de stad toe*.',
            lab: {
              label: 'Tik een zin',
              chips: [
                { k: 'Ze liep in het bos.', out: 'plaats', note: 'Ze was al in het bos en wandelde daar rond.' },
                { k: 'Ze liep het bos in.', out: 'richting', note: 'Eerst stond ze erbuiten, daarna ging ze naar binnen.' },
                { k: 'Ze liep om het bos heen.', out: 'route', note: 'Een omzetsel: om … heen. Ze ging er niet in.' },
              ],
            },
            quiz: {
              q: 'Welke zin beschrijft een beweging naar binnen?',
              options: ['Hij fietst de stad in.', 'Hij fietst in de stad.', 'Hij fietst om de stad heen.'],
              answer: 'Hij fietst de stad in.',
              why: 'Het achterzetsel in geeft een richting: van buiten naar binnen. Met in de stad ben je er al.',
            },
          },
          {
            text: 'Verwijst *het*, *dat* of *wat* naar een ding, dan mag het niet na een voorzetsel staan. Je zegt niet *met het*, maar *ermee*. Het voornaamwoord wordt een *R-woord* (*er*, *daar*, *waar*, *hier*) en het voorzetsel komt erachter: *daarover*, *waarmee*, *hierop*. Let op: *met* wordt *mee* en *tot* wordt *toe*. Staan de twee delen naast elkaar, dan schrijf je ze aan elkaar. Maar ze kunnen ook uit elkaar: *Waar denk je aan?* *Daar heb ik niet op gerekend.*',
            rule: 'Bij een ding: niet voorzetsel + het/dat/wat, maar er/daar/waar + voorzetsel.',
            mark: {
              q: 'Tik de twee helften van het gesplitste R-woord',
              sentence: 'Daar had ik eerlijk gezegd nooit op gerekend.',
              targets: [0, 6],
              note: 'daar … op: samen daarop. Tussen de twee helften staat het middenveld van de zin.',
            },
            quiz: {
              q: 'Je praat over een pen. Wat is goed?',
              options: ['Ik schrijf ermee.', 'Ik schrijf met het.', 'Ik schrijf ermet.'],
              answer: 'Ik schrijf ermee.',
              why: 'Het voorzetsel komt achter er, en met wordt daarbij mee.',
            },
          },
          {
            text: 'Sommige werkwoorden en bijvoeglijke naamwoorden kiezen hun eigen voorzetsel. Je *wacht op* de bus, je *denkt aan* je moeder, je *houdt van* jazz, je bent *bang voor* honden. Zo’n voorzetsel heeft zijn gewone betekenis verloren: bij *wachten op* gaat het niet om ‘bovenop’. Je kunt het daarom ook niet vervangen. De hele groep heet in de schoolgrammatica een *voorzetselvoorwerp*.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'wachten', out: 'op', note: 'Ik wacht op de bus. Niet: voor de bus.' },
                { k: 'denken', out: 'aan', note: 'Ik denk aan je. Niet: naar je.' },
                { k: 'houden', out: 'van', note: 'Ik houd van jazz.' },
                { k: 'geïnteresseerd', out: 'in', note: 'Ze is geïnteresseerd in taal. Niet: voor taal.' },
                { k: 'jaloers', out: 'op', note: 'Hij is jaloers op zijn broer.' },
              ],
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'soorten',
        prompt: 'Waar staat het voorzetsel?',
        buckets: ['voor de groep (voorzetsel)', 'achter de groep (achterzetsel)', 'eromheen (omzetsel)'],
        items: [
          { t: 'op de tafel', b: 0 },
          { t: 'de trap af', b: 1 },
          { t: 'om het huis heen', b: 2 },
          { t: 'met de fiets', b: 0 },
          { t: 'het water in', b: 1 },
          { t: 'tegen de muur aan', b: 2 },
          { t: 'de straat over', b: 1 },
          { t: 'naar de stad toe', b: 2 },
          { t: 'zonder suiker', b: 0 },
        ],
        why: 'Voorzetsels staan vooraan. Achterzetsels (af, in, over) staan achter de groep en geven een richting. Omzetsels hebben twee delen: om … heen, tegen … aan, naar … toe.',
      },
      {
        kind: 'choice',
        id: 'vast-voorzetsel',
        prompt: 'Kies het vaste voorzetsel.',
        before: 'Ik ben erg geïnteresseerd',
        after: 'taalkunde.',
        options: ['in', 'voor', 'aan', 'op'],
        answer: 'in',
        why: 'geïnteresseerd in. Geïnteresseerd voor is een veelgemaakte fout, waarschijnlijk onder invloed van interesse voor.',
      },
      {
        kind: 'type',
        id: 'r-woord',
        prompt: 'Typ het R-woord. Het gaat over een sleutel.',
        before: 'Ik heb de deur',
        after: 'opengemaakt.',
        hint: 'er + voorzetsel',
        answer: 'ermee',
        why: 'met de sleutel wordt ermee: er + met, en met wordt mee. Aan elkaar, want de delen staan naast elkaar.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Kern vooraan, en wat er mag achterblijven',
        panels: [
          {
            text: 'Taalkundigen gebruiken *adpositie* als koepelterm voor voorzetsels, achterzetsels en omzetsels. Hans Broekhuis wijdde er een heel deel van *Syntax of Dutch* aan (*Adpositions and Adpositional Phrases*, 2013). Het gewone patroon is *kern-eerst*: de kern staat vóór zijn complement. Dat is opvallend, want het Nederlandse werkwoord doet het in de bijzin omgekeerd: *dat ik [de krant lees]*, met de kern achteraan. Het Nederlands is dus gemengd. Achterzetsels als *de berg op* laten zien dat ook de adpositie soms achteraan kan.',
            rule: 'De gewone voorzetselgroep is kern-eerst: eerst het voorzetsel, dan het complement.',
            bracket: {
              q: 'Bouw de voorzetselgroep van binnen naar buiten',
              words: true,
              tree: '[naar [de [oude stad]]]',
              nodes: [
                { w: 'oude stad', cat: 'N′', note: 'oude bepaalt stad.' },
                { w: 'de oude stad', cat: 'NP', note: 'Het lidwoord maakt de naamwoordgroep af.' },
                { w: 'naar de oude stad', cat: 'PP', note: 'Het voorzetsel neemt de hele naamwoordgroep als complement.' },
              ],
              traps: [{ w: 'naar de', note: 'naar neemt een hele naamwoordgroep als complement, niet alleen het lidwoord.' }],
              note: 'Eerst de naamwoordgroep, dan pas het voorzetsel: het komt er als laatste bij, maar staat vooraan. Kern-eerst.',
            },
          },
          {
            text: 'In het Engels kun je een voorzetsel achterlaten: *Who are you waiting for?* Taalkundigen noemen dat *stranding* (laten stranden). Het Nederlands staat dat alleen toe als het complement een R-woord is: *Waar wacht je op?* is goed, maar (fout) *Wie wacht je op?* niet. Bij een persoon moet de hele groep mee naar voren: *Op wie wacht je?* Henk van Riemsdijk beschreef dit in 1978 in zijn proefschrift *A Case Study in Syntactic Markedness*: het R-woord is de ontsnappingsroute uit de voorzetselgroep.',
            rule: 'Een voorzetsel blijft alleen achter als zijn complement een R-woord is.',
            lab: {
              label: 'Tik een vraag',
              chips: [
                { k: 'Waar wacht je op?', out: 'goed', note: 'Het R-woord waar gaat naar voren, op blijft achter.' },
                { k: 'Op wie wacht je?', out: 'goed', note: 'De hele voorzetselgroep gaat naar voren.' },
                { k: 'Wie wacht je op?', out: 'fout', note: 'wie is geen R-woord, dus op kan niet achterblijven.' },
                { k: 'Waarop wacht je?', out: 'goed', note: 'Het R-woord en het voorzetsel samen vooraan, aan elkaar geschreven.' },
              ],
            },
            quiz: {
              q: 'Welke zin is fout in het standaardnederlands?',
              options: ['Wie denk je aan?', 'Aan wie denk je?', 'Waar denk je aan?'],
              answer: 'Wie denk je aan?',
              why: 'Alleen een R-woord kan het voorzetsel achterlaten. Bij wie moet aan mee naar voren.',
            },
          },
          {
            text: 'Hoe weet je of een voorzetselgroep een *voorzetselvoorwerp* is of een *bepaling van plaats*? Vergelijk *Ik wacht op de bus* met *Ik wacht op het perron*. Vervang de groep door een R-woord of door *daar*. Bij de plaatsbepaling past *daar*: *Ik wacht daar.* Bij het voorzetselvoorwerp moet het voorzetsel mee: *Ik wacht daarop.* Ook kun je bij een plaats het voorzetsel ruilen (*bij het perron*, *naast het perron*); bij het vaste voorzetsel niet.',
            rule: 'Past ‘daar’, dan is het een plaatsbepaling. Moet het ‘daarop’ of ‘daaraan’ worden, dan is het een voorzetselvoorwerp.',
            quiz: {
              q: 'In welke zin is de voorzetselgroep een voorzetselvoorwerp?',
              options: ['Hij denkt aan zijn moeder.', 'Hij staat aan de kant.', 'Hij zit aan tafel.'],
              answer: 'Hij denkt aan zijn moeder.',
              why: 'Hij denkt daaraan: aan is vast bij denken. Bij aan de kant en aan tafel gaat het om een plek.',
            },
          },
        ],
      },
      {
        kind: 'ambiguity',
        id: 'rekenen',
        prompt: 'Eén zin, twee betekenissen',
        intro: 'Kies een betekenis en zoek de zin die alleen dát kan betekenen.',
        sentence: 'Ze rekent op de bank.',
        meanings: [
          {
            id: 'vast',
            label: 'Ze vertrouwt op de bank (voorzetselvoorwerp)',
            highlight: ['rekent op'],
            right: 'Klopt. rekenen op is hier een vaste combinatie: ze rekent erop dat de bank helpt.',
          },
          {
            id: 'plaats',
            label: 'Ze maakt sommen op de bank (plaatsbepaling)',
            highlight: ['op de bank'],
            right: 'Klopt. Hier is op de bank gewoon een plek: ze rekent daar.',
          },
        ],
        options: [
          { t: 'Ze rekent erop dat de bank haar helpt.', fits: 'vast' },
          { t: 'Ze zit op de bank en maakt daar haar sommen.', fits: 'plaats' },
          { t: 'Ze rekent vandaag op de bank.', fits: null, note: 'Nog steeds allebei mogelijk: alleen een tijd erbij.' },
        ],
        done: {
          title: 'Twee analyses',
          text: 'Dezelfde woorden, twee structuren: een voorzetselvoorwerp of een bepaling van plaats. De daar-test haalt ze uit elkaar.',
        },
      },
      {
        kind: 'sort',
        id: 'daar-test',
        prompt: 'Voorzetselvoorwerp of bepaling van plaats?',
        buckets: ['voorzetselvoorwerp (vast voorzetsel)', 'bepaling van plaats'],
        items: [
          { t: 'Ik wacht op de bus.', b: 0 },
          { t: 'Ik wacht op het perron.', b: 1 },
          { t: 'Ze denkt aan haar oma.', b: 0 },
          { t: 'Ze woont aan de kust.', b: 1 },
          { t: 'Hij houdt van jazz.', b: 0 },
          { t: 'Hij slaapt in de tent.', b: 1 },
          { t: 'Wij zorgen voor de kat.', b: 0 },
          { t: 'Wij staan voor het huis.', b: 1 },
          { t: 'Ze lijkt op haar vader.', b: 0 },
          { t: 'Ze zit op haar fiets.', b: 1 },
        ],
        why: 'Ik wacht daarop, ze denkt daaraan, hij houdt daarvan: vaste voorzetsels. Ik wacht daar, ze woont daar, hij slaapt daar: plaatsen.',
      },
      {
        kind: 'proofread',
        id: 'voorzetsels',
        prompt: 'Lees het bericht na',
        intro: 'Er staan vier verkeerde vaste voorzetsels in. Tik ze aan.',
        tokens: [
          { t: 'Ik' },
          { t: 'wacht' },
          { t: 'al' },
          { t: 'maanden' },
          { t: 'voor', fix: 'op', why: 'wachten op.' },
          { t: 'een' },
          { t: 'goede' },
          { t: 'camera.' },
          { t: 'Ik' },
          { t: 'ben' },
          { t: 'vooral' },
          { t: 'geïnteresseerd' },
          { t: 'voor', fix: 'in', why: 'geïnteresseerd in.' },
          { t: 'natuurfotografie.' },
          { t: 'Mijn' },
          { t: 'zus' },
          { t: 'is' },
          { t: 'jaloers' },
          { t: 'over', fix: 'op', why: 'jaloers op.' },
          { t: 'mijn' },
          { t: 'nieuwe' },
          { t: 'camera,' },
          { t: 'maar' },
          { t: 'ik' },
          { t: 'ben' },
          { t: 'trots' },
          { t: 'aan', fix: 'op', why: 'trots op.' },
          { t: 'mijn' },
          { t: 'werk.' },
        ],
        done: { title: 'Vaste voorzetsels', text: 'Een vast voorzetsel leer je samen met zijn werkwoord of bijvoeglijk naamwoord, als één woordenboekregel.' },
      },
      {
        kind: 'rewrite',
        id: 'blij-mee',
        prompt: 'Herschrijf in verzorgde schrijftaal: gebruik een R-woord.',
        source: 'Ik heb een nieuwe fiets en ik ben heel blij met het.',
        accept: [
          'Ik heb een nieuwe fiets en ik ben er heel blij mee.',
          'Ik heb een nieuwe fiets en ik ben daar heel blij mee.',
          'Ik heb een nieuwe fiets en daar ben ik heel blij mee.',
          'Ik heb een nieuwe fiets en ik ben daarmee heel blij.',
        ],
        why: 'met het over een ding wordt ermee of daarmee. Het R-woord staat vaak vroeg in het middenveld en mee blijft bij blij: er … blij mee.',
      },
    ],
  },
  {
    id: 'p8',
    stage: 'bachelor',
    domain: 'syn',
    also: ['sem'],
    title: 'Complement of bepaling',
    skill: 'Zinsbouw',
    icon: 'C/B',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Wat de kern nodig heeft, en wat er los bij komt',
        panels: [
          {
            text: 'Sommige woorden komen nooit alleen naar een feestje. *Geven* neemt altijd iemand mee die iets krijgt; *slapen* kan prima alleen. Wat een kern nodig heeft om af te zijn, heet een *complement* (ook: *argument*). Wat er vrij bij komt, als extra informatie, heet een *bepaling* (Engels: *adjunct*). Ook in de naamwoordgroep: in *de student natuurkunde met lang haar* zegt *natuurkunde* wát hij studeert (complement), en *met lang haar* is extra (bepaling).',
            rule: 'Complement: wat de kern nodig heeft. Bepaling: wat er vrij bij komt.',
            phrase: {
              q: 'Vind de hele groep rond student, het complement en de bepaling',
              sentence: 'De student natuurkunde met het lange haar zat in de zaal.',
              groups: [
                { span: [0, 6], cat: 'naamwoordgroep', head: 1, note: 'De hele groep, met kern student.' },
                { span: [2, 2], cat: 'naamwoordgroep (complement)', head: 2, note: 'natuurkunde zegt wat de student studeert: een complement van één woord.' },
                { span: [3, 6], cat: 'voorzetselgroep (bepaling)', head: 3, note: 'met het lange haar is extra informatie: een bepaling.' },
              ],
              traps: [{ span: [2, 3], note: 'natuurkunde met loopt over de grens tussen complement en bepaling.' }],
              note: 'Het complement staat direct naast de kern; de bepaling komt daarna.',
            },
          },
          {
            text: 'Dat is geen toeval. Een complement staat het dichtst bij zijn kern; bepalingen komen verder weg. Daarom klinkt *de student van natuurkunde met lang haar* gewoon, maar *de student met lang haar van natuurkunde* raar: dan lijkt het alsof het haar van natuurkunde is.',
            swap: {
              goal: 'Zet de groep in de natuurlijke volgorde',
              blocks: ['met lang haar', 'de student', 'van natuurkunde'],
              accept: ['de student van natuurkunde met lang haar'],
              note: 'Kern, dan complement, dan bepaling.',
            },
          },
          {
            text: 'In de werkwoordgroep werkt het net zo. In *Ik las het boek in de tuin* is *het boek* een complement van *las* en *in de tuin* een bepaling. Bepalingen kun je stapelen: *in de tuin, gisteren, met plezier*. Een complement niet: (fout) *Ik las het boek de krant*. En pas op: ook een voorzetselgroep kan een complement zijn. *Sanne zette de vaas* is niet af; *zetten* heeft een plek nodig.',
            quiz: {
              q: 'Wat is een bepaling in: Sanne zette de vaas op de tafel?',
              options: ['op de tafel', 'de vaas', 'geen van beide: het zijn allebei complementen'],
              answer: 'geen van beide: het zijn allebei complementen',
              why: 'zetten vraagt om iets én een plek. Zonder op de tafel is de zin niet af. Een voorzetselgroep is dus niet automatisch een bepaling.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'complement-bepaling',
        prompt: 'Is het eerste stuk een complement of een bepaling in de groep erachter?',
        buckets: ['complement', 'bepaling'],
        items: [
          { t: 'natuurkunde · de student natuurkunde', b: 0 },
          { t: 'met lang haar · de student met lang haar', b: 1 },
          { t: 'van de stad · de verwoesting van de stad', b: 0 },
          { t: 'na de oorlog · de verwoesting na de oorlog', b: 1 },
          { t: 'het boek · Ik las het boek.', b: 0 },
          { t: 'in de tuin · Ik las in de tuin.', b: 1 },
          { t: 'op zijn moeder · Hij wacht op zijn moeder.', b: 0 },
          { t: 'om vier uur · Hij wacht om vier uur.', b: 1 },
          { t: 'in Utrecht · Zij woont in Utrecht.', b: 0 },
        ],
        why: 'Complementen vult de kern zelf in: wat je studeert, wat er verwoest wordt, wat je leest, op wie je wacht, waar je woont. Bepalingen voegen tijd, plaats of kenmerken toe die bij bijna elke kern passen.',
      },
      {
        kind: 'choice',
        id: 'leraar-frans',
        prompt: 'Welke volgorde klinkt natuurlijk?',
        before: '',
        after: '',
        options: ['de leraar Frans uit Lyon', 'de leraar uit Lyon Frans', 'Frans de leraar uit Lyon', 'de uit Lyon leraar Frans'],
        answer: 'de leraar Frans uit Lyon',
        why: 'Frans is het complement van leraar (wat hij onderwijst) en staat dus direct naast de kern. uit Lyon is een bepaling en komt daarna.',
      },
      {
        kind: 'bet',
        id: 'wonen',
        prompt: 'Is ‘in Utrecht’ in ‘Zij woont in Utrecht’ een bepaling van plaats?',
        options: ['Nee, een complement: wonen heeft een plek nodig', 'Ja, het zegt waar iets gebeurt'],
        answer: 'Nee, een complement: wonen heeft een plek nodig',
        why: 'Zij woont. klinkt niet af (behalve met iets als zo of daar). wonen kiest een plek, net als zetten.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Testen voor het verschil',
        panels: [
          {
            text: 'Een betrouwbare test is de *doen-test*, het Nederlandse broertje van de Engelse *do so*-test. Je vervangt het werkwoord met zijn complementen door *deed dat*. Een bepaling mag erbuiten blijven: *Ik las het boek in de tuin en zij deed dat in de keuken.* Een complement niet: (fout) *Ik las het boek en zij deed dat de krant.* Wat na *deed dat* kan staan, is dus een bepaling.',
            rule: 'Kan het na ‘deed dat’ staan, dan is het een bepaling. Kan dat niet, dan zit het in de werkwoordgroep: een complement.',
            lab: {
              label: 'Ik las het boek in de tuin en zij deed dat …',
              chips: [
                { k: 'in de keuken', out: 'goed · bepaling', note: 'De plaats valt buiten deed dat.' },
                { k: 'vanavond', out: 'goed · bepaling', note: 'Een tijdsbepaling kan altijd los.' },
                { k: 'de krant', out: 'fout · complement', note: 'het boek zat al in deed dat; een tweede lijdend voorwerp kan niet los.' },
                { k: 'met plezier', out: 'goed · bepaling', note: 'Een bepaling van wijze.' },
              ],
            },
            quiz: {
              q: 'Hij dacht aan zijn moeder en zij deed dat aan haar vader. Wat zegt dat?',
              options: ['aan zijn moeder is een complement: de zin klinkt fout', 'aan zijn moeder is een bepaling: de zin klinkt goed'],
              answer: 'aan zijn moeder is een complement: de zin klinkt fout',
              why: 'Het vaste voorzetsel aan hoort bij denken. Je kunt het niet buiten deed dat houden.',
            },
          },
          {
            text: 'In de naamwoordgroep werkt *die* als test. In de X-bar-theorie van Ray Jackendoff (*X-bar Syntax*, 1977) is dat de bekende *one*-test van het Engels: *one* vervangt een kern mét zijn complement, maar zonder zijn bepalingen. In het Nederlands: *de student natuurkunde met lang haar en die met kort haar* is goed; *die* staat voor *de student natuurkunde*. Maar (fout) *de student natuurkunde en die scheikunde*: een kaal complement kan niet zonder zijn kern. In de boom zie je waarom: het complement hangt eerst aan de kern, de bepaling pas daarna.',
            bracket: {
              q: 'Bouw de groep: eerst het complement, dan de bepaling',
              words: true,
              tree: '[de [[student natuurkunde] [met [lang haar]]]]',
              nodes: [
                { w: 'student natuurkunde', cat: 'N′', note: 'Kern + complement: het eerste, binnenste stuk.' },
                { w: 'lang haar', cat: 'NP', note: 'lang bepaalt haar.' },
                { w: 'met lang haar', cat: 'PP', note: 'De voorzetselgroep die als bepaling dient.' },
                { w: 'student natuurkunde met lang haar', cat: 'N′', note: 'De bepaling hangt aan kern + complement samen.' },
                { w: 'de student natuurkunde met lang haar', cat: 'NP', note: 'Het lidwoord maakt de groep af.' },
              ],
              traps: [
                { w: 'natuurkunde met', note: 'natuurkunde hoort bij student, met bij lang haar.' },
                { w: 'de student', note: 'de hoort bij de hele groep, inclusief complement en bepaling.' },
              ],
              note: 'Jackendoff noemde het tussenniveau N′ (N-bar). Complementen zijn zus van N, bepalingen zus van N′.',
            },
          },
          {
            text: 'Werkwoorden geven hun complementen door aan zelfstandige naamwoorden die ervan gemaakt zijn. *De vijand verwoestte de stad* wordt *de verwoesting van de stad*: het lijdend voorwerp van het werkwoord wordt een *van*-groep, en die staat weer direct naast de kern. *In 1940* blijft een bepaling, in de zin én in de groep: *de verwoesting van de stad in 1940*.',
            quiz: {
              q: 'Wat is het complement in: de verwoesting van de stad in 1940?',
              options: ['van de stad', 'in 1940', 'allebei'],
              answer: 'van de stad',
              why: 'van de stad is wat er verwoest wordt, geërfd van het werkwoord verwoesten. in 1940 is een tijdsbepaling.',
            },
            deep: {
              q: 'Werkt de doen-test dan ook in de naamwoordgroep?',
              a: 'Niet letterlijk, want daar is geen werkwoord. Daarvoor dient *die*. De tests hebben wel dezelfde logica: de vervanger neemt kern + complement mee, en alleen een bepaling mag erachter blijven staan. In de les over X-bar-theorie zie je dat dit één algemeen bouwplan is.',
            },
          },
        ],
      },
      {
        kind: 'order',
        id: 'volgorde',
        prompt: 'Zet de naamwoordgroep in de natuurlijke volgorde.',
        tiles: ['met de bril', 'de leraar', 'Frans'],
        answer: 'de leraar Frans met de bril',
        why: 'Eerst kern + complement (de leraar Frans), dan de bepaling (met de bril).',
      },
      {
        kind: 'rewrite',
        id: 'rode-jas',
        prompt: 'Zet het complement weer naast zijn kern.',
        source: 'Ik ontmoette gisteren een student met een rode jas geneeskunde.',
        accept: ['Ik ontmoette gisteren een student geneeskunde met een rode jas.'],
        why: 'geneeskunde is het complement van student en hoort er direct naast. met een rode jas is een bepaling.',
      },
      {
        kind: 'choice',
        id: 'die-test',
        prompt: 'Welke zin is goed?',
        before: '',
        after: '',
        options: [
          'de student natuurkunde met lang haar en die met kort haar',
          'de student natuurkunde met lang haar en die scheikunde',
          'de student met lang haar natuurkunde en die scheikunde',
        ],
        answer: 'de student natuurkunde met lang haar en die met kort haar',
        why: 'die vervangt kern + complement (de student natuurkunde). Alleen een bepaling, zoals met kort haar, kan erachter staan.',
      },
      {
        kind: 'swipe',
        id: 'tests-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Een complement staat dichter bij de kern dan een bepaling.', ok: true, why: 'de student natuurkunde met lang haar.' },
          {
            t: 'Een voorzetselgroep is altijd een bepaling.',
            ok: false,
            fix: 'kan ook een complement zijn',
            why: 'zette de vaas op de tafel, wacht op de bus.',
          },
          { t: 'Bepalingen kun je stapelen.', ok: true, why: 'in de tuin, gisteren, met plezier.' },
          {
            t: 'Wat na ‘deed dat’ kan staan, is een complement.',
            ok: false,
            fix: 'is een bepaling',
            why: 'De doen-test laat alleen bepalingen buiten deed dat.',
          },
          { t: 'In de verwoesting van de stad is van de stad een complement.', ok: true, why: 'Geërfd van verwoesten: wat verwoest wordt.' },
          {
            t: 'die in een naamwoordgroep vervangt alleen de kern, zonder complement.',
            ok: false,
            fix: 'kern en complement samen',
            why: 'Daarom kan die scheikunde niet.',
          },
        ],
      },
    ],
  },
  {
    id: 'p9',
    stage: 'bachelor',
    domain: 'syn',
    also: ['sem', 'morf'],
    title: 'De bijvoeglijke groep',
    skill: 'Zinsbouw',
    icon: 'AP',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Bijvoeglijke naamwoorden met gevolg',
        panels: [
          {
            text: 'Trots zijn mag. Maar wáárop? Een bijvoeglijk naamwoord kan, net als een werkwoord, een complement meenemen: *trots op zijn dochter*, *bang voor honden*, *gek op chocola*. Samen met gradeerwoorden als *erg* en *heel* vormt het een *bijvoeglijke groep* (Engels: *adjective phrase*, *AP*). De kern is het bijvoeglijk naamwoord.',
            rule: 'Bijvoeglijke groep = bijvoeglijk naamwoord (kern) + eventueel complement en gradeerwoorden.',
            phrase: {
              q: 'Vind de twee bijvoeglijke groepen',
              sentence: 'Mijn buurvrouw is erg trots op haar zoon en een beetje bang voor zijn motor.',
              groups: [
                { span: [3, 7], cat: 'bijvoeglijke groep', head: 4, note: 'Kern trots, met gradeerwoord erg en complement op haar zoon.' },
                { span: [9, 14], cat: 'bijvoeglijke groep', head: 11, note: 'Kern bang, met een beetje ervoor en voor zijn motor als complement.' },
              ],
              traps: [
                { span: [3, 4], note: 'erg trots is niet af: op haar zoon hoort als complement bij trots.' },
                { span: [9, 10], note: 'een beetje is alleen het gradeerwoord; de kern bang hoort erbij.' },
              ],
              note: 'Elke groep heeft een bijvoeglijk naamwoord als kern, met een vast voorzetsel erachter.',
            },
          },
          {
            text: 'Gradeerwoorden zeggen hoe sterk de eigenschap is: *heel*, *erg*, *zeer*, *een beetje*, *te*, *zo*. Sommige hebben een partner verderop: *te moe om te fietsen*, *zo moe dat ik in slaap viel*. En let op *heel*: in *een heel mooie fiets* bepaalt *heel* het woord *mooie*, niet *fiets*. Het is dan een bijwoord en krijgt geen *-e*. *Een hele mooie fiets* hoor je veel, maar het is spreektaal.',
            rule: 'heel bij een bijvoeglijk naamwoord blijft heel: een heel mooie fiets.',
            quiz: {
              q: 'Wat is de norm in verzorgde schrijftaal?',
              options: ['een heel mooie fiets', 'een hele mooie fiets'],
              answer: 'een heel mooie fiets',
              why: 'heel bepaalt mooie en is dan een bijwoord: geen buigings-e. Een hele fiets betekent een fiets die niet kapot is.',
            },
          },
          {
            text: 'Hetzelfde woord kan op drie plekken staan. *Attributief*: vóór het zelfstandig naamwoord, met buigings-e (*de snelle auto*). *Predicatief*: na *zijn*, *worden*, *blijven* (*de auto is snel*). En *bijwoordelijk*: bij het werkwoord (*hij rijdt snel*). Dan buigt het nooit. Een groep met een echt bijwoord als kern, zoals *heel erg vaak*, heet een *bijwoordgroep*.',
            mark: {
              q: 'Tik de bijvoeglijke naamwoorden die bijwoordelijk gebruikt worden',
              sentence: 'Ze zong mooi en danste licht in haar mooie, lichte jurk.',
              targets: [2, 5],
              note: 'mooi en licht zeggen iets over zingen en dansen: geen -e. mooie en lichte staan bij jurk: attributief.',
            },
          },
        ],
      },
      {
        kind: 'choice',
        id: 'trots-op',
        prompt: 'Kies het vaste voorzetsel.',
        before: 'Ze is',
        after: 'haar examenresultaat.',
        options: ['trots op', 'trots aan', 'trots van', 'trots over'],
        answer: 'trots op',
        why: 'trots kiest op, net zoals bang voor kiest en gek op.',
      },
      {
        kind: 'sort',
        id: 'drie-plekken',
        prompt: 'Hoe wordt het bijvoeglijk naamwoord gebruikt?',
        buckets: ['attributief: bij het zelfstandig naamwoord', 'predicatief: na zijn, worden, blijven', 'bijwoordelijk: bij het werkwoord'],
        items: [
          { t: 'snelle · een snelle auto', b: 0 },
          { t: 'snel · de auto is snel', b: 1 },
          { t: 'snel · hij rijdt snel', b: 2 },
          { t: 'mooie · het mooie huis', b: 0 },
          { t: 'mooi · het huis wordt mooi', b: 1 },
          { t: 'mooi · ze zingt mooi', b: 2 },
          { t: 'koude · koude soep', b: 0 },
          { t: 'koud · de soep blijft koud', b: 1 },
          { t: 'hard · hij werkt hard', b: 2 },
        ],
        why: 'Attributief staat het voor het zelfstandig naamwoord en buigt het meestal. Predicatief en bijwoordelijk buigt het niet; bijwoordelijk zegt het iets over de handeling.',
      },
      {
        kind: 'fix',
        id: 'heel-mooi',
        prompt: 'Verbeter het woord dat niet past in verzorgde schrijftaal.',
        sentence: 'Het was een hele mooie voorstelling.',
        wrong: 3,
        answer: 'heel',
        why: 'heel bepaalt mooie, niet voorstelling. Als bijwoord krijgt het geen -e.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Voor het zelfstandig naamwoord gelden andere regels',
        panels: [
          {
            text: 'Predicatief staat het complement achter de kern: *de vader is trots op zijn dochter*. Maar vóór het zelfstandig naamwoord moet de bijvoeglijke groep eindigen op zijn kern: *de op zijn dochter trotse vader*, en niet (fout) *de trotse op zijn dochter vader*. Edwin Williams beschreef dat in 1982 voor het Engels als het *Head-Final Filter*: een bepaling vóór het zelfstandig naamwoord moet met haar kern eindigen. Het Engels lost het op door de groep achter het naamwoord te zetten (*a father proud of his daughter*); het Nederlands schuift het complement naar voren.',
            rule: 'Vóór het zelfstandig naamwoord eindigt een bijvoeglijke groep op haar kern.',
            bracket: {
              q: 'Bouw de groep van binnen naar buiten',
              words: true,
              tree: '[de [[[op [zijn dochter]] trotse] vader]]',
              nodes: [
                { w: 'zijn dochter', cat: 'NP', note: 'Het complement van op.' },
                { w: 'op zijn dochter', cat: 'PP', note: 'Het complement van trotse.' },
                { w: 'op zijn dochter trotse', cat: 'AP', note: 'De bijvoeglijke groep eindigt op haar kern trotse.' },
                { w: 'op zijn dochter trotse vader', cat: 'N′', note: 'De hele bijvoeglijke groep bepaalt vader.' },
                { w: 'de op zijn dochter trotse vader', cat: 'NP', note: 'Het lidwoord maakt de groep af.' },
              ],
              traps: [{ w: 'trotse vader', note: 'Eerst moet de bijvoeglijke groep af zijn: op zijn dochter hoort bij trotse, niet bij vader.' }],
              note: 'Het lidwoord de en het naamwoord vader staan ver uit elkaar: dat maakt zulke groepen zwaar om te lezen.',
            },
          },
          {
            text: 'Vergelijken doe je met een complement achter de vergrotende trap: *groter dan zijn broer*. Na *even* en *zo* komt *als*: *even groot als zijn broer*. *Groter als* is spreektaal en geldt in verzorgde taal als fout. Gradeerwoorden met een partner zijn bijzonder: *te* en *om te* horen bij elkaar, maar vóór een naamwoord kan de *om*-zin niet blijven staan. Je zegt *een te zware tas om te dragen*, nooit (fout) *een te zware om te dragen tas*.',
            quiz: {
              q: 'Welke zin is verzorgde standaardtaal?',
              options: ['Hij is groter dan zijn broer.', 'Hij is groter als zijn broer.', 'Hij is even groot dan zijn broer.'],
              answer: 'Hij is groter dan zijn broer.',
              why: 'Vergrotende trap + dan; even of zo + als.',
            },
            deep: {
              q: 'Waarom komt om te dragen achter tas?',
              a: 'Dezelfde eis als bij *de op zijn dochter trotse vader*: vóór het naamwoord moet de bijvoeglijke groep op haar kern eindigen. Een *om*-zin kan niet vóór de kern *zware* schuiven, dus verhuist hij naar het eind van de hele naamwoordgroep. Zo staan *te* en *om te dragen* ver uit elkaar, terwijl ze bij elkaar horen.',
            },
          },
          {
            text: 'Een *bijwoordgroep* heeft een bijwoord als kern: *heel erg vaak*, *bijna nooit*, *helemaal daarboven*. Ook daar kunnen gradeerwoorden zich opstapelen. Een bijwoordgroep bepaalt meestal een werkwoord, een bijvoeglijk naamwoord, een ander bijwoord of de hele zin; als nabepaling soms ook een naamwoord (*de man daar*).',
            phrase: {
              q: 'Vind de twee bijwoordgroepen',
              sentence: 'Hij belt zijn moeder heel erg vaak, maar zijn vader bijna nooit.',
              groups: [
                { span: [4, 6], cat: 'bijwoordgroep', head: 6, note: 'Kern vaak, met heel erg ervoor.' },
                { span: [10, 11], cat: 'bijwoordgroep', head: 11, note: 'Kern nooit, met bijna ervoor.' },
              ],
              traps: [{ span: [3, 6], note: 'moeder hoort bij zijn moeder; de bijwoordgroep begint pas bij heel.' }],
              note: 'In beide groepen staat de kern achteraan en de gradeerwoorden ervoor.',
            },
          },
        ],
      },
      {
        kind: 'rewrite',
        id: 'trotse-vader',
        prompt: 'Zet de bijvoeglijke groep vóór het zelfstandig naamwoord.',
        source: 'de vader die trots is op zijn dochter',
        accept: ['de op zijn dochter trotse vader'],
        why: 'Het complement op zijn dochter schuift vóór de kern trotse, zodat de groep op haar kern eindigt.',
      },
      {
        kind: 'order',
        id: 'zware-tas',
        prompt: 'Maak een goede naamwoordgroep.',
        tiles: ['om te dragen', 'tas', 'een', 'te zware'],
        answer: 'een te zware tas om te dragen',
        why: 'De om-zin kan niet vóór het naamwoord staan en gaat naar het eind.',
      },
      {
        kind: 'type',
        id: 'zo-dat',
        prompt: 'Typ het woord dat bij zo hoort.',
        before: 'Ze was zo moe',
        after: 'ze meteen in slaap viel.',
        hint: 'voegwoord',
        answer: 'dat',
        why: 'zo … dat hoort bij elkaar, net als te … om te.',
      },
      {
        kind: 'choice',
        id: 'even-als',
        prompt: 'Kies het goede woord.',
        before: 'Mijn zus is even groot',
        after: 'ik.',
        options: ['als', 'dan', 'of'],
        answer: 'als',
        why: 'even en zo nemen als. dan hoort bij de vergrotende trap: groter dan.',
      },
      {
        kind: 'swipe',
        id: 'ap-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'de trotse op zijn dochter vader', ok: false, fix: 'de op zijn dochter trotse vader', why: 'Vóór het naamwoord eindigt de groep op haar kern.' },
          { t: 'een te zware tas om te dragen', ok: true, why: 'De om-zin staat achter het naamwoord.' },
          { t: 'Hij is groter als ik.', ok: false, fix: 'groter dan ik', why: 'Vergrotende trap + dan.' },
          { t: 'een heel mooie fiets', ok: true, why: 'heel als bijwoord: geen -e.' },
          { t: 'In ‘hij rijdt snel’ is snel bijwoordelijk gebruikt.', ok: true, why: 'Het zegt iets over rijden.' },
          {
            t: 'Een bijwoordelijk gebruikt bijvoeglijk naamwoord krijgt een -e.',
            ok: false,
            fix: 'krijgt nooit een -e',
            why: 'Hij rijdt snel, niet snelle.',
          },
        ],
      },
    ],
  },
  {
    id: 'p10',
    stage: 'bachelor',
    domain: 'syn',
    also: ['tekst', 'prag'],
    title: 'Lange bepalingen voor en na',
    skill: 'Zinsbouw',
    icon: '…N…',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Treinen van woorden',
        panels: [
          {
            text: 'Sommige ambtelijke teksten bouwen naamwoordgroepen als goederentreinen: de locomotief komt pas na vijf wagons. *De door de minister vorige week aangekondigde maatregelen.* De kern is *maatregelen*. Ervoor staat een *uitgebreide bijvoeglijke bepaling*: een deelwoord (*aangekondigde*) met eigen bepalingen erbij (*door de minister*, *vorige week*). Samen vormen ze een bijvoeglijke groep die vóór het zelfstandig naamwoord staat.',
            rule: 'Uitgebreide bijvoeglijke bepaling: een deelwoord of bijvoeglijk naamwoord met eigen bepalingen, vóór het zelfstandig naamwoord.',
            phrase: {
              q: 'Vind de hele naamwoordgroep, de bijvoeglijke groep erin en de voorzetselgroep daarbinnen',
              sentence: 'De door de minister vorige week aangekondigde maatregelen gaan morgen in.',
              groups: [
                { span: [0, 7], cat: 'naamwoordgroep', head: 7, note: 'Kern maatregelen: pas het achtste woord.' },
                { span: [1, 6], cat: 'bijvoeglijke groep', head: 6, note: 'Kern aangekondigde, met door de minister en vorige week ervoor.' },
                { span: [1, 3], cat: 'voorzetselgroep', head: 1, note: 'door de minister: wie de maatregelen aankondigde.' },
              ],
              traps: [{ span: [0, 3], note: 'De hoort bij maatregelen, niet bij door de minister.' }],
              note: 'De lezer ziet het lidwoord De en moet zes woorden wachten op het naamwoord waar het bij hoort.',
            },
          },
          {
            text: 'Zo’n groep is compact, maar zwaar om te lezen. Je kunt hem bijna altijd herschrijven met een *betrekkelijke bijzin*: *de maatregelen die de minister vorige week heeft aangekondigd*. Nu komt de kern eerst en volgen de details. Het deelwoord wordt weer een gewoon werkwoord.',
            swap: {
              goal: 'Zet de kern vooraan en de details erachter',
              blocks: ['die de minister vorige week heeft aangekondigd', 'de maatregelen'],
              accept: ['de maatregelen die de minister vorige week heeft aangekondigd'],
              note: 'Eerst weet de lezer waar het over gaat, dan pas hoe het zit.',
            },
            quiz: {
              q: 'Waarom leest de versie met de bijzin makkelijker?',
              options: ['De lezer kent de kern al voordat de details komen', 'De groep wordt korter', 'Een bijzin heeft geen werkwoord'],
              answer: 'De lezer kent de kern al voordat de details komen',
              why: 'De bijzinversie is zelfs langer, maar de lezer hoeft niets vast te houden zonder te weten waar het bij hoort.',
            },
          },
          {
            text: 'Familie van de lange voorbepaling is de *naamwoordstijl*: werkwoorden die verstopt zijn in zelfstandige naamwoorden. *Na ontvangst van uw betaling* in plaats van *als wij uw betaling hebben ontvangen*. *Het nemen van een besluit* in plaats van *besluiten*. Zulke zinnen worden abstract: je ziet niet meer wie wat doet. Taaladviseurs raden daarom aan de werkwoorden terug te halen.',
            rule: 'Naamwoordstijl: werkwoorden verstopt in zelfstandige naamwoorden. Haal het werkwoord terug, dan zie je weer wie wat doet.',
            lab: {
              label: 'Tik een stuk naamwoordstijl',
              chips: [
                { k: 'na ontvangst van uw betaling', out: 'als wij uw betaling hebben ontvangen', note: 'Nu staat er wie ontvangt: wij.' },
                { k: 'ter verbetering van de leesbaarheid', out: 'om de tekst beter leesbaar te maken', note: 'Het werkwoord maken komt terug.' },
                { k: 'het nemen van een besluit', out: 'besluiten', note: 'Vier woorden worden er één.' },
                { k: 'tot uitvoering brengen', out: 'uitvoeren', note: 'Een werkwoord in vermomming.' },
              ],
            },
          },
        ],
      },
      {
        kind: 'rewrite',
        id: 'brug',
        prompt: 'Herschrijf met een betrekkelijke bijzin, zodat de kern vooraan staat.',
        source: 'De door de gemeente in 2023 gebouwde brug is al kapot.',
        accept: [
          'De brug die de gemeente in 2023 heeft gebouwd, is al kapot.',
          'De brug die de gemeente in 2023 heeft gebouwd is al kapot.',
          'De brug die de gemeente in 2023 gebouwd heeft, is al kapot.',
          'De brug die de gemeente in 2023 gebouwd heeft is al kapot.',
          'De brug die de gemeente in 2023 bouwde, is al kapot.',
          'De brug die de gemeente in 2023 bouwde is al kapot.',
          'De brug die in 2023 door de gemeente is gebouwd, is al kapot.',
          'De brug die in 2023 door de gemeente is gebouwd is al kapot.',
          'De brug die door de gemeente in 2023 is gebouwd, is al kapot.',
          'De brug die door de gemeente in 2023 is gebouwd is al kapot.',
          'De brug die in 2023 door de gemeente gebouwd is, is al kapot.',
          'De brug die door de gemeente in 2023 gebouwd is, is al kapot.',
        ],
        why: 'Kern brug vooraan, dan de bijzin. Een komma tussen de twee werkwoorden (gebouwd, is) helpt de lezer.',
      },
      {
        kind: 'sort',
        id: 'stijl',
        prompt: 'Naamwoordstijl of werkwoordstijl?',
        buckets: ['naamwoordstijl', 'werkwoordstijl'],
        items: [
          { t: 'na ontvangst van uw aanvraag', b: 0 },
          { t: 'als we uw aanvraag hebben ontvangen', b: 1 },
          { t: 'het doen van onderzoek naar', b: 0 },
          { t: 'onderzoeken', b: 1 },
          { t: 'ter bespreking van het plan', b: 0 },
          { t: 'om het plan te bespreken', b: 1 },
          { t: 'de verhoging van de huur vindt plaats per 1 juli', b: 0 },
          { t: 'de huur gaat op 1 juli omhoog', b: 1 },
        ],
        why: 'Naamwoordstijl verpakt de handeling in een zelfstandig naamwoord (ontvangst, het doen, bespreking, verhoging). Werkwoordstijl noemt de handeling met een werkwoord.',
      },
      {
        kind: 'choice',
        id: 'leesbaar',
        prompt: 'Welke versie is het makkelijkst te lezen?',
        before: '',
        after: '',
        options: [
          'De school die vorig jaar is verbouwd, krijgt een nieuwe directeur.',
          'De vorig jaar verbouwde school krijgt een nieuwe directeur.',
          'De na een verbouwing vorig jaar vernieuwde school krijgt een nieuwe directeur.',
        ],
        answer: 'De school die vorig jaar is verbouwd, krijgt een nieuwe directeur.',
        why: 'De kern school staat vooraan. De korte voorbepaling vorig jaar verbouwde kan ook, maar de lange derde versie is een goederentrein.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Waarom het zwaar is, en wat komma’s doen',
        panels: [
          {
            text: 'Waarom leest een lange voorbepaling zwaar? Een lezer verwerkt de zin woord voor woord. Na *De* weet hij: er komt een naamwoord. Tot dat naamwoord er is, moet hij alles wat ertussen staat vasthouden in zijn werkgeheugen, zonder te weten waar het bij hoort. Het Duits gebruikt zulke groepen veel vaker (het *erweitertes Attribut*), vooral in ambtelijke en wetenschappelijke taal. In het Nederlands klinken ze al snel stijf.',
            bracket: {
              q: 'Bouw de groep van binnen naar buiten',
              words: true,
              tree: '[de [[[vorige week] aangekondigde] maatregelen]]',
              nodes: [
                { w: 'vorige week', cat: 'NP', note: 'Een tijdsbepaling, zelf een naamwoordgroep.' },
                { w: 'vorige week aangekondigde', cat: 'AP', note: 'Het deelwoord aangekondigde is de kern; vorige week bepaalt het.' },
                { w: 'vorige week aangekondigde maatregelen', cat: 'N′', note: 'De bijvoeglijke groep bepaalt maatregelen.' },
                { w: 'de vorige week aangekondigde maatregelen', cat: 'NP', note: 'Pas helemaal aan het eind sluit de groep.' },
              ],
              traps: [
                { w: 'week aangekondigde', note: 'Eerst vorige week afmaken: vorige hoort bij week.' },
                { w: 'aangekondigde maatregelen', note: 'Eerst de bijvoeglijke groep afmaken: vorige week hoort bij aangekondigde.' },
              ],
              note: 'Vorige week bepaalt het deelwoord, niet de maatregelen: de maatregelen gelden misschien pas volgend jaar.',
            },
          },
          {
            text: 'Een *bijstelling* (Engels: *apposition*) is een naamwoordgroep die een andere naamwoordgroep opnieuw benoemt: *Utrecht, de vierde stad van het land, heeft een grote universiteit.* Een bijstelling die extra informatie geeft, staat tussen twee komma’s; laat je hem weg, dan blijft de zin kloppen. Zonder komma’s gaat het om een vaste combinatie die de groep beperkt: *de schrijver Mulisch*, *mijn vriend Ahmed*.',
            rule: 'Een bijstelling met extra informatie staat tussen komma’s, aan beide kanten.',
            quiz: {
              q: 'Welke zin is goed gepunctueerd?',
              options: [
                'Utrecht, de vierde stad van het land, heeft een grote universiteit.',
                'Utrecht, de vierde stad van het land heeft een grote universiteit.',
                'Utrecht de vierde stad van het land, heeft een grote universiteit.',
              ],
              answer: 'Utrecht, de vierde stad van het land, heeft een grote universiteit.',
              why: 'De bijstelling wordt aan beide kanten afgesloten. Met maar één komma is de bijstelling niet afgesloten en loopt de zin vast.',
            },
          },
          {
            text: 'Bij betrekkelijke bijzinnen beslist de komma over de betekenis. *De studenten die te laat kwamen, mochten niet meedoen*: alleen de laatkomers vallen af. Dat is een *beperkende* bijzin: hij beperkt over welke studenten het gaat. *De studenten, die te laat kwamen, mochten niet meedoen*: álle studenten vielen af, en ze waren allemaal te laat. Dat is een *uitbreidende* bijzin: hij voegt alleen informatie toe.',
            rule: 'Beperkende bijzin: geen komma ervoor. Uitbreidende bijzin: tussen komma’s.',
            lab: {
              label: 'De studenten … mochten niet meedoen.',
              chips: [
                { k: 'die te laat kwamen,', out: 'beperkend', note: 'Alleen wie te laat kwam, mocht niet meedoen. De anderen wel.' },
                { k: ', die te laat kwamen,', out: 'uitbreidend', note: 'Niemand mocht meedoen. Terloops: ze waren allemaal te laat.' },
              ],
            },
            quiz: {
              q: 'Iemand schrijft: Mijn broer die in Gent woont, belt vaak. Wat suggereert dat?',
              options: ['Ik heb meer dan één broer', 'Ik heb precies één broer'],
              answer: 'Ik heb meer dan één broer',
              why: 'Zonder komma is de bijzin beperkend: hij kiest één broer uit meerdere. Met één broer schrijf je: Mijn broer, die in Gent woont, belt vaak.',
            },
            deep: {
              q: 'Wat is het verschil in de structuur?',
              a: 'Een beperkende bijzin hoort bij het naamwoord vóórdat het lidwoord erbij komt: *de [studenten die te laat kwamen]*. Het lidwoord kiest dan uit de laatkomers. Een uitbreidende bijzin hangt aan de hele, al afgeronde naamwoordgroep: *[de studenten], die te laat kwamen*. Daarom krijgt een eigennaam, die al precies één persoon aanwijst, normaal alleen een uitbreidende bijzin: *Ahmed, die in Gent woont*.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'beperkend',
        prompt: 'Beperkend of uitbreidend?',
        buckets: ['beperkend: kiest uit een groep', 'uitbreidend: voegt alleen informatie toe'],
        items: [
          { t: 'De fietsen die buiten stonden, zijn gestolen.', b: 0 },
          { t: 'De fietsen, die buiten stonden, zijn gestolen.', b: 1 },
          { t: 'Mijn moeder, die in Gent woont, belt elke zondag.', b: 1 },
          { t: 'De boeken die ik heb gelezen, liggen op tafel.', b: 0 },
          { t: 'Amsterdam, dat aan het IJ ligt, trekt veel toeristen.', b: 1 },
          { t: 'Mensen die roken, leven gemiddeld korter.', b: 0 },
          { t: 'De zon, die om 6 uur opkwam, scheen fel.', b: 1 },
          { t: 'Het huis dat we wilden kopen, is verkocht.', b: 0 },
        ],
        why: 'Zonder komma vóór die of dat kiest de bijzin uit een groep. Tussen komma’s voegt hij informatie toe over iets wat al vastligt, zoals een eigennaam, de zon of je moeder.',
      },
      {
        kind: 'proofread',
        id: 'kommas',
        prompt: 'Lees de tekst na',
        intro: 'Er zitten drie kommafouten in. Tik de woorden aan die een komma te veel of te weinig hebben.',
        tokens: [
          { t: 'Mijn' },
          { t: 'moeder', fix: 'moeder,', why: 'Je hebt één moeder: de bijzin is uitbreidend en staat tussen komma’s.' },
          { t: 'die' },
          { t: 'in' },
          { t: 'Gent' },
          { t: 'woont,' },
          { t: 'belt' },
          { t: 'me' },
          { t: 'elke' },
          { t: 'zondag.' },
          { t: 'Ze' },
          { t: 'vertelt' },
          { t: 'dan' },
          { t: 'over' },
          { t: 'Gent', fix: 'Gent,', why: 'Voor de bijstelling de mooiste stad van België hoort een komma.' },
          { t: 'de' },
          { t: 'mooiste' },
          { t: 'stad' },
          { t: 'van' },
          { t: 'België.' },
          { t: 'Ze' },
          { t: 'heeft' },
          { t: 'een' },
          { t: 'hekel' },
          { t: 'aan' },
          { t: 'mensen,', fix: 'mensen', why: 'Ze heeft geen hekel aan alle mensen, alleen aan wie te laat komt: beperkend, dus geen komma.' },
          { t: 'die' },
          { t: 'altijd' },
          { t: 'te' },
          { t: 'laat' },
          { t: 'komen.' },
        ],
        done: { title: 'Komma’s met betekenis', text: 'Een komma voor die of dat is geen adempauze: hij verandert over wie je het hebt.' },
      },
      {
        kind: 'rewrite',
        id: 'betaling',
        prompt: 'Herschrijf in werkwoordstijl. Begin met ‘Als’ of ‘Zodra’ en gebruik ‘versturen’.',
        source: 'Na ontvangst van uw betaling gaan wij over tot verzending van het pakket.',
        accept: [
          'Als wij uw betaling hebben ontvangen, versturen wij het pakket.',
          'Als we uw betaling hebben ontvangen, versturen we het pakket.',
          'Als wij uw betaling ontvangen hebben, versturen wij het pakket.',
          'Als we uw betaling ontvangen hebben, versturen we het pakket.',
          'Zodra wij uw betaling hebben ontvangen, versturen wij het pakket.',
          'Zodra we uw betaling hebben ontvangen, versturen we het pakket.',
          'Zodra wij uw betaling ontvangen hebben, versturen wij het pakket.',
          'Zodra we uw betaling ontvangen hebben, versturen we het pakket.',
          'Als wij uw betaling ontvangen, versturen wij het pakket.',
          'Als we uw betaling ontvangen, versturen we het pakket.',
          'Zodra wij uw betaling ontvangen, versturen wij het pakket.',
          'Zodra we uw betaling ontvangen, versturen we het pakket.',
        ],
        why: 'ontvangst wordt ontvangen, overgaan tot verzending wordt versturen. Nu staat er wie wat doet: wij ontvangen, wij versturen.',
      },
      {
        kind: 'swipe',
        id: 'lang-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'In de door de minister aangekondigde maatregelen is maatregelen de kern.', ok: true, why: 'Al het andere bepaalt maatregelen.' },
          {
            t: 'Een uitbreidende bijzin staat zonder komma’s.',
            ok: false,
            fix: 'tussen komma’s',
            why: 'Zonder komma’s is hij beperkend.',
          },
          { t: 'Een bijstelling met extra informatie staat tussen twee komma’s.', ok: true, why: 'Utrecht, de vierde stad van het land, …' },
          {
            t: 'Naamwoordstijl maakt een tekst concreter.',
            ok: false,
            fix: 'abstracter',
            why: 'Je ziet niet meer wie wat doet.',
          },
          {
            t: 'Na een eigennaam is een betrekkelijke bijzin uitbreidend.',
            ok: true,
            why: 'Ahmed, die in Gent woont: de naam wijst al precies één persoon aan.',
          },
          { t: 'Een lange voorbepaling herschrijf je vaak met een betrekkelijke bijzin.', ok: true, why: 'de maatregelen die de minister heeft aangekondigd.' },
        ],
      },
    ],
  },
];
