import type { LessonInput } from '../schema';

/**
 * De woordgroep, master p15–p18: kwantoren en bereik, de betekenis van bijvoeglijke naamwoorden,
 * woordgroep of samenstelling, en zwaarte, volgorde en typologie.
 */
export const GROEP_THEORIE_LESSONS: LessonInput[] = [
  {
    id: 'p15',
    stage: 'master',
    domain: 'sem',
    also: ['syn'],
    title: 'Kwantoren en bereik',
    skill: 'Zinsbouw',
    icon: '∀∃',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Tellen zonder getallen',
        panels: [
          {
            text: 'Een *kwantor* telt zonder een getal te noemen: *alle*, *sommige*, *geen*, *weinig*, *de meeste*. Ideaal voor een docent die liever niet zegt hoeveel studenten er zakten. In de naamwoordgroep staat de kwantor op de plek van het lidwoord: *iedere student*, *geen boek*, *de meeste boeken*. Samen met het zelfstandig naamwoord vormt hij een *kwantorgroep*.',
            rule: 'Een kwantor zegt hoeveel van iets aan een eigenschap voldoet, zonder een precies aantal.',
            phrase: {
              q: 'Vind de drie naamwoordgroepen die met een kwantor beginnen',
              sentence: 'Iedere student las de meeste boeken van weinig schrijvers.',
              groups: [
                { span: [0, 1], cat: 'naamwoordgroep', head: 1, note: 'Kwantor iedere, kern student.' },
                { span: [3, 8], cat: 'naamwoordgroep', head: 5, note: 'Kwantor de meeste, kern boeken, met de nabepaling van weinig schrijvers.' },
                {
                  span: [7, 8],
                  cat: 'naamwoordgroep',
                  head: 8,
                  note: 'Kwantor weinig, kern schrijvers. Deze groep zit in de voorzetselgroep, die weer in de grotere groep zit.',
                },
              ],
              traps: [{ span: [1, 2], note: 'student las loopt over de grens: las is het werkwoord van de zin.' }],
              note: 'Drie kwantorgroepen, waarvan één genest. De meeste is één kwantor van twee woorden.',
            },
          },
          {
            text: 'Hoe werkt zo’n kwantor? Denk in twee verzamelingen. Bij *Alle studenten slaagden* is A de verzameling studenten en B de verzameling mensen die slaagden. De kwantor zegt hoe A en B zich tot elkaar verhouden. *Alle*: A ligt helemaal in B. *Sommige*: A en B overlappen. *Geen*: A en B overlappen niet.',
            rule: 'Een kwantor is een verband tussen twee verzamelingen: wat het zelfstandig naamwoord noemt (A) en wat de rest van de zin zegt (B).',
            lab: {
              label: 'Tik een kwantor (A = studenten, B = wie slaagde)',
              chips: [
                { k: 'alle', out: 'A ligt helemaal in B', note: 'Geen enkele student valt buiten de geslaagden.' },
                { k: 'sommige', out: 'A en B overlappen', note: 'Minstens één student slaagde.' },
                { k: 'geen', out: 'A en B overlappen niet', note: 'De doorsnede is leeg.' },
                { k: 'de meeste', out: 'A∩B is groter dan A zonder B', note: 'Meer geslaagde dan gezakte studenten.' },
                { k: 'weinig', out: 'A∩B is klein', note: 'Wat klein is, hangt af van wat je verwacht: vaag en afhankelijk van context.' },
              ],
            },
          },
          {
            text: 'Twee kwantoren in één zin geven vaak twee lezingen. *Iedere student las een boek.* Lezing 1: per student een boek, misschien steeds een ander. Lezing 2: er is één boek dat iedere student las. Het verschil zit in het *bereik* (Engels *scope*): welke kwantor de andere ‘omvat’. In lezing 1 heeft *iedere* breed bereik, in lezing 2 heeft *een* breed bereik.',
            rule: 'Bereik: de kwantor met breed bereik bepaalt hoe de andere wordt geteld.',
            quiz: {
              q: 'Welke voortzetting van ‘Iedere student las een boek’ dwingt de lezing met één en hetzelfde boek?',
              options: ['Het was Max Havelaar.', 'Ieder koos er zelf een uit.', 'Ze lazen in de bibliotheek.'],
              answer: 'Het was Max Havelaar.',
              why: 'Het verwijst naar één bepaald boek. Dan heeft een boek breed bereik. Ieder koos er zelf een uit dwingt juist de andere lezing.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'gelijkwaardig',
        prompt: 'Zakken is niet slagen. Wat zegt elke zin over de studenten die slaagden?',
        buckets: ['alle studenten slaagden', 'sommige studenten slaagden', 'geen student slaagde'],
        items: [
          { t: 'Er zakte geen enkele student.', b: 0 },
          { t: 'Niet alle studenten zakten.', b: 1 },
          { t: 'Alle studenten zakten.', b: 2 },
          { t: 'Er is geen student die niet slaagde.', b: 0 },
          { t: 'Minstens één student slaagde.', b: 1 },
          { t: 'Niemand van de studenten slaagde.', b: 2 },
          { t: 'Iedere student haalde het.', b: 0 },
          { t: 'Niet iedere student zakte.', b: 1 },
          { t: 'Geen student haalde het.', b: 2 },
        ],
        why: 'Geen ... niet is alle; niet alle ... zakten is sommige slaagden; alle ... zakten is geen slaagde. Een ontkenning voor een kwantor draait hem om: niet alle is sommige niet, niet sommige is geen.',
      },
      {
        kind: 'ambiguity',
        id: 'bereik-boek',
        prompt: 'Eén zin, twee bereiken',
        intro: 'Kies een lezing en zoek de zin die alleen die lezing heeft.',
        sentence: 'Iedere student las een boek.',
        meanings: [
          {
            id: 'ieder',
            label: 'Per student een boek, misschien steeds een ander',
            highlight: ['Iedere student'],
            right: 'Klopt. Iedere heeft breed bereik: voor iedere student is er een boek.',
          },
          {
            id: 'een',
            label: 'Eén boek dat iedereen las',
            highlight: ['een boek'],
            right: 'Klopt. Een boek heeft breed bereik: er is één boek, en iedere student las het.',
          },
        ],
        options: [
          { t: 'Iedere student las gisteren een boek.', fits: null, note: 'Een tijd erbij verandert het bereik niet. Nog steeds twee lezingen.' },
          { t: 'Iedere student las een ander boek.', fits: 'ieder' },
          { t: 'Er is een boek dat iedere student las.', fits: 'een' },
          { t: 'Iedere student las een dik boek.', fits: null, note: 'Een bijvoeglijk naamwoord kiest geen lezing.' },
        ],
        done: {
          title: 'Bereik gekozen',
          text: 'Wie één boek bedoelt, schrijft hetzelfde boek of er is een boek dat. Wie per persoon bedoelt, schrijft een ander boek of elk een boek.',
        },
      },
      {
        kind: 'choice',
        id: 'de-meeste',
        prompt: 'Er zijn 20 studenten. Wanneer is ‘De meeste studenten slaagden’ waar?',
        before: '',
        after: '',
        options: ['als er 11 of meer slaagden', 'als er 10 of meer slaagden', 'als er meer dan 1 slaagde', 'als er 20 slaagden'],
        answer: 'als er 11 of meer slaagden',
        why: 'De meeste: meer geslaagden dan gezakten. Bij 10 tegen 10 is dat niet zo. Bij 20 is de zin ook waar, maar dat is niet de grens.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Gegeneraliseerde kwantoren',
        panels: [
          {
            text: 'Het idee van de twee verzamelingen komt uit de *theorie van gegeneraliseerde kwantoren*. Jon Barwise en Robin Cooper (1981) lieten zien dat kwantoren als *de meeste* niet uit te drukken zijn met de twee kwantoren van de klassieke logica, ‘voor alle x’ (∀) en ‘er is een x’ (∃). Je hebt een relatie tussen twee verzamelingen nodig. Belangrijk: de kwantor combineert eerst met het zelfstandig naamwoord. Zo ontstaat verzameling A.',
            rule: 'Barwise en Cooper (1981): een kwantor is een relatie tussen twee verzamelingen.',
            bracket: {
              q: 'Bouw de kwantorgroep van binnen naar buiten',
              words: true,
              tree: '[[bijna alle] [nieuwe studenten]]',
              nodes: [
                { w: 'bijna alle', cat: 'kwantor', note: 'bijna wijzigt alle: samen één complexe kwantor.' },
                { w: 'nieuwe studenten', cat: 'N′', note: 'Dit is verzameling A: de nieuwe studenten.' },
                {
                  w: 'bijna alle nieuwe studenten',
                  cat: 'NP',
                  note: 'De kwantor legt het verband tussen A en de verzameling B die de rest van de zin levert.',
                },
              ],
              traps: [{ w: 'alle nieuwe', note: 'alle telt niet de nieuwe, maar de nieuwe studenten: nieuwe hoort eerst bij studenten.' }],
              note: 'Kwantor plus verzameling A: zo’n groep wacht op een verzameling B, bijvoorbeeld slaagden.',
            },
            deep: {
              q: 'Waarom kan ‘de meeste’ niet met ∀ en ∃?',
              a: 'Met ∀ en ∃ kun je alleen zeggen dat iets voor allen of voor minstens één geldt. *De meeste* vergelijkt twee aantallen: het deel van A dat in B ligt, met het deel dat erbuiten ligt. Barwise en Cooper bewezen dat dat in de klassieke eerste-orde logica niet kan, ook niet met slimme combinaties.',
            },
          },
          {
            text: 'Natuurlijke kwantoren hebben een opvallende eigenschap: ze zijn *conservatief*. Je hoeft alleen binnen A te kijken. *Alle studenten slaagden* betekent hetzelfde als *Alle studenten zijn studenten die slaagden*. Barwise en Cooper, en Keenan en Stavi (1986), stelden voor dat dit voor alle determinatoren in alle talen geldt: een kandidaat-universale. Een woord als *alleen* gedraagt zich anders, en geldt daarom meestal niet als determinator.',
            rule: 'Conservativiteit: Q(A, B) betekent hetzelfde als Q(A, A∩B).',
            quiz: {
              q: 'Welk woord is niet conservatief?',
              options: ['alleen', 'alle', 'geen'],
              answer: 'alleen',
              why: 'Alleen studenten slaagden is iets anders dan Alleen studenten zijn studenten die slaagden. Die tweede zin is altijd waar. Bij alle en geen verandert er niets.',
            },
          },
          {
            text: 'Kwantoren verschillen ook in *monotonie*: welke kant een conclusie op mag. Bij *sommige* mag je van klein naar groot: uit *Sommige studenten rennen hard* volgt *Sommige studenten rennen*. Dat heet *opwaarts monotoon*. Bij *weinig* en *geen* gaat het andersom: uit *Weinig studenten rennen* volgt *Weinig studenten rennen hard*. Dat heet *neerwaarts monotoon*. Juist in neerwaartse omgevingen mogen *negatief-polaire* woorden staan, zoals *ook maar* en *hoeven*: *Weinig studenten hebben ook maar één boek gelezen*, maar niet ∗*Veel studenten hebben ook maar één boek gelezen*. Dat verband legde William Ladusaw (1979).',
            rule: 'Negatief-polaire woorden zoals ook maar en hoeven hebben een neerwaarts monotone omgeving nodig.',
            lab: {
              label: 'Tik een kwantor: welke kant gaat de conclusie op in B?',
              chips: [
                { k: 'sommige', out: 'opwaarts · ook maar mag niet', note: 'rennen hard → rennen.' },
                { k: 'alle', out: 'opwaarts in B · neerwaarts in A', note: 'Alle studenten rennen → Alle Groningse studenten rennen.' },
                { k: 'de meeste', out: 'opwaarts · ook maar mag niet', note: 'De meeste rennen hard → de meeste rennen.' },
                { k: 'weinig', out: 'neerwaarts · ook maar mag', note: 'Weinig rennen → weinig rennen hard.' },
                { k: 'geen', out: 'neerwaarts · ook maar mag', note: 'Geen student heeft ook maar iets gezegd.' },
              ],
            },
            deep: {
              q: 'En ‘ooit’?',
              a: 'In het Engels is *ever* een schoolvoorbeeld van een negatief-polair woord. Het Nederlandse *ooit* is lastiger: in een vraag of na *geen* betekent het *ever* (*Heeft iemand ooit ...?*), maar *Ik heb ooit in Parijs gewoond* is gewoon goed Nederlands, met de betekenis ‘eens, vroeger’. *Hoeven* en *ook maar* zijn betere testwoorden.',
            },
          },
          {
            text: 'Gary Milsark (1977) zag dat na *er* in een bestaanszin niet elke kwantor kan. *Er zitten twee studenten in de zaal* en *Er zitten veel studenten in de zaal* zijn goed. ∗*Er zitten alle studenten in de zaal* en ∗*Er zit iedere student in de zaal* niet. Milsark noemde de eerste soort *zwak* (*een*, *twee*, *enkele*, *veel*, *geen*) en de tweede *sterk* (*de*, *alle*, *iedere*, *de meeste*). Een zwakke kwantor introduceert iets nieuws; een sterke veronderstelt dat de verzameling al bekend is.',
            rule: 'Milsark (1977): in een er-zin staan alleen zwakke kwantoren.',
            quiz: {
              q: 'Welke zin is goed?',
              options: ['Er staan enkele fietsen voor de deur.', 'Er staan de meeste fietsen voor de deur.', 'Er staat iedere fiets voor de deur.'],
              answer: 'Er staan enkele fietsen voor de deur.',
              why: 'Enkele is zwak en mag na er. De meeste en iedere zijn sterk.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'milsark',
        prompt: 'Kan deze er-zin?',
        buckets: ['goed: zwakke kwantor', 'fout: sterke kwantor'],
        items: [
          { t: 'Er zitten twee studenten in de zaal.', b: 0 },
          { t: 'Er zitten alle studenten in de zaal.', b: 1 },
          { t: 'Er zitten enkele studenten in de zaal.', b: 0 },
          { t: 'Er zitten de meeste studenten in de zaal.', b: 1 },
          { t: 'Er zitten geen studenten in de zaal.', b: 0 },
          { t: 'Er zit iedere student in de zaal.', b: 1 },
          { t: 'Er zitten veel studenten in de zaal.', b: 0 },
          { t: 'Er zitten beide studenten in de zaal.', b: 1 },
        ],
        why: 'Zwak: twee, enkele, geen, veel. Sterk: alle, de meeste, iedere, beide. Sterke kwantoren veronderstellen een bekende verzameling, en dat botst met er, dat iets nieuws aankondigt.',
      },
      {
        kind: 'swipe',
        id: 'monotonie',
        prompt: 'Volgt de tweede zin uit de eerste?',
        intro: 'Veeg naar rechts als de conclusie altijd klopt, naar links als dat niet zo is.',
        cards: [
          { t: 'Sommige studenten rennen hard. Dus: sommige studenten rennen.', ok: true, why: 'Sommige is opwaarts monotoon.' },
          { t: 'Weinig studenten rennen. Dus: weinig studenten rennen hard.', ok: true, why: 'Weinig is neerwaarts: wie hard rent, rent ook.' },
          {
            t: 'Geen student rent hard. Dus: geen student rent.',
            ok: false,
            fix: 'andersom: uit geen student rent volgt geen student rent hard',
            why: 'Misschien rennen ze allemaal langzaam.',
          },
          { t: 'Alle studenten rennen. Dus: alle Groningse studenten rennen.', ok: true, why: 'Alle is neerwaarts in A: een kleinere groep studenten mag.' },
          { t: 'Weinig studenten rennen hard. Dus: weinig studenten rennen.', ok: false, fix: 'volgt niet', why: 'Misschien rennen er veel, maar langzaam.' },
          { t: 'De meeste studenten rennen hard. Dus: de meeste studenten rennen.', ok: true, why: 'De meeste is opwaarts in B.' },
          {
            t: 'Sommige studenten rennen. Dus: sommige Groningse studenten rennen.',
            ok: false,
            fix: 'volgt niet',
            why: 'Sommige is opwaarts in A: de rennende studenten kunnen allemaal uit Utrecht komen.',
          },
        ],
      },
      {
        kind: 'rewrite',
        id: 'een-boek',
        prompt: 'Herschrijf de zin zo dat alleen de lezing met één en hetzelfde boek overblijft.',
        source: 'Iedere student las een boek.',
        accept: [
          'Iedere student las hetzelfde boek.',
          'Alle studenten lazen hetzelfde boek.',
          'Er is een boek dat iedere student las.',
          'Er is één boek dat iedere student las.',
          'Er is een boek dat alle studenten lazen.',
          'Iedere student las een en hetzelfde boek.',
          'Iedere student las één en hetzelfde boek.',
          'Alle studenten lazen een en hetzelfde boek.',
          'Alle studenten lazen één en hetzelfde boek.',
        ],
        why: 'Hetzelfde boek of er is een boek dat geeft een boek breed bereik. Dan blijft er maar één lezing over.',
      },
      {
        kind: 'bet',
        id: 'ook-maar',
        prompt: 'Welke zin is goed Nederlands?',
        options: [
          'Weinig studenten hebben ook maar één vraag gesteld.',
          'Veel studenten hebben ook maar één vraag gesteld.',
          'Sommige studenten hebben ook maar één vraag gesteld.',
          'De meeste studenten hebben ook maar één vraag gesteld.',
        ],
        answer: 'Weinig studenten hebben ook maar één vraag gesteld.',
        why: 'Ook maar is negatief-polair en heeft een neerwaartse omgeving nodig. Alleen weinig levert die; veel, sommige en de meeste zijn opwaarts.',
      },
    ],
  },
  {
    id: 'p16',
    stage: 'master',
    domain: 'sem',
    also: ['syn'],
    title: 'Wat bijvoeglijke naamwoorden doen',
    skill: 'Zinsbouw',
    icon: 'A∩N',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Rood, groot en voormalig',
        panels: [
          {
            text: 'Een grote muis is een klein dier, en een voormalige minister is geen minister meer. Bijvoeglijke naamwoorden zijn minder braaf dan ze lijken. Toch begrijp je elke nieuwe combinatie meteen. Dat komt door *compositionaliteit*: de betekenis van het geheel volgt uit de betekenis van de delen en de manier waarop ze zijn samengevoegd. Het principe wordt genoemd naar de logicus Gottlob Frege (1848–1925).',
            rule: 'Compositionaliteit: betekenis van het geheel = betekenis van de delen + hoe ze samengaan.',
            bracket: {
              q: 'Bouw de naamwoordgroep van binnen naar buiten',
              words: true,
              tree: '[een [[heel grote] muis]]',
              nodes: [
                { w: 'heel grote', cat: 'AP', note: 'heel versterkt grote.' },
                { w: 'heel grote muis', cat: 'N′', note: 'Hier gebeurt het: groot wordt gemeten aan muizen.' },
                { w: 'een heel grote muis', cat: 'NP', note: 'een maakt er één exemplaar van.' },
              ],
              traps: [{ w: 'een heel', note: 'een hoort bij de hele groep, niet bij heel.' }],
              note: 'Elke stap levert een betekenis op. De stap heel grote + muis is de interessante: daar wordt groot ‘groot voor een muis’.',
            },
          },
          {
            text: 'Het makkelijkste geval is *intersectief*. Een *rode auto* is iets wat rood is én een auto is: de doorsnede (intersectie) van twee verzamelingen. Test: uit *Dit is een rode auto* volgen zowel *Dit is rood* als *Dit is een auto*. Kleuren, vormen en materialen werken zo: *vierkante tafel*, *houten lepel*.',
            rule: 'Intersectief: een A N is A én is een N.',
            quiz: {
              q: 'Welke combinatie is intersectief?',
              options: ['houten lepel', 'grote muis', 'voormalige minister'],
              answer: 'houten lepel',
              why: 'Een houten lepel is van hout en is een lepel. Een grote muis is niet groot in het algemeen, en een voormalige minister is geen minister.',
            },
          },
          {
            text: 'Bij een *subsectief* bijvoeglijk naamwoord is een A N nog wel een N, maar niet zomaar A. Een *grote muis* is een muis, maar groot is ze alleen voor een muis. Een *goede pianist* is een pianist, maar daarmee nog geen goed mens. Jan kan een goede pianist en een slechte violist zijn: dezelfde persoon, goed en slecht tegelijk.',
            rule: 'Subsectief: een A N is een N, maar alleen A als N.',
            lab: {
              label: 'Tik een combinatie',
              chips: [
                { k: 'grote muis', out: 'muis: ja · groot: alleen voor een muis', note: 'Een grote muis is kleiner dan een kleine olifant.' },
                { k: 'goede pianist', out: 'pianist: ja · goed: als pianist', note: 'Over zijn karakter zegt het niets.' },
                { k: 'snelle slak', out: 'slak: ja · snel: voor een slak', note: 'Haal er een fietser mee in en je ziet het verschil.' },
                { k: 'rode auto', out: 'auto: ja · rood: ja', note: 'Intersectief: geen voorbehoud.' },
              ],
            },
          },
          {
            text: 'Dan de buitenbeentjes. Een *voormalige minister* is geen minister meer: het bijvoeglijk naamwoord ontkent het zelfstandig naamwoord. Dat heet *privatief*. Een *vermeende dief* kan een dief zijn, of juist niet. Daarover zegt de combinatie niets: *niet-subsectief*. Bij deze woorden volgt uit *een A N* niet eens *een N*.',
            rule: 'Privatief: een A N is géén N. Niet-subsectief: een A N is misschien een N.',
            quiz: {
              q: 'Wat weet je zeker over een vermeende dief?',
              options: ['Niets: hij kan een dief zijn of niet', 'Hij is een dief', 'Hij is geen dief'],
              answer: 'Niets: hij kan een dief zijn of niet',
              why: 'Vermeend zegt alleen dat iemand het beweert. De rechter beslist.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'soorten',
        prompt: 'Wat voor bijvoeglijk naamwoord is het hier?',
        buckets: ['intersectief', 'subsectief', 'privatief', 'niet-subsectief'],
        items: [
          { t: 'rode auto', b: 0 },
          { t: 'grote muis', b: 1 },
          { t: 'voormalige minister', b: 2 },
          { t: 'vermeende dief', b: 3 },
          { t: 'vierkante tafel', b: 0 },
          { t: 'goede pianist', b: 1 },
          { t: 'gewezen voorzitter', b: 2 },
          { t: 'mogelijke winnaar', b: 3 },
          { t: 'houten lepel', b: 0 },
          { t: 'snelle slak', b: 1 },
        ],
        why: 'Intersectief: A én N. Subsectief: N, maar A alleen als N. Privatief: geen N (meer). Niet-subsectief: misschien een N. Gewezen is een formeel woord voor voormalig.',
      },
      {
        kind: 'bet',
        id: 'olifant',
        prompt: 'Een kleine olifant en een grote muis. Welk dier is groter?',
        options: ['de kleine olifant', 'de grote muis', 'dat kun je niet weten'],
        answer: 'de kleine olifant',
        why: 'Klein en groot meten aan het zelfstandig naamwoord. De kleinste olifant is nog altijd veel groter dan de grootste muis.',
      },
      {
        kind: 'choice',
        id: 'pianist',
        prompt: 'Jan is een goede pianist. Jan is ook violist. Wat volgt daaruit?',
        before: '',
        after: '',
        options: ['Niets over hoe goed hij viool speelt', 'Jan is een goede violist', 'Jan is een slechte violist'],
        answer: 'Niets over hoe goed hij viool speelt',
        why: 'Goed is subsectief: goed als pianist. Dat zegt niets over Jan als violist. Bij een intersectief woord (Jan is een lange pianist) zou lang wel meegaan.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Een indeling en haar grenzen',
        panels: [
          {
            text: 'De indeling in vier soorten staat in een klassiek artikel van Hans Kamp en Barbara Partee (1995, *Prototype theory and compositionality*). Ze vormt een rangorde van sterke naar zwakke conclusies. Intersectief: een A N is A en een N. Subsectief: een A N is een N. Niet-subsectief: niets. Privatief: een A N is géén N. Elke intersectieve combinatie is dus ook subsectief, maar niet andersom.',
            rule: 'Kamp en Partee (1995): intersectief ⊂ subsectief; daarbuiten staan niet-subsectief en privatief.',
            quiz: {
              q: 'Wat volgt zeker uit ‘Dumbo is een kleine olifant’?',
              options: ['Dumbo is een olifant', 'Dumbo is klein', 'Dumbo is klein en een olifant'],
              answer: 'Dumbo is een olifant',
              why: 'Klein is subsectief: Dumbo is een olifant, maar klein alleen voor een olifant.',
            },
            deep: {
              q: 'Welk probleem zagen Kamp en Partee voor compositionaliteit?',
              a: 'Het probleem van de *pet fish*, een voorbeeld van Osherson en Smith (1981). Het typische huisdier is een hond of kat, de typische vis iets als een forel. Maar de typische *pet fish* is een goudvis of guppy: dat prototype volgt niet uit de prototypes van de delen. Kamp en Partee concludeerden dat prototypes niet compositioneel zijn, de betekenis zelf wel.',
            },
          },
          {
            text: 'Woorden als *groot*, *klein* en *snel* zijn *relatief*: ze meten aan een standaard. Die standaard hangt af van een *vergelijkingsklasse*, meestal geleverd door het zelfstandig naamwoord. Ewan Klein (1980) gaf daar een formele analyse van; later bouwde Christopher Kennedy (2007) dat uit tot een theorie van graden en schalen. Je kunt de klasse ook zelf noemen: *groot voor een muis*, *snel voor zijn leeftijd*.',
            rule: 'Relatieve bijvoeglijke naamwoorden meten aan een vergelijkingsklasse: groot voor een N.',
            lab: {
              label: 'Tik een combinatie: wat betekent groot hier?',
              chips: [
                { k: 'grote muis', out: 'boven de standaard voor muizen', note: 'Een paar centimeter extra is genoeg.' },
                { k: 'grote olifant', out: 'boven de standaard voor olifanten', note: 'Al gauw meer dan drie meter.' },
                {
                  k: 'groot voor een kind',
                  out: 'vergelijkingsklasse uitdrukkelijk genoemd',
                  note: 'Hier levert voor een kind de klasse, niet het zelfstandig naamwoord.',
                },
                { k: 'groot huis', out: 'boven de standaard voor huizen', note: 'Waar die grens ligt, verschilt per stad: de standaard is ook vaag.' },
              ],
            },
          },
          {
            text: 'De soorten gedragen zich ook syntactisch anders. Intersectieve woorden kunnen gezegde zijn: *de auto is rood*. Veel niet-intersectieve woorden kunnen alleen vóór het zelfstandig naamwoord staan: *de voormalige minister*, maar ∗*de minister is voormalig*; *de vermeende dief*, maar ∗*de dief is vermeend*. Bij *een mooie danseres* krijg je twee lezingen: ze is mooi, of ze danst mooi. Richard Larson (1998) verklaarde de tweede lezing doordat het bijvoeglijk naamwoord het dansen beschrijft, niet de persoon.',
            rule: 'Veel privatieve en niet-subsectieve bijvoeglijke naamwoorden kunnen geen gezegde zijn.',
            mark: {
              q: 'Tik de bijvoeglijke naamwoorden die alleen vóór het zelfstandig naamwoord kunnen staan',
              sentence: 'De vermeende dief reed met een rode auto naar zijn voormalige huis.',
              targets: [1, 10],
              note: 'vermeende en voormalige: ∗de dief is vermeend, ∗zijn huis is voormalig. De auto is rood kan wel.',
            },
          },
        ],
      },
      {
        kind: 'ambiguity',
        id: 'danseres',
        prompt: 'Eén danseres, twee keer mooi',
        intro: 'Kies een lezing en zoek de zin die alleen die lezing heeft.',
        sentence: 'Ze is een mooie danseres.',
        meanings: [
          { id: 'persoon', label: 'Zij is mooi, en ze is danseres', highlight: ['mooie danseres'], right: 'Klopt. Intersectief: mooi en danseres.' },
          { id: 'dans', label: 'Ze danst mooi', highlight: ['mooie danseres'], right: 'Klopt. Mooi beschrijft hier het dansen: de lezing van Larson.' },
        ],
        options: [
          { t: 'Ze is een mooie danseres bij het Nationale Ballet.', fits: null, note: 'Een werkgever erbij beslist niets.' },
          { t: 'Ze danst mooi, al vindt niemand haar knap.', fits: 'dans' },
          { t: 'Ze is mooi, al danst ze houterig.', fits: 'persoon' },
        ],
        done: { title: 'Twee keer mooi', text: 'Wie precies wil zijn, schrijft ze danst mooi of ze is mooi. De korte naamwoordgroep laat het open.' },
      },
      {
        kind: 'swipe',
        id: 'gevolgtrekking',
        prompt: 'Klopt de conclusie?',
        intro: 'Veeg naar rechts als de conclusie altijd klopt, naar links als dat niet zo is.',
        cards: [
          { t: 'Dit is een houten lepel. Dus: dit is van hout.', ok: true, why: 'Intersectief.' },
          { t: 'Dit is een grote muis. Dus: dit is een groot dier.', ok: false, fix: 'alleen: groot voor een muis', why: 'Groot is subsectief en relatief.' },
          {
            t: 'Zij is een voormalige burgemeester. Dus: zij is burgemeester.',
            ok: false,
            fix: 'zij is geen burgemeester meer',
            why: 'Voormalig is privatief.',
          },
          { t: 'Hij is een snelle slak. Dus: hij is een slak.', ok: true, why: 'Subsectief: een A N is altijd een N.' },
          {
            t: 'Hij is een vermeende fraudeur. Dus: hij is een fraudeur.',
            ok: false,
            fix: 'misschien wel, misschien niet',
            why: 'Vermeend is niet-subsectief.',
          },
          { t: 'Elke intersectieve combinatie is ook subsectief.', ok: true, why: 'Als iets A én een N is, is het zeker een N.' },
        ],
      },
      {
        kind: 'rewrite',
        id: 'voormalig',
        prompt: 'Voormalig kan geen gezegde zijn. Schrijf één goede zin met dezelfde betekenis.',
        source: 'De minister is voormalig en schrijft nu boeken.',
        accept: [
          'De voormalige minister schrijft nu boeken.',
          'De oud-minister schrijft nu boeken.',
          'De ex-minister schrijft nu boeken.',
          'De gewezen minister schrijft nu boeken.',
        ],
        why: 'Voormalig hoort vóór het zelfstandig naamwoord: de voormalige minister. Oud-minister en ex-minister zijn samenstellingen met dezelfde betekenis.',
      },
      {
        kind: 'choice',
        id: 'gezegde',
        prompt: 'Welke zin is fout?',
        before: '',
        after: '',
        options: ['De dief is vermeend.', 'De dief is groot.', 'De auto is rood.', 'De pianist is goed.'],
        answer: 'De dief is vermeend.',
        why: 'Vermeend kan alleen vóór het zelfstandig naamwoord. Groot en goed kunnen wel gezegde zijn, al meet je dan aan een standaard die de context moet leveren.',
      },
    ],
  },
  {
    id: 'p17',
    stage: 'master',
    domain: 'morf',
    also: ['fon', 'orth', 'syn'],
    title: 'Woordgroep of samenstelling',
    skill: 'Zinsbouw',
    icon: 'A N|AN',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Twee woorden of één',
        panels: [
          {
            text: 'Op een *hogeschool* hoef je niet te klimmen, en op de *zwarte markt* is niets zwart geverfd. Een bijvoeglijk naamwoord met een zelfstandig naamwoord kan twee dingen zijn: een *woordgroep* (twee woorden, zoals *hoge school*) of een *samenstelling* (één woord, zoals *hogeschool*). De betekenis helpt niet altijd. De vorm wel.',
            rule: 'Woordgroep: twee woorden die de syntaxis samenvoegt. Samenstelling: één woord uit het lexicon.',
            phrase: {
              q: 'Vind de drie naamwoordgroepen',
              sentence: 'Mijn zus werkt op de hogeschool naast de hoge school.',
              groups: [
                { span: [0, 1], cat: 'naamwoordgroep', head: 1, note: 'Kern zus.' },
                {
                  span: [4, 5],
                  cat: 'naamwoordgroep',
                  head: 5,
                  note: 'Kern hogeschool: één woord, een samenstelling. De naamwoordgroep heeft alleen de als bepaling.',
                },
                { span: [7, 9], cat: 'naamwoordgroep', head: 9, note: 'Kern school; hoge is een losse bepaling: een school in een hoog gebouw.' },
              ],
              traps: [{ span: [1, 2], note: 'zus werkt loopt over de grens tussen onderwerp en werkwoord.' }],
              note: 'In de tweede groep is hoge een eigen woord met een eigen functie. In de eerste zit hoge ín het woord.',
            },
          },
          {
            text: 'Het duidelijkste kenmerk is de klemtoon. In een woordgroep valt de hoofdklemtoon rechts: *hoge SCHOOL*. In een samenstelling valt hij meestal links: *HOgeschool*. Daardoor hoor je het verschil, ook als je het niet ziet. Let op: *zwarte markt* klinkt als een woordgroep (*zwarte MARKT*), ook al is de betekenis vast.',
            rule: 'Woordgroep: klemtoon rechts. Samenstelling: klemtoon meestal links.',
            lab: {
              label: 'Tik een combinatie',
              chips: [
                { k: 'hoge school', out: 'hoge SCHOOL · woordgroep', note: 'Een school die hoog is.' },
                { k: 'hogeschool', out: 'HOgeschool · samenstelling', note: 'Een instelling voor hoger onderwijs.' },
                { k: 'grote moeder', out: 'grote MOEder · woordgroep', note: 'Een moeder die groot is.' },
                { k: 'grootmoeder', out: 'GROOTmoeder · samenstelling', note: 'Je oma.' },
                { k: 'zwarte markt', out: 'zwarte MARKT · woordgroep', note: 'Vaste betekenis, maar de klemtoon van een woordgroep.' },
              ],
            },
          },
          {
            text: 'Tweede kenmerk: de buiging. In een woordgroep past het bijvoeglijk naamwoord zich aan: *een zwart boek*, *het zwarte boek*. In een samenstelling verandert het eerste deel nooit: *een zwartboek*, *het zwartboek* (een verzameling klachten). Het eerste deel is bevroren, ook als het al een -e heeft: *hogeschool* houdt zijn *e*, wat er ook voor staat.',
            rule: 'In een woordgroep buigt het bijvoeglijk naamwoord mee; in een samenstelling is het eerste deel bevroren.',
            paradigm: {
              q: 'Vul de tabel in',
              cols: ['na een', 'na het'],
              rows: [
                {
                  label: 'zwart + boek (woordgroep)',
                  cells: [{ fill: 'een zwart boek' }, { fill: 'het zwarte boek', hint: 'Na het krijgt het bijvoeglijk naamwoord een -e.' }],
                },
                {
                  label: 'zwartboek (samenstelling)',
                  cells: [{ fill: 'een zwartboek' }, { fill: 'het zwartboek', hint: 'Het eerste deel van een samenstelling verandert niet.' }],
                },
              ],
              extra: ['een zwarte boek', 'het zwarteboek'],
              note: 'Alleen het losse bijvoeglijk naamwoord reageert op het lidwoord. In zwartboek is zwart geen bijvoeglijk naamwoord meer, maar een deel van het woord.',
            },
          },
          {
            text: 'Derde kenmerk: de spelling. Een samenstelling schrijf je aan elkaar, een woordgroep los. Dat geldt ook als er een hele woordgroep in een samenstelling zit: *vrije tijd* is los, maar *vrijetijdsbesteding* is één woord. Zo ook *oudejaarsavond* en *hogesnelheidslijn*.',
            rule: 'Samenstelling aan elkaar, ook als er een woordgroep in zit.',
            quiz: {
              q: 'Hoe schrijf je de lijn voor treinen die heel hard rijden?',
              options: ['hogesnelheidslijn', 'hoge snelheidslijn', 'hoge-snelheidslijn'],
              answer: 'hogesnelheidslijn',
              why: 'De woordgroep hoge snelheid zit in een samenstelling met lijn. Het geheel is één woord, dus aan elkaar.',
            },
          },
        ],
      },
      {
        kind: 'speed',
        id: 'los-of-vast',
        prompt: 'Aan elkaar of los?',
        intro: 'Pas op: een vaste betekenis maakt nog geen samenstelling.',
        seconds: 45,
        items: [
          { a: 'zwarte', b: 'markt', joined: false, tip: 'zwarte markt: vaste betekenis, maar een woordgroep.' },
          { a: 'groot', b: 'moeder', joined: true, tip: 'grootmoeder: je oma.' },
          { a: 'rode', b: 'kool', joined: false, tip: 'rode kool: een woordgroep die een groente noemt.' },
          { a: 'oudejaars', b: 'avond', joined: true, tip: 'oudejaarsavond: woordgroep in een samenstelling, dus aan elkaar.' },
          { a: 'dikke', b: 'darm', joined: false, tip: 'dikke darm: een woordgroep.' },
          { a: 'vrijetijds', b: 'kleding', joined: true, tip: 'vrijetijdskleding: één woord.' },
          { a: 'eerste', b: 'hulp', joined: false, tip: 'eerste hulp: los. Maar eerstehulppost is één woord.' },
          { a: 'groen', b: 'strook', joined: true, tip: 'groenstrook: samenstelling, klemtoon links.' },
        ],
        done: {
          title: 'Vorm boven betekenis',
          text: 'Zwarte markt, rode kool en dikke darm hebben een vaste betekenis, maar zijn woordgroepen: los, klemtoon rechts.',
        },
      },
      {
        kind: 'choice',
        id: 'zwartboek',
        prompt: 'Iemand zegt met de klemtoon op ZWART: ‘Ze publiceerden een zwartboek.’ Wat publiceerden ze?',
        before: '',
        after: '',
        options: ['een verzameling klachten over misstanden', 'een boek met een zwarte kaft', 'een boek over de kleur zwart'],
        answer: 'een verzameling klachten over misstanden',
        why: 'Klemtoon links: een samenstelling met een eigen betekenis. Een boek met een zwarte kaft is een zwart BOEK.',
      },
      {
        kind: 'bet',
        id: 'rode-kool',
        prompt: 'Welke is een woordgroep?',
        options: ['rode kool', 'roodborstje', 'grootmoeder', 'hogeschool'],
        answer: 'rode kool',
        why: 'rode kool: los geschreven, klemtoon rechts, en rode buigt. De andere drie zijn samenstellingen.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Lexicalisering en lexicale integriteit',
        panels: [
          {
            text: 'Een woordgroep kan een vaste betekenis krijgen zonder een woord te worden: *zwarte markt*, *rode kool*, *hoge hoed*, *dikke darm*. Dat heet *lexicalisering*: de combinatie wordt als geheel in het lexicon opgeslagen. Geert Booij (onder meer in *Construction Morphology*, 2010) noemt zulke combinaties *woordgroepnamen*: ze benoemen een soort, net als een woord, maar hun vorm is die van een woordgroep. Daarom tellen klemtoon en buiging, niet de betekenis.',
            rule: 'Gelexicaliseerd is niet hetzelfde als samengesteld: zwarte markt is opgeslagen, maar blijft een woordgroep.',
            quiz: {
              q: 'Waarom is zwarte markt een woordgroep en geen samenstelling?',
              options: ['De klemtoon valt rechts en zwarte buigt mee', 'De betekenis is letterlijk', 'Het woord staat niet in het woordenboek'],
              answer: 'De klemtoon valt rechts en zwarte buigt mee',
              why: 'De betekenis is juist niet letterlijk. Maar de vorm is die van een woordgroep: zwarte MARKT, een zwarte markt, de zwarte markt.',
            },
          },
          {
            text: 'Het verschil laat zich ook zien in de boom. Een gelexicaliseerde woordgroep zoals *zwarte markt* gedraagt zich als één N′ (de tussenlaag van een naamwoordgroep), waar nieuwe bepalingen omheen komen. In *een bloeiende zwarte markt* bloeit de markt, niet de kleur.',
            bracket: {
              q: 'Bouw de naamwoordgroep van binnen naar buiten',
              words: true,
              tree: '[een [bloeiende [zwarte markt]]]',
              nodes: [
                { w: 'zwarte markt', cat: 'N′', note: 'De vaste combinatie: eerst samen.' },
                { w: 'bloeiende zwarte markt', cat: 'N′', note: 'bloeiende bepaalt de hele zwarte markt.' },
                { w: 'een bloeiende zwarte markt', cat: 'NP', note: 'Het lidwoord sluit de groep af.' },
              ],
              traps: [{ w: 'bloeiende zwarte', note: 'bloeiende zegt niets over de kleur: een markt kan bloeien, zwart niet.' }],
              note: 'Binnen zwarte markt kun je niets wijzigen zonder de vaste betekenis te verliezen: een heel zwarte markt is weer letterlijk.',
            },
          },
          {
            text: 'Samenstellingen zijn eilanden voor de syntaxis. Dat heet *lexicale integriteit*: zinsregels kunnen niet in een woord kijken. Je kunt het eerste deel niet apart bepalen (∗*een heel hogeschool* in de betekenis ‘een heel hoge school’), niet apart naar het eerste deel verwijzen, en het niet los verplaatsen. Een woordgroep in een samenstelling wordt mee ingevroren: *hogesnelheidslijn*, *vrijetijdskleding*, *oudejaarsavond*.',
            rule: 'Lexicale integriteit: de syntaxis kan niet in een samenstelling kijken.',
            mark: {
              q: 'Tik de drie woorden waar een woordgroep in zit',
              sentence: 'Op oudejaarsavond zat de hogesnelheidstrein vol met dagjesmensen in vrijetijdskleding.',
              targets: [1, 4, 9],
              note: 'oude jaar, hoge snelheid en vrije tijd zijn woordgroepen; in de samenstelling buigen ze niet meer en staan ze aan elkaar. dagjesmensen is dagje + s + mensen: geen woordgroep.',
            },
            deep: {
              q: 'Is de regel waterdicht?',
              a: 'Niet helemaal. Bij samentrekking deel je een stuk van een samenstelling met een andere: *bus- en treinreizigers*. Daar kijkt de nevenschikking wel in het woord. Taalkundigen debatteren dan ook over hoe streng lexicale integriteit is.',
            },
          },
          {
            text: 'Waarom die klemtoonregels? Noam Chomsky en Morris Halle (1968, *The Sound Pattern of English*) formuleerden er twee voor het Engels: de *Compound Stress Rule* (klemtoon links in een samenstelling) en de *Nuclear Stress Rule* (klemtoon rechts in een woordgroep). Het Nederlands volgt hetzelfde patroon. De klemtoon is dus een signaal van de structuur: hij vertelt de luisteraar of hij één woord of twee hoort.',
            rule: 'Samenstellingsklemtoon links, woordgroepklemtoon rechts: de klemtoon verraadt de structuur.',
            quiz: {
              q: 'Je hoort: ‘Mijn GROOTmoeder belde.’ Wie belde er?',
              options: ['je oma', 'een lange moeder', 'dat kun je niet horen'],
              answer: 'je oma',
              why: 'Klemtoon links: de samenstelling grootmoeder. Een lange moeder is een grote MOEder.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'kenmerken',
        prompt: 'Wijst het kenmerk op een woordgroep of op een samenstelling?',
        buckets: ['woordgroep', 'samenstelling'],
        items: [
          { t: 'hoofdklemtoon op het laatste deel', b: 0 },
          { t: 'hoofdklemtoon op het eerste deel', b: 1 },
          { t: 'het bijvoeglijk naamwoord krijgt een -e na het', b: 0 },
          { t: 'het eerste deel verandert nooit van vorm', b: 1 },
          { t: 'je kunt heel voor het bijvoeglijk naamwoord zetten', b: 0 },
          { t: 'je kunt het eerste deel niet apart bepalen', b: 1 },
          { t: 'los geschreven', b: 0 },
          { t: 'aan elkaar geschreven', b: 1 },
        ],
        why: 'Klemtoon, buiging, bepaalbaarheid en spelling zijn vormkenmerken. Een vaste betekenis zegt weinig: zwarte markt heeft die ook en is toch een woordgroep.',
      },
      {
        kind: 'proofread',
        id: 'aaneen',
        prompt: 'Lees de tekst na',
        intro: 'Er staan drie samenstellingen los die aan elkaar horen. Pas op: niet alles wat vast klinkt, is één woord.',
        tokens: [
          { t: 'Op' },
          { t: 'oude jaarsavond', fix: 'oudejaarsavond', why: 'oude jaar zit in een samenstelling: aan elkaar.' },
          { t: 'nam' },
          { t: 'ik' },
          { t: 'de' },
          { t: 'hoge snelheidstrein', fix: 'hogesnelheidstrein', why: 'hoge snelheid + trein: één woord.' },
          { t: 'naar' },
          { t: 'Parijs.' },
          { t: 'Daar' },
          { t: 'dronk' },
          { t: 'ik' },
          { t: 'rode' },
          { t: 'wijn' },
          { t: 'en' },
          { t: 'kocht' },
          { t: 'ik' },
          { t: 'vrije tijds kleding', fix: 'vrijetijdskleding', why: 'vrije tijd + s + kleding: één woord.' },
          { t: 'op' },
          { t: 'de' },
          { t: 'zwarte' },
          { t: 'markt.' },
        ],
        done: {
          title: 'Goed gelezen',
          text: 'oudejaarsavond, hogesnelheidstrein en vrijetijdskleding zijn samenstellingen. rode wijn en zwarte markt zijn woordgroepen: los.',
        },
      },
      {
        kind: 'type',
        id: 'vrije-tijd',
        prompt: 'Schrijf het woord voor ‘hoe je je vrije tijd besteedt’.',
        before: 'Lezen is mijn favoriete',
        after: '.',
        hint: 'vrije tijd + besteding',
        answer: 'vrijetijdsbesteding',
        why: 'De woordgroep vrije tijd zit in een samenstelling. Dan schrijf je het geheel aan elkaar, met de tussen-s.',
      },
      {
        kind: 'swipe',
        id: 'groep-of-woord',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          {
            t: 'Een vaste betekenis maakt van een woordgroep een samenstelling.',
            ok: false,
            fix: 'nee, de vorm beslist',
            why: 'zwarte markt is vast en toch een woordgroep.',
          },
          { t: 'In hogeschool valt de klemtoon op HO.', ok: true, why: 'Samenstellingsklemtoon links.' },
          { t: 'Je schrijft het zwartboek, niet het zwarteboek.', ok: true, why: 'Het eerste deel van een samenstelling buigt niet.' },
          { t: 'Bij een woordgroep valt de hoofdklemtoon meestal links.', ok: false, fix: 'rechts', why: 'hoge SCHOOL.' },
          { t: 'Vrijetijdsbesteding schrijf je aan elkaar, vrije tijd los.', ok: true, why: 'In de samenstelling is de woordgroep één deel geworden.' },
          {
            t: 'Lexicale integriteit betekent dat zinsregels niet in een woord kunnen kijken.',
            ok: true,
            why: 'Daarom kun je het eerste deel niet apart bepalen.',
          },
        ],
      },
    ],
  },
  {
    id: 'p18',
    stage: 'master',
    domain: 'syn',
    also: ['tekst'],
    title: 'Zwaarte, volgorde en typologie',
    skill: 'Zinsbouw',
    icon: 'XP→',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Zwaar spul achteraan',
        panels: [
          {
            text: 'Een zin is net een koffer: het zware spul moet eruit kunnen zonder dat de rest omvalt. In het Nederlands betekent dat: zware groepen naar achteren. Vergelijk *Ik heb gisteren een boek over Napoleon gelezen* met *Ik heb gisteren een boek gelezen over Napoleon*. In de tweede zin staat de voorzetselgroep *over Napoleon* achter het werkwoord, los van *boek*, waar hij bij hoort. Dat heet *extrapositie*.',
            rule: 'Extrapositie: een groep staat achter het laatste werkwoord, ver van het woord waar hij bij hoort.',
            phrase: {
              q: 'Vind de naamwoordgroep met boek en de voorzetselgroep die erbij hoort',
              sentence: 'Ik heb gisteren een boek gelezen over Napoleon.',
              groups: [
                { span: [3, 4], cat: 'naamwoordgroep', head: 4, note: 'Kern boek. Zijn nabepaling staat verderop.' },
                { span: [6, 7], cat: 'voorzetselgroep', head: 6, note: 'Kern over. Hij hoort bij boek, maar staat na gelezen: geëxtraponeerd.' },
              ],
              traps: [{ span: [3, 7], note: 'Daar zit gelezen tussen: dat is geen aaneengesloten woordgroep meer.' }],
              note: 'Eén betekenisgeheel, een boek over Napoleon, in twee stukken. Het Nederlands staat dat toe en maakt er dankbaar gebruik van.',
            },
          },
          {
            text: 'Waarom doen we dat? Tussen *heb* en *gelezen* staat het *middenveld*. Alles wat daar staat, moet de lezer onthouden tot het laatste werkwoord komt. Hoe zwaarder het middenveld, hoe langer het wachten. Bijzinnen gaan daarom bijna altijd naar achteren: *Ik heb gezegd dat ik kom*, niet ∗*Ik heb dat ik kom gezegd*.',
            rule: 'Houd het middenveld licht: zware voorzetselgroepen en bijzinnen naar achteren.',
            swap: {
              goal: 'Zet de zware voorzetselgroep achter het laatste werkwoord',
              blocks: ['Ik heb', 'een boek', 'over de geschiedenis van de Nederlandse spelling', 'gelezen'],
              accept: ['Ik heb een boek gelezen over de geschiedenis van de Nederlandse spelling'],
              note: 'Nu ziet de lezer het werkwoord gelezen al na vier woorden, en volgt de zware groep daarna.',
            },
          },
          {
            text: 'Het andere uiterste is *centrale inbedding*: een bijzin midden in een bijzin. *De vrouw die de mannen die de hond aaiden zag, lachte.* Grammaticaal klopt het, maar je moet drie onderwerpen onthouden voor de werkwoorden komen. George Miller en Noam Chomsky (1963) wezen er al op dat dubbele inbedding grammaticaal kan en toch nauwelijks te begrijpen is.',
            rule: 'Centrale inbedding is grammaticaal, maar zwaar voor het geheugen.',
            quiz: {
              q: 'Wie aaiden de hond in ‘De vrouw die de mannen die de hond aaiden zag, lachte’?',
              options: ['de mannen', 'de vrouw', 'de hond'],
              answer: 'de mannen',
              why: 'aaiden is meervoud, dus het onderwerp is die = de mannen. Zag is enkelvoud: die = de vrouw zag de mannen. De congruentie redt je.',
            },
          },
        ],
      },
      {
        kind: 'clamp',
        id: 'middenveld',
        prompt: 'Maak het middenveld lichter',
        intro: 'Verplaats zinsdelen tot er hoogstens drie woorden tussen heeft en geleverd staan. Laat niets weg.',
        subject: 'de gemeente',
        finite: 'heeft',
        participle: 'geleverd',
        middle: [{ part: 'vorig' }, { text: 'kritiek' }, { part: 'op' }, { part: 'omdat' }],
        parts: [
          { id: 'vorig', t: 'vorige week', front: true, after: false },
          {
            id: 'op',
            t: 'op het plan voor een nieuwe brug',
            front: false,
            after: true,
            note: 'Een voorzetselgroep bij kritiek mag achter het werkwoord: extrapositie.',
          },
          { id: 'omdat', t: 'omdat het te duur was', front: true, after: true, note: 'Een bijzin hoort achteraan. In het middenveld is hij bijna onleesbaar.' },
        ],
        goal: 3,
        done: { title: 'Licht middenveld', text: 'De gemeente heeft vorige week kritiek geleverd op het plan voor een nieuwe brug, omdat het te duur was.' },
      },
      {
        kind: 'sort',
        id: 'naar-achteren',
        prompt: 'Kan het deel achter het laatste werkwoord staan?',
        buckets: ['kan achteraan', 'kan niet achteraan'],
        items: [
          { t: 'over Napoleon (Ik heb een boek gelezen over Napoleon.)', b: 0 },
          { t: 'dat ik kom (Ik heb gezegd dat ik kom.)', b: 0 },
          { t: 'een boek (Ik heb gelezen een boek.)', b: 1 },
          { t: 'dan zijn broer (Hij is groter geweest dan zijn broer.)', b: 0 },
          { t: 'rood (Ik heb de deur geverfd rood.)', b: 1 },
          { t: 'op de bus (Ik heb gewacht op de bus.)', b: 0 },
          { t: 'op (Ik heb gebeld hem op.)', b: 1 },
          { t: 'om te slapen (Ik ben naar huis gegaan om te slapen.)', b: 0 },
        ],
        why: 'Voorzetselgroepen, bijzinnen, vergelijkingen met dan en om te-groepen kunnen naar achteren. Een lijdend voorwerp, een bijvoeglijk naamwoord als resultaat (rood) en een scheidbaar deel (op) blijven in het middenveld.',
      },
      {
        kind: 'choice',
        id: 'leesbaar',
        prompt: 'Welke zin is het best leesbaar?',
        before: '',
        after: '',
        options: [
          'De directie heeft besloten dat het kantoor in juni sluit.',
          'De directie heeft dat het kantoor in juni sluit besloten.',
          'De directie heeft in juni dat het kantoor sluit besloten.',
        ],
        answer: 'De directie heeft besloten dat het kantoor in juni sluit.',
        why: 'De bijzin staat achter besloten. De andere twee zetten de bijzin in het middenveld, en dat is in het Nederlands niet alleen zwaar maar ook fout.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Woordvolgorde in de talen van de wereld',
        panels: [
          {
            text: 'Joseph Greenberg (1963) vergeleek de woordvolgorde van zo’n dertig talen en vond *correlaties*. Talen met het werkwoord vóór het lijdend voorwerp (VO, zoals Engels) hebben meestal voorzetsels: *in the house*. Talen met OV (zoals Japans en Turks) hebben meestal achterzetsels: Japans *ie ni*, letterlijk ‘huis in’. Later formuleerden taalkundigen dat als *kernrichting*: een taal zet de kern meestal steeds aan dezelfde kant van zijn complement. Matthew Dryer (1992) toetste die correlaties op een veel grotere steekproef.',
            rule: 'Greenberg (1963): woordvolgordes hangen samen. VO gaat vaak met voorzetsels, OV met achterzetsels.',
            lab: {
              label: 'Tik een taal',
              chips: [
                { k: 'Engels', out: 'VO · voorzetsels · kern voorop', note: 'read a book, in the house.' },
                { k: 'Japans', out: 'OV · achterzetsels · kern achteraan', note: 'hon o yomu (boek lezen), ie ni (huis in).' },
                { k: 'Nederlands', out: 'OV in de bijzin · vooral voorzetsels · gemengd', note: 'omdat ik een boek lees, in het huis, maar ook de berg op.' },
              ],
            },
          },
          {
            text: 'Het Nederlands is gemengd. In de bijzin staat het werkwoord achteraan: *omdat ik een boek lees*. Jan Koster (1975) betoogde daarom dat het Nederlands in de basis een OV-taal is; in de hoofdzin schuift de persoonsvorm naar de tweede plek. Maar de voorzetselgroep heeft meestal de kern voorop (*op de berg*), en soms achteraan, met een *achterzetsel* (*de berg op*).',
            rule: 'Nederlands: werkwoordgroep met de kern achteraan, voorzetselgroep meestal met de kern voorop.',
            bracket: {
              q: 'Bouw de voorzetselgroep met een achterzetsel',
              words: true,
              tree: '[[de [hoge berg]] op]',
              nodes: [
                { w: 'hoge berg', cat: 'N′', note: 'hoge bepaalt berg.' },
                { w: 'de hoge berg', cat: 'NP', note: 'De hele naamwoordgroep is het complement.' },
                { w: 'de hoge berg op', cat: 'PP', note: 'De kern op staat achteraan: kern-finaal, zoals het werkwoord in de bijzin.' },
              ],
              traps: [{ w: 'berg op', note: 'op neemt de hele naamwoordgroep, de hoge berg, als complement, niet alleen berg.' }],
              note: 'Dezelfde boom als op de hoge berg, maar gespiegeld: de kern staat rechts.',
            },
            quiz: {
              q: 'In welke zin staat het werkwoord na het lijdend voorwerp (OV)?',
              options: ['omdat ik een boek lees', 'ik lees een boek', 'lees jij een boek?'],
              answer: 'omdat ik een boek lees',
              why: 'In de bijzin staat het werkwoord achteraan. In de hoofdzin en de vraag is de persoonsvorm naar voren geschoven.',
            },
          },
          {
            text: 'Waarom zouden talen zo consequent zijn? John Hawkins (1994, *A Performance Theory of Order and Constituency*) gaf een verklaring vanuit de lezer. Zijn principe van *Early Immediate Constituents* zegt: een volgorde is beter naarmate je de directe delen van een groep sneller herkent. In een taal met de kern voorop betekent dat: kort vóór lang. Otto Behaghel had in 1909 al zijn ‘wet van de groeiende leden’ opgesteld: het langere deel komt later. Hawkins voorspelt ook het omgekeerde: in talen met de kern achteraan, zoals Japans, juist lang vóór kort.',
            rule: 'Hawkins (1994): kies de volgorde waarin de lezer de delen van een groep zo snel mogelijk overziet.',
            quiz: {
              q: 'Welke volgorde voorspelt Hawkins voor een taal met de kern achteraan, zoals Japans?',
              options: ['lang vóór kort', 'kort vóór lang', 'geen voorkeur'],
              answer: 'lang vóór kort',
              why: 'Daar komt de kern aan het eind. Als de lange groep vooraan staat, liggen de korte groep en de kern dicht bij elkaar en overzie je het geheel sneller.',
            },
            deep: {
              q: 'Wat heeft extrapositie hiermee te maken?',
              a: 'Het Nederlands heeft de kern van de werkwoordgroep achteraan, maar de meeste andere groepen voorop. Een zware groep in het middenveld rekt het stuk tussen persoonsvorm en laatste werkwoord op. Door *extrapositie* staat het laatste werkwoord eerder, en zie je de opbouw van de zin sneller: precies wat Hawkins voorspelt.',
            },
          },
        ],
      },
      {
        kind: 'rewrite',
        id: 'extrapositie',
        prompt: 'Maak het middenveld licht: zet de zware voorzetselgroep achter het laatste werkwoord.',
        source: 'Ik heb gisteren een boek over de rol van Nederlandse kooplieden in de handel met Japan gelezen.',
        accept: [
          'Ik heb gisteren een boek gelezen over de rol van Nederlandse kooplieden in de handel met Japan.',
          'Gisteren heb ik een boek gelezen over de rol van Nederlandse kooplieden in de handel met Japan.',
        ],
        why: 'over de rol van ... met Japan is de zware nabepaling van boek. Achter gelezen staat hij niet meer tussen de werkwoorden.',
      },
      {
        kind: 'rewrite',
        id: 'inbedding',
        prompt: 'Haal de centrale inbedding weg. Houd de betekenis, verander zo weinig mogelijk.',
        source: 'De vrouw die de mannen die de hond aaiden zag, lachte.',
        accept: [
          'De vrouw die de mannen zag die de hond aaiden, lachte.',
          'De vrouw zag de mannen die de hond aaiden en lachte.',
          'De vrouw zag de mannen die de hond aaiden. Ze lachte.',
          'De vrouw zag de mannen die de hond aaiden, en ze lachte.',
          'De vrouw zag de mannen die de hond aaiden en ze lachte.',
        ],
        why: 'Het kleinst mogelijke ingreep: zet de binnenste bijzin achter zag (extrapositie). Of splits in twee hoofdzinnen. Dan hoeft de lezer nooit meer dan één onderwerp vast te houden.',
      },
      {
        kind: 'sort',
        id: 'kernrichting',
        prompt: 'Staat de kern voorop of achteraan?',
        buckets: ['kern voorop', 'kern achteraan'],
        items: [
          { t: 'op de berg', b: 0 },
          { t: 'de berg op', b: 1 },
          { t: 'een boek lezen', b: 1 },
          { t: 'de vernietiging van de stad', b: 0 },
          { t: 'naar huis', b: 0 },
          { t: '(omdat hij) de krant leest', b: 1 },
          { t: 'met de trein', b: 0 },
          { t: 'het bos in', b: 1 },
        ],
        why: 'Voorzetselgroepen en naamwoordgroepen: kern voorop. Werkwoordgroepen in de bijzin of met een infinitief, en groepen met een achterzetsel: kern achteraan. Het Nederlands is gemengd.',
      },
      {
        kind: 'swipe',
        id: 'typologie',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'OV-talen hebben meestal achterzetsels.', ok: true, why: 'Een van de correlaties van Greenberg (1963).' },
          {
            t: 'Het Nederlands heeft overal de kern voorop.',
            ok: false,
            fix: 'het is gemengd',
            why: 'De werkwoordgroep heeft de kern achteraan: omdat ik een boek lees.',
          },
          { t: 'Een bijzin in het middenveld is in het Nederlands meestal fout.', ok: true, why: 'Ik heb gezegd dat ik kom, niet ik heb dat ik kom gezegd.' },
          {
            t: 'Hawkins voorspelt kort vóór lang voor elke taal.',
            ok: false,
            fix: 'alleen voor talen met de kern voorop',
            why: 'In talen met de kern achteraan voorspelt hij lang vóór kort.',
          },
          {
            t: 'Centrale inbedding is ongrammaticaal.',
            ok: false,
            fix: 'grammaticaal, maar moeilijk',
            why: 'Miller en Chomsky (1963): de grammatica staat het toe, het geheugen protesteert.',
          },
          { t: 'Extrapositie maakt het middenveld lichter.', ok: true, why: 'Het laatste werkwoord komt eerder.' },
        ],
      },
    ],
  },
];
