import type { LessonInput } from '../schema';

/** De woordgroep: nevenschikking in de groep, congruentie en samentrekking (bachelor, p11). */
export const GROEP_EXTRA_LESSONS: LessonInput[] = [
  {
    id: 'p11',
    stage: 'bachelor',
    domain: 'syn',
    also: ['orth'],
    title: 'Nevenschikking in de groep',
    skill: 'Zinsbouw',
    icon: '&',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Groepen aan elkaar knopen',
        panels: [
          {
            text: '*Peper en zout*, *brood en spelen*, *Jan en ik*: het Nederlands knoopt graag dingen aan elkaar. Maar niet alles past bij alles, net als sokken. Twee of meer groepen die je met een *nevenschikkend voegwoord* (*en*, *of*, *maar*) verbindt, heten samen een *nevenschikking*. Het geheel is zelf weer één groep: je kunt het vooraan zetten (*Mijn zus en haar vriend kochten brood*) en vervangen door één voornaamwoord (*zij*).',
            rule: 'Nevenschikking: groepen van dezelfde soort, verbonden door en, maar of een ander nevenschikkend voegwoord, vormen samen één grotere groep.',
            phrase: {
              q: 'Vind de twee nevenschikkingen van naamwoordgroepen: tik telkens het hele geheel, met en erin',
              sentence: 'Mijn zus en haar vriend kochten brood en kaas op de markt.',
              groups: [
                {
                  span: [0, 4],
                  cat: 'nevenschikking van naamwoordgroepen',
                  head: 2,
                  note: 'Mijn zus + en + haar vriend. Samen het onderwerp: je kunt het vervangen door zij.',
                },
                {
                  span: [6, 8],
                  cat: 'nevenschikking van naamwoordgroepen',
                  head: 7,
                  note: 'brood + en + kaas. Samen het lijdend voorwerp: wat kochten ze? Brood en kaas.',
                },
              ],
              traps: [
                { span: [1, 2], note: 'zus en: daar stop je midden in de groep. Het tweede lid haar vriend hoort er ook bij.' },
                { span: [4, 6], note: 'vriend kochten brood: dat loopt over de grens van twee zinsdelen heen.' },
              ],
              note: 'Elke nevenschikking is één zinsdeel. In de verdieping zie je waarom veel taalkundigen en als kern van het geheel zien.',
            },
          },
          {
            text: 'De delen van een nevenschikking heten *leden*. De leden moeten bij elkaar passen: meestal zijn ze van dezelfde soort en hebben ze dezelfde functie in de zin. *trots op haar zus en blij met de prijs* (twee bijvoeglijke groepen), *in de keuken of in de tuin* (twee voorzetselgroepen). Knoop je ongelijke dingen aan elkaar, dan krijg je een scheve zin: *Ze leest graag en romans* (fout).',
            rule: 'De leden van een nevenschikking passen bij elkaar: dezelfde soort groep, dezelfde functie.',
            quiz: {
              q: 'Welke nevenschikking is goed?',
              options: ['trots op haar zus en blij met de prijs', 'trots op haar zus en morgen', 'trots op haar zus en een fiets'],
              answer: 'trots op haar zus en blij met de prijs',
              why: 'Twee bijvoeglijke groepen met dezelfde functie. morgen is een bijwoord en een fiets een naamwoordgroep: die passen er niet naast.',
            },
          },
          {
            text: 'Een nevenschikking als onderwerp stuurt de persoonsvorm. Met *en* is het geheel meervoud: *Jan en Piet komen*. Staat *ik* of *wij* erin, dan neem je de wij-vorm: *Jan en ik gaan*. Er bestaan ook voegwoorden in twee delen, *correlatieve voegwoorden*: *zowel ... als*, *noch ... noch*, *of ... of*, *en ... en*. En let op de naamval: in *tussen jou en mij* staat *mij* na het voorzetsel *tussen*, ook al staat er een *en* tussen.',
            rule: 'Een nevenschikking verandert de naamval niet: tussen jou en mij, voor hem en haar.',
            lab: {
              label: 'Tik een onderwerp',
              chips: [
                { k: 'Jan en ik', out: 'gaan (wij-vorm)', note: 'Met en altijd meervoud; met ik erin de wij-vorm.' },
                { k: 'Jan of Piet', out: 'komt', note: 'Bij of met twee enkelvouden kies je het enkelvoud: één van de twee komt.' },
                { k: 'zowel Jan als Piet', out: 'komen (ook: komt)', note: 'Meervoud is gewoner, enkelvoud wordt ook goedgekeurd.' },
                { k: 'noch Jan noch Piet', out: 'komt of komen', note: 'Beide vormen zijn goed.' },
              ],
            },
          },
        ],
      },
      {
        kind: 'choice',
        id: 'congruentie',
        prompt: 'Kies de goede persoonsvorm.',
        before: 'Mijn broer en ik',
        after: 'morgen naar Utrecht.',
        options: ['gaan', 'ga', 'gaat'],
        answer: 'gaan',
        why: 'Mijn broer en ik is samen wij: dus de wij-vorm gaan.',
      },
      {
        kind: 'fix',
        id: 'tussen-jou-en-mij',
        prompt: 'Eén woord staat in de verkeerde vorm. Tik het aan en verbeter het.',
        sentence: 'Dit blijft echt tussen jou en ik.',
        wrong: 6,
        answer: 'mij',
        why: 'Na een voorzetsel staat een voorwerpsvorm: tussen jou en mij. De en verandert daar niets aan.',
      },
      {
        kind: 'sort',
        id: 'gelijk-of-scheef',
        prompt: 'Passen de leden van de nevenschikking bij elkaar?',
        buckets: ['goed nevengeschikt', 'scheef: ongelijke leden'],
        items: [
          { t: 'trots op haar zus en blij met de prijs', b: 0 },
          { t: 'Ze leest graag en romans.', b: 1 },
          { t: 'in de keuken of in de tuin', b: 0 },
          { t: 'Hij gaf mij en aan zijn moeder een boek.', b: 1 },
          { t: 'zowel de trein als de bus', b: 0 },
          { t: 'een boek over Rome en dat ik gisteren kocht', b: 1 },
          { t: 'snel maar zorgvuldig', b: 0 },
          { t: 'Ze belde gisteren en haar moeder.', b: 1 },
          { t: 'de rode en de blauwe fiets', b: 0 },
        ],
        why: 'Goed: telkens twee groepen van dezelfde soort met dezelfde functie. Scheef: een bijwoord naast een lijdend voorwerp (graag en romans, gisteren en haar moeder), een meewerkend voorwerp zonder aan naast een met aan (mij en aan zijn moeder), een voorzetselgroep naast een bijzin (over Rome en dat ik gisteren kocht).',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'De bouw van en, scheve paren en weggelaten stukken',
        panels: [
          {
            text: 'Hoe ziet de boom van *Jan en mijn zus* eruit? Als elke knoop twee takken heeft, moet *en* eerst met één lid samen. Een veelgebruikte analyse (onder anderen Johannessen, *Coordination*, 1998) maakt van het voegwoord de kern: *en* neemt het tweede lid als complement, en het eerste lid komt daarvoor. Het geheel heet dan een *&P*. Een aanwijzing: *en mijn zus* kan los achteraan komen (*Jan komt morgen, en mijn zus ook*), *Jan en* nooit.',
            bracket: {
              q: 'Bouw de nevenschikking van binnen naar buiten',
              words: true,
              tree: '[Jan [en [mijn zus]]]',
              nodes: [
                { w: 'mijn zus', cat: 'NP', note: 'Eerst het tweede lid: bezittelijk voornaamwoord + kern zus.' },
                { w: 'en mijn zus', cat: '&′', note: 'en neemt het tweede lid als complement, net als een voorzetsel zijn naamwoordgroep.' },
                { w: 'Jan en mijn zus', cat: '&P', note: 'Het eerste lid sluit aan. Het geheel is één groep, met en als kern.' },
              ],
              traps: [{ w: 'Jan en', note: 'en hoort eerst bij het tweede lid: en mijn zus kan los achteraan staan, Jan en nooit.' }],
              note: 'Een binaire boom: [Jan [en [mijn zus]]]. Zo krijgt ook de nevenschikking een kern.',
            },
          },
          {
            text: 'Al in *Syntactic Structures* (1957) gebruikte Chomsky nevenschikking als test: alleen echte groepen kun je met *en* verbinden. Toch is ‘dezelfde soort’ niet de hele waarheid. Sag, Gazdar, Wasow en Weisler (1985) bespraken zinnen als *Pat is wealthy and a Republican*: een bijvoeglijk naamwoord naast een naamwoordgroep. In het Nederlands: *Hij is ziek en een zeur*. Dat kan, omdat beide leden dezelfde *functie* hebben.',
            rule: 'Wat telt is vooral de functie: twee leden die dezelfde rol in de zin spelen, kun je nevenschikken.',
            quiz: {
              q: 'Waarom is ‘Hij is ziek en een zeur’ toch goed?',
              options: ['Beide leden zijn naamwoordelijk deel van het gezegde', 'Beide leden zijn naamwoordgroepen', 'Na is mag je alles nevenschikken'],
              answer: 'Beide leden zijn naamwoordelijk deel van het gezegde',
              why: 'ziek is een bijvoeglijk naamwoord, een zeur een naamwoordgroep. De soort verschilt, de functie is gelijk.',
            },
          },
          {
            text: 'In een nevenschikking laat je vaak iets weg dat al in het andere lid staat. In *de rode en de blauwe fiets* staat *fiets* maar één keer: je bedoelt *de rode fiets en de blauwe fiets*. Dat heet *ellips* (weglating). Laat je ook het tweede lidwoord weg, dan wordt het dubbelzinnig: *de rode en blauwe vlaggen* zijn rode vlaggen plus blauwe vlaggen, of vlaggen die rood met blauw zijn.',
            quiz: {
              q: 'Hoeveel lezingen heeft ‘de rode en blauwe vlaggen’?',
              options: ['één', 'twee'],
              answer: 'twee',
              why: 'Rode vlaggen en blauwe vlaggen (twee soorten), of vlaggen die elk rood en blauw zijn. Met de rode en de blauwe vlaggen blijft alleen de eerste lezing over.',
            },
          },
          {
            text: 'Ook binnen een woord kun je weglaten: *bus- en treinreizigers*, *voor- en nadelen*, *zon- en feestdagen*. Het streepje heet *weglatingsstreepje*. Het mag alleen bij een deel van een samenstelling, en het voorste deel moet precies zo zijn als in het hele woord: *schapen- en geitenkaas*, want het is *schapenkaas*. Bij losse woorden geen streepje: *grote en kleine letters*, *voor en na de wedstrijd*. Weglaten mag ook alleen als het weggelaten woord in beide leden echt hetzelfde is: *Hij heeft het geld gestolen en daarna gevlucht* is een *onjuiste samentrekking*, want *gevlucht* vraagt *is*.',
            rule: 'Samentrekken mag alleen als het weggelaten stuk in beide leden precies hetzelfde is.',
            quiz: {
              q: 'Welke schrijfwijze is goed?',
              options: ['in- en uitvoer', 'in en uitvoer', 'in- en -uitvoer'],
              answer: 'in- en uitvoer',
              why: 'invoer en uitvoer: het gedeelde deel voer valt één keer weg, en het streepje laat zien waar.',
            },
          },
        ],
      },
      {
        kind: 'rewrite',
        id: 'samentrekken',
        prompt: 'Schrijf korter met een weglatingsstreepje.',
        source: 'Op zondagen en op feestdagen rijdt de bus minder vaak.',
        accept: ['Op zon- en feestdagen rijdt de bus minder vaak.'],
        why: 'zondagen en feestdagen delen dagen: zon- en feestdagen. Het tweede op valt ook weg.',
      },
      {
        kind: 'proofread',
        id: 'nalezen',
        prompt: 'Lees het bericht na',
        intro: 'Er zitten vier fouten in. Tik ze aan.',
        tokens: [
          { t: 'Alle' },
          { t: 'bus', fix: 'bus-', why: 'busreizigers en treinreizigers: het weggelaten deel krijgt een streepje.' },
          { t: 'en' },
          { t: 'treinreizigers' },
          { t: 'krijgen' },
          { t: 'op' },
          { t: 'zon-' },
          { t: 'en' },
          { t: 'feestdagen' },
          { t: 'korting.' },
          { t: 'Mijn' },
          { t: 'broer' },
          { t: 'en' },
          { t: 'ik' },
          { t: 'reist', fix: 'reizen', why: 'Mijn broer en ik is wij: de wij-vorm reizen.' },
          { t: 'vaak' },
          { t: 'samen,' },
          { t: 'maar' },
          { t: 'dat' },
          { t: 'blijft' },
          { t: 'tussen' },
          { t: 'jou' },
          { t: 'en' },
          { t: 'ik.', fix: 'mij.', why: 'Na tussen een voorwerpsvorm: tussen jou en mij.' },
          { t: 'Neem' },
          { t: 'grote-', fix: 'grote', why: 'grote is een los woord, geen deel van een samenstelling: grote en kleine tassen.' },
          { t: 'en' },
          { t: 'kleine' },
          { t: 'tassen' },
          { t: 'mee.' },
        ],
      },
      {
        kind: 'swipe',
        id: 'nevenschikking-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Jan en ik gaan morgen naar de markt.', ok: true, why: 'Met ik erin de wij-vorm.' },
          {
            t: 'Voor- en na de wedstrijd is er koffie.',
            ok: false,
            fix: 'Voor en na de wedstrijd',
            why: 'voor en na zijn losse woorden, geen delen van een samenstelling: geen streepje.',
          },
          {
            t: 'In de winkel verkopen ze schaap- en geitenkaas.',
            ok: false,
            fix: 'schapen- en geitenkaas',
            why: 'Het voorste deel is precies zoals in schapenkaas.',
          },
          {
            t: 'Hij heeft het geld gestolen en daarna gevlucht.',
            ok: false,
            fix: 'en is daarna gevlucht',
            why: 'gevlucht vraagt is, niet heeft: dat hulpwerkwoord mag je niet samentrekken.',
          },
          { t: 'In de rode en de blauwe fiets staat fiets maar één keer: dat is ellips.', ok: true, why: 'Je bedoelt de rode fiets en de blauwe fiets.' },
          { t: 'In Jan en mijn zus hoort en eerst bij mijn zus.', ok: true, why: 'en mijn zus kan los achteraan staan: Jan komt, en mijn zus ook.' },
        ],
      },
      {
        kind: 'bet',
        id: 'noch-noch',
        prompt: 'Noch Jan noch Piet ___ het gedaan. Welke vorm is goed?',
        options: ['alleen heeft', 'alleen hebben', 'heeft en hebben zijn allebei goed'],
        answer: 'heeft en hebben zijn allebei goed',
        why: 'Bij noch ... noch mag het enkelvoud (geen van beiden) en het meervoud (de twee samen). Bij en is het altijd meervoud.',
      },
    ],
  },
];

/** De woordgroep, master p12–p14: X-bar-theorie, structurele ambiguïteit en de DP-hypothese. */
export const GROEP_MASTER_LESSONS: LessonInput[] = [
  {
    id: 'p12',
    stage: 'master',
    domain: 'syn',
    title: 'X-bar: één bouwplan',
    skill: 'Zinsbouw',
    icon: 'X′',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Kern, tussenlaag en volle groep',
        panels: [
          {
            text: 'Naamwoordgroep, voorzetselgroep, bijvoeglijke groep: drie soorten, één bouwtekening. Taalkundigen werken net als een meubelwinkel: één handleiding voor alle kasten. Die handleiding heet *X-bar-theorie*. Chomsky stelde haar voor in 1970 (*Remarks on Nominalization*), Jackendoff werkte haar uit in *X-bar Syntax* (1977). De X staat voor elke kern: N, A, P of V. Elke groep heeft drie niveaus: de kern *X*, een tussenlaag *X′* (spreek uit: X-bar) en de volle groep *XP*.',
            rule: 'Elke groep heeft dezelfde bouw: kern X, tussenlaag X′, volle groep XP.',
            bracket: {
              q: 'Bouw de naamwoordgroep van binnen naar buiten',
              words: true,
              tree: '[het [boek [over Rome]]]',
              nodes: [
                { w: 'over Rome', cat: 'PP', note: 'Een voorzetselgroep: kern over, complement Rome.' },
                { w: 'boek over Rome', cat: 'N′', note: 'De kern boek neemt zijn complement: waarover gaat het boek?' },
                { w: 'het boek over Rome', cat: 'NP', note: 'Het lidwoord sluit de groep af: de volle naamwoordgroep.' },
              ],
              traps: [{ w: 'het boek', note: 'In X-bar komt het complement eerst bij de kern. het sluit pas als laatste aan.' }],
              note: 'Drie lagen: N (boek), N′ (boek over Rome), NP (het boek over Rome).',
            },
          },
          {
            text: 'Binnen die bouw heeft elk stuk een vaste plek. Het *complement* is de zus van de kern X: samen maken ze X′. Een *adjunct* (bepaling) is de zus van X′ en maakt weer een X′: zo kun je bepalingen eindeloos stapelen. Dat heet *recursie*. De *specificeerder* is de zus van de bovenste X′ en sluit de XP af. Daarom staat het complement altijd het dichtst bij de kern: *de student natuurkunde met lang haar*, niet *de student met lang haar natuurkunde* (fout).',
            bracket: {
              q: 'Bouw de groep: eerst het complement, dan de bepaling',
              words: true,
              tree: '[de [[student natuurkunde] [met [lang haar]]]]',
              nodes: [
                { w: 'student natuurkunde', cat: 'N′', note: 'Kern + complement: natuurkunde zegt wat voor student, het hoort bij de betekenis van student.' },
                { w: 'lang haar', cat: 'NP', note: 'Een naamwoordgroep met een bijvoeglijke bepaling.' },
                { w: 'met lang haar', cat: 'PP', note: 'De voorzetselgroep die als bepaling dient.' },
                { w: 'student natuurkunde met lang haar', cat: 'N′', note: 'Adjunct bij N′ geeft weer een N′. Je kunt er nog een bepaling achter hangen.' },
                { w: 'de student natuurkunde met lang haar', cat: 'NP', note: 'De specificeerder de sluit de groep af.' },
              ],
              traps: [{ w: 'natuurkunde met', note: 'natuurkunde hoort eerst bij zijn kern student; met hoort bij lang haar.' }],
              note: 'Complement als zus van N, adjunct als zus van N′, specificeerder als zus van de bovenste N′.',
            },
            quiz: {
              q: 'Waar hangt een complement in X-bar-theorie?',
              options: ['als zus van de kern X', 'als zus van X′', 'als zus van XP'],
              answer: 'als zus van de kern X',
              why: 'Kern + complement = X′. Een adjunct is de zus van X′, een specificeerder sluit de XP af.',
            },
          },
          {
            text: 'Het mooie is dat hetzelfde plan voor elke soort groep werkt. In een bijvoeglijke groep is *heel* de specificeerder en *op zijn dochter* het complement: *heel trots op zijn dochter*. In een voorzetselgroep: *vlak boven de deur*. In een werkwoordgroep: *het boek lezen*. Drie regels zijn genoeg: XP → specificeerder + X′; X′ → X′ + adjunct; X′ → X + complement.',
            rule: 'Drie regels voor alle groepen: XP → spec X′, X′ → X′ adjunct, X′ → X complement.',
            lab: {
              label: 'Tik een soort groep',
              chips: [
                { k: 'NP', out: 'de [student natuurkunde]', note: 'Spec de, kern student, complement natuurkunde.' },
                { k: 'AP', out: 'heel [trots op zijn dochter]', note: 'Spec heel (een graadwoord), kern trots, complement op zijn dochter.' },
                { k: 'PP', out: 'vlak [boven de deur]', note: 'Spec vlak, kern boven, complement de deur.' },
                { k: 'VP', out: '[het boek] lezen', note: 'Complement het boek, kern lezen: hier staat de kern achteraan.' },
              ],
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'rol',
        prompt: 'Welke plek heeft het genoemde stuk in de groep na de dubbele punt?',
        buckets: ['complement (zus van X)', 'adjunct (zus van X′)', 'specificeerder (sluit XP af)'],
        items: [
          { t: 'natuurkunde in: de student natuurkunde', b: 0 },
          { t: 'met lang haar in: de student met lang haar', b: 1 },
          { t: 'de in: de student', b: 2 },
          { t: 'op zijn dochter in: trots op zijn dochter', b: 0 },
          { t: 'heel in: heel trots', b: 2 },
          { t: 'vlak in: vlak boven de deur', b: 2 },
          { t: 'de deur in: boven de deur', b: 0 },
          { t: 'in de tuin in: het boek in de tuin lezen', b: 1 },
          { t: 'gisteren in: gisteren het boek lezen', b: 1 },
          { t: 'het boek in: het boek lezen', b: 0 },
        ],
        why: 'Complementen vult de kern zelf in (student van wat, trots op wie, boven wat, lezen wat). Adjuncten voegen iets toe en kun je stapelen. Graadwoorden en lidwoorden sluiten de groep af. In de les over de DP-hypothese krijgt het lidwoord een andere plek.',
      },
      {
        kind: 'choice',
        id: 'recursie',
        prompt: 'Hoeveel N′-lagen heeft ‘de student natuurkunde met lang haar uit Gent’?',
        before: '',
        after: '',
        options: ['één', 'twee', 'drie'],
        answer: 'drie',
        why: 'student natuurkunde (kern + complement), plus met lang haar, plus uit Gent: elke bepaling maakt een nieuwe N′. Dat is recursie.',
      },
      {
        kind: 'bet',
        id: 'volgorde',
        prompt: 'Welke groep klinkt natuurlijk?',
        options: ['een leraar Frans met een baard', 'een leraar met een baard Frans'],
        answer: 'een leraar Frans met een baard',
        why: 'Frans is het complement van leraar (leraar van welk vak) en staat dus het dichtst bij de kern. met een baard is een bepaling en komt daarna.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Waar staat de kern?',
        panels: [
          {
            text: 'X-bar zegt niet of de kern links of rechts van zijn complement staat. Talen kiezen, en het Nederlands kiest gemengd. De voorzetselgroep is *kop-initieel*: kern vooraan (*op de tafel*), behalve bij achterzetsels (*de trap op*). De naamwoordgroep ook: *de student natuurkunde*. Maar de werkwoordgroep is *kop-finaal*: in de bijzin staat het werkwoord achter zijn complement: *dat zij een boek over Rome las*.',
            phrase: {
              q: 'Vind de kleinste werkwoordgroep met kern las, de naamwoordgroep met kern boek en de voorzetselgroep',
              sentence: 'Ik weet dat zij gisteren een boek over Rome las.',
              groups: [
                { span: [5, 9], cat: 'werkwoordgroep', head: 9, note: 'Complement een boek over Rome, kern las achteraan: kop-finaal.' },
                { span: [5, 8], cat: 'naamwoordgroep', head: 6, note: 'Kern boek vooraan, complement over Rome erachter: kop-initieel.' },
                { span: [7, 8], cat: 'voorzetselgroep', head: 7, note: 'Kern over vooraan: kop-initieel.' },
              ],
              traps: [{ span: [8, 9], note: 'Rome las: Rome hoort bij over. las neemt de hele naamwoordgroep als complement.' }],
              note: 'In één bijzin: twee groepen met de kern vooraan, één met de kern achteraan.',
            },
            quiz: {
              q: 'Waar staat de kern van de werkwoordgroep in een Nederlandse bijzin?',
              options: ['achteraan, na het complement', 'vooraan, voor het complement', 'altijd op de tweede plaats'],
              answer: 'achteraan, na het complement',
              why: 'dat zij een boek las: complement een boek, kern las. De tweede plaats geldt voor de persoonsvorm in de hoofdzin.',
            },
          },
          {
            text: 'Maar in de hoofdzin staat het werkwoord toch vooraan: *Zij las een boek*? Jan Koster betoogde in *Dutch as an SOV language* (1975) dat de werkwoordgroep onderliggend kop-finaal is. In de hoofdzin verplaatst de persoonsvorm naar de tweede plaats. Het bewijs zit in scheidbare werkwoorden: *dat zij haar moeder opbelt*, maar *Zij belt haar moeder op*. Het deeltje *op* blijft achter op de oude plek van het werkwoord, achteraan.',
            rule: 'Nederlands: werkwoordgroep kop-finaal, de persoonsvorm verhuist in de hoofdzin naar plek twee.',
            quiz: {
              q: 'Wat laat ‘Zij belt haar moeder op’ zien?',
              options: [
                'Het werkwoord begon achteraan; het deeltje op bleef daar staan',
                'Deeltjes staan altijd aan het eind van een zin',
                'De werkwoordgroep is kop-initieel',
              ],
              answer: 'Het werkwoord begon achteraan; het deeltje op bleef daar staan',
              why: 'In de bijzin staat opbelt nog in één stuk achteraan. In de hoofdzin verhuist alleen belt.',
            },
          },
          {
            text: 'Waarom altijd twee takken per knoop? Richard Kayne verdedigde in *Connectedness and Binary Branching* (1984) dat bomen strikt *binair* zijn. In een binaire boom moet je kiezen wat eerst samengaat, en dat sluit goed aan bij wat de tests uit de bachelorlessen laten zien. Bouw zelf de werkwoordgroep van een bijzin: eerst het complement met de kern, dan de bepaling.',
            bracket: {
              q: 'Bouw de werkwoordgroep (zoals in: dat ik gisteren een boek las)',
              words: true,
              tree: '[gisteren [[een boek] lezen]]',
              nodes: [
                { w: 'een boek', cat: 'NP', note: 'Eerst de naamwoordgroep afmaken.' },
                { w: 'een boek lezen', cat: 'V′', note: 'Complement links, kern lezen rechts: kop-finaal.' },
                { w: 'gisteren een boek lezen', cat: 'V′', note: 'De bepaling gisteren hangt aan V′ en geeft weer een V′.' },
              ],
              traps: [{ w: 'boek lezen', note: 'een hoort bij boek: het werkwoord neemt de hele naamwoordgroep als complement.' }],
              note: 'Ook in de werkwoordgroep: complement dicht bij de kern, bepaling erbuiten.',
            },
            deep: {
              q: 'Is X-bar nog de laatste stand?',
              a: 'Niet helemaal. Kayne ging in *The Antisymmetry of Syntax* (1994) verder: volgens hem is elke taal onderliggend kop-initieel, en ontstaat kop-finale volgorde door verplaatsing. En Chomsky verving in het Minimalistisch Programma (1995) de vaste niveaus door *Merge* (*bare phrase structure*): X′ en XP zijn geen aparte bouwstenen meer, maar volgen uit hoe vaak je samenvoegt. Het idee van kern, complement en bepaling bleef overeind.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'kop-positie',
        prompt: 'Staat de kern vooraan of achteraan in de groep?',
        buckets: ['kern vooraan (kop-initieel)', 'kern achteraan (kop-finaal)'],
        items: [
          { t: 'op de tafel', b: 0 },
          { t: 'de trap op', b: 1 },
          { t: 'het boek lezen (zoals in een bijzin)', b: 1 },
          { t: 'de student natuurkunde', b: 0 },
          { t: 'trots op zijn dochter', b: 0 },
          { t: 'op zijn dochter trots', b: 1 },
          { t: 'de bal schoppen', b: 1 },
          { t: 'met lang haar', b: 0 },
          { t: 'de berg af', b: 1 },
        ],
        why: 'Voorzetsels en zelfstandige naamwoorden staan vooraan. Werkwoorden en achterzetsels staan achter hun complement. Een bijvoeglijk naamwoord kan allebei.',
      },
      {
        kind: 'rewrite',
        id: 'complement-eerst',
        prompt: 'Zet het complement direct naast zijn kern.',
        source: 'Ik sprak de student met de rode jas geneeskunde.',
        accept: ['Ik sprak de student geneeskunde met de rode jas.'],
        why: 'geneeskunde is het complement van student en hoort er direct naast. met de rode jas is een bepaling en komt daarna.',
      },
      {
        kind: 'choice',
        id: 'regel',
        prompt: 'Welke regel hangt een bepaling (adjunct) aan de groep?',
        before: '',
        after: '',
        options: ['X′ → X′ + adjunct', 'X′ → X + complement', 'XP → specificeerder + X′'],
        answer: 'X′ → X′ + adjunct',
        why: 'Links en rechts van de pijl staat X′: daardoor kun je de regel steeds opnieuw toepassen. Zo stapel je bepalingen.',
      },
      {
        kind: 'swipe',
        id: 'xbar-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'In X-bar-theorie heeft elke groep een kern.', ok: true, why: 'Elke XP is een projectie van een X.' },
          {
            t: 'Een bepaling staat dichter bij de kern dan een complement.',
            ok: false,
            fix: 'het complement staat het dichtst bij de kern',
            why: 'Kern + complement = X′, de bepaling komt daarbuiten.',
          },
          { t: 'Bepalingen kun je stapelen; dat heet recursie.', ok: true, why: 'X′ → X′ + adjunct kun je steeds opnieuw toepassen.' },
          {
            t: 'De Nederlandse voorzetselgroep heeft de kern altijd vooraan.',
            ok: false,
            fix: 'meestal, maar bij achterzetsels achteraan',
            why: 'de trap op: kern op achteraan.',
          },
          { t: 'Koster (1975) betoogde dat de Nederlandse werkwoordgroep onderliggend kop-finaal is.', ok: true, why: 'Dutch as an SOV language.' },
          {
            t: 'In de hoofdzin staat de persoonsvorm nog op zijn oorspronkelijke plek.',
            ok: false,
            fix: 'hij is naar de tweede plaats verplaatst',
            why: 'Het deeltje in Zij belt haar moeder op verraadt de oude plek.',
          },
        ],
      },
    ],
  },
  {
    id: 'p13',
    stage: 'master',
    domain: 'syn',
    also: ['sem'],
    title: 'Twee bomen, één zin',
    skill: 'Zinsbouw',
    icon: '[?]',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Structurele ambiguïteit',
        panels: [
          {
            text: '*Ik zag de man met de verrekijker.* Wie had de verrekijker: jij of hij? Dezelfde woorden, twee bomen, en ruzie op de vogelkijkhut. Bij *lexicale ambiguïteit* heeft één woord twee betekenissen (*bank*). Bij *structurele ambiguïteit* zijn alle woorden duidelijk, maar kun je ze op twee manieren groeperen. Hier: hangt *met de verrekijker* aan de werkwoordgroep (ik keek erdoor) of aan *man* (hij had er een)?',
            rule: 'Structurele ambiguïteit: dezelfde woorden, twee manieren om ze te groeperen.',
            phrase: {
              q: 'Lees de zin zo dat de man de verrekijker heeft. Vind de naamwoordgroep met kern man en de voorzetselgroep',
              sentence: 'Ik zag de man met de verrekijker.',
              groups: [
                { span: [2, 6], cat: 'naamwoordgroep', head: 3, note: 'In deze lezing hoort met de verrekijker bij man: de man met de verrekijker.' },
                { span: [4, 6], cat: 'voorzetselgroep', head: 4, note: 'Kern met, complement de verrekijker.' },
              ],
              traps: [{ span: [2, 3], note: 'de man alleen is de groep in de andere lezing, als ik door de verrekijker keek.' }],
              note: 'In de andere lezing is de naamwoordgroep alleen de man, en hangt de voorzetselgroep aan zag.',
            },
          },
          {
            text: 'Teken je de twee lezingen als boom, dan zie je het verschil. Lezing 1 (ik keek erdoor): *[zag [de man]] [met de verrekijker]*. De voorzetselgroep is een bepaling bij de werkwoordgroep. Lezing 2 (hij had er een): *[de [man [met de verrekijker]]]*. De voorzetselgroep is een bepaling bij *man*, binnen de naamwoordgroep. Bouw lezing 2.',
            bracket: {
              q: 'Bouw de naamwoordgroep van lezing 2',
              words: true,
              tree: '[de [man [met [de verrekijker]]]]',
              nodes: [
                { w: 'de verrekijker', cat: 'NP', note: 'Het complement van met.' },
                { w: 'met de verrekijker', cat: 'PP', note: 'Kern met: een voorzetselgroep.' },
                { w: 'man met de verrekijker', cat: 'N′', note: 'De voorzetselgroep hangt aan man: hij heeft de verrekijker.' },
                { w: 'de man met de verrekijker', cat: 'NP', note: 'Eén naamwoordgroep: het lijdend voorwerp van zag.' },
              ],
              traps: [{ w: 'de man', note: 'In lezing 2 is de man geen eenheid: met de verrekijker hangt aan man, binnen de groep.' }],
              note: 'In lezing 1 zou je wel eerst de man maken en de voorzetselgroep pas bij zag hangen.',
            },
          },
          {
            text: 'Ook nevenschikking kan twee bomen geven. *oude mannen en vrouwen*: zijn de vrouwen ook oud? Lezing A: *[oude [mannen en vrouwen]]*, het bijvoeglijk naamwoord geldt voor allebei. Lezing B: *[[oude mannen] en vrouwen]*, alleen de mannen zijn oud. Het verschil heet *bereik* (*scope*): over welk stuk strekt *oude* zich uit?',
            lab: {
              label: 'Tik een lezing',
              chips: [
                { k: 'Lezing A', out: '[oude [mannen en vrouwen]]', note: 'oude heeft bereik over de hele nevenschikking: iedereen is oud.' },
                { k: 'Lezing B', out: '[[oude mannen] en vrouwen]', note: 'oude heeft alleen bereik over mannen.' },
                {
                  k: 'Eenduidig B',
                  out: 'vrouwen en oude mannen',
                  note: 'Zet de bepaling achteraan bij het lid waar ze bij hoort: nu kan oude niet meer over vrouwen gaan.',
                },
              ],
            },
            quiz: {
              q: 'Welke groep heeft alleen lezing B (alleen de mannen zijn oud)?',
              options: ['vrouwen en oude mannen', 'oude mannen en vrouwen', 'de oude mannen en vrouwen'],
              answer: 'vrouwen en oude mannen',
              why: 'oude staat nu alleen voor mannen en kan zijn bereik niet over vrouwen uitstrekken.',
            },
          },
        ],
      },
      {
        kind: 'ambiguity',
        id: 'verrekijker',
        prompt: 'Eén zin, twee bomen',
        intro: 'Kies een lezing en zoek de zin die alleen dát kan betekenen.',
        sentence: 'Ik zag de man met de verrekijker.',
        meanings: [
          {
            id: 'instrument',
            label: 'Ik keek door de verrekijker',
            highlight: ['zag', 'met de verrekijker'],
            right: 'Klopt. Vooraan hangt met de verrekijker aan de werkwoordgroep.',
          },
          {
            id: 'bezit',
            label: 'De man had een verrekijker',
            highlight: ['de man met de verrekijker'],
            right: 'Klopt. Een bijzin bij man laat maar één lezing over.',
          },
        ],
        options: [
          { t: 'Met de verrekijker zag ik de man.', fits: 'instrument' },
          { t: 'Ik zag de man die een verrekijker had.', fits: 'bezit' },
          { t: 'Ik zag gisteren de man met de verrekijker.', fits: null, note: 'Nog steeds allebei mogelijk: gisteren verandert niets aan de groepering.' },
        ],
        done: {
          title: 'Kies de boom',
          text: 'Een dubbelzinnige zin los je op door de groepering zichtbaar te maken: verplaats de groep of maak er een bijzin van.',
        },
      },
      {
        kind: 'sort',
        id: 'soort-ambiguiteit',
        prompt: 'Wat voor dubbelzinnigheid is het?',
        buckets: ['structureel (twee bomen)', 'lexicaal (één woord, twee betekenissen)'],
        items: [
          { t: 'Hij sloeg de hond met de stok.', b: 0 },
          { t: 'We spraken af bij de bank.', b: 1 },
          { t: 'oude mannen en vrouwen', b: 0 },
          { t: 'Die kraan is kapot.', b: 1 },
          { t: 'Zij bekeek het schilderij in de kamer.', b: 0 },
          { t: 'Het blad viel op de grond.', b: 1 },
          { t: 'de leraar van de school in Gent', b: 0 },
          { t: 'Ik heb een bal gekocht.', b: 1 },
          { t: 'Ik zag de man met de verrekijker.', b: 0 },
        ],
        why: 'Structureel: een voorzetselgroep of bijvoeglijk naamwoord kan op twee plekken hangen. Lexicaal: kraan (voor water of om te hijsen), blad (van een boom of om op te dienen), bal (om te spelen of om te dansen), bank (om op te zitten of voor geld).',
      },
      {
        kind: 'rewrite',
        id: 'eenduidig',
        prompt: 'Herschrijf de zin zo dat alleen de man de verrekijker heeft.',
        source: 'Ik zag de man met de verrekijker.',
        accept: [
          'Ik zag de man die de verrekijker had.',
          'Ik zag de man die een verrekijker had.',
          'Ik zag de man die de verrekijker vasthield.',
          'Ik zag de man die een verrekijker vasthield.',
        ],
        why: 'Een bijzin die bij man hoort, kan niet aan zag hangen. Zo blijft er maar één boom over.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Hoe je hoofd kiest',
        panels: [
          {
            text: 'Je leest van links naar rechts en bouwt de boom terwijl je leest. Soms kies je te vroeg de verkeerde. Dat heet een *tuinpadzin* (*garden path*). Het beroemde Engelse voorbeeld van Bever (1970): *The horse raced past the barn fell*. In het Nederlands gebeurt het vaak in bijzinnen: *Dit is de vrouw die de kinderen gezien hebben*. Je leest *die* eerst als onderwerp, maar *hebben* is meervoud en past alleen bij *de kinderen*. Frazier (1987) onderzocht dit soort Nederlandse zinnen.',
            quiz: {
              q: 'Wie heeft wie gezien in ‘Dit is de vrouw die de kinderen gezien hebben’?',
              options: ['De kinderen zagen de vrouw', 'De vrouw zag de kinderen', 'Dat blijft open'],
              answer: 'De kinderen zagen de vrouw',
              why: 'hebben is meervoud, dus het onderwerp is de kinderen. Pas het laatste woord beslist.',
            },
          },
          {
            text: 'Lyn Frazier formuleerde in haar proefschrift (1979) twee strategieën. *Minimal attachment*: kies de boom met de minste knopen. *Late closure*: hang nieuw materiaal aan de groep waar je nu mee bezig bent. In de analyse van toen geeft aanhechting aan de werkwoordgroep de minste knopen. Rayner, Carlson en Frazier (1983) zagen met oogbewegingsmetingen dat lezers bij *The spy saw the cop with binoculars* eerst de instrumentlezing kiezen, en dat ze vertragen als de rest van de zin de andere lezing vraagt.',
            rule: 'Minimal attachment: de eenvoudigste boom eerst. Late closure: hang aan wat je nu aan het bouwen bent.',
            quiz: {
              q: 'Welke lezing kiest een lezer volgens minimal attachment eerst bij ‘Hij sloeg de hond met de stok’?',
              options: ['Hij gebruikte de stok', 'De hond had de stok'],
              answer: 'Hij gebruikte de stok',
              why: 'Aanhechting aan de werkwoordgroep vraagt geen extra naamwoordgroepknoop: de minste knopen.',
            },
          },
          {
            text: 'Zijn die strategieën universeel? Cuetos en Mitchell (1988) testten zinnen als *Iemand schoot op de bediende van de actrice die op het balkon stond*. Wie stond op het balkon? Late closure voorspelt *de actrice*, het laatste woord. Engelse lezers kozen inderdaad vaker de actrice, Spaanse lezers vaker de bediende. Brysbaert en Mitchell (1996) vonden voor het Nederlands ook een voorkeur voor de eerste, *de bediende*. Parseerstrategieën zijn dus voorkeuren, geen wetten.',
            lab: {
              label: 'Tik een taal',
              chips: [
                { k: 'Engels', out: 'vaker: de actrice', note: 'Past bij late closure: hang aan de laatste groep.' },
                { k: 'Spaans', out: 'vaker: de bediende', note: 'Cuetos en Mitchell (1988): tegen late closure in.' },
                { k: 'Nederlands', out: 'vaker: de bediende', note: 'Brysbaert en Mitchell (1996).' },
              ],
            },
            deep: {
              q: 'Wat betekent dit voor schrijvers?',
              a: 'Als lezers verschillen in hun eerste keuze, kun je niet rekenen op één vaste lezing. Herhaal dan liever het zelfstandig naamwoord: *Iemand schoot op de bediende van de actrice. De actrice stond op het balkon.* Een schrijver maakt de boom zichtbaar, zodat de lezer niet hoeft te gokken.',
            },
          },
        ],
      },
      {
        kind: 'choice',
        id: 'tuinpad',
        prompt: 'Welke zin blijft ook aan het eind dubbelzinnig?',
        before: '',
        after: '',
        options: [
          'Dit is de vrouw die het kind gezien heeft.',
          'Dit is de vrouw die de kinderen gezien hebben.',
          'Dit is de vrouw die de kinderen gezien heeft.',
        ],
        answer: 'Dit is de vrouw die het kind gezien heeft.',
        why: 'de vrouw en het kind zijn allebei enkelvoud, dus heeft past bij allebei. In de andere zinnen beslist het getal van de persoonsvorm.',
      },
      {
        kind: 'bet',
        id: 'late-closure',
        prompt: 'Iemand schoot op de bediende van de actrice die op het balkon stond. Welke lezing voorspelt late closure?',
        options: ['De actrice stond op het balkon', 'De bediende stond op het balkon'],
        answer: 'De actrice stond op het balkon',
        why: 'Late closure hangt de bijzin aan de groep waar je net mee bezig was: de actrice. Nederlandse lezers kiezen toch vaker de bediende (Brysbaert en Mitchell, 1996).',
      },
      {
        kind: 'rewrite',
        id: 'bereik',
        prompt: 'Herschrijf zo dat alleen de mannen oud hoeven te zijn.',
        source: 'Er is korting voor oude mannen en vrouwen.',
        accept: [
          'Er is korting voor vrouwen en oude mannen.',
          'Er is korting voor vrouwen en voor oude mannen.',
          'Er is korting voor oude mannen en voor vrouwen.',
          'Er is korting voor oude mannen en voor alle vrouwen.',
        ],
        why: 'Zet vrouwen voorop, of herhaal voor: dan kan oude zijn bereik niet meer over vrouwen uitstrekken.',
      },
      {
        kind: 'swipe',
        id: 'ambiguiteit-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          {
            t: 'Bij structurele ambiguïteit heeft één woord twee betekenissen.',
            ok: false,
            fix: 'de woorden zijn duidelijk, de groepering niet',
            why: 'Eén woord met twee betekenissen is lexicale ambiguïteit.',
          },
          { t: 'In oude mannen en vrouwen kan oude bereik hebben over allebei.', ok: true, why: '[oude [mannen en vrouwen]].' },
          { t: 'Minimal attachment kiest de boom met de minste knopen.', ok: true, why: 'Frazier (1979).' },
          {
            t: 'Late closure geldt in alle talen even sterk.',
            ok: false,
            fix: 'Spaanse en Nederlandse lezers wijken vaak af',
            why: 'Cuetos en Mitchell (1988), Brysbaert en Mitchell (1996).',
          },
          {
            t: 'Een bijzin bij het zelfstandig naamwoord kan een dubbelzinnige voorzetselgroep vervangen.',
            ok: true,
            why: 'de man die een verrekijker had: maar één boom.',
          },
          {
            t: 'In Dit is de vrouw die de kinderen gezien hebben zag de vrouw de kinderen.',
            ok: false,
            fix: 'de kinderen zagen de vrouw',
            why: 'hebben is meervoud: het onderwerp is de kinderen.',
          },
        ],
      },
    ],
  },
  {
    id: 'p14',
    stage: 'master',
    domain: 'syn',
    also: ['sem', 'orth'],
    title: 'Het lidwoord als kern',
    skill: 'Zinsbouw',
    icon: 'DP',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'De DP-hypothese',
        panels: [
          {
            text: 'Tot nu toe was het zelfstandig naamwoord de baas van de naamwoordgroep. Maar wat als dat kleine lidwoord de echte baas is, zoals de stille directeur die nooit op de bedrijfsfoto staat? Dat stelde Steven Abney in zijn proefschrift *The English Noun Phrase in its Sentential Aspect* (1987). Volgens hem is het lidwoord, de *determinator* D, de kern. D neemt de naamwoordgroep (NP) als complement, en het geheel is een *DP*.',
            rule: 'DP-hypothese: het lidwoord (D) is de kern; de NP is zijn complement.',
            bracket: {
              q: 'Bouw de DP van binnen naar buiten',
              words: true,
              tree: '[die [oude [Franse wijn]]]',
              nodes: [
                { w: 'Franse wijn', cat: 'NP', note: 'De kern wijn met een bijvoeglijk naamwoord.' },
                { w: 'oude Franse wijn', cat: 'NP', note: 'Nog een bijvoeglijk naamwoord erbij: nog steeds een NP.' },
                { w: 'die oude Franse wijn', cat: 'DP', note: 'D die neemt de hele NP als complement: een DP met die als kern.' },
              ],
              traps: [{ w: 'die oude', note: 'die hoort bij de hele groep oude Franse wijn, niet alleen bij oude.' }],
              note: 'Vergelijk met X-bar: daar sloot het lidwoord de NP af als specificeerder. Hier is het de kern van een eigen groep.',
            },
          },
          {
            text: 'Eerste bewijs: voornaamwoorden. In *wij taalkundigen* en *jullie Nederlanders* staat een persoonlijk voornaamwoord precies waar anders het lidwoord staat. Een lidwoord kan er niet meer bij: *de wij taalkundigen* (fout). Postal (1966) betoogde al dat voornaamwoorden eigenlijk lidwoorden zijn. In de DP-analyse is *wij* een D met een NP als complement, en staat *wij* los een D zonder complement.',
            phrase: {
              q: 'Vind de drie DP’s',
              sentence: 'Wij taalkundigen lezen dit boek over de Rijn.',
              groups: [
                { span: [0, 1], cat: 'DP', head: 0, note: 'D wij, complement de NP taalkundigen.' },
                { span: [3, 7], cat: 'DP', head: 3, note: 'D dit, complement de NP boek over de Rijn.' },
                { span: [6, 7], cat: 'DP', head: 6, note: 'D de, complement Rijn: een DP binnen de voorzetselgroep.' },
              ],
              traps: [{ span: [4, 7], note: 'boek over de Rijn is de NP: het complement van D. De DP begint bij dit.' }],
              note: 'Elke DP begint bij zijn D: wij, dit, de.',
            },
            quiz: {
              q: 'Wat laat ‘wij taalkundigen’ zien?',
              options: [
                'wij staat op de plek van het lidwoord, dus voornaamwoorden zijn D’s',
                'wij is een bijvoeglijk naamwoord',
                'taalkundigen is het onderwerp en wij een bijstelling',
              ],
              answer: 'wij staat op de plek van het lidwoord, dus voornaamwoorden zijn D’s',
              why: 'Een lidwoord kan er niet meer bij: de plek van D is al bezet door wij.',
            },
          },
          {
            text: 'Tweede bewijs: de bezitter. *Jans fiets*, *Jan z’n fiets*, *Jan zijn fiets*: de bezitter staat vooraan, en een lidwoord kan er niet meer bij: *de Jans fiets* (fout). Abney vergeleek de DP met de zin: zoals een onderwerp vóór de persoonsvorm staat, zo staat de bezitter vóór D. De *-s* of *z’n* staat in D zelf, en daarom is daar geen plaats meer voor *de*.',
            rule: 'Een bezitter vooraan en een lidwoord sluiten elkaar uit: ze strijden om dezelfde plek.',
            lab: {
              label: 'Tik een bezitsvorm',
              chips: [
                { k: 'Jans fiets', out: 'goed, ook in formele tekst', note: 'Jan in de specificeerder, -s in D. Zonder apostrof.' },
                { k: 'Jan z’n fiets', out: 'spreektaal', note: 'z’n staat in D. In formele tekst liever Jans fiets of de fiets van Jan.' },
                { k: 'de fiets van Jan', out: 'goed', note: 'D is hier de; de bezitter staat in een voorzetselgroep achteraan.' },
                { k: 'de Jans fiets', out: 'fout', note: 'Twee dingen op de plek van D.' },
              ],
            },
            quiz: {
              q: 'Wat kan niet samen met een bezitter als ‘Jans’?',
              options: ['een lidwoord ervoor', 'een bijvoeglijk naamwoord', 'een voorzetselgroep erachter'],
              answer: 'een lidwoord ervoor',
              why: 'Jans nieuwe fiets uit Gent kan, de Jans fiets niet: de plek van D is bezet.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'in-d',
        prompt: 'Staat het woord in D, of lager in de NP?',
        buckets: ['in D (de kern van de DP)', 'in de NP (het complement)'],
        items: [
          { t: 'de in: de fiets', b: 0 },
          { t: 'wij in: wij taalkundigen', b: 0 },
          { t: 'taalkundigen in: wij taalkundigen', b: 1 },
          { t: 'deze in: deze oude wijn', b: 0 },
          { t: 'oude in: deze oude wijn', b: 1 },
          { t: 'z’n in: Jan z’n fiets', b: 0 },
          { t: 'fiets in: Jan z’n fiets', b: 1 },
          { t: 'Franse in: die Franse wijn', b: 1 },
          { t: 'hij als losse groep', b: 0 },
        ],
        why: 'Lidwoorden, aanwijzende voornaamwoorden, persoonlijke voornaamwoorden en z’n staan in D. Zelfstandige en bijvoeglijke naamwoorden zitten in de NP. Een los voornaamwoord is een D zonder complement.',
      },
      {
        kind: 'order',
        id: 'wij-jonge',
        prompt: 'Zet de groep in de goede volgorde.',
        tiles: ['taalkundigen', 'wij', 'jonge'],
        answer: 'wij jonge taalkundigen',
        why: 'D (wij) komt eerst, daarna de NP: bijvoeglijk naamwoord + kern.',
      },
      {
        kind: 'proofread',
        id: 'bezitsvormen',
        prompt: 'Lees de tekst na',
        intro: 'Er zitten drie fouten in de bezitsvormen. Tik ze aan.',
        tokens: [
          { t: 'Op' },
          { t: 'Jan’s', fix: 'Jans', why: 'Na een gewone medeklinker plak je de -s er zonder apostrof aan: Jans.' },
          { t: 'verjaardag' },
          { t: 'stond' },
          { t: 'Annas', fix: 'Anna’s', why: 'Na een lange klinker aan het eind (a, i, o, u, y) schrijf je een apostrof: Anna’s.' },
          { t: 'fiets' },
          { t: 'naast' },
          { t: 'Max’s', fix: 'Max’', why: 'Na een s-klank schrijf je alleen een apostrof: Max’.' },
          { t: 'scooter.' },
        ],
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Bepaald, specifiek en generiek',
        panels: [
          {
            text: 'Als D de kern is, wat voegt D dan toe aan de betekenis? Vooral *bepaaldheid*. Een *bepaalde* DP (*de fiets*, *deze fiets*, *Jans fiets*) verwijst naar iets wat de lezer kan thuisbrengen. Irene Heim (1982) beschreef dat als *bekendheid*: *de* gebruik je voor iets dat al in het gesprek bestaat. Iets anders is *specificiteit*: heb je zelf één ding in gedachten? *Ik zoek een student die Fins spreekt* kan gaan over één student die je kent, of over wie dan ook (Fodor en Sag, 1982).',
            rule: 'Bepaald: de lezer weet welk ding. Specifiek: de spreker heeft één ding in gedachten.',
            quiz: {
              q: 'Wanneer kies je ‘de’ in plaats van ‘een’?',
              options: ['als de lezer kan weten welk ding je bedoelt', 'als het ding groot is', 'als jij zelf het ding kent'],
              answer: 'als de lezer kan weten welk ding je bedoelt',
              why: 'Bepaaldheid gaat om de lezer. Dat jij het ding zelf kent, maakt het specifiek, niet bepaald: een student die ik ken.',
            },
          },
          {
            text: 'Een DP kan ook over een hele *soort* gaan: dat heet een *generieke* lezing. *De walvis is een zoogdier*, *Een walvis is een zoogdier* en *Walvissen zijn zoogdieren* gaan alle drie over de soort. Maar ze zijn niet gelijk. Gregory Carlson (1977) liet zien dat kale meervouden als *walvissen* naar de soort zelf kunnen verwijzen. Een predicaat dat alleen voor een soort geldt, zoals *uitgestorven*, past bij *de dodo* maar niet bij *een dodo*.',
            quiz: {
              q: 'Welke zin gaat over de soort?',
              options: ['Walvissen zijn zoogdieren.', 'Er zwemmen walvissen in de baai.', 'De walvis in de baai is moe.'],
              answer: 'Walvissen zijn zoogdieren.',
              why: 'Een algemene uitspraak over alle walvissen. De andere twee gaan over walvissen die nu ergens zwemmen.',
            },
          },
          {
            text: 'En eigennamen? *Jan* heeft geen lidwoord, *de Rijn* en *het Vondelpark* wel. Giuseppe Longobardi (1994) liet voor het Italiaans zien dat een naam zonder lidwoord zelf naar de plek van D kan schuiven: *Gianni mio* (de naam voor het bezittelijk voornaamwoord) naast *il mio Gianni*. Ook dan blijft D gevuld. In het zuiden van het taalgebied hoor je in de spreektaal *de Jan*: daar vult het lidwoord D, en blijft de naam in de NP.',
            lab: {
              label: 'Tik een naam',
              chips: [
                { k: 'Jan', out: 'geen lidwoord', note: 'De naam vult D zelf (Longobardi).' },
                { k: 'de Rijn', out: 'lidwoord verplicht', note: 'Rivieren, landstreken en gebouwen krijgen vaak een vast lidwoord.' },
                { k: 'de Jan', out: 'zuidelijke spreektaal', note: 'Het lidwoord vult D; in de standaardtaal schrijf je Jan.' },
              ],
            },
            deep: {
              q: 'Is de DP-hypothese nu bewezen?',
              a: 'Ze is de standaardanalyse geworden, maar niet onomstreden. Bruening (2009) betoogde bijvoorbeeld dat werkwoorden vooral het zelfstandig naamwoord selecteren (je *drinkt wijn*, het lidwoord maakt daarvoor niet uit), en dat N dus toch de kern is. Zo werkt wetenschap: een sterk idee blijft getest worden.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'generiek',
        prompt: 'Gaat de zin over de hele soort of over een bepaald exemplaar?',
        buckets: ['generiek (over de soort)', 'over een of meer exemplaren'],
        items: [
          { t: 'De walvis is een zoogdier.', b: 0 },
          { t: 'Walvissen zijn zoogdieren.', b: 0 },
          { t: 'Een walvis is een zoogdier.', b: 0 },
          { t: 'Gisteren spoelde er een walvis aan op Texel.', b: 1 },
          { t: 'De computer heeft ons leven veranderd.', b: 0 },
          { t: 'De computer op mijn bureau is kapot.', b: 1 },
          { t: 'Katten jagen op muizen.', b: 0 },
          { t: 'De kat van de buren jaagt op muizen.', b: 1 },
          { t: 'Er zitten muizen in de schuur.', b: 1 },
        ],
        why: 'Generiek: uitspraken over de soort, met de, een of een kaal meervoud. Over exemplaren: een bepaald dier of ding, of muizen die nu ergens zitten.',
      },
      {
        kind: 'bet',
        id: 'uitgestorven',
        prompt: 'Welke zin is goed als uitspraak over de soort?',
        options: ['De dodo is uitgestorven.', 'Een dodo is uitgestorven.'],
        answer: 'De dodo is uitgestorven.',
        why: 'uitgestorven geldt alleen voor een soort, niet voor één dier. De dodo kan naar de soort verwijzen; een dodo is één exemplaar.',
      },
      {
        kind: 'choice',
        id: 'specifiek',
        prompt: 'Ik zoek een student die Fins spreekt. Welke voortzetting maakt ‘een student’ specifiek?',
        before: '',
        after: '',
        options: ['Hij heet Mikko.', 'Ken jij er een?', 'Maakt niet uit wie.'],
        answer: 'Hij heet Mikko.',
        why: 'Met hij heet Mikko heb je één student in gedachten: specifiek, al is de groep onbepaald. Bij de andere twee is elke Finssprekende student goed.',
      },
      {
        kind: 'swipe',
        id: 'dp-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Volgens Abney (1987) is het lidwoord de kern van de groep.', ok: true, why: 'De DP-hypothese: D neemt de NP als complement.' },
          { t: 'In wij taalkundigen staat wij op de plek van D.', ok: true, why: 'Een lidwoord kan er niet meer bij.' },
          { t: 'De Jans fiets is goed Nederlands.', ok: false, fix: 'Jans fiets of de fiets van Jan', why: 'Bezitter en lidwoord strijden om dezelfde plek.' },
          { t: 'Een kaal meervoud zoals walvissen kan naar een hele soort verwijzen.', ok: true, why: 'Carlson (1977).' },
          {
            t: 'Een onbepaalde groep kan nooit specifiek zijn.',
            ok: false,
            fix: 'een student die ik ken is onbepaald en specifiek',
            why: 'Bepaaldheid gaat om de lezer, specificiteit om wat de spreker in gedachten heeft.',
          },
          { t: 'In de DP-analyse is de NP het complement van D.', ok: true, why: '[DP die [NP oude Franse wijn]].' },
        ],
      },
    ],
  },
];
