import type { LessonInput } from '../schema';

/**
 * De woordgroep, bachelor p3–p6: bewijs voor de woordgroep (constituenttests), kern en bepalingen,
 * de naamwoordgroep van binnen (bepalers, volgorde, nabepalingen, kale naamwoorden) en
 * bijvoeglijke naamwoorden stapelen (volgorde en de komma).
 */
export const GROEP_LESSONS: LessonInput[] = [
  {
    id: 'p3',
    stage: 'bachelor',
    domain: 'syn',
    title: 'Bewijs voor de woordgroep',
    skill: 'Zinsbouw',
    icon: '[?]',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Drie tests voor een blok',
        panels: [
          {
            text: 'Woorden gaan graag in groepjes op stap. Maar zeggen dat ze bij elkaar horen is makkelijk; bewijzen is het echte werk. Een groep woorden die samen één blok vormt, heet in de taalkunde een *constituent*. Test 1 is de *vooroptest*: in een Nederlandse hoofdzin staat vóór de persoonsvorm precies één zinsdeel. Wat je samen naar die plek kunt verplaatsen, is dus één blok: *Een fiets met rode banden heeft mijn buurman gekocht.*',
            rule: 'Vooroptest: wat samen vóór de persoonsvorm kan staan, is één constituent.',
            swap: {
              goal: 'Zet het lijdend voorwerp vooraan. De persoonsvorm blijft op plek 2.',
              blocks: ['mijn buurman', 'heeft', 'een fiets met rode banden', 'gekocht'],
              accept: ['een fiets met rode banden heeft mijn buurman gekocht'],
              note: 'Een fiets met rode banden heeft mijn buurman gekocht. Vijf woorden, één blok.',
            },
          },
          {
            text: 'Test 2 is de *vervangtest*: een constituent kun je vervangen door één woord, zoals een voornaamwoord (*hij*, *het*, *hem*) of een bijwoord (*daar*, *toen*). *De oude buurman* wordt *hij*, *in de bibliotheek* wordt *daar*. Een los rijtje als *oude buurman zag* kun je door niets vervangen.',
            phrase: {
              q: 'Vind de drie groepen die je kunt vervangen door hij, het of daar',
              sentence: 'De oude buurman zag het nieuwe boek in de bibliotheek.',
              groups: [
                { span: [0, 2], cat: 'naamwoordgroep', head: 2, note: 'Wordt hij: Hij zag het nieuwe boek in de bibliotheek.' },
                { span: [4, 6], cat: 'naamwoordgroep', head: 6, note: 'Wordt het: De oude buurman zag het in de bibliotheek.' },
                { span: [7, 9], cat: 'voorzetselgroep', head: 7, note: 'Wordt daar: De oude buurman zag het nieuwe boek daar.' },
              ],
              traps: [
                { span: [2, 4], note: 'buurman zag het loopt over twee groepen heen. Geen enkel woord kan dat stuk vervangen.' },
                { span: [5, 7], note: 'nieuwe boek in: het hoort bij boek, en in hoort bij de bibliotheek.' },
              ],
              note: 'Drie blokken, drie vervangers. Het werkwoord zag blijft staan.',
            },
          },
          {
            text: 'Test 3 is de *vraagtest*: een constituent kan in zijn eentje antwoord geven op een vraag. *Wie zag het boek?* *De oude buurman.* *Waar?* *In de bibliotheek.* Zo’n los antwoord heet een *fragment*. Een stuk dat geen blok is, klinkt als los antwoord altijd vreemd.',
            quiz: {
              q: 'Zin: De buurman zag het boek in de bibliotheek. Welk stuk kan geen los antwoord zijn?',
              options: ['boek in de', 'in de bibliotheek', 'het boek'],
              answer: 'boek in de',
              why: 'Op Waar? antwoord je in de bibliotheek, op Wat? het boek. Op boek in de past geen enkele vraag.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'blok-of-niet',
        prompt: 'Zin: Mijn zus heeft gisteren in Utrecht een tweedehands fiets gekocht. Is het stuk een zinsdeel?',
        buckets: ['één blok', 'geen blok'],
        items: [
          { t: 'mijn zus', b: 0 },
          { t: 'gisteren', b: 0 },
          { t: 'in Utrecht', b: 0 },
          { t: 'een tweedehands fiets', b: 0 },
          { t: 'zus heeft', b: 1 },
          { t: 'gisteren in', b: 1 },
          { t: 'Utrecht een', b: 1 },
          { t: 'fiets gekocht', b: 1 },
          { t: 'heeft gisteren', b: 1 },
        ],
        why: 'Mijn zus, gisteren, in Utrecht en een tweedehands fiets kunnen allemaal vooraan staan en een vraag beantwoorden. Ook één woord kan een blok zijn: gisteren. De andere stukken lopen over een grens.',
      },
      {
        kind: 'rewrite',
        id: 'plaats-vooraan',
        prompt: 'Zet de plaatsbepaling vooraan. Let op de plek van de persoonsvorm.',
        source: 'Mijn zus heeft gisteren in Utrecht een fiets gekocht.',
        accept: ['In Utrecht heeft mijn zus gisteren een fiets gekocht.', 'In Utrecht heeft gisteren mijn zus een fiets gekocht.'],
        why: 'In Utrecht is één blok en gaat in zijn geheel naar voren. De persoonsvorm heeft blijft op plek 2, dus het onderwerp schuift erachter.',
      },
      {
        kind: 'choice',
        id: 'vervanger',
        prompt: 'Vervang de groep ‘de man met de hoed’ door één woord.',
        before: 'Ik ken',
        after: 'al jaren.',
        options: ['hem', 'hij', 'het', 'daar'],
        answer: 'hem',
        why: 'De hele groep de man met de hoed is lijdend voorwerp en wordt hem. Dat er één woord voor in de plaats kan, bewijst dat de vijf woorden één blok zijn.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Wat tests wel en niet bewijzen',
        panels: [
          {
            text: 'Het idee dat een zin uit lagen van blokken bestaat, komt uit het Amerikaanse structuralisme. Leonard Bloomfield noemde de twee delen waarin je een blok splitst de *directe constituenten* (*immediate constituents*, in *Language*, 1933). Teken je die lagen, dan krijg je een boom. Elke knoop in die boom is een constituent. De tests zijn manieren om knopen te vinden zonder de boom te zien.',
            rule: 'Een constituent is een knoop in de boom; een test is een manier om die knoop op te sporen.',
            bracket: {
              q: 'Bouw de groep van binnen naar buiten',
              words: true,
              tree: '[in [de [oude bibliotheek]]]',
              nodes: [
                { w: 'oude bibliotheek', cat: 'N′', note: 'oude zegt iets over bibliotheek: het kleinste blok.' },
                { w: 'de oude bibliotheek', cat: 'naamwoordgroep', note: 'Het lidwoord sluit de naamwoordgroep af. Vervangtest: haar of hem.' },
                { w: 'in de oude bibliotheek', cat: 'voorzetselgroep', note: 'Het voorzetsel neemt de hele naamwoordgroep. Vervangtest: daar.' },
              ],
              traps: [
                { w: 'in de', note: 'in de kan nergens vooraan staan en geen vraag beantwoorden. de hoort bij oude bibliotheek.' },
                { w: 'de oude', note: 'de bepaalt de hele groep oude bibliotheek, niet alleen het bijvoeglijk naamwoord.' },
              ],
              note: 'Drie knopen, drie constituenten. Daarom is de oude bibliotheek een blok en in de niet.',
            },
          },
          {
            text: 'Test 4 is de *nevenschikkingstest*: alleen blokken van dezelfde soort kun je met *en* verbinden. *Hij kocht oude en nieuwe boeken* bewijst dat *oude* een eigen blok is. Maar de vooroptest zegt iets anders: ∗*Oude kocht hij boeken* (fout). De naamwoordgroep laat geen stukje uit zichzelf naar voren gaan. De vooroptest vindt dus alleen zinsdelen, niet de kleinere blokken binnenin.',
            lab: {
              label: 'Test het blok oude in: Hij kocht oude boeken.',
              chips: [
                { k: 'vooroptest', out: '∗Oude kocht hij boeken. (fout)', note: 'Mislukt: een stuk uit een naamwoordgroep mag niet alleen naar voren.' },
                { k: 'nevenschikking', out: 'Hij kocht oude en nieuwe boeken.', note: 'Lukt: oude is een blok van dezelfde soort als nieuwe.' },
                { k: 'vraagtest', out: 'Wat voor boeken? Oude.', note: 'Lukt: met de vraag wat voor kom je binnen in de groep.' },
              ],
            },
            quiz: {
              q: 'Wat leer je van dit verschil tussen de tests?',
              options: [
                'De vooroptest vindt alleen zinsdelen, niet de blokken in een groep',
                'oude is toch geen blok',
                'De nevenschikkingstest is altijd fout',
              ],
              answer: 'De vooroptest vindt alleen zinsdelen, niet de blokken in een groep',
              why: 'Elke test kijkt naar een andere laag van de boom. Daarom gebruik je er altijd meer dan één.',
            },
          },
          {
            text: 'Tests kunnen ook te veel goedkeuren. In *Jan kocht een fiets en Marie een helm* lijkt *Marie een helm* een blok. Maar er is een werkwoord weggelaten: *Marie* [*kocht*] *een helm*. Dat heet *gapping*. En een test kan mislukken om een reden die niets met blokken te maken heeft, bijvoorbeeld omdat de betekenis verandert. Taalkundigen als Hans Broekhuis (*Syntax of Dutch*) gebruiken de tests daarom als diagnose, niet als definitie.',
            rule: 'Een geslaagde test is bewijs; een mislukte test is nog geen tegenbewijs.',
            quiz: {
              q: 'Een stuk kan niet vooraan staan. Wat weet je dan zeker?',
              options: ['Niets zeker: de test kan om een andere reden mislukken', 'Dat het geen constituent is', 'Dat het een bijzin is'],
              answer: 'Niets zeker: de test kan om een andere reden mislukken',
              why: 'Denk aan oude in oude boeken: wel een blok, toch niet vooraan. Kijk dus wat de andere tests zeggen.',
            },
            deep: {
              q: 'Waarom zou je meerdere tests combineren?',
              a: 'Elke test heeft zijn eigen blinde vlek. De vooroptest ziet niets binnen een zinsdeel, de nevenschikkingstest laat zich foppen door weglatingen (*Jan kocht een fiets en Marie een helm*), en de vervangtest werkt alleen als er een passend voornaamwoord bestaat. Wijzen drie tests dezelfde kant op, dan is het bewijs sterk. Spreken ze elkaar tegen, dan is dat geen ramp maar informatie: het vertelt je op welke laag van de boom je zit.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'welke-test',
        prompt: 'Welke test wordt hier gebruikt?',
        buckets: ['vooroptest', 'vervangtest', 'vraagtest', 'nevenschikkingstest'],
        items: [
          { t: 'Na de les gingen we naar huis.', b: 0 },
          { t: 'Die rode fiets heb ik nooit gezien.', b: 0 },
          { t: 'De buurvrouw van boven → zij', b: 1 },
          { t: 'op het station → daar', b: 1 },
          { t: 'Wanneer? Na de les.', b: 2 },
          { t: 'Wie belde er? Mijn oudste broer.', b: 2 },
          { t: 'Ik las een roman en twee gedichten.', b: 3 },
          { t: 'Ze is slim en erg grappig.', b: 3 },
        ],
        why: 'Vooraan vóór de persoonsvorm: vooroptest. Eén woord ervoor in de plaats: vervangtest. Een los antwoord: vraagtest. Twee blokken met en: nevenschikkingstest.',
      },
      {
        kind: 'order',
        id: 'bouw-vooraan',
        prompt: 'Maak een zin met de voorzetselgroep vooraan.',
        tiles: ['een oud boek', 'las', 'In de bibliotheek', 'ik'],
        answer: 'In de bibliotheek las ik een oud boek',
        why: 'Het hele blok in de bibliotheek staat vooraan, de persoonsvorm las op plek 2, daarna het onderwerp ik.',
      },
      {
        kind: 'bet',
        id: 'oude-blok',
        prompt: 'Hij kocht oude en nieuwe boeken. Is oude hier een constituent?',
        options: ['Ja: de nevenschikkingstest lukt', 'Nee: oude kan niet vooraan staan', 'Nee: één woord is nooit een constituent'],
        answer: 'Ja: de nevenschikkingstest lukt',
        why: 'Dat oude niet vooraan kan, komt doordat een naamwoordgroep geen stukjes loslaat. Een mislukte vooroptest is geen tegenbewijs.',
      },
      {
        kind: 'swipe',
        id: 'tests-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Vóór de persoonsvorm in een hoofdzin staat precies één zinsdeel.', ok: true, why: 'Daarom werkt de vooroptest.' },
          {
            t: 'Eén woord kan nooit een woordgroep zijn.',
            ok: false,
            fix: 'ook één woord kan een blok zijn, zoals gisteren of hij',
            why: 'Een constituent kan uit één woord bestaan.',
          },
          { t: 'In Jan kocht een fiets en Marie een helm is een werkwoord weggelaten.', ok: true, why: 'Gapping: Marie [kocht] een helm.' },
          {
            t: 'Als de vooroptest mislukt, is het stuk zeker geen constituent.',
            ok: false,
            fix: 'een mislukte test is geen tegenbewijs',
            why: 'oude in oude boeken is een blok, maar kan niet vooraan.',
          },
          { t: 'Bloomfield sprak in 1933 van directe constituenten.', ok: true, why: 'In zijn boek Language.' },
          { t: 'De vervangtest werkt met woorden als hij, het, daar en toen.', ok: true, why: 'Eén woord vervangt het hele blok.' },
        ],
      },
    ],
  },
  {
    id: 'p4',
    stage: 'bachelor',
    domain: 'syn',
    title: 'Kern en bepalingen',
    skill: 'Zinsbouw',
    icon: 'X',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Elke groep heeft een baas',
        panels: [
          {
            text: 'Elke woordgroep heeft een baas. De andere woorden mogen meepraten, maar de baas beslist. Die baas heet de *kern*. De woorden eromheen heten *bepalingen*: ze zeggen iets over de kern. In *mijn heel trotse oom* is *oom* de kern. De kern beslist ook wat voor groep het is: rond een zelfstandig naamwoord krijg je een *naamwoordgroep*, rond een voorzetsel een *voorzetselgroep*.',
            rule: 'De kern bepaalt de soort groep; de bepalingen zeggen iets over de kern.',
            phrase: {
              q: 'Vind vier groepen: twee naamwoordgroepen, een bijvoeglijke groep en een voorzetselgroep',
              sentence: 'Mijn heel trotse oom woont vlak bij het station.',
              groups: [
                { span: [0, 3], cat: 'naamwoordgroep', head: 3, note: 'Kern oom. Mijn en heel trotse zijn bepalingen.' },
                { span: [1, 2], cat: 'bijvoeglijke groep', head: 2, note: 'Kern trotse; heel zegt hoe trots.' },
                { span: [5, 8], cat: 'voorzetselgroep', head: 6, note: 'Kern bij. vlak zegt hoe dichtbij, het station is de aanvulling.' },
                { span: [7, 8], cat: 'naamwoordgroep', head: 8, note: 'Kern station, binnen de voorzetselgroep.' },
              ],
              traps: [
                { span: [3, 4], note: 'oom woont loopt van het onderwerp in het werkwoord. Dat is geen groep.' },
                { span: [4, 6], note: 'woont vlak bij: bij hoort bij het station, niet bij woont.' },
              ],
              note: 'Groepen kunnen in elkaar zitten: de naamwoordgroep het station zit in de voorzetselgroep.',
            },
          },
          {
            text: 'Er zijn vijf soorten groepen, genoemd naar hun kern. De *naamwoordgroep* (kern: zelfstandig naamwoord), de *bijvoeglijke groep* (kern: bijvoeglijk naamwoord), de *voorzetselgroep* (kern: voorzetsel), de *bijwoordgroep* (kern: bijwoord) en de *werkwoordgroep* (kern: werkwoord). Tik een groep en zoek de kern.',
            lab: {
              label: 'Tik een groep',
              chips: [
                { k: 'de oude buurman', out: 'naamwoordgroep · kern buurman', note: 'de en oude zijn bepalingen bij buurman.' },
                { k: 'erg trots op zijn dochter', out: 'bijvoeglijke groep · kern trots', note: 'erg zegt hoe trots, op zijn dochter waarop.' },
                { k: 'vlak achter de kerk', out: 'voorzetselgroep · kern achter', note: 'vlak zegt hoe dichtbij, de kerk is de aanvulling.' },
                { k: 'heel erg vaak', out: 'bijwoordgroep · kern vaak', note: 'erg zegt hoe vaak, heel zegt hoe erg.' },
                { k: 'een boek lezen', out: 'werkwoordgroep · kern lezen', note: 'In het Nederlands staat de werkwoordskern achteraan.' },
              ],
            },
          },
          {
            text: 'Hoe vind je de kern? Twee tests. *Weglaten*: de bepalingen kun je meestal weglaten, de kern niet. *De oude buurman* wordt *de buurman*, maar niet *de oude*. *Congruentie*: de kern van het onderwerp bepaalt of de persoonsvorm enkelvoud of meervoud is. In *De sleutels van de kast* is *sleutels* de kern, niet *kast*.',
            rule: 'Kerntests: de kern kun je niet weglaten, en de kern regelt de persoonsvorm.',
            quiz: {
              q: 'Kies de goede vorm: De sleutels van de kast … op tafel.',
              options: ['liggen', 'ligt'],
              answer: 'liggen',
              why: 'De kern is sleutels, meervoud. van de kast is een bepaling. Dat de kast vlak voor het werkwoord staat, verleidt tot ligt.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'soort-groep',
        prompt: 'Welke soort groep is het? Zoek eerst de kern.',
        buckets: ['naamwoordgroep', 'bijvoeglijke groep', 'voorzetselgroep', 'bijwoordgroep'],
        items: [
          { t: 'die drie oude schoenen', b: 0 },
          { t: 'een kop sterke koffie', b: 0 },
          { t: 'erg bang voor honden', b: 1 },
          { t: 'zeer geschikt voor kinderen', b: 1 },
          { t: 'vlak achter de kerk', b: 2 },
          { t: 'tot diep in de nacht', b: 2 },
          { t: 'met een rode jas', b: 2 },
          { t: 'heel erg vaak', b: 3 },
          { t: 'bijna nooit', b: 3 },
        ],
        why: 'schoenen en kop: zelfstandig naamwoord. bang en geschikt: bijvoeglijk naamwoord. achter, tot en met: voorzetsel. vaak en nooit: bijwoord. Let op: in erg bang voor honden zit een voorzetselgroep, maar de kern van het geheel is bang.',
      },
      {
        kind: 'choice',
        id: 'verzameling',
        prompt: 'Kies de goede persoonsvorm.',
        before: 'De verzameling oude munten van mijn opa',
        after: 'veel geld waard.',
        options: ['is', 'zijn'],
        answer: 'is',
        why: 'De kern is verzameling, enkelvoud. oude munten en van mijn opa zijn bepalingen.',
      },
      {
        kind: 'fix',
        id: 'gedrag',
        prompt: 'Tik de foute persoonsvorm en verbeter hem.',
        sentence: 'Het gedrag van die jongens zijn onacceptabel.',
        wrong: 5,
        answer: 'is',
        why: 'De kern van het onderwerp is gedrag, enkelvoud. jongens staat in een bepaling en telt niet mee.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Endocentrisch: de kern geeft zijn naam door',
        panels: [
          {
            text: 'Bloomfield (*Language*, 1933) noemde een groep *endocentrisch* als ze zich gedraagt als haar kern: *arme Jan* kan overal staan waar *Jan* kan staan. In de X-bartheorie (Chomsky 1970, uitgewerkt door Jackendoff in 1977) werd dat een algemene wet: elke groep heeft een kern van dezelfde soort. Een groep met kern X heet XP. De kern pakt eerst zijn *aanvulling* (het deel dat hij nodig heeft), daarna komen de bepalingen erbij.',
            rule: 'Endocentrisch: een groep met kern X is een XP, en erft de eigenschappen van X.',
            bracket: {
              q: 'Bouw de bijvoeglijke groep van binnen naar buiten',
              words: true,
              tree: '[heel [trots [op [zijn dochter]]]]',
              nodes: [
                { w: 'zijn dochter', cat: 'naamwoordgroep', note: 'zijn bepaalt dochter.' },
                { w: 'op zijn dochter', cat: 'voorzetselgroep', note: 'op neemt de naamwoordgroep als aanvulling.' },
                { w: 'trots op zijn dochter', cat: 'A′', note: 'De kern trots pakt eerst zijn aanvulling: trots waarop?' },
                { w: 'heel trots op zijn dochter', cat: 'bijvoeglijke groep', note: 'heel zegt hoe trots en komt er als laatste bij.' },
              ],
              traps: [
                { w: 'heel trots', note: 'heel gaat over de hele groep trots op zijn dochter. De aanvulling staat dichter bij de kern.' },
                { w: 'trots op', note: 'op hoort eerst bij zijn dochter: samen vormen ze de voorzetselgroep.' },
              ],
              note: 'De hele groep gedraagt zich als trots: je kunt hem zetten waar een bijvoeglijk naamwoord kan staan.',
            },
            deep: {
              q: 'Bestaan er groepen zonder kern?',
              a: 'Bloomfield vond van wel. Hij noemde een zin als *John ran* en een voorzetselgroep als *beside John* *exocentrisch*: geen van beide delen gedraagt zich als het geheel. De X-bartheorie maakte daar later toch een kern van: het voorzetsel is de kern van de voorzetselgroep. Wat de kern van een zin is, is nog steeds een onderwerp van onderzoek.',
            },
          },
          {
            text: 'De *Algemene Nederlandse Spraakkunst* (ANS, 1997) noemt bepalingen vóór de kern *voorbepalingen* en bepalingen erna *nabepalingen*. In *het oude huis aan de gracht* zijn *het* en *oude* voorbepalingen en is *aan de gracht* een nabepaling. Let op: de nabepaling hoort bij de groep. Wie alleen tot de kern tikt, mist een deel van het blok.',
            phrase: {
              q: 'Vind de hele naamwoordgroep met kern huis, en de nabepaling',
              sentence: 'Wij kochten het oude huis aan de gracht.',
              groups: [
                { span: [2, 7], cat: 'naamwoordgroep', head: 4, note: 'Vooroptest: Het oude huis aan de gracht kochten wij. Het hele blok gaat mee.' },
                { span: [5, 7], cat: 'voorzetselgroep', head: 5, note: 'De nabepaling: welk huis? Dat aan de gracht.' },
              ],
              traps: [
                {
                  span: [2, 4],
                  note: 'Het oude huis stopt bij de kern. Maar aan de gracht hoort erbij. Het oude huis kochten wij aan de gracht betekent iets anders: dan gebeurde het kopen aan de gracht.',
                },
                { span: [4, 5], note: 'huis aan: aan hoort bij de gracht.' },
              ],
              note: 'Twee voorbepalingen (het, oude), één kern (huis), één nabepaling (aan de gracht).',
            },
          },
          {
            text: 'In het Nederlands staat de kern van de werkwoordgroep achteraan: *(dat ik) vaak naar de bioscoop ga*, *een boek lezen*. De bepalingen en aanvullingen staan ervoor. Bij het voorzetsel is het omgekeerd: de kern staat vooraan (*naar de bioscoop*). Het Nederlands mengt dus twee volgordes.',
            quiz: {
              q: 'Wat is de kern van de groep ‘vaak naar de bioscoop gaan’?',
              options: ['gaan', 'bioscoop', 'naar', 'vaak'],
              answer: 'gaan',
              why: 'Het is een werkwoordgroep: vaak en naar de bioscoop zeggen iets over gaan. De kern staat achteraan.',
            },
          },
          {
            text: 'Soms spreken de kerntests elkaar tegen. In *een stapel boeken* is *stapel* de grammaticale kern: *een stapel* kan alleen staan, *een boeken* niet. Dus *Een stapel boeken ligt op tafel*. Maar bij *een aantal* en *een paar* denken sprekers aan de losse dingen. Dan is meervoud gewoon: *Een paar studenten kwamen te laat*. Arnold Zwicky liet in zijn artikel *Heads* (1985) zien dat zulke kerncriteria niet altijd op hetzelfde woord wijzen.',
            lab: {
              label: 'Tik een groep als onderwerp',
              chips: [
                { k: 'een stapel boeken', out: 'ligt op tafel', note: 'Kern stapel: enkelvoud is de gewone keuze.' },
                { k: 'een aantal mensen', out: 'is of zijn aanwezig', note: 'Allebei goed: het grammaticale enkelvoud of het meervoud van de betekenis.' },
                { k: 'een paar studenten', out: 'kwamen te laat', note: 'een paar werkt als een telwoord, zoals drie. Dan is studenten de kern.' },
              ],
            },
            quiz: {
              q: 'Waarom is ‘Een paar studenten kwamen te laat’ goed?',
              options: ['een paar werkt als telwoord, dus studenten is de kern', 'paar is altijd meervoud', 'Het is fout; het moet kwam zijn'],
              answer: 'een paar werkt als telwoord, dus studenten is de kern',
              why: 'Net als drie studenten. Bij een stapel boeken blijft stapel de kern.',
            },
          },
        ],
      },
      {
        kind: 'highlight',
        id: 'voor-na',
        prompt: 'Kleur de naamwoordgroep: de twee oude huizen aan de gracht',
        intro: 'Kies een stift en tik de woorden aan.',
        pens: [
          { id: 'voor', label: 'voorbepaling', tag: 'voor', ask: 'Staat dit woord vóór de kern en zegt het er iets over?', accent: 'blue' },
          { id: 'kern', label: 'kern', tag: 'kern', ask: 'Is dit het woord dat de groep zijn soort geeft?', accent: 'purple' },
          { id: 'na', label: 'nabepaling', tag: 'na', ask: 'Staat dit woord na de kern en hoort het bij de groep?', accent: 'orange' },
        ],
        words: [
          { t: 'de', role: 'voor' },
          { t: 'twee', role: 'voor' },
          { t: 'oude', role: 'voor' },
          { t: 'huizen', role: 'kern' },
          { t: 'aan', role: 'na' },
          { t: 'de', role: 'na' },
          { t: 'gracht', role: 'na' },
        ],
        done: { title: 'Kern in het midden', text: 'Drie voorbepalingen (de, twee, oude), de kern huizen en de nabepaling aan de gracht.' },
      },
      {
        kind: 'choice',
        id: 'paar',
        prompt: 'Kies de goede persoonsvorm.',
        before: 'Een paar studenten',
        after: 'te laat binnen.',
        options: ['kwamen', 'kwam'],
        answer: 'kwamen',
        why: 'een paar werkt als een telwoord, net als drie. De kern is studenten, meervoud.',
      },
      {
        kind: 'rewrite',
        id: 'alleen-kern',
        prompt: 'Laat alle bepalingen bij ‘huis’ weg, maar houd het lidwoord.',
        source: 'Het zeer oude huis van mijn oma aan de gracht is verkocht.',
        accept: ['Het huis is verkocht.'],
        why: 'zeer oude, van mijn oma en aan de gracht zijn bepalingen; ze kunnen weg. De kern huis kan niet weg.',
      },
      {
        kind: 'swipe',
        id: 'kern-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          {
            t: 'De kern van ‘vlak achter de kerk’ is kerk.',
            ok: false,
            fix: 'de kern is achter',
            why: 'Het is een voorzetselgroep; de kerk is de aanvulling.',
          },
          { t: 'In een endocentrische groep gedraagt het geheel zich als de kern.', ok: true, why: 'Bloomfield, 1933.' },
          { t: 'De ANS noemt een bepaling na de kern een nabepaling.', ok: true, why: 'Bepalingen ervoor zijn voorbepalingen.' },
          { t: 'In ‘Het gedrag van die jongens zijn slecht’ klopt de persoonsvorm.', ok: false, fix: 'is slecht', why: 'De kern is gedrag, enkelvoud.' },
          { t: 'In de Nederlandse werkwoordgroep staat de kern achteraan.', ok: true, why: 'een boek lezen, vaak naar huis gaan.' },
          {
            t: 'De kerntests wijzen altijd hetzelfde woord aan.',
            ok: false,
            fix: 'soms spreken ze elkaar tegen',
            why: 'Denk aan een aantal mensen is of zijn. Zwicky, 1985.',
          },
        ],
      },
    ],
  },
  {
    id: 'p5',
    stage: 'bachelor',
    domain: 'syn',
    also: ['sem'],
    title: 'De naamwoordgroep van binnen',
    skill: 'Zinsbouw',
    icon: '[N]',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Vaste plaatsen voor de kern',
        panels: [
          {
            text: 'Een naamwoordgroep is een trein: de locomotief staat achteraan en de wagons ervoor hebben elk een vaste plaats. De volgorde is: (*al*) + een *bepaler* + een *telwoord* + *bijvoeglijke naamwoorden* + de kern. Een bepaler is een woord dat de groep afbakent: een lidwoord (*de*, *een*), een aanwijzend voornaamwoord (*die*) of een bezittelijk voornaamwoord (*mijn*). Zo krijg je *al de drie mooie boeken* of *al mijn vijf neven*.',
            rule: 'Volgorde in de naamwoordgroep: al · bepaler · telwoord · bijvoeglijk naamwoord · kern.',
            swap: {
              goal: 'Zet de wagons op hun vaste plaats.',
              blocks: ['mooie', 'de', 'drie', 'al', 'boeken'],
              accept: ['al de drie mooie boeken'],
              note: 'al de drie mooie boeken: al, bepaler, telwoord, bijvoeglijk naamwoord, kern.',
            },
          },
          {
            text: 'Op de plek van de bepaler past maar één woord. Je zegt *mijn fiets* of *die fiets*, maar niet ∗*de mijn fiets* (fout); in het Italiaans kan dat wel (*la mia bicicletta*). Ook *kwantoren* (woorden die een hoeveelheid aangeven) staan vaak op die plek: *elke*, *sommige*, *geen*. Alleen *al* mag nog vóór de bepaler: *al die fietsen*.',
            lab: {
              label: 'Tik een groep',
              chips: [
                { k: 'de mijn fiets', out: 'fout', note: 'Twee bepalers op één plek: dat kan niet in het Nederlands.' },
                { k: 'mijn drie fietsen', out: 'goed', note: 'Bepaler, telwoord, kern.' },
                { k: 'al die fietsen', out: 'goed', note: 'al staat vóór de bepaler.' },
                { k: 'die al fietsen', out: 'fout', note: 'al moet helemaal vooraan.' },
                { k: 'alle drie de fietsen', out: 'goed', note: 'Een vaste constructie: alle + telwoord + de.' },
              ],
            },
            quiz: {
              q: 'Welke groep is goed?',
              options: ['al die oude fietsen', 'die al oude fietsen', 'die oude al fietsen'],
              answer: 'al die oude fietsen',
              why: 'al staat vóór de bepaler die, het bijvoeglijk naamwoord oude vlak voor de kern.',
            },
          },
          {
            text: 'Na de kern komen de *nabepalingen*. Dat kan een voorzetselgroep zijn (*de man met de hoed*), een bijzin (*de man die daar staat*) of zelfs een bijwoord (*de man daar*, *het huis hier*). Al die nabepalingen horen bij het blok.',
            phrase: {
              q: 'Vind de hele naamwoordgroep met kern huis en de twee nabepalingen',
              sentence: 'Het huis daar met het rode dak is van mijn oom.',
              groups: [
                { span: [0, 6], cat: 'naamwoordgroep', head: 1, note: 'Vervangtest: Het is van mijn oom. Alles tot dak gaat weg.' },
                { span: [2, 2], cat: 'bijwoordgroep', head: 2, note: 'Een bijwoord als nabepaling: welk huis? Dat daar.' },
                { span: [3, 6], cat: 'voorzetselgroep', head: 3, note: 'Tweede nabepaling: welk huis? Dat met het rode dak.' },
              ],
              traps: [
                { span: [0, 1], note: 'Het huis stopt bij de kern. Maar daar en met het rode dak horen erbij.' },
                { span: [6, 7], note: 'dak is loopt over de grens van het onderwerp heen.' },
              ],
              note: 'Een kern met twee nabepalingen: een bijwoord en een voorzetselgroep.',
            },
          },
        ],
      },
      {
        kind: 'order',
        id: 'neven',
        prompt: 'Zet de woorden in de goede volgorde.',
        tiles: ['oude', 'vijf', 'al', 'neven', 'mijn'],
        answer: 'al mijn vijf oude neven',
        why: 'al, bepaler mijn, telwoord vijf, bijvoeglijk naamwoord oude, kern neven.',
      },
      {
        kind: 'sort',
        id: 'bepalers',
        prompt: 'Wat voor bepaler is het?',
        buckets: ['lidwoord', 'aanwijzend voornaamwoord', 'bezittelijk voornaamwoord', 'kwantor'],
        items: [
          { t: 'het', b: 0 },
          { t: 'een', b: 0 },
          { t: 'deze', b: 1 },
          { t: 'dat', b: 1 },
          { t: 'onze', b: 2 },
          { t: 'hun', b: 2 },
          { t: 'elke', b: 3 },
          { t: 'sommige', b: 3 },
          { t: 'geen', b: 3 },
        ],
        why: 'het en een zijn lidwoorden. deze en dat wijzen aan. onze en hun geven een bezitter. elke, sommige en geen zeggen hoeveel: kwantoren. De ANS noemt die laatste onbepaalde voornaamwoorden of hoofdtelwoorden.',
      },
      {
        kind: 'choice',
        id: 'een-bepaler',
        prompt: 'Welke groep is fout?',
        before: '',
        after: '',
        options: ['de mijn fiets', 'mijn fiets', 'die fiets van mij', 'al mijn fietsen'],
        answer: 'de mijn fiets',
        why: 'de en mijn zijn allebei bepalers en strijden om dezelfde plek.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Kale naamwoorden en een wet van Greenberg',
        panels: [
          {
            text: 'Soms heeft een naamwoordgroep helemaal geen bepaler. Dat kan bij een *meervoud* (*Boeken zijn duur*) en bij een *stofnaam*: een woord voor iets wat je niet telt, zoals *water*, *zand* of *goud* (*Ik drink water*). Zo’n groep heet *kaal*. Een telbaar zelfstandig naamwoord in het enkelvoud mag niet kaal zijn: ∗*Ik koop fiets* (fout). Er zijn vaste uitzonderingen, zoals *auto rijden* en *piano spelen*.',
            rule: 'Kaal kan: meervoud en stofnamen. Kaal kan niet: telbaar enkelvoud.',
            mark: {
              q: 'Tik de kale zelfstandige naamwoorden (zonder bepaler)',
              sentence: 'Ik kocht brood en een fles melk voor de kinderen.',
              targets: [2, 6],
              note: 'brood en melk zijn stofnamen zonder bepaler. fles heeft een, kinderen heeft de.',
            },
          },
          {
            text: 'Is de volgorde bepaler, telwoord, bijvoeglijk naamwoord toeval? Joseph Greenberg vergeleek in 1963 de woordvolgorde van zo’n dertig talen. Zijn *Universal 20* zegt: als het aanwijzend woord, het telwoord en het bijvoeglijk naamwoord vóór het naamwoord staan, dan altijd in die volgorde. Nederlands *die drie mooie boeken* en Engels *those three nice books* volgen die wet. Guglielmo Cinque gaf in 2005 een structurele verklaring.',
            rule: 'Greenberg (1963), Universal 20: staan ze vóór het naamwoord, dan is het aanwijzend woord · telwoord · bijvoeglijk naamwoord.',
            quiz: {
              q: 'Welke volgorde verbiedt Universal 20?',
              options: ['drie die mooie boeken', 'die drie mooie boeken'],
              answer: 'drie die mooie boeken',
              why: 'Als alles vóór het naamwoord staat, komt het aanwijzend woord eerst, dan het telwoord.',
            },
          },
          {
            text: 'De volgorde volgt ook de boom. Het bijvoeglijk naamwoord hoort het dichtst bij de kern, daarna komt het telwoord, en de bepaler sluit de groep af. Daarom bouw je *die drie mooie boeken* van binnen naar buiten.',
            bracket: {
              q: 'Bouw de naamwoordgroep van binnen naar buiten',
              words: true,
              tree: '[die [drie [mooie boeken]]]',
              nodes: [
                { w: 'mooie boeken', cat: 'N′', note: 'mooie zegt iets over boeken: het blok het dichtst bij de kern.' },
                { w: 'drie mooie boeken', cat: 'N′', note: 'drie telt de mooie boeken.' },
                { w: 'die drie mooie boeken', cat: 'naamwoordgroep', note: 'De bepaler sluit de groep af.' },
              ],
              traps: [
                { w: 'die drie', note: 'die wijst de hele groep drie mooie boeken aan, niet alleen het telwoord.' },
                { w: 'drie mooie', note: 'drie telt boeken, niet de eigenschap mooie.' },
              ],
              note: 'Van binnen naar buiten: eigenschap, aantal, bepaler. Dat is ook de volgorde van Universal 20, van achteren gelezen.',
            },
            deep: {
              q: 'En na iets, niets en veel?',
              a: 'Daar krijgt het bijvoeglijk naamwoord een *-s* en staat het achter het voornaamwoord: *iets moois*, *niets nieuws*, *veel lekkers*. Dat is een oude *partitieve genitief*: een naamval die een deel van een geheel aanduidt. ∗*Iets mooi* (fout) is dus geen gewone naamwoordgroep met een nabepaling.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'kaal',
        prompt: 'Mag het zelfstandig naamwoord hier kaal staan?',
        buckets: ['goed zonder bepaler', 'bepaler nodig'],
        items: [
          { t: 'Ik drink water.', b: 0 },
          { t: 'Boeken zijn duur.', b: 0 },
          { t: 'Goud glimt.', b: 0 },
          { t: 'Er ligt zand op de stoep.', b: 0 },
          { t: 'Hij heeft geduld.', b: 0 },
          { t: 'Ik koop fiets.', b: 1 },
          { t: 'Kind speelt buiten.', b: 1 },
          { t: 'Ik zag hond.', b: 1 },
          { t: 'Ik heb vraag.', b: 1 },
        ],
        why: 'Water, zand, goud en geduld tel je niet; boeken is meervoud. Fiets, kind, hond en vraag zijn telbaar enkelvoud: die hebben een bepaler nodig (een fiets, het kind).',
      },
      {
        kind: 'type',
        id: 'iets-nieuws',
        prompt: 'Vul de goede vorm van ‘nieuw’ in.',
        before: 'Heb jij al iets',
        after: 'gehoord?',
        hint: 'nieuw…',
        answer: 'nieuws',
        why: 'Na iets, niets, veel en wat krijgt het bijvoeglijk naamwoord een -s: iets nieuws.',
      },
      {
        kind: 'proofread',
        id: 'cadeau',
        prompt: 'Tik de fouten in de naamwoordgroepen aan.',
        intro: 'Er zitten drie fouten in.',
        tokens: [
          { t: 'Gisteren' },
          { t: 'kocht' },
          { t: 'ik' },
          { t: 'boek', fix: 'een boek', why: 'Een telbaar enkelvoud kan niet kaal staan.' },
          { t: 'over' },
          { t: 'Amsterdam.' },
          { t: 'Het' },
          { t: 'is' },
          { t: 'voor' },
          { t: 'de mijn', fix: 'mijn', why: 'Twee bepalers op één plek: alleen mijn blijft over.' },
          { t: 'zus.' },
          { t: 'Ze' },
          { t: 'wilde' },
          { t: 'al' },
          { t: 'lang' },
          { t: 'iets' },
          { t: 'nieuw', fix: 'nieuws', why: 'Na iets krijgt het bijvoeglijk naamwoord een -s.' },
          { t: 'over' },
          { t: 'haar' },
          { t: 'stad' },
          { t: 'lezen.' },
        ],
        done: { title: 'Drie gerepareerd', text: 'een boek, mijn zus en iets nieuws. haar stad was goed: één bepaler, één kern.' },
      },
      {
        kind: 'bet',
        id: 'universal',
        prompt: 'Een taal zet het aanwijzend woord, het telwoord en het bijvoeglijk naamwoord alle drie vóór het naamwoord. Welke volgorde verwacht je?',
        options: [
          'aanwijzend · telwoord · bijvoeglijk · naamwoord',
          'telwoord · aanwijzend · bijvoeglijk · naamwoord',
          'bijvoeglijk · telwoord · aanwijzend · naamwoord',
        ],
        answer: 'aanwijzend · telwoord · bijvoeglijk · naamwoord',
        why: 'Greenbergs Universal 20 (1963). Het Nederlands volgt hem: die drie mooie boeken.',
      },
      {
        kind: 'swipe',
        id: 'np-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'In ‘al de drie mooie boeken’ staat al vóór de bepaler.', ok: true, why: 'al is het enige woord dat daar kan.' },
          { t: 'In het Nederlands kun je twee bepalers combineren: de mijn fiets.', ok: false, fix: 'mijn fiets', why: 'Er is maar één plek voor de bepaler.' },
          { t: 'Een stofnaam als water kan zonder bepaler staan.', ok: true, why: 'Ik drink water.' },
          { t: 'In ‘de man daar’ is daar een nabepaling.', ok: true, why: 'Een bijwoord als nabepaling: welke man? Die daar.' },
          {
            t: 'Een telbaar enkelvoud kan altijd kaal staan.',
            ok: false,
            fix: 'het heeft een bepaler nodig',
            why: 'Ik koop een fiets, niet Ik koop fiets. Vaste uitzonderingen als auto rijden daargelaten.',
          },
          { t: 'Greenberg publiceerde zijn universalia van woordvolgorde in 1963.', ok: true, why: 'Universal 20 gaat over de naamwoordgroep.' },
        ],
      },
    ],
  },
  {
    id: 'p6',
    stage: 'bachelor',
    domain: 'syn',
    also: ['sem', 'orth'],
    title: 'Bijvoeglijke naamwoorden stapelen',
    skill: 'Zinsbouw',
    icon: 'bn+',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Een vaste rij voor eigenschappen',
        panels: [
          {
            text: 'Wie ‘een Franse oude mooie wijn’ bestelt, klinkt alsof hij al te veel heeft geproefd. Sprekers zeggen *een mooie oude Franse wijn*. Bijvoeglijke naamwoorden (woorden voor eigenschappen) vóór een zelfstandig naamwoord volgen een vaste neiging: *mening* > *maat* > *leeftijd* > *vorm* > *kleur* > *herkomst* > *materiaal*. Hoe verder rechts in die rij, hoe dichter bij de kern.',
            rule: 'Volgorde: mening · maat · leeftijd · vorm · kleur · herkomst · materiaal · kern.',
            swap: {
              goal: 'Zet de bijvoeglijke naamwoorden in de gewone volgorde.',
              blocks: ['rode', 'een', 'grote', 'mooie', 'auto'],
              accept: ['een mooie grote rode auto'],
              note: 'mening (mooie), maat (grote), kleur (rode), dan de kern auto.',
            },
          },
          {
            text: 'Tik een soort eigenschap en zie welke woorden erbij horen. Let op de *materiaalwoorden*: *houten*, *wollen*, *gouden*. Die eindigen op *-en* en staan het dichtst bij de kern.',
            lab: {
              label: 'Tik een soort eigenschap',
              chips: [
                { k: 'mening', out: 'mooi, lelijk, lekker, saai', note: 'Wat de spreker ervan vindt; staat het verst van de kern.' },
                { k: 'maat', out: 'groot, klein, lang, dik', note: 'Hoe groot iets is.' },
                { k: 'leeftijd', out: 'oud, nieuw, jong', note: 'Hoe oud iets is.' },
                { k: 'vorm', out: 'rond, vierkant, smal', note: 'Welke vorm iets heeft.' },
                { k: 'kleur', out: 'rood, groen, zwart', note: 'Welke kleur iets heeft.' },
                { k: 'herkomst', out: 'Frans, Italiaans, Gronings', note: 'Waar iets vandaan komt.' },
                { k: 'materiaal', out: 'houten, wollen, gouden', note: 'Waarvan iets gemaakt is; staat het dichtst bij de kern.' },
              ],
            },
            quiz: {
              q: 'Welke groep klinkt het natuurlijkst?',
              options: ['een oude ronde houten tafel', 'een houten ronde oude tafel', 'een ronde oude houten tafel'],
              answer: 'een oude ronde houten tafel',
              why: 'Leeftijd, vorm, materiaal: oude, ronde, houten.',
            },
          },
          {
            text: 'Soms staan twee bijvoeglijke naamwoorden *naast* elkaar, op hetzelfde niveau: *een lange, saaie vergadering* is een vergadering die lang is en saai. Dat heet *nevengeschikt*, en daar zet je een komma. Soms staan ze *op elkaar*: *een oude Franse wijn* is een Franse wijn die oud is. Dat heet *gestapeld*: geen komma. De test: kun je *en* ertussen zetten en de volgorde omdraaien? *Een lange en saaie vergadering*, *een saaie, lange vergadering*: ja, dus komma. ∗*Een oude en Franse wijn* (fout): nee, dus geen komma.',
            rule: 'Kan er en tussen en kun je ze omdraaien? Dan nevengeschikt: zet een komma.',
            quiz: {
              q: 'Welke groep heeft terecht een komma?',
              options: ['een spannend, grappig boek', 'een klein, houten huisje', 'een oud, Frans kasteel'],
              answer: 'een spannend, grappig boek',
              why: 'spannend en grappig boek kan, en grappig, spannend ook. klein houten en oud Frans zijn gestapeld: geen komma.',
            },
          },
        ],
      },
      {
        kind: 'order',
        id: 'tas',
        prompt: 'Zet de woorden in de natuurlijke volgorde.',
        tiles: ['leren', 'Italiaanse', 'een', 'prachtige', 'oude', 'tas'],
        answer: 'een prachtige oude Italiaanse leren tas',
        why: 'Mening (prachtige), leeftijd (oude), herkomst (Italiaanse), materiaal (leren), dan de kern tas.',
      },
      {
        kind: 'sort',
        id: 'komma-of-niet',
        prompt: 'Hoort er een komma tussen de twee bijvoeglijke naamwoorden?',
        buckets: ['komma: nevengeschikt', 'geen komma: gestapeld'],
        items: [
          { t: 'een lange saaie vergadering', b: 0 },
          { t: 'een koude natte dag', b: 0 },
          { t: 'een vriendelijke behulpzame buurvrouw', b: 0 },
          { t: 'een slimme grappige collega', b: 0 },
          { t: 'een oude Franse wijn', b: 1 },
          { t: 'een kleine houten doos', b: 1 },
          { t: 'een grote rode bal', b: 1 },
          { t: 'een mooie zilveren ring', b: 1 },
          { t: 'een donkere wollen jas', b: 1 },
        ],
        why: 'Lang en saai, koud en nat, vriendelijk en behulpzaam, slim en grappig: en past ertussen, dus komma. Bij de andere staat het tweede woord vast aan de kern (Franse wijn, houten doos, rode bal): gestapeld, geen komma.',
      },
      {
        kind: 'rewrite',
        id: 'keet',
        prompt: 'Zet een komma waar die hoort, en nergens anders.',
        source: 'Het was een lange saaie vergadering in een kleine houten keet.',
        accept: ['Het was een lange, saaie vergadering in een kleine houten keet.'],
        why: 'lang en saai zijn nevengeschikt: komma. klein en houten zijn gestapeld (maat en materiaal): geen komma.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Waarom die volgorde?',
        panels: [
          {
            text: 'De volgorde is geen Nederlandse gril. Richard Sproat en Chilin Shih (1991) vonden vergelijkbare beperkingen in talen die niet verwant zijn, zoals Engels en Mandarijn. Guglielmo Cinque (*The Syntax of Adjectives*, 2010) zag er een vaste rij plaatsen in de boom in. Bij gestapelde bijvoeglijke naamwoorden zit elk woord op een eigen laag: *mooie* zegt iets over *oude Franse wijn*, niet alleen over *wijn*.',
            bracket: {
              q: 'Bouw de gestapelde groep van binnen naar buiten',
              words: true,
              tree: '[mooie [oude [Franse wijn]]]',
              nodes: [
                { w: 'Franse wijn', cat: 'N′', note: 'Herkomst zit het dichtst bij de kern: samen bijna een soortnaam.' },
                { w: 'oude Franse wijn', cat: 'N′', note: 'oude zegt iets over Franse wijn.' },
                { w: 'mooie oude Franse wijn', cat: 'N′', note: 'De mening komt als laatste en gaat over het hele blok.' },
              ],
              traps: [
                { w: 'mooie oude', note: 'mooie gaat over de oude Franse wijn, niet over het woord oude.' },
                { w: 'oude Franse', note: 'Franse hoort eerst bij wijn: het is een Franse wijn die oud is.' },
              ],
              note: 'Elke laag een nieuw blok. Daarom geen komma: de woorden staan niet naast elkaar.',
            },
            quiz: {
              q: 'Wat betekent ‘een oude Franse wijn’ volgens de boom?',
              options: ['een Franse wijn die oud is', 'een wijn die oud en Frans is, op hetzelfde niveau', 'een wijn uit het oude Frankrijk'],
              answer: 'een Franse wijn die oud is',
              why: 'Franse wijn is eerst een blok; oude zegt daar iets over.',
            },
          },
          {
            text: 'Waarom staat de mening buiten en het materiaal binnen? Gregory Scontras, Judith Degen en Noah Goodman (2017) lieten proefpersonen beoordelen hoe *subjectief* een bijvoeglijk naamwoord is: hoeveel mensen het erover oneens kunnen zijn. Hoe subjectiever, hoe verder van de kern. Over *mooi* verschillen mensen van mening, over *houten* bijna nooit. Woorden met een vaste, objectieve betekenis staan dus vlak bij het naamwoord.',
            rule: 'Hoe subjectiever het bijvoeglijk naamwoord, hoe verder het van de kern staat.',
            quiz: {
              q: 'Welk woord staat volgens die verklaring het dichtst bij de kern?',
              options: ['wollen', 'lekker', 'groot'],
              answer: 'wollen',
              why: 'Over wollen is bijna niemand het oneens: het is het minst subjectief.',
            },
          },
          {
            text: 'Bij nevenschikking is de boom anders. In *een lange, saaie vergadering* vormen *lange* en *saaie* eerst samen een blok, met de komma als verborgen *en*. Daarom kun je ze omdraaien. Een gemarkeerde volgorde kan wel, maar dan zegt je klemtoon iets: *een FRANSE oude wijn* is de Franse, niet een van de andere oude wijnen.',
            lab: {
              label: 'Tik een groep en doe de en-test',
              chips: [
                { k: 'lange, saaie vergadering', out: 'lange en saaie · saaie, lange: kan', note: 'Nevengeschikt: komma.' },
                { k: 'oude Franse wijn', out: 'oude en Franse: kan niet', note: 'Gestapeld: geen komma.' },
                { k: 'grote rode bal', out: 'grote en rode: vreemd', note: 'Maat en kleur zijn verschillende soorten: gestapeld.' },
                { k: 'koude, natte dag', out: 'koude en natte · natte, koude: kan', note: 'Twee indrukken van dezelfde soort: komma.' },
              ],
            },
            deep: {
              q: 'Is die komma een regel of een advies?',
              a: 'De komma tussen nevengeschikte bijvoeglijke naamwoorden is de gewone schrijfwijze; hij vervangt *en*. Bij een rij van drie of meer krijg je *een lange, saaie en nutteloze vergadering*: komma’s, en *en* voor het laatste woord. Bij gestapelde woorden is een komma echt fout, want dan suggereer je een *en* die er niet is: ∗*een oude, Franse wijn* zegt dat de wijn oud is en ook Frans, op hetzelfde niveau.',
            },
          },
        ],
      },
      {
        kind: 'choice',
        id: 'jas',
        prompt: 'Kies de natuurlijke volgorde.',
        before: 'Hij droeg een',
        after: 'jas.',
        options: ['dikke groene wollen', 'wollen groene dikke', 'groene dikke wollen'],
        answer: 'dikke groene wollen',
        why: 'Maat (dikke), kleur (groene), materiaal (wollen).',
      },
      {
        kind: 'proofread',
        id: 'heer',
        prompt: 'Tik de kommafouten aan.',
        intro: 'Er zitten drie fouten in: een komma die ontbreekt en twee die er te veel staan.',
        tokens: [
          { t: 'Op' },
          { t: 'een' },
          { t: 'koude', fix: 'koude,', why: 'koud en nat zijn nevengeschikt: een koude en natte avond. Dus een komma.' },
          { t: 'natte' },
          { t: 'avond' },
          { t: 'liep' },
          { t: 'een' },
          { t: 'oude,', fix: 'oude', why: 'oud zegt iets over Engelse heer: gestapeld, geen komma.' },
          { t: 'Engelse' },
          { t: 'heer' },
          { t: 'met' },
          { t: 'een' },
          { t: 'grote,', fix: 'grote', why: 'Maat en kleur zijn gestapeld: een grote zwarte hond.' },
          { t: 'zwarte' },
          { t: 'hond' },
          { t: 'door' },
          { t: 'de' },
          { t: 'stille,' },
          { t: 'donkere' },
          { t: 'straat.' },
        ],
        done: {
          title: 'Drie komma’s goed gezet',
          text: 'een koude, natte avond; een oude Engelse heer; een grote zwarte hond. De stille, donkere straat was al goed.',
        },
      },
      {
        kind: 'bet',
        id: 'deur',
        prompt: 'Is de komma goed in ‘een zware, houten deur’?',
        options: ['Nee: zwaar en houten zijn gestapeld', 'Ja: er staan twee bijvoeglijke naamwoorden'],
        answer: 'Nee: zwaar en houten zijn gestapeld',
        why: 'Maat en materiaal. Een zware en houten deur klinkt vreemd, en een houten zware deur ook. Dus: een zware houten deur.',
      },
      {
        kind: 'swipe',
        id: 'stapel-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Materiaalwoorden als houten staan het dichtst bij de kern.', ok: true, why: 'een kleine houten doos.' },
          {
            t: 'Een mening staat gewoonlijk vlak voor het zelfstandig naamwoord.',
            ok: false,
            fix: 'een mening staat het verst van de kern',
            why: 'een mooie oude Franse wijn.',
          },
          { t: 'Bij nevengeschikte bijvoeglijke naamwoorden kun je en ertussen zetten.', ok: true, why: 'een lange en saaie vergadering.' },
          { t: 'In ‘een oude, Franse wijn’ hoort een komma.', ok: false, fix: 'een oude Franse wijn', why: 'Gestapeld: oud zegt iets over Franse wijn.' },
          {
            t: 'Volgens Scontras, Degen en Goodman (2017) staan subjectieve woorden verder van de kern.',
            ok: true,
            why: 'Over mooi verschillen we meer van mening dan over houten.',
          },
          {
            t: 'Beperkingen op de volgorde van bijvoeglijke naamwoorden vind je alleen in het Nederlands.',
            ok: false,
            fix: 'ook in niet-verwante talen',
            why: 'Sproat en Shih (1991) vergeleken onder meer Engels en Mandarijn.',
          },
        ],
      },
    ],
  },
];
