import type { LessonInput } from '../schema';

/**
 * Masterlessen voor het niveau "De letter": grafematiek, spellinggeschiedenis, de psychologie
 * van het lezen en de informatietheorie van letters. Ze komen na de lessen uit `letter.ts`.
 */
export const LETTER_MASTER_LESSONS: LessonInput[] = [
  {
    id: 'l11',
    stage: 'master',
    domain: 'orth',
    title: 'Grafeem en allograaf',
    skill: 'Spelling',
    icon: 'aɑ',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Eén letter, veel gezichten',
        panels: [
          {
            text: 'Welkom bij de master. Een *a* in dit lettertype, een ronde *ɑ* in je handschrift, een *A* op een bord: drie vormen, één letter. De *grafematiek*, de taalkunde van het schrift, noemt die vormen *allografen* van één *grafeem*. Net zoals een foneem verschillende uitspraken heeft, heeft een grafeem verschillende vormen.',
            lab: {
              label: 'Tik een vorm',
              chips: [
                { k: 'a', out: 'a', note: 'De gedrukte a met een boogje erboven.' },
                { k: 'ɑ', out: 'ɑ', note: 'De ronde a uit veel handschriften. Zelfde grafeem.' },
                { k: 'A', out: 'A', note: 'De hoofdletter: weer een andere vorm.' },
                { k: 'g', out: 'g / ɡ', note: 'Een g met twee lussen of met één: zelfde grafeem.' },
              ],
            },
            deep: {
              q: 'Wanneer is een vorm een eigen grafeem?',
              a: 'Als de vorm een verschil in betekenis kan maken. In het Nederlands maakt *a* tegenover *ɑ* geen verschil: het blijft hetzelfde woord. In het IPA, het alfabet van de fonetiek, wel: [a] en [ɑ] zijn twee verschillende klanken. Wat een allograaf is, hangt dus af van het systeem.',
            },
          },
          {
            text: 'Hoe vind je grafemen? Met een *minimaal paar*: twee woorden die maar in één teken verschillen. *bak*, *dak* en *pak* verschillen alleen in de eerste letter, dus *b*, *d* en *p* zijn verschillende grafemen. Toch zijn het bijna spiegelbeelden. Daarom haalt elk kind ze in het begin door elkaar.',
            mark: {
              q: 'Tik alle woorden die precies één letter verschillen van bak',
              sentence: 'dak bal pak bek baken bakken',
              targets: [0, 1, 2, 3],
              note: 'dak, bal, pak en bek: vier minimale paren met bak. baken en bakken zijn langer.',
            },
            deep: {
              q: 'Waarom spiegelen kinderen letters?',
              a: 'Ons brein herkent een voorwerp van links en van rechts als hetzelfde: een leeuw blijft een leeuw. Bij letters moet je dat afleren, want *b* en *d* zijn echt verschillend. De neurowetenschapper Stanislas Dehaene noemt lezen daarom *recycling*: oude hersengebieden krijgen een nieuwe taak. Meer daarover in de les over lezen in je hoofd.',
            },
          },
          {
            text: 'Is *ch* één grafeem of twee? Daarover verschillen taalkundigen. De ene school zegt: een grafeem is een letter of lettergroep voor één foneem, dus *ch*, *ng* en *oe* zijn grafemen. Dat heet de *afhankelijkheidsvisie*: het schrift wordt vanuit de klank bekeken. De andere school, de *autonome visie*, kijkt alleen naar het schrift zelf. Dan is een grafeem de kleinste eenheid die betekenis onderscheidt, en dat is de losse letter.',
            split: { q: 'Knip het woord in grafemen, zoals de eerste school', word: 'schoen', answer: 's-ch-oe-n', note: 's, ch, oe en n: vier grafemen voor vier klanken.' },
            quiz: {
              q: 'Hoeveel grafemen heeft ‘boeken’ volgens de eerste school?',
              options: ['4', '5', '6'],
              answer: '5',
              why: 'b, oe, k, e, n: vijf grafemen, en ook vijf klanken.',
            },
          },
          {
            text: 'De twee scholen geven verschillende antwoorden op dezelfde woorden. Voor de afhankelijkheidsvisie heeft *lachen* vijf grafemen: *l-a-ch-e-n*. Voor de autonome visie zes: elke letter. Wie heeft gelijk? Dat hangt af van je vraag. Wil je spelling onderwijzen, dan is de eerste handig. Wil je het schrift als eigen systeem beschrijven, zoals in de Duitse grafematiek van onder anderen Peter Eisenberg, dan de tweede.',
            split: { q: 'Knip lachen in grafemen volgens de afhankelijkheidsvisie', word: 'lachen', answer: 'l-a-ch-e-n', note: 'l, a, ch, e, n: vijf grafemen voor vijf klanken.' },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'allograaf',
        prompt: 'Zelfde grafeem of ander grafeem?',
        buckets: ['zelfde grafeem, andere vorm', 'ander grafeem'],
        items: [
          { t: 'a en A', b: 0 },
          { t: 'b en d', b: 1 },
          { t: 'a en ɑ in een Nederlands boek', b: 0 },
          { t: 'a en ɑ in het IPA', b: 1 },
          { t: 'n en u', b: 1 },
          { t: 'r in drukletters en in schrijfletters', b: 0 },
          { t: 'g met één of twee lussen', b: 0 },
          { t: 'i en l', b: 1 },
        ],
        why: 'Vormen van één grafeem veranderen de betekenis nooit. b en d wel: bak, dak. In het IPA zijn a en ɑ twee verschillende klanken.',
      },
      {
        kind: 'choice',
        id: 'bewijs',
        prompt: 'Welk paar bewijst dat k en l verschillende grafemen zijn?',
        before: '',
        after: '',
        options: ['bak en bal', 'bak en bakken', 'bak en BAK'],
        answer: 'bak en bal',
        why: 'Een minimaal paar: één letter verschil, andere betekenis.',
      },
      {
        kind: 'sort',
        id: 'twee-scholen',
        prompt: 'Hoeveel grafemen volgens de afhankelijkheidsvisie (één grafeem per klank)?',
        buckets: ['drie', 'vier', 'vijf'],
        items: [
          { t: 'zing', b: 0 },
          { t: 'schip', b: 1 },
          { t: 'deuren', b: 2 },
          { t: 'lach', b: 0 },
          { t: 'school', b: 1 },
          { t: 'zingen', b: 2 },
          { t: 'boek', b: 0 },
          { t: 'straat', b: 2 },
        ],
        why: 'zing (z-i-ng), lach (l-a-ch), boek (b-oe-k): drie. schip (s-ch-i-p), school (s-ch-oo-l): vier. deuren (d-eu-r-e-n), zingen (z-i-ng-e-n), straat (s-t-r-aa-t): vijf. Volgens de autonome visie tel je gewoon de letters.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Vrij of bepaald door de plek',
        panels: [
          {
            text: 'Allografen komen in twee soorten, net als allofonen in de fonologie. *Vrije* allografen kun je naar believen wisselen: een *g* met één of twee lussen, een *a* of *ɑ*. *Positionele* allografen hangen af van de plek in het woord. Het Griekse sigma schrijf je als *σ*, maar aan het eind van een woord als *ς*: *σοφός* (wijs).',
            rule: 'Vrije allografen wissel je zomaar. Positionele allografen wisselen met de plek in het woord.',
            lab: {
              label: 'Tik een schrift',
              chips: [
                { k: 'Grieks', out: 'σ … ς', note: 'De slot-sigma staat alleen aan het eind.' },
                { k: 'oud-Nederlands drukwerk', out: 'ſ … s', note: 'Lange ſ aan het begin en in het midden, ronde s aan het eind: ſlaapkamers.' },
                { k: 'Arabisch', out: 'vier vormen', note: 'Veel letters hebben een losse vorm, een beginvorm, een middenvorm en een eindvorm.' },
                { k: 'handschrift', out: 'g / ɡ', note: 'Vrij: geen plek die het voorschrijft.' },
              ],
            },
          },
          {
            text: 'De lange *ſ* stond tot ongeveer 1800 in Nederlandse boeken. Je leest *ſchip*, *ſlapen* en *wiſſel*, maar aan het eind van een woord altijd een ronde *s*: *huis*. Hij lijkt op een *f* zonder streepje rechts. Dat verwarde latere lezers zo dat de vorm verdween. De verdeling heet *complementaire distributie*: waar de ene vorm staat, staat de andere nooit.',
            quiz: {
              q: 'Hoe stond ‘wissels’ gedrukt in een boek uit 1700?',
              options: ['wiſſels', 'wissels', 'wiſſelſ'],
              answer: 'wiſſels',
              why: 'Lange ſ binnen het woord, ronde s aan het eind.',
            },
          },
          {
            text: 'Dan de *ligaturen*: twee letters die tot één teken versmelten. In goed zetwerk worden *f* en *i* samen *ﬁ*, zodat de punt van de *i* niet tegen de *f* botst. Soms wordt een ligatuur een eigen letter: de Deense *æ*, de Duitse *ß* uit *ſ* + *z* of *ſ* + *s*. En de Nederlandse *ij*? Die staat in Unicode als *ĳ*, één teken, maar we typen hem als *i* + *j*.',
            quiz: {
              q: 'Waaruit ontstond de Duitse ß?',
              options: ['uit lange ſ met z of s', 'uit b en s', 'uit twee gewone s’en'],
              answer: 'uit lange ſ met z of s',
              why: 'Een ligatuur die een eigen letter werd.',
            },
            deep: {
              q: 'Is de hoofdletter een allograaf?',
              a: 'Strikt genomen niet helemaal. *A* en *a* veranderen het woord niet, dus het lijken allografen. Maar een hoofdletter zegt wel iets: *de Kamer* (het parlement) is iets anders dan *de kamer* (een vertrek). De hoofdletter draagt dus betekenis op een hoger niveau dan de letter: hij markeert een eigennaam of een zinsbegin. Daarom zien veel grafematici hem als een eigen teken boven op de letter.',
            },
          },
          {
            text: 'Grafematiek staat tot het schrift zoals fonologie tot de klanken. En er is ook een tegenhanger van de fonetiek: de *grafetiek*. Die bestudeert de vorm zelf: lijnen, stokken, lettertypes, handschrift. De grafematiek vraagt welke vormen als *dezelfde* tellen in het systeem.',
            rule: 'fonetiek : fonologie = grafetiek : grafematiek',
            quiz: {
              q: 'Welk vak bestudeert het verschil tussen een schreefletter en een schreefloze letter?',
              options: ['de grafetiek', 'de grafematiek', 'de fonologie'],
              answer: 'de grafetiek',
              why: 'De vorm zelf is grafetiek. Voor het systeem zijn het allografen van dezelfde letters.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'vrij-positioneel',
        prompt: 'Vrije of positionele allografie?',
        buckets: ['vrij', 'positioneel'],
        items: [
          { t: 'σ en ς in het Grieks', b: 1 },
          { t: 'a en ɑ in handschrift', b: 0 },
          { t: 'ſ en s in oud drukwerk', b: 1 },
          { t: 'g met één of twee lussen', b: 0 },
          { t: 'begin- en eindvorm van een Arabische letter', b: 1 },
          { t: 'een a in Arial of in Times', b: 0 },
        ],
        why: 'Positioneel: de plek in het woord kiest de vorm (σ/ς, ſ/s, Arabische vormen). Vrij: de schrijver of het lettertype kiest (a/ɑ, g, Arial/Times).',
      },
      {
        kind: 'choice',
        id: 'lange-s',
        prompt: 'Een boek uit 1750. Welke spelling zie je?',
        before: '',
        after: '',
        options: ['ſchepſel', 'ſchepſelſ', 'schepſel', 'ſchepsel'],
        answer: 'ſchepſel',
        why: 'Aan het begin en in het midden de lange ſ. Er staat geen s aan het eind, dus geen ronde s.',
      },
      {
        kind: 'choice',
        id: 'grafetiek',
        prompt: 'Welke vraag hoort bij de grafematiek, niet bij de grafetiek?',
        before: '',
        after: '',
        options: [
          'Telt ch als één eenheid van het schrift?',
          'Hoe hoog is de x-hoogte van dit lettertype?',
          'Hoe dik zijn de schreven?',
        ],
        answer: 'Telt ch als één eenheid van het schrift?',
        why: 'De grafematiek gaat over het systeem: welke eenheden er zijn. Vorm en maten zijn grafetiek.',
      },
      {
        kind: 'swipe',
        id: 'scholen',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Volgens de afhankelijkheidsvisie is ng in zingen één grafeem.', ok: true, why: 'ng staat voor één klank.' },
          {
            t: 'Een allograaf kan de betekenis van een woord veranderen.',
            ok: false,
            fix: 'een allograaf verandert de betekenis nooit',
            why: 'Anders was het een eigen grafeem.',
          },
          { t: 'b, d, p en q zijn bijna spiegelbeelden van elkaar.', ok: true, why: 'Daarom halen beginnende lezers ze door elkaar.' },
          { t: 'De Griekse slot-sigma ς kan ook midden in een woord staan.', ok: false, fix: 'alleen aan het eind', why: 'σ en ς staan in complementaire distributie.' },
          { t: 'De Duitse ß is ontstaan uit een ligatuur.', ok: true, why: 'Uit lange ſ met z of s.' },
          { t: 'Grafetiek bestudeert het systeem, grafematiek de vorm.', ok: false, fix: 'andersom', why: 'Grafetiek: de vorm. Grafematiek: het systeem.' },
          { t: 'In het IPA is het verschil tussen a en ɑ een verschil in klank.', ok: true, why: 'Het IPA moet elke klank een eigen teken geven.' },
        ],
      },
    ],
  },
  {
    id: 'l12',
    stage: 'master',
    domain: 'orth',
    title: 'Spelling met een geschiedenis',
    skill: 'Spelling',
    icon: 'sch',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'De spelling van je overgrootouders',
        panels: [
          {
            text: 'Je overgrootouders schreven *de boomen*, *zoo* en *de mensch*. Spelling is een afspraak, en afspraken veranderen. Rond 1947 verdween in Nederland en België de *sch* aan het eind van *mensch* en *visch*, en de dubbele klinker in *boomen* en *loopen*.',
            lab: {
              label: 'Tik een woord van vroeger',
              chips: [
                { k: 'boomen', out: 'bomen', note: 'Open lettergreep: één o is genoeg.' },
                { k: 'mensch', out: 'mens', note: 'De ch hoorde je al lang niet meer.' },
                { k: 'zoo', out: 'zo', note: 'Aan het eind van een woord is één o al lang.' },
                { k: 'den man', out: 'de man', note: 'Naamvalsvormen als den en des verdwenen uit de spelling.' },
              ],
            },
          },
          {
            text: 'Maar één groep hield zijn *sch*: bijvoeglijke naamwoorden op *-isch*. Daarom schrijf je nog steeds *logisch*, *praktisch* en *Belgisch*, al zeg je gewoon een *s*. Een fossiel uit de oude spelling, midden in je tekst. Ook namen houden het: *’s-Hertogenbosch*, *Den Bosch*.',
            rule: 'Bijvoeglijk naamwoord dat eindigt op de klank -ies? Schrijf *-isch*: *logisch*.',
            mark: {
              q: 'Tik de woorden met een ch die je niet hoort',
              sentence: 'logisch schip mens praktisch school tropisch',
              targets: [0, 3, 5],
              note: 'In logisch, praktisch en tropisch hoor je geen ch. In schip en school wel.',
            },
          },
          {
            text: 'Wie beslist over spelling? Sinds 1980 de Nederlandse Taalunie, voor Nederland en Vlaanderen, en later ook Suriname. De officiële woordenlijst heet het *Groene Boekje*. In 1995 en 2005 veranderden nog regels, bijvoorbeeld voor de tussen-n: *pannekoek* werd *pannenkoek*.',
            quiz: {
              q: 'Waarom schrijf je ‘logisch’ met sch?',
              options: ['Het is een fossiel uit de oude spelling', 'Je hoort de ch duidelijk', 'Het komt uit het Engels'],
              answer: 'Het is een fossiel uit de oude spelling',
              why: 'Bij -isch bleef de oude spelling staan, ook al hoor je alleen een s.',
            },
          },
        ],
      },
      {
        kind: 'rewrite',
        id: 'modern',
        prompt: 'Zet deze zin uit 1930 in de spelling van nu.',
        source: 'Zoo loopen de menschen onder de boomen.',
        accept: ['Zo lopen de mensen onder de bomen.'],
        why: 'zoo → zo, loopen → lopen, menschen → mensen, boomen → bomen.',
      },
      {
        kind: 'sort',
        id: 'oud-nieuw',
        prompt: 'Spelling van nu of van vroeger?',
        buckets: ['van nu', 'van vroeger'],
        items: [
          { t: 'logisch', b: 0 },
          { t: 'visch', b: 1 },
          { t: 'pannenkoek', b: 0 },
          { t: 'zoo', b: 1 },
          { t: 'praktisch', b: 0 },
          { t: 'loopen', b: 1 },
          { t: 'paardenbloem', b: 0 },
          { t: 'den koning', b: 1 },
          { t: 'tropisch', b: 0 },
          { t: 'paardebloem', b: 1 },
        ],
        why: 'logisch, praktisch en tropisch houden hun sch. visch, zoo, loopen en den koning zijn spelling van vóór 1947. pannenkoek kreeg zijn n in 1995, paardenbloem in 2005.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Twee eeuwen spellingstrijd',
        panels: [
          {
            text: 'In 1804 kreeg Nederland zijn eerste officiële spelling, van de Leidse hoogleraar Matthijs Siegenbeek, en in 1805 een officiële grammatica van Petrus Weiland. Vlaanderen deed daar niet aan mee: na 1830 zocht België zijn eigen weg, en lang schreef men daar anders.',
            quiz: {
              q: 'Van wie was de eerste officiële spelling van Nederland (1804)?',
              options: ['Siegenbeek', 'Kollewijn', 'De Vries en Te Winkel'],
              answer: 'Siegenbeek',
              why: 'Matthijs Siegenbeek, 1804. Kollewijn en De Vries en Te Winkel kwamen later.',
            },
          },
          {
            text: 'Voor het grote *Woordenboek der Nederlandsche Taal* maakten Matthias de Vries en Lammert te Winkel een spelling (1863–1866). België nam die in 1864 over, Nederland in 1883: voor het eerst één spelling voor beide. Zij schreven *mensch* en *visch* omdat de *ch* er ooit klonk, en maakten verschil tussen *zachtlange* en *scherplange* klinkers: *boomen* met *oo*, maar *hopen* met één *o*, op grond van de geschiedenis.',
            quiz: {
              q: 'Welk land nam de spelling van De Vries en Te Winkel als eerste over?',
              options: ['België', 'Nederland', 'Suriname'],
              answer: 'België',
              why: 'België in 1864, Nederland pas in 1883.',
            },
            rule: 'De Vries en Te Winkel: spelling naar uitspraak, gelijkvormigheid, analogie en afkomst.',
            deep: {
              q: 'Wat was dat verschil tussen zachtlang en scherplang?',
              a: 'In het Middelnederlands klonken twee soorten lange *o* en lange *e* verschillend, afhankelijk van hun herkomst. In de negentiende eeuw hoorde bijna niemand dat verschil nog, maar de spelling hield het vast. Wie *boomen* of *hopen* moest schrijven, moest dus de taalgeschiedenis kennen. Precies daar viel de kritiek op aan.',
            },
          },
          {
            text: 'In 1891 schreef de leraar Roeland Kollewijn het stuk *Onze lastige spelling*. Zijn voorstel: schrijf wat je zegt. Weg met de *sch* in *mensch*, weg met het verschil tussen *boomen* en *hopen*, weg met naamvallen als *den* en *des* die niemand meer zei. Het duurde decennia, maar het meeste kwam er: in Nederland eerst in 1934 op scholen (de spelling-Marchant), en in 1946 in België en 1947 in Nederland officieel.',
            quiz: {
              q: 'Wat was de kern van Kollewijns voorstel?',
              options: ['spelling dichter bij de uitspraak brengen', 'meer leenwoorden toelaten', 'de spelling van België overnemen'],
              answer: 'spelling dichter bij de uitspraak brengen',
              why: 'Schrijf wat je zegt: mens in plaats van mensch, bomen in plaats van boomen.',
            },
          },
          {
            text: 'In 1954 kwam het eerste *Groene Boekje*. Voor leenwoorden gaf het vaak twee spellingen: een *voorkeurspelling* en een *toegelaten* spelling, zoals *cadeau* naast *kado*. Dat leverde verwarring op en verdween in 1995. In 2005 volgden nog regels voor de tussen-n (*paardenbloem*), wat zoveel protest gaf dat het Genootschap Onze Taal in 2006 een eigen *Witte Boekje* uitbracht. De laatste editie van het Groene Boekje is van 2015.',
            quiz: {
              q: 'Waarom bracht Onze Taal in 2006 een eigen Witte Boekje uit?',
              options: ['uit onvrede met de regels van 2005', 'omdat er nog geen woordenlijst was', 'om de spelling van 1804 terug te brengen'],
              answer: 'uit onvrede met de regels van 2005',
              why: 'Vooral de nieuwe regels voor de tussen-n gaven protest.',
            },
            deep: {
              q: 'Wat leer je hiervan als taalkundige?',
              a: 'Elke hervorming kiest tussen principes die botsen. In 1947 won de uitspraak (*mens*, *bomen*). Bij *logisch* won de traditie. Bij *hond* met *d* wint de woordbouw. Bij de tussen-n won een abstracte regel over de vorm van het eerste deel, ook waar je geen n hoort. Spelling is dus geen natuurverschijnsel, maar een politieke en culturele afspraak.',
            },
          },
        ],
      },
      {
        kind: 'order',
        id: 'tijdlijn',
        prompt: 'Zet de gebeurtenissen in de tijd, van oud naar nieuw.',
        tiles: ['Witte Boekje', 'Siegenbeek', 'Kollewijn', 'De Vries en Te Winkel', 'eerste Groene Boekje', 'spelling zonder mensch'],
        answer: 'Siegenbeek De Vries en Te Winkel Kollewijn spelling zonder mensch eerste Groene Boekje Witte Boekje',
        why: 'Siegenbeek 1804, De Vries en Te Winkel 1863–1866, Kollewijn 1891, mens zonder ch officieel in 1946–1947, het eerste Groene Boekje in 1954 en het Witte Boekje in 2006.',
      },
      {
        kind: 'rewrite',
        id: 'modern-2',
        prompt: 'Zet deze zin uit 1920 in de spelling van nu.',
        source: 'De visschers zochten den grooten visch met hunne netten.',
        accept: ['De vissers zochten de grote vis met hun netten.'],
        why: 'visschers → vissers, den → de, grooten → grote, visch → vis, hunne → hun.',
      },
      {
        kind: 'choice',
        id: 'scherplang',
        prompt: 'Waarom vonden Kollewijn en anderen boomen naast hopen zo lastig?',
        before: '',
        after: '',
        options: [
          'Je moest de taalgeschiedenis kennen om het juiste aantal o’s te kiezen',
          'Boomen kon je niet uitspreken',
          'Het was een Belgische regel',
        ],
        answer: 'Je moest de taalgeschiedenis kennen om het juiste aantal o’s te kiezen',
        why: 'Het verschil tussen zachtlange en scherplange klinkers hoorde bijna niemand meer.',
      },
      {
        kind: 'bet',
        id: 'taalunie',
        prompt: 'Sinds wanneer beslist de Nederlandse Taalunie over de spelling?',
        options: ['1980', '1804', '1947'],
        answer: '1980',
        why: 'Nederland en België richtten de Taalunie in 1980 op. In 1804 kwam de eerste officiële spelling (Siegenbeek), in 1947 de spelling zonder sch en dubbele klinkers.',
      },
      {
        kind: 'swipe',
        id: 'geschiedenis-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'België nam de spelling van De Vries en Te Winkel eerder over dan Nederland.', ok: true, why: 'België in 1864, Nederland in 1883.' },
          { t: 'Kollewijn wilde de sch in mensch juist houden.', ok: false, fix: 'hij wilde hem schrappen', why: 'Schrijf wat je zegt: mens.' },
          { t: 'Het Witte Boekje is van het Genootschap Onze Taal.', ok: true, why: 'Uitgebracht in 2006, na protest tegen de regels van 2005.' },
          { t: 'De voorkeurspelling en toegelaten spelling bestaan nog steeds.', ok: false, fix: 'afgeschaft in 1995', why: 'Sinds 1995 heeft elk woord één spelling.' },
          { t: 'Dat je praktisch met sch schrijft, is een overblijfsel van de oude spelling.', ok: true, why: 'Bij -isch bleef de sch staan.' },
          { t: 'Spelling volgt altijd de uitspraak.', ok: false, fix: 'spelling is een afspraak tussen principes', why: 'logisch, hond en pannenkoek laten andere principes zien.' },
        ],
      },
    ],
  },
  {
    id: 'l15',
    stage: 'master',
    domain: 'orth',
    also: ['fon'],
    title: 'Letters in je hoofd',
    skill: 'Spelling',
    icon: 'lees',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Wat je ogen doen als je leest',
        panels: [
          {
            text: 'Het voelt alsof je ogen soepel over de regel glijden. Dat is niet zo. Ze springen. Zo’n sprong heet een *saccade*: vaak zo’n zeven tot negen letters ver, drie à vier keer per seconde. Tussen de sprongen staat je oog even stil, een *fixatie* van gemiddeld zo’n kwart seconde. Alleen tijdens die fixaties lees je; tijdens de sprong zie je zo goed als niets.',
            rule: 'Lezen is springen en stilstaan: saccades en fixaties.',
            quiz: {
              q: 'Wanneer neem je tijdens het lezen informatie op?',
              options: ['tijdens de fixaties', 'tijdens de saccades', 'de hele tijd even goed'],
              answer: 'tijdens de fixaties',
              why: 'Tijdens een sprong onderdrukt je brein het beeld grotendeels.',
            },
          },
          {
            text: 'Hoeveel zie je bij één fixatie? Minder dan je denkt. In het *bewegende-venster-experiment* van McConkie en Rayner (1975) toont een computer alleen de letters rond je blik en vervangt de rest door x-en. Lezers merken niets zolang het venster ongeveer drie à vier letters links en veertien à vijftien letters rechts van de fixatie beslaat. Je kijkt dus vooruit, in de leesrichting.',
            lab: {
              label: 'Tik een venster',
              chips: [
                { k: 'klein venster', out: 'xxxxx lezen gaxx xxxx xxxxxxx', note: 'Te klein: lezers gaan merkbaar trager.' },
                { k: 'groot venster', out: 'xxxxx lezen gaat best vlot xx', note: 'Vooruit genoeg ruimte: lezers merken niets.' },
              ],
            },
            deep: {
              q: 'En in het Hebreeuws?',
              a: 'Daar is het venster omgekeerd: groter naar links, want Hebreeuws lees je van rechts naar links (Pollatsek en collega’s, 1981). De asymmetrie zit dus niet in je oog, maar in je aandacht: je kijkt vooruit in de richting waarin je leest.',
            },
          },
          {
            text: 'Een letter herken je beter in een woord dan alleen. Toon iemand heel kort *WORK* of alleen *K*, en vraag dan: was het een D of een K? In het woord gaat het beter. Dat is het *woordsuperioriteitseffect* (Reicher 1969). McClelland en Rumelhart verklaarden het in 1981 met hun *interactieve-activatiemodel*: letters activeren woorden, en woorden geven op hun beurt hun letters een duwtje terug.',
            quiz: {
              q: 'Wat voorspelt het interactieve-activatiemodel?',
              options: [
                'Woordkennis helpt bij het herkennen van losse letters',
                'Letters worden pas na het woord herkend',
                'Woorden worden alleen aan hun omtrek herkend',
              ],
              answer: 'Woordkennis helpt bij het herkennen van losse letters',
              why: 'Het woord stuurt activatie terug naar zijn letters.',
            },
          },
          {
            text: 'Je kent vast het rondzingende bericht: *Vlgones een odnzreoek op Cmabirdge mkaat het neit uit in wlkee vlogrode de ltteers saatn*. Dat onderzoek in Cambridge heeft nooit bestaan. Maar er klopt iets van: verwisselde letters lezen opmerkelijk goed, vooral naast elkaar en midden in het woord. Dat heet het *transpositie-effect*: *jugde* roept *judge* bijna net zo snel op als het echte woord.',
            quiz: {
              q: 'Wat klopt er van het Cambridge-bericht?',
              options: ['het effect bestaat, het onderzoek niet', 'het onderzoek bestaat, het effect niet', 'allebei'],
              answer: 'het effect bestaat, het onderzoek niet',
              why: 'Verwisselde buren lees je goed, maar een onderzoek in Cambridge heeft er nooit achter gezeten.',
            },
            rule: 'Verwisselde buren midden in een woord lees je goed; verre verwisselingen en de eerste letter niet.',
            deep: {
              q: 'Wat zegt dat over hoe je letters codeert?',
              a: 'Dat je brein de plek van een letter niet als vast vakje opslaat, maar losser: ongeveer *d staat vóór g*. Modellen als die van Grainger en Whitney coderen woorden als paren letters in volgorde. Een verwisseling van buren laat de meeste paren heel, een verre verwisseling breekt er veel.',
            },
          },
        ],
      },
      {
        kind: 'choice',
        id: 'transpositie',
        prompt: 'Welke vorm van ‘onderzoek’ lees je het makkelijkst?',
        before: '',
        after: '',
        options: ['ondrezoek', 'kndeozoer', 'zoekonder', 'kreozdno'],
        answer: 'ondrezoek',
        why: 'Twee buren midden in het woord verwisseld; begin en eind staan goed. Bij de andere zijn verre letters en de eerste letter verplaatst.',
      },
      {
        kind: 'type',
        id: 'ontwar',
        prompt: 'Typ het bedoelde woord.',
        before: 'Vlgones mij is dit woord goed te lezen:',
        after: '',
        hint: 'het echte woord',
        answer: 'volgens',
        why: 'Vlgones = volgens, met verwisselde letters in het midden. De eerste en laatste letter helpen je enorm.',
      },
      {
        kind: 'bet',
        id: 'venster',
        prompt: 'Hoeveel letters rechts van je fixatie gebruik je ongeveer bij het lezen?',
        options: ['ongeveer 15', 'ongeveer 3', 'de hele regel'],
        answer: 'ongeveer 15',
        why: 'Ongeveer drie à vier letters naar links, veertien à vijftien naar rechts (McConkie en Rayner).',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Twee routes naar betekenis',
        panels: [
          {
            text: 'Hoe lees je een woord dat je nog nooit zag, zoals *flort*? Je zet letters om in klanken. Maar *chef* of *computer* lees je niet letter voor letter: dan zeg je *sjef* en een Engelse *u*. Het *tweerouteleesmodel* (Coltheart en collega’s, 2001) zegt: er is een *klankroute* die regels toepast, en een *woordroute* die het hele woord opzoekt in je geheugen.',
            rule: 'Klankroute: regels, werkt voor nieuwe woorden. Woordroute: opzoeken, nodig voor onregelmatige woorden.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'flort', out: 'alleen de klankroute', note: 'Geen bestaand woord: je kunt het alleen met regels lezen.' },
                { k: 'chef', out: 'de woordroute', note: 'Met de regels zou je ch als in lachen lezen.' },
                { k: 'bal', out: 'allebei', note: 'Regelmatig en bekend: beide routes geven hetzelfde.' },
              ],
            },
          },
          {
            text: 'Het bewijs komt onder meer uit hersenletsel. Bij *oppervlaktedyslexie* is de woordroute beschadigd: patiënten lezen nieuwe woorden goed, maar regulariseren onregelmatige woorden (*chef* klinkt als met de *ch* van *lachen*). Bij *fonologische dyslexie* is het omgekeerd: bekende woorden gaan goed, maar een nepwoord als *flort* lukt niet.',
            quiz: {
              q: 'Een patiënt leest ‘chef’ met de ch van ‘lachen’, maar ‘flort’ goed. Welke route is beschadigd?',
              options: ['de woordroute', 'de klankroute', 'allebei'],
              answer: 'de woordroute',
              why: 'Regels werken nog (flort), maar het opgeslagen woordbeeld voor chef ontbreekt: oppervlaktedyslexie.',
            },
          },
          {
            text: 'Lezen is te nieuw voor de evolutie: schrift bestaat pas zo’n vijfduizend jaar. Toch heeft elke geoefende lezer op ongeveer dezelfde plek in de linkerhersenhelft een gebied dat letterreeksen herkent: het *visuele woordvormgebied*. Volgens Stanislas Dehaene ‘recyclet’ lezen een gebied dat eigenlijk gezichten en voorwerpen herkent. Daarbij leer je ook iets af: spiegelbeelden als hetzelfde zien, want *b* is geen *d*.',
            quiz: {
              q: 'Wat moet je afleren als je leert lezen?',
              options: ['spiegelbeelden als hetzelfde zien', 'gezichten herkennen', 'kleuren onderscheiden'],
              answer: 'spiegelbeelden als hetzelfde zien',
              why: 'Voor een leeuw maakt links of rechts niet uit, voor b en d wel.',
            },
            deep: {
              q: 'Wat doet dat gebied precies?',
              a: 'Het reageert op letters, ongeacht lettertype of hoofdletter: *LEZEN*, *lezen* en *LeZeN* activeren het op dezelfde manier. Die *abstracte letteridentiteit* is precies het grafeembegrip uit de les over allografen, maar dan in je hersenen. Bij mensen die nooit leerden lezen, is het gebied minder gespecialiseerd voor letters.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'routes',
        prompt: 'Welke route heb je nodig om het woord goed te lezen?',
        buckets: ['alleen de klankroute (nepwoord)', 'de woordroute (onregelmatig)', 'allebei werken (regelmatig)'],
        items: [
          { t: 'flort', b: 0 },
          { t: 'chef', b: 1 },
          { t: 'kip', b: 2 },
          { t: 'brimpel', b: 0 },
          { t: 'computer', b: 1 },
          { t: 'tafel', b: 2 },
          { t: 'niveau', b: 1 },
          { t: 'snoek', b: 2 },
          { t: 'gralf', b: 0 },
        ],
        why: 'Nepwoorden (flort, brimpel, gralf) kun je alleen met regels lezen. Leenwoorden met een eigen uitspraak (chef, computer, niveau) vragen het opgeslagen woord. Regelmatige woorden (kip, tafel, snoek) lukken langs beide routes.',
      },
      {
        kind: 'choice',
        id: 'fonologische-dyslexie',
        prompt: 'Een patiënt leest ‘computer’ en ‘niveau’ perfect, maar kan ‘brimpel’ niet lezen. Wat is er aan de hand?',
        before: '',
        after: '',
        options: ['fonologische dyslexie', 'oppervlaktedyslexie', 'een probleem met de ogen'],
        answer: 'fonologische dyslexie',
        why: 'De woordroute werkt (onregelmatige woorden gaan goed), de klankroute niet (nepwoorden lukken niet).',
      },
      {
        kind: 'swipe',
        id: 'lezen-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Tijdens het lezen glijden je ogen soepel over de regel.', ok: false, fix: 'ze springen: saccades en fixaties', why: 'Je leest tijdens de fixaties.' },
          { t: 'Een letter herken je beter in een bestaand woord dan alleen.', ok: true, why: 'Het woordsuperioriteitseffect.' },
          { t: 'Het Cambridge-onderzoek naar verwisselde letters heeft echt bestaan.', ok: false, fix: 'het bestond niet', why: 'Het effect is echt, het onderzoek uit het bericht niet.' },
          { t: 'Bij het lezen van Hebreeuws kijk je verder naar links vooruit.', ok: true, why: 'Het venster volgt de leesrichting.' },
          { t: 'Het visuele woordvormgebied reageert anders op LEZEN dan op lezen.', ok: false, fix: 'het reageert op beide hetzelfde', why: 'Het herkent abstracte letteridentiteit.' },
          { t: 'Een nepwoord als flort lees je via de klankroute.', ok: true, why: 'Er is geen opgeslagen woord om op te zoeken.' },
          { t: 'Lezen is zo oud dat de evolutie er een eigen hersengebied voor maakte.', ok: false, fix: 'lezen recyclet een bestaand gebied', why: 'Schrift is pas zo’n vijfduizend jaar oud.' },
        ],
      },
    ],
  },
  {
    id: 'l16',
    stage: 'master',
    domain: 'orth',
    title: 'Letters tellen',
    skill: 'Spelling',
    icon: 'e%',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Niet elke letter is evenveel waard',
        panels: [
          {
            text: 'Tel alle letters in een grote stapel Nederlandse tekst. Ongeveer één op de vijf is een *e*, zo’n 19 procent. Daarna komt de *n* met ongeveer 10 procent, en dan *a*, *t*, *i*, *r* en *o*. Achteraan bungelen *x*, *y* en *q*, met minder dan één op de tweeduizend.',
            alpha: {
              q: 'Tik de drie letters die het vaakst voorkomen in Nederlandse tekst',
              targets: ['e', 'n', 'a'],
              note: 'e (ongeveer 19%), n (ongeveer 10%) en a (ongeveer 7,5%). Daarna volgen t, i, r en o.',
            },
            deep: {
              q: 'Waarom is de n zo vaak?',
              a: 'Door de grammatica. Het meervoud (*boeken*), de infinitief (*lopen*) en de meervoudige werkwoordsvorm (*wij lopen*) eindigen allemaal op *-en*. En de doffe *e* in die uitgang telt mee voor de *e*. In het Engels, zonder die *-en*, staat de *n* veel lager en de *t* hoger.',
            },
          },
          {
            text: 'Wie letters vaak nodig heeft, maakt ze kort. In het *morsealfabet* is de *e* één punt en de *t* één streep, terwijl de zeldzame *q* vier tekens krijgt. Volgens het verhaal telde Alfred Vail, die het alfabet met Samuel Morse maakte, daarvoor de loden letters in een drukkerij. In 1952 bewees David Huffman wiskundig hoe je de kortste code maakt: geef de vaakste tekens de kortste codes.',
            rule: 'Efficiënte code: hoe vaker een teken, hoe korter de code.',
            lab: {
              label: 'Tik een letter',
              chips: [
                { k: 'E', out: '·', note: 'De vaakste letter, de kortste code.' },
                { k: 'T', out: '–', note: 'Ook heel vaak, ook één teken.' },
                { k: 'S', out: '· · ·', note: 'SOS: · · · – – – · · ·' },
                { k: 'Q', out: '– – · –', note: 'Zeldzaam, dus een lange code.' },
              ],
            },
          },
          {
            text: 'Frequentie is ook een wapen. In de negende eeuw beschreef de Arabische geleerde Al-Kindi de *frequentieanalyse*: vervang je elke letter door een andere, dan blijft de vaakste letter toch de vaakste. Is in een Nederlandse geheimtekst de *h* opvallend vaak, dan staat die waarschijnlijk voor de *e*. Elke eenvoudige vervangingscode valt zo te kraken.',
            quiz: {
              q: 'In een lange Nederlandse geheimtekst is de q veruit de vaakste letter. Waar staat de q dan waarschijnlijk voor?',
              options: ['e', 'q', 'n', 'z'],
              answer: 'e',
              why: 'De vaakste letter van het Nederlands is de e. Een vervangingscode verandert de letters, niet hoe vaak ze voorkomen.',
            },
          },
        ],
      },
      {
        kind: 'order',
        id: 'frequentie',
        prompt: 'Zet de letters van vaak naar zeldzaam, zoals in Nederlandse tekst.',
        tiles: ['k', 'e', 'q', 't', 'n'],
        answer: 'e n t k q',
        why: 'e ongeveer 19%, n ongeveer 10%, t ongeveer 7%, k ongeveer 2% en q bijna nooit.',
      },
      {
        kind: 'type',
        id: 'caesar',
        prompt: 'Ontcijfer het woord. Elke letter is drie plaatsen in het alfabet opgeschoven (a werd d, b werd e).',
        before: 'wddo =',
        after: '',
        hint: 'een woord van vier letters',
        answer: 'taal',
        why: 'Schuif elke letter drie terug: w → t, d → a, d → a, o → l. Dit heet het Caesarcijfer: Julius Caesar gebruikte zo’n verschuiving.',
      },
      {
        kind: 'choice',
        id: 'morse',
        prompt: 'Welke letter krijgt in een efficiënte code de kortste code?',
        before: '',
        after: '',
        options: ['de letter die het vaakst voorkomt', 'de eerste letter van het alfabet', 'de letter met de minste streepjes', 'een klinker'],
        answer: 'de letter die het vaakst voorkomt',
        why: 'Dan maak je berichten gemiddeld het kortst. Morse voelde dat aan, Huffman bewees het.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Informatie en voorspelbaarheid',
        panels: [
          {
            text: 'Hoeveel informatie zit er in één letter? De wiskundige Claude Shannon meet dat in *bits*: het aantal ja-nee-vragen dat je nodig hebt om de letter te raden. Zijn alle 26 letters even waarschijnlijk, dan heb je ongeveer 4,7 vragen nodig (2 tot de macht 4,7 is 26). Maar letters zijn niet even waarschijnlijk, dus het gemiddelde is lager.',
            rule: 'Informatie = verrassing. Een voorspelbare letter bevat weinig informatie.',
            quiz: {
              q: 'Hoeveel bits heeft een letter als alle 26 letters even vaak voorkwamen?',
              options: ['ongeveer 4,7', '26', 'precies 1'],
              answer: 'ongeveer 4,7',
              why: '2 tot de macht 4,7 is ongeveer 26: met 4,7 ja-nee-vragen kun je de letter vinden.',
            },
          },
          {
            text: 'Het meeste effect heeft de context. Na *kopje th* is *ee* bijna zeker. In 1951 liet Shannon proefpersonen tekst letter voor letter raden. Zijn schatting: in Engelse tekst draagt een letter in zijn context gemiddeld maar ongeveer één bit, ruim vier keer minder dan het maximum. De rest is *redundantie*: overbodig, maar nuttig als er iets misgaat.',
            lab: {
              label: 'Raad de volgende letter',
              chips: [
                { k: 'Ik drink een kopje th', out: 'e', note: 'Bijna zeker: thee. Bijna geen informatie.' },
                { k: 'Ik heb een q', out: 'u', note: 'Na q komt in het Nederlands bijna altijd u.' },
                { k: 'Mijn naam is ', out: '?', note: 'Hier kan alles: veel informatie.' },
              ],
            },
          },
          {
            text: 'Door die redundantie kun je tekst lezen waar letters uit ontbreken. Haal alle klinkers weg: *Dt s n zn zndr klnkrs*. Lukt nog redelijk, toch? Medeklinkers dragen in het Nederlands meer informatie dan klinkers. Dat is ook waarom een medeklinkerschrift, zoals het Hebreeuws en Arabisch, prima werkt voor wie de taal kent.',
            quiz: {
              q: 'Waarom kun je een zin zonder klinkers vaak nog lezen?',
              options: ['medeklinkers dragen veel informatie en de context vult aan', 'klinkers zijn in het Nederlands overbodig', 'omdat de zin kort is'],
              answer: 'medeklinkers dragen veel informatie en de context vult aan',
              why: 'Dat is redundantie: de taal zegt meer dan strikt nodig.',
            },
            deep: {
              q: 'Hangt dat samen met de wet van Zipf?',
              a: 'Ja, het is dezelfde gedachte op een ander niveau. Op woordniveau zijn de vaakste woorden het kortst (*de*, *en*, *een*): dat zie je in de les over Zipf bij Het woord. Op letterniveau krijgen voorspelbare tekens weinig informatie. Taal lijkt overal een compromis te zoeken tussen kort en duidelijk.',
            },
          },
        ],
      },
      {
        kind: 'rewrite',
        id: 'klinkers-terug',
        prompt: 'Zet de klinkers terug.',
        source: 'Dt s n zn zndr klnkrs.',
        accept: ['Dit is een zin zonder klinkers.'],
        why: 'Medeklinkers dragen genoeg informatie om de zin te herkennen: redundantie.',
      },
      {
        kind: 'bet',
        id: 'shannon',
        prompt: 'Hoeveel informatie draagt een Engelse letter in zijn context volgens de schatting van Shannon?',
        options: ['ongeveer 1 bit', 'ongeveer 4,7 bits', 'ongeveer 10 bits'],
        answer: 'ongeveer 1 bit',
        why: 'Door frequentie en context veel minder dan het maximum van 4,7 bits.',
      },
      {
        kind: 'sort',
        id: 'informatie',
        prompt: 'Is de letter op de plek van … voorspelbaar of verrassend?',
        buckets: ['voorspelbaar: weinig informatie', 'verrassend: veel informatie'],
        items: [
          { t: 'de u in q…', b: 0 },
          { t: 'de eerste letter van een onbekende naam', b: 1 },
          { t: 'de laatste e in thé…', b: 0 },
          { t: 'de eerste letter van een zin', b: 1 },
          { t: 'de n in lope…', b: 0 },
          { t: 'een cijfer in een pincode', b: 1 },
        ],
        why: 'Hoe beter je de letter kunt raden, hoe minder informatie hij draagt. Een pincode is met opzet zo onvoorspelbaar mogelijk.',
      },
      {
        kind: 'swipe',
        id: 'tellen-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'De e is de vaakste letter in Nederlandse tekst.', ok: true, why: 'Ongeveer één op de vijf letters.' },
          { t: 'In morse krijgen alle letters even lange codes.', ok: false, fix: 'vaak voorkomende letters krijgen kortere codes', why: 'e is één punt, q vier tekens.' },
          { t: 'Een vervangingscode verandert hoe vaak elke letter voorkomt.', ok: false, fix: 'de frequenties blijven gelijk, alleen de letters wisselen', why: 'Daarom werkt frequentieanalyse.' },
          { t: 'Een voorspelbare letter bevat weinig informatie.', ok: true, why: 'Informatie is verrassing.' },
          { t: 'De n is vaak in het Nederlands door de uitgang -en.', ok: true, why: 'Meervoud, infinitief en meervoudige werkwoordsvormen.' },
          { t: 'Zonder klinkers is Nederlandse tekst onleesbaar.', ok: false, fix: 'je kunt hem vaak nog lezen', why: 'Medeklinkers dragen de meeste informatie.' },
        ],
      },
    ],
  },
];
