import type { LessonInput } from '../schema';

/**
 * Nieuwe lessen voor het niveau "De letter". Ze komen na l1, l2 en l4 en lopen op in diepte:
 * basis (het alfabet, de ij, kleine tekens) en bachelor (afbreken, hoofdletters, de geschiedenis
 * van het alfabet, de vorm van letters, spellingdiepte). De masterlessen staan in `letter-master.ts`.
 *
 * Elke les heeft twee uitlegrondes (eerst de kern, dan de verdieping) met daartussen en daarna
 * oefeningen die steeds moeilijker worden.
 */
export const LETTER_LESSONS: LessonInput[] = [
  {
    id: 'l5',
    stage: 'basis',
    domain: 'orth',
    title: 'Het alfabet op volgorde',
    skill: 'Spelling',
    icon: 'abc',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Zesentwintig letters op een rij',
        panels: [
          {
            text: 'Het woord *alfabet* is zelf een mini-alfabet: *alfa* en *bèta* zijn de eerste twee letters van het Griekse alfabet. Ons alfabet heeft 26 letters. Een paar daarvan gebruikt het Nederlands bijna alleen in leenwoorden en namen.',
            alpha: {
              q: 'Tik de drie letters die je bijna alleen in leenwoorden ziet',
              targets: ['q', 'x', 'y'],
              note: 'Denk aan quiz, taxi en baby. Ook de c is zeldzaam, behalve in ch: lachen, school.',
            },
            deep: {
              q: 'Hoe zeldzaam is zeldzaam?',
              a: 'Tel je alle letters in een grote stapel Nederlandse tekst, dan is ongeveer één op de vijf letters een *e*. De *q* komt nog geen één keer per tienduizend letters voor. In de masterles over letterfrequentie reken je daarmee verder.',
            },
          },
          {
            text: 'Letters hebben ook namen. Hoor je het patroon? Bij sommige letters komt de klinker ervóór: *ef*, *el*, *em*. Bij andere erna: *bee*, *dee*, *tee*. Dat verschil is al tweeduizend jaar oud: de Romeinen deden het ook zo.',
            lab: {
              label: 'Tik een letter',
              chips: [
                { k: 'f', out: 'ef', note: 'Een f kun je aanhouden: ffff. De klinker komt ervoor.' },
                { k: 'm', out: 'em', note: 'Mmmm kun je ook aanhouden: klinker ervoor.' },
                { k: 'b', out: 'bee', note: 'Een b is een kort plofje. Die kun je niet aanhouden: klinker erna.' },
                { k: 't', out: 'tee', note: 'Ook een plofje: klinker erna.' },
                { k: 'h', out: 'ha', note: 'Uitzondering: hhh kun je aanhouden, toch komt de klinker erna.' },
              ],
            },
            deep: {
              q: 'Waarom zit de klinker soms ervoor?',
              a: 'Een plofklank als *b* of *t* hoor je nauwelijks zonder klinker erachter. Een klank als *f* of *s* kun je wel aanhouden, dus daar kan de klinker ervoor. Letternamen zijn een stukje fonetiek. Uitzonderingen als *ha*, *gee* en *vee* komen uit een tijd waarin die letters anders klonken, of uit het Latijn via het Frans.',
            },
          },
          {
            text: 'Door de telefoon gaat het snel mis. *Bee*, *cee*, *dee*, *ee*, *gee*, *pee*, *tee* en *wee*: acht letternamen rijmen op *-ee*. Daarom bestaat er een *spelalfabet*: bij elke letter een woord dat je niet kunt verwarren. In het Nederlandse spelalfabet hoor je onder meer *Anton*, *Bernard*, *Dirk*, *Pieter*, *Utrecht*, *Willem* en *Zaandam*.',
            lab: {
              label: 'Tik een letter die je door de telefoon spelt',
              chips: [
                { k: 'B', out: 'B van Bernard', note: 'Anders hoort de ander misschien een D, P of T.' },
                { k: 'D', out: 'D van Dirk', note: 'Dee en tee klinken bijna gelijk.' },
                { k: 'IJ', out: 'IJ van IJmuiden', note: 'De ij heeft in het Nederlandse spelalfabet een eigen woord.' },
                { k: 'Z', out: 'Z van Zaandam', note: 'Zet en ses? Met een plaatsnaam erbij is er geen twijfel.' },
              ],
            },
            quiz: {
              q: 'Waarom gebruik je door de telefoon een spelalfabet?',
              options: [
                'Omdat veel letternamen bijna hetzelfde klinken',
                'Omdat de telefoon sommige letters niet doorgeeft',
                'Omdat het officieel verplicht is',
              ],
              answer: 'Omdat veel letternamen bijna hetzelfde klinken',
              why: 'bee, dee, pee, tee: ze rijmen allemaal. Een heel woord kun je niet verwarren.',
            },
          },
          {
            text: 'In een woordenboek staan de woorden op alfabet. Je vergelijkt ze letter voor letter. Zijn de eerste letters gelijk, dan kijk je naar de tweede, dan naar de derde.',
            rule: 'Vergelijk letter voor letter: het eerste verschil beslist.',
            swap: {
              goal: 'Zet de woorden op alfabet',
              blocks: ['kat', 'kip', 'kaas', 'kast'],
              accept: ['kaas kast kat kip'],
              note: 'kaas vóór kast: de derde letter beslist (a vóór s). kast vóór kat: s vóór t.',
            },
          },
        ],
      },
      {
        kind: 'order',
        id: 'sch-woorden',
        prompt: 'Zet de woorden op alfabet.',
        tiles: ['schip', 'school', 'schaap', 'scherp'],
        answer: 'schaap scherp schip school',
        why: 'Alle vier beginnen met sch. De vierde letter beslist: a, e, i, o.',
      },
      {
        kind: 'sort',
        id: 'letternamen',
        prompt: 'Komt de klinker van de letternaam ervoor of erna?',
        buckets: ['ervoor, zoals ef', 'erna, zoals bee'],
        items: [
          { t: 's', b: 0 },
          { t: 'p', b: 1 },
          { t: 'l', b: 0 },
          { t: 'd', b: 1 },
          { t: 'r', b: 0 },
          { t: 'b', b: 1 },
          { t: 'n', b: 0 },
          { t: 'k', b: 1 },
          { t: 'x', b: 0 },
          { t: 'h', b: 1 },
        ],
        why: 'es, el, er, en, iks: die klanken kun je aanhouden. pee, dee, bee, ka: plofklanken, dus de klinker erna. De h (ha) is de uitzondering: aanhoudbaar, toch klinker erna.',
      },
      {
        kind: 'type',
        id: 'naam-s',
        prompt: 'Typ de naam van de letter.',
        before: 'De letter s heet',
        after: '.',
        hint: 'twee letters',
        answer: 'es',
        why: 'Een s kun je aanhouden: ssss. Dus komt de klinker ervoor: es.',
      },
      {
        kind: 'type',
        id: 'naam-x',
        prompt: 'Typ de naam van de letter.',
        before: 'De letter x heet',
        after: '.',
        hint: 'drie letters',
        answer: 'iks',
        why: 'De x staat voor twee klanken: k + s. De naam is iks, met de klinker ervoor, net als bij es.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'De fijne regels van het woordenboek',
        panels: [
          {
            text: 'Alfabetiseren lijkt simpel, tot je een accent, een hoofdletter of een streepje tegenkomt. De afspraak in woordenboeken: alleen de letters tellen. Een accent, een hoofdletter, een spatie of een koppelteken sla je over. *één* staat dus op de plek van *een*, en *e-mail* op de plek van *email*.',
            rule: 'Alleen letters tellen: accenten, hoofdletters, spaties en streepjes sla je over.',
            swap: {
              goal: 'Zet de woorden op alfabet',
              blocks: ['e-mail', 'eiland', 'één', 'echt'],
              accept: ['echt één eiland e-mail'],
              note: 'Lees ze als echt, een, eiland, email. De tweede letter beslist: c, e, i, m.',
            },
          },
          {
            text: 'Namen met een tussenvoegsel zijn een valkuil, en Nederland en België doen het verschillend. In Nederland sorteer je *Jan de Vries* onder de *V*: *Vries, Jan de*. In België hoort het tussenvoegsel bij de achternaam, dus staat *Jan De Vries* onder de *D*.',
            lab: {
              label: 'Tik een land',
              chips: [
                { k: 'Nederland', out: 'Vries, Jan de', note: 'Onder de V. Het tussenvoegsel komt achteraan.' },
                { k: 'België', out: 'De Vries, Jan', note: 'Onder de D. Het tussenvoegsel is een vast deel van de naam.' },
              ],
            },
            deep: {
              q: 'Waarom het verschil?',
              a: 'In België wordt de naam geschreven zoals hij in de geboorteakte staat, vaak met een hoofdletter: *De Smet*, *Van Damme*. Daar is *De* dus echt het eerste stuk van de achternaam. In Nederland geldt het tussenvoegsel als los woordje vóór de naam. Daarom krijgt het in *Jan de Vries* ook een kleine letter.',
            },
          },
          {
            text: 'Hoeveel letters heeft het Nederlands nu echt? Officieel 26. Maar de *ij* is een buitenbeentje. Veel kinderen leerden vroeger het rijtje *…, iks, ij, zet*, met de *ij* op de plek van de *y*. In een kruiswoordpuzzel krijgt de *ij* meestal één hokje, en als hoofdletter worden beide tekens groot.',
            quiz: {
              q: 'Welke plek gaf het oude schoolrijtje aan de ij?',
              options: ['De plek van de y', 'De plek van de i', 'Een eigen plek na de z'],
              answer: 'De plek van de y',
              why: 'iks, ij, zet: de ij nam de plek van de griekse y in. In het woordenboek telt hij wel als i + j.',
            },
          },
        ],
      },
      {
        kind: 'order',
        id: 'tekens-negeren',
        prompt: 'Zet de woorden op alfabet zoals een woordenboek.',
        tiles: ['café', 'cacao', 'Cadzand', 'ca-va'],
        answer: 'cacao Cadzand café ca-va',
        why: 'Lees cacao, cadzand, cafe, cava. De derde letter beslist: c, d, f, v. Hoofdletter, accent en streepje tellen niet mee.',
      },
      {
        kind: 'choice',
        id: 'telefoonboek-nl',
        prompt: 'Een Nederlands telefoonboek. Onder welke letter vind je Anna van der Berg?',
        before: '',
        after: '',
        options: ['B', 'V', 'D', 'A'],
        answer: 'B',
        why: 'In Nederland sorteer je op het eerste woord ná de tussenvoegsels: Berg, Anna van der.',
      },
      {
        kind: 'order',
        id: 'namen-nl',
        prompt: 'Zet de namen op Nederlandse volgorde, zoals in een telefoonboek.',
        tiles: ['Piet de Jong', 'Els Bakker', 'Kees van Dam', 'Ria ten Brink'],
        answer: 'Els Bakker Ria ten Brink Kees van Dam Piet de Jong',
        why: 'Sorteer op Bakker, Brink, Dam, Jong. De tussenvoegsels ten, van en de tellen niet mee.',
      },
      {
        kind: 'swipe',
        id: 'alfabet-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'In het woordenboek staat één op dezelfde plek als een.', ok: true, why: 'Accenten tellen bij het sorteren niet mee.' },
          { t: 'De letternaam van de m is mee.', ok: false, fix: 'de m heet em', why: 'Een m kun je aanhouden, dus de klinker komt ervoor.' },
          { t: 'In België staat Jan De Smet onder de D.', ok: true, why: 'In België is het tussenvoegsel een vast deel van de achternaam.' },
          { t: 'bee, dee en pee rijmen, en dat maakt spellen door de telefoon lastig.', ok: true, why: 'Daarom gebruik je een spelalfabet: Bernard, Dirk, Pieter.' },
          { t: 'In een woordenboek staat e-mail vóór echt.', ok: false, fix: 'echt staat vóór e-mail', why: 'Lees email: de m komt na de c.' },
          { t: 'De letter q heet koe.', ok: false, fix: 'de q heet ku', why: 'Ku, met de klank van de u, net als in het Frans.' },
        ],
      },
    ],
  },
  {
    id: 'l6',
    stage: 'basis',
    domain: 'orth',
    also: ['fon'],
    title: 'De lange ij',
    skill: 'Spelling',
    icon: 'IJ',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Twee letters die samen groot worden',
        panels: [
          {
            text: 'IJsland, IJmuiden, het IJ in Amsterdam: de *ij* is de enige letter die als hoofdletter met twee tekens tegelijk komt. Begint een naam of een zin met *ij*, dan worden de *i* en de *j* allebei groot.',
            rule: 'Hoofdletter op ij? Schrijf *IJ*: *IJsland*, nooit *Ijsland*.',
            mark: {
              q: 'Tik de woorden die een hoofdletter IJ krijgen',
              sentence: 'het ijs bij ijmuiden en het ijzer uit ijsland',
              targets: [3, 8],
              note: 'IJmuiden en IJsland zijn namen. ijs en ijzer blijven klein.',
            },
          },
          {
            text: 'Waarom zit er een *j* in? In de middeleeuwen schreef men een lange *i*-klank als *ii*. Schrijvers gaven de tweede *i* een staart, zodat je hem beter zag: *ij*. Daarom heet hij de *lange ij*. De *ei* heet de *korte ei*: hij heeft geen staart. Met de klank heeft dat niets te maken; die is hetzelfde.',
            quiz: {
              q: 'Waarom heet de ij ‘lang’?',
              options: ['Omdat de j een lange staart heeft', 'Omdat je hem langer uitspreekt dan ei', 'Omdat hij uit twee letters bestaat'],
              answer: 'Omdat de j een lange staart heeft',
              why: 'Lang en kort gaan over de vorm. ij en ei klinken precies hetzelfde.',
            },
            deep: {
              q: 'En de y?',
              a: 'In oude teksten staat soms een *y* waar wij nu *ij* schrijven. In handschrift kreeg de *ij* vaak twee puntjes, zodat hij op een *ÿ* leek. Sommige namen houden die vorm vast: *Van Dyck* naast *Van Dijk*. Verder is de *y* vooral een letter voor leenwoorden: *baby*, *hobby*, *yoga*. Je noemt hem *i-grec* of *griekse ij*.',
            },
          },
          {
            text: 'In het woordenboek telt de *ij* als twee letters: eerst *i*, dan *j*. Daarom staat *ijs* tussen *iglo* en *ik*. In oude telefoonboeken stond de *ij* vaak bij de *y*, en in een kruiswoordpuzzel krijgt hij vaak één hokje. Eén letter of twee? Dat hangt af van wie je het vraagt.',
            quiz: {
              q: 'Welk woord komt als eerste in het woordenboek?',
              options: ['ijs', 'ik', 'iglo'],
              answer: 'iglo',
              why: 'i-g, dan i-j, dan i-k. De ij telt hier als i + j.',
            },
            deep: {
              q: 'Bestaat er een ij-toets?',
              a: 'Nee. Er bestaat wel een apart teken *ĳ*, één teken in plaats van twee, maar dat is er alleen voor oude systemen. Typ gewoon *i* + *j*: met het aparte teken vindt een zoekfunctie het woord *ijs* vaak niet terug.',
            },
          },
        ],
      },
      {
        kind: 'rewrite',
        id: 'hoofdletters',
        prompt: 'Zet de hoofdletters goed.',
        source: 'we fietsen langs het ijsselmeer naar ijmuiden.',
        accept: ['We fietsen langs het IJsselmeer naar IJmuiden.'],
        why: 'Zinsbegin: We. Namen met ij krijgen IJ: IJsselmeer, IJmuiden.',
      },
      {
        kind: 'choice',
        id: 'landen',
        prompt: 'Welk land staat als eerste op alfabet?',
        before: '',
        after: '',
        options: ['IJsland', 'Italië', 'Ierland'],
        answer: 'Ierland',
        why: 'Ie, IJ, It: de e komt vóór de j, en de j vóór de t.',
      },
      {
        kind: 'rewrite',
        id: 'ijzer-zin',
        prompt: 'Zet de hoofdletters goed.',
        source: 'ijzersterk: zo noemde ik de ijshockeyploeg uit ijsland.',
        accept: ['IJzersterk: zo noemde ik de ijshockeyploeg uit IJsland.'],
        why: 'IJ aan het begin van de zin en in de naam IJsland. ijshockeyploeg is geen naam en blijft klein, ook al begint hij met ij.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Ei of ij: een eeuwenoud probleem',
        panels: [
          {
            text: 'Waarom schrijven we één klank op twee manieren? Omdat het vroeger twee klanken waren. In het Middelnederlands klonk de *ij* als een lange *ie*: *wijn* klonk ongeveer als *wien*. De *ei* was al een tweeklank. Rond de zestiende eeuw werd ook die lange *ie* een tweeklank, en in Holland en Brabant vielen de twee samen. De spelling bleef staan.',
            rule: 'ij en ei klinken nu gelijk, maar waren vroeger twee klanken. De spelling onthoudt het verschil.',
            deep: {
              q: 'Hoor je het oude verschil nog ergens?',
              a: 'Ja. In delen van Zeeland en West-Vlaanderen klinkt de oude lange *ie* nog: *ies* voor *ijs*. En kijk naar het Engels en het Duits: *wijn*, *wine*, *Wein*; *tijd*, *time*, *Zeit*. Ook daar werd de lange *i* een tweeklank. Taalkundigen noemen zo’n verschuiving van lange klinkers een *diftongering*.',
            },
          },
          {
            text: 'Daar zit een handig trucje in. Heeft het Engelse familielid een *i*, dan schrijf je in het Nederlands vaak *ij*. Heeft het een *oa* of *o*, dan vaak *ei*. Het werkt niet altijd, maar wel verrassend vaak.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'ijs', out: 'ice', note: 'Engels i: ij.' },
                { k: 'wijn', out: 'wine', note: 'Engels i: ij.' },
                { k: 'rijden', out: 'ride', note: 'Engels i: ij.' },
                { k: 'eik', out: 'oak', note: 'Engels oa: ei.' },
                { k: 'geit', out: 'goat', note: 'Engels oa: ei.' },
              ],
            },
            quiz: {
              q: 'Het Engelse woord is ‘mine’. Hoe schrijf je het Nederlandse familielid?',
              options: ['mijn', 'mein', 'mien'],
              answer: 'mijn',
              why: 'Engels i, Nederlands ij: mine, mijn. Net als time en tijd.',
            },
          },
          {
            text: 'Twee achtervoegsels moet je gewoon kennen. *-lijk* schrijf je met *ij*, maar je zegt het met een doffe klank: *vriendelijk* klinkt als *vriendelək*. *-heid* schrijf je met *ei*: *vrijheid*, *waarheid*. Zo kan één woord allebei hebben: *eerlijkheid*.',
            rule: '*-lijk* met *ij*, *-heid* met *ei*: *duidelijkheid*.',
            show: [
              { wrong: 'vriendelijkhijd', right: 'vriendelijkheid' },
              { wrong: 'gevaarleik', right: 'gevaarlijk' },
            ],
          },
          {
            text: 'Soms bestaan beide spellingen, met een andere betekenis. Dan moet je echt weten welk woord je bedoelt. *Leiden* is de weg wijzen (en een stad); *lijden* is pijn hebben. *Peil* is een niveau (*het waterpeil*), *pijl* schiet je met een boog.',
            lab: {
              label: 'Tik een paar',
              chips: [
                { k: 'leiden / lijden', out: 'de weg wijzen / pijn hebben', note: 'Een gids leidt, een zieke lijdt.' },
                { k: 'peil / pijl', out: 'niveau / iets dat je schiet', note: 'Het peil stijgt, de pijl vliegt.' },
                { k: 'mei / mij', out: 'de maand / mij, zelf', note: 'Geef het aan mij, in mei.' },
                { k: 'hei / hij', out: 'heide / die man', note: 'Hij wandelt op de hei.' },
              ],
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'ei-ij',
        prompt: 'Ei of ij? Gebruik het Engelse trucje waar het kan.',
        buckets: ['ei', 'ij'],
        items: [
          { t: 'g…t (dier, Engels goat)', b: 0 },
          { t: 't…d (Engels time)', b: 1 },
          { t: 'r…den (Engels ride)', b: 1 },
          { t: 'e…k (boom, Engels oak)', b: 0 },
          { t: 'w…s (Engels wise)', b: 1 },
          { t: 'waarh…d', b: 0 },
          { t: 'gevaarl…k', b: 1 },
          { t: 'tr…n (je reist ermee)', b: 0 },
          { t: 'z…de (Engels side)', b: 1 },
          { t: 'h…lig (Engels holy)', b: 0 },
        ],
        why: 'Engels i wordt vaak ij (time, ride, wise, side). Engels oa of o wordt vaak ei (goat, oak, holy). -heid met ei, -lijk met ij. trein komt uit het Frans en moet je gewoon onthouden.',
      },
      {
        kind: 'choice',
        id: 'leiden-lijden',
        prompt: 'Kies de goede vorm.',
        before: 'Na de val had hij veel pijn; hij',
        after: 'zichtbaar.',
        options: ['leed', 'leidde', 'lijdde'],
        answer: 'leed',
        why: 'Pijn hebben is lijden: ik lijd, hij leed, hij heeft geleden. leidde hoort bij leiden, de weg wijzen.',
      },
      {
        kind: 'type',
        id: 'lijk-typen',
        prompt: 'Typ de ontbrekende letters.',
        before: 'Wat een vriendel',
        after: 'ke buurman!',
        hint: 'twee letters',
        answer: 'ij',
        why: 'Het achtervoegsel -lijk schrijf je met ij, ook al klinkt het dof: vriendelijk.',
      },
      {
        kind: 'proofread',
        id: 'nalezen',
        prompt: 'Lees het bericht na',
        intro: 'Er zitten vier fouten in met ei, ij of IJ. Tik ze aan.',
        tokens: [
          { t: 'In' },
          { t: 'mij', fix: 'mei', why: 'De maand schrijf je met ei: mei.' },
          { t: 'gaan' },
          { t: 'we' },
          { t: 'naar' },
          { t: 'Ijsland,', fix: 'IJsland,', why: 'Bij een hoofdletter worden de i en de j allebei groot.' },
          { t: 'want' },
          { t: 'ik' },
          { t: 'wil' },
          { t: 'de' },
          { t: 'gijsers', fix: 'geisers', why: 'geiser schrijf je met ei.' },
          { t: 'zien.' },
          { t: 'Het' },
          { t: 'wordt' },
          { t: 'vast' },
          { t: 'heerlijk' },
          { t: 'en' },
          { t: 'gezellig,' },
          { t: 'met' },
          { t: 'veel' },
          { t: 'vrijheid' },
          { t: 'en' },
          { t: 'weinig' },
          { t: 'tijt.', fix: 'tijd.', why: 'tijd met een d: denk aan tijden.' },
        ],
      },
      {
        kind: 'swipe',
        id: 'waar-of-niet',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'IJmuiden schrijf je met een hoofdletter I én een hoofdletter J.', ok: true, why: 'Bij ij worden beide letters groot.' },
          {
            t: 'De lange ij heet zo omdat je hem langer uitspreekt dan de ei.',
            ok: false,
            fix: 'lang gaat over de staart van de j',
            why: 'ij en ei klinken precies hetzelfde.',
          },
          { t: 'In het woordenboek staat ijs vóór ik.', ok: true, why: 'De ij telt als i + j, en de j komt vóór de k.' },
          { t: 'Aan het begin van een zin schrijf je Ijzer.', ok: false, fix: 'IJzer', why: 'Ook aan het begin van een zin worden beide letters groot.' },
          { t: 'In de middeleeuwen klonk wijn ongeveer als wien.', ok: true, why: 'De ij was toen een lange ie. Later werd het een tweeklank.' },
          { t: 'Het achtervoegsel -heid schrijf je met ij.', ok: false, fix: '-heid schrijf je met ei', why: 'vrijheid, waarheid: -heid met ei, -lijk met ij.' },
          { t: 'Dat ij en ei nu gelijk klinken, komt doordat twee klanken samenvielen.', ok: true, why: 'Rond de zestiende eeuw werd de lange ie een tweeklank en viel samen met ei.' },
        ],
      },
    ],
  },
  {
    id: 'l7',
    stage: 'basis',
    domain: 'orth',
    also: ['fon'],
    title: 'Accent, apostrof, koppelteken',
    skill: 'Spelling',
    icon: 'é',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Kleine tekens, groot verschil',
        panels: [
          {
            text: 'Eén streepje verandert de zin. *Ik heb een fiets* zegt weinig. *Ik heb één fiets* betekent: niet twee. Accenten gebruik je in het Nederlands vooral voor nadruk.',
            lab: {
              label: 'Tik een versie',
              chips: [
                { k: 'een', out: 'Ik heb een fiets.', note: 'Lidwoord: zomaar een fiets.' },
                { k: 'één', out: 'Ik heb één fiets.', note: 'Het getal: niet twee.' },
                { k: 'dé', out: 'Dit is dé fiets van het jaar.', note: 'Nadruk: de beste, de echte.' },
                { k: 'vóór', out: 'Hij stond vóór het huis.', note: 'Nadruk: aan de voorkant, niet erachter.' },
              ],
            },
            deep: {
              q: 'En het streepje de andere kant op?',
              a: 'Dat is het accent grave. Je ziet het in *hè* en in Franse leenwoorden als *crème*. Soms maakt het een ander woord: een *appel* eet je, bij een *appèl* moet iedereen aanwezig zijn. *Hé* (een groet) en *hè* (een vraag om instemming) verschillen ook.',
            },
            quiz: {
              q: 'In welke zin moet een accent op een?',
              options: ['Er kan maar een winnaar zijn.', 'Ik zie een vogel.', 'Ze kocht een jas.'],
              answer: 'Er kan maar een winnaar zijn.',
              why: 'Het gaat om het getal: maar één winnaar. In de andere zinnen is een gewoon het lidwoord.',
            },
          },
          {
            text: 'De apostrof houdt een klinker lang. Schrijf je *autos*, dan lees je *au-tos*, met een korte *o*. Met een apostrof blijft de *o* lang: *auto’s*.',
            rule: 'Eindigt een woord op *a, i, o, u* of *y*? Meervoud met een apostrof: *pizza’s*, *ski’s*, *menu’s*, *baby’s*.',
            build: { before: 'Twee', stem: 'pizza', endings: ['s', '’s', 'en'], answer: '’s', note: 'pizza’s. Zonder apostrof lees je pizzas met een korte a.' },
            deep: {
              q: 'En bij namen?',
              a: 'Meestal plak je gewoon een *s* achter een naam: *Peters fiets*, niet *Peter’s fiets*. Een apostrof komt er alleen bij een lange klinker aan het eind (*Anna’s fiets*) of na een s-klank (*Hans’ fiets*).',
            },
          },
          {
            text: 'Botsen twee klinkers, zodat je het woord verkeerd zou lezen? Binnen één woord krijgt de tweede klinker een trema: *ideeën*, *geërfd*. Plak je twee woorden aan elkaar, dan komt er een koppelteken tussen: *zee-egel*, *auto-ongeluk*.',
            rule: 'Twee woorden aan elkaar: koppelteken. Anders: trema.',
            lab: {
              label: 'Tik een combinatie',
              chips: [
                { k: 'zee + egel', out: 'zee-egel', note: 'egel is een woord: koppelteken.' },
                { k: 'zee + en', out: 'zeeën', note: '-en is geen woord, maar een uitgang: trema.' },
                { k: 'auto + ongeluk', out: 'auto-ongeluk', note: 'Twee woorden: koppelteken.' },
                { k: 'be + invloeden', out: 'beïnvloeden', note: 'be- is een voorvoegsel, geen woord: trema.' },
                { k: 'ge + uit', out: 'geüit', note: 'Zonder trema lees je geu-it.' },
              ],
            },
          },
        ],
      },
      {
        kind: 'chat',
        id: 'appje',
        prompt: 'App je vriendin terug',
        intro: 'De twee antwoorden verschillen één teken. Kies het antwoord zonder fout.',
        contact: { name: 'Noor', initials: 'N' },
        rounds: [
          {
            say: 'Zin in eten? Ik heb trek.',
            options: ['Ja! Zullen we pizza’s halen?', 'Ja! Zullen we pizzas halen?'],
            right: 0,
            fix: 'pizzas → pizza’s',
            why: 'Eindigt op een a: meervoud met een apostrof.',
          },
          {
            say: 'Goed plan. Neem jij de fiets van Peter?',
            options: ['Ja, Peter’s fiets staat hier.', 'Ja, Peters fiets staat hier.'],
            right: 1,
            fix: 'Peter’s → Peters',
            why: 'Achter een naam komt gewoon een s, zonder apostrof.',
          },
          {
            say: 'En hoeveel nemen we er?',
            options: ['Eén grote is genoeg.', 'Een grote is genoeg.'],
            right: 0,
            fix: 'Een → Eén',
            why: 'Het gaat om het getal: niet twee, maar één.',
          },
          {
            say: 'Daarna nog naar een terrasje?',
            options: ['Ja, er zijn hier genoeg café’s.', 'Ja, er zijn hier genoeg cafés.'],
            right: 1,
            fix: 'café’s → cafés',
            why: 'café eindigt op é, niet op a, i, o, u of y. De é blijft ook zonder apostrof lang: cafés.',
          },
        ],
        bye: 'Top, tot zo!',
      },
      {
        kind: 'sort',
        id: 'trema-koppelteken',
        prompt: 'Trema of koppelteken?',
        buckets: ['trema', 'koppelteken'],
        items: [
          { t: 'idee + en', b: 0 },
          { t: 'zee + egel', b: 1 },
          { t: 'ge + erfd', b: 0 },
          { t: 'auto + ongeluk', b: 1 },
          { t: 'zee + en', b: 0 },
          { t: 'radio + omroep', b: 1 },
          { t: 'be + invloeden', b: 0 },
          { t: 'mini + industrie', b: 1 },
          { t: 'ge + ent', b: 0 },
          { t: 'zonne + energie', b: 1 },
        ],
        why: 'Twee echte woorden aan elkaar (zee-egel, auto-ongeluk, radio-omroep, mini-industrie, zonne-energie): koppelteken. Een uitgang of voorvoegsel (ideeën, geërfd, zeeën, beïnvloeden, geënt): trema.',
      },
      {
        kind: 'bet',
        id: 'appel',
        prompt: 'Welk woord betekent: iedereen moet aanwezig zijn?',
        options: ['appèl', 'appel'],
        answer: 'appèl',
        why: 'Een appel eet je. Bij een appèl wordt iedereen geteld.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Wanneer wel, wanneer niet',
        panels: [
          {
            text: 'De apostrof in het meervoud heeft één doel: een lange klinker aan het eind lang houden. Eindigt een woord op een *é*, op een stomme *e* of op twee klinkers, dan heb je hem niet nodig. Die klinker blijft ook zonder apostrof wat hij is.',
            rule: 'Apostrof alleen na één lange *a, i, o, u* of *y*: *foto’s*, maar *cafés*, *garages*, *ideeën*.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'foto', out: 'foto’s', note: 'Eindigt op een lange o: apostrof.' },
                { k: 'collega', out: 'collega’s', note: 'Lange a: apostrof.' },
                { k: 'café', out: 'cafés', note: 'De é blijft lang: geen apostrof.' },
                { k: 'garage', out: 'garages', note: 'Stomme e: gewoon -s.' },
                { k: 'idee', out: 'ideeën', note: 'Twee klinkers en een uitgang -en: trema, geen apostrof.' },
              ],
            },
          },
          {
            text: 'Ook afkortingen krijgen een apostrof als je er iets achter plakt: *tv’s*, *cd’s*, *wc’s*, *sms’je*, *A4’tje*. Maar maak je er een samenstelling mee, dan komt er een koppelteken: *tv-programma*, *A4-papier*, *cd-speler*.',
            rule: 'Afkorting + uitgang: apostrof (*tv’s*). Afkorting + woord: koppelteken (*tv-gids*).',
            quiz: {
              q: 'Welke schrijfwijze is goed?',
              options: ['twee A4’tjes op een A4-blok', 'twee A4-tjes op een A4’blok', 'twee A4tjes op een A4blok'],
              answer: 'twee A4’tjes op een A4-blok',
              why: 'Een uitgang (-tjes) krijgt een apostrof, een woord (blok) een koppelteken.',
            },
          },
          {
            text: 'De apostrof kan ook laten zien dat er letters weg zijn. *’s Morgens* is ingekort uit *des morgens*. *Zo’n* komt van *zo een*, *m’n* van *mijn*. Begint een zin met zo’n ingekort woordje, dan krijgt het volgende woord de hoofdletter: *’s Avonds lees ik.*',
            rule: 'Zin begint met *’s* of *’t*? De hoofdletter gaat naar het woord erna: *’s Morgens*.',
            show: [
              { wrong: 'zon fiets', right: 'zo’n fiets' },
              { wrong: '’S morgens', right: '’s Morgens' },
            ],
            deep: {
              q: 'Waarom heet het eigenlijk des morgens?',
              a: '*Des* is een oude tweede naamval van *de*. Die naamval zie je nog in vaste uitdrukkingen: *’s winters*, *’s nachts*, *de dag des oordeels*. De apostrof is dus een litteken van een verdwenen naamval.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 's-of-apostrof',
        prompt: 'Hoe maak je het meervoud?',
        buckets: ['met ’s', 'met s zonder apostrof', 'met en en trema'],
        items: [
          { t: 'menu', b: 0 },
          { t: 'café', b: 1 },
          { t: 'paraplu', b: 0 },
          { t: 'garage', b: 1 },
          { t: 'zee', b: 2 },
          { t: 'hobby', b: 0 },
          { t: 'tafel', b: 1 },
          { t: 'idee', b: 2 },
          { t: 'tv', b: 0 },
          { t: 'kano', b: 0 },
        ],
        why: 'Lange a, i, o, u of y aan het eind (menu’s, paraplu’s, hobby’s, kano’s) en afkortingen (tv’s): apostrof. cafés, garages en tafels: gewoon s. zeeën en ideeën: -en met trema.',
      },
      {
        kind: 'choice',
        id: 'afkorting',
        prompt: 'Kies de goede schrijfwijze.',
        before: 'Ik kijk vanavond naar mijn favoriete',
        after: '.',
        options: ['tv-programma', 'tv’programma', 'tvprogramma', 'TV programma'],
        answer: 'tv-programma',
        why: 'Afkorting plus een heel woord: een samenstelling met koppelteken.',
      },
      {
        kind: 'proofread',
        id: 'nalezen',
        prompt: 'Lees de mail na',
        intro: 'Er zitten vijf fouten in met een accent, apostrof, trema of koppelteken. Tik ze aan.',
        header: { to: 'de buren', subject: 'Feest zaterdag' },
        tokens: [
          { t: 'Beste' },
          { t: 'buren,' },
          { t: 'zaterdag' },
          { t: 'geven' },
          { t: 'we' },
          { t: 'een' },
          { t: 'feest.' },
          { t: 'Er' },
          { t: 'komen' },
          { t: 'veel' },
          { t: 'auto’s,' },
          { t: 'maar' },
          { t: 'we' },
          { t: 'hebben' },
          { t: 'onze' },
          { t: 'ideën', fix: 'ideeën', why: 'idee + en: drie e’s, en de laatste krijgt een trema.' },
          { t: 'goed' },
          { t: 'uitgewerkt.' },
          { t: 'De' },
          { t: 'coordinatie', fix: 'coördinatie', why: 'co + ordinatie: zonder trema lees je coor-di-na-tie.' },
          { t: 'van' },
          { t: 'het' },
          { t: 'parkeren' },
          { t: 'is' },
          { t: 'ook' },
          { t: 'geregeld.' },
          { t: 'Na' },
          { t: 'het' },
          { t: 'eten' },
          { t: 'draaien' },
          { t: 'we' },
          { t: 'oude' },
          { t: 'cd’s' },
          { t: 'en' },
          { t: 'maken' },
          { t: 'we' },
          { t: 'fotos', fix: 'foto’s', why: 'Eindigt op een lange o: meervoud met apostrof.' },
          { t: 'bij' },
          { t: 'de' },
          { t: 'zeeegel.', fix: 'zee-egel.', why: 'zee + egel: twee woorden met botsende klinkers, dus een koppelteken.' },
          { t: 'Om' },
          { t: 'twaalf' },
          { t: 'uur' },
          { t: 'is' },
          { t: 'het' },
          { t: 'afgelopen,' },
          { t: 'dat' },
          { t: 'beloven' },
          { t: 'we.' },
          { t: 'Een' },
          { t: 'verzoek:' },
          { t: 'zet' },
          { t: 'zon', fix: 'zo’n', why: 'zo’n is ingekort uit zo een: met apostrof.' },
          { t: 'bordje' },
          { t: 'op' },
          { t: 'de' },
          { t: 'stoep?' },
        ],
      },
      {
        kind: 'swipe',
        id: 'tekens-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Het meervoud van café is cafés.', ok: true, why: 'De é blijft lang zonder apostrof.' },
          { t: 'Het meervoud van paraplu is paraplus.', ok: false, fix: 'paraplu’s', why: 'Een lange u aan het eind: apostrof.' },
          { t: 'In tv-gids staat een koppelteken omdat gids een heel woord is.', ok: true, why: 'Afkorting + woord: koppelteken.' },
          { t: 'Een zin die begint met ’s morgens, schrijf je als ’S morgens.', ok: false, fix: '’s Morgens', why: 'De hoofdletter gaat naar het woord na ’s.' },
          { t: 'In geüit staat een trema omdat je anders geu-it leest.', ok: true, why: 'ge- is een voorvoegsel: trema op de u.' },
          { t: 'zonne-energie krijgt een trema op de e.', ok: false, fix: 'koppelteken: zonne-energie', why: 'zonne + energie zijn twee woorden: koppelteken.' },
        ],
      },
    ],
  },
  {
    id: 'l8',
    stage: 'bachelor',
    domain: 'orth',
    also: ['fon', 'morf'],
    title: 'Afbreken: klank of betekenis?',
    skill: 'Spelling',
    icon: 'ver-',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Waar mag het streepje?',
        panels: [
          {
            text: 'Past een woord niet meer op de regel, dan breek je het af. Meestal volg je de lettergrepen, zoals je het woord langzaam uitspreekt: *bo-men*, *kat-ten*. Een dubbele medeklinker gaat dus uit elkaar.',
            split: { q: 'Breek het woord af', word: 'appels', answer: 'ap-pels', note: 'Twee p’s: één aan elke kant van het streepje.' },
          },
          {
            text: 'Staan er meer medeklinkers tussen twee klinkers? Dan geef je de volgende lettergreep zoveel medeklinkers als er aan het begin van een Nederlands woord kunnen staan. *st* kan een woord beginnen (*stoel*), dus: *ven-ster*. *tr* ook (*trein*): *ex-tra*. *mbt* kan dat niet, *t* wel: *amb-te-naar*.',
            rule: 'De volgende lettergreep krijgt zoveel medeklinkers als een Nederlands woord kan beginnen.',
            split: { q: 'Breek het woord af', word: 'monster', answer: 'mon-ster', note: 'st kan een woord beginnen (stok), nst niet. Dus mon-ster.' },
            deep: {
              q: 'Hoe heet dat principe?',
              a: 'Taalkundigen noemen het *onsetmaximalisatie*: maak het begin (de onset) van de volgende lettergreep zo groot als de taal toestaat. In De lettergreep zie je hoe dat principe ook de uitspraak stuurt. Bij afbreken gaat het om letters, dus zie je af en toe een afwijking, zoals bij de *ng*.',
            },
          },
          {
            text: 'Maar niet elke lettergroep mag uit elkaar. De *ch* blijft altijd heel: *la-chen*, nooit *lac-hen*. Gek genoeg gaat de *ng* wél uit elkaar: *zin-gen*, al hoor je maar één klank. De *ij* splits je nooit, en de *sch* aan het begin van een lettergreep ook niet: *be-schrij-ven*.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'lachen', out: 'la-chen', note: 'ch blijft heel.' },
                { k: 'zingen', out: 'zin-gen', note: 'ng gaat uit elkaar.' },
                { k: 'blijven', out: 'blij-ven', note: 'ij blijft heel.' },
                { k: 'logisch', out: 'lo-gisch', note: 'sch blijft bij elkaar aan het eind.' },
              ],
            },
            deep: {
              q: 'Waarom ch wel en ng niet?',
              a: 'Afspraak, geen natuurwet. In de spelling geldt *ch* als één teken: je verdubbelt hem ook nooit (*lachen*, niet *lachchen*). De *ng* zie je als *n* + *g*. Afbreekregels gaan dus over letters, niet over klanken.',
            },
          },
          {
            text: 'Bij voorvoegsels en samenstellingen wint de betekenis. Je zegt *ve-ran-de-ren*, maar je breekt af als *ver-an-de-ren*: het voorvoegsel *ver-* blijft heel. Net zo: *ont-eren*, *her-in-ne-ren*, *aard-ap-pel*.',
            rule: 'Afbreken volgt de lettergrepen, maar woorddelen blijven heel: *ver-an-de-ren*.',
            split: { q: 'Breek af en houd het voorvoegsel heel', word: 'veranderen', answer: 'ver-an-de-ren', note: 'ver- blijft heel, ook al zeg je ve-ran-de-ren.' },
            deep: {
              q: 'Klinkt verassen anders dan verrassen?',
              a: 'Nee. Toch breek je ze anders af: *ver-as-sen* (cremeren, met *as*) en *ver-ras-sen*. De spelling laat zien hoe een woord gebouwd is, ook als je het niet hoort.',
            },
          },
        ],
      },
      {
        kind: 'choice',
        id: 'trema-weg',
        prompt: 'Je breekt ‘ideeën’ af op de plek van het trema. Hoe schrijf je het?',
        before: '',
        after: '',
        options: ['idee-ën', 'idee-en', 'ide-eën'],
        answer: 'idee-en',
        why: 'Breek je af op de plek van het trema, dan valt het trema weg. Het streepje doet nu zijn werk.',
      },
      {
        kind: 'sort',
        id: 'goed-fout',
        prompt: 'Goed of fout afgebroken?',
        buckets: ['goed', 'fout'],
        items: [
          { t: 'la-chen', b: 0 },
          { t: 'lac-hen', b: 1 },
          { t: 'zin-gen', b: 0 },
          { t: 'bli-jven', b: 1 },
          { t: 'ver-an-de-ren', b: 0 },
          { t: 'ka-tten', b: 1 },
          { t: 'ven-ster', b: 0 },
          { t: 'vens-ter', b: 1 },
          { t: 'be-schrij-ven', b: 0 },
          { t: 've-ran-de-ren', b: 1 },
        ],
        why: 'ch en ij blijven heel, ng mag uit elkaar, een dubbele medeklinker gaat uit elkaar (kat-ten), st mag een lettergreep beginnen (ven-ster), en ver- blijft heel.',
      },
      {
        kind: 'type',
        id: 'ambtenaar',
        prompt: 'Breek het woord af. Zet een koppelteken op elk afbreekpunt.',
        before: 'ambtenaar =',
        after: '',
        hint: 'met koppeltekens',
        answer: 'amb-te-naar',
        why: 'mbt kan geen woord beginnen, bt ook niet, t wel. Dus amb-te-naar.',
      },
      {
        kind: 'choice',
        id: 'verassen',
        prompt: 'Hoe breek je ‘verassen’ (cremeren) af?',
        before: '',
        after: '',
        options: ['ver-as-sen', 'ver-ras-sen', 've-ras-sen'],
        answer: 'ver-as-sen',
        why: 'ver + as + sen. Verrassen breek je af als ver-ras-sen. Je hoort het verschil niet; je ziet het wel.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Als de computer afbreekt',
        panels: [
          {
            text: 'Samenstellingen kunnen op twee manieren gelezen worden, en dan beslist het afbreekpunt over de betekenis. Een *massagebed* is een bed voor massage. Breek je het af als *massa-gebed*, dan staat er ineens een gebed van een menigte.',
            lab: {
              label: 'Tik een afbreking',
              chips: [
                { k: 'massage-bed', out: 'massage + bed', note: 'De bedoelde betekenis.' },
                { k: 'massa-gebed', out: 'massa + gebed', note: 'Een gebed van een grote groep. Oeps.' },
                { k: 'kwart-slag', out: 'kwart + slag', note: 'Een draai van een kwart.' },
                { k: 'kwarts-lag', out: 'kwarts + lag', note: 'Een laag van het mineraal kwarts.' },
              ],
            },
          },
          {
            text: 'Tekstverwerkers breken af met *patronen*. Frank Liang schreef daarvoor in 1983 een algoritme voor het zetprogramma TeX. Het leert uit een woordenlijst welke lettercombinaties een afbreekpunt toelaten of verbieden. Dat werkt goed voor gewone woorden, maar het Nederlands maakt eindeloos nieuwe samenstellingen, en die staan in geen lijst.',
            quiz: {
              q: 'Waarom zijn samenstellingen lastig voor een afbreekprogramma?',
              options: [
                'Het programma ziet niet waar het ene woord ophoudt en het andere begint',
                'Samenstellingen mag je nooit afbreken',
                'Samenstellingen hebben geen lettergrepen',
              ],
              answer: 'Het programma ziet niet waar het ene woord ophoudt en het andere begint',
              why: 'Afbreken bij een woordgrens gaat vóór de lettergrepen, maar de woordgrens staat nergens in de letters.',
            },
            deep: {
              q: 'Hoe lang kan zo’n samenstelling worden?',
              a: 'In principe oneindig: *arbeidsongeschiktheidsverzekeringsmaatschappij* is een echt bestaand woord. Elk deel heeft een eigen woordgrens. Een mens ziet die grenzen omdat hij de woorden kent; een programma moet ze raden.',
            },
          },
          {
            text: 'Tot slot een zetregel. Een losse letter aan het eind of begin van een regel leest rommelig, en hij spaart vrijwel geen ruimte. Zetters en de meeste tekstverwerkers breken *apen* daarom niet af als *a-pen*, al is dat een correcte lettergreepgrens.',
            rule: 'Correct is niet altijd mooi: laat liever geen losse letter achter.',
          },
        ],
      },
      {
        kind: 'choice',
        id: 'kwartslag',
        prompt: 'Je draait de sleutel een kwart rond. Hoe breek je het woord af?',
        before: 'Ik gaf de sleutel een',
        after: '.',
        options: ['kwart-slag', 'kwarts-lag', 'kwar-tslag'],
        answer: 'kwart-slag',
        why: 'kwart + slag. Bij een samenstelling breek je af op de woordgrens, en die hangt af van de betekenis.',
      },
      {
        kind: 'type',
        id: 'herinneren',
        prompt: 'Breek het woord af. Zet een koppelteken op elk afbreekpunt.',
        before: 'herinneren =',
        after: '',
        hint: 'met koppeltekens',
        answer: 'her-in-ne-ren',
        why: 'her- is een voorvoegsel en blijft heel. Daarna volg je de lettergrepen: in-ne-ren, met de dubbele n uit elkaar.',
      },
      {
        kind: 'sort',
        id: 'wat-beslist',
        prompt: 'Wat bepaalt hier het afbreekpunt?',
        buckets: ['de lettergrepen', 'een woorddeel of woordgrens'],
        items: [
          { t: 'bo-men', b: 0 },
          { t: 'ont-eren', b: 1 },
          { t: 'mon-ster', b: 0 },
          { t: 'aard-appel', b: 1 },
          { t: 'zin-gen', b: 0 },
          { t: 'massage-bed', b: 1 },
          { t: 'ver-an-de-ren', b: 1 },
          { t: 'kat-ten', b: 0 },
        ],
        why: 'Zonder voorvoegsel of samenstelling volg je de lettergrepen. Met een voorvoegsel (ont-, ver-) of een samenstelling (aard + appel, massage + bed) wint de bouw van het woord.',
      },
      {
        kind: 'swipe',
        id: 'afbreken-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'ng gaat bij afbreken uit elkaar, ook al hoor je maar één klank.', ok: true, why: 'zin-gen: de spelling ziet n + g.' },
          { t: 'Je breekt ontEREN af als on-te-ren.', ok: false, fix: 'ont-eren', why: 'ont- is een voorvoegsel en blijft heel.' },
          { t: 'Afbreekregels gaan over letters, niet over klanken.', ok: true, why: 'Daarom blijft ch heel en gaat ng uit elkaar.' },
          { t: 'Een afbreekprogramma kent alle samenstellingen.', ok: false, fix: 'nieuwe samenstellingen staan in geen lijst', why: 'Het Nederlands maakt steeds nieuwe samenstellingen.' },
          { t: 'Bij ex-tra gaat tr naar de volgende lettergreep omdat tr een woord kan beginnen.', ok: true, why: 'trein, trap: tr is een goed begin.' },
          { t: 'Op de plek van het trema blijft het trema na het afbreken staan.', ok: false, fix: 'het trema valt weg: idee-en', why: 'Het streepje neemt de taak van het trema over.' },
        ],
      },
    ],
  },
  {
    id: 'l13',
    stage: 'bachelor',
    domain: 'orth',
    also: ['sem'],
    title: 'Hoofdletters: naam of soort?',
    skill: 'Spelling',
    icon: 'Aa',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Eén ding of een soort ding?',
        panels: [
          {
            text: 'Waarom krijgt *de Maas* een hoofdletter en *de rivier* niet? Bijna alle hoofdletterregels komen terug op één onderscheid. Een *eigennaam* wijst één bepaald ding aan: deze rivier, deze stad, deze persoon. Een *soortnaam* noemt een soort: elke rivier, elke stad. Eigennamen krijgen een hoofdletter.',
            rule: 'Eigennaam: hoofdletter (*de Maas*). Soortnaam: kleine letter (*de rivier*).',
            mark: {
              q: 'Tik de eigennamen',
              sentence: 'de rivier de maas stroomt langs de stad maastricht naar de zee',
              targets: [3, 8],
              note: 'Maas en Maastricht wijzen één ding aan. rivier, stad en zee zijn soortnamen.',
            },
          },
          {
            text: 'Afleidingen van aardrijkskundige namen houden de hoofdletter: talen, inwoners en bijvoeglijke naamwoorden. *Nederlands*, *Fransman*, *Amsterdammer*, *Belgisch bier*, *Friese paarden*. Ze verwijzen nog steeds naar die ene plek.',
            lab: {
              label: 'Tik een naam',
              chips: [
                { k: 'Frankrijk', out: 'het Frans, een Fransman, Franse kaas', note: 'Taal, inwoner en bijvoeglijk naamwoord: hoofdletter.' },
                { k: 'Amsterdam', out: 'een Amsterdammer, Amsterdamse grachten', note: 'Allemaal met hoofdletter.' },
                { k: 'Friesland', out: 'het Fries, een Fries paard', note: 'Ook hier: hoofdletter.' },
              ],
            },
          },
          {
            text: 'Maar wordt een naam een soortnaam, dan verdwijnt de hoofdletter. Een *berliner* is een gebakje, een *afrikaantje* een bloem, een *havanna* een sigaar. Eenheden naar een geleerde gaan net zo: *watt*, *ampère*, *newton*. En een *röntgenfoto* kan iedereen laten maken.',
            rule: 'Wordt een naam een soort ding, dan wordt hij klein: *een berliner*, *zestig watt*.',
            quiz: {
              q: 'Welke schrijfwijze is goed?',
              options: ['een lamp van zestig watt', 'een lamp van zestig Watt', 'een lamp van zestig WATT'],
              answer: 'een lamp van zestig watt',
              why: 'De eenheid is genoemd naar James Watt, maar is een soortnaam geworden: klein. Alleen het symbool is een hoofdletter: 60 W.',
            },
            deep: {
              q: 'En merknamen?',
              a: 'Een merk is een eigennaam: *Hij rijdt in een Volkswagen*. Maar wordt een merknaam de gewone naam voor een soort ding, dan schrijft het Groene Boekje hem klein, zoals *luxaflex* voor elk lamellengordijn. Taalkundigen noemen dat *deonymisering*: een naam verliest zijn verwijzing naar één ding.',
            },
          },
          {
            text: 'Windstreken zijn soortnamen: *het noorden van het land*, *we rijden naar het zuiden*. Maar in een aardrijkskundige naam horen ze bij de naam en krijgen ze een hoofdletter met koppelteken: *Noord-Holland*, *Zuid-Afrika*, *het Midden-Oosten*, *Oost-Europa*.',
            quiz: {
              q: 'Welke zin is goed geschreven?',
              options: [
                'In het noorden van Noord-Holland waait het hard.',
                'In het Noorden van Noord-Holland waait het hard.',
                'In het noorden van noord-Holland waait het hard.',
              ],
              answer: 'In het noorden van Noord-Holland waait het hard.',
              why: 'het noorden is een richting, dus klein. Noord-Holland is een naam, dus hoofdletter.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'naam-of-soort',
        prompt: 'Hoofdletter of kleine letter?',
        buckets: ['hoofdletter', 'kleine letter'],
        items: [
          { t: '(e/E)ngels (de taal)', b: 0 },
          { t: '(b/B)erliner (het gebakje)', b: 1 },
          { t: '(g/G)roninger (een inwoner)', b: 0 },
          { t: '(a/A)mpère (de eenheid)', b: 1 },
          { t: '(z/Z)uid-Afrika', b: 0 },
          { t: 'het (z/Z)uiden', b: 1 },
          { t: '(f/F)ranse wijn', b: 0 },
          { t: '(r/R)öntgenfoto', b: 1 },
          { t: 'het (m/M)idden-Oosten', b: 0 },
          { t: 'een (h/H)avanna (sigaar)', b: 1 },
        ],
        why: 'Talen, inwoners, bijvoeglijke naamwoorden van plaatsnamen en aardrijkskundige namen: hoofdletter. Namen die een soort ding zijn geworden (berliner, ampère, röntgenfoto, havanna) en windrichtingen: klein.',
      },
      {
        kind: 'rewrite',
        id: 'herschrijf-reis',
        prompt: 'Zet de hoofdletters goed.',
        source: 'in het zuiden van frankrijk dronken we franse wijn met een nederlander uit noord-brabant.',
        accept: ['In het zuiden van Frankrijk dronken we Franse wijn met een Nederlander uit Noord-Brabant.'],
        why: 'Zinsbegin, het land, het bijvoeglijk naamwoord Franse, de inwoner Nederlander en de provincie Noord-Brabant. het zuiden is een richting en blijft klein.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'De lastige gevallen',
        panels: [
          {
            text: 'Dagen en maanden zijn soortnamen: elke week heeft een *maandag*. Feestdagen zijn eigennamen: *Kerstmis*, *Pasen*, *Pinksteren*, *Koningsdag*. Maar een samenstelling met een feestdag is weer een soort ding: *een kerstboom*, *een paasei*, *het pinksterweekend*.',
            rule: 'Feestdag: hoofdletter (*Pasen*). Ding dat erbij hoort: klein (*paasei*).',
            mark: {
              q: 'Tik de woorden die een hoofdletter krijgen',
              sentence: 'met kerstmis zetten we in december een kerstboom en met pasen zoeken we op maandag paaseieren',
              targets: [1, 10],
              note: 'Kerstmis en Pasen zijn feestdagen. december, maandag, kerstboom en paaseieren blijven klein.',
            },
          },
          {
            text: 'Godsdiensten en hun aanhangers schrijf je klein: *het christendom*, *de islam*, *het jodendom*, *een christen*, *een moslim*, *een boeddhist*. De naam van de ene God in een godsdienst met één god krijgt wel een hoofdletter: *God*, *Allah*. Een *Jood* (lid van het volk) krijgt een hoofdletter; een *jood* (aanhanger van de godsdienst) niet.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'islam', out: 'de islam, een moslim', note: 'Godsdienst en aanhanger: klein.' },
                { k: 'God', out: 'God, Allah', note: 'De naam van de ene god: hoofdletter.' },
                { k: 'goden', out: 'de Griekse goden', note: 'Een soort wezens: klein. Zeus zelf is wel een naam.' },
                { k: 'Jood / jood', out: 'het volk / de godsdienst', note: 'Volk: hoofdletter. Godsdienst: klein.' },
              ],
            },
          },
          {
            text: 'Tijdperken zijn soortnamen, gebeurtenissen eigennamen. Je schrijft *de middeleeuwen*, *de renaissance*, *de steentijd*. Maar *de Tweede Wereldoorlog* en *de Franse Revolutie* zijn unieke gebeurtenissen: hoofdletters.',
            quiz: {
              q: 'Welke zin is goed geschreven?',
              options: [
                'Na de middeleeuwen kwam de renaissance; veel later volgde de Franse Revolutie.',
                'Na de Middeleeuwen kwam de Renaissance; veel later volgde de Franse Revolutie.',
                'Na de middeleeuwen kwam de renaissance; veel later volgde de franse revolutie.',
              ],
              answer: 'Na de middeleeuwen kwam de renaissance; veel later volgde de Franse Revolutie.',
              why: 'Tijdperken klein, een unieke gebeurtenis met hoofdletters.',
            },
          },
          {
            text: 'Tussenvoegsels in Nederlandse namen: staat er een voornaam of voorletter voor, dan klein: *Jan de Vries*, *J. de Vries*. Staat er niets voor, dan groot: *meneer De Vries*, *De Vries won*. In België schrijf je de naam zoals hij in de geboorteakte staat, vaak met hoofdletter: *Jan Van Damme*.',
            rule: 'Nederland: *Jan de Vries*, maar *mevrouw De Vries*.',
            quiz: {
              q: 'Welke Nederlandse schrijfwijze is goed?',
              options: ['Gisteren sprak ik met mevrouw Van Dijk.', 'Gisteren sprak ik met mevrouw van Dijk.', 'Gisteren sprak ik met Mevrouw van Dijk.'],
              answer: 'Gisteren sprak ik met mevrouw Van Dijk.',
              why: 'Geen voornaam of voorletter ervoor: tussenvoegsel met hoofdletter. mevrouw blijft klein.',
            },
          },
          {
            text: 'En na een dubbele punt? Daar schrijf je in principe een kleine letter: *Eén ding is zeker: het wordt laat.* Alleen bij een letterlijk citaat of een eigennaam komt er een hoofdletter: *Ze zei: ‘Het wordt laat.’*',
            rule: 'Na een dubbele punt: klein, behalve bij een citaat of een naam.',
          },
        ],
      },
      {
        kind: 'sort',
        id: 'lastige-gevallen',
        prompt: 'Hoofdletter of kleine letter?',
        buckets: ['hoofdletter', 'kleine letter'],
        items: [
          { t: '(p/P)inksteren', b: 0 },
          { t: 'een (k/K)erstboom', b: 1 },
          { t: 'de (i/I)slam', b: 1 },
          { t: 'de (t/T)weede Wereldoorlog', b: 0 },
          { t: 'de (m/M)iddeleeuwen', b: 1 },
          { t: 'meneer (d/D)e Jong', b: 0 },
          { t: 'Piet (d/D)e Jong (in Nederland)', b: 1 },
          { t: '(k/K)oningsdag', b: 0 },
          { t: 'een (c/C)hristen', b: 1 },
          { t: 'in (a/A)ugustus', b: 1 },
        ],
        why: 'Feestdagen, unieke gebeurtenissen en een tussenvoegsel zonder voornaam ervoor: hoofdletter. Godsdiensten en aanhangers, tijdperken, maanden, samenstellingen met een feestdag en een tussenvoegsel na de voornaam: klein.',
      },
      {
        kind: 'rewrite',
        id: 'herschrijf-pasen',
        prompt: 'Zet de hoofdletters goed.',
        source: "’s maandags na pasen bezocht meneer de graaf een museum over de middeleeuwen.",
        accept: ["’s Maandags na Pasen bezocht meneer De Graaf een museum over de middeleeuwen."],
        why: 'Na ’s aan het zinsbegin krijgt het volgende woord de hoofdletter. Pasen is een feestdag. De Graaf: geen voornaam ervoor. middeleeuwen is een tijdperk en blijft klein.',
      },
      {
        kind: 'rewrite',
        id: 'herschrijf-dubbele-punt',
        prompt: 'Zet de hoofdletters goed.',
        source: 'mijn advies aan jan de vries: lees eerst het boek over de franse revolutie.',
        accept: ['Mijn advies aan Jan de Vries: lees eerst het boek over de Franse Revolutie.'],
        why: 'Zinsbegin en voornaam: hoofdletter. de blijft klein na de voornaam. Na de dubbele punt komt geen citaat: klein. Franse Revolutie is een unieke gebeurtenis.',
      },
      {
        kind: 'proofread',
        id: 'nalezen',
        prompt: 'Lees het verslag na',
        intro: 'Er zitten zes hoofdletterfouten in. Tik ze aan.',
        tokens: [
          { t: 'Op' },
          { t: 'Zondag', fix: 'zondag', why: 'Dagen van de week zijn soortnamen: klein.' },
          { t: 'gingen' },
          { t: 'we' },
          { t: 'met' },
          { t: 'mevrouw' },
          { t: 'Bakker' },
          { t: 'naar' },
          { t: 'de' },
          { t: 'Waddenzee.' },
          { t: 'Ze' },
          { t: 'vertelde' },
          { t: 'over' },
          { t: 'de' },
          { t: 'Middeleeuwen,', fix: 'middeleeuwen,', why: 'Een tijdperk: klein.' },
          { t: 'over' },
          { t: 'Friese' },
          { t: 'boerderijen' },
          { t: 'en' },
          { t: 'over' },
          { t: 'het' },
          { t: 'Noorden', fix: 'noorden', why: 'Een windrichting: klein.' },
          { t: 'van' },
          { t: 'het' },
          { t: 'land.' },
          { t: 'Ze' },
          { t: 'is' },
          { t: 'zelf' },
          { t: 'Katholiek,', fix: 'katholiek,', why: 'Een aanhanger van een godsdienst: klein.' },
          { t: 'maar' },
          { t: 'viert' },
          { t: 'ook' },
          { t: 'het' },
          { t: 'suikerfeest', fix: 'Suikerfeest', why: 'Een feestdag: hoofdletter.' },
          { t: 'met' },
          { t: 'haar' },
          { t: 'buren.' },
          { t: 'Om' },
          { t: 'zes' },
          { t: 'uur' },
          { t: 'aten' },
          { t: 'we' },
          { t: 'een' },
          { t: 'Berliner.', fix: 'berliner.', why: 'Het gebakje is een soortnaam geworden: klein.' },
        ],
      },
      {
        kind: 'swipe',
        id: 'hoofdletters-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Bijna elke hoofdletterregel draait om het verschil tussen eigennaam en soortnaam.', ok: true, why: 'Eén bepaald ding: hoofdletter. Een soort: klein.' },
          { t: 'In Nederland schrijf je: Ik sprak Kees De Boer.', ok: false, fix: 'Kees de Boer', why: 'Na een voornaam blijft het tussenvoegsel klein.' },
          { t: 'Een kerstboom krijgt geen hoofdletter, Kerstmis wel.', ok: true, why: 'De feestdag is een naam, de boom een soort ding.' },
          { t: 'Na een dubbele punt komt altijd een hoofdletter.', ok: false, fix: 'in principe een kleine letter', why: 'Alleen bij een citaat of een naam komt er een hoofdletter.' },
          { t: 'watt schrijf je klein, al is de eenheid naar een persoon genoemd.', ok: true, why: 'Een eenheid is een soortnaam.' },
          { t: 'De taal die je in Spanje spreekt, schrijf je als spaans.', ok: false, fix: 'Spaans', why: 'Talen krijgen een hoofdletter.' },
          { t: 'Een Jood met hoofdletter is een lid van het volk.', ok: true, why: 'De godsdienst schrijf je klein: een jood, het jodendom.' },
        ],
      },
    ],
  },
  {
    id: 'l9',
    stage: 'bachelor',
    domain: 'orth',
    title: 'Van ossenkop tot A',
    skill: 'Spelling',
    icon: 'Aα',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Waar onze letters vandaan komen',
        panels: [
          {
            text: 'Schrift is een paar keer los van elkaar uitgevonden, waarschijnlijk vier keer: rond 3200 voor Christus in Mesopotamië (het spijkerschrift), rond dezelfde tijd in Egypte (de hiërogliefen), later in China en in Midden-Amerika. Maar het *alfabet* is, voor zover we weten, maar één keer uitgevonden. Alle alfabetten van nu stammen daarvan af.',
            quiz: {
              q: 'Hoe vaak is het alfabet uitgevonden, voor zover we weten?',
              options: ['één keer', 'vier keer', 'in elke beschaving opnieuw'],
              answer: 'één keer',
              why: 'Schrift ontstond meerdere keren, maar alle alfabetten gaan terug op één uitvinding.',
            },
          },
          {
            text: 'Die uitvinding deden Semitische arbeiders in Egypte en de Sinaï, rond 1800 voor Christus. Ze leenden plaatjes uit de hiërogliefen, maar gebruikten ze voor de eerste klank van hun eigen woord. Het plaatje van een os, *ʾalp*, werd de klank waarmee *ʾalp* begint. Dat principe heet *acrofonie*. Draai een *A* op zijn kop: zie je de kop van de os met twee hoorns?',
            rule: 'Acrofonie: een plaatje staat voor de eerste klank van het woord dat het tekent.',
            lab: {
              label: 'Tik een letter',
              chips: [
                { k: 'A', out: 'aleph · os', note: 'Op zijn kop zie je de hoorns.' },
                { k: 'B', out: 'beth · huis', note: 'Ooit een tekening van een huis.' },
                { k: 'M', out: 'mem · water', note: 'Golfjes: daarom die zigzag.' },
                { k: 'O', out: 'ayin · oog', note: 'Een rond oog.' },
                { k: 'R', out: 'resh · hoofd', note: 'Een hoofd op een nek. De R kreeg later een pootje.' },
              ],
            },
            deep: {
              q: 'Hoe weten we dat?',
              a: 'In 1905 vonden archeologen bij Serabit el-Khadim, een oude turkooismijn in de Sinaï, inscripties in een onbekend schrift. De egyptoloog Alan Gardiner zag in 1916 dat een herhaald groepje tekens te lezen was als *bʿlt*: de godin Baälat. Dat *Proto-Sinaïtische* schrift is de oudst bekende voorouder van ons alfabet.',
            },
          },
          {
            text: 'De Feniciërs, handelaars aan de kust van het huidige Libanon, verspreidden het schrift vanaf ongeveer 1050 voor Christus over de hele Middellandse Zee. Hun alfabet had 22 letters, allemaal medeklinkers, en las van rechts naar links. De lezer vulde de klinkers zelf in.',
            quiz: {
              q: 'Welke klanken schreef het Fenicische alfabet?',
              options: ['alleen medeklinkers', 'alleen klinkers', 'medeklinkers en klinkers'],
              answer: 'alleen medeklinkers',
              why: 'De lezer kende de taal en vulde de klinkers zelf in.',
            },
          },
          {
            text: 'Rond 800 voor Christus namen de Grieken het over. Hun taal kon niet zonder klinkers. Dus gaven ze letters voor Semitische keelklanken, die het Grieks niet had, een nieuwe taak. *Aleph* werd *alfa*, *he* werd *epsilon*, *yod* werd *iota*, *ayin* werd *omikron*. Zo ontstond het eerste alfabet met klinkers én medeklinkers.',
            rule: 'Fenicisch → Grieks → Etruskisch → Latijn → ons alfabet.',
            lab: {
              label: 'Tik een Fenicische letter',
              chips: [
                { k: 'aleph', out: 'alfa (A)', note: 'Een keelklank werd de klinker a.' },
                { k: 'he', out: 'epsilon (E)', note: 'Een h-achtige klank werd de e.' },
                { k: 'yod', out: 'iota (I)', note: 'Een j-klank werd de i.' },
                { k: 'ayin', out: 'omikron (O)', note: 'Een diepe keelklank werd de o.' },
              ],
            },
            deep: {
              q: 'Waarom staan sommige letters ‘verkeerd’ om?',
              a: 'De vroegste Grieken schreven nog van rechts naar links, of afwisselend heen en terug: *boustrophedon*, ‘zoals een os ploegt’. Bij elke omkeer draaiden de letters mee. Toen links naar rechts de vaste richting werd, bleven de gespiegelde vormen over. Onze *E* kijkt daarom de andere kant op dan de Fenicische *he*.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'griekse-klinkers',
        prompt: 'Welke Griekse klinker werd deze Fenicische letter?',
        buckets: ['alfa', 'epsilon', 'iota', 'omikron'],
        items: [
          { t: 'yod (een j-klank)', b: 2 },
          { t: 'aleph (os)', b: 0 },
          { t: 'ayin (oog)', b: 3 },
          { t: 'he (een h-klank)', b: 1 },
        ],
        why: 'aleph werd alfa, he werd epsilon, yod werd iota en ayin werd omikron. Letters voor keelklanken die het Grieks niet had, kregen een nieuwe taak.',
      },
      {
        kind: 'order',
        id: 'stamboom',
        prompt: 'Zet de schriften in de volgorde waarin ze werden doorgegeven.',
        tiles: ['Latijn', 'Fenicisch', 'Etruskisch', 'Grieks', 'Proto-Sinaïtisch'],
        answer: 'Proto-Sinaïtisch Fenicisch Grieks Etruskisch Latijn',
        why: 'Proto-Sinaïtisch (rond 1800 v.C.), Fenicisch (vanaf 1050 v.C.), Grieks (rond 800 v.C.), Etruskisch en dan het Latijn. Ons alfabet is het Latijnse.',
      },
      {
        kind: 'choice',
        id: 'acrofonie',
        prompt: 'Stel: je maakt een alfabet met acrofonie. Waar zou het plaatje van een vis voor staan?',
        before: '',
        after: '',
        options: ['de klank v', 'het woord vis', 'de klank s', 'de hele lettergreep vis'],
        answer: 'de klank v',
        why: 'Bij acrofonie staat het plaatje voor de eerste klank van het woord: vis begint met v.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Van Rome naar jouw toetsenbord',
        panels: [
          {
            text: 'Via de Etrusken in Italië kwam het alfabet bij de Romeinen. Het Etruskisch had geen verschil tussen *k* en *g*, dus het Latijn kreeg een *C* met twee taken. In de derde eeuw voor Christus kwam er een nieuwe letter bij: de *G*, een *C* met een streepje. Hij kreeg de plek van de *Z*, die het Latijn toen niet nodig had.',
            quiz: {
              q: 'Hoe maakten de Romeinen de G?',
              options: ['Ze zetten een streepje aan de C', 'Ze leenden hem uit het Grieks', 'Ze draaiden de Q om'],
              answer: 'Ze zetten een streepje aan de C',
              why: 'De C stond eerst voor k én g. Met een streepje erbij werd het de G.',
            },
          },
          {
            text: 'Waarom staan de *Y* en de *Z* achteraan? Omdat ze laat kwamen. In de eerste eeuw voor Christus leende het Latijn veel Griekse woorden, en daarvoor haalden de Romeinen de Griekse *Y* (upsilon) en *Z* (zèta) erbij. Nieuwe letters sluiten achteraan aan.',
            rule: 'Wie laat komt, staat achteraan: *Y* en *Z* kwamen er pas voor Griekse leenwoorden bij.',
          },
          {
            text: 'De Romeinen kenden nog geen *J*, *U* en *W*. De *I* stond voor *i* én *j*, de *V* voor *u* én *v*. Pas in de zestiende eeuw werden het aparte letters, onder meer op voorstel van de Fransman Petrus Ramus. De *W* is letterlijk een dubbele *V* of *U*: Germaanse schrijvers zetten er twee naast elkaar voor hun w-klank. Daarom heet hij in het Engels *double u* en in het Frans *double vé*.',
            lab: {
              label: 'Tik een letter',
              chips: [
                { k: 'J', out: 'vroeger: I', note: 'Een i met een staart werd pas in de zestiende eeuw een eigen letter.' },
                { k: 'U', out: 'vroeger: V', note: 'De ronde vorm en de puntige vorm werden twee letters.' },
                { k: 'W', out: 'VV of UU', note: 'Twee v’s naast elkaar. Engels: double u.' },
              ],
            },
          },
          {
            text: 'Niet elk schrift is een alfabet. Een *woordschrift* heeft een teken per woord of woorddeel, zoals het Chinees. Een *lettergreepschrift* heeft een teken per lettergreep, zoals Japans kana. Een *medeklinkerschrift* schrijft vooral medeklinkers, zoals het Arabisch en Hebreeuws. Een *alfabet* heeft tekens voor medeklinkers én klinkers.',
            quiz: {
              q: 'In welk soort schrift staan de korte klinkers vaak niet in de tekst?',
              options: ['medeklinkerschrift', 'alfabet', 'lettergreepschrift'],
              answer: 'medeklinkerschrift',
              why: 'In het Arabisch en Hebreeuws staan korte klinkers meestal niet in de tekst. De lezer kent het woord.',
            },
            deep: {
              q: 'Een schrift dat de mond tekent',
              a: 'Het Koreaanse *hangul* uit de vijftiende eeuw is een alfabet, maar de letters staan per lettergreep in blokjes. De vorm van sommige medeklinkers tekent zelfs de stand van tong en lippen. Taalkundigen noemen het daarom een kenmerkenschrift. En de Germaanse *runen* zijn een zijtak van het alfabet: de *futhark*, genoemd naar de eerste zes tekens, f-u-th-a-r-k, gaat vermoedelijk terug op een Noord-Italiaans alfabet.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'schriften',
        prompt: 'Wat voor schrift is het?',
        buckets: ['woordschrift', 'lettergreepschrift', 'medeklinkerschrift', 'alfabet'],
        items: [
          { t: 'Chinees', b: 0 },
          { t: 'Japans kana', b: 1 },
          { t: 'Arabisch', b: 2 },
          { t: 'Hebreeuws', b: 2 },
          { t: 'Grieks', b: 3 },
          { t: 'Russisch', b: 3 },
          { t: 'Fenicisch', b: 2 },
          { t: 'Koreaans hangul', b: 3 },
          { t: 'runen', b: 3 },
        ],
        why: 'Chinees: tekens voor woorden. Kana: lettergrepen. Arabisch, Hebreeuws en Fenicisch: vooral medeklinkers. Grieks, Russisch, hangul en runen: alfabetten met klinkers.',
      },
      {
        kind: 'order',
        id: 'tijdlijn',
        prompt: 'Zet de gebeurtenissen in de tijd, van oud naar nieuw.',
        tiles: ['aparte J en U', 'Grieks alfabet met klinkers', 'eerste alfabet', 'spijkerschrift', 'de Latijnse G', 'Y en Z in het Latijn'],
        answer: 'spijkerschrift eerste alfabet Grieks alfabet met klinkers de Latijnse G Y en Z in het Latijn aparte J en U',
        why: 'Spijkerschrift rond 3200 v.C., het eerste alfabet rond 1800 v.C., Griekse klinkers rond 800 v.C., de G in de derde eeuw v.C., Y en Z in de eerste eeuw v.C., J en U pas in de zestiende eeuw.',
      },
      {
        kind: 'choice',
        id: 'y-z-achteraan',
        prompt: 'Waarom staan de Y en de Z achteraan in het alfabet?',
        before: '',
        after: '',
        options: [
          'Ze kwamen laat, voor Griekse leenwoorden',
          'Het zijn de zeldzaamste letters',
          'De Feniciërs zetten ze al achteraan',
          'Ze klinken als medeklinker én klinker',
        ],
        answer: 'Ze kwamen laat, voor Griekse leenwoorden',
        why: 'De Romeinen voegden ze in de eerste eeuw voor Christus toe voor Griekse woorden. Nieuwe letters sloten achteraan aan.',
      },
      {
        kind: 'bet',
        id: 'j-en-u',
        prompt: 'Wanneer werden de J en de U eigen letters, los van I en V?',
        options: ['in de zestiende eeuw', 'in de eerste eeuw voor Christus', 'rond het jaar 800'],
        answer: 'in de zestiende eeuw',
        why: 'Lang waren het twee vormen van dezelfde letter. In de zestiende eeuw werden ze, onder meer door Petrus Ramus, als aparte letters voorgesteld.',
      },
      {
        kind: 'swipe',
        id: 'geschiedenis-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'De A was ooit een plaatje van een os.', ok: true, why: 'aleph betekent os; op zijn kop zie je de hoorns.' },
          { t: 'De Feniciërs voegden de klinkers toe.', ok: false, fix: 'de Grieken voegden de klinkers toe', why: 'Het Fenicisch schreef alleen medeklinkers.' },
          { t: 'De W is ontstaan uit twee V’s of U’s naast elkaar.', ok: true, why: 'Daarom heet hij double u in het Engels.' },
          { t: 'Julius Caesar schreef zijn naam met een J.', ok: false, fix: 'IVLIVS, met een I', why: 'De J bestond nog niet als aparte letter.' },
          { t: 'Acrofonie betekent dat een plaatje voor de eerste klank van zijn woord staat.', ok: true, why: 'Zo werd de os de klank waarmee ʾalp begint.' },
          { t: 'De vroegste Grieken schreven soms heen en terug, zoals een os ploegt.', ok: true, why: 'Dat heet boustrophedon.' },
          { t: 'Spijkerschrift is een alfabet.', ok: false, fix: 'een woord- en lettergreepschrift', why: 'Spijkerschrift heeft tekens voor woorden en lettergrepen, niet voor losse klanken.' },
        ],
      },
    ],
  },
  {
    id: 'l14',
    stage: 'bachelor',
    domain: 'orth',
    title: 'Van kapitaal tot onderkast',
    skill: 'Spelling',
    icon: 'Rg',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Hoe de kleine letter ontstond',
        panels: [
          {
            text: 'Een Romein zou deze zin niet herkennen: hij schreef alleen hoofdletters, en vaak zonder spaties. Op de zuil van keizer Trajanus in Rome (113 na Christus) staan de beroemdste: de *capitalis monumentalis*. Letterontwerpers kopiëren die vormen nog steeds. Kleine letters bestonden toen gewoon niet.',
            deep: {
              q: 'Zonder spaties? Hoe las je dat?',
              a: 'Hardop en langzaam. Dat heet *scriptio continua*: doorlopend schrift. De spatie tussen woorden werd pas in de zevende en achtste eeuw gewoon, bij Ierse en Angelsaksische monniken. Zij lazen Latijn als vreemde taal en hadden houvast nodig. Volgens de historicus Paul Saenger maakte de spatie stillezen veel makkelijker.',
            },
          },
          {
            text: 'Met de pen schrijf je sneller en ronder dan met de beitel. Zo veranderden de letters in boeken langzaam: eerst *unciaal*, een rond hoofdletterschrift, daarna vormen waarin sommige letters boven of onder de regel uitstaken. Rond het jaar 800 liet Karel de Grote in zijn rijk één helder boekschrift invoeren: de *Karolingische minuskel*. Dat is de directe voorouder van onze kleine letters.',
            rule: 'Kleine letters zijn een handschrift: de Karolingische minuskel, rond 800.',
            quiz: {
              q: 'Wie liet het boekschrift invoeren waar onze kleine letters van afstammen?',
              options: ['Karel de Grote', 'Julius Caesar', 'Johannes Gutenberg'],
              answer: 'Karel de Grote',
              why: 'Onder Karel de Grote werd rond 800 de Karolingische minuskel het standaardschrift voor boeken.',
            },
          },
          {
            text: 'In de late middeleeuwen werd het schrift smal, hoekig en zwart: het *gotische* schrift, of *textura*. Mooi, maar lastig. Het woord *minimum* bestaat in dat schrift uit vijftien bijna gelijke streepjes. Daarom kreeg de *i* een puntje: zo zie je waar hij staat tussen de *m*, *n* en *u*.',
            lab: {
              label: 'Tik een woord',
              chips: [
                { k: 'minimum', out: 'ııııııııııııııı', note: 'In textura: vijftien bijna gelijke streepjes. Waar zit de i?' },
                { k: 'minimum met puntjes', out: 'minimum', note: 'Het puntje (eerst een streepje) wijst elke i aan.' },
              ],
            },
            deep: {
              q: 'En Gutenberg?',
              a: 'Gutenberg drukte zijn Bijbel rond 1455 in precies dat gotische schrift: zijn letters moesten op handschrift lijken. In Duitsland bleef een gotische letter, de *fraktur*, tot in de twintigste eeuw gewoon.',
            },
          },
          {
            text: 'Rond 1400 zochten Italiaanse humanisten de teksten van de klassieken. Ze vonden ze in Karolingische handschriften en dachten dat dát het schrift van de Romeinen was. Ze kopieerden het: de *humanistische minuskel*. De drukker Nicolas Jenson maakte er in 1470 in Venetië een drukletter van, de *romein*. In 1501 kwam daar de schuine *cursief* bij, van Aldus Manutius en Francesco Griffo.',
            rule: 'Romeinse hoofdletters + Karolingische kleine letters = de letters op dit scherm.',
            quiz: {
              q: 'Wat dachten de humanisten toen ze de Karolingische minuskel vonden?',
              options: ['dat het het schrift van de Romeinen was', 'dat het een nieuw schrift was', 'dat het uit het Grieks kwam'],
              answer: 'dat het het schrift van de Romeinen was',
              why: 'Een productieve vergissing: ze noemden het littera antiqua en maakten er de basis van onze drukletter van.',
            },
          },
        ],
      },
      {
        kind: 'order',
        id: 'schriftgeschiedenis',
        prompt: 'Zet de schriften in de tijd, van oud naar nieuw.',
        tiles: ['humanistische minuskel', 'capitalis', 'textura', 'Karolingische minuskel', 'unciaal'],
        answer: 'capitalis unciaal Karolingische minuskel textura humanistische minuskel',
        why: 'Romeinse hoofdletters, dan het ronde unciaal, de Karolingische minuskel rond 800, het gotische textura in de late middeleeuwen en de humanistische minuskel rond 1400.',
      },
      {
        kind: 'choice',
        id: 'i-puntje',
        prompt: 'Waarom kreeg de i een puntje?',
        before: '',
        after: '',
        options: [
          'Om hem te onderscheiden tussen streepjes van m, n en u',
          'Om de klemtoon aan te geven',
          'Om hem te onderscheiden van de l',
          'Omdat de Romeinen dat al deden',
        ],
        answer: 'Om hem te onderscheiden tussen streepjes van m, n en u',
        why: 'In het gotische schrift bestonden m, n, u en i uit dezelfde streepjes. Het puntje wijst de i aan.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Anatomie van een letter',
        panels: [
          {
            text: 'Waarom heten ze *bovenkast* en *onderkast*? Letterzetters bewaarden hun loden letters in houten bakken, de kasten. De hoofdletters lagen in de bovenste, de kleine letters, die ze vaker nodig hadden, onder handbereik in de onderste. Het Engels zegt nog steeds *upper case* en *lower case*.',
            quiz: {
              q: 'Waar lagen de kleine letters bij de letterzetter?',
              options: ['in de onderkast', 'in de bovenkast', 'in een aparte la'],
              answer: 'in de onderkast',
              why: 'Onder handbereik, want ze waren het vaakst nodig.',
            },
          },
          {
            text: 'Een kleine letter leeft tussen vier lijnen. Het lijfje van *a*, *e* en *o* hangt tussen de basislijn en de *x-hoogte*. Sommige letters steken erboven uit met een *stok*, andere eronder met een *staart*. Die uitsteeksels geven een woord een herkenbaar silhouet.',
            alpha: {
              q: 'Tik alle letters met een stok omhoog',
              targets: ['b', 'd', 'f', 'h', 'k', 'l', 't'],
              note: 'b, d, f, h, k, l en t steken boven de x-hoogte uit. g, j, p, q en y hebben een staart omlaag.',
            },
          },
          {
            text: 'Lees je woorden aan hun silhouet? Lang dachten onderzoekers van wel. Maar oogbewegingsonderzoek laat zien dat je de losse letters van een woord tegelijk herkent, niet de vorm als geheel. Tekst in hoofdletters leest vooral trager omdat je hem minder gewend bent.',
            deep: {
              q: 'Hoe test je dat?',
              a: 'Geef lezers woorden in *AlTeRnErEnDe* hoofd- en kleine letters. Het silhouet is dan weg, maar met wat oefening lezen ze bijna even snel. Ook de *woordvormtheorie* voorspelt dat een woord met een fout die het silhouet heel laat, zoals *tesl* voor *test*, lastiger op te merken is; dat effect valt in experimenten tegen. Kevin Larson vatte dat onderzoek in 2004 samen in *The Science of Word Recognition*.',
            },
          },
          {
            text: 'Letters met *schreven*, de kleine voetjes aan de uiteinden, heten *schreefletters*; letters zonder heten *schreefloos*. Een Nederlandse ontwerper maakte in 2008 de letter *Dyslexie*, met zwaardere onderkanten zodat letters minder zouden kantelen. Onderzoek van Marinus en collega’s (2016) vond geen voordeel boven Arial zodra de ruimte tussen de letters gelijk was. Het effect zat in de ruimte, niet in de vorm.',
            rule: 'Een goede onderzoeksvraag houdt alles gelijk behalve het ene ding dat je test.',
            quiz: {
              q: 'Wat verklaarde het voordeel dat lezers met dyslexie leken te hebben bij de letter Dyslexie?',
              options: ['de grotere ruimte tussen de letters', 'de zwaardere onderkanten', 'de schreven'],
              answer: 'de grotere ruimte tussen de letters',
              why: 'Met gelijke spatiëring verdween het verschil met Arial.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'stok-staart',
        prompt: 'Waar steekt de letter uit?',
        buckets: ['stok omhoog', 'staart omlaag', 'blijft binnen de x-hoogte'],
        items: [
          { t: 'b', b: 0 },
          { t: 'g', b: 1 },
          { t: 'a', b: 2 },
          { t: 'k', b: 0 },
          { t: 'p', b: 1 },
          { t: 'e', b: 2 },
          { t: 'l', b: 0 },
          { t: 'y', b: 1 },
          { t: 's', b: 2 },
          { t: 'q', b: 1 },
        ],
        why: 'Stokken: b, d, f, h, k, l, t. Staarten: g, j, p, q, y. De rest, zoals a, e en s, blijft binnen de x-hoogte.',
      },
      {
        kind: 'type',
        id: 'onderkast',
        prompt: 'Typ het woord.',
        before: 'De kleine letters heten bij letterzetters de',
        after: '.',
        hint: 'een kast',
        answer: 'onderkast',
        why: 'De kleine letters lagen in de onderste kast, onder handbereik.',
      },
      {
        kind: 'bet',
        id: 'jenson',
        prompt: 'Waar en wanneer maakte Nicolas Jenson zijn romein, de voorouder van de meeste drukletters?',
        options: ['Venetië, 1470', 'Mainz, 1455', 'Aken, 800'],
        answer: 'Venetië, 1470',
        why: 'Gutenberg drukte in Mainz rond 1455 in een gotische letter. Aken was de hoofdstad van Karel de Grote. Jenson sneed zijn romein in 1470 in Venetië.',
      },
      {
        kind: 'swipe',
        id: 'letters-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'De Romeinen schreven al kleine letters.', ok: false, fix: 'alleen hoofdletters', why: 'Kleine letters ontstonden later uit handschrift.' },
          { t: 'Onze kleine letters stammen af van de Karolingische minuskel.', ok: true, why: 'Via de humanisten, die dat schrift kopieerden.' },
          { t: 'Gutenberg drukte zijn Bijbel in een gotische letter.', ok: true, why: 'Zijn letters moesten op handschrift lijken.' },
          { t: 'Onderzoek bewees dat de letter Dyslexie beter leest dan Arial.', ok: false, fix: 'geen voordeel bij gelijke ruimte', why: 'Het voordeel kwam door de ruimte tussen de letters.' },
          { t: 'We lezen een woord vooral door de losse letters te herkennen, niet het silhouet.', ok: true, why: 'Oogbewegingsonderzoek wijst die kant op.' },
          { t: 'Lower case komt van de onderste letterkast van de zetter.', ok: true, why: 'Daar lagen de kleine letters.' },
          { t: 'De spatie tussen woorden is net zo oud als het alfabet.', ok: false, fix: 'pas sinds de zevende en achtste eeuw gewoon', why: 'Romeinen schreven vaak zonder spaties.' },
        ],
      },
    ],
  },
  {
    id: 'l10',
    stage: 'bachelor',
    domain: 'orth',
    also: ['fon', 'morf'],
    title: 'Hoe diep is een spelling?',
    skill: 'Spelling',
    icon: 'e?',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Lezen is makkelijker dan spellen',
        panels: [
          {
            text: 'Fins is de droom van elke leerling: één letter, één klank, altijd. Engels is het andere uiterste: *though*, *through*, *tough*. Taalkundigen noemen dat de *diepte* van een spelling. Een ondiepe spelling volgt de klank. Een diepe spelling laat ook geschiedenis en woordbouw zien.',
            swap: {
              goal: 'Zet de talen van ondiep naar diep',
              blocks: ['Engels', 'Fins', 'Nederlands', 'Frans'],
              accept: ['Fins Nederlands Frans Engels'],
              note: 'Fins volgt de klank bijna perfect. Nederlands is vrij ondiep, Frans dieper (denk aan stomme letters), Engels het diepst.',
            },
          },
          {
            text: 'Het Nederlands zit dicht bij de ondiepe kant, maar niet helemaal. Lezen gaat vrij regelmatig: van letter naar klank. Spellen is lastiger: van klank naar letter heb je vaak twee keuzes. Hoor je de klank van *wijn* en *klein*, dan moet je kiezen tussen *ij* en *ei*. En één letter kan meer klanken hebben.',
            lab: {
              label: 'Tik een woord en kijk wat de e doet',
              chips: [
                { k: 'bed', out: 'e = kort', note: 'Een gesloten lettergreep: korte e.' },
                { k: 'beter', out: 'e = lang', note: 'be- is een open lettergreep: lange e.' },
                { k: 'de', out: 'e = dof', note: 'Een zwakke klank zonder klemtoon: de sjwa.' },
              ],
            },
            quiz: {
              q: 'Wat is voor een Nederlandse schrijver het lastigst?',
              options: ['van klank naar letter: spellen', 'van letter naar klank: lezen'],
              answer: 'van klank naar letter: spellen',
              why: 'Lezen is vrij regelmatig. Bij spellen moet je vaak kiezen: ei of ij, d of t.',
            },
          },
          {
            text: 'Diepte heeft gevolgen. In een groot onderzoek naar het eerste leesjaar in dertien Europese spellingen lazen kinderen uit landen met een ondiepe spelling aan het eind van dat jaar bijna alle simpele woorden goed. Nederlandse kinderen kwamen ook hoog uit. Kinderen in Schotland, die Engels leerden lezen, lazen er maar ongeveer een derde goed.',
            deep: {
              q: 'Welk onderzoek?',
              a: 'Seymour, Aro en Erskine (2003) vergeleken het eerste leesjaar in dertien Europese spellingen. Fins, Grieks en Duits scoorden bijna perfect, Frans, Portugees en Deens lager, Engels veruit het laagst. Het idee erachter heet de *orthografische-diepte-hypothese* (Katz en Frost, 1992): hoe dieper de spelling, hoe langer leren lezen duurt.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'e-klanken',
        prompt: 'Hoe klinkt de e?',
        buckets: ['kort, zoals in bed', 'lang, zoals in beter', 'dof, zoals in de'],
        items: [
          { t: 'pen', b: 0 },
          { t: 'zebra', b: 1 },
          { t: 'je', b: 2 },
          { t: 'nek', b: 0 },
          { t: 'veto', b: 1 },
          { t: 'te', b: 2 },
          { t: 'de -en in lopen', b: 2 },
          { t: 'de eerste e in eten', b: 1 },
          { t: 'de e in wesp', b: 0 },
        ],
        why: 'In een gesloten lettergreep klinkt de e kort: pen, nek, wesp. In een open lettergreep met klemtoon lang: ze-bra, ve-to, e-ten. Zonder klemtoon dof: je, te, lopen.',
      },
      {
        kind: 'bet',
        id: 'diepste',
        prompt: 'Welke taal heeft de diepste spelling?',
        options: ['Engels', 'Fins', 'Italiaans'],
        answer: 'Engels',
        why: 'In het Engels kan één lettergroep veel klanken hebben: though, through, tough.',
      },
      {
        kind: 'choice',
        id: 'twee-keuzes',
        prompt: 'Bij welk woord schrijf je niet wat je hoort?',
        before: '',
        after: '',
        options: ['hond', 'boek', 'kip'],
        answer: 'hond',
        why: 'Je hoort een t aan het eind, maar je schrijft een d. Bij boek en kip schrijf je wat je hoort.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Diepte meten in twee richtingen',
        panels: [
          {
            text: 'Onderzoekers meten diepte in twee richtingen. *Vooruit* (van letter naar klank): hoeveel klanken kan deze letter hebben? *Terug* (van klank naar letter): op hoeveel manieren kun je deze klank schrijven? Het Nederlands is vooruit vrij consistent en terug veel minder. De klank in *oud* en *blauw* kun je op vier manieren schrijven: *ou*, *au*, *ouw*, *auw*.',
            rule: 'Lezen meet consistentie vooruit, spellen meet consistentie terug. Het Nederlands is terug veel minder consistent.',
            lab: {
              label: 'Tik een klank',
              chips: [
                { k: 'de klank in wijn', out: 'ij of ei', note: 'wijn, klein' },
                { k: 'de klank in koud', out: 'ou, au, ouw of auw', note: 'oud, saus, vrouw, blauw' },
                { k: 'de doffe klank', out: 'e, i of ij', note: 'lopen, aardig, vriendelijk' },
                { k: 'de slotklank in hond', out: 't, d of dt', note: 'kat, hond, hij wordt' },
              ],
            },
          },
          {
            text: 'De diepte van het Nederlands komt vooral uit de woordbouw. Je schrijft *hond* met een *d* omdat het meervoud *honden* is: de spelling houdt het woorddeel gelijk. En *hij wordt* krijgt *dt* omdat er stam + *t* staat. Je hoort het niet, maar je ziet de bouw. Dat heet het *morfologische principe*.',
            quiz: {
              q: 'Waarom schrijf je ‘hond’ met een d?',
              options: ['Omdat het meervoud honden is', 'Omdat je een d hoort', 'Omdat het uit het Duits komt'],
              answer: 'Omdat het meervoud honden is',
              why: 'De spelling houdt het woorddeel gelijk: hond, honden. Dat is het morfologische principe.',
            },
            deep: {
              q: 'Is diepte dan slecht?',
              a: 'Niet per se. Een diepe spelling kost beginners meer moeite, maar helpt ervaren lezers: *hond* en *honden* zien er verwant uit, en *hij wordt* en *ik word* laten de grammatica zien. Spelling is een afweging tussen klank en betekenis, en elke taal kiest anders.',
            },
          },
          {
            text: 'Diepte bepaalt ook *hoe* je leest. Volgens de *grootte-van-de-korrel-theorie* van Ziegler en Goswami (2005) lezen kinderen met een ondiepe spelling letter voor letter: dat werkt. Engelse kinderen leren grotere stukken herkennen, zoals *-ight* in *night*, *light*, *right*, omdat losse letters te onbetrouwbaar zijn.',
            quiz: {
              q: 'Welke leesstrategie past het best bij een diepe spelling als het Engels?',
              options: ['grotere stukken herkennen, zoals -ight', 'letter voor letter klanken plakken', 'alleen de eerste letter lezen'],
              answer: 'grotere stukken herkennen, zoals -ight',
              why: 'Losse letters zijn in het Engels onbetrouwbaar; grotere stukken zijn consistenter.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'doffe-klank',
        prompt: 'Hoe schrijf je de doffe klank in de laatste lettergreep?',
        buckets: ['e', 'i', 'ij'],
        items: [
          { t: 'taf…l', b: 0 },
          { t: 'aard…g', b: 1 },
          { t: 'eerl…k', b: 2 },
          { t: 'lop…n', b: 0 },
          { t: 'monn…k', b: 1 },
          { t: 'vriendel…k', b: 2 },
          { t: 'kog…l', b: 0 },
          { t: 'zonn…g', b: 1 },
          { t: 'mogel…k', b: 2 },
        ],
        why: 'Allemaal dezelfde doffe klank, met drie spellingen: e (tafel, lopen, kogel), i (aardig, zonnig, monnik) en ij (eerlijk, vriendelijk, mogelijk). Je moet het woordbeeld kennen.',
      },
      {
        kind: 'choice',
        id: 'au-klank',
        prompt: 'Op hoeveel manieren kun je de klank in ‘koud’ schrijven?',
        before: '',
        after: '',
        options: ['vier', 'twee', 'drie', 'één'],
        answer: 'vier',
        why: 'ou (koud), au (saus), ouw (vrouw) en auw (blauw).',
      },
      {
        kind: 'sort',
        id: 'principe',
        prompt: 'Waarom schrijf je het zo?',
        buckets: ['je schrijft wat je hoort', 'de woordbouw beslist'],
        items: [
          { t: 'kip', b: 0 },
          { t: 'hond (honden)', b: 1 },
          { t: 'hij wordt', b: 1 },
          { t: 'boek', b: 0 },
          { t: 'web (webben)', b: 1 },
          { t: 'vis', b: 0 },
          { t: 'hij vindt', b: 1 },
        ],
        why: 'kip, boek en vis klinken zoals ze geschreven worden. Bij hond, web, wordt en vindt hoor je een t of p, maar de spelling volgt het woorddeel: honden, webben, stam + t.',
      },
      {
        kind: 'dictation',
        id: 'dictee',
        prompt: 'Luister en typ',
        intro: 'Een zin vol diepe spelling. Typ precies wat je hoort, met hoofdletter en punt.',
        sentence: 'Hij vindt de lelijke hond van de buren aardig.',
        right: 'vindt met dt (stam + t), lelijke met ij, hond met d (honden) en aardig met ig: allemaal dingen die je niet hoort.',
        wrong: 'Kijk naar vindt (stam vind + t), lelijke (-lijk met ij), hond (honden, dus d) en aardig (-ig). Begin met een hoofdletter en eindig met een punt.',
      },
      {
        kind: 'swipe',
        id: 'diepte-waar',
        prompt: 'Klopt het?',
        intro: 'Veeg naar rechts als de zin klopt, naar links als hij niet klopt.',
        cards: [
          { t: 'Het Nederlands is van letter naar klank consistenter dan van klank naar letter.', ok: true, why: 'Lezen is regelmatiger dan spellen.' },
          { t: 'De d in hond schrijf je omdat je een d hoort.', ok: false, fix: 'je hoort een t, maar schrijft d door honden', why: 'Het morfologische principe houdt het woorddeel gelijk.' },
          { t: 'Engelse kinderen herkennen vaker grotere stukken, zoals -ight.', ok: true, why: 'Losse letters zijn in het Engels te onbetrouwbaar.' },
          { t: 'Een diepe spelling heeft alleen maar nadelen.', ok: false, fix: 'hij helpt ervaren lezers de woordbouw te zien', why: 'hond en honden zien er verwant uit.' },
          { t: 'De doffe klank kun je schrijven als e, i of ij.', ok: true, why: 'lopen, aardig, eerlijk.' },
          { t: 'Fins is een van de diepste spellingen van Europa.', ok: false, fix: 'een van de ondiepste', why: 'In het Fins hoort bij elke letter bijna altijd één klank.' },
        ],
      },
    ],
  },
];
