import type { LessonInput } from '../schema';

/**
 * Masterlessen voor het niveau "Het woord": valentie en thematische rollen, onaccusativiteit
 * (hebben of zijn), prototypetheorie tegenover kenmerkanalyse, collocaties, idioom en frames,
 * woordfrequentie (Zipf) en de grenzen van het woord (partikelwerkwoorden en klitieken).
 *
 * Elke les heeft twee uitlegrondes (eerst de kern, dan een verdieping met onderzoek en debat)
 * met daartussen en daarna oefeningen die steeds moeilijker worden.
 */
export const WOORD_MASTER_LESSONS: LessonInput[] = [
  {
    id: 'w15',
    stage: 'master',
    domain: 'syn',
    also: ['sem'],
    title: 'Wat een werkwoord nodig heeft',
    skill: 'Zinsbouw',
    icon: 'V³',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Valentie en rollen',
        panels: [
          {
            text: 'Welkom in de master, waar werkwoorden tafels reserveren. *Geven* boekt meteen voor drie: iemand geeft iemand iets. Lucien Tesnière (1959) noemde dat de *valentie* van een werkwoord, naar de scheikunde: het aantal plekken waar iets aan vast moet.',
            lab: {
              label: 'Tik een werkwoord',
              chips: [
                { k: 'regenen', out: '0: Het regent.', note: 'Het is een loos onderwerp: er is niemand die regent.' },
                { k: 'slapen', out: '1: Anna slaapt.', note: 'Eén deelnemer.' },
                { k: 'zien', out: '2: Anna ziet de zee.', note: 'Wie ziet, en wat.' },
                { k: 'geven', out: '3: Anna geeft Bo een boek.', note: 'Wie geeft, aan wie, en wat.' },
              ],
            },
          },
          {
            text: 'Wat het werkwoord vraagt, heet een *argument*. De rest is een *bepaling*: vrij toe te voegen, zoals tijd en plaats. De toets is de *doe-dat-toets*. *Ze sliep, en dat deed ze in de tuin*: kan, dus *in de tuin* is een bepaling. *Ze zette het glas, en dat deed ze op tafel*: raar, want *zetten* vraagt een plek. *Op tafel* is een argument.',
            rule: 'Argument: het werkwoord vraagt erom. Bepaling: mag erbij, en de doe-dat-toets lukt.',
            mark: { q: 'Tik alle woorden van de bepalingen', sentence: 'Gisteren gaf Anna haar broer in de keuken een boek.', targets: [0, 5, 6, 7], note: 'Gisteren en in de keuken mogen weg. Anna, haar broer en een boek vraagt geven zelf.' },
          },
          {
            text: 'Elk argument speelt een *rol*. De *agens* doet iets, het *thema* ondergaat of verplaatst, de *ontvanger* krijgt, de *ervaarder* voelt of merkt. Het onderwerp is lang niet altijd de agens. In *Die film bevalt me* is *me* de ervaarder en *die film* het onderwerp.',
            deep: {
              q: 'Wat doet de lijdende vorm met de rollen?',
              a: 'De rollen blijven, de zinsdelen schuiven. In *Anna gaf Bo een boek* is Anna agens en onderwerp. In *Het boek werd door Anna aan Bo gegeven* is het boek onderwerp, maar nog steeds thema. Daarom zeggen taalkundigen dat rollen bij het *lexicon* horen (het werkwoord) en zinsdelen bij de *syntaxis* (de zin). De koppeling ertussen heet *linking*.',
            },
            quiz: {
              q: 'In ‘De sleutel opende de deur’ is ‘de sleutel’…',
              options: ['een instrument, geen agens', 'de agens', 'het thema'],
              answer: 'een instrument, geen agens',
              why: 'Een sleutel doet niets uit zichzelf. Iemand gebruikte hem. Toch staat hij op de plek van het onderwerp.',
            },
          },
        ],
      },
      {
        kind: 'highlight',
        id: 'rollen',
        prompt: 'Kleur de rollen',
        intro: 'Wie doet het, wie krijgt het, wat gaat er over, en wat is erbij gezet?',
        pens: [
          { id: 'agens', label: 'agens', tag: 'doet', ask: 'Is dit wie de handeling uitvoert?', accent: 'red' },
          { id: 'ontv', label: 'ontvanger', tag: 'krijgt', ask: 'Is dit wie iets krijgt?', accent: 'teal' },
          { id: 'thema', label: 'thema', tag: 'wat', ask: 'Is dit wat er van eigenaar wisselt?', accent: 'blue' },
          { id: 'bep', label: 'bepaling', tag: 'erbij', ask: 'Mag dit weg?', accent: 'slate' },
        ],
        words: [
          { t: 'Gisteren', role: 'bep' },
          { t: 'gaf' },
          { t: 'Anna', role: 'agens' },
          { t: 'haar', role: 'ontv' },
          { t: 'broer', role: 'ontv' },
          { t: 'een', role: 'thema' },
          { t: 'boek.', role: 'thema' },
        ],
        done: { title: 'Drie plekken, één extra', text: 'Geven heeft drie argumenten. Gisteren is een bepaling: die mag bij elk werkwoord.' },
      },
      {
        kind: 'sort',
        id: 'valentie',
        prompt: 'Hoeveel argumenten?',
        buckets: ['0', '1', '2', '3'],
        items: [
          { t: 'regenen', b: 0 },
          { t: 'slapen', b: 1 },
          { t: 'lachen', b: 1 },
          { t: 'kennen', b: 2 },
          { t: 'zien', b: 2 },
          { t: 'sturen', b: 3 },
          { t: 'geven', b: 3 },
          { t: 'sneeuwen', b: 0 },
          { t: 'wonen', b: 2 },
        ],
        why: 'Regenen en sneeuwen hebben alleen een loos het. Wonen vraagt een plek: Anna woont is onaf. Sturen en geven: wie, aan wie, wat.',
      },
      {
        kind: 'choice',
        id: 'zetten',
        prompt: 'Welke zin mist een argument?',
        before: '',
        after: '',
        options: ['Hij zette het glas.', 'Hij zette het glas op tafel.', 'Hij dronk het glas leeg.'],
        answer: 'Hij zette het glas.',
        why: 'Zetten vraagt een plek. Zonder op tafel voelt de zin onaf.',
      },
      {
        kind: 'bet',
        id: 'bevallen',
        prompt: 'Welke rol heeft ‘me’ in ‘Die film bevalt me’?',
        options: ['ervaarder', 'agens', 'thema'],
        answer: 'ervaarder',
        why: 'Ik voel iets bij de film. Bij bevallen staat de ervaarder niet op de plek van het onderwerp.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Protorollen en een valentie die verschuift',
        panels: [
          {
            text: 'Hoeveel rollen zijn er? Charles Fillmore (1968) begon met een korte lijst ‘diepe naamvallen’, maar elke onderzoeker kwam op een andere lijst uit. David Dowty (1991) gooide het over een andere boeg. Er zijn maar twee *protorollen*, elk een bundel kenmerken. *Proto-agens*: handelt met opzet, voelt of merkt, veroorzaakt iets, beweegt, bestaat los van de gebeurtenis. *Proto-patiens*: verandert, wordt geraakt, staat stil, ontstaat pas door de gebeurtenis. Het argument met de meeste agenskenmerken wordt onderwerp.',
            rule: 'Dowty: het argument met de meeste proto-agenskenmerken wordt onderwerp, dat met de meeste patienskenmerken lijdend voorwerp.',
            lab: {
              label: 'Tik een onderwerp en tel de agenskenmerken',
              chips: [
                { k: 'Anna bakt een taart', out: 'Anna: opzet, voelt, veroorzaakt, beweegt', note: 'Bijna alle agenskenmerken. De taart ontstaat pas door het bakken: patiens.' },
                { k: 'Anna ziet de zee', out: 'Anna: alleen voelt of merkt', note: 'Eén kenmerk, maar meer dan de zee. Dus toch onderwerp.' },
                { k: 'De sleutel opent de deur', out: 'sleutel: veroorzaakt, beweegt', note: 'Geen opzet, maar meer agenskenmerken dan de deur.' },
              ],
            },
          },
          {
            text: 'Valentie ligt niet vast. Er zijn operaties die argumenten weghalen of toevoegen. Het *passief* schuift de agens naar een *door*-bepaling. Het *causatief* met *laten* voegt een veroorzaker toe. Het *anticausatief* laat de veroorzaker weg: *Het glas breekt* (zie w16 voor het hulpwerkwoord). En de *middenconstructie*: *Dit boek leest lekker*. Daar is de lezer verdwenen, de uitspraak is algemeen, en er moet een bijwoord bij. Peter Ackema en Maaike Schoorlemmer (1995) maakten van de Nederlandse middenconstructie een bekend studieobject.',
            paradigm: {
              q: 'Hoeveel argumenten heeft het werkwoord in elke zin?',
              cols: ['argumenten'],
              rows: [
                { label: 'Anna breekt het glas.', cells: ['2'] },
                { label: 'Het glas breekt.', cells: [{ fill: '1', hint: 'Anticausatief: alleen het glas, de veroorzaker is weg.' }] },
                { label: 'Ik laat Anna het glas breken.', cells: [{ fill: '3', hint: 'Causatief: ik, Anna en het glas.' }] },
                { label: 'Het glas wordt gebroken.', cells: [{ fill: '1', hint: 'Passief: de agens is weg of staat in een door-bepaling, die mag weg.' }] },
                { label: 'Dit glas breekt makkelijk.', cells: [{ fill: '1', hint: 'Middenconstructie: wie breekt is weg, de uitspraak is algemeen.' }] },
              ],
              extra: ['0', '4'],
              note: 'Hetzelfde werkwoord, van één tot drie argumenten. Valentie is een begin, geen eindstation.',
            },
          },
          {
            text: 'Een driewaardig werkwoord kan op twee manieren: *Anna geeft Bo een boek* en *Anna geeft een boek aan Bo*. Dat heet de *datiefalternantie*. Maar de twee zijn niet altijd uitwisselbaar. *Ik stuur het pakket naar de zolder* kan, *Ik stuur de zolder het pakket* niet. Zonder *aan* moet de ontvanger iets kunnen *bezitten*. Het Nederlands heeft bovendien het *krijgen-passief*: *Bo krijgt een boek toegestuurd*. Daar wordt de ontvanger onderwerp.',
            rule: 'Zonder aan moet de ontvanger iets kunnen krijgen en hebben.',
            quiz: {
              q: 'Welke zin kan niet?',
              options: ['Ik stuur de zolder het pakket.', 'Ik stuur het pakket naar de zolder.', 'Ik stuur mijn zus het pakket.'],
              answer: 'Ik stuur de zolder het pakket.',
              why: 'Een zolder kan niets bezitten. Zonder aan of naar moet de ontvanger een mogelijke eigenaar zijn.',
            },
          },
          {
            text: 'Ook een bepaling van plaats kan een argument zijn. *Anna woont in Gent*: de doe-dat-toets faalt (*Anna woont, en dat doet ze in Gent*). *Wonen* vraagt dus een plek, net als *zetten*. De ANS noemt *in Gent* een bijwoordelijke bepaling, maar voor de valentie is het een argument. Woordsoort en zinsdeel zeggen niet alles over wat een werkwoord nodig heeft.',
            quiz: {
              q: 'Is ‘in Gent’ in ‘Anna woont in Gent’ een argument?',
              options: ['Ja: wonen vraagt een plek', 'Nee: het is een plaatsbepaling, die mag altijd weg'],
              answer: 'Ja: wonen vraagt een plek',
              why: 'Anna woont is onaf. De doe-dat-toets faalt, dus in Gent hoort bij de valentie.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'operatie',
        prompt: 'Welke operatie op de valentie?',
        buckets: ['passief', 'causatief', 'anticausatief', 'middenconstructie'],
        items: [
          { t: 'Het raam werd ingegooid.', b: 0 },
          { t: 'De deur wordt gesloten.', b: 0 },
          { t: 'Ik liet hem de auto wassen.', b: 1 },
          { t: 'Ze liet de kinderen dansen.', b: 1 },
          { t: 'De deur ging open.', b: 2 },
          { t: 'Het ijs smelt.', b: 2 },
          { t: 'De vaas brak.', b: 2 },
          { t: 'Dit boek leest lekker.', b: 3 },
          { t: 'Die stoel zit prettig.', b: 3 },
        ],
        why: 'Passief: worden + deelwoord. Causatief: laten. Anticausatief: het ding verandert vanzelf. Middenconstructie: een algemene eigenschap, met een bijwoord als lekker of prettig.',
      },
      {
        kind: 'rewrite',
        id: 'krijgen',
        prompt: 'Maak er een krijgen-passief van: de ontvanger wordt onderwerp.',
        source: 'Ze stuurden Bo een pakket toe.',
        accept: ['Bo kreeg een pakket toegestuurd.'],
        why: 'Bij het krijgen-passief schuift de ontvanger naar de plek van het onderwerp. Het pakket blijft lijdend voorwerp.',
      },
      {
        kind: 'bet',
        id: 'dowty',
        prompt: 'In ‘Anna ontvangt een brief’ is Anna onderwerp. Welk proto-agenskenmerk heeft ze?',
        options: ['Ze voelt en merkt iets', 'Ze veroorzaakt iets', 'Ze verandert van toestand'],
        answer: 'Ze voelt en merkt iets',
        why: 'Anna weet dat ze een brief krijgt. De brief heeft geen enkel agenskenmerk, dus Anna wint.',
      },
      {
        kind: 'choice',
        id: 'zolder',
        prompt: 'Kies de goede zin.',
        before: '',
        after: '',
        options: ['Ik stuur het pakket naar de zolder.', 'Ik stuur de zolder het pakket.'],
        answer: 'Ik stuur het pakket naar de zolder.',
        why: 'Een zolder kan niets bezitten. Dan moet de ontvanger in een voorzetselgroep.',
      },
      {
        kind: 'swipe',
        id: 'valentie2',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Dowty werkt met een lange vaste lijst van rollen.', ok: false, fix: 'Dowty werkt met twee protorollen', why: 'Proto-agens en proto-patiens, elk een bundel kenmerken.' },
          { t: 'In ‘Dit boek leest lekker’ is de lezer verdwenen.', ok: true, why: 'Dat is de middenconstructie.' },
          { t: 'Laten voegt een argument toe.', ok: true, why: 'Causatief: ik laat Anna lachen.' },
          { t: 'Het passief verandert de rollen van de argumenten.', ok: false, fix: 'De rollen blijven, de zinsdelen schuiven', why: 'Het boek blijft thema, ook als het onderwerp wordt.' },
          { t: 'In ‘Bo krijgt een boek toegestuurd’ is Bo ontvanger en onderwerp.', ok: true, why: 'Het krijgen-passief maakt de ontvanger onderwerp.' },
          { t: 'Een bepaling van plaats kan nooit een argument zijn.', ok: false, fix: 'Bij wonen en zetten is de plek een argument', why: 'Anna woont is onaf zonder plek.' },
        ],
      },
    ],
  },
  {
    id: 'w16',
    stage: 'master',
    domain: 'syn',
    also: ['sem'],
    title: 'Hebben of zijn?',
    skill: 'Zinsbouw',
    icon: 'zijn',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Onaccusativiteit',
        panels: [
          {
            text: 'Je *hebt* gewerkt, maar je *bent* gevallen. Het Nederlands houdt blijkbaar bij of je iets deed of dat het je overkwam. David Perlmutter (1978) zag dat werkwoorden met één argument in twee groepen vallen. *Onergatief*: het onderwerp doet iets (*werken*, *lachen*, *dansen*). *Onaccusatief*: het onderwerp ondergaat iets (*vallen*, *sterven*, *groeien*).',
            lab: {
              label: 'Tik een werkwoord',
              chips: [
                { k: 'werken', out: 'Ik heb gewerkt.', note: 'Onergatief: ik doe het.' },
                { k: 'vallen', out: 'Ik ben gevallen.', note: 'Onaccusatief: het overkomt me.' },
                { k: 'telefoneren', out: 'Ik heb getelefoneerd.', note: 'Onergatief.' },
                { k: 'verdwijnen', out: 'Het is verdwenen.', note: 'Onaccusatief.' },
              ],
            },
            deep: {
              q: 'Waarom die rare naam?',
              a: 'De theorie zegt dat het onderwerp van *vallen* eigenlijk begint als lijdend voorwerp (de *accusatief*) en pas later naar de plek van het onderwerp schuift. Een werkwoord zonder echt lijdend voorwerp maar met zo’n verkapt voorwerp heet dus *on-accusatief*. Teun Hoekstra (1984) werkte de Nederlandse kant uit.',
            },
          },
          {
            text: 'Het hulpwerkwoord is niet het enige bewijs. Het deelwoord van een onaccusatief werkwoord kan vóór een naamwoord: *de gevallen boom*, *het verdwenen boek*. Bij een onergatief werkwoord niet: *de gewerkte man*. En andersom: een onpersoonlijk passief lukt alleen met onergatieve werkwoorden: *Er werd gelachen*, maar niet *Er werd gevallen*.',
            paradigm: {
              q: 'Doe de drie toetsen',
              cols: ['hulpwerkwoord', 'deelwoord vóór zn', 'er werd ge…'],
              rows: [
                { label: 'werken', cells: ['heeft', 'kan niet', 'kan'] },
                { label: 'vallen', cells: [{ fill: 'is', hint: 'Het overkomt je: zijn.' }, { fill: 'kan', hint: 'de gevallen boom: kan.' }, { fill: 'kan niet', hint: 'Er werd gevallen? Dat klinkt fout.' }] },
                { label: 'dansen', cells: [{ fill: 'heeft', hint: 'Je doet het zelf: hebben.' }, { fill: 'kan niet', hint: 'de gedanste vrouw? Dat kan niet.' }, { fill: 'kan', hint: 'Er werd gedanst: kan.' }] },
                { label: 'sterven', cells: [{ fill: 'is', hint: 'Het overkomt je: zijn.' }, { fill: 'kan', hint: 'de gestorven soldaat: kan.' }, { fill: 'kan niet', hint: 'Er werd gestorven? Dat klinkt fout.' }] },
              ],
              note: 'Drie toetsen, steeds dezelfde twee groepen. Dat is het bewijs dat het om één onderliggend verschil gaat.',
            },
          },
          {
            text: 'Nu wordt het subtiel. *Ik heb gelopen*, maar *Ik ben naar huis gelopen*. Zodra er een eindpunt bij komt, kiest hetzelfde werkwoord *zijn*. Wat telt is of de gebeurtenis een *verandering met een eindpunt* is. Antonella Sorace (2000) zette werkwoorden op een schaal: verandering van plaats krijgt het vaakst *zijn*, gecontroleerde activiteit het vaakst *hebben*.',
            rule: 'Verandering met een eindpunt → zijn. Activiteit zonder eindpunt → hebben.',
            show: [{ right: 'We hebben de hele middag gefietst. (activiteit)' }, { right: 'We zijn naar Utrecht gefietst. (verandering van plaats)' }],
            quiz: {
              q: '‘Ze … naar de overkant gezwommen.’ Welk hulpwerkwoord?',
              options: ['is', 'heeft'],
              answer: 'is',
              why: 'Naar de overkant is een eindpunt: verandering van plaats, dus zijn.',
            },
          },
        ],
      },
      {
        kind: 'choice',
        id: 'fietsen1',
        prompt: 'hebben of zijn?',
        before: 'Ik',
        after: 'naar het station gefietst.',
        options: ['ben', 'heb'],
        answer: 'ben',
        why: 'Naar het station is een eindpunt: verandering van plaats, dus zijn.',
      },
      {
        kind: 'choice',
        id: 'fietsen2',
        prompt: 'hebben of zijn?',
        before: 'Wij',
        after: 'de hele middag gefietst.',
        options: ['hebben', 'zijn'],
        answer: 'hebben',
        why: 'Geen eindpunt, alleen activiteit: hebben.',
      },
      {
        kind: 'sort',
        id: 'hulp',
        prompt: 'heb of ben?',
        buckets: ['heb …', 'ben …'],
        items: [
          { t: 'getelefoneerd', b: 0 },
          { t: 'gestorven', b: 1 },
          { t: 'gegroeid', b: 1 },
          { t: 'gehuild', b: 0 },
          { t: 'ontstaan', b: 1 },
          { t: 'geslapen', b: 0 },
          { t: 'gebleven', b: 1 },
          { t: 'bestaan', b: 0 },
          { t: 'gedanst', b: 0 },
        ],
        why: 'Sterven, groeien, ontstaan en blijven: zijn. Telefoneren, huilen, slapen en dansen doet het onderwerp zelf. Let op bestaan: geen activiteit, en toch heb bestaan (zie de schaal van Sorace hieronder).',
      },
      {
        kind: 'bet',
        id: 'boom',
        prompt: 'Waarom kan ‘de gevallen boom’ wel en ‘de gewerkte man’ niet?',
        options: ['Het onderwerp van vallen gedraagt zich als een lijdend voorwerp', 'Vallen is een sterk werkwoord', 'Gewerkt heeft te veel lettergrepen'],
        answer: 'Het onderwerp van vallen gedraagt zich als een lijdend voorwerp',
        why: 'Net als bij de gelezen krant (lijdend voorwerp van lezen) slaat het deelwoord op wie iets onderging.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Andere talen, een schaal en twijfelgevallen',
        panels: [
          {
            text: 'Het Nederlands staat niet alleen. Het Duits kiest tussen *sein* en *haben*, het Italiaans tussen *essere* en *avere*: *sono caduto* (ik ben gevallen), maar *ho lavorato* (ik heb gewerkt). Luigi Burzio (1986) vond voor het Italiaans nog een eigen toets, met het woordje *ne*. Het Frans gebruikt *être* maar bij een korte lijst bewegingswerkwoorden, zoals *aller*, *venir* en *mourir*. Het Engels had het ook: *The hour is come* in oude bijbelvertalingen. Nu zegt het overal *have*.',
            lab: {
              label: 'Tik een taal',
              chips: [
                { k: 'Duits', out: 'ich bin gefallen · ich habe gearbeitet', note: 'Bijna dezelfde verdeling als het Nederlands.' },
                { k: 'Italiaans', out: 'sono caduto · ho lavorato', note: 'Essere voor onaccusatief, avere voor onergatief.' },
                { k: 'Frans', out: 'je suis venu · j’ai travaillé', note: 'Être alleen bij een kleine groep werkwoorden.' },
                { k: 'Engels', out: 'I have fallen', note: 'Het oude be-hulpwerkwoord is verdwenen: the hour is come.' },
              ],
            },
          },
          {
            text: 'Antonella Sorace (2000) zette werkwoorden op een schaal. Bovenaan *verandering van plaats* (*komen*), dan *verandering van toestand* (*groeien*), *voortduren van een toestand* (*blijven*), *bestaan* (*bestaan*), *ongecontroleerd proces* (*trillen*), *gecontroleerd proces met beweging* (*zwemmen*), en onderaan *gecontroleerd proces zonder beweging* (*werken*). Bovenaan kiezen talen *zijn*, onderaan *hebben*. In het midden verschillen talen en twijfelen sprekers. Het Nederlands knipt tussen *blijven* (zijn) en *bestaan* (hebben).',
            rule: 'Hoe meer verandering met eindpunt, hoe meer zijn. Hoe meer gecontroleerde activiteit, hoe meer hebben.',
            quiz: {
              q: 'Waar knipt het Nederlands op de schaal van Sorace?',
              options: ['Tussen blijven (zijn) en bestaan (hebben)', 'Tussen werken en zwemmen', 'Helemaal bovenaan'],
              answer: 'Tussen blijven (zijn) en bestaan (hebben)',
              why: 'Ik ben gebleven, maar het heeft bestaan.',
            },
          },
          {
            text: 'Hetzelfde werkwoord kan beide hulpwerkwoorden krijgen. *Het ijs is gesmolten*, maar *De zon heeft het ijs gesmolten*. *De vaas is gebroken*, maar *Hij heeft de vaas gebroken*. Zonder veroorzaker is het werkwoord onaccusatief (*zijn*); met veroorzaker overgankelijk (*hebben*). Het hulpwerkwoord hangt dus niet aan het werkwoord, maar aan de argumentstructuur van de zin.',
            paradigm: {
              q: 'Vul het hulpwerkwoord in',
              cols: ['zonder veroorzaker', 'met veroorzaker'],
              rows: [
                { label: 'smelten', cells: ['is', 'heeft'] },
                { label: 'breken', cells: [{ fill: 'is', hint: 'De vaas is gebroken: het overkomt de vaas.' }, { fill: 'heeft', hint: 'Hij heeft de vaas gebroken: een agens met een lijdend voorwerp.' }] },
                { label: 'stoppen', cells: [{ fill: 'is', hint: 'De trein is gestopt.' }, { fill: 'heeft', hint: 'De conducteur heeft de trein gestopt.' }] },
                { label: 'veranderen', cells: [{ fill: 'is', hint: 'De stad is veranderd.' }, { fill: 'heeft', hint: 'Dat heeft alles veranderd.' }] },
              ],
              extra: ['wordt'],
              note: 'Eén werkwoord, twee structuren, twee hulpwerkwoorden.',
            },
          },
          {
            text: 'Dan de twijfelgevallen. *Vergeten*: *Ik ben mijn sleutels vergeten* en *Ik heb mijn sleutels vergeten* zijn allebei correct. *Volgen*: *Ik heb een cursus gevolgd*, maar *Ik ben hem naar huis gevolgd*, want dan beweeg je. En *beginnen* krijgt altijd *zijn*, ook met een lijdend voorwerp: *Ik ben een nieuw boek begonnen*. Zulke gevallen laten zien dat het hulpwerkwoord geen simpele regel volgt, maar een betekenisschaal.',
            quiz: {
              q: 'Welke zin is goed?',
              options: ['Ik ben een nieuw boek begonnen.', 'Ik heb een nieuw boek begonnen.'],
              answer: 'Ik ben een nieuw boek begonnen.',
              why: 'Beginnen krijgt altijd zijn, ook met een lijdend voorwerp.',
            },
          },
        ],
      },
      {
        kind: 'ladder',
        id: 'sorace',
        prompt: 'Bouw de schaal van Sorace',
        intro: 'Zet de werkwoorden van ‘meestal hebben’ naar ‘meestal zijn’.',
        sentence: { before: 'Op deze plek in de schaal staat:', after: '' },
        steps: [{ t: 'werken' }, { t: 'zwemmen' }, { t: 'trillen' }, { t: 'bestaan' }, { t: 'blijven' }, { t: 'groeien' }, { t: 'komen' }],
        low: 'hebben',
        high: 'zijn',
        startHint: 'Begin met een gecontroleerde activiteit zonder beweging.',
        done: { title: 'Schaal compleet', text: 'Van gecontroleerde activiteit naar verandering van plaats. Het Nederlands knipt tussen bestaan (heeft) en blijven (is).' },
      },
      {
        kind: 'sort',
        id: 'tweehulp',
        prompt: 'heeft of is?',
        buckets: ['heeft', 'is'],
        items: [
          { t: 'De zon … het ijs gesmolten.', b: 0 },
          { t: 'Hij … de vaas gebroken.', b: 0 },
          { t: 'De conducteur … de trein gestopt.', b: 0 },
          { t: 'Ze … een cursus gevolgd.', b: 0 },
          { t: 'Het ijs … gesmolten.', b: 1 },
          { t: 'De vaas … gebroken.', b: 1 },
          { t: 'De trein … gestopt.', b: 1 },
          { t: 'Ze … hem naar huis gevolgd.', b: 1 },
          { t: 'Hij … een nieuw boek begonnen.', b: 1 },
        ],
        why: 'Met een veroorzaker en een lijdend voorwerp: heeft. Zonder veroorzaker, of met beweging naar een doel: is. Beginnen krijgt altijd is.',
      },
      {
        kind: 'fix',
        id: 'ijs',
        prompt: 'Tik het foute woord aan en verbeter het.',
        sentence: 'Het ijs heeft in de zon gesmolten.',
        wrong: 2,
        answer: 'is',
        why: 'Zonder veroorzaker overkomt het smelten het ijs: onaccusatief, dus zijn.',
      },
      {
        kind: 'bet',
        id: 'vergeten',
        prompt: 'Welke hulpwerkwoorden passen in ‘Ik … mijn paraplu in de trein vergeten’?',
        options: ['ben en heb allebei', 'alleen ben', 'alleen heb'],
        answer: 'ben en heb allebei',
        why: 'Vergeten kan met zijn en met hebben. Zijn hoor je vaker, vooral als het je overkwam.',
      },
      {
        kind: 'bet',
        id: 'italiaans',
        prompt: 'Het Italiaans zegt ‘sono caduto’ maar ‘ho lavorato’. Wat laat dat zien?',
        options: ['Onaccusativiteit is niet alleen Nederlands', 'Het Italiaans leende het van het Nederlands', 'Het is toeval'],
        answer: 'Onaccusativiteit is niet alleen Nederlands',
        why: 'Talen die niet nauw verwant zijn, maken dezelfde splitsing. Dat wijst op een diep verschil tussen soorten gebeurtenissen.',
      },
      {
        kind: 'swipe',
        id: 'hulpww',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Het Engels gebruikt nog steeds be bij vallen: I am fallen.', ok: false, fix: 'Het Engels zegt nu I have fallen', why: 'Be als hulpwerkwoord van het voltooid is uit het Engels verdwenen.' },
          { t: 'Bestaan krijgt in het Nederlands hebben.', ok: true, why: 'Het heeft lang bestaan.' },
          { t: 'Beginnen krijgt hebben als er een lijdend voorwerp bij staat.', ok: false, fix: 'Beginnen krijgt altijd zijn', why: 'Ik ben een boek begonnen.' },
          { t: 'Hetzelfde werkwoord kan zijn en hebben krijgen.', ok: true, why: 'Het ijs is gesmolten, de zon heeft het ijs gesmolten.' },
          { t: 'Op de schaal van Sorace staat verandering van plaats bovenaan.', ok: true, why: 'Daar kiezen talen het vaakst zijn.' },
          { t: 'Ik ben hem gevolgd en ik heb hem gevolgd betekenen altijd hetzelfde.', ok: false, fix: 'Met zijn beweeg je achter hem aan', why: 'Een cursus volgen: hebben. Iemand naar huis volgen: zijn.' },
        ],
      },
    ],
  },
  {
    id: 'w17',
    stage: 'master',
    domain: 'sem',
    also: ['prag'],
    title: 'Is een pinguïn een vogel?',
    skill: 'Woorden',
    icon: '◎',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Kenmerken tegenover prototypen',
        panels: [
          {
            text: 'Een pinguïn is een vogel. Iedereen weet het, niemand gelooft het helemaal. De klassieke theorie zegt: een woord betekent een bundel *kenmerken* die allemaal nodig en samen genoeg zijn. *Man* = [+mens, +volwassen, +mannelijk]. Dat heet *componentiële analyse*, naar het voorbeeld van klankkenmerken (zie Klank en letter, k17).',
            paradigm: {
              q: 'Vul de kenmerken in',
              cols: ['volwassen', 'mannelijk'],
              rows: [
                { label: 'man', cells: ['+', '+'] },
                { label: 'vrouw', cells: [{ fill: '+', hint: 'Een vrouw is volwassen.' }, { fill: '−', hint: 'Een vrouw is niet mannelijk.' }] },
                { label: 'jongen', cells: [{ fill: '−', hint: 'Een jongen is nog niet volwassen.' }, { fill: '+', hint: 'Een jongen is mannelijk.' }] },
                { label: 'meisje', cells: [{ fill: '−', hint: 'Een meisje is nog niet volwassen.' }, { fill: '−', hint: 'Een meisje is niet mannelijk.' }] },
              ],
              note: 'Twee kenmerken, vier woorden. Elegant, en toch klopt het niet helemaal.',
            },
          },
          {
            text: 'Is de paus een vrijgezel? Volgens de kenmerken [+man, +volwassen, −getrouwd] wel. Toch voelt het fout. Eleanor Rosch (1975) liet mensen beoordelen hoe goed iets bij een categorie past. Een roodborst scoort als ideale vogel, een pinguïn bijna onderaan. Mensen beslissen ook sneller dat een roodborst een vogel is. Categorieën hebben een *prototype*: een beste voorbeeld in het midden en een vage rand.',
            quiz: {
              q: 'Welke vogel scoorde bij Rosch als beste voorbeeld van een vogel?',
              options: ['de roodborst', 'de pinguïn', 'de struisvogel'],
              answer: 'de roodborst',
              why: 'Het prototype zit in het midden van de categorie; de pinguïn hangt aan de rand.',
            },
            rule: 'Een categorie is geen lijstje eisen maar een middelpunt met een vage rand.',
            deep: {
              q: 'Kopje of kom?',
              a: 'William Labov (1973) liet tekeningen zien van bakjes die steeds breder werden. Bij een smal bakje zeiden mensen *kopje*, bij een breed *kom*. Maar de grens verschoof met de context: stond er soep in, dan werd hetzelfde bakje eerder een kom. Al eerder schreef Ludwig Wittgenstein dat de leden van *spel* (schaken, voetbal, kiekeboe) geen gemeenschappelijk kenmerk delen, alleen een *familiegelijkenis*.',
            },
          },
          {
            text: 'Taal heeft speciale woorden voor de rand van een categorie. George Lakoff (1973) noemde ze *hedges*: *technisch gezien* is een walvis een zoogdier, een tomaat is *strikt genomen* een vrucht, een mus is *een echte* vogel. Een goede schrijver gebruikt ze precies: ze vertellen de lezer waar in de categorie iets staat.',
            show: [{ right: 'Technisch gezien is een tomaat een vrucht. (rand)' }, { right: 'Een appel is een echte vrucht. (midden)' }],
            quiz: {
              q: '‘Een mus is een echte vogel.’ Waar staat de mus volgens deze hedge?',
              options: ['In het midden van de categorie', 'Aan de rand van de categorie', 'Buiten de categorie'],
              answer: 'In het midden van de categorie',
              why: 'Een echte X wijst naar het prototype. Technisch gezien wijst naar de rand.',
            },
          },
        ],
      },
      {
        kind: 'ladder',
        id: 'vogel',
        prompt: 'Hoe vogelig is deze vogel?',
        intro: 'Zet de vogels op de ladder, van rand naar prototype. Zo scoorden ze ongeveer bij Rosch.',
        sentence: { before: 'Een', after: 'is een vogel.' },
        steps: [{ t: 'pinguïn' }, { t: 'kip' }, { t: 'eend' }, { t: 'roodborst' }],
        low: 'rand',
        high: 'prototype',
        startHint: 'Begin met de vogel die niet vliegt en zwemt als een vis.',
        done: { title: 'Gradiënt', text: 'Alle vier zijn vogels, maar niet allemaal even goed. Dat verschil zit in je hoofd en je kunt het meten.' },
      },
      {
        kind: 'choice',
        id: 'hedge',
        prompt: 'Kies de hedge die past.',
        before: '',
        after: 'is een tomaat een vrucht.',
        options: ['Technisch gezien', 'Typisch', 'Echt'],
        answer: 'Technisch gezien',
        why: 'Een tomaat staat aan de rand van vrucht. Technisch gezien zegt: volgens de definitie wel, gevoelsmatig niet.',
      },
      {
        kind: 'swipe',
        id: 'prototype',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Volgens de prototypetheorie zijn alle vogels even goed vogel.', ok: false, fix: 'Sommige leden zijn betere voorbeelden', why: 'Een roodborst is een beter voorbeeld dan een pinguïn.' },
          { t: 'Mensen herkennen een prototype sneller als lid van de categorie.', ok: true, why: 'Dat mat Rosch met reactietijden.' },
          { t: 'Componentiële analyse werkt met kenmerken als [+volwassen].', ok: true, why: 'Elk woord is een bundel plussen en minnen.' },
          { t: 'De grens tussen kopje en kom ligt vast.', ok: false, fix: 'De grens verschuift met de context', why: 'Bij Labov werd een bakje met soep eerder een kom.' },
          { t: 'Volgens Wittgenstein delen alle spelen één gemeenschappelijk kenmerk.', ok: false, fix: 'Ze delen alleen een familiegelijkenis', why: 'Schaken, voetbal en kiekeboe hebben geen kenmerk dat ze allemaal delen.' },
          { t: 'Een hedge als technisch gezien wijst naar de rand van een categorie.', ok: true, why: 'Technisch gezien is een tomaat een vrucht.' },
        ],
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Leugens, oneven getallen en een gevaarlijke klasse',
        panels: [
          {
            text: 'Prototypen gelden ook voor werkwoorden. Linda Coleman en Paul Kay (1981) onderzochten het Engelse *lie* (liegen). Een prototypische leugen heeft drie elementen: (1) wat je zegt is onwaar, (2) je denkt dat het onwaar is, (3) je wilt de ander misleiden. Ze legden mensen verhaaltjes voor met steeds andere combinaties. Met alle drie: een duidelijke leugen. Met minder: een randgeval. Het zwaarst woog element 2: zelf denken dat het onwaar is.',
            rule: 'Een prototypische leugen: onwaar, je weet het, en je wilt misleiden. Minder elementen: randgeval.',
            lab: {
              label: 'Tik een situatie',
              chips: [
                { k: 'ziek melden terwijl je gezond bent', out: '3 van 3: echte leugen', note: 'Onwaar, je weet het, en je wilt je baas misleiden.' },
                { k: 'verkeerde tijd, maar je dacht dat het klopte', out: '1 van 3: vergissing', note: 'Alleen onwaar. Bijna niemand noemt dit liegen.' },
                { k: 'bewust misleiden, maar het blijkt toevallig waar', out: '2 van 3: randgeval', note: 'Je dacht dat het onwaar was en wilde misleiden. Veel mensen noemen het toch een leugen.' },
                { k: 'een acteur op het toneel', out: '2 van 3: geen bedoeling', note: 'Onwaar en hij weet het, maar niemand wordt misleid.' },
              ],
            },
          },
          {
            text: 'Nu de tegenaanval. Sharon Armstrong, Lila Gleitman en Henry Gleitman (1983) vroegen mensen hoe goed iets een *oneven getal* is. Antwoord: 3 is een beter oneven getal dan 447. Maar iedereen weet de definitie: niet deelbaar door twee. Er is geen vage rand. Hun conclusie: typicaliteitsoordelen bewijzen niet dat een categorie vaag is. Mensen kunnen een scherpe definitie hebben én een gevoel voor het beste voorbeeld. Sindsdien onderscheiden onderzoekers *prototype-effecten* van *prototype-structuur*.',
            rule: 'Prototype-effecten bewijzen nog geen vage categorie: ook oneven getal heeft ze.',
            quiz: {
              q: 'Wat lieten Armstrong en de Gleitmans zien?',
              options: ['Zelfs een scherp gedefinieerde categorie geeft typicaliteitseffecten', 'Oneven getallen hebben een vage grens', 'Prototypen bestaan niet'],
              answer: 'Zelfs een scherp gedefinieerde categorie geeft typicaliteitseffecten',
              why: '3 voelt als een beter oneven getal dan 447, maar de definitie is glashelder.',
            },
          },
          {
            text: 'George Lakoff (1987) gaf zijn boek de titel *Women, Fire, and Dangerous Things*. Die komt uit het Dyirbal, een Australische taal die R.M.W. Dixon beschreef. Eén naamwoordklasse, *balan*, bevat onder meer vrouwen, vuur en gevaarlijke dingen. Ze delen geen kenmerk, maar zijn via een keten van verbanden aan elkaar gekoppeld, onder meer via mythen. Lakoff noemde zoiets een *radiale categorie*: een centrum met uitlopers. Ook *moeder* werkt zo: biologische moeder in het midden, met pleegmoeder, stiefmoeder en draagmoeder als uitlopers.',
            lab: {
              label: 'Tik een soort moeder',
              chips: [
                { k: 'biologische moeder', out: 'centrum', note: 'Baart, voedt op, geeft de genen: alle kenmerken.' },
                { k: 'pleegmoeder', out: 'uitloper: opvoeden', note: 'Voedt op, maar baarde niet.' },
                { k: 'draagmoeder', out: 'uitloper: baren', note: 'Baart, maar voedt meestal niet op.' },
                { k: 'stiefmoeder', out: 'uitloper: huwelijk', note: 'Getrouwd met de vader, niet gebaard.' },
              ],
            },
          },
          {
            text: 'Is er dan één prototype in je hoofd, of iets anders? Douglas Medin en Marguerite Schaffer (1978) stelden de *exemplaartheorie* voor: je slaat geen abstract middelpunt op, maar herinneringen aan alle voorbeelden die je ooit zag. Een nieuw ding vergelijk je met al die voorbeelden. Leuvense onderzoekers rond Gert Storms vergeleken beide modellen voor Nederlandse categorieën; het beeld is dat allebei iets verklaren. Het debat loopt nog.',
            quiz: {
              q: 'Wat slaat je geheugen op volgens de exemplaartheorie?',
              options: ['Herinneringen aan losse voorbeelden', 'Eén abstract middelpunt', 'Een lijst noodzakelijke kenmerken'],
              answer: 'Herinneringen aan losse voorbeelden',
              why: 'Je vergelijkt een nieuw geval met alle voorbeelden die je kent, niet met één gemiddelde.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'leugen',
        prompt: 'Hoeveel van de drie leugenelementen heeft dit geval?',
        buckets: ['alle drie', 'twee van de drie', 'één van de drie'],
        items: [
          { t: 'Je zegt bewust iets onwaars om je baas te misleiden.', b: 0 },
          { t: 'Je meldt je ziek terwijl je gezond bent, om vrij te hebben.', b: 0 },
          { t: 'Je wilt misleiden met iets wat je onwaar vindt, maar het blijkt waar.', b: 1 },
          { t: 'Een acteur zegt op het toneel: Ik ben de koning.', b: 1 },
          { t: 'Je overdrijft in een grap en iedereen weet het.', b: 1 },
          { t: 'Je noemt per ongeluk het verkeerde tijdstip.', b: 2 },
          { t: 'Je zegt iets wat waar is, om iemand op het verkeerde spoor te zetten.', b: 2 },
          { t: 'Je geeft een fout antwoord dat je zelf gelooft.', b: 2 },
        ],
        why: 'Onwaar, zelf onwaar vinden, en willen misleiden. Hoe minder elementen, hoe verder het geval van de prototypische leugen staat.',
      },
      {
        kind: 'choice',
        id: 'element',
        prompt: 'Welk element woog bij Coleman en Kay het zwaarst?',
        before: '',
        after: '',
        options: ['Je denkt zelf dat het onwaar is', 'Het is echt onwaar', 'Je wilt misleiden'],
        answer: 'Je denkt zelf dat het onwaar is',
        why: 'Wie iets zegt wat hij zelf onwaar vindt, liegt in de ogen van de meeste mensen, ook als het toevallig waar blijkt.',
      },
      {
        kind: 'bet',
        id: 'oneven',
        prompt: 'Mensen vinden 3 een beter oneven getal dan 447. Wat volgt daaruit?',
        options: ['Typicaliteit bewijst niet dat een categorie vaag is', 'Oneven getal heeft een vage rand', '447 is eigenlijk even'],
        answer: 'Typicaliteit bewijst niet dat een categorie vaag is',
        why: 'Dat was het punt van Armstrong, Gleitman en Gleitman (1983).',
      },
      {
        kind: 'choice',
        id: 'vleermuis',
        prompt: 'Kies de hedge die past.',
        before: 'Een vleermuis is',
        after: 'een zoogdier, ook al vliegt hij.',
        options: ['technisch gezien', 'typisch', 'een prototypisch'],
        answer: 'technisch gezien',
        why: 'Een vleermuis staat aan de rand van zoogdier: volgens de definitie wel, gevoelsmatig niet.',
      },
      {
        kind: 'bet',
        id: 'balan',
        prompt: 'Waarom zitten vrouwen, vuur en gevaarlijke dingen in het Dyirbal in één klasse?',
        options: ['Via een keten van verbanden, niet via één gedeeld kenmerk', 'Omdat ze allemaal heet zijn', 'Toeval: de klasse heeft geen betekenis'],
        answer: 'Via een keten van verbanden, niet via één gedeeld kenmerk',
        why: 'Een radiale categorie: een centrum met uitlopers die elk met een buur verbonden zijn.',
      },
      {
        kind: 'chat',
        id: 'hedges',
        prompt: 'Help je vriendin met haar biologieverslag',
        intro: 'Kies telkens de hedge die past bij waar het dier in de categorie staat.',
        contact: { name: 'Noor', role: 'studeert biologie', initials: 'N' },
        rounds: [
          {
            say: 'Ik schrijf over walvissen. Hoe begin ik de zin over zoogdieren?',
            options: ['Strikt genomen is een walvis een zoogdier.', 'Een walvis is een echt zoogdier.'],
            right: 0,
            fix: 'een echt zoogdier → strikt genomen',
            why: 'Een walvis lijkt op een vis en staat aan de rand van zoogdier.',
          },
          {
            say: 'En een hond als voorbeeld van een zoogdier?',
            options: ['Een hond is technisch gezien een zoogdier.', 'Een hond is een typisch zoogdier.'],
            right: 1,
            fix: 'technisch gezien → typisch',
            why: 'Een hond staat in het midden. Technisch gezien zou suggereren dat hij aan de rand staat.',
          },
          {
            say: 'Laatste: de struisvogel.',
            options: ['Een struisvogel is een vogel, al kan hij niet vliegen.', 'Een struisvogel is de ideale vogel.'],
            right: 0,
            fix: 'de ideale vogel → een vogel, al kan hij niet vliegen',
            why: 'Een struisvogel mist een typisch kenmerk. Al kan hij niet vliegen markeert de rand.',
          },
        ],
        bye: 'Top, dank je! Mijn docent houdt van precieze hedges.',
      },
    ],
  },
  {
    id: 'w18',
    stage: 'master',
    domain: 'sem',
    also: ['prag', 'syn'],
    title: 'Woorden met vaste buren',
    skill: 'Woorden',
    icon: '∞',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Collocaties, idioom en frames',
        panels: [
          {
            text: 'Koffie is *sterk*, regen is *hevig*, een roker is *zwaar*. Logica heeft er niets mee te maken: het zijn *collocaties*, vaste buren. Je *neemt* een besluit, je *stelt* een vraag, je *houdt* rekening. Igor Mel’čuk beschreef ze als *lexicale functies*: dezelfde betekenis (‘doen’, ‘heel erg’) krijgt per woord een andere vorm.',
            paradigm: {
              q: 'Welk werkwoord hoort erbij?',
              cols: ['werkwoord'],
              rows: [
                { label: 'een besluit', cells: [{ fill: 'nemen', hint: 'Een besluit maak je niet in het Nederlands: je neemt het.' }] },
                { label: 'een vraag', cells: [{ fill: 'stellen', hint: 'Een vraag stel je.' }] },
                { label: 'een fout', cells: [{ fill: 'maken', hint: 'Een fout maak je.' }] },
                { label: 'aandacht', cells: [{ fill: 'besteden', hint: 'Aandacht besteed je (aan iets).' }] },
                { label: 'een belofte', cells: [{ fill: 'doen', hint: 'Een belofte doe je.' }] },
              ],
              extra: ['zetten'],
              note: 'Oper(besluit) = nemen, Oper(vraag) = stellen: één functie, vijf vormen. Die leer je per woord.',
            },
          },
          {
            text: 'Een stap verder: het *idioom*. *De pijp uit gaan* betekent doodgaan, maar geen enkel stuk betekent iets daarvan. *Het ijs breken* is anders: *ijs* staat voor de spanning, *breken* voor doorbreken. Zulke idiomen kun je ombouwen: *Het ijs was snel gebroken.* Met *de pijp* lukt dat niet. Nunberg, Sag en Wasow (1994) maakten van dat verschil een theorie.',
            rule: 'Heeft elk stuk van een idioom een eigen betekenis, dan kun je het ombouwen. Anders is het één blok.',
            quiz: {
              q: 'Welke zin behoudt de idiomatische betekenis?',
              options: ['De knoop werd eindelijk doorgehakt.', 'De pijp werd uitgegaan.', 'De lamp werd tegen gelopen.'],
              answer: 'De knoop werd eindelijk doorgehakt.',
              why: 'Knoop staat voor het probleem, dus het idioom kan in de lijdende vorm. Pijp en lamp betekenen los niets.',
            },
          },
          {
            text: 'Woorden roepen een hele scène op. Charles Fillmore noemde dat een *frame*. Het koopframe heeft een koper, een verkoper, een goed en een prijs. *Kopen* zet de koper voorop, *verkopen* de verkoper, *kosten* het goed en de prijs. Wie een werkwoord kiest, kiest een perspectief.',
            lab: {
              label: 'Tik een werkwoord uit het koopframe',
              chips: [
                { k: 'kopen', out: 'Anna koopt een fiets van Piet.', note: 'De koper staat voorop.' },
                { k: 'verkopen', out: 'Piet verkoopt Anna een fiets.', note: 'De verkoper staat voorop.' },
                { k: 'kosten', out: 'De fiets kost honderd euro.', note: 'Het goed en de prijs staan voorop.' },
              ],
            },
            show: [{ right: 'Het bedrijf ontsloeg tweehonderd mensen. (wie deed het)' }, { right: 'Er gingen tweehonderd banen verloren. (niemand deed het)' }],
            deep: {
              q: 'Waarom is dat belangrijk voor een schrijver?',
              a: 'Omdat elk frame deelnemers kan verstoppen. *Er gingen banen verloren* noemt geen dader. *Fouten zijn gemaakt* ook niet. Journalisten en politici gebruiken dat bewust. Wie precies schrijft, kiest het werkwoord dat de deelnemers zichtbaar maakt die de lezer moet kennen.',
            },
          },
        ],
      },
      {
        kind: 'swipe',
        id: 'collocatie',
        prompt: 'Klopt deze combinatie?',
        cards: [
          { t: 'Ik maak morgen een besluit.', ok: false, fix: 'Ik neem morgen een besluit.', why: 'Een besluit neem je. Maken is een anglicisme (make a decision).' },
          { t: 'Hij is een zware roker.', ok: true, why: 'Zwaar is de vaste versterker bij roker.' },
          { t: 'We moeten met de kosten rekening maken.', ok: false, fix: 'We moeten met de kosten rekening houden.', why: 'Rekening houden met.' },
          { t: 'Ze stelde een lastige vraag.', ok: true, why: 'Een vraag stel je.' },
          { t: 'Ik wil een foto nemen van de taart.', ok: false, fix: 'Ik wil een foto maken van de taart.', why: 'Een foto maak je. Nemen is een anglicisme (take a photo).' },
          { t: 'Het regende hevig de hele nacht.', ok: true, why: 'Hevig is de vaste versterker bij regen.' },
        ],
      },
      {
        kind: 'sort',
        id: 'idioom',
        prompt: 'Hebben de stukken een eigen betekenis?',
        buckets: ['ja: stukken betekenen iets', 'nee: alleen het geheel'],
        items: [
          { t: 'het ijs breken', b: 0 },
          { t: 'de knoop doorhakken', b: 0 },
          { t: 'open kaart spelen', b: 0 },
          { t: 'de pijp uit gaan', b: 1 },
          { t: 'het roer omgooien', b: 0 },
          { t: 'tegen de lamp lopen', b: 1 },
          { t: 'de kat uit de boom kijken', b: 1 },
          { t: 'met de deur in huis vallen', b: 1 },
          { t: 'boter op je hoofd hebben', b: 1 },
        ],
        why: 'Knoop = probleem, kaart = informatie, roer = koers. Maar pijp, lamp, kat, deur en boter staan nergens voor.',
      },
      {
        kind: 'fix',
        id: 'stellen',
        prompt: 'Tik het foute woord aan en verbeter het.',
        sentence: 'Ik wil graag een vraag maken over de factuur.',
        wrong: 5,
        answer: 'stellen',
        why: 'Een vraag stel je.',
      },
      {
        kind: 'bet',
        id: 'kosten',
        prompt: 'Welk werkwoord uit het koopframe laat de koper en de verkoper weg?',
        options: ['kosten', 'kopen', 'verkopen'],
        answer: 'kosten',
        why: 'Het boek kost tien euro: alleen het goed en de prijs.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Meten, constructies en frames die denken sturen',
        panels: [
          {
            text: '‘You shall know a word by the company it keeps’, schreef J.R. Firth (1957). Maar hoe meet je dat gezelschap? Kenneth Church en Patrick Hanks (1990) gebruikten *pointwise mutual information* (PMI). Je vergelijkt hoe vaak twee woorden samen voorkomen met hoe vaak dat bij toeval zou gebeuren. Komen *sterke* en *koffie* honderd keer vaker samen voor dan toeval voorspelt, dan zijn ze een collocatie. Zo vinden woordenboekmakers collocaties in miljoenen woorden tekst.',
            rule: 'PMI = log₂ (waargenomen samen ÷ verwacht bij toeval). Hoe hoger, hoe vaster de buren.',
            quiz: {
              q: 'Verwacht bij toeval: 2 keer samen. Waargenomen: 16 keer. Hoeveel keer vaker dan toeval?',
              options: ['8', '14', '32'],
              answer: '8',
              why: '16 gedeeld door 2 = 8. De PMI is dan log₂ 8 = 3.',
            },
          },
          {
            text: 'Soms is het vaste stuk groter dan een woord, maar met open plekken. Adele Goldberg (1995) noemde zulke vorm-betekenisparen *constructies*. *Zich suf piekeren*, *zich een ongeluk lachen*, *zich een weg banen*. *Piekeren* heeft geen lijdend voorwerp: *Ik piekerde mezelf* kan niet. Maar *Ik piekerde me suf* wel. De constructie voegt zelf een argument toe (zie valentie, w15). Charles Fillmore, Paul Kay en Catherine O’Connor (1988) beschreven zo al de Engelse constructie *let alone*, ons *laat staan*.',
            rule: 'Een constructie kan argumenten toevoegen die het werkwoord zelf niet heeft.',
            swap: {
              goal: 'Bouw de constructie: zich [iets] [werkwoord]',
              blocks: ['lachte', 'Ze', 'een ongeluk', 'zich'],
              accept: ['Ze lachte zich een ongeluk'],
              note: 'Lachen heeft zelf geen lijdend voorwerp. Zich een ongeluk komt van de constructie.',
            },
          },
          {
            text: 'Frames sturen hoe we denken. Elizabeth Loftus en John Palmer (1974) lieten een filmpje van een botsing zien. Wie vroeg hoe hard de auto’s gingen toen ze elkaar *smashed* (verpletterden), kreeg hogere schattingen dan wie *hit* (raakten) gebruikte. Een week later zei de *smashed*-groep vaker dat ze gebroken glas had gezien, terwijl dat er niet was. Paul Thibodeau en Lera Boroditsky (2011) beschreven misdaad als een *beest* of als een *virus*. Bij *beest* kozen lezers vaker voor harder straffen, bij *virus* vaker voor de oorzaken aanpakken.',
            lab: {
              label: 'Tik een frame',
              chips: [
                { k: 'smashed', out: 'hogere snelheid, vaker gebroken glas', note: 'Eén werkwoord veranderde de herinnering.' },
                { k: 'hit', out: 'lagere snelheid', note: 'Hetzelfde filmpje, een ander woord.' },
                { k: 'misdaad is een beest', out: 'jagen, opsluiten', note: 'Het frame van een roofdier roept om bestrijding.' },
                { k: 'misdaad is een virus', out: 'oorzaken, preventie', note: 'Het frame van een ziekte roept om behandeling.' },
              ],
            },
          },
          {
            text: 'Collocaties zitten in alle hoeken van het lexicon, en Mel’čuk gaf ze namen. *Oper* is het lege werkwoord (een besluit *nemen*). *Magn* is de versterker: zwaar, hevig, diep. Die versterker verschilt per woord, en je moet hem per woord leren. Voor wie Nederlands als tweede taal leert, is dit een van de moeilijkste stukken: elk woord is goed, maar de combinatie klinkt vreemd.',
            paradigm: {
              q: 'Kies de versterker (Magn)',
              cols: ['Magn'],
              rows: [
                { label: 'een … roker', cells: ['zware'] },
                { label: '… regen', cells: [{ fill: 'hevige', hint: 'Regen is hevig.' }] },
                { label: 'een … slaap', cells: [{ fill: 'diepe', hint: 'Slaap is diep.' }] },
                { label: '… vrienden', cells: [{ fill: 'dikke', hint: 'Goede vrienden zijn dikke vrienden.' }] },
                { label: '… dank', cells: [{ fill: 'hartelijk', hint: 'Hartelijk dank.' }] },
              ],
              extra: ['sterke', 'harde'],
              note: 'Eén functie, Magn, met per woord een andere vorm.',
            },
          },
        ],
      },
      {
        kind: 'type',
        id: 'pmi',
        prompt: 'Reken het uit.',
        before: 'Bij toeval verwacht je sterke en koffie 0,5 keer samen. Ze staan 50 keer samen. Dat is',
        after: 'keer vaker dan toeval.',
        hint: 'getal',
        answer: '100',
        why: '50 gedeeld door 0,5 = 100. De PMI is log₂ 100, ongeveer 6,6: een sterke collocatie.',
      },
      {
        kind: 'choice',
        id: 'ongeluk',
        prompt: 'Kies de vaste constructie.',
        before: 'Hij lachte',
        after: 'toen hij het filmpje zag.',
        options: ['zich een ongeluk', 'een ongeluk', 'zich ongelukkig'],
        answer: 'zich een ongeluk',
        why: 'De constructie zich + resultaat + werkwoord: zich een ongeluk lachen, zich suf piekeren.',
      },
      {
        kind: 'rewrite',
        id: 'dader',
        prompt: 'Maak de dader zichtbaar: de minister. Houd de voltooide tijd.',
        source: 'Er zijn fouten gemaakt.',
        accept: ['De minister heeft fouten gemaakt.'],
        why: 'Het passief zonder door-bepaling verstopt de dader. Met de minister als onderwerp weet de lezer wie verantwoordelijk is.',
      },
      {
        kind: 'bet',
        id: 'loftus',
        prompt: 'Wat gebeurde er bij Loftus en Palmer met de groep die smashed hoorde?',
        options: ['Ze schatten de snelheid hoger en herinnerden zich vaker gebroken glas', 'Ze onthielden het filmpje beter', 'Er was geen verschil met hit'],
        answer: 'Ze schatten de snelheid hoger en herinnerden zich vaker gebroken glas',
        why: 'Eén werkwoord riep een ander frame op en veranderde zelfs de herinnering.',
      },
      {
        kind: 'proofread',
        id: 'anglicismen',
        prompt: 'Lees de tekst na',
        intro: 'Er zitten drie foute collocaties in. Tik ze aan.',
        tokens: [
          { t: 'Mag' },
          { t: 'ik' },
          { t: 'een' },
          { t: 'vraag' },
          { t: 'maken?', fix: 'stellen?', why: 'Een vraag stel je.' },
          { t: 'Op' },
          { t: 'het' },
          { t: 'feest' },
          { t: 'wilde' },
          { t: 'ik' },
          { t: 'een' },
          { t: 'foto' },
          { t: 'nemen', fix: 'maken', why: 'Een foto maak je. Nemen komt uit het Engels (take a photo).' },
          { t: 'van' },
          { t: 'de' },
          { t: 'taart,' },
          { t: 'maar' },
          { t: 'ik' },
          { t: 'had' },
          { t: 'geen' },
          { t: 'rekening' },
          { t: 'gemaakt', fix: 'gehouden', why: 'Rekening houden met.' },
          { t: 'met' },
          { t: 'de' },
          { t: 'lege' },
          { t: 'batterij.' },
        ],
        done: { title: 'Alle drie gevonden', text: 'Stellen, maken, gehouden: elk woord apart was Nederlands, maar de combinatie niet.' },
      },
    ],
  },
  {
    id: 'w19',
    stage: 'master',
    domain: 'sem',
    also: ['tekst'],
    title: 'Woorden tellen met Zipf',
    skill: 'Woorden',
    icon: 'Σ',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Frequentie, dekking en dichtheid',
        panels: [
          {
            text: 'Het vaakst gebruikte woord van geschreven Nederlands is *de*. Spannend is anders, maar het verklaart veel. George Kingsley Zipf (1935) zag dat frequentie maal rang ongeveer gelijk blijft: het tweede woord komt ongeveer half zo vaak voor als het eerste, het tiende een tiende zo vaak. Dat heet de *wet van Zipf*.',
            rule: 'Frequentie × rang ≈ constant.',
            show: [{ right: 'rang 1: 60.000 keer · rang 2: ±30.000 · rang 3: ±20.000 · rang 10: ±6.000' }],
            quiz: {
              q: 'Woord 1 komt 60.000 keer voor. Hoe vaak verwacht Zipf woord 6?',
              options: ['ongeveer 10.000 keer', 'ongeveer 54.000 keer', 'ongeveer 6.000 keer'],
              answer: 'ongeveer 10.000 keer',
              why: '60.000 gedeeld door 6 = 10.000. Frequentie maal rang blijft ongeveer gelijk.',
            },
          },
          {
            text: 'Gevolg: een paar honderd woorden maken het grootste deel van elke tekst, en de rest is een lange staart van zeldzame woorden. Ongeveer de helft van alle verschillende woorden in een groot corpus komt maar één keer voor: de *hapaxen* uit Het betekenisvolle woorddeel (d15). Voor lezen zonder woordenboek moet je volgens Paul Nation (2006) zo’n 98 procent van de woorden kennen; voor een roman zijn dat in het Engels 8.000 à 9.000 woordfamilies.',
            quiz: {
              q: 'Welk deel van de verschillende woorden in een groot corpus komt maar één keer voor?',
              options: ['ongeveer de helft', 'ongeveer een procent', 'bijna alle'],
              answer: 'ongeveer de helft',
              why: 'Die hapaxen vormen de lange staart van de verdeling.',
            },
            deep: {
              q: 'Wat betekent dat voor mij als leerder?',
              a: 'Dat de eerste duizend woorden je snel heel ver brengen, en dat elke duizend erna minder dekking opleveren. Vanaf een paar duizend woorden leer je nieuwe woorden het best door *veel te lezen*: zeldzame woorden kom je alleen in grote hoeveelheden tekst vaak genoeg tegen. Zo verklaart Zipf waarom lezen de beste woordenschatles is.',
            },
          },
          {
            text: 'Zipf zag nog iets: vaak gebruikte woorden zijn kort. *De*, *en*, *ik*, *is*. En wat vaak gebruikt gaat worden, wordt kort: *televisie* werd *tv*, *laboratorium* werd *lab*. De meeste korte, frequente woorden zijn *functiewoorden*. De *inhoudswoorden* (zelfstandige naamwoorden, werkwoorden, bijvoeglijke naamwoorden, bijwoorden) dragen de informatie. Hun aandeel heet de *lexicale dichtheid*.',
            mark: { q: 'Tik de inhoudswoorden', sentence: 'De kat van de buren ligt op het dak.', targets: [1, 4, 5, 8], note: 'kat, buren, ligt, dak: vier van de negen. Lexicale dichtheid: ongeveer 44 procent.' },
            rule: 'Lexicale dichtheid = inhoudswoorden gedeeld door alle woorden.',
          },
        ],
      },
      {
        kind: 'type',
        id: 'zipf',
        prompt: 'Woord 1 komt 60.000 keer voor. Hoe vaak verwacht Zipf woord 4?',
        before: 'Ongeveer',
        after: 'duizend keer.',
        hint: 'getal',
        answer: '15',
        why: '60.000 gedeeld door 4 = 15.000.',
      },
      {
        kind: 'sort',
        id: 'functie',
        prompt: 'Inhoudswoord of functiewoord?',
        buckets: ['inhoudswoord', 'functiewoord'],
        items: [
          { t: 'tafel', b: 0 },
          { t: 'de', b: 1 },
          { t: 'lopen', b: 0 },
          { t: 'omdat', b: 1 },
          { t: 'groen', b: 0 },
          { t: 'van', b: 1 },
          { t: 'hij', b: 1 },
          { t: 'snel', b: 0 },
          { t: 'ondanks', b: 1 },
        ],
        why: 'Inhoudswoorden komen uit de open klassen (zie w8). Functiewoorden uit de gesloten klassen.',
      },
      {
        kind: 'type',
        id: 'dichtheid',
        prompt: 'Reken de lexicale dichtheid uit.',
        before: 'Een tekst van 200 woorden heeft 90 inhoudswoorden. Dichtheid:',
        after: 'procent.',
        hint: 'getal',
        answer: '45',
        why: '90 gedeeld door 200 = 0,45. Een vakartikel zit vaak boven de 50 procent, een gesprek ver eronder.',
      },
      {
        kind: 'bet',
        id: 'kort',
        prompt: 'Waarom zijn de vaakst gebruikte woorden kort?',
        options: ['Wat vaak moet, wordt kort: dat spaart moeite', 'Toeval', 'Korte woorden zijn altijd ouder'],
        answer: 'Wat vaak moet, wordt kort: dat spaart moeite',
        why: 'Zipf noemde dit het principe van de minste moeite. Je ziet het live gebeuren: televisie → tv.',
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Een betere maat, een aap en een debat',
        panels: [
          {
            text: 'Frequenties per miljoen zijn lastig te vergelijken: 0,02 of 20.000? Walter van Heuven, Paweł Mandera, Emmanuel Keuleers en Marc Brysbaert (2014) stelden de *Zipf-schaal* voor: de logaritme (grondtal 10) van de frequentie per miljard woorden. Eén keer per miljoen woorden is dan Zipf 3, honderd keer per miljoen is Zipf 5. De schaal loopt ruwweg van 1 tot 7. Welke telling je gebruikt, maakt ook uit: SUBTLEX-NL (Keuleers, Brysbaert en New 2010), geteld in ondertitels van films en series, voorspelt hoe snel mensen woorden herkennen beter dan tellingen uit boeken.',
            rule: 'Zipf-waarde = log₁₀ (frequentie per miljard woorden) = log₁₀ (per miljoen) + 3.',
            quiz: {
              q: 'Een woord komt 100 keer per miljoen woorden voor. Zipf-waarde?',
              options: ['5', '2', '100'],
              answer: '5',
              why: '100 per miljoen is 100.000 per miljard. Log₁₀ 100.000 = 5.',
            },
          },
          {
            text: 'Is de wet van Zipf diep, of een rekentruc? George Miller (1957) liet zien dat een aap die willekeurig op een typemachine met een spatiebalk tikt, ook ‘woorden’ maakt die ongeveer Zipf volgen: korte letterreeksen ontstaan vanzelf vaker. Benoît Mandelbrot had de formule al eerder verfijnd. Steven Piantadosi (2014) zette het debat op een rij: het patroon is robuust, maar het is nog niet duidelijk wélke verklaring klopt. Dat een patroon overal opduikt, bewijst dus nog niet dat er één diepe oorzaak achter zit.',
            quiz: {
              q: 'Wat liet Miller (1957) zien met willekeurig getikte tekst?',
              options: ['Ook toeval geeft een Zipf-achtige verdeling', 'Apen leren woorden van mensen', 'Zipf geldt alleen voor het Engels'],
              answer: 'Ook toeval geeft een Zipf-achtige verdeling',
              why: 'Daarom is de wet alleen niet genoeg bewijs voor een diep principe in taal.',
            },
          },
          {
            text: 'Hoe rijk is de woordenschat van een tekst? De eenvoudigste maat is de *type-tokenverhouding*: types gedeeld door tokens. Maar die daalt altijd als een tekst langer wordt, want nieuwe woorden komen steeds trager: dat heet de *wet van Heaps*. Een tekst van 100 woorden en een van 10.000 vergelijk je dus niet met deze maat. Philip McCarthy en Scott Jarvis (2010) ontwikkelden maten zoals *MTLD* die minder van de lengte afhangen.',
            rule: 'Type-tokenverhouding daalt met de lengte. Vergelijk alleen even lange teksten, of gebruik een gecorrigeerde maat.',
            quiz: {
              q: 'Tekst A (100 tokens) heeft 70 types, tekst B (5000 tokens) 1500. Mag je concluderen dat A rijker is?',
              options: ['Nee, de verhouding daalt vanzelf met de lengte', 'Ja, 70 procent is meer dan 30 procent'],
              answer: 'Nee, de verhouding daalt vanzelf met de lengte',
              why: 'Elke lange tekst herhaalt meer woorden. De maat is alleen eerlijk bij gelijke lengte.',
            },
          },
          {
            text: 'Zipf zei: vaak gebruikte woorden zijn kort. Steven Piantadosi, Harry Tily en Edward Gibson (2011) verfijnden dat. In elf talen voorspelde de *voorspelbaarheid* van een woord in zijn context de lengte beter dan de frequentie alleen. Woorden die je vaak al ziet aankomen, mogen kort zijn; woorden die veel nieuwe informatie dragen, worden langer. Taal lijkt zo ingericht dat informatie gelijkmatig over de tijd wordt verdeeld.',
            mark: { q: 'Tik de korte, voorspelbare functiewoorden', sentence: 'Ik zag de hond in de tuin.', targets: [0, 2, 4, 5], note: 'Ik, de, in, de: kort en goed te voorspellen. Zag, hond en tuin dragen de nieuwe informatie.' },
          },
        ],
      },
      {
        kind: 'type',
        id: 'zipfwaarde',
        prompt: 'Reken de Zipf-waarde uit.',
        before: 'Een woord komt 10 keer per miljoen woorden voor. Zipf-waarde:',
        after: '',
        hint: 'getal',
        answer: '4',
        why: '10 per miljoen = 10.000 per miljard. Log₁₀ 10.000 = 4. Vanaf ongeveer 4 heet een woord frequent.',
      },
      {
        kind: 'type',
        id: 'ttr',
        prompt: 'Reken de type-tokenverhouding uit als percentage.',
        before: 'Een tekst van 400 tokens heeft 160 types. Verhouding:',
        after: 'procent.',
        hint: 'getal',
        answer: '40',
        why: '160 gedeeld door 400 = 0,4, dus 40 procent. Vergelijk dit alleen met teksten van ongeveer 400 woorden.',
      },
      {
        kind: 'order',
        id: 'rang',
        prompt: 'Zet de woorden van frequent naar zeldzaam.',
        tiles: ['kwispelen', 'de', 'ondanks', 'huis'],
        answer: 'de huis ondanks kwispelen',
        why: 'De is een functiewoord bovenaan de lijst, huis een vaak gebruikt inhoudswoord, ondanks een minder vaak gebruikt functiewoord, kwispelen staat ver in de staart.',
      },
      {
        kind: 'bet',
        id: 'aap',
        prompt: 'Willekeurig getikte tekst volgt ook ongeveer Zipf. Wat volgt daaruit?',
        options: ['Het patroon alleen bewijst nog geen diepe oorzaak in taal', 'Apen spreken een taal', 'De wet van Zipf klopt niet'],
        answer: 'Het patroon alleen bewijst nog geen diepe oorzaak in taal',
        why: 'Miller (1957) liet dat zien. De wet klopt wel, maar de verklaring is nog onderwerp van debat.',
      },
      {
        kind: 'choice',
        id: 'lengte',
        prompt: 'Kies de beste voorspeller.',
        before: 'Volgens Piantadosi en collega’s voorspelt',
        after: 'de lengte van een woord het best.',
        options: ['de voorspelbaarheid in context', 'de frequentie alleen', 'de leeftijd van het woord'],
        answer: 'de voorspelbaarheid in context',
        why: 'In elf talen deed voorspelbaarheid het beter dan frequentie alleen.',
      },
      {
        kind: 'swipe',
        id: 'tellen',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Zipf 3 betekent ongeveer één keer per miljoen woorden.', ok: true, why: 'Eén per miljoen = 1000 per miljard, log₁₀ = 3.' },
          { t: 'Tellingen uit ondertitels voorspellen woordherkenning slechter dan boeken.', ok: false, fix: 'Ze voorspellen het beter', why: 'Dat bleek bij SUBTLEX-NL.' },
          { t: 'De type-tokenverhouding blijft gelijk als een tekst langer wordt.', ok: false, fix: 'Ze daalt met de lengte', why: 'De wet van Heaps: nieuwe woorden komen steeds trager.' },
          { t: 'Willekeurige tekst kan een Zipf-achtige verdeling geven.', ok: true, why: 'Miller (1957).' },
          { t: 'Ongeveer de helft van de types in een groot corpus komt maar één keer voor.', ok: true, why: 'De hapaxen: de lange staart van Zipf.' },
          { t: 'Woordlengte hangt alleen af van frequentie.', ok: false, fix: 'Voorspelbaarheid in context speelt ook mee', why: 'Piantadosi, Tily en Gibson (2011).' },
        ],
      },
    ],
  },
  {
    id: 'w20',
    stage: 'master',
    domain: 'morf',
    also: ['syn', 'orth'],
    title: 'Waar houdt het woord op?',
    skill: 'Spelling',
    icon: '|',
    steps: [
      {
        kind: 'explain',
        id: 'uitleg',
        title: 'Partikelwerkwoorden en klitieken',
        panels: [
          {
            text: '*Opbellen* is één woord. Tot je zegt: *Ik bel je morgen op.* Dan ligt het in twee stukken over de zin verspreid. In het deelwoord kruipt *ge-* ertussen: *opgebeld*. Bij *te* ook: *op te bellen*. Is het nu een woord of een woordgroep? Geert Booij (2010) zegt: allebei. Het is een *constructie*: een vaste eenheid in je hoofd, die de zin toch uit elkaar mag halen.',
            lab: {
              label: 'Tik een vorm',
              chips: [
                { k: 'ik bel op', out: 'hoofdzin: twee stukken', note: 'De persoonsvorm gaat naar plek 2, het partikel blijft achter.' },
                { k: 'omdat ik opbel', out: 'bijzin: één stuk', note: 'Alles achteraan, dus weer aan elkaar.' },
                { k: 'opgebeld', out: 'ge- ertussen', note: 'Het partikel staat buiten het werkwoord.' },
                { k: 'op te bellen', out: 'te ertussen', note: 'Drie woorden, één lexeem.' },
              ],
            },
          },
          {
            text: 'De klemtoon beslist of een werkwoord scheidbaar is. *Vóórkomen* (gebeuren) is scheidbaar: *Dat komt vaak voor.* *Voorkómen* (tegenhouden) niet: *Dat voorkomt problemen.* Het scheidbare krijgt *ge-*, het onscheidbare niet. Dit kwam al kort langs bij De lettergreep; hier zie je het hele paradigma.',
            paradigm: {
              q: 'Scheidbaar of niet?',
              cols: ['hij … (nu)', 'voltooid deelwoord'],
              rows: [
                { label: 'opbellen', cells: [{ fill: 'belt op', hint: 'Scheidbaar: het partikel blijft achter.' }, { fill: 'opgebeld', hint: 'ge- tussen partikel en stam.' }] },
                { label: 'vóórkomen', cells: [{ fill: 'komt voor', hint: 'Klemtoon op voor: scheidbaar.' }, { fill: 'voorgekomen', hint: 'Scheidbaar: ge- ertussen.' }] },
                { label: 'voorkómen', cells: [{ fill: 'voorkomt', hint: 'Klemtoon op komen: onscheidbaar, één stuk.' }, { fill: 'voorkomen', hint: 'Onscheidbaar: geen ge-, net als bij vertellen.' }] },
              ],
              extra: ['geopbeld', 'gevoorkomen'],
              note: 'Klemtoon op het partikel: scheidbaar, met ge- ertussen. Klemtoon op de stam: één woord, zonder ge-.',
            },
          },
          {
            text: 'Het omgekeerde geval: *klitieken*. In *Heeft ie ’t gezien?* zijn *ie* en *’t* grammaticaal gewoon woorden (onderwerp en lijdend voorwerp), maar ze hebben geen eigen klemtoon. Ze leunen op hun buur. Zo komen we terug bij les w7: schriftwoord, klankwoord, grammaticaal woord en lexeem vallen meestal samen, en de interessantste taalkunde zit waar ze uit elkaar gaan.',
            rule: 'Het woord is geen ding maar een kruispunt van spelling, klank, zinsbouw en geheugen.',
            mark: { q: 'Tik de klitieken', sentence: 'Heeft ie ’t boek al?', targets: [1, 2], note: 'ie (hij) en ’t (het): grammaticaal woorden, maar klanklijk aangeplakt. In verzorgde tekst schrijf je hij en het.' },
          },
        ],
      },
      {
        kind: 'type',
        id: 'opbellen',
        prompt: 'Vul opbellen in met te.',
        before: 'Vergeet niet je moeder',
        after: '.',
        hint: '… te …',
        answer: 'op te bellen',
        why: 'Scheidbaar: te komt tussen partikel en stam.',
      },
      {
        kind: 'choice',
        id: 'voorkomen',
        prompt: 'Kies de goede vorm.',
        before: 'Dankzij de dijk hebben ze een overstroming',
        after: '.',
        options: ['voorkomen', 'voorgekomen'],
        answer: 'voorkomen',
        why: 'Tegenhouden is voorkómen: onscheidbaar, dus geen ge-.',
      },
      {
        kind: 'swipe',
        id: 'grens',
        prompt: 'Klopt deze zin?',
        cards: [
          { t: 'Bij een scheidbaar werkwoord komt ge- vóór het partikel.', ok: false, fix: 'ge- komt tussen partikel en stam: opgebeld', why: 'Het partikel staat buiten het werkwoord.' },
          { t: 'Klitieken hebben geen eigen klemtoon.', ok: true, why: 'Ze leunen op hun buur: heeft ie.' },
          { t: 'Vóórkomen en voorkómen verschillen alleen in klemtoon en buiging.', ok: true, why: 'En daardoor ook in betekenis: gebeuren tegenover tegenhouden.' },
          { t: 'In een bijzin staat een partikelwerkwoord altijd in één stuk.', ok: false, fix: 'Ook: dat ik je op wil bellen', why: 'Het partikel kan vóór het hele werkwoordcluster staan.' },
          { t: 'In ‘de buurman z’n auto’ hoort z’n bij de hele groep de buurman.', ok: true, why: 'Een klitiek hecht zich aan een woordgroep, niet aan één woord.' },
          { t: 'Stofzuigen vervoeg je als een scheidbaar werkwoord: ik zuig stof.', ok: false, fix: 'ik stofzuig, gestofzuigd', why: 'Stofzuigen is één onscheidbaar werkwoord geworden.' },
        ],
      },
      {
        kind: 'explain',
        id: 'verdieping',
        title: 'Klitiek of affix, en woorden die half verzinken',
        panels: [
          {
            text: 'Hoe weet je of iets een klitiek of een affix is? Arnold Zwicky en Geoffrey Pullum (1983) gaven toetsen. Een affix is kieskeurig: het hangt alleen aan een bepaalde woordsoort. Een klitiek hangt aan bijna alles. Een affix heeft gaten en grillige vormen; een klitiek is regelmatig. Hun bekendste conclusie: het Engelse *n’t* is geen klitiek maar een affix, want het heeft grillige vormen (*won’t*, niet *willn’t*) en gaten (geen *amn’t*). Het Nederlandse *’t* hangt aan alles: *heb ’t*, *dat ’t*, *met ’t*. Dus: klitiek.',
            rule: 'Klitiek: hangt aan bijna alles en is regelmatig. Affix: kieskeurig, met gaten en uitzonderingen.',
            lab: {
              label: 'Tik een vorm',
              chips: [
                { k: '’t', out: 'klitiek', note: 'Heb ’t, dat ’t, met ’t: na een werkwoord, voegwoord of voorzetsel.' },
                { k: '-te (werkte)', out: 'affix', note: 'Alleen achter een werkwoordsstam.' },
                { k: 'n’t', out: 'affix (Engels)', note: 'Won’t en het ontbrekende amn’t: grillig, dus een affix.' },
                { k: 'z’n', out: 'klitiek', note: 'De buurman z’n auto: hangt aan een hele woordgroep.' },
              ],
            },
          },
          {
            text: 'Kijk naar *de buurman z’n auto*. Het bezittelijk *z’n* hoort bij de hele groep, ook als die lang is: *de man van de bakker z’n auto* is de auto van de man, niet van de bakker. Het Engels doet hetzelfde met *’s*: *the king of England’s hat* is de hoed van de koning. Zo’n vorm heet een *frasale klitiek*: hij hecht zich aan het laatste woord, maar hoort bij de hele woordgroep.',
            mark: { q: 'Tik de klitiek', sentence: 'De man van de bakker z’n auto staat fout.', targets: [5], note: 'z’n staat na bakker, maar de auto is van de man van de bakker: de hele groep.' },
          },
          {
            text: 'Terug naar *opbellen*. In een bijzin kan het partikel vóór het hele werkwoordcluster staan: *dat ik je morgen op wil bellen*, naast *dat ik je morgen wil opbellen*. De zinsbouw zet hier dus iets tússen de twee stukken van één lexeem. Volgens de eilandtoets uit w7 kan een woord dat niet hebben. Marcel den Dikken (1995) analyseerde het partikel daarom als een zelfstandig zinsdeel, een soort klein gezegde. Geert Booij (2010) ziet het als een constructie: één eenheid in het lexicon, die de syntaxis toch mag splitsen.',
            swap: {
              goal: 'Maak de bijzin met het partikel vóór het cluster',
              blocks: ['bellen', 'op', 'dat ik je', 'wil'],
              accept: ['dat ik je op wil bellen'],
              note: 'Het partikel op staat vóór wil. Dat kan alleen als op geen gewoon stuk van een woord is.',
            },
          },
          {
            text: 'Dan de half verzonken woorden: *pseudo-incorporatie*. *Stofzuigen* is helemaal één werkwoord geworden: *ik stofzuig*, *ik heb gestofzuigd*. *Pianospelen* niet: *Ze is aan het pianospelen* kan, maar *Ze pianospeelt* niet. Dan zeg je *Ze speelt piano*. Zulke werkwoorden leven alleen in een paar vormen, vooral de infinitief. Ze staan precies op de grens tussen woord en woordgroep.',
            paradigm: {
              q: 'Vul de vormen in',
              cols: ['ik … (nu)', 'voltooid deelwoord'],
              rows: [
                { label: 'stofzuigen', cells: ['stofzuig', { fill: 'gestofzuigd', hint: 'Eén onscheidbaar werkwoord: ge- vooraan. Stam op g: -d.' }] },
                { label: 'pianospelen', cells: [{ fill: 'speel piano', hint: 'Ik pianospeel kan niet: het naamwoord gaat weer los.' }, { fill: 'piano gespeeld', hint: 'Ik heb piano gespeeld.' }] },
                { label: 'opbellen', cells: [{ fill: 'bel op', hint: 'Scheidbaar: het partikel blijft achter.' }, { fill: 'opgebeld', hint: 'ge- tussen partikel en stam.' }] },
                { label: 'overléggen (beraadslagen)', cells: [{ fill: 'overleg', hint: 'Klemtoon op leggen: onscheidbaar.' }, { fill: 'overlegd', hint: 'Onscheidbaar: geen ge-.' }] },
              ],
              extra: ['pianospeel', 'gepianospeeld', 'overgelegd'],
              note: 'Van volledig één woord (stofzuigen) via scheidbaar (opbellen) naar half los (pianospelen). Overgelegd hoort bij het andere, scheidbare óverleggen: papieren tonen.',
            },
          },
        ],
      },
      {
        kind: 'sort',
        id: 'klitaffix',
        prompt: 'Klitiek of affix?',
        buckets: ['klitiek', 'affix'],
        items: [
          { t: '’t in heb ’t', b: 0 },
          { t: '’k in weet ’k', b: 0 },
          { t: 'ie in heeft ie', b: 0 },
          { t: 'z’n in de buurman z’n auto', b: 0 },
          { t: '’m in zag ’m', b: 0 },
          { t: '-te in werkte', b: 1 },
          { t: '-s in tafels', b: 1 },
          { t: 'ge- in gewerkt', b: 1 },
          { t: '-je in boekje', b: 1 },
        ],
        why: 'Klitieken hangen aan bijna alles en zijn woorden zonder eigen klemtoon. Affixen hangen alleen aan een bepaalde woordsoort.',
      },
      {
        kind: 'choice',
        id: 'cluster',
        prompt: 'Welke bijzin is ook correct?',
        before: 'Ik beloof',
        after: '',
        options: ['dat ik je morgen op wil bellen.', 'dat ik je morgen bellen op wil.', 'dat ik je morgen wil bellen op.'],
        answer: 'dat ik je morgen op wil bellen.',
        why: 'Het partikel mag vóór het werkwoordcluster staan. Achter het werkwoord kan het niet.',
      },
      {
        kind: 'type',
        id: 'overleggen',
        prompt: 'Vul het voltooid deelwoord in. Hier betekent overleggen: papieren tonen.',
        before: 'Hij heeft zijn paspoort aan de douane',
        after: '.',
        hint: 'over…',
        answer: 'overgelegd',
        why: 'Óverleggen (tonen, overhandigen) is scheidbaar: hij legt het over, overgelegd. Overléggen (beraadslagen) is onscheidbaar: overlegd.',
      },
      {
        kind: 'bet',
        id: 'nt',
        prompt: 'Waarom is het Engelse n’t volgens Zwicky en Pullum eerder een affix dan een klitiek?',
        options: ['Het heeft gaten en grillige vormen: won’t, en geen amn’t', 'Het is korter dan not', 'Het staat altijd achteraan'],
        answer: 'Het heeft gaten en grillige vormen: won’t, en geen amn’t',
        why: 'Gaten en uitzonderingen horen bij morfologie. Klitieken zijn regelmatig.',
      },
      {
        kind: 'fix',
        id: 'stofzuigen',
        prompt: 'Tik het foute woord aan en verbeter het.',
        sentence: 'Ik heb gisteren de hele kamer gestofzuigt.',
        wrong: 6,
        answer: 'gestofzuigd',
        why: 'Stam stofzuig eindigt op g, niet in ’t kofschip: -d. Gestofzuigd, als één onscheidbaar werkwoord.',
      },
      {
        kind: 'highlight',
        id: 'eindbaas',
        prompt: 'Eindbaas: kleur de soorten woord in ‘Ik bel ’m morgen op’',
        intro: 'Wat is één lexeem over twee plekken, wat leunt op zijn buur, en wat is een gewoon vrij woord?',
        pens: [
          { id: 'partikel', label: 'partikelwerkwoord', tag: 'één lexeem', ask: 'Hoort dit bij opbellen?', accent: 'purple' },
          { id: 'klitiek', label: 'klitiek', tag: 'leunt', ask: 'Heeft dit woord geen eigen klemtoon?', accent: 'orange' },
          { id: 'vrij', label: 'vrij woord', tag: 'gewoon', ask: 'Is dit een woord dat in alle betekenissen een woord is?', accent: 'blue' },
        ],
        words: [
          { t: 'Ik', role: 'vrij' },
          { t: 'bel', role: 'partikel' },
          { t: '’m', role: 'klitiek' },
          { t: 'morgen', role: 'vrij' },
          { t: 'op.', role: 'partikel' },
        ],
        done: { title: 'Niveau uitgespeeld', text: 'bel … op is één lexeem op twee plekken, ’m is een woord zonder eigen klank, en Ik en morgen zijn woorden op alle vier de manieren.' },
      },
    ],
  },
];
